### ISSUE TITLE
Update NYMEX March spreadsheet

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#100]
When downloading the latest NYMEX Excel spreadsheet (March) we notice that we get a warning 'pop-up' that states "The file format...does not match.  The file could be corrupt..."  The end-user can choose to accept the risk and select "Yes" and open it, but we would prefer that the pop-up not happen. 

It looks like it is due to the SS for March having a different file extension than prior months. The March file extension is .xlsx and the prior months are .xls.

GitHub does not support the .xls file format for attachments and this is why we changed the file format, but that created the above stated issue.

Do you know of a solution to remove the warning pop-up?

@sudarr  @jboroos

**Comment by jennmalcolm** [comment]
@forgravec we have to use the .xls with the code as it is right now, and all of the old files are also .xls. We will work on that in the future. 

For the March error though, I was able to save the file in a different way that should get rid of the error. I pushed the fix live to onrr.gov already, so could you could confirm that it looks good to you?

**Comment by forgravec** [comment]
The fix worked for opening the file, but what do you suggest we do for the future months. GitHub does not accept the .xls that is required by the website?

Should we email the .xls file directly to whomever is working on the request?

Thanks,
Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
________________________________

**Comment by jennmalcolm** [comment]
@forgravec you can just continue to put the .xlsx files on GitHub, and I will just make sure our team knows how to save them in the site files. 

We will have a more permanent solution in the future, but we want to do as much as possible through GitHub because that is where the site will be in the future too. Thanks!
