### ISSUE TITLE
Update sitemap (sections 1-4) to remove documents removed with 508 compliance

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1000]
I added notes to the sitemap Axure preview.

**Comment by daniel-coleman-1** [comment]
Reviewed and I think we're good to go here

**Comment by mcharg** [comment]
@daniel-coleman-1 I went through those sections and there are still some things that aren't resolved.  I also noted where the checklists have been renamed and we added in the button to eCommerce.

**Comment by daniel-coleman-1** [comment]
@mcharg I reviewed the comments and resolved the outstanding issues

**Comment by mcharg** [comment]
@daniel-coleman-1 There are still a handful of comments that you marked as resolved that weren't resolved.  I reopened them.

**Comment by mcharg** [comment]
@daniel-coleman-1 There's still one instance where there's two WebCenter Portal links and no eCommerce on the System Access page. ![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/06e43a31-ca2c-40ac-a283-7eab686d21c5)

**Comment by daniel-coleman-1** [comment]
Thanks for the edits and updates @mcharg, went through and updated and resolved outstanding comments.
https://92ix0j.axshare.com/#id=ll6g0k&p=primary_nav
