### ISSUE TITLE
Royalty and Error Correction Contact List Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1001]
Additional revisions were needed, 
[royassign_revised_9-8-21.pdf](https://github.com/ONRR/onrr.gov-site/files/7130884/royassign_revised_9-8-21.pdf)
Please replace the Royalty Reporting and Error Correction contact list at the following location - https://www.onrr.gov/reportpay/PDFDocs/royassign.pdf, with the attached updated version.
royassign.pdf

**Comment by Maroyafaied** [comment]
@lpgoldstein @codyeckstein let me know if you have time to take this one, also please update the contact spreadsheet we're using for the CMS if needed. Thanks

**Comment by codyeckstein** [comment]
Confirmed- this list is no good as of today.  Will see if I can get the updated list.

**Comment by codyeckstein** [comment]
Upon receiving further clarification- they want us to upload this one for now. @lpgoldstein and I will do this tomorrow.

**Comment by codyeckstein** [comment]
Accessibility check failed. Requested updated document.

**Comment by codyeckstein** [comment]
http://2017onrr/ @bowlenj Does it look ok on the dev site?

**Comment by bowlenj** [comment]
Looks great, thank you!

Thank You,
Jessica Bowlen
Office of Natural Resource Revenue
Distribution and Disbursement Support Services
Team 1B
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: codyeckstein ***@***.***>
Sent: Thursday, September 9, 2021 11:37 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Royalty and Error Correction Contact List Update (#1001)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



http://2017onrr/ @bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C7e2ec44617a445b8f26908d973b89432%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637668058863120567%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kzFE8v1aZ9wxue2q%2FVn%2FHvCW04wMwu9Ley9DatlgfPo%3D&reserved=0> Does it look ok on the dev site?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1001%23issuecomment-916301872&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C7e2ec44617a445b8f26908d973b89432%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637668058863130522%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QycVAnSvEw3MCXTUhnUvX4Ogg0r3AWOlNcHUH09f6P8%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VHZDRADSLNEQYE4IJLDUBDWFVANCNFSM5DVLXMTQ&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C7e2ec44617a445b8f26908d973b89432%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637668058863130522%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IfMrt2QXT5MXOvVHpq2AUIzU004suN14VfgME6KqlZk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C7e2ec44617a445b8f26908d973b89432%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637668058863140479%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XiqOgMkGvlmN0MZ7gV8Rw2sRLioNURzqu0%2BLVZ8ExD0%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C7e2ec44617a445b8f26908d973b89432%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637668058863140479%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=u6i1KSBPFWb26NLl2udgGLW%2BcZfi%2BMIvbr1YLAFNUcY%3D&reserved=0>.

**Comment by codyeckstein** [comment]
@bowlenj This is live!
