### ISSUE TITLE
Editor JS bugs

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1002]

**Comment by Maroyafaied** [comment]
@jlouis-onrr page builder not loading, here are the dev errors and my browser version
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/d9ebf9a5-385a-4cdd-b1b3-a62cc127e153)![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/91340ac9-316a-4e7f-999e-bb98aacb1a3f)
