### ISSUE TITLE
Revisit contacts organization

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1006]
I just pulled categories from the existing docs.  There's room for improvement.

These are the categories used in the wireframes: 
https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Contacts/ContactsFiles.xlsx?d=wee2fc3b441964dce928684aaf6e25e00&csf=1&web=1&e=sfnILQ

**Comment by codyeckstein** [comment]
@mcharg let's have a quick meeting on this.

**Comment by mcharg** [comment]
@codyeckstein My calendar is up to date, if you want to schedule one.

**Comment by mcharg** [comment]
We're going to wait until after the usability study for findings related to this.

**Comment by mcharg** [comment]
Addressing with design studio changes.
