### ISSUE TITLE
Update links to all use the same case

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#101]
If they use different cases, they're getting split in the analytics.

For example, these two links to the EMARF instructions are coming up separately in analytics:
https://www.onrr.gov/reportpay/PDFDocs/EMARF_Instructions.pdf
https://www.onrr.gov/ReportPay/PDFDocs/EMARF_Instructions.pdf

The only difference I see in the url is capitalization of the "reportpay"/"ReportPay" portion of the url.

I'm sure there are other links that have the same problem.

**Comment by jennmalcolm** [comment]
Could you give us a list of the links that have variations based on what you're seeing in the analytics?Otherwise, it could be hard to find everything.

**Comment by mcharg** [comment]
Sure

**Comment by mcharg** [comment]
Pushed live
