### ISSUE TITLE
Can't copy and paste text onto a tab

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1010]
It's pasting below the tabs.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/c95c26bc-7c43-41e8-b49b-8a54c808c37c)

**Comment by mcharg** [comment]
Same thing when trying to paste into the tab content.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/8431af41-41ca-4ec7-907d-3c4e7d4b8796)

**Comment by mcharg** [comment]
Pasting as plain text using the right click menu works, but I can't use the enter button to add another paragraph.  It just puts an extra row below the tabs.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/b450048f-0a4d-40ec-b31d-cf07f16bd571)

**Comment by jlouis-onrr** [comment]
@mcharg, try out shift + enter after the paragraph

**Comment by mcharg** [comment]
@jlouis-onrr That works.

**Comment by mcharg** [comment]
@jlouis-onrr Except it just renders it all in one blob.  I think we need to add the plus sign into the tab content, so we can have headers and images within tabs.

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/3b630f82-30c0-4b0c-91c2-ec26f23238a2)

**Comment by mcharg** [comment]
@jlouis-onrr It takes out the carriage returns when saving the page.

**Comment by jlouis-onrr** [comment]
@mcharg, Might be best to not add any content except for basic text to the tabs until we can add the rich tool editor to the textarea.

**Comment by mcharg** [comment]
@jlouis-onrr Should we use this issue for adding the rich tool editor to tabs?

**Comment by jlouis-onrr** [comment]
@mcharg, probably not as this is an issue with the content editable div's innerHTML tags being stripped out once saved.  This should be a quick fix to get basic tags to work within the textarea.

**Comment by mcharg** [comment]
@jlouis-onrr I created a new issue (#1011) for adding the rich editor tool to tabs.
