### ISSUE TITLE
Form 4109 for 508 Compliance

### ISSUE THREAD

**Issue by CaGarcia1** [ONRR/onrr.gov-site#1017]
[4109.pdf](https://github.com/ONRR/onrr.gov-site/files/7164559/4109.pdf)

**Comment by cthomasONRR** [comment]
@CaGarcia1 Thanks! The document passed the 508 accessibility check. I updated the live site (https://www.onrr.gov/reportpay/royalty-reporting.htm), but it can take around 30min for the changes to go live. I will close the issue once the new accessible document is live.

Thanks!
Christine

**Comment by cthomasONRR** [comment]
The updated, 508-compliant PDF is live. Closing this issue.
