### ISSUE TITLE
Link to a tab/ an accordion item when there are sub tabs.

### ISSUE THREAD

**Issue by jkwonatx** [ONRR/onrr.gov-site#1018]
To allow the user to share a link to a specific item under an accordion or a tab on the same page.

**Comment by mcharg** [comment]
@jkwonatx FYI - This issue was in the NRRD repo, so I moved it to the onrr.gov repo.

**Comment by mcharg** [comment]
Needed to finish adding Oil & Gas Production page.

**Comment by mcharg** [comment]
@mojobnichols This works when linking from a first level tab to a first level tab, but it doesn't even show up as a link when attempting to link from a sub-tab.

**Comment by mcharg** [comment]
I'm pretty sure this will be an issue on the unbundling page, but I can't test it because the wrong sub-tabs are showing up on that page.

**Comment by mcharg** [comment]
@mojobnichols Linking to sub-tabs definitely isn't working.  From Valuation & Pricing > Unbundling > Unbundling methods, I linke to Valuation & Pricing > Unbundling > Standardized UCAs and it just opens to the main Valuation & Pricing page on the first tab.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/f7aa6560-765d-4044-bc95-36f03ac7e418)

**Comment by jlouis-onrr** [comment]
@mcharg, this is now out in dev.  Sample link:
https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=unbundling,plant-specific-ucas

**Comment by mcharg** [comment]
@jlouis-onrr This works!
