### ISSUE TITLE
Send thank you emails to user interview participants

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1021]

**Comment by cthomasONRR** [comment]
Here is a draft thank-you email:

SUBJECT: Thank you for providing feedback on the new onrr.gov!

"Hello [participant name],

Thank you so much for taking time out of your work day to talk with the Open Data, Design, and Development team. Your feedback on the new onrr.gov prototype is very much appreciated and valued! We will apply your input in this next round of modifications to the prototype.

If you have any remaining questions/comments/concerns, please feel free to respond to this email and we will be happy to continue the conversation.

Thanks again,
Christine"

**Comment by mcharg** [comment]
@cthomasONRR Looks good.

**Comment by cthomasONRR** [comment]
Thanks! @Maroyafaied and @lpgoldstein please let me know if you are good with this email, and I will send it to the 4 participants that I contacted and were interviewed (Alicia, Kelsey, Latisha, Janice).

**Comment by Maroyafaied** [comment]
@cthomasONRR looks great. Thanks

**Comment by mcharg** [comment]
@cthomasONRR Can you add a column to the participant sheet indicating which participants you send it to, so we don't forget anyone?

**Comment by cthomasONRR** [comment]
@mcharg Yep- Got that added in column 'R' of the participant sheet :)

**Comment by lpgoldstein** [comment]
@cthomasONRR

**Comment by cthomasONRR** [comment]
Awesome! I just sent this email out the the 4 participants I recruited.
@cvojslavek and @codyeckstein - Please feel free to use this template as well!

**Comment by cvojslavek** [comment]
@cthomasONRR Thank you, I used your template!

**Comment by codyeckstein** [comment]
Just sent out a couple with your template. Thank you.
