### ISSUE TITLE
Check OCS contacts

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1022]
A couple of participants have said one is on maternity leave and the other is no longer on the team.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/8bd74813-9db6-4775-b954-3b205779e11e)

**Comment by codyeckstein** [comment]
Apparently, these are the contacts for now. Stacey is back from maternity leave on the 22nd and we won't update these contacts until a new technician is hired.
