### ISSUE TITLE
Added content to what you might have missed edition

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1032]

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 @mcharg this is what I plan to submit to Nichelle. Can you review? Thanks https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/WYMHM.docx?web=1

**Comment by mcharg** [comment]
@Maroyafaied I added a couple of comments.
