### ISSUE TITLE
Url field not updating when slug gets updated/changed

### ISSUE THREAD

**Issue by jlouis-onrr** [ONRR/onrr.gov-site#1034]

**Comment by Maroyafaied** [comment]
@jlouis-onrr please review.

**Comment by jlouis-onrr** [comment]
Double urls are being created.

![image.png](https://images.zenhubusercontent.com/5d893e494c2d9e0001fa99ad/01c691aa-3dd1-4db7-83b3-ef42aed7235f)

**Comment by mcharg** [comment]
This is also happening on sub pages. ![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/c1d5159d-c927-48da-8904-c76989deb9f8)

**Comment by mcharg** [comment]
I'm wondering if #1234 is also related.  Maybe it's the pages with the double slash that aren't showing up in the menu?

**Comment by mcharg** [comment]
Fixed!
