### ISSUE TITLE
Create external bulk 301 redirects

### ISSUE THREAD

**Issue by jlouis-onrr** [ONRR/onrr.gov-site#1035]

**Comment by cthomasONRR** [comment]
Did a quick inventory, 1,129 internal onrr.gov links need appropriate 301 redirects. Not sure how long this will take me.
I also need to create a new column for external redirects (this will just be copy+pasting to a new column).

**Comment by cthomasONRR** [comment]
@mcharg I completed all the 301 internal redirects (breadcrumbs) in Column C, Marked those as complete in Column D, and created a new "External Redirect" Column F for all external links.

I found several instances where links were to incorrect docs, and fixed those.

Ready for your review.

**Comment by mcharg** [comment]
@cthomasONRR There's a bunch marked as external in column D, but don't have anything in column F. Do we just need to copy column B to column F? ![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/777bc81c-3b1c-4058-b433-2d78d6fdd5f3)

**Comment by mcharg** [comment]
@cthomasONRR It let me do it.

**Comment by mcharg** [comment]
@cthomasONRR Looks good.

**Comment by cthomasONRR** [comment]
Great! Jerome, the 301 redirects spreadsheet is ready for you. Spreadsheet located [here](https://teams.microsoft.com/l/file/8F317B52-F37E-47BB-8D41-DC17EA254E0C?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FContent%2FContent%20Audit%2FRedirects.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

**Comment by jlouis-onrr** [comment]
thanks @cthomasONRR, I'll check it out.

**Comment by cthomasONRR** [comment]
@mcharg @jlouis-onrr In the Redirects CMS collection- I fixed all the 'new urls' that had hashtags in them with the correct breadcrumb url. All should be good now :)

**Comment by cthomasONRR** [comment]
@mcharg @jlouis-onrr Great! I will close this issue now.
