### ISSUE TITLE
Add disclaimer to onrr.gov glossary

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1043]
Language to add at the top of the glossary page:

_The definitions in this glossary are simplified. Some are ONRR-specific in their usage. None of the definitions takes precedence over laws, legislation, regulations, contracts, or specific interpretations or rulings._

This glossary defines many commonly used terms and initialisms but isn’t a full list. To request changes to terms on this list, or to suggest new terms be added, email nrrd@onrr.gov.

Idea came from the glossary issue [#906](https://app.zenhub.com/workspaces/data-display-5464fa79c3cc8d7f4c384eaf/issues/onrr/onrr.gov-site/906)

**Comment by cthomasONRR** [comment]
I updated the Glossary on the dev site (http://2017onrr/glossary.htm)

Waiting for review before going live.

![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/4f611ad5-f2c9-4252-b56d-823716618353)

**Comment by mcharg** [comment]
@cthomasONRR We should use the onnrweb@onrr.gov email address on onrr.gov.  And we can make it into a link by using "mailto:onrrweb@onrr.gov" as the url.

**Comment by cthomasONRR** [comment]
Changed the wording slightly:

<p>The definitions in this glossary are simplified. Some are ONRR-specific in their usage. None of the definitions takes precedence over laws, legislation, regulations, contracts, or specific interpretations or rulings.</p>
<p>This glossary defines many commonly used terms and acronyms but isn’t a full list. To request changes to terms on this list, or to suggest new terms be added, email <a href=mailto:onrrweb@onrr.gov>onrrweb@onrr.gov</a>.</p>

Moving this change to the live site and will close this issue once it goes live.
