### ISSUE TITLE
Figure out shutdown banner

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1044]

**Comment by mcharg** [comment]
Looks like Jennifer had one ready to go last year, so we just need to find it and be ready to uncomment it out.
https://github.com/ONRR/onrr.gov-site/issues/364

**Comment by daniel-coleman-1** [comment]
It's quite close to the top of the page, very easy to find.

Code:

**Comment by daniel-coleman-1** [comment]
![Screenshot 2021-09-27 132519](https://user-images.githubusercontent.com/83892362/134972167-cc2d6901-1aea-4029-b00c-4862234118c2.png)
