### ISSUE TITLE
Heidi Badaracco Accessible documents 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1045]
Here are 2 out of the 3 docs for Heidi's program, they are working on the last one. @cvojslavek do you have to do these? @cthomasONRR can you review once Cat uploads in dev and updates the tracking sheet? Thank
[Roles-and-Responsibilities-Booklet.pdf](https://github.com/ONRR/onrr.gov-site/files/7236998/Roles-and-Responsibilities-Booklet.pdf)
[ONRR-Tribal-Consultation-Policy.pdf](https://github.com/ONRR/onrr.gov-site/files/7237000/ONRR-Tribal-Consultation-Policy.pdf)

s

**Comment by cthomasONRR** [comment]
@Maroyafaied and @cvojslavek 
I'm happy to help with this. Cat, let me know if you want to walk through the process again, or if you just need me to review. Thanks!

**Comment by cvojslavek** [comment]
@cthomasONRR these are ready for your review, thank you. I followed the steps below for the 2 documents.
- [x] Recheck docs for accessibility
- [x] Upload docs in dev site
- [x] Review docs in dev site
- [x] Publish to the live site
- [x] Update Accessibility tracking sheet
- [x] Checked the live site

Do I need to move/save the updated files anywhere else, or was that just a step for Carrie's documents in her OneDrive?

**Comment by cthomasONRR** [comment]
@cvojslavek - I just checked the accessibility tracking spreadsheet and was able to download the remediated PDFs from the website. Everything looks good to me!

Yes- that extra step of moving files was specifically for Carrie's OneDrive.

I think you're good to close this issue. Thanks!

**Comment by cvojslavek** [comment]
@cthomasONRR thank you!
