### ISSUE TITLE
Update production reporting references 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1046]
This came in from the onrreweb mailbox 

All,
On the ONRR.gov home page, please update the Production Reporting References with the attached files. The new as of date is 09/27/2021.

There are five Gulf files, three Pacific files, and one Alaska file.

**Comment by daniel-coleman-1** [comment]
I can take this one

**Comment by daniel-coleman-1** [comment]
http://2017onrr/reportpay/references.htm

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 this was approved by email, please push to the live site. Thanks

**Comment by daniel-coleman-1** [comment]
Pushed live about 30 min ago, just confirmed.
