### ISSUE TITLE
September analytics

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1047]

**Comment by mcharg** [comment]
Comment for this was put in the NRRD issue.
https://github.com/ONRR/nrrd/issues/1754#issuecomment-933838104

**Comment by mcharg** [comment]
@daniel-coleman-1 Page views graph is missing.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/a1860674-3803-47eb-b9b2-048346cfddf5)

**Comment by mcharg** [comment]
@daniel-coleman-1 It's fine to skip the not set landing page.

**Comment by mcharg** [comment]
@daniel-coleman-1 Safari desktop is above 1% and needs to be added. ![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/7ff01611-e50c-49d4-a720-5493f2391a88)

**Comment by mcharg** [comment]
@daniel-coleman-1 The download numbers are copied from August.  These are the September numbers.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/75d07d5b-f20f-4b2a-8cc6-5645dd61995e)

**Comment by daniel-coleman-1** [comment]
@mcharg I think we're good on this one
