### ISSUE TITLE
FY21 analytics

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1048]

**Comment by mcharg** [comment]
Requested unsampled reports, so we have them ready to go for Monday.

**Comment by daniel-coleman-1** [comment]
Mostly good, I found two issues.

It looks like the Active Leases file has 1740 downloads from ReportPay (upper case) and 1692 downloads from reportpay (lower case).  Should I combine them?
![ONRR_Downloads_FY21](https://user-images.githubusercontent.com/83892362/135934360-31353b18-a2b7-4ea2-b613-f3712c320d92.png)

I pulled the below search from search.gov.  Where could "bddbhagf efdfvibcyf" be coming from? My first impression is to ignore it, thoughts?
![searchdotgovONRR](https://user-images.githubusercontent.com/83892362/135934541-a4876166-01ff-497d-84dd-f6f6279895ea.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 Yes, we should combine all the instances of capitalization differences.

I would keep the search term as is, since it's what's in the report.

**Comment by mcharg** [comment]
@daniel-coleman-1 Chrome desktop should be 48.87%
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/9858c0c3-77db-4680-84ed-c929af857a5e)

**Comment by mcharg** [comment]
@daniel-coleman-1 The third outbound link is DataWarehouse Portal (what WebCenter Portal used to be), not NRRD portal.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/e9fef234-d581-4829-b66c-375bb0483ddf)

**Comment by daniel-coleman-1** [comment]
@mcharg thanks for the notes, updated.
Is there a way to identify total unique searches for FY 2021?  We have them for FY 2019 but not 2020 or 2021

2021
![fy2021](https://user-images.githubusercontent.com/83892362/136058380-e4e87e9b-3044-4c66-b460-4aadb4867160.png)

.
2020
![FY2020](https://user-images.githubusercontent.com/83892362/136058472-32aab444-8708-42bf-882c-f66b36affce4.png)


2019
![FY2019](https://user-images.githubusercontent.com/83892362/136058439-861ab1f3-f5ac-4df5-8a74-df54c67c4dfc.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 I think you may have to generate the report for the date range and then copy and paste into Excel and get a sum to get the yearly numbers.

**Comment by mcharg** [comment]
@daniel-coleman-1 Makes sense to add up the monthly numbers.  That may have been what I did for 2019.

**Comment by daniel-coleman-1** [comment]
@mcharg I think this one is good to close

**Comment by mcharg** [comment]
Looks like all is good.  I updated the FY19 total searches to add monthly because it wasn't doing that.
