### ISSUE TITLE
Publish press release - request from chief of staff

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1056]
https://www.onrr.gov/pdfdocs/GOMESA.National.Release.pdf

send dev site to chief of staff for review.

**Comment by Maroyafaied** [comment]
@mcharg do you know how I can get rid of the pdf icon on this page, it doesn't show on the homepage but it shows here http://2017onrr/About/NewsReleases.htm

**Comment by mcharg** [comment]
@Maroyafaied I took a look at it and I can't figure out how the NewsReleases page is pulling the XML file.

**Comment by mcharg** [comment]
@Maroyafaied Actually, it doesn't look like the page is being updated on the dev site.  I think there was something weird with press releases and you have to put live for them to show up on that page.

**Comment by mcharg** [comment]
@Maroyafaied Wait, it is updating.

**Comment by Maroyafaied** [comment]
@mcharg it shows on dev for me , and I actually just pushed it live because they want it out ASAP so we can figure out the icon thing later.
