### ISSUE TITLE
Request to Update ONRR's FRN Page

### ISSUE THREAD

**Issue by aklong09** [ONRR/onrr.gov-site#1058]
Good morning,

Please update the ONRR Federal Register Notices page located at: https://www.onrr.gov/Laws_R_D/FRNotices/index.htm

Please create a new entry at the top of the page for September 10, 2021 to read as follows:

“86 FR 50742
Friday, September 10, 2021
**Denver, CO** In accordance with the Paperwork Reduction Act of 1995, ONRR is proposing to renew an information collection request. OMB Control Number 1012-0004.

View 86 FR 50742 document”

For the “View 86 FR 50742 document” language please connect the following hyperlink:  https://www.federalregister.gov/documents/2021/09/10/2021-19552/agency-information-collection-activities-royalty-and-production-reporting

Please let us know if you have any questions.

Thank you in advance,
Alexis

**Comment by cthomasONRR** [comment]
@aklong09

I have this update on the dev site: http://2017onrr/Laws_R_D/FRNotices/index.htm

Please review and let me know if it's good to go live.

Thanks!

**Comment by aklong09** [comment]
@cthomasONRR this looks absolutely perfect! It's good to push live. Thank you!!

**Comment by cthomasONRR** [comment]
@aklong09 Great! I just pushed it to the live site. It can take up to 30min for the changes to go live, and you might need to press 'ctrl+F5' to refresh the page. I'll close this issue once I see it live. Thanks!
