### ISSUE TITLE
Updates to ONRR Information Collection Pages

### ISSUE THREAD

**Issue by aklong09** [ONRR/onrr.gov-site#1060]
Good morning,

Please update the expiration dates on the following ONRR ICR pages:

For the page located at https://www.onrr.gov/Laws_R_D/FRNotices/ICR0122.htm -- please change the expiration date (currently reads February 28, 2021) to "October 31, 2023."

For the page located at https://www.onrr.gov/Laws_R_D/FRNotices/ICR0073.htm -- please change the expiration date (currently December 31, 2020) to "January 31, 2024."

For the page located at https://www.onrr.gov/Laws_R_D/FRNotices/ICR0120.htm -- please change the expiration date (currently January 31, 2020) to "January 31, 2023."

Thank you,
Alexis

**Comment by aklong09** [comment]
@daniel-coleman-1 All three pages look great! Approved to push them live. Thank you!!

**Comment by daniel-coleman-1** [comment]
Fantastic, all changes are now live:
https://www.onrr.gov/Laws_R_D/FRNotices/ICR0073.htm
https://www.onrr.gov/Laws_R_D/FRNotices/ICR0120.htm
https://www.onrr.gov/Laws_R_D/FRNotices/ICR0122.htm
