### ISSUE TITLE
Request to Update ONRR's FRN Page

### ISSUE THREAD

**Issue by aklong09** [ONRR/onrr.gov-site#1061]
Good morning, 

Please update ONRR's FRN page located at https://www.onrr.gov/Laws_R_D/FRNotices/index.htm

Please create an entry for today, September 30, 2021 to read as follows:
"86 FR 54045
Thursday, September 30, 2021
**Denver, CO** ONRR is withdrawing the ONRR 2020 Valuation Reform and Civil Penalty Rule ("2020 Rule"). As of November 1, 2021, ONRR's 2020 Rule, published in the Federal Register on January 15, 2021 at 86 FR 4612, currently effective November 1, 2021 (as extended at 86 FR 9286 and 86 FR 20032), is withdrawn.

View 86 FR 54045 document"

For the "View 86 FR 54045 document" language, please add a hyperlink to the following location: https://www.federalregister.gov/documents/2021/09/30/2021-20979/onrr-2020-valuation-reform-and-civil-penalty-rule-final-withdrawal-rule

Please let us know if you have any questions and thank you in advance!

**Comment by cthomasONRR** [comment]
Good morning!

Here is the preview on the dev site: http://2017onrr/Laws_R_D/FRNotices/index.htm

Please let us know if it's good to go live.

Thanks, and CONGRATULATIONS!!!!

**Comment by aklong09** [comment]
@cthomasONRR this looks perfect!! Should be good to go live. Thanks so much!
