### ISSUE TITLE
Request to Update ONRR's RIN 1012-AA27 Page

### ISSUE THREAD

**Issue by aklong09** [ONRR/onrr.gov-site#1062]
Good morning,

Please update ONRR's RIN 1012-AA27 page, located at https://www.onrr.gov/Laws_R_D/FRNotices/AA27.htm

In the last full paragraph of the abstract (directly above the "For more information . . ." area), please revise so it reads as follows:
"ONRR published a Notice of Proposed Withdrawal of this rulemaking in the Federal Register on June 11, 2021. The proposed withdrawal provides a 60-day public comment period. On September 30, 2021, ONRR published a final rule withdrawing the 2020 Rule."

Please also add a bullet at the bottom of the bulleted list with the following text: "To view the final withdrawal rule:" and add the following hyperlink to the publication: https://www.federalregister.gov/documents/2021/09/30/2021-20979/onrr-2020-valuation-reform-and-civil-penalty-rule-final-withdrawal-rule

Please let me or Luis Aguilar know if you have any questions. 

Thank you,
Alexis

**Comment by cthomasONRR** [comment]
@aklong09 

Here is the preview link on the dev site: http://2017onrr/Laws_R_D/FRNotices/AA27.htm

Please review and let us know if it's good to go live.

Thanks!

**Comment by aklong09** [comment]
@cthomasONRR -- looks perfect! Approved to push live. Thank you again!!

**Comment by cthomasONRR** [comment]
@aklong09 

Great! I just pushed these updates to the live site. I will close this issue once they go live.
https://www.onrr.gov/Laws_R_D/FRNotices/AA27.htm
