### ISSUE TITLE
Upload last doc for Heidi - Phase 2

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1063]
Please check for accessibility & upload and update the tracking sheet. @cvojslavek can you take this one @cthomasONRR can you review
[Understanding_Your_OST_Quarterly_Statement.pdf](https://github.com/ONRR/onrr.gov-site/files/7260729/Understanding_Your_OST_Quarterly_Statement.pdf)
.

**Comment by cthomasONRR** [comment]
@Maroyafaied @cvojslavek Sounds good. Let me know if you need help!

**Comment by cvojslavek** [comment]
@cthomasONRR ready for your review, thank you. I followed the steps below:

- [x] Recheck docs for accessibility
- [x] Upload docs in dev site
- [x] Review docs in dev site
- [x] Publish to the live site
- [x] Update Accessibility tracking sheet
- [x] Checked the live site

**Comment by cthomasONRR** [comment]
@cvojslavek I just checked the live site and the accessibility tracking spreadsheet. Everything looks good! I think you are good to close this issue.

Just FYI- I think ZenHub is being weird again because it's saying your comment was deleted, but I still see it in GitHub.
