### ISSUE TITLE
EVENT CALENDAR   (To be added to the calendar on the Allottee Assistance page.

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#1066]
**U & O, Fort Duchesne, Salt Lake City, UT Virtual Outreach**
Tuesday, October 19, 2021 
Time: 10:00 am - 11:00 am MST 

Location:  By Telephone 
Description: Representatives from the Office of Natural Resources Revenue will host a Question and Answer session by phone for Indian Mineral Owners and Indian trust property owners regarding their Indian Oil & Gas leases, IIM Accounts, and Indian trust properties. Representatives from the Bureau of Land Management, Bureau of Indian Affairs, and Bureau of Trust Funds Administration are invited to be in attendance to answer questions.  

Who Should Attend:  IIM account holders, Indian mineral owners, and Indian trust property owners in the U & O, Fort Duchesne, Salt Lake City areas in Utah.  

Other Information: To attend the outreach session, please contact the ONRR Denver Outreach Office at (800) 982-3226, for the call-in number and passcode.  The ONRR Denver Outreach Office hours are Monday-Friday 7:30am-4:00pm. 

Event Contact:  
Name: ONRR Denver Outreach Office, 
Phone:  Toll Free (800) 982-3226         
Email:  onrroutreachdenver@onrr.gov

**PAWNEE AREA VIRTUAL OUTREACH MEETING**
Tuesday, October 20, 2021
Time: 1:00 pm - 2:00 pm CST

Location: By Telephone 
Description: Meeting will be a Call-in Meeting to hear a presentation and updates from ONRR OKC Office.  Representatives from BLM, BTFM, and BIA will also be available to discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian trust properties.  
Who Should Attend:  IIM account holders, Indian mineral owners, and other Indian trust property owners in the Pawnee Agency Area, or any mineral owners located in the Southern Plains Region in Oklahoma. 
Other Information: To attend meeting you must contact the ONRR OKC Outreach office at (800) 354-7015 to reserve your space and get the call-in number and passcode for the meeting.   ONNR OKC Outreach office hours are Monday- Friday from 7:30 am-5:00 pm.
Event Contact:
Name: ONRR OKC Outreach Office 
Phone: Toll Free (800) 354-7015          
Email:  onrroutreachokc@onrr.gov

**Fort Hall, ID Virtual Outreach**
Thursday, October 21, 2021 
Time: 10:00 am - 11:00 am MST 

Location:  Telephone 
Description: Representatives from the Office of Natural Resources Revenue will host a Question and Answer session by phone for Indian Mineral Owners and Indian trust property owners regarding their Indian Oil & Gas leases, IIM Accounts, and Indian trust properties. Representatives from the Bureau of Land Management, Bureau of Indian Affairs, and Bureau of Trust Funds Administration are invited to be in attendance to answer questions.  

Who Should Attend:  IIM account holders, Indian mineral owners, and Indian trust property owners in the Fort Hall area in Idaho.  

Other Information: To attend the outreach session, please contact the ONRR Denver Outreach Office at (800) 982-3226, for the call-in number and passcode.  The ONRR Denver Outreach Office hours are Monday-Friday 7:30am-4:00pm. 

Event Contact:  
Name: ONRR Denver Outreach Office, 
Phone:  Toll Free (800) 982-3226 
Email:   onrroutreachdenver@onrr.gov

**Comment by daniel-coleman-1** [comment]
@Toddsand21  updated for your review:
http://2017onrr/events.htm

With your approval, I will push these changes live.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 can you take "Name" out. Thanks
![image](https://user-images.githubusercontent.com/40175688/135539150-585dca19-a72f-49af-ba15-17e06cdfb8e4.png)

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 Also the description of the 2nd event doesn't match what was requested. 
![image](https://user-images.githubusercontent.com/40175688/135539349-983b2edf-4738-408a-bce3-efdf4ac668fd.png)

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 description of the 1st event doesn't match either. 
![image](https://user-images.githubusercontent.com/40175688/135539488-864c85be-646e-4ef9-b4c4-4d03e28eff84.png)

**Comment by daniel-coleman-1** [comment]
thanks for catching, @Maroyafaied.  Corrected.

**Comment by daniel-coleman-1** [comment]
@Toddsand21 pushing live now for timeliness.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 Next time please allow the person making the request a chance to review before pushing live. @Toddsand21 please let us know if it's ok to close this issue or if you'd like any additional changes. Thanks

**Comment by Toddsand21** [comment]
In the 2nd meeting announcement, Pawnee Area Meeting could I get you to add the word "Indian"  in the paragraph Who Should Attend: the last sentence after the comma, should read.... or any Indian mineral owners located....

Other than that it looks fine.  Thanks.

**Comment by Maroyafaied** [comment]
@Toddsand21 please review the change you requested. Thanks

http://2017onrr/events.htm

**Comment by Toddsand21** [comment]
It looks fine and ready to go live.  Thanks!

**Comment by Toddsand21** [comment]
One other change:  Please change the day from Tuesday, October 20, 2021 to read... Wednesday, October 20, 2021 on the Pawnee Meeting?  And there should be no other changes and ready to go.  Thanks!

**Comment by Maroyafaied** [comment]
Ok I'll make that change. Thanks

**Comment by Maroyafaied** [comment]
Changes should be live within 30 min, I'll close this once its live. http://2017onrr/events.htm

**Comment by Maroyafaied** [comment]
All changes are live. Closing.

**Comment by Toddsand21** [comment]
Changes look fine. Thanks!
