### ISSUE TITLE
Sitemap changes related to miscellaneous pages added to wireframes

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1070]
IONR page has subpages that need to be added. https://qmcq5k.axshare.com/#id=yus88b&p=ionr&g=1

And I added the glossary page to the header. https://qmcq5k.axshare.com/#id=r7lprg&p=glossary&g=1

**Comment by daniel-coleman-1** [comment]
@mcharg should I nest the page under 6.4.3.2.1 in Indian References -> Regulations -> Oil -> IONR?

![Screenshot 2021-10-13 101557](https://user-images.githubusercontent.com/83892362/137173254-1f64e982-11c6-4e79-a98b-857e3b499937.png)

**Comment by daniel-coleman-1** [comment]
@mcharg Updated, not sure what you mean about sub pages though.  I can jump on a call if that's easier.

**Comment by mcharg** [comment]
@daniel-coleman-1 You got it right this time.
