### ISSUE TITLE
September Indian Index Zone prices ready

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#1071]
The September Indian Gas Index Zone prices have been calculated and are ready to be posted onto ONRR.gov.
The prices have been placed into the "Data for ONRR.gov" spreadsheet in the shared Onedrive location.

Thanks,
Cory Forgrave
@Sudarr

**Comment by lpgoldstein** [comment]
@forgravec This is ready for your review: http://2017onrr/valuation/allzones.htm

**Comment by forgravec** [comment]
Prices look good.

Thanks for doing this so quickly.
Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
***@***.***

________________________________
From: lpgoldstein ***@***.***>
Sent: Monday, October 4, 2021 3:42 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Forgrave, Cory J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] September Indian Index Zone prices ready (#1071)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@forgravec<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fforgravec&data=04%7C01%7Ccory.forgrave%40onrr.gov%7C4d9da875f4844f17a03b08d9877fee9a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637689805804004479%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BBtBS8uXVdU8nWCT32l4IfrrOE8lDeIP2OEJNZefLPw%3D&reserved=0> This is ready for your review: http://2017onrr/valuation/allzones.htm

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1071%23issuecomment-933878692&data=04%7C01%7Ccory.forgrave%40onrr.gov%7C4d9da875f4844f17a03b08d9877fee9a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637689805804004479%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zFGqbY0xQayRw7YAZK0Pxy7d0vI8PIOdE9jikXFq7uc%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOXGYMB5AS6COHIVSXIZEPDUFINVHANCNFSM5FKIX3AA&data=04%7C01%7Ccory.forgrave%40onrr.gov%7C4d9da875f4844f17a03b08d9877fee9a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637689805804014437%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WM%2FTT3OyX0%2BQuW%2BtD%2BXoS83shghUsl4hs%2BL2odoAO1U%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ccory.forgrave%40onrr.gov%7C4d9da875f4844f17a03b08d9877fee9a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637689805804024394%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WEJEhZT6T0gLbcMWZcbMzzqNUbOH289AzOpQ7div3hY%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ccory.forgrave%40onrr.gov%7C4d9da875f4844f17a03b08d9877fee9a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637689805804024394%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hXPN2MMIYioXmZmn8lH7wtdY2PxAOe4slCz1woPzS8Q%3D&reserved=0>.

**Comment by lpgoldstein** [comment]
@forgravec Of course! I know how important they are to users. It should be live in the next hour and I'll close out the issue once you let me know if it looks okay.

**Comment by forgravec** [comment]
You can close it out...all looks well.

Thanks,
Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
***@***.***

________________________________
From: lpgoldstein ***@***.***>
Sent: Monday, October 4, 2021 4:01 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Forgrave, Cory J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] September Indian Index Zone prices ready (#1071)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@forgravec<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fforgravec&data=04%7C01%7Ccory.forgrave%40onrr.gov%7Ce864997979e842e0eccf08d9878299f9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637689817269205660%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=etLb7Js0Upu26lsPqWN5oeIHmpY8%2FDXxBC8r1f2Dvy4%3D&reserved=0> Of course! I know how important they are to users. It should be live in the next hour and I'll close out the issue once you let me know if it looks okay.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1071%23issuecomment-933888825&data=04%7C01%7Ccory.forgrave%40onrr.gov%7Ce864997979e842e0eccf08d9878299f9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637689817269205660%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HEHUMRl3fRI8SCrRHL1XF2W3Azcvd89t%2FouS%2BzhbHDY%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOXGYMGLF3E65WB7NJRJGEDUFIP4VANCNFSM5FKIX3AA&data=04%7C01%7Ccory.forgrave%40onrr.gov%7Ce864997979e842e0eccf08d9878299f9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637689817269215618%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0BXJLa4skEUoA9PrcJ4gDxtRIi3CasJEkx8nO0NGmNY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ccory.forgrave%40onrr.gov%7Ce864997979e842e0eccf08d9878299f9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637689817269215618%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8xvCMZ4oXvFEBpcdVRRi0QgxqbmcAuKrAvFtQa65AVg%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ccory.forgrave%40onrr.gov%7Ce864997979e842e0eccf08d9878299f9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637689817269225574%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4cFpybkRHfVw8kcxG0NywmT0MBaG0qWlHr%2FmsjIdKhE%3D&reserved=0>.
