### ISSUE TITLE
Add September NYMEX prices to ONRR.gov

### ISSUE THREAD

**Issue by penvosej** [ONRR/onrr.gov-site#1072]
The September NYMEX prices are ready to be posted to ONRR.gov. The file with the data is attached. Thank you!
@sudarr
[NYMEX092021.xlsx](https://github.com/ONRR/onrr.gov-site/files/7287958/NYMEX092021.xlsx)

**Comment by cthomasONRR** [comment]
@penvosej I made the update on the dev site. Please review and let us know if it's good to go live. Thanks! http://2017onrr/valuation/NYMEX.htm

**Comment by penvosej** [comment]
Hi Christine! Thanks for taking care of this so quickly!

The data for September looks good, but can you do me a favor? Can you make it so that all months show two digits past the decimal point? So the January NYMEX would be $52.10, the April NYMEX would be $61.70, and the May Roll would be $0.00. I try to catch this when I am assigned to one of the price calculations, but I've been doing Indian Index Zone prices lately and haven't see the NYMEX data in a while!

From: Christine Thomas ***@***.***>
Sent: Tuesday, October 5, 2021 11:44 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Add September NYMEX prices to ONRR.gov (#1072)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpenvosej&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C7ab6881a3bb74106c1b308d98827b00c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637690526313514388%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2Fvn7oN%2F8U%2F3KCbMz%2FEUf7YHc%2BZKjN5yJmkZETn5RVN4%3D&reserved=0> I made the update on the dev site. Please review and let us know if it's good to go live. Thanks! http://2017onrr/valuation/NYMEX.htm

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1072%23issuecomment-934625658&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C7ab6881a3bb74106c1b308d98827b00c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637690526313514388%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=clJActhdknsE4KIiYKKamB4ZVso9u83%2Fpd%2BGCjTW9ME%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQQSAVHLSZWADD5G5M3FG73UFM2MFANCNFSM5FMG2UMQ&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C7ab6881a3bb74106c1b308d98827b00c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637690526313524342%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zuKIb5WAorfE%2BVLYyAGt%2BYLsIImDKH3Vjw1dG5US5qo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C7ab6881a3bb74106c1b308d98827b00c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637690526313524342%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BI835bR9XYd8R%2FK5j64eaBgQWnVEwNyp2aDYvU9oDIE%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C7ab6881a3bb74106c1b308d98827b00c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637690526313534302%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wSZER7RKYaE2D3zghc2buo7xsmZ7%2Blg0QjLNkxdYp2w%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@penvosej It should be fixed now (http://2017onrr/valuation/NYMEX.htm)... There's some odd communication between the spreadsheet and the website, s0 I have to manually get it to 2 decimal places every time.

**Comment by penvosej** [comment]
That looks great, thank you! I thought it probably was an idiosyncrasy of one of the systems, so I really appreciate you manually fixing it!!!

This page looks ready to go live!

From: Christine Thomas ***@***.***>
Sent: Tuesday, October 5, 2021 12:00 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Add September NYMEX prices to ONRR.gov (#1072)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpenvosej&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C0c699ec4a45f4a86d2f408d9882a0337%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637690536291025622%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kOuoieBo44VuV%2BfFNaoXkaHh6rEYyIRuLgRKznt7RS0%3D&reserved=0> It should be fixed now (http://2017onrr/valuation/NYMEX.htm)... There's some odd communication between the spreadsheet and the website, so I have to manually get it to 2 decimal places every time.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1072%23issuecomment-934638457&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C0c699ec4a45f4a86d2f408d9882a0337%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637690536291025622%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=83%2FdT5zA53%2Fz0ohI%2Bj6D8g6i%2BzxXmZOVGvqhKf4UtxM%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQQSAVEO4MCK2W75CMSGR7TUFM4J7ANCNFSM5FMG2UMQ&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C0c699ec4a45f4a86d2f408d9882a0337%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637690536291035577%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kFhJxHYzjqb5P%2F81RgPU1Hma4VE7ZQzBTpmJNxR6BG4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C0c699ec4a45f4a86d2f408d9882a0337%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637690536291035577%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=h2umwGROB%2Fp%2FZBmjyxY%2Bo4ou01e3MUe1W3R9iFt%2F5AM%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C0c699ec4a45f4a86d2f408d9882a0337%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637690536291035577%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0Rgjem%2BmGK2QOD2cIBDoEuU01kOEHpUV8GkQoa3A97g%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@penvosej The changes are live! https://www.onrr.gov/valuation/NYMEX.htm Closing this issue now.
