### ISSUE TITLE
Contacts Design Studio - offline hole poking analysis

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/onrr.gov-site#1078]

**Comment by cthomasONRR** [comment]
I added in some comments/questions/concerns in Shannon's [Word Doc](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Contacts/Contacts%20Hole%20Poking.docx?d=wb83d7d72509f4c439ec7a65f7774534e&csf=1&web=1&e=ZbfISh)
