### ISSUE TITLE
Request to Update ONRR ICR Page

### ISSUE THREAD

**Issue by aklong09** [ONRR/onrr.gov-site#1080]
Good morning,

Please update ONRR's ICR page (1012-0001) located at: https://www.onrr.gov/Laws_R_D/FRNotices/ICR0162.htm

At the top, please add a new bullet to the bulleted list to read as follows: "30-Day Agency Information Collection - (86 FR 55858--October 7, 2021)".

For the "(86 FR 55858--October 7, 2021)" language, please attach the following hyperlink: https://www.federalregister.gov/documents/2021/10/07/2021-21893/agency-information-collection-activities-accounts-receivable-confirmations-reporting

Please let me know if you have any questions.

Thanks in advance,
Alexis

**Comment by cthomasONRR** [comment]
@aklong06 The changes are live! Closing this issue.
