### ISSUE TITLE
Webpage Update - Active Leases

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#1083]
Please update the following webpage with the attached file -
http://www.onrr.gov/ReportPay/CrossRef.htm 

Active leases sorted by State and Agency lease number - Please change to read updated 10/01/2021.

Thank you
[ALwState.xlsx](https://github.com/ONRR/onrr.gov-site/files/7306316/ALwState.xlsx)

**Comment by cthomasONRR** [comment]
The live site is updated! Closing this issue.
