### ISSUE TITLE
Side menu to drop down for mobile views

### ISSUE THREAD

**Issue by jlouis-onrr** [ONRR/onrr.gov-site#1087]

**Comment by shannonmcharg** [comment]
Yeah, it was an old iteration. No need for a background.

**Comment by jlouis-onrr** [comment]
ok, thanks!

**Comment by jlouis-onrr** [comment]
@mcharg, mobile side menu and main menu updates are in dev.

**Comment by mcharg** [comment]
Or rather the main menu.

**Comment by jlouis-onrr** [comment]
yep. Ill get that added.
