### ISSUE TITLE
Request to Update ONRR ICR Page

### ISSUE THREAD

**Issue by aklong09** [ONRR/onrr.gov-site#1088]
Good morning,

Please update ONRR's ICR page (1012-0003) located at: https://www.onrr.gov/Laws_R_D/FRNotices/ICR0087.htm

At the top, please add a new bullet to the bulleted list to read as follows: "30-Day Agency Information Collection - (86 FR 56288--October 8, 2021)".

For the "(86 FR 56288--October 8, 2021)" language, please attach the following hyperlink: https://www.federalregister.gov/documents/2021/10/08/2021-21894/agency-information-collection-activities-delegated-and-cooperative-activities-with-states-and-indian

Please let me know if you have any questions.

Thanks in advance,
Alexis

**Comment by cthomasONRR** [comment]
@aklong09 

I made the changes in the dev site: http://2017onrr/Laws_R_D/FRNotices/ICR0087.htm
Please review and let me know if you approve the changes to go live.

Thanks!
Christine
