### ISSUE TITLE
Active Leases - Webpage

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#1094]
Hello, would you please re-upload the attached file. The fields were not expanding correctly on the original document.
![image](https://user-images.githubusercontent.com/61758108/137023033-f87d2b12-b958-4579-b9d0-89cdc3d29463.png)

Thank you!
[ALwState.xlsx](https://github.com/ONRR/onrr.gov-site/files/7332905/ALwState.xlsx)

**Comment by codyeckstein** [comment]
This is now live. @merrellc
