### ISSUE TITLE
September IBMP Prices

### ISSUE THREAD

**Issue by damionschulte** [ONRR/onrr.gov-site#1098]
All, I have updated the Data for ONRR.gov sheet on the OneDrive  With the September 2021 IBMP prices. Can you please have the published to the website?  Thanks 

@sudarr

**Comment by damionschulte** [comment]
These look perfect!  Thank you

From: lpgoldstein ***@***.***>
Sent: Wednesday, October 13, 2021 2:05 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] September IBMP Prices (#1098)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@damionschulte<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdamionschulte&data=04%7C01%7Cdamion.schulte%40onrr.gov%7C1e26a8ab77ee4ef2b84008d98e84c2ee%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637697523124972279%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=01lP2bqh2Gkqvpehef5NV4BDokuZZJdoSHhZ2zWKrIE%3D&reserved=0> please let me know if this looks okay and I'll publish http://2017onrr/valuation/IndianOilIBMP.htm

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1098%23issuecomment-942676641&data=04%7C01%7Cdamion.schulte%40onrr.gov%7C1e26a8ab77ee4ef2b84008d98e84c2ee%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637697523124982245%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cfuNv9Etg0gIwLTgzJfuKS91QxZp8go0ToDr72SQWXY%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAO4AEPK6AXATSPPJV4K327DUGXQ55ANCNFSM5F5Z54NQ&data=04%7C01%7Cdamion.schulte%40onrr.gov%7C1e26a8ab77ee4ef2b84008d98e84c2ee%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637697523124982245%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fvGda95Ygr7SBuitIS6sYl6UynoOp98dWtB1wOL5R2U%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdamion.schulte%40onrr.gov%7C1e26a8ab77ee4ef2b84008d98e84c2ee%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637697523124992191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VKmuoq4XX65NY4Wldnbcjy%2B1cNU0R6LSXcSEm0TCn4Y%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdamion.schulte%40onrr.gov%7C1e26a8ab77ee4ef2b84008d98e84c2ee%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637697523124992191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=p6GZxHxRllIoTYkXdM7J8mbcD8qZXk7oP4yVmzPpuY8%3D&reserved=0>.

**Comment by lpgoldstein** [comment]
@damionschulte https://onrr.gov/valuation/IndianOilIBMP.htm live! please let me know if this looks okay and I'll close out the issue.
