### ISSUE TITLE
Royalty Contact update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1102]
Please update the Royalty Contact list at the following location with the attached list - https://www.onrr.gov/reportpay/PDFDocs/royassign.pdf

[royassign.pdf](https://github.com/ONRR/onrr.gov-site/files/7348475/royassign.pdf)

**Comment by Maroyafaied** [comment]
@cvojslavek let me know if you don't have time for this issue and I'll reassign it. Thanks

**Comment by cvojslavek** [comment]
@bowlenj The changes are on the dev site, http://2017onrr/reportpay/PDFDocs/royassign.pdf. Please review and give us your approval to go live.

Thanks!
Cat
