### ISSUE TITLE
Create onrr.gov Axure widget library

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1108]

**Comment by Isabelh99** [comment]
For getting working access to Axure is there a way to get in w/out buying license? Also, its there like a NRRD domain in Axure that I should consider? 
I have this link:
https://qmcq5k.axshare.com/#id=ucmj7g&p=minerals_production_reporter_handbook&g=1
that maybe get me access to it but I'm not to sure...

**Comment by Isabelh99** [comment]
For the widgets library, what should it cover? Should I create something similar to like this:
![image.png](https://images.zenhubusercontent.com/618982f60788a50b9734edf8/e94484e1-8603-40f1-b922-6ed586ed3835)

**Comment by mcharg** [comment]
Here's the one we have for NRRD. We need to create something similar that has the widgets and styles we have on the new onrr.gov dev site.
[NRRD-library.zip](https://github.com/ONRR/onrr.gov-site/files/8622296/NRRD-library.zip)

**Comment by mcharg** [comment]
@cthomasONRR and I completed this.
