### ISSUE TITLE
Get pdfs of the full handbooks

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1112]
We don't have them for these:
- [ ] Minerals Production Reporter Handbook
- [ ] Indian Payor Handbook

**Comment by Maroyafaied** [comment]
look into consolidated the chapters in pdf.

**Comment by cthomasONRR** [comment]
I combined all documents associated with each handbook into 1 PDF.

The Indian Payor Handbook now has table headers failing due to the new Adobe update, but otherwise passes accessibility check.

The MPRH has a TON of accessibility errors when combined. Combined, it is 310 pages. I'm really unsure how to go about resolving.

**Comment by cthomasONRR** [comment]
The combined MPRH has flagged errors in Chapters 3 and 6- when checking those individual docs, there are no errors and it passes accessibility check.

The combined MPRH has flagged errors in: Chapters 2, 4, and 7; Appendices E and I; and the Glossary. All these individual documents are now giving the same errors as well. Errors are mainly associated with Table rows, headers, and summaries.

**Comment by cthomasONRR** [comment]
Maybe a different option would be to have a .zip download on the new website to have 1 download for all individual documents. This could be a workaround because it might not be feasible to make the 300pg MPRH 508 compliant.

**Comment by Maroyafaied** [comment]
@cthomasONRR let's talk about this during our check in tomorrow.

**Comment by cthomasONRR** [comment]
@mcharg 

Here is the Indian Payor Handbook PDF:
[Indian-Payor-Handbook-All-Chapters-Combined.pdf](https://github.com/ONRR/onrr.gov-site/files/7636029/Indian-Payor-Handbook-All-Chapters-Combined.pdf)

We are working with Shannon Hahn to see if they can remediate Ch 7 and Appendix I of the MPRH. Hopefully once those PDFs are fixed, the combined PDF will have less issues.

**Comment by Maroyafaied** [comment]
will make an issue for production handbook.
