### ISSUE TITLE
Make logo in the header clickable

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#112]
Logos in the site header usually go to the homepage.  Ours isn't clickable.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/4583fb48-fbb5-4adf-81b3-681c55e72ae6)

**Comment by jennmalcolm** [comment]
needs to also stay on mobile

**Comment by jennmalcolm** [comment]
Also fix overlapping text on small viewports ![image](https://user-images.githubusercontent.com/30806839/80533304-68bdda00-896b-11ea-9eb6-c8bd41f4a4d5.png)

**Comment by jennmalcolm** [comment]
I didn't get the logo to show up on smaller viewports, so I created #251 for that.

@Maroyafaied could you review the clickable logo in dev?

**Comment by Maroyafaied** [comment]
@jennmalcolm the log is clickable and goes to homepage, looks good.
