### ISSUE TITLE
Please post Dear Reporter Letter

### ISSUE THREAD

**Issue by jpetersononrr** [ONRR/onrr.gov-site#1123]
Christina and I checked for compliance.  Please post the Dear Reporter Letter signed today, Oct 21, and let us know what the link is!  Thank you!

[2021-10-13 Withdrawal Rule DRL Final signed.pdf](https://github.com/ONRR/onrr.gov-site/files/7392716/2021-10-13.Withdrawal.Rule.DRL.Final.signed.pdf)]

**Comment by cthomasONRR** [comment]
@jpetersononrr

Great! I just moved the updates to the live site (https://www.onrr.gov/DearRep.htm).
It can take 30-60min for the live site to update, please use 'Ctrl+F5' to refresh the webpage.

I will close this issue once I see the changes live.

Thanks,
Christine
