### ISSUE TITLE
Update primary nav to match best practices and analytics

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#113]
Current nav:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/083db3f4-6059-4568-9cd1-ea5579b91121)

Proposed nav:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/67b5af52-9ffe-4265-a5af-4afa3d031cbb)

Changes:
* Replaces logo with Home link to bring the link inline with best web practices
* Moves About to the end to bring the order inline with best web practices
* Reorders the rest of the links in order of usage from the FY19 analytics

**Comment by jennmalcolm** [comment]
@mcharg could you take a look at the changes in dev? http://2017onrr/

I'm currently also making some changes to add an anti-harassment page, which is in the nav. They don't want to make it live until next week, so I'll push these changes next week too.

**Comment by mcharg** [comment]
@jennmalcolm Looks good!

**Comment by jennmalcolm** [comment]
Ok, I'm trying to get the alignment better, but I can't seem to get my css changes to update on files in Dreamweaver, so I'll see if I can figure that out.

**Comment by jennmalcolm** [comment]
going to close since these will go live when I push #127
