### ISSUE TITLE
Update sitemap Rulemaking page

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1138]
This does not match the wireframe, and some numberings are incorrect. I put comments on the sitemap.

**Comment by daniel-coleman-1** [comment]
@Maroyafaied updated:
https://92ix0j.axshare.com

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 can you change the title on the navigation to be "Rulemaking". Also some of them have a parenthesis with information that doesn't follow the wireframe such as AA21 "(final rule not published)."   @cthomasONRR can you please review the sitemap vs. the wireframe and make any comments or changes needed for the sitemap? Thanks 

Sitemap
https://92ix0j.axshare.com/#id=6s7b1a&p=3_2_rules___regulations&g=14

Wireframe
https://qmcq5k.axshare.com/#id=h57jbd&p=rulemakings

**Comment by cthomasONRR** [comment]
@mcharg On the wireframe Rule Titles, there are several that are missing parenthetical comments like "(No Final Rule Published)" or "(Withdrawn)". These are all still notated in bold in the site map, they just need to be added to the wireframe. Let me know if I should make a list of these for you to make checking easier.

@daniel-coleman-1 For the sitemap, the pages are titled as "3.2.1.1 AA29: Inflation Adjustment to Civil Monetary Penalty Rates for Calendar Year 2021" ... for all the rulemakings, I think we need to add **1012**-AA29 to the titles (using AA29 as an example here). The full RINs are listed in the wireframes. AA29 through AA02 should have **1012** before them to indicate ONRR. AD70 through AB17 should have **1010** before them to indicate MMS.

Other than that, the list of rulemakings match and are in the correct order between the wireframe and the sitemap. This is my first time reviewing the sitemap, so please let me know if there is anything else I should be reviewing. Thanks!

**Comment by daniel-coleman-1** [comment]
@cthomasONRR and @Maroyafaied thanks for the review, changes have been updated in the site map.

**Comment by mcharg** [comment]
@cthomasONRR Can you make a new issue with what needs to be changed in the wireframe?

**Comment by cthomasONRR** [comment]
@mcharg Done! Issue #1165
