### ISSUE TITLE
October Analytics

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1140]

**Comment by daniel-coleman-1** [comment]
@mcharg what's the correct title for the XREF text file below?

![Screenshot 2021-11-16 122738](https://user-images.githubusercontent.com/83892362/142054349-0433d6c3-0f74-4f2d-96b2-4c9333c6ea56.png)

Otherwise good to go

**Comment by mcharg** [comment]
Cross-Reference Lease to Agreement Number

**Comment by mcharg** [comment]
@daniel-coleman-1 The email I have has a different total for site searches.  Otherwise, looks good.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/4f72dac4-7a6d-418c-9e3f-e77959fe0f83)

**Comment by daniel-coleman-1** [comment]
Resolved issues, thanks for taking a look @mcharg
