### ISSUE TITLE
Add Indian Distribution Dates calendar to ONRR.gov

### ISSUE THREAD

**Issue by bakercook** [ONRR/onrr.gov-site#1142]
Please add Indian Distribution Dates for Calendar Year 2022 to Allottee Assistance page.

[Indian Distribution Dates for Calendar Year 2022.pdf](https://github.com/ONRR/onrr.gov-site/files/7444066/Indian.Distribution.Dates.for.Calendar.Year.2022.pdf)

![image](https://user-images.githubusercontent.com/84582338/139481705-59887a25-5e79-4188-b4d9-cb40e15399b4.png)

**Comment by cthomasONRR** [comment]
@bakercook

Hello,
I made this update on the dev site: http://2017onrr/IndianServices/index.htm
Please review and let us know if you approve for these changes to go live.
Thanks!
Christine

**Comment by bakercook** [comment]
Thank you Christine. That was fast! Can you put the 2021 memo back on the page? The Mineral Owners still need that through December. I will request removal in Q1 CY 2022.


Cheri Baker
Supervisor, Accounts Payable
Office of Natural Resources Revenue
Bldg. 85, Denver Federal Center
Phone: 303-231-3137

________________________________
From: Christine Thomas ***@***.***>
Sent: Friday, October 29, 2021 12:15 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Baker, Cheri L ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Add Indian Distribution Dates calendar to ONRR.gov (Issue #1142)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bakercook<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbakercook&data=04%7C01%7Ccheri.baker%40onrr.gov%7C898a508619df408c952508d99b0832a9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637711282355413695%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Lt0aJi39fqmizQiwzOFvSUwLrbKghnIQdaPM60v8nwA%3D&reserved=0>

Hello,
I made this update on the dev site: http://2017onrr/IndianServices/index.htm
Please review and let us know if you approve for these changes to go live.
Thanks!
Christine

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1142%23issuecomment-954949712&data=04%7C01%7Ccheri.baker%40onrr.gov%7C898a508619df408c952508d99b0832a9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637711282355423651%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Drnv8ulBrlBsk%2F4MoLrHdkqsnXAS7UEg4T4QyBVsIwQ%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUFJ7QR3QMMRPKYBGVI327TUJLQFPANCNFSM5G735JYA&data=04%7C01%7Ccheri.baker%40onrr.gov%7C898a508619df408c952508d99b0832a9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637711282355423651%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gmMKhy0xH1PuInC0ffjdWnXtng3xBNgLV5r8UjK%2F%2Bbo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ccheri.baker%40onrr.gov%7C898a508619df408c952508d99b0832a9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637711282355433603%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=seiceae9pvfKenW%2BgkvcpGYVpI3PTfAak98a2rFIQ5I%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ccheri.baker%40onrr.gov%7C898a508619df408c952508d99b0832a9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637711282355433603%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZfRd3%2Fcw4ITU18pDGQMMs5zw3EBgzW%2B%2Ft%2BCAesS9HEQ%3D&reserved=0>.

**Comment by bakercook** [comment]
Forgot to mention CY 2022 looks good. thanks again


Cheri Baker
Supervisor, Accounts Payable
Office of Natural Resources Revenue
Bldg. 85, Denver Federal Center
Phone: 303-231-3137

________________________________

**Comment by cthomasONRR** [comment]
@bakercook

Sorry for my misunderstanding!
Here is the updated dev site with both CY 21 and 22: http://2017onrr/IndianServices/index.htm
Please review again and let me know if you approve.
Thanks!
Christine

**Comment by bakercook** [comment]
No worries. I approve. Thank you and enjoy your weekend!


Cheri

________________________________
From: Christine Thomas ***@***.***>
Sent: Friday, October 29, 2021 12:28 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Baker, Cheri L ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Add Indian Distribution Dates calendar to ONRR.gov (Issue #1142)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bakercook<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbakercook&data=04%7C01%7Ccheri.baker%40onrr.gov%7C2208ee2ff41f486d08bc08d99b09f9ee%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637711289421949633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=69qIJtO%2FZcrTFI7wkS3YFYLKDsW7Kyz0Yw0QovaATmw%3D&reserved=0>

Sorry for my misunderstanding!
Here is the updated dev site with both CY 21 and 22: http://2017onrr/IndianServices/index.htm
Please review again and let me know if you approve.
Thanks!
Christine

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1142%23issuecomment-954960390&data=04%7C01%7Ccheri.baker%40onrr.gov%7C2208ee2ff41f486d08bc08d99b09f9ee%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637711289421949633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0uVmZwTQKMC7vVlSE5gTKknwd1M0Vl1OWNCKhpT0cd0%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUFJ7QUK47IWCLZ6WYD5HZTUJLRVLANCNFSM5G735JYA&data=04%7C01%7Ccheri.baker%40onrr.gov%7C2208ee2ff41f486d08bc08d99b09f9ee%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637711289421959589%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JiNGX1PmN28ZMUw2mGnYccpaSIE53T5pzeciypsN8oY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ccheri.baker%40onrr.gov%7C2208ee2ff41f486d08bc08d99b09f9ee%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637711289421959589%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wKh%2Fs6tsRVk0HIeOWUiJBLgCQ%2BjpIhpyP85%2FZOswJkg%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ccheri.baker%40onrr.gov%7C2208ee2ff41f486d08bc08d99b09f9ee%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637711289421969547%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8FOXCvfyBKcFF00ltfPTQW%2Bt8uIoXTua1LifRFvGBos%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@bakercook
Great! I just made the changes live. It can take about 30min for the changes to appear on the live site. Use 'Ctrl+F5' to refresh the page. I will close this issue once I see the changes live.
Thanks!
Christine
