### ISSUE TITLE
Add new site 301 redirects to Redirects spreadsheet

### ISSUE THREAD

**Issue by cvojslavek** [ONRR/onrr.gov-site#1145]
For internal redirects found, add the new site 301 redirects from the [SEO_Export spreadsheet](https://doimspp.sharepoint.com/sites/NRRD/Shared Documents/General/ONRR.gov/Design/CMS/SEO_export.xlsx?web=1) to the [Redirects spreadsheet](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared Documents/General/ONRR.gov/Content Audit/Redirects.xlsx?d=w8f317b52f37e47bb8d41dc17ea254e0c&csf=1&web=1&e=R4yhsX) for mapping onrr.gov old urls to new urls. E.g., Redirect spreadsheet has "https://www.onrr.gov/foia/index.htm", add 301 redirect to "/about/foia".

**Comment by cvojslavek** [comment]
@mcharg @jlouis-onrr here is a  redirects update and ready for your review: 
- I’ve added 116 new onrr.gov redirect links to column E, whole redirect attempt. 
- The 116 new onrr.gov redirect links cover the 1,138 blanks remaining for the column C, 301 redirects, located in the Redirects spreadsheet. 
- The 301 redirects status spreadsheet and the Redirects spreadsheet are located at: https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Content%20Audit?csf=1&web=1&e=YFrbMQ

Thanks @jlouis-onrr for answering my questions!

Next Steps:
- Let me know if we should meet.
- After your review, and if there are no issues, I can use the 116 new onrr.gov redirect links in column E, whole redirect attempt, to fill in the 1,138 blanks in the Redirects spreadsheet.

**Comment by mcharg** [comment]
I defer to @jlouis-onrr about whether what you have works.
