### ISSUE TITLE
Royalty Reporting and Error Correction Contact List

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1146]
Please update the Royalty contact list at the following link with the attached list - https://www.onrr.gov/reportpay/PDFDocs/royassign.pdf

They've added a backup column.

[ROYASSIGN 11-2-2021.pdf](https://github.com/ONRR/onrr.gov-site/files/7462122/ROYASSIGN.11-2-2021.pdf)

**Comment by cthomasONRR** [comment]
@bowlenj 

I updated the document on the dev site: http://2017onrr/reportpay/royalty-reporting.htm
Please review and let me know if you approve this update.

Thanks,
Christine

**Comment by bowlenj** [comment]
Looks great, thank you!


Thank You,
Jessica Bowlen
Office of Natural Resource Revenue
Distribution and Disbursement Support Services
Team 1B
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Tuesday, November 2, 2021 9:59 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Royalty Reporting and Error Correction Contact List (Issue #1146)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cbbbe2f51dd4c446f904308d99e19c857%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637714655851452437%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KZ3e4cZ5ecaxDShXvmx9WXntSqMcJ1T%2BNzKz5aqPFFs%3D&reserved=0>

I updated the document on the dev site: http://2017onrr/reportpay/royalty-reporting.htm
Please review and let me know if you approve this update.

Thanks,
Christine

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1146%23issuecomment-957877624&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cbbbe2f51dd4c446f904308d99e19c857%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637714655851462404%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yQn7UA1yqbXYKJbNx%2BznxbzbuB2c2d53haCFflPJ%2FR4%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH72RRHKXOWAUWCFV6LUKAKGPANCNFSM5HGZV2FQ&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cbbbe2f51dd4c446f904308d99e19c857%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637714655851462404%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yKaVhFYgA1uNYbmM14iUXb3It4bsaJF3FL9jiwRLOKw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cbbbe2f51dd4c446f904308d99e19c857%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637714655851472361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=skuHl04AkzcOtdG5QUIXgBBjG38frd5JkA6yXOjOi78%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cbbbe2f51dd4c446f904308d99e19c857%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637714655851472361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MfeOvRm1bJovaCvxo7rEJHVRg1MuvbRiHIJ8mmxgoXM%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@bowlenj
Great! I just made this change live. It can take up to 30min for the change to appear on the live site. Please remember to use 'Ctrl+F5' to refresh the page. I will close this issue once I see the change live.
Thanks,
Christine
