### ISSUE TITLE
Review new glossary definitions.

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1150]
Christine and Cody developed new definitions for previously undefined glossary terms. Please review these new definitions via this [Word document](https://teams.microsoft.com/l/file/8FF796B3-4580-442C-9BE0-4768938BB9A6?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FONRR_Glossary_Terms.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a). The new definitions are in Track Changes, and the corresponding term is notated with a ***** in front of it. Please:

- Do a high level review of the definition (ie. Does it make sense?)
- Make suggestions for which ONRR group or individual SME should review each new definition
- Make suggestions for lowering the reading level, but without changing the content of the definition (I did my best, but struggled with a few)

There are about 60 new definitions. Cat, Lindsay, and Dan- maybe yall can divide it up amongst yourselves and look at ~20 terms each? I game for whatever method works best for yall! Thanks!

**Comment by lpgoldstein** [comment]
@cvojslavek @daniel-coleman-1 I can take the first 20 new definitions.

**Comment by cvojslavek** [comment]
@cthomasONRR for adding suggestions for which ONRR group or individual SME should review the new definition, do you want us to put it under the definition or make a new column?

**Comment by cthomasONRR** [comment]
@cvojslavek You can put it under the definition. Thanks :)

**Comment by cvojslavek** [comment]
@lpgoldstein @daniel-coleman-1 I can take the second 20, *Indian Gas Major Portion to *Production Allocation Schedule Report (PASR)

**Comment by daniel-coleman-1** [comment]
@cvojslavek @lpgoldstein I added numbers, I'll take 41-60.  Looks like an even 160 total.

Cat, I'm seeing "Indian Gas Major Portion" as 68 and "Production Allocation Schedule Report (PASR)" as 119.

**Comment by cthomasONRR** [comment]
@daniel-coleman-1  Just making sure we're all on the same page- you only have to review the new glossary terms (the ones in TrackChanges and with an * in front of the term). We decided to leave the terms that were already defined as-is, because they are already publicly available and we don't want to create multiple versions of the same definition.

**Comment by daniel-coleman-1** [comment]
@cthomasONRR ahh, gotcha gotcha

**Comment by cvojslavek** [comment]
@cthomasONRR I worked on Indian Oil Index-Based Major Portion (IBMP) to Production Allocation Schedule Report (PASR) that has a * in front of the term. I added SMEs/Groups and added a suggestion if I was able to reduce the readability. I also added some notes for consideration, e.g., see Lease, Plant-Specific UCA. Let me know if you'd like to discuss.

**Comment by cthomasONRR** [comment]
@cvojslavek Thanks for your input- I put in comments to your modified definitions and will be accepting almost all of them :)

@lpgoldstein and @daniel-coleman-1 Are you still working on this issue? Just curious if we will need to extend it to next sprint.

**Comment by lpgoldstein** [comment]
@cthomasONRR I think I'm done unless you have any questions.

**Comment by daniel-coleman-1** [comment]
@cthomasONRR I still need to spend some time on this, I'll add comments this afternoon.

**Comment by daniel-coleman-1** [comment]
@cthomasONRR added my notes

**Comment by cthomasONRR** [comment]
Thanks! Closing this issue.
