### ISSUE TITLE
Update 5 corrected docs - Phase 3

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1152]
Please update the documents that Antoinette send by email on 11/3/2021.

**Comment by cthomasONRR** [comment]
- [ ] [880111.pdf](https://github.com/ONRR/onrr.gov-site/files/7474867/880111.pdf)
- [ ] [910708.pdf](https://github.com/ONRR/onrr.gov-site/files/7474868/910708.pdf)
- [ ] [920206b.pdf](https://github.com/ONRR/onrr.gov-site/files/7474869/920206b.pdf)
- [ ] [20030416.pdf](https://github.com/ONRR/onrr.gov-site/files/7474874/20030416.pdf)
- [ ] [csv_Rent_example.pdf](https://github.com/ONRR/onrr.gov-site/files/7474876/csv_Rent_example.pdf)

**Comment by cthomasONRR** [comment]
All 5 files have been updated on the dev and live sites, and they are updated in the document tracking spreadsheet.
