### ISSUE TITLE
Active Leases File Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1153]
Please replace the Active Leases - Sorted by State and Agency Lease Number at the below location with the attached file.  Please leave the date (updated 10/01/2021) as is.  We were notified there were some issues with the current file and need to replace it with the corrected file.

https://www.onrr.gov/reportpay/CrossRef.h
[ALwState_11-3-21.xlsx](https://github.com/ONRR/onrr.gov-site/files/7474719/ALwState_11-3-21.xlsx)
tm

**Comment by cthomasONRR** [comment]
@bowlenj 
I updated this excel in the dev site: https://www.onrr.gov/ReportPay/CrossRef.htm
Please review and give us your approval to go live.
Thanks,
Christine

**Comment by bowlenj** [comment]
Perfect, thank you!

Thank You,
Jessica Bowlen
Office of Natural Resource Revenue
Distribution and Disbursement Support Services
Team 1B
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, November 4, 2021 6:36 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Active Leases File Update (Issue #1153)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C6c38467869bb4e8547d808d99f8fdcab%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716262507201099%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6iX%2BvfaY87M5rYKvLbh7rsBTBaGy1SuBE54W4QuVq3s%3D&reserved=0>
I updated this excel in the dev site: https://www.onrr.gov/ReportPay/CrossRef.htm<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2FReportPay%2FCrossRef.htm&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C6c38467869bb4e8547d808d99f8fdcab%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716262507211054%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0x0runUG0qc2NooYzULoMXwKyEx6uvtMwuvCYnm%2FPKA%3D&reserved=0>
Please review and give us your approval to go live.
Thanks,
Christine

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1153%23issuecomment-960820476&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C6c38467869bb4e8547d808d99f8fdcab%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716262507211054%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qnk9Fzu5s%2Bz4p5IZu37C4vWmmpISO8tqnscCL91OY2w%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH7DWRUEIIZNHLZU22LUKKD43ANCNFSM5HLKDIWQ&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C6c38467869bb4e8547d808d99f8fdcab%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716262507221013%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mQW9dwrz4ErEAB0NBxbihSivfuRAkUHJJuzTJHm5q28%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C6c38467869bb4e8547d808d99f8fdcab%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716262507221013%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=n2wHBWZBfTCHXT5XdsHGddiHliCjnYDfFymmrqICBGE%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C6c38467869bb4e8547d808d99f8fdcab%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716262507230973%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=um0Rb4GDWVieVzUSOpCFgCySMz2r7qBe0LaBDOmkgzg%3D&reserved=0>.
