### ISSUE TITLE
Updates to Payment Webpage

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1154]
Please update this webpage per the attached word document - https://www.onrr.gov/reportpay/payments.htm

The document includes screenshots, please let me know if you need additional information.

Thank You!
[Payments WebPage Update.docx](https://github.com/ONRR/onrr.gov-site/files/7474743/Payments.WebPage.Update.docx)

**Comment by cthomasONRR** [comment]
@bowlenj 
I made all the requested updates. You can review on the dev site: http://2017onrr/reportpay/payments.htm
Please give it a review and let me know if you approve the changes.
Thanks,
Christine

**Comment by Maroyafaied** [comment]
@cthomasONRR @bowlenj this document has accessibility errors and will need to be corrected before publishing on onrr.gov.  Both images need alternative texts. Thanks 
![image](https://user-images.githubusercontent.com/40175688/140316141-202bb3c3-54a0-44a5-88bc-2e98c173c0cd.png)

**Comment by Maroyafaied** [comment]
@bowlenj @cthomasONRR I apologize, I misunderstood and thought you wanted the document itself to be posted on onrr.gov.

**Comment by cthomasONRR** [comment]
@blowlenj linked below is the PDF we have. 
@Maroyafaied I'm not seeing the missing alt text errors, just a missing document title. 
Is there another PDF I should be linking to?
[eCommerce_Online_Rental_FAQ](https://app.zenhub.com/files/210892300/18ff8204-cf10-4cea-99f0-a9a4e1c8c153/download)

**Comment by cthomasONRR** [comment]
@bowlenj could you check to see if you have an updated version of that eCommerce_Online_Rental_FAQ PDF? We have that your team corrected it, but the only version I see on our drives is from 2015. Apologies for any inconvenience!

**Comment by bowlenj** [comment]
Good Morning Christine,

The online in front of Rental Payments looks great!  Were you able to correct the path to Online Rental Payment FAQs, I didn't see it on the review page?

Thank You,
Jessica Bowlen
Office of Natural Resource Revenue
Distribution and Disbursement Support Services
Team 1B
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, November 4, 2021 6:44 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Updates to Payment Webpage (Issue #1154)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C8082a5a81c594551a89608d99f90fdc1%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716267344962110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Vr8x59NJI84VeLlqK9B0nKUhlZ0mCqH%2FoIBAclRRreo%3D&reserved=0>
I made all the requested updates. You can review on the dev site: http://2017onrr/reportpay/payments.htm
Please give it a review and let me know if you approve the changes.
Thanks,
Christine

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1154%23issuecomment-960837923&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C8082a5a81c594551a89608d99f90fdc1%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716267344962110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rXPqOAcfflPygOTsSbsu5XOAYBfN2Yc6rNAAKk%2ByUQk%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH4XR733ZDZVLC5DDB3UKKE5XANCNFSM5HLKKRQA&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C8082a5a81c594551a89608d99f90fdc1%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716267344972066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yc7lInvuOyrcZU%2FMHT1Ac%2FvdMsl0ljsQVBHTRHWB340%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C8082a5a81c594551a89608d99f90fdc1%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716267344972066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EYUiGGXzIHD5sgdtXhawWDHwG6OjV7qOtqj%2FEGmJqHc%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C8082a5a81c594551a89608d99f90fdc1%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716267344982024%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Kbkb6Nk1z0ZGbkiZXdXijyTKBXR4dqfO1O2SwLxOi58%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@bowlenj

The PDF should be appearing here: http://2017onrr/reportpay/PDFDocs/eCommerce_Online_Rental_FAQ.pdf
You might need to press 'Ctrl+F5' to update the webpage.

Could you check to see if you have an updated version of that eCommerce_Online_Rental_FAQ PDF? It's coming up with a document title fail in the accessibility checker. We have that your team corrected it, but the only version I see on our drives is from 2015. Apologies for any inconvenience!

**Comment by bowlenj** [comment]
I will look and let you know, thank you so much for your help on this!

Thank You,
Jessica Bowlen
Office of Natural Resource Revenue
Distribution and Disbursement Support Services
Team 1B
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, November 4, 2021 7:00 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Updates to Payment Webpage (Issue #1154)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf47d800765c04cc76cb408d99f933344%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716276841136508%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ST74KCyi3vYvvLqjTFYon%2B9o8%2FRKLnvPySE8tY96V%2Bs%3D&reserved=0> could you check to see if you have an updated version of that eCommerce_Online_Rental_FAQ PDF? We have that your team corrected it, but the only version I see on our drives is from 2015. Apologies for any inconvenience!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1154%23issuecomment-960870601&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf47d800765c04cc76cb408d99f933344%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716276841146462%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LVyw30u%2Bf3XmtwkPh7NkGwFQFGRcqjSEhsyW3YUU74Y%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH2QYIH2QQCURLIUZ5TUKKGY5ANCNFSM5HLKKRQA&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf47d800765c04cc76cb408d99f933344%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716276841146462%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NxbdtqgD55EXMlKOqUyGNqGD5R6nsNw9RYYUb3Yz1tw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf47d800765c04cc76cb408d99f933344%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716276841156420%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ykcC7K3QOomye7ED4QstVDlXCGxCLxNCnzccm0qc5gk%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf47d800765c04cc76cb408d99f933344%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716276841156420%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EZJHQ%2FO9lzq9rUKDtk4aZUCUdWHMUXiWkR%2FcvPSFGuo%3D&reserved=0>.

**Comment by bowlenj** [comment]
That's it and it pulls up perfectly.  We don't have a newer version, that's it.  Thank you!!!!!!!!!!!!!!

Thank You,
Jessica Bowlen
Office of Natural Resource Revenue
Distribution and Disbursement Support Services
Team 1B
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, November 4, 2021 7:02 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Updates to Payment Webpage (Issue #1154)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C50ff5da0379f4ecdd3e108d99f9375db%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716277959937717%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RnCyDfzyWUJqhFp0gWR3KBtcK8TazODjJcrCex%2BmHgQ%3D&reserved=0>

The PDF should be appearing here: http://2017onrr/reportpay/PDFDocs/eCommerce_Online_Rental_FAQ.pdf
You might need to press 'Ctrl+F5' to update the webpage.

Could you check to see if you have an updated version of that eCommerce_Online_Rental_FAQ PDF? It's coming up with a document title fail in the accessibility checker. We have that your team corrected it, but the only version I see on our drives is from 2015. Apologies for any inconvenience!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1154%23issuecomment-960874407&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C50ff5da0379f4ecdd3e108d99f9375db%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716277959937717%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uqw6qmT46E7vx9X1F8jpzDgQm%2FwiruAxc9ogQz9BhOA%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VHYNDGWTXOVFZ5NZOL3UKKG73ANCNFSM5HLKKRQA&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C50ff5da0379f4ecdd3e108d99f9375db%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716277959947668%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=s%2BOSFH0C%2BraPpF5gVxwIlhekhRmASgLsN1yd44LzRT4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C50ff5da0379f4ecdd3e108d99f9375db%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716277959957629%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UtMbi8HIOlC3cJzvvEPM4jRL6WW5seo2gIKME%2BfMRKs%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C50ff5da0379f4ecdd3e108d99f9375db%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716277959967583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=aL2ATCJ7K3mef7vqxIscZYVSAYkxO0%2FUrSuMrDCvyHo%3D&reserved=0>.

**Comment by bowlenj** [comment]
The link that Christine sent has 508 errors?  Can you send me the pdf and I will get those correct and send back?

Thank You,
Jessica Bowlen
Office of Natural Resource Revenue
Distribution and Disbursement Support Services
Team 1B
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Maroyafaied ***@***.***>
Sent: Thursday, November 4, 2021 6:49 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Updates to Payment Webpage (Issue #1154)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@cthomasONRR<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FcthomasONRR&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf2c63dea55284a440e2208d99f918981%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716269709618422%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ks88aNoXjPuCtE9Qv9rzWl%2BthPxrNA5r65ArV49PTPA%3D&reserved=0> @bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf2c63dea55284a440e2208d99f918981%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716269709618422%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nligxsc2HSVQ0zz2IHIq8D6Uw7eRBTaHUSIMAn95jJM%3D&reserved=0> this document has accessibility errors and will need to be corrected before publishing on onrr.gov. Both images need alternative texts. Thanks
[image]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F40175688%2F140316141-202bb3c3-54a0-44a5-88bc-2e98c173c0cd.png&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf2c63dea55284a440e2208d99f918981%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716269709628376%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Bmp4RCDW9c%2F02wozD5LuxSQO1YDt3YNsQQL4sA722JU%3D&reserved=0>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1154%23issuecomment-960846395&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf2c63dea55284a440e2208d99f918981%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716269709628376%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WII4cSgoyzWXvGX%2B9GSESFZBPiTRgxaNGol0UGAmZT8%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH6N3ROGAKGIAXVPIODUKKFNDANCNFSM5HLKKRQA&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf2c63dea55284a440e2208d99f918981%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716269709638343%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FUEkSbob8RgYcKjdSttan7jjcM2iyulHedVlH55iKSg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf2c63dea55284a440e2208d99f918981%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716269709638343%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=djBWX%2Fb10nV42VE6swXRNFArP%2BZ1BIkt%2ByvWWbyaia0%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf2c63dea55284a440e2208d99f918981%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716269709648292%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=O4OULFR965n65Jx4Cn1r8FOvJLzrMd6%2FmDiKiwn6N7Y%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@bowlenj
Yes, the PDF I sent has an error (document title fail). We need you to correct it. If you have time, we can do a teams call and I can show you how. Thanks, Christine Thomas.

**Comment by cthomasONRR** [comment]
@bowlenj
Thanks for sending the compliant PDF to me! I made that update, and moved both updates to the live site: https://www.onrr.gov/reportpay/payments.htm
It can take up to 30min for the changes to go live. Please use 'Ctrl+F5' to update the webpage.
I will close this issue once I see the changes live.
Thanks!
Christine

**Comment by bowlenj** [comment]
Perfect, thank you!

Thank You,
Jessica Bowlen
Office of Natural Resource Revenue
Distribution and Disbursement Support Services
Team 1B
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, November 4, 2021 7:44 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Updates to Payment Webpage (Issue #1154)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C06c323163a8e4d5bfc6e08d99f994c96%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716303040661415%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MTlzcsWYi0%2B5cP6vUdJ9yl%2F5jPPiWcWzBbpWJk1oVRI%3D&reserved=0>
Thanks for sending the compliant PDF to me! I made that update, and moved both updates to the live site: https://www.onrr.gov/reportpay/payments.htm<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2Freportpay%2Fpayments.htm&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C06c323163a8e4d5bfc6e08d99f994c96%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716303040661415%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=u51eEKGq4tL48NfszVjDfdBgLZakypJYOKW%2FFmZX2NM%3D&reserved=0>
It can take up to 30min for the changes to go live. Please use 'Ctrl+F5' to update the webpage.
I will close this issue once I see the changes live.
Thanks!
Christine

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1154%23issuecomment-960960663&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C06c323163a8e4d5bfc6e08d99f994c96%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716303040671371%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gcicTM0LIuowoDKBpd1TzZSt2zhXoVNrZXOXrbI79yU%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH3CJOELZRTQTSDXABTUKKL5LANCNFSM5HLKKRQA&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C06c323163a8e4d5bfc6e08d99f994c96%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716303040671371%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=e1QAAR75hEwofEy2OisWoA9tIg0DApys0vMSs8v2Ot4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C06c323163a8e4d5bfc6e08d99f994c96%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716303040681326%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LtmZ94GI1Ye3WegM%2FnuggIDH8moaUt31x7opQDeLWMQ%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C06c323163a8e4d5bfc6e08d99f994c96%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716303040681326%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Hl31aoCDN%2BRT77hrMP4HtjFZLykoBnHxiietlCrBJ9Y%3D&reserved=0>.
