### ISSUE TITLE
FOIA page updates

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1160]
ONRR FOIA has been asked to complete the “Chief Officer Report” to DOJ; one of the questions/requirements is regarding ONRR’s FOIA website.  See below question / website guidance:

 

“OIP issued guidance in 2017 [https://www.justice.gov/oip/oip-guidance/OIP%20Guidance%3A%20%20Agency%20FOIA%20Websites%202.0] encouraging agencies to regularly review their FOIA websites to ensure that they contain essential resources, and are informative and user-friendly. Has your bureau/office reviewed its FOIA website(s) during the reporting period to ensure it addresses the elements noted in the guidance?”

 

ONRR FOIA completed this task with your help, however, we missed the direct link on ONRR’s homepage.  Is it possible for you to add this link asap?  When can it be completed so ONRR FOIA can answer the question as “in process”?

**Comment by Maroyafaied** [comment]
Added FOIA link to the footer and send dev link to Tracey Fey to review. http://2017onrr/

**Comment by mcharg** [comment]
@Maroyafaied If you want the link to appear on all pages in the footer, it needs to be updated in Dreamweaver.  Also, it shouldn't have the external link icon.

**Comment by Maroyafaied** [comment]
@mcharg I removed the external link icon, Tracey only mentioned having it in the homepage but it should probably be on each page. I'll try to do it in Dreamweaver.

**Comment by Maroyafaied** [comment]
The footer is not a library in Dreamweaver so the link will be just in the homepage for now as requested. We have the link in the wireframe on all the pages for the new site.
