### ISSUE TITLE
October 2021 NYMEX on ONRR.gov

### ISSUE THREAD

**Issue by penvosej** [ONRR/onrr.gov-site#1161]
Hello,

The October NYMEX prices are ready to be posted to ONRR.gov. The file with the data is attached. Thank you!
@sudarr
[NYMEX102021.xlsx](https://github.com/ONRR/onrr.gov-site/files/7477446/NYMEX102021.xlsx)

**Comment by cthomasONRR** [comment]
@penvosej 
The October prices are on the dev site: http://2017onrr/valuation/NYMEX.htm
Please review and give us your approval for these changes to go live.
Thanks,
Christine

**Comment by penvosej** [comment]
Hi Christine,

The data for October on the website looks good! Thanks for doing that so quickly!

Jessica

From: Christine Thomas ***@***.***>
Sent: Thursday, November 4, 2021 12:54 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] October 2021 NYMEX on ONRR.gov (Issue #1161)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpenvosej&data=04%7C01%7Cjessica.penvose%40onrr.gov%7Cce35e9a40da5473fe94f08d99fc4782f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716488456002735%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ElRd6GXQugMPxjC2AAIJEtg%2Fp0LJJcgkdRBVQ1cFgNY%3D&reserved=0>
The October prices are on the dev site: http://2017onrr/valuation/NYMEX.htm
Please review and give us your approval for these changes to go live.
Thanks,
Christine

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1161%23issuecomment-961327074&data=04%7C01%7Cjessica.penvose%40onrr.gov%7Cce35e9a40da5473fe94f08d99fc4782f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716488456012686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OnbkutkVBGJCozLW1nt6Ymcqg5DbdtRIdSDBMJEowFI%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQQSAVDPZ5F757P7HOSDH3DUKLQENANCNFSM5HMEFVQA&data=04%7C01%7Cjessica.penvose%40onrr.gov%7Cce35e9a40da5473fe94f08d99fc4782f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716488456012686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=O8wOYYeG%2FTs4AVb1Zns58z1lLBt4B%2FUdoAKmJp8VtVE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.penvose%40onrr.gov%7Cce35e9a40da5473fe94f08d99fc4782f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716488456022646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=twTigUhEKgg%2FX%2BXUzHjO3oHZjopdyPdblTcm5SJtWEg%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.penvose%40onrr.gov%7Cce35e9a40da5473fe94f08d99fc4782f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637716488456022646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JxYUHudlX00OBbAnnBgEFvbDG3tATgqhhCVzweRN0vM%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@penvosej
Great! I just moved the changes over to the live site: https://www.onrr.gov/valuation/NYMEX.htm
It can take up to 30min for the changes to go live. Please use 'Ctrl+F5' to refresh the page.
I will close this issue once I see the changes live.
Thanks!
Christine

**Comment by cthomasONRR** [comment]
October prices are live! Closing this issue.
