### ISSUE TITLE
Remove docs in phase 3 without response for doc owners

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1163]

**Comment by cthomasONRR** [comment]
From April Lockler, approval to remove:

- [ ] 20080829b.pdf
- [ ] 20080829.pdf

**Comment by cthomasONRR** [comment]
@cvojslavek I just removed the 6 documents listed above from the dev site. Could you review and let me know if the changes are good to go live? Thanks!

**Comment by cvojslavek** [comment]
@cthomasONRR, looks good! Thanks.

**Comment by cthomasONRR** [comment]
@cvojslavek Awesome- thanks! Just move these changes to the live site :)

**Comment by mcharg** [comment]
Is there anything I need to do on this issue?

**Comment by Maroyafaied** [comment]
@mcharg not now, I'll wait till the 15th and identify who didn't respond and which docs to remove.

**Comment by cthomasONRR** [comment]
@mcharg I think I'll be able to do all the removals, and Cat is here to peer review. We can tag you if we need help!

**Comment by Maroyafaied** [comment]
@cthomasONRR @mcharg here is a status for each doc owner, please go ahead and remove & archive the 13 docs detailed below.

Patty- Remove & Archive 9 docs (emailed on 7/19 and 10/28)
Ken - Remove & Archive 4 docs (emailed on 7/19 and 10/28)
Amy - Jodie & Christina confirmed they will be able to correct docs by end of Nov
Bill - Will meet and discuss, might take videos out of this project and make it seperate
Rob - still working though them, will get a status by end of this week

**Comment by cthomasONRR** [comment]
Removing the following documents for Patty Damon/Stacey Brown. Putting them in the following folders: Y:\reportpay\PDFDocs\archive\PattyDamon-Stacey Brown Phase 3 No Response AND Y:\PDFDocs\archive\PattyDamon-Stacey Brown Phase 3 No Response

- [ ] https://www.onrr.gov/ReportPay/PDFDocs/20011022.pdf
- [ ] https://www.onrr.gov/ReportPay/PDFDocs/20010815.pdf
- [ ] https://www.onrr.gov/ReportPay/PDFDocs/20060907.pdf
- [ ] https://www.onrr.gov/ReportPay/PDFDocs/980512b.pdf
- [ ] https://www.onrr.gov/ReportPay/PDFDocs/911210.pdf
- [ ] https://www.onrr.gov/ReportPay/PDFDocs/990813.pdf
- [ ] https://www.onrr.gov/ReportPay/PDFDocs/20021009.pdf
- [ ] https://www.onrr.gov/PDFDocs/Dear-Reporter-Letter-August-2019-System-Outage.pdf
- [ ] https://www.onrr.gov/PDFDocs/Web-Based-Reporting-Letter.pdf
- [ ] https://www.onrr.gov/PDFDocs/Dear-Report-Letter-November-2018-System-Outage.pdf
- [ ] https://www.onrr.gov/reportpay/PDFDocs/2012ReporterTrainingBook.pdf

**Comment by cthomasONRR** [comment]
@Maroyafaied @mcharg I was able to remove all the reporter letters above except "https://www.onrr.gov/reportpay/PDFDocs/2012ReporterTrainingBook.pdf" because I can't find it anywhere... need to do some more searching on this one.

**Comment by mcharg** [comment]
@cthomasONRR Looks like that doc was also assigned to April and was removed.
![image](https://user-images.githubusercontent.com/38465926/142037263-d6c30c10-f9b2-4bd0-be71-0da7f6fb2adf.png)

**Comment by cthomasONRR** [comment]
@mcharg ok I set it up as removed in the accessibility tracking
