### ISSUE TITLE
Update rulemaking titles in wireframe to match sitemap

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1165]
Sitemap
https://92ix0j.axshare.com/#id=6s7b1a&p=3_2_rules___regulations&g=14

Wireframe
https://qmcq5k.axshare.com/#id=h57jbd&p=rulemakings

On the wireframe Rule Titles, there are several that are missing parenthetical comments like "(No Final Rule Published)" or "(Withdrawn)". These are all still notated in bold in the site map, they just need to be added to the wireframe. 

Let me know if you have any questions. Thanks, Christine.

**Comment by mcharg** [comment]
@cthomasONRR This is updated.  Let me know if additional changes are needed or if we're good to close.
https://qmcq5k.axshare.com/#id=h57jbd&p=rulemakings&g=1

**Comment by cthomasONRR** [comment]
@mcharg Looks good! Thanks for updating!
