### ISSUE TITLE
CONCHO AREA VIRTUAL MEETING                        (Please add to the Events Calendar on Allottee Assistance Page)

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#1168]
NOVEMBER 17, 2021

CONCHO AREA VIRTUAL MEETING

Event Information
Location:  By Telephone
Time: 1:00 pm to 2:00 pm CST
 
Description:  Meeting will be a Call-in Meeting to hear a presentation and updates from ONRR Outreach Office and representatives from BLM, BTFM, and BIA will discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust properties.    A limited number of lines will be available for callers to this meeting. 
 
Who Should Attend:  IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Concho Agency area,  and the Southern Plains Region in Oklahoma.
Other Information: To attend the meeting you must contact the ONRR OKC Outreach Office at (800) 354-7015 to reserve your space and to get the call-in number and passcode for the meeting on August 18th, 2021.   A limited number of lines will be available for callers to this meeting.  ONNR Outreach office hours are Monday- Friday from 7:30 am-5:00 pm.

Event Contact
Name: ONRR OKC Outreach Office
Phone: Toll-free (800) 354-7015,           Email: onrroutreachokc@onrr.gov

**Comment by cthomasONRR** [comment]
@Toddsand21 

I have this update on the dev site: http://2017onrr/events.htm
Please review and give us your approval to go live.

Thanks!
Christine

**Comment by Toddsand21** [comment]
1) If you could change BTFM to BTFA in the first sentence in the description and 2) put a "the: in front of ONRR Outreach Office in that same sentence. 3) In the sentence after Other Information:  Delete everything after meeting and change it to read... the call-in number and passcode for this meeting.  4) Next sentence should read: A limited number of lines will be available for callers to this meeting, so reserve your space as soon as possible.  5) ONRR Outreach Office hours are Mon-Fri from 7:30am-5:00pm CST.

.  Please Delete all of October events.

**Comment by cthomasONRR** [comment]
@toddsand21

I'm not sure I understand all your rewrite instructions for the 'Other Information' section. This is what I understood:

To attend the meeting you must contact the ONRR OKC Outreach Office at (800) 354-7015 to reserve your space and to get the call-in number and passcode for this meeting. A limited number of lines will be available for callers to this meeting, so reserve your space as soon as possible. ONNR Outreach office hours are Monday- Friday from 7:30 am-5:00 pm CST.

Here is the update on the dev site: http://2017onrr/events.htm

**Comment by Toddsand21** [comment]
Looks great and ready to post.

**Comment by cthomasONRR** [comment]
@Toddsand21

Great! I just moved the updates to the live site (https://www.onrr.gov/events.htm). It can take up to 30min for the updates to go live. Please use 'Ctrl+F5' to refresh the page. I will close this issue once I see the changes live.

Thanks,
Christine
