### ISSUE TITLE
Add press releases to cms 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1173]

**Comment by mcharg** [comment]
@cvojslavek Here's a start at a spreadsheet with what's in the content audit.  I think it's missing the date of the press release, the blurb that displays in the list, and whether it's archived.  The collection isn't showing up for me in the CMS, so waiting for @jlouis-onrr to tell us if there are other fields necessary.
https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Collections/Press%20Releases/PressReleases.xlsx?d=w883e10797efd47f88ccf73b892d45f21&csf=1&web=1&e=6pKAKx

**Comment by mcharg** [comment]
Some of the newer press releases are also missing.

**Comment by cvojslavek** [comment]
Looks great. Yes, I agree that the status (archived, published), date, and excerpt are missing based on Jerome's comments yesterday. Good idea to double check the accessibility.

**Comment by mcharg** [comment]
@cvojslavek I updated with the fields from the CMS.  The fields on the right starting with year aren't in the CMS, but thought they might be useful to have for reference.

**Comment by mcharg** [comment]
@mentastc You wanted all the press releases from previous administrations to go into the archived tab, correct?

**Comment by cvojslavek** [comment]
@mcharg I've added the dates and excerpts to the [PressReleases](https://teams.microsoft.com/l/file/883E1079-7EFD-47F8-8CCF-73B892D45F21?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FDesign%2FCollections%2FPress%20Releases%2FPressReleases.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a) spreadsheet; and added the 2020 and 2021 press releases that were missing and put notes for the accessibility.

A few other notes:
- Fixed the "Interior s", "ONRR s", "Obama s" to "Interior's", "ONRR's", "Obama's" (and various other States and companies) in the excerpts.
- For the excerpts, there is not consistency when there is a city before the excerpt, e.g., Denver; Denver -; DENVER; DENVER, CO; Denver, CO -; and the most recent ones are in all caps. Should we make these consistent and not in all caps for accessibility?

Next step:

- Let me know if you want me to add a status when you hear back from Chris.

**Comment by mcharg** [comment]
@cvojslavek I think consistent and not in all caps would be best.

**Comment by mcharg** [comment]
@cvojslavek Chris confirmed that everything from previous administrations should be archived.

**Comment by cvojslavek** [comment]
@mcharg marked the press releases before January 20, 2021 to archived and made the beginning of the excerpts consistent, e.g., Washington—. Also, not sure if matters because it is archived, but the excerpt at F136 has a NRRD site link.
