### ISSUE TITLE
KAULEY VIRTUAL OUTREACH MEETING                               (To be added to the Event Calendar under Events)

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#1176]
**KAULEY VIRTUAL OUTREACH MEETING**
December 15, 2021

EVENT INFORMATION
LOCATION: **By Telephone**
TIME: 1:00 PM – 2:00 PM CST

DESCRIPTION: Meeting will be a Call-in Meeting to hear a brief presentation and updates from the Office of Natural Resources Revenue (ONRR) Indian Outreach Office  Representatives from the Bureau of Land Management (BLM), Bureau of Trust Funds Administration (BTFA), and the Bureau of Indian Affairs (BIA) will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust property issues.  Owners will also have an opportunity to ask questions for the representatives of the four agencies during the Q&A session.

WHO SHOULD ATTEND: IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Southern Plains Region in Oklahoma.
OTHER INFORMATION: To reserve a space and get a passcode for this meeting please contact the ONRR OKC Outreach office at (800)354-7015. The Oklahoma City Outreach office hours are Mon.- Fri. from 7:30 am-5:00 pm.

EVENT CONTACT
NAME: ONRR OKC Outreach Office,  PHONE: Toll Free (800) 354-7015
EMAIL: onrroutreachokc@onrr.gov

**FT BERTHOLD-NEW TOWN, TRENTON, PARSHALL, MINOT, MANDAREE, TWIN BUTTES, WHITE SHIELD, ND, AND FT. PECK-POPLAR, MT VIRTUAL OUTREACH**
December 16, 2021 

EVENT INFORMATION
LOCATION:  **By Telephone** 
TIME 10:00 AM-11:00 AM MST 

DESCRIPTION: Representatives from the Office of Natural Resources Revenue (ONRR) will host a Question and Answer (Q&A) session by phone for Indian Mineral Owners and Indian Trust Property owners regarding their Indian Oil & Gas leases, IIM Accounts, and other Indian Trust properties. Representatives from the Bureau of Land Management (BLM), Bureau of Indian Affairs (BIA), and Bureau of Trust Funds Administration (BTFA), will also be on the call to answer questions. 
 
WHO SHOULD ATTEND:  IIM account holders, Indian mineral owners, and Indian trust property owners in the Ft. Berthold - New Town, Trenton, Parshall, Minot, Mandaree, Twin Buttes, White Shield, ND and Ft. Peck - Poplar areas in Montana.  
OTHER INFORMATION: To attend the outreach session, please contact the ONRR Denver Outreach Office at (800) 982-3226, for the call-in number and passcode.  The Denver Outreach Office hours are Monday-Friday 7:30 am- 4:00 pm MST. 

EVENT CONTACT:  
NAME: ONRR Denver Outreach Office, PHONE: Toll-free: (800) 982-3226
EMAIL:  onrroutreachdenver@onrr.gov

**SHAWNEE AREA VIRTUAL OUTREACH**
December 16, 2021

EVENT INFORMATION
LOCATION: **By Telephone**
TIME: 1:00 PM– 2:00 PM CST

DESCRIPTION: Meeting will be a Call-in Meeting to hear a brief presentation and updates from the ONRR Outreach Office  Representatives from the BLM, BTFA, and BIA will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust property issues, and Bureau updates.  Owners will have an opportunity to ask questions for the representatives of the four agencies during the Q&A session.

WHO SHOULD ATTEND: IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Shawnee Agency Area, Southern Plains Region in Oklahoma.
OTHER INFORMATION: To reserve a space and get the call-in number and passcode for this meeting you may contact the ONRR OKC Outreach office at (800) 354-7015. The Oklahoma City Outreach office hours are Mon- Fri., 7:30 am-5:00 pm CST.

EVENT CONTACT
NAME: ONRR OKC Outreach Office, PHONE: Toll Free (800) 354-7015
EMAIL: onrroutreachokc@onrr.gov

**Comment by cthomasONRR** [comment]
@Toddsand21 

These events have been added to the dev site for your review: http://2017onrr/events.htm
Please let us know if you approve for these changes to go live.

Thanks,
Christine

**Comment by Toddsand21** [comment]
I can't seem to see anything wehn using the link above.  Can you try to send it again?

**Comment by cthomasONRR** [comment]
@Toddsand21 
Make sure you are on PuleSecure, otherwise the dev site won't work.
http://2017onrr/events.htm

**Comment by Toddsand21** [comment]
My Pulse Secure is on and again nothing I cannot view it.

**Comment by Toddsand21** [comment]
Ok. I redone my Pulse and I can see it now.

**Comment by Toddsand21** [comment]
1. under the Kauley Meeting in the first sentence after the Description: Put a period after Office where it reads.... (ONRR) Indian Outreach Office.
2  under the Shawnee Meeting after Other Information: move the phone number (800) 354-7015 all on the same line.

**Comment by cthomasONRR** [comment]
@Toddsand21 

I made these changes. Please do another review and let me know if you approve.
http://2017onrr/events.htm

Thanks,
Christine

**Comment by Toddsand21** [comment]
I don't see the changes.  What is it I hit Control F5 to update the view?

**Comment by cthomasONRR** [comment]
@Toddsand21 Yes, please use 'Ctrl+F5' to refresh the page.

**Comment by cthomasONRR** [comment]
@Toddsand21 Are you able to view? Do you approve the changes?

**Comment by Toddsand21** [comment]
Yes I see the changes now.  They look fine.  Ready to post.

**Comment by cthomasONRR** [comment]
@Toddsand21 Thanks! The changes are live. Closing this issue.
