### ISSUE TITLE
Collect all press releases in one folder

### ISSUE THREAD

**Issue by cvojslavek** [ONRR/onrr.gov-site#1177]

**Comment by cvojslavek** [comment]
@cthomasONRR if you'd like to review, the press releases are located in the [PressReleases folder](https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Collections/Press%20Releases/PressReleases?csf=1&web=1&e=Nfizbr). And the press release information is in the [Press Release spreadsheet](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Collections/Press%20Releases/PressReleases.xlsx?d=w883e10797efd47f88ccf73b892d45f21&csf=1&web=1&e=jdjRPe). Thanks :)

**Comment by cthomasONRR** [comment]
@cvojslavek WOW!!! Thank you so much! This looks amazing!

**Comment by cthomasONRR** [comment]
@lpgoldstein Do you want to review, or are you good with this issue being closed?

**Comment by lpgoldstein** [comment]
@cthomasONRR @cvojslavek Looks great, thanks!
