### ISSUE TITLE
About Page - Update ONRR organization chart 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#118]
https://www.onrr.gov/about/pdfdocs/ONRR_External_Org_Chart.pdf
![image](https://user-images.githubusercontent.com/40175688/79351739-469d7400-7ef6-11ea-8a9d-a2a55060ac43.png)

**Comment by Maroyafaied** [comment]
This is the other location the org chart is located. https://www.onrr.gov/About/index.htm

![image](https://user-images.githubusercontent.com/40175688/79358936-24f4ba80-7eff-11ea-9af8-8277e4bd66aa.png)


Onrresource does not have the pdf organizational chart updated but they have this visual updated https://onrresource/Dynamic-Org-Chart/.

**Comment by jennmalcolm** [comment]
Since this is on the navigation menus, this will be a larger effort than first estimated.

**Comment by jennmalcolm** [comment]
[ONRR External Org Chart, 5-6-2020.pdf](https://github.com/ONRR/onrr.gov-site/files/4628228/ONRR.External.Org.Chart.5-6-2020.pdf)

**Comment by jennmalcolm** [comment]
Updated file on about page--overview. Still need to remove from navigation, along with #119, #120, #147.

**Comment by jennmalcolm** [comment]
@Maroyafaied this is in dev for your review.

**Comment by jennmalcolm** [comment]
changes live
