### ISSUE TITLE
Prep new glossary terms for SME review

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1180]
I need to:

- [x] Accept and reconcile changes/comments in the word document
- [x] Move the definitions in the word document into excel
- [x] Make sure each new definition has a SME assigned to review
- [x] Make the excel sortable by SME
- [x] Draft email to send to all SMEs explaining the review
- [x] Create individual excel files to send to each SME
- [x] Only include the definitions we need each individual SME to review in the personalized email to them
- [ ] Email SMEs - after Thanksiving

New Glossary folder located [here](https://teams.microsoft.com/_#/files/General?groupId=81f624a1-bcde-4f77-ba3b-69c787c88ed3&threadId=19%3A34f9f9ee6b0441dbacab56bfd552f819%40thread.skype&ctx=channel&context=Glossary&rootfolder=%252Fsites%252FNRRD%252FShared%2520Documents%252FGeneral%252FONRR.gov%252FDesign%252FGlossary)
Word document saved [here](https://app.zenhub.com/files/210892300/00cd0452-9359-4df2-a24b-1596cffd8339/download)
Excel saved [here](https://app.zenhub.com/files/210892300/8ce01f93-b798-43e4-967c-759c15b1b5b0/download)

**Comment by cthomasONRR** [comment]
Draft email to SMEs:

"Hello [SME],

As you know, the Open Data, Design, and Development (ODDD) team is working to redesign onrr.gov. Part of this redesign includes adding terms to the ONRR glossary (https://www.onrr.gov/glossary.htm). 

In order to identify relevant terms to add, we targeted the 10 most frequently webpages and pulled terms that needed defining from there. Most of these terms have already been defined in handbooks and other publicly available ONRR documents, but a few had not.

Attached is a list of previously undefined terms that ODDD took the first attempt at defining. We believe these terms fall within your SME-purview, so we would like you to review these definitions. Please review these definitions by [DEADLINE] and left us know if you have any proposed changes.

Thanks for your time and patience,
Christine"

**Comment by cthomasONRR** [comment]
@lpgoldstein and @Maroyafaied When you have time, could you review the draft email (in the comment above) that I'm planning to send SMEs? Planning to email them next week. Thanks!

**Comment by lpgoldstein** [comment]
@cthomasONRR I just changed out "let" instead of "left" in the last sentence. Looks good! Thanks!

**Comment by Maroyafaied** [comment]
@cthomasONRR This looks good, I don't have any changes.

**Comment by cthomasONRR** [comment]
@Maroyafaied What should I do for the deadline? Give them 2 weeks to complete?

**Comment by Maroyafaied** [comment]
@cthomasONRR about how many terms did you identify for each SME?

**Comment by cthomasONRR** [comment]
@Maroyafaied Most SMEs ahve under 10 terms... April and Amy have 15 and 13 respectively. 15 is the most terms that any SME has.
![image](https://user-images.githubusercontent.com/72526208/144061569-c4c5bef2-df9e-4eff-8751-55374339587d.png)

**Comment by cthomasONRR** [comment]
Emails are sent out. Closing this issue.
