### ISSUE TITLE
eCFR contains old onrr.gov links

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1181]
The Regulations Team identified that the eCFR section 1210 (https://www.ecfr.gov/current/title-30/chapter-XII/subchapter-A/part-1210) contains onrr.gov links that no longer work.

I need to:

- [x] Create a list of all the broken links
- [x] Identify if they are already on the redirects sheet
- [x] If not, identify where the broken links should be redirecting
- [x] Figure out a method to properly redirect

**Comment by cthomasONRR** [comment]
@cvojslavek After I compile a list of all the links that don't work, would you have time to help me identify if they are on the redirects spreadsheet?

**Comment by cthomasONRR** [comment]
There are only 4 broken links across all of part 2010, they are just referenced multiple times:

- [ ] http://www.onrr.gov/FM/PDFDocs/eCommerce_FAQ.pdf
- [ ] http://www.onrr.gov/FM/Handbooks/default.htm
- [ ] http://www.onrr.gov/FM/Forms/AFSOil_Gas.htm
- [ ] http://www.onrr.gov/FM/Forms/AFSSol_Min.htm

![image](https://user-images.githubusercontent.com/72526208/142642555-ee973c3d-4251-48b6-92d6-dba862c6559a.png)

**Comment by cthomasONRR** [comment]
- [ ] REDIRECT http://www.onrr.gov/FM/PDFDocs/eCommerce_FAQ.pdf TO https://www.onrr.gov/ReportPay/PDFDocs/eCommerce_Online_Rental_FAQ.pdf

- [ ] REDIRECT http://www.onrr.gov/FM/Handbooks/default.htm TO https://www.onrr.gov/reportpay/Handbooks/index.htm

- [ ] REDIRECT http://www.onrr.gov/FM/Forms/AFSOil_Gas.htm TO https://www.onrr.gov/reportpay/index.htm

- [ ] REDIRECT http://www.onrr.gov/FM/Forms/AFSSol_Min.htm TO https://www.onrr.gov/reportpay/solids.htm

**Comment by mcharg** [comment]
@cthomasONRR I would send the eCommerce FAQ here. https://onrrreporting.onrr.gov/Help/FAQs.aspx

**Comment by cthomasONRR** [comment]
Made a new file folder for the redirect pages: Y:\FM

**Comment by mcharg** [comment]
@cthomasONRR The redirects are all working in dev.

**Comment by cvojslavek** [comment]
@cthomasONRR @mcharg Added those 4 redirects from above to the [Redirects](https://teams.microsoft.com/l/file/8F317B52-F37E-47BB-8D41-DC17EA254E0C?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FContent%20Audit%2FRedirects.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a) spreadsheet and added the new onrr.gov links in the 301 redirects column, see rows 2527-2530.

**Comment by cthomasONRR** [comment]
@cvojslavek Thanks!!!

I emailed the Regs Team, and they are happy with these redirects. I'm going to close this issue now.
