### ISSUE TITLE
Design print view for contacts

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1184]

**Comment by mcharg** [comment]
Include date printed and/or disclaimer.

**Comment by mcharg** [comment]
@jkwonatx You can use this updated version of the spreadsheet to figure out how the contacts should display when printed.  I would look at one of the ones that has 6 contacts.
https://teams.microsoft.com/l/file/EE2FC3B4-4196-4DCE-9286-84AAF6E25E00?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FDesign%2FContacts%2FContactsFiles.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by mcharg** [comment]
Here's a first pass.  I used STRAC and search results.  STRAC because it is the only one with 6 contacts in a topic and search results because it shows the whole topic path.

@lpgoldstein @codyeckstein Do you want to review?

[STRAC Contacts](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Contacts/Print%20Views/Contacts_STRAC.docx?d=w06254be6d92140f48922a76ce9b9a162&csf=1&web=1&e=V82dYl)
[Search Results Contacts](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Contacts/Print%20Views/Contacts_SearchResults.docx?d=w2513fea437dd44b1b7456a4a28efcbb4&csf=1&web=1&e=b9jTz5)

**Comment by codyeckstein** [comment]
Looking at "chev" - Johnny Erle is the offshore contact but in the topic path it says onshore. 
![image.png](https://images.zenhubusercontent.com/612e68b98872341fdb32e3ff/aac24aac-2b00-4d54-b8bc-58335ef882a4)
![image.png](https://images.zenhubusercontent.com/612e68b98872341fdb32e3ff/f14693a3-990c-4fb8-a1ba-f3da5c8b85b3)

**Comment by mcharg** [comment]
@codyeckstein Good catch.  Copy and paste error.  Fixed.

**Comment by codyeckstein** [comment]
Looks good.
