### ISSUE TITLE
About Page: Remove ONRR Highlights pdf 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#119]
This pdf highlights facts from FY 15, it should be removed or replaced with an updated one. https://www.onrr.gov/about/pdfdocs/Fact%20Sheet_ONRR%20Highlights_July%202016.pdf
![image](https://user-images.githubusercontent.com/40175688/79352162-bb70ae00-7ef6-11ea-9c06-9682bf58a65a.png)

**Comment by jennmalcolm** [comment]
@Maroyafaied this change is in dev. Please review.

**Comment by Maroyafaied** [comment]
@jennmalcolm looks good.

**Comment by jennmalcolm** [comment]
changes live
