### ISSUE TITLE
Update Navajo Nation information

### ISSUE THREAD

**Issue by vcs5274** [ONRR/onrr.gov-site#1193]
Good afternoon,

Please remove 

Lockbox mailing address:

Navajo Nation
PO Box 52543
Phoenix AZ 85072-02543
Include Acct No. 6008301569 on the payment. 

Courier (delivery) address:

Wells Fargo Lockbox-S4001-01A
Ref: Navajo Nation/Acct No. 6008301569
1305 West 23rd Street
Tempe AZ 85282 

Note: Payment address will change effective May 26, 2020

Effective May 26, 2020, the lockbox mailing address and courier address will change. Checks for Tribal lease revenues must be made payable to the Navajo Nation Tribe, Distributee Code 341. All checks must include your Payor Code and the Payor-Assigned Document Number (PAD) from the corresponding Report of Sales and Royalty Remittance (Form ONRR-2014), or invoice number. 

Please update New lockbox mailing address to Lockbox Mailing Address and New courier (delivery) address to Courier (delivery) 
Address.

Respectfully,

Victoria Soto

**Comment by lpgoldstein** [comment]
@vcs5274 This is ready for your review: http://2017onrr/reportpay/payments.htm

**Comment by vcs5274** [comment]
Good afternoon,

Thank you. The update looks great.

Respectfully,

Victoria Soto, Supervisory Accountant
Accounting Services, General Ledger
Office of Natural Resources Revenue
Denver Federal Center (6th Ave West & Kipling St
Bldg. 85, Entrance N-1
Denver, CO  80225
Phone: 1-800-433-9801 x13085
     -or-      303-231-3085
Mobile: 720-220-6044
Fax: 303-445-9526
Email: ***@***.******@***.***>

"Remember. Everyday some ordinary person does something extraordinary. Today, it's your turn." - Lou Holtz

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________
From: lpgoldstein ***@***.***>
Sent: Tuesday, November 23, 2021 12:07 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Soto, Victoria C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update Navajo Nation information (Issue #1193)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@vcs5274<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvcs5274&data=04%7C01%7Cvictoria.soto%40onrr.gov%7C91bf9775028e48eb0ad408d9aeb49291%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637732912864477339%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=L2yfP1kTU9oWoTcyHNa3%2BNivHz1qd50BCzrxPK1p0ZE%3D&reserved=0> This is ready for your review: http://2017onrr/reportpay/payments.htm

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1193%23issuecomment-977031997&data=04%7C01%7Cvictoria.soto%40onrr.gov%7C91bf9775028e48eb0ad408d9aeb49291%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637732912864477339%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=P%2BcpfqzwY6g7dEu56Sunsm7QDCQxWQDo8EQu8b0zo3Y%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQUVKJHD7ATZIV3YS34MN23UNPRAHANCNFSM5IUHDUIA&data=04%7C01%7Cvictoria.soto%40onrr.gov%7C91bf9775028e48eb0ad408d9aeb49291%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637732912864487308%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lZUHRjrDQvkOa0EKXZsKwqHdnAgFv5gJKmdapHzTIus%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cvictoria.soto%40onrr.gov%7C91bf9775028e48eb0ad408d9aeb49291%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637732912864487308%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=220FcaE9V73AxIOkGoupbcb6ftq%2FNkURCEypw2U4sZ0%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cvictoria.soto%40onrr.gov%7C91bf9775028e48eb0ad408d9aeb49291%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637732912864487308%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bYrj%2BKTcYPaMZ0XK2y5KZODUxPqhrgoWh%2B82fvUB64Q%3D&reserved=0>.

**Comment by lpgoldstein** [comment]
Thanks @vcs5274  - I'll let you know when it's live for final review.

**Comment by lpgoldstein** [comment]
@vcs5274 This is live!

**Comment by vcs5274** [comment]
Hello,

I checked the live site and I am not seeing the updates. The old information is still showing

[cid:3c416d9f-78b8-40a3-98f3-57f3099951ed]

Respectfully,

Victoria Soto, Supervisory Accountant
Accounting Services, General Ledger
Office of Natural Resources Revenue
Denver Federal Center (6th Ave West & Kipling St)
Bldg. 85, Entrance N-1
Denver, CO  80225
Phone: 1-800-433-9801 x13085
     -or-      303-231-3085
Mobile: 720-220-6044
Fax: 303-445-9526
Email: ***@***.******@***.***>

"Remember. Everyday some ordinary person does something extraordinary. Today, it's your turn." - Lou Holtz

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________
From: lpgoldstein ***@***.***>
Sent: Tuesday, November 23, 2021 1:33 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Soto, Victoria C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update Navajo Nation information (Issue #1193)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@vcs5274<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvcs5274&data=04%7C01%7Cvictoria.soto%40onrr.gov%7C6087efe2dd8c48d395bc08d9aec0962c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637732964453476517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=N9yKumlRro3sz8piv9TXkTLivRstyTrFVrIH0V1ghCU%3D&reserved=0> This is live!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1193%23issuecomment-977147959&data=04%7C01%7Cvictoria.soto%40onrr.gov%7C6087efe2dd8c48d395bc08d9aec0962c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637732964453476517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=p%2Fr%2BwnH6Qk%2FcR4M1GMVpmulmUVO%2BEjTibwdTf0BBrX0%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQUVKJHCPOJYXOG6TLNCTCTUNP3CPANCNFSM5IUHDUIA&data=04%7C01%7Cvictoria.soto%40onrr.gov%7C6087efe2dd8c48d395bc08d9aec0962c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637732964453486472%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=s9CdtV1N4vtssGe5ZAJ9OYiXoPGlkoE4YVj4EYYYAmA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cvictoria.soto%40onrr.gov%7C6087efe2dd8c48d395bc08d9aec0962c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637732964453486472%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zoYHPU9iTYrVPRhLgPYSsj9ifBJN68%2F3ymaq3vJV9NA%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cvictoria.soto%40onrr.gov%7C6087efe2dd8c48d395bc08d9aec0962c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637732964453496430%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=00NjxmkT4Vdn6BtMXGYHvrKYgn2qJ8NZ9FCTOwv9QMg%3D&reserved=0>.
