### ISSUE TITLE
Update onrr.gov with new logo

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1194]

**Comment by mcharg** [comment]
This is updated in dev.  @lpgoldstein Do you want to take a look and let me know if it looks ok to go live?
http://2017onrr/

**Comment by daniel-coleman-1** [comment]
@mcharg I can't read the text underneath ONRR, but I can't even see the white text on the old logo so I'm thinking ok to go live.

**Comment by mcharg** [comment]
@daniel-coleman-1 It needs to be about 125px to be readable, which we can fix on the new site.

**Comment by mcharg** [comment]
Pushed live.
