### ISSUE TITLE
Add FY21 Press Release to Site

### ISSUE THREAD

**Issue by mentastc** [ONRR/onrr.gov-site#1196]
Add FY21 Disbursements press release to ONRR.gov site. 

Press Release attached
[Fiscal Year 2021 Disbursements Press Release.pdf](https://github.com/ONRR/onrr.gov-site/files/7591283/Fiscal.Year.2021.Disbursements.Press.Release.pdf)

**Comment by cthomasONRR** [comment]
@lpgoldstein and @mentastc 

The dev site is available for your review:
http://2017onrr/about/NewsReleases.htm

**Comment by cthomasONRR** [comment]
Lindsay reviewed. I moved the changes to the live site.

**Comment by cthomasONRR** [comment]
It's live! Closing this issue.
