### ISSUE TITLE
Unbundling page changes

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1199]
RV sent us a doc with changes they want.

**Comment by mcharg** [comment]
I started this, but a lot of the changes bring the reading level up to grade 14 or 15, so I sent it back asking them to try to lower the reading level.

**Comment by cthomasONRR** [comment]
@mcharg Do you want to review before I send this to Sara?
https://qmcq5k.axshare.com/#id=l9inb4&p=valuation___pricing

**Comment by cthomasONRR** [comment]
Emailed Sara, awaiting additional changes since she's reevaluating with Hemmingway.

**Comment by cthomasONRR** [comment]
Sara reviewed the axure and approved changes. She might email us with reading level changes after the holidays.
