### ISSUE TITLE
Merge contacts prototype with other prototype and add troubleshooting tab to reporting pages

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1201]
After we finalize them for contacts.

**Comment by mcharg** [comment]
https://qmcq5k.axshare.com/#id=079wgt&p=contact_us

I made the following changes.
* Imported the Contact Us pages from the contact prototype into the overall one.
* Updated the Contacts tabs on the other pages to match the ones in Contact Us.
* Updated Troubleshooting tab on System Access page to match the one in Contact Us.
* Added Troubleshooting tabs to all the Reporting pages to match the ones in Contact Us.

I'll reflect all the changes in the content tracking sheet as part of issue #1328.

@cthomasONRR Can you review and make sure I didn't break anything?

**Comment by cthomasONRR** [comment]
For getting started and system access, the only contact in the contacts tab is the IT help desk... is this correct?

In Geothermal, there is a duplicate accordion:
![image](https://user-images.githubusercontent.com/72526208/148437933-1befd99f-23cb-4f91-8c6d-6ca5cf732658.png)

For the payments and debt collection contacts page, I'm wondering if these 4 accordions would be better as tabs:
![image](https://user-images.githubusercontent.com/72526208/148438071-690b823e-f4a9-4b11-b4cb-81414383d4b6.png)

In payments and debt collection, I think this "Paying Contacts" link should be reworded to "Payments and Debt Collection Contacts" if possible. Or should it actually be redirecting to the paying contacts under the paying webpage? Right now it's linking to the Payments and Debt Collection Contacts within Contact Us. Are these the same webpage? It looks like the same contacts duplicated in 2 different locations.
![image](https://user-images.githubusercontent.com/72526208/148438313-abe7f5d6-657c-49d3-adc4-c2644fddeda1.png)

In the Indian Services Contacts, there is content that needs to be filled out (you likely know this, but wanted to point it out just in case.):
![image](https://user-images.githubusercontent.com/72526208/148439437-eb574339-7fbc-4c51-aa28-03fb76f5d218.png)

That's all I have found so far. I'll keep clicking around though!

**Comment by mcharg** [comment]
For getting started and system access, the only contact in the contacts tab is the IT help desk... is this correct?

SM: This is correct.  We were told the other contacts we had on that page aren't monitored.

**Comment by mcharg** [comment]
The two paying pages are the same, just in different places.  I'll change the accordions to tabs and change the link to just say "Contacts", since it opens the Contacts accordion on the same page.

**Comment by mcharg** [comment]
@cthomasONRR 

Geothermal extra accordion is gone.

Paying - Accordions are now tabs.  Also applied the card design to this page. https://qmcq5k.axshare.com/#id=rmsbze&p=payments&g=1

Indian - Removed intro copy.  Amanda said they don't really have a problem with people contacting the wrong people for Indian, so I don't think we need it.

**Comment by cthomasONRR** [comment]
@mcharg I reviewed again, and it looks good! Thanks for making those changes.
