### ISSUE TITLE
Upload accessible chapter 7 and appendix I

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1202]

**Comment by Maroyafaied** [comment]
@cthomasONRR I believe Appendix I is located in more than one place in the website. I believe it's in the production handbook section as well as in here https://onrr.gov/reportpay/references.htm ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/9d05089b-1826-4bfd-8db7-e23aefc36e42)

**Comment by cthomasONRR** [comment]
Got all locations on the Y and Z drive updated :)
I'll wait for Shannon H's response before attempting to create a combined handbook again.
