### ISSUE TITLE
Add Solids videos page to the live site

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1204]
There are 5 P&R videos that aren't linked on the site.
https://www.youtube.com/user/ONRRChannel

**Comment by daniel-coleman-1** [comment]
The page is up in Y: Report Pay > Training > Solids-Training-Videos.

It looks like we keep MP4's of the videos available for download on the live site from our servers.  I reached out to Bill Blackburn for MP4 copies.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 what's the link for the page in the dev site? The 5 videos are in the link that @mcharg posted in the issue, you only need the youtube links to post the videos.
![image](https://user-images.githubusercontent.com/40175688/145492331-059ab4b0-026b-43b9-b0d2-45383b4dbdf7.png)

**Comment by daniel-coleman-1** [comment]
file:///Y:/reportpay/training/Solids-Training-Videos.html#

**Comment by daniel-coleman-1** [comment]
@Maroyafaied the buttons on the right offer a download of the video, but we don't have saved copies of these videos

![Screenshot 2021-12-09 163940](https://user-images.githubusercontent.com/83892362/145492648-9ccb1d90-5425-44a2-a89b-4ffb5b38d6af.png)

**Comment by Maroyafaied** [comment]
Ok, I see what you mean.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 if you haven't heard from Bill yet then let's just push live without the MP4

**Comment by mcharg** [comment]
@daniel-coleman-1 Can you make the tab for the first video blue instead of green?  The only page with the green is the OGOR one and I'm not sure why.

Also, please link to this page from these two pages:
http://2017onrr/reportpay/training/index.htm (add to the list of training videos)
http://2017onrr/reportpay/solids.htm (create a new header for videos after the Regulations header)

**Comment by daniel-coleman-1** [comment]
Pages have been updated in dev:
http://2017onrr/reportpay/training/index.htm
http://2017onrr/reportpay/solids.htm
http://2017onrr/reportpay/training/Solids-Training-Videos.html

@mcharg on the Solids page I didn't create a new header for videos, I placed the link under the "Training Materials" header in the right sidebar.  I could move that heading from the right sidebar to the center underneath Regulations.
dev:
![Screenshot 2022-01-11 102615](https://user-images.githubusercontent.com/83892362/148991863-55460f37-1b1e-4445-9cdc-909d14b3eaec.png)
live:
![Screenshot 2022-01-11 102914](https://user-images.githubusercontent.com/83892362/148992115-fdf54362-d68a-4e51-a5e5-7bfb765d4bea.png)

**Comment by daniel-coleman-1** [comment]
I don't like the spaces here but I think it's ok for now until we can get the MP4's and return the download button.  I sent Bill B a follow up email about the files.
![Screenshot 2022-01-11 103307](https://user-images.githubusercontent.com/83892362/148992687-5f1452c7-9196-429a-9110-24cf8dc4b56e.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 

Here's my feedback:
* The solids page is .html and all the other video pages are .htm.  We should be consistent.
* We should use relative links instead of linking to the live site from dev.  I made the change on the training page, since I was in there making other updates.  Please make the same change to the solids page.  I will comment out the link to the solids page on this page if the other changes are approved to go live before you make your edits.
* The first video tab is still showing up as green for me. ![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/a4fd8151-abe0-4990-8575-e2e288d24e11)
* I'm fine with where you put the link on the solids page.

**Comment by mcharg** [comment]
* Just noticed the download icons are still there for me.  Did you not save your changes to the page on the Y drive?

**Comment by daniel-coleman-1** [comment]
@mcharg you may need to clear your cache

**Comment by daniel-coleman-1** [comment]
@mcharg thanks for the feedback, I've edited the link in the solids page to a relative link and changed the Solids Training Videos file to a .htm file.  I think we're good to push changes live.

**Comment by mcharg** [comment]
@daniel-coleman-1 You just need to change the .html to .htm on the link from the training page.

**Comment by daniel-coleman-1** [comment]
@mcharg got it in, thanks

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 can you push this live.

**Comment by daniel-coleman-1** [comment]
We are live:
http://2017onrr/reportpay/training/Solids-Training-Videos.htm
http://2017onrr/reportpay/solids.htm
https://onrr.gov/reportpay/training/index.htm
