### ISSUE TITLE
Figure out linking to CFR from troubleshooting guide

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1205]
This is the page where it was recommended.
https://4pkq0v.axshare.com/#id=bhj7vh&p=oil___gas_production&g=4

**Comment by cthomasONRR** [comment]
Oil and Gas Production falls within 30 CFR 1210: https://www.ecfr.gov/current/title-30/chapter-XII/subchapter-A/part-1210

OGOR report filing falls under 30 CFR 1210 Subpart C: https://www.ecfr.gov/current/title-30/chapter-XII/subchapter-A/part-1210#subpart-C

I recommend adding a new card under the "I need to understand how to file an OGOR" accordion, with the link to 30 CFR 1210 Subpart C:
![image](https://user-images.githubusercontent.com/72526208/144880079-302a1bef-638d-4672-a193-1ef5990f55db.png)

**Comment by mcharg** [comment]
@cthomasONRR Should we add CFR links for any of the other guide pages?

**Comment by cthomasONRR** [comment]
@mcharg Give me some time and I'll make you a table showing which links should go where in each troubleshooting guide.

**Comment by mcharg** [comment]
@cthomasONRR Awesome!  You're amazing.

**Comment by cthomasONRR** [comment]
@mcharg Here is my table: [eCFR links for troubleshooting guides.xlsx](https://github.com/ONRR/onrr.gov-site/files/7662359/eCFR.links.for.troubleshooting.guides.xlsx)

Let me know if you want to put it in a shared drive location. I did my best to ID the correct CFR cites, but I mainly work in part 2016 so SMEs might have recommendations on better links to add.

**Comment by mcharg** [comment]
@cthomasONRR This folder would be a good place to put it. https://teams.microsoft.com/_#/files/General?threadId=19%3A34f9f9ee6b0441dbacab56bfd552f819%40thread.skype&ctx=channel&context=Contacts&rootfolder=%252Fsites%252FNRRD%252FShared%2520Documents%252FGeneral%252FONRR.gov%252FDesign%252FContacts

**Comment by cthomasONRR** [comment]
@mcharg Great, I just added it there. Thanks!

**Comment by mcharg** [comment]
I added #1223 for applying to wireframes.

**Comment by mcharg** [comment]
https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Contacts/eCFR%20links%20for%20troubleshooting%20guides.xlsx?d=w6f9e65db7c3f40ceb3a5ad7d598558be&csf=1&web=1&e=hYVq1o

**Comment by cthomasONRR** [comment]
@mcharg Great! Let me know if you need any revisions to the table. I will close this issue.
