### ISSUE TITLE
NYMEX Monthly Upload

### ISSUE THREAD

**Issue by WW-Git-Hub** [ONRR/onrr.gov-site#1214]
November Nymex prices are ready for upload.

[NYMEX Monthly Price Calc Instructions 202110.docx](https://github.com/ONRR/onrr.gov-site/files/7651695/NYMEX.Monthly.Price.Calc.Instructions.202110.docx)

Walter Weathersby
@sudarr

**Comment by WW-Git-Hub** [comment]
I added the wrong file. 

Here's the correct one:

[NYMEX112021.xlsx](https://github.com/ONRR/onrr.gov-site/files/7651697/NYMEX112021.xlsx)

@sudarr

**Comment by cthomasONRR** [comment]
@WW-Git-Hub 

Great! I made the changes in Dev: http://2017onrr/valuation/NYMEX.htm
Please review the dev site and give us the ok to go live.

Thanks,
Christine

**Comment by WW-Git-Hub** [comment]
Prices are correct.

From: Christine Thomas ***@***.***>
Sent: Friday, December 3, 2021 12:49 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Weathersby, Walter B ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] NYMEX Monthly Upload (Issue #1214)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@WW-Git-Hub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWW-Git-Hub&data=04%7C01%7Cwalter.weathersby%40onrr.gov%7Ca006be962b864a38bacd08d9b68da33d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637741541725434949%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=14VSSa8LAG3d5SLw4XaDC1do9kekId7fCEDuFUxMyPI%3D&reserved=0>

Great! I made the changes in Dev: http://2017onrr/valuation/NYMEX.htm
Please review the dev site and give us the ok to go live.

Thanks,
Christine

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1214%23issuecomment-985749179&data=04%7C01%7Cwalter.weathersby%40onrr.gov%7Ca006be962b864a38bacd08d9b68da33d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637741541725434949%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DrQl0oZDYwsJK7Ft5kjsGzVzXsrNCji%2BwxQo29EX1Xw%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWYROVMMY7PKH7ROBMHLL6TUPEGJZANCNFSM5JKL6OTQ&data=04%7C01%7Cwalter.weathersby%40onrr.gov%7Ca006be962b864a38bacd08d9b68da33d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637741541725444940%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=b7JZP6wTHPahV1OQqNHtHtzdRfFEwDDen9eael83lCw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cwalter.weathersby%40onrr.gov%7Ca006be962b864a38bacd08d9b68da33d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637741541725444940%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=S6mc2DhjC%2BuXqTEwZiMWxH4RNJptRg5bUgk3u9gUnjg%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cwalter.weathersby%40onrr.gov%7Ca006be962b864a38bacd08d9b68da33d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637741541725444940%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=da5z3n8Pv10O%2B2oWjPRhBkzjAqGC2DONNSBM2c%2FA5q0%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
Thanks! The changes are now live: https://www.onrr.gov/valuation/NYMEX.htm

Closing this issue.
