### ISSUE TITLE
Present 508 compliance study findings to 508 team

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1216]

**Comment by cthomasONRR** [comment]
Do we have a meeting scheduled for this? If not, I can work on getting one scheduled.

**Comment by mcharg** [comment]
@cthomasONRR We don't.  Not sure when Nichelle is back in the office.

**Comment by cthomasONRR** [comment]
We have a meeting scheduled with Nichelle for Tuesday, January 4 @ 9am.

**Comment by cthomasONRR** [comment]
Some of the action items discussed with Nichelle: incorporate 508 info into all-hands meetings, put the compiled resource list (developed by the 508 Documents Team) on ONRResource, promote the use of Microsoft documents over PDFs for the website and ask Kimbra/Howard to endorse this. 

I believe we can close this issue now.
