### ISSUE TITLE
Page: Oil & Gas Production

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1217]
https://dev-onrr-frontend.app.cloud.gov/reporting/production
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/19
https://qmcq5k.axshare.com/#id=sw7sll&p=oil___gas_production&g=1

**Comment by Maroyafaied** [comment]
@jlouis-onrr will do a bulk upload for the press releases.

**Comment by Maroyafaied** [comment]
Start with production reporting page.

**Comment by mcharg** [comment]
Didn't get very far until I ran into things I couldn't do.  I added issues and added them as dependencies on this one.

**Comment by mcharg** [comment]
Page in dev: https://dev-onrr-frontend.app.cloud.gov/reporting/production

**Comment by mcharg** [comment]
Changing this issue to just be setting up tabs and then creating separate issues for tabs.

**Comment by mcharg** [comment]
@cthomasONRR This is just reviewing the tabs (not the content within them.)

**Comment by cthomasONRR** [comment]
@mcharg I reviewed the tabs. It looks good to me. Added my name as reviewed in the ContentTracking sheet.
