### ISSUE TITLE
Add a folder to house compiled Dear Reporter Letters

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1222]
Beginning of creating a 'collection' for CMS.

Folder located [here](https://teams.microsoft.com/_#/files/General?groupId=81f624a1-bcde-4f77-ba3b-69c787c88ed3&threadId=19%3A34f9f9ee6b0441dbacab56bfd552f819%40thread.skype&ctx=channel&context=Dear%2520Reporter%2520Letters&rootfolder=%252Fsites%252FNRRD%252FShared%2520Documents%252FGeneral%252FONRR.gov%252FDesign%252FCollections%252FDear%2520Reporter%2520Letters)

**Comment by cthomasONRR** [comment]
@mcharg This is ready for your review. I have the folder link in the issue description. In the excel, I have the 10 documents not yet 508-compliant highlighted. I am waiting to add those PDFs until we get compliant documents. Christina M should likely get those last 10 to us by the end of the week.

**Comment by mcharg** [comment]
@cthomasONRR There's a monthly revenue csv in the folder, but otherwise looks good.

**Comment by cthomasONRR** [comment]
@mcharg Oops! I was wondering where that file went to! I removed it from the Reporter Letters folder.

**Comment by cthomasONRR** [comment]
@mcharg The last 10 PDFs are now saved in the folder and 508-compliant. Do you want to do another review, or are you OK with me closing this issue?

**Comment by mcharg** [comment]
@cthomasONRR Go ahead and close.
