### ISSUE TITLE
Add CFR links to wireframes

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1223]

**Comment by mcharg** [comment]
Spreadsheet: https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Contacts/eCFR%20links%20for%20troubleshooting%20guides.xlsx?d=w6f9e65db7c3f40ceb3a5ad7d598558be&csf=1&web=1&e=hYVq1o

**Comment by mcharg** [comment]
@cthomasONRR These are ready for you to review in the wireframes.
https://4pkq0v.axshare.com/

**Comment by cthomasONRR** [comment]
@mcharg I'm looking though each troubleshooting card, and everything looks good to me!
