### ISSUE TITLE
Component: Report Electronically

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1224]
This is going to live on lots of pages.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/2189efa0-4af3-4a82-b5d3-34b14d5b0e3d)

**Comment by mcharg** [comment]
The component was created for the homepage, but it need buttons and the ability to have two columns.

**Comment by mcharg** [comment]
Also needs to be able to be reused on tabs.

**Comment by cthomasONRR** [comment]
@mcharg Buttons work! Approved
