### ISSUE TITLE
Add References page to CMS

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1228]
I picked one I thought I might be able to build now.

Design: https://qmcq5k.axshare.com/#id=7g1uot&p=references

**Comment by mcharg** [comment]
Won't display in dev because of the slug error. https://dev-onrr-frontend.app.cloud.gov/references

**Comment by mcharg** [comment]
@cthomasONRR Take a looks and see if you think this one is good to call done.
https://dev-onrr-frontend.app.cloud.gov/references

**Comment by cthomasONRR** [comment]
The Rulemakings and Valuation & Pricing links highlighted below don't work.
The Regulations and ICRs links highlighted below send you to 'Page not found'.
![image](https://user-images.githubusercontent.com/72526208/149572043-7d0051d5-53a9-4517-9cf9-e7cd58e6dfeb.png)

**Comment by cthomasONRR** [comment]
Links are fixed, looks good!
