### ISSUE TITLE
change contact info for communications manager on office locations page

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#123]
They want two email boxes to show up separately:

onrrcongressionalaffairs@onrr.gov
onrrpublicaffairs@onrr.gov

**Comment by jennmalcolm** [comment]
@mentastc please review your requested changes http://2017onrr/About/office-locations.htm

**Comment by mentastc** [comment]
@jennmalcolm looks good! thank you for making that change!

**Comment by jennmalcolm** [comment]
changes live
