### ISSUE TITLE
Improve table interaction.

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1230]
- [ ] Copying and pasting content doesn't work.
It pastes below the table instead of in the cell.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/0b924bd8-7a1d-418e-83f7-4f807f093c7e)

**Comment by mcharg** [comment]
Also, adding a column adds them to the beginning even if you click on the plus sign at the end.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/82304a66-bd22-401b-bf9f-f239dece6510)

**Comment by mcharg** [comment]
- [ ] You can't delete a column once you add it.

**Comment by Maroyafaied** [comment]
Look into functionality of adding a spreadsheet that creates a table.

**Comment by mcharg** [comment]
@daniel-coleman-1 Showed us how to do all of this.
