### ISSUE TITLE
Page: Statutes

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1231]
https://dev-onrr-frontend.app.cloud.gov/references/statutes
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/20
https://qmcq5k.axshare.com/#id=lef7h9&p=statutes

**Comment by mcharg** [comment]
We can build this without a collection.

**Comment by cthomasONRR** [comment]
@mcharg I built the table and this page is ready for your review. Aside from getting more table functions (sizing, sorting), this page is complete.

**Comment by mcharg** [comment]
@cthomasONRR Looks good!
