### ISSUE TITLE
Fix links for OGOR Training videos

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1232]
This issue came in the onrrweb mailbox, I asked if they know the correct links but I'm sure we can find them on youtube. 

We've been preparing to give various internal and external trainings and in the course of that I found that several of the links on https://www.onrr.gov/reportpay/training/OGOR-Training-Videos.htm are not correct.  It is a combination of broken links and links pointing to the incorrect video.  The items I found are below:

The download link for "OGOR 01: Basic OGOR report" does not match the linked YouTube video and instead points to the same video as "OGOR Edit 11030 (onshore) & 11050 (offshore)":

The "OGOR 03-01: Manually Enter OGOR - Header" YouTube link is wrong.  It is pointing to a video on how to manually modify an OGOR Header (the same video as "OGOR 06-1: How to Manually Modify OGOR Header").  The download link points to the correct video:

The "OGOR 03-4: Manually Enter OGOR - Part B Example" YouTube link is wrong.  It is pointing to a video on how to manually modify OGOR Part B (the same video as "OGOR 06-3: How to Manually Modify OGOR Part B").  The download link is also broken.

Thank you very much,

**Comment by Maroyafaied** [comment]
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/e045964a-7098-40d7-92ca-202b11f172cf)

**Comment by lpgoldstein** [comment]
@Maroyafaied I was able to fix the first one but the second video isn't on YouTube but we do have it in the folder. We don't have the video for the 3rd one either nor is it on YouTube. I'll email Bill about it and CC you.

**Comment by lpgoldstein** [comment]
The first two videos are fixed and live and I have commented out the last video. Waiting on approval for removing the last video from the site until the video itself is completed.
