### ISSUE TITLE
Revamp block columns to be collection of layout breaks

### ISSUE THREAD

**Issue by jlouis-onrr** [ONRR/onrr.gov-site#1233]

**Comment by mcharg** [comment]
@jlouis-onrr Here's a layout we can't do with the current setup to consider when reworking this.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/f6d78737-88ff-4d23-9ae2-5bba97da4cfd)

**Comment by mcharg** [comment]
@jlouis-onrr I updated the contacts layout so that we don't have cards within a card.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/668d41b6-2b66-400b-aa2f-565d744b1b36)

**Comment by mcharg** [comment]
Fixed.
