### ISSUE TITLE
Add ability to use reusable components on a tab and vice versa

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1235]
I wanted to use the table I created on the Statutes page on the Compliance Authorities tab of the Compliance tab, but there's no way to do that from within a tab.  Also can't go the other way because you would have to pick the whole tab component.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/9ec0c0a4-539b-4d05-ad29-70574a7da89a)

Statutes wireframe: https://qmcq5k.axshare.com/#id=lef7h9&p=statutes
Compliance page wireframe: https://qmcq5k.axshare.com/#id=wxa2eb&p=compliance

**Comment by Maroyafaied** [comment]
revamp should fix this @mcharg please check and close if it's fixed.

**Comment by mcharg** [comment]
For this particular instance, it would work to create the table as a collection and then use the collection in two places.

**Comment by mcharg** [comment]
Here, I want the report electronically component on the File Reports tab, but I can only put it below the tabs.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/19d656fc-346f-432f-ad6f-019dbdc8e85e)
