### ISSUE TITLE
Create an example to have a card with two columns of content

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1237]
Example: 
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/77328a01-c492-48e2-a19f-a7a54607cefa)

We want to be able to lay it out something like this with the courier payment in the right column:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/e9a617c0-b017-4970-a33d-c6ca5341055d)

**Comment by mcharg** [comment]
Another example.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/409cd311-672c-41d1-b066-f4bfce569817)

**Comment by Maroyafaied** [comment]
@jlouis-onrr will create examples to do this through editor js

**Comment by mcharg** [comment]
@jlouis-onrr This is working well.  I applied it to the Report Electronically component and the office locations page.
