### ISSUE TITLE
Page: Office Locations

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1238]
https://dev-onrr-frontend.app.cloud.gov/about/office-locations
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/24
https://qmcq5k.axshare.com/#id=56s5ve&p=office_locations

**Comment by mcharg** [comment]
@Maroyafaied Can you review?  I think we can close this one now that we have the single spacing in the addresses.
https://dev-onrr-frontend.app.cloud.gov/about/office-locations

**Comment by Maroyafaied** [comment]
@mcharg looks good!
