### ISSUE TITLE
November 21 IBMP Pirces

### ISSUE THREAD

**Issue by damionschulte** [ONRR/onrr.gov-site#1240]
All I have updated the ONNR.gov spreadsheet with the November 21 IBMP prices.  Can you please have them ready to publish?  Thank you.

@sudarr

**Comment by lpgoldstein** [comment]
@damionschulte http://2017onrr/valuation/IndianOilIBMP.htm This is ready for your review - sorry for the delay - your issue was buried in a ton of new issues.

**Comment by damionschulte** [comment]
These look perfect!  Thank you so much.

From: lpgoldstein ***@***.***>
Sent: Tuesday, December 7, 2021 1:53 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] November 21 IBMP Pirces (Issue #1240)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@damionschulte<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdamionschulte&data=04%7C01%7Cdamion.schulte%40onrr.gov%7C8425176159f74e8e18ab08d9b9c39b26%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637745072044433775%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vcS2%2F%2FQcGtb5%2Bk1OBTrK%2FL5j5Ed72w6ra0HvmX1s4Ss%3D&reserved=0> http://2017onrr/valuation/IndianOilIBMP.htm This is ready for your review - sorry for the delay - your issue was buried in a ton of new issues.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1240%23issuecomment-988255729&data=04%7C01%7Cdamion.schulte%40onrr.gov%7C8425176159f74e8e18ab08d9b9c39b26%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637745072044433775%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=edPPRWbs%2BDTVcmW2M3684JX5n6X7v6qimWl6vS7XEQI%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAO4AEPLBG4LNPNJU6OSXY5DUPZX25ANCNFSM5JRU3ONQ&data=04%7C01%7Cdamion.schulte%40onrr.gov%7C8425176159f74e8e18ab08d9b9c39b26%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637745072044433775%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WpeF%2B%2BOXUhGjeOrPeGeSvWrkXPDJ2lu%2FMYgSu6CJGuQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdamion.schulte%40onrr.gov%7C8425176159f74e8e18ab08d9b9c39b26%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637745072044433775%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jM7imnCF0YEDm5Wh2VW5F4auEcDBu4%2F97NVRxoAC3m8%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdamion.schulte%40onrr.gov%7C8425176159f74e8e18ab08d9b9c39b26%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637745072044433775%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=g3LjMcpzKgu0EezCpwHRinyOiEKFGftmCRFZ6cdlo64%3D&reserved=0>.

**Comment by lpgoldstein** [comment]
@damionschulte It's live!
