### ISSUE TITLE
Inconsistent bullet formatting

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1242]
If you copy and paste text already formatted as bullets, you get normal spacing between bullets, but if you try to create them within the CMS each bullet is treated as a separate component and they end up spaced out too far.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/9f54fc7c-c1a4-4091-8837-f021ee89fd89)

**Comment by Maroyafaied** [comment]
@jlouis-onrr Review docs of extension and give instructions how to fix it.
