### ISSUE TITLE
Page: About ONRR home

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1244]
https://qmcq5k.axshare.com/#id=vsgcdx&p=about_onrr

**Comment by mcharg** [comment]
Jerome has most of this page in, we just need a cleaner diagram and a compliant pdf.

**Comment by mcharg** [comment]
Page in dev: https://dev-onrr-frontend.app.cloud.gov/about

**Comment by mcharg** [comment]
Added alt text.

**Comment by cthomasONRR** [comment]
@mcharg Looks good. Approved.
