### ISSUE TITLE
Request 508 compliant version of strategic plan objectives

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1245]
It's on the About ONRR homepage and I asked Nichelle for a compliant version and she didn't respond.
https://dev-onrr-cms.app.cloud.gov/assets/28df066e-f610-48f4-a3e8-605b202148b2

**Comment by mcharg** [comment]
I sent Nichelle another email about this.

**Comment by mcharg** [comment]
Nichelle said the plan is being redone and expects to have a new doc in January.

**Comment by mcharg** [comment]
Nichelle said David is working on a new version of the doc.  They are getting resistance to using Word, so I suggested they try using PPT.  I gave them the renewables snapshot as an example.

**Comment by mcharg** [comment]
Dave sent a version with errors and asked for help fixing the last few, so @jkwonatx is going to take a look.

**Comment by mcharg** [comment]
Dave gave us permission to post this as a PPT instead of a PDF.

**Comment by jkwonatx** [comment]
Demonstrated how Dave and his team could fix the accessibility issues they've identified -- how to replace the diagram elements with images and add to the images the alt text that describe the diagram; and how to add metadata .

**Comment by jkwonatx** [comment]
I read the draft of Getting Beyond Auto Checks and examined the solution for the ONRR external org chart. Which got me wondering: 

Yesterday I suggested to Dave to replace the diagram with an image file and add alt text to that image, as an easy solution. After reading about the two solutions that Sid proposed, I thought about whether that solution would make the content actually accessible. 

I think it would, given how the diagrams aren't necessarily the main focus in the strategic plan. The main focus is the body text, and the diagrams are there to aid in communicating the article to the reader. So I still think the image file + alt text solution is apt.  And that the alt text can be a descriptive summary of the diagram. 

But I wonder if there should also be a link to the actual diagram chart that has the detailed description of the chart, such as the one in the ONRR org chart, which communicates both layers of information: 

1. The structure of the organization that conveys the relative position of each role/individual and 
2. The detailed information about that individual within each of the boxes.

**Comment by mcharg** [comment]
Received the accessible doc from Dave. Just confirming whether it's the one-pager or full plan that should go on the About page.
