### ISSUE TITLE
Update December Indian Index Zone Prices on onrr.gov

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#1247]
Please update the Indian Index Zone prices for December on ONRR.gov. The "Data for ONRR.gov" spreadsheet has been updated with the newest prices.

@sudarr

**Comment by lpgoldstein** [comment]
@boices This is ready for your review: http://2017onrr/valuation/allzones.htm

**Comment by boices** [comment]
That looks perfect--thank you!

**Comment by lpgoldstein** [comment]
@boices This is live!
