### ISSUE TITLE
Remove from onrr.gov

### ISSUE THREAD

**Issue by cmathers1** [ONRR/onrr.gov-site#1249]
Good morning, 

Please remove from onrr.gov. Thank you!

[950203.pdf](https://github.com/ONRR/onrr.gov-site/files/7670019/950203.pdf)

**Comment by cthomasONRR** [comment]
@cmathers1 

Thanks! This document is now removed.

Here is a list of the 11 remaining documents. 1 seems to be a duplicate (Keepwhole Gas Processing Contracts), so really only 10 documents left!
![image](https://user-images.githubusercontent.com/72526208/145079509-b2f56809-eac2-4335-b19d-901d584c1acb.png)
