### ISSUE TITLE
request for notice on home page

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#125]
Description: Could we have the following notification put on the front page of ONRR.gov?
 
ONRR would like to let the mineral owners know that we are still operating, processing 2014’s and payments, as well as processing distributions. Our outreach group is also answering phones so if you have any questions or concerns, please call us. The contact numbers for our offices are below.

**Comment by jennmalcolm** [comment]
Check with the requester, but it seems like this would be a better place for this announcement since it applies to allottees.

https://www.onrr.gov/IndianServices/index.htm

**Comment by lpgoldstein** [comment]
Clarified the message and they want the message on the homepage and on the Indian Service Center homepage too. Appropriate contact information below. 

https://www.onrr.gov/IndianServices/indian-energy-service-center.htm#
![image](https://user-images.githubusercontent.com/39419003/79500874-2a372f80-7ffb-11ea-8670-9ea1af917d5e.png)

**Comment by jennmalcolm** [comment]
So, now they want those contact info to appear on the home page too? That doesn't make sense, but perhaps we could link to that page from the home page with the contact info.

**Comment by lpgoldstein** [comment]
Yep! That is a better idea. There isn't enough space on the homepage for all of the message.
