### ISSUE TITLE
Page: Unpaid Debt

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1251]
https://qmcq5k.axshare.com/#id=xmti8p&p=unpaid_debt

**Comment by cthomasONRR** [comment]
@mcharg Shouldn't the DRL pdf be pointing to /reporter-letters/filename.pdf and not /document/filename.pdf?
![image](https://user-images.githubusercontent.com/72526208/167863423-158550c2-17a8-4881-b44f-40b463c4778d.png)

![image](https://user-images.githubusercontent.com/72526208/167863318-7c98abba-5fcc-45a0-870a-0a4500356235.png)

**Comment by mcharg** [comment]
@cthomasONRR Fixed url

**Comment by cthomasONRR** [comment]
@mcharg Approved :)
