### ISSUE TITLE
Add NYMEX page content to CMS

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1252]

**Comment by Maroyafaied** [comment]
@Maroyafaied review

**Comment by mcharg** [comment]
This looks good to me.  @mojobnichols I added titles for each of the tabs, so you might want to pull the changes into your local build.

**Comment by Maroyafaied** [comment]
@mcharg can we make the "crude oil market centers" tab next to the NYMEX Oil tab since they relate to each other? We should also add content to the crude oil market center tab before demo if we could.

**Comment by mcharg** [comment]
@Maroyafaied They will be next to each other, but we decided to move NYMEX first for the demo.  I can move it for the demo, if you think it's valuable.

**Comment by Maroyafaied** [comment]
@mcharg That's fine for the demo.

**Comment by mcharg** [comment]
@Maroyafaied I created #1318 to add the content and move the tab.

**Comment by Maroyafaied** [comment]
@mcharg I'm good to close this since you created issue #1318.

**Comment by mcharg** [comment]
@Maroyafaied I added the note about prices being in $ per bbl, if you want to review again.
https://dev-onrr-frontend.app.cloud.gov/references/valuation?tab=pricing

**Comment by Maroyafaied** [comment]
@mcharg looks good
