### ISSUE TITLE
Tab: Valuation & Pricing > How Valuation Works

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1254]

**Comment by mcharg** [comment]
Moving this one to the product backlog, since we have it far enough for demo and are waiting on the ability to add alt text to images.
https://dev-onrr-frontend.app.cloud.gov/references/valuation?tab=how-valuation-works

**Comment by mcharg** [comment]
I also want to play with the width of the images once we get the layout stuff.

**Comment by mcharg** [comment]
Resized images.
https://dev-onrr-frontend.app.cloud.gov/references/valuation

**Comment by mcharg** [comment]
Added alt text.  @lpgoldstein This page is now ready for ODDD Approval.

**Comment by lpgoldstein** [comment]
@mcharg How do I check the alt text?

**Comment by mcharg** [comment]
@lpgoldstein If you go into where the image is in the CMS, it should display below the image.
![image](https://user-images.githubusercontent.com/38465926/155393230-4690cad5-f167-4e47-bfdc-55db4991cd70.png)
