### ISSUE TITLE
Add way to have a second link for reporter letters for the accessible version

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1256]
We only have one right now, but could end up with others in the future.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/8205e4f3-4a08-492a-8af2-4857fd7ec914)

**Comment by Maroyafaied** [comment]
@jlouis-onrr  is this ready for review?

**Comment by Maroyafaied** [comment]
@Maroyafaied review

**Comment by Maroyafaied** [comment]
I've reviewed and it looks great.
