### ISSUE TITLE
Images cut off on the side

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1258]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/64d57eb8-96fb-4d86-99a5-337167c345f3)

**Comment by Maroyafaied** [comment]
@jlouis-onrr Figure out requirements for images and threshold size

**Comment by mcharg** [comment]
@Maroyafaied Did we want to have @jlouis-onrr do this before the demo, so the images on How Valuation Works aren't cut off?

**Comment by Maroyafaied** [comment]
@mcharg Yes, it would be great if @jlouis-onrr can get the images not to cut off before our meeting next Tuesday.

**Comment by mcharg** [comment]
Looks good.
