### ISSUE TITLE
Plan a card sort for onrr.gov

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#126]
Annie read an article about conducting a card sort using Trello and I think we could do it using Github Projects where each card is an issue and participants create categories using the column in the project.

First step is identifying cards to include in the sort.  It should be a mix of things we know people look for and things we know are hard to find and include good coverage of the site's content.

**Comment by mcharg** [comment]
Here's a link to a test card sort in the research repo:
https://github.com/ONRR/research/projects/1

**Comment by mcharg** [comment]
Here's a draft of instructions for participants.
https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B22988B47-0198-4BC9-8767-8A79D86069CE%7D&file=Card%20Sort%20Instructions.docx&action=default&mobileredirect=true

@lpgoldstein @Maroyafaied @persam2 @alenahuang Any of you want to test them out?

**Comment by Maroyafaied** [comment]
@mcharg yes, I'll test it out. Thanks
