### ISSUE TITLE
Reporter Training Agenda & Registration

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1267]
Please update the Reporter Training page to add the below training dates at the following link - https://www.onrr.gov/reportpay/training/index.htm

Training Dates
Oil and Gas Reporter Training, January 10-14, 2022

Please also post the attached Agenda and Registration Information just below the date
[Reporter Training Agenda and Registration Information.pdf](https://github.com/ONRR/onrr.gov-site/files/7688491/Reporter.Training.Agenda.and.Registration.Information.pdf)
.

**Comment by cthomasONRR** [comment]
@bowlenj Are you sure you mean January 2021? That was almost a year ago....

**Comment by bowlenj** [comment]
This looks great!  Thank you so much 🙂

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, December 9, 2021 2:30 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Reporter Training Agenda & Registration (Issue #1267)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C4e22a4d351bd4917f0ad08d9bb5b2aca%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637746822498951396%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xD%2FnJO4BBYrgNPBOFNKzaYq1dTkQrrciLUG7W7xKHOY%3D&reserved=0>
I added your changes to the dev site: http://2017onrr/reportpay/training/index.htm
Please review and let me know if you approve for the changes to go live.

Thanks,
Christine

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1267%23issuecomment-990283209&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C4e22a4d351bd4917f0ad08d9bb5b2aca%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637746822498951396%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ppf%2BdGZQVqhmEM9VU3WfvUjL1ATDdqnXHJwurYVt8ss%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VHZAWCQIQURGQ3WFPRTUQENXZANCNFSM5JXPVU2Q&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C4e22a4d351bd4917f0ad08d9bb5b2aca%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637746822498961359%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ucOk9rAFYBrFZPhvxUI0hmMBSpNNf7MlNu4Dp4Z3xJw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C4e22a4d351bd4917f0ad08d9bb5b2aca%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637746822498961359%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=i%2FuxlSLhgF7WdrkKImNuDjniUdgXeYhSynydZOJ5EFA%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C4e22a4d351bd4917f0ad08d9bb5b2aca%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637746822498971315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=f9rTtFot7fMv7BgRTWDakB69%2FhSU%2BSOm2Dy8c2%2B96E4%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
No worries!!!! It's been a long day!
I just moved the changes to the live site, and it is now live. Remember you might need to click 'Ctel+F5' to refresh the page.
https://www.onrr.gov/reportpay/training/index.htm

**Comment by cthomasONRR** [comment]
@daniel-coleman-1 Here is another new PDF for the site map.
