### ISSUE TITLE
Update Sitemap with compiled MPRH

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/onrr.gov-site#1268]
https://www.onrr.gov/reportpay/Handbooks/index.htm

**Comment by daniel-coleman-1** [comment]
@cthomasONRR  Updated in 3.7.2
https://92ix0j.axshare.com

**Comment by daniel-coleman-1** [comment]
@lpgoldstein

**Comment by lpgoldstein** [comment]
@daniel-coleman-1 Looks good!
