### ISSUE TITLE
New ONRR Anti-Harassment Page

### ISSUE THREAD

**Issue by NRONRR** [ONRR/onrr.gov-site#127]
Hello, 
We have been directed to create a page on ONRR.gov for ONRR's Anti-Harassment program.  It should have the same content as what's on this ONRResource page:  https://onrresource/ONRR-Anti-Harassment/

There will be more content coming, but this is most of it.  Please do not include the last item on the main page as I don't yet have that:  
__*WES Results 2017 compared to 2019 Federal Employee Viewpoint Survey, Agency Specific Inquiry (FEVS/ASI) (Most likely a similar graph)
*ONRR’s results are included within the Office of Secretary responses._

Also, please do not include the intake form information.  I don't think that is supposed to be included.  Please contact me if you have questions.

**Comment by jennmalcolm** [comment]
@NRONRR should this page go under About and be on the main navigation under about? Is there a deadline for this page to be live or is it just ASAP?

**Comment by NRONRR** [comment]
Hi Jennifer,

Please load this as soon as possible.  If there is a way for me to view prior to go-live, I’d appreciate it.

Yes, let’s load this off our “About” menu.

Thanks,

Nichelle Rogers
Communication, Performance, and Change Management Supervisor
Office of Natural Resources Revenue
Phone:  (303) 231-3755
Mobile:  (720) 202-8692
Fax:  (303) 231-3908
What have you found on ONRResource<http://onrresource/> lately?

**Comment by jennmalcolm** [comment]
@NRONRR you can take a look at the page in dev: http://2017onrr/About/anti-harassment.htm

I still need to add it to the navigation--which I will work on tomorrow because I need to make some other changes to the navigation as well. Let me know if you want any changes to this page. Thanks.

**Comment by jennmalcolm** [comment]
The page is live and it should be on the navigation menu on all pages.

**Comment by NRONRR** [comment]
Thank you so much Jennifer!  Appreciate you doing this!

Thanks,

Nichelle Rogers
Communication, Performance, and Change Management Supervisor
Office of Natural Resources Revenue
Phone:  (303) 231-3755
Mobile:  (720) 202-8692
Fax:  (303) 231-3908
What have you found on ONRResource<http://onrresource/> lately?
