### ISSUE TITLE
Create language about MLRS for troubleshooting guide

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1275]
LR2000 is changing to MLRS in February, so we'll need language to help people with that.

**Comment by mcharg** [comment]
@bowlenj Can you help with this?

**Comment by bowlenj** [comment]
I just replied to an email now regarding the conversion.  I'm happy to help with any wording, let me know if you have questions or need additional information.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: mcharg ***@***.***>
Sent: Tuesday, June 7, 2022 10:10 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Create language about MLRS for troubleshooting guide (Issue #1275)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C6092d058473340c2012f08da48a0303a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637902150086129091%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kYXSITt2QU28l7dGLzwPip06WQLozO3POVBc58OeZLs%3D&reserved=0> Can you help with this?

**Comment by mcharg** [comment]
@codyeckstein Do you think we can get this done in the next 2 weeks?

**Comment by mcharg** [comment]
I scheduled a meeting for next week.

**Comment by cthomasONRR** [comment]
I added MLRS language in the troubleshooting guide in issue #2051 

Language:
"LR2000 is no longer updated by BLM. You can see the updated [Serial Register Page](https://reports.blm.gov/reports/MLRS/) and find additional information in [MLRS](https://mlrs.blm.gov/s/)."

**Comment by mcharg** [comment]
@cthomasONRR Found another instance of LR2000 in the troubleshooting guide.
https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?panel=i-need-contract-or-lease-expiration%2Ftermination-information

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/f79974db-d898-4143-b76a-c0dff369a741)

**Comment by mcharg** [comment]
Also:
https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?panel=i-received-a-bill-for-a-lease-thats-not-mine
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/12b033cb-86f7-409d-99c1-147b64c545ed)

**Comment by bowlenj** [comment]
This looks great!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: mcharg ***@***.***>
Sent: Monday, July 11, 2022 11:24 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Create language about MLRS for troubleshooting guide (Issue #1275)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@cthomasONRR<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FcthomasONRR&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cd822daad591b463b089508da63624667%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637931570989488254%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aoloSsVaJoBsjJ0sTnlCkWrrOPUQ%2FHPGxt2K7FHd87s%3D&reserved=0> Found another instance of LR2000 in the troubleshooting guide.
https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?panel=i-need-contract-or-lease-expiration%2Ftermination-information<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Fabout%2Fcontact%2Flease-agreement-contacts%3Fpanel%3Di-need-contract-or-lease-expiration%252Ftermination-information&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cd822daad591b463b089508da63624667%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637931570989488254%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cTDMUwzslCX4td5czm3pS%2BWnHcvYacL0HRaZad%2FYBzg%3D&reserved=0>

[image.png]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcamo.githubusercontent.com%2Fd893335399558f70268c4461f380d4122c13ee4647d5254ec07f0c93fe05378d%2F68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563353839666535653138303632303831326561323261612f66373939373464622d643839382d343134332d623736612d633064666633363961373431&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cd822daad591b463b089508da63624667%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637931570989488254%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oEIknAmwb%2FnJxibh%2FwFeWCRc6MkUL0JQQAEDT5CzMBQ%3D&reserved=0>

**Comment by cthomasONRR** [comment]
@mcharg I got these updated. I'm going through to see if there are any other instances that need to be updated. Thanks.

**Comment by mcharg** [comment]
@cthomasONRR Looks good.
