### ISSUE TITLE
Decide what errors to add to troubleshooting guide

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1276]
Add errors like my lease is not producing, sales date must be prior to termination/expiration.  Go to Lease & Agreement contacts.

**Comment by mcharg** [comment]
9630 Lease is not producing – Now fatal in eCommerce
9640 Agreement Number not related to reported lease

For both, send to lease & agreement contacts.

**Comment by mcharg** [comment]
@codyeckstein I added the error to both the leases & agreements and oil & gas royalty pages.  I also added the error number to the nonreporting status accordion.  Let me know if you have any feedback.

https://qmcq5k.axshare.com/#id=q4kw41&p=leases___agreements
https://qmcq5k.axshare.com/#id=its4or&p=oil___gas_royalty

**Comment by codyeckstein** [comment]
Looks great! @mcharg
