### ISSUE TITLE
Replace Docs on onrr.gov

### ISSUE THREAD

**Issue by cmathers1** [ONRR/onrr.gov-site#1278]
Good afternoon, 

Please replace docs on onrr.gov with the attached remediated documents.  Please let me know if you have any questions. 

Thank you!
[20161005.pdf](https://github.com/ONRR/onrr.gov-site/files/7695278/20161005.pdf)
[991201.pdf](https://github.com/ONRR/onrr.gov-site/files/7695279/991201.pdf)
[970130a.pdf](https://github.com/ONRR/onrr.gov-site/files/7695280/970130a.pdf)
[960311.pdf](https://github.com/ONRR/onrr.gov-site/files/7695281/960311.pdf)
[941104.pdf](https://github.com/ONRR/onrr.gov-site/files/7695282/941104.pdf)
[20040922.pdf](https://github.com/ONRR/onrr.gov-site/files/7695283/20040922.pdf)
[Dear Reporter Letter - Keepwhole Gas Processing Contracts.pdf](https://github.com/ONRR/onrr.gov-site/files/7695287/Dear.Reporter.Letter.-.Keepwhole.Gas.Processing.Contracts.pdf)
[981218.pdf](https://github.com/ONRR/onrr.gov-site/files/7695289/981218.pdf)
[981124a.pdf](https://github.com/ONRR/onrr.gov-site/files/7695290/981124a.pdf)
[970220.pdf](https://github.com/ONRR/onrr.gov-site/files/7695291/970220.pdf)

**Comment by cthomasONRR** [comment]
- [ ] 20161005.pdf
- [ ] 991201.pdf
- [ ] 970130a.pdf
- [ ] 960311.pdf
- [ ] 941104.pdf
- [ ] 20040922.pdf
- [ ] Dear Reporter Letter - Keepwhole Gas Processing Contracts.pdf
- [ ] 981218.pdf
- [ ] 981124a.pdf
- [ ] 970220.pdf

@cmathers1 Thank you so much for volunteering your time to help RV complete their Phase 3 tasks. Thanks to you, we are now officially complete with Phase 3 of the 508 project!!!!

**Comment by cmathers1** [comment]
Thank you, Christine!  Have a great weekend!

Sincerely,

Christina

Christina Mathers
Staff Assistant
Director/Deputy Director's Office
Office of Natural Resources Revenue
6th Avenue and Kipling Street Bldg. 85
Denver, Colorado 80225
Phone:  303-231-3429
Cell: 303-503-1315
________________________________
From: Christine Thomas ***@***.***>
Sent: Friday, December 10, 2021 1:47 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Mathers, Christina ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Replace Docs on onrr.gov (Issue #1278)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



  *    20161005.pdf
  *    991201.pdf
  *    970130a.pdf
  *    960311.pdf
  *    941104.pdf
  *    20040922.pdf
  *    Dear Reporter Letter - Keepwhole Gas Processing Contracts.pdf
  *    981218.pdf
  *    981124a.pdf
  *    970220.pdf

@cmathers1<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcmathers1&data=04%7C01%7Cchristina.mathers%40onrr.gov%7Cf8298fe7c595463d478a08d9bc1e5157%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637747660667064228%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hTpX8H0ZZsEdFGrWSDERcwDS2bj8IWodCaNUcf6cW6E%3D&reserved=0> Thank you so much for volunteering your time to help RV complete their Phase 3 tasks. Thanks to you, we are now officially complete with Phase 3 of the 508 project!!!!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1278%23issuecomment-991283076&data=04%7C01%7Cchristina.mathers%40onrr.gov%7Cf8298fe7c595463d478a08d9bc1e5157%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637747660667064228%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=q%2BGdJrG8KL2Cz8%2BbhUes7udxYL%2FnEXwyC76mABsetzA%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAU5GF7QAAA3QADCZVG6LCS3UQJROBANCNFSM5JZ7DLLA&data=04%7C01%7Cchristina.mathers%40onrr.gov%7Cf8298fe7c595463d478a08d9bc1e5157%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637747660667074191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1B0c82ogRtK4DMZ5sLCoGKSKnQznWjVR2S5DzZb9ezA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cchristina.mathers%40onrr.gov%7Cf8298fe7c595463d478a08d9bc1e5157%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637747660667074191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=J1Tsnxheq93Lf8V7CoQw7CQ249xFFlGCLPQKdyHLArQ%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cchristina.mathers%40onrr.gov%7Cf8298fe7c595463d478a08d9bc1e5157%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637747660667084139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UlrhGAzmgub6XFepO7Vf2qbsuTVq0zvwMB%2FHT8tsYdA%3D&reserved=0>.
