### ISSUE TITLE
Add archived press releases and fix any titles or descriptions with symbols

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1280]

**Comment by mcharg** [comment]
@daniel-coleman-1 This folder has the spreadsheet with all the press releases and a sub-folder with all the press release documents. https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Collections/Press%20Releases?csf=1&web=1&e=t4bjLy

**Comment by daniel-coleman-1** [comment]
The drop down by year menu isn't providing years in descending order:

![Screenshot 2021-12-20 131724](https://user-images.githubusercontent.com/83892362/146827531-1c80ee53-9d99-46cf-942b-1fc891549455.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 Please create a new issue for @jlouis-onrr to fix the year menu.

**Comment by daniel-coleman-1** [comment]
We have three titles with symbols that aren't presenting correctly, looks like mdashes and single quotes:
![Screenshot 2021-12-21 110142](https://user-images.githubusercontent.com/83892362/146977313-0913f3ca-7360-40c7-b564-e774882682ef.png)

**Comment by daniel-coleman-1** [comment]
@mcharg and @jlouis-onrr will it break anything if I add commas to dollar value totals in titles?
![Screenshot 2021-12-21 111228](https://user-images.githubusercontent.com/83892362/146978555-65c21dd8-66af-4805-a9ad-9987314b5a99.png)

**Comment by mcharg** [comment]
@Baymatt will be reviewing to make sure the correct document is added to each release.

**Comment by mcharg** [comment]
@daniel-coleman-1 There's a new press release from Nov 23 that needs to be added to the spreadsheet and CMS. https://www.onrr.gov/about/NewsReleases.htm

**Comment by mcharg** [comment]
@jlouis-onrr Did you see Daniel's question above about commas?

**Comment by mcharg** [comment]
@daniel-coleman-1 This one has a markdown formatted link that probably needs to use the link component in the editor.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/b342be2a-a555-4d95-8556-93c5f806b6d7)

**Comment by daniel-coleman-1** [comment]
![Screenshot 2021-12-22 122639](https://user-images.githubusercontent.com/83892362/147145178-a8d71453-bf81-4d9b-8263-545e69185313.png)

I've replaced the apostrophes with quotation marks and mdashes with regular dashes with a space on each side, and that works in titles.  We'll still need apostrophes for possessives, though:
![Screenshot 2021-12-22 122844](https://user-images.githubusercontent.com/83892362/147145370-3fd0b4af-287a-4806-bbc1-d47e7a9930a8.png)

**Comment by Baymatt** [comment]
Looked through the press releases and fixed any pdfs that were incorrect. The press release for March 27th, 2014 does still have the strange diamond with a question mark but it seems like that has already been noted.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 There's one current press releases missing, @mcharg mentioned above in the comments from November 23rd that needs to be added to the cms and the spreadsheet. ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/fe30fd98-ffd6-4276-8ad5-10991c147f3c)!. This is it on the on the live site currently. ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/11492909-7e54-4873-b3e9-68a18dce88ff)

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 the links look good. Please add Nov 23rd  press release to spreadsheet and cms, make all title cases consistent, remove the NRRD link from the press release below (1st pic), and remove the periods or rename the title of the 2nd press release below (2nd pic), and remove the space in the 3rd pic to get rid of that symbol.  
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/a8d66e0d-deeb-4b87-9ce2-!08f552a3988f)
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/7c2f5214-6efd-4e3a-818e-4988cf669abb)
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/1f9566c9-b42b-4514-b074-340cf91f5052)

**Comment by daniel-coleman-1** [comment]
@Maroyafaied title case is consistent throughout.

Link removed:
![Screenshot 2021-12-28 123407](https://user-images.githubusercontent.com/83892362/147601585-1ee1b7ef-8eec-4c6a-a2bb-dc88876f6df9.png)

Apostrophe corrected:
![Screenshot 2021-12-28 123338](https://user-images.githubusercontent.com/83892362/147601588-afb30a4b-5342-41d7-9542-6610bcd97eb5.png)

Rephrased to match structure of other titles:
![Screenshot 2021-12-28 123251](https://user-images.githubusercontent.com/83892362/147601595-70924a93-ed8c-49f6-9b27-eb98d1c12196.png)

and I've added the new press release to the site twice, once as a link and once with the document uploaded. The delete button is not available yet, so I moved the link doc to "Draft" so only one appears on the site.  Updated the tracking spreadsheet as well (just once).  For now the new press release showing in the CMS but at the bottom of the page, below previously published:
![Screenshot 2021-12-28 124954](https://user-images.githubusercontent.com/83892362/147601979-dd61b5ce-c458-472d-b1b4-f0646f7cb05e.png)

**Comment by Maroyafaied** [comment]
@daniel-coleman-1  I've reviewed , here are my comments.

 These need to be fixed
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/df977ec8-e38a-4d64-aa89-22c40252bd35)![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/45e6ee7f-6f26-46d9-9d7f-72b20a68757a)

Add space
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/2ed7ae7c-f54d-4fd6-bea9-dd2a8f77a8f8)

Should this have an apostrophe like the other one?![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/8bd3c784-cdb7-45a0-a0d3-ccad7441cc1e)

Add dollar sign ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/c45eea06-f386-4712-a068-a8320180092b)

Is there a reason why some "to" is capitalized and others not?
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/588ab763-19fc-4f4c-80ea-6d7c84d83261) 
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/e12cf838-deda-46f3-be67-f07a65779ecf)
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/4b61ca6d-5a3a-4402-9c31-cfc219b546fa)
 ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/528bc14a-4f3e-4541-af20-e57cd740cb67)

**Comment by daniel-coleman-1** [comment]
@maroya Corrected the first three, thanks for catching.  Also, "to" should always be uncapitalized in titles, so I fixed those as well.

for March 30, we don't need an apostrophe after States because it's plural, not possessive
for Feb 11, the 1 Billion is referring to billions of barrels of oil, not a dollar amount, so no dollar sign needed

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 there's a few more I found that need to be fixed, please fix and review all of them thoroughly. 

![image](https://user-images.githubusercontent.com/40175688/147615535-f3ce926b-810f-4c3d-97c9-3920d9161945.png)

![image](https://user-images.githubusercontent.com/40175688/147615871-cb8d2b59-e941-4d4a-ae1c-e05408b1dedc.png)

![image](https://user-images.githubusercontent.com/40175688/147615777-9c2a472e-eea4-42f2-a33d-63e5b80a1d52.png)

**Comment by daniel-coleman-1** [comment]
I think we're good to close this one
