### ISSUE TITLE
Press release date order issues

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/onrr.gov-site#1291]
Set Archived Press Release drop down menu to descending year order
Right now they're displaying like this:
![Screenshot 2021-12-21 083248](https://user-images.githubusercontent.com/83892362/146956305-2f6f65c9-fdd9-4d82-8455-0824fffd721a.png)

**Comment by mcharg** [comment]
@jlouis-onrr The most recent date should also display at the top instead of the bottom.

**Comment by Baymatt** [comment]
When updating the pdf for the press releases in the CMS, the newly updated one gets pushed to the bottom of the page. ![Screen Shot 2021-12-21 at 12.35.06 PM.png](https://images.zenhubusercontent.com/5f584cee7f8acc2201148806/a34cf19f-46cd-4ab3-acb4-910595f35ed1)

**Comment by jlouis-onrr** [comment]
#1158 fixes this
