### ISSUE TITLE
Determine whether we can swap out double quotes for single quotes in press release titles

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1294]
Examples:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/f72b412a-a6d3-484a-8cdf-c7a25759aa8b)

**Comment by daniel-coleman-1** [comment]
@mentastc I did some research, it looks like Knowing or Willful is a specific legal term, in which case it is correct to refer to the term with full quotes and incorrect to refer to the term with a single quote, unless that single quote is contained inside a full quotation.
I'm thinking 'Knowing or Willful' is incorrect and "Knowing or Willful" would be correct, including in titles.  What do you think?

**Comment by Maroyafaied** [comment]
@mentastc I'm closing this issue since @daniel-coleman-1 did the research and decided using full quotes is appropriate, also these press release are from 2013 but but please let us know if you disagree. Thanks
