### ISSUE TITLE
Add topics to reporter letters spreadsheet

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1298]
This will drive which ones show up on which references tab within the Reporting section.
https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Collections/Dear%20Reporter%20Letters/Dear%20Reporter%20Letters.xlsx?d=wd17d795b45f34b639c5728525d36fe04&csf=1&web=1&e=wV0tdM

**Comment by cthomasONRR** [comment]
@mcharg I added topic(s) for all reporter letters. I did my best to be consistent. In some situations, it was very hard to stay general (ex: should I put Federal Oil, Federal Gas -OR- Federal Leases), but put the more detailed commodity info when I had the specifics to do so.

**Comment by mcharg** [comment]
@cthomasONRR Looks great. Thank you!
