### ISSUE TITLE
Fix agency logos links on the Indian energy service center page.

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#130]
This issue came from the content audit. Clicking on the agency logos just takes you to the top of the page not to the actual agency page.

https://www.onrr.gov/IndianServices/indian-energy-service-center.htm#
![image](https://user-images.githubusercontent.com/40175688/79778999-da0be600-82f6-11ea-9f75-67b2f465e6f7.png)

**Comment by jennmalcolm** [comment]
This is ready in dev. Please review @Maroyafaied

**Comment by Maroyafaied** [comment]
@jennmalcolm it looks good.

**Comment by jennmalcolm** [comment]
changes live
