### ISSUE TITLE
Continue Rulemakings Pages Collection

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1300]
@cthomasONRR Do you want to help with this?

I'm going through each of the rulemakings pages and pulling abstracts and link titles, dates, and urls.  I'm hoping we can use this spreadsheet to build the pages automatically instead of manually.

https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Collections/Rulemakings/RulemakingsPagesCollection.xlsx?d=w9f16fedb910a400fac30a3d3da426b6b&csf=1&web=1&e=WNReQn

**Comment by cthomasONRR** [comment]
@mcharg I filled out the rest of the spreadsheet except for 6 entries (highlighted in yellow). These 6 have more complicated webpages (more narratives and links) so we might want to discuss a better method for these than putting them into this spreadsheet.

**Comment by mcharg** [comment]
@cthomasONRR Let's discuss the complicated ones with @jlouis-onrr in synch up tomorrow.

**Comment by cthomasONRR** [comment]
@mcharg I'm going to close this issue. Let me know if you feel that we need to reopen it.
