### ISSUE TITLE
Request to update ONRR's Federal Register Notices Page

### ISSUE THREAD

**Issue by ginger-johnson** [ONRR/onrr.gov-site#1302]
Good morning, 

I am requesting two updates to this page https://www.onrr.gov/Laws_R_D/FRNotices/index.htm  

Please add two new entries in chronological order.

For the first entry, please create it with November 18, 2021.
It should read as follows:
“86 FR 64523
Thursday, November 18, 2021
**Denver, CO** In accordance with the Paperwork Reduction Act of 1995, ONRR is proposing to renew an information collection request. OMB Control Number 1012-0002.

At the bottom of the entry, please add a hyperlink labeled as “View 86 FR 64253 document” with the link below
https://www.federalregister.gov/documents/2021/11/18/2021-24341/agency-information-collection-activities-indian-oil-and-gas-valuation 

Please add a second entry with today’s date (December 27, 2021).

The second entry should read as follows: 
“86 FR 73314
Monday, December 27, 2021
**Denver, CO** ONRR provides two types of accounting and auditing relief for Federal onshore or Outer Continental Shelf lease production from marginal properties. This Notice provides the public each State’s decision on whether to participate in marginal property relief.”

At the bottom of the entry, please add a hyperlink labeled as “View 86 FR 73314 document” with the link below
https://www.federalregister.gov/documents/2021/12/27/2021-28045/states-decisions-on-participating-in-accounting-and-auditing-relief-for-federal-oil-and-gas-marginal

Please let me know if you have any questions. 

Ginger Johnson

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 thanks for taking this issue, please make these updates to the cms as well if needed. Thanks

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 disregard my comment about the cms , I confused this with the press releases.

**Comment by daniel-coleman-1** [comment]
@ginger-johnson your requested changes have been implemented in the dev site:
http://2017onrr/Laws_R_D/FRNotices/index.htm

with your approval I will push these changes live

**Comment by ginger-johnson** [comment]
The changes look great. I approve the changes to go live. Thank you!

**Comment by daniel-coleman-1** [comment]
Fantastic, we are live:
https://www.onrr.gov/Laws_R_D/FRNotices/index.htm

**Comment by mcharg** [comment]
@cthomasONRR Would these FRNs need to be added to ICR or rulemaking pages in the new site, since we'll no longer have a list of all FRNs?

**Comment by cthomasONRR** [comment]
@mcharg 

The first one (with 11/18/21 date) is an ICR and will go under the respective ICR page. Current site: https://www.onrr.gov/Laws_R_D/FRNotices/FRInfColl.htm. Future site: https://qmcq5k.axshare.com/#id=tqf3j1&p=information_collection_requests.

The second one (with 12/27/21 date) is the annual marginal property FRN. Current site: https://www.onrr.gov/Laws_R_D/FRNotices/index.htm. Future site: https://qmcq5k.axshare.com/#id=kkqoxq&p=federal_register_notices.

Does that make sense?

**Comment by mcharg** [comment]
@cthomasONRR Makes sense.  Can you add the ICR one to the ICR spreadsheet?

The FRN one will need to be updated in the CMS, since that page is in there.  @daniel-coleman-1 Can you do that one?

**Comment by mcharg** [comment]
@lpgoldstein We should note in the content tracking sheet that the most recent FRN links on the FRNs page will change every year.

**Comment by cthomasONRR** [comment]
@mcharg setting up a new issue to update the ICR excel sheet, it is out of date.

**Comment by Maroyafaied** [comment]
Will close and create separate issues.
