### ISSUE TITLE
Request Updates to ONRR's Information Collection Page

### ISSUE THREAD

**Issue by ginger-johnson** [ONRR/onrr.gov-site#1303]
Good morning, 

I am requesting updates to this page https://www.onrr.gov/Laws_R_D/FRNotices/ICR0103.htm.

Under the Federal Register Publications heading, please add a bullet to the top of the list. The bullet should read as follows: “30-Day Agency Information Collection - (86 FR 64523--November 18, 2021)”

Please add this hyperlink to the language in the parenthesis: https://www.federalregister.gov/documents/2021/11/18/2021-24341/agency-information-collection-activities-indian-oil-and-gas-valuation

Please let me know if you have any questions. 

Ginger Johnson

**Comment by daniel-coleman-1** [comment]
@ginger-johnson your requested changes have been implemented in the dev site:
http://2017onrr/Laws_R_D/FRNotices/index.htm

with your approval I will push these changes live

**Comment by daniel-coleman-1** [comment]
@ginger-johnson the requested change has been implemented in dev:
http://2017onrr/Laws_R_D/FRNotices/ICR0103.htm

with your approval I will push these changes live

**Comment by ginger-johnson** [comment]
The changes look great. I approve the changes to go live. Thank you!

**Comment by daniel-coleman-1** [comment]
Fantastic, we are live:
https://www.onrr.gov/Laws_R_D/FRNotices/ICR0103.htm
