### ISSUE TITLE
Add 508 compliance study plan and findings to wiki

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1304]
@cthomasONRR can you add the plan and findings to wiki and link to them in the 508 compliance study blog post .

here's the link to [research repo ](https://github.com/ONRR/research/tree/master/onnr-dot-gov-research)

[Study plan](https://teams.microsoft.com/l/file/AAD04284-EFF2-45C7-8063-9D8EB069F5F4?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FUser%20Research%2FStudies%2F09_508_compliance%2F508%20stakeholder%20interview%20guide%20.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

[Study findings](https://teams.microsoft.com/l/file/EA017369-9735-4ACE-ACA1-DD745789A9C7?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=pptx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FUser%20Research%2FStudies%2F09_508_compliance%2F508%20Stakeholder%20Interview%20Findings%20.pptx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

**Comment by cthomasONRR** [comment]
This is complete. 

New folder and files are located here: https://github.com/ONRR/research/tree/master/onnr-dot-gov-research/09_508_Study

Dan's reference I used to create the new folder: https://github.community/t/add-a-folder/2304

Closing this issue.
