### ISSUE TITLE
Upload NYMEX files

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1309]
Add the rest of the NYMEX files.

**Comment by mcharg** [comment]
@Baymatt I cleaned up the formatting in all the files in Teams.  Working on uploading to the live site, so you can use the upload from url function.

**Comment by Baymatt** [comment]
Thank you, that'll definitely help to speed things up!

**Comment by mcharg** [comment]
@Baymatt The updated files are on the live site. I tested the import from url out with 2004, so you only need to do 2005-2010.

**Comment by mcharg** [comment]
@Baymatt The files all look like they're there. I'll create a separate issue to review the data.
