### ISSUE TITLE
Update ICR excel collections for CMS (current and discontinued)

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1311]
https://doimspp.sharepoint.com/:x:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7B0A9FA42E-3AF2-4CA8-8A9B-AC1991A6F368%7D&file=CurrentICRCollection.xlsx&action=default&mobileredirect=true

Need to update this spreadsheet with the recent ICR publications.

**Comment by cthomasONRR** [comment]
Link for discontinued ICRs: https://doimspp.sharepoint.com/:x:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7BA22FFB69-DAC4-4884-8439-C400E5A9AFC2%7D&file=DiscontinuedICRCollection.xlsx&action=default&mobileredirect=true

**Comment by cthomasONRR** [comment]
Folder housing collections: https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=hHcebS&cid=5837c964%2D7e25%2D4165%2Dbd63%2D6e7c0c1e4b99&RootFolder=%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR%2Egov%2FDesign%2FCollections&FolderCTID=0x01200044BDC74607AB0342BAC14F3B92EB1E28

**Comment by cthomasONRR** [comment]
@mcharg On the current live site and spreadsheet, only some of the current ICRs have links to the docket folders. ICRs 0004, 0008, 1010 have docket folder links. ICRs 0001, 0002, 0003, 0005, 0006, and 0009 do not have docket folder links. Want me to add those? It will take me a bit to make sure I have the correct docket and add them to the live site.

**Comment by mcharg** [comment]
@cthomasONRR I defer to you on whether they are needed.

**Comment by cthomasONRR** [comment]
I will work on adding them within this issue. The dockets are good to have in case regs decides they want to remove the older FR pubs... those are all saved within the docket.

**Comment by cthomasONRR** [comment]
@mcharg ICR 1012-0010 (http://2017onrr/Laws_R_D/FRNotices/FRInfColl.htm) links to 1012-0009 (http://2017onrr/Laws_R_D/FRNotices/ICR0120.htm). I might need your help fixing this link.

**Comment by cthomasONRR** [comment]
@mcharg I finished updating the Current ICRs Excel, if you would like to review. The Discontinued ICRs Excel has similar issues that we discussed. Should I go through and revise this spreadsheet to look like my updated Current ICR spreadsheet?

**Comment by mcharg** [comment]
@cthomasONRR That works.

**Comment by cthomasONRR** [comment]
@mcharg I updated the Discontinued ICRs Excel to match the reformatting I did within the Current ICRs Excel. Please let me know if you want to review, or if I'm good to close this issue. Thanks!

**Comment by mcharg** [comment]
@cthomasONRR I think they look good.
