### ISSUE TITLE
Format Dates in NYMEX files 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1313]
@mojobnichols can you specify which files we need to format the dates for and to which format?

**Comment by mojobnichols** [comment]
Files in link below the here prior to 2011 don't have dates for the month, instead it is the string "January 2010", etc.   These need to be turned into proper dates and then formatted to be January 2010 etc


https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Collections/NYMEX?csf=1&web=1&e=YMIaDl

**Comment by Maroyafaied** [comment]
@Baymatt can you give a status for this issue please?

**Comment by Baymatt** [comment]
Still working through the files, will have it done before the weekend.

**Comment by Maroyafaied** [comment]
@Baymatt sounds good, thank you!

**Comment by Baymatt** [comment]
Was able to finish formatting the remaining necessary files yesterday. For some reason, it wouldn't let me edit in the browser so I had to download the files and then reupload them with the fixed formatting. If there are any issues that occur let me know.
