### ISSUE TITLE
Webpage- Federal Onshore Terminable Leases

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#1314]
Please update the following webpage http://www.onrr.gov/reportPay/royalty-reporting.htm with the attached PDF file-

Federal Onshore Terminable leases - sorted by Due Date - change update to 01/03/2022.

Thank you!

[20220103.xlsx](https://github.com/ONRR/onrr.gov-site/files/7803160/20220103.xlsx)

**Comment by cthomasONRR** [comment]
@merrellc I just want to double-check to make sure you sent over the correct document- your request says PDF but you sent an Excel. Thanks!

**Comment by cthomasONRR** [comment]
@merrellc You can view the changes on the dev site: http://2017onrr/reportpay/royalty-reporting.htm

**Comment by merrellc** [comment]
Sorry, it should be Excel.


Thank you,
​Candace Merrell
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________
From: Christine Thomas ***@***.***>
Sent: Monday, January 3, 2022 10:49 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Webpage- Federal Onshore Terminable Leases (Issue #1314)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@merrellc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmerrellc&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C4a62e782f9544e7c042708d9cee16c21%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637768289842775281%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kolm8QYojgnl%2BI03HN2wn61QSNvwBYIcwKalOPOfX8g%3D&reserved=0> I just want to double-check to make sure you sent over the correct document- your request says PDF but you sent an Excel. Thanks!

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1314%23issuecomment-1004253802&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C4a62e782f9544e7c042708d9cee16c21%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637768289842775281%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=k4YMwZakjhiUeXcSoxCvRM8sPtEMyB2D%2Bl5lld18Dsc%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOXFVHHJY55TN2OSX4GPXF3UUHORXANCNFSM5LFUVSMQ&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C4a62e782f9544e7c042708d9cee16c21%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637768289842775281%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qsY71%2BXm8KHdBehbp6mAjy3YaIbS%2B8i%2BVflHUr7m7Y8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C4a62e782f9544e7c042708d9cee16c21%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637768289842775281%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NdXzs9WKVr6MCiJTXPk8OX6OSLbEedMo7y9hVGG3U4c%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C4a62e782f9544e7c042708d9cee16c21%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637768289842775281%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wNqADHtdsdERgRuvS7O4DV6Q%2BBeIz%2B5yW02dIldisRc%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@merrellc Thanks! Can you please review the dev site and give us your approval to go live? You can view the changes on the dev site: http://2017onrr/reportpay/royalty-reporting.htm

**Comment by merrellc** [comment]
Approve to go live.


Thank you,
​Candace Merrell
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________
From: Christine Thomas ***@***.***>
Sent: Monday, January 3, 2022 11:28 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Webpage- Federal Onshore Terminable Leases (Issue #1314)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@merrellc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmerrellc&data=04%7C01%7Ccandace.merrell%40onrr.gov%7Cbabec1c531cc4320f90d08d9cee6eb2f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637768313448665450%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uR02cqaaRpY1uzRROO5kF3clU1eI1NUI6S49%2Bf5vbNg%3D&reserved=0> Thanks! Can you please review the dev site and give us your approval to go live? You can view the changes on the dev site: http://2017onrr/reportpay/royalty-reporting.htm

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1314%23issuecomment-1004275389&data=04%7C01%7Ccandace.merrell%40onrr.gov%7Cbabec1c531cc4320f90d08d9cee6eb2f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637768313448665450%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4oCkT7ln8d3FDegYj3Cuv9aZHL9BgAV46OvAeTL7ltY%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOXFVHHJQFTYXJR3SG2G7RDUUHTFZANCNFSM5LFUVSMQ&data=04%7C01%7Ccandace.merrell%40onrr.gov%7Cbabec1c531cc4320f90d08d9cee6eb2f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637768313448665450%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VXhPYhXx3eFzeackpqDbbiZaOk34QHjqP4bHc3dUQsc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ccandace.merrell%40onrr.gov%7Cbabec1c531cc4320f90d08d9cee6eb2f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637768313448665450%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=frcyavWgeclRTQvSUhrVGaJuvOqMBWFUi3%2FCMqNCvsA%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ccandace.merrell%40onrr.gov%7Cbabec1c531cc4320f90d08d9cee6eb2f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637768313448665450%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=evWpZxxYYsBIYG%2FE5XDQSNGwVyCtNzuVZRFsMLlQzwE%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@merrellc Great thanks! I just moved the changes to the live site. It will take about 30min for the site to update. Please remember to use 'Ctrl+F5' to refresh the webpage. https://www.onrr.gov/reportpay/royalty-reporting.htm

I will close this issue once I see the changes live.
