### ISSUE TITLE
Update CMS with updated annual FRN link

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1315]
See #1302

**Comment by mcharg** [comment]
@lpgoldstein to also note in the content tracking sheet that the link gets updated annually.

**Comment by mcharg** [comment]
@lpgoldstein I added the note to the content tracking sheet and updated the wireframe.

**Comment by daniel-coleman-1** [comment]
@cthomasONRR this is ready to review:
https://dev-onrr-frontend.app.cloud.gov/references/frns

**Comment by cthomasONRR** [comment]
@daniel-coleman-1

The most recent publication should be: https://www.federalregister.gov/documents/2021/12/27/2021-28045/states-decisions-on-participating-in-accounting-and-auditing-relief-for-federal-oil-and-gas-marginal
As per the link Ginger sent in #1302
![image](https://user-images.githubusercontent.com/72526208/151420345-e718358c-38a9-4209-bf7e-9d305dbf461f.png)

**Comment by daniel-coleman-1** [comment]
@cthomasONRR should be good to go, thanks

**Comment by cthomasONRR** [comment]
@daniel-coleman-1 I did Ctrl+F5 and I'm still getting the old 2020 publication.

**Comment by daniel-coleman-1** [comment]
@cthomasONRR try again?  Should be good

**Comment by cthomasONRR** [comment]
@daniel-coleman-1 OK, now it's showing! Thanks! Approve.
