### ISSUE TITLE
Webpage Update-Active Agreements

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#1319]
Please update the following webpage-
www.onrr.gov/ReportPay/CrossRef.htm
Active Agreements - sorted by state and Agency Agreement number with the attached Excel file. Please use updated 01/03/2022.

Thank you!
[Active Agreements sorted by Agency Number.xlsx](https://github.com/ONRR/onrr.gov-site/files/7804260/Active.Agreements.sorted.by.Agency.Number.xlsx)

**Comment by cthomasONRR** [comment]
@merrellc I made these changes on the dev site: http://2017onrr/reportpay/CrossRef.htm. Please review and give us your approval to go live. Thanks!

**Comment by merrellc** [comment]
Approved.


Thank you,
​Candace Merrell
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________
From: Christine Thomas ***@***.***>
Sent: Monday, January 3, 2022 3:18 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Webpage Update-Active Agreements (Issue #1319)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@merrellc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmerrellc&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C008533f9341b455c6a1608d9cf06f02a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637768451713949584%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=B5dQqTydQa88INlqZaJWNB9BM5NCDkouCdOSaSjAf7s%3D&reserved=0> I made these changes on the dev site: http://2017onrr/reportpay/CrossRef.htm. Please review and give us your approval to go live. Thanks!

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1319%23issuecomment-1004395983&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C008533f9341b455c6a1608d9cf06f02a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637768451713949584%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ltWMD8kP%2FN1bQBQplvjXOJx1Pi37IxhrrfENZvASw4A%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOXFVHGFKCVWRBNEUEEQXALUUIOBXANCNFSM5LGDBH5Q&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C008533f9341b455c6a1608d9cf06f02a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637768451713949584%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JewzbKEkuHVIsy1nHzomeBKG9A7HqW%2FByXXzAAq3mWQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C008533f9341b455c6a1608d9cf06f02a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637768451713949584%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dRZSO1ExG6EVtiyPhKvAjEJC3Tj2AvYI0lrd%2FqRWakg%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C008533f9341b455c6a1608d9cf06f02a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637768451713949584%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hjfupN78Ttp9n0GSeZF%2B%2FnIiT1y7QjkO3SKL5Lkt83c%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@merrellc Great! I just moved these changes to the live site (https://www.onrr.gov/ReportPay/CrossRef.htm). Please allow around 30min for the live site to update. Remember to use 'Ctrl+F5' to refresh the page. I will close this issue once I see the changes live.
