### ISSUE TITLE
Remove Drip Condensate Reporter Letter

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1321]
April and RV have requested for this reporter letter to be removed, @cthomasONRR can you please make the changes in the dev site and send to April for approval. Also, we'll need to remove it from  the reporter letter collection spreadsheet &  delete it from CMS. Thanks
![image](https://user-images.githubusercontent.com/40175688/147992531-179913a2-7f12-4875-98fd-b90ebd8727b0.png)

**Comment by cthomasONRR** [comment]
@Maroyafaied I emailed April the dev site and requester her approval.
I also removed this letter from the Collections folder and the corresponding excel. Both collection items located [here](https://teams.microsoft.com/_#/files/General?groupId=81f624a1-bcde-4f77-ba3b-69c787c88ed3&threadId=19%3A34f9f9ee6b0441dbacab56bfd552f819%40thread.skype&ctx=channel&context=Dear%2520Reporter%2520Letters&rootfolder=%252Fsites%252FNRRD%252FShared%2520Documents%252FGeneral%252FONRR.gov%252FDesign%252FCollections%252FDear%2520Reporter%2520Letters).

**Comment by cthomasONRR** [comment]
April approved and the changes are live. Closing this issue.
