### ISSUE TITLE
Review Statutes collection

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1322]
Can you please make sure I did it right?
https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Collections/Statutes/StatutesCollection.xlsx?d=w099e7c44232841bba656b6c4627cb2fd&csf=1&web=1&e=p53f7s

**Comment by cthomasONRR** [comment]
@mcharg I reviewed. This page is much more simple than the ICRs! No big revisions to do. I changed the column B title to "Law Name Hyperlink" so that everyone knows those URLs should be linked within the law name.
