### ISSUE TITLE
Revised Reporter Training Agenda

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1323]
Please replace the existing Agenda and Registration Information document at - https://www.onrr.gov/reportpay/training/index.htm, with the attached Revised Agenda and Registration Information
[REVISED Reporter Training agenda.pdf](https://github.com/ONRR/onrr.gov-site/files/7808128/REVISED.Reporter.Training.agenda.pdf)
.

**Comment by cthomasONRR** [comment]
@bowlenj Good morning, I made this change on the dev site: http://2017onrr/reportpay/training/index.htm. Please review and give us your approval to go live. Thanks!

**Comment by bowlenj** [comment]
Looks Great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Tuesday, January 4, 2022 7:23 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Revised Reporter Training Agenda (Issue #1323)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf83e67ac212b48e2ef4508d9cf8de2d2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637769030572731771%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=560G8PZ7RtlqbXaTdqJbdFUmVHb79BDWRJoml5aQ%2BFI%3D&reserved=0> Good morning, I made this change on the dev site: http://2017onrr/reportpay/training/index.htm. Please review and give us your approval to go live. Thanks!

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1323%23issuecomment-1004853056&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf83e67ac212b48e2ef4508d9cf8de2d2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637769030572741723%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SuEVlxVfGjzS%2BClmw%2F%2BJIkEc2%2BVjBlcQMRJnYwdQIFU%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VHZDOZERPOLM722EN4TUUL7E5ANCNFSM5LHQ5XDA&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf83e67ac212b48e2ef4508d9cf8de2d2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637769030572741723%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0A%2FQFxIqnXmBBQIntVWvelTsVIwGWqWlWHhK3N3P3D0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf83e67ac212b48e2ef4508d9cf8de2d2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637769030572751680%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yr9ODTx%2FeU0qYIzskZmawIME2oLlfyeRP5yvSczGj1E%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf83e67ac212b48e2ef4508d9cf8de2d2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637769030572751680%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=N0WWqvntxQnG25zMLnMJDiVDh32GPaUMjxkiGr8BQTc%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@bowlenj Great! I just moved the change to the live site (https://www.onrr.gov/reportpay/training/index.htm). It can take the live site about 30min to update. Please remember to use 'Ctrl+F5' to refresh the webpage. I will close this issue once I see the change live. Thanks!
