### ISSUE TITLE
100% Fed Agmt Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1326]
Please update the following webpage https://www.onrr.gov/reportpay/royalty-reporting.htm with the attached excel file.

100% Federal Agreements with the Same Royalty Rate & Royalty Distributions

Also change (updated 10/07/2021) to read 01/04/2022.
[fedagmts.xlsx](https://github.com/ONRR/onrr.gov-site/files/7809823/fedagmts.xlsx)

**Comment by cthomasONRR** [comment]
@bowlenj Hello, this change is ready for your review and approval in dev: http://2017onrr/reportpay/royalty-reporting.htm. Please let us know if you approve these changes to go live. Thanks!

**Comment by bowlenj** [comment]
Looks great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Tuesday, January 4, 2022 12:20 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] 100% Fed Agmt Update (Issue #1326)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1e46c624bca74d881c4708d9cfb7715a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637769209056923061%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JSAVLd%2Bc9jZgV212BZTJZgMWOca%2FIhyZwnt2JyqJ7cM%3D&reserved=0> Hello, this change is ready for your review and approval in dev: http://2017onrr/reportpay/royalty-reporting.htm. Please let us know if you approve these changes to go live. Thanks!

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1326%23issuecomment-1005102875&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1e46c624bca74d881c4708d9cfb7715a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637769209056933016%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HjFX4kM6rPBbm8xKpiQGaOUFGmRWse25y5RVyOGdhDw%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH27T7YHWRRKP6CG2CTUUNCBDANCNFSM5LIE6EJA&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1e46c624bca74d881c4708d9cfb7715a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637769209056933016%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iIie%2F%2FONiPp8hsQf9X86U26oHha0KeeWW%2BzNDqKUnyk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1e46c624bca74d881c4708d9cfb7715a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637769209056942974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pyHr9l6WJRat9N9Rq22QXZnwfkf0dqUPlpZVMHEv1ao%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1e46c624bca74d881c4708d9cfb7715a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637769209056942974%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9bx%2ByDZCZDBk4pQKWsSJVjpLs9JLpYyELUuqJo%2B1BoQ%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@bowlenj These changes are now live: https://www.onrr.gov/reportpay/royalty-reporting.htm. Closing this issue.
