### ISSUE TITLE
Report Pay Training page - PASR training videos "coming soon"

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#133]
Another issue from the content audit.  Remove this not and upload with the right videos. 

https://www.onrr.gov/ReportPay/training/PASR-Training-Videos.htm

![image](https://user-images.githubusercontent.com/40175688/79793915-9a50f880-830e-11ea-906a-b897faf5d5cd.png)

**Comment by lpgoldstein** [comment]
@jennmalcolm No ETA on the videos for now - they have been filmed but not edited - and the team is working on another project right now. We should take down the placeholders for now.

**Comment by jennmalcolm** [comment]
Ok, can you work on taking them down @lpgoldstein

**Comment by lpgoldstein** [comment]
@jennmalcolm for your review: http://2017onrr/ReportPay/training/PASR-Training-Videos.htm

**Comment by jennmalcolm** [comment]
Looks good, thanks!
