### ISSUE TITLE
Add Federal Gas Index Option tab

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1331]

**Comment by mcharg** [comment]
@Maroyafaied Another one that we can show in the demo.  Just needs some styling cleanup.

@cthomasONRR Should we have a link on the CFR in the intro paragraph?  We didn't have one in the wireframe.
https://dev-onrr-frontend.app.cloud.gov/references/valuation?tab=federal-gas-index-option

**Comment by cthomasONRR** [comment]
We can link:

1206.141(c) with the following hyperlink: https://www.ecfr.gov/current/title-30/chapter-XII/subchapter-A/part-1206#p-1206.141(c)

and

1206.142(d) with the following hyperlink: https://www.ecfr.gov/current/title-30/chapter-XII/subchapter-A/part-1206#p-1206.142(d)

**Comment by cthomasONRR** [comment]
@mcharg For the Pricing intro paragraph, we can link 30 CFR 1206 with the following hyperlink: https://www.ecfr.gov/current/title-30/chapter-XII/subchapter-A/part-1206

![image](https://user-images.githubusercontent.com/72526208/148284320-2960d903-0042-4434-abfe-fc5677ca10c7.png)

**Comment by Maroyafaied** [comment]
@mcharg the middle column should be titled New Mexico not Gulf of Mexico. 
![image](https://user-images.githubusercontent.com/40175688/148288110-6deaa4f8-ba4d-4466-b915-120a0198eba1.png)

**Comment by mcharg** [comment]
@Maroyafaied Should we add "ONRR" to the Approved Publications headers like on the Crude Oil Market Centers page?

**Comment by mcharg** [comment]
@cthomasONRR The new links are added, if you want to test them.

**Comment by cthomasONRR** [comment]
@mcharg Just checked them, they are good to go!

**Comment by Maroyafaied** [comment]
@mcharg No we don't need to add "ONRR" for the publications.

**Comment by mcharg** [comment]
@Maroyafaied Ok.  I'm going to close this one, since the blockers are all styling things that don't require updates at the page level.
