### ISSUE TITLE
Clean up header styling

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1332]
The styling isn't very clean and H5 is bigger than H4.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/4cd309f8-6ad1-434c-873a-524baa395bb7)

Wireframe:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/ad88c350-86a7-4659-a5b0-260bbdecdc0f)

Fonts used in wireframe:

Color for all text except H1: #1C2326
H1: 45 pt Lato (only this one is #333333)
H2: 34 pt Lato
H3: 24 pt Lato
H4: 20 pt Lato bold
H5: 18 pt Lato

**Comment by mcharg** [comment]
We should also add more space when headers appear directly below each other.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/0a45e320-5aeb-4820-b50c-d518e594e121)

**Comment by jlouis-onrr** [comment]
@mcharg, can you provide the margins for all headings?

**Comment by mcharg** [comment]
Let's try these to start. That's what they are from eyeballing in the wireframes.  I can provide adjustments once I see them on a page.

H1: 50px between breadcrumbs and title, 10px above the yellow line, 40px below the line
H2: 15 px above, 25 px below
H3: 15 px above, 25 px below
H4: 15 px above, 25 px below
H5: 15 px above, 25 px below

**Comment by jlouis-onrr** [comment]
@mcharg, the vuetify margin and padding classes are in multiples of 4.  For the heading styles I've started with margin-top 16px and margin-bottom: 24px.  I can override these styles and do 15 and 25px respectively, but I'd thought we could see how this looks first.

**Comment by mcharg** [comment]
@jlouis-onrr Yeah, let's do what's easiest.

**Comment by jlouis-onrr** [comment]
@mcharg, these updates are now out in dev.

**Comment by mcharg** [comment]
@jlouis-onrr Looks good!
