### ISSUE TITLE
Tab: Valuation & Pricing > Pricing > Indian Gas Index Zone

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1333]
https://dev-onrr-frontend.app.cloud.gov/references/valuation?tab=pricing
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/50
https://qmcq5k.axshare.com/#id=l9inb4&p=valuation___pricing&g=1

Also:
https://dev-onrr-frontend.app.cloud.gov/indian/indian-pricing
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/34
https://qmcq5k.axshare.com/#id=y89dq7&p=indian_pricing&g=1

**Comment by mcharg** [comment]
Got as far as I could get. https://dev-onrr-frontend.app.cloud.gov/references/valuation?tab=indian-gas-index-zone

**Comment by mcharg** [comment]
Added counties expansion panel.

**Comment by cthomasONRR** [comment]
@mcharg Documents are linked and ready for your review.

**Comment by mcharg** [comment]
Documents look good.

**Comment by mcharg** [comment]
@cthomasONRR Another one approved by SME that's still open.

**Comment by cthomasONRR** [comment]
@mcharg I think we are good to close this issue.
