### ISSUE TITLE
Tab: Valuation & Pricing > Pricing > Indian Oil Major Portion

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1334]
https://dev-onrr-frontend.app.cloud.gov/references/valuation?tab=pricing
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/50
https://qmcq5k.axshare.com/#id=l9inb4&p=valuation___pricing&g=1

Also:
https://dev-onrr-frontend.app.cloud.gov/indian/indian-pricing
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/34
https://qmcq5k.axshare.com/#id=y89dq7&p=indian_pricing&g=1

**Comment by mcharg** [comment]
Added as much as I could. https://dev-onrr-frontend.app.cloud.gov/references/valuation?tab=indian-oil-major-portion

**Comment by cthomasONRR** [comment]
@mcharg Documents are linked and ready for your review.

**Comment by mcharg** [comment]
Documents look good.

**Comment by mcharg** [comment]
@cthomasONRR Another one approved by SME that's still open.

**Comment by cthomasONRR** [comment]
@mcharg For this one, looks like we still need to link a Dear Reporter Letter at the bottom of the page. Are we able to do that yet?
![image](https://user-images.githubusercontent.com/72526208/163399328-8f9c87e9-69aa-4ec5-897f-9d1815bd8168.png)

**Comment by mcharg** [comment]
Not yet.

**Comment by mcharg** [comment]
@cthomasONRR Reporter letter link added. This is ready for full ODDD approval. (Note: It's marked as Approved by SME in spreadsheet.)

**Comment by mcharg** [comment]
@cthomasONRR Fixed the url.

**Comment by cthomasONRR** [comment]
@mcharg Approved :)
