### ISSUE TITLE
Tab: Valuation & Pricing > Pricing > Indian Gas Major Portion

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1335]
https://dev-onrr-frontend.app.cloud.gov/references/valuation?tab=pricing
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/50
https://qmcq5k.axshare.com/#id=l9inb4&p=valuation___pricing&g=1

Also:
https://dev-onrr-frontend.app.cloud.gov/indian/indian-pricing
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/34
https://qmcq5k.axshare.com/#id=y89dq7&p=indian_pricing&g=1

**Comment by mcharg** [comment]
Added as much as I could. https://dev-onrr-frontend.app.cloud.gov/references/valuation?tab=indian-oil-major-portion

**Comment by cthomasONRR** [comment]
@mcharg Documents are linked and ready for your review.

**Comment by mcharg** [comment]
Documents look good.

**Comment by mcharg** [comment]
This is already marked as approved by SME in the spreadsheet. Not sure how this issue is still open.

**Comment by cthomasONRR** [comment]
@mcharg I think this is good to close. We are actively updating the collection and all content has been added.
