### ISSUE TITLE
Tab: Valuation & Pricing > Valuation Regulations

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1336]

**Comment by mcharg** [comment]
Putting this one off because we need rulemakings pages before we can add all the links.

**Comment by cthomasONRR** [comment]
https://dev-onrr-frontend.app.cloud.gov/references/valuation?tab=valuation-regulations
https://qmcq5k.axshare.com/#id=l9inb4&p=valuation___pricing&g=1

@mcharg This is ready for your review. All tables are added, with links to the rulemakings page and eCFR. I also added in the handbooks and the links at the bottom of the wireframe.

The tables definitely need some sizing functionality. There is one link at the bottom that's a PDF, which I could not add.

**Comment by mcharg** [comment]
@cthomasONRR Looks good.  Putting into the backlog.

**Comment by mcharg** [comment]
@cthomasONRR The links aren't filtering the rulemakings page for me.  I added a comment to the issue about filtering for Jerome to look at it.

**Comment by cthomasONRR** [comment]
@mcharg Argh, ok, if you look at the hyperlinks, the are individualized to the filter topic. Not sure why the filtered tables aren't displaying

**Comment by mcharg** [comment]
@cthomasONRR The links to the filters are fixed.  I checked the links and they all work.  Moving to backlog.

**Comment by mcharg** [comment]
@cthomasONRR This is ready for ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg Approved
