### ISSUE TITLE
Tab: Valuation & Pricing > Unbundling

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1337]
https://dev-onrr-frontend.app.cloud.gov/references/valuation?tab=unbundling
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/50
https://qmcq5k.axshare.com/#id=l9inb4&p=valuation___pricing&g=1

**Comment by mcharg** [comment]
Added as much as I could. https://dev-onrr-frontend.app.cloud.gov/references/valuation?tab=unbundling

**Comment by mcharg** [comment]
This issue is for the disclaimer accordion and adding the subtabs.

**Comment by cthomasONRR** [comment]
The expansion panel needs to be added to the dev site. I'm assuming that's because it hasn't been developed yet? Also, within the expansion panel, the subheaders are bolded in the wireframe. Do you want to add that in?

![image](https://user-images.githubusercontent.com/72526208/150012914-2e1919fc-4495-4c3a-8893-f9763540045f.png)

**Comment by mcharg** [comment]
@cthomasONRR The content is ready to review for the accordion and the sub tab labels.  The headers are using a heading style that needs to be updated as part of the issue @jlouis-onrr has for that and there's an issue to have the accordion open by default.  But the content is good to review.

Can you pay attention to capitalization?  @daniel-coleman-1 said anything less than an H1 should be sentence case, but I wasn't sure which things are proper nouns in the headers.  Also not sure if we need to keep the capitalization approved by whatever authority would have reviewed this language.

**Comment by cthomasONRR** [comment]
@mcharg The subtabs look good. The capitalization within the accordion content is correct, based on my understanding. My one question - did unbundling ask you not to use the section symbol after 30 CFR? I know there was discussion about the use of it, but I'm so far removed from those conversations now that I don't think we were informed of the decision.

**Comment by mcharg** [comment]
@cthomasONRR I don't remember what they said about the section symbol.  I think you made the last set of edits in the wireframes, so I assume they're what they asked for.

**Comment by cthomasONRR** [comment]
@mcharg OK, I think it looks good and will approve. If they want to add section symbols later, that will be an easy fix.
