### ISSUE TITLE
Tab: Valuation & Pricing > Unbundling > Standardized UCAs

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1338]
https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Collections/Unbundling/StandardizedUCAsCollection.xlsx?d=w1bc26a68e0594f6a9999de2b4e309294&csf=1&web=1&e=6BxNVz

**Comment by Maroyafaied** [comment]
@mcharg try to do without a collection.

**Comment by mcharg** [comment]
Added cards without a collection.
https://dev-onrr-frontend.app.cloud.gov/references/valuation?tab=standardized-ucas

**Comment by mcharg** [comment]
@cthomasONRR This is ready for ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg Approved
