### ISSUE TITLE
Collection: Plant-Specific UCAs

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1339]
https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/CMS/Collections/Unbundling/Plant-SpecificUCAsCollection.xlsx?d=w4652e771955048258c79f8e9a2f2f572&csf=1&web=1&e=f92SuW

**Comment by mcharg** [comment]
Some of these have changed from PDF to XLS, so we need to make sure the collection can accommodate either.

**Comment by jlouis-onrr** [comment]
@mcharg, plant-specific ucas are in dev: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=unbundling,plant-specific-ucas

**Comment by mcharg** [comment]
@jlouis-onrr This looks great. We'll review the links and content in the issue for adding content to the page.
