### ISSUE TITLE
ReportPay payments page - review/cleanup page structure and fix nav bar

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#134]
https://www.onrr.gov/reportpay/payments.htm#PIL-INSTRUCTIONS

![image](https://user-images.githubusercontent.com/40175688/79794379-61655380-830f-11ea-83f8-c60903add854.png)

**Comment by jennmalcolm** [comment]
This is a bigger project than originally anticipated, so we will need to work on it next sprint

**Comment by lpgoldstein** [comment]
@jennmalcolm I have all of the information in dev but I"m stuck on formatting if you want to take a look. file://iondeniisp01/ONRR2017/reportpay/payments.htm
