### ISSUE TITLE
Update December NYMEX prices on onrr.gov

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#1341]
Good morning,

Please update the December NYMEX CMA and roll prices on onrr.gov. Prices attached.

Thanks!

@sudarr

[NYMEX122021.xlsx](https://github.com/ONRR/onrr.gov-site/files/7822374/NYMEX122021.xlsx)

**Comment by Maroyafaied** [comment]
@cthomasONRR can you also add this file to the collection NYMEX folder please.

**Comment by cthomasONRR** [comment]
@boices Good morning, these updates are now on the dev site: http://2017onrr/valuation/NYMEX.htm. Please review and give us your approval to go live. Thanks!

**Comment by cthomasONRR** [comment]
@Maroyafaied This new NYMEX file is now also in the NYMEX collections folder.

**Comment by boices** [comment]
Looks perfect--thanks again!

**Comment by cthomasONRR** [comment]
@boices Great! The changes are now live: https://www.onrr.gov/valuation/NYMEX.htm. I will close this issue now.
