### ISSUE TITLE
Have external links open in a new browser tab

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1342]

**Comment by Maroyafaied** [comment]
@mcharg this is ready to review again.

**Comment by mcharg** [comment]
@mojobnichols Not working. The pay.gov link under QuickLinks goes opens in the current window.
https://dev-onrr-frontend.app.cloud.gov/

Some of the links on this page are also not working.
https://dev-onrr-frontend.app.cloud.gov/references/statutes

Also, the [1996 Amendments to FOGRMA](https://dev-onrr-cms.app.cloud.gov/references/statutes/fogrma-amendments) link on this page is also not working. It's an internal link set up using the default link tool.
https://dev-onrr-frontend.app.cloud.gov/references/statutes

**Comment by Maroyafaied** [comment]
@mojobnichols I just realized this issue was forgotten about from last sprint. Is this done?

**Comment by Maroyafaied** [comment]
@mojobnichols will update content in database

**Comment by mojobnichols** [comment]
Database is updated for content_blocks and card_blocks.   I refrained from updating tab blocks because its a stlightly more complex json object and there were only two of them.  If we can find where they so I can try locally and test other wise it might just be easier to use external link in new tool to correct these two. 

To be clear @mcharg can you find (which page on frontend) the external links in tab blocks are in so I can test.

**Comment by lpgoldstein** [comment]
@mojobnichols I'll find for you because Shannon won't be back until next week.

**Comment by lpgoldstein** [comment]
@mojobnichols This is an external link that doesn't open on a new page https://dev-onrr-frontend.app.cloud.gov/reporting/production?tabs=new-reporter-checklist&panel=give-onrr-your-taxpayer-id
I think it's on a card, within an accordion, within a tab.

**Comment by Maroyafaied** [comment]
@mojobnichols I tested the ones in Shannon's comment above and they all are working now and opening in a new tab. Here's an example of a link in a tab that doesn't work.  https://dev-onrr-frontend.app.cloud.gov/indian/assistance?tabs=federal-indian-minerals-office
![image](https://user-images.githubusercontent.com/40175688/170370088-a2ceac26-d808-47e6-945a-1b17593ce491.png)

**Comment by mojobnichols** [comment]
BLM is set to http instead of https  it redirects to https so its not a big deal but that is why it didn't get fixed and the others did

**Comment by mojobnichols** [comment]
@lpgoldstein same thing href is http:// instead of https://

@Maroyafaied and @lpgoldstein I'll fix http:// as well to open in new tags

**Comment by lpgoldstein** [comment]
@mojobnichols Thank you! Let me know when I can start checking.

**Comment by Maroyafaied** [comment]
@mojobnichols everything looks good and opening in a new tab. Thanks!

**Comment by lpgoldstein** [comment]
@mojobnichols @Maroyafaied Everything I've opened works as well!

**Comment by Maroyafaied** [comment]
@mcharg we checked the external links and everything is working , please review and let  @mojobnichols know if there's issues. Thanks

**Comment by mcharg** [comment]
Looks good.
