### ISSUE TITLE
Add Employment page content

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1343]

**Comment by mcharg** [comment]
Fixed a couple of links.  Now blocked by the layout breaks to get the icons on the right and the video player.
https://dev-onrr-frontend.app.cloud.gov/about/employment

**Comment by mcharg** [comment]
@lpgoldstein I added the columns. https://dev-onrr-frontend.app.cloud.gov/about/employment

**Comment by mcharg** [comment]
@cthomasONRR This is ready for ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg Approved
