### ISSUE TITLE
Tab: Valuation & Pricing > Valuation Examples

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1344]

**Comment by mcharg** [comment]
@cthomasONRR Should we have links to the CFR on this one?
https://dev-onrr-frontend.app.cloud.gov/references/valuation?tab=valuation-examples

**Comment by cthomasONRR** [comment]
@mcharg 

30 CFR Part 1290, Subpart B: https://www.ecfr.gov/current/title-30/chapter-XII/subchapter-B/part-1290
I think this should be reworded as just "30 CFR Part 1290" ... I don't see a subpart B, but 1290 is within Subchapter B, that's where the confusion might have occurred.

30 CFR Part 1241: https://www.ecfr.gov/current/title-30/chapter-XII/subchapter-A/part-1241

**Comment by mcharg** [comment]
@cthomasONRR Links added.

**Comment by mcharg** [comment]
This one is far as it can get without being able to put cards on a tab, so moving back to product backlog.
https://dev-onrr-frontend.app.cloud.gov/references/valuation?tab=valuation-examples

**Comment by cthomasONRR** [comment]
@mcharg Links look good!

**Comment by mcharg** [comment]
Added cards. https://dev-onrr-frontend.app.cloud.gov/references/valuation?tab=valuation-examples

**Comment by mcharg** [comment]
@cthomasONRR This is ready for ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg Approved
