### ISSUE TITLE
Add solids videos to wireframes

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1346]

**Comment by mcharg** [comment]
@cthomasONRR Will you please review?  I separated training presentations from videos to make room for both collections to grow. Also added the currently scheduled training to the schedule tab as an example.
https://qmcq5k.axshare.com/#g=1&id=cwcm9b&p=reporter_training

@daniel-coleman-1 This will require updates to the sitemap.  Please create a separate issue to make those changes.

**Comment by cthomasONRR** [comment]
@mcharg I think we need to add a date under Training Presentations. They just asked me to add "January FY22" to the current website.

Current Site:
![image](https://user-images.githubusercontent.com/72526208/148796077-aabf67df-0b2a-45f0-a2e3-3c23d47250f8.png)

Wireframe:
![image](https://user-images.githubusercontent.com/72526208/148796142-e5c3a316-555d-4fff-9a48-b082c2992ad3.png)

**Comment by cthomasONRR** [comment]
@mcharg Did a 2nd review, everything looks good!
