### ISSUE TITLE
Reporter Training Presentations Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1350]
Please replace the existing presentations with the same names with the attached presentations at https://www.onrr.gov/reportpay/training/index.htm.

Also please make the following changes to this page - https://www.onrr.gov/reportpay/training/index.htm:
- Move Training Video's under training Presentations
- Change header for Training Presentations to read Reporter Training Presentations January FY2

[Overlapping Agreements.pptx](https://github.com/ONRR/onrr.gov-site/files/7830632/Overlapping.Agreements.pptx)
[WebCenter Portal User Guide.pptx](https://github.com/ONRR/onrr.gov-site/files/7830633/WebCenter.Portal.User.Guide.pptx)
[Basic Leases and Agreements - Federal and Indian.pptx](https://github.com/ONRR/onrr.gov-site/files/7830639/Basic.Leases.and.Agreements.-.Federal.and.Indian.pptx)
[ONRR Audit Process.pptx](https://github.com/ONRR/onrr.gov-site/files/7830641/ONRR.Audit.Process.pptx)
[Accounts Receivable.pptx](https://github.com/ONRR/onrr.gov-site/files/7830642/Accounts.Receivable.pptx)
2

**Comment by cthomasONRR** [comment]
@bowlenj The changes are now on the dev site: http://2017onrr/reportpay/training/index.htm. Please review and give us your approval to make the changes live. Thanks!

**Comment by bowlenj** [comment]
Can you move the Training videos to the bottom under Compliance?  That way the presentations are at the top?

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Friday, January 7, 2022 12:24 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Reporter Training Presentations Update (Issue #1350)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C594fce0902cd493fc30f08d9d2135d1c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637771803784473617%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xpn7Gtxe3PoyLF2azbJ5D1k3oh3cpVBlVD5tcU63d5k%3D&reserved=0> The changes are now on the dev site: http://2017onrr/reportpay/training/index.htm. Please review and give us your approval to make the changes live. Thanks!

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1350%23issuecomment-1007675856&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C594fce0902cd493fc30f08d9d2135d1c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637771803784473617%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pcBPZq7hwHy5X3HDSFXJAgNMzyPienM%2FENwwr%2FXPcZ0%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VHZPV3CAEAXPLNTM4LTUU44W3ANCNFSM5LPMDKAA&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C594fce0902cd493fc30f08d9d2135d1c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637771803784483569%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CQsA09HDqlvjyq6Brywvzdxqf4FTPNWE9mCeBVN2jEQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C594fce0902cd493fc30f08d9d2135d1c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637771803784483569%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QiXKous5tyhFXp2HV5%2BwALKdQeFTCMNmRPERBWnavmc%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C594fce0902cd493fc30f08d9d2135d1c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637771803784483569%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IZ03qc84OfAQuByHjl%2BQFdyiDbIteVEh88KKJiVx8Jc%3D&reserved=0>.

**Comment by bowlenj** [comment]
I have one more presentation that needs to be replaced.  It's Billing under the Paying category
[Billing.pptx](https://github.com/ONRR/onrr.gov-site/files/7830926/Billing.pptx)
.

**Comment by cthomasONRR** [comment]
@bowlenj 

Ok, I moved the training videos and updated the Billing powerpoint.
http://2017onrr/reportpay/training/index.htm

Let me know if anything else needs modifications.
Thanks!

**Comment by bowlenj** [comment]
You are AMAZING!!!!  Thank you, it looks perfect 🙂

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Friday, January 7, 2022 12:35 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Reporter Training Presentations Update (Issue #1350)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cef055791066c414b05b508d9d214f108%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637771810112255391%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BrA3WKTPRviO%2BpEb7A5Y336PaSas5PjqqNkXv4nCNZE%3D&reserved=0>

Ok, I moved the training videos and updated the Billing powerpoint.
http://2017onrr/reportpay/training/index.htm

Let me know if anything else needs modifications.
Thanks!

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1350%23issuecomment-1007683259&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cef055791066c414b05b508d9d214f108%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637771810112265354%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GNXE17fjB3AgfBwdIfOGJiP%2FE%2BEtzTULVEol9VcINrs%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH7GKJ4HLSBNRJ4LFH3UU46ATANCNFSM5LPMDKAA&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cef055791066c414b05b508d9d214f108%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637771810112265354%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=58r%2BripOr%2B%2BjaU2QrdTmC1NwKLucGHtIKmep0d25Nvk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cef055791066c414b05b508d9d214f108%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637771810112275292%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UxuF4L9Zjtz6%2FcK29I5EXUkwYrwlXu0AZg8qPwd2KUc%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cef055791066c414b05b508d9d214f108%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637771810112275292%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xYx4mq3WGYgF%2BQz%2F81nD8%2BFseWc4M9oekZ4mefF%2FobU%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@bowlenj 
Great! The changes are now live: https://www.onrr.gov/reportpay/training/index.htm.
I will close this issue now.
