### ISSUE TITLE
2021 Index Zone prices not visible

### ISSUE THREAD

**Issue by sudarr** [ONRR/onrr.gov-site#1351]
I'm hearing from a few companies that the 2021 prices for Indian Index zone prices aren't available on the site because 2021 isn't in the year drop-down selection now that 2022 is the default page.
![image](https://user-images.githubusercontent.com/61762459/148611342-60825f7f-bdba-406f-9703-db4cce473ada.png)

**Comment by cthomasONRR** [comment]
@jlouis-onrr Could you help Robert with this issue? I just checked the Excel sheets, and the 2021 data is there. I'm also looking at the 'allzones' html page, and I can't see where I can resolve this issue. Your help would be much appreciated. Thanks!

**Comment by Maroyafaied** [comment]
@sudarr This has been fixed on the live site, can you please check and verify it looks good. Thanks https://onrr.gov/valuation/allzones.htm

**Comment by sudarr** [comment]
It looks great! Thank you guys for getting it resolved.


Robert J Sudar
Manager, Market & Spatial Analytics
Office of Natural Resources Revenue
***@***.***
Office: 303-231-3511, Cell: 720-492-6420
________________________________
From: Maroyafaied ***@***.***>
Sent: Monday, January 10, 2022 10:10 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Sudar, Robert J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] 2021 Index Zone prices not visible (Issue #1351)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@sudarr<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsudarr&data=04%7C01%7Crobert.sudar%40onrr.gov%7C2602c2b75fd2461c491008d9d45c1f1e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774314401046585%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=RzzA1kfT6Zm0Qs9yrukj7PAvVxB3ZhhJTlB%2BkRp3B%2Bg%3D&reserved=0> This has been fixed on the live site, can you please check and verify it looks good. Thanks https://onrr.gov/valuation/allzones.htm<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fonrr.gov%2Fvaluation%2Fallzones.htm&data=04%7C01%7Crobert.sudar%40onrr.gov%7C2602c2b75fd2461c491008d9d45c1f1e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774314401056534%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sLu%2B6gP8CETQCPJoH4ZnIFjKQCbcLxUMg86fFtPxvF4%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1351%23issuecomment-1009140733&data=04%7C01%7Crobert.sudar%40onrr.gov%7C2602c2b75fd2461c491008d9d45c1f1e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774314401056534%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ujSa%2B1eewyZICooTdtDAETWzdw%2BNN3YXmdCNRSuXClI%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOXGXG3ITPW65QAOD3UASLLUVMHHZANCNFSM5LPWS3YQ&data=04%7C01%7Crobert.sudar%40onrr.gov%7C2602c2b75fd2461c491008d9d45c1f1e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774314401066492%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2Bzkf10I3ECd89YrjptsPa3DxiYl%2FG2SLpb221XNoFEc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crobert.sudar%40onrr.gov%7C2602c2b75fd2461c491008d9d45c1f1e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774314401066492%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=e%2FH7GJIaQj88D6VZuomZGYLKz5Cq%2FdsfYKHSTxj%2B6TI%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crobert.sudar%40onrr.gov%7C2602c2b75fd2461c491008d9d45c1f1e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774314401076448%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qgEN6SjGOhUQEikoVTIQeMQiytSSwhBiI0yl0s5EQSo%3D&reserved=0>.
