### ISSUE TITLE
Reporter Training Presentations

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1352]
Please add the attached presentations CMP-2014 Industry View and ONRR Enforcement to Reporter Training Presentations under Compliance & Enforcement at the following webpage - https://www.onrr.gov/reportpay/training/index.htm

[173_CMP2014_Industry_View_2022-01-13_v2.pptx](https://github.com/ONRR/onrr.gov-site/files/7839546/173_CMP2014_Industry_View_2022-01-13_v2.pptx)
[ONRR Enforcement.pptx](https://github.com/ONRR/onrr.gov-site/files/7839601/ONRR.Enforcement.pptx)

**Comment by cthomasONRR** [comment]
@bowlenj 
Good morning! I have these 2 new trainings uploaded in dev: http://2017onrr/reportpay/Training/index.htm. Please review and give us your approval to go live. Thanks!

**Comment by bowlenj** [comment]
Perfect, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Monday, January 10, 2022 7:51 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Reporter Training Presentations (Issue #1352)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cd2d3b1513b344c15eb0708d9d448c604%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774231294365595%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iNNZi8FfmTyvq9tX2V010G2mYVYaOuNU1TePwlW8Rls%3D&reserved=0>
Good morning! I have these 2 new trainings uploaded in dev: http://2017onrr/reportpay/Training/index.htm. Please review and give us your approval to go live. Thanks!

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1352%23issuecomment-1008947499&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cd2d3b1513b344c15eb0708d9d448c604%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774231294375569%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sPb11wEyYwWA9U7eIfbTh3bLQITYWRTyjw0NndaIbV0%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH6722Y2BW36WD64BITUVLXAXANCNFSM5LT2U4FQ&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cd2d3b1513b344c15eb0708d9d448c604%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774231294375569%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YR3unm1BzCUcWKUsNhk2jxWc%2FRptWNrRyWVM8nxlzbU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cd2d3b1513b344c15eb0708d9d448c604%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774231294375569%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QVk%2FiaUYAntaUaN7hpE%2F7BtHHfnPhJa9rxZkJrlmDcs%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cd2d3b1513b344c15eb0708d9d448c604%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774231294385527%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cGFmkQmd9B%2BudDji3cFhtFSl7eL6xiA9AsDejuV4kNg%3D&reserved=0>.

**Comment by mcharg** [comment]
@cthomasONRR Yes and I need to add them to the wireframes.  I'm working on that page right now to get the solids videos added, so I'll add these at the same time.

**Comment by mcharg** [comment]
@cthomasONRR Added to wireframe.

@bowlenj You may want to look at the wireframe, as well.  I separated training presentations from training videos to make room for the solids videos.  It'll also help the presentations be more prominent and make room for both collections to grow.  I also added the training that's currently on the site to the schedule tab as an example.
https://qmcq5k.axshare.com/#g=1&id=cwcm9b&p=reporter_training
