### ISSUE TITLE
Oil & Gas Reporter Training Presentations

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1353]
Please add and/or replace the attached slides to the following webpage at onrr.gov - https://www.onrr.gov/reportpay/training/index.htm

Please replace ONRR-4054 Oil and Gas Operations Report (OGOR) with attached Basic OGOR Reporting
[Basic OGOR  Reporting- 012022.pptx](https://github.com/ONRR/onrr.gov-site/files/7839774/Basic.OGOR.Reporting-.012022.pptx)

Please replace OGOR Comma Separated Value (CSV) Reporting with attached CSV Reporting file (keep file name as OGOR Comma Separated Value (CSV) Reporting)
[CSV REPORTING (new logo, 508 compliant - 012022 lr).pptx](https://github.com/ONRR/onrr.gov-site/files/7839835/CSV.REPORTING.new.logo.508.compliant.-.012022.lr.pptx)

Please add eCommerce and Electronic Tools
[Ecommerce and Electronic Tools- Production 012022.pptx](https://github.com/ONRR/onrr.gov-site/files/7839908/Ecommerce.and.Electronic.Tools-.Production.012022.pptx)

Please add Edit 11020 Inventory Error
[Edit 11030 Inventory Error - Jared G - Final updated PPT 012022.pptx](https://github.com/ONRR/onrr.gov-site/files/7839924/Edit.11030.Inventory.Error.-.Jared.G.-.Final.updated.PPT.012022.pptx)

Please replace Facility Measurement Points (FMP) with the attached presentation, please keep the name as currently shown on webpage
[FMP-PASR January 2022.pptx](https://github.com/ONRR/onrr.gov-site/files/7840338/FMP-PASR.January.2022.pptx)

Please add How to Save your OGOR
[How to Save Your OGOR Reports 012022.pptx](https://github.com/ONRR/onrr.gov-site/files/7840408/How.to.Save.Your.OGOR.Reports.012022.pptx)

Please add LVS-GVA presentation
[LVS-GVS - updated 01 2022.pptx](https://github.com/ONRR/onrr.gov-site/files/7840508/LVS-GVS.-.updated.01.2022.pptx)

Please Replace OGOR Reporting Errors with the attached presentation
[OGOR ERROR Reporting_012022.pptx](https://github.com/ONRR/onrr.gov-site/files/7840541/OGOR.ERROR.Reporting_012022.pptx)

**Comment by cthomasONRR** [comment]
@bowlenj The following PowePoint is not 508-compliant. Could you please correct this powepoint:

> Please replace ONRR-4054 Oil and Gas Operations Report (OGOR) with attached Basic OGOR Reporting
> Basic OGOR Reporting- 012022.pptx

**Comment by bowlenj** [comment]
I'm sorry I attached the wrong one, this one is 508 compliant.  There were 2 in the folder for some reason.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Monday, January 10, 2022 10:49 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Oil & Gas Reporter Training Presentations (Issue #1353)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf05c111b339d49fda04b08d9d461a552%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774338123080244%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EWDWlu440uiw4DOSKJvMeliagttANLI5erZxq321Mvc%3D&reserved=0> The following PowePoint is not 508-compliant. Could you please correct this powepoint:

Please replace ONRR-4054 Oil and Gas Operations Report (OGOR) with attached Basic OGOR Reporting
Basic OGOR Reporting- 012022.pptx

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1353%23issuecomment-1009175286&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf05c111b339d49fda04b08d9d461a552%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774338123090221%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CWhNB2O9K3fIn4Vv2SBh7M8XNdbbCzLi9hNucBFRn1M%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH6AD46XFID52QNYQCDUVML35ANCNFSM5LUFLQXQ&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf05c111b339d49fda04b08d9d461a552%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774338123090221%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eUsx7Ff%2FrvWjGcKgJYoBvzbDuqdkf1YXq%2FMT9ZrI%2FYo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf05c111b339d49fda04b08d9d461a552%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774338123100173%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FO%2Bpg4A7se%2Fqz60ht6uBbOnTrCUWIjknzmx3D%2B%2BwADM%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf05c111b339d49fda04b08d9d461a552%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774338123100173%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eFYrRpB%2BZ%2BvtK6bpOpITpo8GxXUrLnQThJ6s6KpCbYY%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@bowlenj Could you send the 508-compliant attachment? I did not receive it.

**Comment by cthomasONRR** [comment]
@bowlenj These revisions are ready for your review and approval: http://2017onrr/reportpay/training/index.htm

**Comment by bowlenj** [comment]
Perfect!!!!!!!!!!!!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Monday, January 10, 2022 11:42 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Oil & Gas Reporter Training Presentations (Issue #1353)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C9e5d6e23a5a5405086c508d9d468fda6%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774369669282791%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zFrOvfVehfgAY%2BdAVDGzH2YURgLdOrGWs%2FTejWlPMOY%3D&reserved=0> These revisions are ready for your review and approval: http://2017onrr/reportpay/training/index.htm

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1353%23issuecomment-1009234679&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C9e5d6e23a5a5405086c508d9d468fda6%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774369669282791%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8Gll3zjSnvJb5any5C6mJkIkYyM6zMkMACp8YQND9LM%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH7ROHBH7YLXSYWLG33UVMSBBANCNFSM5LUFLQXQ&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C9e5d6e23a5a5405086c508d9d468fda6%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774369669292727%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6hgtnSVXLoR6Mscc%2FJnymKjqkPafsRPxqS4XL4NkX%2Fc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C9e5d6e23a5a5405086c508d9d468fda6%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774369669292727%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vXVAdjA44Zbxq5LWvGJJNDBVxQbJIubtCd5cT4HC2tU%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C9e5d6e23a5a5405086c508d9d468fda6%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774369669292727%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aMRCR27PRoAJaMBk1foyBtfUpPWUfSL4E%2F8JuYybhTs%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@bowlenj Great! The changes are now live: https://www.onrr.gov/reportpay/training/index.htm.

@mcharg @daniel-coleman-1 The sitemap and wireframes need to be updated to reflect the addition of new training documents.
