### ISSUE TITLE
Update Solids Presentations

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1355]
Please replace the Reporter Training Presentations under the Solids category with the below attachments at the following webpage - https://www.onrr.gov/reportpay/training/index.htm

Replace Solids Minerals Reporter Opening, Form 4444, Payor Codes, and EMARF with the attached, please keep current name as shown on webpage
[1 - Opening Form ONRR-4444 Payor Codes EMARF 2022.pptx](https://github.com/ONRR/onrr.gov-site/files/7840836/1.-.Opening.Form.ONRR-4444.Payor.Codes.EMARF.2022.pptx)

Please replace Solids Mineral Leases, Sales Summary, Sales Contracts & Facility Data, Handbook
[2 - Solids Lease Summary, Facility and Contracts Training January 2022.pptx](https://github.com/ONRR/onrr.gov-site/files/7840845/2.-.Solids.Lease.Summary.Facility.and.Contracts.Training.January.2022.pptx)

Please replace Form ONRR-4430 (P&R)
[3 - Form ONRR-4430 (P&R) Final 2022.pptx](https://github.com/ONRR/onrr.gov-site/files/7840847/3.-.Form.ONRR-4430.P.R.Final.2022.pptx)

Please replace Solids Billing
[4 - Solids Billing Jan 2022.pptx](https://github.com/ONRR/onrr.gov-site/files/7840849/4.-.Solids.Billing.Jan.2022.pptx)

Please add Soilds AR Basics presentation
[5 - Solids AR Basics Jan 2022.pptx](https://github.com/ONRR/onrr.gov-site/files/7840856/5.-.Solids.AR.Basics.Jan.2022.pptx)

Please add Solids Audit
[6 - Solids Audit Module Jan 2022.pptx](https://github.com/ONRR/onrr.gov-site/files/7840859/6.-.Solids.Audit.Module.Jan.2022.pptx)

Please add Solids Valuation Sodium and Potassium
[7 - Valuation Sodium and Potassium Training Jan 2022.pptx](https://github.com/ONRR/onrr.gov-site/files/7840864/7.-.Valuation.Sodium.and.Potassium.Training.Jan.2022.pptx)

**Comment by cthomasONRR** [comment]
@bowlenj These revisions are ready for your review and approval: http://2017onrr/reportpay/training/index.htm

**Comment by bowlenj** [comment]
Looks GREAT, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Monday, January 10, 2022 11:42 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update Solids Presentations (Issue #1355)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C5e858ba400eb4b49ce5708d9d4690529%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774369791527464%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Tl2xIrkzBfVfS7wgr34GQSyHjSW17aqVwkCZvhWYev4%3D&reserved=0> These revisions are ready for your review and approval: http://2017onrr/reportpay/training/index.htm

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1355%23issuecomment-1009234867&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C5e858ba400eb4b49ce5708d9d4690529%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774369791537422%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lVpfTbagv93pdmj7cVmJX9V7T%2BfaGW1vwEiMmSDQgbg%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH74MCU6IVW35S3FPMTUVMSCDANCNFSM5LUIMVQA&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C5e858ba400eb4b49ce5708d9d4690529%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774369791537422%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xY%2ByKGpZOR%2BXQ8Bl3KO2MPDTNcr%2BYwmAq1DwroA%2B3c4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C5e858ba400eb4b49ce5708d9d4690529%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774369791547379%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=we9o5sUQNs9f88%2B%2B43oFF%2B1E9cT%2FkEWb20Jsd9Rvdvw%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C5e858ba400eb4b49ce5708d9d4690529%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774369791547379%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9ppiA0Tj4DLcq6DL6VTrExlsoQVqwzdkKA3JJIqZf8I%3D&reserved=0>.
