### ISSUE TITLE
Royalty Valuation Presentation

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1357]
Please add a Royalty Valuation category to the following page - https://www.onrr.gov/reportpay/training/index.htm

Please add attached presentation to the Royalty Valuation category
[Federal Processed Gas Reporting.pdf](https://github.com/ONRR/onrr.gov-site/files/7841671/Federal.Processed.Gas.Reporting.pdf)

**Comment by cthomasONRR** [comment]
@bowlenj These changes are now in dev: http://2017onrr/reportpay/training/index.htm. Please review and give us your approval to go live. Thanks!

**Comment by bowlenj** [comment]
Perfect!!!!!!!!!!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Monday, January 10, 2022 1:31 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Royalty Valuation Presentation (Issue #1357)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C8bdb29a382344291113308d9d4783c70%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774435159471694%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0v3WNbMEB9X%2FZSC7yhtYqxJrXbm3E7m2LNaaCZsM0Q4%3D&reserved=0> These changes are now in dev: http://2017onrr/reportpay/training/index.htm. Please review and give us your approval to go live. Thanks!

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1357%23issuecomment-1009316900&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C8bdb29a382344291113308d9d4783c70%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774435159481618%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tbNCsghKgqpcWBW9uxjlayf2C%2B99KjlWWpo%2FS1fyT0c%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH64P24DVZWL6C2VF7TUVM6ZZANCNFSM5LUSBSZA&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C8bdb29a382344291113308d9d4783c70%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774435159481618%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TUUfYY5RkO92cZUwI17cFUqkNklQ2JGF2oJfAC1zKSI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C8bdb29a382344291113308d9d4783c70%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774435159491583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NAe7Jbk94gr8vBxt%2F938vCM0hGV2H%2F6ASva86%2Bawg4M%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C8bdb29a382344291113308d9d4783c70%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637774435159491583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OQXaRxR%2B4rUYH7enpn9cRMHE1OssQjKvnpQBP6V7K3g%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@bowlenj I moved the Royalty Valuation section to be after the 'Oil and Gas Reporting' section, since the RV presentation is about gas. Are you OK with that? Thanks!
