### ISSUE TITLE
Reporter Training Presentation

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1358]
Please add the attached presentation to the following page under Oil & Gas - https://www.onrr.gov/reportpay/training/index.htm

Basic 2014
[2014 Reporting 012022.pptx](https://github.com/ONRR/onrr.gov-site/files/7847418/2014.Reporting.012022.pptx)

**Comment by Maroyafaied** [comment]
@bowlenj Do you want the presentation titled to be "Basic 2014" or Form-2014 Basic Reporting Principles". Also, just wanted to let you know that the presenter notes are visible in the attachment, are you ok with that?

**Comment by bowlenj** [comment]
Let's do Form-2014 for the title.  Is it possible to load it as read only with just the presentation?

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Maroyafaied ***@***.***>
Sent: Tuesday, January 11, 2022 8:10 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Reporter Training Presentation (Issue #1358)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C9281eaa0ba394ec2edad08d9d51535b4%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637775109338533368%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Puwi6no2kosl9cvtdnTMmMWSMpvVnEdZI%2Ftaa0I1pbY%3D&reserved=0> Do you want the presentation titled to be "Basic 2014" or Form-2014 Basic Reporting Principles". Also, just wanted to let you know that the presenter notes are visible in the attachment, are you ok with that?

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1358%23issuecomment-1010057738&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C9281eaa0ba394ec2edad08d9d51535b4%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637775109338543326%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=44n5pdMwZSNM3ZXX7cF71qt0SExa7sKv5SuxKQ5iAD4%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH6L4YOM2YMGQDBOF7DUVRB65ANCNFSM5LWPX3ZQ&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C9281eaa0ba394ec2edad08d9d51535b4%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637775109338543326%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mqvCMg4WIjfZCAjp440GOunv8Od5l9Ov1ScwGwcY6Do%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C9281eaa0ba394ec2edad08d9d51535b4%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637775109338553280%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xmUZPmF4t1hPLbT3CySdcQIoHGwM9Y7FIz11bh3iVUc%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C9281eaa0ba394ec2edad08d9d51535b4%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637775109338553280%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fCMJTcLFqmSbOriaxBNZkp2rh3qpVbiGhSm3%2BvlMh24%3D&reserved=0>.

**Comment by Maroyafaied** [comment]
@bowlenj Please review. @mcharg please add this to the wireframes and content audit tracking sheet. Thanks

**Comment by Maroyafaied** [comment]
this is live
