### ISSUE TITLE
Updated Royalty Ecommerce and Electronic Tools

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1359]
Please replace the Royalty Ecommerce and Electronic Tools presentation with the attached - https://www.onrr.gov/reportpay/training/index.htm
[Ecommerce and Electronic Tools- Royalty-Revised (004) (1).pptx](https://github.com/ONRR/onrr.gov-site/files/7847919/Ecommerce.and.Electronic.Tools-.Royalty-Revised.004.1.pptx)
.

**Comment by Maroyafaied** [comment]
@bowlenj please review http://2017onrr/reportpay/training/index.htm

**Comment by bowlenj** [comment]
I'm sorry I didn't finish typing out the whole name, can you use the name you suggested for this one - Form-2014 Basic Reporting Principles

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Maroyafaied ***@***.***>
Sent: Tuesday, January 11, 2022 9:12 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Updated Royalty Ecommerce and Electronic Tools (Issue #1359)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1397aa2d25bb42ea806308d9d51dbbea%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637775145959100730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BUkQ%2FN%2ByQAtRv%2F19DvDIXfpsEbIi9EYDHLv0iLiOSlc%3D&reserved=0> please review http://2017onrr/reportpay/training/index.htm

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1359%23issuecomment-1010120154&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1397aa2d25bb42ea806308d9d51dbbea%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637775145959110685%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2vpi64qULLtUr2gkIH7Su8ap3pm6B8gRXDI4zancn6s%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH4VY2ZORB3ZYJLSDEDUVRJHNANCNFSM5LWU7HAA&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1397aa2d25bb42ea806308d9d51dbbea%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637775145959110685%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NPnYmGsStNYxf%2F7K95EMBTIK5Yj280B%2FyZ6RMUFuBJY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1397aa2d25bb42ea806308d9d51dbbea%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637775145959120641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=r94iceAWyb2lQie%2BTo0pIzCq6GV8MYQoKWJwyzLdpxM%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1397aa2d25bb42ea806308d9d51dbbea%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637775145959120641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ku82nsALNyOfXv6GvnxXuzZ65vIlRwc6pppnsz1v5%2FA%3D&reserved=0>.

**Comment by Maroyafaied** [comment]
@bowlenj no worries, please review the updated title http://2017onrr/reportpay/training/index.htm

**Comment by bowlenj** [comment]
I'm sorry, I think I'm getting things mixed up!  The Royalty Ecommerce and Electronic Tools looks great!

Can we name the Form 2014 what you originally suggested, Form-2014 Basic Reporting Principles

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Maroyafaied ***@***.***>
Sent: Tuesday, January 11, 2022 9:12 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Updated Royalty Ecommerce and Electronic Tools (Issue #1359)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1397aa2d25bb42ea806308d9d51dbbea%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637775145959100730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BUkQ%2FN%2ByQAtRv%2F19DvDIXfpsEbIi9EYDHLv0iLiOSlc%3D&reserved=0> please review http://2017onrr/reportpay/training/index.htm

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1359%23issuecomment-1010120154&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1397aa2d25bb42ea806308d9d51dbbea%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637775145959110685%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2vpi64qULLtUr2gkIH7Su8ap3pm6B8gRXDI4zancn6s%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH4VY2ZORB3ZYJLSDEDUVRJHNANCNFSM5LWU7HAA&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1397aa2d25bb42ea806308d9d51dbbea%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637775145959110685%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NPnYmGsStNYxf%2F7K95EMBTIK5Yj280B%2FyZ6RMUFuBJY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1397aa2d25bb42ea806308d9d51dbbea%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637775145959120641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=r94iceAWyb2lQie%2BTo0pIzCq6GV8MYQoKWJwyzLdpxM%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1397aa2d25bb42ea806308d9d51dbbea%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637775145959120641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ku82nsALNyOfXv6GvnxXuzZ65vIlRwc6pppnsz1v5%2FA%3D&reserved=0>.
