### ISSUE TITLE
Update Allottee Assistance page

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#136]
@lpgoldstein this is from ServiceNow. I'll forward the email to our shared box for contact info so you can follow up.

I found a change that needs to be made on our Allottee Assistance page, the link is below.

https://www.onrr.gov/IndianServices/index.htm [https://www.onrr.gov/IndianServices/index.htm]

Regarding Distribution dates there are two links.

Indian Distribution Dates for Current Calendar Year.  When you click on it, is has 2019 schedule.  This could be deleted.  Because below it is Indian Distribution Dates for Calendar Year 2020.  This one has the 2020 schedule.

If there is anyone I can notify to change this, please let me know.

Allottee Assistance [https://www.onrr.gov/IndianServices/index.htm]

**Comment by lpgoldstein** [comment]
@jennmalcolm Got it!

**Comment by lpgoldstein** [comment]
@jennmalcolm This is ready for your review. I confirmed the change with Marvin Hamsher and have sent the link to him as well. 
http://2017onrr/IndianServices/index.htm
http://2017onrr/IndianServices/tribal-assistance.htm
http://2017onrr/IndianServices/consultation.htm

**Comment by jennmalcolm** [comment]
Looks good. Thanks.
