### ISSUE TITLE
PAWNEE AREA VIRTUAL MEETING                               (To be added to Event Calendar on the Allottee Assistance Page)

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#1360]
PAWNEE AREA VIRTUAL MEETING
Wednesday, January 19, 2022
Time: 1:00 pm - 2:00 pm CST
Location: By Telephone 

Description: This meeting will be a Call-in Meeting to hear a presentation and updates from the Office of Natural Resources Revenue (ONRR) OKC Office.  Representatives from each of the four agencies including the BLM, BTFA, and the BIA will also be available to discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust property issues.  There will be an Q&A session available for owners to ask questions regarding their Indian Trust properties.

Who Should Attend:  IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Pawnee Agency Area, or any mineral owners located in the Southern Plains Region in Oklahoma.  
Other Information: To attend meeting you must contact the ONRR OKC Outreach office by calling toll-free (800) 354-7015 to reserve your space and to get the call-in number and passcode for the meeting.  A limited number of spaces will be available for this meeting so call and reserve your space as soon as possible. ONNR OKC Outreach office hours are Monday- Friday from 7:30 am-5:00 pm.
Event Contact:
Name: ONRR OKC Outreach Office 
Phone: Toll Free (800) 354-7015 or (405) 879-6050;        
Email:  onrroutreachokc@onrr.gov

 
**ALSO, PLEASE DELETE ALL NOVEMBER AND DECEMBER EVENTS FROM CALENDAR**

**Comment by Maroyafaied** [comment]
@toddsand21 please review http://2017onrr/events.htm

**Comment by Toddsand21** [comment]
Just one change in the last sentence in the first paragraph: replace "an" with "a" to read There will be a Q&A...  

No other corrections. Ready to post.

**Comment by Maroyafaied** [comment]
@Toddsand21 I made the change you requested, it's live.

**Comment by Toddsand21** [comment]
Thank you!
