### ISSUE TITLE
Reporter Training Slide Update for Audit

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1363]
Please replace the CMP 2014 presentation under Audit with the attached presentation at the following webpage - https://www.onrr.gov/reportpay/training/index.htm
[173_CMP2014_Industry_View_2022-01-13_v3.pptx](https://github.com/ONRR/onrr.gov-site/files/7856958/173_CMP2014_Industry_View_2022-01-13_v3.pptx)

**Comment by cthomasONRR** [comment]
@bowlenj The changes are on the dev site: http://2017onrr/reportpay/training/index.htm. Please review and give us your approval to go live. Thanks!

**Comment by bowlenj** [comment]
Looks great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, January 12, 2022 12:01 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Reporter Training Slide Update for Audit (Issue #1363)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf43cd9d511594a18a53d08d9d5fe816d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637776111336802443%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7oGx8yw4xhXYEeiwzZApQkBGwFiWuht0CpnFQdQrmp8%3D&reserved=0> The changes are on the dev site: http://2017onrr/reportpay/training/index.htm. Please review and give us your approval to go live. Thanks!

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1363%23issuecomment-1011359143&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf43cd9d511594a18a53d08d9d5fe816d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637776111336812397%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=G031P1awmi3sBQv%2FbOGVMrpZDuYfaLw6K8H4%2BlBAQqM%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH6YBDOSQME3LD2JLT3UVXFZ7ANCNFSM5LZXJ6PA&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf43cd9d511594a18a53d08d9d5fe816d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637776111336812397%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Q1%2Fa6MG0g5UZdxR83OWdoIKJdwLTBXQOWa1jeVejcvY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf43cd9d511594a18a53d08d9d5fe816d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637776111336822353%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FeHWKX74thIjyTeHYMPjhX2cOsEutZ5ByM1LOoPNwOY%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf43cd9d511594a18a53d08d9d5fe816d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637776111336822353%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PuyX%2BSacnLUtmiu4DwTCeDFaJWDrA5jVwqgEJ3%2BKBzc%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@bowlenj Great! The changes are now live: https://www.onrr.gov/reportpay/training/index.htm.
Closing this issue.
