### ISSUE TITLE
Reporter Training Solids Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1364]
Please remove the Federal & Indian Coal Valuation from the Solid Minerals section on the following webpage - https://www.onrr.gov/reportpay/training/index.htm

**Comment by cthomasONRR** [comment]
@bowlenj The changes are on the dev site: http://2017onrr/reportpay/training/index.htm.
Please review and give us your approval to go live. Thanks!

**Comment by bowlenj** [comment]
Perfect, thank you!


Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, January 12, 2022 12:28 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Reporter Training Solids Update (Issue #1364)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C45243bcfb94548f7448008d9d601cb24%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637776125464652369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HmEhDQfvS6jG4i%2BRENgsoiilukAZWfxsEceOve0Ok2c%3D&reserved=0> The changes are on the dev site: http://2017onrr/reportpay/training/index.htm.
Please review and give us your approval to go live. Thanks!

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1364%23issuecomment-1011380832&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C45243bcfb94548f7448008d9d601cb24%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637776125464652369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XnMdHebvtRZErzeN4t7E0VFvXKoOnS35PU0eT%2BVR%2Ffk%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH3FV2RI4Z42DMWQDSTUVXI7DANCNFSM5LZZRE7Q&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C45243bcfb94548f7448008d9d601cb24%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637776125464662318%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tgoOH7kNtziwdZ1cXwNgSfKSYaM4UyijhzU6FNiMUpE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C45243bcfb94548f7448008d9d601cb24%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637776125464662318%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2lmhNjIFVSJUNKsasdTLPKbxIR%2B7AFZPXPpzzB5dxiU%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C45243bcfb94548f7448008d9d601cb24%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637776125464672298%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Hi4la6Tyo7n7a%2FmM9sOKDdFl5NWPS5b9JN0OhXn0qf8%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@bowlenj Great! The changes are live: https://www.onrr.gov/reportpay/training/index.htm.

@mcharg @daniel-coleman-1 This needs to be updated on the wireframe and site map. Thanks!

**Comment by mcharg** [comment]
@cthomasONRR Removed from wireframes and tracking sheet.
