### ISSUE TITLE
update penalty amount 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1366]
This request came from Sam through email. @cthomasONRR please send Sam the dev link to review the updates. Thanks

 The Federal Register came out today, updating our penalty amounts. Would you be able to assist us in updating our external page with the following changes?

 

URL: https://www.onrr.gov/compliance/civil-penalties.htm

 

In the second paragraph, please update the penalty amounts as follows (in bold):

 

ONRR regulations at 30 CFR part 1241 provide a cure period of at least 20 days for regulatory violations such as failure to submit reports. Violations not cured within the period are subject to civil penalty assessments, until they are cured, of as much as **$1,368.00** per day (**$13,693.00** per day after 40 days).

 

In the third paragraph, please update the penalty amounts as follows (in bold):

 

However, certain violations such as failure to permit an audit, failure to timely pay royalties, or submission/maintenance of false, inaccurate, or misleading information are subject to civil penalty assessments of as much as **$27,384.00** or **$68,462.00** per violation for each day the violation continues. Some violations are also crimes under Title 18, U.S.C. or False Claims under 31 U.S.C. 3729. ONRR works in partnership with the Department’s Office of the Inspector General and the U.S. Attorney’s Office in pursuing these violations.

**Comment by cthomasONRR** [comment]
Emailed Sam the dev site and awaiting his approval to go live.

**Comment by cthomasONRR** [comment]
The changes are now live and I emailed Sam letting him know. Closing this issue now.
