### ISSUE TITLE
Set up redirect for contact pdf that changed to a doc

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1367]
Since many people are likely to have it bookmarked.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/505ca1bd-4e86-450b-abab-b2d7da1dacb4)

**Comment by mcharg** [comment]
Updated in dev.  @codyeckstein @cthomasONRR Can you please review before I push live?
http://2017onrr/ReportPay/PDFDocs/FSFederalCOAssignm.pdf

I also updated this one that was set to redirect to the old pdf.
http://2017onrr/ReportPay/PDFDocs/finserassign.pdf

**Comment by codyeckstein** [comment]
Looks good. We should remind them to change the "Updated 11/17/2021" next time

**Comment by cthomasONRR** [comment]
@mcharg Both redirects work for me!

**Comment by mcharg** [comment]
Pushed live.  Will check to make sure it's working in 30 minutes.
https://www.onrr.gov/ReportPay/PDFDocs/FSFederalCOAssignm.pdf
https://www.onrr.gov/ReportPay/PDFDocs/finserassign.pdf

**Comment by mcharg** [comment]
Working in the live site.
