### ISSUE TITLE
Reupload formatted NYMEX files to onrr.gov 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1369]

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 here is the files where the nymex files were updated from 2011 to prior .https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Collections/NYMEX?csf=1&web=1&e=YMIaDl

**Comment by daniel-coleman-1** [comment]
@Maroyafaied this page is ready for your review:
http://2017onrr/valuation/NYMEX.htm

With your approval I will push changes to the live site.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I only checked a couple of files, they look fine. You can push live.

**Comment by daniel-coleman-1** [comment]
We are live:
https://onrr.gov/valuation/NYMEX.htm
