### ISSUE TITLE
Page: Home Page

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1384]
https://dev-onrr-frontend.app.cloud.gov/
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/1
https://qmcq5k.axshare.com/#id=e1wh3o&p=home_v3

**Comment by mcharg** [comment]
We need to add all the hyperlinks.

@jlouis-onrr Is this something you do programmatically or can one of us do it manually?

**Comment by Maroyafaied** [comment]
@mcharg Please review, I've added all the links except for the 4444 pdf. For NYMEX oil prices, I linked to the page and removed the "(xls)" for now.  For the Dear Reporter letter link under Announcements, I used the dev site link .. not sure how to link from a collection?  https://dev-onrr-frontend.app.cloud.gov/?tab=pricing

**Comment by mcharg** [comment]
@Maroyafaied I changed the link for NYMEX to https://dev-onrr-frontend.app.cloud.gov/references/valuation?tab=nymex-oil-prices since it won't be the first tab on pricing when we move it to it's final location.  It doesn't work right now because it's a sub-tab, so I added that issue as a dependency.

**Comment by mcharg** [comment]
@Maroyafaied I also updated the link in the first announcement to go to the Indian Outreach tab instead of Assistance.  All the other links work.

**Comment by mcharg** [comment]
@Maroyafaied I fixed the two links to the 4444 and the link to the NYMEX tab on the homepage. I think it's good for full ODDD approval.

**Comment by mcharg** [comment]
Note: I dropped the icon for the 4444 docs because they broke the spacing. I use "(pdf)" at the end of the title instead. https://dev-onrr-frontend.app.cloud.gov/

**Comment by Maroyafaied** [comment]
@mcharg everything looks good except these links don't work, I fixed the links in the announcement for Indian outreach & the mineral owners link. 
![image](https://user-images.githubusercontent.com/40175688/158898469-7c2b0afb-1343-48a4-b8c9-9d077652756e.png)

**Comment by mcharg** [comment]
The links to those docs on the Reporter Letters and Press Releases pages are also broken. I looked in the CMS and the docs are there.  @jlouis-onrr @mojobnichols Any idea what's going on? Those links did work at one point.

**Comment by mcharg** [comment]
@cthomasONRR The reporter letter and press releases links are fixed, so I think the homepage is ready for ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg I went thought all the links. The only minor thing I see is that this dear reporter letter is displaying the old url:
![image](https://user-images.githubusercontent.com/72526208/163400700-f401044f-8b0f-408b-a9b8-f0ffb7a04764.png)

**Comment by mcharg** [comment]
@cthomasONRR We have a separate issue for the announcements collection. I'll add the reporter letter links issue as a dependency on that and we can close this one.
