### ISSUE TITLE
Page: Getting Started Home

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1386]
https://dev-onrr-frontend.app.cloud.gov/getting-started
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/9
https://qmcq5k.axshare.com/#id=o52v1g&p=getting_started

**Comment by mcharg** [comment]
I started this one.

**Comment by mcharg** [comment]
@Maroyafaied This one could be done and ready for approval if we decide not to do the checklist logic at launch. https://dev-onrr-frontend.app.cloud.gov/getting-started

**Comment by Maroyafaied** [comment]
@mcharg Yes, we can launch without that logic, and added that enhancement feature later. Let's add links to the actual new reporter checklist though and take out the "build me a checklist".

**Comment by mcharg** [comment]
@Maroyafaied I created #1733 to put tabs for each product in the new reporter checklist that copies what we have in the ones in Reporting.

**Comment by mcharg** [comment]
@cthomasONRR This is ready for ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg Button works! Approving.
