### ISSUE TITLE
Page: How Leasing Works

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1387]
https://dev-onrr-frontend.app.cloud.gov/getting-started/how-leasing-works
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/10
https://qmcq5k.axshare.com/#id=1t0m2d&p=how_leasing_works

**Comment by mcharg** [comment]
I need to save off the images to png for this one.

**Comment by Maroyafaied** [comment]
@mcharg let me know when images are saved. Thanks

**Comment by mcharg** [comment]
Attribution for disbursements icon (maybe put it in the caption field for now):
Money Distribution by Xinh Studio from NounProject.com

The rest are all CFPB and don't require attribution.
![Lease.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/f466767f-f859-49f7-9671-2ce25fa948e5)
![Disbursements.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/7b77c61e-2a78-4152-8bd1-43535b45d8d1)
![Compliance.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/0ac9c74f-4ef7-4b1d-8b92-53400da339d5)
![Reporting.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/cf7210d4-ac57-4b7d-98ee-c559a450b2f3)

**Comment by Maroyafaied** [comment]
@mcharg This is ready for your review, I did my best with it but let me know if you think there's other ways to make it look better. https://dev-onrr-frontend.app.cloud.gov/getting-started/how-leasing-works

**Comment by mcharg** [comment]
@Maroyafaied I think this looks good until we get better control over image sizing.

**Comment by Maroyafaied** [comment]
@mcharg ya I agree, it's the best we can do for now.

**Comment by mcharg** [comment]
Added alt text.  @lpgoldstein This one is ready for ODDD approval.

**Comment by lpgoldstein** [comment]
@mcharg I approve
