### ISSUE TITLE
Page: New Reporter Checklist

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1388]
https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklisthttps://dev-onrr-cms.app.cloud.gov/admin/content/pages/11
https://qmcq5k.axshare.com/#id=muwj32&p=new_reporter_checklist

**Comment by mcharg** [comment]
Added panels.  Blocked by not being able to link to documents or having logic.
https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist

**Comment by mcharg** [comment]
@cthomasONRR Links to docs are ready to review. Will need logic before final ODDD approval.

**Comment by mcharg** [comment]
@cthomasONRR Hold off on this one. I'm going to put in tabs in place of the logic, so we can wait until after launch for logic.

**Comment by mcharg** [comment]
@cthomasONRR Doc links are ready to review.

**Comment by cthomasONRR** [comment]
@mcharg approved

**Comment by cthomasONRR** [comment]
@mcharg I think this page is complete and ready for approval?

**Comment by mcharg** [comment]
@cthomasONRR We still need buttons for the EMARF.

**Comment by mcharg** [comment]
@cthomasONRR This is ready for ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg Looks good, approved
