### ISSUE TITLE
Create consistent link styles 

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/onrr.gov-site#139]
Link styles 

Related to contrast, color should not be the only indication of the presence of a link. For people who are color blind or visually impaired, the links can be lost in the text. For links to be accessible, they should have a secondary visual characteristic (commonly underline) to distinguish them from other text. 
![image](https://user-images.githubusercontent.com/39419003/80116527-15efb700-8554-11ea-8324-ace22bf6e4fc.png)

**Comment by jennmalcolm** [comment]
Closing in favor of #154
