### ISSUE TITLE
Tab: System Access > Setting Up Access

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1390]
https://dev-onrr-frontend.app.cloud.gov/getting-started/system-access
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/12
https://qmcq5k.axshare.com/#id=uy4lvh&p=system_access

**Comment by Maroyafaied** [comment]
@mcharg this is ready for review. https://dev-onrr-frontend.app.cloud.gov/getting-started/system-access

**Comment by mcharg** [comment]
@Maroyafaied Looks good.  Moving to backlog until we can link to docs.

**Comment by mcharg** [comment]
@cthomasONRR Docs are ready to review on this page.

**Comment by mcharg** [comment]
@cthomasONRR This is ready for ODDD approva.

**Comment by cthomasONRR** [comment]
@mcharg Approved
