### ISSUE TITLE
Page: New Reporter Training

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1394]
https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-training
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/13
https://qmcq5k.axshare.com/#id=tgwtqb&p=new_reporter_training&g=1

**Comment by daniel-coleman-1** [comment]
@mcharg is this the correct format to link to pages within the CMS?
![Screenshot 2022-02-10 090944](https://user-images.githubusercontent.com/83892362/153448280-c8bcf6cb-f576-4565-af4e-82fe76f1fbff.png)

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 you have to link to the page url which is /references/training

**Comment by daniel-coleman-1** [comment]
@Maroyafaied am I adding a ".htm" to the end?

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 no

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 Ok, moving it to backlog.

**Comment by mcharg** [comment]
@cthomasONRR This is ready for ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg Approved
