### ISSUE TITLE
Page: Reporting Home

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1395]
https://dev-onrr-frontend.app.cloud.gov/reporting
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/4
https://qmcq5k.axshare.com/#id=oy6t9q&p=reporting&g=1

**Comment by mcharg** [comment]
I started this one.

**Comment by mcharg** [comment]
@cthomasONRR This is ready for ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg approved
