### ISSUE TITLE
Tab: Production > File Reports

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1396]
https://dev-onrr-frontend.app.cloud.gov/reporting/production
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/19
https://qmcq5k.axshare.com/#id=sw7sll&p=oil___gas_production&g=1

**Comment by mcharg** [comment]
I got this one as far as I could.

**Comment by mcharg** [comment]
@cthomasONRR File Reports tab is ready to review.
https://dev-onrr-frontend.app.cloud.gov/reporting/production

**Comment by cthomasONRR** [comment]
@mcharg All content looks good.
