### ISSUE TITLE
Tab: Production > Forms

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1397]
https://dev-onrr-frontend.app.cloud.gov/reporting/production
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/19
https://qmcq5k.axshare.com/#id=sw7sll&p=oil___gas_production&g=1

Also:
https://dev-onrr-frontend.app.cloud.gov/references/forms?tab=oil-gas-production-reporting
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/47
https://qmcq5k.axshare.com/#id=6zhm0q&p=forms&g=1

**Comment by mcharg** [comment]
I got this one as far as I could.

**Comment by mcharg** [comment]
Documents uploaded. Waiting for Excel icon for one file.

**Comment by mcharg** [comment]
@cthomasONRR The pdfs are ready to review. Waiting on Excel icon before adding the Excel file.

**Comment by cthomasONRR** [comment]
Looks good.

**Comment by cthomasONRR** [comment]
All good except the last link. This should be teh PASR CSV Record Layout. Right now it's the same ASCII file as listed above.
![image](https://user-images.githubusercontent.com/72526208/158886393-35c378e5-d8ca-4a54-b093-e0c9f17b247d.png)

**Comment by mcharg** [comment]
@cthomasONRR Fixed to link to CSV. https://dev-onrr-frontend.app.cloud.gov/references/forms?tabs=oil-gas-production-reporting

**Comment by cthomasONRR** [comment]
@mcharg Thanks! I have all the docs and the page set to approved by oddd :)
