### ISSUE TITLE
Tab: Production > References

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1398]
https://dev-onrr-frontend.app.cloud.gov/reporting/production
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/19
https://qmcq5k.axshare.com/#id=sw7sll&p=oil___gas_production&g=1

**Comment by mcharg** [comment]
@cthomasONRR Links are ready to review. There are two reporter letter links in the reporting codes section that I was able to hard code link, but the icons won't display until we get them added to the links builder.
https://dev-onrr-frontend.app.cloud.gov/reporting/production?tabs=references

**Comment by cthomasONRR** [comment]
@mcharg I approved all docs listed as ready on the spreadsheet... those two reporter letter links in the reporting codes section still have the old url for me.

**Comment by mcharg** [comment]
Moving to backlog until additional blockers are cleared.

**Comment by mcharg** [comment]
Reporter letter links added. Waiting on link list fix to fix double pdf icons.

**Comment by mcharg** [comment]
@cthomasONRR This is ready for full ODDD approva.

**Comment by cthomasONRR** [comment]
@mcharg These are good- all DRL are pointing to /reporter-letters/ . Approved :)

![image](https://user-images.githubusercontent.com/72526208/167864044-14acb302-5829-4a36-b825-56d26629e11a.png)
example:
![image](https://user-images.githubusercontent.com/72526208/167864121-46bfc790-82d5-4d8e-aa69-5e61f85e2d5c.png)
