### ISSUE TITLE
Tab: Production > New Reporter Checklist

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1399]
https://dev-onrr-frontend.app.cloud.gov/reporting/production
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/19
https://qmcq5k.axshare.com/#id=sw7sll&p=oil___gas_production&g=1

**Comment by mcharg** [comment]
Got the panels all created.  Blocked by not being able to link to documents.
https://dev-onrr-frontend.app.cloud.gov/reporting/production?tab=new-reporter-checklist

**Comment by mcharg** [comment]
@cthomasONRR Links are ready to review. Just need button before final ODDD Approval.

**Comment by mcharg** [comment]
Moving to backlog until we get the button.

**Comment by mcharg** [comment]
@cthomasONRR This is ready for ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg Approved
