### ISSUE TITLE
Tab: Production > Contacts

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1401]
https://dev-onrr-frontend.app.cloud.gov/reporting/production
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/19
https://qmcq5k.axshare.com/#id=sw7sll&p=oil___gas_production&g=1

Also:
https://qmcq5k.axshare.com/#id=bhj7vh&p=oil___gas_production_1&g=1

**Comment by mcharg** [comment]
@cthomasONRR This is ready to review.

**Comment by cthomasONRR** [comment]
Will there be a-z hyperlinks? This was really difficult to review.

**FOR ONSHORE:**

The following entries are at the very last page in dev, and NOT in alphabetical order. I thought they were missing while reviewing the pages in numerical order.
-  Companies starting with: CA - CRA 
-  Companies starting with: CRB - CZ
- Companies starting with: O
- Companies starting with: W

The following entries are difference between dev and the wireframes:
- Companies starting with: E, P, Q, R, U, V, O, W

**Comment by cthomasONRR** [comment]
@mcharg I'm getting really overwhelmed and not sure how to review offshore production

**Comment by cthomasONRR** [comment]
@mcharg 

**Offshore**
Operator numbers that are with the company name in the wireframes need to be added to dev:
![image](https://user-images.githubusercontent.com/72526208/162760260-8aad2c32-68ea-4d11-b4b9-54cd413bd673.png)

**Comment by mcharg** [comment]
I added #1820 to add the operator number.

**Comment by mcharg** [comment]
@cthomasONRR It would probably be better to review against the spreadsheet instead of the wireframe, since we've been updating that and not the wireframes when contacts change.

**Comment by mcharg** [comment]
It'll be easier to navigate once the search is added.

**Comment by cthomasONRR** [comment]
@mcharg For **onshore** in dev, there needs to be some reorganization. The "C's" are missing in the alphabetical order, and are on the last page. Same with "O" and "W"
![image](https://user-images.githubusercontent.com/72526208/162766888-e107572e-e955-4f8f-a890-555151f13fe0.png)
I created a pivot in the spreadsheet to more efficiently check names. Names are now matching up.

**Comment by mcharg** [comment]
@jlouis-onrr Can you look into how the contacts are sorting?

**Comment by cthomasONRR** [comment]
@mcharg The sorting is fixed. Should I go ahead and approve, or wait till offshore operator # is included?

**Comment by cthomasONRR** [comment]
@mcharg Great, I just set these as approved in the spreadsheet.

**Comment by mcharg** [comment]
@cthomasONRR Jerome did actually put in the operator numbers. https://dev-onrr-frontend.app.cloud.gov/reporting/production?tabs=contacts,offshore-production
