### ISSUE TITLE
Page: Oil & Gas Revenue

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1402]
https://dev-onrr-frontend.app.cloud.gov/reporting/revenue
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/41
https://qmcq5k.axshare.com/#id=5ud60e&p=oil___gas_revenue&g=1

**Comment by mcharg** [comment]
This issue is to add tabs.  Created separate issues for each tab.

**Comment by mcharg** [comment]
@cthomasONRR Tabs are ready to review. https://dev-onrr-frontend.app.cloud.gov/reporting/revenue

**Comment by cthomasONRR** [comment]
@mcharg The tabs look good. I signed off in the Content Tracking sheet.
