### ISSUE TITLE
Tab: Oil & Gas Revenue > File Reports

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1403]
https://dev-onrr-frontend.app.cloud.gov/reporting/revenue
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/41
https://qmcq5k.axshare.com/#id=5ud60e&p=oil___gas_revenue&g=1

**Comment by mcharg** [comment]
@cthomasONRR File Reports tab is ready to review.
https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tab=file-reports

**Comment by cthomasONRR** [comment]
@mcharg All content looks good.
