### ISSUE TITLE
Tab: Revenue > Forms

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1404]
https://dev-onrr-frontend.app.cloud.gov/reporting/revenue
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/41
https://qmcq5k.axshare.com/#id=5ud60e&p=oil___gas_revenue&g=1

Also:
https://dev-onrr-frontend.app.cloud.gov/references/forms?tab=oil-gas-revenue-reporting
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/47
https://qmcq5k.axshare.com/#id=6zhm0q&p=forms&g=1

**Comment by mcharg** [comment]
Added content to both pages.  Blocked by being able to link to docs.
https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tab=forms
https://dev-onrr-frontend.app.cloud.gov/references/forms?tab=oil-gas-revenue-reporting

**Comment by mcharg** [comment]
Documents added. Waiting on Excel icon for one.

**Comment by mcharg** [comment]
@cthomasONRR PDFs are ready to review.

**Comment by cthomasONRR** [comment]
@mcharg One kind of weird PDF icon placement, but otherwise looks good
![image](https://user-images.githubusercontent.com/72526208/157285174-58af0193-2586-4f90-93d1-8f2c1d83b6f5.png)

**Comment by mcharg** [comment]
Created #1694 for the wrapping issue.

**Comment by mcharg** [comment]
@cthomasONRR Docs are ready to review and ready for full ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg Everything looks good. Set the docs and page as 'approved by oddd' Yay :)
