### ISSUE TITLE
Tab: Revenue > References

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1405]
https://dev-onrr-frontend.app.cloud.gov/reporting/revenue
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/41
https://qmcq5k.axshare.com/#id=5ud60e&p=oil___gas_revenue&g=1

Also:
https://dev-onrr-frontend.app.cloud.gov/references/reference-lists
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/48
https://qmcq5k.axshare.com/#id=1f6ois&p=reference_lists___codes&g=1

**Comment by mcharg** [comment]
I'm not sure where I got the reporting code diagram and can't find it on the live site.  Will need to figure out how to get a higher resolution version of it.

**Comment by mcharg** [comment]
Got as far as I can without linking docs.
https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tab=references
https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tab=revenue-reporting-references

**Comment by mcharg** [comment]
@lpgoldstein Links are ready to review. Waiting on button, reporter letters, and video icon before final approval.

**Comment by lpgoldstein** [comment]
@mcharg Should both of these links go to the same place? 
![image](https://user-images.githubusercontent.com/39419003/159145685-48419aa0-7515-4032-a3b5-78b3a207241e.png)

**Comment by mcharg** [comment]
@lpgoldstein I fixed the links to the videos.

**Comment by lpgoldstein** [comment]
@mcharg looks good!

**Comment by cthomasONRR** [comment]
@mcharg Just a thought - when we can move cards again, it might be nice to move the reporting code diagram card last so it can be the width of the page. Then Reference Lists, Instructions, and Reporter Letters cards could all be in-line with each other.

![image](https://user-images.githubusercontent.com/72526208/167148694-38f8b059-4b57-4c2f-976c-a8c7ba9c94cc.png)

**Comment by cthomasONRR** [comment]
@mcharg Approved
