### ISSUE TITLE
Tab: Revenue > New Reporter Checklist

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1406]
https://dev-onrr-frontend.app.cloud.gov/reporting/revenue
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/41
https://qmcq5k.axshare.com/#id=5ud60e&p=oil___gas_revenue&g=1

**Comment by mcharg** [comment]
Added all the panels.  Blocked by not being able to link to documents.
https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tab=new-reporter-checklist

**Comment by mcharg** [comment]
@cthomasONRR Links are ready to review. Just need button before final ODDD Approval.

**Comment by cthomasONRR** [comment]
@mcharg Links look good. Approved.

**Comment by mcharg** [comment]
Moving to backlog until we get the button.

**Comment by mcharg** [comment]
@cthomasONRR This is ready for ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg Approved
