### ISSUE TITLE
Tab: Revenue > Troubleshooting

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1407]
https://dev-onrr-frontend.app.cloud.gov/reporting/revenue
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/41
https://qmcq5k.axshare.com/#id=5ud60e&p=oil___gas_revenue&g=1

Also:
https://qmcq5k.axshare.com/#id=its4or&p=oil___gas_royalty&g=1

**Comment by mcharg** [comment]
This is as far as I can get without linking to docs.
https://dev-onrr-frontend.app.cloud.gov/about/contact/royalty-contacts?tab=troubleshooting

**Comment by mcharg** [comment]
@cthomasONRR Links are ready to review. https://dev-onrr-frontend.app.cloud.gov/about/contact/royalty-contacts?tabs=troubleshooting

**Comment by cthomasONRR** [comment]
Docs look good - approved

**Comment by mcharg** [comment]
@cthomasONRR This is ready for ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg Approved
