### ISSUE TITLE
Page: Solid Minerals

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1409]
https://dev-onrr-frontend.app.cloud.gov/reporting/solids
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/42
https://qmcq5k.axshare.com/#id=hi0nnh&p=solid_minerals&g=1

**Comment by mcharg** [comment]
Add tabs to the page.  Separate issues for each tab.

**Comment by mcharg** [comment]
@cthomasONRR Tabs are ready to review

**Comment by cthomasONRR** [comment]
@mcharg Tabs look good
