### ISSUE TITLE
Delete third party tools - AddThis 

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/onrr.gov-site#141]
The site also includes a utility triggered by scroll depth that produces “Recommendations,” a utility from “AddThis,” a product from Oracle. The user benefit of this is unclear to me, as the recommended pages don’t appear to be related to the content the user is looking at presently. In this instance, a page for reporting forms produces a recommendation for Public Affairs and Office Locations: 

 
![image](https://user-images.githubusercontent.com/39419003/80117348-16d51880-8555-11ea-9f72-332f80519d50.png)

 

 
From a certain point of view, everything on the site is “related,” but the relationship here feels random. 

 

Sometimes, the utility loads nothing at all, resulting in the message “Server Error.” 

 

 

 

The utility panel also covers up the content behind it. This can be problematic, especially if the page is scrolled all the way to the bottom, obscuring the content behind. A user can collapse the panel, but the user interface element to do so is inconspicuous (a small, grey arrow only present when hovering over the panel). 

 

With an observed load-time performance hit, this utility needs to be evaluated for user benefit. If it provides measurable user value, it could offset the negative performance impacts. My suspicion is that the user benefit (if any) isn’t sufficient to merit this utility.

**Comment by jennmalcolm** [comment]
done
