### ISSUE TITLE
Tab: Solid Minerals > File Reports

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1410]
https://dev-onrr-frontend.app.cloud.gov/reporting/solids
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/42
https://qmcq5k.axshare.com/#id=hi0nnh&p=solid_minerals&g=1

**Comment by mcharg** [comment]
@cthomasONRR File Reports tab is ready to review.
https://dev-onrr-frontend.app.cloud.gov/reporting/solids?tab=file-reports

**Comment by cthomasONRR** [comment]
@mcharg All content looks good.
