### ISSUE TITLE
Tab: Solid Minerals > Forms

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1411]
https://dev-onrr-frontend.app.cloud.gov/reporting/solids
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/42
https://qmcq5k.axshare.com/#id=hi0nnh&p=solid_minerals&g=1

Also:
https://dev-onrr-frontend.app.cloud.gov/references/forms?tab=solid-minerals-reporting
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/47
https://qmcq5k.axshare.com/#id=6zhm0q&p=forms&g=1

**Comment by mcharg** [comment]
Added cards in both places.  Blocked by not being able to add documents.
https://dev-onrr-frontend.app.cloud.gov/references/forms?tab=solid-minerals-reporting
https://dev-onrr-frontend.app.cloud.gov/reporting/solids?tab=forms

**Comment by mcharg** [comment]
@cthomasONRR PDFs are ready to review. Needs to go back into backlog after review until we get the button component.

**Comment by mcharg** [comment]
@cthomasONRR Links ready to review. Still need button.

**Comment by cthomasONRR** [comment]
@mcharg Approved all documents. Looks good.

**Comment by mcharg** [comment]
Moving to backlog until we get button component.
