### ISSUE TITLE
Tab: Solid Minerals > References

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1412]
https://dev-onrr-frontend.app.cloud.gov/reporting/solids
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/42
https://qmcq5k.axshare.com/#id=hi0nnh&p=solid_minerals&g=1

**Comment by mcharg** [comment]
Got as far as I can without being able to add docs.
https://dev-onrr-frontend.app.cloud.gov/reporting/solids?tab=references

**Comment by mcharg** [comment]
@lpgoldstein Links are ready to review. Need video icon before full approval.

**Comment by lpgoldstein** [comment]
@mcharg same comments as in geothermal references - but everything else works!

**Comment by mcharg** [comment]
Moving back to backlog until we get button and ability to link to reporter letters.

**Comment by mcharg** [comment]
@cthomasONRR This page is ready for ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg Approved
