### ISSUE TITLE
Tab: Solid Minerals > Troubleshooting

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1414]
https://dev-onrr-frontend.app.cloud.gov/reporting/solids
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/42
https://qmcq5k.axshare.com/#id=hi0nnh&p=solid_minerals&g=1

Also:
https://qmcq5k.axshare.com/#id=5f8bk2&p=solid_minerals_1&g=1

**Comment by mcharg** [comment]
Got this as far as I could without linking to docs.
https://dev-onrr-frontend.app.cloud.gov/about/contact/solids-contacts?tab=troubleshooting

**Comment by mcharg** [comment]
@cthomasONRR Docs are ready to review.

**Comment by mcharg** [comment]
@cthomasONRR This is ready for ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg Approved
