### ISSUE TITLE
Tab: Solid Minerals > Contacts

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1415]
https://dev-onrr-frontend.app.cloud.gov/reporting/solids
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/42
https://qmcq5k.axshare.com/#id=hi0nnh&p=solid_minerals&g=1

Also:
https://qmcq5k.axshare.com/#id=5f8bk2&p=solid_minerals_1&g=1

**Comment by mcharg** [comment]
@cthomasONRR This is ready to review.

**Comment by cthomasONRR** [comment]
@mcharg Approved
