### ISSUE TITLE
Tab: Geothermal > Forms

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1418]
https://dev-onrr-frontend.app.cloud.gov/reporting/geothermal
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/43
https://qmcq5k.axshare.com/#id=up0lnh&p=geothermal&g=1

Also:
https://dev-onrr-frontend.app.cloud.gov/references/forms?tab=geothermal-reporting
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/47
https://qmcq5k.axshare.com/#id=6zhm0q&p=forms&g=1

**Comment by mcharg** [comment]
Added cards in both places reusing content from revenue tab. Blocked by not being able to add documents.
https://dev-onrr-frontend.app.cloud.gov/reporting/geothermal?tab=forms
https://dev-onrr-frontend.app.cloud.gov/references/forms?tab=geothermal-reporting

**Comment by mcharg** [comment]
Documents added. Waiting on Excel icon for one.

**Comment by mcharg** [comment]
@cthomasONRR PDFs are ready to review.

**Comment by cthomasONRR** [comment]
@mcharg Looks good

**Comment by mcharg** [comment]
@cthomasONRR Ready for full ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg Looks good. Approved all docs and the page.
