### ISSUE TITLE
Tab: Geothermal > References

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1419]
https://dev-onrr-frontend.app.cloud.gov/reporting/geothermal
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/43
https://qmcq5k.axshare.com/#id=up0lnh&p=geothermal&g=1

**Comment by mcharg** [comment]
Got as far as I could before hitting blockers.
https://dev-onrr-frontend.app.cloud.gov/reporting/geothermal?tab=references

**Comment by mcharg** [comment]
@lpgoldstein Links are ready to review.

**Comment by lpgoldstein** [comment]
@mcharg these are the ones that don't work and I think we discussed but I wanted to document. [eCommerce FAQ](https://onrrreporting.onrr.gov/Help/FAQs.aspx)
[Form 2014 Training Videos](https://dev-onrr-cms.app.cloud.gov/references/training?tab=oil-gas-revenue)
![image](https://user-images.githubusercontent.com/39419003/159145269-acc578e1-b2bb-40ce-9df2-5890f7235e46.png)
![image](https://user-images.githubusercontent.com/39419003/159145280-246bda9c-5712-45b2-a56b-0b6ff19607e4.png)

**Comment by lpgoldstein** [comment]
@mcharg approved

**Comment by mcharg** [comment]
Moving to backlog until we get button and ability to link to reporter letters.

**Comment by mcharg** [comment]
@cthomasONRR This page is ready for ODDD approval.

**Comment by cthomasONRR** [comment]
This link does not work: 
![image](https://user-images.githubusercontent.com/72526208/167146969-67f82a3d-de96-4654-a945-060cb8919785.png)

**Comment by mcharg** [comment]
@cthomasONRR Fixed

**Comment by cthomasONRR** [comment]
@mcharg Thanks! Approved.
