### ISSUE TITLE
Get rid of embedded twitter feed

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/onrr.gov-site#142]
From Ryan: It’s unclear to me why this Twitter feed is embedded here.  

There’s no question the site takes a performance hit with this, requiring load time to pull it in.  

Since ONRR has its own Twitter account, it’s unclear why the DOI feed is present instead. The use of the acronym “DOI” in “DOI Tweets” also isn’t ideal, since it’s never defined on the site and the branding isn’t that of the Department of the Interior. 

Does it provide user value? It’s unclear, but this content is readily available elsewhere (namely on Twitter) and probably more intuitively accessed there (or in one’s Twitter feed). 

The embedded DOI Twitter feed is even more baffling because the other Twitter link on the page, in the header, links to ONRR’s Twitter account.

**Comment by mcharg** [comment]
Also, nobody clicks on this according to analytics.

**Comment by Maroyafaied** [comment]
@mcharg are you referring to this section? I just want to make sure. 
![image](https://user-images.githubusercontent.com/40175688/85742562-9354b680-b6c0-11ea-99ad-143c47593c5b.png)

**Comment by mcharg** [comment]
Yes

**Comment by Maroyafaied** [comment]
http://2017onrr/

**Comment by jennmalcolm** [comment]
This is done
