### ISSUE TITLE
Tab: Geothermal > New Reporter Checklist

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1420]
https://dev-onrr-frontend.app.cloud.gov/reporting/geothermal
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/43
https://qmcq5k.axshare.com/#id=up0lnh&p=geothermal&g=1

**Comment by mcharg** [comment]
Exact same content as Revenue, so was able to just reuse the entire expansion panel block.
https://dev-onrr-frontend.app.cloud.gov/reporting/geothermal?tab=new-reporter-checklist

**Comment by mcharg** [comment]
@cthomasONRR Links are ready to review. Just need button before final ODDD Approval.

**Comment by cthomasONRR** [comment]
@mcharg Links look good. Approved.

**Comment by mcharg** [comment]
Moving to backlog until we get the button.

**Comment by mcharg** [comment]
@cthomasONRR This is ready for ODDD approval.
