### ISSUE TITLE
Tab: Geothermal > Troubleshooting

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1421]
https://dev-onrr-frontend.app.cloud.gov/reporting/geothermal
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/43
https://qmcq5k.axshare.com/#id=up0lnh&p=geothermal&g=1

Also:
https://qmcq5k.axshare.com/#id=b5lzlu&p=geothermal_1&g=1

**Comment by mcharg** [comment]
Got as far as I could without linking docs. /about/contact/geothermal-contacts?tab=troubleshooting

**Comment by mcharg** [comment]
@cthomasONRR Links are ready to review. https://dev-onrr-frontend.app.cloud.gov/about/contact/geothermal-contacts?tabs=troubleshooting

**Comment by cthomasONRR** [comment]
@mcharg 

In the first accordion, these 2 links are missing: 
![image](https://user-images.githubusercontent.com/72526208/159080037-8066c7d1-3835-490b-9026-dc395ef589f5.png)

In the 3rd to last accordion (lease and agreement number), the "Indian Leases Cross-walked to Distributee Codes" excel is listed on the spreadsheet as bring present, but it is not on the dev site. Should it be on this card?
![image](https://user-images.githubusercontent.com/72526208/159080175-8eb3ec28-014a-4d27-bbf3-ea94925140c9.png)

**Comment by mcharg** [comment]
@cthomasONRR the missing links should be there now, I forgot to save my changes.

**Comment by mcharg** [comment]
@cthomasONRR The Indian one should be there. I'll fix it on Monday. It's not an easy fix to add a bullet in the middle of the list.

**Comment by cthomasONRR** [comment]
@mcharg Great, I approved the 2 in the Training Presentations card, but don't see the one missing from the Reference Lists card I have above... does that Indian lease cross-walk need to be here in Geothermal?

**Comment by mcharg** [comment]
@cthomasONRR Added the missing link.

**Comment by cthomasONRR** [comment]
@mcharg Great! Approved that doc in the spreadsheet. I think this can go to the backlog now.

**Comment by mcharg** [comment]
@cthomasONRR This is ready for ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg Approved
