### ISSUE TITLE
Tab: Geothermal > Contacts

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1422]
https://dev-onrr-frontend.app.cloud.gov/reporting/geothermal
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/43
https://qmcq5k.axshare.com/#id=up0lnh&p=geothermal&g=1

https://qmcq5k.axshare.com/#id=b5lzlu&p=geothermal_1&g=1

**Comment by mcharg** [comment]
@cthomasONRR This is ready to review.

**Comment by cthomasONRR** [comment]
@mcharg Approved
