### ISSUE TITLE
Page: FOGRMA Amendments

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1424]
https://qmcq5k.axshare.com/#id=02vpg8&p=fogrma_amendments&g=1

**Comment by cthomasONRR** [comment]
https://dev-onrr-frontend.app.cloud.gov/references/statutes/fogrma-amendments

**Comment by mcharg** [comment]
@cthomasONRR I added a couple of missing subtab titles and made sure all the accordions are there.  I'll review the content in detail after I finish my other issues for the sprint.  Also pinged @jlouis-onrr and @daniel-coleman-1 to see if either of them know how to indent in the CMS.

**Comment by cthomasONRR** [comment]
@mcharg I've made all the pages uniform with no tabbing. I think the can go into the backlog until we can do text colors

**Comment by mcharg** [comment]
@cthomasONRR I added horizontal lines to separate the bold sections as a workaround for the colored text. I also updated the intro paragraph accordingly. Take a look and see if it looks good to you.
https://dev-onrr-frontend.app.cloud.gov/references/statutes/fogrma-amendments

**Comment by mcharg** [comment]
Removed (date) and marked page as approved by ODDD.
