### ISSUE TITLE
Add ability to have colored text

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1425]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/0dd3c50d-c9eb-4131-a74c-e82180e52f6b)

**Comment by mcharg** [comment]
Hex values.

Dark Gold: #71500F
Blue: #1A227E (can use a similar dark blue that's already in the palette)

**Comment by mcharg** [comment]
We have work around for these for the launch.

**Comment by R-mohansai** [comment]
Completed adding new plugin from scratch took some time to figure out the source code and flow and checking on errors and restrictions. Working fine right now and closing the ticket.
