### ISSUE TITLE
Page: Rulemakings

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1426]
https://dev-onrr-frontend.app.cloud.gov/references/rulemakings
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/44
https://qmcq5k.axshare.com/#id=h57jbd&p=rulemakings&g=1

**Comment by mcharg** [comment]
@cthomasONRR I think this page is done and ready for your review.

**Comment by cthomasONRR** [comment]
@mcharg The collection is working well- I was able to filter and multi-selects topics. I tested the search for some basic terms like 'gas' and 'coal', and it worked well. I also spot-checked to make sure hyperlinks are working, and all that I checked worked properly. Looks great! I think this issue can be closed :)
