### ISSUE TITLE
Collection: Rulemakings

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1427]

**Comment by Maroyafaied** [comment]
@mcharg please add the link to the spreadsheet

**Comment by cthomasONRR** [comment]
@jlouis-onrr 
Rulemakings Collection linked [here](https://teams.microsoft.com/l/file/5DCF7519-C156-44B3-BE8D-C0749A9D9CC3?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FDesign%2FCollections%2FRulemakings%2FRulemakingsPagesCollection_NEW%20FOR%20CMS.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

**Comment by mcharg** [comment]
@cthomasONRR Here's the ICR issue. https://app.zenhub.com/workspaces/open-data-design--development-5464fa79c3cc8d7f4c384eaf/issues/onrr/onrr.gov-site/1429
