### ISSUE TITLE
Collection: Discontinued ICRs

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1429]

**Comment by cthomasONRR** [comment]
Discontinued ICR Collection Linked [here](https://teams.microsoft.com/l/file/ED400BD4-581E-4C99-B0BE-DD0C3037DAA5?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FDesign%2FCollections%2FDiscontinued%20ICRs%2FDiscontinuedICRCollection_NEW%20FOR%20CMS.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

**Comment by mcharg** [comment]
We built this as a static table instead of a collection.
