### ISSUE TITLE
Update the Valuation example

### ISSUE THREAD

**Issue by jpetersononrr** [ONRR/onrr.gov-site#143]
I have updated the page for the valuation example (https://www.onrr.gov/valuation/2016-rule-processed-example.htm).  The revised page needs to be "put" live as well as the images file under "valuation" and in the PDF file "Processed-Gas-Example-Updated-Final-04272020".  I've made all the changes and checked all the links.  As long as the images file is put live as well, it should all work fine.  Please let me know if you need something else from me!  Thanks!

**Comment by jennmalcolm** [comment]
@jpetersononrr it is live now. Please check it and make sure you don't notice anything missing.

**Comment by jpetersononrr** [comment]
One is missing--it's on me!  I forgot that "Example-processed-gas-statement-03102020" needs to be put from the pdf docs folder too.  Thank you!  Looks good otherwise!!

**Comment by jpetersononrr** [comment]
Sorry don't know if I was supposed to tag you...@jennmalcolm.  New to this!

**Comment by jennmalcolm** [comment]
No need to tag me since I'm already participating on this issue. I pushed the other file, and it should be live in about 10 mins.

**Comment by jpetersononrr** [comment]
I'm so sorry.  You know how sometimes people don't think of things until later?  We got a late comment that was particularly valid.  Could you put the image folder, page itself, and the PDF "Processed-Gas-Example-Updated-04272020" again?  Thank you for your help!!!

**Comment by jennmalcolm** [comment]
Done, @jpetersononrr. Please verify your changes are live.

**Comment by jpetersononrr** [comment]
Thank you!!  It's great!
