### ISSUE TITLE
Page: ICRs

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1430]
https://dev-onrr-frontend.app.cloud.gov/references/icrs
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/46
https://qmcq5k.axshare.com/#id=tqf3j1&p=information_collection_requests&g=1

**Comment by mcharg** [comment]
Add intro content and tabs.  Separate issues for each tab.

**Comment by cthomasONRR** [comment]
@mcharg I added the ICR intro content and tabs.
I also added the cards for the Current ICR tab, but links to the individual webpages are needed.

Could you please review? Thanks!

**Comment by cthomasONRR** [comment]
Shannon reviewed intro content and tabs. Closing.
