### ISSUE TITLE
Tab: Forms > Appeal Surety

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1435]
https://dev-onrr-frontend.app.cloud.gov/references/forms
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/47
https://qmcq5k.axshare.com/#id=6zhm0q&p=forms&g=1

Also:
https://qmcq5k.axshare.com/#id=otcgbi&p=appeals&g=1

**Comment by mcharg** [comment]
@lpgoldstein Looks good.  I split off the title from the content, since the two locations have different tab titles.

Moving to backlog until we can link to documents.

**Comment by mcharg** [comment]
@cthomasONRR This one is ready to review. There are no remaining blockers, so ready for full ODDD Approval.
https://dev-onrr-frontend.app.cloud.gov/references/forms?tab=appeal-surety

**Comment by mcharg** [comment]
Content is duplicated on this page. https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/appeals?tab=sureties

**Comment by cthomasONRR** [comment]
@mcharg Looks good, Full ODDD approval granted :)

**Comment by mcharg** [comment]
@cthomasONRR Links updated. Ready for full ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg Looks good. Approved all docs and the page.
