### ISSUE TITLE
Page: Reference Lists & Codes

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1437]
https://dev-onrr-frontend.app.cloud.gov/references/reference-lists
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/48
https://qmcq5k.axshare.com/#id=1f6ois&p=reference_lists___codes&g=1

**Comment by mcharg** [comment]
Add tabs.  Separate issue for each tab.

**Comment by mcharg** [comment]
@cthomasONRR Tabs are ready to review. https://dev-onrr-frontend.app.cloud.gov/references/reference-lists

**Comment by cthomasONRR** [comment]
@mcharg Tabs look good
