### ISSUE TITLE
Tab: Reference Lists & Codes > Lease & Agreement Numbers

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1438]
https://dev-onrr-frontend.app.cloud.gov/references/reference-lists
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/48
https://qmcq5k.axshare.com/#id=1f6ois&p=reference_lists___codes&g=1

**Comment by mcharg** [comment]
Got as far as I could before hitting blockers.
https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tab=leases-agreement-numbers

**Comment by cthomasONRR** [comment]
@mcharg I added all doc links. Docs and entire page are ready for your approval.

**Comment by mcharg** [comment]
Approved and updated dates to match dates on live site.
