### ISSUE TITLE
Page: Valuation & Pricing

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1441]
https://dev-onrr-frontend.app.cloud.gov/references/valuation
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/50
https://qmcq5k.axshare.com/#id=l9inb4&p=valuation___pricing&g=1

**Comment by mcharg** [comment]
Add tabs.  Separate issues for each tab.

**Comment by mcharg** [comment]
@cthomasONRR This is just reviewing the tabs (not the content within them).

**Comment by cthomasONRR** [comment]
@mcharg I reviewed the tabs. It looks good to me. Added my name as reviewed in the Content Tracking sheet.
