### ISSUE TITLE
Add ability to link to a filtered view of the rulemaking page

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1445]
Click on any of the historical rules link on this page to see how we want it to behave.
https://qmcq5k.axshare.com/#id=l9inb4&p=valuation___pricing&g=1

**Comment by cthomasONRR** [comment]
Rulemakings Collection linked [here](https://teams.microsoft.com/l/file/5DCF7519-C156-44B3-BE8D-C0749A9D9CC3?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FDesign%2FCollections%2FRulemakings%2FRulemakingsPagesCollection_NEW%20FOR%20CMS.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a). This has all the categories to sort/filter by.

**Comment by cthomasONRR** [comment]
@jlouis-onrr 

Dev site page: https://dev-onrr-frontend.app.cloud.gov/references/rulemakings?topic=All

I clicked though all the sorting options, and they work well! I spot-checked to make sure the hyperlinks are working, and all the ones I checked worked for me.

One question- can we have the Topic dropdown set so multiple items can be selected?

**Comment by mcharg** [comment]
@jlouis-onrr I don't think the links are working.  Christine added links from the valuation regulations page and it's opening the rulemakings page, but the filters aren't applying.

**Comment by mcharg** [comment]
@jlouis-onrr Filters are fixed!
