### ISSUE TITLE
Page: 2016 Valuation Rule Federal Processed Gas Reporting Example (all tabs)

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1446]
https://dev-onrr-frontend.app.cloud.gov/references/valuation/processed-gas-example
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/68
https://qmcq5k.axshare.com/#id=0royo3&p=valuation_example&g=1

**Comment by cthomasONRR** [comment]
@mcharg This entire example is ready for your review.

**Comment by mcharg** [comment]
@cthomasONRR PC15 has the Transportation Allowances step 1.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/aa238fe5-cbff-4852-9554-ec7c9a162d5b)

**Comment by mcharg** [comment]
@cthomasONRR RVLA has the intro and step 1 from processing allowances.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/8633b025-89a5-4c96-8329-4f2ff8bfbb8a)

**Comment by mcharg** [comment]
@cthomasONRR The rest looks good.  I just adjusted some heading levels.

**Comment by cthomasONRR** [comment]
@mcharg Thanks for catching those issues! They are now fixed!

**Comment by mcharg** [comment]
@cthomasONRR Looks good.  Moving to backlog.

**Comment by mcharg** [comment]
@cthomasONRR I added headers to this table to fix the issue with the first row looking like a header. Probably is also better for accessibility. Do you think that works?
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/eb7137c0-3a34-4435-bf76-f8747d6d44f8)

**Comment by mcharg** [comment]
Put pipes in as a workaround for the table with multiple lines. ![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/cbf068a4-d093-4d1d-8720-bad6fd2dc66a)

**Comment by cthomasONRR** [comment]
@mcharg It looks loads better! I would definitely like more formatting options in the future (maybe make the header font larger than the consent, possible colors on the header), but this is a great improvement :)

**Comment by cthomasONRR** [comment]
@mcharg and thanks for adding in the 'pipes' I saw you doing this in other tables, but didn't know how to do it myself.

**Comment by mcharg** [comment]
@cthomasONRR The pipe is the symbol on the \ key (right above the enter key) if you use shift.

**Comment by mcharg** [comment]
Approved by ODDD
