### ISSUE TITLE
Create helpful tips functionality for valuation examples

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1447]
https://qmcq5k.axshare.com/#id=0royo3&p=valuation_example&g=1

**Comment by Maroyafaied** [comment]
look into adding icon property within the card block.

**Comment by mcharg** [comment]
Analytics from May to help determine whether we need the coloring on the icons at launch.

2016 example: 160 page views (0.48% of total page views)
POP example: 61 page views (0.18% of total page views)

**Comment by Maroyafaied** [comment]
Will close and make another issues for coloring icons.
