### ISSUE TITLE
Page: Federal Percent-of-Proceeds Contract Reporting Example (all tabs)

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1449]
https://dev-onrr-frontend.app.cloud.gov/references/valuation/pop-example
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/69
https://qmcq5k.axshare.com/#id=nm9ju1&p=valuation_example_2&g=1

**Comment by cthomasONRR** [comment]
@mcharg I've done all that I can with this one. Want to review, or should I put in in Product Backlog?

**Comment by mcharg** [comment]
@cthomasONRR Looks good.  Moving to backlog.

**Comment by mcharg** [comment]
@cthomasONRR Looks good.  Adjusted some heading levels and moving to backlog.

**Comment by cthomasONRR** [comment]
@mcharg Yay! This one was though to get together!

**Comment by mcharg** [comment]
Added pipes in table. ![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/4abb458d-dacd-4945-afe9-095b6010c722)

**Comment by mcharg** [comment]
Approved by ODDD.
