### ISSUE TITLE
Update Production Reporting References

### ISSUE THREAD

**Issue by ONRR-31577** [ONRR/onrr.gov-site#145]
On the ONRR.gov home page, 
under Reporting/Paying
Production Reporting
Reporter Tools / References

Please replace the five existing Gulf Files and and replace the three Pacific Files with the attached files and change the "as of date to 04/28/20.

Thank you,

[Gulf-Metering-Systems.pdf](https://github.com/ONRR/onrr.gov-site/files/4546418/Gulf-Metering-Systems.pdf)
[Gulf-Sales-Tanks.pdf](https://github.com/ONRR/onrr.gov-site/files/4546420/Gulf-Sales-Tanks.pdf)
[Gulf-Gas-Plants.pdf](https://github.com/ONRR/onrr.gov-site/files/4546422/Gulf-Gas-Plants.pdf)
[Gulf-Flash-Gas.pdf](https://github.com/ONRR/onrr.gov-site/files/4546423/Gulf-Flash-Gas.pdf)
[Gulf-Buy-Back.pdf](https://github.com/ONRR/onrr.gov-site/files/4546424/Gulf-Buy-Back.pdf)
[Pacific-Metering-Systems.pdf](https://github.com/ONRR/onrr.gov-site/files/4546429/Pacific-Metering-Systems.pdf)
[Pacific-Sales-Tanks.pdf](https://github.com/ONRR/onrr.gov-site/files/4546431/Pacific-Sales-Tanks.pdf)
[Pacific-Gas-Plants.pdf](https://github.com/ONRR/onrr.gov-site/files/4546433/Pacific-Gas-Plants.pdf)

**Comment by Maroyafaied** [comment]
@ONRR-31577 please review the development link for the changes you have requested. If everything looks correct, I will push it to the live site. Thanks h

ttp://2017onrr/ReportPay/references.htm

**Comment by ONRR-31577** [comment]
It looks good.
Thank you

**Comment by ONRR-31577** [comment]
It looks good.
Thank you

Johnny Erle

Office of Natural Resources Revenue (ONRR)
RRM Team 1A
Minerals Revenue Specialist-GVS
john.erle@onrr.gov<mailto:john.erle@onrr.gov>
303-231-3577
800-525-7922  ext.13577
fax: 303-231-3566
________________________________

**Comment by Maroyafaied** [comment]
The requester approved and the changes are on the live site.

**Comment by ONRR-31577** [comment]
Please change the as of date on the live site. It still shows the old date.

**Comment by Maroyafaied** [comment]
@ONRR-31577 I'm showing the updated dates on the live site, have you tried refreshing? 
![image](https://user-images.githubusercontent.com/40175688/80515450-3c8c6400-893f-11ea-986f-12ad32779e55.png)

**Comment by jennmalcolm** [comment]
@ONRR-31577 you may need to press ctrl and F5 to see the changes.

**Comment by ONRR-31577** [comment]
Jennifer,
    That was it.

Thanks,




Johnny Erle

Office of Natural Resources Revenue (ONRR)
RRM Team 1A
Minerals Revenue Specialist-GVS
john.erle@onrr.gov<mailto:john.erle@onrr.gov>
303-231-3577
800-525-7922  ext.13577
fax: 303-231-3566
________________________________
