### ISSUE TITLE
Tab: Valuation & Pricing > Contacts

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1450]
https://dev-onrr-frontend.app.cloud.gov/references/valuation?tab=contacts
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/50
https://qmcq5k.axshare.com/#id=l9inb4&p=valuation___pricing&g=1

Also:
https://qmcq5k.axshare.com/#id=6wj92e&p=valuation___pricing_1&g=1

**Comment by mcharg** [comment]
@cthomasONRR This is ready to review.

**Comment by cthomasONRR** [comment]
@mcharg Approved
