### ISSUE TITLE
Tab: Reporter Training > Training Presentations

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1453]
https://dev-onrr-frontend.app.cloud.gov/references/training
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/52
https://qmcq5k.axshare.com/#id=cwcm9b&p=reporter_training&g=1

**Comment by daniel-coleman-1** [comment]
@mcharg I've added the content but none of the links to training documents

**Comment by mcharg** [comment]
@daniel-coleman-1 Looks good.  Moving back to backlog until we can link docs.

**Comment by cthomasONRR** [comment]
@mcharg I added all the doc links to the Training Presentations page. All docs are ready for approval, and I believe this page is also ready for final approval. Then this issue can be closed :)

**Comment by mcharg** [comment]
@cthomasONRR All approved.
