### ISSUE TITLE
Tab: Training Presentations > Training Videos

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1454]
https://dev-onrr-frontend.app.cloud.gov/references/training
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/52
https://qmcq5k.axshare.com/#id=cwcm9b&p=reporter_training&g=1

**Comment by mcharg** [comment]
Added intro content and subtabs. https://dev-onrr-frontend.app.cloud.gov/references/training?tab=training-videos

**Comment by mcharg** [comment]
@cthomasONRR This is ready for ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg Approved
