### ISSUE TITLE
Tab: Reporter Training > Training Schedule

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1455]
https://dev-onrr-frontend.app.cloud.gov/references/training
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/52
https://qmcq5k.axshare.com/#id=cwcm9b&p=reporter_training&g=1

**Comment by lpgoldstein** [comment]
@mcharg https://dev-onrr-frontend.app.cloud.gov/references/training?tabs=training-schedule

**Comment by mcharg** [comment]
@lpgoldstein Do we not have the pdf to link to?

**Comment by mcharg** [comment]
Actually, where the event is in the past, maybe we should remove it an just add a line of text that says there are no upcoming trainings.
