### ISSUE TITLE
Page: Paying Home

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1456]
https://dev-onrr-frontend.app.cloud.gov/paying
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/6
https://qmcq5k.axshare.com/#id=caluw3&p=paying&g=1

**Comment by mcharg** [comment]
@lpgoldstein The links to pay.gov, ACH, and Fedwire are going to the prototype.

**Comment by mcharg** [comment]
@Maroyafaied The tabs will need to be created on the Payment Options before you'll be able to link to them.  @daniel-coleman-1 Let Maroya know when the tabs are created.

**Comment by mcharg** [comment]
@daniel-coleman-1 Can you please making adding tabs to the Payment Options page a high priority, so we can get this page finished?  Let me know if you need help.

**Comment by mcharg** [comment]
Added @lpgoldstein and upped the estimate because all the tables she added were a lot of work.

**Comment by daniel-coleman-1** [comment]
@mcharg got the tabs in:
https://dev-onrr-frontend.app.cloud.gov/paying/payment-options?tab=paygov

**Comment by mcharg** [comment]
@daniel-coleman-1 Awesome!  Thank you!

**Comment by Maroyafaied** [comment]
@lpgoldstein @mcharg I've added the correct links and unlinked the documents. Please review.

**Comment by mcharg** [comment]
@Maroyafaied Looks good and tested all the links.  Moving to backlog until we can link to docs.

**Comment by mcharg** [comment]
@cthomasONRR Doc links added.  Ready for full ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg Set the page and docs to approved
