### ISSUE TITLE
Update royalty reporting contacts

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#146]
This came from Service Now. I've forwarded the email to our shared web box so you have contact info @lpgoldstein 
[royassign 04-28-2020.pdf](https://github.com/ONRR/onrr.gov-site/files/4546943/royassign.04-28-2020.pdf)

 Will you please post the attached listing on the onrr.gov web page at the following address: https://www.onrr.gov/ReportPay/PDFDocs/royassign.pdf [https://www.onrr.gov/ReportPay/PDFDocs/royassign.pdf]

 Thanks

**Comment by lpgoldstein** [comment]
@jennmalcolm this is ready for your review http://2017onrr/ReportPay/PDFDocs/royassign.pdf

**Comment by jennmalcolm** [comment]
Looks like the file sent in. Go ahead and push to production.
