### ISSUE TITLE
Page: Paying > Contacts

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1461]
https://dev-onrr-frontend.app.cloud.gov/paying/contacts-paying
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/40
https://qmcq5k.axshare.com/#id=cqd7rp&p=contacts&g=1

**Comment by mcharg** [comment]
@cthomasONRR Tabs are ready to review.
https://dev-onrr-frontend.app.cloud.gov/paying/contacts-paying

**Comment by cthomasONRR** [comment]
@mcharg tabs look good
