### ISSUE TITLE
Page: Compliance

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1462]
https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/compliance
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/22
https://qmcq5k.axshare.com/#id=wxa2eb&p=compliance&g=1

**Comment by mcharg** [comment]
Separate page for each tab.  This issue is to create tabs.

**Comment by mcharg** [comment]
@cthomasONRR Tabs are ready to review.

**Comment by cthomasONRR** [comment]
@mcharg Tabs look good
