### ISSUE TITLE
Tab: Compliance > Compliance Authorities

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1464]
https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/compliance
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/22
https://qmcq5k.axshare.com/#id=wxa2eb&p=compliance&g=1

Same table as Statutes page.

**Comment by mcharg** [comment]
@cthomasONRR Once you build the table for the Statutes page, you can use it here.

**Comment by cthomasONRR** [comment]
@mcharg I was able to add in the statutes as an existing content block! This tab is ready for your review.

**Comment by mcharg** [comment]
@cthomasONRR Looks good!
