### ISSUE TITLE
Page: Enforcement & Litigation Support

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1466]
https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/enforcement
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/26
https://qmcq5k.axshare.com/#id=5w0f4w&p=enforcement&g=1

**Comment by mcharg** [comment]
This issue is for adding the intro content and the tabs.

**Comment by lpgoldstein** [comment]
@mcharg please review

**Comment by mcharg** [comment]
Looks good.
