### ISSUE TITLE
Page: Assistance

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1470]
https://dev-onrr-frontend.app.cloud.gov/indian/assistance?tab=choosing-assistance
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/23
https://qmcq5k.axshare.com/#id=tzo87j&p=assistance&g=1

**Comment by mcharg** [comment]
@cthomasONRR This is to review the tab, not the content within them.

**Comment by cthomasONRR** [comment]
@mcharg I reviewed the tabs. It looks good to me. Added my name as reviewed in the Content Tracking sheet.
