### ISSUE TITLE
Page: Tribal Consultation

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1471]
https://dev-onrr-frontend.app.cloud.gov/indian/tribal-consultation
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/33
https://qmcq5k.axshare.com/#id=htd1ha&p=tribal_consultation&g=1

**Comment by mcharg** [comment]
This issue is to add the tabs.

**Comment by lpgoldstein** [comment]
@mcharg please review

**Comment by mcharg** [comment]
@lpgoldstein Looks good.
