### ISSUE TITLE
Page: Indian Pricing

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1472]
https://dev-onrr-frontend.app.cloud.gov/indian/indian-pricing
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/34
https://qmcq5k.axshare.com/#id=y89dq7&p=indian_pricing&g=1

**Comment by mcharg** [comment]
This issue is to add the tabs.

**Comment by mcharg** [comment]
@cthomasONRR Tabs are ready to review.

**Comment by cthomasONRR** [comment]
@mcharg Tabs look good
