### ISSUE TITLE
Add filtering ability to tables

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1473]
https://qmcq5k.axshare.com/#id=h57jbd&p=rulemakings&g=1

**Comment by Maroyafaied** [comment]
@mcharg please review

**Comment by Maroyafaied** [comment]
No need to create a PR for this. @mcharg @cthomasONRR please review

**Comment by mcharg** [comment]
I created #1617 for multi-select.  Both reporter letters and rulemakings look good to me.
