### ISSUE TITLE
Tab: Enforcement & Litigation Support > Enforcement

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1475]
https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/enforcement
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/26
https://qmcq5k.axshare.com/#id=5w0f4w&p=enforcement&g=1

**Comment by mcharg** [comment]
Content on Enforcement tab

**Comment by lpgoldstein** [comment]
@mcharg

**Comment by mcharg** [comment]
Looks good.
