### ISSUE TITLE
Tab: Enforcement & Litigation Support > Civil Penalties

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1476]
https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/enforcement
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/26
https://qmcq5k.axshare.com/#id=5w0f4w&p=enforcement&g=1

**Comment by lpgoldstein** [comment]
@mcharg please review

**Comment by mcharg** [comment]
@lpgoldstein Looks good.  Moving to backlog until we get the ability to link to documents.

**Comment by Maroyafaied** [comment]
@cthomasONRR U added this one to this sprint, can you please review and update spreadsheets if everything looks good? Thanks

https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/enforcement?tabs=civil-penalties,penalty-collections

**Comment by cthomasONRR** [comment]
@Maroyafaied The Penalty Collections tab looks good. I set all those document links as 'approved by oddd' in the spreadsheet.

The Civil Penalties page is not ready for review, since docs need to be linked in the 'References' and 'Assessment Tables' subtabs as well.

**Comment by cthomasONRR** [comment]
@Maroyafaied I can link the docs in the  'References' and 'Assessment Tables' subtabs today if you want to actually take your Friday off! ;)

**Comment by Maroyafaied** [comment]
@cthomasONRR lol I was just too eager to play around with linking, if you have time today or Monday you can take it over. If not, no worries I will finish it next week.

**Comment by mcharg** [comment]
Approved.
