### ISSUE TITLE
Late Payment & Underpayment Interest Tables on ONRR.gov

### ISSUE THREAD

**Issue by badeh** [ONRR/onrr.gov-site#148]
Good Morning,
Please eliminate the following narratives immediately:

Highlighted section - "Effective December 5, 2015, ONRR is no longer authorized to pay overpayment interest. On this date, H.R. 22, "Fixing America's Surface Transportation Act," was signed into law. Any bills issued after this date do not contain overpayment interest regardless of the sales month/year. The "FAST" act amended the Federal Oil and Gas Royalty Management Act of 1982, eliminating overpayment interest."

Below table (bottom of page) - "**Effective December 5, 2015, ONRR is no longer authorized to pay overpayment interest. On this date, H.R. 22, "Fixing America's Surface Transportation Act," was signed into law. Any bills issued after this date do not contain overpayment interest regardless of the sales month/year. The "FAST" act amended the Federal Oil and Gas Royalty Management Act of 1982, eliminating overpayment interest."

Thank you,

Hannah Bade

**Comment by jennmalcolm** [comment]
@badeh I've made the changes in dev. Please review and let me know if you see any issues before I push it to production.

http://2017onrr/ReportPay/interest.htm

**Comment by badeh** [comment]
Hi Jennifer,

The page looks great and can be loaded to production.

Thank you for getting this page updated!

​Hannah Bade
Office of Natural Resources Revenue
Financial Management/Financial Services
(303) 231-3373
Hannah.Bade@onrr.gov

________________________________

**Comment by jennmalcolm** [comment]
The changes are live.

**Comment by badeh** [comment]
Thank you so much.

​Hannah Bade
Office of Natural Resources Revenue
Financial Management/Financial Services
(303) 231-3373
Hannah.Bade@onrr.gov

________________________________
