### ISSUE TITLE
Tab: Appeals > Contacts

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1481]
https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/appeals
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/27
https://qmcq5k.axshare.com/#id=otcgbi&p=appeals&g=1

**Comment by mcharg** [comment]
@cthomasONRR This is ready to review.

@Maroyafaied Do we want to add this to the list of pages for regs to review once Christine approved?

**Comment by Maroyafaied** [comment]
@mcharg Yes, if enforcements and appeals contacts are ready, I can send them with a reminder email to review.

**Comment by cthomasONRR** [comment]
@mcharg Looks good - approve.
