### ISSUE TITLE
Tab: STRAC > Contacts

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1485]
https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/cooperative
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/28
https://qmcq5k.axshare.com/#id=5fxgha&p=strac&g=1

**Comment by mcharg** [comment]
@lpgoldstein Moving to backlog, since we don't have the contacts collection.

**Comment by mcharg** [comment]
@cthomasONRR This is ready to review.

**Comment by cthomasONRR** [comment]
@mcharg Approved
