### ISSUE TITLE
Tab: Assistance > Choosing Assistance

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1486]
https://dev-onrr-frontend.app.cloud.gov/indian/assistance?tab=choosing-assistance
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/23
https://qmcq5k.axshare.com/#id=tzo87j&p=assistance&g=1

**Comment by mcharg** [comment]
@cthomasONRR The Choosing Assistance tab is ready to review.

**Comment by cthomasONRR** [comment]
@mcharg I reviewed the content in this tab. It looks good to me - all links are working. Added my name as reviewed in the Content Tracking sheet.
