### ISSUE TITLE
Tab: Assistance > Indian Outreach > Overview

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1488]
https://dev-onrr-frontend.app.cloud.gov/indian/assistance?tab=indian-outreach
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/23
https://qmcq5k.axshare.com/#id=tzo87j&p=assistance&g=1

**Comment by mcharg** [comment]
@lpgoldstein Looks good.  Moving to backlog because we need icons for the contact info.  I added the link to the directory.

**Comment by lpgoldstein** [comment]
added pdf

**Comment by mcharg** [comment]
@cthomasONRR Ready for ODDD approval. Created separate issue for icons.

**Comment by cthomasONRR** [comment]
@mcharg Approved
