### ISSUE TITLE
Tab: Assistance > Indian Outreach > Videos

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1489]
https://dev-onrr-frontend.app.cloud.gov/indian/assistance?tab=indian-outreach
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/23
https://qmcq5k.axshare.com/#id=tzo87j&p=assistance&g=1

**Comment by mcharg** [comment]
@cthomasONRR This is ready for ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg Approved
