### ISSUE TITLE
Tab: Assistance > FIMO

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1490]
https://dev-onrr-frontend.app.cloud.gov/indian/assistance?tab=federal-indian-minerals-office
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/23
https://qmcq5k.axshare.com/#id=tzo87j&p=assistance&g=1

**Comment by mcharg** [comment]
@lpgoldstein Looks good.  Moving to backlog until we get icons.

**Comment by mcharg** [comment]
Added columns to clean up card height.

**Comment by mcharg** [comment]
@cthomasONRR Ready for ODDD approval. Created a separate issue for icons.

**Comment by cthomasONRR** [comment]
@mcharg Approved
