### ISSUE TITLE
Tab: Assistance > Tribal Assistance

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1491]
https://dev-onrr-frontend.app.cloud.gov/indian/assistance?tab=tribal-assistance
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/23
https://qmcq5k.axshare.com/#id=tzo87j&p=assistance&g=1

**Comment by mcharg** [comment]
@lpgoldstein I added the missing links.  Moving to backlog until we get icons.

**Comment by mcharg** [comment]
@cthomasONRR Ready for ODDD approval. Created separate issue for icons.

**Comment by cthomasONRR** [comment]
@mcharg Approved
