### ISSUE TITLE
Tab: Assistance > IESC

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1492]
https://dev-onrr-frontend.app.cloud.gov/indian/assistance?tab=indian-energy-service-center
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/23
https://qmcq5k.axshare.com/#id=tzo87j&p=assistance&g=1

**Comment by mcharg** [comment]
This issue is just to add the tabs.

**Comment by lpgoldstein** [comment]
Do we need an image in the video tab - I added the link

**Comment by lpgoldstein** [comment]
@mcharg ready to review

**Comment by mcharg** [comment]
@lpgoldstein We should create a separate issue for the video tab that has the video player as a dependency.

**Comment by mcharg** [comment]
Tabs look good.  Created #1574 for the video tab.
