### ISSUE TITLE
Tab: Assistance > IESC > About

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1493]
https://dev-onrr-frontend.app.cloud.gov/indian/assistance?tab=indian-energy-service-center
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/23
https://qmcq5k.axshare.com/#id=tzo87j&p=assistance&g=1

**Comment by mcharg** [comment]
@lpgoldstein I added in the About tab title and Principles content that were missing and adjusted the heading levels in the cards on the right.  Otherwise, looks good until we get functionality to clean up the layout.  Moving to backlog.

**Comment by mcharg** [comment]
Added alt text and cleaned up columns for agencies.

**Comment by mcharg** [comment]
Columns are cleaned up and I put the video back on this tab.

**Comment by mcharg** [comment]
@cthomasONRR Ready for ODDD approval. Created separate issue for icons.

**Comment by cthomasONRR** [comment]
@mcharg Approved
