### ISSUE TITLE
Tab: Assistance > IESC > Referral Information

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1494]
https://dev-onrr-frontend.app.cloud.gov/indian/assistance?tab=indian-energy-service-center&tabs=indian-energy-service-center,referral-information
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/23
https://qmcq5k.axshare.com/#id=tzo87j&p=assistance&g=1

**Comment by mcharg** [comment]
@lpgoldstein Looks good.  I adjusted heading levels.  Moving to backlog until we get the ability to add phone and email icons.

**Comment by cthomasONRR** [comment]
@mcharg Approved
