### ISSUE TITLE
Tab: Indian Pricing > How to Value

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1498]
https://dev-onrr-frontend.app.cloud.gov/indian/indian-pricing
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/34
https://qmcq5k.axshare.com/#id=y89dq7&p=indian_pricing&g=1

**Comment by lpgoldstein** [comment]
@mcharg do you want to check the tabs?

**Comment by mcharg** [comment]
@lpgoldstein Looks good. Moving to backlog until we can link to docs.

**Comment by cthomasONRR** [comment]
@mcharg All docs are linked. I think this entire page is ready for approval.

**Comment by mcharg** [comment]
Approved.
