### ISSUE TITLE
Page: Indian References

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1499]
https://dev-onrr-frontend.app.cloud.gov/indian/indian-references
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/35
https://qmcq5k.axshare.com/#id=xj5291&p=indian_references&g=1

**Comment by mcharg** [comment]
@lpgoldstein I added the tabs to the page, so I could add in the intro content for the contact page I built for another page.
https://dev-onrr-frontend.app.cloud.gov/indian/indian-references

**Comment by mcharg** [comment]
@cthomasONRR Tabs are ready to review.
https://dev-onrr-frontend.app.cloud.gov/indian/indian-references

**Comment by cthomasONRR** [comment]
@mcharg Tabs look good. FYI the axure is buggy for this one. Not sure if it's just me.
