### ISSUE TITLE
Tab: Indian References > Training

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1500]
https://dev-onrr-frontend.app.cloud.gov/indian/indian-references
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/35
https://qmcq5k.axshare.com/#id=xj5291&p=indian_references&g=1

**Comment by mcharg** [comment]
@cthomasONRR This is ready for ODDD Review.

**Comment by cthomasONRR** [comment]
@mcharg Approved
