### ISSUE TITLE
Tab: Indian References > References

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1501]
https://dev-onrr-frontend.app.cloud.gov/indian/indian-references
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/35
https://qmcq5k.axshare.com/#id=xj5291&p=indian_references&g=1

**Comment by mcharg** [comment]
@lpgoldstein Moving to backlog until we can link to docs.

**Comment by lpgoldstein** [comment]
added pdfs

**Comment by mcharg** [comment]
@cthomasONRR Docs look good. Leaving in backlog until we get button.

**Comment by cthomasONRR** [comment]
@mcharg Approved
