### ISSUE TITLE
Tab: Engagement > Presentations

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1507]
https://dev-onrr-frontend.app.cloud.gov/about/engagement?tab=presentations
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/29
https://qmcq5k.axshare.com/#id=ocslh8&p=engagement&g=1

**Comment by mcharg** [comment]
Need to confirm with @mentastc whether we will have presentations to put on the site.

**Comment by Maroyafaied** [comment]
Chris would like to get rid of it, I will make the update in the cms and delete it from the tracking sheet @mcharg do you want to update the wireframe? We'll update the sitemap with everything else.

**Comment by mcharg** [comment]
@Maroyafaied Wireframe will be updated shortly.  Just waiting for it to publish.

**Comment by Maroyafaied** [comment]
@mcharg I deleted the tab, can you review. Thanks

**Comment by mcharg** [comment]
@Maroyafaied Looks good.
