### ISSUE TITLE
Page: Interagency Coordination

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1509]
https://dev-onrr-frontend.app.cloud.gov/about/interagency
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/30
https://qmcq5k.axshare.com/#id=206gu4&p=interagency_coordination&g=1

**Comment by mcharg** [comment]
Includes all tab content.

**Comment by daniel-coleman-1** [comment]
Do we want to add the ability to add line breaks to tab headers or have them adjust responsively?  Right now I'm only able to have the headers as one horizontal line like this (dev):
![Screenshot 2022-02-09 132136](https://user-images.githubusercontent.com/83892362/153287421-df76386d-2080-4892-9680-bcf9fdd1324e.png)

here it is in the wireframe:
![Screenshot 2022-02-09 134701](https://user-images.githubusercontent.com/83892362/153287471-75150aa6-432b-4d3d-90b9-c0521b0ba3a8.png)

**Comment by daniel-coleman-1** [comment]
@Maroyafaied this is ready to review.

Aside from that all the previous blockers still exist:
- Add ability for links to display an icon depending on file type
- Add ability to decide how large an image displays
- Add ability to put alt text on images
- Add way to link to documents

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 moving it to backlog

**Comment by lpgoldstein** [comment]
added pdfs

**Comment by cthomasONRR** [comment]
@mcharg Set the docs and page as approved
