### ISSUE TITLE
Page: Anti-Harassment Program

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1510]
https://dev-onrr-frontend.app.cloud.gov/about/anti-harassment
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/32
https://qmcq5k.axshare.com/#id=l88jo0&p=anti-harassment_program&g=1

**Comment by daniel-coleman-1** [comment]
@Maroyafaied this is good to go, text is entered in and formatted but the two blockers still exist.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 looks good, moving to backlog since this page has blockers.

**Comment by mcharg** [comment]
@cthomasONRR This page has the documents linked and is ready to review.

**Comment by cthomasONRR** [comment]
@mcharg All 4 pdf links worked and I was able to view the documents. But, I'm really concerned about the PDF urls... they all look like this:
![image](https://user-images.githubusercontent.com/72526208/157116921-1040c18b-7f64-4bbd-b3d4-1b980e766d07.png)

Will we have normal PDF titles in the urls like we currently have on the live site?

**Comment by cthomasONRR** [comment]
@mcharg Sorry this one was complicated. Do you want me to review and approve on the tracking sheet?

**Comment by mcharg** [comment]
@cthomasONRR Sure

**Comment by cthomasONRR** [comment]
@mcharg OK all documents and page are set to approved by oddd. Closing this issue.
