### ISSUE TITLE
Add ability to main search from the contacts us page

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1512]

**Comment by jlouis-onrr** [comment]
@mcharg, i pushed out a the contacts search and search results page.  still working on smoothing out the filters on the results page.  There's also some styling updates in this update.

**Comment by mcharg** [comment]
@lpgoldstein Please test out the search.

**Comment by lpgoldstein** [comment]
@jlouis-onrr It doesn't seem like the "all categories" filter narrows down the search. Is it supposed to?

**Comment by lpgoldstein** [comment]
@mcharg I've searched by first, last, partial names, company names, partial company numbers, people that are listed only as backup contacts, people that are only supervisors. Different key words. you can't search by phone number or type in Supervisor to get those people.

**Comment by mcharg** [comment]
@jlouis-onrr Can you make it submit the search when you pick from the suggestions, so you don't have to hit the button?
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/e32ab794-a0c0-48a2-94d8-e1664aa40209)

**Comment by mcharg** [comment]
You can drop the suggested searches line below the field. That was just in the prototype because I couldn't make it work.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/cf3dc2c5-03c2-4f6b-91eb-694bae607d89)

**Comment by jlouis-onrr** [comment]
yes, that can be added.

**Comment by lpgoldstein** [comment]
@mcharg Do we want people to be able to search by role? Is that important?

**Comment by mcharg** [comment]
@jlouis-onrr Can you add the page, tab, and accordion categories to the header bar in search results? We'll also want that for the contacts by company page.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/33bdf53b-b49f-4fb3-a8e4-3881d7783548)

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/8adcf9d7-53a6-4ecc-94dd-8724f94a5f99)

Note: The bars for the FIMO ones will need to get taller.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/e92ff0c5-9508-4402-8ca5-31b6fe51b76a)

**Comment by jlouis-onrr** [comment]
for the category headers, we probably need @mojobnichols to style them

**Comment by mcharg** [comment]
Created #1877 for an issue with the search fields on the main contacts page and search results pages behaving differently.

**Comment by mcharg** [comment]
Created #1878 to split out the levels of categories into separate filters.

**Comment by mcharg** [comment]
Looks like the above issues are all addressed. Created new issues for two new items I noticed.

**Comment by mcharg** [comment]
@lpgoldstein Do you want to review one more time before closing?

**Comment by lpgoldstein** [comment]
@mcharg Looks good.
