### ISSUE TITLE
Design way to flexibly find contacts

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/onrr.gov-site#152]
Users have trouble finding contacts on the website. We need a better way to organize contacts and all allow users to search.

**Comment by branic18** [comment]
Contacts Design: https://studentsdesu-my.sharepoint.com/:x:/g/personal/bcnichols18_students_desu_edu/EVGdnB6LvQ5EpmroKfgrwQQBvUGmP6Yjm3ixE9eoxMO8jg?e=9HEnef

**Comment by mcharg** [comment]
Continuing in #516
