### ISSUE TITLE
Tab: Lease & Agreement Contacts > Contacts

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1521]
https://qmcq5k.axshare.com/#id=q4kw41&p=leases___agreements&g=1

**Comment by mcharg** [comment]
@cthomasONRR This is ready to review.

**Comment by cthomasONRR** [comment]
@mcharg 

- Is there an issue for the "a-z" hyperlinks to be added?
- New Mexico, Kansas, Oklahoma (federal), & Texas contacts are different between dev and wireframe

**Comment by mcharg** [comment]
@cthomasONRR It should be whatever is in the spreadsheet.

It'll be easier to navigate once search is in.

**Comment by cthomasONRR** [comment]
@mcharg Approved.
