### ISSUE TITLE
Page: Oil & Gas Production Contacts

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1522]
https://qmcq5k.axshare.com/#id=bhj7vh&p=oil___gas_production_1&g=1

Add page and tabs.

**Comment by mcharg** [comment]
@cthomasONRR The tabs are ready to review.

**Comment by cthomasONRR** [comment]
@mcharg I can't find the right dev site location here... went to 'about ONRR' then 'contact us' like in the wireframe but don't see any O&G in that location in the dev site.

**Comment by mcharg** [comment]
@cthomasONRR Here's the link.  I haven't built the main contact page with links yet. https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts

**Comment by cthomasONRR** [comment]
@mcharg Thanks! Tabs look good
