### ISSUE TITLE
Page: Oil & Gas Royalty Contacts

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1523]
https://qmcq5k.axshare.com/#id=its4or&p=oil___gas_royalty&g=1

Add page and tabs.

**Comment by mcharg** [comment]
@cthomasONRR Tabs are ready to review.
https://dev-onrr-frontend.app.cloud.gov/about/contact/royalty-contacts

**Comment by cthomasONRR** [comment]
@mcharg Tabs look good
