### ISSUE TITLE
Page: Oil & Gas Rent

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1524]
https://qmcq5k.axshare.com/#id=ekmgn0&p=oil___gas_rent&g=1

Add page and tabs.

**Comment by mcharg** [comment]
@cthomasONRR Tabs are ready to review.
https://dev-onrr-frontend.app.cloud.gov/about/contact/rent-contacts

**Comment by cthomasONRR** [comment]
@mcharg tabs look good
