### ISSUE TITLE
Tab: Oil & Gas Rent Contacts > Troubleshooting

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1525]
https://qmcq5k.axshare.com/#id=ekmgn0&p=oil___gas_rent&g=1

**Comment by mcharg** [comment]
Got this as far as I could without linking to docs.
https://dev-onrr-frontend.app.cloud.gov/about/contact/rent-contacts?tab=troubleshooting

**Comment by mcharg** [comment]
@cthomasONRR Docs are ready to review.

**Comment by cthomasONRR** [comment]
@mcharg approved

**Comment by cthomasONRR** [comment]
@mcharg Approved
