### ISSUE TITLE
Archive outdated FAQ page 

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/onrr.gov-site#153]
Delete outdated FAQ page 

https://www.onrr.gov/about/faqs.htm

**Comment by lpgoldstein** [comment]
http://2017onrr/about/faqs.htm

**Comment by jennmalcolm** [comment]
Instead of simply deleting it, let's make sure we have an archive folder (maybe on onedrive) where we can move files that we don't want to keep on the site. That way at least we'll have some sort of record of what used to be there.

**Comment by lpgoldstein** [comment]
@jennmalcolm that's a better idea.  I also need to figure out how to get rid of the link in the footer.

**Comment by jennmalcolm** [comment]
From what I can find, we have to edit the header and footer on each page. I'm going to work on the header anyway, so I can probably make this change at the same time.

**Comment by lpgoldstein** [comment]
Okay thanks. That's what it looked like to me too.

**Comment by lpgoldstein** [comment]
Archived page stored here N:\IDM\DD\Archived ONRR pages
