### ISSUE TITLE
Tab: Paying Contacts > Troubleshooting

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1530]
https://qmcq5k.axshare.com/#id=rmsbze&p=payments&g=1

**Comment by mcharg** [comment]
Got this as far as I could without linking to docs. https://dev-onrr-frontend.app.cloud.gov/about/contact/paying-contacts?tab=troubleshooting

**Comment by mcharg** [comment]
@cthomasONRR Documents are ready to review.

**Comment by cthomasONRR** [comment]
@mcharg approved

**Comment by mcharg** [comment]
@cthomasONRR This is ready for ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg Are there supposed to be any buttons present in the accordions?

**Comment by cthomasONRR** [comment]
Maybe the Payment Options, because you have similar buttons on other troubleshooting pages. Otherwise I think it's find to not have buttons 
![image](https://user-images.githubusercontent.com/72526208/164268162-488278a0-26c6-4dde-8967-e726c50c506a.png)
