### ISSUE TITLE
Tab: Updating Contact Info > Troubleshooting

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1533]
https://qmcq5k.axshare.com/#id=yo51a5&p=4444&g=1

**Comment by mcharg** [comment]
And for the Next buttons that take you to the next panel in the new reporter checklist.

**Comment by mcharg** [comment]
Got as far as I couldn't without linking to docs.
https://dev-onrr-frontend.app.cloud.gov/about/contact/4444-contacts?tab=troubleshooting

**Comment by mcharg** [comment]
@cthomasONRR This is ready for full ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg This looks good- set as approved by oddd
