### ISSUE TITLE
New within text link design

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/onrr.gov-site#154]
Link design needs to be consistent. Things to consider: 
- underline vs no underline
- color 
- hover state

**Comment by jennmalcolm** [comment]
Another thing to consider: 
A lot (I'm not sure about all) of our links to pdfs and external sites are set up to open in a new tab. This seems to not be the typical behavior, so we should decide if we have a reason to keep it this way and possible remove.

Here's an article that discusses when to use this behavior:

https://css-tricks.com/use-target_blank/

**Comment by jennmalcolm** [comment]
Link styles

Related to contrast, color should not be the only indication of the presence of a link. For people who are color blind or visually impaired, the links can be lost in the text. For links to be accessible, they should have a secondary visual characteristic (commonly underline) to distinguish them from other text.
image

**Comment by mcharg** [comment]
I got the links underlined in dev. Not sure how to edit hover state.

http://2017onrr/

**Comment by mcharg** [comment]
@jennmalcolm @lpgoldstein Do you want to review?

**Comment by lpgoldstein** [comment]
@mcharg The links underline for me on hover if that's the way it is supposed to work.

**Comment by mcharg** [comment]
@lpgoldstein They're supposed to be underlined by default and un-underline on hover.  You might have to do a hard refresh.

**Comment by lpgoldstein** [comment]
@mcharg looks good!

**Comment by mcharg** [comment]
This is now live.
