### ISSUE TITLE
Page: Sitemap

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1542]
https://qmcq5k.axshare.com/#id=d6wgq0&p=sitemap&g=1

**Comment by mcharg** [comment]
@Maroyafaied Are you okay with not having a sitemap page and just having the XML sitemap for SEO? I just had it there because we have it on the existing site, but I don't think it's needed for SEO.

**Comment by Maroyafaied** [comment]
@mcharg Do you know if having the sitemap as a page is good practice for accessibility purposes? That the only thing I can think of for have it as a page.

**Comment by mcharg** [comment]
We could just reuse the homepage blocks for a quick one.

**Comment by Maroyafaied** [comment]
@mcharg Thanks for looking into it, I'm fine with doing a quick one manually.

**Comment by mcharg** [comment]
@lpgoldstein This is ready to review.
https://dev-onrr-frontend.app.cloud.gov/site-map

**Comment by lpgoldstein** [comment]
Missing "How Leasing Works" 
![image](https://user-images.githubusercontent.com/39419003/167949346-7c54002b-f64a-4a6e-8eb6-72bef199fa6a.png)

**Comment by lpgoldstein** [comment]
And new reporter training

**Comment by lpgoldstein** [comment]
@mcharg Looks good.
