### ISSUE TITLE
Page: Disclaimer

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1543]
https://dev-onrr-frontend.app.cloud.gov/disclaimer
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/15
https://qmcq5k.axshare.com/#id=bp2rns&p=disclaimer&g=1

**Comment by daniel-coleman-1** [comment]
@Maroyafaied this page is good to review, aside from the current blocker around linking to it.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 this page doesn't have any blockers. I reviewed and looks good.
