### ISSUE TITLE
Tab: Payment Options > Pay.gov

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1544]
https://dev-onrr-frontend.app.cloud.gov/paying/payment-options
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/21
https://qmcq5k.axshare.com/#id=373ruk&p=payment_options&g=1

**Comment by daniel-coleman-1** [comment]
Blocker: needs blue buttons for links.

Otherwise, good to go.

**Comment by mcharg** [comment]
@daniel-coleman-1 

* Cards should use the primary color instead of purple.
* Add links to external sites and remove links to docs on the current onrr.gov site.
* Card titles should be H4, not H3

**Comment by mcharg** [comment]
Intro sentence is also missing a period.

**Comment by daniel-coleman-1** [comment]
@mcharg cards are purple on the wireframe.  Can you let me know what each of the colors is to be used for so I can add that to the content style guide?

**Comment by mcharg** [comment]
They're blue on the wireframes.  So far, it's the primary blue for everything except contact info, which is the secondary blue, and announcements, which are yellow.

**Comment by daniel-coleman-1** [comment]
@mcharg I've input your edits, should be good to go.

I did an accessibility check on the style tile and it's not accessible, so I added the following guidance in text in the ONRR content style guide:


![Screenshot 2022-01-28 121119](https://user-images.githubusercontent.com/83892362/151607510-a64d74aa-31de-4548-ad0c-509e05741b75.png)

I'm assuming this will expand as we continue to develop the site.

**Comment by mcharg** [comment]
@daniel-coleman-1 Looks good.  Moving to backlog.

**Comment by lpgoldstein** [comment]
added pdfs

**Comment by lpgoldstein** [comment]
added links @mcharg ready for approval

**Comment by mcharg** [comment]
@lpgoldstein Looks good. Moving to backlog until we get button.

**Comment by mcharg** [comment]
@cthomasONRR This is ready for ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg Approved
