### ISSUE TITLE
Tab: Payment Options > ACH

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1545]
https://dev-onrr-frontend.app.cloud.gov/paying/payment-options
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/21
https://qmcq5k.axshare.com/#id=373ruk&p=payment_options&g=1

**Comment by daniel-coleman-1** [comment]
Wireframe has a closed table but mine is open for the ONRR Bank Account information in dev.

Wireframe:
![Screenshot 2022-01-25 093735](https://user-images.githubusercontent.com/83892362/151019757-02b487a9-ba5c-4634-a7bc-8409e840bef9.png)



Dev:
![Screenshot 2022-01-25 093620](https://user-images.githubusercontent.com/83892362/151019784-71313b7f-ab42-43a1-a6dc-594242f01f96.png)

**Comment by daniel-coleman-1** [comment]
Blocker: table styling.

Otherwise, good to go.

**Comment by mcharg** [comment]
@daniel-coleman-1 Please remove the link to the document on the current site.

**Comment by daniel-coleman-1** [comment]
@mcharg removed

**Comment by mcharg** [comment]
@daniel-coleman-1 Looks good.  Moving back to backlog until we get the ability to link to documents.

**Comment by lpgoldstein** [comment]
added pdfs

**Comment by mcharg** [comment]
@cthomasONRR Doc added. Ready for full ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg I set the doc and page as approved
