### ISSUE TITLE
Tab: Payment Options > Fedwire

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1546]
https://dev-onrr-frontend.app.cloud.gov/paying/payment-options
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/21
https://qmcq5k.axshare.com/#id=373ruk&p=payment_options&g=1

**Comment by daniel-coleman-1** [comment]
need link to distributee codes:
![Screenshot 2022-01-25 105301](https://user-images.githubusercontent.com/83892362/151032033-5a9337e8-517a-4cf1-a927-e446b9afd783.png)

**Comment by daniel-coleman-1** [comment]
Blocker: table styling.  Both color and adding line breaks in between cells.
![Screenshot 2022-01-26 112230](https://user-images.githubusercontent.com/83892362/151223443-80c3eab1-ff94-42d7-bd77-aa69ccfe1dc7.png)

Otherwise good to go.

**Comment by mcharg** [comment]
@daniel-coleman-1 Please remove the link to the document on the current site.

**Comment by mcharg** [comment]
@daniel-coleman-1 Looks good.  Moving to backlog until we get the ability to link docs.

**Comment by lpgoldstein** [comment]
added pdfs

**Comment by mcharg** [comment]
@lpgoldstein I also added link to distributee codes in one of the tables. Approved doc and page.
