### ISSUE TITLE
Tab: Payment Options > Rent Payments

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1547]
https://dev-onrr-frontend.app.cloud.gov/paying/payment-options
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/21
https://qmcq5k.axshare.com/#id=373ruk&p=payment_options&g=1

**Comment by daniel-coleman-1** [comment]
Blocker: Blue buttons needed.

Otherwise, good to go.

**Comment by mcharg** [comment]
@daniel-coleman-1 Please remove the links to the documents on the live site.

**Comment by daniel-coleman-1** [comment]
@mcharg removed

**Comment by mcharg** [comment]
@daniel-coleman-1 Looks good.  Moving to the backlog until we get the ability to upload docs.

**Comment by lpgoldstein** [comment]
added pdfs

**Comment by mcharg** [comment]
@lpgoldstein Links look good.

**Comment by mcharg** [comment]
@cthomasONRR This is ready for ODDD approval.

**Comment by cthomasONRR** [comment]
@mcharg Approved
