### ISSUE TITLE
Add ability to link to a page with a specific expansion panel open

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1554]
This will be important for the troubleshooting guide.

**Comment by jlouis-onrr** [comment]
@mcharg, this issue is now out in dev, here is a sample of this:
https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist?panel=mail-your-completed-forms-to-onrr

**Comment by mcharg** [comment]
@jlouis-onrr Looks good. One issue - when I click on a closed panel, it sets the url, but I have to click it a second time to open the panel.
![image](https://user-images.githubusercontent.com/38465926/157754962-705df71e-5344-40b9-9f0d-e4dc34c9de5d.png)

**Comment by jlouis-onrr** [comment]
@mcharg.  Ok, I'll check out why that is occurring.
