### ISSUE TITLE
Design contact card search results

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1556]

**Comment by mcharg** [comment]
This page is in the prototype.
https://qmcq5k.axshare.com/#id=fdd7df&p=search_results&g=1

@cthomasONRR Do you want to review?

**Comment by cthomasONRR** [comment]
@mcharg I played around with the category filters, and they work well! Here are the issues I found:

The Indian Services section has some formatting errors:
![image](https://user-images.githubusercontent.com/72526208/153036074-fc53fa13-3b41-4513-8cb6-8ce18db29850.png)

The Oil and Gas Production - Onshore contact list here is not updated to reflect the changes you made yesterday:
![image](https://user-images.githubusercontent.com/72526208/153036536-860bf0d9-c4e9-4a66-9cc2-c03b7207e6e7.png)

**Comment by mcharg** [comment]
@cthomasONRR Updated with the new onshore production contacts.  The wrapping issues will have to wait until build. https://qmcq5k.axshare.com/#id=fdd7df&p=search_results&g=1

**Comment by cthomasONRR** [comment]
@mcharg Looks good! Thanks :)
