### ISSUE TITLE
Make it easier to have content in a right rail

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1559]
One potential solution is to make it so that cards without cards next to them size to the content inside the card instead of the content next to it.  To prevent things like this: https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/cooperative?tab=ipa-fellowship-program

**Comment by mcharg** [comment]
We have a workaround where we can split the content not in the block from the content next to the block.  Will open a new issue if we discover places where the workaround doesn't work.

**Comment by mcharg** [comment]
Other pages.
https://dev-onrr-frontend.app.cloud.gov/indian/assistance?tab=federal-indian-minerals-office
https://dev-onrr-frontend.app.cloud.gov/indian/assistance?tab=indian-energy-service-center

**Comment by mcharg** [comment]
So they can stack and not break up content in the left column in responsive views.

**Comment by mcharg** [comment]
Upped the priority on this one because the workaround isn't working well for the valuation examples.

**Comment by jlouis-onrr** [comment]
@mcharg, CMS frontend is back up now and the ability to equalize card heights and add outer columns to pages and tab content is in dev.  I've setup some examples in the builder page and also on this page: https://dev-onrr-frontend.app.cloud.gov/indian/assistance?tab=indian-energy-service-center

**Comment by jlouis-onrr** [comment]
@mcharg, when creating any new layouts choose from the 'Add Existing' option.  This will prevent dupes from being created.  Currently Directus doesnt support attaching a singleton collection to the m2a field.  It breaks the blocks builder.  Its currently a bug and there are requests for this feature with Directus.

**Comment by mcharg** [comment]
@jlouis-onrr Looks good!
