### ISSUE TITLE
Create a study plan for the card sorting study 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#156]

**Comment by mcharg** [comment]
I started a plan.
https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B0f1fdd33-336a-4bd5-9c66-c1d155348f4f%7D&action=edit&wdPid=9dd3738

@jennmalcolm @Maroyafaied  Do you want to review?

**Comment by Maroyafaied** [comment]
@mcharg it looks great, I added one comment at the end.
