### ISSUE TITLE
Tab: Late Payment Interest > Rates

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1561]
https://dev-onrr-frontend.app.cloud.gov/paying/interest?tab=rates
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/38
https://qmcq5k.axshare.com/#id=qw8sdk&p=late_payment_interest

**Comment by mcharg** [comment]
Blocked by not having the interest rates collection.

**Comment by Maroyafaied** [comment]
Added the collections to the webpage

**Comment by Maroyafaied** [comment]
@cthomasONRR can you please review and mark this page as "Approved by ODDD" if everything looks good? Thanks

**Comment by cthomasONRR** [comment]
@Maroyafaied These are already set to "Approved by SME"

**Comment by Maroyafaied** [comment]
@cthomasONRR It shouldn't have that status since we left that page out when we asked the Paying section SMEs to review, it wasn't completed at the time. 
![image](https://user-images.githubusercontent.com/40175688/171211306-7bf0c2f9-f7dc-4a3a-aa9d-8ba7359cbf64.png)

**Comment by cthomasONRR** [comment]
@Maroyafaied OK I set the Late Payment Interest page back to "Approved by ODDD"
