### ISSUE TITLE
Tab: Late Payment Interest > Interest Calculator

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1562]
https://dev-onrr-frontend.app.cloud.gov/paying/interest?tab=interest-calculator
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/38
https://qmcq5k.axshare.com/#id=qw8sdk&p=late_payment_interest

**Comment by mcharg** [comment]
@lpgoldstein We need to copy the content from the Sample Calculation pop-up on this page.
https://www.onrr.gov/reportpay/interest.htm

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 Let @mcharg know if you need help. Thanks

**Comment by daniel-coleman-1** [comment]
@mcharg added the content from the pop up to the interest calculator.  The current formula image is grainy so I made a new image, what do you think?  Should we go with something more stylized?

Blockers: need to add subscript and superscript options to text, needs shift+enter line breaks within the table, need to be able to resize images, if we want to keep the below blue we need text color and text background color options:
![Screenshot 2022-01-27 144439](https://user-images.githubusercontent.com/83892362/151448777-6a5b123e-3c68-4504-afa4-30205d3d3a7d.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 Try using a card with the primary color for the principal and interest rates.

@Maroyafaied Who owns this page?  We should try to get a higher res image of the formula from them or see if there are requirements when creating a new one.

**Comment by Maroyafaied** [comment]
@mcharg @lpgoldstein This page is owned by the Financial Services , you can email Chris Davis or this mailbox and ask for a better pic. ONRR-RFMASGL@onrr.gov

**Comment by daniel-coleman-1** [comment]
@Maroyafaied I sent them an email

**Comment by daniel-coleman-1** [comment]
I just got an email saying the image I provided works

**Comment by mcharg** [comment]
@daniel-coleman-1 I did some layout cleanup to make this page more scannable and added dependencies.  Moving to backlog.

**Comment by daniel-coleman-1** [comment]
@mcharg it looks good to me, I added some line breaks to decrease cognitive load on the reader:
![Screenshot 2022-03-17 102939](https://user-images.githubusercontent.com/83892362/158848304-ac750c67-4149-4e42-a574-9233f595958f.png)


![Screenshot 2022-03-17 102958](https://user-images.githubusercontent.com/83892362/158848325-a449714b-dd43-4d6a-b101-008bae4b7b2c.png)

**Comment by mcharg** [comment]
We should probably wait until we know the document link is final before approving. We shouldn't wait on superscript, but that likely won't be a priority before launch.

**Comment by mcharg** [comment]
Closing, since the link is final. @daniel-coleman-1 I updated the page in the content tracking sheet to Approved by ODDD.
