### ISSUE TITLE
Late Payment & Underpayment Interest

### ISSUE THREAD

**Issue by bbell0229** [ONRR/onrr.gov-site#1565]
Good Morning,

On the Late Payment & Underpayment Interest Tables page, at https://onrr.gov/ReportPay/interest.htm, please make the following updates:

Replace the interest calculator excel file below the questions/contact box on the page.

If you have any questions let me know.
[Interest_Calculator_Master.xlsx](https://github.com/ONRR/onrr.gov-site/files/7936944/Interest_Calculator_Master.xlsx)

Thank you!

Brittney Bell

**Comment by cthomasONRR** [comment]
@bbell0229 

This change is available on the dev site: http://2017onrr/reportpay/interest.htm.
Please review and give us your approval to go live.

Thanks!
Christine

**Comment by bbell0229** [comment]
Good to go live!

Brittney A. Bell
Staff Accountant, Financial Services
Revenue, Reporting, & Compliance Management
Office of Natural Resources Revenue
Bldg 85, Denver Federal Center
Denver, CO 80225
1-800-433-9801 x 3381
303.231.3381
***@***.******@***.***>

From: Christine Thomas ***@***.***>
Sent: Tuesday, January 25, 2022 2:01 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bell, Brittney A ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Late Payment & Underpayment Interest (Issue #1565)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bbell0229<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbbell0229&data=04%7C01%7Cbrittney.bell%40onrr.gov%7C4cd8764b52c340775a8608d9e045ece0%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637787413197878633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bF6eAByIKq6SjwcoEd4SK6Gx2fPf%2BByQYA6w5p8%2F1Q8%3D&reserved=0>

This change is available on the dev site: http://2017onrr/reportpay/interest.htm.
Please review and give us your approval to go live.

Thanks!
Christine

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1565%23issuecomment-1021604540&data=04%7C01%7Cbrittney.bell%40onrr.gov%7C4cd8764b52c340775a8608d9e045ece0%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637787413197878633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=clEj54%2FT8DjFiq45oKmprtjFykmUYcGiyC4n%2FANkls8%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUVLX3PKUTPUT67X5533AUTUX4FSHANCNFSM5MZI6ENA&data=04%7C01%7Cbrittney.bell%40onrr.gov%7C4cd8764b52c340775a8608d9e045ece0%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637787413197878633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0i31BBHY1oDqzh0IHIhtqBrjTSJbArNvuSZHcKRskG4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cbrittney.bell%40onrr.gov%7C4cd8764b52c340775a8608d9e045ece0%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637787413197878633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=e2c%2F7c1dP4kK%2FXvuLuZrZaXXVKOL1wkLO2g6u8YI0qA%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cbrittney.bell%40onrr.gov%7C4cd8764b52c340775a8608d9e045ece0%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637787413197878633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bWrP%2B1TG8MfN6N5vABd7iDYB9Mk8U6q5j3JhSqydtYM%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@bbell0229 Great! The changes are now live: https://onrr.gov/ReportPay/interest.htm.
Please remember to use Ctrl+F5 to refresh the page.

I will close this issue now.

Thanks,
Christine
