### ISSUE TITLE
Dear Reporter Letter

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1566]
Please add the attached Dear Reporter Letter to the following page - https://www.onrr.gov/DearRep.ht
[Dear Reporter Letter - File Structure Change_01242022.pdf](https://github.com/ONRR/onrr.gov-site/files/7937802/Dear.Reporter.Letter.-.File.Structure.Change_01242022.pdf)
m

**Comment by daniel-coleman-1** [comment]
@bowlenj edits applied in dev for your review:
http://2017onrr/DearRep.htm

with your approval I will push these changes live.

**Comment by bowlenj** [comment]
This looks great!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: daniel-coleman-1 ***@***.***>
Sent: Tuesday, January 25, 2022 4:25 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Dear Reporter Letter (Issue #1566)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C73102085fcb946aa010208d9e05a0811%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637787499568566342%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CrzUDd3Y%2BQFoWg2in3NjZNYo1B%2BXsSAvsRgSp2dO72o%3D&reserved=0> edits applied in dev for your review:
http://2017onrr/DearRep.htm

with your approval I will push these changes live.

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1566%23issuecomment-1021704072&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C73102085fcb946aa010208d9e05a0811%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637787499568566342%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NPpBiO4OazQSa1O9anWZLjJKtzPexGwpaz62Y095g%2BA%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VHZBPMBKZGAYILCDPFLUX4WPLANCNFSM5MZSA4HA&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C73102085fcb946aa010208d9e05a0811%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637787499568566342%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jTXPs9Khyttki5U1L9kTkNI7AQxElJPDag3y4SimzTg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C73102085fcb946aa010208d9e05a0811%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637787499568566342%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JTaSp7mhRlrhpRodh5MI0rzKfBK5uhjDVzhqlQyazck%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C73102085fcb946aa010208d9e05a0811%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637787499568566342%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FG%2F3W6LaKZaGwD72cJiEMw7zfjrM8Thg17csUoarbz4%3D&reserved=0>.

**Comment by daniel-coleman-1** [comment]
@bowlenj fantastic, we are live:
https://www.onrr.gov/DearRep.htm

**Comment by Maroyafaied** [comment]
@bowlenj I apologize but we realized that accessibility checks weren't done before @daniel-coleman-1 uploaded this dear reporter letter to onrr.gov.  The accessibility check shows 2 errors, can you please correct them and resend the accessible version to be uploaded? Thanks
![image](https://user-images.githubusercontent.com/40175688/161133094-273a1cc4-f2f7-4130-9042-40a8da438d51.png)

**Comment by bowlenj** [comment]
I've downloaded the document and I'm trying to fix the errors but it's saying the document security settings won't allow the fix.  I'm not able to do anything with it in the content or tags panel either.  I'm not sure how to correct the document.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Maroyafaied ***@***.***>
Sent: Thursday, March 31, 2022 1:21 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Dear Reporter Letter (Issue #1566)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cc8870ad0e01e42b586a608da134baea2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637843513011797944%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MvqfwJC%2B6oTNi51ZzEX9%2Bh4gm9vPJyfog1nqcTWcLx0%3D&reserved=0> I apologize but we realized that accessibility checks weren't done before @daniel-coleman-1<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdaniel-coleman-1&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cc8870ad0e01e42b586a608da134baea2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637843513011797944%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ReB4FfM2RzSSBq55JoKasr4LcuWOstFHlTU4KzY03ig%3D&reserved=0> uploaded this dear reporter letter to onrr.gov. The accessibility check shows 2 errors, can you please correct them and resend the accessible version to be uploaded? Thanks
[image]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F40175688%2F161133094-273a1cc4-f2f7-4130-9042-40a8da438d51.png&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cc8870ad0e01e42b586a608da134baea2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637843513011797944%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4LZXqp8oPfxN%2BClg9dXDEUXsZIjWGu6sSVI4HdLY7iU%3D&reserved=0>

**Comment by Maroyafaied** [comment]
@bowlenj Do you happen to have the source file? This is the only pdf version I have that was attached to this issue.
[Dear.Reporter.Letter.-.File.Structure.Change_01242022.pdf](https://github.com/ONRR/onrr.gov-site/files/8392714/Dear.Reporter.Letter.-.File.Structure.Change_01242022.pdf)

**Comment by bowlenj** [comment]
Candace and I both reviewed the attached Dear Reporter Letter - File Structure, and due to document security settings applied at the time of signature we are now unable to make this document compliant.  It was originally compliant but it looks like this is a new error and we are unable to correct it.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Maroyafaied ***@***.***>
Sent: Thursday, March 31, 2022 1:59 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Dear Reporter Letter (Issue #1566)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cfc947c3ef7f645a7a4c108da13511b89%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637843536330139156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4omR7cijUts%2F7ljP05iphUmqjmJmaoVVBP77jhATIlk%3D&reserved=0> Do you happen to have the source file? This is the only pdf version I have that was attached to this issue.
Dear.Reporter.Letter.-.File.Structure.Change_01242022.pdf<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Ffiles%2F8392714%2FDear.Reporter.Letter.-.File.Structure.Change_01242022.pdf&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cfc947c3ef7f645a7a4c108da13511b89%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637843536330139156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=b7rkPfXExNG5T5CYTyo%2FcpX4AKR1znejGq%2Bmd5Rr7Js%3D&reserved=0>

**Comment by Maroyafaied** [comment]
Another issue is open for this #1752
