### ISSUE TITLE
Create Webpages for Current ICRs

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1567]
Parent site: https://dev-onrr-frontend.app.cloud.gov/references/icrs

- [x] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0001
- [x] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0002
- [x] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0003
- [x] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0004
- [x] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0005
- [x] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0006
- [x] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0008
- [x] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0009
- [x] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0010

**Comment by cthomasONRR** [comment]
All of the Forms links within each ICR page needs to be updated with a new website link. They are currently directing to the current/live onrr.gov site.

**Comment by cthomasONRR** [comment]
@mcharg These are ready for your review. When you have time, I'd also like some help adding them to the ContentTracking excel. Thanks!

**Comment by mcharg** [comment]
Added #1572 for adding documents.

**Comment by cthomasONRR** [comment]
@mcharg Great! I can take that issue once we're have document-adding functionality!

**Comment by mcharg** [comment]
@cthomasONRR Looks good.  I checked all the link except for forms and created a new issue for adding the forms links, so closing.
