### ISSUE TITLE
Create new webpages for each handbook

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1570]
Parent site: https://dev-onrr-frontend.app.cloud.gov/references/handbooks

- [x] Minerals Revenue 
https://dev-onrr-frontend.app.cloud.gov/references/handbooks/minerals-revenue-reporter-handbook
- [x] Minerals Production 
https://dev-onrr-frontend.app.cloud.gov/references/handbooks/minerals-production-reporter-handbook
- [x] Solid Minerals 
https://dev-onrr-frontend.app.cloud.gov/references/handbooks/solid-minerals-reporter-handbook
- [x] Geothermal - Class 1
https://dev-onrr-frontend.app.cloud.gov/references/handbooks/geothermal-class-1
- [x] Geothermal - Class 2 and 3
https://dev-onrr-frontend.app.cloud.gov/references/handbooks/geothermal-class-2-and-3
- [x] Indian Payor
https://dev-onrr-frontend.app.cloud.gov/references/handbooks/indian-payor-handbook

**Comment by cthomasONRR** [comment]
@mcharg These pages are ready for your review. This review is just to check the link on the parent site and verify that I made the new handbook pages correctly. No content is on the individual handbook pages yet. I added these new pages to the content tracking spreadsheet, and set their status to Blocked.

**Comment by mcharg** [comment]
@cthomasONRR Pages and links from the handbooks page look good.  I think we should mark the pages as blocked, since we need to discuss with developers how to best build those pages.

**Comment by mcharg** [comment]
I marked them as blocked.
