### ISSUE TITLE
Add documents to current ICR pages

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1572]
Parent site: https://dev-onrr-frontend.app.cloud.gov/references/icrs

- [x] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0002
- [x] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0004
- [x] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0005
- [x] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0006
- [x] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0008
- [x] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0010

**Comment by mcharg** [comment]
@cthomasONRR I fixed the icons.  The rest looks good.

**Comment by mcharg** [comment]
@cthomasONRR Marked all these pages as Approved by ODDD in the tracking sheet.

**Comment by cthomasONRR** [comment]
thank you!

**Comment by cthomasONRR** [comment]
@mcharg This is ready for your review. All the pages were already set to approved by oddd, but all the docs still need approval. I have them set as ready to review on the spreadsheet. After your review, this issue can be closed :)

**Comment by mcharg** [comment]
@cthomasONRR These all look good. Spreadsheet updated.
