### ISSUE TITLE
Create Rulemaking pages

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1575]
All the pages linked from here need to be created.
https://qmcq5k.axshare.com/#id=h57jbd&p=rulemakings

**Comment by mcharg** [comment]
@cthomasONRR Created these ones yesterday.  I will review and check off when I approve.

- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/aa29
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/aa27
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/aa26
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/aa25
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/aa24
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/aa23

**Comment by mcharg** [comment]
@cthomasONRR On AA27, I'm getting this error when I click on the beta.regulations.gov page on both the old and new sites. ![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/0cb9739d-e916-49d4-a07b-8fed7fef691d)

**Comment by cthomasONRR** [comment]
@mcharg I will remove the beta link- that's from when they were redesigning regulations.gov. It's not necessary anymore.

**Comment by cthomasONRR** [comment]
@mcharg New batch to review. I'm going to send them out in groups of ~8-10. I'm having some of the same tabbing/indentation issues I mentioned in FOGRMA, but all content is there.

- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/aa22
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/aa21
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/aa20
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/aa17
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/aa15
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/aa14
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/aa13
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/aa11
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ad70

**Comment by cthomasONRR** [comment]
@mcharg New batch to review:

- [ ] https://www.onrr.gov/Laws_R_D/FRNotices/AA08.htm
- [ ] https://www.onrr.gov/Laws_R_D/FRNotices/AA05.htm
- [ ] https://www.onrr.gov/Laws_R_D/FRNotices/AA04.htm
- [ ] https://www.onrr.gov/Laws_R_D/FRNotices/AA03.htm
- [ ] https://www.onrr.gov/Laws_R_D/FRNotices/AA02.htm

**Comment by Baymatt** [comment]
@cthomasONRR Here is the first batch of my links to review, I've also added the ones we added during our meeting.

- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ad32
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ad28
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ad22
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ad20
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ad05
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ad04
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ad01
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ad00
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ac86

**Comment by Baymatt** [comment]
@cthomasONRR Finished up the remaining MMS Revenue Rulemakings and adding links for review. The spreadsheet is updated but the first column needs reordering.

- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ac72
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ac70
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ac59
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ac51
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ac40
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ac38
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ac30
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ac25
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ac21
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ac08
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ac06
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ac00
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ab57
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ab17
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/89coal

**Comment by cthomasONRR** [comment]
@Baymatt @mcharg I marked the following regs pages as 'Blocked' because they require internal/CMS links to forms. This is noted in the status and comments section of the tracking sheet.

https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ad22
https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ad01
https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ac86

The following are Blocked because ey require internal/CMS links to other CMS webpages (like NYMAX) but because of tabs, the link isn't navigating to the correct page. This is noted in the status and comments section of the tracking sheet.

https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/ad04

**Comment by mcharg** [comment]
@cthomasONRR Reviewed all the ones that weren't checked.  All look good.
