### ISSUE TITLE
Make individual webpages for each discontinued ICR

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1584]
Parent:
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/46
https://dev-onrr-frontend.app.cloud.gov/references/icrs?tab=discontinued

**Comment by cthomasONRR** [comment]
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0012
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0007
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1010-0090
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1010-0140
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1010-0169
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1010-0110
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1010-0074
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1010-0088
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1010-0138
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1010-0104

**Comment by cthomasONRR** [comment]
@mcharg These pages are ready for your review.

**Comment by mcharg** [comment]
@cthomasONRR Getting a page not found for this one. https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0007

**Comment by cthomasONRR** [comment]
@mcharg I just checked the CMS for 1012-0007 (Page ID 146) and everything looks fine :( I don't know what's going on.

**Comment by mcharg** [comment]
@cthomasONRR It's working now.

**Comment by mcharg** [comment]
@cthomasONRR These all look good.
