### ISSUE TITLE
Clean up contacts pages in prototype for user testing

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1586]
Need to add pagination.

**Comment by mcharg** [comment]
All the contacts pages now have pagination.  @cthomasONRR Do you want to take a look and see if I missed anything?
https://qmcq5k.axshare.com/

**Comment by cthomasONRR** [comment]
Is this the correct location? https://qmcq5k.axshare.com/#id=079wgt&p=contact_us
Sorry- what is new that I should be checking?

**Comment by mcharg** [comment]
@cthomasONRR The cards on the Contacts tab on each of the pages linked from Contact Us now have pagination.

**Comment by cthomasONRR** [comment]
Ok sorry for misunderstanding.

Several pages have this type of overlap with the cards and page navigation, so I think the pages in Axure need to be lengthened. Here's an example within Oil & Gas Production:
![image](https://user-images.githubusercontent.com/72526208/152859649-03307db0-c393-47e6-9a0c-33a9adeb2afb.png)

Would it be possible to also have links to first page and last page in addition to previous and next?
![image](https://user-images.githubusercontent.com/72526208/152859923-c8f8fffb-be67-4e90-bb75-4b9c86107afd.png)

Axure is now generating the project. Will post more comments once I can access again...

**Comment by cthomasONRR** [comment]
Geothermal has some weird formatting overlap:
![image](https://user-images.githubusercontent.com/72526208/152861196-9e61e0bc-6356-4654-83f3-163cdc865ab2.png)

Pages that have overlap with the cards and page navigation (mentioned in the comment above): Oil & Gas Production, Payments & Debt Collection - Federal Accounts Receivable, 

Aside from that, it they all look really good!!!

**Comment by cthomasONRR** [comment]
@mcharg Sounds good!!!

**Comment by mcharg** [comment]
@cthomasONRR Fixed geothermal. https://qmcq5k.axshare.com/#id=b5lzlu&p=geothermal_1

**Comment by cthomasONRR** [comment]
@mcharg Looks good! Herb Black retired, so we should probably remove his name. I doubt anyone in RV will remember to request its removal...

**Comment by mcharg** [comment]
@cthomasONRR Good call.  I also saw Bruce Rumberg still in the list.  @cvojslavek Do you know who should be taking over Bruce's contacts?

**Comment by cvojslavek** [comment]
@mcharg @cthomasONRR Hi! I believe Bruce Rumburg should still be on there because he is still the Agreement Officer Representative. I can check with him if you'd like.

**Comment by mcharg** [comment]
@cvojslavek Thanks!

We've got him listed a few times on the STRAC page. https://qmcq5k.axshare.com/#id=5fxgha&p=strac&g=1

**Comment by cvojslavek** [comment]
@mcharg I connected with Bruce and he said he can be in each of those categories, i.e., Agreement Administration, Intergovernmental Personnel Act Fellowship Program, and Work Planning & Budgets. 
Looks great!
