### ISSUE TITLE
Finalize capitalization guidance for CMS

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/onrr.gov-site#1587]
- [ ] H1s
- [ ] H2s
- [ ] H3s
- [ ] H4s
- [ ] H5s
- [ ] Card H2s
- [ ] Card H3s
- [ ] Card H4s
- [ ] Tab Headings
- [ ] Accordions
- [ ] Table headers

**Comment by daniel-coleman-1** [comment]
@mcharg here's what I'm thinking, but I don't know of any examples of H5s on the site.  Can you show me where we have an H5 or two on the wireframe?

H1s – Title Case
H2s – Title Case
H3s – Title Case
H4s – Title case
H5s – Sentence case

Card H2s – Title Case
Card H3s – Title Case
Card H4s – Title case

Tab Headings – Title Case
Accordions – Title Case
Table Headers – Title Case

**Comment by mcharg** [comment]
@daniel-coleman-1 

Why is H5 the only one that's sentence case?  If all other headers are title case, we might as well make that one title, as well.

The Approve Publications headers on this page are H5.
https://dev-onrr-frontend.app.cloud.gov/references/valuation?tab=federal-gas-index-option

For accordions, a lot of them are actual sentences (like in the troubleshooting guide and new reporter checklist), so I'd be inclined to use sentence case for those.

**Comment by daniel-coleman-1** [comment]
@mcharg I'm not sure I'm seeing the H5 correctly, can you post a screenshot?

I took another look at the accordions and you're right, many are actual sentences and sentence case does make more sense, so I changed that guidance.

**Comment by mcharg** [comment]
@daniel-coleman-1 You can right click on the page and use the Inspect option to view the code and get the heading levels or you could look at the page in the CMS.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/d0e6a960-78c4-4959-808d-877852900e23)

**Comment by mcharg** [comment]
@daniel-coleman-1 Another H5 example.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/875f3670-ce6e-4edb-8912-74aa067df31f)

**Comment by mcharg** [comment]
@daniel-coleman-1 And another.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/08d75c91-7061-45b4-b6db-8fddc26350ed)

**Comment by Maroyafaied** [comment]
All headings will be title case, and the accordions will be sentence case. @daniel-coleman-1 please add this guidance to onrr.gov's wiki. Thanks

**Comment by daniel-coleman-1** [comment]
![Screenshot 2022-02-09 131146](https://user-images.githubusercontent.com/83892362/153282322-d733e5b6-39f8-4bb0-8389-b1aa22067222.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 what you have doesn't mention H5.

**Comment by daniel-coleman-1** [comment]
@mcharg nice catch, amended.
![Screenshot 2022-02-09 134117](https://user-images.githubusercontent.com/83892362/153286410-4bccbdc3-4dd9-4a52-8e2c-ff3ddda0c8ec.png)
