### ISSUE TITLE
Update Production Reporting References

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1590]
All, 

On the ONRR.gov home page, please update the Production Reporting References with the attached files. The new as of date is 02/01/2022.
There are five Gulf files.

Thank you,

Johnny Erle

Minerals Revenue Specialist - Offshore Production
Reference and Reporting Team 1A
Office of Natural Resources Revenue
Office: (303) 231-3577

**Comment by cthomasONRR** [comment]
- [ ] [Gulf-Metering-Systems.xlsx](https://github.com/ONRR/onrr.gov-site/files/7981211/Gulf-Metering-Systems.xlsx)
- [ ] [Gulf-Sales-Tanks.xlsx](https://github.com/ONRR/onrr.gov-site/files/7981213/Gulf-Sales-Tanks.xlsx)
- [ ] [Gulf-Gas-Plants.xlsx](https://github.com/ONRR/onrr.gov-site/files/7981215/Gulf-Gas-Plants.xlsx)
- [ ] [Gulf-Flash-Gas.xlsx](https://github.com/ONRR/onrr.gov-site/files/7981216/Gulf-Flash-Gas.xlsx)
- [ ] [Gulf-Buy-Back.xlsx](https://github.com/ONRR/onrr.gov-site/files/7981217/Gulf-Buy-Back.xlsx)

**Comment by mcharg** [comment]
Docs updated in CMS.
