### ISSUE TITLE
Add content to the Minerals Revenue Reporter Handbook

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1592]

**Comment by mcharg** [comment]
@cthomasONRR Docs are uploaded and ready to review.

**Comment by cthomasONRR** [comment]
@mcharg Doc links look good. Approving. This stays in backlog to wait for the handbook collection.

**Comment by Maroyafaied** [comment]
@cthomasONRR  this link goes to the paying section instead of the oil and gas revenue reporting. 

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/6f1bc718-feb4-4b21-9fd7-ad4409a2a9b1)

**Comment by cthomasONRR** [comment]
@Maroyafaied Fixed

**Comment by Maroyafaied** [comment]
@cthomasONRR looks good.
