### ISSUE TITLE
Add content to the Minerals Production Reporter Handbook

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1593]

**Comment by mcharg** [comment]
@cthomasONRR This is ready to review.

**Comment by cthomasONRR** [comment]
@mcharg I think Appendices E and F are incorrect. Their URL indicates "RRM-Appendix.E" which is the naming scheme that RRM used for the MRRH. If you look on the Y drive (Y:\reportpay\Handbooks\pdfdocs) there is MPRH-Appendix-E and MPRH-Appendix-F, which have different content. I think these are the correct appendices to include here.
![image](https://user-images.githubusercontent.com/72526208/159918815-6964b562-1d58-4410-bfc4-a1d00360bc77.png)

**Comment by cthomasONRR** [comment]
@mcharg I went in the CMS and replaced these 2 documents. Everything is approved now.
