### ISSUE TITLE
Add content to the Solid Mineral Reporter Handbook

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1594]

**Comment by mcharg** [comment]
@Isabelh99 Looks good.
@cthomasONRR Do you want to review, as well?

**Comment by cthomasONRR** [comment]
@mcharg I just looked over the PDF links, and they are all correct.

**Comment by mcharg** [comment]
@cthomasONRR Great. Moving to backlog until we get the TOC collection.
