### ISSUE TITLE
Add content to the Geothermal Payor Handbook - Class 1 Leases

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1595]

**Comment by jkwonatx** [comment]
Done. Ready for review @cthomasONRR

**Comment by cthomasONRR** [comment]
@jkwonatx I checked the docs and everything looks good! Thanks for your help. I'll move this issue back to the Product Backlog because the Table of Contents is still needed.

**Comment by Maroyafaied** [comment]
@cthomasONRR In the Supplemental Information tab can you please add  Appendix B, and change the title to Appendix A to match the TOC. ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/5f60100d-b074-488f-a395-6f392af14928)
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/049d3e0e-22dd-437d-a9df-9550b7d18948)

**Comment by cthomasONRR** [comment]
@Maroyafaied There is not a separate Appendix B document. It's this way on the live site too:
![image](https://user-images.githubusercontent.com/72526208/169125602-0676451c-29f3-41f1-ba30-9a3bcc0612ae.png)

**Comment by Maroyafaied** [comment]
@cthomasONRR We can Keep them as one document, but let's change the title to "Appendix A and B - Class 1"

**Comment by cthomasONRR** [comment]
@Maroyafaied Is this better? 
https://dev-onrr-frontend.app.cloud.gov/references/handbooks/geothermal-class-1?tabs=supplemental-information
![image](https://user-images.githubusercontent.com/72526208/169144027-3487b241-a2e2-4352-b6fa-d4246422db57.png)
