### ISSUE TITLE
Add content to the Geothermal Payor Handbook - Class 2&3 Leases

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1596]

**Comment by kmhtran** [comment]
@cthomasONRR Finished and is now ready to review.

**Comment by cthomasONRR** [comment]
@kmhtran This looks great, thank you for your help! Approved. I'm moving this back to Product Backlog because we still need to do the Table of Contents.

**Comment by Maroyafaied** [comment]
@cthomasONRR the TOC looks good . In the Supplemental Information tab, can you list Appendix A and B separately with the same titles as the TOC. 
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/7df00fa7-ead9-4a35-afc2-550590df3c8e)
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/edbfdaba-eed2-4c98-98a8-3d7274f581bc)

**Comment by cthomasONRR** [comment]
@Maroyafaied It's a single PDF in the documents library, and it like this on the live site too

![image](https://user-images.githubusercontent.com/72526208/169124102-bc895b9d-be2e-4759-9ddd-2cce78f1db1b.png)
![image](https://user-images.githubusercontent.com/72526208/169124326-8e7b448a-9ef7-4af0-8a1c-6c486b0a6775.png)

**Comment by Maroyafaied** [comment]
@cthomasONRR The handbook has them separated and Appendix A is definition of terms not contacts.  We can ask RV if they prefer to keep it like the live site but it would be inconsistent with what we have in the TOC and the handbook. 

![image](https://user-images.githubusercontent.com/40175688/169132484-ca09a58a-73f1-401c-b510-cf3cbd3ae1ae.png)

**Comment by cthomasONRR** [comment]
@Maroyafaied I'm not sure what you want me to do- I do not have separate PDFs of appendix a and b to upload.

**Comment by Maroyafaied** [comment]
@cthomasONRR We can Keep them as one document, but let's change the title to "Appendix A and B - Class 2 & 3"

**Comment by cthomasONRR** [comment]
@Maroyafaied Is this better?
https://dev-onrr-frontend.app.cloud.gov/references/handbooks/geothermal-class-2-and-3?tabs=supplemental-information
![image](https://user-images.githubusercontent.com/72526208/169143942-b1a9504d-53fe-4dec-802c-29c5e34785f1.png)

**Comment by Maroyafaied** [comment]
Yes, thanks.
