### ISSUE TITLE
Add content to the Indian Payor Handbook (all tabs)

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1597]
- https://www.onrr.gov/reportpay/Handbooks/indian-payor-handbook.htm
- https://qmcq5k.axshare.com/#id=4b22sl&p=indian_payor_handbook&g=1
- https://dev-onrr-frontend.app.cloud.gov/references/handbooks/indian-payor-handbook?tab=chapter-1-about-this-handbook
- https://dev-onrr-cms.app.cloud.gov/admin/content/pages/99

**Comment by cthomasONRR** [comment]
Items blocking this from being complete:

- Several instances of linking internal ONRR documents (like the full chapters, Dear Reporter Letters, and specific chapters of other Handbooks)
- Need better dimensions for tables
- Need better dimension editing for cards
- Need better dimension editing for images
- There is an image (Ch 3.1) that will need to be updated to reflect the new website
- For the 'Updated Rules' tab, we need to add in a filtered version of the Rulemakings collection, filtered to show just Indian Rulemakings

**Comment by cthomasONRR** [comment]
@mcharg Let me know if you'd like to review, or I can just move it back to Product Backlog

**Comment by mcharg** [comment]
@cthomasONRR Looks good.  Adjusted a few heading levels and moving to backlog.

**Comment by cthomasONRR** [comment]
@mcharg Awesome, thanks!!!

**Comment by mcharg** [comment]
@cthomasONRR Image size and alignment is now in (in the 4 dots menu to the right of the image), if you want to go in and adjust any of the images in the handbook.

**Comment by cthomasONRR** [comment]
@mcharg Images are adjusted, not many needed to be manually adjusted. I have issue #1660 out but it is associated with alt text, not size adjusting. I'm putting this issue in the product backlog again.

**Comment by lpgoldstein** [comment]
uploaded pdfs

**Comment by lpgoldstein** [comment]
@mcharg linked pdfs

**Comment by mcharg** [comment]
@lpgoldstein Looks good.

@cthomasONRR I noticed in your checklist above that there are other documents that need to be linked. Do you want to add those?

**Comment by cthomasONRR** [comment]
Added PDFs or links to other (new) onrr.gov pages to sections:
- [ ] 1.6
- [ ] 2.4.2
- [ ] 2.5.5.4
- [ ] 2.7
- [ ] 3.1 (Will need to update navigation language)

We still need the ability to link to Dear Reporter Letters on sections:
- [ ] 2.4.5
- [ ] 2.5.6

Other:
- [ ] The product code image here (section 2.11) is now missing: https://dev-onrr-frontend.app.cloud.gov/references/handbooks/indian-payor-handbook?tabs=chapter-2-indian-valuation-basics,211
- [ ] There is an image (Ch 3.1) that will need to be updated to reflect the new website, and navigation instruction will need updating too
- [ ] There is a map image that is now missing at 3.1.1.1 (https://dev-onrr-frontend.app.cloud.gov/references/handbooks/indian-payor-handbook?tabs=chapter-3-indian-oil-valuation,31&panel=3111-designated-areas)

**Comment by cthomasONRR** [comment]
@mcharg For the Updated Rules section, can we just have a link that brings them to the filtered Rulemakings table?

**Comment by mcharg** [comment]
@cthomasONRR I think that works until we get the ability to display a filtered view of the rulemakings.

**Comment by cthomasONRR** [comment]
@mcharg I linked to Dear Reporter Letters on sections:

- [ ]  2.4.5 (1 letter)
- [ ]  2.5.6 (2 letters)

I'm noticing that when you do the inline search for these docs, they are appearing as both /document/filename.pdf and /reporter-letters/filename.pdf ... I made sure I was selecting the "/reporter-letters/filename.pdf" version, but we might want to get rid of the /document/ version to prevent confusion.

I think we might finally be done with this Handbook? The images I mentioned as missing are present, and I believe we just excluded the image mentioned as "There is an image (Ch 3.1) that will need to be updated to reflect the new website, and navigation instruction will need updating too"

**Comment by mcharg** [comment]
@cthomasONRR The reporter letters look good. I think we're just waiting on the alert card styles.

**Comment by cthomasONRR** [comment]
@mcharg OK moving to Product Backlog

**Comment by mcharg** [comment]
Approved by ODDD.
