### ISSUE TITLE
CONCHO AREA MEETING                                                      (to add to the Event Calendar tab on Allottee Asst. page)

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#1598]
EVENTS

CONCHO AREA MEETING
FEBRUARY 16, 2022
1:00 pm to 2:00 pm CST
Location:  By Telephone

Description:  Meeting will be a Call-in Meeting to hear brief updates from ONRR Outreach Office and representatives from BLM, BTFA, and BIA.  Owners will be able to ask questions regarding Indian Oil & Gas leases, IIM Accounts, and Indian Trust properties issues.  A limited number of lines will be available for callers to join this meeting.  See Other Information below on how to attend this meeting.
 
Who Should Attend:  IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Concho Agency area, in the Southern Plains Region in Oklahoma.

Other Information: To attend the meeting you must contact the ONRR OKC Outreach Office at toll-free (800) 354-7015 to reserve your space and to get the call-in number and passcode for this meeting.  The ONNR OKC Outreach office hours are Monday- Friday from 7:30 am-5:00 pm.

Contact: ONRR OKC Outreach Office
Phone: Toll-free (800) 354-7015
Email: onrroutreachokc@onrr.gov

Montana Virtual Outreach
February 24, 2022 
10:00 am-11:00 am MST 
Location:  Telephone 

Description: Representatives from the Office of Natural Resources Revenue will host a Question and Answer session by phone for Indian Mineral Owners and Trust Property Owners regarding their Indian Oil & Gas leases, IIM Accounts, and Indian Trust Properties. Representatives from the Bureau of Land Management, Bureau of Indian Affairs, and Bureau of Trust Funds Administration are invited to be in attendance to answer questions.
Who Should Attend:  IIM account holders, Indian mineral owners, and Indian trust property owners in the Billings, Lame Deer, Crow, Butte, Helena, Missoula, Harlem, Browning, or Great Falls, Montana areas.  
Other Information: To attend the outreach session, please contact the ONRR Denver Outreach Office at (800) 982-3226, for the call-in number and passcode.  The ONRR Denver Outreach Office hours are Monday-Friday 7:30am-4:00pm. 
Contact:  ONRR Denver Outreach Office, Toll Free (800) 982-9226,  Email: onrroutreachdenver@onrr.gov

**Comment by Toddsand21** [comment]
Please add "VIRTUAL" in the title to read:  "CONCHO AREA VIRTUAL MEETING"

**Comment by cthomasONRR** [comment]
@Toddsand21 

Hello,
These changes are now available for you to view on the dev site: http://2017onrr/events.htm
Please let us know if you would like any modifications, or if you approve for these changes to go live.

Thanks,
Christine

**Comment by Toddsand21** [comment]
1. In 1st sentence after **Description:** delete "issues" after it reads "and Indian trust properties"  End sentence with properties.   2. in **Who Should Attend**: Please add the following after it reads,  "the Concho Agency Area," including Canadian, Kingfisher, Custer, and Blaine counties,

**Comment by cthomasONRR** [comment]
@Toddsand21 
Great, these changes are now on the dev site: http://2017onrr/events.htm
Please review again, and give us your approval to go live.

Thanks,
Christine

**Comment by Toddsand21** [comment]
They look fine and ready to go live. Thanks!

**Comment by cthomasONRR** [comment]
@Toddsand21 
Great! The changes are now live: https://www.onrr.gov/events.htm
Please remember to use Ctrl+F5 to refresh the page.
Thanks, Christine

**Comment by Toddsand21** [comment]
Thank you!

Sandra Todd
Minerals Revenue Specialist
Office of Natural Resources Revenue
Indian Outreach, OKC
(405) 879-6052
(800) 354-7015
________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, February 3, 2022 7:34 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Todd, Sandra L. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] CONCHO AREA MEETING (to add to the Event Calendar tab on Allottee Asst. page) (Issue #1598)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Closed #1598<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1598&data=04%7C01%7Csandra.todd%40onrr.gov%7C31c04053f9c6420566e408d9e719efc5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637794921426666501%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IlDw17iVxGIHN%2BH%2Boj%2BFxv5Zl1H92A5TclIlP0157LU%3D&reserved=0>.

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1598%23event-6002805386&data=04%7C01%7Csandra.todd%40onrr.gov%7C31c04053f9c6420566e408d9e719efc5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637794921426666501%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=s4Syb1AXRhdptKDreQPJDiuCgRdj0XidJ76yjIGuZrc%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASR6F25FMPPUFIGYOHIEJ73UZJ76PANCNFSM5NMWHTIQ&data=04%7C01%7Csandra.todd%40onrr.gov%7C31c04053f9c6420566e408d9e719efc5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637794921426666501%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cATniMuOmVq5J78zBCz0BUoRGqqdk9oXYgf%2BqFziboA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csandra.todd%40onrr.gov%7C31c04053f9c6420566e408d9e719efc5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637794921426666501%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mIAQwvpVn6jo4gzbBIA2nbPe9TlkrFpj%2Ff5FkyyL4Y4%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csandra.todd%40onrr.gov%7C31c04053f9c6420566e408d9e719efc5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637794921426666501%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TnAhIg9xurwyWSjDotPj81O4or9RjuqH3courUyGvwk%3D&reserved=0>.
