### ISSUE TITLE
 Contacts front end cards 

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1599]

**Comment by jlouis-onrr** [comment]
@mcharg, frontend cards are in dev.  I've added the collections to the Getting Started, System Access, Leases & Agreements, and Oil & Gas Production sections.

**Comment by mcharg** [comment]
@jlouis-onrr These all look good. The only thing missing is the operator number when there's a company in the header.  I added #1820 for that, since it's a nice to have.
