### ISSUE TITLE
Make spreadsheet of handbooks for CMS collection

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1601]
Put page number in spreadsheet.

**Comment by Baymatt** [comment]
@Maroyafaied Which spreadsheet is this and where can I find the handbooks?

**Comment by Maroyafaied** [comment]
@Baymatt I'll have to set up a meeting with you to discuss this issue, I set it for next sprint but we can meet next week if you'd like.

**Comment by Baymatt** [comment]
Next week will work for me

**Comment by Maroyafaied** [comment]
@lpgoldstein @Baymatt I created a [folder ](https://teams.microsoft.com/_#/files/General?threadId=19%3A34f9f9ee6b0441dbacab56bfd552f819%40thread.skype&ctx=channel&context=Handbooks&rootfolder=%252Fsites%252FNRRD%252FShared%2520Documents%252FGeneral%252FONRR.gov%252FDesign%252FCollections%252FHandbooks)for the handbooks collection and saved all 5 handbook in there and started an excel sheet with 5 tabs. I'll take both Geothermal handbooks, please put your name next to which handbook you'd like to take in the list below.

- [ ] Revenue Handbook

- [ ] Production Handbook

- [ ] Solid Minerals Handbook

- [ ] Geothermal Class 1 Handbook - Maroya

- [ ] Geothermal Class 2&3 Handbook - Maroya

**Comment by Baymatt** [comment]
I can take the Revenue and Production handbooks.

**Comment by mcharg** [comment]
Do we need to add a column with the 1-1 or whatever displays in the page column in the TOC table?  @kmhtran and I were wondering this when trying out wireframing it.  I think they'll need to know what displays when it's built.

**Comment by mcharg** [comment]
This is what it looks like if we use what's in the spreadsheet in the wireframe. (Disregard the column widths - Kaitlyn will be cleaning those up.)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/263ad261-4285-4eec-bf21-a6f53f85cec6)

I think we're missing the display text shown here.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/5724d193-d7a0-41b4-a69d-4e712b395a8b)

**Comment by Maroyafaied** [comment]
@mcharg Not sure what you mean, do you mean adding the chapter number before the page number?

**Comment by Baymatt** [comment]
As I understood it from yesterday's meeting, we were including actual page numbers because the ones in the table of contents didn't tell us where the page was actually located in the pdf (e.g. Page 1-1 is page 23 in the pdf for the revenue handbook). Do we still need to keep the original page information for display purposes?

@Maroyafaied @mcharg Should I add an additional column with the original page information?

**Comment by mcharg** [comment]
I think we need the original page information for display purposes and the actual page number for linking purposes.

**Comment by mcharg** [comment]
The 1-1 is what displays in the TOC in the pdf rather than the physical page number.
![image](https://user-images.githubusercontent.com/38465926/153429035-e284a93b-1f5a-4024-8b17-8c40270fcb2e.png)

And it displays at the bottom of the page within the pdf, so I think we should have those for display purposes to be consistent.
![image](https://user-images.githubusercontent.com/38465926/153429193-16e1e444-6227-4948-8443-1509f5ef6d10.png)

**Comment by Maroyafaied** [comment]
@mcharg not all the handbook have the same display of page numbers as the revenue one, the geothermal TOC shows just the actual page number. 
![image](https://user-images.githubusercontent.com/40175688/153432335-ea362993-66e4-460a-8d6d-a04cb8e8e7cb.png)

**Comment by Baymatt** [comment]
Found a slight discrepancy in the table of contents of the production handbook. Not sure if its our team that maintains this document but just wanted to bring it up.

<img width="486" alt="Screen Shot 2022-02-13 at 3 52 03 PM" src="https://user-images.githubusercontent.com/43329595/153780980-06e8c115-428a-4d9b-8a97-7eb4219c09d9.png">

**Comment by Maroyafaied** [comment]
@Baymatt @lpgoldstein lets have a column for the actual page numbers and a column for the section that's displayed. We can talk more at the intern meeting.

**Comment by Maroyafaied** [comment]
I found a mistake in the Geothermal class 2&3 handbook , I think these should be 2.5.2 and 2.5.3, I'll let royalty valuation know. 
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/a099f277-6cff-4cf9-be67-fc788fd2b925)

**Comment by lpgoldstein** [comment]
@Baymatt I finished production - do you want me to finish revenue?

**Comment by Baymatt** [comment]
@lpgoldstein If you can that'd be great! I don't think I'll be able to get to it by today or tomorrow.

**Comment by lpgoldstein** [comment]
@Maroyafaied This should read 7-1 in the revenue handbook 
![image](https://user-images.githubusercontent.com/39419003/154298609-e4f8b226-c875-4f9f-a41a-1d7fb3ba7879.png)

**Comment by lpgoldstein** [comment]
And this inconsistent page formatting - should be 9-1 etc
![image](https://user-images.githubusercontent.com/39419003/154299848-1a82c11a-d675-444d-a35d-b16ff0037482.png)

**Comment by Maroyafaied** [comment]
@lpgoldstein please email Shannon Hahn and Aaron Lindquist

**Comment by lpgoldstein** [comment]
Keeping this here so I remember - this is missing from the TOC 
![image](https://user-images.githubusercontent.com/39419003/154309005-85b8ee49-2143-4b3c-9ea7-bcbfc8dcf728.png)

**Comment by lpgoldstein** [comment]
missing from TOC 
![image](https://user-images.githubusercontent.com/39419003/154310917-7e56a5fc-26cc-4ea5-b439-faf0afca136b.png)
