### ISSUE TITLE
ONRR.gov Indian Gas Index Zone Prices - February

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#1602]
The February Indian Gas Index Zone prices are ready to be posted to ONRR.gov.  The prices have been added to the Data for ONRR.gov spreadsheet in the OneDrive.

Thanks,
Cory

@Sudarr

**Comment by cthomasONRR** [comment]
@forgravec 

These changes are now on the dev site: http://2017onrr/valuation/allzones.htm
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by forgravec** [comment]
Prices look good.

Thanks,
Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
***@***.***

________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, February 3, 2022 1:16 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Forgrave, Cory J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] ONRR.gov Indian Gas Index Zone Prices - February (Issue #1602)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@forgravec<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fforgravec&data=04%7C01%7Ccory.forgrave%40onrr.gov%7Cd8788946ae75408a159108d9e752280d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637795162313284748%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TBMGCqO6tzzmpfR2k3o0AQj2Zk1ArjdPupZw58ggD0g%3D&reserved=0>

These changes are now on the dev site: http://2017onrr/valuation/allzones.htm
Please review and give us your approval to go live.

Thanks,
Christine

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1602%23issuecomment-1029363403&data=04%7C01%7Ccory.forgrave%40onrr.gov%7Cd8788946ae75408a159108d9e752280d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637795162313284748%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=o%2BedGwqNPkifN789bipY4DaXwarxWZjEgivSRC6ii8w%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOXGYMG7IEMZAUK7PNU2ZY3UZLPDLANCNFSM5NP5DUWQ&data=04%7C01%7Ccory.forgrave%40onrr.gov%7Cd8788946ae75408a159108d9e752280d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637795162313284748%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lD%2BVBpQpm9pLq5Cp3nT518QejdFZD%2BEaUTbejXxQgi8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ccory.forgrave%40onrr.gov%7Cd8788946ae75408a159108d9e752280d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637795162313284748%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1ZZ%2BWU8D8A3ydL7DThtFd7hBTBluxBQsuPxTsF9OP4w%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ccory.forgrave%40onrr.gov%7Cd8788946ae75408a159108d9e752280d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637795162313284748%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=a%2Bac%2F45rR1%2FZayoDzNqo7fJYg2G50P0f42atgWaNcDI%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@forgravec Great! The changes are now live: https://www.onrr.gov/valuation/allzones.htm
Please remember to use Ctrl+F5 to refresh the page.

Thanks,
Christine
