### ISSUE TITLE
Update Jan 2022 NYMEX

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#1603]
Good afternoon,

Please update the Jan NYMEX on onrr.gov
@sudarr

[NYMEX012022.xlsx](https://github.com/ONRR/onrr.gov-site/files/7998435/NYMEX012022.xlsx)

Thank you!

**Comment by cthomasONRR** [comment]
@boices 
These changes are available to view on the dev site: http://2017onrr/valuation/NYMEX.htm
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@boices 
I got Sean's approval via Teams Chat. 
These updates are now live: https://www.onrr.gov/valuation/NYMEX.htm
