### ISSUE TITLE
Onshore Production Contact List

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1604]
Please update the Onshore Production Contact list at the following webpage with the attached contact list - https://www.onrr.gov/about/contact.hts
[Onshore Production Reporting Contacts.pdf](https://github.com/ONRR/onrr.gov-site/files/7998802/Onshore.Production.Reporting.Contacts.pdf)

**Comment by cthomasONRR** [comment]
@bowlenj These changes are on the dev site: http://2017onrr/about/contact.htm
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by bowlenj** [comment]
It looks great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Friday, February 4, 2022 6:43 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Onshore Production Contact List (Issue #1604)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Ce2de02af79614f11c7bf08d9e7e460eb%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637795790337549420%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EKN6GxySBWzfAZ97w4DceBqQYtoepFwa%2FOmhtLzXxRM%3D&reserved=0> These changes are on the dev site: http://2017onrr/about/contact.htm
Please review and give us your approval to go live.

Thanks,
Christine

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1604%23issuecomment-1029997188&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Ce2de02af79614f11c7bf08d9e7e460eb%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637795790337549420%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CYDYOGSufCtf0BMp8X6Mu5%2FB7w3HSSGgtPiYrdoe1pA%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH7SE2L326QP2K3UHCLUZPJYTANCNFSM5NQHNIVQ&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Ce2de02af79614f11c7bf08d9e7e460eb%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637795790337549420%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WQC4FwWToEOH12k3Lr7IF1tXUYwApRTL8W8CuTN4zVs%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Ce2de02af79614f11c7bf08d9e7e460eb%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637795790337549420%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LKhp11K%2FCFx%2F4yCNj5YyRhpmmR4%2Bznz%2BdFbcwTSAZeg%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Ce2de02af79614f11c7bf08d9e7e460eb%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637795790337549420%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xxn5vj7Ymp9ui55RrisN2Elq8PHZdy4CY%2BhYuqvszg8%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@bowlenj Great! It's not live: https://www.onrr.gov/about/contact.htm
Please remember to use Ctrl+F5 to refresh the page.

Thanks,
Christine
