### ISSUE TITLE
Webpage Update - New Lease Agreement XREF file for onrr.gov

### ISSUE THREAD

**Issue by HammenONRR** [ONRR/onrr.gov-site#1605]
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm called “Cross-Reference Lease to Agreement Number” with the file entitled “February 2022 Lease Agreement XREF.txt”.  It was queried from the system on 2/04/2022.
[February 2022 Lease Agreement XREF.txt](https://github.com/ONRR/onrr.gov-site/files/8004103/February.2022.Lease.Agreement.XREF.txt)

**Comment by HammenONRR** [comment]
Hello Christine,

They are suppose to be reviewing this today. I will send a reminder.

Thanks!

Jeremy Hammen
Program Analyst
Data Optimization, Retrieval, and Coordination (DORC)
Information and & Data Management (IDM)
Office of Natural Resources Revenue (ONRR)
515-351-0254
***@***.******@***.***>

Warning: This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law. If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited. If you have received this communication in error, please notify the sender immediately by return e-mail.


From: Christine Thomas ***@***.***>
Sent: Monday, February 7, 2022 9:50 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Hammen, Jeremy J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Webpage Update - New Lease Agreement XREF file for onrr.gov (Issue #1605)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@HammenONRR<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHammenONRR&data=04%7C01%7Cjeremy.hammen%40onrr.gov%7C5c639c365177473456d208d9ea5a09ef%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637798495482624319%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zBoi%2BkG%2FoyozT3c6uQTbT1b2ZiSa2ZUWgUcLsiPbWNg%3D&reserved=0>
Good morning, is someone available to review the dev site: http://2017onrr/reportpay/CrossRef.htm
Thanks,
Christine

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1605%23issuecomment-1031686148&data=04%7C01%7Cjeremy.hammen%40onrr.gov%7C5c639c365177473456d208d9ea5a09ef%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637798495482624319%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mXrt1hmibdcy1iLBh4smFR41DH%2F%2Bsj6kxmRSHb04RDQ%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXSPNZIV66JM3HMTLRZQRMTUZ7Z35ANCNFSM5NSBYRTA&data=04%7C01%7Cjeremy.hammen%40onrr.gov%7C5c639c365177473456d208d9ea5a09ef%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637798495482624319%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9zza%2Fs3USb%2FpSJZCPCAu%2FE5qHnr7puct4hhPEBXG%2FIM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjeremy.hammen%40onrr.gov%7C5c639c365177473456d208d9ea5a09ef%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637798495482624319%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5wYrwQgpq45azcOPQshrppP0M93gv45UeCzB%2F43g14g%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjeremy.hammen%40onrr.gov%7C5c639c365177473456d208d9ea5a09ef%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637798495482624319%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YnVhQgWgEf5lQzNyxZLhgmnv%2F1bXz1M1WrxozxddkPc%3D&reserved=0>.

**Comment by HammenONRR** [comment]
Hello, Happy to report the file looks correct and feel free to move the file to live site. Thank you for your patience!

**Comment by cthomasONRR** [comment]
@HammenONRR 
Fantastic! These changes are now live: https://www.onrr.gov/ReportPay/CrossRef.htm
Please remember to use 'Ctrl+F5' to refresh the page.
Thanks,
Christine

**Comment by mcharg** [comment]
Documents updated in CMS.
