### ISSUE TITLE
Update onshore production reporting contacts in the spreadsheet

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1606]
They changed the whole format of the list.
https://www.onrr.gov/reportpay/PDFDocs/OnshoreProductionContacts.pdf

**Comment by cthomasONRR** [comment]
Updating in the following Contacts Files [Spreadsheet ](https://teams.microsoft.com/l/file/EE2FC3B4-4196-4DCE-9286-84AAF6E25E00?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FDesign%2FContacts%2FContactsFiles.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

**Comment by cthomasONRR** [comment]
@mcharg This is complete. Do you want to review?

**Comment by mcharg** [comment]
@cthomasONRR Looks good.
