### ISSUE TITLE
Remove Herb Black's info from Geothermal Handbook webpage

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1607]
Herb retired. I will remove his contact information here: https://www.onrr.gov/reportpay/Handbooks/index.htm

**Comment by cthomasONRR** [comment]
@mcharg Want to review before I go live?
http://2017onrr/reportpay/Handbooks/index.htm

**Comment by mcharg** [comment]
@cthomasONRR Looks good!
