### ISSUE TITLE
Update to Onshore Production Contact List

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1609]
We found a few errors in the Onshore Production Contact list.  Can you please replace the contact list located at the following link with the attached list - https://www.onrr.gov/reportpay/PDFDocs/OnshoreProductionContacts.pdf
[Onshore Production Assignments revised 022203.pdf](https://github.com/ONRR/onrr.gov-site/files/8027488/Onshore.Production.Assignments.revised.022203.pdf)

**Comment by cthomasONRR** [comment]
@bowlenj 
Sure thing- here it is in dev: http://2017onrr/about/contact.htm
Please review and let me know if you approve to go live.

Could you point out what changed? We have a contacts spreadsheet we're keeping updated for the new onrr.gov site, and I want to make sure I capture the changes there too. Thanks!

**Comment by bowlenj** [comment]
This looks great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Tuesday, February 8, 2022 2:15 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update to Onshore Production Contact List (Issue #1609)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cb0f0936f81b743ca42f108d9eb482a69%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637799517447219915%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=j%2F8xrWIeq5vninmNpTIPW1y0SVME4VwhNw6NAH7em%2B0%3D&reserved=0>
Sure thing- here it is in dev: http://2017onrr/about/contact.htm
Please review and let me know if you approve to go live.

Could you point out what changed? We have a contacts spreadsheet we're keeping updated for the new onrr.gov site, and I want to make sure I capture the changes there too. Thanks!

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1609%23issuecomment-1033068609&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cb0f0936f81b743ca42f108d9eb482a69%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637799517447376144%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mXzna%2FtZbKZkNKlYDi3ZL%2BqZFqBJCNFdOs25G0siTVo%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH53RHLSRG7VRDRISP3U2GBWJANCNFSM5N3TWMAQ&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cb0f0936f81b743ca42f108d9eb482a69%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637799517447376144%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=halDEabe1eLEcUH83Ydyqp%2F%2F%2FLr2GexseHg%2FrbVZZqc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cb0f0936f81b743ca42f108d9eb482a69%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637799517447376144%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BCElZNi%2FtRtNiYSoufX9HGrJI8RLvVUrxXpW%2BoCpkfo%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cb0f0936f81b743ca42f108d9eb482a69%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637799517447376144%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KUHHRmX8mVhTUj71B1PGC8i%2Fw%2FPjwtz56Andjqi6r2I%3D&reserved=0>.
