### ISSUE TITLE
January 2022 IBMP

### ISSUE THREAD

**Issue by damionschulte** [ONRR/onrr.gov-site#1610]
All, I have updated the Data for ONRR sheet on the one drive with the January 2022 IBMP Prices.  Can you please publish them to the website?  Thanks

@sudarr

**Comment by Maroyafaied** [comment]
@damionschulte Please review http://2017onrr/valuation/IndianOilIBMP.htm

**Comment by damionschulte** [comment]
These look amazing.  Thank you.

From: Maroyafaied ***@***.***>
Sent: Tuesday, February 8, 2022 3:14 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] January 2022 IBMP (Issue #1610)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@damionschulte<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdamionschulte&data=04%7C01%7Cdamion.schulte%40onrr.gov%7Cd8bc3418a19f49b29b3a08d9eb50566d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637799552994193590%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AShDwwUSihl2pj2ZiyGUEGGf9OqNbb0vXqJV3VpRJ84%3D&reserved=0> Please review http://2017onrr/valuation/IndianOilIBMP.htm

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1610%23issuecomment-1033116145&data=04%7C01%7Cdamion.schulte%40onrr.gov%7Cd8bc3418a19f49b29b3a08d9eb50566d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637799552994193590%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aArjG17fp5gji4St6yfWRHtF7zuR3W4DJWNcC%2Bzpnvw%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAO4AEPPPUQSIFALUS5ANGUTU2GISTANCNFSM5N3XBVYQ&data=04%7C01%7Cdamion.schulte%40onrr.gov%7Cd8bc3418a19f49b29b3a08d9eb50566d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637799552994193590%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9IPg%2F7fjTmzSC4NhwA6xHxJry6lA3QuvTSphZvh0xv4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdamion.schulte%40onrr.gov%7Cd8bc3418a19f49b29b3a08d9eb50566d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637799552994193590%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=w4IkisuOl%2BsxgENS%2FlYsIfsPKc69C%2B%2F%2FyNEw3wZxsPs%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdamion.schulte%40onrr.gov%7Cd8bc3418a19f49b29b3a08d9eb50566d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637799552994193590%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YttXUwH1fejTuvYs41h5Jn044XFa7LfceMypaJkowjM%3D&reserved=0>.

**Comment by Maroyafaied** [comment]
@damionschulte Thanks, this is live.
