### ISSUE TITLE
Add Outreach Videos to ONRR.gov

### ISSUE THREAD

**Issue by Rebekah474** [ONRR/onrr.gov-site#1611]
We have 2 videos to add to the allottee assistance page of ONRR.gov. The first video (#1) Where do I go for royalty help? and the most recent video (#4) Why are there negative amounts on my statement? There are already 2 videos on the page, please keep all 4, I know the page will be crowded, maybe 2 videos on the left panel and 2 on the right.

Video 1  - Where do I go for royalty help? - YouTube https://www.youtube.com/watch?v=kyOZwxd9CSQ&list=PLHqjbxv3m6RyeSJz42qgr2bo0Mw9eTYWP
 
Video 4  - Why are there negative amounts on my statement? - YouTube https://www.youtube.com/watch?v=EyOOx6fA9t4

thank you
Rebekah Ingraham

**Comment by mcharg** [comment]
I'm taking this one, since I talked with Rebekah about adding a tab for the videos.

**Comment by mcharg** [comment]
@rebekah474 I have this updated in the dev site.  Please review and let me know if it looks good to push live.
http://2017onrr/IndianServices/index.htm

**Comment by Rebekah474** [comment]
Yes it can go live, it looks great, thank you

**Comment by Rebekah474** [comment]
Yes it can go live. I also added a comment on GitHub with the approval to go live.
Thank you

Rebekah Ingraham
Mineral Revenue Specialist
ONRR SIO
Oklahoma City
405-879-6037
800-354-7015
6:30-3:00 CT M-F
We all have different gifts, so we all have different ways of saying to the world who we are. - Fred Rogers
For Allottee Assistance go to:
https://www.onrr.gov/IndianServices/index.htm
To see ONRR's training videos, go to:
http://onrr.gov/ReportPay/training/default.htm<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fonrr.gov%2FReportPay%2Ftraining%2Fdefault.htm&data=04%7C01%7CRebekah.Ingraham%40onrr.gov%7Ca29245c053404365512b08d8c2539fbc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637473011765313008%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E142FCBxPg5gABpSs1evwGMqNwb74eYi%2FydxnFHgZkE%3D&reserved=0>
https://www.youtube.com/user/ONRRChannel<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fuser%2FONRRChannel&data=04%7C01%7CRebekah.Ingraham%40onrr.gov%7Ca29245c053404365512b08d8c2539fbc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637473011765322970%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Tn5sNbkUPpw1HNAEfqFHNm%2BCELA47cvwFxcq%2BJYIWns%3D&reserved=0>



From: mcharg ***@***.***>
Sent: Wednesday, February 9, 2022 12:30 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Ingraham, Rebekah J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Add Outreach Videos to ONRR.gov (Issue #1611)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Rebekah474<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRebekah474&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7Cfa0f95acd2cf49d2c1de08d9ebfa4afc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637800282498361990%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=d2Lw8qmsZkwGDtC4cDihZrlfIUbnUOcYA0%2BPUa6TXx4%3D&reserved=0> I have this updated in the dev site. Please review and let me know if it looks good to push live.
http://2017onrr/IndianServices/index.htm

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1611%23issuecomment-1034068931&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7Cfa0f95acd2cf49d2c1de08d9ebfa4afc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637800282498361990%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3%2FzYmW9FOLe9vMmLx1abl%2FuESEgK3euSIVuTo5JLUvs%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATGBZG3H2TISEVDINAVXNG3U2KXD7ANCNFSM5N6CXHTQ&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7Cfa0f95acd2cf49d2c1de08d9ebfa4afc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637800282498361990%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FXY90VuPJGKJT%2Frevn1wmfbatUCt8OmjGLoktymL0N0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7Cfa0f95acd2cf49d2c1de08d9ebfa4afc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637800282498361990%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YvTZUcQXAClQ1ja6IDtHAWFqikQxpRnLiFB6hHthbIM%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7Cfa0f95acd2cf49d2c1de08d9ebfa4afc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637800282498361990%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=V6eDudjTJbRqbXnGF9ZM%2FNZcODpwXmem1JLihEIF3j8%3D&reserved=0>.

**Comment by mcharg** [comment]
@rebekah474 I pushed it live.  The change should be visible within an hour.  I'll check to make sure the change is live before closing this issue.

**Comment by Rebekah474** [comment]
Thank you

Rebekah Ingraham
Mineral Revenue Specialist
ONRR SIO
Oklahoma City
405-879-6037
800-354-7015
6:30-3:00 CT M-F
We all have different gifts, so we all have different ways of saying to the world who we are. - Fred Rogers
For Allottee Assistance go to:
https://www.onrr.gov/IndianServices/index.htm
To see ONRR's training videos, go to:
http://onrr.gov/ReportPay/training/default.htm<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fonrr.gov%2FReportPay%2Ftraining%2Fdefault.htm&data=04%7C01%7CRebekah.Ingraham%40onrr.gov%7Ca29245c053404365512b08d8c2539fbc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637473011765313008%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E142FCBxPg5gABpSs1evwGMqNwb74eYi%2FydxnFHgZkE%3D&reserved=0>
https://www.youtube.com/user/ONRRChannel<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fuser%2FONRRChannel&data=04%7C01%7CRebekah.Ingraham%40onrr.gov%7Ca29245c053404365512b08d8c2539fbc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637473011765322970%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Tn5sNbkUPpw1HNAEfqFHNm%2BCELA47cvwFxcq%2BJYIWns%3D&reserved=0>



From: mcharg ***@***.***>
Sent: Wednesday, February 9, 2022 1:07 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Ingraham, Rebekah J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Add Outreach Videos to ONRR.gov (Issue #1611)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Rebekah474<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRebekah474&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7C46e77390b5bf4391bda608d9ebffd011%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637800306204404222%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WY4Jl2K2ka8Ohh8jeC9EpwecJur%2BtooMbsRfMTsCR1E%3D&reserved=0> I pushed it live. The change should be visible within an hour. I'll check to make sure the change is live before closing this issue.

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1611%23issuecomment-1034098910&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7C46e77390b5bf4391bda608d9ebffd011%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637800306204404222%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dplR84h2ILvTcGXIFFka%2F%2F%2BjMlFh3HO4APsVlWb0Gus%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATGBZG2XOJ5XXZTXDHPAOITU2K3MBANCNFSM5N6CXHTQ&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7C46e77390b5bf4391bda608d9ebffd011%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637800306204404222%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=v%2FhygjyQtMUKczBRAOzIHb9peM78970pT7Y%2FQTOP2WA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7C46e77390b5bf4391bda608d9ebffd011%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637800306204404222%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lhOMbTUlVJak1w4d4%2BNl7Z%2FzEnh7eXp1YVWUgG2ITmw%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7C46e77390b5bf4391bda608d9ebffd011%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637800306204404222%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FUxpFiEbntgEbkEjO%2By%2BPkWil4adFBn58p9vfLelDbU%3D&reserved=0>.

**Comment by mcharg** [comment]
This is live.

**Comment by Rebekah474** [comment]
Thank you, it looks great!

Rebekah Ingraham
Mineral Revenue Specialist
ONRR SIO
Oklahoma City
405-879-6037
800-354-7015
6:30-3:00 CT M-F
We all have different gifts, so we all have different ways of saying to the world who we are. - Fred Rogers
For Allottee Assistance go to:
https://www.onrr.gov/IndianServices/index.htm
To see ONRR's training videos, go to:
http://onrr.gov/ReportPay/training/default.htm<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fonrr.gov%2FReportPay%2Ftraining%2Fdefault.htm&data=04%7C01%7CRebekah.Ingraham%40onrr.gov%7Ca29245c053404365512b08d8c2539fbc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637473011765313008%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E142FCBxPg5gABpSs1evwGMqNwb74eYi%2FydxnFHgZkE%3D&reserved=0>
https://www.youtube.com/user/ONRRChannel<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fuser%2FONRRChannel&data=04%7C01%7CRebekah.Ingraham%40onrr.gov%7Ca29245c053404365512b08d8c2539fbc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637473011765322970%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Tn5sNbkUPpw1HNAEfqFHNm%2BCELA47cvwFxcq%2BJYIWns%3D&reserved=0>



From: mcharg ***@***.***>
Sent: Wednesday, February 9, 2022 3:09 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Ingraham, Rebekah J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Add Outreach Videos to ONRR.gov (Issue #1611)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



This is live.

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1611%23issuecomment-1034193964&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7C43ec61e6d61c46fc753d08d9ec106db7%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637800377573932582%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6mIilp%2FYzUaOb2ZUFN4DDZGcXu8%2FX7SG4DVzaSO%2BT4M%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATGBZG3JLTPPLVZFNHN6OLTU2LJWRANCNFSM5N6CXHTQ&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7C43ec61e6d61c46fc753d08d9ec106db7%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637800377573932582%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rmTX0HUBmRhGD%2BFCi6atN%2BVhVVZcQ5w9ucpGW%2BGsZGI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7C43ec61e6d61c46fc753d08d9ec106db7%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637800377573932582%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8bvajVc%2BtHP891PrS5U6oNtr1u9XQA%2BgeOxb4diF2sM%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7C43ec61e6d61c46fc753d08d9ec106db7%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637800377573932582%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0GMC0FkNp1F4fY7XO4IutWWlscCTryIZTROnTLjTjwY%3D&reserved=0>.
