### ISSUE TITLE
Recruit participants for contacts study

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1618]

**Comment by daniel-coleman-1** [comment]
@lpgoldstein  how's this for an invite email:

Hi [Name],

I hope you are all doing well! The Data Display team is working on a new version of onrr.gov and we would love your feedback.

We are planning a study to understand how users approach the contacts section, and how it could be improved. As part of this effort, we’re conducting short interviews with people who use the contacts section of onrr.gov.

Would you be interested in participating in a 30 minute online interview between the dates of X and Y?  If so, let me know a few good times in those weeks.

Thank you,

ODDD Team

**Comment by mcharg** [comment]
@daniel-coleman-1 You call us both Data Display and ODDD.  For internal folks, I think you need to spell out what ODDD is.  For external folks, it would be better to refer to us as ONRR.

**Comment by mcharg** [comment]
Also, we have templates we've used before. https://teams.microsoft.com/l/file/BE542636-D0E1-40CE-9EF4-7CFA4326CBAD?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FUser%20Research%2FTemplates%2FRecruiting%20Email%20Templates.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by mcharg** [comment]
And the language from Cat's husband. https://github.com/ONRR/onrr.gov-site/issues/929#issuecomment-919321694

**Comment by lpgoldstein** [comment]
@daniel-coleman-1 I changed just a few things but this looks fine. It doesn't seem to matter what you write if you are contacting people that want to help. Cat's husband's email was helpful and provided more of a call to action than our standard template. 

 Hi [Name],

I hope you are all doing well! We are working on a new version of onrr.gov and we would love your feedback.

We are planning a study to understand how users approach the contacts section, and how it could be improved. As part of this effort, we’re conducting short interviews with people who use the contacts section of onrr.gov.

Would you be interested in participating in a 30 minute online interview between the dates of X and Y? If so, let me know a few good times in those weeks.

Thank you,

Name of person sending email

**Comment by daniel-coleman-1** [comment]
participant list document:
https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/User%20Research/Studies/11_Troubleshooting_study/participant%20list.xlsx?d=wd67cfd8732194a51bbb832dc43e4c7ef&csf=1&web=1&e=vYzrGh

**Comment by mcharg** [comment]
@daniel-coleman-1 Can you please edit the invites you sent to include information about what the participant should expect and a number to call if they have issues getting into Teams.  Here's language we've used before.

Thank you so much for taking the time to talk with with us. My colleague, Shannon McHarg, will be conducting the interview along with one or two of my colleagues joining to take notes.  If this time doesn't work for you, feel free to propose a different time. 

We will be using Teams for this meeting. 

If you have trouble getting in, feel free to call me at [Phone Number] , and  I can walk you through it.

It would be great if you could be at a computer and able to share your screen with us.

We look forward to talking with you!
