### ISSUE TITLE
Upload NYMEX April prices

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#162]
We have the monthly NYMEX prices and spreadsheet ready to be uploaded to the ONRR.gov website. The spreadsheet is attached. Please reference the shared document "Data for ONRR.gov" on OneDrive.

@sudarr

[NYMEX0420.xlsx](https://github.com/ONRR/onrr.gov-site/files/4589387/NYMEX0420.xlsx)

**Comment by jennmalcolm** [comment]
ready for review @boices and @sudarr

http://2017onrr/Valuation/NYMEX.htm

**Comment by boices** [comment]
That looks perfect--thanks!

**Comment by jennmalcolm** [comment]
The prices are live now.

**Comment by boices** [comment]
Thanks!

Sean Boice
Economist
Office of Natural Resources Revenue
