### ISSUE TITLE
Request Updates to ONRR's Information Collection Page

### ISSUE THREAD

**Issue by ginger-johnson** [ONRR/onrr.gov-site#1622]
Good morning, 

I am requesting updates to this page https://www.onrr.gov/Laws_R_D/FRNotices/ICR0139.htm

Under the Federal Register Publications heading, please add a bullet to the top of the list. The bullet should read as follows: “30-Day Agency Information Collection - (87 FR 3330--January 21, 2022)"

Please add this hyperlink to the language in the parenthesis: https://www.federalregister.gov/documents/2022/01/21/2022-01158/agency-information-collection-activities-royalty-and-production-reporting 

Please let me know if you have any questions. 

Ginger Johnson

**Comment by cthomasONRR** [comment]
@ginger-johnson 
Good morning, these changes are on the dev site: http://2017onrr/Laws_R_D/FRNotices/ICR0139.htm
Please review and give me your approval to go live.

Thanks,
Christine

**Comment by ginger-johnson** [comment]
Christine, 

The update looks great.

We are ready for it to go live. 

Thank you!

**Comment by cthomasONRR** [comment]
@ginger-johnson The changes are now live: https://www.onrr.gov/Laws_R_D/FRNotices/ICR0139.htm

Closing this issue.

**Comment by mcharg** [comment]
No doc updates needed in CMS.
