### ISSUE TITLE
Review pricing tables with MSA

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1623]

**Comment by Maroyafaied** [comment]
We met with MSA on 2/15 and reviewed all the pricing tables wireframes.
- They would like prices to display 2 decimal places
-  They don't want the major portions maps displayed on the page and to keep them as pdfs. 
- They like the multi select filter option and would like to implement that feature to NYMEX as well
- They asked we only keep the sort arrows for zones/areas & years and remove from the rest of the tables
- Damion will provide test files for Indian oil & gas major portion and Indian gas index zones.

@mcharg did I miss anything? Is this good to close?

**Comment by mcharg** [comment]
Looks good.
