### ISSUE TITLE
Request to update ONRR's Federal Register Notices Page

### ISSUE THREAD

**Issue by ginger-johnson** [ONRR/onrr.gov-site#1624]
Good morning, 

I am requesting updates to this page https://www.onrr.gov/Laws_R_D/FRNotices/index.htm

For the entry, please create it with January 21, 2022.
It should read as follows:
"87 FR 3330
Friday, January 21, 2022
**Denver, CO** In accordance with the Paperwork Reduction Act of 1995, ONRR is proposing to renew an information collection request. OMB Control Number 1012-0004."

At the bottom of the entry, please add a hyperlink labeled as "View 87 FR 3330 document" with the link below
https://www.federalregister.gov/documents/2022/01/21/2022-01158/agency-information-collection-activities-royalty-and-production-reporting

Please let me know if you have any questions.

Ginger Johnson

**Comment by cthomasONRR** [comment]
@ginger-johnson 
Good morning,
The updates are on the dev site: http://2017onrr/Laws_R_D/FRNotices/index.htm. (Remember to navigate to 2022 on the right-hand side.)
Please review and give me your permission to go live.
Thanks,
Christine

**Comment by lpgoldstein** [comment]
@ginger-johnson Please see the live site with your updates https://www.onrr.gov/Laws_R_D/FRNotices/index.htm
