### ISSUE TITLE
Review capitalization on pages in CMS

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1625]
To ensure it matches the style guide.

**Comment by daniel-coleman-1** [comment]
I think in the Troubleshooting tab we should grant an exception to the "All card headers are capitalized" rule, since these headers are being used as an ordered list.  Current presentation:
![Screenshot 2022-02-22 160728](https://user-images.githubusercontent.com/83892362/155234891-ad3f3ddc-622d-47ad-bdde-424e0e2ff26d.png)

Title case (what I think we shouldn't do):
![Screenshot 2022-02-22 160249](https://user-images.githubusercontent.com/83892362/155234949-8a0f639b-d5d3-4c73-b2ae-6d90a4435256.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 Makes sense to me.  Do they need periods, since they're complete sentences?

**Comment by daniel-coleman-1** [comment]
@mcharg I am thinking we go with no punctuation, and we also remove punctuation from the text in the accordions - except in the instances where there is a question mark.  I think because this is an ordered list in cards where the text is acting as a title, we don't need to punctuate the ends of the sentences.  What do you think about that?

**Comment by daniel-coleman-1** [comment]
@mcharg for the accordions, I think we treat them more like newspaper headlines, which act like titles and are often unpunctuated.   For the card case, I did both and I'm thinking it makes more sense with a period.  What do you think?
No period:
![Screenshot 2022-02-23 082523](https://user-images.githubusercontent.com/83892362/155350746-5179aacb-6e1b-4b4c-8837-b56aa55766db.png)

with a period:
![Screenshot 2022-02-23 082547](https://user-images.githubusercontent.com/83892362/155350875-7b4343e0-c407-46dc-a46d-db9aa2539676.png)


accordions with:
![Screenshot 2022-02-23 082053](https://user-images.githubusercontent.com/83892362/155350893-7e26cb65-95a9-4f15-83e2-5b4d692ea9e4.png)

accordions without:
![Screenshot 2022-02-23 081945](https://user-images.githubusercontent.com/83892362/155350909-69650c26-0b65-4f94-8c00-e3c6b34a7969.png)

**Comment by daniel-coleman-1** [comment]
@mcharg I could go either way on the cards, if you feel strongly that there should be a period I'll agree with you.  For the accordions, I think they are better off without the punctuation.

**Comment by mcharg** [comment]
I think without periods they both look like we forgot to put them on.

**Comment by daniel-coleman-1** [comment]
@mcharg what about here, should we add periods for consistency?  These are imperative case with an implied you subject:
![Screenshot 2022-02-23 081945](https://user-images.githubusercontent.com/83892362/155354596-082d1ee4-b4fe-40bf-9e50-55556900763e.png)

**Comment by mcharg** [comment]
I think so.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I don't have access to the link above, please put it our shared drive. Also, give a status update for this issue since it's been open for a while. I'd like to know if all pages have been reviewed and if there's any pages that need to be corrected for capitalization. Thanks

**Comment by daniel-coleman-1** [comment]
@Maroyafaied that link should be accessible now, at 205/299.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 Does the edited column mean that there's issues in capitalization? Does the "yes" in that column mean that there's issues? 
![image](https://user-images.githubusercontent.com/40175688/157490992-145003ba-9a64-45c4-8472-c01fce3d0dff.png)

**Comment by daniel-coleman-1** [comment]
@Maroyafaied "Reviewed" means I've looked at the page, "Edited" means I made edits.  So if Reviewed is yes and Edited is no, it has been reviewed but no edits were necessary.  If Reviewed is yes and Edited is yes, edits were made in the CMS.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 Ok, thanks for explaining. Just taking a quick glimpse at the dev site and the Geothermal file reports tab says reviewed and no edits but I see a heading that needs to be fixed to be title case but that was not noted or edited? 
![image](https://user-images.githubusercontent.com/40175688/157496802-dd09662a-bf58-41aa-a3dd-5d05157d41a8.png)
![image](https://user-images.githubusercontent.com/40175688/157496899-23203328-92a0-4ebd-adb2-51647c786a29.png)

**Comment by daniel-coleman-1** [comment]
@Maroyafaied it looks like I missed that one, thanks for catching

**Comment by Maroyafaied** [comment]
These accordions need to be sentence case 
![image](https://user-images.githubusercontent.com/40175688/157792039-e9ef5e30-41be-4f21-a9c8-f066ba82988e.png)
![image](https://user-images.githubusercontent.com/40175688/157792092-c06c1883-9379-440e-9d47-b173ed1b771a.png)
![image](https://user-images.githubusercontent.com/40175688/157792742-20f86651-6f74-4f7b-8133-d3bdef220b50.png)


There's a few instances where "Sample Layout" is written as bold sentence but I believe it should be written as a heading 
![image](https://user-images.githubusercontent.com/40175688/157792236-071dac7f-61e5-41ad-9e4d-387f26fbea5d.png)

In some cases payor number is capitalized and some not, we also need to look if the following is proper nouns and should be capitalized or not (Operator number, payor number, payor code)
![image](https://user-images.githubusercontent.com/40175688/157792575-66d7482c-0d50-4365-8173-005a40ec6a7c.png)
![image](https://user-images.githubusercontent.com/40175688/157792841-480f3eb1-aef6-4fcf-9ad0-d5a163202985.png)
![image](https://user-images.githubusercontent.com/40175688/157793924-bd5b698d-ced7-496d-95d9-1697eddc1d38.png)

Need to be capital 
![image](https://user-images.githubusercontent.com/40175688/157793052-6f0be883-4ea0-40d7-a56c-519afa98ac31.png)

**Comment by daniel-coleman-1** [comment]
@Maroyafaied edits have been input to the CMS, thanks.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 seems like the the layout and order of the Denver office location changed when you updated it, can you please change it back to the original order.  Also, here's another title that needs to be fixed.  I confirmed with @mcharg that all the "sample layout" should be a heading so please fix those as well. Thanks

![image](https://user-images.githubusercontent.com/40175688/158175422-165b18fc-6e76-41ea-8fd3-a34998090a7d.png)
![image](https://user-images.githubusercontent.com/40175688/158175760-ff52ca1a-91b6-4530-814d-9ada3cc57420.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 Yes, we should use headings whenever possible to improve readability for screen readers.

**Comment by daniel-coleman-1** [comment]
@Maroyafaied input edits into CMS: Sureties on appeals page, Sample Layout and office location order.

Should be good to close.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I'm not seeing the changes in the dev site for the office location and sample layout. I only see the changes on the card in the sureties tab. 
![image](https://user-images.githubusercontent.com/40175688/158267252-c3a85451-467a-4d36-a801-41b59cdca811.png)
![image](https://user-images.githubusercontent.com/40175688/158267320-c7188b48-f731-44bd-9139-59c75fdf07c8.png)

**Comment by daniel-coleman-1** [comment]
@Maroyafaied I hit the check mark for the above levels, but not the base level. Should be good now.

**Comment by daniel-coleman-1** [comment]
@Maroyafaied is this what you're looking for for office locations?
![Screenshot 2022-03-14 161126](https://user-images.githubusercontent.com/83892362/158269597-5e2757df-91c4-463d-966e-1c4393b5b047.png)

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 No the check payments came first before Other U.S Mail like the wireframe and this pic. 
![image](https://user-images.githubusercontent.com/40175688/158269822-baa24c49-f282-483f-a05d-938ba3e473a4.png)

**Comment by daniel-coleman-1** [comment]
@Maroyafaied ok we're up:
![Screenshot 2022-03-14 161525](https://user-images.githubusercontent.com/83892362/158270002-a5841a6f-919f-495a-9c69-12d2540b9a97.png)
