### ISSUE TITLE
Webpage Update- Indian Fund Code

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#1627]
Hello,

Please update the following webpage http://onrr.gov/reportPay/payments.htm with the attached file's:

Indian Leases cross-walked to Distributee Codes-

Downloadable Excel Version Indian Leases cross-walked to Distributee Codes.
Also change update to read 02/14/2022.

Thank you!

[FCIL.xlsx](https://github.com/ONRR/onrr.gov-site/files/8062886/FCIL.xlsx)

**Comment by lpgoldstein** [comment]
@merrellc This is ready for your review: http://2017onrr/reportpay/payments.htm

**Comment by merrellc** [comment]
Reviewed. Thank you!


Kind Regards,
​Candace Merrell
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________
From: lpgoldstein ***@***.***>
Sent: Monday, February 14, 2022 3:47 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Webpage Update- Indian Fund Code (Issue #1627)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@merrellc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmerrellc&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C99db023c8522458e997708d9f00bffc0%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637804756609899573%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=y%2BUQRZhre9h8rXiUYADRGD%2BUFmKeGdkg2Es34mFl%2Bj8%3D&reserved=0> This is ready for your review: http://2017onrr/reportpay/payments.htm

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1627%23issuecomment-1039649497&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C99db023c8522458e997708d9f00bffc0%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637804756609899573%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lXAhmE7U5HBa3e5kEq1a6o2fNrHnmKIxKV8BB%2F8d2Jw%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOXFVHEWLRHCUSR2CQBDM23U3GA73ANCNFSM5OMFIQRQ&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C99db023c8522458e997708d9f00bffc0%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637804756609899573%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AHTmbBQBeViTN0fQtSoY55MlzEclS3ZyDOnAlIPogxU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C99db023c8522458e997708d9f00bffc0%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637804756609899573%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jZ26mtwgcPDIMfp%2FGtF70GQOpTDi7dDRYxUaYoy4Rts%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C99db023c8522458e997708d9f00bffc0%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637804756609899573%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7qOvx0evnYfhqnB1tswOt%2FGyQTswxfbSi1LWFzMQP7U%3D&reserved=0>.

**Comment by lpgoldstein** [comment]
@merrellc It's live!
