### ISSUE TITLE
Add new FRN to dev site

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1631]
Add FRN from #1624 to new site.

**Comment by cthomasONRR** [comment]
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/88
https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0004

The new FR doc is added. @mcharg do you want to review?

**Comment by mcharg** [comment]
@cthomasONRR Looks good.

**Comment by mcharg** [comment]
Documents updated in CMS.
