### ISSUE TITLE
Narrative update on onrr.gov-site Late Payment & Underpayment Interest Tables

### ISSUE THREAD

**Issue by badeh** [ONRR/onrr.gov-site#164]
Good Morning,
Please replace current narrative with below:

The Federal Oil and Gas Royalty Simplification and Fairness Act of 1996 (RSFA), required ONRR to pay interest on Federal oil and gas royalty overpayments. On December 4, 2015, the Fixing America’s Surface Transportation (FAST) Act was signed by the President. The FAST Act contained a provision that removed ONRR’s authority to pay interest on Federal oil and gas overpayments. It has been interpreted that ONRR retained authority to pay interest which had accrued prior to the effective date of the FAST Act on December 4, 2015, but not for periods beyond that date. The RSFA and the FAST Act applies only to Federal oil and gas payments, not to payments for Indian, Solid mineral, and geothermal obligations.      
The Federal Oil and Gas Royalty Management Act of 1982 requires underpayment interest to be charged on late payments or any underpayment due. Underpayment interest on solid mineral and geothermal leases is calculated as simple interest using the United States Treasury Current Value of Funds Rate. Underpayment interest on oil and gas leases is calculated as compound interest using the Internal Revenue Service underpayment rate for corporate tax payers. Overpayment interest on oil and gas leases is calculated as compound interest using the Federal short-term rate plus 1 percentage point.

**Comment by Maroyafaied** [comment]
@badeh please review the changes your requested, if everything looks correct then I will push it on to the live site. Thanks 

http://2017onrr/ReportPay/interest.htm

**Comment by badeh** [comment]
Looks good; please push to live site.

Thank you!

​Hannah Bade
Office of Natural Resources Revenue
Financial Management/Financial Services
(303) 231-3373
Hannah.Bade@onrr.gov

________________________________
