### ISSUE TITLE
Add reporter letters collection items to links

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1643]

**Comment by mcharg** [comment]
This is blocking the majority of pages that aren't approved, so increasing priority to high.

**Comment by mcharg** [comment]
This is fixed.

**Comment by mcharg** [comment]
Reporter letters are showing up in both the Reporter Letters and Documents folders and not using the correct endpoint in the url.

**Comment by Maroyafaied** [comment]
@cthomasONRR please review.

**Comment by cthomasONRR** [comment]
When doing the inline linking of dear reporter letters, they are only sourcing from the DRL collection. So that part of this issue is resolved :)

**Comment by mcharg** [comment]
@cthomasONRR Did it put in a pdf icon when adding?

**Comment by cthomasONRR** [comment]
@mcharg no it did not
