### ISSUE TITLE
Prepare to present to Tim and Joe

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1652]
I scheduled a presentation on March 7th, here are the items we need to present about

- History of NRRD
- Technology used for NRRD
- Onrr.gov Redesign strategy (talk a bit about 508 project, user research done, visual design work, wireframes reviews)
- Decision to use Directus vs Drupal

**Comment by Maroyafaied** [comment]
They would like to know

- Why Directus over Drupal? What's the true cost of Directus
- Why the transition to cloud.gov? cost?
- Does Directus need an ATO
- I think we should also add a slide for tools and technology we use such as GitHub, ZenHub, CircleCI, etc.

**Comment by mcharg** [comment]
@Maroyafaied I added a first pass at slides to address all of the bullets you mention above.
https://doimspp.sharepoint.com/:p:/r/sites/NRRD/Shared%20Documents/General/Admin/Outreach/NRRD%26Onrr.gov.pptx?d=w97b896f578794560be7d9e5b293cf1fd&csf=1&web=1&e=mEq9uC
