### ISSUE TITLE
Update to Lease/Agreement Maintenance Contacts

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1654]
Please replace the contact list at the following link with the attached updated list - https://onrr.gov/reportpay/PDFDocs/RS_LeAgAssignments.pdf
[Lease Agreement Maintenance Contacts_2-16-22.pdf](https://github.com/ONRR/onrr.gov-site/files/8082854/Lease.Agreement.Maintenance.Contacts_2-16-22.pdf)

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 please update this document and also update the content tracking sheet with any changes. Thanks

**Comment by daniel-coleman-1** [comment]
https://doimspp.sharepoint.com/:x:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7BEE2FC3B4-4196-4DCE-9286-84AAF6E25E00%7D&file=ContactsFiles.xlsx&wdOrigin=OFFICECOM-WEB.START.SEARCH&ct=1644952501990&action=default&mobileredirect=true&ovuser=0693b5ba-4b18-4d7b-9341-f32f400a5494%2Ccolemanw%40mms.gov&cid=fdd5dcbe-28c8-4b51-8840-a470489bb4db

**Comment by daniel-coleman-1** [comment]
@bowlenj this page has been updated in dev for your review:
http://2017onrr/ReportPay/contacts.htm

with your approval I will push these changes live.

**Comment by bowlenj** [comment]
Looks great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: daniel-coleman-1 ***@***.***>
Sent: Thursday, February 17, 2022 9:17 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update to Lease/Agreement Maintenance Contacts (Issue #1654)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C36fa91364db5487d2d8408d9f232a1bf%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637807121543456162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=i1S7ZxaoNVNG3oY7qkk2e8VPP4VDk1%2FqagvU3lLNBj0%3D&reserved=0> this page has been updated in dev for your review:
http://2017onrr/ReportPay/contacts.htm

with your approval I will push these changes live.

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1654%23issuecomment-1043141497&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C36fa91364db5487d2d8408d9f232a1bf%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637807121543456162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KcWSGXd1yz%2BxRUvll8chBE05jg9RiSfZYHoQw6wxW6k%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH6XYEWB3BREPD46CNTU3UNR3ANCNFSM5OSRQBMA&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C36fa91364db5487d2d8408d9f232a1bf%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637807121543456162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yPinvo3bEzTF99ylFsixiB%2FDXpZAuWcXUi2D1LdZYOo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C36fa91364db5487d2d8408d9f232a1bf%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637807121543456162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=X4wI%2FIfthqKXpm9qfWhZsE6KNIO1dgqXEqiRpa9iQGQ%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C36fa91364db5487d2d8408d9f232a1bf%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637807121543456162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DlcTKJ5IWaMzoiaeoHTPJrL49tNr7oDLZOk9I1lY7u4%3D&reserved=0>.

**Comment by daniel-coleman-1** [comment]
@bowlenj we are live:
https://www.onrr.gov/ReportPay/contacts.htm
