### ISSUE TITLE
Collection: Image Blocks

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1656]
This will allow image and text to appear next to each other within the same column.

Wireframe:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/0495094f-09b8-4536-9872-e77a12c601b8)

What it does currently:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/a2c54d66-cb59-4fc6-acba-7c23fb69edd6)

**Comment by mcharg** [comment]
Wireframe:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/d165206e-7767-4dba-9780-237cc2463685)

How it currently appears: 
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/77059b16-35fd-42f8-a185-3cf853cae4f0)

**Comment by jlouis-onrr** [comment]
@mcharg, I think we'll want to create a new collection called Image Blocks, this will allow this to happen.  Just like the arrangement of other blocks and column sizing.

**Comment by mcharg** [comment]
Wireframe: ![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/2dc340ee-376e-49f3-9737-96f175ff96c6)

How it displays currently:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/daed327a-7dd5-471a-b2f8-11cb90bab39e)

**Comment by jlouis-onrr** [comment]
@mcharg, maybe image blocks might not be needed? I've added two more column choices to content blocks (2, 5) and setup the company contacts card using this.  Check it out. https://dev-onrr-frontend.app.cloud.gov/about/contact

**Comment by mcharg** [comment]
@jlouis-onrr I think that could work.  I'll try it out on the other pages next week.

**Comment by mcharg** [comment]
@jlouis-onrr Can you make a 10 wide content block, so we can have a 2 wide image and then have the content fill the rest of the row?  Right now, the next image goes on the first row.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/b1336999-a876-4e60-9e57-c88dc3e854e3)

**Comment by mcharg** [comment]
@jlouis-onrr I was able to put in a 2 wide column on the right as a workaround, but it would be better to have the 10 wide. ![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/7432cc1a-0609-492b-9527-292d5b8f5b20)

**Comment by jlouis-onrr** [comment]
@mcharg, added 10 col to the content block block col
