### ISSUE TITLE
Add alt text to images.

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1657]
See #1008 for list of pages.

**Comment by mcharg** [comment]
I'm only going to add alt text for images that we have alt text for as part of this issue.  I created a new issue for Dan to write alt text for images we don't have it for.

**Comment by mcharg** [comment]
Added alt text on these pages. @daniel-coleman-1 Please review.

- [ ] About ONRR https://dev-onrr-frontend.app.cloud.gov/about
- [ ] How Valuation Works https://dev-onrr-frontend.app.cloud.gov/references/valuation?tab=how-valuation-works
- [ ] Organization & Leadership https://dev-onrr-frontend.app.cloud.gov/about/organization
- [ ] IESC https://dev-onrr-frontend.app.cloud.gov/indian/assistance?tab=about
- [ ] How Leasing Works https://dev-onrr-frontend.app.cloud.gov/getting-started/how-leasing-works
- [ ] Contact Us https://dev-onrr-frontend.app.cloud.gov/about/contact
- [ ] Compliance Overview https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/compliance?tab=overview

**Comment by mcharg** [comment]
@cthomasONRR Can you please review the alt text on the above pages, since Dan is out the rest of the week.

**Comment by cthomasONRR** [comment]
@mcharg I don't see the alt text for 'About' in the CMS, but I think it's there on the dev site:
![image](https://user-images.githubusercontent.com/72526208/155561947-deb9ec1b-ac7b-4302-99a5-d1a4ca84352d.png)

![image](https://user-images.githubusercontent.com/72526208/155561904-5b4441e8-7e99-4e57-b180-8d427b365102.png)

**Comment by mcharg** [comment]
I'm not seeing it in the CMS either.

**Comment by mcharg** [comment]
@cthomasONRR About now has the alt text.

**Comment by cthomasONRR** [comment]
@mcharg Thanks, I'm seeing the About alt text now too. All other pages were good. You can close this issue now :)

**Comment by mcharg** [comment]
@cthomasONRR Can you check the Geothermal diagram?  The alt text wasn't displaying in the doc before, but it was there when I went to get the About text again.
https://dev-onrr-frontend.app.cloud.gov/reporting/geothermal

**Comment by cthomasONRR** [comment]
@mcharg I see the alt text for both CMS and dev site!
