### ISSUE TITLE
Update contacts

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#1658]
Hello -
Would you please update the contacts on onrr.gov for the Production and Payor Handbooks from April Lockler and Mary Dietrick to Aaron Lindquist - 303-231-3020. 

Thank you!

 https://onrr.gov/reportpay/Handbooks/index.htm

**Comment by cthomasONRR** [comment]
@merrellc 

Good morning, the changes are on the dev site: http://2017onrr/reportpay/Handbooks/index.htm
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@mcharg This is also updated in the CMS/new dev site.

**Comment by mcharg** [comment]
@kmhtran FYI for the handbooks wireframes - The production and Indian handbooks have new contacts.

**Comment by cthomasONRR** [comment]
@bowlenj

It looks like Candace Merrell is out for the entire week... would you be able to review and approve this issue for us? Thanks!!!

**Comment by bowlenj** [comment]
Yes, can you send me the link to view and approve?

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Tuesday, February 22, 2022 2:13 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update contacts (Issue #1658)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1f21fffc33644fe9018208d9f6483f3b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637811612427337707%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=N2OQ77blHla1G1kUj6VAHi8H3qiVF5dy27CXEX%2BEu18%3D&reserved=0>

It looks like Candace Merrell is out for the entire week... would you be able to review and approve this issue for us? Thanks!!!

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1658%23issuecomment-1048217061&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1f21fffc33644fe9018208d9f6483f3b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637811612427337707%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=a9YVsi%2BQSIQ7sT7VgyYNoQ8udSDXXKCBgIbl%2Bk9qr8o%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH6D3DDUOUMGNGYG6P3U4P4A5ANCNFSM5OZPMQRQ&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1f21fffc33644fe9018208d9f6483f3b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637811612427337707%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=V9qGlhbgmRzf7oypr%2Fwzb2n7kq9RLf9gr2VW4EpyRYo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1f21fffc33644fe9018208d9f6483f3b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637811612427337707%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ggw5LY8%2BHyBVF%2BdvNa3z9Hf3rQtVVSdlmXLfLEA7Uck%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1f21fffc33644fe9018208d9f6483f3b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637811612427337707%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=we2PdGyutua8pdoOKB%2BleaPBapocPZZI1C5yZ%2Fghy1E%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@bowlenj

Here is the link to the dev site: http://2017onrr/reportpay/Handbooks/index.htm.

The request was:
"Hello -
Would you please update the contacts on onrr.gov for the Production and Payor Handbooks from April Lockler and Mary Dietrick to Aaron Lindquist - 303-231-3020.

Thank you!
https://onrr.gov/reportpay/Handbooks/index.htm"

**Comment by bowlenj** [comment]
This looks great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Tuesday, February 22, 2022 2:57 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update contacts (Issue #1658)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C65432e1920504483a4b208d9f64e474d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637811638334691682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KUNDcsqBR6111nFXwmYUMl4Yg2ISeOKzuWDmHjxevD4%3D&reserved=0>

Here is the link to the dev site: http://2017onrr/reportpay/Handbooks/index.htm.

The request was:
"Hello -
Would you please update the contacts on onrr.gov for the Production and Payor Handbooks from April Lockler and Mary Dietrick to Aaron Lindquist - 303-231-3020.

Thank you!
https://onrr.gov/reportpay/Handbooks/index.htm<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fonrr.gov%2Freportpay%2FHandbooks%2Findex.htm&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C65432e1920504483a4b208d9f64e474d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637811638334691682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cZq9%2FPq3Irk0CDRasV7SbD89bzkPolgutCfs7JDtfeo%3D&reserved=0>"

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1658%23issuecomment-1048250625&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C65432e1920504483a4b208d9f64e474d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637811638334691682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bKtznMm0vxrYH7DjzmadSrWjffPMg3x8XIyjU3iZSX0%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH7J3VNRSFCLX2PFTJ3U4QBDBANCNFSM5OZPMQRQ&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C65432e1920504483a4b208d9f64e474d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637811638334691682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9gRCMgRymDYr27kKq18bGoV22Wt0%2Fq5hcsJu64hPtA8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C65432e1920504483a4b208d9f64e474d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637811638334691682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6Ij8jEfOX%2Fxr%2F5uoe8NtE6V8GvkPS7QoF%2BE7ABPPEW4%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C65432e1920504483a4b208d9f64e474d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637811638334691682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pQcCWe1Hkgnl%2BP3BX4hWlx7zrBiZfXKvlROZY51lliQ%3D&reserved=0>.

**Comment by merrellc** [comment]
Approval to go live.


Kind Regards,
​Candace Merrell
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.
________________________________
From: Christine Thomas ***@***.***>
Sent: Tuesday, February 22, 2022 6:32 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update contacts (Issue #1658)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@merrellc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmerrellc&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C2b337a936fbd4f3f809c08d9f607d88b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637811336716124977%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Qhjv9HOpmZ3i5Ndlz3bni5i8EviD8PV%2B4Nmy8NkjQkI%3D&reserved=0>

Good morning, the changes are on the dev site: http://2017onrr/reportpay/Handbooks/index.htm
Please review and give us your approval to go live.

Thanks,
Christine

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1658%23issuecomment-1047801075&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C2b337a936fbd4f3f809c08d9f607d88b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637811336716124977%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0SUepuwWp3MGXVy74o4Q4e9LpcK1nxuHPO1fg7ht4p8%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOXFVHHPYY7F642SGUWC3C3U4OF7VANCNFSM5OZPMQRQ&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C2b337a936fbd4f3f809c08d9f607d88b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637811336716124977%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=a8BT3ocv4T26ajnLANHd2hYRnsClTzsTMXf5kyg%2B4XQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C2b337a936fbd4f3f809c08d9f607d88b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637811336716124977%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MpfXHumCoSolje5KwiYYE2PPLRiUiidiIb%2FpalXfhjo%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C2b337a936fbd4f3f809c08d9f607d88b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637811336716124977%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zMFbRN8lazD5fD9kwYhgFvgVjxyOR6ZvQMYY7YJrIXI%3D&reserved=0>.
