### ISSUE TITLE
Write alt text for images

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1659]
See #1008 for list of pages with images needing alt text.

@daniel-coleman-1 Can you draft alt text for all the images in a doc that can be reviewed with SMEs?  Looking at the current site and handbooks pdfs, the alt text is pretty sparse and doesn't describe the images.

**Comment by cthomasONRR** [comment]
@mcharg I have 3 of the 4 webpages you listed completed. For the interest calculator equation, the CMS was not saving/retaining my alt text. Could you please review and see if you're having the same issue? Thanks!

**Comment by cthomasONRR** [comment]
@mcharg I was finally able to add alt text to late payment interest. Do you approve for this issue to close? Thanks for reviewing!
