### ISSUE TITLE
CMS image alt text issues

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1660]
@jlouis-onrr 

I'm trying to add alt text within the Indian Payor Handbook (https://dev-onrr-frontend.app.cloud.gov/references/handbooks/indian-payor-handbook?tab=25). 
CMS: https://dev-onrr-cms.app.cloud.gov/admin/content/pages/99

In Chapter 2, accordion 2.4.1, I added in the alt text, and now the image will not align with the actual text. They used to be side-by-side and now they are not:
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/3d47db38-948d-47de-bff4-e6a081ee46e2)
I even tried adjusting the image size to be smaller, but it did not help.

I know I have the content block spacing correct in the CMS:![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/6e6aed4f-6438-4189-9aa7-c81d6583aa0c)

Could you help me resolve this issue? None of the other images I added alt text to did this.

**Comment by jlouis-onrr** [comment]
@cthomasONRR, I've adjusted the image width smaller than the container (block that it is contained in) which allows it to fit as I think you where intending.  I'm going to add the ability to just stretch the image via the tunes button which will allow for the image to stretch to its container automatically without having to know the size. This image position issue is not related to the alt issue as that is a completely separate issue.

**Comment by cthomasONRR** [comment]
@jlouis-onrr

Thanks for your help!!! It's really weird that this happened after adding alt text. I did not adjust the image size at all. It's when I added the alt text that the alignment got messed up. Before adding the alt text, it was aligned appropriately. Anyway, thanks for fixing this for me. I will close this issue now. :)

**Comment by jlouis-onrr** [comment]
@cthomasONRR, just pushed out new updates that address the alt tag and the image containment issues.  Can you check it out when you have a chance?

**Comment by cthomasONRR** [comment]
@jlouis-onrr I was able to add and save alt text to the content block listed in issues #1661 and #1663. Thanks!
