### ISSUE TITLE
Swap out OST logo on the IESC page

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1662]
I checked with BTFA and they don't have a new logo yet and said to use the DOI seal.
https://www.onrr.gov/IndianServices/indian-energy-service-center.htm

**Comment by mcharg** [comment]
This updated in dev. @cthomasONRR Can you please review and let me know if it looks good to push live.
http://2017onrr/IndianServices/indian-energy-service-center.htm

**Comment by cthomasONRR** [comment]
@mcharg Updated logo looks good, approve to go live :)

**Comment by mcharg** [comment]
This is live.
