### ISSUE TITLE
Update Production Contact List

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1664]
Please replace the existing Onshore Production Contact list at the following link with the attached list - https://www.onrr.gov/reportpay/PDFDocs/OnshoreProductionContacts.pdf

[Onshore Production Assignments revised 2022.pdf](https://github.com/ONRR/onrr.gov-site/files/8120523/Onshore.Production.Assignments.revised.2022.pdf)

**Comment by daniel-coleman-1** [comment]
@bowlenj edits have been entered into dev for your review:
http://2017onrr/ReportPay/contacts.htm
with your approval I will push the update live.

**Comment by daniel-coleman-1** [comment]
@mcharg changes are entered into the tracking spreadsheet

**Comment by bowlenj** [comment]
Looks great!  Thank you

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: daniel-coleman-1 ***@***.***>
Sent: Tuesday, February 22, 2022 3:51 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update Production Contact List (Issue #1664)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C85446be35e454866c2d108d9f655d2e3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637811670741340288%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7vRXpU%2BFxCYiMPhn6sYt8bYJBsL5PctkpWWcCzTRHPk%3D&reserved=0> edits have been entered into dev for your review:
http://2017onrr/ReportPay/contacts.htm
with your approval I will push the update live.

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1664%23issuecomment-1048286475&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C85446be35e454866c2d108d9f655d2e3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637811670741340288%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ALsNjhM0vnMvQ2dS2YWyqcrVM9NWLGO0RrZNwmVhYS8%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VHYW26A4NKT3DKGGRLTU4QHNRANCNFSM5PCV2YBA&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C85446be35e454866c2d108d9f655d2e3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637811670741340288%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aLXe2S25vSWaTS4fLpgbEavMmLM57IjpxtHJ8OtVnR8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C85446be35e454866c2d108d9f655d2e3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637811670741340288%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PusjEbFsDBR5g82IP2fnc8Kq2s6RlFV3UBL6EHak9V4%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C85446be35e454866c2d108d9f655d2e3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637811670741340288%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gB8wWU0Z4ca6e%2B8RNaYkda7LwyQYP0k8rYbAF9OfFqA%3D&reserved=0>.

**Comment by daniel-coleman-1** [comment]
@bowlenj fantastic, we are live:
https://www.onrr.gov/ReportPay/contacts.htm
