### ISSUE TITLE
KAULEY VIRUTAL OUTREACH MEETING                               (To be added to Event Calendar on Allottee Assistance Page)

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#1666]
**KAULEY VIRTUAL OUTREACH MEETING**
WEDNESDAY, MARCH 16, 2022
1:00 pm to 2:00 pm CST
Location:  By Telephone

DESCRIPTION: This meeting will be a Call-in Meeting to hear a brief presentation and updates from the Office of Natural Resources Revenue (ONRR) Indian Outreach Office  Representatives from the Bureau of Land Management (BLM), Bureau of Trust Funds Administration (BTFA), and the Bureau of Indian Affairs (BIA) will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust property issues.  Owners will also have an opportunity to ask questions with the representatives of the four agencies during the Q&A session.

WHO SHOULD ATTEND: IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Southern Plains Region in Oklahoma.

OTHER INFORMATION: To reserve a space and get a passcode for this meeting please contact the ONRR OKC Outreach Office toll-free at (800) 354-7015. The OKC Outreach Office hours are Monday-Friday from 7:30 am-5:00 pm.

CONTACT: ONRR OKC Outreach Office, Toll Free (800) 354-7015;  EMAIL: onrroutreachokc@onrr.gov

**ID, UT, NE, WY, and CO VIRTUAL OUTREACH** 
THURSDAY, MARCH 24, 2022 
Time: 1:00 pm-1:30 pm MST 
Location:  By Telephone 

DESCRIPTION: Representatives from the Office of Natural Resources Revenue will host a Question and Answer session by phone for Indian Mineral Owners and Trust Property Owners regarding their Indian Oil & Gas leases, IIM Accounts, and Indian Trust Properties. Representatives from the Bureau of Land Management, Bureau of Indian Affairs, and Bureau of Trust Funds Administration are invited to be in attendance to answer questions.  

WHO SHOULD ATTEND:  IIM account holders, Indian mineral owners, and Indian trust property owners in the Idaho, Utah, Nebraska, Wyoming, and Colorado areas.  
OTHER INFORMATION: To attend the outreach session, please contact the ONRR Denver Outreach Office at (800) 982-3226, for the call-in number and passcode.  The ONRR Denver Outreach Office hours are Monday-Friday 7:30am-4:00pm. 

CONTACT:  ONRR Denver Outreach Office, Toll Free (800) 982-3226,  Email: onrroutreachdenver@onrr.gov

**Comment by cthomasONRR** [comment]
@Toddsand21 

Good morning, the changes are on the dev site: http://2017onrr/events.htm.
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by Toddsand21** [comment]
In the 1st sentence after DESCRIPTION: Put a period after it reads.... (ONRR) Indian Outreach Office.

**Comment by cthomasONRR** [comment]
@Toddsand21 

Updates are on the dev site: http://2017onrr/events.htm
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by Toddsand21** [comment]
Looks ready to go. Thanks!

**Comment by cthomasONRR** [comment]
@Toddsand21 Great, thanks! These changes are now live: https://www.onrr.gov/events.htm. Please feel free to email me if you need the time changed.

**Comment by Toddsand21** [comment]
Thanks!
