### ISSUE TITLE
February analytics

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1670]

**Comment by daniel-coleman-1** [comment]
@mcharg this is ready for review

**Comment by mcharg** [comment]
@daniel-coleman-1 I'm seeing a different total for search.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/1af3dfac-ce20-4232-8faa-4dbf8bfdc46e)

**Comment by mcharg** [comment]
Everything else looks good.

**Comment by daniel-coleman-1** [comment]
Thanks for the edits @mcharg, closing
