### ISSUE TITLE
Clean up handbooks wireframes and import into overall prototype

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1671]

**Comment by Maroyafaied** [comment]
@Maroyafaied @lpgoldstein review once it's ready.

**Comment by mcharg** [comment]
Link to review: https://qmcq5k.axshare.com/#id=th2nbq&p=handbooks

**Comment by mcharg** [comment]
@lpgoldstein @Maroyafaied I removed the links to the pdfs from the TOCs in the wireframes.

**Comment by Maroyafaied** [comment]
@mcharg Is there a prototype for Solid Minerals Handbook? the link just takes me to the solid minerals page, all the other ones look good.  Also, we probably need to think about the Indian payor handbook and how to design it or if we're keeping it the same? I can't remember if we spoke to any SME regarding that handbook?

**Comment by mcharg** [comment]
@Maroyafaied Here's Solids.  I'll fix the link on the handbooks page. https://qmcq5k.axshare.com/#id=xhb8nn&p=solid_minerals_reporter_handbook&dp=0&g=1

We did review the Indian Payor handbook and they said we need to keep it very close to the way it is now because of something to do with the RPC and not being able to change anything that came out of requests from that.  They were good with the way it is in the wireframes.

**Comment by Maroyafaied** [comment]
@mcharg thanks for the reminder. Solids looks good.
