### ISSUE TITLE
Crop hero images externally and replace the ones in dev with them

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1678]

**Comment by mcharg** [comment]
Ready to review. @Maroyafaied @lpgoldstein @cthomasONRR 

Home: https://dev-onrr-frontend.app.cloud.gov/
Getting Started: https://dev-onrr-frontend.app.cloud.gov/getting-started
Reporting: https://dev-onrr-frontend.app.cloud.gov/reporting
References: https://dev-onrr-frontend.app.cloud.gov/references
Paying: https://dev-onrr-frontend.app.cloud.gov/paying
Compliance: https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement
Indian Resources: https://dev-onrr-frontend.app.cloud.gov/indian
About: https://dev-onrr-frontend.app.cloud.gov/about

I also found attribution info for the ones not made by ONRR employees and added that to the descriptions.

The Compliance one looks grainier than the others and the beauty is lost when you crop off the reflection.  Thoughts on replacing?

**Comment by mcharg** [comment]
Note: If you're not seeing the new cropping - clear cache.

**Comment by mcharg** [comment]
Those are what those looked like before cropping. You'll have to clear cache to see the new versions.
![image](https://user-images.githubusercontent.com/38465926/158465291-dc390bcb-2b3f-49ed-b6ec-4e2c6072ffec.png)
![image](https://user-images.githubusercontent.com/38465926/158465323-445b1f46-3995-4904-bb4d-e07c74152bfd.png)

**Comment by mcharg** [comment]
@Maroyafaied I had to wait for quite a while for them to show up.  You could also try a different browser.

**Comment by cthomasONRR** [comment]
@mcharg The only one I don't personally like is compliance and enforcement. This is super picky, but could you re-center so that the mountain isn't cut off? 
![image](https://user-images.githubusercontent.com/72526208/158465947-8649c2c7-8c91-4d05-bc9a-e23e427cefa7.png)

**Comment by mcharg** [comment]
@cthomasONRR Replacing it with this image.
![Echo Lake Mt Evans CO](https://user-images.githubusercontent.com/38465926/158466132-06acc5b2-295c-4286-981a-d737d1bb96b6.jpg)

**Comment by mcharg** [comment]
Looks nice in the page. 
![image](https://user-images.githubusercontent.com/38465926/158466304-cf421a9d-9923-4370-be64-d6108a7292d8.png)

**Comment by cthomasONRR** [comment]
@mcharg Love it! Thanks!

**Comment by mcharg** [comment]
And the functionality to replace the images worked and propagated to everywhere it's used.  Even was able to upload a file with a different name with no problem.

**Comment by Maroyafaied** [comment]
@mcharg I'm able to see all the cropped images now, everything looks good!
