### ISSUE TITLE
April IBMP Prices

### ISSUE THREAD

**Issue by jboroos** [ONRR/onrr.gov-site#168]
We've posted our April Indian Oil IBMP prices to the IBMP tab of the "Data for ONRR.gov" spreadsheet on OneDrive.  Can you please update (https://www.onrr.gov/Valuation/IndianOilIBMP.htm) with the new prices? 

Please update our development site first (http://2017onrr/Valuation/IndianOilIBMP.htm) and let me know so I can review them before they go public.  Thanks! @jboroos @sudarr

**Comment by lpgoldstein** [comment]
@jboroos @sudarr This is ready for your review http://2017onrr/Valuation/IndianOilIBMP.htm

**Comment by jboroos** [comment]
Thanks @lpgoldstein. It looks like we lost our trailing 0s in the table.  Other than that, everything looks good.  @jboroos @sudarr

**Comment by lpgoldstein** [comment]
@jboroos I'll fix that before it goes live.

**Comment by lpgoldstein** [comment]
@jboroos @sudarr It should be live now.

**Comment by jboroos** [comment]
Thanks @lpgoldstein.  Looks good! @jboroos @sudarr
