### ISSUE TITLE
PDF icons are displaying black instead of blue

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1680]

**Comment by mcharg** [comment]
@jlouis-onrr The PDF icons are now blue, but all the other file types are still black.

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/6313bc24-71b0-4f8e-a267-2004f19b38af)

**Comment by jlouis-onrr** [comment]
the update was only for the pdf icons, let me target all other icons.

**Comment by jlouis-onrr** [comment]
updates are in dev

**Comment by mcharg** [comment]
@jlouis-onrr Looks good. Thanks!
