### ISSUE TITLE
Events:  Kauley Virtual Meeting                                                          (found Events under the Allotte Assistance Page)

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#1684]
Can we change the date of the Kauley Meeting from March 16th to March 17th?  Everything else remains the same.

**Comment by cthomasONRR** [comment]
@Toddsand21 

Sure, this change is now on the dev site: http://2017onrr/events.htm
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by Toddsand21** [comment]
It looks fine and ready to go.  Thanks.

**Comment by cthomasONRR** [comment]
@Toddsand21 Great, the changes are now live: https://www.onrr.gov/events.htm.
Closing this issue now.
