### ISSUE TITLE
NYMEX February prices for ONRR.gov

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#1685]
The February NYMEX prices are ready to be uploaded to ONRR.gov.  The spreadsheet is attached.

Thanks,
Cory Forgrave
@sudarr  
[NYMEX022022.xlsx](https://github.com/ONRR/onrr.gov-site/files/8187516/NYMEX022022.xlsx)

**Comment by forgravec** [comment]
Christine,

The prices look good.

Thanks,
Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
***@***.***
________________________________
From: Christine Thomas ***@***.***>
Sent: Friday, March 4, 2022 10:09 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Forgrave, Cory J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] NYMEX February prices for ONRR.gov (Issue #1685)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@forgravec<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fforgravec&data=04%7C01%7Ccory.forgrave%40onrr.gov%7C550727c16c6d43bf571b08d9fe01eb48%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637820106476842489%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=C%2FZPMbxm33cdPXpElhYuj49ifzQkp3A1CjCGRxPsFGs%3D&reserved=0>

Good morning, these changes are now on the dev site: http://2017onrr/valuation/NYMEX.htm
Please review and give us your approval to go live.

Thanks,
Christine

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1685%23issuecomment-1059348910&data=04%7C01%7Ccory.forgrave%40onrr.gov%7C550727c16c6d43bf571b08d9fe01eb48%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637820106476842489%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FFmxzCSgAK7DiukbvWpwJw4VU91ik6qR64mQ9%2Bd%2FwNA%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOXGYMCSTNAFMJHCOHIDIBLU6I7VVANCNFSM5P6B7B5A&data=04%7C01%7Ccory.forgrave%40onrr.gov%7C550727c16c6d43bf571b08d9fe01eb48%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637820106476998721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ME37YrzfMP%2FpCbUM0CfUDeviqJ2JbJCvSAg8kOgTGZk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ccory.forgrave%40onrr.gov%7C550727c16c6d43bf571b08d9fe01eb48%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637820106476998721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fySDMJM3jxkaZVhzwB0DQVtL5X4ODih1FIdte8Wky74%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ccory.forgrave%40onrr.gov%7C550727c16c6d43bf571b08d9fe01eb48%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637820106476998721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0XPZ8dOvBhJihGckFdchRBASUfOSymnFCpALaiB1wGY%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@forgravec Great, these changes are now live: https://www.onrr.gov/valuation/NYMEX.htm

@mcharg I also updated the CMS with the this new 2/2022 NYMEX excel.
