### ISSUE TITLE
Update March Index Zone prices on onrr.gov

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#1686]
Good morning,

Please update the index zone pricing as shown on the "Data for onrr.gov" spreadsheet.

@sudarr

Thanks,
Sean

**Comment by cthomasONRR** [comment]
@boices 

Good morning, these changes are now on the dev site: http://2017onrr/valuation/allzones.htm
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by boices** [comment]
Those look great, thanks again!

**Comment by cthomasONRR** [comment]
@boices Great, these changes are now live: https://www.onrr.gov/valuation/allzones.htm
