### ISSUE TITLE
Revisit onrr.gov personas/user types

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1687]
It's become clear that we are missing some user types. I'd like to do a series of design studios where we define the dimensions for how people use onrr.gov and do something similar to the triangles.

**Comment by jkwonatx** [comment]
@mcharg happy to help. Lmk how

**Comment by mcharg** [comment]
@jkwonatx Here's the ppt from the design studio when we did this for NRRD. Let's discuss after you get back from vacation.
https://doimspp.sharepoint.com/:p:/r/sites/NRRD/Shared%20Documents/General/NRRD/User%20Research/User%20Types/User%20Types%20Design%20Studio.pptx?d=w78b18e59a41242d288019453fc0881b8&csf=1&web=1&e=egFQUv

**Comment by mcharg** [comment]
I was thinking about this today and I think a good first step is for me to go through all of the existing onrr.gov studies and catalog user tasks and then after Jae and Kaitlyn are back, we can do a design studio where we group the users into like categories to arrive at a task-based set of user types.
