### ISSUE TITLE
Remove PDF at ICR 1012-0008, wrong primary location

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1692]
https://dev-onrr-cms.app.cloud.gov/admin/content/pages/91
https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0008

I added a PDF here as the primary location, but the primary location should be within the forms webpage.

Could you please remove this PDF?

Thanks!

**Comment by mcharg** [comment]
https://dev-onrr-cms.app.cloud.gov/admin/files/c2d94fc4-5297-4e8c-bdc9-b13eaab774d7

**Comment by mcharg** [comment]
Done
