### ISSUE TITLE
Clean up spacing with document icons

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1696]
The spacing is much wider than for other bullets.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/d6b7bfae-95f6-4c0c-b05c-481160fb00ab)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/52d8d109-d364-4d84-9377-dcaecf6e4b54)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/c4b042d6-fb3c-41dd-838f-53b817d54f7e)

**Comment by Maroyafaied** [comment]
@mcharg please review
