### ISSUE TITLE
Plan user interviews for onrr.gov

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#17]
- [ ] Compile list of questions to ask for each user type
- [ ] Write study plan and script

We will plan on conducting this study in January.

**Comment by alenahuang** [comment]
The link to the interview plan:
https://docs.google.com/document/d/1eKYKnz9YCIeKofMuMFn2yitPUiaScllBeNLUyuXfCog/edit?usp=sharing

**Comment by mcharg** [comment]
@jennmalcolm @persam2 @lpgoldstein Please review the interview plan.

**Comment by jennmalcolm** [comment]
Looks good. I added my comments.

**Comment by mcharg** [comment]
@alenahuang Can you please take a look at Jennifer's comments and update the plan accordingly.

@persam2 Have you had a chance to review?
