### ISSUE TITLE
Footer "Accessibility" link broken

### ISSUE THREAD

**Issue by Christian-Sibo-ONRR** [ONRR/onrr.gov-site#1700]
In the standard page footer, the `Accessibility` link is pointing at "https://www.doi.gov/accessibility.cfm". That page seems to no longer exist. doi.gov's own footer points at "https://www.doi.gov/accessibility".

The `DOI Privacy` link is similarly outdated but doi.gov appears to redirect that one to their new page already.

**Comment by Christian-Sibo-ONRR** [comment]
> I corrected the accessibility link in the homepage for now. Please review the changes in the homepage, if it looks good to you then I will push the changes to the live site.

The link in the test site looks correct. Thank you.

**Comment by Maroyafaied** [comment]
@Christian-Sibo-ONRR Thanks, this is live.

**Comment by mcharg** [comment]
@Christian-Sibo-ONRR we got DOI to redirect the broken url, so it should now be fixed on all pages.
