### ISSUE TITLE
Ensure all document icons display the same size.

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1703]
The pdf one is smaller than the others.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/6dec849d-6d66-47c4-95e9-10831a8f21ab)

**Comment by mcharg** [comment]
And they should all be blue.

**Comment by jlouis-onrr** [comment]
@mcharg, the pdf icon size has been increased to match closer to other icons
