### ISSUE TITLE
Review Accordion Punctuation

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/onrr.gov-site#1705]
- [x] Getting Started - System Access - Troubleshooting
- [x] Getting Started - System Access - New Reporter Checklist
- [x] Reporting - Oil & Gas Production - New Reporter Checklist
- [x] Reporting - Oil & Gas Production - Troubleshooting
- [x] Reporting - Oil & Gas Revenue - New Reporter Checklist
- [x] Reporting - Oil & Gas Revenue - Troubleshooting
- [x] Reporting - Solid Minerals - New Reporter Checklist
- [x] Reporting - Solid Minerals - Troubleshooting
- [x] Reporting - Geothermal - New Reporter Checklist
- [x] Reporting - Geothermal - Troubleshooting
- [x] References - Valuation and Pricing - Unbundling
- [x] References - Reporter Training - Training Videos - New Reporters
- [x] References - Reporter Training - Training Videos - Oil & Gas Production
- [x] References - Reporter Training - Training Videos - Oil & Gas Revenue
- [x] Paying - Contacts - Troubleshooting
- [x] Contact Us - Getting Started Contacts - Troubleshooting
- [x] Contact Us - System Access Contacts - Troubleshooting
- [x] Contact Us - Lease & Agreement Contacts - Troubleshooting
- [x] Contact Us - Oil & Gas Production Contacts - Troubleshooting
- [x] Contact Us - Oil & Gas Royalty Contacts - Troubleshooting
- [x] Contact Us - Oil & Gas Rent Contacts - Troubleshooting
- [x] Contact Us - Solid Minerals Contacts - Troubleshooting
- [x] Contact Us - Geothermal Contacts - Troubleshooting
- [x] Contact Us - Payment & Debt Collection Contacts - Troubleshooting
  - [x] Contact Us - Updating Contact Info Contacts - Troubleshooting

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I started my review and found quite a few accordions that haven't been worked on, I stopped reviewing. Please review the dev site before requesting my review to save me time. Thanks

![image](https://user-images.githubusercontent.com/40175688/158427406-79fa44d8-1a07-498d-9ccb-cfb02b19f6c7.png)
![image](https://user-images.githubusercontent.com/40175688/158427567-1101b274-f62d-4bdc-810e-4ac0a6d4ac92.png)
![image](https://user-images.githubusercontent.com/40175688/158427929-8e3d07c6-d719-4794-9a65-186f96bf864c.png)
![image](https://user-images.githubusercontent.com/40175688/158427998-f88b3c0c-9424-4eea-8662-b0db7d3c453b.png)

**Comment by daniel-coleman-1** [comment]
@Maroyafaied the following are fragments and do not require punctuation at the end:

Unbundling tab on References -> Valuation and Pricing
![Screenshot 2022-03-15 104746](https://user-images.githubusercontent.com/83892362/158429224-7ef44a96-3237-4c7f-bfc3-14839878d9f3.png)


New Reporters tab on References -> Reporter Training -> Training Videos
![Screenshot 2022-03-15 104814](https://user-images.githubusercontent.com/83892362/158429282-c69a8fe9-a39d-4a4b-a9c5-a010d8b6393b.png)


Oil & Gas Production tab on References -> Reporter Training -> Training Videos
![Screenshot 2022-03-15 104830](https://user-images.githubusercontent.com/83892362/158429343-f6cf5bb3-1148-4cc1-ace4-ea964bee8a35.png)


Oil & Gas Revenue tab on References -> Reporter Training -> Training Videos
![Screenshot 2022-03-15 104850](https://user-images.githubusercontent.com/83892362/158429396-f6e491ff-1f15-4031-bd00-91e2579ccc5a.png)

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 Ok, thanks for clarifying. I'll review again once you have implemented the common noun changes in issue#1714 so I only have to review once. Let me know when those changes are done. Thanks

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 can you change agreement number to also be a common noun and not sure if you reviewed the content within the accordions but there's a few instances where operator number and payor code are still capitalized. 
![image](https://user-images.githubusercontent.com/40175688/158477255-b8d3d804-e3ae-4538-a813-633e284627ff.png)
![image](https://user-images.githubusercontent.com/40175688/158478634-4d8fa966-f6c1-4286-8ee2-ea723d7cc127.png)
![image](https://user-images.githubusercontent.com/40175688/158478783-7ab6bdaf-359e-47ba-aa1a-0ed57699a36a.png)
![image](https://user-images.githubusercontent.com/40175688/158478886-c6256048-3ec1-4eea-910a-fa2beefdc24c.png)

**Comment by daniel-coleman-1** [comment]
@Maroyafaied thanks for catching, I got those edits entered into the CMS

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 is there a reason why agreement is still capital ? See comment and pic above from my review yesterday.

**Comment by daniel-coleman-1** [comment]
@Maroyafaied Agreement is capitalized there because it's the first word of a quotation

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 Is that guidance from Chicago Manuel style? The quotation is not in the start of the sentence.

**Comment by daniel-coleman-1** [comment]
@Maroyafaied yes, that's correct for Chicago

**Comment by daniel-coleman-1** [comment]
@Maroyafaied this isn't a punctuation issue, so I can save it for a sync up if you'd prefer, but I'm looking at the Leases & Agreements accordion and it seems we refer the user to the page they are on here:
![Screenshot 2022-03-16 090123](https://user-images.githubusercontent.com/83892362/158621593-310ac43f-f903-487d-ae75-bc923af91695.png)

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I'm reviewing both punctuation and proper/common nouns at once.  My understanding is that when quoting a complete sentence, you should capitalize the first word no matter where the quote is placed but in this case when the quote is a fragment and not a complete sentence then it doesn't have to be capitalized when it's placed in the middle of a sentence. If you can share the Chicago style guidance you found that sentence fragment quotation within a sentence  should be capitalized  then I'm good with leaving it capital.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I'm reviewing both punctuation and proper/common nouns at once.  My understanding is that when quoting a complete sentence, you should capitalize the first word no matter where the quote is placed but in this case when the quote is a fragment and not a complete sentence then it doesn't have to be capitalized when it's placed in the middle of a sentence. If you can share the Chicago style guidance you found that sentence fragment quotation within a sentence  should be capitalized  then I'm good with leaving it capital.

**Comment by daniel-coleman-1** [comment]
@Maroyafaied the Chicago Manual guidance as per section 13.18 is to capitalize here, because it is a quote taken from a different context (the error message) and placed in this line of text.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I don't have a subscription to Chicago's Manuel, can you post a screen shot of the section you referenced.

**Comment by daniel-coleman-1** [comment]
@Maroyafaied I have a physical copy, here's the text:

Changing Capitalization to suit syntax - an overview.  Aside from proper nouns and some of the words derived from them (see 8.1), most words are normally lowercased unless they begin a sentence (or, often, a line of poetry).  To suit this requirement, the first word in a quoted passage must often be adjusted to conform to the surrounding text.  In most types of works, this adjustment may be done silently, as such capitalization does not normally affect the significance of such quoted matter, which is assumed to be taken from another contex (see 13.7, item 3).  In some types of works, however, it may be obligatory to indicate the change by bracketing the initial quoted letter; for examples of this practice, appropriate to legal writing and some types of textual commentary, see 13.21.

**Comment by daniel-coleman-1** [comment]
@Maroyafaied so if the quote suits the syntax, you don't capitalize, but if it doesn't, you do capitalize.  The example my manual gives is:
Benjamin Franklin admonishes us to "plough deep while sluggards sleep."

Where in that example the syntax of the sentence is continued, but in:
I'm getting an error message about "Agreement number not related to reported lease"

so if we wanted to drop that to lower case we'd need something more like:
I'm getting an error message saying my "agreement number does not match the lease"

Is that a little more clear?

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 Thanks, can you change it to lower case with the sentence you suggested (I'm getting an error message saying my "agreement number does not match the lease"). You can close this issue and issue #1714 after this change. Thanks

**Comment by daniel-coleman-1** [comment]
@Maroyafaied input edits, closing the issue now.

![Screenshot 2022-03-16 143053](https://user-images.githubusercontent.com/83892362/158685426-1dc0308d-387d-468d-8aef-3b424eaf906a.png)
