### ISSUE TITLE
Change utility header nav to make it more visible

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1709]
We made this change to the prototype based on user research findings. Also change contact icon.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/76fcd480-66e2-40aa-ad1a-fa948b5ff811)

**Comment by jlouis-onrr** [comment]
@mcharg, looks like you were trying to use a mui icon.  I've since added the material icons link to the input field and updated the value.

![menu-icon.png](https://images.zenhubusercontent.com/5d893e494c2d9e0001fa99ad/e9c81973-d165-49a5-aaae-3a0a677452cd)

**Comment by mcharg** [comment]
@jlouis-onrr Can you also add the new icon to the contacts link in the footer?

**Comment by jlouis-onrr** [comment]
@mcharg, these updates are now in dev.

**Comment by mcharg** [comment]
@jlouis-onrr Looks good!
