### ISSUE TITLE
RRM Handbook Files for Update on ONRR.gov

### ISSUE THREAD

**Issue by jillbong79** [ONRR/onrr.gov-site#171]
[MRRH-Appendix-A.pdf](https://github.com/ONRR/onrr.gov-site/files/4629667/MRRH-Appendix-A.pdf)
[MRRH-Appendix-B.pdf](https://github.com/ONRR/onrr.gov-site/files/4629669/MRRH-Appendix-B.pdf)
[MRRH-Appendix-C.pdf](https://github.com/ONRR/onrr.gov-site/files/4629670/MRRH-Appendix-C.pdf)
[Uploading MRRH-Appendix-D.pdf…]
[MRRH-Appendix-E.pdf](https://github.com/ONRR/onrr.gov-site/files/4629672/MRRH-Appendix-E.pdf)
[Uploading MRRH-Appendix-F.pdf…]
[MRRH-Appendix-G.pdf](https://github.com/ONRR/onrr.gov-site/files/4629675/MRRH-Appendix-G.pdf)
[MRRH-Chapter-1.pdf](https://github.com/ONRR/onrr.gov-site/files/4629676/MRRH-Chapter-1.pdf)
[MRRH-Chapter-2.pdf](https://github.com/ONRR/onrr.gov-site/files/4629677/MRRH-Chapter-2.pdf)
[MRRH-Chapter-4.pdf](https://github.com/ONRR/onrr.gov-site/files/4629678/MRRH-Chapter-4.pdf)
[MRRH-Table-of-Contents_HAHN-Draft.docx](https://github.com/ONRR/onrr.gov-site/files/4629681/MRRH-Table-of-Contents_HAHN-Draft.docx)
[Codes_for_2014  onrr website (working copy).pdf](https://github.com/ONRR/onrr.gov-site/files/4629682/Codes_for_2014.onrr.website.working.copy.pdf)
[Glossary.pdf](https://github.com/ONRR/onrr.gov-site/files/4629683/Glossary.pdf)
[MRRH-Abbreviations.pdf](https://github.com/ONRR/onrr.gov-site/files/4629684/MRRH-Abbreviations.pdf)

These are the files identified by Glen as final copies of the updated version of RRM's Handbook for Production and Royalty.  Please let me know if you have any questions.  Thank you!

**Comment by jillbong79** [comment]
[MRRH-Appendix-D.pdf](https://github.com/ONRR/onrr.gov-site/files/4629705/MRRH-Appendix-D.pdf)
[MRRH-Appendix-F.pdf](https://github.com/ONRR/onrr.gov-site/files/4629706/MRRH-Appendix-F.pdf)

**Comment by jillbong79** [comment]
Good morning, and happy Friday!
Glen has given the green light for these final documents.  These are ready for publication.  Please let me know if you have any questions.  Thank you!
[RRM-Abbreviations.pdf](https://github.com/ONRR/onrr.gov-site/files/4703141/RRM-Abbreviations.pdf)
[RRM-Appendix A.pdf](https://github.com/ONRR/onrr.gov-site/files/4703142/RRM-Appendix.A.pdf)
[RRM-Appendix B.pdf](https://github.com/ONRR/onrr.gov-site/files/4703143/RRM-Appendix.B.pdf)
[RRM-Appendix C.pdf](https://github.com/ONRR/onrr.gov-site/files/4703145/RRM-Appendix.C.pdf)
[RRM-Appendix D.pdf](https://github.com/ONRR/onrr.gov-site/files/4703146/RRM-Appendix.D.pdf)
[RRM-Appendix F.pdf](https://github.com/ONRR/onrr.gov-site/files/4703148/RRM-Appendix.F.pdf)
[RRM-Appendix-G.pdf](https://github.com/ONRR/onrr.gov-site/files/4703149/RRM-Appendix-G.pdf)
[RRM-Form_CMP2014_Industry_FAQ.pdf](https://github.com/ONRR/onrr.gov-site/files/4703150/RRM-Form_CMP2014_Industry_FAQ.pdf)
[RRM-Multi-Unit Well Agreements.pdf](https://github.com/ONRR/onrr.gov-site/files/4703152/RRM-Multi-Unit.Well.Agreements.pdf)
[RRM-Overlapping Agreement Training 2020 Handbook.pdf](https://github.com/ONRR/onrr.gov-site/files/4703158/RRM-Overlapping.Agreement.Training.2020.Handbook.pdf)
[RRM-Table of Contents for Suppl V7.pdf](https://github.com/ONRR/onrr.gov-site/files/4703164/RRM-Table.of.Contents.for.Suppl.V7.pdf)

**Comment by jennmalcolm** [comment]
Thanks, @jillbong79

**Comment by jennmalcolm** [comment]
@jillbong79 in looking at the first table of contents vs. the newer table of contents for the supplemental documents, I have a question. Do you want the sections and subsections of the supplemental documents included in the searchable table of contents?

**Comment by sghahn** [comment]
@jennmalcolm We would like to have the "supplemental" under it's own "tab" and under the Main TOC with all of the section and subsection documents included for search, if possible.

**Comment by jennmalcolm** [comment]
Ok, thanks

**Comment by jillbong79** [comment]
@jennmalcolm 

okie dokie.  here are the 508 compliant documents that are ready to go!  glen will be following up with an email to confirm.  please let me know if you have any questions.  thank you!

**Final Documents:**
[RRM-Multi-Unit Well Agreements.pdf](https://github.com/ONRR/onrr.gov-site/files/4773123/RRM-Multi-Unit.Well.Agreements.pdf)
[RRM-Form_CMP2014_Industry_FAQ.pdf](https://github.com/ONRR/onrr.gov-site/files/4773124/RRM-Form_CMP2014_Industry_FAQ.pdf)
[RRM-Appendix D.pdf](https://github.com/ONRR/onrr.gov-site/files/4773044/RRM-Appendix.D.pdf)
[RRM-Appendix F.pdf](https://github.com/ONRR/onrr.gov-site/files/4773045/RRM-Appendix.F.pdf)
[RRM-Appendix G.pdf](https://github.com/ONRR/onrr.gov-site/files/4773046/RRM-Appendix.G.pdf)
[RRM-Chapter 3 - Paper 2014 Reporting.pdf](https://github.com/ONRR/onrr.gov-site/files/4773047/RRM-Chapter.3.-.Paper.2014.Reporting.pdf)

**Things to note:**
- Appendix E and Glossary are pending
- Next week we will be sending ch. 1-3, 6 and 8

**Comment by jillbong79** [comment]
**some of the documents didn't go through...these are final also:**
[RRM-Appendix B.pdf](https://github.com/ONRR/onrr.gov-site/files/4773137/RRM-Appendix.B.pdf)
[RRM-Appendix C.pdf](https://github.com/ONRR/onrr.gov-site/files/4773138/RRM-Appendix.C.pdf)
[RRM-Appendix A.pdf](https://github.com/ONRR/onrr.gov-site/files/4773139/RRM-Appendix.A.pdf)
[RRM-Overlapping Agreement Training 2020 Handbook.pdf](https://github.com/ONRR/onrr.gov-site/files/4773140/RRM-Overlapping.Agreement.Training.2020.Handbook.pdf)
[RRM-Table of Contents for Suppl V7.pdf](https://github.com/ONRR/onrr.gov-site/files/4773146/RRM-Table.of.Contents.for.Suppl.V7.pdf)

**Comment by jillbong79** [comment]
[RRM-Abbreviations.pdf](https://github.com/ONRR/onrr.gov-site/files/4773158/RRM-Abbreviations.pdf)

**Comment by jennmalcolm** [comment]
Final title page
[RRM-Title page.pdf](https://github.com/ONRR/onrr.gov-site/files/4782056/RRM-Title.page.pdf)

**Comment by jillbong79** [comment]
@jennmalcolm 

Howdy!  Hope you are doing well!

Here are the docs Glen emailed you about today.  Please let me know if you have any questions.  
*Note: The first doc (sliding scale) is part of the supplemental documentation.  

**Documents:**
[RRM-Step- sliding-scale royalty rates.pdf](https://github.com/ONRR/onrr.gov-site/files/4801159/RRM-Step-.sliding-scale.royalty.rates.pdf)
[RRM-Chapter 1.pdf](https://github.com/ONRR/onrr.gov-site/files/4801160/RRM-Chapter.1.pdf)
[RRM-Chapter 2.pdf](https://github.com/ONRR/onrr.gov-site/files/4801161/RRM-Chapter.2.pdf)
[RRM-Chapter 3 Electronic 2014 Reporting.pdf](https://github.com/ONRR/onrr.gov-site/files/4801163/RRM-Chapter.3.Electronic.2014.Reporting.pdf)
[RRM-Chapter 6.pdf](https://github.com/ONRR/onrr.gov-site/files/4801164/RRM-Chapter.6.pdf)
[RRM-Chapter 8.pdf](https://github.com/ONRR/onrr.gov-site/files/4801167/RRM-Chapter.8.pdf)
[RRM-Chapter 9.pdf](https://github.com/ONRR/onrr.gov-site/files/4801168/RRM-Chapter.9.pdf)

**Comment by jennmalcolm** [comment]
@jillbong79 you gave us a chapter 9, but we don't have chapter 9 on the table of contents. Is there a newer version of the table of contents that includes chapter 9? Thanks.

**Comment by jillbong79** [comment]
@jennmalcolm eek!  i don't know.  let me ask glen.  i don't work this particular section of RRM, so i'll have to see what glen says.  will get back with you today.  thanks!

**Comment by jennmalcolm** [comment]
New table of contents submitted by email 
[Table of Contents (working copy-Jennifer).docx](https://github.com/ONRR/onrr.gov-site/files/4832600/Table.of.Contents.working.copy-Jennifer.docx)

**Comment by sghahn** [comment]
@jennmalcolm, thank you.

**Comment by lpgoldstein** [comment]
@jennmalcolm think this is a space issue in TOC ![image.png](https://images.zenhubusercontent.com/5c59d3cd7592186396262002/a95e3e0b-da6d-4700-8bb3-5e5b5095f6d0)

**Comment by jennmalcolm** [comment]
Thanks @lpgoldstein

**Comment by jillbong79** [comment]
morning @jennmalcolm 

**Here are the files for the Table of Contents replacement chapters:**
[RRM-Chapter 5.pdf](https://github.com/ONRR/onrr.gov-site/files/4837445/RRM-Chapter.5.pdf)
[RRM-Chapter 7.pdf](https://github.com/ONRR/onrr.gov-site/files/4837448/RRM-Chapter.7.pdf)

**Here are the files for the Supplemental Information section:**
[RRM-Appendix B.pdf](https://github.com/ONRR/onrr.gov-site/files/4837454/RRM-Appendix.B.pdf)
[RRM-Glossary.pdf](https://github.com/ONRR/onrr.gov-site/files/4837455/RRM-Glossary.pdf)

Let me know if you have any questions.  Thank you!  Happy Friday!

**Comment by jennmalcolm** [comment]
Thanks @jillbong79 I will get these files saved. We are still waiting on chapter 4 and appendix E, correct?

**Comment by jillbong79** [comment]
@jennmalcolm you're welcome!  i still have those files coming.  I believe Lydia is finalizing them, and I will load them this evening or Monday morning.  I'm not quite sure when they will be done.  Thanks!  Appreciate ya!

**Comment by jennmalcolm** [comment]
@jillbong79 @sghahn everything we have should be ready and linked to the table of contents if you want to review it here http://2017onrr/ReportPay/Handbooks/revenue-handbook/index.htm. Do you want us to publish what we have now live to onrr.gov or wait until we receive chapter 4 and appendix E?

**Comment by jennmalcolm** [comment]
Also, @jillbong79 and @sghahn will we be receiving the full version of the handbook in one pdf? Glen said he would send that too. If not, I'll remove that link on the main handbook page (http://2017onrr/ReportPay/Handbooks/index.htm).

**Comment by jillbong79** [comment]
@jennmalcolm talking to Glen now.  We don't know the status of 4 or E.  Lydia is supposed to be finishing those today.  Glen says yes to making it live, but we also have an update to Ch. 3.  The full version is a yes, but that won't be available to Tuesday.  Thank you!!

**Comment by jillbong79** [comment]
@jennmalcolm 
i looked over the link and was wondering if it's possible to click on the hyperlink to the document and get a preview of the doc that a person can scroll through, before downloading the document.  if that makes sense.  if we talked about this already, i apologize.  maybe it's an idea we can do later, but if it's possible, i think it would be helpful.  thanks!!

**Comment by jennmalcolm** [comment]
@jillbong79 do you mean for the full document? I think that’s the way it will work just like the rest of the PDFs. We just need the document first to link to. I can reword the link to make it clear that you don’t have to download it. I can change it to “view.”

**Comment by jillbong79** [comment]
@jennmalcolm yes!  that would be great.  thank you!

**Comment by jennmalcolm** [comment]
Ok, I changed it to view, but I also removed the link for now and will add it back when we get the document.

**Comment by sghahn** [comment]
@jennmalcolm and @jillbong79 I am waiting on Glen to reply on the full pdf for the link.

**Comment by sghahn** [comment]
@jennmalcolm and @jillbong79 Glen said he should have it ready by Monday.  He isn't able to complete it until the final chapters are ready and he verifies that the page numbers for Chapter 3 & 4 are correct on the table of contents.

**Comment by jennmalcolm** [comment]
Ok, @jillbong79 @sghahn I am waiting on the updates for chapter 3, and when I receive that, I will get what we have published live. Let me know if that plan doesn't work for you all. Thanks.

**Comment by jillbong79** [comment]
@jennmalcolm that works.  thank you!

**Comment by sghahn** [comment]
Ch. 3 will belong to the (TOC) Table of Contents files. 

[RRM-Chapter 3 Electronic 2014.pdf](https://github.com/ONRR/onrr.gov-site/files/4839342/RRM-Chapter.3.Electronic.2014.pdf)
[RRM-Chapter 3 Paper ONRR FORM-2014 Reporting.pdf](https://github.com/ONRR/onrr.gov-site/files/4839343/RRM-Chapter.3.Paper.ONRR.FORM-2014.Reporting.pdf)

This is the one for the Production handbook...

[Appendix L - Product Codes wc.docx](https://github.com/ONRR/onrr.gov-site/files/4839350/Appendix.L.-.Product.Codes.wc.docx)

The snippet below is the only text change to TOC (Ch. 3 Electronic Reporting), please add the word "Electronic" .
![image](https://user-images.githubusercontent.com/66125889/85903527-c0d65880-b7c3-11ea-9a48-8e6ce19c322c.png)

**Comment by jillbong79** [comment]
@jennmalcolm 

Here is chapter 4 and appendix E.  They have been converted into a pdf.  Please let me know if you need me to do anything to these.  Thanks!
[Chapter 4 (Final Replacement).pdf](https://github.com/ONRR/onrr.gov-site/files/4839755/Chapter.4.Final.Replacement.pdf)
[Appendix E (Final Replacement).pdf](https://github.com/ONRR/onrr.gov-site/files/4839756/Appendix.E.Final.Replacement.pdf)

**Comment by jennmalcolm** [comment]
Thanks @jillbong79 all of the files we have now should be live on onrr.gov now. Do the updates to Chapter 4 require any changes to the table of contents? If so, you can let me know next week, and we can take care of it then.

**Comment by jillbong79** [comment]
@jennmalcolm 

Welcome!  I will ask and let you know.  Appreciate it!  I believe we have 2 more files coming for the production piece in about an hour for Lydia.

**Comment by sghahn** [comment]
These are the final changes to the TOC for Ch. 4...

- 4.6.3, change from "6A9" to "6a9"
- 4.6.6, delete "41" and replace with "55"
- 4.10.1, page # should be 4-93
- 4.12.2, Delete line

![image](https://user-images.githubusercontent.com/66125889/85925341-0db63f80-b855-11ea-821c-670dcafa96f2.png)

Glen is completing the printable handbook now.

**Comment by Maroyafaied** [comment]
Thanks, I'll make those changes.

**Comment by sghahn** [comment]
Thank you Maroya!!

**Comment by sghahn** [comment]
Here is the final printable Minerals Revenue Handbook...

Please let us know if there are any questions.

Thank you for all of your support!!

[RRM-Printable Minerals Revenue Handbook.pdf](https://github.com/ONRR/onrr.gov-site/files/4841319/RRM-Printable.Minerals.Revenue.Handbook.pdf)

**Comment by Maroyafaied** [comment]
Thanks , this is live now. https://www.onrr.gov/ReportPay/Handbooks/index.htm

**Comment by jennmalcolm** [comment]
Thanks, Maroya!

**Comment by sghahn** [comment]
Thank you everyone!
