### ISSUE TITLE
Events                                                                                 (to be added to Event Calendar on Allottee Assistance Page)

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#1710]
**EASTERN OK REGIONAL VIRTUAL MEETING**
THURSDAY, MARCH 24, 2022
1:00 pm to 2:00 pm CST
Location:  By Telephone

DESCRIPTION: This meeting will be a call-in meeting to hear a brief presentation and updates from the Office of Natural Resources Revenue (ONRR) Indian Outreach Office.  Representatives from the Bureau of Land Management (BLM), Bureau of Trust Funds Administration (BTFA), and the Bureau of Indian Affairs (BIA) will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust property issues.  Owners will also have an opportunity to ask questions with the representatives of the four agencies during the Q&A session.

WHO SHOULD ATTEND: IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Eastern regional areas in Oklahoma, including Muskogee, Okmulgee, and Sequoyah counties.    
   
OTHER INFORMATION: To reserve a space and get a passcode for this meeting please contact the ONRR OKC Outreach Office toll-free at (800) 354-7015. The OKC office hours are Mon.- Fri. from 7:30 am-5:00 pm.

CONTACT: ONRR OKC Outreach Office,  PHONE: Toll Free (800) 354-7015
EMAIL: onrroutreachokc@onrr.gov

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 please work on this issue. Thanks

**Comment by daniel-coleman-1** [comment]
@Toddsand21 the requested changes have been implemented in dev:
http://2017onrr/events.htm
with your approval I will push these changes live

**Comment by lpgoldstein** [comment]
@daniel-coleman-1 Did you see the requested changes?

**Comment by Toddsand21** [comment]
Where do I view it?

**Comment by daniel-coleman-1** [comment]
@Toddsand21 edits have been input in dev here:
http://2017onrr/events.htm

with your approval I will push these changes live.

Thanks for the tag, @lpgoldstein

**Comment by Toddsand21** [comment]
Please make the following changes for the paragraph, **Description**: The Office of Natural Resources Revenue (ONRR) will be hosting a virtual (call-in) Outreach Meeting for Indian mineral owners.  (Delete This meeting will be a Call-in Meeting to hear a brief presentation and updates from the Office of Natural Resources Revenue (ONRR) Indian Outreach Office.)  

Also add this as the last sentence for the Description should read....(Please add after Q&A session.)  The meeting will begin with ONRR staff member's brief introduction of the agency representatives that are present.

**Comment by daniel-coleman-1** [comment]
@Toddsand21 can you post your completed final draft here for me to add to the site?

**Comment by Toddsand21** [comment]
EASTERN OK REGIONAL VIRTUAL MEETING
THURSDAY, MARCH 24, 2022
1:00 pm to 2:00 pm CST
Location:  By Telephone

DESCRIPTION: The Office of Natural Resources Revenue (ONRR) will be hosting a virtual (call-in) Outreach Meeting for Indian mineral owners.  Representatives from the Bureau of Land Management (BLM), Bureau of Trust Funds Administration (BTFA), and the Bureau of Indian Affairs (BIA) will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts, and Indian Trust property issues.  There will be a Q&A session for owners to ask questions.  The meeting will begin with the ONRR representative giving a brief introduction of agency representatives present.

WHO SHOULD ATTEND:  Indian mineral owners, IIM account holders and other Indian Trust property owners in the Eastern Regional areas in Oklahoma, including Muskogee, Okmulgee, Creek, and Wagoner counties. 
  
OTHER INFORMATION: To reserve a space and get a passcode for this meeting please contact the ONRR OKC Outreach Office toll-free at (800) 354-7015. The OKC office hours are Mon.- Fri. from 7:30 am-5:00 pm.

CONTACT: ONRR OKC Outreach Office,  PHONE: Toll Free (800) 354-7015
EMAIL: onrroutreachokc@onrr.gov

**Comment by daniel-coleman-1** [comment]
Thanks @Toddsand21, edits have been input in dev here:
http://2017onrr/events.htm

with your approval I will push these changes live.

**Comment by Toddsand21** [comment]
I never received an email that you had updated it.  I cannot see any new updates.  Is there someway to give me the new updated version>

**Comment by daniel-coleman-1** [comment]
@Toddsand21 you can view the page with the following link:
http://2017onrr/events.htm

Do we need to get you access to the dev site?

**Comment by Toddsand21** [comment]
It looks fine and ready to post.

**Comment by daniel-coleman-1** [comment]
@Toddsand21 fantastic, we are live:
https://onrr.gov/events.htm
