### ISSUE TITLE
Updates to civil penalty page

### ISSUE THREAD

**Issue by KristianL3101** [ONRR/onrr.gov-site#1718]
Please update page: https://onrr.gov/compliance/civil-penalties.htm    

Under "Penalty Collections by Fiscal Year" please delete FY2016 and replace with the attached 2021. Also please update "Historical Penalty Collections" Link with the new one attached. Thank you.

[2021.pdf](https://github.com/ONRR/onrr.gov-site/files/8235400/2021.pdf)
[Penalty Collections.pdf](https://github.com/ONRR/onrr.gov-site/files/8235402/Penalty.Collections.pdf)
.

**Comment by daniel-coleman-1** [comment]
@KristianL3101 updates have been entered into dev:
http://2017onrr/compliance/civil-penalties.htm

with your approval I will push these changes live

**Comment by KristianL3101** [comment]
Yes. Thank you.

Kristian Lee
Enforcement Specialist
ONRR/OE Litigation Support
Denver Federal Center, Bldg 85/B76
PO Box 25165 MS 64200B
Denver, CO  80225-0165
(303) 231-3101

________________________________
From: daniel-coleman-1 ***@***.***>
Sent: Friday, March 11, 2022 1:33 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Lee, Kristian H ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Updates to civil penalty page (Issue #1718)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@KristianL3101<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKristianL3101&data=04%7C01%7Ckristian.lee%40onrr.gov%7C8d0a85133222402997b408da039e7079%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637826276709631014%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FzsYLFtOhIaMsK2VAL1DJNLJM1CQ%2Fc6mDrsTMmdbVQo%3D&reserved=0> updates have been entered into dev:
http://2017onrr/compliance/civil-penalties.htm

with your approval I will push these changes live

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1718%23issuecomment-1065496489&data=04%7C01%7Ckristian.lee%40onrr.gov%7C8d0a85133222402997b408da039e7079%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637826276709631014%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TWotMDzI%2BA3VS3Uz2X4cZb8adxz%2FU68MaaSrJuPTtQ8%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYEDRGH6VFMUZRTLHKJE3LLU7OUZZANCNFSM5QQTMYEA&data=04%7C01%7Ckristian.lee%40onrr.gov%7C8d0a85133222402997b408da039e7079%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637826276709631014%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TsVGHFgePkovhyusHZLg8BfKSUZfNX9j6Ru6xteMTjU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckristian.lee%40onrr.gov%7C8d0a85133222402997b408da039e7079%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637826276709631014%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Wg7HdTb9HQSVbMgxNwIITV0HX%2BdTv7aYwgWh85fwZOU%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckristian.lee%40onrr.gov%7C8d0a85133222402997b408da039e7079%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637826276709631014%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xgHBnHhFOBD%2FMjfVp48ijSentbNRl46edK4F98NSpRo%3D&reserved=0>.

**Comment by daniel-coleman-1** [comment]
we are live:
https://onrr.gov/compliance/civil-penalties.htm
