### ISSUE TITLE
Update EMARF Links under quick forms on homepage  

### ISSUE THREAD

**Issue by CarlishaWells** [ONRR/onrr.gov-site#172]
The EMARF had been updated to a new version.  Please replace the “old” Electronic MRMSS Access Request Form (EMARF) link on ONRR.GOV page with the following “new” EMARF link: https://bseedev.servicenowservices.com/emarf  

- Please see attached screen shot:

![onrr gov](https://user-images.githubusercontent.com/62393210/82097276-cec29500-96bf-11ea-9159-49641b27041f.PNG)

**Comment by jennmalcolm** [comment]
Waiting on this and #173, #174, #175, #176, #177, #178 to get an updated link.

**Comment by mcharg** [comment]
@CarlishaWells This is updated in dev.  Let me know if it's good to push to production.
http://2017onrr/

**Comment by mcharg** [comment]
@CarlishaWells, @bowlenj approved the changes, so this change is now live.
https://www.onrr.gov/
