### ISSUE TITLE
Organize 508 excel sheet for onrresource 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1721]

**Comment by jkwonatx** [comment]
[ONRResources 508 Compliance.xlsx](https://github.com/ONRR/onrr.gov-site/files/8247740/ONRResources.508.Compliance.xlsx)

**Comment by jkwonatx** [comment]
@Maroyafaied @mcharg I've added the excel for Christina. What's her GH handle? Thank you!

**Comment by mcharg** [comment]
@jkwonatx Christina is @cmathers1 and Carrie is @carrie-anderson. I think they both need to be added to the org to be properly tagged.   I sent them both invites.

**Comment by jkwonatx** [comment]
![Screen Shot 2022-03-14 at 1 48 45 PM](https://user-images.githubusercontent.com/85380376/158240585-a270203c-b603-469d-a035-14a1b6a22794.png)

**Comment by Maroyafaied** [comment]
I added @cmathers1 and @carrie-anderson to the issue, please comment on this issue with status updates so @jkwonatx is aware.  Here is the excel file [ONRResources 508 Compliance.xlsx](https://github.com/ONRR/onrr.gov-site/files/8247740/ONRResources.508.Compliance.xlsx) Thanks

**Comment by jkwonatx** [comment]
@cmathers1 please suggest the times for our next meeting once you have gotten a sense of how long it would take to add the description to the files. 

Please provide a brief description, limiting to the information that would help us understand what it is used for and how it should be categorized. May prove to be a bit tricky, so don't hesitate to reach out. Thank you.

**Comment by carrie-anderson** [comment]
[ONRResources.508.Compliance.xlsx](https://github.com/ONRR/onrr.gov-site/files/8292525/ONRResources.508.Compliance.xlsx)

**Comment by jkwonatx** [comment]
https://miro.com/app/board/uXjVOZY8bT8=/?invite_link_id=923924300917

Link to the miro board for today's meeting. Also have ready the compliance spreadsheet above. Thank you.

**Comment by mcharg** [comment]
Link to the spreadsheet in Teams. https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/ONRR%20508%20Compliance%20Approach%20Team/ONRResources.508.Compliance.xlsx?d=wec83f76fa29249789220c3cd5b92cb2e&csf=1&web=1&e=YRK2r0

**Comment by cmathers1** [comment]
Carrie and I made updates to the spreadsheet.  I had to download and make the updates.  Can someone help us upload it back onto the Github as a version or do I need to upload a new spreadsheet.  We will continue to work  on this.  Thanks!

Sincerely,

Christina

Christina Mathers
Staff Assistant
Director/Deputy Director's Office
Office of Natural Resources Revenue
6th Avenue and Kipling Street Bldg. 85
Denver, Colorado 80225
Phone:  303-231-3429
Cell: 303-503-1315
________________________________
From: jkwonatx ***@***.***>
Sent: Monday, March 14, 2022 1:53 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Mathers, Christina ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Organize 508 excel sheet for onrresource (Issue #1721)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@cmathers1<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcmathers1&data=04%7C01%7Cchristina.mathers%40onrr.gov%7C121b9522506549b3d86e08da05f44893%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637828843994721514%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LBtN8LgBNNfvBHhOVTkb%2BRKbnUhr4OXmCy5Eo6WW0FM%3D&reserved=0> please suggest the times for our next meeting once you have gotten a sense of how long it would take to add the description to the files.

Please provide a brief description, limiting to the information that would help us understand what it is used for and how it should be categorized. May prove to be a bit tricky, so don't hesitate to reach out. Thank you.

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F1721%23issuecomment-1067223881&data=04%7C01%7Cchristina.mathers%40onrr.gov%7C121b9522506549b3d86e08da05f44893%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637828843994721514%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dlCq%2B3EEjPGW%2BirrUBj6e8ojFL4Y7sDKo95rAYPCiPc%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAU5GF7RHAXXAKY5GW7DPT43U76KKPANCNFSM5QWLLY4A&data=04%7C01%7Cchristina.mathers%40onrr.gov%7C121b9522506549b3d86e08da05f44893%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637828843994721514%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PAiHSeYX3RabxV3%2BHeuWzmstRH0YwCam14YZt0z2J%2Bg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cchristina.mathers%40onrr.gov%7C121b9522506549b3d86e08da05f44893%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637828843994721514%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1C3xbVBPOlJ05EFGKmMGRZZJe4mxjfUYR2xJdcnC5HE%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cchristina.mathers%40onrr.gov%7C121b9522506549b3d86e08da05f44893%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637828843994721514%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YxtQsxx2yNZCsayA6ETqv2rWXnDSva1t0wDOsYvm6Fk%3D&reserved=0>.

**Comment by Maroyafaied** [comment]
@cmathers1 Is this the spreadsheet that lives on onrresource? If it is, then you will need to ask Christa Mcurdy's team to upload the new version.  Feel free to chat or call me if I'm not understanding correctly :) and Thank you for keeping up and updating these resources!
