### ISSUE TITLE
Upload non pdf docs and tag appropriately 

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/onrr.gov-site#1726]

**Comment by lpgoldstein** [comment]
Reporter Training

- [ ] WebCenter Portal

- [ ] WebCenter Portal User Guide
- [ ] Basic Leases and Agreements
- [ ] Overlapping Agreements
- [ ] ONRR-4054 Oil and Gas Operations Report   (OGOR)
- [ ] OGOR Comma Separated Value (CSV)   Reporting
- [ ] Production Reporting for   eCommerce and Electronic Tools
- [ ] Edit 11030 Inventory Error
- [ ] OGOR Reporting Errors
- [ ] Liquid Verification System (LVS) and Gas   Verification System (GVS)
- [ ] LVS-GVS Presentation
- [ ] Facility Measurement Points (FMP)
- [ ] How to Save your OGOR Reports
- [ ] Indian Adjustments and Recoupments
- [ ] Federal Adjustments
- [ ] Form-2014 Basic Reporting Principles
- [ ] Report of Sales and Royalty Remittance   (FORM-ONRR 2014)
- [ ] Royalty Reporting for eCommerce   and Electronic Tools
- [ ] Commonly Used 2014 Transaction Codes
- [ ] 2014 Reporting Errors
- [ ] Solid Minerals Reporter Opening, Form   4444, Payor Codes, and EMARF
- [ ] Solid Mineral Leases, Sales Summary,   Sales Contracts & Facility Data, Handbook
- [ ] Form ONRR-4430 (P&R)
- [ ] Solid Minerals Compliance Processes
- [ ] Solids Enforcement
- [ ] Solids Billing
- [ ] Solids   AR Basics
- [ ] Solids   Audit
- [ ] Solids Valuation Sodium and Potassium

**Comment by lpgoldstein** [comment]
Other 

Geothermal 
- [ ] Form ONRR-2014 Geothermal Codes

Payment Options
- [ ] Indian Distributee Codes

Reference Lists and Codes

- [ ] Cross-Reference Lease to Agreement Number

**Comment by cthomasONRR** [comment]
@lpgoldstein Thanks!!! I will hopefully have these all reviewed by tomorrow morning at the latest.

**Comment by cthomasONRR** [comment]
@lpgoldstein I checked all documents in those CMS page locations, and all look good with tags!

I also checked the pdfs folder to make sure there weren't any documents without tags, and I'm still seeing the 'Solids_Opening.pptx" document we chatted about yesterday there without tags. So I added it to the Reporter Training page and added tags. Let me know if you can see those changes. Other than that one, everything looks good!

We need to have a discussion with the developers to:

1. See if they have any preference for there to be spacing in tags with multiple words (ex: "TrainingPresentations" versus "Training Presentations"), and
2. See how labor-intensive it would be for them to add functionality that would allow us to bulk edit a tag (ex: change all the "TrainingPresentations" to "Training Presentations").

**Comment by cthomasONRR** [comment]
@lpgoldstein Great, let's bring up tagging at stand up today. I think this issue can be closed.
