### ISSUE TITLE
Convert "Tab" to "Tabs" in CMS

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/onrr.gov-site#1728]

**Comment by mcharg** [comment]
@Maroyafaied Can I take this one? I'll be removing a bunch of these links as part of updating the contact pages to match the prototype, so might as well look at them all.

**Comment by mcharg** [comment]
@lpgoldstein Can you check all the links from the Paying home page to the payment options tabs? Maroya missed those and I had to edit them each manually, so there's definitely room for error. https://dev-onrr-frontend.app.cloud.gov/paying

**Comment by mcharg** [comment]
@Maroyafaied I found a few you missed and added them. Approving.
