### ISSUE TITLE
Links to reporter letters and press releases are broken

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1732]
See #1384 for details.

**Comment by mcharg** [comment]
@mcharg everything looks good except these links don't work, I fixed the links in the announcement for Indian outreach & the mineral owners link. 
![image](https://user-images.githubusercontent.com/40175688/158898469-7c2b0afb-1343-48a4-b8c9-9d077652756e.png)

_Originally posted by @Maroyafaied in https://github.com/ONRR/onrr.gov-site/issues/1384#issuecomment-1071519069_

**Comment by mcharg** [comment]
The links to those docs on the Reporter Letters and Press Releases pages are also broken. I looked in the CMS and the docs are there.  @jlouis-onrr @mojobnichols Any idea what's going on? Those links did work at one point.

_Originally posted by @mcharg in https://github.com/ONRR/onrr.gov-site/issues/1384#issuecomment-1072370732_

**Comment by mcharg** [comment]
We also want them to have the nice urls.

**Comment by jlouis-onrr** [comment]
@mcharg, the link updates and nice urls are now in dev.

**Comment by mcharg** [comment]
@jlouis-onrr Looks great!

The only issue I'm noticing is on the one with the accessible docx, clicking both links opens the pdf and I can't open the docx.
![image](https://user-images.githubusercontent.com/38465926/160129353-314a5f9b-1f0d-4890-bc47-2741f78c5fb5.png)
