### ISSUE TITLE
Links to historical rulemakings are broken

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1738]
They used to work.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/47faa657-f0e5-403c-a148-40c83bcf6a5d)

**Comment by jlouis-onrr** [comment]
looks like the domain is wrong in the links:

working link:
https://dev-onrr-frontend.app.cloud.gov/references/rulemakings?topic=Federal%20Oil

non-working link:
https://dev-onrr-cms.app.cloud.gov/references/rulemakings?topic=Federal%20Oil

**Comment by cthomasONRR** [comment]
@mcharg Sure

**Comment by cthomasONRR** [comment]
@mcharg @jlouis-onrr Links are fixed!

**Comment by mcharg** [comment]
@cthomasONRR I reviewed and they look good. This is good to close.
