### ISSUE TITLE
Unable to create a new page without attaching a document

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1739]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/e558507e-6969-4fdd-a631-aee18b80517b)

**Comment by jlouis-onrr** [comment]
turned off validation for 'file_name' field

**Comment by mcharg** [comment]
@cthomasONRR You were able to create a page without attaching a file? Can we close this?

**Comment by cthomasONRR** [comment]
@mcharg Yep!
