### ISSUE TITLE
Add contacts survey and troubleshooting study to GitHub

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1740]
Will need to link to them from the troubleshooting blog post.

**Comment by lpgoldstein** [comment]
@mcharg ready for your review

**Comment by mcharg** [comment]
@lpgoldstein Contacts survey looks good. Are you going to add the ones from the troubleshooting guide as part of this issue or do that separately?

**Comment by lpgoldstein** [comment]
@mcharg do you have a preference? Now thinking together is better?
