### ISSUE TITLE
Fix debt collection solids contacts

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1744]
Participant pointed out inaccuracies with the solids contacts, which we need to fix. Can drop the solids line, repetitive (?), MA### contacts are solids so no need for an additional solids line item

**Comment by cthomasONRR** [comment]
@mcharg Should I add in their email addresses to the ContactsFIles excel?

**Comment by mcharg** [comment]
@cthomasONRR Sure.

**Comment by cthomasONRR** [comment]
@mcharg I added all emails except for Yoo Na Conrad and Sharon Weddle... I looked them up in Teams, Address Book, and onrr resource's new dynamic org chart (https://oep.onrr.local/Reports/OrgChart)... they are not listed anywhere. Have they left onrr? Maybe we need to check in with SMEs to make sure they are the correct contact.

**Comment by mcharg** [comment]
Yeah, we should figure out who gives us that contact file and ask if they have updates.

**Comment by cthomasONRR** [comment]
@mcharg I'd say contact Rebecca Dyess for an update... looks like it hasn't been updated since October 2019

**Comment by cthomasONRR** [comment]
Email sent to Rebecca Dyess:

"Hi Rebecca,

My name is Christine Thomas with ONRR’s Open Data, Design, and Development (ODDD) team. As you likely know, our team is working to redesign onrr.gov. Part of this redesign includes keeping all the ONRR contacts up to date. 

We are working on the Debt Collection - Company Assignments contacts (attached, and located here: https://www.onrr.gov/about/contact.htm), and noticed that we can’t find Yoo Na Conrad and Sandra Weddle in any ONRR directory. We were wondering if you could let us know if this contact list needs to be updated. We will be happy to get an updated contact list on the website for you.

Thanks for your time,

Christine Thomas"

**Comment by cthomasONRR** [comment]
Rebecca's response:

"Hello Christine,

Thank you so much for reaching out about updating the contacts for Debt Collection.  Yoo Na Conrad is no longer working with ONRR, and her replacement is Tiffany Mamayev .  Tiffany can be reached at 303-231-3758, [tiffany.mamayev@onrr.gov](mailto:tiffany.mamayev@onrr.gov).   Sharon Weddle has retired and has been recently replaced with Tammy C Johnson.  Tammy can be reached at 303-231-3680, [tammy.johnson@onrr.gov](mailto:tammy.johnson@onrr.gov).

Thank you again.  Please let me know if you have any additional questions.

Rebecca Dyess"

@mcharg I made these updates in the ContactsFiles spreadsheet. Should I ask her to update her excel that's online, or do you think it's ok for me to update?? I can make that update and get it online tomorrow.

**Comment by cthomasONRR** [comment]
Rebecca gave me permission to update the excel that's online. The updates have been made and the update excel is live: https://www.onrr.gov/about/contact.htm
![image](https://user-images.githubusercontent.com/72526208/159798408-7f526d9c-fd64-4254-9d75-7199ea93ddab.png)

**Comment by cthomasONRR** [comment]
@mcharg I think we're good to close this now
