### ISSUE TITLE
2014 CSV and ASCII file

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#1746]
Please replace the sample layouts for the CSV and ASCII record layout for the Form ONRR-2014 with the attached files.
https://onrr.gov/reportpay/royalty-reporting.htm#contacts

Thank you!

[_ASC2014Rev20220401.pdf](https://github.com/ONRR/onrr.gov-site/files/8335897/_ASC2014Rev20220401.pdf)
[_CSV2014Rev20220401.pdf](https://github.com/ONRR/onrr.gov-site/files/8335898/_CSV2014Rev20220401.pdf)

**Comment by Maroyafaied** [comment]
@lpgoldstein please also tag these documents with the "update" tag in the CMS.

**Comment by lpgoldstein** [comment]
@merrellc The first document needs to have the table summary corrected on the first page. Please correct and then I'll update. Thanks! Lindsay 
![image](https://user-images.githubusercontent.com/39419003/159794900-6833e26b-a5cb-4f4f-acec-5e8640aecec0.png)

**Comment by lpgoldstein** [comment]
[_ASC2014Rev20220401.pdf](https://github.com/ONRR/onrr.gov-site/files/8342728/_ASC2014Rev20220401.pdf)
revised document

**Comment by lpgoldstein** [comment]
@merrellc this is ready for your review! http://2017onrr/reportpay/royalty-reporting.htm

**Comment by merrellc** [comment]
Great! Thank you!


Kind Regards,
​Candace Merrell
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.
________________________________
From: lpgoldstein ***@***.***>
Sent: Thursday, March 24, 2022 9:21 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] 2014 CSV and ASCII file (Issue #1746)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@merrellc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmerrellc&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C40dd861a18c3413c977a08da0daa041c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637837321104092145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OhSS0eVmFidwwmmH2hHdgroVvM5zZJF4DXZYXB5nKE4%3D&reserved=0> this is ready for your review! http://2017onrr/reportpay/royalty-reporting.htm

**Comment by merrellc** [comment]
Ready to go live.


Kind Regards,
​Candace Merrell
Minerals Revenue Specialist - Staff Analyst
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.
________________________________
From: lpgoldstein ***@***.***>
Sent: Thursday, March 24, 2022 9:21 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] 2014 CSV and ASCII file (Issue #1746)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@merrellc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmerrellc&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C40dd861a18c3413c977a08da0daa041c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637837321104092145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OhSS0eVmFidwwmmH2hHdgroVvM5zZJF4DXZYXB5nKE4%3D&reserved=0> this is ready for your review! http://2017onrr/reportpay/royalty-reporting.htm

**Comment by lpgoldstein** [comment]
@merrellc It's live! https://onrr.gov/reportpay/royalty-reporting.htm

**Comment by mcharg** [comment]
Files updated in CMS.
