### ISSUE TITLE
Production Reporting Updates

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1747]
Please update the following page with the attached updated forms - https://www.onrr.gov/reportpay/production-reporting.htm

[4054-c 20220401.pdf](https://github.com/ONRR/onrr.gov-site/files/8336045/4054-c.20220401.pdf)
[4058 20220401.pdf](https://github.com/ONRR/onrr.gov-site/files/8336046/4058.20220401.pdf)
[OGOR-Reporting-Instructions-ASCII-Format 20220401.pdf](https://github.com/ONRR/onrr.gov-site/files/8336047/OGOR-Reporting-Instructions-ASCII-Format.20220401.pdf)
[OGOR-Reporting-Instructions-CSV-Format 20220401.pdf](https://github.com/ONRR/onrr.gov-site/files/8336048/OGOR-Reporting-Instructions-CSV-Format.20220401.pdf)
[PASR_CSV_Record_Layout_20220401.pdf](https://github.com/ONRR/onrr.gov-site/files/8336051/PASR_CSV_Record_Layout_20220401.pdf)
[_ASCpasrRev20220401.pdf](https://github.com/ONRR/onrr.gov-site/files/8336052/_ASCpasrRev20220401.pdf)
[4054-a 20220401.pdf](https://github.com/ONRR/onrr.gov-site/files/8336053/4054-a.20220401.pdf)
[4054-b 20220401.pdf](https://github.com/ONRR/onrr.gov-site/files/8336055/4054-b.20220401.pdf)

Please let me know if you have any questions.

**Comment by Maroyafaied** [comment]
@cthomasONRR can you please make these updates and tag these documents in CMS to be updated. Thanks

**Comment by cthomasONRR** [comment]
@bowlenj Good afternoon,
These 8 documents are now updated on the dev site: http://2017onrr/reportpay/production-reporting.htm. Please review and give us your approval to go live.

@Maroyafaied I tagged all 8 documents with 'Update' in the CMS.

**Comment by bowlenj** [comment]
This looks great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, March 23, 2022 2:02 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Production Reporting Updates (Issue #1747)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C2bbe99c5995445010fd808da0d0834d1%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637836626165086965%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=e6KNEv5Cuomf6CdRMaJtMpsrUkEic%2BJDjEtxWgmz7tM%3D&reserved=0> Good afternoon,
These 8 documents are now updated on the dev site: http://2017onrr/reportpay/production-reporting.htm. Please review and give us your approval to go live.

@Maroyafaied<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMaroyafaied&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C2bbe99c5995445010fd808da0d0834d1%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637836626165086965%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=607SegxmGSkuBPdaDqHNIix2EBm0c1qgDr7d6JvPPNY%3D&reserved=0> I tagged all 8 documents with 'Update' in the CMS.

**Comment by cthomasONRR** [comment]
@bowlenj Great, these changes are now live: https://www.onrr.gov/reportpay/production-reporting.htm. Remember to use 'Ctrl+F5' to refresh the page. Closing this issue. Thanks, Christine

**Comment by mcharg** [comment]
Files updated in CMS.
