### ISSUE TITLE
Check accessibility on uploaded docs

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1748]
We have 626 unique docs.  Run accessibility checks to make sure we have no errors being added to the new site.

**Comment by cthomasONRR** [comment]
**Documents on Y:\PDFDocs not found in tracking sheet:**

- [ ] ONRR_External_User_Acceptable_Use_Policy.pdf (Accessible)
- [ ] All States GOMESA Release 3.30.pdf (Table Errors)
- [ ] 2020_GOMESA_States.pdf (Table Errors)
- [ ] 2020_Disbursements_States.pdf (Table & Alt Text Errors)

**Documents on Y:\compliance\PDFDocs not found in tracking sheet:**

- [ ] 2016.pdf (Table Errors) likely not needed on the new site

**Documents on Y:\IndianServices\pdfdocs not found in tracking sheet:**

- [ ] Calendar-Year-2021-DistDates (Table & Page Content Errors) likely not needed on the new site

**Comment by mcharg** [comment]
@cthomasONRR The first one is in the sheet. Sort ID 333.

The two GOMESA and Disbursements ones are probably in press releases somewhere.

2016 - we removed that one because they only want the most recent 5 years on the site.

Cal year 21 dist dates was replaced by a 2022 file.

**Comment by cthomasONRR** [comment]
@mcharg I removed all filters and found ONRR_External_User_Acceptable_Use_Policy.pdf. It was set as secondary, so I change it to primary. I can't find the GOMESA and Disbursement docs anywhere though.

**Comment by cthomasONRR** [comment]
Found "All States GOMESA Release 3.30.pdf"... the one instance was marked as Secondary, so I changed that to Primary

**Comment by cthomasONRR** [comment]
I checked the spreadsheet, and I think we can close this issue :)
