### ISSUE TITLE
Press releases search doesn't work

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1751]
I was looking for a press release in 2011 with "Carlsbad" in the title, but it didn't filter at all when searching regardless of year selected.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/e93d0846-332a-4cd3-89d7-0eecf415e575)

**Comment by jlouis-onrr** [comment]
@mcharg, yes, I can add that.

**Comment by jlouis-onrr** [comment]
@mcharg, selection for all years is in dev.
