### ISSUE TITLE
Request a 508-compliant version of latest Dear Reporter Letter

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1752]
We are checking to make sure documents are 508 compliant. The latest Dear Reporter Letter (https://www.onrr.gov/PDFDocs/Dear.Reporter.Letter.File.Structure.Change.pdf) was uploaded via GitHub Issue #1556 (https://github.com/ONRR/onrr.gov-site/issues/1566). A 508 compliance check was not done, and it was uploaded with accessibility errors. Since @daniel-coleman-1 had the pervious issue (#1556), please contact the person who submitted this issue and request a 508-compliant version of the Dear Reporter Letter.

**Comment by Maroyafaied** [comment]
Taking this issue since @daniel-coleman-1 is out.

**Comment by bowlenj** [comment]
Please find attached the unsigned accessible copy of Dear Reporter Letter File Structure Change.  Please add this to the following page, below the existing letter and identify as accessible copy.  We want to keep the signed version up as well.
[Dear Reporter Letter - File Changes MLRS_01242022 unsigned.pdf](https://github.com/ONRR/onrr.gov-site/files/8418212/Dear.Reporter.Letter.-.File.Changes.MLRS_01242022.unsigned.pdf)

**Comment by Maroyafaied** [comment]
This is an accessible version, I will upload it in the current site and in the cms.

[Dear Reporter Letter - File Changes MLRS_01242022 unsigned (1) (1).pdf](https://github.com/ONRR/onrr.gov-site/files/8418680/Dear.Reporter.Letter.-.File.Changes.MLRS_01242022.unsigned.1.1.pdf)

**Comment by Maroyafaied** [comment]
@mcharg I added the two version to the docs tab but not sure what to put in the sort column, can you review I did this correctly. Thanks

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/6beb48c9-97f0-4f97-b1f9-16a293acb42a)

**Comment by mcharg** [comment]
@Maroyafaied Looks good. I need to redo the sort order anyway.  I'll move them up with the other reporter letters and then update the sort order.
