### ISSUE TITLE
Strategy for non-accessible docs

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1753]

**Comment by mcharg** [comment]
Status for top 100 docs.
**Rank**|**FY21 Downloads**|**% of Total**|**Cumulative %**|**Accessibility**|**URL**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
1|1740|8.03%|8.03%|Pass|https://www.onrr.gov/ReportPay/PDFDocs/ALwState.xlsx
2|1158|5.34%|13.37%|Pass|https://www.onrr.gov/reportpay/PDFDocs/2014.pdf
3|886|4.09%|17.46%|Pass|https://www.onrr.gov/reportpay/PDFDocs/CRLNumber.xlsx
4|715|3.30%|20.76%|Pass|https://www.onrr.gov/reportpay/PDFDocs/ONRR4444.pdf
5|617|2.85%|23.60%|Pass|https://www.onrr.gov/ReportPay/PDFDocs/4054-a.pdf
6|573|2.64%|26.25%|Pass|https://www.onrr.gov/PDFDocs/dear-reporter-letter-30-june-2020.pdf
7|523|2.41%|28.66%|Pass|https://www.onrr.gov/reportpay/handbooks/pdfdocs/RRM-Printable.Minerals.Revenue.Handbook.pdf
8|449|2.07%|30.73%|N/A|https://www.onrr.gov/ReportPay/PDFDocs/XREF.txt
9|383|1.77%|32.50%|Pass|https://www.onrr.gov/ReportPay/PDFDocs/ONRR4444\_Instructions.pdf
10|334|1.54%|34.04%|#N/A|https://www.onrr.gov/reportpay/Handbooks/pdfdocs/MPRH-Table-of-Contents.pdf
11|328|1.51%|35.55%|Pass|https://www.onrr.gov/ReportPay/PDFDocs/Paygov--Royalty-Invoice\_Form.pdf
12|314|1.45%|37.00%|Table Errors|https://www.onrr.gov/reportpay/PDFDocs/Codes\_for\_2014.pdf
13|313|1.44%|38.44%|Pass|https://www.onrr.gov/ReportPay/PDFDocs/4054-b.pdf
14|290|1.34%|39.78%|Pass|https://www.onrr.gov/valuation/PDFDocs/Example-processed-gas-plant-statement-03102020.pdf
15|270|1.25%|41.03%|Pass|https://www.onrr.gov/PDFDocs/ONRR\_External\_User\_Acceptable\_Use\_Policy.pdf
16|239|1.10%|42.13%|Pass|https://www.onrr.gov/reportpay/Handbooks/pdfdocs/MPRH-Appendix-I.pdf
17|232|1.07%|43.20%|#N/A|https://www.onrr.gov/about/pdfdocs/ONRR\_External\_Org\_Chart.pdf
18|220|1.01%|44.21%|Pass|https://www.onrr.gov/reportpay/PDFDocs/ACHInst.pdf
19|203|0.94%|45.15%|Pass|https://www.onrr.gov/reportpay/handbooks/pdfdocs/MPRH-Chapter-5.pdf
20|202|0.93%|46.08%|Pass|https://www.onrr.gov/ReportPay/PDFDocs/Industry.WebCenter.Portal.User.Guide.pptx
21|194|0.89%|46.98%|Pass|https://www.onrr.gov/ReportPay/PDFDocs/CSV2014Rev.pdf
22|191|0.88%|47.86%|Pass|https://www.onrr.gov/valuation/pdfdocs/Indian\_Gas\_Index\_Zone\_Map.pdf
23|185|0.85%|48.71%|Table Errors|https://www.onrr.gov/reportpay/PDFDocs/fedwire.pdf
24|171|0.79%|49.50%|Pass|https://www.onrr.gov/ReportPay/PDFDocs/4054-c.pdf
25|167|0.77%|50.27%|Table Errors|https://www.onrr.gov/ReportPay/Handbooks/revenue-handbook/pdfs/RRM-Chapter.4.pdf
26|164|0.76%|51.03%|Pass|https://www.onrr.gov/reportpay/PDFDocs/Form\_CMP2014\_Industry\_FAQ.pdf
27|164|0.76%|51.79%|Other Errors|https://www.onrr.gov/ReportPay/Forms/SamExcel2014csv.xls
28|159|0.73%|52.52%|Other Errors|https://www.onrr.gov/unbundling/pdf/How-to-calculate-a-Transportation-UCA.pdf
29|156|0.72%|53.24%|Table Errors|https://www.onrr.gov/valuation/PDFDocs/Processed%20Gas%20Example%20Final%2005262020.pdf
30|155|0.72%|53.95%|Pass|https://www.onrr.gov/ReportPay/PDFDocs/FCIL.xlsx
31|154|0.71%|54.66%|#N/A|https://www.onrr.gov/unbundling/pdf/Ignacio-UCA-Table-20180208.pdf
32|147|0.68%|55.34%|Pass|https://www.onrr.gov/ReportPay/PDFDocs/ASC2014Rev.pdf
33|146|0.67%|56.02%|Pass|https://www.onrr.gov/ReportPay/Handbooks/revenue-handbook/pdfS/RRM-Chapter.2.pdf
34|146|0.67%|56.69%|Pass|https://www.onrr.gov/ReportPay/PDFDocs/OGOR-REPORTING-INSTRUCTIONS-CSV-FORMAT.pdf
35|143|0.66%|57.35%|Table Errors|https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MPRH-Chapter-2.pdf
36|141|0.65%|58.00%|Pass|https://www.onrr.gov/reportpay/PDFDocs/Questions2014.pdf
37|137|0.63%|58.63%|Pass|https://www.onrr.gov/ReportPay/Forms/SamExcelOGORcsv.xls
38|136|0.63%|59.26%|Other Errors|https://www.onrr.gov/PDFDocs/20141218.pdf
39|127|0.59%|59.84%|Table Errors|https://www.onrr.gov/compliance/PDFDocs/2019.pdf
40|127|0.59%|60.43%|Other Errors|https://www.onrr.gov/ReportPay/PDFDocs/4425.pdf
41|126|0.58%|61.01%|Table Errors|https://www.onrr.gov/compliance/PDFDocs/2020.pdf
42|126|0.58%|61.59%|Other Errors|https://www.onrr.gov/pdfdocs/FY2020\_Disbursements\_National\_Press\_Release.pdf
43|125|0.58%|62.17%|Table Errors|https://www.onrr.gov/ReportPay/PDFDocs/2014CLEdits.pdf
44|125|0.58%|62.75%|Pass|https://www.onrr.gov/about/PDFDocs/Dear-Reporter-Letter\_OGOR\_4.9.2018.pdf
45|123|0.57%|63.31%|Table Errors|https://www.onrr.gov/reportpay/PDFDocs/4109.pdf
46|120|0.55%|63.87%|Pass|https://www.onrr.gov/reportpay/PDFDocs/TranCodes.pdf
47|115|0.53%|64.40%|Pass|https://www.onrr.gov/reportpay/Handbooks/pdfdocs/MPRH-List-of-Examples.pdf
48|111|0.51%|64.91%|Pass|https://www.onrr.gov/ReportPay/PDFDocs/Interest\_Calculator\_Master.xlsx
49|111|0.51%|65.42%|Pass|https://www.onrr.gov/unbundling/pdf/How-to-calculate-a-Processing-UCA.pdf
50|100|0.46%|65.88%|Table Errors|https://www.onrr.gov/pdfdocs/2020\_GOMESA.pdf
51|97|0.45%|66.33%|Table Errors|https://www.onrr.gov/ReportPay/Handbooks/revenue-handbook/pdfs/RRM-Appendix.C.pdf
52|94|0.43%|66.77%|Table Errors|https://www.onrr.gov/reportpay/handbooks/pdfdocs/SMRH.Complete.Handbook.pdf
53|92|0.42%|67.19%|Table Errors|https://www.onrr.gov/unbundling/pdf/Echo\_Springs\_UCA\_Table\_w\_Example\_Correction\_2018.2.1.pdf
54|91|0.42%|67.61%|Pass|https://www.onrr.gov/unbundling/pdf/Versado.Saunders.Gas.Plant.UCA.pdf
55|91|0.42%|68.03%|Table Errors|https://www.onrr.gov/compliance/PDFDocs/2018.pdf
56|90|0.42%|68.44%|Pass|https://www.onrr.gov/ReportPay/PDFDocs/OGOR-REPORTING-INSTRUCTIONS-ASCII-FORMAT.pdf
57|90|0.42%|68.86%|#N/A|https://onrr.gov/ReportPay/PDFDocs/ONRR4444.pdf
58|87|0.40%|69.26%|Pass|https://www.onrr.gov/unbundling/pdf/DRL\_Transportation\_Systems\_and\_Processing\_Plants\_October\_6\_2010.pdf
59|85|0.39%|69.65%|Pass|https://www.onrr.gov/PDFDocs/20150515.pdf
60|85|0.39%|70.05%|Pass|https://www.onrr.gov/reportpay/Handbooks/pdfdocs/MPRH-Appendix-L.pdf
61|85|0.39%|70.44%|Pass|https://www.onrr.gov/reportpay/Handbooks/pdfdocs/MPRH-Appendix-H.pdf
62|85|0.39%|70.83%|Table Errors|https://www.onrr.gov/unbundling/pdf/Neptune-UCA-Tables-2008-2015-with-Example.pdf
63|84|0.39%|71.22%|Table Errors|https://www.onrr.gov/unbundling/pdf/Meeker-UCA-20170816.pdf
64|83|0.38%|71.60%|#N/A|https://www.onrr.gov/unbundling/pdf/Mobile-Bay-UCA-Example-Updated-FINA-LS-7-8-16-with-table.pdf
65|79|0.36%|71.96%|Pass|https://www.onrr.gov/reportpay/PDFDocs/4410.pdf
66|79|0.36%|72.33%|Table Errors|https://www.onrr.gov/reportpay/PDFDocs/4110.pdf
67|79|0.36%|72.69%|Pass|https://www.onrr.gov/valuation/pdfdocs/Indian\_Oil\_Major\_Portion\_Map.pdf
68|78|0.36%|73.05%|Pass|https://www.onrr.gov/ReportPay/PDFDocs/4058.pdf
69|78|0.36%|73.41%|Pass|https://www.onrr.gov/unbundling/pdf/Chipeta-Plant-Example.pdf
70|77|0.36%|73.77%|Pass|https://www.onrr.gov/reportpay/PDFDocs/fedagmts.xlsx
71|77|0.36%|74.12%|Pass|https://www.onrr.gov/ReportPay/pdfdocs/dispAdj.pdf
72|76|0.35%|74.47%|Pass|https://www.onrr.gov/PDFDocs/ReporterLetter\_KeepwholeGasProcessingContracts.pdf
73|76|0.35%|74.82%|Table Errors|https://www.onrr.gov/PDFDocs/GOMESA.National.Release.pdf
74|76|0.35%|75.18%|Table Errors|https://www.onrr.gov/compliance/PDFDocs/2017.pdf
75|73|0.34%|75.51%|#N/A|https://www.onrr.gov/unbundling/pdf/Sea-Robin-UCA-Table-200-to-2016-with-example.pdf
76|71|0.33%|75.84%|Pass|https://www.onrr.gov/PDFDocs/dear-reporter-letter-20-Nov-19.pdf
77|70|0.32%|76.16%|Table Errors|https://www.onrr.gov/reportpay/Handbooks/pdfdocs/MPRH-Glossary.pdf
78|70|0.32%|76.49%|#N/A|https://www.onrr.gov/Laws\_R\_D/FRNotices/PDFDocs/24794.pdf
79|69|0.32%|76.80%|Table Errors|https://www.onrr.gov/ReportPay/Handbooks/revenue-handbook/pdfs/RRM-Appendix.E.pdf
80|69|0.32%|77.12%|#N/A|https://www.onrr.gov/compliance/PDFDocs/2016.pdf
81|67|0.31%|77.43%|Table Errors|https://www.onrr.gov/unbundling/pdf/Black-Fork-Plant-UCA-Example.pdf
82|67|0.31%|77.74%|Table Errors|https://www.onrr.gov/unbundling/pdf/Willow-Creek-Gas-Plant.pdf
83|65|0.30%|78.04%|Table Errors|https://www.onrr.gov/unbundling/pdf/Opal-UCA-20170816.pdf
84|64|0.30%|78.34%|Pass|https://www.onrr.gov/valuation/pdfdocs/Indian\_Gas\_Major\_Portion\_Map.pdf
85|64|0.30%|78.63%|#N/A|https://www.onrr.gov/unbundling/pdf/Pascagoula-UCAs.pdf
86|63|0.29%|78.92%|Table Errors|https://www.onrr.gov/reportpay/PDFDocs/4295.pdf
87|63|0.29%|79.21%|#N/A|https://www.onrr.gov/unbundling/pdf/Toca-Plant-UCA.pdf
88|63|0.29%|79.50%|Pass|https://www.onrr.gov/unbundling/pdf/Orla.UCA.example.pdf
89|61|0.28%|79.78%|Table Errors|https://www.onrr.gov/unbundling/pdf/Offshore-Standard-UCA-Cryo-Example.pdf
90|60|0.28%|80.06%|#N/A|https://www.onrr.gov/unbundling/pdf/Val\_Verde.pdf
91|59|0.27%|80.33%|Pass|https://www.onrr.gov/reportpay/Handbooks/pdfdocs/MPRH-Chapter-3.pdf
92|58|0.27%|80.60%|Other Errors|https://www.onrr.gov/about/PDFDocs/20160913.pdf
93|58|0.27%|80.87%|Pass|https://www.onrr.gov/unbundling/pdf/Williams\_Torre\_Alta\_Transportation\_System\_Kutz\_Plant.pdf
94|57|0.26%|81.13%|Pass|https://www.onrr.gov/reportpay/PDFDocs/4430.pdf
95|57|0.26%|81.39%|Pass|https://www.onrr.gov/reportpay/PDFDocs/4435.pdf
96|57|0.26%|81.66%|Pass|https://www.onrr.gov/ReportPay/PDFDocs/Paygov--ROW-RUE-Rent\_Form.pdf
97|56|0.26%|81.92%|Pass|https://www.onrr.gov/ReportPay/Handbooks/revenue-handbook/pdfs/RRM-Appendix.F.pdf
98|56|0.26%|82.17%|Table Errors|https://www.onrr.gov/unbundling/pdf/Venice-UCA-Example.pdf
99|54|0.25%|82.42%|Table Errors|https://www.onrr.gov/PDFDocs/Dear-Reporter-Letter-2016-Rule.pdf
100|54|0.25%|82.67%|Pass|https://www.onrr.gov/unbundling/pdf/UCA-calculations-Engineering-Data-Needs.pdf

**Comment by cthomasONRR** [comment]
@mcharg I'm looking at instances other than table errors where I was in charge of the GitHub issue.

- [ ] For 4425.pdf (row 37 in the table), I'm not sure what happened. Luis emailed a 508-compliant version that passed, but now when I run it, it no longer passes.
- [ ] For 930202.pdf (row 331 in the table), The GitHub issue has the 508 compliant doc, it just doesn't seem to have transferred over. I can pull the compliant version to the live site now.
- [ ] For the PowerPoints, the 'Check reading order' is a warning, not a true fail. I thought we were OK to accept these. Apologies if I misunderstood.

**Comment by mcharg** [comment]
@cthomasONRR For the PPT warnings, if they're easy to correct, like reading order and duplicate slide title, they should be fixed. It's the more difficult warnings that can't be cleared that we'll accept.

**Comment by cthomasONRR** [comment]
@mcharg Ok apologies, that information was definitely lost on me.  

I updated 930202.pdf on the Z drive... looks like it made it to the Y but I missed pulling it over to Z. Honestly surprised I didn't do this more with the bulk updates lol.

**Comment by cthomasONRR** [comment]
@mcharg I found a compliant version of the 4425.pdf... I will upload it to the Y and Z drives right now. Luis had sent at least 2 versions and looks like I accidentally uploaded the wrong one.

**Comment by mcharg** [comment]
Breakdown of table errors by team.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/9eabd4ee-57e6-4824-867d-d4c253e42391)

**Comment by mcharg** [comment]
Breakdown of non-table errors.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/0ffe3ad5-4325-49a5-a02f-f97ad91887c5)

**Comment by lpgoldstein** [comment]
updated reporter letter that had table issues and updated spreadsheet

**Comment by Maroyafaied** [comment]
I let Jodie know about the two that belong to her group with issues, she will look into correcting them.
