### ISSUE TITLE
21st Century Idea Act update

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1758]
We need to provide an updated status on IDEA by Wednesday at 12 EST.

**Comment by Maroyafaied** [comment]
@mcharg here's a simple status as Deron asked for

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/faiedm/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/faiedm/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



Webiste | Status | Conerns or issues
-- | -- | --
revenuedata.doi.gov | Modernization complete | none
onrr.gov | Undergoing Modernization | Requirement for an ATO if using CMS other than Drupal



</body>

</html>

**Comment by mcharg** [comment]
@Maroyafaied Sent to DeRon.
