### ISSUE TITLE
Please Update EMARF Link on New Royalty Reporter Page

### ISSUE THREAD

**Issue by CarlishaWells** [ONRR/onrr.gov-site#176]
The EMARF has been updated to a newer version. Please replace the “old” Electronic MRMSS Access Request Form (EMARF) link on www.onrr.gov/ReportPay/roy-checklist.htm
with the following “new” EMARF link:

https://bseedev.servicenowservices.com/emarf

Please See Attached File: 

![onrr gov reportpay roy checklist htm](https://user-images.githubusercontent.com/62393210/82100544-1b5d9e80-96c7-11ea-9b82-4b2b549c6cdf.png)

**Comment by jennmalcolm** [comment]
Hi @carlishawells, the link you provided is not working at all for me. I just want to confirm it is the right one before I change all of the links.  Thanks.

**Comment by CarlishaWells** [comment]
Hi Jennifer

It was working last week.  I will check to see if something has changed. thanks for letting me know.
________________________________

**Comment by mcharg** [comment]
@CarlishaWells This is updated in dev. Let me know if it's good to push to production.
http://2017onrr/reportpay/roy-checklist.htm

**Comment by mcharg** [comment]
@CarlishaWells, @bowlenj approved the changes, so this change is now live.
https://www.onrr.gov/reportpay/roy-checklist.htm
