### ISSUE TITLE
Production Reporting Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1760]
Please replace the existing instructions with the attached on the production reporting webpage - https://www.onrr.gov/reportpay/production-reporting.htm

[_PASR_CSV_Record_Layout 20220401.pdf](https://github.com/ONRR/onrr.gov-site/files/8365479/_PASR_CSV_Record_Layout.20220401.pdf)
[_OGOR-REPORTING-INSTRUCTIONS-ASCII-FORMAT 20220401.pdf](https://github.com/ONRR/onrr.gov-site/files/8365480/_OGOR-REPORTING-INSTRUCTIONS-ASCII-FORMAT.20220401.pdf)
[_OGOR-REPORTING-INSTRUCTIONS-CSV-FORMAT 20220401.pdf](https://github.com/ONRR/onrr.gov-site/files/8365481/_OGOR-REPORTING-INSTRUCTIONS-CSV-FORMAT.20220401.pdf)

**Comment by lpgoldstein** [comment]
@bowlenj Ready for your approval https://www.onrr.gov/reportpay/production-reporting.htm

**Comment by lpgoldstein** [comment]
@bowlenj Sorry I sent you the wrong link http://2017onrr/reportpay/production-reporting.htm - it's still in dev

**Comment by bowlenj** [comment]
This looks great!!!!!!  Thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: lpgoldstein ***@***.***>
Sent: Monday, March 28, 2022 1:36 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Production Reporting Update (Issue #1760)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C7acbd81ac904461953da08da10f2476d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637840930020605623%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OhOn0eoKd04H9V5EcfrAYYFNT8kltmm6HdE7jrjno9s%3D&reserved=0> Sorry I sent you the wrong link http://2017onrr/reportpay/production-reporting.htm - it's still in dev

**Comment by lpgoldstein** [comment]
@bowlenj This is live so closing out

**Comment by mcharg** [comment]
Files updated in CMS.
