### ISSUE TITLE
Royalty Reporting Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1761]
Please replace existing instruction on the royalty reporting page with the attached - https://www.onrr.gov/reportpay/royalty-reporting.htm
[_CSV2014Rev20220401.pdf](https://github.com/ONRR/onrr.gov-site/files/8365498/_CSV2014Rev20220401.pdf)
[_ASC2014Rev20220401.pdf](https://github.com/ONRR/onrr.gov-site/files/8365499/_ASC2014Rev20220401.pdf)

**Comment by lpgoldstein** [comment]
@bowlenj This is ready for your review: http://2017onrr/reportpay/royalty-reporting.htm

**Comment by bowlenj** [comment]
This one looks great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: lpgoldstein ***@***.***>
Sent: Monday, March 28, 2022 2:06 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Royalty Reporting Update (Issue #1761)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Ce15cf8e2b4e44548562d08da10f675d6%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637840947965362172%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Q4B1i75X7S9aauSch386CJy1ZeJKlxESwWYGn0oVm1U%3D&reserved=0> This is ready for your review: http://2017onrr/reportpay/royalty-reporting.htm

**Comment by lpgoldstein** [comment]
@bowlenj live so closing

**Comment by mcharg** [comment]
Files updated in CMS.
