### ISSUE TITLE
Handbook Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1767]
Please replace the existing "View Complete Handbook" with the attached - https://www.onrr.gov/reportpay/Handbooks/index.htm

Minerals Revenue Reporter Handbook - View Complete Handbook
[RRM-Printable.Minerals.Revenue.Handbook.pdf](https://github.com/ONRR/onrr.gov-site/files/8374085/RRM-Printable.Minerals.Revenue.Handbook.pdf)

Minerals Production Reporter Handbook - View Complete Handbook
[Production_View Complete Handbook.pdf](https://github.com/ONRR/onrr.gov-site/files/8374090/Production_View.Complete.Handbook.pdf)

**Comment by Maroyafaied** [comment]
@cthomasONRR Please also tag these docs as "update" in cms.

**Comment by bowlenj** [comment]
This looks great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Tuesday, March 29, 2022 12:46 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Handbook Update (Issue #1767)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cdc53e763ebef42c3855b08da11b490cb%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637841764469200454%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CWhQ2d04qNGAH1YDwmTy8oDj47KXXeFTmVt9Hrfyyx8%3D&reserved=0> These 2 PDFs are updated in the dev site: http://2017onrr/reportpay/Handbooks/index.htm. Please review and give us your approval to go live.

@Maroyafaied<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMaroyafaied&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cdc53e763ebef42c3855b08da11b490cb%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637841764469200454%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hcT%2BsQ0c8IlQ7kEASQJGoVvWsv9Z%2FxKI%2FkPr29Xnzi8%3D&reserved=0> These 2 PDFs are now tagged with 'update' in the CMS.

**Comment by cthomasONRR** [comment]
@bowlenj Great! The changes are now live: https://www.onrr.gov/reportpay/Handbooks/index.htm.
Closing this issue now.

**Comment by mcharg** [comment]
File updated in CMS.
