### ISSUE TITLE
Correct Table Summary errors 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1768]
@mcharg can you please create a spreadsheet for @carrie-anderson with the 80 docs that have the table summary errors.

**Comment by mcharg** [comment]
@carrie-anderson Here's a spreadsheet with a list of all the documents with table errors.
https://teams.microsoft.com/l/file/56CFB7DB-F3DC-4B43-A486-C2ADAAD400EC?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2F508%2FTableErrors.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a
