### ISSUE TITLE
Upload reformatted NYMEX files to live site

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1769]
I cleaned up the formatting for import in the CMS and it'll be a lot easier for @Baymatt to upload via url than to download from Teams then upload to the CMS.

**Comment by mcharg** [comment]
@lpgoldstein I uploaded new versions of the files from 2004 - 2010. Can you take a look and make sure I didn't break anything before copying to Z? http://2017onrr/valuation/NYMEX.htm

**Comment by lpgoldstein** [comment]
I see missing zeros ex 61.1 instead of 61.10 and also I'm getting a 403 - forbidden access for the files without the icon 
![image](https://user-images.githubusercontent.com/39419003/160689712-30ee16df-d27e-4411-b124-22fe47268fab.png)

**Comment by mcharg** [comment]
@lpgoldstein Those are both issues on the live site.  Nothing I broke.

**Comment by mcharg** [comment]
We don't have files for the early 2004 months.

**Comment by lpgoldstein** [comment]
@mcharg Then it all looks okay - I opened a bunch of them

**Comment by mcharg** [comment]
Pushed to live site.  Will close once changes are reflected in live site.
