### ISSUE TITLE
Please Update EMARF Link on New Solids Minerals Reporters Page

### ISSUE THREAD

**Issue by CarlishaWells** [ONRR/onrr.gov-site#177]
The EMARF has been updated to a newer version. Please replace the “old” Electronic MRMSS Access Request Form (EMARF) link on https://www.onrr.gov/ReportPay/solids-checklist.htm
with the following “new” EMARF link:

https://bseedev.servicenowservices.com/emarf

Please See Attached File: 
![onrr gov reportPay solids checklist htm](https://user-images.githubusercontent.com/62393210/82101126-dc304d00-96c8-11ea-875e-63d64e8ffe8e.png)

**Comment by mcharg** [comment]
@CarlishaWells This is updated in dev. Let me know if it looks good to push to production.
http://2017onrr/reportpay/solids-checklist.htm

**Comment by mcharg** [comment]
@CarlishaWells, @bowlenj approved these changes, so this change is live.
https://www.onrr.gov/reportpay/solids-checklist.htm
