### ISSUE TITLE
Replacing a file in a collection doesn't replace the file in the folder

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1770]
For example, we now have several versions of the file we were trying to get to import to NYMEX.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/38f0624c-075f-4df3-999f-6f05b7d51534)![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/947c1d5b-c11-47c6-a8d0-5e72efbd81c7)

**Comment by mcharg** [comment]
Might go away when Directus fixes file updates.

**Comment by Maroyafaied** [comment]
@mojobnichols @mcharg can you confirm this is fixed by the update.

**Comment by mcharg** [comment]
It's still not deleting the file when you replace it in the collection, but we can go to the folder and use the replace file function as a workaround.
