### ISSUE TITLE
Add Form.2014.pptx presentation to Training Presentations page

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1772]
Jessica noted the file was missing when looking to download it to make accessible. File is in box Y and Z drives, not sure where the link went.

**Comment by mcharg** [comment]
@bowlenj How's this? I also split up the Oil & Gas Reporting into Leases & Agreements, Oil & Gas Production Reporting, and Oil & Gas Revenue Reporting to match what it will be on the new site. http://2017onrr/reportpay/training/index.htm

**Comment by bowlenj** [comment]
Great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: mcharg ***@***.***>
Sent: Wednesday, March 30, 2022 1:06 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Add Form.2014.pptx presentation to Training Presentations page (Issue #1772)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf4a8917134dd4c4c746b08da12806f81%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637842640079336061%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gK%2BLkucDUWOKoK6s4QXfw4nLGzgBPVBdoCNRGkJ%2FaK4%3D&reserved=0> How's this? I also split up the Oil & Gas Reporting into Leases & Agreements, Oil & Gas Production Reporting, and Oil & Gas Revenue Reporting to match what it will be on the new site. http://2017onrr/reportpay/training/index.htm

**Comment by mcharg** [comment]
Pushed to the live site. Will check in an hour to make sure it's gone through.

**Comment by mcharg** [comment]
Update is live.
