### ISSUE TITLE
Accessibility Updates for Training Presentations

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1776]
Attached are the updated training presentations Shannon requested be updated for accessibility in order to be added to the new onrr.gov site.
[Form.ONRR-4430.PR.pptx](https://github.com/ONRR/onrr.gov-site/files/8383377/Form.ONRR-4430.PR.pptx)
[How.to.Save.Your.OGOR.Reports.pptx](https://github.com/ONRR/onrr.gov-site/files/8383379/How.to.Save.Your.OGOR.Reports.pptx)
[OGOR.CSV.REPORTING.pptx](https://github.com/ONRR/onrr.gov-site/files/8383384/OGOR.CSV.REPORTING.pptx)
[ONRR.Enforcement.pptx](https://github.com/ONRR/onrr.gov-site/files/8383386/ONRR.Enforcement.pptx)
[Royalty.Transaction.Codes.pptx](https://github.com/ONRR/onrr.gov-site/files/8383387/Royalty.Transaction.Codes.pptx)
[Solids.AR.Basics.pptx](https://github.com/ONRR/onrr.gov-site/files/8383389/Solids.AR.Basics.pptx)
[Solids.Audit.pptx](https://github.com/ONRR/onrr.gov-site/files/8383390/Solids.Audit.pptx)
[Valuation.Sodium.and.Potassium.pptx](https://github.com/ONRR/onrr.gov-site/files/8383391/Valuation.Sodium.and.Potassium.pptx)
[2014.Federal.Adjustments.pptx](https://github.com/ONRR/onrr.gov-site/files/8383393/2014.Federal.Adjustments.pptx)
[2014.Reporting.pptx](https://github.com/ONRR/onrr.gov-site/files/8383394/2014.Reporting.pptx)
[Accounts.Receivable.FED.Basic.pptx](https://github.com/ONRR/onrr.gov-site/files/8383396/Accounts.Receivable.FED.Basic.pptx)
[Audit.Module.pptx](https://github.com/ONRR/onrr.gov-site/files/8383397/Audit.Module.pptx)
[Basic.Lease.and.Agreements.pptx](https://github.com/ONRR/onrr.gov-site/files/8383400/Basic.Lease.and.Agreements.pptx)
[Billing.pptx](https://github.com/ONRR/onrr.gov-site/files/8383401/Billing.pptx)
[Edit.11030.Inventory.Error.pptx](https://github.com/ONRR/onrr.gov-site/files/8383402/Edit.11030.Inventory.Error.pptx)
[ERRORS.2014.Reporting.pptx](https://github.com/ONRR/onrr.gov-site/files/8383403/ERRORS.2014.Reporting.pptx)
[ERRORS.OGOR.Reporting.pptx](https://github.com/ONRR/onrr.gov-site/files/8383404/ERRORS.OGOR.Reporting.pptx)
[Form.2014.pptx](https://github.com/ONRR/onrr.gov-site/files/8383405/Form.2014.pptx)

**Comment by cthomasONRR** [comment]
@bowlenj Thank you so much for your help! These even more compliant power points are now live. https://www.onrr.gov/reportpay/training/index.htm

@mcharg @Maroyafaied I tagged all 18 powerpoints with the 'update' tag in the CMS, and updated both the accessibility and content audit spreadsheets.

**Comment by mcharg** [comment]
Files updated in CMS.
