### ISSUE TITLE
Please Update EMARF Link on Maintain Operator Information Page

### ISSUE THREAD

**Issue by CarlishaWells** [ONRR/onrr.gov-site#178]
The EMARF has been updated to a newer version. Please replace the “old” Electronic MRMSS Access Request Form (EMARF) link on https://www.onrr.gov/ReportPay/access.htm
with the following “new” EMARF link:

https://bseedev.servicenowservices.com/emarf

Please See Attached File:
![onrr gov ReportPay access htm](https://user-images.githubusercontent.com/62393210/82102045-785b5380-96cb-11ea-8612-455241f11e44.png)

**Comment by jennmalcolm** [comment]
Hi @CarlishaWells, could you  provide us a status update on the new EMARF? Is the production version of the new form available? Thanks.

**Comment by jennmalcolm** [comment]
@carlishawells, could we get rid of this page and just re-direct it to https://www.onrr.gov/reportpay/reporter-maintenance.htm

It seems like they have the same content, and the access page isn't linked anywhere on the site that we've found.

**Comment by mcharg** [comment]
@CarlishaWells We've updated the reporter maintenance page in dev.  Please let us know if you are okay with these changes and redirecting the access page to this one - we don't think the access page is currently linked anywhere.
http://2017onrr/reportpay/reporter-maintenance.htm

**Comment by mcharg** [comment]
I created #494 to redirect the access page to the reporter maintenance page.
