### ISSUE TITLE
Create and upload accessible reporter letter  20191017

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/onrr.gov-site#1783]
https://www.onrr.gov/PDFDocs/20191017.pdf

heading issues

**Comment by lpgoldstein** [comment]
[https://app.zenhub.com/files/210892300/1fc7a767-d1b7-4139-b65b-f1d56422a16e/download](https://app.zenhub.com/files/210892300/1fc7a767-d1b7-4139-b65b-f1d56422a16e/download)

Accessible document

**Comment by lpgoldstein** [comment]
@mcharg This is ready for your review: http://2017onrr/PDFDocs/20191017.pdf

**Comment by mcharg** [comment]
@lpgoldstein Looks good.
