### ISSUE TITLE
Form ONRR-2014 CSV Sample File accessibility

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1784]
Update file to xlsx and delete blank worksheets.

**Comment by mcharg** [comment]
@lpgoldstein This is ready to review.
http://2017onrr/reportpay/royalty-reporting.htm

**Comment by lpgoldstein** [comment]
@mcharg looks good!

**Comment by mcharg** [comment]
Pushed live.

**Comment by mcharg** [comment]
Updates are live.
