### ISSUE TITLE
Rewrite  alt texts 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1786]
After all image issues are resolved, we need to audit the alt texts to ensure proper descriptions are given.

**Comment by cthomasONRR** [comment]
@mcharg This is ready for your review. In the Images tab of the ContentTracking spreadsheet, 

- I sorted Column D (Type) by "Images".
- Updated Alt Texts are indicated in Column F 
- Full alt text is in the CMS as well as Column G

Let me know if I should also work on "Hero" Images and "Icon" Images (from Column D - Type)

**Comment by mcharg** [comment]
@cthomasONRR All the updated alt text looks good to me. Should I mark them as approved in the spreadsheet?

**Comment by cthomasONRR** [comment]
@mcharg Sure! I also just updated all the Hero images if you want to that that too. I made sure their titles matched the spreadsheet and made sure all had alt text.

I can't find the icon images, so I haven't edited any of their metadata.

**Comment by mcharg** [comment]
The icons are pulled from MUI, so hopefully the alt text is embedded as part of that.

**Comment by cthomasONRR** [comment]
@mcharg Great! I will close this issue now.
