### ISSUE TITLE
SME Approval - Compliance webpages 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1789]
Meeting scheduled on April 6th

**Comment by Maroyafaied** [comment]
Moving to next sprint since meeting was rescheduled for April 13th.

**Comment by Maroyafaied** [comment]
Met on April 13th

- [ ] In overview tab, take out numbers from each card and "Approximate" infront of timeframe

- [ ] Jennifer will send contact info to add to contacts tab for Compliance Management

- [ ] Yvette will be the SME for the STRAC page

**Comment by Maroyafaied** [comment]
Send email with requested changes and asked for final approval by April 18.

**Comment by cthomasONRR** [comment]
Yevette responded:

> Good morning,
Thank you for sharing the links to review. The only comment I have is on the contacts page for STRAC. The "Work Planning & Budgets" contacts are broken out into multiple sections. Can you update that sections to look similar to the "Audit Assistance" contacts?
Thanks!
Yvette Smith 

I made those changes, sent it to her, and she gave final approval on the STRAC pages. I set those pages as "approved by SME" on the content tracking spreadsheet

**Comment by cthomasONRR** [comment]
From Jennifer Goldblatt:

> Sorry I just now thought of this, but should we include the definition of compliance and ONRR's comprehensive compliance goal? Either or both?
 
>Compliance is the timely and correct reporting and payment of royalties and other obligations in accordance with the applicable laws, regulations, lease terms, and ONRR policies. 
The strategic goal of ONRR’s comprehensive compliance program is to protect the integrity of Federal and Indian energy and mineral revenues by holding industry accountable for compliance with statutes, regulations, and lease terms. 
 
>Also, on the contact page, please add to the end of the last sentence...
"or Compliance Management Support staff."
 
>Thanks, 
Jennifer

I made these corrections, and sent it back for review. They wanted to change the order of the new language, so adjusted that as well.

**Comment by Maroyafaied** [comment]
@cthomasONRR we just received approval from SME, can you please mark the compliance pages as "approved by SME" then close this issue. Thanks

**Comment by cthomasONRR** [comment]
@Maroyafaied All compliance pages are marked as "approved by SME". Closing this issue now.
