### ISSUE TITLE
SME Approval - Regulations webpages

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1790]
Meeting scheduled for April 4th@10:30AM MT.

**Comment by cthomasONRR** [comment]
@mcharg @Maroyafaied 

I updated the References Home to have the card named "Rules and Regulations" and added the CFR link in the card:
https://dev-onrr-frontend.app.cloud.gov/references
![image](https://user-images.githubusercontent.com/72526208/161595486-447535e8-5668-49a4-98a8-5e865ff2a06b.png)

And renamed the webpages "Rules and Regulations" as well. Should I rename the slug?
https://dev-onrr-frontend.app.cloud.gov/references/rulemakings
![image](https://user-images.githubusercontent.com/72526208/161595607-de1a959e-264e-489d-ace7-c202b9951051.png)

**Comment by cthomasONRR** [comment]
@Maroyafaied @mcharg The Statutes table is now updated to have FOGRMA and Amendments up front:
https://dev-onrr-frontend.app.cloud.gov/references/statutes
![image](https://user-images.githubusercontent.com/72526208/161597526-d2766d0a-8cc8-4d8d-9116-0c40fc1ed79e.png)

**Comment by Maroyafaied** [comment]
> @Maroyafaied @cthomasONRR Did Bonnie also ask for the Statutes and ICRs to be searchable?

@mcharg Ya she mentioned it at the end so I'll let her know that we will have the search functionality working for all pages later.

**Comment by cthomasONRR** [comment]
@Maroyafaied @mcharg Shouldn't the card title and page title be consistent though?

**Comment by Maroyafaied** [comment]
@cthomasONRR I asked that during the meeting and @mcharg made the point that other cards titles are not matching with the page title and the cards are meant to help users find what they needs quickly and Bonnie didn't seem to care that they are not consistent. @mcharg do you agree ?

**Comment by Maroyafaied** [comment]
@cthomasONRR this is showing for me twice, can we remove the second link? 
![image](https://user-images.githubusercontent.com/40175688/161603484-b9048678-4455-483a-b196-b389c585da00.png)

**Comment by cthomasONRR** [comment]
@Maroyafaied Sorry about that, it is now removed

**Comment by cthomasONRR** [comment]
@mcharg @Maroyafaied I think we updated everything we needed to today. In the email, I would be sure to add the caveats: developers are working on search features and contacts, as well as the ability to add colored text (for FOGRMA amendments).

**Comment by Maroyafaied** [comment]
Hi,

Thank you all for meeting with us today, we have implemented your feedback by doing the following:


- In the R[eference homepage](https://dev-onrr-frontend.app.cloud.gov/references), we changed the card title from "Rulemakings" to "Rules and Regulations" and the GPO eCFR link above the rulemakings links. 

- In the [Statues tab](https://dev-onrr-frontend.app.cloud.gov/references/statutes), we moved the FOGRMA of 1982 link on the top of the table followed by the 1996 amendments to FORGRMA link.

**Upcoming changes:**

- Our developers will be working on the search functionality for the entire website and it will be working when the new website launches.

- Our developers will be working on the ability to add colored texts and this will be implemented in the [FOGRMA amendments ](https://dev-onrr-frontend.app.cloud.gov/references/statutes/fogrma-amendments)page. 

- Our developers are currently working on building the contacts for the entire website. 

**Action items:**

- For the [How to Appeal tab](https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/appeals), please send us changes to content and links to 30 C.F.R. Part 1290 and 43 C.F.R. Part 4.

- Please give us your final approval with the upcoming changes in mind for the following pages by April 11; [References Home](https://dev-onrr-frontend.app.cloud.gov/references), [Statues](https://dev-onrr-frontend.app.cloud.gov/references/statutes), [Rulemakings](https://dev-onrr-frontend.app.cloud.gov/references/rulemakings), [Federal Register Notices](https://dev-onrr-frontend.app.cloud.gov/references/frns), [Information Collection Requests](https://dev-onrr-frontend.app.cloud.gov/references/icrs), [How to Appeal](https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/appeals), [Sureties](https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/appeals?tabs=sureties), and[ Past Decisions](https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/appeals?tabs=past-decisions). 

- Please feel free to review other pages in the [development website](https://dev-onrr-frontend.app.cloud.gov/) and give us your feedback.

**Comment by cthomasONRR** [comment]
I also have Appeals updated incorporated now
https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/appeals?tabs=how-to-appeal
![image](https://user-images.githubusercontent.com/72526208/161621192-8e3ded4a-66e4-4266-ad6e-a57bce3c058c.png)

**Comment by Maroyafaied** [comment]
@cthomasONRR changes look good. Please review my email above and let me know if it's good to send out.

**Comment by cthomasONRR** [comment]
@Maroyafaied The email looks good- the only edit I made was to correct the spelling of 'statutes'

**Comment by cthomasONRR** [comment]
@Maroyafaied This is ready for your review

**Comment by Maroyafaied** [comment]
@cthomasONRR  please mark these pages as approved by SME in the tracking sheet and close this issue. Thanks

References Home, Statutes, Rulemakings, Federal Register Notices, Information Collection Requests, How to Appeal, Sureties, and Past Decisions.

**Comment by cthomasONRR** [comment]
@Maroyafaied Done!
