### ISSUE TITLE
SME Approval - Enforcement webpages 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1791]
Meeting schedule for April 4th at 12PM MT.

**Comment by Maroyafaied** [comment]
Summary of meeting:
- Add this content and email address to the enforcement tab "If you are aware of any mineral revenue violations (unpaid royalties, unfiled or inaccurate reporting etc.) please email us at ONRR.Enforcement.Referrals@onrr.gov"
- In the contacts tab, combine Enforcement team A & B into one with Sam and Allen as primary and Michael as the supervisor
- Reach out to Kim regarding her contact info in the appeals tab.
- In the future, they might consider adding cards or visuals explaining the difference but we have their SME approval for now with the changes above.

@cthomasONRR @mcharg did I mess anything?

**Comment by Maroyafaied** [comment]
@cthomasONRR I added the content and email address in the bottom of the enforcement tab, please review https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/enforcement. 

@mcharg should we make the contacts changes in the wireframe to show them or is it not necessary?

I will reach out to Kim about her contacts in the appeals sections.

**Comment by mcharg** [comment]
@Maroyafaied I guess it would be good to do that, so they can sign off on it, since we're changing how theirs are structured.

**Comment by mcharg** [comment]
I don't think you missed anything.

We should update the contacts in the spreadsheet and let @jlouis-onrr know when it's updated, so he can have the updates when he imports it to the CMS.

**Comment by cthomasONRR** [comment]
@Maroyafaied Looks good.

**Comment by Maroyafaied** [comment]
@mcharg @cthomasONRR  Kim replied to keep her contact in that section. I'll wait to send enforcement an email until the wireframe is done.

**Comment by mcharg** [comment]
I'll do the wireframe and update the contacts spreadsheet in the morning.

**Comment by mcharg** [comment]
I split the intro up into two lines to make it easier to skim and see what each time does. I also added a missing period to the enforcement referrals sentence and moved that to a card to be consistent with other contacts and add some visual appeal.
https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/enforcement?tabs=enforcement

I fixed the contacts in the spreadsheet and let @jlouis-onrr know it's updated.

I updated the wireframe with the new contacts organization. https://qmcq5k.axshare.com/#id=5w0f4w&p=enforcement
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/6b5d4d2e-5389-4c5c-a6a4-5b0e075a95d7)

**Comment by mcharg** [comment]
I was also thinking we could put all the subtabs under civil penalties into cards to make it less text heavy and easier to see how those all relate.  @cthomasONRR @Maroyafaied Thoughts?

**Comment by mcharg** [comment]
The overview wouldn't be in a card, so we would have the overview paragraphs and then cards for References, Assessment Tables, Penalty Collections by Year and Historical Penalty Collections.

**Comment by cthomasONRR** [comment]
@mcharg Yeah let's mock up putting the civil penalties tabs into cards below the overview information. I think that will be easier to read/navigate.

**Comment by Maroyafaied** [comment]
@mcharg I'm fine with that.

**Comment by mcharg** [comment]
@cthomasONRR @Maroyafaied How's this? https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/enforcement?tabs=civil-penalties,penalty-collections

**Comment by cthomasONRR** [comment]
@mcharg Nice! I like it!

**Comment by Maroyafaied** [comment]
@mcharg I agree, looks good. I'll draft an email and send for approval this afternoon. Thanks

**Comment by Maroyafaied** [comment]
Send email and gave deadline for approval by April 8.

**Comment by Maroyafaied** [comment]
@mcharg can you please make these changes and let me know when it's ready for review. Thanks

- [ ] Under the yellow banner at the top, please change "ONRR's enforcement team evaluates the enforceability of compliance violations." to "ONRR's two enforcement teams evaluate the enforceability of compliance violations and issue civil penalties when appropriate."   

- [ ] Also please capitalize the Litigation Support Team by changing to: "Our Litigation Support Team provides support and coordination through lawsuits and bankruptcies."

- [ ] Under the "Enforcement" tab, I'm ok with keeping the tab as just "Enforcement", but when clicking on it, I think we should change the heading from "Enforcement" to "Enforcement Teams".

- [ ] Under the "Civil Penalty" tab, please edit "Our civil penalty program encourages compliance and deters future compliance violations." to "The two enforcement teams administer our civil penalty program to encourage compliance and deter future compliance violations."

- [ ] Under the "Bankruptcies and Litigation Support" tab, please change "When companies who owe us money file for bankruptcy, we:  Ensure. . Review .. Provide. . Coordinate . ." to "When companies with mineral revenue lease obligations file for bankruptcy, the Litigation Support Team:  Ensures . . . Reviews . . . Provides . . Coordinates. . ."

- [ ] Also please edit: 
"When we provide litigation support, we:
Act as a liaison between ONRR, the Solicitor’s Office, and the Department of Justice (DOJ).
Provide legal help. We coordinate and prepare litigation cases throughout the evidentiary and hearing process.
Monitor appellant’s financial solvency.
Review class action lawsuits alleging underpaid royalties or improper deductions from royalties. We respond that the Federal Government is not a party.  
Manage information requests from DOJ about Indian Tribal Trust Suits.
Fulfill Freedom of Information Act (FOIA) requests made through either the Office of the Secretary or ONRR. We forward requests to ONRR departments that have potentially responsive records." to:
"Whether litigation is in the bankruptcy context or not, the Litigation Support Team: 
Acts as a liaison between ONRR, the Solicitor’s Office, and the Department of Justice (DOJ).
Gathers and provides the administrative record to the Solicitor's Office when ONRR decisions are appealed to the Interior Board of Land Appeals.
Coordinates and prepares litigation cases throughout the evidentiary and hearing process.
Reviews the financial solvency of civil penalty litigants when litigants seek a compromise based on their insolvency."

- [ ] Under the enforcement contact tabs, please change "Enforcement" to "Enforcement Teams" .  In Sam's contact box, please change the title from "Primary Contact" to "Primary Contact, Enforcement Team A" and next to Sam's name, add "Supervisor". 

- [ ]  In Allen's contact box, please change the title from "Primary Contact" to "Primary Contact, Enforcement Team B" and next to Allen's name, add "Supervisor".  In my contact box, please change "Supervisor" to "Manager" and add "Program Manager" next to my name.

- [ ] For the litigation support contact tabs, please change "Litigation Support" to "Litigation Support Team".  Also, change "Timothy Calahan" to "Michael Marchetti, Acting Supervisor" and change to my email (michael.marchetti@onrr.gov) and phone number ((303) 231-3125).  And for my contact box, I'd like it to be similarly changed (from "Supervisor" to "Manager" and add my title to now read "Michael Marchetti, Program Manager").

**Comment by mcharg** [comment]
@Maroyafaied This is ready to review. I couldn't do exactly what he wants with the contacts because we only have the options of Primary Contact, Back-up Contact, Supervisor, and Manager for the card headers. I think I captured the spirit of what he's looking for by putting the additional title details with the contact name.

**Comment by Maroyafaied** [comment]
@mcharg please mark all the pages as approved by SME and close this issue. Thanks
We also build the Contacts page and it's ready for your approval as well as the pages listed below. Thanks

Enforcements, Civil Penalties, Bankruptcies & Litigation Support, Contacts
