### ISSUE TITLE
CMS Wiki Guide: building new webpage and setting up tabs, accordions, and cards.

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1796]
Issue for writing the following sections of the CMS users guide wiki:

- [x] Building a new webpage
- [x] Setting up tabs
- [x] Settling up accordions
- [x] Setting up cards

Word doc located here: https://teams.microsoft.com/l/file/3399470E-E341-48E5-A818-C49141DF7EC3?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FCMS%2FWiki%20Guides%2FCMS%20Instructions%20for%20ONRR.gov%20wiki.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by cthomasONRR** [comment]
@mcharg The 4 sections listed above are ready for your review. There's a lot of sections in the document, so I recommend using the Navigation Pane. Thanks!
![image](https://user-images.githubusercontent.com/72526208/161551461-004e2995-c3e0-4c85-8a8d-c9bc6c630e3f.png)

**Comment by lpgoldstein** [comment]
@cthomas - this looks awesome. I really how you've added the examples for each type of content. Those can be so useful. The only thing I would add is more emphasis on saving your work. Thank you!

**Comment by mcharg** [comment]
@cthomasONRR I added my comments to the doc.

**Comment by cthomasONRR** [comment]
@mcharg I responded to you comments. I think I have one question in there for you to verify, then I can add these to the wiki

**Comment by mcharg** [comment]
@cthomasONRR I responded to your question.

**Comment by cthomasONRR** [comment]
@mcharg @lpgoldstein Thanks for reviewing! These 4 sections are now on the wiki: https://github.com/ONRR/onrr.gov-site/wiki/CMS-User-Guide. Closing issue.

**Comment by mcharg** [comment]
@cthomasONRR Can you please add alt text for the images in the wiki? It goes in the brackets before the link in parentheses.
![image](https://user-images.githubusercontent.com/38465926/161988075-86fab2e5-ced5-4d4a-9cfa-6eb4b347f703.png)

**Comment by cthomasONRR** [comment]
@mcharg Done :)
