### ISSUE TITLE
CMS Workflow

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1797]
Kaitlyn is going to work on a workflow diagram for how the workflow with the CMS, content editors, GitHub, dev vs. production, etc. should work.

**Comment by mcharg** [comment]
@mojobnichols We met without you and came up with an approach. Let us know when you're back in the office and we can schedule a time to loop you in and get your feedback.

**Comment by mcharg** [comment]
Post-its from our meeting.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/4affec30-964e-4c1d-8e5e-42866526beca)

**Comment by Maroyafaied** [comment]
@mcharg @mojobnichols @jlouis-onrr I made [two visuals on ppt ](https://doimspp.sharepoint.com/:p:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/CMS/Workflow/Workflow.pptx?d=wf304d9bdaec745f396ca5be16bfbf44f&csf=1&web=1&e=zeXica)to summarize the workflow process we discussed. The first one details the steps and the second is simpler, let me know if I captured anything wrong.  @kmhtran please let me know if this helps or if you need more clarification to be able to do the diagram. Here are pics of the visuals incase you can't open the ppt. 
![image](https://user-images.githubusercontent.com/40175688/163285148-2997a06a-612a-4a82-af5f-27f0d0b4c1ce.png)
![image](https://user-images.githubusercontent.com/40175688/163285677-8a0fca00-c488-4cb7-a612-7a961ad0db28.png)

**Comment by Maroyafaied** [comment]
I also started a work doc with workflow steps starting with GitHub issue submitted, I will go over this with the team today. https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/ONRR.gov/CMS/Workflow/Workflow%20example.docx?web=1

**Comment by mcharg** [comment]
@Maroyafaied All of the above match my understanding.

**Comment by kmhtran** [comment]
Been having issues with Visio so I'll send a screenshot for now and add my document in the ODDD sharepoint. 
@Maroyafaied @mcharg @mojobnichols @jlouis-onrr Here's my understanding of the workflow I gathered from the meetings and Maroya's visuals. I tried to keep it straightforward with the different status changes represented by arrows, and the viewing ability on the Dev/Staging/Production sites on the left. Feel free to let me know if there's something I'm misunderstanding or missing from the diagram.

![image](https://user-images.githubusercontent.com/89661018/165618388-62663a81-724b-4af3-936f-527d35ce562a.png)

**Comment by mcharg** [comment]
@kmhtran Makes sense to me.

**Comment by mcharg** [comment]
Here's a link to the Visio file on Teams. 
https://doimspp.sharepoint.com/:u:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/CMS/Workflow/CMS%20Workflow.vsdx?d=w3679d45f46f24d17b5277bede84dfcbe&csf=1&web=1&e=6sUJrC

@mojobnichols @jlouis-onrr Can you take a look at the diagram?

**Comment by mcharg** [comment]
Please review in sync up today.

**Comment by Maroyafaied** [comment]
@lpgoldstein please make the following changes

- remove the ready to review status
-  clarify on the arrow to development that this shows draft and published status
- clarify on the arrow to staging that this shows publish status and already published
- clarify on the arrow to ODDD push button that only after review and approval . 
-

**Comment by lpgoldstein** [comment]
@Maroyafaied changes made. Let me know if we need further revisions.

**Comment by Maroyafaied** [comment]
@lpgoldstein looks good.
