### ISSUE TITLE
Enable editing revenue statistics in home page

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1798]
Change Explore revenue statistics icon to graph

To match the NRRD link in the header. I can't figure out where to edit this.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/e6e03093-a5bb-4a35-b55c-c83b6251b934)

**Comment by mcharg** [comment]
Need to be able to add/update GOMESA and disbursements press releases, as well.

**Comment by jlouis-onrr** [comment]
@mcharg, I wonder if its easier to just create a new card block with the content you want inside that block, then trying to pull the data dynamically and remove the dynamic block from template.

**Comment by mcharg** [comment]
@jlouis-onrr Card created. It'll also need the Vuetify icon that you use in the header for the NRRD link.

**Comment by mcharg** [comment]
@jlouis-onrr Were you going to make a way to pull numbers from NRRD into the new block?
