### ISSUE TITLE
Fix NYMEX prices on current website 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1799]
- [x] Jan 2008 - Roll

- [x] Jan 2007- CMA

- [x] Jan 2006 - Roll

- [x] Dec 2005 - Roll

- [x] March 2009 -Roll

**Comment by cthomasONRR** [comment]
@Maroyafaied January 2008 Roll should be $0.55, it is still $0.56 on http://2017onrr/valuation/NYMEX.htm
![image](https://user-images.githubusercontent.com/72526208/161579270-1a3df48d-757e-4f1a-ab4a-025b71f6c930.png)

All the others match now :)

**Comment by Maroyafaied** [comment]
@cthomasONRR I fixed it and pushing live. Thanks

**Comment by Maroyafaied** [comment]
This is live. Closing
