### ISSUE TITLE
Walk through and document current state processes for persona tasks

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#18]
Put together a click through in Axure.  This may uncover new pain points for the personas.

**Comment by lpgoldstein** [comment]
Links to payments instructions. 
https://www.onrr.gov/reportpay/payments.htm

New payor instructions
https://www.onrr.gov/reportpay/roy-checklist.htm

Pay.gov how to video
https://youtu.be/0ClyFaAnWSA

Production reporter how to 
https://www.onrr.gov/reportpay/prod-checklist.htm

Rent payments on leases
https://youtu.be/vbT0PAh-kko

**Comment by mcharg** [comment]
@alenahuang will be starting on this.

**Comment by mcharg** [comment]
@alenahuang Can you please add the link to the Axure file and close this issue?

**Comment by alenahuang** [comment]
https://os2cz3.axshare.com/

**Comment by alenahuang** [comment]
https://os2cz3.axshare.com/
