### ISSUE TITLE
Update 2020 Indian Major Portion Gas Prices on onrr.gov

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#1801]
Good afternoon,

Could you please update the MPP on onrr.gov according to the attached spreadsheet. Since they were just published today, the due date for a response will be June 30, 2022
[Maj_Portion_FinalPrices_2020.xls](https://github.com/ONRR/onrr.gov-site/files/8413158/Maj_Portion_FinalPrices_2020.xls)

Thank you!

@sudarr

**Comment by Maroyafaied** [comment]
@boices I'm not familiar with this spreadsheet since we usually get the shared spreadsheet updated with the final prices. Are columns S to W what should be published? @lpgoldstein we will need to update that page in the cms as well.

**Comment by lpgoldstein** [comment]
@boices This is ready for your review: http://2017onrr/valuation/MonMajPP.htm

**Comment by boices** [comment]
@lpgoldstein @Maroyafaied 

Prices look great. Sorry for the initial confusion--I didn't see that our shared data sheet had a tab for the MPP. I went ahead and updated that too just to maintain a complete record. Thanks for your help!

**Comment by lpgoldstein** [comment]
@boices Thanks, I'll let you know when live.

**Comment by lpgoldstein** [comment]
@boices it's live so I'm closing the issue
