### ISSUE TITLE
Update 2020 Indian Gas Major Portion prices in CMS & write how to instructions

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1802]
Related to issue #1801

**Comment by cthomasONRR** [comment]
@lpgoldstein I checked the raw data, dev, and the live site. Everything matches up for me!

**Comment by lpgoldstein** [comment]
@cthomasONRR Thank you!

**Comment by lpgoldstein** [comment]
@cthomasONRR I've added instructions to the word doc if you have time to review https://teams.microsoft.com/l/file/3399470E-E341-48E5-A818-C49141DF7EC3?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FCMS%2FWiki%20Guides%2FCMS%20Instructions%20for%20ONRR.gov%20wiki.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by cthomasONRR** [comment]
@lpgoldstein Looks good. I will use it the next time I upload prices to see if anything needs modification
