### ISSUE TITLE
CMS Wiki Guide: Adding images, and adjusting content dimensions and images

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1803]
Complete the following wiki sections:
- [x] Adjusting content dimensions
- [x] Adding images and proper tagging
- [x] Adjusting images

Wiki word document saved here: https://teams.microsoft.com/l/file/3399470E-E341-48E5-A818-C49141DF7EC3?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FCMS%2FWiki%20Guides%2FCMS%20Instructions%20for%20ONRR.gov%20wiki.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by cthomasONRR** [comment]
@mcharg @lpgoldstein These next 3 sections are now ready for your review

**Comment by mcharg** [comment]
@cthomasONRR I added my comments to the doc.

**Comment by cthomasONRR** [comment]
@mcharg I responded to you comments. I'm waiting for Jerome's response about image sizing, then I can add this to the wiki

**Comment by lpgoldstein** [comment]
@cthomasONRR They look good to me. Thanks!

**Comment by cthomasONRR** [comment]
I added these sections to the wiki, with alt text incorporated for the images
https://github.com/ONRR/onrr.gov-site/wiki/CMS-user-guide

Closing this issue now
