### ISSUE TITLE
Get an accessible version of the FY 2020 disbursements national press release 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1805]

**Comment by lpgoldstein** [comment]
@mentastc ere is the doc [https://app.zenhub.com/files/210892300/a098a091-f4b1-4a84-ae02-8e1507fa7434/download](https://app.zenhub.com/files/210892300/a098a091-f4b1-4a84-ae02-8e1507fa7434/download)
