### ISSUE TITLE
Late Payment & Underpayment Interest Table

### ISSUE THREAD

**Issue by bbell0229** [ONRR/onrr.gov-site#1808]
Hello,

On the Late Payment & Underpayment Interest Tables page, at https://onrr.gov/ReportPay/interest.htm, please make the following updates:

1) replace the interest Calculator Excel file below the Questions/Contact box on the page with the attached file.
2) Add a new line at the bottom of the Late Payments and Underpayments table for Period 4/1/2022-6/30/2022. 
- Indian O&G will be 4%, Solid's remain at 1%, Federal O&G will be 4%, and overpayments remain the same.

If you have any question, please let me now.

Thank you,
Brittney

[Quarterly Interest Rate Changes FY 2022.xls](https://github.com/ONRR/onrr.gov-site/files/8421426/Quarterly.Interest.Rate.Changes.FY.2022.xls)

**Comment by lpgoldstein** [comment]
@bbell0229 This is ready for your review: http://2017onrr/reportpay/interest.htm

**Comment by bbell0229** [comment]
Looks perfect! Thank you!

Brittney A. Bell
Staff Accountant, Financial Services
Revenue, Reporting, & Compliance Management
Office of Natural Resources Revenue
Bldg 85, Denver Federal Center
Denver, CO 80225
1-800-433-9801 x 3381
303.231.3381
***@***.******@***.***>

From: lpgoldstein ***@***.***>
Sent: Wednesday, April 6, 2022 9:27 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bell, Brittney A ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Late Payment & Underpayment Interest Table (Issue #1808)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bbell0229<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbbell0229&data=04%7C01%7Cbrittney.bell%40onrr.gov%7Cf4495bcfad9c410f793a08da17e1dd65%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637848556097438055%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=09UX0eAjESAcIpJQTxnotFGs%2BqFh6Oz95A7nnftFcsI%3D&reserved=0> This is ready for your review: http://2017onrr/reportpay/interest.htm

-

**Comment by lpgoldstein** [comment]
@bbell0229 This is live so I will close the issue https://onrr.gov/reportpay/interest.htm
