### ISSUE TITLE
Explore ways to make it clear the Revenue Data link goes to a separate site

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1810]
An internal ONRR person who didn't know NRRD was separate had no idea it was a separate site and wondered why we have no home link.  Maybe we have it open in another browser tab or add an external icon (though the USWDS did some research on the external icon and learned that nobody knows what it means). Or maybe we call it Revenue Data Website?
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/790fc336-d1c3-4170-9343-d5a6fee26e26)

**Comment by mcharg** [comment]
I think this is going to be a bigger problem than with the current site because the two sites look so much alike.

**Comment by mcharg** [comment]
Or maybe we make it a banner advertising the sister site rather than look like the in site navigation.

**Comment by mcharg** [comment]
@Isabelh99 @kmhtran @jkwonatx Are any of you interested in working on this?

**Comment by Isabelh99** [comment]
> 

Hi Kaitlyn, I can also help on this! Do you want to work together on this, generate ideas, etc?

**Comment by kmhtran** [comment]
@Isabelh99 I'd be down to work on this together! We can come up with some ideas independently and meet up sometime this week to talk it through.

**Comment by Isabelh99** [comment]
Sounds good! I'll be posting some sketches of my ideas with interpretations under here!

**Comment by Isabelh99** [comment]
Here are some ideas I came up with:
![image](https://user-images.githubusercontent.com/93946660/163249691-067ff45a-7645-429a-a7d9-c52e59eb5a98.png)
![image](https://user-images.githubusercontent.com/93946660/163249716-f2ce254b-b488-4c60-846c-5550520a1dc6.png)
![image](https://user-images.githubusercontent.com/93946660/163249772-96b67c73-fa24-4274-b510-fe6a15a9f3ca.png)

**Comment by Isabelh99** [comment]
fourth idea generated from intern meeting:
![image](https://user-images.githubusercontent.com/93946660/163253517-23aa9a99-2c34-43d6-af67-51eab6af6212.png)

**Comment by mcharg** [comment]
Created #1837 for @jlouis-onrr to build this.
