### ISSUE TITLE
CMS wiki guide: Creating tables, and adding external and internal links

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1813]
Issue to complete the last sections within the CMS wiki:

- [x] Creating tables
- [x] Adding external links
- [x] Adding internal links

Word document located here:
https://teams.microsoft.com/l/file/3399470E-E341-48E5-A818-C49141DF7EC3?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FCMS%2FWiki%20Guides%2FCMS%20Instructions%20for%20ONRR.gov%20wiki.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by cthomasONRR** [comment]
@mcharg @lpgoldstein These 3 sections are ready for your review

**Comment by mcharg** [comment]
@cthomasONRR Looks good. I added one comment about linking to tabs and accordions.

**Comment by cthomasONRR** [comment]
@mcharg Thanks, added in a note to address your comment

**Comment by mcharg** [comment]
@cthomasONRR Looks good.

**Comment by cthomasONRR** [comment]
@mcharg Great! These are now in the wiki if you want to do a final review. All images have alt text. https://github.com/ONRR/onrr.gov-site/wiki/CMS-user-guide#Creating-tables

**Comment by mcharg** [comment]
@cthomasONRR Looks good.
