### ISSUE TITLE
Inventory all the locations of videos on the new site

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1815]
So, when we're told to remove the ones that aren't being refreshed, we know where to remove them.

**Comment by mcharg** [comment]
@lpgoldstein This is ready for you to review.

We now have a master video list tab with all the videos across the current site, YouTub channel, and Bill's list. And a Video Locations tab that shows where they exist on the new site.
https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Content/Content%20Audit/ContentTracking.xlsx?d=w74b27b0272bc4cee92b0a1280895cb73&csf=1&web=1&e=5j1UX1

**Comment by lpgoldstein** [comment]
@mcharg Looks good
