### ISSUE TITLE
Update index zone prices on onrr.gov

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#1816]
Good morning,

Please update the April index zone values on onrr.gov. The "Data for onrr.gov" worksheet has been updated with current prices.

Thanks!
@sudarr

**Comment by boices** [comment]
Prices look great--thanks again!

**Comment by cthomasONRR** [comment]
@boices The April prices are live: https://www.onrr.gov/valuation/allzones.htm. Closing this issue now. Thanks!

**Comment by cthomasONRR** [comment]
@Maroyafaied April 2022 prices are now also on the CMS.
