### ISSUE TITLE
March 2022 Nymex Prices 

### ISSUE THREAD

**Issue by damionschulte** [ONRR/onrr.gov-site#1817]
All, can you please post the March 2022 Nymex prices to the website?  Thank you

@sudarr

[NYMEX032022.xlsx](https://github.com/ONRR/onrr.gov-site/files/8444884/NYMEX032022.xlsx)

**Comment by cthomasONRR** [comment]
@damionschulte The March 2022 NYMEX prices are now on the dev site: http://2017onrr/valuation/NYMEX.htm. Please review and give us your approval to go live.
Thanks, 
Christine

**Comment by damionschulte** [comment]
Prices look great!  Thank you

From: Christine Thomas ***@***.***>
Sent: Thursday, April 7, 2022 11:28 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] March 2022 Nymex Prices (Issue #1817)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@damionschulte<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdamionschulte&data=04%7C01%7Cdamion.schulte%40onrr.gov%7Ce5d0dfe8ccbc44f535d208da18bbf6b2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637849493303873123%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WVpno%2FI%2F7Y4RQCT4DnkgMSc6uLKlZZ2YsJL0%2BEZlCxk%3D&reserved=0> The March 2022 NYMEX prices are now on the dev site: http://2017onrr/valuation/NYMEX.htm. Please review and give us your approval to go live.
Thanks,
Christine

-

**Comment by cthomasONRR** [comment]
@damionschulte Great! These changes are now live: https://www.onrr.gov/valuation/NYMEX.htm

@Maroyafaied These prices are also uploaded in the CMS

Closing this issue now.
