### ISSUE TITLE
Production Checklist Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1818]
Please update the production checklist page at this link - https://www.onrr.gov/reportpay/prod-checklist.htm, as indicated on the attached file.  Please let me know if you have any questions, thank you!

[Production Checklist Update_4-7-22.docx](https://github.com/ONRR/onrr.gov-site/files/8445558/Production.Checklist.Update_4-7-22.docx)
.

**Comment by mcharg** [comment]
@lpgoldstein Let me know if we need to make any changes to the checklist on the dev site to match these changes.

**Comment by lpgoldstein** [comment]
@bowlenj Please let me know if this looks okay - I think I got everything http://2017onrr/reportpay/prod-checklist.htm

**Comment by bowlenj** [comment]
This looks great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: lpgoldstein ***@***.***>
Sent: Thursday, April 7, 2022 1:45 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Production Checklist Update (Issue #1818)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cbf201c7c739d40458acd08da18cf271e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637849575237343617%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NfzLP5iBgYua3HwC%2FNtEBZRJIADE2f2dDlc5HRsCcM0%3D&reserved=0> Please let me know if this looks okay - I think I got everything http://2017onrr/reportpay/prod-checklist.htm

**Comment by lpgoldstein** [comment]
@bowlenj This is live so I'm closing out the issue. https://www.onrr.gov/reportpay/prod-checklist.htm

**Comment by mcharg** [comment]
@bowlenj I just took a look at the production checklist and I think it got replaced with the content from the reporter information maintenance page somehow.
https://www.onrr.gov/reportpay/reporter-maintenance.htm

I think it's also missing the sections for OCS numbers and W-9. Do you want us to add them and remove the cancel user access and change company name sections?

**Comment by mcharg** [comment]
@bowlenj How's this?
http://2017onrr/reportpay/prod-checklist.htm

**Comment by mcharg** [comment]
@bowlenj Hold off on reviewing. There's something wonky going on and the page is now blank in development. We're investigating the bugs. The changes from yesterday appear to no longer be on the live site, as well.
