### ISSUE TITLE
Add video links to CMS

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1819]

**Comment by mcharg** [comment]
Video links added to these pages.

- [ ] [Reporter Training](https://dev-onrr-frontend.app.cloud.gov/references/training?tabs=training-videos,new-reporters)
- [ ] [New Reporter Training](https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-training)
- [ ] [Getting Started Contacts](https://dev-onrr-frontend.app.cloud.gov/about/contact/getting-started-contacts)
- [ ] [Production Contacts](https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts)
- [ ] [Royalty Contacts](https://dev-onrr-frontend.app.cloud.gov/about/contact/royalty-contacts)

**Comment by mcharg** [comment]
@lpgoldstein This is ready to review.  I marked all the links on the Video Locations tab in the content tracking sheet as ready to review.

**Comment by lpgoldstein** [comment]
@mcharg looks good and updated in content tracking as well.
