### ISSUE TITLE
Add instruction for adding and updating contacts to CMS wiki

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1824]

**Comment by mcharg** [comment]
@Maroyafaied @cthomasONRR This is ready to review.

I added a Contacts section at the end of the doc. https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/CMS/Wiki%20Guides/CMS%20Instructions%20for%20ONRR.gov%20wiki.docx?d=w3399470ee34148e5a818c49141df7ec3&csf=1&web=1&e=fwdqsd

**Comment by mcharg** [comment]
@cthomasONRR @Maroyafaied I addressed all the comments.

**Comment by Maroyafaied** [comment]
@mcharg looks god

**Comment by cthomasONRR** [comment]
@mcharg Thanks for addressing my comments. Looks good!

**Comment by mcharg** [comment]
Added to the wiki. @cthomasONRR Can you please review?
https://github.com/ONRR/onrr.gov-site/wiki/CMS-User-Guide#Contacts

**Comment by cthomasONRR** [comment]
@mcharg Looks good!
