### ISSUE TITLE
Contacts aren't sorting correctly

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1825]
@mcharg For **onshore** in dev, there needs to be some reorganization. The "C's" are missing in the alphabetical order, and are on the last page. Same with "O" and "W"
![image](https://user-images.githubusercontent.com/72526208/162766888-e107572e-e955-4f8f-a890-555151f13fe0.png)
I created a pivot in the spreadsheet to more efficiently check names. Names are now matching up.

_Originally posted by @cthomasONRR in https://github.com/ONRR/onrr.gov-site/issues/1401#issuecomment-1095163692_

**Comment by mcharg** [comment]
There are also issues in Paying.
https://github.com/ONRR/onrr.gov-site/issues/1531#issuecomment-1095176347

**Comment by jlouis-onrr** [comment]
@mcharg, sorting update is now out in dev, along with #1820, #1827

**Comment by mcharg** [comment]
Looks good.
