### ISSUE TITLE
Apostrophes don't display in contacts

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1826]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/e438c32a-7b7b-410f-87ed-44c39b0be984)

**Comment by mcharg** [comment]
@jlouis-onrr Is this an upload issue and we just need to type in the apostrophes in the collection? I think I remember a similar issue with press releases.

**Comment by Maroyafaied** [comment]
@mcharg @cthomasONRR please review. Thanks

![image](https://user-images.githubusercontent.com/40175688/163230913-2396b1d4-cd06-4a86-b986-8cdf496bb509.png)
![image](https://user-images.githubusercontent.com/40175688/163231080-cc89d563-925d-4571-b39d-bb6470de306d.png)
![image](https://user-images.githubusercontent.com/40175688/163231190-50314e1f-9f9a-4169-8a0e-4fb99a3cf05f.png)

**Comment by cthomasONRR** [comment]
@Maroyafaied I checked it on the site, looks good!

**Comment by mcharg** [comment]
@Maroyafaied Looks good.
