### ISSUE TITLE
Draft status doesn't work

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1828]
I made the expansion panels for videos draft, so they wouldn't display until we get the accessible videos, but they're still displaying on the site.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/f4831d12-346c-4504-9a59-c0c59f7d3a56)

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/4abc03c0-85df-4d9c-978e-8b99ffb04c30)

**Comment by Maroyafaied** [comment]
will close this since the work flow process we agreed on will cover this.
