### ISSUE TITLE
Remove video from live site

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1831]
It's supposed to be the overview of the videos we provide, but got replaced with the overview of reporting, which appears later on the screen.  The overview of the videos we provide is no longer available.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/04f68c2f-8c66-4621-84a8-516376645b95)

**Comment by lpgoldstein** [comment]
@mcharg ready for your review http://2017onrr/reportpay/training/index.htm

**Comment by lpgoldstein** [comment]
live so closing
