### ISSUE TITLE
Remove RRM videos

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1840]
I confirmed with Aaron that he'd like these videos removed from the current website and not included in the new website. The team will eventually remake these videos in the future.  

- [x] Remove videos from current website

- [x] Update video inventory excel sheet with "Removed by SME request" or something along those lines

- [x] Unlink the videos from the CMS if they were added

[https://app.zenhub.com/files/210892300/fa1f4d9b-bcf0-4a43-a93d-77cdf68a8b2c/download](https://app.zenhub.com/files/210892300/fa1f4d9b-bcf0-4a43-a93d-77cdf68a8b2c/download)

**Comment by cthomasONRR** [comment]
- [ ] Basic eCommerce Navigation Series - part 1  https://youtu.be/iQh2DIqfOkE
- [ ] New Payor Overview https://youtu.be/NJPtpJnOxiA
- [ ] Overview of reporting to ONRR  https://youtu.be/Qi0RISYbJP4
- [ ] New Operator Overview  https://youtu.be/waNh3gxCBW0
- [ ] OGOR Edits: 11030, 11050  https://youtu.be/JKF0s9TLDm0
- [ ] OGOR Edits: 11259  https://youtu.be/gpaOFORYxhw
- [ ] OGOR Video Series: How to Manually Submit an OGOR Part C https://youtu.be/fuhvCrUYbJI

**Comment by mcharg** [comment]
@cthomasONRR Do you want to remove from the old site and I'll remove the links I added in the CMS?

**Comment by cthomasONRR** [comment]
@mcharg Sounds good- I'm working on removing the links from the old site right now

**Comment by mcharg** [comment]
@cthomasONRR There are 4 more that need to be removed. There was a "correct" filter applied to the list that shouldn't have.

- [ ] Form 2014 Series: Basic Overview: Form ONRR-2014 https://youtu.be/Moafa_VqzPo
- [ ] OGOR Edits: 11260 https://youtu.be/krz19kKUTRo
- [ ] Online Rentals Part 1:  Basic Overview https://youtu.be/vbT0PAh-kko
- [ ] Online Rentals Part 2: Add New Lease https://youtu.be/DIWxSpn-uXY

**Comment by mcharg** [comment]
Removed from CMS:
- [ ] Basic eCommerce Navigation Series - part 1  https://youtu.be/iQh2DIqfOkE
- [ ] New Payor Overview https://youtu.be/NJPtpJnOxiA
- [ ] Overview of reporting to ONRR  https://youtu.be/Qi0RISYbJP4
- [ ] New Operator Overview  https://youtu.be/waNh3gxCBW0
- [ ] OGOR Edits: 11030, 11050  https://youtu.be/JKF0s9TLDm0
- [ ] OGOR Edits: 11259  https://youtu.be/gpaOFORYxhw
- [ ] OGOR Video Series: How to Manually Submit an OGOR Part C https://youtu.be/fuhvCrUYbJI
- [ ] - [ ] Form 2014 Series: Basic Overview: Form ONRR-2014 https://youtu.be/Moafa_VqzPo
- [ ] OGOR Edits: 11260 https://youtu.be/krz19kKUTRo
- [ ] Online Rentals Part 1:  Basic Overview https://youtu.be/vbT0PAh-kko
- [ ] Online Rentals Part 2: Add New Lease https://youtu.be/DIWxSpn-uXY

**Comment by mcharg** [comment]
@cthomasONRR They're all removed from the CMS. The Video Locations tab shows the pages I removed them from. Will you please review?

**Comment by cthomasONRR** [comment]
@mcharg Could you please respond to my slack messages or give me a call? I'm having a ton of issues with html formatting when removing from the old site

**Comment by cthomasONRR** [comment]
@mcharg The following webpages are ready for your review before I go live:
- [ ] http://2017onrr/reportpay/payments.htm
- [ ] http://2017onrr/reportpay/training/index.htm
- [ ] http://2017onrr/reportpay/training/OGOR-Training-Videos.htm
- [ ] http://2017onrr/reportpay/training/2014-Training-Videos.htm

Working on reviewing the CMS now

**Comment by cthomasONRR** [comment]
@mcharg CMS looks good- approved!

**Comment by mcharg** [comment]
@cthomasONRR Dev on the old site looks good. Approved to push live!

**Comment by cthomasONRR** [comment]
@mcharg The live site updated. Closing this issue now.
