### ISSUE TITLE
Minerals Revenue Reporter Handbook Appendix C Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1841]
Please replace Appendix C under the Supplemental Information tab for the Minerals Revenue Reporter Handbook with the attached on the following page - https://www.onrr.gov/reportpay/Handbooks/revenue-handbook/index.htm
[RRM-Appendix C (Final).pdf](https://github.com/ONRR/onrr.gov-site/files/8498178/RRM-Appendix.C.Final.pdf)

**Comment by cthomasONRR** [comment]
@bowlenj 

Good afternoon,
This update is now on the dev site: http://2017onrr/reportpay/Handbooks/revenue-handbook/index.htm
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by bowlenj** [comment]
This looks great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Friday, April 15, 2022 2:42 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Minerals Revenue Reporter Handbook Appendix C Update (Issue #1841)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C87bc6c31ef20494d268508da1f2074ca%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637856521944565484%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2F0q6LBHhOpJ0FVq20caehlgGJIDrsEx88Q8KSsiGKxM%3D&reserved=0>

Good afternoon,
This update is now on the dev site: http://2017onrr/reportpay/Handbooks/revenue-handbook/index.htm
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj Great! The changes are now live: https://www.onrr.gov/reportpay/Handbooks/revenue-handbook/index.htm

Closing this issue. Have a great weekend!
