### ISSUE TITLE
Glossary Meeting with Data Governance

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1842]
Wendy Ranone set a meeting invite for Thursday April 21 @ 9:30am

**Comment by Maroyafaied** [comment]
@cthomasONRR they also wanted to go to SME for "Trust Land"

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks, not sure who is SME is for that. Added it to the list, I had it marked in green on the spreadsheet.

**Comment by cthomasONRR** [comment]
Maroya emailed DGO this follow-up:

Hi,

To summarize our meeting today, here is a list of terms that DG's will need to get approval from SMEs. Please let us know when a SME approves a term and we will make the changes accordingly. Thanks

•	Agreement Number (April Lockler)
•	Lease (April Lockler)
•	Net Royalty (Amy Lunt)
•	Processing Allowance (Amy Lunt)
•	Transaction Code (April Locker)
•	Transportation Allowance (Amy Lunt & Solids SME)
•	Trust Land (Marvin?)

Maroya Faied


Closing this issue now.
