### ISSUE TITLE
Review Data Governance Glossary input

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1843]

**Comment by cthomasONRR** [comment]
Spreadsheet Wendy provided located here: https://teams.microsoft.com/l/file/1872EBEB-B9FC-4205-BEC8-52A8CEFA9769?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FCMS%2FCollections%2FGlossary%2FONRR-gov%20Glossary%20DGO%20Input%202022-04-15.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by cthomasONRR** [comment]
**Terms that will require SME approval to change**
- Agreement Number (April Lockler)
- Lease (April Lockler)
- Processing Allowance (Amy Lunt)

**Terms that should be removed**
- Serial Register Page (SRP)
- Surety

**Terms that we do not want to change because of one of the following: we know SME will not approve change, new definition too complicated for public website, want to keep the consistent definition from handbooks (Column C of the spreadsheet)**
- Compensatory Royalty Agreement
- Disposition Code
- Net Royalty
- Oil
- Outer Continental Shelf (OCS)
- Product
- Production Allocation Schedule Report (PASR)
- Rent
- Royalty in Kind
- Royalty in Value
- Solid Minerals
- Subsurface Rights
- Surface Management Agency
- Surface Rights
- Transaction Code
- Transportation Allowance
- Trust Land
- Unit Value
- Well Status Code

**Terms where will will accept DGO's changes (Column A of spreadsheet)**
- BIA
- Buy-Back Volumes
- Coal
- Contact 
- Cooperative Agreement
- Dual Accounting
- FIMO
- Facility Measurement Point (FMP)
- Federal Land
- Fee Land
- Formation
- Geothermal Revenue
- Index
- Jointly-Owned Lease Payment
- Lessee
- Minimum Royalty Payment
- OGOR
- Payor Code
- Royalty
- State Lands

**Comment by Maroyafaied** [comment]
@cthomasONRR I send this to Ryan by email and he'll let me know if we need to meet prior to Thursday's meeting.
