### ISSUE TITLE
Update corrected table summary files 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1844]
Related to issue #1768 , Carrie corrected some docs and Christina was going to take over. We need to update the current website with the accessible files and tag these files with "update" in CMS.

[Spreadsheet ](https://teams.microsoft.com/l/file/56CFB7DB-F3DC-4B43-A486-C2ADAAD400EC?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2F508%2FTableErrors.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)with documents with table errors

[Folder](https://teams.microsoft.com/_#/files/General?threadId=19%3A34f9f9ee6b0441dbacab56bfd552f819%40thread.skype&ctx=channel&context=Accessible%2520Table%2520Summary%2520Docs&rootfolder=%252Fsites%252FNRRD%252FShared%2520Documents%252FGeneral%252FONRR.gov%252F508%252FAccessible%2520Table%2520Summary%2520Docs) with accessible docs

**Comment by cthomasONRR** [comment]
The following files are updated on onrr.gov and have update tags in the CMS:

- [ ] [2014CLEdits.pdf](https://github.com/ONRR/onrr.gov-site/files/8515620/2014CLEdits.pdf)

- [ ]  [FY2020_Disbursements_Texas_Press_Release.pdf](https://github.com/ONRR/onrr.gov-site/files/8515623/FY2020_Disbursements_Texas_Press_Release.pdf) **Duplicate file in the press release collection**

- [ ] [Meeker-UCA-20170816.pdf](https://github.com/ONRR/onrr.gov-site/files/8515624/Meeker-UCA-20170816.pdf) **not found in the cms... unbundling collection still needed?**

- [ ] [MPRH-Chapter-2.pdf](https://github.com/ONRR/onrr.gov-site/files/8515625/MPRH-Chapter-2.pdf)

- [ ] [MPRH-Glossary.pdf](https://github.com/ONRR/onrr.gov-site/files/8515626/MPRH-Glossary.pdf)

- [ ] [RRM-Appendix.C.pdf](https://github.com/ONRR/onrr.gov-site/files/8515627/RRM-Appendix.C.pdf) **Updated by RRM on 4/15/22**

- [ ] [SMRH.Complete.Handbook.pdf](https://github.com/ONRR/onrr.gov-site/files/8515628/SMRH.Complete.Handbook.pdf)

- [ ] [SMRH_Appendix_E.pdf](https://github.com/ONRR/onrr.gov-site/files/8515630/SMRH_Appendix_E.pdf)

- [ ] [SMRH_Chapter_3.pdf](https://github.com/ONRR/onrr.gov-site/files/8515632/SMRH_Chapter_3.pdf)

- [ ] [2018.pdf](https://github.com/ONRR/onrr.gov-site/files/8515633/2018.pdf)

- [ ] [2019.pdf](https://github.com/ONRR/onrr.gov-site/files/8515634/2019.pdf)

- [ ] [2020.pdf](https://github.com/ONRR/onrr.gov-site/files/8515635/2020.pdf)

- [ ] [2020_GOMESA_LA.pdf](https://github.com/ONRR/onrr.gov-site/files/8515636/2020_GOMESA_LA.pdf)

- [ ] [4109.pdf](https://github.com/ONRR/onrr.gov-site/files/8515637/4109.pdf)

- [ ] [Codes_for_2014.pdf](https://github.com/ONRR/onrr.gov-site/files/8515638/Codes_for_2014.pdf)

- [ ] [Echo_Springs_UCA_Table_w_Example_Correction_2018.2.1.pdf](https://github.com/ONRR/onrr.gov-site/files/8515639/Echo_Springs_UCA_Table_w_Example_Correction_2018.2.1.pdf) **not found in the cms... unbundling collection still needed?**

**Comment by cthomasONRR** [comment]
I checked just now, and there are no additional updated documents in the "508 Done" folder.

**Comment by cthomasONRR** [comment]
@Maroyafaied @mcharg In the spreadsheet linked above, there are 40 more documents that need fixing. But the folder linked above only has 14 documents in need of fixing. Do I have to hunt down the addition 26 and add them to the folder?

**Comment by mcharg** [comment]
I don't know anything about the folder. I think @Maroyafaied created it.

**Comment by cthomasONRR** [comment]
@mcharg I'm correcting the unbundling ones and updating them in the Y and Z drives. They are just not in the CMS yet, that's why I'm flagging them.

**Comment by cthomasONRR** [comment]
I corrected the following 10 files myself. The following files are updated on onrr.gov and have update tags in the CMS.

- [ ] [FY2020_Disbursements_North_Dakota_Press_Release.pdf](https://github.com/ONRR/onrr.gov-site/files/8565515/FY2020_Disbursements_North_Dakota_Press_Release.pdf)
- [ ] [FY2020_Disbursements_Wyoming_Press_Release.pdf](https://github.com/ONRR/onrr.gov-site/files/8565516/FY2020_Disbursements_Wyoming_Press_Release.pdf)
- [ ] [Louisiana.GOMESA.Release.3.30.pdf](https://github.com/ONRR/onrr.gov-site/files/8565517/Louisiana.GOMESA.Release.3.30.pdf)
- [ ] [Mississippi.GOMESA.Release.3.30.pdf](https://github.com/ONRR/onrr.gov-site/files/8565518/Mississippi.GOMESA.Release.3.30.pdf)
- [ ] [San Juan Transportation System - Chaco Gas Plant.pdf](https://github.com/ONRR/onrr.gov-site/files/8565519/San.Juan.Transportation.System.-.Chaco.Gas.Plant.pdf)
- [ ] [2020_GOMESA.pdf](https://github.com/ONRR/onrr.gov-site/files/8565520/2020_GOMESA.pdf)
- [ ] [2021_gomesa_Texas.pdf](https://github.com/ONRR/onrr.gov-site/files/8565521/2021_gomesa_Texas.pdf)
- [ ] [Alabama.GOMESA.Release.3.30.pdf](https://github.com/ONRR/onrr.gov-site/files/8565522/Alabama.GOMESA.Release.3.30.pdf)
- [ ] [FY2020_Disbursements_Louisiana_Press_Release.pdf](https://github.com/ONRR/onrr.gov-site/files/8565523/FY2020_Disbursements_Louisiana_Press_Release.pdf)
- [ ] [FY2020_Disbursements_New_Mexico_Press_Release.pdf](https://github.com/ONRR/onrr.gov-site/files/8565524/FY2020_Disbursements_New_Mexico_Press_Release.pdf)

**Comment by cthomasONRR** [comment]
I corrected the following 10 files myself. The following files are updated on onrr.gov and have update tags in the CMS.

- [ ] [2020_GOMESA_MS.pdf](https://github.com/ONRR/onrr.gov-site/files/8566103/2020_GOMESA_MS.pdf)
- [ ] [2020_GOMESA_TX.pdf](https://github.com/ONRR/onrr.gov-site/files/8566104/2020_GOMESA_TX.pdf)
- [ ] [20131119.pdf](https://github.com/ONRR/onrr.gov-site/files/8566105/20131119.pdf)
- [ ] [All States GOMESA Release 3.30.pdf](https://github.com/ONRR/onrr.gov-site/files/8566106/All.States.GOMESA.Release.3.30.pdf)
- [ ] [FINAL Interagency SOP - 09-23-13.pdf](https://github.com/ONRR/onrr.gov-site/files/8566107/FINAL.Interagency.SOP.-.09-23-13.pdf)
- [ ] [Fiscal_Year_2021_Disbursements_Press_Release.pdf](https://github.com/ONRR/onrr.gov-site/files/8566108/Fiscal_Year_2021_Disbursements_Press_Release.pdf)
- [ ] [GOMESA.National.Release.pdf](https://github.com/ONRR/onrr.gov-site/files/8566109/GOMESA.National.Release.pdf)
- [ ] [11-13-DOI-SummaryDisbursementsData.pdf](https://github.com/ONRR/onrr.gov-site/files/8566110/11-13-DOI-SummaryDisbursementsData.pdf)
- [ ] [12-14-FY-2014-SummaryDisbursements.pdf](https://github.com/ONRR/onrr.gov-site/files/8566111/12-14-FY-2014-SummaryDisbursements.pdf)
- [ ] [2020_GOMESA_AL.pdf](https://github.com/ONRR/onrr.gov-site/files/8566112/2020_GOMESA_AL.pdf)

**Comment by cthomasONRR** [comment]
I corrected the following 9 files myself. The following files are updated on onrr.gov and have update tags in the CMS. I've reached my limit in 508 remediation knowledge- we need Christina's help on the remaining 10. We might need to go back to SMEs to see if they have better documents, because the table header errors are very time-consuming.

- [ ] [Enterprise Carlsbad Transportation System and Dew Point Plant.pdf](https://github.com/ONRR/onrr.gov-site/files/8566590/Enterprise.Carlsbad.Transportation.System.and.Dew.Point.Plant.pdf) **Not in CMS… collection needed**
- [ ] [Onshore Std UCA Example_San Juan Basin_9.12.18 LS FINAL.pdf](https://github.com/ONRR/onrr.gov-site/files/8566591/Onshore.Std.UCA.Example_San.Juan.Basin_9.12.18.LS.FINAL.pdf)
- [ ] [Onshore Std UCA Example_Green River Basin_9.12.18 LS FINAL.pdf](https://github.com/ONRR/onrr.gov-site/files/8566592/Onshore.Std.UCA.Example_Green.River.Basin_9.12.18.LS.FINAL.pdf)
- [ ] [Neptune-UCA-Tables-2008-2015-with-Example.pdf](https://github.com/ONRR/onrr.gov-site/files/8566593/Neptune-UCA-Tables-2008-2015-with-Example.pdf) **Not in CMS… collection needed**
- [ ] [RRM-Chapter.9.pdf](https://github.com/ONRR/onrr.gov-site/files/8566594/RRM-Chapter.9.pdf)
- [ ] [GOMESA-Mississippi-2019.pdf](https://github.com/ONRR/onrr.gov-site/files/8566595/GOMESA-Mississippi-2019.pdf)
- [ ] [Press_Release2020_Proposed_Valuation_Reform_and_Civil_Penalty_Rule.pdf](https://github.com/ONRR/onrr.gov-site/files/8566596/Press_Release2020_Proposed_Valuation_Reform_and_Civil_Penalty_Rule.pdf)
- [ ] [20070723.pdf](https://github.com/ONRR/onrr.gov-site/files/8566597/20070723.pdf)
- [ ] [900913.pdf](https://github.com/ONRR/onrr.gov-site/files/8566598/900913.pdf)

**Comment by cthomasONRR** [comment]
@Maroyafaied Should I email both Carrie and Christina as a follow-up? Here is a draft email:

Hi Carrie and Christina,

I wanted to follow up on the GitHub Issue # [# 1768](https://github.com/ONRR/onrr.gov-site/issues/1768) that Maroya created for you.

I had some time last week and earlier this week to complete most of the documents that were showing various table errors in the Adobe 508 accessibility check. There are 10 documents left, and these remaining 10 are all above my 508 PDF remediation proficiency level to resolve. Do either of you have time to see if you can remediate these 10?

The documents folder is located [here](https://teams.microsoft.com/_#/files/General?groupId=81f624a1-bcde-4f77-ba3b-69c787c88ed3&threadId=19%3A34f9f9ee6b0441dbacab56bfd552f819%40thread.skype&ctx=channel&context=Accessible%2520Table%2520Summary%2520Docs&rootfolder=%252Fsites%252FNRRD%252FShared%2520Documents%252FGeneral%252FONRR.gov%252F508%252FAccessible%2520Table%2520Summary%2520Docs). There are 6 docs in this linked folder and 4 more docs within the “Trouble Files” folder. I was able to resolve 2 in there, but the remaining are above my ability. If you are able to get any of these 10 docs resolved, you can move them to the “508 Done” folder.

Please let us know if either of you have time to help. We really appreciate it!

Thanks,
Christine

**Comment by Maroyafaied** [comment]
@cthomasONRR Yes, please go ahead and email them. Thanks

**Comment by cthomasONRR** [comment]
email sent

**Comment by cthomasONRR** [comment]
@Maroyafaied I'm thinking about emailing Jessica Bowlen and whoever else in RRM that might be able to resolve April Lockler's docs. Here's a draft email:

"Hi Jessica,

As you know, the most recent Adobe update is now flagging table header errors. After talking with Sid Sharma, all table errors need to be remediated. We've been able to correct the majority of these, but there are 4 docs within RRM that are above my skill level to remediate. Would you, or someone else in your team, be able to fix the following 4 documents? Errors are mostly constrained to table headers and table summaries.

Here's the list of docs:
- https://www.onrr.gov/reportpay/Handbooks/pdfdocs/MPRH-Appendix-E.pdf
- https://www.onrr.gov/reportpay/Handbooks/pdfdocs/MPRH-Chapter-4.pdf
- https://www.onrr.gov/ReportPay/Handbooks/revenue-handbook/pdfs/RRM-Appendix.E.pdf
- https://www.onrr.gov/ReportPay/PDFDocs/Error_Msg_Production_HOW_TO.pdf

Please let us know if you will be able to correct these 4 docs.

Thanks,
Christine"

**Comment by Maroyafaied** [comment]
@cthomasONRR please include Aaron Lindquist and Shannon H in the email. Thanks

**Comment by cthomasONRR** [comment]
email sent

**Comment by cthomasONRR** [comment]
We have all of RRM's docs completed save for "https://www.onrr.gov/ReportPay/Handbooks/revenue-handbook/pdfs/RRM-Appendix.E.pdf" which is on hold as RRM needs to coordinate with RV on transaction codes.

**Comment by Maroyafaied** [comment]
@cthomasONRR  I will send Amy's doc to Jodie. https://www.onrr.gov/valuation/PDFDocs/Processed%20Gas%20Example%20Final%2005262020.pdf

**Comment by Maroyafaied** [comment]
I sent the fedwire doc to be corrected by the document owners.

**Comment by cthomasONRR** [comment]
I have the following document updated in the Y, Z, and CMS locations.

 https://www.onrr.gov/reportpay/PDFDocs/4110.pdf (owner: James Smith)

**Comment by Maroyafaied** [comment]
will create a new issue for the 2 docs left.
