### ISSUE TITLE
Updates to ONRR.govs Current ICR's

### ISSUE THREAD

**Issue by gingerhensley** [ONRR/onrr.gov-site#1845]
Good afternoon, 

I am requesting updates to this page https://onrr.gov/Laws_R_D/FRNotices/ICR0120.htm 
Under the Federal Register Publications heading, please add a bullet to the top of the list. The bullet should read as follows: “60-Day Agency Information Collection - (87 FR 21921--April 13, 2022)”

Please add this hyperlink to the language in the parenthesis: https://www.federalregister.gov/documents/2022/04/13/2022-07893/agency-information-collection-activities-solid-minerals-and-geothermal-collections

Please let me know if you have any questions. 
Ginger Hensley

**Comment by cthomasONRR** [comment]
@gingerhensley This update is on the dev site: http://2017onrr/Laws_R_D/FRNotices/ICR0120.htm. Please review and give us your approval to go live.

@Maroyafaied This ICR page is also update on the CMS.

Thanks,
Christine

**Comment by gingerhensley** [comment]
Hi Christine, I have reviewed the updates and approve. 

Thank you!

**Comment by cthomasONRR** [comment]
@gingerhensley Great, the changes are now live: https://onrr.gov/Laws_R_D/FRNotices/AA29.htm. Please remember to use "Ctrl+F5" to refresh the page. I will close this issue now. Thanks, Christine.
