### ISSUE TITLE
Replace outdated SOP Attachment with new one

### ISSUE THREAD

**Issue by ONRRamandagarrison** [ONRR/onrr.gov-site#1848]
At the bottom of the page (https://www.onrr.gov/About/MOUs-and-SOPs.htm), there is a .pdf labeled [Interagency SOP Attachment A Addendum 1]. This will need to be replaced with a new, updated version that is 508 compliant. It will be called Interagency SOP Attachment A Addendum 2 (effective 2.10.2022).  The .pdf is attached.

![image](https://user-images.githubusercontent.com/62029054/164106590-d17bf3a1-7e40-4fed-8e65-c08403c2397c.png)
[For Distribution - Interagency SOP Attachment A Addendum 2 (Effective 2.10.2022)_508.pdf](https://github.com/ONRR/onrr.gov-site/files/8516639/For.Distribution.-.Interagency.SOP.Attachment.A.Addendum.2.Effective.2.10.2022._508.pdf)

**Comment by Maroyafaied** [comment]
@lpgoldstein please make this update and tag this doc with "update" in the cms. Thanks

**Comment by lpgoldstein** [comment]
Sorry just seeing this

**Comment by lpgoldstein** [comment]
@ONRRamandagarrison Ready for your review: http://2017onrr/about/MOUs-and-SOPs.htm

**Comment by ONRRamandagarrison** [comment]
Lindsay,

Looks good! It's ready to be published.

Thank you,
Amanda

Amanda Garrison

IESC Supervisory Minerals Revenue Specialist
Indian Energy Service Center
P: (720) 595-2025
C: (720) 219-3272
***@***.***

From: lpgoldstein ***@***.***>
Sent: Thursday, April 21, 2022 11:27 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Garrison, Amanda T ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Replace outdated SOP Attachment with new one (Issue #1848)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@ONRRamandagarrison<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRRamandagarrison&data=05%7C01%7Camanda.garrison%40onrr.gov%7C7ce5b939775e4d1edba108da23bc36b5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637861588964721065%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=66DYInKCygKne4QEe0tENstErbYIk7DhEhIplK4a5Ag%3D&reserved=0> Ready for your review: http://2017onrr/about/MOUs-and-SOPs.htm

-

**Comment by lpgoldstein** [comment]
@ONRRamandagarrison It's live!

**Comment by ONRRamandagarrison** [comment]
Yay! Thank you so much!


Amanda Garrison

IESC Supervisory Minerals Revenue Specialist



IESC Mineral Services, Leasing, and Production

Indian Energy Service Center |

Office of Natural Resources Revenue

13922 Denver West Parkway, <x-apple-data-detectors://10/0>

Building 54, Suite 300 <x-apple-data-detectors://10/0>

Lakewood, CO 80401<x-apple-data-detectors://10/0>

P:(720) 595-2025

C:(720) 219-3272

***@***.******@***.***>



For more information, you can visit: https://www.onrr.gov/IndianServices/indian-energy-service-center.htm<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2FIndianServices%2Findian-energy-service-center.htm&data=04%7C01%7CAmanda.Garrison%40onrr.gov%7C5d3b664c5a1d4d65a3ff08d936a3435d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637600897101004481%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=eBClScUF%2BllEIUkaGA71q0mOgNa5PemRpodahNzHGhk%3D&reserved=0>



Need assistance? Fill out this form: Request for IESC Assistance Digital Referral Form<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.office.com%2FPages%2FResponsePage.aspx%3Fid%3DurWTBhhLe02TQfMvQApUlAG9FkklRGNHoggEpBcwhwpUNlQ2VFZOOFUxRDdEUk80TDBCNVI2RDBFMyQlQCN0PWcu&data=04%7C01%7CAmanda.Garrison%40onrr.gov%7C5d3b664c5a1d4d65a3ff08d936a3435d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637600897101014436%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Mu4bPkyuE9ftue9OPAAvD1RQzPWjlIi7v4JUZwwU%2FIc%3D&reserved=0>





Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you received this communication in error, please notify the sender immediately by return email and delete this message.

On Apr 21, 2022, at 3:40 PM, lpgoldstein ***@***.***> wrote:

﻿



 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@ONRRamandagarrison<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRRamandagarrison&data=05%7C01%7Camanda.garrison%40onrr.gov%7C415813784c3b47fc518708da23df947b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637861740427485293%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=W0WReGZp1Tsv1MnM1zoMLLPDrAV0%2FqmIpoRUcOmbtm8%3D&reserved=0> It's live!

**Comment by mcharg** [comment]
File updated in CMS.
