### ISSUE TITLE
Update CMS with new regulation page

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1849]
See issue #1847

I need to:

- [x] Create a new webpage for AA28
- [x] Add the new webpage to the Rulemakings collection

**Comment by cthomasONRR** [comment]
New AA-28 regulation page located here: https://dev-onrr-frontend.app.cloud.gov/references/rulemakings/aa28

Updated Rulemakings collection located here: https://dev-onrr-frontend.app.cloud.gov/references/rulemakings

**Comment by cthomasONRR** [comment]
@mcharg Want to review this?

**Comment by mcharg** [comment]
@cthomasONRR Looks good.
