### ISSUE TITLE
Couple items to "put"

### ISSUE THREAD

**Issue by jpetersononrr** [ONRR/onrr.gov-site#185]
Hi!

Could you please put the following for me?  With an additional example, I had to update a few things on the previous one (like a link to the new one).  Thank you!

1.  This page:  https://www.onrr.gov/valuation/2016-rule-processed-example.htm
2.  The image file for valuation
3.  The pdf "Processed-Gas-Example-Final-05262020"

Thanks for your help!

**Comment by jennmalcolm** [comment]
This is done. Please review it on the live site. Thanks.

**Comment by jpetersononrr** [comment]
Thank you!  Looks great!!
