### ISSUE TITLE
Add LVS-GVS overview video to CMS and current site

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1850]
This was in the YouTube Channel, but not on the live site Aaron would like it added. I'll add it to both the current and new sites.
https://youtu.be/82QVP2lrFgU

**Comment by mcharg** [comment]
Added to old site: http://2017onrr/reportpay/training/OGOR-Training-Videos.htm
And new site: https://dev-onrr-frontend.app.cloud.gov/references/training?tabs=training-videos,oil-gas-production&panel=liquid-verification-system-lvs-gas-verification-system-gvs

**Comment by mcharg** [comment]
Aaron approved via chat, so pushing live.

**Comment by mcharg** [comment]
Also added to troubleshooting.
https://dev-onrr-frontend.app.cloud.gov/reporting/production?tabs=troubleshooting&panel=i-need-to-understand-how-to-file-an-oil-gas-operators-report-ogor

**Comment by mcharg** [comment]
@lpgoldstein Do you want to review in the CMS?

**Comment by mcharg** [comment]
Live on the old site. https://www.onrr.gov/reportpay/training/OGOR-Training-Videos.htm

**Comment by lpgoldstein** [comment]
@mcharg Looks good!
