### ISSUE TITLE
Dear Reporter Letter

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1852]
Please add the attached letters (1 signed - not 508 and 1 unsigned 508 version) to the following web page - https://www.onrr.gov/DearRep.htm
[Navajo Dear Reporter RIK Program.pdf](https://github.com/ONRR/onrr.gov-site/files/8521952/Navajo.Dear.Reporter.RIK.Program.pdf)
[Navajo Dear Reporter RIK Program (signed).pdf](https://github.com/ONRR/onrr.gov-site/files/8521953/Navajo.Dear.Reporter.RIK.Program.signed.pdf)

**Comment by lpgoldstein** [comment]
@bowlenj What date do you want to put on this letter?

**Comment by bowlenj** [comment]
Lets do 04/18/2022, that's the date Yvette signed it.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: lpgoldstein ***@***.***>
Sent: Wednesday, April 20, 2022 8:53 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Dear Reporter Letter (Issue #1852)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Ca1a408c058a3498ed00208da22dd8958%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637860632131308855%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=92PdYUYZgXQ97yX%2B7k8hAchnDgdnDm7KWtkjP6d%2BJXE%3D&reserved=0> What date do you want to put on this letter?

**Comment by lpgoldstein** [comment]
@bowlenj please review http://2017onrr/DearRep.htm

**Comment by lpgoldstein** [comment]
@mcharg please confirm in CMS properly 

Termination of Navajo Nation Royalty In-Kind Program (signed)

Termination of Navajo Nation Royalty In-Kind Program


https://dev-onrr-cms.app.cloud.gov/admin/content/reporter_letters
https://dev-onrr-frontend.app.cloud.gov/references/reporter-letters

**Comment by bowlenj** [comment]
This looks great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: lpgoldstein ***@***.***>
Sent: Wednesday, April 20, 2022 9:21 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Dear Reporter Letter (Issue #1852)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C352d158825094dd47c2b08da22e187be%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637860649285156603%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YkZmd%2FIq2zHVOYB5CNeAu2si51hrG9v3E9dizTiIqQA%3D&reserved=0> please review http://2017onrr/DearRep.htm

**Comment by mcharg** [comment]
@lpgoldstein Looks good in CMS.

**Comment by lpgoldstein** [comment]
@bowlenj It's live so I'm closing issue.
