### ISSUE TITLE
Add next and back links to the detailed example tabs in valuation examples

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1856]

**Comment by mcharg** [comment]
@cthomasONRR Isabel is going to work on this and will let you know when it's ready to review.

**Comment by cthomasONRR** [comment]
Sounds good!

**Comment by Isabelh99** [comment]
I have a question on the CMS: 
So far I've added the content blocks (location: https://dev-onrr-frontend.app.cloud.gov/references/valuation/processed-gas-example?tabs=detailed-example,pc-1) to all the examples remaining and published them. But they're not popping up on the dev onrr location I've assigned them to... I think I'm missing a step on CMS by switching placement of the navigation links..

**Comment by Isabelh99** [comment]
Also, can I add links to this one as well?
![image](https://user-images.githubusercontent.com/93946660/166748916-c6713d13-b0fb-421d-83b4-946addf6c0c9.png)
bottom tabs' location: https://dev-onrr-frontend.app.cloud.gov/references/valuation/pop-example

**Comment by mcharg** [comment]
@Isabelh99 There's a bug in the CMS at the moment where new content blocks can't be reordered on pages with long lists of subtabs. I can explain in our check-in.

Yes, you can add the links to the second example.

**Comment by Isabelh99** [comment]
Noted! And completed the other example.

**Comment by mcharg** [comment]
Yep, they're all at the end of the last tab. After the reordering bug gets fixed, we can put them in the correct spots.
![image](https://user-images.githubusercontent.com/38465926/166803259-489b43a3-7892-4ee4-8fda-429dca6fa6b0.png)

**Comment by cthomasONRR** [comment]
@mcharg I set these to "Draft" instead of "Published" until the Directus bug gets fixed.

**Comment by cthomasONRR** [comment]
@mcharg Next and Back links are in place. This is ready for your review.

**Comment by mcharg** [comment]
@cthomasONRR Looks good. I created a new issue to address the Assumptions panel reopening when you use the Next tab and Previous tab links.
