### ISSUE TITLE
Review Payments pages with SMEs

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1859]

**Comment by Maroyafaied** [comment]
Scheduled April 28th at 8:30am MT.

**Comment by Maroyafaied** [comment]
@cthomasONRR @mcharg I forwarded an email I received today with requested changes. Thanks

**Comment by mcharg** [comment]
I made the updates from the email and sent a response to the requestor.

**Comment by Maroyafaied** [comment]
We received an email approving the webpages by SME's. @mcharg please mark as approved by SME in the spreadsheet and close this issue. Thanks
