### ISSUE TITLE
ONRR Resource Production Reporting References Update

### ISSUE THREAD

**Issue by ONRR-31577** [ONRR/onrr.gov-site#186]
On the Production Reporting References page at https://onrr.gov/ReportPay/references.htm, in the Offshore section,
please
- replace the five Gulf link pdf files with the attached pdf files--the
file names are the same;
- replace the (as of ...) dates for all files with 28 May 2020.

Thank you,
[Gulf-Metering-Systems.pdf](https://github.com/ONRR/onrr.gov-site/files/4697930/Gulf-Metering-Systems.pdf)
[Gulf-Sales-Tanks.pdf](https://github.com/ONRR/onrr.gov-site/files/4697931/Gulf-Sales-Tanks.pdf)
[Gulf-Gas-Plants.pdf](https://github.com/ONRR/onrr.gov-site/files/4697932/Gulf-Gas-Plants.pdf)
[Gulf-Flash-Gas.pdf](https://github.com/ONRR/onrr.gov-site/files/4697933/Gulf-Flash-Gas.pdf)
[Gulf-Buy-Back.pdf](https://github.com/ONRR/onrr.gov-site/files/4697934/Gulf-Buy-Back.pdf)

**Comment by Maroyafaied** [comment]
@jennmalcolm @lpgoldstein I apologize, I didn't realize I was unassigned but I started working on this already, I'll add my name as assigned again and will send link to development soon.

**Comment by Maroyafaied** [comment]
@ONRR-31577 Please review the changes you requested in the development site and let me know if everything looks correct. Thanks
http://2017onrr/ReportPay/references.htm

**Comment by ONRR-31577** [comment]
Hi,
   I see the dates have been updated , but the files look to be the same as last month?



Johnny Erle

Office of Natural Resources Revenue (ONRR)
RRM Team 1A
Minerals Revenue Specialist-GVS
john.erle@onrr.gov<mailto:john.erle@onrr.gov>
303-231-3577
800-525-7922  ext.13577
fax: 303-231-3566
________________________________

**Comment by Maroyafaied** [comment]
@ONRR-31577 the documents should be updated now, please refresh your browser and check again. Thanks

**Comment by ONRR-31577** [comment]
They look great, thank you!



Johnny Erle

Office of Natural Resources Revenue (ONRR)
RRM Team 1A
Minerals Revenue Specialist-GVS
john.erle@onrr.gov<mailto:john.erle@onrr.gov>
303-231-3577
800-525-7922  ext.13577
fax: 303-231-3566
________________________________
