### ISSUE TITLE
Review Indian pages with SMEs

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1860]

**Comment by Maroyafaied** [comment]
Scheduled April 28th at 9am MT.

**Comment by cthomasONRR** [comment]
Regulations table made: https://dev-onrr-frontend.app.cloud.gov/indian/indian-references?tabs=regulations

**Comment by cthomasONRR** [comment]
Added SOP to references tab and fixed title to have "SOP" in all caps

https://dev-onrr-frontend.app.cloud.gov/indian/indian-references?tabs=references

**Comment by cthomasONRR** [comment]
Removed tabs in tribal consultation and removed "view scheduled consultations" link 
https://dev-onrr-frontend.app.cloud.gov/indian/tribal-consultation

**Comment by cthomasONRR** [comment]
email sent

**Comment by cthomasONRR** [comment]
Added IESC logo, and updated IESC contacts as per Amanda Garrison's email. Huge update to contacts. https://dev-onrr-frontend.app.cloud.gov/indian/assistance?tabs=contacts,indian-energy-service-center-iesc-contacts

**Comment by cthomasONRR** [comment]
Continuing to make edits as per Heidi's emails

**Comment by cthomasONRR** [comment]
I asked Heidi to check in with Amanda before I make any more changes.

**Comment by Maroyafaied** [comment]
We met with Heidi and her team today, we made some changes as we're talking.  The only change we haven't done yet is moving the Tribal Assistance tab after Choosing Assistance and adding Marvin as a contact (request send by email after the meeting).

 I created issue #1906 to work on reducing the grade level for the content changes, and will send our recommendations to Heidi for her approval.

**Comment by mcharg** [comment]
@Maroyafaied Can we mark the Indian pages as approved by SME?

**Comment by Maroyafaied** [comment]
@mcharg I sent an email asking Heidi if we have her final approval or if she wants to wait until the tribal assistance tab is moved and for the FIMO contacts updates.

**Comment by Maroyafaied** [comment]
@mcharg Heidi gave her final approval. Please update the spreadsheet and close this issue. Thanks

**Comment by mcharg** [comment]
Marked as approved in the spreadsheet.
