### ISSUE TITLE
Review Valuation pages with SMEs

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1862]

**Comment by Maroyafaied** [comment]
@cthomasONRR Thanks! I sent Jodi an invite for June 13th.

**Comment by cthomasONRR** [comment]
I resolved all their requested updated. I created Issue #2003 for the one that is blocked by the Directus bug.

**Comment by cthomasONRR** [comment]
Jodie emailed her approval, so I marked RV's pages as "approved by SME" in the content tracking sheet.
