### ISSUE TITLE
Review About pages with SMEs

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1864]

**Comment by mcharg** [comment]
Reviewed wireframes with: Kimbra Davis, Howard Cantor, Nathan Brannberg, Heidi Murphy, Nichelle Rogers

**Comment by Maroyafaied** [comment]
@mcharg @lpgoldstein email sent and cc'd both of you.

**Comment by mcharg** [comment]
About ONRR
- [ ] Can we link to a pdf version of the strategic plan one-pager instead of a PowerPoint?  
SM: I explained that PDFs have accessibility issues, so Howard said he's okay with staying in PPT.

- [ ] Under "Our History," "...our offices responsibilities..." should be "our offices' responsibilities..."

Organization and Leadership
- [ ] Please delete the last sentence of Bonnie's bio ("She lives in Colorado with her husband and two Italian Greyhounds.")
- [ ] Please replace the org chart with the version we have used in recent ONRR presentations (please contact Joe Coleman).
SM: I emailed Joe.
- [ ] Budget Justification -- Isn't there a page with FY22 justifications?  
SM: I don't think there is one.
- [ ] Also, can we point out to the reader that ONRR is listed under Office of the Secretary Department-wide Programs?  
Employment
- [ ] Please touch base with Heidi to ensure we are participating in the Pathways Programs, and whether we participate in any of the other programs listed on the linked page.
Engagement 
- [ ] Please reach out to Yvette Smith regarding STRAC and ask if we still want to refer to it as a "committee" or if instead we should talk about our "partnerships" with states and tribes under FOGRMA 202 and 205.
- [ ] Do we need to list the other committees, given that they each have terminated?  Please talk to Bonnie and anyone else she believes appropriate.

Interagency Coordination
- [ ] I think there may be an updated ONRR/BOEM/BSEE MOU.  Please check with Jennifer Goldblatt.  
- [ ] Also, I think the two hyperlinks (Collaboration on Processes, Policies and Systems Relating to the Management of Outer Continental Shelf and Energy and Marine Mineral Development MOU) take you to the same document.
SM: This is one link. I made it a bullet to make it clear it's one link.
- [ ] There is no document linked under "Federal Indian Mineral Office (FIMO) MOU."
SM: We were told to remove the document.  I think by Amanda.

**Comment by Maroyafaied** [comment]
Sent Howard an email updating him and asked if he wants us to add EITI in the engagement section.

**Comment by mcharg** [comment]
All changes addressed.
