### ISSUE TITLE
Interest Calculator

### ISSUE THREAD

**Issue by bbell0229** [ONRR/onrr.gov-site#1872]
Hello,

On the Late Payment & Underpayment Interest Tables page, at https://onrr.gov/ReportPay/interest.htm, please make the following updates:
1.replace the interest Calculator Excel file below the Questions/Contact box on the page with the attached file.
[Interest_Calculator_Master.xlsx](https://github.com/ONRR/onrr.gov-site/files/8534991/Interest_Calculator_Master.xlsx)

Thank you,

Brittney

**Comment by Maroyafaied** [comment]
@bbell0229 please review http://2017onrr/reportpay/interest.htm

**Comment by bbell0229** [comment]
Looks good.

Brittney A. Bell
Staff Accountant, Financial Services
Revenue, Reporting, & Compliance Management
Office of Natural Resources Revenue
Bldg 85, Denver Federal Center
Denver, CO 80225
1-800-433-9801 x 3381
303.231.3381
***@***.******@***.***>

From: Maroyafaied ***@***.***>
Sent: Thursday, April 21, 2022 3:40 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bell, Brittney A ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Interest Calculator (Issue #1872)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bbell0229<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbbell0229&data=05%7C01%7Cbrittney.bell%40onrr.gov%7Cf5e42ab69271469376b708da23df7af4%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637861739996438993%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8K1%2FEl9B4Sb5Wcv8IYlaYv3Q%2B6n8y2%2F2TWrmJFbWIyk%3D&reserved=0> please review http://2017onrr/reportpay/interest.htm

-

**Comment by lpgoldstein** [comment]
@bbell0229 Should be live soon. I'll close out the issue once I can see the change on the live site.
