### ISSUE TITLE
Update collections spreadsheets with new urls

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1874]
The current spreadsheets link to the old site. We need to update the spreadsheets with the links to the pdfs on the new site.

**Comment by mcharg** [comment]
@Maroyafaied Who do you want to work on this?

**Comment by mcharg** [comment]
Spreadsheet location: https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/CMS/Collections/Handbooks?csf=1&web=1&e=4UqMxf

**Comment by mcharg** [comment]
We should discuss in synch up tomorrow to make sure we're putting in what @jlouis-onrr needs for the urls.

**Comment by lpgoldstein** [comment]
@mcharg I can work on this
