### ISSUE TITLE
Consolidate findings for eCommerce & WebCenter portal

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1876]
Look at previous user research notes for findings on ONRR's reporting systems to share with ONRR's IT modernization manager.

**Comment by Maroyafaied** [comment]
https://doimspp.sharepoint.com/:x:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7BAA698DB3-E8F9-428C-A868-4E7018B320A5%7D&file=OtherSystemFindings.xlsx&action=default&mobileredirect=true

**Comment by lpgoldstein** [comment]
@Maroyafaied This is ready for your review: https://doimspp.sharepoint.com/:x:/s/NRRD/EbONaar56IxCqGhOcBizIKUBk3mBRQ0rqRUb3AgbgVcoyA?email=Maroya.Faied%40onrr.gov&e=aQqdVH

**Comment by Maroyafaied** [comment]
@mcharg @lpgoldstein This is great, I didn't think we have that many findings. I will share it with Nathan and IT managers.
