### ISSUE TITLE
Separate out category levels on search results filters

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1878]
We don't need to filter for albequerque until you've filtered for Indian Services and FIMO.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/c54ddce2-9d9d-4917-b554-fc03d4a6a03c)

Wireframe:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/08196c01-4bfd-4399-ba7e-b85da0b5f1c7)

**Comment by mcharg** [comment]
@jlouis-onrr That works.

**Comment by jlouis-onrr** [comment]
:+1:

**Comment by jlouis-onrr** [comment]
@mcharg, this is now in dev

**Comment by mcharg** [comment]
@jlouis-onrr Looks good.
