### ISSUE TITLE
Figure out how to upload a spreadsheet for production contacts

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1879]
We met with @codyeckstein about being able to upload a spreadsheet pulled out of Peoplesoft for weekly production contact updates.

**Comment by mcharg** [comment]
Spreadsheet: 
[ANALYST_RESPONSIBILITY_PUB_05092022.xlsx](https://github.com/ONRR/onrr.gov-site/files/8689943/ANALYST_RESPONSIBILITY_PUB_05092022.xlsx)

**Comment by cthomasONRR** [comment]
@lpgoldstein I think we completed this issue already this sprint
