### ISSUE TITLE
OGOR CSV Record Layout

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#1881]
Hello, please replace the current OGOR CSV record layout with the attached file at 
https://onrr.gov/reportpay/production-reporting.htm.

Thank you!

[_OGOR-REPORTING-INSTRUCTIONS-CSV-FORMAT 20220401 (1).pdf](https://github.com/ONRR/onrr.gov-site/files/8572589/_OGOR-REPORTING-INSTRUCTIONS-CSV-FORMAT.20220401.1.pdf)

**Comment by cthomasONRR** [comment]
@merrellc 

Good morning, this new file is now on the dev site: http://2017onrr/reportpay/production-reporting.htm. Please review and give us your approval to go live.

Thanks,
Christine

**Comment by merrellc** [comment]
Approve to go live.  Thank you!


Kind Regards,
​Candace Merrell
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.
________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, April 27, 2022 7:59 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] OGOR CSV Record Layout (Issue #1881)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@merrellc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmerrellc&data=05%7C01%7Ccandace.merrell%40onrr.gov%7Cfd0c05cc2c9b4f2685a308da28561e1b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637866647583057840%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3z3K0SlQqsmmMB5X8fWhh4tDdci%2BzFltVyZd2A7EB7Y%3D&reserved=0>

Good morning, this new file is now on the dev site: http://2017onrr/reportpay/production-reporting.htm. Please review and give us your approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@merrellc Great! The changes are now live: https://www.onrr.gov/reportpay/production-reporting.htm. Please remember to use "Ctrl+F5" to refresh the page. Closing this issue now. Thanks, Christine.

**Comment by mcharg** [comment]
Document updated in CMS.
