### ISSUE TITLE
Make a new redirect for old/broken link

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1885]
At https://www.ecfr.gov/current/title-30/chapter-XII/subchapter-A/part-1218/subpart-H/section-1218.560, the following web link is listed (https://www.onrr.gov/FM/Forms/default.htm) which is now a broken link. We need it to redirect to https://www.onrr.gov/reportpay/Forms/index.htm.

**Comment by mcharg** [comment]
@cthomasONRR Looks good.

**Comment by cthomasONRR** [comment]
@mcharg Is this the correct spreadsheet to update?

![image](https://user-images.githubusercontent.com/72526208/165588263-82351c0a-4304-480a-92c9-469a289095ce.png)

**Comment by mcharg** [comment]
@cthomasONRR I think so, but not sure what the 301 redirect status sheet is and how they relate to each other.

**Comment by cthomasONRR** [comment]
I updated the Redirects spreadsheet, not sure how to update the 301 redirect status spreadsheet
