### ISSUE TITLE
Mineral Revenue Reporter Handbook Chapter 4 Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1886]
Please replace the existing Chapter 4 at the following page, under Chapters and Table of Contents, with the attached - https://www.onrr.gov/reportpay/Handbooks/revenue-handbook/index.htm
[Chapter 4 (Final Replacement) 11-15 update.pdf](https://github.com/ONRR/onrr.gov-site/files/8577853/Chapter.4.Final.Replacement.11-15.update.pdf)

**Comment by cthomasONRR** [comment]
@bowlenj Good morning, this handbook chapter is updated on the dev site: http://2017onrr/reportpay/Handbooks/revenue-handbook/index.htm. Please give us your approval to go live. Thanks! Christine

**Comment by bowlenj** [comment]
This looks great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, April 28, 2022 6:30 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Mineral Revenue Reporter Handbook Chapter 4 Update (Issue #1886)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C35e6b1fc40724c14cfd508da2912e26b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637867458757767318%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2SdsyhenaiDRTrR7UtkZ5exc2Mo7dIRz7AiE0PMSKoM%3D&reserved=0> Good morning, this handbook chapter is updated on the dev site: http://2017onrr/reportpay/Handbooks/revenue-handbook/index.htm. Please give us your approval to go live. Thanks! Christine

**Comment by cthomasONRR** [comment]
@bowlenj Great! These changes are now live: https://www.onrr.gov/reportpay/Handbooks/revenue-handbook/index.htm. Closing this issue.

**Comment by mcharg** [comment]
Document updated in CMS.
