### ISSUE TITLE
Mineral Revenue Reporter Handbook Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1887]
Please replace the existing Mineral Revenue Reporter Handbook - View Complete Handbook with the attached on the following page - https://www.onrr.gov/reportpay/Handbooks/revenue-handbook/index.htm
[RRM-Printable.Minerals.Revenue.Handbook.pdf](https://github.com/ONRR/onrr.gov-site/files/8577948/RRM-Printable.Minerals.Revenue.Handbook.pdf)

**Comment by Maroyafaied** [comment]
@lpgoldstein please update this doc in the current website, and mark this doc as "update" in the cms. @lpgoldstein @mcharg we'll also have to make sure that page numbers didn't change for the collection Jerome is building.

**Comment by lpgoldstein** [comment]
@bowlenj This is ready for your review: http://2017onrr/reportpay/Handbooks/index.htm

**Comment by lpgoldstein** [comment]
@mcharg @Maroyafaied I started checking the page numbers and will finish in the morning.

**Comment by bowlenj** [comment]
This looks great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: lpgoldstein ***@***.***>
Sent: Wednesday, April 27, 2022 8:35 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Mineral Revenue Reporter Handbook Update (Issue #1887)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cfb2640356a2a41a9914608da28bfd75a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637867102101140833%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WL7ttnKM65fDCxaRYWqEr6%2F6BNvV8%2FxqcturQN%2BNNGQ%3D&reserved=0> This is ready for your review: http://2017onrr/reportpay/Handbooks/index.htm

**Comment by lpgoldstein** [comment]
@bowlenj It's live so I'm closing the issue.

**Comment by lpgoldstein** [comment]
@bowlenj This is ready for your review http://2017onrr/reportpay/Handbooks/index.htm

**Comment by lpgoldstein** [comment]
Updated document for reference [RRM-Printable.Minerals.Revenue.Handbook (5).pdf](https://github.com/ONRR/onrr.gov-site/files/8585081/RRM-Printable.Minerals.Revenue.Handbook.5.pdf)

**Comment by bowlenj** [comment]
The B.1.2 is fixed but page 59, Chapter 54 isn't showing the updated version 4.1 4-27-2022.  That was there this morning.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: lpgoldstein ***@***.***>
Sent: Thursday, April 28, 2022 11:30 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Mineral Revenue Reporter Handbook Update (Issue #1887)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C74f534647a0945e9932f08da293cc7d2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637867638275229813%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rZwZzF7NVzKsLMU0VYgs8WLmGMZ58ln%2B8Uj9yHkBn%2F8%3D&reserved=0> This is ready for your review http://2017onrr/reportpay/Handbooks/index.htm

**Comment by lpgoldstein** [comment]
@bowlenj closing out the issue!

**Comment by mcharg** [comment]
Document is updated in CMS.
