### ISSUE TITLE
Review Debt Collection page & contacts with SMEs

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1888]
https://dev-onrr-frontend.app.cloud.gov/about/contact/paying-contacts?tabs=contacts,debt-collection

https://dev-onrr-frontend.app.cloud.gov/paying/unpaid-debt

**Comment by Maroyafaied** [comment]
We need this link updated before we send for review

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/e9b18dcd-e38d-402b-a4c9-d2fed45d2284)

**Comment by mcharg** [comment]
@Maroyafaied I added the reporter letter links issue as a dependency.

**Comment by mcharg** [comment]
@Maroyafaied Link is added.

**Comment by Maroyafaied** [comment]
@mcharg I think we can mark this one approved by SME since they didn't have any changes on this page.

**Comment by mcharg** [comment]
Done
