### ISSUE TITLE
Training announcement

### ISSUE THREAD

**Issue by jpetersononrr** [ONRR/onrr.gov-site#189]
Hello!

Could you please post the following under the announcement banner on the home page?  Under the "Dear Reporter Letter" one would work fine, if that's an option.

Header:  Processed Gas Valuation
Body:  Royalty Valuation will offer Processed Gas Reporting training addressing the changes resulting from the reinstatement of the 2016 Valuation Rule via WebEx on Wednesday, June 10, 2020.  This session will run from 8:00 am to 10:30 am Mountain Daylight Time. Click here to register.

Link for "Click here to register":  https://onrr.webex.com/onrr/k2/j.php?MTID=te565fdbdf475ed979d54c1c523784c77

Thank you!

**Comment by jpetersononrr** [comment]
Alternatively, if I need to just reword the "Dear Reporter" box to include that information as well as the letter (because we could title the whole thing 2016 Rule Implementation or something like that), I'm happy to do so.  Let me know what is easier!  Thanks!

**Comment by jennmalcolm** [comment]
@jpetersononrr I added it as a separate announcement in dev. You can check it out here http://2017onrr/

I think it would look better if we can combine the two together like you suggested in your second comment. We have an abnormally high number of announcements right now, and it looks unbalanced with 4 in 3 columns. I can work on another design that looks better too, but it's probably faster to make the two announcements into one if you don't mind working on that.

**Comment by jpetersononrr** [comment]
Ok!

Let me get language approved and I'll have it for you as soon as (hopefully) tomorrow morning.  Harder to get people after 4!

**Comment by jennmalcolm** [comment]
No problem, thanks.

**Comment by jennmalcolm** [comment]
Hi @jpetersononrr if you want to keep the announcements separate, I can just make it two columns. I think that looks ok. Let me know what you think.
![image](https://user-images.githubusercontent.com/30806839/83568907-ba6cfd80-a4f1-11ea-9920-efcfd3ac9018.png)

**Comment by jpetersononrr** [comment]
Sorry, Amy was pretty busy today!

That way works if you like it!  Otherwise all of this inside a header of “2016 Valuation Rule Implementation” would work too:

Please see the Dear Reporter (link) letter on extending the deadline for compliance with the 2016 Valuation Rule to July 1, 2020.

Royalty Valuation will also offer Processed Gas Reporting training addressing the changes resulting from the reinstatement of the 2016 Valuation Rule via WebEx on Wednesday, June 10, 2020. This session will run from 8:00 am to 10:30 am Mountain Daylight Time. Click here to register.<https://onrr.webex.com/onrr/k2/j.php?MTID=te565fdbdf475ed979d54c1c523784c77>

Thanks!  Sorry, we’re getting inundated as people figure out they only have 28 days to fix 3 years of reporting (because why would they have bothered doing it before now even though they’ve had a full year warning?!).

​Jodie Peterson
Minerals Revenue Specialist
Office of Natural Resources Revenue
​jodie.peterson@onrr.gov
(303)231-3719

Royalty Valuation - Consistent Answers to Complex Questions

**Comment by jennmalcolm** [comment]
Thanks, Jodie. I've changed it back to the three columns and made the changes live.

**Comment by jpetersononrr** [comment]
Thank you!  Looks great!

​Jodie Peterson
Minerals Revenue Specialist
Office of Natural Resources Revenue
​jodie.peterson@onrr.gov
(303)231-3719

Royalty Valuation - Consistent Answers to Complex Questions
