### ISSUE TITLE
Update production reporting documents - gas 

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/onrr.gov-site#1890]
[Gulf-Buy-Back (1).xlsx](https://github.com/ONRR/onrr.gov-site/files/8593092/Gulf-Buy-Back.1.xlsx)
[Gulf-Flash-Gas (1).xlsx](https://github.com/ONRR/onrr.gov-site/files/8593093/Gulf-Flash-Gas.1.xlsx)
[Gulf-Metering-Systems (1).xlsx](https://github.com/ONRR/onrr.gov-site/files/8593095/Gulf-Metering-Systems.1.xlsx)
[Gulf-Gas-Plants (1).xlsx](https://github.com/ONRR/onrr.gov-site/files/8593096/Gulf-Gas-Plants.1.xlsx)
[Gulf-Sales-Tanks (1).xlsx](https://github.com/ONRR/onrr.gov-site/files/8593097/Gulf-Sales-Tanks.1.xlsx)
 
request received via email

**Comment by mcharg** [comment]
@lpgoldstein Johnny approved via email and I pushed to the live site.  Will check to see if they're live before closing.

**Comment by mcharg** [comment]
Changes are live.

**Comment by mcharg** [comment]
Documents are updated in CMS.
