### ISSUE TITLE
Update documents in CMS

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1892]

**Comment by mcharg** [comment]
https://dev-onrr-cms.app.cloud.gov/document/4440.pdf
Linked on pages: 
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/icrs/1012-0010
- [ ] https://dev-onrr-frontend.app.cloud.gov/references/forms?tabs=solid-minerals-reporting
- [ ] https://dev-onrr-frontend.app.cloud.gov/reporting/solids?tabs=forms

**Comment by lpgoldstein** [comment]
tracking sheet https://doimspp.sharepoint.com/:x:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7B74B27B02-72BC-4CEE-92B0-A1280895CB73%7D&file=ContentTracking.xlsx&action=default&mobileredirect=true&cid=8a7f9c54-c06f-4349-be50-ab4d747c31f1

**Comment by mcharg** [comment]
@cthomasONRR Lindsay and I got all the documents yesterday. Can you please review when you're back in the office?

**Comment by cthomasONRR** [comment]
@mcharg How should I review? Can we sort by tags in the CMS yet? Also, should I put 'update' tags on the the reporter letters listed in the excel that do not have tags?

**Comment by mcharg** [comment]
@cthomasONRR We added a tab to the Content Tracking sheet called "Doc Updates" that shows which files we updated.
https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Content/Content%20Audit/ContentTracking.xlsx?d=w74b27b0272bc4cee92b0a1280895cb73&csf=1&web=1&e=5bGWKa

**Comment by cthomasONRR** [comment]
@mcharg Yes I know. Have you updated documents and I should be checking if the updated docs are in the CMS? 

Looks like you updated all Reporter Letters, as per the note in the doc descriptions. I made sure the update tags were removed.

For Press Releases, all tags are absent in the CMS for me. Were these intentionally removed? I don't see any notes in the doc descriptions to indicate that these have been updated.

**Comment by mcharg** [comment]
The Update tags were intentionally removed and I didn't make any notes in the doc descriptions. I only noted in the spreadsheet. Can you check to see if the updated docs are in the CMS based on the spreadsheet?

**Comment by cthomasONRR** [comment]
So I will have to download every doc to check? CMS won't display anything in the "modified by" column option. I'm also going through the spreadsheet and removing "update" from the tags list in column F where I know it's been updated

**Comment by cthomasONRR** [comment]
I'm check by making sure the update tag has been removed in the CMS. If I see that removed, I know you've updated it. Then I'm deleting the update tag in column f of the excel.

**Comment by mcharg** [comment]
You could just compare against the same doc on the live site.  We uploaded the new ones from the Y drive.

**Comment by cthomasONRR** [comment]
OK I will do both, but it will take me most of the day to do this.

**Comment by mcharg** [comment]
@cthomasONRR Fixed

**Comment by cthomasONRR** [comment]
OK finished reviewing, @mcharg and @lpgoldstein are thorough, didn't find any issues!

**Comment by mcharg** [comment]
Yay!
