### ISSUE TITLE
Spell out FMP in the reporter letter drop-down

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1897]
From Melissa:
Noticed just now on reporter letter drop down selection of FMP.  Probably should spell out acronym since this is for the public website in the drop down.

**Comment by cthomasONRR** [comment]
@mcharg 

I believe I have these fixed:
![image](https://user-images.githubusercontent.com/72526208/172389598-37d6eb08-afc9-4605-b406-f183b541af3f.png)

Want to review, or can I close?

**Comment by mcharg** [comment]
@cthomasONRR Looks good.

**Comment by cthomasONRR** [comment]
@mcharg Great! Closing!
