### ISSUE TITLE
Get access to onrr.gov adjacent tools and collect screenshots

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#19]
- [x]  Data Warehouse

- [ ] pay.gov

- [ ] ecommerce.

- [ ] Maybe search.gov?

**Comment by lpgoldstein** [comment]
Found a video on ONRR.gov that walks a payor through how to pay rents on federal leases in eCommerce. Maybe some good screenshots? https://youtu.be/vbT0PAh-kko

**Comment by lpgoldstein** [comment]
I have access to data warehouse.

**Comment by lpgoldstein** [comment]
Closing in favor of #18
