### ISSUE TITLE
Lease Assignments

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#190]
Please update to the current assignments.  See attached.
https://www.onrr.gov/ReportPay/PDFDocs/RS_LeAgAssignments.pdf

Thank you
[RS_LeAgAssignments.pdf](https://github.com/ONRR/onrr.gov-site/files/4724965/RS_LeAgAssignments.pdf)
Thank you

**Comment by Maroyafaied** [comment]
@merrellc the pdf you send seems to be the same as the one that's already on the website. Is there an updated one? They both have the updated date on the bottom of 2/25/2020

**Comment by merrellc** [comment]
I forgot to change the update date. It should be todays date.  Do I need to send an updated copy?

Thank you

​Candace Merrell
Minerals Revenue Analyst

Office of Natural Resources Revenue

Reference and Reporting Management

303-231-3517

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________

**Comment by Maroyafaied** [comment]
@merrellc yes please. Thank you

**Comment by merrellc** [comment]
See attached. Thank you
[RS_LeAgAssignments.pdf](https://github.com/ONRR/onrr.gov-site/files/4725748/RS_LeAgAssignments.pdf)

**Comment by Maroyafaied** [comment]
Thanks @merrellc please review http://2017onrr/ReportPay/PDFDocs/RS_LeAgAssignments.pdf

**Comment by Maroyafaied** [comment]
It's live now. Thanks
