### ISSUE TITLE
CONCHO AREA MEETING                                                          (To be added to Event Calendar on Allottee Asst. page)

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#1904]
CONCHO AREA MEETING
MAY 19, 2022
1:00 pm to 2:00 pm CST
Location:  By Telephone

Description:  Meeting will be a Call-in Meeting to hear brief updates from ONRR Outreach Office.  Representatives from BLM, BTFA, and BIA. will also be present to give brief announcements and updates for their agencies.  Owners will be able to ask questions during the Q&A session regarding Indian Oil & Gas leases, IIM Accounts, and Indian Trust properties issues.  A limited number of lines will be available for callers to join this meeting.  See Other Information below on how to attend.
 
Who Should Attend:  IIM account holders, Indian mineral owners, and other Indian Trust property owners under the Concho Agency area in surrounding counties within the Southern Plains Region in Oklahoma. 

Other Information: To attend the meeting you must contact the ONRR OKC Outreach Office at toll-free (800) 354-7015 to reserve your space and to get the call-in number and passcode for this meeting.  The ONNR OKC Outreach office hours are Monday- Friday from 7:30 am-5:00 pm.

Contact: ONRR OKC Outreach Office
Phone: Toll-free (800) 354-7015
Email: [onrroutreachokc@onrr.gov]

**Comment by Toddsand21** [comment]
in the first sentence after Description could you change it to read....will be a Call-In Meeting and will begin with updates from the ONRR Outreach Office.  Followed by representatives from BLM, BTFA and the BIA will also....
Everything else looks fine and ready to go.

**Comment by lpgoldstein** [comment]
@Toddsand21 how about this? http://2017onrr/events.htm

**Comment by Toddsand21** [comment]
Yes it looks fine with the updates and ready to post. Thanks!

**Comment by lpgoldstein** [comment]
@Toddsand21 It's live so I'm closing the issue.
