### ISSUE TITLE
Update April NYMEX on onrr.gov

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#1905]
Good afternoon,

Please update the NYMEX values for April according to the attached spreadsheet.

Thanks!
@sudarr
[NYMEX042022.xlsx](https://github.com/ONRR/onrr.gov-site/files/8626237/NYMEX042022.xlsx)

**Comment by Maroyafaied** [comment]
@lpgoldstein please add this file to the CMS NYMEX collection as well. Thanks

**Comment by lpgoldstein** [comment]
@boices Ready for your review: http://2017onrr/valuation/NYMEX.htm

**Comment by boices** [comment]
That's perfect. Thanks again!

**Comment by lpgoldstein** [comment]
It's live so I'm closing out the issue @boices
