### ISSUE TITLE
Reduce reading grade level for Indian pages

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1906]
Heidi suggested content updates for [Tribal Resource Home](https://dev-onrr-frontend.app.cloud.gov/indian), [Tribal Assistance](https://dev-onrr-frontend.app.cloud.gov/indian/assistance), and [Tribal Consultation](https://dev-onrr-frontend.app.cloud.gov/indian/tribal-consultation) .

We will recommend changes to reduce reading level if possible and get her approval.

**Comment by Maroyafaied** [comment]
https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Indian/ITOC_ReadingLevel.docx?web=1

**Comment by mcharg** [comment]
@cthomasONRR I did my best. I put SMM before my rewrites and put them under yours. I'm not good at determining whether Tribe/Tribal is a proper noun. Can you take a pass through and fix capitalization?

**Comment by cthomasONRR** [comment]
@mcharg Great! I accepted your changes and made sure "tribal" and "tribe(s)" are lower-case.

Should I remove the red text completely to make the doc easier to read, then we can send to Heidi for approval? Or I can try to highlight what sections changed in our lower reading level edits.

**Comment by mcharg** [comment]
I think removing all the red text works.

**Comment by Maroyafaied** [comment]
Sent email to Heidi.

**Comment by cthomasONRR** [comment]
Heidi sent back minor edits. Doc located [here](https://teams.microsoft.com/l/file/62D22316-C1C1-49C9-B183-8BD95074CD12?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FDesign%2FIndian%2FONRR.gov_ITOC_ReadingLevel_Heidi%20Review.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

I'm working on getting all this text updated in the CMS.

**Comment by cthomasONRR** [comment]
@mcharg The following webpages are ready for your review:

- [ ] https://dev-onrr-frontend.app.cloud.gov/indian
- [ ] https://dev-onrr-frontend.app.cloud.gov/indian/assistance?tabs=tribal-assistance
- [ ] https://dev-onrr-frontend.app.cloud.gov/indian/tribal-consultation

**Comment by mcharg** [comment]
@cthomasONRR Looks good.

**Comment by cthomasONRR** [comment]
@mcharg Are you ok with me emailing Heidi to say that the text is all in (just waiting on tabs reorg).

**Comment by mcharg** [comment]
@cthomasONRR Yes

**Comment by cthomasONRR** [comment]
Email sent!
