### ISSUE TITLE
Indian Index Zone Prices ready for upload

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#1907]
The May 2022 Indian Index Zone prices are ready to be added to the ONRR.gov valuation page. The prices have been inputted into the Data for ONRR spreadsheet in the OneDrive.

Thanks,
Cory Forgrave
@sudarr

**Comment by Maroyafaied** [comment]
@lpgoldstein please also update the prices in the CMS. Thanks

**Comment by lpgoldstein** [comment]
@forgravec Ready for review: http://2017onrr/valuation/allzones.htm

**Comment by forgravec** [comment]
Prices look good...thanks.

Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
***@***.***
________________________________
From: lpgoldstein ***@***.***>
Sent: Wednesday, May 4, 2022 3:12 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Forgrave, Cory J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Indian Index Zone Prices ready for upload (Issue #1907)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@forgravec<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fforgravec&data=05%7C01%7Ccory.forgrave%40onrr.gov%7Cfab94cbd1c904a1405dd08da2e12cfaa%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637872955992298031%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ctQ7o0DAkHb7acDfpFNF9izuuqch6u0b6Y0Kz0EX4Zo%3D&reserved=0> Ready for review: http://2017onrr/valuation/allzones.htm

**Comment by lpgoldstein** [comment]
@forgravec It's live so I'm closing issue.
