### ISSUE TITLE
Review Handbook Collections

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1909]

**Comment by lpgoldstein** [comment]
- [ ] Minerals Revenue Reporter Handbook

- [ ] Minerals Production Reporter Handbook

- [ ] Solid Minerals Reporter Handbook

- [ ] Geothermal Payor Handbook - Class 1 Leases

- [ ] Geothermal Payor Handbook - Class 2 & 3 Leases

- [ ] Indian Payor Handbook

**Comment by lpgoldstein** [comment]
Do people know there is an error in the production handbook? This is wrong in the actual handbook - it should be B.2.2. 
![image](https://user-images.githubusercontent.com/39419003/167674209-801573d2-65d7-4eef-ae5a-a4f1fca56a76.png)

**Comment by lpgoldstein** [comment]
@Baymatt This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/handbookshttps://doimspp.sharepoint.com/:x:/s/NRRD/ETaIMvlaYqlBtzxDwRDENmcBdm6AJdf7STTTQjOkcczlQg?e=Gt8XvL
I've added columns to the spreadsheet that shows that I've checked everything, what I've checked and noted that I fixed it. Please let me know if you have any questions.

**Comment by lpgoldstein** [comment]
@cthomasONRR Do you have time to review?

**Comment by cthomasONRR** [comment]
@lpgoldstein Sure, the link above isn't working. Could you re-link the spreadsheet for me?

**Comment by Maroyafaied** [comment]
@lpgoldstein sorry, also for revenue Appendix G has the wrong title ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/080d1a12-5049-49a1-83da-9c1cc8b9b52f)

**Comment by Maroyafaied** [comment]
@lpgoldstein can you add "Appendix G" before the title to be consistent with other rows and also add a row underneath titled "Supplemental Reporting Guidance" before the Glossary and abbreviations.  Also, not sure if you saw my other comment above but I didn't see these fixes in dev. 
![image](https://user-images.githubusercontent.com/40175688/169118577-ff016ec0-4bb5-40aa-8927-618405f51ab9.png)

**Comment by Baymatt** [comment]
The description for the Class 2&3 Handbook seems incorrect.

<img width="891" alt="Screen Shot 2022-05-18 at 11 40 58 AM" src="https://user-images.githubusercontent.com/43329595/169121689-6c2d99d5-4b38-4c41-8364-9d9f3dc63050.png">

**Comment by cthomasONRR** [comment]
@mcharg @Baymatt I updated this, but looks like the same card is used in both handbooks. I'm not sure how to make separate cards with the directus bug.

**Comment by cthomasONRR** [comment]
@Baymatt @mcharg OK get separate cards set up- no pagination so directus bug didn't interfere
![image](https://user-images.githubusercontent.com/72526208/169132722-fef92576-41b7-4d10-8d45-f8218048a171.png)
![image](https://user-images.githubusercontent.com/72526208/169132868-eb11f7ae-279b-43ca-b4d6-06b7aabe5586.png)

**Comment by lpgoldstein** [comment]
@maroya removed the duplicates in production handbook after chapter 7 
![image](https://user-images.githubusercontent.com/39419003/169158282-2f74282d-bdbb-48c4-b8ce-36b758b9ffe0.png)
And the words "supplemental information" 
![image](https://user-images.githubusercontent.com/39419003/169158376-bce40198-3c53-4ca8-b6de-af500c462b76.png)

**Comment by Maroyafaied** [comment]
@lpgoldstein Thanks.
