### ISSUE TITLE
Wait for Directus to fix nested tabs bug

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1916]

**Comment by mcharg** [comment]
https://github.com/directus/directus/issues/11430

**Comment by mcharg** [comment]
I checked today and the PR still hasn't been merged. https://github.com/directus/directus/pull/12506

**Comment by Maroyafaied** [comment]
I asked for an update and received this response @mojobnichols @mcharg @cthomasONRR 
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/d8e8237a-bc9a-45e5-b203-31fcc33a7dac)

**Comment by Maroyafaied** [comment]
@mcharg @mojobnichols @cthomasONRR  Also, it seems like there are some nested tabs that you can sort and move around. For example ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/4ba36e34-9720-4388-aff4-02ff307a12de)

**Comment by mcharg** [comment]
@Maroyafaied You can sort if there's only one page of content. If there are multiple pages, you can't sort.

**Comment by cthomasONRR** [comment]
I added a comment (https://github.com/directus/directus/pull/12506)
![image](https://user-images.githubusercontent.com/72526208/172702861-9d8c803b-371b-4146-9a18-869bd4eac041.png)

**Comment by mcharg** [comment]
@mojobnichols This might be a quick fix.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/89870e14-48df-4a9a-b425-37e9b8485cf0)

**Comment by cthomasONRR** [comment]
https://github.com/directus/directus/discussions/12818

**Comment by mcharg** [comment]
Fixed
