### ISSUE TITLE
Consolidate user tasks from previous studies

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1917]

**Comment by mcharg** [comment]
@lpgoldstein This is ready for you to review.
https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/User%20Research/Studies/UserTypes.xlsx?d=w8d6e1a5762644d4e98c52f6af51cd008&csf=1&web=1&e=QlYm1N

**Comment by lpgoldstein** [comment]
@mcharg Looks good!
