### ISSUE TITLE
North Dakota, South Dakota, Washington, Oregon Virtual Outreach                       (add to Events Calendar for May)

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#1918]
North Dakota, South Dakota, Washington, Oregon Virtual Outreach 
Thursday, May 26, 2022 
10:00 am-10:30 am MST
 
Location:  Telephone 

Description: Representatives from the Office of Natural Resources Revenue will host a Question and Answer session by phone for Indian Mineral Owners and Trust Property Owners regarding their Indian Oil & Gas leases, IIM Accounts, and Indian Trust Properties. Representatives from the Bureau of Land Management, Bureau of Indian Affairs, and Bureau of Trust Funds Administration are invited to be in attendance to answer questions.  

Who Should Attend:  IIM account holders, Indian mineral owners, and Indian trust property owners in the Trenton, Parshall, Ft. Berthold, Minot, Ft. Totten, Turtle Mountain, Mandaree, Twin Buttes, White Shield, Bismarck, Fargo, North Dakota, Poplar, Montana, Rapid City, Agency Village, Aberdeen, Standing Rock, South Dakota, Portland, Oregon, Spokane, Seattle, Washington areas.  

Other Information: To attend the outreach session, please contact the ONRR Denver Outreach Office at (800) 982-3226, for the call-in number and passcode.  The ONRR Denver Outreach Office hours are Monday-Friday 7:30am-4:00pm. 

Contact: ONRR Denver Outreach Office, 
Phone: (800) 982-3226 (toll-free);  Email:  [onrroutreachdenver@onrr.gov}

**Comment by lpgoldstein** [comment]
@Toddsand21 This is ready for your review: http://2017onrr/events.htm

**Comment by Toddsand21** [comment]
It looks fine with me and ready to post.

**Comment by lpgoldstein** [comment]
@Toddsand21 This is live! https://onrr.gov/events.htm
