### ISSUE TITLE
Update index zone prices on ONRR.gov

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#192]
Please update the June index zone values on the ONRR.gov website. The data can be found in our OneDrive in a spreadsheet called "Data for ONRR.gov" in the first tab "Index-Zones".

@sudarr

Thanks!

**Comment by lpgoldstein** [comment]
@boices @sudarr This is ready for your review: http://2017onrr/Valuation/allzones.htm

**Comment by boices** [comment]
All prices look good--thanks!

@sudarr

**Comment by lpgoldstein** [comment]
@boices It should be live soon
