### ISSUE TITLE
Add ability to have a header on a homepage sidebar block

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1923]
Just noticed the Announcements header is missing.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/5bdf2587-0abe-498a-bff0-9bf09aedeb27)

**Comment by jlouis-onrr** [comment]
@mcharg, this feature is already available via the home page -> sidebar blocks

**Comment by mcharg** [comment]
@jlouis-onrr It might be a permission issue.

I can view or remove the block that's there, but not add a new block.
![image](https://user-images.githubusercontent.com/38465926/167891497-38ba9052-1f55-4702-920a-2428b6539816.png)

**Comment by jlouis-onrr** [comment]
ok, looking into why its not editable

**Comment by mcharg** [comment]
@jlouis-onrr Looks good and now I have ability to edit.
