### ISSUE TITLE
Move tribal assistance tab

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1927]
Heidi wants the Tribal Assistance tab (located at: https://dev-onrr-frontend.app.cloud.gov/indian/assistance) to be located after the "choosing assistance" tab

![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/f9afdda1-3b98-4b1a-8f3e-88a6730f9a6e)

**Comment by cthomasONRR** [comment]
Complete:
![image](https://user-images.githubusercontent.com/72526208/173829911-ebf85d17-5411-4e2f-bfce-e7853d26fc05.png)

@mcharg Want to review?

**Comment by mcharg** [comment]
@cthomasONRR Looks good.
