### ISSUE TITLE
Update to Enforcement and Litigation Support Page

### ISSUE THREAD

**Issue by KristianL3101** [ONRR/onrr.gov-site#1933]
Please update the right hand side of the Enforcement and Litigation Support page that currently says "Have a Referral for OE?  Here's an optional form for submitting your request."  to:

"Have a Referral for OE?  Please submit directly into OE's database using the following link:"

Also update the Link to read "OE Referrals"  and to the OE Database link below.

[OE Referrals](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Foed.onrr.local%2FReferralRequests%2FReferralRequests&data=05%7C01%7CKristian.Lee%40onrr.gov%7C7e441adc399f41ee33e608da33a4206b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637879077249611285%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=U%2FEzldXVJd4B6w9UF5gV724nzzPNmWwqmkpaTkRC5Kc%3D&reserved=0)

**Comment by cthomasONRR** [comment]
@KristianL3101 Hello! I'm having trouble finding this text "Have a Referral for OE? Here's an optional form for submitting your request." on the current onrr.gov or the new site. Could you please point me to the exact webpage/location where you want this change? Thanks!

**Comment by KristianL3101** [comment]
Hello,

it is on the right hand side of Enforcement's onrresource page here:

https://onrresource/Enforcement/

Kristian Lee
Enforcement Specialist
ONRR/OE Litigation Support
Denver Federal Center, Bldg 85/B76
PO Box 25165 MS 64200B
Denver, CO  80225-0165
(303) 231-3101

________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, May 12, 2022 9:51 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Lee, Kristian H ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update to Enforcement and Litigation Support Page (Issue #1933)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@KristianL3101<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKristianL3101&data=05%7C01%7Ckristian.lee%40onrr.gov%7C97619d3993594af8267008da342f5028%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637879675058921086%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OeFjq47ZxGKi%2BPsCmTaQjg1EmuUHUTDPG2A2Zc5U%2BT0%3D&reserved=0> Hello! I'm having trouble finding this text "Have a Referral for OE? Here's an optional form for submitting your request." on the current onrr.gov or the new site. Could you please point me to the exact webpage/location where you want this change? Thanks!

**Comment by cthomasONRR** [comment]
@KristianL3101 Ok, sorry for the confusion. We do not own onrrresource, and do not have the capability to change the intranet webpage. (My team - ODDD - is in charge of onrr.gov and revenuedata.doi.gov.) Please contact David Wentzel
 or Lori Yokomizo to make updates on https://onrresource/Enforcement/

**Comment by KristianL3101** [comment]
Ok, Thank you. Sorry for the confusion.

Kristian Lee
Enforcement Specialist
ONRR/OE Litigation Support
Denver Federal Center, Bldg 85/B76
PO Box 25165 MS 64200B
Denver, CO  80225-0165
(303) 231-3101

________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, May 12, 2022 9:57 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Lee, Kristian H ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update to Enforcement and Litigation Support Page (Issue #1933)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@KristianL3101<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKristianL3101&data=05%7C01%7Ckristian.lee%40onrr.gov%7C571a07f2d47d4f1171b608da343016ed%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637879678390285420%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=h0t9h063J1jIavWoKTTLp7BKJN3%2FIrmKsiBpinFFHh8%3D&reserved=0> Ok, sorry for the confusion. We do not own onrrresource, and do not have the capability to change the intranet webpage. (My team - ODDD - is in charge of onrr.gov and revenuedata.doi.gov.) Please contact David Wentzel
or Lori Yokomizo to make updates on https://onrresource/Enforcement/
