### ISSUE TITLE
Redo org chart

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1934]
David sent me the one Joe has been using in presentations and we need to make it accessible.

**Comment by mcharg** [comment]
@Maroyafaied I went ahead and updated the org chart based on what Dave sent me. If Joe comes back with something different, we can revise.
[ONRR_External_Org_Chart.pptx](https://github.com/ONRR/onrr.gov-site/files/8689480/ONRR_External_Org_Chart.pptx)

**Comment by Maroyafaied** [comment]
@mcharg I spoke with Joe, the only change is to change the highlighted name to Shayna Varnedoe, she was selected for this position. [Uploading... image.png]

**Comment by mcharg** [comment]
@Maroyafaied Looks like it didn't upload the image. Which position does Shayna go on?

**Comment by Maroyafaied** [comment]
@mcharg Internal Review, Oversight, and Compliance

**Comment by mcharg** [comment]
@Maroyafaied Updated
[ONRR_External_Org_Chart.pptx](https://github.com/ONRR/onrr.gov-site/files/8710776/ONRR_External_Org_Chart.pptx)

**Comment by Maroyafaied** [comment]
@mcharg for Rob Winter's notes, can you add "reports to" and capitalize Revenue. Otherwise looks good. 
![image](https://user-images.githubusercontent.com/40175688/168890478-07424de7-d9fa-48ed-94d8-7c7eaa16d6e3.png)

**Comment by mcharg** [comment]
@Maroyafaied Fixed
[ONRR_External_Org_Chart.pptx](https://github.com/ONRR/onrr.gov-site/files/8710841/ONRR_External_Org_Chart.pptx)

**Comment by mcharg** [comment]
@Maroyafaied Replaced the file in the CMS. https://dev-onrr-frontend.app.cloud.gov/about/organization?tabs=organization-chart

**Comment by Maroyafaied** [comment]
@mcharg looks good. Thanks
