### ISSUE TITLE
Remove FIMO paragraph 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1935]
@cthomasONRR Heidi asked to remove this paragraph from this page https://www.onrr.gov/about/MOUs-and-SOPs.htm

 ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/3d4f8f57-982e-48ef-9db9-1e437f540f07)

**Comment by cthomasONRR** [comment]
@Maroyafaied 

Also remove this entire tab on the new dev site? Not sure if I can delete tabs until that directs bug is fixed.
![image](https://user-images.githubusercontent.com/72526208/168157916-969c82fa-6df6-44cf-a96e-c8d188f402c4.png)

**Comment by cthomasONRR** [comment]
@Maroyafaied It's now removed from the current dev site if you would like to review before I go live: http://2017onrr/about/MOUs-and-SOPs.htm

**Comment by Maroyafaied** [comment]
@cthomasONRR No don't remove the tab from the dev site, this change is only on the current site.

**Comment by Maroyafaied** [comment]
@cthomasONRR dev looks good, please go ahead and push live.

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks, it's live now: https://www.onrr.gov/about/MOUs-and-SOPs.htm

**Comment by Maroyafaied** [comment]
@cthomasONRR looks good. Closing.
