### ISSUE TITLE
Get onrr.gov domain from BSEE

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1938]

**Comment by Maroyafaied** [comment]
I previously asked BSEE's web manager about this and was told that ONRR already has the onrr.gov domain and BSEE controls the Domain Name Server (DNS) services and they will only need the IP address information of where to point onrr.gov and when to do it, and they can easily re-point it to that location at the time we tell them to.

**Comment by Maroyafaied** [comment]
@mojobnichols and I met with BSEE's web manager. It sounds like all the needs is the "c name address" from cloud.gov and that will route the DNS appropriately. Apparently this is what we did with the NRRD site when we transitioned from federalist to cloud.gov. @mojobnichols feel free to add more details in the issue if I missed anything or not explaining correctly,  I will create an issue for to get the c name once the production site is build.
