### ISSUE TITLE
Table column alignment tweaks

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1940]
- [x] make numerical values that aren't dollar amounts align right.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/673cfce7-9d43-403a-b197-d27a887df880)
https://dev-onrr-frontend.app.cloud.gov/references/valuation/processed-gas-example

- [x] Make this column not align right.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/5a3de2ee-57a4-407e-842d-8996a9e2b819)
https://dev-onrr-frontend.app.cloud.gov/references/handbooks/indian-payor-handbook?tabs=chapter-3-indian-oil-valuation,32&panel=333-example

- [x] Make percentages right aligned.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/e4b2f92e-12c3-47be-aa40-55bb11fe160d)

**Comment by mcharg** [comment]
@jlouis-onrr These are all right aligned, but shouldn't be.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/d74678b7-106a-4237-ad42-a5818c2ef4cb)
https://dev-onrr-frontend.app.cloud.gov/references/valuation/pop-example?tabs=sample-statement&panel=disallowed-pipeline-plant-fuels

**Comment by mcharg** [comment]
@jlouis-onrr Another one that's right aligning that shouldn't.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/40d3cd4e-bcfb-4a98-b2a8-db387e87f91d)
https://dev-onrr-frontend.app.cloud.gov/indian/indian-references?tabs=regulations

**Comment by jlouis-onrr** [comment]
@mcharg, looks like I need to adjust the regex pattern a bit more.  thx

**Comment by jlouis-onrr** [comment]
@mcharg, updated regex has been added for percentages

**Comment by mcharg** [comment]
Looks good.
