### ISSUE TITLE
Table bottom rule

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1941]
Add a rule on the bottom row, so it doesn't look like it's floating when the last row is white.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/1506dda0-51f4-4cbe-859f-2d21da3a1a56)

**Comment by jlouis-onrr** [comment]
@mcharg, updated table styles are out in dev.

**Comment by mcharg** [comment]
Looks good.
