### ISSUE TITLE
Quick Start Guide

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1946]
Can we please have the Quick Start Guide found at the following link removed, this information is no longer valid and was found by a payor via google -[ [https://onrrreporting.onrr.gov/Help/DoiWebGettingStarted.aspx](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fonrrreporting.onrr.gov%2FHelp%2FDoiWebGettingStarted.aspx&data=05%7C01%7CJessica.Bowlen%40onrr.gov%7Cbb925ab7f29b48236f9e08da39b0abc2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637885728206002980%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Gw0zE%2FjwnEz%2F9ueXOlZQZdWNwSIGQZizSWRKi9v86a4%3D&reserved=0)](https://onrrreporting.onrr.gov/Help/DoiWebGettingStarted.aspx)

**Comment by mcharg** [comment]
@bowlenj That's an eCommerce page, so Stacey Browne's team would need to make the change.
