### ISSUE TITLE
Add example plant statement for RV

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1947]
Megan Hessee emailed with an example plant statement to go with the 2 new Indian examples (#1943 and #1944).

I'm waiting on them to send me a 508-compliant version, and for them to tell me where they want it.

**Comment by cthomasONRR** [comment]
After email discussions with Megan H, we have the dev site set for the new document:
http://2017onrr/valuation/index.htm

![image](https://user-images.githubusercontent.com/72526208/169414822-3a5bf6ff-cc34-4074-8af6-285ba3125421.png)

When we get the document, we need to title it as "Indian_unprocessed_gas_example_statement.pdf"... we will need to replace the spaces in the file name with underscores.

**Comment by cthomasONRR** [comment]
Adding @lpgoldstein to this issue because we likely won't get the 508-compliant document until next week (when I'm on leave).

**Comment by lpgoldstein** [comment]
@cthomasONRR RV added the example to each of the documents that are already in the cards above. I updated onrr.gov accordingly and deleted the new example line item in the table. In the CMS,  I replaced the existing documents and deleted the placeholder links in the cards.
