### ISSUE TITLE
Update NYMEX prices on ONRR.gov

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#195]
Please update the prices and upload the attached spreadsheet. Thanks!
@sudarr

[NYMEX0520.xlsx](https://github.com/ONRR/onrr.gov-site/files/4730748/NYMEX0520.xlsx)

**Comment by jennmalcolm** [comment]
@boices it's ready for your review in dev.

http://2017onrr/Valuation/NYMEX.htm

**Comment by jennmalcolm** [comment]
@boices if you could review this today, that will help make sure I can get it pushed to production on time.We have a few people off tomorrow. Thanks.

**Comment by boices** [comment]
That looks perfect--sorry for the delay!

@sudarr

**Comment by jennmalcolm** [comment]
No problem @boices, I just wanted to make sure I got it done for you today. The changes are live now.
