### ISSUE TITLE
Dear Reporter Letters that need relinking to show PDF icon

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1951]

**Comment by cthomasONRR** [comment]
- [ ] https://dev-onrr-frontend.app.cloud.gov/ (2016 Rule yellow info box)
- [ ]

**Comment by cthomasONRR** [comment]
@mcharg I was able to get PDF icons for the DRLs listed above. The only one I couldn't figure out how to do was the one on the homepage because it is within a collection.

**Comment by mcharg** [comment]
@cthomasONRR We don't have access to the link tool from within the announcements collection.  We have an issue to add that, so we'll have to update that one when we get to that issue.

**Comment by cthomasONRR** [comment]
@mcharg OK, thanks for letting me know. I went through the website, so I think I caught all DRLs (and other docs) that needed icons. Most DRLs were a collection list within accordions, so all of those had links already.

**Comment by mcharg** [comment]
@cthomasONRR All the links look good.

**Comment by cthomasONRR** [comment]
Cool, I'll close this now.
