### ISSUE TITLE
Update to Minerals Revenue Reporter Handbook

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1955]
I updated Appendix C in the "View Complete Handbook" for Minerals Revenue Reporter Handbook located here - https://www.onrr.gov/reportpay/Handbooks/revenue-handbook/index.htm

Please replace the current version "View Complete Handbook" with the attached updated version.
[RRM-Printable.Minerals.Revenue.Handbook.pdf](https://github.com/ONRR/onrr.gov-site/files/8765303/RRM-Printable.Minerals.Revenue.Handbook.pdf)

**Comment by lpgoldstein** [comment]
@bowlenj Will you please send me an updated copy of appendix c as well so that the individual appendix pdf matches the information in the complete handbook?

**Comment by bowlenj** [comment]
I just sent it to you in chat!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: lpgoldstein ***@***.***>
Sent: Tuesday, May 24, 2022 2:02 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update to Minerals Revenue Reporter Handbook (Issue #1955)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C9957f19d0b5e43c5573a08da3dc062ec%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637890193750375106%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jRF0kFpd%2Fy87pKB2lKcpqkakjNo83DIvV%2Fg9iLfVLck%3D&reserved=0> Will you please send me an updated copy of appendix c as well so that the individual appendix pdf matches the information in the complete handbook?

**Comment by lpgoldstein** [comment]
@bowlenj This is ready for your review: http://2017onrr/reportpay/Handbooks/index.htm

**Comment by lpgoldstein** [comment]
Updated in cms as well

**Comment by bowlenj** [comment]
This looks great, thank you!!!!!!!!!!!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: lpgoldstein ***@***.***>
Sent: Tuesday, May 24, 2022 2:11 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update to Minerals Revenue Reporter Handbook (Issue #1955)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C202c02069a354e5c1ab308da3dc1a78c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637890199194802611%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Xg24aHo%2FtFGk1UoV00CWG%2Bfp75ag%2BZRr6YImWDpUF5c%3D&reserved=0> This is ready for your review: http://2017onrr/reportpay/Handbooks/index.htm

**Comment by lpgoldstein** [comment]
@bowlenj It's live!
