### ISSUE TITLE
SME review - Reference Lists & Codes

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1958]
Sent email to RRM to review on 5/24

https://dev-onrr-frontend.app.cloud.gov/references/reference-lists

**Comment by Maroyafaied** [comment]
Sent another email asking for status but got multiple out of office automatic replies.

**Comment by mcharg** [comment]
Crystel pointed out some copy we need to add. Waiting on RRM to send final copy.

**Comment by Maroyafaied** [comment]
@mcharg please take out the formatting tab and add link to appendix B from the revenue handbook and send to Jessica for approval. Thanks

**Comment by mcharg** [comment]
Done and approved.
