### ISSUE TITLE
KAULEY VIRTUAL OUTREACH MEETING                (to be added to Event Calendar on Allottee Asst. Page)

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#1959]
KAULEY VIRTUAL OUTREACH MEETING
Thursday, June 16, 2022
1:00 pm to 2:00 pm CST
Location:  By Telephone

Description: This meeting will be a Call-in Meeting to hear a brief presentation and updates from the Office of Natural Resources Revenue (ONRR) Outreach Office. Representatives from the Bureau of Land Management (BLM), Bureau of Trust Funds Administration (BTFA), and the Bureau of Indian Affairs (BIA) will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust property issues.  Owners will also have an opportunity to ask questions with the representatives of the four agencies during the Q&A session.

Who Should Attend: IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Southern Plains Region in Oklahoma.

Other Information: To reserve a space and get a passcode for this meeting please contact the ONRR OKC Outreach Office toll-free (800)354-7015. The OKC Outreach office hours are Mon.- Fri. from 7:30 am-4:30 pm.

Contact: ONRR OKC Outreach, Phone: (800) 354-7015; EMAIL: [onrroutreachokc@onrr.gov] (mailto:onrroutreachokc@onrr.gov)

PAWNEE AREA VIRTUAL MEETING
Thursday, June 23, 2022
Time: 1:00 pm - 2:00 pm CST
Location: By Telephone 

Description: This meeting will be a Call-in Meeting to hear a presentation and updates from the Office of Natural Resources Revenue (ONRR) OKC Office.  Representatives from each of the four agencies including the BLM, BTFA, and the BIA will also be available to discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust property issues. There will be a Q&A session for owners to ask questions from the agency representatives.   

Who Should Attend:  IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Pawnee Agency Area, or any mineral owners located in the Southern Plains Region in Oklahoma. 

Other Information: To reserve a space and get a passcode for this meeting please contact the ONRR OKC Outreach Office toll-free (800)354-7015. The OKC Outreach office hours are Mon.- Fri. from 7:30 am-4:30 pm.

Contact: ONRR OKC Outreach, Phone: (800) 354-7015; Email:  [onrroutreachokc@onrr.gov](mailto:onrroutreachokc@onrr.gov)

**Comment by Toddsand21** [comment]
Please note: I will be out of the office until June 6, but I will check my email today and tomorrow to get this through and posted by 06/01/22. Thanks,.

**Comment by lpgoldstein** [comment]
@Toddsand21 This is ready for your review: http://2017onrr/events.htm

**Comment by Toddsand21** [comment]
The time on the Pawnee Area Meeting should be 1:00 pm to 2:00 pm instead of  to 2:30 pm.

**Comment by Toddsand21** [comment]
That seems to be the only corrections I see and it should be ready to post.

**Comment by Maroyafaied** [comment]
@Toddsand21 I made that correction. It should be live in 30 min or so. Thanks http://2017onrr/events.htm

**Comment by lpgoldstein** [comment]
@Toddsand21 It's live! I'll go ahead and close out the issue. https://onrr.gov/events.htm
