### ISSUE TITLE
Updates to ONRR's Current ICR's page

### ISSUE THREAD

**Issue by gingerhensley** [ONRR/onrr.gov-site#1960]
Good morning, 
I am requesting updates to this page https://onrr.gov/Laws_R_D/FRNotices/ICR0136.htm 
 
Under the Federal Register Publications heading, please add a bullet to the top of the list. The bullet should read as follows: “60-Day Agency Information Collection - (87 FR 32050--May 26th, 2022)”

Please add this hyperlink to the language in the parenthesis:  https://www.federalregister.gov/documents/2022/05/26/2022-11380/agency-information-collection-activities-federal-oil-and-gas-valuation 

Please let me know if you have any questions. 
Ginger Hensley

**Comment by lpgoldstein** [comment]
@gingerhensley This is ready for your review: http://2017onrr/Laws_R_D/FRNotices/ICR0136.htm

**Comment by gingerhensley** [comment]
Approved, 

Thank you!

**Comment by lpgoldstein** [comment]
@gingerhensley This is live so I'm closing.
