### ISSUE TITLE
Updates to ONRR's Current FRN's 2022 page

### ISSUE THREAD

**Issue by gingerhensley** [ONRR/onrr.gov-site#1961]
Good morning, 
I am requesting updates to this page https://onrr.gov/Laws_R_D/FRNotices/index.htm 

Please create it with May 26th, 2022.
It should read as follows:
“87 FRN 32050 
Thursday, May 26th, 2022 
**Denver, CO** In accordance with the Paperwork Reduction Act of 1995, ONRR is proposing to renew an information collection request. OMB Control Number 1012-0005.
View FR document"

Please add this hyperlink to the "View FR document" language https://www.federalregister.gov/documents/2022/05/26/2022-11380/agency-information-collection-activities-federal-oil-and-gas-valuation

Please let me know if you have any questions. 
Ginger Hensley

**Comment by lpgoldstein** [comment]
@Maroyafaied This isn't updating and I'm not sure why. I think Jerome had to manually push something. I tried to push it live as well so it may just be slow.

**Comment by Maroyafaied** [comment]
@lpgoldstein it's on the live site in the bottom of the homepage and the webpage, make sure you select year 2022 to be able to see it. The year goes to 2021 by default.  https://onrr.gov/Laws_R_D/FRNotices/index.htm

![image](https://user-images.githubusercontent.com/40175688/170774698-b0045142-92ce-4063-8f98-f7fe1a31876f.png)

**Comment by Maroyafaied** [comment]
@gingerhensley please select year 2022 and review, let us know if you have any changes. Thanks https://onrr.gov/Laws_R_D/FRNotices/index.htm

**Comment by gingerhensley** [comment]
Approved,

Thank you!
