### ISSUE TITLE
Screen reader only reads the highlighted item in the left nav

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1969]
So here, it only reads How Leasing Works.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/c862421c-129d-44be-a29c-44693fb0c018)

**Comment by mcharg** [comment]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/31a10e9a-a0e9-4015-98b4-85cad825d7d8)

**Comment by mcharg** [comment]
[Uploading... image.png]

**Comment by mcharg** [comment]
There are also issues with this menu on mobile. ![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/cf1bed4e-4628-4663-b2f5-5b9da21871de)

**Comment by cthomasONRR** [comment]
I emailed Sam for him to double-check accessibility and am waiting for his response.
