### ISSUE TITLE
Screen Reader issue: Headings are not tagged correctly

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1976]
For instance, this page has an H1 and an H2 and neither are showing up in the headings list.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/74939905-d6c1-4370-b683-d1dbb4d98bf6)

**Comment by cthomasONRR** [comment]
I talked with Sam, and these headings are how he navigates through a webpage. He says they are necessary and without them, the website can't be considered 508-compliant.

**Comment by cthomasONRR** [comment]
I emailed Sam for him to double-check accessibility and am waiting for his response.
