### ISSUE TITLE
Research search.gov

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1977]

**Comment by lpgoldstein** [comment]
unable to access search.gov. emailed and waiting to hear back.

**Comment by mcharg** [comment]
@mojobnichols I set up a site for search.gov. I think we just need to add in this code somewhere.

Form Snippet
`<!DOCTYPE html>
<html>
<head><title>page title</title></head>
<body>
  <form id="search_form" action="https://search.usa.gov/search" accept-charset="UTF-8" method="get">

    <input type="hidden" name="affiliate" id="affiliate" value="onrr.gov" autocomplete="off" />
    <label for="query">Enter Search Term(s):</label>
    <input type="text" name="query" id="query" autocomplete="off" class="usagov-search-autocomplete" />
    <input type="submit" name="commit" value="Search" data-disable-with="Search" />
  </form>`

Type-ahead search and Search.gov Tag Snippet
`<script>
//<![CDATA[
      var usasearch_config = { siteHandle:"onrr.gov" };

      var script = document.createElement("script");
      script.type = "text/javascript";
      script.src = "//search.usa.gov/javascripts/remote.loader.js";
      document.getElementsByTagName("head")[0].appendChild(script);

//]]>
</script>
</body>
</html>`

**Comment by mcharg** [comment]
I also applied styling to search results.
https://search.usa.gov/search?affiliate=onrr.gov&query=production&commit=Search

**Comment by mcharg** [comment]
@mojobnichols I also found API stuff. I added you to the account, so you can go in and take a look. You should have an invite in your email.

**Comment by lpgoldstein** [comment]
I'm still emailing with search.gov to get a meeting set up and approve Maroya and Christine.

**Comment by lpgoldstein** [comment]
closing this issue because we've met with the search.gov team and know what we need to do around launch to make our search function.
