### ISSUE TITLE
New file for onrr.gov

### ISSUE THREAD

**Issue by StaceyKaiser** [ONRR/onrr.gov-site#198]
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm called “Downloadable Text Cross-Reference Lease to Agreement Number” file entitled “Jun 2020 Lease Agreement XREF.txt”.  It was queried from the system on 6/3/2020.

[Jun 2020 Lease Agreement XREF.txt](https://github.com/ONRR/onrr.gov-site/files/4748998/Jun.2020.Lease.Agreement.XREF.txt)

**Comment by jennmalcolm** [comment]
@StaceyKaiser please review the changes on our development site and let us know if it looks ok to push to production. Thanks.
http://2017onrr/ReportPay/CrossRef.htm

**Comment by StaceyKaiser** [comment]
The file looks correct. Thank you!

**Comment by jennmalcolm** [comment]
changes are live
