### ISSUE TITLE
Indian Index Zones for June 2022

### ISSUE THREAD

**Issue by penvosej** [ONRR/onrr.gov-site#1982]
Hello, the June 2022 Indian Index Zone prices are ready to be published on ONRR.gov.  The "Data for ONRR.gov" Excel spreadsheet has been updated with relevant data.

@sudarr

**Comment by lpgoldstein** [comment]
@penvosej ready for review http://2017onrr/valuation/allzones.htm

**Comment by lpgoldstein** [comment]
Approved via email. Live and closing issue.

**Comment by penvosej** [comment]
Hi Lindsay,

Thanks for taking care of this so quickly! Everything looks good!

- Jessica

From: lpgoldstein ***@***.***>
Sent: Friday, June 3, 2022 9:52 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Indian Index Zones for June 2022 (Issue #1982)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpenvosej&data=05%7C01%7CJessica.Penvose%40onrr.gov%7Ccc2202e30a6b46872e8c08da4579095a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637898683397951661%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8b3HCr6I9buVWM%2FKVT%2BYfcEynsnR1JWh9N7RQUBwVto%3D&reserved=0> ready for review http://2017onrr/valuation/allzones.htm

-
