### ISSUE TITLE
NVDA not reading out the alt text for the following images

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1987]
**Hero images**

- [x] None of the Hero Images have alt text: https://dev-onrr-cms.app.cloud.gov/admin/files/folders/8c9f9538-b9ba-424e-a1ac-28983c1a8354

**Home**

- [x] Revenue Statistics Image (NRRD Oil Rig): https://dev-onrr-cms.app.cloud.gov/admin/files/02564c61-ce46-4a9e-813e-2870861643a1

**Reporting Home** 

- [x] Oil & Gas Icon: https://dev-onrr-cms.app.cloud.gov/admin/files/dca156d4-68e0-4abb-8226-d13a49cce408
- [x] Solid Mineral Icon: https://dev-onrr-cms.app.cloud.gov/admin/files/0b9ad168-7d90-4cc6-964a-c8eda2f6ad92
- [x] Geothermal Icon: https://dev-onrr-cms.app.cloud.gov/admin/files/4babed51-0913-4e88-a93d-965c1156dac6

**Indian Payor Handbook**
- [x] Ch 1.6, Product Codes Image: https://dev-onrr-cms.app.cloud.gov/admin/files/a7f04b85-ed15-452e-9052-5369ce1d09a0
- [x] Ch 2.4.3, Pressure Base Example Image not displaying all all text just says "Pressure base example": https://dev-onrr-cms.app.cloud.gov/admin/files/6722c487-5c25-40c8-8f37-ecebb34c14fa
- [x] Ch 2.5.1, Lease Language: https://dev-onrr-cms.app.cloud.gov/admin/files/2bd33b2c-0590-43f6-9138-708f77c9f12a
- [x] Ch 2.5.5, Flow Chart not displaying full alt text: https://dev-onrr-cms.app.cloud.gov/admin/files/e55f8679-1262-41f0-9afe-20cb603b002f
- [x] Ch 2.5.5, Indian Gas Index Zone map: https://dev-onrr-cms.app.cloud.gov/admin/files/c2339783-0219-4fa4-8f9f-e1b6f4575950
- [x] Ch 2.5.5, Arm's Length Dedicated Sale: https://dev-onrr-cms.app.cloud.gov/admin/files/e0185fdc-1728-4902-8ed9-a5c4d0f6b02c
- [x] Ch 2.5.5, Indian Gas Major Portion Map: https://dev-onrr-cms.app.cloud.gov/admin/files/6ee9dccb-8b27-4285-8b0e-470444bf5843
- [x] Ch 2.5.8, Arm's Length Control: https://dev-onrr-cms.app.cloud.gov/admin/files/865d7a59-2378-491d-8c63-389534b8db15
- [x] Ch 2.8.1 Marketable Condition: https://dev-onrr-cms.app.cloud.gov/admin/files/c51c9d59-cf13-4348-b779-9d1d84c0d157
- [x] Ch 2.8.3 Multiple Pressures Example: https://dev-onrr-cms.app.cloud.gov/admin/files/55bb8237-6fa4-43b3-9a58-e5a2db9b2f12
- [x] Ch 2.11, Product Codes Image: https://dev-onrr-cms.app.cloud.gov/admin/files/a7f04b85-ed15-452e-9052-5369ce1d09a0
- [x] Ch 3.1.1, has the Indian Gas Index Zone Map: https://dev-onrr-cms.app.cloud.gov/admin/files/c2339783-0219-4fa4-8f9f-e1b6f4575950
- [x] Product Codes Tab, Product Codes Image: https://dev-onrr-cms.app.cloud.gov/admin/files/a7f04b85-ed15-452e-9052-5369ce1d09a0

**Valuation and Pricing** 

- [x] RVPA image: https://dev-onrr-cms.app.cloud.gov/admin/files/9a8e7d3e-fa93-45fc-945d-586f88e57793

**Interactive Example (2016 Valuation Rule Federal Processed Gas Reporting Example)**

- [x] Product Codes image: https://dev-onrr-cms.app.cloud.gov/admin/files/a7f04b85-ed15-452e-9052-5369ce1d09a0
- [x] PC 03 Steps 4-5: https://dev-onrr-cms.app.cloud.gov/admin/files/4465ee32-20d6-4405-8311-465c327e0007
- [x] PC 07 Step 4: https://dev-onrr-cms.app.cloud.gov/admin/files/7a9c6067-03ef-4693-8372-5ed5c40bb329
- [x] PC 15 Step 1: https://dev-onrr-cms.app.cloud.gov/admin/files/a5863949-1abb-4929-84d7-a3404b9f15ca
- [x] PC 15 Step 2: https://dev-onrr-cms.app.cloud.gov/admin/files/56ccb509-b3cf-4675-93fb-ebff97fbf470
- [x] PC 15 Step 3: https://dev-onrr-cms.app.cloud.gov/admin/files/309a1dd1-13d3-4fba-b662-9173d44a0515
- [x] TA Step 9a: https://dev-onrr-cms.app.cloud.gov/admin/files/c37ec825-0142-4933-aa50-4e4bded7953a
- [x] RVLA Step 1: https://dev-onrr-cms.app.cloud.gov/admin/files/b84952e8-8c94-4e5d-9ec6-497ef71b5325
- [x] Sample Statement: https://dev-onrr-cms.app.cloud.gov/admin/files/48d1b918-a27d-41f1-930d-c1d78f0a24a8
- [x] Product Code Image: https://dev-onrr-cms.app.cloud.gov/admin/files/a7f04b85-ed15-452e-9052-5369ce1d09a0

**Interactive Example (Percent-of-Proceeds (POP) Contract Reporting Pre-2016)**

- [x] Gross Proceeds Step 7: https://dev-onrr-cms.app.cloud.gov/admin/files/3c687c28-3476-49f4-8b8b-4de3512b2c36
- [x] Sample Statement: https://dev-onrr-cms.app.cloud.gov/admin/files/5599773c-0480-48cb-8235-562a8cb466c4
- [x] Product Codes image: https://dev-onrr-cms.app.cloud.gov/admin/files/a7f04b85-ed15-452e-9052-5369ce1d09a0

**Late Payment Interest** 

- [x] interest calculator formula image: https://dev-onrr-cms.app.cloud.gov/admin/files/57fb29d5-f8ba-4c25-be60-c7a9d82a063d

**Compliance**

- [x] Data Mining Review image: https://dev-onrr-cms.app.cloud.gov/admin/files/53a22524-dddf-49ce-b973-80bb8fd4b838

**Assistance**

- [x] IESE Logo image: https://dev-onrr-cms.app.cloud.gov/admin/files/eac9a769-0009-4bd3-80c0-fb772cf4a131

**Indian Pricing**

- [x] Indian Gas Index Zone Map: https://dev-onrr-cms.app.cloud.gov/admin/files/c2339783-0219-4fa4-8f9f-e1b6f4575950
- [x] Indian Gas Major Portion Map; https://dev-onrr-cms.app.cloud.gov/admin/files/6ee9dccb-8b27-4285-8b0e-470444bf5843

**Employment**

- [x] Healthy Workplace logo: https://dev-onrr-cms.app.cloud.gov/admin/files/a50d3976-f416-4f89-bbb4-78210a787e53
- [x]  USA Jobs logo: https://dev-onrr-cms.app.cloud.gov/admin/files/bf6ca679-348e-4248-b620-9c0151e9dd68

**Comment by Maroyafaied** [comment]
@mojobnichols please give a status update on this issue.

**Comment by cthomasONRR** [comment]
@mcharg I added the alt text in each page. All images above should show the associated alt text now. Want to review? I will make an issue to review all pages to make sure alt text is in both the image file location and the individual instance on each page.
