### ISSUE TITLE
May Analytics 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#1990]

**Comment by cthomasONRR** [comment]
@mcharg This is ready for your review. Waiting on the image to be viewable because of the branch updates, but it's update in the file folder. 
https://github.com/ONRR/onrr.gov-site/wiki/Analytics

**Comment by mcharg** [comment]
@cthomasONRR The dashboard report needs to be uploaded to this folder.
![image](https://user-images.githubusercontent.com/38465926/173431242-a5f82d4d-0df0-49e1-b093-17d337c56c36.png)

**Comment by cthomasONRR** [comment]
@mcharg It's there for me:
![image](https://user-images.githubusercontent.com/72526208/173431870-86adbc12-ab18-4d4b-a27f-9a4a5416be3b.png)
https://github.com/ONRR/research/tree/master/onnr-dot-gov-research/analytics/FY22

**Comment by mcharg** [comment]
@cthomasONRR Looks good!
