### ISSUE TITLE
Add caution and info icons to cards

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1993]
- [x] 2016 Processed Gas Example

- [x] POP Unprocessed Gas Example

- [x] Indian Payor Handbook

**Comment by cthomasONRR** [comment]
@mcharg Want to click through these 3 webpages and make sure I got icons on all the cards?

**Comment by mcharg** [comment]
@cthomasONRR I think you got them all. Are these pages ready for ODDD approval now?

**Comment by cthomasONRR** [comment]
@mcharg The only things missing are: 

- [ ] Colors for the icons
- [ ] Next and back links (blocked by directus bug)

So I guess they are ok for approval.
