### ISSUE TITLE
Active Agreements and Active Lease Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#1995]
Please update the following webpage:
https://onrr.gov/reportpay/CrossRef.htm

1. Active Agreements - sorted by State and Agreement name.
2. Active Agreements - sorted by State and Agreement number.

with the attached excel files.  Please also change (updated 1/01/2022) to 6/9/2022 for both.
[saanum.xlsx](https://github.com/ONRR/onrr.gov-site/files/8873163/saanum.xlsx)
[saaname.xlsx](https://github.com/ONRR/onrr.gov-site/files/8873164/saaname.xlsx)

**Comment by cthomasONRR** [comment]
@bowlenj Thanks for your clarifications. This is on the dev site: http://2017onrr/reportpay/CrossRef.htm.

Please review and give us your approval to go live.

Thanks,
Christine

**Comment by bowlenj** [comment]
Perfect, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, June 9, 2022 1:21 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Active Agreements and Active Lease Update (Issue #1995)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cde31bcafe24b444063fd08da4a4d359a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637903993170165447%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jPPDbML4eDdcvv%2Fs3%2FShdl9tvMtjVFI2DyUuLCHv6mA%3D&reserved=0> Thanks for your clarifications. This is on the dev site: http://2017onrr/reportpay/CrossRef.htm.

Please review and give us your approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj Great, this is live: https://www.onrr.gov/reportpay/CrossRef.htm. Please remember to use "Ctrl+F5" to refresh the page.

Thanks,
Christine
