### ISSUE TITLE
Revise sample statement copy to not mention gold text

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1998]
https://dev-onrr-frontend.app.cloud.gov/references/valuation/processed-gas-example?tabs=sample-statement
https://dev-onrr-frontend.app.cloud.gov/references/valuation/pop-example?tabs=sample-statement

**Comment by mcharg** [comment]
@cthomasONRR This is ready to review.

**Comment by cthomasONRR** [comment]
@mcharg looks good, thanks!
