### ISSUE TITLE
Update favicon

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#1999]
Should we use the one from NRRD or the ONRR logo?

**Comment by mcharg** [comment]
@Maroyafaied Do we want to use the favicon from NRRD or the ONRR logo?

**Comment by mcharg** [comment]
NRRD:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/6504878f-32c8-4e23-8540-dfbe1be3d204)
ONRR logo:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/3ebc4ed9-777f-4abb-8367-1b880b7ad74b)

**Comment by Maroyafaied** [comment]
@mcharg ONRR logo.

**Comment by mcharg** [comment]
https://dev-onrr-frontend.app.cloud.gov/

**Comment by mcharg** [comment]
@Maroyafaied This is ready to review.

**Comment by mcharg** [comment]
Also updated on the search results page. https://search.usa.gov/search?affiliate=onrr.gov

**Comment by Maroyafaied** [comment]
@mcharg looks great.

**Comment by mcharg** [comment]
If you need to update the favicon after I leave, the SVG and ICO files are in this folder. https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Visual%20Design/Favicon?csf=1&web=1&e=nFi2qD
