### ISSUE TITLE
Recruit participants for onrr.gov user interviews

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#20]
I think we'll be ready to start recruiting next sprint.  

It'll probably need to be internal folks recruiting, since we can't share the market map spreadsheet with the interns.

**Comment by Maroyafaied** [comment]
I added a column in the market map for onrr.gov to keep track of who we contact 

https://doimspp-my.sharepoint.com/:x:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7BC55B52B5-A7E3-40D3-983D-FD8D95FA993B%7D&file=Market%20Map.xlsx&action=default&mobileredirect=true

I created a new folder for this study called onrr.gov iles
NRRD Portal >User Research>Studies>31_onrr.gov

**Comment by mcharg** [comment]
Recruiting requirements from the study plan:

Over the course of a few weeks, we would like to interview at least 4 participants from each of the following user groups for 30 minute 1:1 interviews. We will focus on people who actually use the site because they will have real questions that they look for the site to answer.
 
User Type 1: Operator (Reporter)
User Type 2: Payor
User Type 3: Production (Internal) 
User Type 4: Royalty (Internal)
User Type 5: Compliance (Internal)

**Comment by Maroyafaied** [comment]
I just found two pdf's with ONRR's royalty reporting and production reporting contacts, if you send recruiting emails please add them to market map and mark that you contacted them. Thanks

ONRR"s royalty reporting contacts
https://www.onrr.gov/ReportPay/PDFDocs/royassign.pdf

ONRR's production reporting contacts 
https://www.onrr.gov/ReportPay/PDFDocs/operasgn.pdf

**Comment by jennmalcolm** [comment]
Will create a new issue for only ONRR folks.
