### ISSUE TITLE
FAQ page linked from footer returns a 404 error

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#200]
Current url: https://www.onrr.gov/about/faqs.htm
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/6627ee3f-bc15-4b77-a991-4cf653e894bf)

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/21303c51-cd36-40b5-9033-9a2d2285a774)

**Comment by jennmalcolm** [comment]
This should be updated in all pages in dev. @Maroyafaied could you review please?

**Comment by Maroyafaied** [comment]
@jennmalcolm I don't see the FAQ's in the footer in dev 
![image](https://user-images.githubusercontent.com/40175688/89832040-179db480-db1c-11ea-8c0e-5188ef3f9f73.png)

**Comment by jennmalcolm** [comment]
Yes, thanks. I meant to remove it.
