### ISSUE TITLE
Update spacing in Processed Gas example

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#2003]
https://dev-onrr-frontend.app.cloud.gov/references/valuation/processed-gas-example?tabs=overview

RV doesn't like the spaces with the text of the Overview section. I believe I can fix this when the Directus pagination bug is fixed. 

![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/f18dc292-a1bd-4860-b462-9ae376285f27)

**Comment by cthomasONRR** [comment]
Completed: 
![image](https://user-images.githubusercontent.com/72526208/173834324-f03dc719-d7d4-483b-9d6b-ae11ad9bea32.png)

@mcharg Want to review?

**Comment by mcharg** [comment]
@cthomasONRR Looks good.
