### ISSUE TITLE
Submit sitemap to Bing and Google 

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#2007]
https://smallbusiness.chron.com/submit-map-bing-75016.html

**Comment by cthomasONRR** [comment]
Method to submit to Bing: https://smallbusiness.chron.com/submit-map-bing-75016.html
![image](https://user-images.githubusercontent.com/72526208/182223383-ea13fdb0-936a-439d-8d45-9dc9f6fef365.png)

Method to submit to Google: https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap
![image](https://user-images.githubusercontent.com/72526208/182223498-303d0752-60e3-4a4d-8ea2-e7e20808dd43.png)

I emailed our search.gov contacts to see if they agree with these methods, and if they have any other suggestions.

**Comment by cthomasONRR** [comment]
Search.gov noted that this sitemap submission for Google is ok.

Search.gov also noted that it looks like Bing has stopped supporting the "ping" method ([https://blogs.bing.com/webmaster/may-2022/Spring-cleaning-Removed-Bing-anonymous-sitemap-submission](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fblogs.bing.com%2Fwebmaster%2Fmay-2022%2FSpring-cleaning-Removed-Bing-anonymous-sitemap-submission&data=05%7C01%7Cchristine.thomas%40onrr.gov%7Cbad16ad6b92b41cdf87708da73f5a219%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637949796067412264%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fapMnZn3H4348I7hC1KH2rNZgqJZkRY02zDRPfUCGEk%3D&reserved=0)) so you may need to submit via Webmaster Tools, instructions here: [https://www.bing.com/webmasters/help/Sitemaps-3b5cf6ed](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.bing.com%2Fwebmasters%2Fhelp%2FSitemaps-3b5cf6ed&data=05%7C01%7Cchristine.thomas%40onrr.gov%7Cbad16ad6b92b41cdf87708da73f5a219%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637949796067412264%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PIVUk7VwJawUnLkcXUT2wijMcj4DgVYm5adFR6NrP4I%3D&reserved=0)

**Comment by Maroyafaied** [comment]
@cthomasONRR BSEE will be able to verify the website when the time comes. Please see the email forwarded on 8/8. Thanks

**Comment by Maroyafaied** [comment]
@eelzi-ONRR we can do this on Friday or next week. We will need Rob from BSEE to be around to coordinate.

**Comment by eelzi-ONRR** [comment]
@Maroyafaied @cthomasONRR can one of you please forward me the email mentioned in this comments to this issue? Just so I have that background info before we talk to Rob? Thx!

**Comment by eelzi-ONRR** [comment]
Updated link for sitemap: [https://onrr.gov/documents/sitemap.xml](https://onrr.gov/documents/sitemap.xml
)

Updated sitemap has been submitted to Google

**Comment by Maroyafaied** [comment]
@eelzi-ONRR Thanks for submitting to Google. For Bing, let's try the XML file verification method before we resort to adding the camae record to DNS method. I can try this once it's ok to push dev to beta. ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/8ecfacec-dcd3-4685-895f-68dec62e3694)
