### ISSUE TITLE
Offline sketching user types 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2011]

**Comment by cthomasONRR** [comment]
I added my brainstorming ideas to the folder [here](https://teams.microsoft.com/_#/files/General?groupId=81f624a1-bcde-4f77-ba3b-69c787c88ed3&threadId=19%3A34f9f9ee6b0441dbacab56bfd552f819%40thread.skype&ctx=channel&context=User%2520Types&rootfolder=%252Fsites%252FNRRD%252FShared%2520Documents%252FGeneral%252FONRR.gov%252FUser%2520Research%252FUser%2520Types)

**Comment by mcharg** [comment]
Added my sketches. https://doimspp.sharepoint.com/:p:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/User%20Research/User%20Types/Sketches/Shannon_Sketches.pptx?d=w60275f70daa14ea7a34b2a7c7eac37f7&csf=1&web=1&e=YpC22O

**Comment by Maroyafaied** [comment]
Added my sketch 

https://teams.microsoft.com/l/file/AE9F2492-FEFE-42F9-A576-CF2B4BA766CC?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=pptx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FUser%20Research%2FUser%20Types%2FSketches%2FMaroya's%20sketch.pptx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a
