### ISSUE TITLE
Conduct dev study 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2016]

**Comment by cthomasONRR** [comment]
Here's a thank you email template we can use for this study. I can send these to the 2 participants so far:

SUBJECT: Thank you for providing feedback on the new onrr.gov!

"Hello [participant name],

Thank you so much for taking time out of your work day to talk with the Open Data, Design, and Development team. Your feedback on the new onrr.gov is very much appreciated and valued! 

If you have any remaining questions/comments/concerns, please feel free to respond to this email and we will be happy to continue the conversation.

Thanks again,
Christine"

**Comment by cthomasONRR** [comment]
Closing and opening a new issue for next sprint.
