### ISSUE TITLE
Consolidate Dev Study Findings 

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/onrr.gov-site#2024]

**Comment by cthomasONRR** [comment]
@lpgoldstein 

I started a presentation on the study findings. Presentation is in the Study 12 Folder. 
Presentation here: https://teams.microsoft.com/l/file/EE069225-4962-4C3C-9793-DDCD6CAADF23?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=pptx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FUser%20Research%2FStudies%2F12_DevSite%2F12_Dev%20Site%20Study.pptx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by cthomasONRR** [comment]
@lpgoldstein Thanks! I added more visuals, and an additional slide about our findings on "Search".

**Comment by cthomasONRR** [comment]
Changing this to a 5 since it includes both consolidating findings and creating the presentation

**Comment by Maroyafaied** [comment]
@cthomasONRR This is great, I made minor comments.

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks! I addressed your comments.
