### ISSUE TITLE
SHAWNEE AREA VIRTUAL OUTREACH

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#2028]
SHAWNEE AREA VIRTUAL OUTREACH
Thursday, July 21, 2022 
1:00 PM– 2:00 PM CST

LOCATION: By Telephone

DESCRIPTION: Meeting will be a Call-in Meeting to hear a brief presentation and updates from the ONRR Outreach Office.  Representatives from each of the BLM, BTFA, and BIA will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust property issues, and agency updates.  Owners will have an opportunity to ask questions for the representatives of the four agencies during the Q&A session.

WHO SHOULD ATTEND: IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Shawnee Agency Area, Southern Plains region in Oklahoma. 

OTHER INFORMATION: To reserve a space and get the call-in number and passcode for this meeting you may contact the ONRR OKC Outreach office at (800) 354-7015. Office hours are Mon- Fri., 7:30 AM-5:00 PM CST. 

CONTACT: ONRR OKC Outreach Office, PHONE: (800) 354-7015 (toll-free)
EMAIL: [onrroutreachokc@onrr.gov](https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=onrroutreachokc@onrr.gov)

**Colorado, Idaho, Nebraska, Utah, Wyoming Virtual Outreach**
Thursday, July 28, 2022 
10;00 AM – 10:30 AM CST

LOCATION:  By Telephone 

DESCRIPTION: Representatives from the Office of Natural Resources Revenue will host a Question and Answer session by phone for Indian Mineral Owners and Trust Property Owners regarding their Indian Oil & Gas leases, IIM Accounts, and Indian Trust Properties. Representatives from the Bureau of Land Management, Bureau of Indian Affairs, and Bureau of Trust Funds Administration are invited to be in attendance to answer questions.

WHO SHOULD ATTEND:  IIM account holders, Indian mineral owners, and Indian trust property owners in the Towaoc, Ignacio, Omaha, Fort Hall, Fort Duchesne, Salt Lake City, and Wind River areas.

OTHER INFORMATION: To attend the outreach session, please contact the ONRR Denver Outreach Office at (800) 982-3226, for the call-in number and passcode.  The ONRR Denver Outreach Office hours are Monday-Friday 7:30am-4:00pm. 

CONTACT:  ONRR Denver Outreach Office, Toll Free (800) 982-9226, Email: [onrroutreachdenver@onrr.gov](mailto:onrroutreachdenver@onrr.gov)

**Comment by lpgoldstein** [comment]
@Toddsand21 Ready for your review: http://2017onrr/events.htm

**Comment by Toddsand21** [comment]
On the Colorado meeting Please change the time to MST after it reads ....10:30 AM MST

Other than that it looks fine.  Thanks!

**Comment by lpgoldstein** [comment]
@Toddsand21 Changed to MST and I'll let you know when it goes live. Thanks!

**Comment by Toddsand21** [comment]
Thank you I appreciate it!

Sandra Todd
Minerals Revenue Specialist
Office of Natural Resources Revenue
Indian Outreach, OKC
(405) 879-6052
(800) 354-7015
________________________________
From: lpgoldstein ***@***.***>
Sent: Friday, July 1, 2022 2:39 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Todd, Sandra L. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] SHAWNEE AREA VIRTUAL OUTREACH (Issue #2028)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Toddsand21<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FToddsand21&data=05%7C01%7Csandra.todd%40onrr.gov%7C3df547e5244f4e8c4ca508da5b995f55%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637923011538425925%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HhRISpWfSZ6Bj491W32Y%2FeugjWI%2FSW2gBNl%2BtIVWojw%3D&reserved=0> Changed to MST and I'll let you know when it goes live. Thanks!

**Comment by lpgoldstein** [comment]
@Toddsand21 It's live so I'm closing the issue. Thanks!
