### ISSUE TITLE
Homepage language

### ISSUE THREAD

**Issue by jpetersononrr** [ONRR/onrr.gov-site#203]
Morning!

Could you please replace the language on the home page under the 2016 Valuation rule change to replace the training language with:

"An example of how to value processed gas under the new 2016 Valuation Rule can be found here."  (Link for "here":  https://www.onrr.gov/valuation/2016-rule-processed-example.htm) 

Thanks!

**Comment by jennmalcolm** [comment]
The changes are ready for your review in dev @jpetersononrr

**Comment by jpetersononrr** [comment]
Looks great!  Thank you!!

​Jodie Peterson
Minerals Revenue Specialist
Office of Natural Resources Revenue
​jodie.peterson@onrr.gov
(303)231-3719

Royalty Valuation - Consistent Answers to Complex Questions

**Comment by jennmalcolm** [comment]
changes are live

**Comment by jpetersononrr** [comment]
Thank you!
