### ISSUE TITLE
Webpage - Active Leases

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#2036]
Hello, please update the following webpage:
www.onrr.gov/ReportPay/CrossRef.htm with the attached file.

Active Leases- Sorted by state and Agency Lease number- please update to show updated 07/01/2022.

Thank you!
[ALwState.xlsx](https://github.com/ONRR/onrr.gov-site/files/9055852/ALwState.xlsx)

**Comment by merrellc** [comment]
Approved. Thank you!


Kind Regards,
​Candace Merrell
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.
________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, July 6, 2022 8:57 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Webpage - Active Leases (Issue #2036)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@merrellc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmerrellc&data=05%7C01%7Ccandace.merrell%40onrr.gov%7Cbf22b4933b3444485aa308da5f5fd859%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637927162502586588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jtZhCs6JXeU1aJnOmCHvVFQooG%2B6Z0KKVVDH%2FbWS%2B34%3D&reserved=0>

Good morning, this change is in the dev site: http://2017onrr/reportpay/CrossRef.htm
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@merrellc 

Great, this change is live: https://www.onrr.gov/reportpay/CrossRef.htm
Please use "Ctrl+F5" to refresh the page.

Closing this issue now.

Thanks,
Christine
