### ISSUE TITLE
Webpage Update (Active Agreements)

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#2037]
Hello, please update the following webpae:
www.onrr.gov/ReprotPay/CrossRef.htm
Active Agreements - sorted by State and Agreement name
Active Agreements - sorted by state and Agency Agreement number

Also update date to read 07/01/2022

Thank you!

[saaname.xlsx](https://github.com/ONRR/onrr.gov-site/files/9055900/saaname.xlsx)
[saanum.xlsx](https://github.com/ONRR/onrr.gov-site/files/9055901/saanum.xlsx)

**Comment by cthomasONRR** [comment]
@merrellc It looks like "saanum" was removed for the site... do you want to add it back in?

**Comment by merrellc** [comment]
No. Do not add back in. Thank you!


Kind Regards,
​Candace Merrell
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.
________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, July 6, 2022 9:06 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Webpage Update (Active Agreements) (Issue #2037)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@merrellc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmerrellc&data=05%7C01%7Ccandace.merrell%40onrr.gov%7Cf8f89d74e414406c53b608da5f612a8b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637927168173648754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yqbIGdRT98wTjOJ8ouJbbhtpeNFwLiLRDspcIDe0TCM%3D&reserved=0> It looks like "saanum" was removed for the site... do you want to add it back in?

**Comment by cthomasONRR** [comment]
@merrellc 

Ok, "saaname" is updated on the dev site: http://2017onrr/reportpay/CrossRef.htm
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by merrellc** [comment]
Approved. Thank you!


Kind Regards,
​Candace Merrell
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.
________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, July 6, 2022 9:26 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Webpage Update (Active Agreements) (Issue #2037)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@merrellc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmerrellc&data=05%7C01%7Ccandace.merrell%40onrr.gov%7Cd4b3d88a60ab4d8b66e308da5f63effc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637927180077247418%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QA0fMmikDizX1oL4BjSr6EHAzuNd%2F2tfULY5Gxjd2xA%3D&reserved=0>

Ok, "saaname" is updated on the dev site: http://2017onrr/reportpay/CrossRef.htm
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@merrellc 

Great, this change is live: https://www.onrr.gov/reportpay/CrossRef.htm
Please use "Ctrl+F5" to refresh the page.

Closing this issue now.

Thanks,
Christine
