### ISSUE TITLE
Update June NYMEX on onrr.gov

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#2039]
Good afternoon,

Please update the June NYMEX prices on the website.

Thank you!

@sudarr
[NYMEX062022.xlsx](https://github.com/ONRR/onrr.gov-site/files/9058035/NYMEX062022.xlsx)

**Comment by boices** [comment]
That's perfect--thanks again!

**Comment by cthomasONRR** [comment]
@boices 

Great, these changes are live: https://www.onrr.gov/valuation/NYMEX.htm
Please remember to use "Ctrl+F5" to refresh the page.

Closing this issue now.

Thanks,
Christine
