### ISSUE TITLE
FS Federal Contact Info Update - ONRR.GOV Payments Page

### ISSUE THREAD

**Issue by jdougherty913** [ONRR/onrr.gov-site#204]
[finserAssign.pdf](https://github.com/ONRR/onrr.gov-site/files/4821960/finserAssign.pdf)
Good afternoon, please see attached to be used to update the FS Federal Team contact sheet on ONRR.gov. The URL is https://www.onrr.gov/ReportPay/payments.htm

**I tried uploading the file, but it does not appear to be working. Please contact me so I can provide the file that needs uploaded. Jennifer.dougherty@onrr.gov

**Comment by lpgoldstein** [comment]
@jdougherty913 This is ready for your review: http://2017onrr/ReportPay/PDFDocs/FSFederalCOAssignm.pdf

**Comment by jdougherty913** [comment]
Thank you, I submitted the wrong file. Please use this file instead.
[finserAssign.pdf](https://github.com/ONRR/onrr.gov-site/files/4827688/finserAssign.pdf)

**Comment by lpgoldstein** [comment]
@jdougherty913 This is ready for your review again.

**Comment by jdougherty913** [comment]
looks good, thank you!

**Comment by lpgoldstein** [comment]
@jdougherty913 it should be live soon!

**Comment by jdougherty913** [comment]
I realized that the contact us page on onrr.gov needs to be updated as well with the same file I had provided previously provided for the Payments page.  
[Doc1.docx](https://github.com/ONRR/onrr.gov-site/files/4838835/Doc1.docx)
[finserAssign.pdf](https://github.com/ONRR/onrr.gov-site/files/4838837/finserAssign.pdf)

**Comment by lpgoldstein** [comment]
@jdougherty913 This is ready for your review again: http://2017onrr/about/contact.htm

**Comment by jdougherty913** [comment]
Looks good, thank you!

Jennifer Dougherty
Supervisor, Financial Services Team 2
Revenue, Reporting, & Compliance Management
Office of Natural Resources Revenue
Bldg 85, Denver Federal Center
Denver, CO 80225
1-800-433-9801 ext. 3563
303.231.3563
jennifer.dougherty@onrr.gov<mailto:jennifer.dougherty@onrr.gov>

**Comment by lpgoldstein** [comment]
@jdougherty913 - It should be live soon!
