### ISSUE TITLE
Posting of July Indian Index Zone Prices

### ISSUE THREAD

**Issue by penvosej** [ONRR/onrr.gov-site#2040]
Hello, the July 2022 Indian Index Zone prices are ready to be published on ONRR.gov. The "Data for ONRR.gov" Excel spreadsheet has been updated with the data you need. Can you please also make sure all prices display to the thousandths place? Thanks!!

@sudarr

**Comment by Maroyafaied** [comment]
@penvosej please review http://2017onrr/valuation/allzones.htm

**Comment by penvosej** [comment]
Hi Maroya,

Everything looks great! Thanks for doing that.

Jessica

From: Maroyafaied ***@***.***>
Sent: Thursday, July 7, 2022 6:18 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Posting of July Indian Index Zone Prices (Issue #2040)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpenvosej&data=05%7C01%7CJessica.Penvose%40onrr.gov%7C93b5dad65c0f4d21be6f08da6012b0ad%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637927930639205136%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wwyb5%2Byq8Pd0oGkdNrA3LTa81Dw20Iy7SkDqytYnUv8%3D&reserved=0> please review http://2017onrr/valuation/allzones.htm

-

**Comment by Maroyafaied** [comment]
@penvosej you're welcome. It's live now. Thanks
