### ISSUE TITLE
Draft strategy & communication plan for the new website launch

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2044]
- Figure out how to communicate the launch internally and externally to industry
- Think about offering demos of how to navigate the website before we launch

**Comment by cthomasONRR** [comment]
Some thoughts:

- I'd be happy to do internal ONRR 'lunch and learns' where I demo the site.
- To communicate to external users, I believe most groups have listservs/mailing lists. I know RV has one. Maybe RRM has one too. Could we draft an email for them to send out to their mailing lists?
- We could add a banner to the current onrr.gov site stating the anticipated launch.
- We could get an announcement in the DOI All Employee Digest email. (Not sure how to submit to it).
- We could post to the gov listservs that we are part of, to get the word out across federal entities.

**Comment by cthomasONRR** [comment]
@lpgoldstein Love the market map idea!

For the website, we could add something before or after the scam alert... but yeah it would be best to do this when we know our launch date and know that it will not change.
![image](https://user-images.githubusercontent.com/72526208/182660465-47707a9f-fd16-4eac-86a9-24ca89f37e08.png)

**Comment by Maroyafaied** [comment]
Another idea that was discussed is to make our scheduled demos as a "lunch & learn" until we launch and adding more audiance.
