### ISSUE TITLE
Update ONRR.gov

### ISSUE THREAD

**Issue by bakercook** [ONRR/onrr.gov-site#2049]
Please replace the CY 2022 IDD calendar on the website with the updated memo.

[CY 2022 Disb Memo_2.pdf](https://github.com/ONRR/onrr.gov-site/files/9066569/CY.2022.Disb.Memo_2.pdf)

[ONRR.gov location.docx](https://github.com/ONRR/onrr.gov-site/files/9066599/ONRR.gov.location.docx)

Also, please remove the CY 2021 memo from the website.  

Thank you,

**Comment by cthomasONRR** [comment]
@bakercook 

Hello,

Please let me know if you and your team are having issues getting a 508-compliant version of this document. I have some resources that may help.

Thanks,
Christine

**Comment by bakercook** [comment]
Hi Christine,

Please find attached updated 508 compliant memo. Do you want me to me submit another github request?

Thank you.



Respectfully,

Cheri Baker
Supervisor, Accounts Payable
Office of Natural Resources Revenue
Phone: 303-231-3137


From: Christine Thomas ***@***.***>
Sent: Thursday, July 7, 2022 3:11 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Baker, Cheri L ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update ONRR.gov (Issue #2049)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bakercook<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbakercook&data=05%7C01%7Ccheri.baker%40onrr.gov%7C07eeae12a7ed412e7f4208da605d4d94%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637928251668906588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=d8amf%2BABIrF1N6NMGndpWFyrT%2FCOPME5L9eIqHwbFuU%3D&reserved=0>

Hello,

I checked your PDF, and it has 508 Compliance accessibility issues. Please send us an accessible version of this document and we can post it on the website.

Thanks, Christine.

[Image removed by sender. image]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F72526208%2F177871963-b6224722-77fb-487a-a6be-ec713be0c0e8.png&data=05%7C01%7Ccheri.baker%40onrr.gov%7C07eeae12a7ed412e7f4208da605d4d94%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637928251668906588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=fvVriUZlAA3pCSoUo4wpLYh%2B%2BkFDDMBcsRNU%2F7IIOuY%3D&reserved=0>

-

**Comment by cthomasONRR** [comment]
@bakercook 

Hi Cheri,

I did not receive the attachment. Could you please email it to me at christine.thomas@onrr.gov?
No need to create a new issue, thanks!

Christine

**Comment by cthomasONRR** [comment]
@bakercook 

Thanks for emailing the doc to me!

Just FYI- the doc had 1 accessibility error. I was able to quickly fix it by going into the tags panel and specifying that that text was a paragraph and not a table. I will email you this updated doc. 
![image](https://user-images.githubusercontent.com/72526208/178766455-fa696b6f-a176-4531-a342-eb77d3722266.png)

These updates are now on the dev site: http://2017onrr/IndianServices/tribal-assistance.htm
Please review and give us your approval to go live.

Thanks,
Christine
