### ISSUE TITLE
Update to Forms page

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2050]
Please remove Aaron Lindquist's name and email from the Address/Addressee of Record Changes (Form ONRR-4444) section on the forms page at  https://www.onrr.gov/reportpay/Forms/index.htm.

Please replace with - Form ONRR-4444 may be emailed to forms.industry@onrr.gov.

**Comment by mcharg** [comment]
@bowlenj We've also got Aaron's email on the new reporter checklists. Do you want it updated there, as well?

**Comment by bowlenj** [comment]
Yes please also remove Aaron's name and email from New Royalty Reporter Checklist (onrr.gov)<https://www.onrr.gov/reportpay/roy-checklist.htm> and replace with email form to ***@***.***  Thank you for finding that!
New Royalty Reporter Checklist<https://www.onrr.gov/reportpay/roy-checklist.htm>
Perform the following tasks to assure your company is set up to report and remit rental and royalties for Federal and Indian leases/agreements correctly and timely.. Have ONRR assign a Payor Code to your company. To obtain your ONRR Payor Number, to set up electronic reporting, and to receive an explanation of reporting requirements, email both contacts listed below:
www.onrr.gov


Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: mcharg ***@***.***>
Sent: Friday, July 8, 2022 11:47 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update to Forms page (Issue #2050)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C20442755a8b341404ca508da6109f9dd%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637928992716960139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BidhO4Tkyjy7EDiHDqpxMpYFBmxTP7b5ElgQBzZCWHs%3D&reserved=0> We've also got Aaron's email on the new reporter checklists. Do you want it updated there, as well?

**Comment by bowlenj** [comment]
I also found his name on the production and solids checklist.  Can you also update those?

New Solid Minerals Reporters (onrr.gov)<https://www.onrr.gov/reportpay/solids-checklist.htm>
Reporter Information Maintenance (onrr.gov)<https://www.onrr.gov/reportpay/prod-checklist.htm>
Reporter Information Maintenance<https://www.onrr.gov/reportpay/prod-checklist.htm>
Perform the following tasks to assure your company is set up to report production for Federal and Indian leases/agreements correctly and timely.. Get an Outer Continental Shelf (OCS) Qualification Number (if you'll be reporting offshore production) Call any of the 3 Outer Continental Shelf (OCS) Regional offices to apply for an OCS Qualification Number.
www.onrr.gov

New Solid Minerals Reporters<https://www.onrr.gov/reportpay/solids-checklist.htm>
It's Secure. This site is protected by a Secure Sockets Layer (SSL) Certificate authorized through the United States Government. The https:// means all transmitted data is encrypted - in other words, any information or browsing history that you provide is transmitted securely.
www.onrr.gov


Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: mcharg ***@***.***>
Sent: Friday, July 8, 2022 11:47 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update to Forms page (Issue #2050)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C20442755a8b341404ca508da6109f9dd%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637928992716960139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BidhO4Tkyjy7EDiHDqpxMpYFBmxTP7b5ElgQBzZCWHs%3D&reserved=0> We've also got Aaron's email on the new reporter checklists. Do you want it updated there, as well?

**Comment by mcharg** [comment]
Of course. I also Reporter Maintenance page when I did a site search on the email address.  Will also find all the places on the new site.

**Comment by mcharg** [comment]
@bowlenj 

The following pages are ready to review in dev on the old site:
http://2017onrr/reportpay/forms/index.htm
http://2017onrr/reportpay/roy-checklist.htm
http://2017onrr/reportpay/prod-checklist.htm
http://2017onrr/reportpay/solids-checklist.htm
http://2017onrr/reportpay/reporter-maintenance.htm

**Comment by mcharg** [comment]
@bowlenj

The following pages are ready to review on the new site:
https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist
https://dev-onrr-frontend.app.cloud.gov/getting-started/system-access
https://dev-onrr-frontend.app.cloud.gov/about/contact/4444-contacts?panel=i-need-to-give-onrr-my-companys-contact-information&tabs=troubleshooting
https://dev-onrr-frontend.app.cloud.gov/about/contact/getting-started-contacts?panel=i-need-to-give-onrr-my-companys-contact-information

Do you want us to update the contacts on this page?
https://dev-onrr-frontend.app.cloud.gov/about/contact/4444-contacts?panel=i-need-to-give-onrr-my-companys-contact-information&tabs=contacts

**Comment by bowlenj** [comment]
This looks great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: mcharg ***@***.***>
Sent: Friday, July 8, 2022 12:14 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update to Forms page (Issue #2050)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C9720c15ed2894848d6ba08da610dab1b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637929008577427268%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=b8yZBFnj%2BOc%2FrQDW9n8lZPiRLbKpLL6tKnMo4VkdHgI%3D&reserved=0>

The following pages are ready to review in dev on the old site:
http://2017onrr/reportpay/forms/index.htm
http://2017onrr/reportpay/roy-checklist.htm
http://2017onrr/reportpay/prod-checklist.htm
http://2017onrr/reportpay/solids-checklist.htm
http://2017onrr/reportpay/reporter-maintenance.htm

**Comment by bowlenj** [comment]
This looks great, and yes let's go ahead and update the contacts on the new page also.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: mcharg ***@***.***>
Sent: Friday, July 8, 2022 12:28 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update to Forms page (Issue #2050)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C8796c73775de47c57d2e08da610fa3c5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637929017044040517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IR3sptqzaQEY2p0sQ%2FREDUmIG4ZRZK64dnuiDmkKgqE%3D&reserved=0>

The following pages are ready to review on the new site:
https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-checklist<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Fgetting-started%2Fnew-reporter-checklist&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C8796c73775de47c57d2e08da610fa3c5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637929017044040517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iIQBgqgzr8esmAb7R8vuw90v3Vre6s2S0kxv2Q3Li3w%3D&reserved=0>
https://dev-onrr-frontend.app.cloud.gov/getting-started/system-access<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Fgetting-started%2Fsystem-access&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C8796c73775de47c57d2e08da610fa3c5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637929017044040517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JRfC3%2Bcd1Akb23UrUuOtRpDuBIoC3V9Of3HNxVCfWBA%3D&reserved=0>
https://dev-onrr-frontend.app.cloud.gov/about/contact/4444-contacts?panel=i-need-to-give-onrr-my-companys-contact-information&tabs=troubleshooting<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Fabout%2Fcontact%2F4444-contacts%3Fpanel%3Di-need-to-give-onrr-my-companys-contact-information%26tabs%3Dtroubleshooting&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C8796c73775de47c57d2e08da610fa3c5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637929017044040517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FrPvkWR30ODvGTfQJXd94yQY9epABqEqnIeOdZOZgME%3D&reserved=0>
https://dev-onrr-frontend.app.cloud.gov/about/contact/getting-started-contacts?panel=i-need-to-give-onrr-my-companys-contact-information<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Fabout%2Fcontact%2Fgetting-started-contacts%3Fpanel%3Di-need-to-give-onrr-my-companys-contact-information&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C8796c73775de47c57d2e08da610fa3c5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637929017044040517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3W8IvcyDNK2cyMPKJEHn715Qzhn6mZQ2Kda4TLD8ze0%3D&reserved=0>

Do you want us to update the contacts on this page?
https://dev-onrr-frontend.app.cloud.gov/about/contact/4444-contacts?panel=i-need-to-give-onrr-my-companys-contact-information&tabs=contacts<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Fabout%2Fcontact%2F4444-contacts%3Fpanel%3Di-need-to-give-onrr-my-companys-contact-information%26tabs%3Dcontacts&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C8796c73775de47c57d2e08da610fa3c5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637929017044040517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BXJhMfusRIrkvMy74o8s4%2BojTb8XRHTZQmxPFrrfwIo%3D&reserved=0>

**Comment by mcharg** [comment]
@bowlenj Do you want me to keep Aaron as a backup contact or remove him altogether?

**Comment by mcharg** [comment]
This is what it looks like with Aaron as a back-up. https://dev-onrr-frontend.app.cloud.gov/about/contact/4444-contacts?tabs=contacts

**Comment by bowlenj** [comment]
For the 4444's let's remove him altogether.  I'm not sure what to do about the W-9's and Lisa Salazar.....

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: mcharg ***@***.***>
Sent: Friday, July 8, 2022 1:07 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update to Forms page (Issue #2050)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C5ca42783540845b846e108da61152e9e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637929040850668063%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AA47sQISgSqSvgXOqcmzuD27v7uWrjQ3ck0LyURiL%2Fo%3D&reserved=0> Do you want me to keep Aaron as a backup contact or remove him altogether?

**Comment by bowlenj** [comment]
Let's remove him as a backup, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: mcharg ***@***.***>
Sent: Friday, July 8, 2022 1:13 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update to Forms page (Issue #2050)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



This is what it looks like with Aaron as a back-up. https://dev-onrr-frontend.app.cloud.gov/about/contact/4444-contacts?tabs=contacts<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Fabout%2Fcontact%2F4444-contacts%3Ftabs%3Dcontacts&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Ca925405a0043464df51d08da6115ebce%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637929044024728069%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rvx%2F1aEM0w2r7EEmNLe9jku42hLG%2F54J95cHXzpNpiU%3D&reserved=0>

**Comment by mcharg** [comment]
Done.
https://dev-onrr-frontend.app.cloud.gov/about/contact/4444-contacts?tabs=contacts

And I pushed the changes to the old site live. I'll close the issue when they show up.

**Comment by bowlenj** [comment]
Thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: mcharg ***@***.***>
Sent: Friday, July 8, 2022 1:21 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update to Forms page (Issue #2050)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Done.
https://dev-onrr-frontend.app.cloud.gov/about/contact/4444-contacts?tabs=contacts<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Fabout%2Fcontact%2F4444-contacts%3Ftabs%3Dcontacts&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C3320552fa1b048a7450c08da61171d80%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637929049155283943%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Lr4fHhfnVjByl7BtXbSBJ96fbu%2BnCjVHRHxZy82SPx4%3D&reserved=0>

And I pushed the changes to the old site live. I'll close the issue when they show up.

**Comment by mcharg** [comment]
Changes are live.
