### ISSUE TITLE
Update LR2000 links in the troubleshooting guide

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#2051]
New language:
LR2000 is no longer updated by BLM. You can see the updated [Serial Register Page](https://reports.blm.gov/reports/MLRS/) and find additional information in [MLRS](https://mlrs.blm.gov/s/).

**Comment by cthomasONRR** [comment]
Places updated:

- [ ] https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=troubleshooting&panel=i-need-help-finding-a-lease-or-agreement-number
- [ ] https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=troubleshooting&panel=i-need-to-know-my-royalty-rate
- [ ] https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=troubleshooting&panel=my-well-lease-or-communitization-agreement-ca-is-in-a-nonproducing-status-error-9630

@mcharg Want to review?

**Comment by mcharg** [comment]
@cthomasONRR Looks good!

**Comment by cthomasONRR** [comment]
@mcharg Should I send these links to Cody and Brittany? Or good to close?

**Comment by mcharg** [comment]
Maybe have @bowlenj review.
