### ISSUE TITLE
Directus pagination issue is back

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#2052]
@mojobnichols I'm seeing the Directus pagination issue again.

It seems to be confined to accordions. Here are locations where I have found it:

- [ ] https://dev-onrr-cms.app.cloud.gov/admin/content/pages/41 Revenue Troubleshooting expansion panel block
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/9bac4433-9bc0-477c-a220-b413addf4dc6)!
- [ ] https://dev-onrr-cms.app.cloud.gov/admin/content/pages/99 Ch 2.5 accordions, 
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/56dbc9f1-f291-4c7c-819e-31eb4a8dcb8d)!

**Comment by cthomasONRR** [comment]
- [ ] https://dev-onrr-cms.app.cloud.gov/admin/content/pages/43 Geothermal troubleshooting accordion
- [ ] https://dev-onrr-cms.app.cloud.gov/admin/content/pages/11 production, revenue, solids, and geothermal accordions

**Comment by mojobnichols** [comment]
Each collection will have its own pagination issue. since the default is 15. 

To correct as admin.

Directus -> Model -> Collection ( in this case Expansion Panel ) -> Builder Field aka M2M (in this case expansion_panel_blocks.   After clicking on fiel on panel to the right select Interface modtify per page (I set to 150)

**Comment by cthomasONRR** [comment]
@mojobnichols Is there a reason why expansion panel is greyed out? I'm afraid to change this in case it messes something up 
![image](https://user-images.githubusercontent.com/72526208/178060103-cc4ec001-160c-4d14-9a45-f3a3e601dcc2.png)

**Comment by mcharg** [comment]
@cthomasONRR I was able to click on it even though it's grayed out.

**Comment by mcharg** [comment]
I'm able to get there. @mojobnichols Some of your labels for the steps were slightly off.
![image](https://user-images.githubusercontent.com/38465926/178060295-67f3bf76-e958-4e99-bd12-ebe59e40550c.png)

I did the following:
- Settings gear
- Data model
- expansion_panels
- expansion_panel_blocks
- interface
- Per page field

**Comment by cthomasONRR** [comment]
@mojobnichols 

I found where you are referring to. I see the 150 but it says M2A instead of M2M... could you explain the difference between M2A and M2M?

![image](https://user-images.githubusercontent.com/72526208/178060491-a36dff16-0f38-4b2f-90a6-116ada95ad2e.png)


![image](https://user-images.githubusercontent.com/72526208/178060312-771c533b-3e74-4ca0-9e33-dfb1bab9e648.png)

**Comment by mcharg** [comment]
Mojo said the grayed out means it doesn't display in the collections list in Directus.  And he was assuming M2M, but M2A is fine. I showed him what I clicked on and that was it.
