### ISSUE TITLE
Add analytics for outbound links 

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#2054]
At a minimum we should have downloads and outbound links. Not sure if those are done using Google Tag Manager.

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/a7631055-ad92-4f51-b741-03a195ac94ca)

**Comment by mcharg** [comment]
@mojobnichols I forwarded an email from the DAP team about how page views are tracked using DAP. That might have something to do with why we're not seeing downloads or outbound links or documents clicked on.
[DAP coding capabilities guide](https://app.zenhub.com/files/210892300/fd8ba73a-3867-4c75-9a99-fd2208831d25/download)

Instructions from email:
Hello:

Thanks for your note. I see DAP firing on your staging server (see screenshot below). Your staging server using cloud.gov which won't show up in your profile in DAP, because it uses cloud.gov which lives in the GSA profile (see screenshot below). Your coding language will have downstream impacts on your ability to implement Google Analytics.

 

Vue.js (angular, etc.) is a dynamic coding language that does not use page views for most functionality - these are referred to as Single Page Apps and Progressive Web Apps.

 

Single page applications (SPAs) really mess with the way Google Analytics works, since Google Analytics is mostly dependent on page loads to re-initiate the javascript file. So, a SPA with no alterations made for GA only has a full pageload once, and all the other content loads are done dynamically, without an HTML refresh. You'll need to implement virtual pageviews, which tell GA that a new pageview has happened. 

I'm attaching documentation from our Github - Please see page 18 for virtual pageviews. I'm also including high level documentation from Google on [SPA's](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevelopers.google.com%2Fanalytics%2Fdevguides%2Fcollection%2Fanalyticsjs%2Fsingle-page-applications&data=05%7C01%7Cshannon.mcharg%40onrr.gov%7C1c03e6e2bd4c41c1a2f808da6362c3a9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637931573100646260%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YyjiSoplNfy5WrnHxQwMPf4%2B1RKQR4XRTnmcu6caNjM%3D&reserved=0). Please request your developer to review and you'll need to instruct them to develop virtual pageviews.

**Comment by mcharg** [comment]
@mojobnichols  Downloads/document clicks and outbound links are definitely not being tracked.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/35bdf0f5-50f1-427f-a5b4-d2d85f78f268)

**Comment by Maroyafaied** [comment]
@mojobnichols this is the code you need. ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/61c33c4a-c2bb-4ec0-999d-2a8f7fed020a)
