### ISSUE TITLE
June 2022 IBMP Pirces

### ISSUE THREAD

**Issue by damionschulte** [ONRR/onrr.gov-site#2055]
All I have updated the Data for ONRR sheet in the OneDrive with the June 22 IBMP Prices.  Can you please prepare them to be posted to the website?  I have also attached the spreadsheet with the prices in it as well.  Thanks 

Damion 

@sudarr
[June 22 IBMP For GitHub.xlsx](https://github.com/ONRR/onrr.gov-site/files/9085929/June.22.IBMP.For.GitHub.xlsx)

**Comment by cthomasONRR** [comment]
@damionschulte 
Great, these changes are now live: https://www.onrr.gov/valuation/IndianOilIBMP.htm. 
Closing this issue now.

Thanks,
Christine
