### ISSUE TITLE
Reporter Training Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2057]
Please update the training page at the following location - https://onrr.gov/reportpay/training/index.htm, with the below info:

Change training dates from January 10-14, 2022 to August 14-19, 2022 and replace the agenda and registration pdf with the attached.

Also please update Reporter Training Presentations to show January & August FY22

[August Reporter Training agenda.pdf](https://github.com/ONRR/onrr.gov-site/files/9096581/August.Reporter.Training.agenda.pdf)

**Comment by lpgoldstein** [comment]
@daniel-coleman-1 Please update this on both sites. The new site has two locations. https://dev-onrr-frontend.app.cloud.gov/references/training?tabs=training-schedule

**Comment by daniel-coleman-1** [comment]
@lpgoldstein I'm having some trouble getting the event to populate - and it doesn't seem like the events in the CMS are the same as presenting on the dev site:
![Screenshot 2022-07-13 105249](https://user-images.githubusercontent.com/83892362/178789140-1bcea023-f9b7-4360-a7ca-6cd7f82094cd.png)

![Screenshot 2022-07-13 105302](https://user-images.githubusercontent.com/83892362/178789161-797014e7-8cfb-40a9-bd07-083f4d4a7709.png)

**Comment by bowlenj** [comment]
I'm not seeing the changes on this link you sent.  Is there something I need to do on my side?


Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: daniel-coleman-1 ***@***.***>
Sent: Wednesday, July 13, 2022 10:56 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Reporter Training Update (Issue #2057)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@lpgoldstein<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flpgoldstein&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C6e8d9c3a04134777e9cd08da64f0a416%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637933281977294677%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aazNu9eVncXrn%2BMV0ncCEJhydIiy%2BG1xxkt4XrMazW8%3D&reserved=0> I'm having some trouble getting the event to populate - and it doesn't seem like the events in the CMS are the same as presenting on the dev site:
[Screenshot 2022-07-13 105249]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F83892362%2F178789140-1bcea023-f9b7-4360-a7ca-6cd7f82094cd.png&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C6e8d9c3a04134777e9cd08da64f0a416%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637933281977294677%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=T%2FChPcR%2FPOspUgfo%2B64AlroukoV%2B%2BVya8Xh57chI%2F2c%3D&reserved=0>

[Screenshot 2022-07-13 105302]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F83892362%2F178789161-797014e7-8cfb-40a9-bd07-083f4d4a7709.png&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C6e8d9c3a04134777e9cd08da64f0a416%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637933281977294677%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=s4B%2BdTS7PI57PUhNec6x1pRjDIxCBZIJoW1VHR%2B8qgk%3D&reserved=0>

**Comment by daniel-coleman-1** [comment]
@bowlenj you may need to press CTRL+F5 a handful of times to clear your cache

**Comment by bowlenj** [comment]
Hi Dan,

The link is working but the text is still reading January.  Can you please replace January 10-14, 2022 to read August 14-19, 2022.  Also please update January FY22 to read January & August FY22.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: daniel-coleman-1 ***@***.***>
Sent: Wednesday, July 13, 2022 8:15 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Reporter Training Update (Issue #2057)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C2c8e4b66bd594e60e26c08da64da2574%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637933185352327319%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mSIf4GXT7psIV2oF7LxYqOw8DtVr%2BL1Sh0JnmDXraGg%3D&reserved=0> requested changes have been implemented in the dev site:
http://2017onrr/reportpay/training/index.htm

With your approval I will push these changes live

**Comment by daniel-coleman-1** [comment]
@bowlenj if you tap CRTL+F5 the changes should appear.  I am seeing them on my side, and have pushed changes live:
https://onrr.gov/reportpay/training/index.htm

You may still need to clear your cache to see the changes.

**Comment by bowlenj** [comment]
Perfect, I see them and they look great!  Thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: daniel-coleman-1 ***@***.***>
Sent: Thursday, July 14, 2022 7:33 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Reporter Training Update (Issue #2057)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cbe7167a4a95f439e0a3308da659d66e2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637934023954536009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YkYxa6fle5tnwjjD8a0pYXYzmlAsOqUg1CL6Jt7X7zY%3D&reserved=0> if you tap CRTL+F5 the changes should appear. I am seeing them on my side, and have pushed changes live:
https://onrr.gov/reportpay/training/index.htm<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fonrr.gov%2Freportpay%2Ftraining%2Findex.htm&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cbe7167a4a95f439e0a3308da659d66e2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637934023954536009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KKXlM%2FMhD%2FPnNe0gDj3OwMRcEpiijRm73V9OOYlc25s%3D&reserved=0>

You may still need to clear your cache to see the changes.

**Comment by daniel-coleman-1** [comment]
@lpgoldstein we are good to go on the current ONRR.gov site and the Reporter Training -> Training Schedule tab, but I'm having trouble populating the event to the events page.

**Comment by lpgoldstein** [comment]
@bowlenj do you want to add this to the events page as well? https://onrr.gov/events.htm

**Comment by daniel-coleman-1** [comment]
@lpgoldstein I think I figured it out by using the InlineLink feature to add a link & button:

![Screenshot 2022-07-14 095638](https://user-images.githubusercontent.com/83892362/179025423-460f7da5-73ca-42d5-9963-1708a5acc5d1.png)

**Comment by daniel-coleman-1** [comment]
@lpgoldstein I've input your requested edits in the dev site:

http://2017onrr/reportpay/training/index.htm

http://2017onrr/events.htm

With your approval I will push these changes live

**Comment by lpgoldstein** [comment]
@daniel-coleman-1 Please push to live site.

**Comment by daniel-coleman-1** [comment]
@bowlenj @lpgoldstein we are live:
https://onrr.gov/events.htm
https://onrr.gov/reportpay/training/index.htm

**Comment by bowlenj** [comment]
We just found an error on the agenda, the date should be August 15-19 2022.  Also one of the links wasn't working.  I've corrected it now.  Do you want me to do a new Github request or just attach?  I've attached here but if you want a new issue let me know.......

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: daniel-coleman-1 ***@***.***>
Sent: Thursday, July 14, 2022 9:57 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Reporter Training Update (Issue #2057)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@lpgoldstein<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flpgoldstein&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C95d33fd09de343b69ed508da65b19971%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637934110705527346%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=woGmYb6NtGjfp%2FiHix%2BIc1WHE5zS%2FjYs%2Bzi8r5HvE5w%3D&reserved=0> I think I figured it out by using the InlineLink feature to add a link & button:

[Screenshot 2022-07-14 095638]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F83892362%2F179025423-460f7da5-73ca-42d5-9963-1708a5acc5d1.png&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C95d33fd09de343b69ed508da65b19971%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637934110705527346%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vA7BUz4CCYTwVTS2Y7sAn6pL7duyJ5JQovm1KZdthA0%3D&reserved=0>

**Comment by bowlenj** [comment]
Yes, that would be great!  We just need to correct the date to August 15-19, 2022 and we have a corrected agenda as well.  I've attached the updated agenda so you can attach if you need to.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: lpgoldstein ***@***.***>
Sent: Thursday, July 14, 2022 9:00 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Reporter Training Update (Issue #2057)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C7c5a48aa33764bdcef4008da65a99608%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637934076288365316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TAAcsR7ot62W6nbkT6RsBG90DL%2FwBwTe1Qr84X%2BZeV0%3D&reserved=0> do you want to add this to the events page as well? https://onrr.gov/events.htm<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fonrr.gov%2Fevents.htm&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C7c5a48aa33764bdcef4008da65a99608%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637934076288365316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FUzute0Co3aIzaDwW1tshKmRVV3DHPYXVS6yNDlqqpg%3D&reserved=0>
