### ISSUE TITLE
Update Coal sections of the dev site

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#2061]
- [x] Add coal training to reporter training locations
- [x] Specifying that Coal Washing and Coal Transportation forms are Indian only
- [x] Add (Including Coal) to Solid Minerals headers

**Comment by cthomasONRR** [comment]
https://dev-onrr-frontend.app.cloud.gov/references/training

https://dev-onrr-frontend.app.cloud.gov/references/forms?tabs=solid-minerals-reporting

https://dev-onrr-frontend.app.cloud.gov/reporting/solids

@mcharg Want to review these locations for updated listed above?

**Comment by mcharg** [comment]
@cthomasONRR I think he also wanted the coal training in this accordion.
https://dev-onrr-frontend.app.cloud.gov/reporting/solids?tabs=troubleshooting&panel=i-have-a-question-about-solid-minerals-valuation

**Comment by mcharg** [comment]
Otherwise, looks good.

**Comment by cthomasONRR** [comment]
@mcharg 

Added here: https://dev-onrr-frontend.app.cloud.gov/reporting/solids?tabs=troubleshooting&panel=i-have-a-question-about-solid-minerals-valuation
