### ISSUE TITLE
Make New Reporter Training page use same content as Reporter Training page

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#2062]

**Comment by mcharg** [comment]
@lpgoldstein This is ready for you to review.
https://dev-onrr-frontend.app.cloud.gov/getting-started/new-reporter-training

**Comment by mcharg** [comment]
@cthomasONRR Do you want to review?

**Comment by cthomasONRR** [comment]
@mcharg Thanks!!!

**Comment by mcharg** [comment]
@cthomasONRR The whole tab blog was one component, so it was super easy.
