### ISSUE TITLE
PowerPoint icon is not appearing when new documents are added

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#2064]
New PowerPoint presentations being added to the site are not showing the "P" document icon.

Examples:
https://dev-onrr-frontend.app.cloud.gov/references/training?tabs=training-presentations
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/96a7daf8-39a1-42e5-a12e-189e06173298)

https://dev-onrr-frontend.app.cloud.gov/reporting/solids?tabs=troubleshooting&panel=i-have-a-question-about-solid-minerals-valuation
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/10f7d16c-2df2-4557-8630-aa92596ab8ce)

I tested this, and the PPT icons are not appearing for both bulleted lists and in-line text. New PDF documents are getting the "PDF" icon added without issue.

**Comment by Maroyafaied** [comment]
This is now fixed. In case it happens in the future, below are the folder it should be corrected in , in this case I had to add "application\" before the case for word and power point.
 editorjs/src/custom-plugins/plugin-links-inline.js
 cms/extensions/interfaces/editorjs/index.js
Mojo had to combile the custom plugins for the corrections to show in the cms, that is not something a non-developer can do as of now but we could build script so it gets built in circleci when needed.
