### ISSUE TITLE
Webpage Update (100% Fed Agmt)

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#2067]
Hello, please update the following webpage http://www.onrr.gov/ReportPay/royalty-reporting.htm with the attached file.

100% Federal Agreements with the Same Royalty Rate and Royalty Distributions, also change update to read 07/01/2022.

Thank you!

[100pct fed agreements.xlsx](https://github.com/ONRR/onrr.gov-site/files/9142342/100pct.fed.agreements.xlsx)

**Comment by daniel-coleman-1** [comment]
@merrellc changes have been input to dev:
http://2017onrr/ReportPay/royalty-reporting.htm

with your approval I will push these changes live.

**Comment by lpgoldstein** [comment]
@daniel-coleman-1 next step is to update the new site as well: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=revenue-reporting-reference
![image (11)](https://user-images.githubusercontent.com/39419003/179793176-dfc41d18-1727-4f35-8691-c370c1054706.png)
s

**Comment by merrellc** [comment]
Not seeing on new site.

When I click on the link I see this-



[cid:395150ff-9538-4ec1-ac07-13b8b45030b4]


Kind Regards,
​Candace Merrell
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.
________________________________
From: lpgoldstein ***@***.***>
Sent: Tuesday, July 19, 2022 9:47 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Webpage Update (100% Fed Agmt) (Issue #2067)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@daniel-coleman-1<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdaniel-coleman-1&data=05%7C01%7Ccandace.merrell%40onrr.gov%7Cfa13af0a6a854ae18ebd08da699df897%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637938424445426037%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9U5t0x%2BuG2qpVkdttFghWev0sPBqGNT%2B9PvefQqDh3A%3D&reserved=0> next step is to update the new site as well: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=revenue-reporting-reference<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Freferences%2Freference-lists%3Ftabs%3Drevenue-reporting-reference&data=05%7C01%7Ccandace.merrell%40onrr.gov%7Cfa13af0a6a854ae18ebd08da699df897%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637938424445426037%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ymRaC0P%2FCHnXNnLwn%2FG0veJIrD7TmLy5o5J726W4yLo%3D&reserved=0>
[image (11)]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F39419003%2F179793176-dfc41d18-1727-4f35-8691-c370c1054706.png&data=05%7C01%7Ccandace.merrell%40onrr.gov%7Cfa13af0a6a854ae18ebd08da699df897%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637938424445426037%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Hp0QhTm%2F3jegW3lzvjTP%2Fk4hdO2NIwxuwPoq92%2BBFoc%3D&reserved=0>
s

**Comment by daniel-coleman-1** [comment]
@merrellc are you seeing updates reflected on the below page?

http://2017onrr/ReportPay/royalty-reporting.htm

**Comment by merrellc** [comment]
Yes, I see updated on this site.


Kind Regards,
​Candace Merrell
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.
________________________________
From: daniel-coleman-1 ***@***.***>
Sent: Tuesday, July 19, 2022 10:10 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Webpage Update (100% Fed Agmt) (Issue #2067)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@merrellc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmerrellc&data=05%7C01%7Ccandace.merrell%40onrr.gov%7C7f48242a2bd54f093cbc08da69a145cf%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637938438627532343%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UQSYjVRdFGVtAqAxZ0BpQdpmfaoi637lrZv4lQOiz2U%3D&reserved=0> are you seeing updates reflected on the below page?

http://2017onrr/ReportPay/royalty-reporting.htm

**Comment by daniel-coleman-1** [comment]
@merrellc fantastic, we are live:
https://www.onrr.gov/ReportPay/royalty-reporting.htm
