### ISSUE TITLE
Add Org Chart as an image to webpage

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#2069]
From user interviews, a lot of people actually look at the org chart. We have it as a powerpoint slide, but I want to also include it on the webpage as an image. I can save the PPT slide as a jpeg and add it to the webpage with the existing alt text.

https://dev-onrr-frontend.app.cloud.gov/about/organization?tabs=organization-chart

**Comment by cthomasONRR** [comment]
@lpgoldstein I added the image and put it up front. I moved the PPT link and the updated date to down below the image. Let me know if you approve these changes.

**Comment by lpgoldstein** [comment]
@cthomasONRR approved!
