### ISSUE TITLE
Create DOL plain language presentation - September 1, 2022

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#2070]
DOL plain language community presentation on September 1, 2022. Issue is to start developing a PowerPoint about how we reduced the reading levels on onrr.gov.

**Comment by cthomasONRR** [comment]
Presentation started so I can collect screengrabs of the old site with post-grad reading levels, and compare them to the new site version. 

https://teams.microsoft.com/l/file/8E7D9173-4D9D-4009-945F-85966B971B14?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=pptx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FOutreach%2FProposals%20%26%20Presentations%2FFY23%2FDOI%20Plain%20Language%20Community_Nov%2022.pptx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by cthomasONRR** [comment]
@lpgoldstein This is ready for your review and input. There are two background slides that I need your help on getting the details. I also added notes to the screenshot slides explaining what I'm planning to discuss and why I chose those particular webpages. All images should have alt text.

**Comment by lpgoldstein** [comment]
@cthomasONRR I added some sections and a bunch of comments. Available to chat tomorrow too. Overall I think it looks great - thank you. And looks like a future blog post!

**Comment by cthomasONRR** [comment]
@lpgoldstein Awesome, thanks for your input! I addressed your comments.

@Maroyafaied This presentation is ready for your review.

**Comment by Maroyafaied** [comment]
@cthomasONRR @lpgoldstein This is a great start, my recommendation is not to make all the examples at the end focused on just reading levels. We did a lot of other things that relate to the plain language act to organize technical information to make easier for users to read/understand.  Some examples from the top of my head are the table design for reporter letters with option to filter by topic, the redesign of handbooks specifically to make it easer to find which handbook you need and search for chapter/topic, pricing tables, tabs to organize information, headings to organize information, the new way we displayed the RV technical examples. I would highlight some other things we did besides reading levels and maybe how we tested and reiterated to ensure "Design for reading". We can also mention testing with screen reader user to ensure they can navigate the menue and the headings/subheadings. 

https://www.plainlanguage.gov/guidelines/design/
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/83879e4e-0185-496f-b052-0968618e07bf).

**Comment by cthomasONRR** [comment]
@Maroyafaied @lpgoldstein I'll work on this tomorrow.

**Comment by cthomasONRR** [comment]
@lpgoldstein I removed all but one Hemmingway example (kept one at the very beginning of the examples). I added different slides and screengrabs to show different redesigns that help with plain language. Screenshots show examples of tables, headings, lists, cards, and shorter sentences.

Could you review and let me know what you think? Thanks!

**Comment by lpgoldstein** [comment]
@cthomasONRR Looks great - I added response comments as needed.

**Comment by cthomasONRR** [comment]
@Maroyafaied This is ready for a second round of your review.

**Comment by Maroyafaied** [comment]
@cthomasONRR looks great, I like the examples you used.

**Comment by cthomasONRR** [comment]
@Maroyafaied @lpgoldstein Great! I'll set up an issue for next spring to practice giving the presentation. I'll close this issue now.
