### ISSUE TITLE
onrr.gov June Analytics 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2073]
@daniel-coleman-1  please complete this task and have it ready for review no later than August 1, 2022. Please tag me in the issue when its ready for review.  After incorporating comments received from review, please  publish to the wiki no later than August 5, 2022

**Comment by daniel-coleman-1** [comment]
@Maroyafaied this one is good to go except for the site search, I sent an email to reestablish access:
![Screenshot 2022-07-28 141541](https://user-images.githubusercontent.com/83892362/181630030-6207fb33-f759-4ce4-b723-2bb4f309e2c8.png)

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I get an error when I try to open the June 2022 Dashboard report, can you please link correctly. Also, please forward me the email you sent to reestablish access. Thanks

![image](https://user-images.githubusercontent.com/40175688/181639634-8d52a883-c99c-4bab-a1a0-3b64866d54d5.png)

![image](https://user-images.githubusercontent.com/40175688/181639576-3f38abb3-cad9-4ebb-97f5-1683072f1330.png)

**Comment by daniel-coleman-1** [comment]
@Maroyafaied corrected and forwarded, will send response email when received.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 All of the data for browsers (desktop, mobile, and tablet) are inaccurate, please update with the correct percentages for June.  
![image](https://user-images.githubusercontent.com/40175688/181650329-68250c03-9756-4342-9a13-9da93c8b9cb1.png)

**Comment by daniel-coleman-1** [comment]
@Maroyafaied ok this is good to go, got access to search.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 looks good
