### ISSUE TITLE
review authorized users for search.gov

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/onrr.gov-site#2074]
Due September 30 

Hello,

As announced in our monthly newsletter, we are conducting a review of our search sites’ authorized users, to be completed by the end of September 2022. We ask you to please: 

1. review that the users’ names and email addresses listed on your search site(s) are correct; 

2. if your current list of authorized users is not accurate, make any necessary updates, and 
3. once you complete this review, let us know by answering this Touchpoints form before September 30, 2022. 

To find your users listed on your search site(s) log in to the Admin Center: 

Admin Center > YourSite > Dashboard > Manage Users. 

If you need a reminder, here are the steps to add/remove users.

If you have more than one search site, from the Admin Center use the “Select a Site” dropdown menu located at the top left of the screen. 

If you have any questions, please contact us at search@gsa.gov.

**Comment by cthomasONRR** [comment]
@lpgoldstein I got this email too.

**Comment by lpgoldstein** [comment]
@cthomasONRR was thinking we should wait until we have our new employee to take care of this?

**Comment by cthomasONRR** [comment]
@lpgoldstein I removed Shannon and Dan was already removed. Here's our user list right now: 
![image](https://user-images.githubusercontent.com/72526208/184698958-261609ec-7231-4e90-b959-2866ec6f9457.png)
I don't think any new employees will be on-board by September 30.

**Comment by lpgoldstein** [comment]
@cthomasONRR sounds good and thank you. Do you want to respond to them or me?

**Comment by cthomasONRR** [comment]
@lpgoldstein I just filled out their Touchpoints form. We are good to close this issue.
