### ISSUE TITLE
Add new outreach video to allottee assistance video tab

### ISSUE THREAD

**Issue by Rebekah474** [ONRR/onrr.gov-site#2075]
Outreach has created a new FAQ outreach video covering transportation and processing allowances. We would like the new video link loaded with the others on the videos tab on the allottee assistance page on onrr.gov. The video description is as follows: What are allowances? – This video discusses transportation and processing allowances and why you might see them on your oil and gas royalty statement.
The video tab link is below;
[][(url)](https://onrr.gov/IndianServices/index.htm)
The YouTube video link is below
[][(url)](https://www.youtube.com/watch?v=X03D5ida1Kg)

**Comment by Maroyafaied** [comment]
@Rebekah474 please review and let me know if it looks good to publish
http://2017onrr/IndianServices/index.htm
Also, just FYI that when we launch the new website we won't be embedding the videos in the webpage since the videos are not yet accessible, we will only be providing the link to the youtube video. This is the link to new redesigned dev site https://dev-onrr-frontend.app.cloud.gov/indian/assistance?tabs=indian-outreach,videos

**Comment by Rebekah474** [comment]
Hi,
Yes it looks perfect
Thank you

Rebekah Ingraham
Mineral Revenue Specialist
ONRR SIO
Oklahoma City
405-879-6037
800-354-7015
6:30-3:00 CT M-F
We all have different gifts, so we all have different ways of saying to the world who we are. - Fred Rogers
For Allottee Assistance go to:
https://www.onrr.gov/IndianServices/index.htm
Mail industry forms to: ***@***.******@***.***>
To see ONRR's training videos, go to:
http://onrr.gov/ReportPay/training/default.htm<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fonrr.gov%2FReportPay%2Ftraining%2Fdefault.htm&data=04%7C01%7CRebekah.Ingraham%40onrr.gov%7Ca29245c053404365512b08d8c2539fbc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637473011765313008%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E142FCBxPg5gABpSs1evwGMqNwb74eYi%2FydxnFHgZkE%3D&reserved=0>
https://www.youtube.com/user/ONRRChannel<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fuser%2FONRRChannel&data=04%7C01%7CRebekah.Ingraham%40onrr.gov%7Ca29245c053404365512b08d8c2539fbc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637473011765322970%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Tn5sNbkUPpw1HNAEfqFHNm%2BCELA47cvwFxcq%2BJYIWns%3D&reserved=0>

From: Maroyafaied ***@***.***>
Sent: Tuesday, July 26, 2022 2:21 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Ingraham, Rebekah J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Add new outreach video to allottee assistance video tab (Issue #2075)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Rebekah474<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRebekah474&data=05%7C01%7CRebekah.Ingraham%40onrr.gov%7Cb21ef302451e4eb5694208da6f3bebdc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637944600401775518%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Eoc46w5kjZnGaAk%2FGLXnyWJDJppaMJW8iM4345he9%2Fc%3D&reserved=0> please review and let me know if it looks good to publish
http://2017onrr/IndianServices/index.htm
Also, just FYI that when we launch the new website we won't be embedding the videos in the webpage since the videos are not yet accessible, we will only be providing the link to the youtube video. This is the link to new redesigned dev site https://dev-onrr-frontend.app.cloud.gov/indian/assistance?tabs=indian-outreach,videos<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Findian%2Fassistance%3Ftabs%3Dindian-outreach%2Cvideos&data=05%7C01%7CRebekah.Ingraham%40onrr.gov%7Cb21ef302451e4eb5694208da6f3bebdc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637944600401775518%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=J4LfCIX%2B4pQ%2B%2BAzzk5bVqYbq8RZbKVNGn2J8gQOf230%3D&reserved=0>

-

**Comment by Maroyafaied** [comment]
@Rebekah474 This is live. Thanks

**Comment by Rebekah474** [comment]
Hi,
I have one question about the new website, will the embedded videos ever be available in the new website?
I shared the preview with my supervisor and we both like it with the thumbnails better.
Thank you

Rebekah Ingraham
Mineral Revenue Specialist
ONRR SIO
Oklahoma City
405-879-6037
800-354-7015
6:30-3:00 CT M-F
We all have different gifts, so we all have different ways of saying to the world who we are. - Fred Rogers
For Allottee Assistance go to:
https://www.onrr.gov/IndianServices/index.htm
Mail industry forms to: ***@***.******@***.***>
To see ONRR's training videos, go to:
http://onrr.gov/ReportPay/training/default.htm<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fonrr.gov%2FReportPay%2Ftraining%2Fdefault.htm&data=04%7C01%7CRebekah.Ingraham%40onrr.gov%7Ca29245c053404365512b08d8c2539fbc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637473011765313008%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E142FCBxPg5gABpSs1evwGMqNwb74eYi%2FydxnFHgZkE%3D&reserved=0>
https://www.youtube.com/user/ONRRChannel<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fuser%2FONRRChannel&data=04%7C01%7CRebekah.Ingraham%40onrr.gov%7Ca29245c053404365512b08d8c2539fbc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637473011765322970%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Tn5sNbkUPpw1HNAEfqFHNm%2BCELA47cvwFxcq%2BJYIWns%3D&reserved=0>

From: Maroyafaied ***@***.***>
Sent: Tuesday, July 26, 2022 2:21 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Ingraham, Rebekah J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Add new outreach video to allottee assistance video tab (Issue #2075)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Rebekah474<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRebekah474&data=05%7C01%7CRebekah.Ingraham%40onrr.gov%7Cb21ef302451e4eb5694208da6f3bebdc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637944600401775518%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Eoc46w5kjZnGaAk%2FGLXnyWJDJppaMJW8iM4345he9%2Fc%3D&reserved=0> please review and let me know if it looks good to publish
http://2017onrr/IndianServices/index.htm
Also, just FYI that when we launch the new website we won't be embedding the videos in the webpage since the videos are not yet accessible, we will only be providing the link to the youtube video. This is the link to new redesigned dev site https://dev-onrr-frontend.app.cloud.gov/indian/assistance?tabs=indian-outreach,videos<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Findian%2Fassistance%3Ftabs%3Dindian-outreach%2Cvideos&data=05%7C01%7CRebekah.Ingraham%40onrr.gov%7Cb21ef302451e4eb5694208da6f3bebdc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637944600401775518%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=J4LfCIX%2B4pQ%2B%2BAzzk5bVqYbq8RZbKVNGn2J8gQOf230%3D&reserved=0>

-

**Comment by Maroyafaied** [comment]
@Rebekah474 After discussions with the video team, we decided not to embed videos until we have the resources to verify the videos meet section 508 compliance. The video team is working on adding audio descriptions for each video so we will be adding the links to the audio description versions as an option for users with disability.

**Comment by Rebekah474** [comment]
Thank you for keeping me posted. I've seen the updates so hopefully they'll be ready soon.

Rebekah Ingraham
Mineral Revenue Specialist
ONRR SIO
Oklahoma City
405-879-6037
800-982-3226
6:30-3:00 CT M-F
For Allottee Assistance go to:
https://www.onrr.gov/IndianServices/index.htm
Mail industry forms to: ***@***.******@***.***>
To see ONRR's training videos, go to:
http://onrr.gov/ReportPay/training/default.htm<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fonrr.gov%2FReportPay%2Ftraining%2Fdefault.htm&data=04%7C01%7CRebekah.Ingraham%40onrr.gov%7Ca29245c053404365512b08d8c2539fbc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637473011765313008%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E142FCBxPg5gABpSs1evwGMqNwb74eYi%2FydxnFHgZkE%3D&reserved=0>
https://www.youtube.com/user/ONRRChannel<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fuser%2FONRRChannel&data=04%7C01%7CRebekah.Ingraham%40onrr.gov%7Ca29245c053404365512b08d8c2539fbc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637473011765322970%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Tn5sNbkUPpw1HNAEfqFHNm%2BCELA47cvwFxcq%2BJYIWns%3D&reserved=0>

From: Maroyafaied ***@***.***>
Sent: Tuesday, October 11, 2022 7:40 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Ingraham, Rebekah J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Add new outreach video to allottee assistance video tab (Issue #2075)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Rebekah474<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRebekah474&data=05%7C01%7CRebekah.Ingraham%40onrr.gov%7C2568c5c1ae9a4f3d83a208daab85c83b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638010888351209077%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BLASorlrSWZ2QZ7kQbnUxx8pSoMdMXTkTIHhx2xkCkQ%3D&reserved=0> After discussions with the video team, we decided not to embed videos until we have the resources to verify the videos meet section 508 compliance. The video team is working on adding audio descriptions for each video so we will be adding the links to the audio description versions as an option for users with disability.

-
