### ISSUE TITLE
CONCHO AREA VIRTUAL MEETING                                                  (To be added to Event calendar)

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#2077]
**CONCHO AREA VIRTUAL MEETING**
August 25, 2022
1:00 pm to 2:00 pm CST
Location:  By Telephone

DESCRIPTION: Meeting will be a Call-in Meeting to hear a brief presentation and updates from the ONRR Outreach Office.  Representatives from each of the BLM, BTFA, and BIA will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust property issues, and agency updates.  Owners will have an opportunity to ask questions for the representatives of the four agencies during the Q&A session.

WHO SHOULD ATTEND: IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Concho Agency Area, Southern Plains Region in Oklahoma. 

OTHER INFORMATION: To reserve a space and get the call-in number and passcode for this meeting you may contact the ONRR OKC Outreach office at (800) 354-7015. Office hours are Mon- Fri., 7:30 AM-5:00 PM CST. 

CONTACT: ONRR OKC Outreach Office, PHONE: (800) 354-7015 (toll-free)
EMAIL: onrroutreachokc@onrr.gov

**NORTH DAKOTA, MONTANA VIRTUAL OUTREACH MEETING**
August 25, 2022
10:00 am to 10:30 am MST
Location: By Telephone

DESCRIPTION: Representatives from the Office of Natural Resources Revenue will host a Question and Answer session by phone for Indian Mineral Owners and Trust Property Owners regarding their Indian Oil & Gas leases, IIM Accounts, and Indian Trust Properties. Representatives from the Bureau of Land Management, Bureau of Indian Affairs, and Bureau of Trust Funds Administration are invited to be in attendance to answer questions.  

WHO SHOULD ATTEND:  IIM account holders, Indian mineral owners, and Indian trust property owners in the Trenton, Parshall, Forth Berthold, Minot, Fort Totten, Turtle Mountain, Madaree, Twin Buttes, White Shield (North Dakota) and Poplar (Montana) area.
OTHER INFORMATION: To attend the outreach session, please contact the ONRR Denver Outreach Office at (800) 982-3226, for the call-in number and passcode.   Office hours are Mon-Fri 7:30 AM-4:00 PM MST. 

CONTACT:  ONRR Denver Outreach Office, Phone: (800) 982-3226 (toll-free)
Email: onrroutreachdenver@onrr.gov

**Comment by cthomasONRR** [comment]
@Toddsand21 

Good morning!

These updates are on the dev site: http://2017onrr/events.htm.
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by Toddsand21** [comment]
In the Concho Area Meeting under the Other Information could you put the (800) 354 together on the next line with the rest of the phone number (800) 354-7015 
And on the North Dakota Area meeting on Other Information could you add to "T" before the "o" to read ....To attend the outreach session.....
The rest looks fine and ready.

**Comment by cthomasONRR** [comment]
@Toddsand21 

Great, these modifications are made: http://2017onrr/events.htm.
Could you do one final review before I go live?

Thanks,
Christine

**Comment by Toddsand21** [comment]
Yes it looks fine!

**Comment by cthomasONRR** [comment]
@Toddsand21 

Great, these changes are now live: https://www.onrr.gov/events.htm
Please remember to use "Ctrl+F5" to refresh the page.

Thanks,
Christine

**Comment by Toddsand21** [comment]
Thanks and it looks fine!
