### ISSUE TITLE
Online Files

### ISSUE THREAD

**Issue by jillbong79** [ONRR/onrr.gov-site#208]
@jennmalcolm 

Glen is sending you an email to explain these online files and requested I start another issue for these.  Please let me know if you have any questions!  Thank you!!

**Online Files:**
[RRM-Form ONRR-2014 Codes onrr website.pdf](https://github.com/ONRR/onrr.gov-site/files/4833116/RRM-Form.ONRR-2014.Codes.onrr.website.pdf)
[RRM-Step- sliding-scale royalty rates.pdf](https://github.com/ONRR/onrr.gov-site/files/4833117/RRM-Step-.sliding-scale.royalty.rates.pdf)

**Comment by jennmalcolm** [comment]
the updates are live
