### ISSUE TITLE
Figure out how to submit sitemap to google 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2080]

**Comment by cthomasONRR** [comment]
@Maroyafaied 

I found the following site that gives these directions:
https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap
![image](https://user-images.githubusercontent.com/72526208/182210228-86eb7eac-c7e5-4ea6-8779-e6573218bc32.png)

I can send an email to search.gov folks if this plus the instructions I have for Bing submission are good and accurate.

**Comment by cthomasONRR** [comment]
I emailed our search.gov contacts to see if they agree with the method I listed in the comment above, and if they have any other suggestions.

**Comment by cthomasONRR** [comment]
Got an out of office from Arantxa Piperova, but will wait to see if anyone cc'ed responds. If no response by Wednesday, I'll fwd the email to search@gsa.gov.

**Comment by cthomasONRR** [comment]
Search.gov verified that this method of submitting a sitmap to Google is ok. Closing this issue and will put addition info in #2007
