### ISSUE TITLE
Updates to ONRR.gov's Production Reporting Page

### ISSUE THREAD

**Issue by gingerhensley** [ONRR/onrr.gov-site#2084]
Good afternoon, 

I am requesting updates to this page 
https://onrr.gov/ReportPay/production-reporting.htm
 
Under OGOR — Oil and Gas Operations Report
(Offshore and Onshore)
Form ONRR-4054
Please update Part A, Part B, and Part C with the attached documents below which have a new expiration date. 
[4054 - Part A 8.2.2022 accesible.pdf](https://github.com/ONRR/onrr.gov-site/files/9245250/4054.-.Part.A.8.2.2022.accesible.pdf)
[4054 - Part B 8.2.2022 accessible.pdf](https://github.com/ONRR/onrr.gov-site/files/9245251/4054.-.Part.B.8.2.2022.accessible.pdf)
[4054 - Part C 8.2.2022 accesible.pdf](https://github.com/ONRR/onrr.gov-site/files/9245252/4054.-.Part.C.8.2.2022.accesible.pdf)

Please let me know if you have any questions. Thank you. 
Ginger Hensley

**Comment by lpgoldstein** [comment]
@gingerhensley Documents are looking great except that you need to add a title to each document. Here are directions to help or I can walk you through it https://www.w3.org/TR/WCAG20-TECHS/PDF18.html

**Comment by lpgoldstein** [comment]
@gingerhensley It was an error on my end - I will post to dev now and send you a link to check. Sorry about that!

**Comment by lpgoldstein** [comment]
@gingerhensley ready for your review: http://2017onrr/reportpay/production-reporting.htm

**Comment by gingerhensley** [comment]
Approved. 

Thank you!

**Comment by lpgoldstein** [comment]
@gingerhensley This is live!
