### ISSUE TITLE
Updates to ONRR.gov's Production Reporting Page

### ISSUE THREAD

**Issue by gingerhensley** [ONRR/onrr.gov-site#2085]
Good afternoon, 

I am requesting updates to this page https://onrr.gov/ReportPay/production-reporting.htm

Under PASR — Production Allocation Schedule Report
(Offshore only)
Form ONRR-4058
Please update the Form ONRR-4058 with the attached document which has a new expiration date. 

Please let me know if you have any questions. Thank you. 
Ginger Hensley
[4058 8.2.2022 accesible.pdf](https://github.com/ONRR/onrr.gov-site/files/9245291/4058.8.2.2022.accesible.pdf)

**Comment by cthomasONRR** [comment]
@gingerhensley 

Good afternoon,

This update is in the dev site: http://2017onrr/reportpay/production-reporting.htm
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by gingerhensley** [comment]
Approved. 

Thank you!

**Comment by cthomasONRR** [comment]
@gingerhensley 

Great, these changes are now live: https://onrr.gov/ReportPay/production-reporting.htm
Please remember to use "Ctrl+F5" to refresh the page.

Thanks,
Christine
