### ISSUE TITLE
Solids Minerals Handbook Project

### ISSUE THREAD

**Issue by jillbong79** [ONRR/onrr.gov-site#209]
@jennmalcolm 

I will load files for this section of the handbook project at some point today.  I don't have access to the drive they are currently housed.  Thanks!

**Comment by jillbong79** [comment]
@jennmalcolm 
**Solids Operator Handbook Final PDFs:**
[Solid Minerals Chapter 6 - Value Adjustment.pdf](https://github.com/ONRR/onrr.gov-site/files/4838455/Solid.Minerals.Chapter.6.-.Value.Adjustment.pdf)
[Solid Minerals Chapter 7 - Other Obligations.pdf](https://github.com/ONRR/onrr.gov-site/files/4838456/Solid.Minerals.Chapter.7.-.Other.Obligations.pdf)
[Solid Minerals Chapter 8 - Volume-Value Adjustment Report.pdf](https://github.com/ONRR/onrr.gov-site/files/4838457/Solid.Minerals.Chapter.8.-.Volume-Value.Adjustment.Report.pdf)
[Solid Minerals Chapter 9 - Volume-Value Allocation Tools.pdf](https://github.com/ONRR/onrr.gov-site/files/4838458/Solid.Minerals.Chapter.9.-.Volume-Value.Allocation.Tools.pdf)
[Solid Minerals Reporter Handbook Release 2.0.pdf](https://github.com/ONRR/onrr.gov-site/files/4838461/Solid.Minerals.Reporter.Handbook.Release.2.0.pdf)
[Table of Contents.pdf](https://github.com/ONRR/onrr.gov-site/files/4838468/Table.of.Contents.pdf)
[Title Page.pdf](https://github.com/ONRR/onrr.gov-site/files/4838469/Title.Page.pdf)
[Abbreviations.pdf](https://github.com/ONRR/onrr.gov-site/files/4838470/Abbreviations.pdf)
[Appendix A - Contact Information.pdf](https://github.com/ONRR/onrr.gov-site/files/4838471/Appendix.A.-.Contact.Information.pdf)
[Appendix B - Payment Method Codes.pdf](https://github.com/ONRR/onrr.gov-site/files/4838472/Appendix.B.-.Payment.Method.Codes.pdf)
[Appendix C - Lease Prefix Conversion Tables.pdf](https://github.com/ONRR/onrr.gov-site/files/4838473/Appendix.C.-.Lease.Prefix.Conversion.Tables.pdf)
[Appendix D - Product Codes.pdf](https://github.com/ONRR/onrr.gov-site/files/4838474/Appendix.D.-.Product.Codes.pdf)
[Appendix E - Transaction Codes.pdf](https://github.com/ONRR/onrr.gov-site/files/4838475/Appendix.E.-.Transaction.Codes.pdf)
[Appendix F - Adjustment Reason Codes.pdf](https://github.com/ONRR/onrr.gov-site/files/4838476/Appendix.F.-.Adjustment.Reason.Codes.pdf)
[Glossary.pdf](https://github.com/ONRR/onrr.gov-site/files/4838478/Glossary.pdf)
[Solid Minerals Chapter 1 - About This Handbook.pdf](https://github.com/ONRR/onrr.gov-site/files/4838479/Solid.Minerals.Chapter.1.-.About.This.Handbook.pdf)
[Solid Minerals Chapter 2 - Reporting Overview.pdf](https://github.com/ONRR/onrr.gov-site/files/4838481/Solid.Minerals.Chapter.2.-.Reporting.Overview.pdf)
[Solid Minerals Chapter 3 - Paper Form ONRR-4430 Field Descriptions and Explanations.pdf](https://github.com/ONRR/onrr.gov-site/files/4838483/Solid.Minerals.Chapter.3.-.Paper.Form.ONRR-4430.Field.Descriptions.and.Explanations.pdf)
[Solid Minerals Chapter 4 - Production and Royalty Report P&R.pdf](https://github.com/ONRR/onrr.gov-site/files/4838487/Solid.Minerals.Chapter.4.-.Production.and.Royalty.Report.P.R.pdf)
[Solid Minerals Chapter 5 - Original P&R.pdf](https://github.com/ONRR/onrr.gov-site/files/4838489/Solid.Minerals.Chapter.5.-.Original.P.R.pdf)

These files are verified ready to go.  Let me know if you have any questions.  Thank you!

**Comment by jennmalcolm** [comment]
@lpgoldstein can you work on replacing these files for the solid minerals handbook? We aren’t changing the structure for this one, just updating the files.

**Comment by lpgoldstein** [comment]
@jillbong79 I notice that there is no updated Chapter 10 or Appendix G included in your attached files. Should we remove the current files from the website?

**Comment by lpgoldstein** [comment]
@jillbong79 This is ready for your review: http://2017onrr/ReportPay/Handbooks/index.htm#solids-handbook

**Comment by jillbong79** [comment]
@lpgoldstein looks great; thanks!  I sent it to Glen to review.  Appreciate it!

**Comment by jennmalcolm** [comment]
I noticed that the links in the table of contents don't work. It looks like their relative document links, which means that it would require the user to have downloaded those items and saved them in the same folder for them to work. We also changed the document names so that we could just save over the old versions. I could show someone how to change those table of contents document links to be web links instead so that they will work for everyone (with internet). That will have to wait until next week though.

**Comment by jillbong79** [comment]
Sure!  That would be great.  Wanna set up a calendar invite for Wednesday?  We can do teams chat.


Sincerely,


Jill Bongiovanni

Office of Natural Resources Revenue

Minerals Revenue Specialist

Production, Reporting & Verification (PRV), Onshore Team 1A

Direct Line: 303-231-3523


Please note **ONRR is bound by lease terms and therefore, pursuant to 30 CFR:  For production reporting of oil, gas and geothermal resources on Federal lands, Indian lands, and in the Outer Continental Shelf, per 30 CFR §1210.103, production forms (Form ONRR-4054, Oil and Gas Operations Report, and Form ONRR-4058, Production Allocation Schedule Report) must be received by ONRR by the 15th day of the second month following the month for which you are reporting.**


SELF-HELP LINKS

·         Help with REPORTING here<https://www.onrr.gov/ReportPay/royalty-reporting.htm>!
·       Data Warehouse (E-Commerce, Invoices, eSoa, etc.)<https://sso.onrr.gov/oaam_server/login.do>
·         Reporter handbooks<https://www.onrr.gov/reportpay/Handbooks/index.htm>
·         Guidance on adjustments, recoupments & refunds<https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Chapter-6.pdf>
·         Lease (STATUS & MAINTENANCE) click here<https://www.onrr.gov/ReportPay/PDFDocs/RS_LeAgAssignments.pdf>!
·         Access to the system/update your info here<https://www.onrr.gov/reportpay/forms/index.htm>! (EMARF/4444/SURETY/W-9)
·         Help with PAYMENTS here<https://www.onrr.gov/reportpay/payments.htm>!
·         Help with a ‘Demand to Pay’ or ‘Potential Treasury Referral’ here<https://www.onrr.gov/ReportPay/PDFDocs/DebtCollectionAssign.pdf>!
·         Federal Accounts Receivable Contacts<https://www.onrr.gov/ReportPay/PDFDocs/finserAssign.pdf>
·         Indian Accounts Receivable Contacts<https://www.onrr.gov/ReportPay/PDFDocs/FSIndianCoAssign.pdf>
·         Password resets/System issues-contact the help desk at 303-231-3333 or enterpriseitservicedesk@bsee.gov<mailto:enterpriseitservicedesk@bsee.gov>
For help with 2014's: Royalty Reporting Contacts<http://www.onrr.gov/ReportPay/PDFDocs/royassign.pdf>
For help with OGOR's: Production Reporting Contacts<http://www.onrr.gov/ReportPay/PDFDocs/operasgn.pdf>
For help with Lease/Agreement Reporting: Lease Agreement Reporting Contacts<http://www.onrr.gov/ReportPay/PDFDocs/RS_LeAgAssignments.pdf>

________________________________

**Comment by jennmalcolm** [comment]
The files should all be live now. I'll set up a meeting about the table of contents. Invite whomever you want.

**Comment by jillbong79** [comment]
thank you!!


Sincerely,


Jill Bongiovanni

Office of Natural Resources Revenue

Minerals Revenue Specialist

Production, Reporting & Verification (PRV), Onshore Team 1A

Direct Line: 303-231-3523


Please note **ONRR is bound by lease terms and therefore, pursuant to 30 CFR:  For production reporting of oil, gas and geothermal resources on Federal lands, Indian lands, and in the Outer Continental Shelf, per 30 CFR §1210.103, production forms (Form ONRR-4054, Oil and Gas Operations Report, and Form ONRR-4058, Production Allocation Schedule Report) must be received by ONRR by the 15th day of the second month following the month for which you are reporting.**


SELF-HELP LINKS

·         Help with REPORTING here<https://www.onrr.gov/ReportPay/royalty-reporting.htm>!
·       Data Warehouse (E-Commerce, Invoices, eSoa, etc.)<https://sso.onrr.gov/oaam_server/login.do>
·         Reporter handbooks<https://www.onrr.gov/reportpay/Handbooks/index.htm>
·         Guidance on adjustments, recoupments & refunds<https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Chapter-6.pdf>
·         Lease (STATUS & MAINTENANCE) click here<https://www.onrr.gov/ReportPay/PDFDocs/RS_LeAgAssignments.pdf>!
·         Access to the system/update your info here<https://www.onrr.gov/reportpay/forms/index.htm>! (EMARF/4444/SURETY/W-9)
·         Help with PAYMENTS here<https://www.onrr.gov/reportpay/payments.htm>!
·         Help with a ‘Demand to Pay’ or ‘Potential Treasury Referral’ here<https://www.onrr.gov/ReportPay/PDFDocs/DebtCollectionAssign.pdf>!
·         Federal Accounts Receivable Contacts<https://www.onrr.gov/ReportPay/PDFDocs/finserAssign.pdf>
·         Indian Accounts Receivable Contacts<https://www.onrr.gov/ReportPay/PDFDocs/FSIndianCoAssign.pdf>
·         Password resets/System issues-contact the help desk at 303-231-3333 or enterpriseitservicedesk@bsee.gov<mailto:enterpriseitservicedesk@bsee.gov>
For help with 2014's: Royalty Reporting Contacts<http://www.onrr.gov/ReportPay/PDFDocs/royassign.pdf>
For help with OGOR's: Production Reporting Contacts<http://www.onrr.gov/ReportPay/PDFDocs/operasgn.pdf>
For help with Lease/Agreement Reporting: Lease Agreement Reporting Contacts<http://www.onrr.gov/ReportPay/PDFDocs/RS_LeAgAssignments.pdf>

________________________________

**Comment by jennmalcolm** [comment]
Closing this since all files are live. Once table of contents links are fixed, we can open a new issue to update that.
