### ISSUE TITLE
August Indian Index Zone prices

### ISSUE THREAD

**Issue by penvosej** [ONRR/onrr.gov-site#2094]
Hello, the August Indian Index Zone prices are ready for posting to ONRR.gov. The data can be found in the usual file "Data for ONRR.gov.xlsx". Can you please make sure that the prices ending in zero display the price to the thousandths place? Thanks!!
@sudarr

**Comment by Maroyafaied** [comment]
@lpgoldstein please update the current website and the cms. Thanks

**Comment by lpgoldstein** [comment]
@penvosej this is ready for your review: http://2017onrr/valuation/allzones.htm

**Comment by penvosej** [comment]
Hi Lindsay,

The prices look good! Thanks for updating the website so quickly!!

- Jessica

From: lpgoldstein ***@***.***>
Sent: Thursday, August 4, 2022 12:02 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] August Indian Index Zone prices (Issue #2094)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpenvosej&data=05%7C01%7CJessica.Penvose%40onrr.gov%7C98c3aa95b5654a407a0b08da76436e2f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637952329235338435%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cIw4aro72ZkhgpAYNi8bvpaMG3jd%2BUiCxvND12BMnhY%3D&reserved=0> this is ready for your review: http://2017onrr/valuation/allzones.htm

-

**Comment by lpgoldstein** [comment]
@penvosej It's live! https://onrr.gov/valuation/allzones.htm
