### ISSUE TITLE
Update ONRR webpage

### ISSUE THREAD

**Issue by vcs5274** [ONRR/onrr.gov-site#2095]
ONRR has a new lockbox account for MHA and we need to add it to ONRR's payment page.

Navajo Nation also needs to be updated. Please see attached word document for the changes.

[Webpage.docx](https://github.com/ONRR/onrr.gov-site/files/9269416/Webpage.docx)

**Comment by lpgoldstein** [comment]
@vcs5274 This is ready for your review: http://2017onrr/reportpay/payments.htm

**Comment by vcs5274** [comment]
Thank you. The page looks great.
