### ISSUE TITLE
Updated Instructions

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2098]
Please replace the instructions for Form ONRR-4444 and W-9 with the attached instructions on this webpage - https://www.onrr.gov/reportpay/Forms/index.htm

[Form ONRR-4444 Instructions.pdf](https://github.com/ONRR/onrr.gov-site/files/9283903/Form.ONRR-4444.Instructions.pdf)
[Instructions for Payors and Operators - Form W-9.pdf](https://github.com/ONRR/onrr.gov-site/files/9283904/Instructions.for.Payors.and.Operators.-.Form.W-9.pdf)

**Comment by lpgoldstein** [comment]
@bowlenj ready for your review: http://2017onrr/reportpay/Forms/index.htm

**Comment by bowlenj** [comment]
Hi Lindsey,

Both of the instructions are showing the title with AL review.....do you want me to re-do that and resent it to you?

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: lpgoldstein ***@***.***>
Sent: Monday, August 8, 2022 12:49 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Updated Instructions (Issue #2098)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Ce7d75e8baa8d4823f1fe08da796ebbad%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637955813747906618%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0AbA6x%2FT6W4DqJtBsoY8A8q2QcSmaDNhTixdcYPFEhI%3D&reserved=0> ready for your review: http://2017onrr/reportpay/Forms/index.htm

**Comment by bowlenj** [comment]
Looks Great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: lpgoldstein ***@***.***>
Sent: Monday, August 8, 2022 12:49 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Updated Instructions (Issue #2098)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Ce7d75e8baa8d4823f1fe08da796ebbad%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637955813747906618%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0AbA6x%2FT6W4DqJtBsoY8A8q2QcSmaDNhTixdcYPFEhI%3D&reserved=0> ready for your review: http://2017onrr/reportpay/Forms/index.htm

**Comment by lpgoldstein** [comment]
@bowlenj live so closing the issue!
