### ISSUE TITLE
Fix links on the wiki analytics

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2099]
@Baymatt https://github.com/ONRR/onrr.gov-site/wiki/Analytics
Some of the older hyperlinks in Landing Pages, Most Viewed Pages, and Outbound Links are not the proper hyperlinks. They have this github link (Ex: https://github.com/ONRR/onrr.gov-site/wiki/onrrreporting.onrr.gov) instead of the accurate link

**Comment by Baymatt** [comment]
@cthomasONRR I'm working on confirming which links need to be fixed and I noticed this inconsistency where we include Not Set for certain months and exclude it from others (ex. April 2019). Should I leave this alone? 
<img width="453" alt="Screen Shot 2022-08-09 at 12 09 00 PM" src="https://user-images.githubusercontent.com/43329595/183743504-b6b002c0-0e1c-477d-99fd-c94c84b3b504.png">
<img width="572" alt="Screen Shot 2022-08-09 at 12 09 16 PM" src="https://user-images.githubusercontent.com/43329595/183743510-1aa50d2e-d009-47af-8d7e-b6c1941226af.png">
<img width="565" alt="Screen Shot 2022-08-09 at 12 15 09 PM" src="https://user-images.githubusercontent.com/43329595/183743515-e22a4be9-4c65-4192-8281-cea98975d741.png">

**Comment by cthomasONRR** [comment]
@Baymatt You can keep the old records as-is. Thanks for being so detailed!

**Comment by Baymatt** [comment]
@cthomasONRR Fixed links for the Landing Pages, Most Viewed Pages and Outbound Links sections (mainly by adding https:// in front of the links). Below are the links I associated with each page, I had trouble connecting to the Data Warehouse Portal, so if you could double check that the links work, that'd be great. 

There was also a Data Warehouse and Data Warehouse Portal in FY21 totals in the Outbound Links section. Can you help to clarify if the links for those two are correct? Thank you!

[Homepage](https://www.onrr.gov/)
[News Releases](https://www.onrr.gov/about/newsreleases.htm)
[NYMEX](https://www.onrr.gov/valuation/nymex.htm)
[Royalty Reporting](https://www.onrr.gov/reportpay/royalty-reporting.htm)
[Indian Index Zones Natural Gas Prices](https://www.onrr.gov/valuation/allzones.htm)
[Training](https://www.onrr.gov/reportpay/training/index.htm)

[eCommerce](https://onrrreporting.onrr.gov)
[WebCenter Portal](https://portal.onrr.gov)
[NRRD Portal](https://revenuedata.doi.gov)
[Data Warehouse](https://dwportal.onrr.gov)
[Eventbrite](https://www.eventbrite.com)

**Comment by cthomasONRR** [comment]
@Baymatt I checked:

- [ ] Landing pages
- [ ] Most viewed pages
- [ ] Outbound links

For Data Warehouse and Data Warehouse Portal, I believe they are both https://portal.onrr.gov. I can't get the link you used for Data Warehouse Portal (https://dwportal.onrr.gov) to work either. I'd go back and replace those with https://portal.onrr.gov. Other than that, everything looks good!

**Comment by Baymatt** [comment]
@cthomasONRR Replaced all the links for the Data Warehouse with https://portal.onrr.gov. Everything should be good to go

**Comment by cthomasONRR** [comment]
@Baymatt This looks great! Thank you for fixing these links! This issue is good to close.

**Comment by cthomasONRR** [comment]
@Baymatt This same issues is happening on the NRRD wiki as well. I'll set up another issue for the NRRD wiki for you.
