### ISSUE TITLE
Production Handbook Replacement Files

### ISSUE THREAD

**Issue by jillbong79** [ONRR/onrr.gov-site#210]
@jennmalcolm 

Here are the replacement files Glen sent me today.  I am off till Wednesday, but I will be checking this once a day while off.  Thanks!

[Appendix L - Product Codes wc.docx](https://github.com/ONRR/onrr.gov-site/files/4839187/Appendix.L.-.Product.Codes.wc.docx)
[MPRH-Abbreviations.docx](https://github.com/ONRR/onrr.gov-site/files/4839188/MPRH-Abbreviations.docx)
[Appendix B - Lse Agmt (Final Replacement).docx](https://github.com/ONRR/onrr.gov-site/files/4839189/Appendix.B.-.Lse.Agmt.Final.Replacement.docx)
[Appendix F - API No wc.docx](https://github.com/ONRR/onrr.gov-site/files/4839191/Appendix.F.-.API.No.wc.docx)
[Appendix J - FMP wc.docx](https://github.com/ONRR/onrr.gov-site/files/4839192/Appendix.J.-.FMP.wc.docx)
[Appendix K - Commingling Codes wc.docx](https://github.com/ONRR/onrr.gov-site/files/4839193/Appendix.K.-.Commingling.Codes.wc.docx)

**Comment by jennmalcolm** [comment]
@jillbong79 do you want me to make these into PDFs rather than Word docs?

**Comment by jennmalcolm** [comment]
I'm going to go ahead and convert them since I think they need to be live today. You can let me know later if something needs to be changed.

**Comment by jillbong79** [comment]
thank you!  Lydia is finishing up some docs, so I will send those tonight also.


Sincerely,


Jill Bongiovanni

Office of Natural Resources Revenue

Minerals Revenue Specialist

Production, Reporting & Verification (PRV), Onshore Team 1A

Direct Line: 303-231-3523


Please note **ONRR is bound by lease terms and therefore, pursuant to 30 CFR:  For production reporting of oil, gas and geothermal resources on Federal lands, Indian lands, and in the Outer Continental Shelf, per 30 CFR §1210.103, production forms (Form ONRR-4054, Oil and Gas Operations Report, and Form ONRR-4058, Production Allocation Schedule Report) must be received by ONRR by the 15th day of the second month following the month for which you are reporting.**


SELF-HELP LINKS

·         Help with REPORTING here<https://www.onrr.gov/ReportPay/royalty-reporting.htm>!
·       Data Warehouse (E-Commerce, Invoices, eSoa, etc.)<https://sso.onrr.gov/oaam_server/login.do>
·         Reporter handbooks<https://www.onrr.gov/reportpay/Handbooks/index.htm>
·         Guidance on adjustments, recoupments & refunds<https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Chapter-6.pdf>
·         Lease (STATUS & MAINTENANCE) click here<https://www.onrr.gov/ReportPay/PDFDocs/RS_LeAgAssignments.pdf>!
·         Access to the system/update your info here<https://www.onrr.gov/reportpay/forms/index.htm>! (EMARF/4444/SURETY/W-9)
·         Help with PAYMENTS here<https://www.onrr.gov/reportpay/payments.htm>!
·         Help with a ‘Demand to Pay’ or ‘Potential Treasury Referral’ here<https://www.onrr.gov/ReportPay/PDFDocs/DebtCollectionAssign.pdf>!
·         Federal Accounts Receivable Contacts<https://www.onrr.gov/ReportPay/PDFDocs/finserAssign.pdf>
·         Indian Accounts Receivable Contacts<https://www.onrr.gov/ReportPay/PDFDocs/FSIndianCoAssign.pdf>
·         Password resets/System issues-contact the help desk at 303-231-3333 or enterpriseitservicedesk@bsee.gov<mailto:enterpriseitservicedesk@bsee.gov>
For help with 2014's: Royalty Reporting Contacts<http://www.onrr.gov/ReportPay/PDFDocs/royassign.pdf>
For help with OGOR's: Production Reporting Contacts<http://www.onrr.gov/ReportPay/PDFDocs/operasgn.pdf>
For help with Lease/Agreement Reporting: Lease Agreement Reporting Contacts<http://www.onrr.gov/ReportPay/PDFDocs/RS_LeAgAssignments.pdf>

________________________________

**Comment by jennmalcolm** [comment]
Ok, I will make what I have live now and try to check in tomorrow to see if there are more documents to add. Since I do not have all of the production handbook documents, should I change the release version and date on that one? 
![image](https://user-images.githubusercontent.com/30806839/85910169-710b8780-b7eb-11ea-8b96-993e5f51e19a.png)

**Comment by jillbong79** [comment]
Let me ask Lydia about changing the release date.


Sincerely,


Jill Bongiovanni

Office of Natural Resources Revenue

Minerals Revenue Specialist

Production, Reporting & Verification (PRV), Onshore Team 1A

Direct Line: 303-231-3523


Please note **ONRR is bound by lease terms and therefore, pursuant to 30 CFR:  For production reporting of oil, gas and geothermal resources on Federal lands, Indian lands, and in the Outer Continental Shelf, per 30 CFR §1210.103, production forms (Form ONRR-4054, Oil and Gas Operations Report, and Form ONRR-4058, Production Allocation Schedule Report) must be received by ONRR by the 15th day of the second month following the month for which you are reporting.**


SELF-HELP LINKS

·         Help with REPORTING here<https://www.onrr.gov/ReportPay/royalty-reporting.htm>!
·       Data Warehouse (E-Commerce, Invoices, eSoa, etc.)<https://sso.onrr.gov/oaam_server/login.do>
·         Reporter handbooks<https://www.onrr.gov/reportpay/Handbooks/index.htm>
·         Guidance on adjustments, recoupments & refunds<https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Chapter-6.pdf>
·         Lease (STATUS & MAINTENANCE) click here<https://www.onrr.gov/ReportPay/PDFDocs/RS_LeAgAssignments.pdf>!
·         Access to the system/update your info here<https://www.onrr.gov/reportpay/forms/index.htm>! (EMARF/4444/SURETY/W-9)
·         Help with PAYMENTS here<https://www.onrr.gov/reportpay/payments.htm>!
·         Help with a ‘Demand to Pay’ or ‘Potential Treasury Referral’ here<https://www.onrr.gov/ReportPay/PDFDocs/DebtCollectionAssign.pdf>!
·         Federal Accounts Receivable Contacts<https://www.onrr.gov/ReportPay/PDFDocs/finserAssign.pdf>
·         Indian Accounts Receivable Contacts<https://www.onrr.gov/ReportPay/PDFDocs/FSIndianCoAssign.pdf>
·         Password resets/System issues-contact the help desk at 303-231-3333 or enterpriseitservicedesk@bsee.gov<mailto:enterpriseitservicedesk@bsee.gov>
For help with 2014's: Royalty Reporting Contacts<http://www.onrr.gov/ReportPay/PDFDocs/royassign.pdf>
For help with OGOR's: Production Reporting Contacts<http://www.onrr.gov/ReportPay/PDFDocs/operasgn.pdf>
For help with Lease/Agreement Reporting: Lease Agreement Reporting Contacts<http://www.onrr.gov/ReportPay/PDFDocs/RS_LeAgAssignments.pdf>

________________________________

**Comment by jillbong79** [comment]
I asked Lydia about the release version and date, and they want Release 3.0 and Date 6/25/2020.


Sincerely,


Jill Bongiovanni

Office of Natural Resources Revenue

Minerals Revenue Specialist

Production, Reporting & Verification (PRV), Onshore Team 1A

Direct Line: 303-231-3523


Please note **ONRR is bound by lease terms and therefore, pursuant to 30 CFR:  For production reporting of oil, gas and geothermal resources on Federal lands, Indian lands, and in the Outer Continental Shelf, per 30 CFR §1210.103, production forms (Form ONRR-4054, Oil and Gas Operations Report, and Form ONRR-4058, Production Allocation Schedule Report) must be received by ONRR by the 15th day of the second month following the month for which you are reporting.**


SELF-HELP LINKS

·         Help with REPORTING here<https://www.onrr.gov/ReportPay/royalty-reporting.htm>!
·       Data Warehouse (E-Commerce, Invoices, eSoa, etc.)<https://sso.onrr.gov/oaam_server/login.do>
·         Reporter handbooks<https://www.onrr.gov/reportpay/Handbooks/index.htm>
·         Guidance on adjustments, recoupments & refunds<https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Chapter-6.pdf>
·         Lease (STATUS & MAINTENANCE) click here<https://www.onrr.gov/ReportPay/PDFDocs/RS_LeAgAssignments.pdf>!
·         Access to the system/update your info here<https://www.onrr.gov/reportpay/forms/index.htm>! (EMARF/4444/SURETY/W-9)
·         Help with PAYMENTS here<https://www.onrr.gov/reportpay/payments.htm>!
·         Help with a ‘Demand to Pay’ or ‘Potential Treasury Referral’ here<https://www.onrr.gov/ReportPay/PDFDocs/DebtCollectionAssign.pdf>!
·         Federal Accounts Receivable Contacts<https://www.onrr.gov/ReportPay/PDFDocs/finserAssign.pdf>
·         Indian Accounts Receivable Contacts<https://www.onrr.gov/ReportPay/PDFDocs/FSIndianCoAssign.pdf>
·         Password resets/System issues-contact the help desk at 303-231-3333 or enterpriseitservicedesk@bsee.gov<mailto:enterpriseitservicedesk@bsee.gov>
For help with 2014's: Royalty Reporting Contacts<http://www.onrr.gov/ReportPay/PDFDocs/royassign.pdf>
For help with OGOR's: Production Reporting Contacts<http://www.onrr.gov/ReportPay/PDFDocs/operasgn.pdf>
For help with Lease/Agreement Reporting: Lease Agreement Reporting Contacts<http://www.onrr.gov/ReportPay/PDFDocs/RS_LeAgAssignments.pdf>

________________________________

**Comment by jennmalcolm** [comment]
All files provided were made live on Friday.
