### ISSUE TITLE
Production Contact List Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2100]
Please replace the Onshore and Offshore Production contacts lists with the attached at this location - https://www.onrr.gov/about/contact.htm

[Onshore Production Assignments.pdf](https://github.com/ONRR/onrr.gov-site/files/9294639/Onshore.Production.Assignments.pdf)
[Offshore Operators.pdf](https://github.com/ONRR/onrr.gov-site/files/9294638/Offshore.Operators.pdf)

**Comment by lpgoldstein** [comment]
http://2017onrr/about/contact.htm

**Comment by bowlenj** [comment]
They both look great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: lpgoldstein ***@***.***>
Sent: Tuesday, August 9, 2022 3:46 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Production Contact List Update (Issue #2100)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



http://2017onrr/about/contact.htm

**Comment by lpgoldstein** [comment]
@bowlenj live! https://www.onrr.gov/about/contact.htm
