### ISSUE TITLE
Reporter Training Presentations

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2101]
Please replace existing presentations with the attached on this webpage - https://onrr.gov/reportpay/training/index.htm

- [x] [Federal and Indian Billing.pptx](https://github.com/ONRR/onrr.gov-site/files/9300998/Federal.and.Indian.Billing.pptx)
- [x] [How to Save the OGOR Document.pptx](https://github.com/ONRR/onrr.gov-site/files/9300999/How.to.Save.the.OGOR.Document.pptx)
- [x] [Lease_Agreement Basics (Federal and Indian).pptx](https://github.com/ONRR/onrr.gov-site/files/9301002/Lease_Agreement.Basics.Federal.and.Indian.pptx)
- [x] [Office of Enforcement.pptx](https://github.com/ONRR/onrr.gov-site/files/9301003/Office.of.Enforcement.pptx)
- [x] [OGOR ERROR Reporting_012022.pptx](https://github.com/ONRR/onrr.gov-site/files/9301004/OGOR.ERROR.Reporting_012022.pptx)
- [x] [OGOR Errors - Including 11030 Inventory Edit.pptx](https://github.com/ONRR/onrr.gov-site/files/9301005/OGOR.Errors.-.Including.11030.Inventory.Edit.pptx)
- [x] [ONRR Compliance Overview.pptx](https://github.com/ONRR/onrr.gov-site/files/9301006/ONRR.Compliance.Overview.pptx)
- [x] [ONRR Data Requests.pptx](https://github.com/ONRR/onrr.gov-site/files/9301007/ONRR.Data.Requests.pptx)
- [x] [Overlapping Agreements.pptx](https://github.com/ONRR/onrr.gov-site/files/9301009/Overlapping.Agreements.pptx)
- [x] [TC 11_15 Adjustments.pptx](https://github.com/ONRR/onrr.gov-site/files/9301010/TC.11_15.Adjustments.pptx)
- [x] [Top Royalty Errors - How to Correct.pptx](https://github.com/ONRR/onrr.gov-site/files/9301013/Top.Royalty.Errors.-.How.to.Correct.pptx)
- [x] [2014 Adjustment and Recoupments.pptx](https://github.com/ONRR/onrr.gov-site/files/9301014/2014.Adjustment.and.Recoupments.pptx)
- [x] [Basic 2014.pptx](https://github.com/ONRR/onrr.gov-site/files/9301015/Basic.2014.pptx)
- [x] [Basic OGOR Report.pptx](https://github.com/ONRR/onrr.gov-site/files/9301016/Basic.OGOR.Report.pptx)
- [x] [Commonly Used 2014 Transaction Codes.pptx](https://github.com/ONRR/onrr.gov-site/files/9301017/Commonly.Used.2014.Transaction.Codes.pptx)
- [x] [Compliance - Production and Royalty Walk-Through.pptx](https://github.com/ONRR/onrr.gov-site/files/9301019/Compliance.-.Production.and.Royalty.Walk-Through.pptx)
- [x] [CSV file - OGORS.pptx](https://github.com/ONRR/onrr.gov-site/files/9301020/CSV.file.-.OGORS.pptx)
- [x] [eCommerce and Electronic Tools - Production.pptx](https://github.com/ONRR/onrr.gov-site/files/9301022/eCommerce.and.Electronic.Tools.-.Production.pptx)
- [x] [Ecommerce and Electronic Tools- Royalty.pptx](https://github.com/ONRR/onrr.gov-site/files/9301029/Ecommerce.and.Electronic.Tools-.Royalty.pptx)
- [x] [Federal & Indian AR and Debt Collection.pptx](https://github.com/ONRR/onrr.gov-site/files/9301031/Federal.Indian.AR.and.Debt.Collection.pptx)

**Comment by cthomasONRR** [comment]
@bowlenj I'm having trouble matching up these docs names to what we have on file, on https://onrr.gov/reportpay/training/index.htm. It would be a huge help if you could rename these files to match what it currently on the website.

- [ ] "Federal.and.Indian.Billing.pptx" Is the one new? I can't match it with any files.
- [ ] "Lease_Agreement.Basics.Federal.and.Indian.pptx" Is this one new? I can't match it with any files.
- [ ] "Office.of.Enforcement.pptx" is this the same as "ONRR.Enforcement.pptx"? That's the file name we currently have.
- [ ]  "OGOR.ERROR.Reporting_012022.pptx" is this the same as "ERRORS.OGOR.Reporting.pptx"? That's the file name we currently have.
- [ ] "OGOR.Errors.-.Including.11030.Inventory.Edit.pptx" is this the same as ""Edit.11030.Inventory.Error.pptx"? That's the file name we currently have.
- [ ] "ONRR.Compliance.Overview.pptx" Is the one new? I can't match it with any files.
- [ ] "ONRR.Data.Requests.pptx" Is the one new? I can't match it with any files.
- [ ] "Overlapping.Agreements.pptx" is this the same as "Overlap.Training"?  That's the file name we currently have.
- [ ] "TC.11_15.Adjustments.pptx" Is the one new? I can't match it with any files.
- [ ] "Top.Royalty.Errors.-.How.to.Correct.pptx" is this the same as "ERRORS.2014.Reporting.pptx"? That's the file name we currently have.
- [ ] "2014.Adjustment.and.Recoupments.ppt" Is the one new? I can't match it with any files.
- [ ] "Basic.2014.pptx"  is the the same as "2014.Reporting.pptx"? That's the file name we currently have.
- [ ] "Commonly.Used.2014.Transaction.Codes.pptx" is the the same as "Royalty.Transaction.Codes.pptx"? That's the file name we currently have.
- [ ] "Compliance.-.Production.and.Royalty.Walk-Through.pptx" is this the same as "173_CMP2014_Industry_View.pptx"? That's the file name we currently have.
- [ ] "Federal.Indian.AR.and.Debt.Collection.pptx" Is the one new? I can't match it with any files.

**Comment by bowlenj** [comment]
Hi Christine,

Thank you so much for all the time and research you put into this request.  I replied in chat that the remaining 5 you had questions on I believe are new.  I was unable to find a matching presentation already on the website.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, August 10, 2022 9:21 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Reporter Training Presentations (Issue #2101)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C3fbba958a2cc42a2dc1508da7ae3fa4f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637957416826121666%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=b8Wfib%2BeO4qMoEqd6Ik5KHE8B4sV9YZHv6Iyxb%2FMBpo%3D&reserved=0> I'm having trouble matching up these docs names to what we have on file, on https://onrr.gov/reportpay/training/index.htm<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fonrr.gov%2Freportpay%2Ftraining%2Findex.htm&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C3fbba958a2cc42a2dc1508da7ae3fa4f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637957416826277895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7sB6Ndj8NIhsrqiiD%2BdU4nQfKBC93ftQAIFh3CalFZY%3D&reserved=0>. It would be a huge help if you could rename these files to match what it currently on the website.

  *    "Federal.and.Indian.Billing.pptx" Is the one new? I can't match it with any files.
  *    "Lease_Agreement.Basics.Federal.and.Indian.pptx" Is this one new? I can't match it with any files.
  *    "Office.of.Enforcement.pptx" is this the same as "ONRR.Enforcement.pptx"? That's the file name we currently have.
  *    "OGOR.ERROR.Reporting_012022.pptx" is this the same as "ERRORS.OGOR.Reporting.pptx"? That's the file name we currently have.
  *    "OGOR.Errors.-.Including.11030.Inventory.Edit.pptx" is this the same as ""Edit.11030.Inventory.Error.pptx"? That's the file name we currently have.
  *    "ONRR.Compliance.Overview.pptx" Is the one new? I can't match it with any files.
  *    "ONRR.Data.Requests.pptx" Is the one new? I can't match it with any files.
  *    "Overlapping.Agreements.pptx" is this the same as "Overlap.Training"? That's the file name we currently have.
  *    "TC.11_15.Adjustments.pptx" Is the one new? I can't match it with any files.
  *    "Top.Royalty.Errors.-.How.to.Correct.pptx" is this the same as "ERRORS.2014.Reporting.pptx"? That's the file name we currently have.
  *    "2014.Adjustment.and.Recoupments.ppt" Is the one new? I can't match it with any files.
  *    "Basic.2014.pptx" is the the same as "2014.Reporting.pptx"? That's the file name we currently have.
  *    "Commonly.Used.2014.Transaction.Codes.pptx" is the the same as "Royalty.Transaction.Codes.pptx"? That's the file name we currently have.
  *    "Compliance.-.Production.and.Royalty.Walk-Through.pptx" is this the same as "173_CMP2014_Industry_View.pptx"? That's the file name we currently have.
  *    "Federal.Indian.AR.and.Debt.Collection.pptx" Is the one new? I can't match it with any files.

**Comment by cthomasONRR** [comment]
@bowlenj 

Great! I have all docs- new and old- in the dev site now: http://2017onrr/reportpay/training/index.htm

Please review and let me know if it's good to go live.

Thanks,
Christine

**Comment by bowlenj** [comment]
They all look GREAT!  Thank you again!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, August 10, 2022 12:01 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Reporter Training Presentations (Issue #2101)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C4b60c040366d445e0b8408da7afa66f8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637957513136600346%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AXkV%2FVbldNU6MWgrbx1gQJDFG3Gz5YGdNg77uCTsgHc%3D&reserved=0>

Great! I have all docs- new and old- in the dev site now: http://2017onrr/reportpay/training/index.htm

Please review and let me know if it's good to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj Great, these changes are now live: https://www.onrr.gov/reportpay/training/index.htm
Please remember to use "Ctrl+F5" to refresh the page.

Thanks,
Christine
