### ISSUE TITLE
Update Supervisor on Bankruptcy page

### ISSUE THREAD

**Issue by KristianL3101** [ONRR/onrr.gov-site#2102]
Please remove Tim Calahan as contact and replace with Cindy Hergenreder

cindy.hergenreder@onrr.gov
303-231-3557

https://onrr.gov/compliance/bankruptcies.htm

**Comment by lpgoldstein** [comment]
@KristianL3101 ready for review: http://2017onrr/compliance/bankruptcies.htm

**Comment by KristianL3101** [comment]
Looks good.

Kristian Lee
Enforcement Specialist
ONRR/OE Litigation Support
Denver Federal Center, Bldg 85/B76
PO Box 25165 MS 64200B
Denver, CO  80225-0165
(303) 231-3101

________________________________
From: lpgoldstein ***@***.***>
Sent: Wednesday, August 10, 2022 12:54 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Lee, Kristian H ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update Supervisor on Bankruptcy page (Issue #2102)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@KristianL3101<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKristianL3101&data=05%7C01%7Ckristian.lee%40onrr.gov%7C7f592b70e9d94dfac9d708da7b01b515%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637957544518283106%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1z9wErmEkas9f4v9pTBciaoTX%2BE%2BqSDQilgTN3s%2BrO0%3D&reserved=0> ready for review: http://2017onrr/compliance/bankruptcies.htm

**Comment by lpgoldstein** [comment]
@KristianL3101 It's live https://www.onrr.gov/compliance/bankruptcies.htm
