### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov

### ISSUE THREAD

**Issue by StaceyKaiser** [ONRR/onrr.gov-site#2105]
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm called “Cross-Reference Lease to Agreement Number” with the file entitled “August 2022 Lease Agreement XREF.txt and August 2022 Lease Agreement XREF.xlsx”.  It was queried from the system on 8/11/2022.

[August 2022 Lease Agreement XREF.txt](https://github.com/ONRR/onrr.gov-site/files/9309953/August.2022.Lease.Agreement.XREF.txt)
[August 2022 Lease Agreement XREF.xlsx](https://github.com/ONRR/onrr.gov-site/files/9309966/August.2022.Lease.Agreement.XREF.xlsx)

**Comment by Maroyafaied** [comment]
@StaceyKaiser please review http://2017onrr/ReportPay/CrossRef.htm

**Comment by StaceyKaiser** [comment]
@Maroyafaied the file looks good. Please move to the live site.  Thanks!

**Comment by Maroyafaied** [comment]
@StaceyKaiser Thanks, this is now live.

**Comment by Maroyafaied** [comment]
This is updated in the cms as well.
