### ISSUE TITLE
Draft presentation material with ideas for leadership on communicating launch

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2106]

**Comment by Maroyafaied** [comment]
@cthomasONRR @lpgoldstein Since we are not ready to actually consult with leadership, I will change this issue title to "Draft presentation material with ideas for leadership on communicating launch". By this I mean, I'd like us to start a brief power point or maybe just a word doc with our ideas in issue #2044 and assign roles to each idea.  I'll schedule a meeting to start this today.

**Comment by cthomasONRR** [comment]
@Maroyafaied @lpgoldstein I'm working on a powerpoint, I will post it here when it's ready.

**Comment by cthomasONRR** [comment]
@Maroyafaied @lpgoldstein PowerPoint is located here: https://doimspp.sharepoint.com/:p:/r/sites/NRRD/Shared%20Documents/General/Outreach/Website%20Launch%20Communications%20Plan.pptx?d=wb885012d9a164096a6169d18ed4cacd9&csf=1&web=1&e=hHe6g1

**Comment by cthomasONRR** [comment]
@Maroyafaied @lpgoldstein This is ready for your review

**Comment by Maroyafaied** [comment]
@cthomasONRR It looks great. I added slide #6 and #9 as options if we don't want to specify a date and rearranged wording. Let me know your thoughts , I will show this to Nathan as well. @lpgoldstein

**Comment by cthomasONRR** [comment]
@Maroyafaied I made some minor text/formatting updates. Looks good! Thanks!

**Comment by Maroyafaied** [comment]
Nathan would like us to add the Banner with no dates mentioned and with the link to the Beta Site.

**Comment by cthomasONRR** [comment]
@Maroyafaied @lpgoldstein The powerpoint has been thoroughly reviewed. Closing this issue.
