### ISSUE TITLE
Updated Reporter Training Presentations

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2108]
Please replace the existing presentations with the attached updated slides here - https://onrr.gov/reportpay/training/index.htm

NOTE: The Indian Gas Major Portion Reporting presentation is new and should be put under Royalty Valuation.

- [x] [2014 Adjustment and Recoupments.pptx](https://github.com/ONRR/onrr.gov-site/files/9338119/2014.Adjustment.and.Recoupments.pptx)
- [x] [Basic 2014.pptx](https://github.com/ONRR/onrr.gov-site/files/9338120/Basic.2014.pptx)
- [x] [Basic OGOR Report.pptx](https://github.com/ONRR/onrr.gov-site/files/9338122/Basic.OGOR.Report.pptx)
- [x] [Commonly Used 2014 Transaction Codes.pptx](https://github.com/ONRR/onrr.gov-site/files/9338123/Commonly.Used.2014.Transaction.Codes.pptx)
- [x] [Compliance - Production and Royalty Walk-Through.pptx](https://github.com/ONRR/onrr.gov-site/files/9338124/Compliance.-.Production.and.Royalty.Walk-Through.pptx)
- [x] [CSV file - OGORS.pptx](https://github.com/ONRR/onrr.gov-site/files/9338125/CSV.file.-.OGORS.pptx)
- [x] [eCommerce and Electronic Tools - Production.pptx](https://github.com/ONRR/onrr.gov-site/files/9338126/eCommerce.and.Electronic.Tools.-.Production.pptx)
- [x] [Ecommerce and Electronic Tools- Royalty.pptx](https://github.com/ONRR/onrr.gov-site/files/9338137/Ecommerce.and.Electronic.Tools-.Royalty.pptx)
- [x] [Federal & Indian AR and Debt Collection.pptx](https://github.com/ONRR/onrr.gov-site/files/9338138/Federal.Indian.AR.and.Debt.Collection.pptx)
- [x] [Federal and Indian Billing.pptx](https://github.com/ONRR/onrr.gov-site/files/9338140/Federal.and.Indian.Billing.pptx)
- [x] [How to Save the OGOR Document.pptx](https://github.com/ONRR/onrr.gov-site/files/9338141/How.to.Save.the.OGOR.Document.pptx)
- [x] [Indian Gas Major Portion Reporting.pptx](https://github.com/ONRR/onrr.gov-site/files/9338149/Indian.Gas.Major.Portion.Reporting.pptx)
- [x] [Lease_Agreement Basics (Federal and Indian).pptx](https://github.com/ONRR/onrr.gov-site/files/9338150/Lease_Agreement.Basics.Federal.and.Indian.pptx)
- [x] [Office of Enforcement.pptx](https://github.com/ONRR/onrr.gov-site/files/9338152/Office.of.Enforcement.pptx)
- [x] [OGOR ERROR Reporting_012022.pptx](https://github.com/ONRR/onrr.gov-site/files/9338155/OGOR.ERROR.Reporting_012022.pptx)
- [x] [OGOR Errors - Including 11030 Inventory Edit.pptx](https://github.com/ONRR/onrr.gov-site/files/9338156/OGOR.Errors.-.Including.11030.Inventory.Edit.pptx)
- [x] [ONRR Compliance Overview.pptx](https://github.com/ONRR/onrr.gov-site/files/9338157/ONRR.Compliance.Overview.pptx)
- [x] [ONRR Data Requests.pptx](https://github.com/ONRR/onrr.gov-site/files/9338159/ONRR.Data.Requests.pptx)
- [x] [Overlapping Agreements.pptx](https://github.com/ONRR/onrr.gov-site/files/9338160/Overlapping.Agreements.pptx)
- [x] [TC 11_15 Adjustments.pptx](https://github.com/ONRR/onrr.gov-site/files/9338163/TC.11_15.Adjustments.pptx)
- [x] [Top Royalty Errors - How to Correct.pptx](https://github.com/ONRR/onrr.gov-site/files/9338166/Top.Royalty.Errors.-.How.to.Correct.pptx)

**Comment by bowlenj** [comment]
This looks great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Monday, August 15, 2022 10:00 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Updated Reporter Training Presentations (Issue #2108)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C5ce1f86c9beb43f76c2208da7ed75889%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637961760609630962%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hX7KHpziaRInk%2FdqfmMYoP0B3FXiYJa%2BKOKnnZMp8hk%3D&reserved=0>

These changes are now on the dev site: http://2017onrr/reportpay/training/index.htm.
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj Great these changes are now live: https://www.onrr.gov/reportpay/training/index.htm
Please remember to use "Ctrl+F5" to refresh the page.

Thanks,
Christine
