### ISSUE TITLE
Update 2 Reporter Training Slides

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2110]
Please replace/add the attached slides as indicated below on the following page - https://onrr.gov/reportpay/training/index.htm

Replace Billing Presentation under "Paying" with Federal and Indian Billing

Add new presentation Unbundling Basics to "Royalty Valuation"

[Federal and Indian Billing.pptx](https://github.com/ONRR/onrr.gov-site/files/9339968/Federal.and.Indian.Billing.pptx)
[Unbundling Basics.pdf](https://github.com/ONRR/onrr.gov-site/files/9339969/Unbundling.Basics.pdf)

**Comment by Maroyafaied** [comment]
@bowlenj please review http://2017onrr/reportpay/training/index.htm

**Comment by Maroyafaied** [comment]
@cthomasONRR i've added these 2 documents to the cms but waiting for the site to be back up to review. Just letting you know incase you have to take over this issue tomorrow and push live. Thanks

![image](https://user-images.githubusercontent.com/40175688/184744530-709541ad-22b4-4b2d-b52c-9c9c6620eeee.png)

**Comment by cthomasONRR** [comment]
I discussed with Jessica over Teams. These changes are approved and now live.

**Comment by bowlenj** [comment]
Good Morning,

Could Federal and Indian Billing be moved to "Paying" and replace the existing presentation Billing under "Paying"?

[cid:c77127c4-4910-43a9-acf9-f2e58898d6d3][cid:b5cec661-a076-4759-9884-89b97f2e91d5]

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Maroyafaied ***@***.***>
Sent: Monday, August 15, 2022 5:16 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update 2 Reporter Training Slides (Issue #2110)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cad6deffbeba84482bfc908da7f142c15%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637962021863829899%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0SARWXOSK40t1xkyQFkZoO1n%2FNbvjv15LFFvd6EHMVo%3D&reserved=0> please review http://2017onrr/reportpay/training/index.htm
