### ISSUE TITLE
Reporter Training Presentation

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2111]
Please add the attached presentation under Royalty Valuation located here - https://www.onrr.gov/reportpay/training/index.htm
[Federal Valuation Basics.pdf](https://github.com/ONRR/onrr.gov-site/files/9353500/Federal.Valuation.Basics.pdf)

**Comment by cthomasONRR** [comment]
@bowlenj Is this a new presentation? Or is it replacing the one currently titled "Federal Processed Gas Reporting"?

**Comment by cthomasONRR** [comment]
@bowlenj I cross-referenced, and these looks like different presentations. I added it as a new document under Royalty Valuation. It's in dev for you to review: http://2017onrr/reportpay/training/index.htm

**Comment by bowlenj** [comment]
Darn I thought I covered everything!  From what I can tell this is a new one, it is not replacing anything.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Tuesday, August 16, 2022 12:37 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Reporter Training Presentation (Issue #2111)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cc7cdff6485844a902c0308da7fb663a3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637962718573899757%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xj6b8ksy9tjMJ68rLNEw%2BtzVK%2BAeUVnzh8SfoNDstsI%3D&reserved=0> Is this a new presentation? Or is it replacing the one currently titled "Federal Processed Gas Reporting"?

**Comment by cthomasONRR** [comment]
Chatted with Jessica on Teams. Changes are live: https://www.onrr.gov/reportpay/training/index.htm. Closing this issue.

**Comment by bowlenj** [comment]
I just saw this, thank you.  Yes it was a new presentation.  I checked and it looks great!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Tuesday, August 16, 2022 12:44 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Reporter Training Presentation (Issue #2111)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C83ddb19110444c55413908da7fb7656c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637962722906199019%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ISzxQdctFcLx9483w3vESOtS8C%2F1PPCTHGtuhuyvALg%3D&reserved=0> I cross-referenced, and these looks like different presentations. I added it as a new document under Royalty Valuation. It's in dev for you to review: http://2017onrr/reportpay/training/index.htm
