### ISSUE TITLE
Reporter Training Presentation Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2112]
Under Compliance & Enforcement please replace ONRR Enforcement with the attached updated presentation located here - https://www.onrr.gov/reportpay/training/index.htm
[Office of Enforcement.pptx](https://github.com/ONRR/onrr.gov-site/files/9363582/Office.of.Enforcement.pptx)

**Comment by cthomasONRR** [comment]
@bowlenj 

This update is now on the dev site: http://2017onrr/reportpay/training/index.htm
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by bowlenj** [comment]
Looks great!  Thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, August 17, 2022 9:07 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Reporter Training Presentation Update (Issue #2112)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cad9e738111ba46d9010b08da806244c0%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637963456799255255%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BzuUOUDljMaCz%2BRK8iqnq418R%2FQT5oQIGx8IMFJQVT8%3D&reserved=0>

This update is now on the dev site: http://2017onrr/reportpay/training/index.htm
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj 

Great,
This change is now live: https://www.onrr.gov/reportpay/training/index.htm
Please remember to use "Ctrl+F5" to refresh the page.
Thanks,
Christine
