### ISSUE TITLE
CMP Dear Reporter Letter

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2113]
Please add the attached Dear Reporter Letter CMP P&R to the following webpage - https://onrr.gov/DearRep.htm

[Dear Reporter Letter-CMP P&R_508 2022-08-17_SIGNED.pdf](https://github.com/ONRR/onrr.gov-site/files/9365061/Dear.Reporter.Letter-CMP.P.R_508.2022-08-17_SIGNED.pdf)

**Comment by lpgoldstein** [comment]
@bowlenj Is this a new entry and what should the title be? Thanks!

**Comment by bowlenj** [comment]
Hi Lindsey,

Yes this is a new letter.  The subject of the letter is CMP P&R Electronic Reporting Requirement and it was dated 8/17/2022.  Can we use CMP P&R Electronic Reporting Requirement as the title and 8/17/2022 for the date column?

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: lpgoldstein ***@***.***>
Sent: Wednesday, August 17, 2022 12:01 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] CMP Dear Reporter Letter (Issue #2113)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C2c7eee93252643e6fb4908da807a888e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637963561042520765%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Yl260kuI5ubC8zRzEe0%2FcGamN2TzF9efqU3Nb2Yx8ek%3D&reserved=0> Is this a new entry and what should the title be? Thanks!

**Comment by lpgoldstein** [comment]
@bowlenj ready for your review

**Comment by bowlenj** [comment]
Can you provide the link for me to review?

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: lpgoldstein ***@***.***>
Sent: Wednesday, August 17, 2022 1:34 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] CMP Dear Reporter Letter (Issue #2113)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cdddc762414394301b05408da80878202%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637963616731666475%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FpNQGnQDgisoM86N1zAzvwBxllm61%2BH9dTNlZe7PTYo%3D&reserved=0> ready for your review

**Comment by lpgoldstein** [comment]
approved via teams chat. @bowlenj will be live soon.

**Comment by bowlenj** [comment]
It looks great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: lpgoldstein ***@***.***>
Sent: Wednesday, August 17, 2022 1:34 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] CMP Dear Reporter Letter (Issue #2113)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cdddc762414394301b05408da80878202%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637963616731666475%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FpNQGnQDgisoM86N1zAzvwBxllm61%2BH9dTNlZe7PTYo%3D&reserved=0> ready for your review
