### ISSUE TITLE
Update training presentation cards

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#2116]
Make the training presentations cards "block v col" 4 in length:
- [x] https://dev-onrr-frontend.app.cloud.gov/reporting/production?tabs=references

Make a training videos card for:
- [x] https://dev-onrr-frontend.app.cloud.gov/reporting/production?tabs=references

Make sure training presentations are consistent and retitle cards
- [x] https://dev-onrr-frontend.app.cloud.gov/reporting/production?tabs=references
- [x] https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=references
- [x] https://dev-onrr-frontend.app.cloud.gov/reporting/solids?tabs=references

Create new training cards on https://dev-onrr-frontend.app.cloud.gov/references/training for:
- [x] Reporting systems
- [x] Lease and Agreements
- [x] Royalty Valuation
- [x] Paying 
- [x] Compliance and Enforcement

Add existing training cards to https://dev-onrr-frontend.app.cloud.gov/references/training for:
- [x] O&G Production Reporting
- [x] O&G Revenue Reporting
- [x] Solid Minerals

**Comment by cthomasONRR** [comment]
@Maroyafaied These are ready for your review:

At https://dev-onrr-frontend.app.cloud.gov/reporting/production?tabs=references, I changed the training presentation card width and added the training videos card:
![image](https://user-images.githubusercontent.com/72526208/185467832-ddc02dfe-74af-4488-a89b-9974d1323047.png)

At https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=references, I made sure all training presentations were included in the card
![image](https://user-images.githubusercontent.com/72526208/185467921-713c5175-cdd9-4102-9c04-0f7738a2d827.png)

At https://dev-onrr-frontend.app.cloud.gov/reporting/solids?tabs=references, I decided to keep the "Solids Reporting Presentations" slide because it's part of a response in Troubleshooting. Since RRM specifically picked what they wanted in Troubleshooting, I didn't want to change it. I added all Solids Training presentations in the next card. Let me know if you think we should remove the "Solids Reporting Presentations" from this references tab and just have it in the Troubleshooting response.
![image](https://user-images.githubusercontent.com/72526208/185468348-302d1ad3-4405-4bb9-9dcb-8852074198ac.png)

At https://dev-onrr-frontend.app.cloud.gov/references/training, I was able to reuse the cards within Reporting-References and added new cards for everything else. I'm still having issues getting the PowerPoint icon to appear, but all other icons (pdfs) are present.

**Comment by Maroyafaied** [comment]
@cthomasONRR There's one ppt that's on the current website that we don't have listed in dev under oil & gas production training. Otherwise everything else looks great. Thanks

![image](https://user-images.githubusercontent.com/40175688/185674992-2ebb15ba-9599-4c43-bf94-2572da4bee51.png)

**Comment by cthomasONRR** [comment]
@Maroyafaied Fixed!
![image](https://user-images.githubusercontent.com/72526208/186163325-f8f72101-f333-4033-b690-0c96f23e0b9d.png)

**Comment by Maroyafaied** [comment]
@cthomasONRR This looks good to close. Thanks
