### ISSUE TITLE
Appendix I - Disposition /Adjustment Code

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#2120]
Hello, please update Appendix I PDF with the attached document. 

https://www.onrr.gov/reportpay/Handbooks/index.htm

Thank you!

[MPRH-Appendix-I Disp codes.pdf](https://github.com/ONRR/onrr.gov-site/files/9410911/MPRH-Appendix-I.Disp.codes.pdf)

**Comment by cthomasONRR** [comment]
@merrellc 

Good morning,
This change is on the dev site: http://2017onrr/reportpay/Handbooks/index.htm
Please review and give us your approval to go live.
Thanks,
Christine

**Comment by cthomasONRR** [comment]
@merrellc 
I got Candace to review and approve via Teams chat.
This update is now live: https://www.onrr.gov/reportpay/Handbooks/index.htm
Please use "Ctrl+F5" to refresh the page.
Thanks,
Christine
