### ISSUE TITLE
Add VDP to the footer 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2121]
ACISO informed the IT program manager that the current onnr.gov is not in compliance with Vulnerability Disclosure Policy. We need to add the link to the footer of the current website and the new dev website. I'm asking if it's ok if we only add it to the homepage of the current website since to make that change on dreamweaver for every single webpage would be extremely time consuming. 

This is link we need to add https://www.doi.gov/vulnerability-disclosure-policy

**Comment by Maroyafaied** [comment]
@cthomasONRR can you review the Vulnerability disclosure policy is added to the footer, if it looks good then I'll push live. Thanks http://2017onrr/

**Comment by cthomasONRR** [comment]
@Maroyafaied I see it on the dev site and the link works for me.

**Comment by Maroyafaied** [comment]
@cthomasONRR I also added the link to the footer on the dev site and rearranged the order of some of the links. Please review.  I sent Joe an email explaining that it's added on the current homepage and it's time consuming to add to every page. I'll keep this open until I hear that its ok to only have it on the homepage.

**Comment by cthomasONRR** [comment]
@Maroyafaied Looks good!

**Comment by Maroyafaied** [comment]
@cthomasONRR Thanks. IT program manager confirmed the update meets the requirement and asked we add this to the NRRD footer as well. I opened an issue for next sprint for the NRRD.
