### ISSUE TITLE
Solid Minerals Reporter Handbook - Appendix D

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#2123]
Hi, please update Appendix D on the ONRR website with the attached PDF document. The current Appendix D is located at -
https://www.onrr.gov/reportpay/Handbooks/pdfdocs/SMRH_Appendix_D.pdf

Thank you!
[Appendix D Product Codes.pdf](https://github.com/ONRR/onrr.gov-site/files/9426032/Appendix.D.Product.Codes.pdf)

**Comment by cthomasONRR** [comment]
@merrellc 
Hi Candace,
I ran the Adobe accessibility check on this document, and these are several errors that need to be corrected:
![image](https://user-images.githubusercontent.com/72526208/186707947-460315c8-0b04-46b6-8834-db1fe3f5463c.png)
Please send us an accessible version of this document to post on the website.
Thanks,
Christine

**Comment by merrellc** [comment]
The PDF was updated from the one that was already on the web to correct some spelling. Thought it would be compliant.  Thanks!


Kind Regards,
​Candace Merrell
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.
________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, August 25, 2022 9:34 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Solid Minerals Reporter Handbook - Appendix D (Issue #2123)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@merrellc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmerrellc&data=05%7C01%7Ccandace.merrell%40onrr.gov%7C7002eff5505549df019108da86af3e2f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637970384465292990%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FEvUsP4g1LWsXr4i0uWPla6Z9beYd55wfc2AWoOCA9Y%3D&reserved=0>
Hi Candace,
I ran the Adobe accessibility check on this document, and these are several errors that need to be corrected:
[image]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F72526208%2F186707947-460315c8-0b04-46b6-8834-db1fe3f5463c.png&data=05%7C01%7Ccandace.merrell%40onrr.gov%7C7002eff5505549df019108da86af3e2f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637970384465292990%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bObD%2Bp5X60tuSKykJoSWl2h%2FDJPb7jW1K8tW99AUj6U%3D&reserved=0>
Please send us an accessible version of this document to post on the website.
Thanks,
Christine

**Comment by merrellc** [comment]
Corrected file attached.
[Appendix D Product Codes.pdf](https://github.com/ONRR/onrr.gov-site/files/9426624/Appendix.D.Product.Codes.pdf)

**Comment by cthomasONRR** [comment]
@merrellc 
Thanks! This update is on the dev site:
http://2017onrr/reportpay/Handbooks/index.htm
http://2017onrr/reportpay/Handbooks/pdfdocs/SMRH_Appendix_D.pdf
Please review and give me your approval to go live.
Thanks,
Christine

**Comment by merrellc** [comment]
Ready to go live.  Thank you!


Kind Regards,
​Candace Merrell
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.
________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, August 25, 2022 10:33 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Solid Minerals Reporter Handbook - Appendix D (Issue #2123)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@merrellc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmerrellc&data=05%7C01%7Ccandace.merrell%40onrr.gov%7C7375524369e34a95c2a808da86b796b5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637970420309775110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QPaP6ghHhuN8f%2BTewUl%2Fm0D9NDQdclHl9XY3cuVQ3vY%3D&reserved=0>
Thanks! This update is on the dev site:
http://2017onrr/reportpay/Handbooks/index.htm
http://2017onrr/reportpay/Handbooks/pdfdocs/SMRH_Appendix_D.pdf
Please review and give me your approval to go live.
Thanks,
Christine

**Comment by cthomasONRR** [comment]
@merrellc Great! These changes are now live:
https://www.onrr.gov/reportpay/Handbooks/index.htm
https://www.onrr.gov/reportpay/Handbooks/pdfdocs/SMRH_Appendix_D.pdf
Please remember to use "Ctrl+F5" to refresh the page.
Thanks,
Christine
