### ISSUE TITLE
Appendix I- Disposition /Adjustment Codes

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#2129]
Hello, please update Production Reporter Handbook Appendix I on the ONRR website at the following link-

https://www.onrr.gov/reportpay/Handbooks/index.htm

Please use the attached PDF document.

Thank you!

[MPRH-Appendix-I Disp codes_3.0-1.pdf](https://github.com/ONRR/onrr.gov-site/files/9455380/MPRH-Appendix-I.Disp.codes_3.0-1.pdf)

**Comment by lpgoldstein** [comment]
@merrellc This is ready for your review: http://2017onrr/reportpay/Handbooks/index.htm

**Comment by merrellc** [comment]
Ready to go live. Thank you!


Kind Regards,
​Candace Merrell
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.
________________________________
From: lpgoldstein ***@***.***>
Sent: Tuesday, August 30, 2022 12:26 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Appendix I- Disposition /Adjustment Codes (Issue #2129)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@merrellc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmerrellc&data=05%7C01%7Ccandace.merrell%40onrr.gov%7Cb9a508431c1b45a246e908da8ab535e4%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637974808143730846%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ngp8%2FsxdDF90jLeAdZQNks%2BIn81IY1JsbLRAPLQ8GhA%3D&reserved=0> This is ready for your review: http://2017onrr/reportpay/Handbooks/index.htm

**Comment by lpgoldstein** [comment]
@merrellc I'm not sure how this document is different from the old one so I can't tell if it's live or not. If it isn't yet, it should be very soon. Thanks!

**Comment by lpgoldstein** [comment]
confirmed via chat that this is live and correct
