### ISSUE TITLE
find another location for physical address change message

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#213]
![image](https://user-images.githubusercontent.com/40175688/86142195-279f8e80-bab0-11ea-8556-44146482e2db.png)

**Comment by Maroyafaied** [comment]
@jennmalcolm the physical address is already updated in the office location section, I can add to that section the part about visitor parking and who to call to gain entrance. Let me know you thoughts.
https://www.onrr.gov/About/office-locations.htm
 ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/bb9e1c6b-7c81-4928-8468-33b78d85f03b)

**Comment by jennmalcolm** [comment]
Yes, I think that works @Maroyafaied

**Comment by Maroyafaied** [comment]
We added the information in the office location page under the Denver section.  https://www.onrr.gov/About/office-locations.htm
