### ISSUE TITLE
Write wiki instructions for the new release workflow process

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#2130]
https://github.com/ONRR/onrr.gov-site/wiki/Releasing-changes-to-production-for-the-new-CMS

**Comment by cthomasONRR** [comment]
@lpgoldstein @Maroyafaied I drafted some instructions. Hopefully we can discuss if I'm going in the right direction here at our meeting on Wednesday: https://github.com/ONRR/onrr.gov-site/wiki/Releasing-changes-to-production-for-the-new-CMS

**Comment by Maroyafaied** [comment]
@Maroyafaied review

**Comment by Maroyafaied** [comment]
@cthomasONRR Looks good, I don't have any changes.
