### ISSUE TITLE
Cross-Referenced Lease & Agreement Number Lists page Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2138]
Please remove the below report from this page - https://www.onrr.gov/reportpay/CrossRef.htm.  It's an old version that's been replaced by Cross-Reference Lease to Agreement Number.

Agreements Tied to a Lease Number (updated 5/3/2021)

**Comment by cthomasONRR** [comment]
@bowlenj

Good morning,
I removed this document: http://2017onrr/reportpay/CrossRef.htm
Please review and give us you approval to go live.
Thanks,
Christine

**Comment by bowlenj** [comment]
Perfect, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, September 1, 2022 7:32 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Cross-Referenced Lease & Agreement Number Lists page Update (Issue #2138)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cea9eea5928454712c5b008da8c1e7368%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637976359666501547%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4x5SVaXadC9wqjgyyve8Bje1zo3QB1jNqDXAzoqyzC4%3D&reserved=0>

Good morning,
I removed this document: http://2017onrr/reportpay/CrossRef.htm
Please review and give us you approval to go live.
Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj

Great! These changes are now live: https://www.onrr.gov/reportpay/CrossRef.htm
Please remember to use "Ctrl+F5" to refresh the page.

Thanks,
Christine
