### ISSUE TITLE
URGENT:  New Dear Reporter Letter

### ISSUE THREAD

**Issue by jpetersononrr** [ONRR/onrr.gov-site#214]
I sent the PDF to Jennifer, Lindsay, and Maroya.  We need to post the Dear Reporter letter on ONRR.gov.  The date is being extended to October 1, 2020.  Could you please post the letter here:  https://www.onrr.gov/DearRep.htm

Title:  Extending the Deadline for 2016 Valuation Rule Compliance to 10/01/2020

I believe the Dear Reporter letter section on the homepage is fed from that page automatically.

Also we need to adjust the language and the letter link in the announcements section.  If it could say:

2016 Valuation Rule Implementation
Please see the Dear Reporter Letter on Extending the Deadline for 2016 Valuation Rule Compliance to October 1, 2020.

An example of how to value processed gas under the new 2016 Valuation Rule can be found here.

The link should go to the new letter, and if you could bold the October 1, 2020, that would be great!  If the box could be another color to indicate the change (green or red) that would also be fantastic, but I understand if it's not going to work. 

Please give me a call if I've left something out.  508-527-7729.  Thanks!

**Comment by lpgoldstein** [comment]
@jpetersononrr I'm taking care of this right now

**Comment by lpgoldstein** [comment]
@jpetersononrr This is ready for your review: 
http://2017onrr/DearRep.htm
http://2017onrr/

**Comment by jpetersononrr** [comment]
Hi Lindsay,

The link on this page is wrong.  http://2017onrr/DearRep.htm Looks like the letter link needs an extra “20” to round out “2020”.  And if you could change the date to 06/30/2020 in the table.  Also maybe list updates after you publish? On the home page under the “Dear Reporter” tab.  Thanks for your help!

​Jodie Peterson
Minerals Revenue Specialist
Office of Natural Resources Revenue
​jodie.peterson@onrr.gov
(303)231-3719

Royalty Valuation - Consistent Answers to Complex Questions

**Comment by lpgoldstein** [comment]
@jpetersononrr I've fixed the dear reporter page https://www.onrr.gov/DearRep.htm and am now working on the press release announcement area on the bottom of the homepage

**Comment by jpetersononrr** [comment]
That looks good!  Thank you!


​Jodie Peterson
Minerals Revenue Specialist
Office of Natural Resources Revenue
​jodie.peterson@onrr.gov
(303)231-3719

Royalty Valuation - Consistent Answers to Complex Questions

**Comment by lpgoldstein** [comment]
@jpetersononrr the announcement section at the bottom of the page is should work now too http://2017onrr/#letters

**Comment by jpetersononrr** [comment]
That looks great!

My only concern is that the links on the announcement box and the dear reporter page start with 2017onrr.  The one on the dear reporter tab at the bottom of the homepage doesn’t work right now because it’s onrr.gov/pdfdoc/ etc.  Which is fine.  But I wanted to check those.  Thanks!

​Jodie Peterson
Minerals Revenue Specialist
Office of Natural Resources Revenue
​jodie.peterson@onrr.gov
(303)231-3719

Royalty Valuation - Consistent Answers to Complex Questions

**Comment by lpgoldstein** [comment]
@jpetersononrr for some reason it's not updating in Chrome but when I copied the link into explorer it worked

**Comment by lpgoldstein** [comment]
![image](https://user-images.githubusercontent.com/39419003/86184085-a1f00300-baf0-11ea-8db1-32ca64c88bb7.png)
@jpetersononrr

**Comment by jpetersononrr** [comment]
Ok!  Let’s put it live and we can check it before telling folks!

​Jodie Peterson
Minerals Revenue Specialist
Office of Natural Resources Revenue
​jodie.peterson@onrr.gov
(303)231-3719

Royalty Valuation - Consistent Answers to Complex Questions

**Comment by lpgoldstein** [comment]
@jpetersononrr I've pushed everything and will keep checking on it until it's live

**Comment by jpetersononrr** [comment]
Hi!

Looks like the announcement box is the only thing that didn’t change.  Thanks!

​Jodie Peterson
Minerals Revenue Specialist
Office of Natural Resources Revenue
​jodie.peterson@onrr.gov
(303)231-3719

Royalty Valuation - Consistent Answers to Complex Questions

**Comment by jpetersononrr** [comment]
Did you put the homepage live?  Still not seeing the announcement box.

​Jodie Peterson
Minerals Revenue Specialist
Office of Natural Resources Revenue
​jodie.peterson@onrr.gov<mailto:jodie.peterson@onrr.gov>
(303)231-3719

Royalty Valuation - Consistent Answers to Complex Questions

From: Peterson, Jodie F
Sent: Tuesday, June 30, 2020 5:04 PM
To: ONRR/onrr.gov-site <reply@reply.github.com<mailto:reply@reply.github.com>>
Subject: RE: [EXTERNAL] Re: [ONRR/onrr.gov-site] URGENT: New Dear Reporter Letter (#214)

Hi!

Looks like the announcement box is the only thing that didn’t change.  Thanks!

​Jodie Peterson
Minerals Revenue Specialist
Office of Natural Resources Revenue
​jodie.peterson@onrr.gov<mailto:jodie.peterson@onrr.gov>
(303)231-3719

Royalty Valuation - Consistent Answers to Complex Questions
