### ISSUE TITLE
Add banner announcement of site launch on homepage 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2144]

**Comment by Maroyafaied** [comment]
@cthomasONRR @lpgoldstein please review this banner, let me know if you have any changes. I'll ask Nathan about specifying the date or not. http://2017onrr/

**Comment by cthomasONRR** [comment]
@Maroyafaied Looks good!

**Comment by Maroyafaied** [comment]
This is live.
