### ISSUE TITLE
EASTERN OK REGIONAL VIRTUAL MEETING                            (to be added to Event Calendar)

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#2145]
****EASTERN OK REGIONAL VIRTUAL MEETING**
**Tuesday, September 20, 2022****
1:00 pm to 2:00 pm CST

Location:  By Telephone

DESCRIPTION: The Office of Natural Resources Revenue (ONRR) will be hosting a virtual (call-in) Outreach Meeting for Indian mineral owners.  Representatives from the Bureau of Land Management (BLM), Bureau of Trust Funds Administration (BTFA), and the Bureau of Indian Affairs (BIA) will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts, and Indian Trust property issues.  The meeting will begin with the brief introduction by the ONRR representative.  Owners will have an opportunity to ask questions with the representatives of the four agencies during the Q&A session 

WHO SHOULD ATTEND:  Indian mineral owners, IIM account holders and other Indian Trust property owners in the Eastern Regional areas in Oklahoma, including Muskogee, Okmulgee, Creek, and Wagoner counties. 
  
OTHER INFORMATION: To reserve a space and get a passcode for this meeting please contact the ONRR OKC Outreach Office toll-free at (800) 354-7015. The OKC office hours are Mon.- Fri. from 7:30 am-5:00 pm.

CONTACT: ONRR OKC Outreach Office, Phone: Toll Free (800) 354-7015 or Main No..(405)879-6050.
EMAIL: onrroutreachokc@onrr.gov

**KAULEY VIRTUAL OUTREACH MEETING**
**Tuesday, September 27, 2022**
1:00 pm to 2:00 pm CST

Location:  By Telephone

DESCRIPTION: The Office of Natural Resources Revenue (ONRR) will be hosting a virtual Outreach Meeting for Indian trust property owners. This call-in meeting will begin with a brief presentation given by the host representative of the ONRR office.  Representatives from the Bureau of Land Management (BLM), Bureau of Trust Funds Administration (BTFA), and the Bureau of Indian Affairs (BIA) will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust property issues.  Owners will have an opportunity to ask questions with the representatives of the four agencies during the Q&A session.

WHO SHOULD ATTEND: IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Eastern OK region of Oklahoma.

OTHER INFORMATION: To reserve a space and get a passcode for this meeting please contact the ONRR OKC Outreach Office toll-free (800)354-7015. The OKC Outreach office hours are Mon.- Fri. from 7:30 am-4:30 pm CST.

CONTACT: ONRR OKC Outreach Office, Phone: (800) 354-7015 or Main No: (405) 879-6050.   EMAIL: [onrroutreachokc@onrr.gov](https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=onrroutreachokc@onrr.gov)

**Comment by Toddsand21** [comment]
And there is no hurry on this.  I am off tomorrow but I might check and see if I get it back tomorrow sometime, otherwise I'll see it next week.  Thanks!

**Comment by lpgoldstein** [comment]
@Toddsand21 Are office hours in OKC until 4:30 or 5:00? Thanks!

**Comment by Toddsand21** [comment]
Sorry it changed at one time.  Hours are 7:30am-5:00pm

**Comment by lpgoldstein** [comment]
@Toddsand21 This is ready for your review: http://2017onrr/events.htm

**Comment by Toddsand21** [comment]
1. On the EASTERN REGIONAL Who Should Attend:  Can you just end the sentence after?     Eastern Regional areas,   AND DELETE rest of sentence  in Oklahoma.   and delete the rest  which reads  "including Muskogee, Okmulgee, Creek, and Wagoner counties."
2. On the EASTERN REGIONALMTG'S  DESCRIPTION: Could you change the end of the first sentence from Indian mineral owners to read Indian trust property owners.
3. ON KAULEY MTG.  in the DESCRIPTION; Delete after presentation given by  "the host representative of"  and just add the word "representative" at the end of sentence  ... to read given by the ONRR office representative.

**Comment by Toddsand21** [comment]
Here is the newer version with the edits made. 

EASTERN OK REGIONAL AREA VIRTUAL MEETING
Tuesday, September 20, 2022
1:00 pm to 2:00 pm CST

Location:  By Telephone

DESCRIPTION: The Office of Natural Resources Revenue (ONRR) will host a virtual (call-in) Outreach Meeting for Indian trust property owners.  Representatives from the Bureau of Land Management (BLM), Bureau of Trust Funds Administration (BTFA), and the Bureau of Indian Affairs (BIA) will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts, and Indian Trust property issues.  The meeting will begin with the brief introduction by the ONRR representative.  Owners will have an opportunity to ask questions with the representatives of the four agencies during the Q&A session 

WHO SHOULD ATTEND:  Indian mineral owners, IIM account holders and other Indian Trust property owners in the Eastern OK Regional areas in Oklahoma. 
  
OTHER INFORMATION: To reserve a space and get a passcode for this meeting please contact the ONRR OKC Outreach Office toll-free at (800) 354-7015. The OKC office hours are Mon.- Fri. from 7:30 am-5:00 pm CST.

CONTACT: ONRR OKC Outreach Office, Phone: Toll Free (800) 354-7015 or Main No.
(405)879-6050.  EMAIL: onrroutreachokc@onrr.gov

KAULEY OUTREACH MEETING (VIRTUAL)
Tuesday, September 27, 2022
1:00 pm to 2:00 pm CST

Location:  By Telephone

DESCRIPTION: The Office of Natural Resources Revenue (ONRR) will host a virtual Outreach Meeting for Indian trust property owners.  This call-in meeting will begin with a brief presentation by the ONRR Office representative.  Representatives from the Bureau of Land Management (BLM), Bureau of Trust Funds Administration (BTFA), and the Bureau of Indian Affairs (BIA) will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust property issues.  Owners will have an opportunity to ask questions with the representatives of the four agencies during the Q&A session.

WHO SHOULD ATTEND: IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Southern Plains region in Oklahoma.  

OTHER INFORMATION: To reserve a space and get a passcode for this meeting please contact the OKC ONRR Outreach Office toll-free at (800)354-7015. The OKC Outreach office hours are Mon.- Fri. from 7:30 am-5:00 pm CST.

CONTACT: ONRR OKC Outreach Office, Phone: (800) 354-7015 or Main No: (405) 879-6050.   EMAIL: onrroutreachokc@onrr.gov

**Comment by lpgoldstein** [comment]
@Toddsand21 this is ready for your review: http://2017onrr/events.htm

**Comment by Toddsand21** [comment]
On Eastern OK: under Who Should Attend:  Delete the rest of the sentence after it reads   in the Eastern Regional areas in Oklahoma.    (End here after Oklahoma.

**Comment by lpgoldstein** [comment]
@Toddsand21 ready for review again http://2017onrr/events.htm

**Comment by Toddsand21** [comment]
In the first sentence of the Eastern OK Meeting under the Description:  Take out the word "virtual" and the parenthesis around call-in and leave call-in Outreach Meeting...

Everything looks fine and ready to go.

**Comment by lpgoldstein** [comment]
@Toddsand21 done. I'll push live when you give the okay.

**Comment by Toddsand21** [comment]
It looks fine and ready to post.

**Comment by lpgoldstein** [comment]
@Toddsand21 I posted it. I'll let you know when live.

**Comment by lpgoldstein** [comment]
@Toddsand21 live so closing issue.
