### ISSUE TITLE
Update to Dev Site

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2148]
Please update the Dev site page for "What happens if I pay late?":

Third paragraph "Terminable Nonproducing Leases" should read:

If your lease is terminable and you miss your rent, your lease will terminate. You will need to work with BLM to reinstate your lease. 

[Mail - Bowlen, Jessica G - Outlook.pdf](https://github.com/ONRR/onrr.gov-site/files/9500166/Mail.-.Bowlen.Jessica.G.-.Outlook.pdf)

**Comment by cthomasONRR** [comment]
@bowlenj 

The changes are in the dev site: https://dev-onrr-frontend.app.cloud.gov/paying/contacts-paying?panel=what-happens-if-i-pay-late

![image](https://user-images.githubusercontent.com/72526208/188728838-eae297a2-ccbe-472a-b3f2-a8799e16cc9f.png)

Please review and give me your approval.

Thanks,
Christine

**Comment by bowlenj** [comment]
Perfect!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Tuesday, September 6, 2022 2:09 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update to Dev Site (Issue #2148)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cf0d80e165be943695beb08da9043cbbf%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637980918101608290%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5z8ckFhwT3Blis7ur2bsql2zIpCk50zWiw1WSppWprE%3D&reserved=0>

The changes are in the dev site: https://dev-onrr-frontend.app.cloud.gov/paying/contacts-paying?panel=what-happens-if-i-pay-late<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Fpaying%2Fcontacts-paying%3Fpanel%3Dwhat-happens-if-i-pay-late&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cf0d80e165be943695beb08da9043cbbf%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637980918101608290%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=y3J4KyIoQK21qfQAuzm9JYjFuZtO3lTIV7NHIGhDqdY%3D&reserved=0>

[image]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F72526208%2F188728838-eae297a2-ccbe-472a-b3f2-a8799e16cc9f.png&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cf0d80e165be943695beb08da9043cbbf%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637980918101608290%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=V%2F6MJMddMaZJgsV0Ti8jFxPqc56h08JKsQx4R2Gg3XQ%3D&reserved=0>

Please review and give me your approval.

Thanks,
Christine
