### ISSUE TITLE
ONRR.gov NYMEX August prices ready

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#2149]
The NYMEX prices for August 2022 are ready to be posted and the spreadsheet ready to be uploaded as well.
[NYMEX082022.xlsx](https://github.com/ONRR/onrr.gov-site/files/9501514/NYMEX082022.xlsx)

Thanks,
Cory Forgrave
@sudarr

**Comment by lpgoldstein** [comment]
@foregravec ready for your review: http://2017onrr/valuation/NYMEX.htm

**Comment by forgravec** [comment]
It all looks good...thanks.

Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
***@***.***
________________________________
From: lpgoldstein ***@***.***>
Sent: Wednesday, September 7, 2022 6:08 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Forgrave, Cory J ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] ONRR.gov NYMEX August prices ready (Issue #2149)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@foregravec ready for your review: http://2017onrr/valuation/NYMEX.htm

**Comment by lpgoldstein** [comment]
@forgravec Live!
