### ISSUE TITLE
Webpage Update (Active Leases)

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#215]
Please update the following webpage -
http;//www.onrr.gov/reportpay/crossRef.htm with the attached pdf file.

Active Leases - sorted by state and Agency lease number. Please change to read updated 07/01/2020.
[ALwState.pdf](https://github.com/ONRR/onrr.gov-site/files/4860073/ALwState.pdf)

Thank you

**Comment by lpgoldstein** [comment]
@merrellc this is ready for your review: http://2017onrr/ReportPay/CrossRef.htm

**Comment by merrellc** [comment]
Looks ready to go. Thank you

​Candace Merrell
Minerals Revenue Analyst

Office of Natural Resources Revenue

Reference and Reporting Management

303-231-3517

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________
