### ISSUE TITLE
Update index zone pricing on onrr.gov

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#2150]
Good afternoon,

Please update the September index zone prices based on the values provided in the "Data for onrr.gov" spreadsheet.

Thank you!

@sudarr

**Comment by boices** [comment]
Those are perfect--thanks again!

**Comment by cthomasONRR** [comment]
@boices 

Great, it's now live: https://www.onrr.gov/valuation/allzones.htm
Please remember to use "Ctrl+F5" to refresh the page.

Thanks,
Christine
