### ISSUE TITLE
Add the newest two reporter letters to CMS

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2151]
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/d12db731-3468-4c7c-9512-1fd22f29b70b)

**Comment by cthomasONRR** [comment]
@Maroyafaied They are now in dev: https://dev-onrr-frontend.app.cloud.gov/references/reporter-letters

![image](https://user-images.githubusercontent.com/72526208/189122798-aa5c5f9b-877e-423d-babe-ce1f9a6ddedd.png)

**Comment by Maroyafaied** [comment]
@cthomasONRR looks good, thanks
