### ISSUE TITLE
Please update the Payments webpage with the following form

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#2152]
Hello,

On the Payments webpage: https://www.onrr.gov/reportpay/payments.htm

Please update the existing Form ONRR-2014 (https://www.onrr.gov/reportpay/PDFDocs/2014.pdf)

With the following document:
[2014.pdf](https://github.com/ONRR/onrr.gov-site/files/9528585/2014.pdf)

Thanks,
Christine

**Comment by Maroyafaied** [comment]
@cthomasONRR your update is ready to be reviewed http://2017onrr/reportpay/Forms/index.htm

**Comment by cthomasONRR** [comment]
@Maroyafaied Looks great! Ready to go live!

**Comment by Maroyafaied** [comment]
@cthomasONRR this is live.
