### ISSUE TITLE
Update to Royalty & Production Reporter Checklist

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2154]
Please update onrr.gov as described below:

https://onrr.gov/reportpay/roy-checklist.htm - under title "Have ONRR assign a Payor Code to your company"
     Replace Jessica Bowlen's name and email with Tony Demons  Tony.Demons@onrr.gov

https://onrr.gov/reportpay/prod-checklist.htm - under title "Have ONRR assign an Operator Number to your company"
    Replace Jessica Bowlen's name and email with Tony Demons  Tony.Demons@onrr.gov

Thank You!

**Comment by cthomasONRR** [comment]
@bowlenj 

The changes are now in dev: 
http://2017onrr/reportpay/roy-checklist.htm
http://2017onrr/reportpay/prod-checklist.htm

Please review and let me know if you approve.

Thanks,
Christine

**Comment by bowlenj** [comment]
Looks great, I approve!!!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, September 8, 2022 1:58 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update to Royalty & Production Reporter Checklist (Issue #2154)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C85a0228a36ef404e676208da91d48dba%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637982639345990842%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qaDjP3Ws2mXoSzwv2eoKoO8qWxNVlcHHAlNxzn8oHPo%3D&reserved=0>

The changes are now in dev:
http://2017onrr/reportpay/roy-checklist.htm
http://2017onrr/reportpay/prod-checklist.htm

Please review and let me know if you approve.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj 

Great, the changes are now live:
https://onrr.gov/reportpay/roy-checklist.htm 
https://onrr.gov/reportpay/prod-checklist.htm 
Please remember to use "Ctrl+F5" to refresh the page.

Thanks,
Christine
