### ISSUE TITLE
Update Press Releases missing Date

### ISSUE THREAD

**Issue by mentastc** [ONRR/onrr.gov-site#2158]
Hi All,
Howard noticed that 5 of my press releases (2021 GOMESA press releases) we missing dates. Could you please replace them with the attached press releases? 
[Mississippi.GOMESA.Release.3.30.pdf](https://github.com/ONRR/onrr.gov-site/files/9536381/Mississippi.GOMESA.Release.3.30.pdf)
[2021_gomesa_Texas.pdf](https://github.com/ONRR/onrr.gov-site/files/9536382/2021_gomesa_Texas.pdf)
[Louisiana.GOMESA.Release.3.30.pdf](https://github.com/ONRR/onrr.gov-site/files/9536383/Louisiana.GOMESA.Release.3.30.pdf)
[GOMESA.National.Release.pdf](https://github.com/ONRR/onrr.gov-site/files/9536384/GOMESA.National.Release.pdf)
[Alabama.GOMESA.Release.3.30.pdf](https://github.com/ONRR/onrr.gov-site/files/9536385/Alabama.GOMESA.Release.3.30.pdf)

**Comment by Maroyafaied** [comment]
@mentastc I checked the first pdf and it failed for accessibility.  All the docs will need to be made accessible before we can post them. Thanks

**Comment by mentastc** [comment]
@Maroyafaied  I think I have the files fixed below. 
[Louisiana.GOMESA.Release.3.30.pdf](https://github.com/ONRR/onrr.gov-site/files/9536783/Louisiana.GOMESA.Release.3.30.pdf)
[Alabama.GOMESA.Release.3.30.pdf](https://github.com/ONRR/onrr.gov-site/files/9536784/Alabama.GOMESA.Release.3.30.pdf)
[Mississippi.GOMESA.Release.3.30.docx](https://github.com/ONRR/onrr.gov-site/files/9536785/Mississippi.GOMESA.Release.3.30.docx)
[GOMESA.National.Release.pdf](https://github.com/ONRR/onrr.gov-site/files/9536786/GOMESA.National.Release.pdf)
[Mississippi.GOMESA.Release.3.30.pdf](https://github.com/ONRR/onrr.gov-site/files/9536787/Mississippi.GOMESA.Release.3.30.pdf)
[2021_gomesa_Texas.pdf](https://github.com/ONRR/onrr.gov-site/files/9536788/2021_gomesa_Texas.pdf)

**Comment by lpgoldstein** [comment]
@mentastc I'm getting table summary failures on all of the docs. When you check accessibility you have to make sure that all options are checked. 
![image (2)](https://user-images.githubusercontent.com/39419003/189388700-24b11854-a7e8-46db-bc8a-400dcc87faab.png)

**Comment by mentastc** [comment]
@lpgoldstein Third times a charm. See if these work. 
[Louisiana.GOMESA.Release.3.30.pdf](https://github.com/ONRR/onrr.gov-site/files/9537005/Louisiana.GOMESA.Release.3.30.pdf)
[2021_gomesa_Texas.pdf](https://github.com/ONRR/onrr.gov-site/files/9537006/2021_gomesa_Texas.pdf)
[Mississippi.GOMESA.Release.3.30.pdf](https://github.com/ONRR/onrr.gov-site/files/9537007/Mississippi.GOMESA.Release.3.30.pdf)
[GOMESA.National.Release.pdf](https://github.com/ONRR/onrr.gov-site/files/9537008/GOMESA.National.Release.pdf)
[Alabama.GOMESA.Release.3.30.pdf](https://github.com/ONRR/onrr.gov-site/files/9537009/Alabama.GOMESA.Release.3.30.pdf)

**Comment by lpgoldstein** [comment]
@mentastc They pass the test! I'll send you a dev link shortly

**Comment by lpgoldstein** [comment]
@mentastc they are live
