### ISSUE TITLE
Plan user testing on new handbook design

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#216]

**Comment by jennmalcolm** [comment]
Can talk to Glen for people to interview.

**Comment by Maroyafaied** [comment]
Here is an attempt draft for the plan, I spoke with Glen about task ideas and he will get back to me next week.
 https://doimspp-my.sharepoint.com/personal/mchargs_mms_gov/_layouts/15/doc.aspx?sourcedoc={1c9e364c-6571-49ef-b601-06de87ef89c1}&action=edit

**Comment by mcharg** [comment]
@Maroyafaied Looks good!  I added a couple of comments.

**Comment by Maroyafaied** [comment]
@mcharg Thanks, I'll add Glenn's tasks once he sends them. @jennmalcolm please review when you have time.

**Comment by jennmalcolm** [comment]
I reviewed the plan and added my suggestions. Looks good.

**Comment by jennmalcolm** [comment]
recruiting in #733

**Comment by Maroyafaied** [comment]
@jennmalcolm I incorporated your comments, I didn't specify any tables or figures because for some reason I couldn't find the tables or figures on the handbook last time I checked.

**Comment by Maroyafaied** [comment]
All comments are incorporated.
