### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov

### ISSUE THREAD

**Issue by grjson** [ONRR/onrr.gov-site#2160]
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm called “Cross-Reference Lease to Agreement Number” with the file entitled “September 2022 Lease Agreement XREF.txt and September 2022 Lease Agreement XREF.xlsx”.  It was queried from the system on 9/12/2022.
[September 2022 Lease Agreement XREF.txt](https://github.com/ONRR/onrr.gov-site/files/9549623/September.2022.Lease.Agreement.XREF.txt)
[September 2022 Lease Agreement XREF.xlsx](https://github.com/ONRR/onrr.gov-site/files/9549649/September.2022.Lease.Agreement.XREF.xlsx)

**Comment by lpgoldstein** [comment]
@grjson Ready for your review: http://2017onrr/reportpay/CrossRef.htm

**Comment by lpgoldstein** [comment]
This is awaiting review by someone who is out of office until Wednesday.

**Comment by lpgoldstein** [comment]
Approved via email. closing out because live.
