### ISSUE TITLE
August 2022 IBMP Price 

### ISSUE THREAD

**Issue by damionschulte** [ONRR/onrr.gov-site#2163]
All, I have updated the Data for ONRR sheet on the OneDrive with the August 2022 IBMP Prices. Can you please publish them to the website?  Also I have attached a separate sheet with the prices in it.  Please let me know if you need anything else.  Thanks 
[August 22 IBMP For GitHub.xlsx](https://github.com/ONRR/onrr.gov-site/files/9550340/August.22.IBMP.For.GitHub.xlsx)

@sudarr

**Comment by cthomasONRR** [comment]
@damionschulte

These updates are on the dev site: http://2017onrr/valuation/IndianOilIBMP.htm
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by damionschulte** [comment]
These look perfect!  Thank you so much.

From: Christine Thomas ***@***.***>
Sent: Monday, September 12, 2022 11:55 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] August 2022 IBMP Price (Issue #2163)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@damionschulte<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdamionschulte&data=05%7C01%7Cdamion.schulte%40onrr.gov%7Ce8ef63dff2434ee6a78508da94e7ddf0%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637986020852202801%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BoYyULcrI8ycnqNwAxcP5t4ueeVggAvtcGYwY8ybHbQ%3D&reserved=0>

These updates are on the dev site: http://2017onrr/valuation/IndianOilIBMP.htm
Please review and give us your approval to go live.

Thanks,
Christine

-

**Comment by cthomasONRR** [comment]
@damionschulte

These changes are live: https://www.onrr.gov/valuation/IndianOilIBMP.htm
Please remember to use "Ctrl+F5' to refresh the page.

Thanks!
Christine

**Comment by damionschulte** [comment]
These look great as well.  Thank you again.

From: Christine Thomas ***@***.***>
Sent: Monday, September 12, 2022 12:32 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] August 2022 IBMP Price (Issue #2163)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@damionschulte<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdamionschulte&data=05%7C01%7Cdamion.schulte%40onrr.gov%7C94234eba3dd3413210d308da94ed1b6d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637986043342477162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2FmzNcll9ejTnXjj8GZRRv97G6qMc3nN%2FJ87vR3hCiA%3D&reserved=0>

These changes are live: https://www.onrr.gov/valuation/IndianOilIBMP.htm<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2Fvaluation%2FIndianOilIBMP.htm&data=05%7C01%7Cdamion.schulte%40onrr.gov%7C94234eba3dd3413210d308da94ed1b6d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637986043342633393%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8FjvECfHr8dYJeao7eLSu3pwaOo0itOR0zRiOxXqtfM%3D&reserved=0>
Please remember to use "Ctrl+F5' to refresh the page.

Thanks!
Christine

-
