### ISSUE TITLE
Draft social media post for beta site 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2165]

**Comment by cthomasONRR** [comment]
@Maroyafaied Do we know what social media? Twitter or Facebook, or both? I know Twitter has a character limit, 140 I think? (I don't have a personal twitter)

**Comment by Maroyafaied** [comment]
Yes twitter and FB. Chris asked to give him something general to post and then he can tweak it if needed.

**Comment by Maroyafaied** [comment]
@cthomasONRR Chris is good with what you sent and he will modify it a bit and post today.
