### ISSUE TITLE
Update production contacts in beta site 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2167]
We received an email that the beta site doesn't have the most updated contacts for production for onshore.  Issue #2100 was the last issue received for production contacts update.  Please make sure that the contacts in Beta are updated with that issue and match the current site.

**Comment by Maroyafaied** [comment]
@lpgoldstein SME confirmed this pdf has the most updated contacts https://www.onrr.gov/reportpay/PDFDocs/OnshoreProductionContacts.pdf

**Comment by cthomasONRR** [comment]
@lpgoldstein It looks like offshore production also needs to be updated.

**Comment by Maroyafaied** [comment]
@lpgoldstein I looked at the spreadhseet, we can't do the conceptual tap because we can't edit the headings in the cms. They can have two tabs, one for Fed and once for Indian so in the excel sheet they need to have a tab for Indian and a tab for Fed with the same fields. 
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/3de8eb9a-e3cb-4031-8b16-1ccb26e446f1
)

**Comment by cthomasONRR** [comment]
@Maroyafaied @lpgoldstein It might have to be 2 separate spreadsheets- we can only import CSV files into the CMS, and I'm pretty sure CSV doesn't allow for multiple tabs. Or, I might be totally out of the loop, and we'll export the CMS sheet, edit it as needed based on their multi-tab sheet, then re-import?

**Comment by Maroyafaied** [comment]
@cthomasONRR @lpgoldstein You can upload excel sheets in the cms, the NYMEX spreadsheet has multiple tabs. But it may be best to ask for two seperate spreadshees if Indian and Fed contacts changes don't happen at the same time.

**Comment by Maroyafaied** [comment]
@lpgoldstein please create a new template for them to use that is identical to the file that we use to export all contacts.  We can identify and describe which fields are relevant to them, we also need to tell them to do this as a csv.

**Comment by lpgoldstein** [comment]
closing this issue because we updated the contacts with the information available. This section will be updated later once the new company assignments are determined.
