### ISSUE TITLE
ONRR.gov website - Update NYMEX price June

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#217]
I am requesting to update the NYMEX and NYMEX roll prices for June 2020 onto ONRR.gov valuation page.
The prices have been added to the Onedrive "Data for ONRR.gov" spreadsheet. The Excel spreadsheet for uploading to the site is attached.
[NYMEX0620.xlsx](https://github.com/ONRR/onrr.gov-site/files/4865894/NYMEX0620.xlsx)

Thanks,
Cory Forgrave

@sudarr

**Comment by lpgoldstein** [comment]
@forgravec This is ready for your review: http://2017onrr/Valuation/NYMEX.htm

I had trouble seeing the preview in chrome so had to open it in IE. I promise it's there!

**Comment by forgravec** [comment]
The prices look good.  Open question though, why do we post the negative roll prices as a double negative?  The parenthesis represent a negative, but we also include the '-' as well.

Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589

________________________________

**Comment by lpgoldstein** [comment]
@forgravec I have no idea....is that what it always looks like? I'm just copying and pasting into a file.

**Comment by lpgoldstein** [comment]
@forgravec It's live! https://www.onrr.gov/Valuation/NYMEX.htm Have a good weekend!

**Comment by forgravec** [comment]
No worries...it has been like that and so I just chose not to raise the question until now.

Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589

________________________________

**Comment by jennmalcolm** [comment]
I have wondered about that too. That's just the formatting that they originally set up, but I would agree we should change that. We can put in an issue to work on that formatting. Would you want just the parentheses or just the minus sign?

**Comment by forgravec** [comment]
We are going to keep the '-' sign and remove the parenthesis.  Would you like me to open a new request?

Robert also would like for the text of the negative  Roll numbers to be red and positive to be black (currently they are blue) In addition we would change the NYMEX prices to be black as well (currently they are green).

Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589

________________________________

**Comment by jennmalcolm** [comment]
Thanks @forgravec. I'll open an issue, and we'll work on it this sprint (next 2 weeks). We'll let you know when the changes are ready to review.

**Comment by forgravec** [comment]
Thanks, I appreciate it.

Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589

________________________________
