### ISSUE TITLE
Posting new examples

### ISSUE THREAD

**Issue by jpetersononrr** [ONRR/onrr.gov-site#2172]
Hello!

Could you please add these to the table on the Valuation Regulations page?  Christine and I already discussed they won't go to the beta site until you have a developer and can put it on their list.  Thanks!
[Initial Reporting for Processed Gas in Non-Index Zone (Major Portion) Areas.pdf](https://github.com/ONRR/onrr.gov-site/files/9559330/Initial.Reporting.for.Processed.Gas.in.Non-Index.Zone.Major.Portion.Areas.pdf)
[Revised Reporting Using Actual Dual Accounting for Processed Gas in Non-Index Zone (Major Portion) Areas.pdf](https://github.com/ONRR/onrr.gov-site/files/9559331/Revised.Reporting.Using.Actual.Dual.Accounting.for.Processed.Gas.in.Non-Index.Zone.Major.Portion.Areas.pdf)
[Revised Reporting Using Alternative Dual Accounting for Processed Gas in Non-Index Zone (Major Portion) Areas.pdf](https://github.com/ONRR/onrr.gov-site/files/9559332/Revised.Reporting.Using.Alternative.Dual.Accounting.for.Processed.Gas.in.Non-Index.Zone.Major.Portion.Areas.pdf)

**Comment by cthomasONRR** [comment]
@jpetersononrr Here is the existing table. What do you want the titles for these 3 new docs? Should I be putting "Indian Example:" in front of any of the file names, so that would be the title?
![image](https://user-images.githubusercontent.com/72526208/189968391-443aaeda-e386-4412-b04d-45465c7b3d20.png)

**Comment by jpetersononrr** [comment]
Yes please!  Same as those titles, so it will be 
Indian Example:  Initial Reporting for Processed Gas in Non-Index Zone (Major Portion) Areas
Indian Example:  Revised Reporting Using Alternative Dual Accounting for Processed Gas in Non-Index Zone MP Areas
Indian Example:  Revised Reporting Using Actual Dual Accounting for Processed Gas in Non-Index Zone MP Areas

If those last 2 are too long, you can shorten to DA.  Thank you!!

**Comment by cthomasONRR** [comment]
@jpetersononrr

The changes are in the dev site: http://2017onrr/valuation/index.htm
Please review and give us approval to go live.

Thanks,
Christine

**Comment by jpetersononrr** [comment]
This may be totally on me.  The Actual Dual accounting is for Processed gas.  Not unprocessed.

Also, could you group the three processed ones and then have the 2 unprocessed ones?  Sorry..I know that’s a bit nitpicky, it just shows how they flow.

Thank you!!

Jodie Peterson
Minerals Revenue Specialist
Office of Natural Resources Revenue
***@***.******@***.***>
(303)231-3719

Royalty Valuation - Consistent Answers to Complex Questions

This email does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. Rather, this communication serves as guidance for determining value for royalties and is not an appealable decision or order under 30 CFR Part 1290, Subpart B. This guidance is based solely on the information provided and should only be used for the particular issue or question presented at the time of this communication. While this message is not appealable, ONRR may use this guidance in conducting audits and as a basis for demanding additional royalties.

From: Christine Thomas ***@***.***>
Sent: Tuesday, September 13, 2022 11:44 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Peterson, Jodie F ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Posting new examples (Issue #2172)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jpetersononrr<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjpetersononrr&data=05%7C01%7Cjodie.peterson%40onrr.gov%7Cab8246df5de8402c723008da95af9084%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637986878522832703%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RNrqdxbp0BdYrrv4kEqoLWB5inwY06kMAF1vOOuKYm0%3D&reserved=0>

The changes are in the dev site: http://2017onrr/valuation/index.htm
Please review and give us approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@jpetersononrr

How about this: http://2017onrr/valuation/index.htm

**Comment by jpetersononrr** [comment]
Awesome!!  Thank you so much for putting it up for us 😊!  We’re plugging them Thursday during STRAC.  I really appreciate it!

Jodie Peterson
Minerals Revenue Specialist
Office of Natural Resources Revenue
***@***.******@***.***>
(303)231-3719

Royalty Valuation - Consistent Answers to Complex Questions

This email does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. Rather, this communication serves as guidance for determining value for royalties and is not an appealable decision or order under 30 CFR Part 1290, Subpart B. This guidance is based solely on the information provided and should only be used for the particular issue or question presented at the time of this communication. While this message is not appealable, ONRR may use this guidance in conducting audits and as a basis for demanding additional royalties.

From: Christine Thomas ***@***.***>
Sent: Tuesday, September 13, 2022 11:58 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Peterson, Jodie F ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Posting new examples (Issue #2172)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jpetersononrr<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjpetersononrr&data=05%7C01%7Cjodie.peterson%40onrr.gov%7Caa553cb8d5ce405e207c08da95b18fd9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637986887099452879%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4SPltDTIMlgAa2ytheDG5KLxk1dR%2BOFnIe%2FvWG%2FLDko%3D&reserved=0>

How about this: http://2017onrr/valuation/index.htm

**Comment by cthomasONRR** [comment]
@jpetersononrr

Here's the new dev site for your review. https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=valuation-examples

**Comment by jpetersononrr** [comment]
Oh that is super fantastic too!!!  Thank you!!

Jodie Peterson
Minerals Revenue Specialist
Office of Natural Resources Revenue
***@***.******@***.***>
(303)231-3719

Royalty Valuation - Consistent Answers to Complex Questions

This email does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. Rather, this communication serves as guidance for determining value for royalties and is not an appealable decision or order under 30 CFR Part 1290, Subpart B. This guidance is based solely on the information provided and should only be used for the particular issue or question presented at the time of this communication. While this message is not appealable, ONRR may use this guidance in conducting audits and as a basis for demanding additional royalties.

From: Christine Thomas ***@***.***>
Sent: Tuesday, September 13, 2022 12:07 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Peterson, Jodie F ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Posting new examples (Issue #2172)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jpetersononrr<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjpetersononrr&data=05%7C01%7Cjodie.peterson%40onrr.gov%7Cbf3d90ee82164d1c6de608da95b2bcb7%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637986892152006737%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=p5P5YDxEwoBrout0fcJxzT55JISNjdLQpmMaBZRlxgs%3D&reserved=0>

Here's the new dev site for your review. https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=valuation-examples<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Freferences%2Fvaluation%3Ftabs%3Dvaluation-examples&data=05%7C01%7Cjodie.peterson%40onrr.gov%7Cbf3d90ee82164d1c6de608da95b2bcb7%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637986892152006737%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lnCvgx6f44IpN7%2Fb4ovjaSSY0p6cfKnZGoNT6Me6ICI%3D&reserved=0>

**Comment by jpetersononrr** [comment]
You rock!!  Thank you!

Jodie Peterson
Minerals Revenue Specialist
Office of Natural Resources Revenue
***@***.******@***.***>
(303)231-3719

Royalty Valuation - Consistent Answers to Complex Questions

This email does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. Rather, this communication serves as guidance for determining value for royalties and is not an appealable decision or order under 30 CFR Part 1290, Subpart B. This guidance is based solely on the information provided and should only be used for the particular issue or question presented at the time of this communication. While this message is not appealable, ONRR may use this guidance in conducting audits and as a basis for demanding additional royalties.

From: Christine Thomas ***@***.***>
Sent: Tuesday, September 13, 2022 12:32 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Peterson, Jodie F ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Posting new examples (Issue #2172)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jpetersononrr<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjpetersononrr&data=05%7C01%7Cjodie.peterson%40onrr.gov%7C0432c6ff7abf4f6893d608da95b63205%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637986907003191448%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gP0a1DzSp2r%2FRoPF6rVeSIShw8cvaMF4kZSJ1s%2F%2Fw5w%3D&reserved=0>

The changes are live,
on the old site: https://www.onrr.gov/valuation/index.htm<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2Fvaluation%2Findex.htm&data=05%7C01%7Cjodie.peterson%40onrr.gov%7C0432c6ff7abf4f6893d608da95b63205%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637986907003191448%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tY1u8XOQJN4qVFE7g0hqrBiVpGNOv11zT%2BAm2MUlQMk%3D&reserved=0>
and the beta site: https://beta.onrr.gov/references/valuation?tabs=valuation-examples<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbeta.onrr.gov%2Freferences%2Fvaluation%3Ftabs%3Dvaluation-examples&data=05%7C01%7Cjodie.peterson%40onrr.gov%7C0432c6ff7abf4f6893d608da95b63205%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637986907003191448%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nqc%2BUd3ylFZ6Ekm0xCxCH7168GzIjG47SVMHoqEhFzQ%3D&reserved=0>

Thanks,
Christine
