### ISSUE TITLE
Number tabs 9 and 20 not clickable in Offshore Production Contacts

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/onrr.gov-site#2175]
https://beta.onrr.gov/about/contact/production-contacts?tabs=contacts,offshore-production
![image](https://user-images.githubusercontent.com/39419003/190001837-e28db3ac-bb58-4b18-967f-8650d1dc656d.png)

**Comment by Maroyafaied** [comment]
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/dc1b7d0a-f21e-41e8-b56a-a932f47984b8)
