### ISSUE TITLE
Update July index zone on ONRR.gov

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#218]
Please update the July index zone values on the ONRR.gov website. The data can be found in our OneDrive in a spreadsheet called "Data for ONRR.gov" in the first tab "Index-Zones".

@sudarr

Thanks!

**Comment by lpgoldstein** [comment]
@boices @sudarr This is ready for your review: http://2017onrr/Valuation/allzones.htm

**Comment by boices** [comment]
@lpgoldstein that looks perfect--thank you!

@sudarr

**Comment by lpgoldstein** [comment]
@boices @sudarr It should be live https://www.onrr.gov/Valuation/allzones.htm
