### ISSUE TITLE
September 2022 Analytics 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2189]

**Comment by cthomasONRR** [comment]
@lpgoldstein 

onrr.gov analytics are ready for your review: https://github.com/ONRR/onrr.gov-site/wiki/Analytics

Word doc to help with your review: https://doimspp-my.sharepoint.com/:w:/r/personal/thomasc_mms_gov/Documents/CLT%20Analytics/Analytics%20September%2022.docx?d=w202417110061419d8836e2d0a4f9ad60&csf=1&web=1&e=jnBIu4

**Comment by lpgoldstein** [comment]
@cthomasONRR Looks good!
