### ISSUE TITLE
Changes to NYMEX formatting

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#219]
For negative numbers, keep the '-' sign and remove the parenthesis. 

Also,  the text of the negative Roll numbers to be red and positive to be black (currently they are blue) In addition we would change the NYMEX prices to be black as well (currently they are green).

**Comment by jennmalcolm** [comment]
@forgravec it looks like they probably made the NYMEX and roll prices green and blue to correspond to the colors on the line graph. We can look at adding labels to those lines or creating a legend for the graph or something else... Let us know if your team has ideas about how to make it clear what those lines represent if we're changing the text color?

![image](https://user-images.githubusercontent.com/30806839/86606108-93cd3700-bf75-11ea-8bbf-e70d468ca6c8.png)

**Comment by forgravec** [comment]
I think a legend would be best. Is that graph automatically created within the code of the website? Or is it copied and pasted in?

I will ask Robert his thoughts and get back with you.

Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589

________________________________

**Comment by forgravec** [comment]
Robert says a legend would be fine to add to the graph.

Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589

________________________________

**Comment by jennmalcolm** [comment]
It is automatically created through the code, so we'll get one of our developers to help us look into how to improve it and add a legend. Thanks.

**Comment by jennmalcolm** [comment]
Hi @forgravec could you please review the changes in dev?

http://2017onrr/Valuation/NYMEX.htm

**Comment by forgravec** [comment]
Jennifer,

Overall the color of the prices look good but in the formatting can a '0' be added for the hundreds position in the price...for instance instead of $78.4 have it $78.40?

Thanks!
Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589

________________________________

**Comment by jennmalcolm** [comment]
Yes, I made that change @forgravec. Let me know if it's ready to go live.

**Comment by forgravec** [comment]
Is there  a new link to see the change? Using the prior link you sent I am not seeing the change. This is what I am seeing...
[cid:495fe819-372c-4d05-aed1-9ec0bbe017d1]

Thanks,
Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589

________________________________

**Comment by jennmalcolm** [comment]
@forgravec It's the same link. You may need to clear your cache. Try pressing ctrl and F5 or viewing it in another browser.

**Comment by forgravec** [comment]
That worked. The prices look good.

Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589

________________________________

**Comment by jennmalcolm** [comment]
The changes are live now.

**Comment by forgravec** [comment]
Thanks!

Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589

________________________________
