### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov

### ISSUE THREAD

**Issue by grjson** [ONRR/onrr.gov-site#2191]
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm called “Cross-Reference Lease to Agreement Number” with the file entitled “September 2022 Lease Agreement XREF.txt and September 2022 Lease Agreement XREF.xlsx”.  It was queried from the system on 9/27/2022.
[September 2022 Lease Agreement XREF.txt](https://github.com/ONRR/onrr.gov-site/files/9656024/September.2022.Lease.Agreement.XREF.txt)
[September 2022 Lease Agreement XREF.xlsx](https://github.com/ONRR/onrr.gov-site/files/9656040/September.2022.Lease.Agreement.XREF.xlsx)

**Comment by cthomasONRR** [comment]
@grjson 

Good morning,
These changes are on the dev site: http://2017onrr/reportpay/CrossRef.htm
Please review and give us your approval to go live.
Thanks,
Christine

**Comment by grjson** [comment]
Christine,
Thank you, the analyst that is Peer Reviewing this request is off today. We will review it tomorrow and get back with you.
Thanks,
Gary


Gary Johnson

Information & Data Management/

Data Optimization, Retrieval, and Coordination (DORC)

Office of Natural Resources Revenue (ONRR)
***@***.******@***.***>
303-231-3962

DORC_FOIA Group Email
***@***.***

________________________________
From: Christine Thomas ***@***.***>
Sent: Tuesday, September 27, 2022 7:37 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Johnson, Gary R ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Webpage Update - New Lease Agreement XREF files for onrr.gov (Issue #2191)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@grjson<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgrjson&data=05%7C01%7Cgary.johnson%40onrr.gov%7C90b266eaaacc488a742f08daa08d7dfe%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637998826811966028%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=a0rQhWE07%2FWDNp8bYgT0uUJN7qqmhwfpv6IgzeuillU%3D&reserved=0>

Good morning,
These changes are on the dev site: http://2017onrr/reportpay/CrossRef.htm
Please review and give us your approval to go live.
Thanks,
Christine

**Comment by cthomasONRR** [comment]
@grjson 

Great, the changes are live: https://www.onrr.gov/reportpay/CrossRef.htm
Please remember to use "Ctrl+F5" to refresh the page.
Thanks,
Christine
