### ISSUE TITLE
Fort Duchesne, UT – Ute Outreach                                                           (To be added to Event Calendar)

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#2193]
Tuesday, October 18, 2022
9:00 am-12:00 pm MST

Location:  Ute Crossing Grill, 7491 Highway 40, Fort Duchesne, UT 84026

Description:  Representatives from the Office of Natural Resources Revenue will host an in-person Question and Answer session for Indian Mineral Owners and Trust Property Owners regarding their Indian Oil & Gas leases, IIM Accounts, and Indian Trust Properties. Representatives from the Bureau of Land Management, Bureau of Indian Affairs, and Bureau of Trust Funds Administration have been invited to be in attendance to answer questions
.
Who Should Attend:  IIM account holders, Indian mineral owners, and Indian trust property owners in the Fort Duchesne area in Utah.
 
Other Information:  If you have any questions regarding the in-person outreach, feel free to contact the ONRR Denver Outreach Office at (800) 982-3226. The ONRR Denver Outreach Office hours are Monday-Friday 7:30am-4:00pm.MST

Contact:  ONRR Denver Outreach Office, Toll Free (800) 982-3226,  Email: onrroutreachdenver@onrr.gov

SHAWNEE AREA VIRTUAL OUTREACH
Thursday, October 20, 2022 
1:00 PM– 2:00 PM CST

LOCATION: By Telephone

DESCRIPTION: Meeting will be a Call-in Meeting to hear a brief presentation and updates from the ONRR Outreach Office.  Representatives from each of the BLM, BTFA, and BIA will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust property issues, and agency updates.  Owners will have an opportunity to ask questions for the representatives of the four agencies during the Q&A session.

WHO SHOULD ATTEND: IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Shawnee Agency Area, Southern Plains region in Oklahoma. 

OTHER INFORMATION: To reserve a space and get the call-in number and passcode for this meeting you may contact the ONRR OKC Outreach office at (800) 354-7015. Office hours are Mon- Fri., 7:30 AM-4:30 PM CST. 

CONTACT: ONRR OKC Outreach Office, PHONE: (800) 354-7015 (toll-free)
EMAIL:  onrroutreachokc@onrr.gov

CONCHO AREA VIRTUAL MEETING
October 27, 2022
1:00 pm to 2:00 pm CST

Location:  By Telephone

DESCRIPTION: Meeting will be a Call-in Meeting to hear a brief presentation and updates from the ONRR Outreach Office.  Representatives from each of the BLM, BTFA, and BIA will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust property issues, and agency updates.  Owners will have an opportunity to ask questions for the representatives of the four agencies during the Q&A session.

WHO SHOULD ATTEND: IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Concho Agency Area, Southern Plains Region in Oklahoma. 

OTHER INFORMATION: To reserve a space and get the call-in number and passcode for this meeting you may contact the ONRR OKC Outreach office at (800) 354-7015. Office hours are Mon- Fri., 7:30 AM-4:30 PM CST. 

CONTACT: ONRR OKC Outreach Office, PHONE: (800) 354-7015 (toll-free)
EMAIL: onrroutreachokc@onrr.gov

**Comment by cthomasONRR** [comment]
@Toddsand21 

These changes are now on the dev site: http://2017onrr/events.htm
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by Toddsand21** [comment]
Can we put the toll free number for OK's 2 events all on the same line?

**Comment by Toddsand21** [comment]
Other than that I think its ready to go!

**Comment by cthomasONRR** [comment]
@Toddsand21 

Sure, how does this look: http://2017onrr/events.htm

Thanks
Christine

**Comment by cthomasONRR** [comment]
@Toddsand21

I incorporated your requested changes: http://2017onrr/events.htm
Do we have your approval to go live?

Thanks
Christine

**Comment by Toddsand21** [comment]
Yes it looks fine  and ready to go live.  

I have another issue but I have a few questions first.  My manager, Marvin Hamsher wants a statement posted either on the first main page or on the Allottee Assistance page (tab).  Where can it be posted?

**Comment by cthomasONRR** [comment]
@Toddsand21 

Great these changes are live: https://www.onrr.gov/events.htm

Maroya is going to contact you about your other question.

Thanks,
Christine

**Comment by Toddsand21** [comment]
Thanks You!
