### ISSUE TITLE
Attention Indian Mineral Owners

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#2194]
ONRR will no longer be providing estimates. Distribution estimates will be available the week of October 11th, however after this week ONRR will no longer be providing estimates for distributions. These will be the last estimates provided by ONRR. However, ONRR will still be available to answer any questions not related to estimates.

Question:  Can this go on the main first page or where?

**Comment by lpgoldstein** [comment]
@Toddsand21 This is ready for your review: http://2017onrr/
I edited it slightly for consistency.

**Comment by Toddsand21** [comment]
That looks fine and ready to post then.  Thanks!
