### ISSUE TITLE
External links are not opening in new tab 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2195]
I added videos to the youtube chanel and they open in the same tab

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/923a354f-6f29-4de8-ac59-3f82c4127ee5)

**Comment by cthomasONRR** [comment]
@Maroyafaied 

I think what you have to do is go to the Inline Link function and put the URL in the box next to "Create External Link". You think have to click on  "Create External Link" (It's not clear that it's a button), then click "Add". Then your link will open a new tab. I'm not sure if there's an easier way. This is the only way I know of.

**Comment by Maroyafaied** [comment]
@cthomasONRR You're awesome, thank you. That fixed it.
