### ISSUE TITLE
New file for onrr.gov

### ISSUE THREAD

**Issue by StaceyKaiser** [ONRR/onrr.gov-site#220]
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm called “Downloadable Text Cross-Reference Lease to Agreement Number” with the file entitled “July 2020 Lease Agreement XREF.txt”.  It was queried from the system on 7/6/2020.
[July 2020 Lease Agreement XREF.txt](https://github.com/ONRR/onrr.gov-site/files/4880452/July.2020.Lease.Agreement.XREF.txt)

**Comment by StaceyKaiser** [comment]
Our methodology says to send an email to the onrrweb@onrr.gov mailbox after we submit this change to GitHub.  Is the email necessary or should I amend our methodology to eliminate the email step?

**Comment by jennmalcolm** [comment]
That email is not necessary. Just submitting on GitHub is great. Thanks!

**Comment by Maroyafaied** [comment]
@StaceyKaiser please review the changes on the development site link below, if everything looks correct then I will push it to the live site. Thanks

 http://2017onrr/reportpay/CrossRef.htm

**Comment by StaceyKaiser** [comment]
@Maroyafaied the file on the development site looks good.  Thank you!

**Comment by Maroyafaied** [comment]
This is live now. Thanks
