### ISSUE TITLE
Update Jicarilla payment information

### ISSUE THREAD

**Issue by vcs5274** [ONRR/onrr.gov-site#2203]
![image](https://user-images.githubusercontent.com/69817636/194091083-0b3d0a9b-cf5d-40e7-96b1-aa4dd88641af.png)

When I click on Jicarilla it shows the information for MHA. MHA should say Electronic payment required. Contact Victoria Soto at ONRR-RFMASGL@onrr.gov for electronic payment instructions.

Please update Jicarilla to say Contact Victoria Soto at ONRR-RFMASGL@onrr.gov for payment instructions.

**Comment by lpgoldstein** [comment]
live so closing https://onrr.gov/reportpay/payments.htm
