### ISSUE TITLE
ONRR.gov Indian Gas Index Zone - October prices

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#2204]
The Indian Gas Index Zone October prices have been inputted into the "Data for ONRR.gov" spreadsheet and are ready for ONRR.gov site.

Thanks,
Cory Forgrave
@Sudarr

**Comment by forgravec** [comment]
The prices look good.

Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
***@***.***
________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, October 5, 2022 10:02 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Forgrave, Cory J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] ONRR.gov Indian Gas Index Zone - October prices (Issue #2204)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@forgravec<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fforgravec&data=05%7C01%7Ccory.forgrave%40onrr.gov%7Cc7e6a824d4d94245a66608daa6eaf9fc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638005825395227755%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JGNBKP%2FDPfOaFHWIfKktxYfs6kcDA4ZD55Mx5QwE7cM%3D&reserved=0>

Good morning,
The changes are in the dev site: http://2017onrr/valuation/allzones.htm
Please review and give us approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@forgravec 

Great! The changes are now live: https://www.onrr.gov/valuation/allzones.htm
Please use "Ctrl+F5" to refresh the page.

Thanks,
Christine
