### ISSUE TITLE
September 2022

### ISSUE THREAD

**Issue by damionschulte** [ONRR/onrr.gov-site#2205]
Can you please have the September Nymex prices published to the website?  Thanks 
[NYMEX092022.xlsx](https://github.com/ONRR/onrr.gov-site/files/9718422/NYMEX092022.xlsx)

**Comment by lpgoldstein** [comment]
@damionschulte ready for review http://2017onrr/valuation/NYMEX.htm

**Comment by lpgoldstein** [comment]
approved via teams chat. will close once live

**Comment by lpgoldstein** [comment]
Live so closing out the issue.

**Comment by damionschulte** [comment]
Oh my goodness.  I totally forgot to reply to you.  These look great! Thank you

From: lpgoldstein ***@***.***>
Sent: Wednesday, October 5, 2022 1:49 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] September 2022 (Issue #2205)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@damionschulte<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdamionschulte&data=05%7C01%7Cdamion.schulte%40onrr.gov%7Cea99b7e003884cc9d32b08daa70aadd9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638005961549292956%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nL5lY32AJqrmaqHXXT7dAFC4g63oE88thVkEwspj%2BWI%3D&reserved=0> ready for review http://2017onrr/valuation/NYMEX.htm

-
