### ISSUE TITLE
Offshore Production Contacts Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2209]
Please update the Offshore Production contact list on the following page - https://onrr.gov/about/contact.htm, with the attached file.

[RRM Offshore Production Contacts.pdf](https://github.com/ONRR/onrr.gov-site/files/9727515/RRM.Offshore.Production.Contacts.pdf)

Thank You
Jessica Bowlen

**Comment by lpgoldstein** [comment]
@bowlenj ready for your review http://2017onrr/about/contact.htm

**Comment by bowlenj** [comment]
Perfect, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: lpgoldstein ***@***.***>
Sent: Thursday, October 6, 2022 2:34 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Offshore Production Contacts Update (Issue #2209)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C7367fff8c23245b93ac608daa7da3626%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638006852903268207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RiHMK6Hj4pRgPWzU7kBjqHR8%2Bs1crxij0sV0cSTJoxM%3D&reserved=0> ready for your review http://2017onrr/about/contact.htm

**Comment by lpgoldstein** [comment]
@bowlenj live! https://onrr.gov/reportpay/PDFDocs/OffshoreProductionContacts.pdf
