### ISSUE TITLE
Update to Current Information Collection Requests: ICR 1012-0010 30-Day Notice

### ISSUE THREAD

**Issue by ajace81** [ONRR/onrr.gov-site#2211]
Hi Maroya and Christine,

ONRR's Information Collection Request (ICR) 1012-0010 30-Day Notice published in the Federal Register on September 16, 2022, and so we need to update the website accordingly.  

Can you please update the following link:

https://www.onrr.gov/Laws_R_D/FRNotices/ICR0120.htm

On this page, under "Federal Register Publications" and "ICR Docket Folder" please add:

"30-Day Agency Information Collection - (87 FR 56974--September 16, 2022)"  

The "(87 FR 56974 --September 16, 2022)" should hyperlink to the following Federal Register page:  https://www.federalregister.gov/documents/2022/09/16/2022-20013/agency-information-collection-activities-solid-minerals-and-geothermal-collections

This is my first GitHub request and so I hope it was not too confusing!  Please let me know if you have any questions.  Thanks!

Amanda Johnson

**Comment by cthomasONRR** [comment]
@ajace81 

Good morning,

For the FRN webpage (http://2017onrr/Laws_R_D/FRNotices/index.htm), there is usually more descriptor content. Here's one for an old ICR post:
![image](https://user-images.githubusercontent.com/72526208/194559670-9ffe5ebf-e5a3-4b1b-8429-177b3da7c672.png)
Could you please give me this same type of content for this new ICR posting?

Please feel free to chat me on Teams if my message is confusing.

Thanks,
Christine

**Comment by ajace81** [comment]
Sure, for the page (http://2017onrr/Laws_R_D/FRNotices/index.htm), please add:

"87 FR 56974
Friday, September 16, 2022
Denver, CO  In accordance with the Paperwork Reduction Act of ONRR is proposing to renew an information collection request. OMB Control Number 1012-0010. 

View 87 FR 59674 document"

Please hyperlink to https://www.federalregister.gov/documents/2022/09/16/2022-20013/agency-information-collection-activities-solid-minerals-and-geothermal-collections

**Comment by ajace81** [comment]
The other link you sent takes you to the general ICR page, which lists all the current ICRs.

**Comment by cthomasONRR** [comment]
@ajace81 

Thanks! These changes are now on the dev site for you to review:
FRN page: http://2017onrr/Laws_R_D/FRNotices/index.htm
ICR page: http://2017onrr/Laws_R_D/FRNotices/ICR0120.htm

Please review and give us your approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@ajace81 

I got approval from Amanda via Teams chat.
These changes are now live:
https://www.onrr.gov/Laws_R_D/FRNotices/index.htm
https://www.onrr.gov/Laws_R_D/FRNotices/ICR0120.htm

Please remember to use "Ctrl+F5" to refresh the page.

Thanks,
Christine
