### ISSUE TITLE
SME resume review 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2212]

**Comment by cthomasONRR** [comment]
@Maroyafaied I have all 19 rating sheets filled out and signed, and will send them to Amber on Monday

**Comment by cthomasONRR** [comment]
I emailed my 19 rating sheets to Amber. She is out of the office, doing training, all this week. I will follow up with her next week if I don't get a response.

**Comment by cthomasONRR** [comment]
Reopening because I got 11 more resumes to review.

**Comment by cthomasONRR** [comment]
I sent Amber the 11 rating sheets. I don't think I will get more resumes, but will keep this open until I hear back from her.

**Comment by cthomasONRR** [comment]
I got 5 more resumes to review

**Comment by cthomasONRR** [comment]
Third batch was the last of the resumes to review. Finished!
