### ISSUE TITLE
Add analytic for  download files

### ISSUE THREAD

**Issue by mojobnichols** [ONRR/onrr.gov-site#2213]

**Comment by mojobnichols** [comment]
@mojobnichols I forwarded an email from the DAP team about how page views are tracked using DAP. That might have something to do with why we're not seeing downloads or outbound links or documents clicked on.
DAP coding capabilities guide

Instructions from email:
Hello:

Thanks for your note. I see DAP firing on your staging server (see screenshot below). Your staging server using cloud.gov which won't show up in your profile in DAP, because it uses cloud.gov which lives in the GSA profile (see screenshot below). Your coding language will have downstream impacts on your ability to implement Google Analytics.

Vue.js (angular, etc.) is a dynamic coding language that does not use page views for most functionality - these are referred to as Single Page Apps and Progressive Web Apps.

Single page applications (SPAs) really mess with the way Google Analytics works, since Google Analytics is mostly dependent on page loads to re-initiate the javascript file. So, a SPA with no alterations made for GA only has a full pageload once, and all the other content loads are done dynamically, without an HTML refresh. You'll need to implement virtual pageviews, which tell GA that a new pageview has happened.

I'm attaching documentation from our Github - Please see page 18 for virtual pageviews. I'm also including high level documentation from Google on SPA's. Please request your developer to review and you'll need to instruct them to develop virtual pageviews.

**Comment by Maroyafaied** [comment]
@R-mohansai here is a list of all the collections, I believe that the previous developer started adding the code to the press releases but the analytics weren't showing the title of them.

**Comment by Maroyafaied** [comment]
@R-mohansai  This is the folder where you will need to implement the code fore each collection: frontend/src/components/collections

The previous developer started adding code to the press release collection: frontend/src/components/collections/PressReleases.vue

These are the links to the code to his last comitts
https://github.com/ONRR/onrr.gov-site/commit/9cdf891493c6d1648ab0e0fbcb8de72f1c073422
https://github.com/ONRR/onrr.gov-site/commit/334fcdd21ff94052b1734aa9cb1d6d835b931690
https://github.com/ONRR/onrr.gov-site/commit/dbaadfd1c1d7a642c2bbaf3eaa7eefe5d7fc5117

When I checked the Aanalytics after Mojo's code, I was able to see downloads showing up but they weren't labeled correctly. ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/60aa5ba1-f846-4318-aecf-bed7d9103b33)

This is how the downloads are showing in the current website with the correct labeling ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/75eb2a5a-dc45-4bae-a012-e70b1924829b)

**Comment by Maroyafaied** [comment]
![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/94a80690-306f-42f9-ac5b-c535a281d979)

**Comment by Maroyafaied** [comment]
@R-mohansai please resend your email to dap@gsa.gov.  You sent it to dap@support.digital.gov is no longer in service, you should've gotten an error message when you sent the first email. Thanks

**Comment by R-mohansai** [comment]
@Maroyafaied I got response from DAP as duplicate request I think they have considered the old ticket which I sent to other email i.e([dap@support.digital.gov]-->as seen in DAP registration form.

**Comment by Maroyafaied** [comment]
@R-mohansai @greensomes I came across this link so I'm sharing incase it's helpful. https://developers.google.com/analytics/devguides/migration/ua/analyticsjs-to-gtagjs
