### ISSUE TITLE
September IBMP Prices

### ISSUE THREAD

**Issue by damionschulte** [ONRR/onrr.gov-site#2214]
All, I have update the Data for ONRR sheet on the one drive and attached the specified formatted sheet with the September 2022 IBMP Prices.  Can you please have them posted to the website?  Please let me know if you need anything else.  Thanks

@sudarr
[September 22 IBMP For GitHub.xlsx](https://github.com/ONRR/onrr.gov-site/files/9758669/September.22.IBMP.For.GitHub.xlsx)

**Comment by lpgoldstein** [comment]
@damionschulte ready for your review http://2017onrr/valuation/IndianOilIBMP.htm

**Comment by damionschulte** [comment]
Prices are good.  Thank you all so much.

From: lpgoldstein ***@***.***>
Sent: Tuesday, October 11, 2022 2:26 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] September IBMP Prices (Issue #2214)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@damionschulte<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdamionschulte&data=05%7C01%7Cdamion.schulte%40onrr.gov%7C4285d03b682e4781dc0708daabc6c8e7%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638011167508352078%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=k29w2eUo8QTeZ6ZWkhmjfG7JclpQPfuCKTrnhetqcCg%3D&reserved=0> ready for your review http://2017onrr/valuation/IndianOilIBMP.htm

-

**Comment by lpgoldstein** [comment]
@damionschulte live! https://onrr.gov/valuation/IndianOilIBMP.htm

**Comment by damionschulte** [comment]
Amazing!  Thank you so much.

From: lpgoldstein ***@***.***>
Sent: Tuesday, October 11, 2022 3:16 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] September IBMP Prices (Issue #2214)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@damionschulte<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdamionschulte&data=05%7C01%7Cdamion.schulte%40onrr.gov%7C1fbb10cd26cb4e9e285708daabcdc810%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638011197561572795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zAUK5NSLd%2BRY72Tals4J3FhrJ%2BD8kfMpKbp%2FH%2FF36pM%3D&reserved=0> live! https://onrr.gov/valuation/IndianOilIBMP.htm<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fonrr.gov%2Fvaluation%2FIndianOilIBMP.htm&data=05%7C01%7Cdamion.schulte%40onrr.gov%7C1fbb10cd26cb4e9e285708daabcdc810%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638011197561729466%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=V7p6H6r3IEa%2B0n7V0zkIrRJB7eFmjb88ntB4zr3hgxU%3D&reserved=0>

-
