### ISSUE TITLE
Update contacts for Accounts Receivable and Billing Federal

### ISSUE THREAD

**Issue by hoffmanb12** [ONRR/onrr.gov-site#2218]
Please use the attached file to replace the Accounts Receivable and Billing Federal contacts.  The contact information is located near the bottom of the Payments page.

https://www.onrr.gov/ReportPay/payments.htm

Contacts
Accounts Receivable and Billing
[Accounts Receivable, Billing, and Financial Issues Information -- Federal](https://www.onrr.gov/reportpay/PDFDocs/FSFederalCOAssignm.docx)

Thank you,

Brian Hoffman

[FSFederalCOAssignm.docx](https://github.com/ONRR/onrr.gov-site/files/9780216/FSFederalCOAssignm.docx)

**Comment by Maroyafaied** [comment]
@hoffmanb12 Thank you for submitting a request, I've assigned @cthomasONRR to work on this, please note that we are very short staffed and this request might not be completed until early next week as we have other high priority tasks. Thanks!

**Comment by cthomasONRR** [comment]
@hoffmanb12 

This document is updated on the dev site: http://2017onrr/reportpay/payments.htm
Please review and give us approval to go live.

**Also, could you please send me a version of this doc with the changes highlighted? I need that help to update the new website's contact list.**

Thanks,
Christine

**Comment by hoffmanb12** [comment]
Christine,

I have reviewed the changes and the updates look good.

I have also attached the file with highlighted changes per your request.

Regards,

Brian Hoffman
Staff Accountant, Financial Services
Revenue, Report and Compliance Management
Office of Natural Resources Revenue
Department of the Interior
P:  303.231.3235

From: Christine Thomas ***@***.***>
Sent: Friday, October 14, 2022 6:57 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Hoffman, Brian R ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update contacts for Accounts Receivable and Billing Federal (Issue #2218)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@hoffmanb12<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhoffmanb12&data=05%7C01%7Cbrian.hoffman%40onrr.gov%7Ccf86a25a425940f8e79e08daade3dc8e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638013491418448942%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LsVUlaKIrRRisRaznlEX1GsJa%2BG%2B6ze%2By31zBXW6F%2Fg%3D&reserved=0>

This document is updated on the dev site: http://2017onrr/reportpay/payments.htm
Please review and give us approval to go live.

Also, could you please send me a version of this doc with the changes highlighted? I need that help to update the new website's contact list.

Thanks,
Christine

-

**Comment by cthomasONRR** [comment]
@hoffmanb12 

Thank you!

These changes are now live: https://www.onrr.gov/reportpay/payments.htm
Please remember to use "Ctrl+F5" to refresh the page.

Christine
