### ISSUE TITLE
Royalty Reporting and Error Corrections Contact Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2219]
Please remove the Royalty Reporting and Error Corrections contact page located here - https://www.onrr.gov/about/contact.htm.

Please replace that contact sheet with the 2 attached, one for Indian and one for Federal.

[Federal Royalty Reporting Contacts.pdf](https://github.com/ONRR/onrr.gov-site/files/9780540/Federal.Royalty.Reporting.Contacts.pdf)
[Indian Royalty Assignments.pdf](https://github.com/ONRR/onrr.gov-site/files/9780541/Indian.Royalty.Assignments.pdf)

**Comment by Maroyafaied** [comment]
@bowlenj Thank you for submitting a request, I've assigned @cthomasONRR to work on this, please note that we are very short staffed and this request might not be completed until early next week as we have other high priority tasks. Thanks!

**Comment by cthomasONRR** [comment]
@bowlenj 

Could you please list all the webpages that need to be updated with the 2 new links?

**Comment by cthomasONRR** [comment]
@bowlenj 

Thanks,
This update is now on the dev site: http://2017onrr/about/contact.htm
Please review and give us approval to go live.

We'll discuss getting this big structure change/update in the new CMS with you... I believe there's a spreadsheet that will be sent to us. Feel free to chat me to discuss. 

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj 

These changes are now live: 
https://www.onrr.gov/about/contact.htm

Please remember to use "Ctrl+F5" to refresh the page.

We'll update the new website with these changes once we receive that spreadsheet we discussed.

Thanks for your patience!
Christine
