### ISSUE TITLE
Web Page-Federal Onshore Terminable Leases

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#222]
Please updated the following webpage http://www.onrr.gov/ReportPay/royalty-reporting.htm with the attached PDF file:
Federal Onshore Terminable leases-sorted by Due Date. Also update to 07/01/2020.

Thank you

[FLTerm.pdf](https://github.com/ONRR/onrr.gov-site/files/4880647/FLTerm.pdf)

**Comment by lpgoldstein** [comment]
@merrellc this is ready for your review: http://2017onrr/ReportPay/royalty-reporting.htm

**Comment by merrellc** [comment]
Reviewed and ready to go.




Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________

**Comment by lpgoldstein** [comment]
@merrellc it's live!
