### ISSUE TITLE
Lease/Agreement Maintenance Contacts Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2220]
Please replace the Lease/Agreement Maintenance Contacts sheet on this page - https://www.onrr.gov/reportpay/PDFDocs/RS_LeAgAssignments.pdf, with the updated attachement.

[Reference Contact List Template_10-5-22.pdf](https://github.com/ONRR/onrr.gov-site/files/9780689/Reference.Contact.List.Template_10-5-22.pdf)

Thank you
Jessica

**Comment by Maroyafaied** [comment]
@bowlenj Thank you for submitting a request, I've assigned @cthomasONRR to work on this, please note that we are very short staffed and this request might not be completed until early next week as we have other high priority tasks. Thanks!

**Comment by cthomasONRR** [comment]
@bowlenj

This document is updated on the dev site: http://2017onrr/reportpay/PDFDocs/RS_LeAgAssignments.pdf
Please review and give us approval to go live.

Also, could you please send me a version of this doc with the changes highlighted? I need that help to update the new website's contact list.

Thanks,
Christine

**Comment by bowlenj** [comment]
Looks GREAT!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Friday, October 14, 2022 6:52 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Lease/Agreement Maintenance Contacts Update (Issue #2220)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C3550c48034784b5510e708daade330d7%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638013488534513889%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=g9rcap90GDdfDqXL3rdHoFXHSOm1BxQdqcCoWbxz4ak%3D&reserved=0>

This document is updated on the dev site: http://2017onrr/reportpay/PDFDocs/RS_LeAgAssignments.pdf
Please review and give us approval to go live.

Also, could you please send me a version of this doc with the changes highlighted? I need that help to update the new website's contact list.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj

Could you please send me a version of this doc with the changes highlighted? I need that help to update the new website's contact list.

**Comment by bowlenj** [comment]
Hi Christine,

Attached is the Lease/Agreement contacts with the changes highlighted.  I highlighted the state for the ones that someone was removed!  Please let me know if you have any questions.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Friday, October 14, 2022 7:15 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Lease/Agreement Maintenance Contacts Update (Issue #2220)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cc233a487e0ff4ba33f6608daade6506d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638013502397732395%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4Bx9GVDa1iuhshM3ERverWD3wHWn5qSTlQO1eKzR6PM%3D&reserved=0>

Could you please send me a version of this doc with the changes highlighted? I need that help to update the new website's contact list.

**Comment by cthomasONRR** [comment]
@bowlenj 

These changes are now live: https://www.onrr.gov/about/contact.htm

We'll update the new website with these changes once we receive that spreadsheet we discussed.

Thanks for your patience!
Christine
