### ISSUE TITLE
Onshore Production Contacts Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2221]
Please remove the Onshore Production Contacts page located here - https://www.onrr.gov/reportpay/PDFDocs/OnshoreProductionContacts.pdf

Please replace this contact sheet with the 2 attached contact pages, one for Indian and one for Federal.

[Federal Onshore Production Assignments.pdf](https://github.com/ONRR/onrr.gov-site/files/9780823/Federal.Onshore.Production.Assignments.pdf)
[Indian Onshore Production Assignments.pdf](https://github.com/ONRR/onrr.gov-site/files/9780824/Indian.Onshore.Production.Assignments.pdf)

Thank You!

**Comment by Maroyafaied** [comment]
@bowlenj Thank you for submitting a request, I've assigned @cthomasONRR to work on this, please note that we are very short staffed and this request might not be completed until early next week as we have other high priority tasks. Thanks!

**Comment by cthomasONRR** [comment]
@bowlenj 

Could you please list all the webpages that need to be updated with the 2 new links?

**Comment by bowlenj** [comment]
Good Morning Christine,

There appears to be a link to the Onshore Production Contacts and Offshore Production Contacts here under Reporter Tools - New Royalty Reporter Checklist (onrr.gov)<https://www.onrr.gov/reportpay/roy-checklist.htm>
New Royalty Reporter Checklist - Office of Natural Resources Revenue<https://www.onrr.gov/reportpay/roy-checklist.htm>
Perform the following tasks to assure your company is set up to report and remit rental and royalties for Federal and Indian leases/agreements correctly and timely.. Have ONRR assign a Payor Code to your company. To obtain your ONRR Payor Number, to set up electronic reporting, and to receive an explanation of reporting requirements, email both contacts listed below:
www.onrr.gov
[cid:94e4f187-7033-4259-8608-0ef8e5456e95]

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Friday, October 14, 2022 6:57 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Onshore Production Contacts Update (Issue #2221)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C164135ee682948f5e90608daade3de79%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638013491445813902%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jshGcIz2Rz5dtCVK9fJB4Y7daOB07MrRp0x4d0gWirg%3D&reserved=0>

Could you please list all the webpages that need to be updated with the 2 new links?

**Comment by bowlenj** [comment]
They look great!  I approve to go Live 🙂

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Friday, October 14, 2022 8:11 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Onshore Production Contacts Update (Issue #2221)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cfc088a6edd5543c1af6408daadee255c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638013536036230987%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qle8jq98QKtt9R6zhDY2%2FK8xEAyM6Npt0EOKIZt%2BlDg%3D&reserved=0>

Thanks,
This update is now on the dev site:
http://2017onrr/about/contact.htm
http://2017onrr/reportpay/roy-checklist.htm
Please review and give us approval to go live.

We'll discuss getting this big structure change/update in the new CMS with you... I believe there's a spreadsheet that will be sent to us. Feel free to chat me to discuss.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj 

These changes are now live: 
https://www.onrr.gov/about/contact.htm
https://www.onrr.gov/reportpay/roy-checklist.htm

Please remember to use "Ctrl+F5" to refresh the page.

We'll update the new website with these changes once we receive that spreadsheet we discussed.

Thanks for your patience!
Christine
