### ISSUE TITLE
Offshore Production Contact Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2222]
Please replace the Offshore Production Contact List here - https://www.onrr.gov/reportpay/PDFDocs/OffshoreProductionContacts.pdf, with the attached document.

[Offshore Production Contacts.pdf](https://github.com/ONRR/onrr.gov-site/files/9780899/Offshore.Production.Contacts.pdf)

Thank You!

**Comment by Maroyafaied** [comment]
@bowlenj Thank you for submitting a request, I've assigned @cthomasONRR to work on this, please note that we are very short staffed and this request might not be completed until early next week as we have other high priority tasks. Thanks!

**Comment by cthomasONRR** [comment]
@bowlenj 

This document is updated on the dev site: http://2017onrr/reportpay/PDFDocs/OffshoreProductionContacts.pdf
Please review and give us approval to go live.

Also, could you please send me a version of this doc with the changes highlighted? I need that help to update the new website's contact list.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj 

Could you please send me a version of this doc with the changes highlighted? I need that help to update the new website's contact list.

**Comment by cthomasONRR** [comment]
@bowlenj 

Thanks so much! It doesn't look like I need to change anything on our new website then. Did you outline the changes from last Friday to whoever took that issue?
