### ISSUE TITLE
Add vdp page on current website 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2225]

**Comment by Maroyafaied** [comment]
@cthomasONRR Please review http://2017onrr/VDP.htm . There's two places that I couldn't link to an email address so I put it in parenthesis.

**Comment by cthomasONRR** [comment]
@Maroyafaied The text looks good.

My only question is that where I have "Disclaimer" highlighted in yellow in the image below, should this instead say "VDP" or "Vulnerability Disclosure Policy"?

![image](https://user-images.githubusercontent.com/72526208/196950029-bc2a963b-8b5f-462e-aa7c-1292ea601636.png)

Other than that, I think it's good to link!

**Comment by Maroyafaied** [comment]
@cthomasONRR I tried to change that and didn't find a way. I'll look into it some more later today.
