### ISSUE TITLE
Updated Documents ready for posting on ONRR.gov

### ISSUE THREAD

**Issue by NSweeneyonrr** [ONRR/onrr.gov-site#2226]
Please replace documents located on onrr.gov with the attached, updated versions as follows:

Under "Reporting/Paying" ->"Royalty Reporting" the section titled 'Reporting Codes for Form ONRR-2014'  the documents "Form ONRR-2014 Codes" and "Data Elements by Transaction Code." 
[Form ONRR-2014 Codes.pdf](https://github.com/ONRR/onrr.gov-site/files/9814856/Form.ONRR-2014.Codes.pdf)
[Data Elements by Transaction Code.pdf](https://github.com/ONRR/onrr.gov-site/files/9814859/Data.Elements.by.Transaction.Code.pdf)

**Comment by cthomasONRR** [comment]
@NSweeneyonrr 

Hello, 

I checked these 2 documents with the Adobe Accessibility Checker. They both failed due to issues with the table summaries. Please fix these table summaries and then we can post these documents.

![image](https://user-images.githubusercontent.com/72526208/196539318-f7128cc3-f809-4b39-bf38-f403a39042a0.png)

Thanks,
Christine

**Comment by NSweeneyonrr** [comment]
Hello, 

Updated both documents to add table summaries.  Please see attached.

Thanks, 
Nicole

[Form ONRR-2014 Codes V3.pdf](https://github.com/ONRR/onrr.gov-site/files/9820452/Form.ONRR-2014.Codes.V3.pdf)

[Data Elements by Transaction Code_V2.pdf](https://github.com/ONRR/onrr.gov-site/files/9820454/Data.Elements.by.Transaction.Code_V2.pdf)

**Comment by cthomasONRR** [comment]
@NSweeneyonrr 

Good morning!

Thank you so much for making these docs compliant!
These updates are on the dev site: http://2017onrr/reportpay/royalty-reporting.htm

Please review and give us your approval to go live.

Thanks!
Christine

**Comment by NSweeneyonrr** [comment]
Good Morning, 

I've reviewed on the dev site and everything looks good. I approve for this to go live.

Thank you so much!
Nicole

**Comment by cthomasONRR** [comment]
@NSweeneyonrr 

Great! 
These changes are now live: https://www.onrr.gov/reportpay/royalty-reporting.htm
Please use "Ctrl+F5" to refresh the page.

Thanks,
Christine
