### ISSUE TITLE
remove calendar

### ISSUE THREAD

**Issue by bakercook** [ONRR/onrr.gov-site#2227]
Please remove 2021 calendar under Allottee Assistance
[2021 calendar.docx](https://github.com/ONRR/onrr.gov-site/files/9820673/2021.calendar.docx)

**Comment by cthomasONRR** [comment]
@bakercook 

Do you mean the "Indian Distribution Dates for Calendar Year 2021" PDF?
http://2017onrr/IndianServices/index.htm
![image](https://user-images.githubusercontent.com/72526208/196700894-7e88b574-a21a-462b-a08b-a82d3ece6149.png)

Thanks,
Christine

**Comment by bakercook** [comment]
Yes.

**Comment by cthomasONRR** [comment]
@bakercook 

Thanks for clarifying.
These changes are now on the dev site: http://2017onrr/IndianServices/index.htm
Please review and give us approval to go live.

Thanks
Christine

**Comment by bakercook** [comment]
Looks good. Thank you.

**Comment by cthomasONRR** [comment]
@bakercook 

Great! 
This change is now live: https://www.onrr.gov/IndianServices/index.htm
Please use "Ctrl+F5" to refresh the page.

Thanks,
Christine
