### ISSUE TITLE
Onshore Production Reporting Contacts

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2228]
Please update the following webpages with the attached updated Onshore Production Reporting contact list:
https://www.onrr.gov/reportpay/PDFDocs/OnshoreProductionContacts.pdf
https://www.onrr.gov/reportpay/PDFDocs/Federal.Onshore.Production.Assignments.pdf

Thank You
Jessica

[Federal Onshore Production Assignments.pdf](https://github.com/ONRR/onrr.gov-site/files/9821715/Federal.Onshore.Production.Assignments.pdf)

**Comment by cthomasONRR** [comment]
@bowlenj 

Could you please give me more information:

- Which webpages need to be updated? 
- I see the "OnshoreProductionContacts.pdf" here: http://2017onrr/reportpay/production-reporting.htm and here: http://2017onrr/reportpay/royalty-reporting.htm.  Do you want me to replace the "OnshoreProductionContacts.pdf" on these two webpages with the new "Federal Onshore Production Assignments.pdf"?
- On http://2017onrr/about/contact.htm, do you want me to replace the current "Federal.Onshore.Production.Assignments.pdf" the the new "Federal Onshore Production Assignments.pdf"?

Thanks,
Christine

**Comment by bowlenj** [comment]
Hi Christine,

I'm sorry I thought I provided the webpages to update.  Yes, please update the 3 pages you identified below.  Thank you!

We found some changes to the one you updated and I think I missed a page before for the update.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, October 19, 2022 9:24 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Onshore Production Reporting Contacts (Issue #2228)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Ce4514f58a73d45d1e96b08dab1e61247%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638017898952542555%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FP1x7YI531oSFUUJ1M9t4T93lWp2GtXx%2B8qNFT4NRtU%3D&reserved=0>

Could you please give me more information:

  *   Which webpages need to be updated?
  *   I see the "OnshoreProductionContacts.pdf" here: http://2017onrr/reportpay/production-reporting.htm and here: http://2017onrr/reportpay/royalty-reporting.htm. Do you want me to replace the "OnshoreProductionContacts.pdf" on these two webpages with the new "Federal Onshore Production Assignments.pdf"?
  *   On http://2017onrr/about/contact.htm, do you want me to replace the current "Federal.Onshore.Production.Assignments.pdf" the the new "Federal Onshore Production Assignments.pdf"?

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj 

Thanks for clarifying.
I just checked the new PDF for accessibility, and it failed the Adobe Accessibility Checks.
Could you please make the document accessible and resend it?

Thanks,
Christine

![image](https://user-images.githubusercontent.com/72526208/196736602-1fcab15b-858e-4b0d-8550-bc77caf9eb62.png)

**Comment by bowlenj** [comment]
Hi Christine,

I'm so sorry about that, I completely forgot to redo the 508 after I made the changes needed.

I've attached the corrected document and verified the 508 compliance.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, October 19, 2022 9:30 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Onshore Production Reporting Contacts (Issue #2228)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C6b22e61202564640494708dab1e717fd%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638017903377897688%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=KQRj99DP4ltpLgYOOQtl%2FVqUtV3qdNejDBasu%2BCh5FI%3D&reserved=0>

Thanks for clarifying.
I just checked the new PDF for accessibility, and it failed the Adobe Accessibility Checks.
Could you please make the document accessible and resend it?

Thanks,
Christine

[image]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F72526208%2F196736602-1fcab15b-858e-4b0d-8550-bc77caf9eb62.png&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C6b22e61202564640494708dab1e717fd%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638017903377897688%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=dQ430NQHc1Wk3Ft6D%2Fz5cvwgd3h2l9Ao9iAcm2xcMgU%3D&reserved=0>

**Comment by cthomasONRR** [comment]
@bowlenj 

Great!
These updates are now on the dev site:
http://2017onrr/reportpay/production-reporting.htm
http://2017onrr/reportpay/royalty-reporting.htm
http://2017onrr/about/contact.htm

Please review and give us approval to go live.

Thanks,
Christine

**Comment by bowlenj** [comment]
They're all perfect, thank you!  Approved for Live 🙂

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, October 19, 2022 12:43 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Onshore Production Reporting Contacts (Issue #2228)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Ca1b35e17f06e4eaa377e08dab201cd0a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638018018052654757%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=w8F7YHd3PAgulhkC%2FMO7ni%2Bb5%2FGK6pzW9lAH14lRXNE%3D&reserved=0>

Great!
These updates are now on the dev site:
http://2017onrr/reportpay/production-reporting.htm
http://2017onrr/reportpay/royalty-reporting.htm
http://2017onrr/about/contact.htm

Please review and give us approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj 

Great, these changes are now live:
https://www.onrr.gov/reportpay/production-reporting.htm
https://www.onrr.gov/reportpay/royalty-reporting.htm
https://www.onrr.gov/about/contact.htm

Please remember to use "Ctrl+F5" to refresh the page.

Also note: we will update the new onrr.gov site with these contact changes once we receive that spreadsheet we discussed last week.

Thanks,
Christine
