### ISSUE TITLE
Federal Onshore Production Contacts

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2229]
I found another page where the production contacts need to be updated.  Please update this webpage - https://www.onrr.gov/reportpay/PDFDocs/OnshoreProductionContacts.pdf, with the attached list.

Thank You
Jessica

[Federal Onshore Production Assignments.pdf](https://github.com/ONRR/onrr.gov-site/files/9824164/Federal.Onshore.Production.Assignments.pdf)

**Comment by cthomasONRR** [comment]
@bowlenj 

In the future, please add the website url, not the pdf url, so I know where to make this update.

The changes are now on the dev site: http://2017onrr/reportpay/contacts.htm
Please review, and give us your approval to go live.

Thanks,
Christine

**Comment by bowlenj** [comment]
Thank you, that's good to know!  I'll do that in the future.  The update looks great and is approved for live!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, October 19, 2022 2:54 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Federal Onshore Production Contacts (Issue #2229)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C4b0dfd85bf604964502808dab2142494%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638018096827173970%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EA6umBNAccPnQ68dDxmlgGQq8%2FNe1XsqtqegUWvl%2Bnk%3D&reserved=0>

In the future, please add the website url, not the pdf url, so I know where to make this update.

The changes are now on the dev site: http://2017onrr/reportpay/contacts.htm
Please review, and give us your approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj 

Great, these changes are now live: https://onrr.gov/reportpay/contacts.htm
Please user "Ctrl+F5" to refresh the page.

Note: We will update the contacts on the new site when we get that excel sheet that we discussed last week.

Thanks,
Christine
