### ISSUE TITLE
Add technical overview page on wiki 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2231]
Jerome will help draft a technical overview of technology used for the new onrr.gov website.

**Comment by Maroyafaied** [comment]
I will send you the documents. @lpgoldstein please show @eelzi-ONRR how to update the wiki.

**Comment by Maroyafaied** [comment]
@lpgoldstein @eelzi-ONRR Please add the [Contributing to Code](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/NRRD/Contributing%20to%20Code.docx?d=wad581224714844b5a6aabc0a3f5e6fd3&csf=1&web=1&e=Vf4We1) doc to the NRRD's wiki under the  Development sections. Also, please create a section called 'Development" in onrr.gov wiki and  add the  [Technical Overview](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Technical%20overview.docx?d=wce223e3fce3f4ee59dc19a0acb14572a&csf=1&web=1&e=ai9Dm2) . Thanks

**Comment by eelzi-ONRR** [comment]
@lpgoldstein these are ready for you to review

[https://github.com/ONRR/nrrd/wiki/Contributing-to-code](https://github.com/ONRR/nrrd/wiki/Contributing-to-code)

[https://github.com/ONRR/onrr.gov-site/wiki/Technical-overview](https://github.com/ONRR/onrr.gov-site/wiki/Technical-overview)

**Comment by lpgoldstein** [comment]
@eelzi-ONRR Looks good! I made a few edits and fixed a link. @Maroyafaied is the spotify reference a joke? -->Under frontend dev apps - [Spotify](https://open.spotify.com/) - All the music you'll ever need

**Comment by Maroyafaied** [comment]
@lpgoldstein lol yes, that's @jlouis-onrr sense of humor so I left it :)
