### ISSUE TITLE
Update to Federal Royalty Contacts

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2232]
Please replace the Federal Royalty Reporting contact lists on the below webpages with the attached list and add the Indian Royalty Reporting contact list (also attached) to the 2 sites indicated below:

https://www.onrr.gov/about/contact.htm - replace Federal Royalty Reporting
https://www.onrr.gov/reportpay/royalty-reporting.htm#contacts - replace Federal and add Indian Royalty Reporting also
https://www.onrr.gov/reportpay/royalty-reporting.htm - replace Federal and add Indian Royalty Reporting also

Thank you,
Jessica

[Federal Royalty Reporting Assignments.pdf](https://github.com/ONRR/onrr.gov-site/files/9830091/Federal.Royalty.Reporting.Assignments.pdf)
[Indian Royalty Assignments.pdf](https://github.com/ONRR/onrr.gov-site/files/9830092/Indian.Royalty.Assignments.pdf)

**Comment by cthomasONRR** [comment]
@bowlenj 

Could you please clarify the web locations?

- https://www.onrr.gov/reportpay/royalty-reporting.htm#contacts A this location, I do not see any links for royalty reporting contacts. Do you want me to add them somewhere?
- https://www.onrr.gov/reportpay/royalty-reporting.htm This location links me to the same location as the URL in the bullet above.

**Comment by cthomasONRR** [comment]
@bowlenj 

I think  I have these locations updated:

- http://2017onrr/reportpay/royalty-reporting.htm  (in the right-side blue contacts box)
- http://2017onrr/about/contact.htm

Please let me know if there are any other locations that you would like updated.

Thanks,
Christine

**Comment by bowlenj** [comment]
The 2 you updated look great and are approved.  I still don't see this one updated - Royalty Reporting (except Solid Minerals) (onrr.gov)<https://www.onrr.gov/reportpay/royalty-reporting.htm#contacts>.  I did the refresh in both chrome and edge but I'm still not seeing the udpate.
Royalty Reporting (except Solid Minerals) - Office of Natural Resources Revenue<https://www.onrr.gov/reportpay/royalty-reporting.htm#contacts>
It's Secure. This site is protected by a Secure Sockets Layer (SSL) Certificate authorized through the United States Government. The https:// means all transmitted data is encrypted - in other words, any information or browsing history that you provide is transmitted securely.
www.onrr.gov



Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning, and Coordination
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, October 20, 2022 7:03 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update to Federal Royalty Contacts (Issue #2232)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cf65e3f7b0f904efb506408dab29b7b12%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638018678111747850%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oCKcjdjbOVCtBwTJHfJhoXwyCZnXv089A%2FLnEcWPQp4%3D&reserved=0>

I think I have these locations updated:

  *   http://2017onrr/reportpay/royalty-reporting.htm (in the right-side blue contacts box)
  *   http://2017onrr/about/contact.htm

Please let me know if there are any other locations that you would like updated.

Thanks,
Christine

**Comment by bowlenj** [comment]
All locations have been updated and look great!  Approved to push to Live.


Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning, and Coordination
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, October 20, 2022 7:03 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update to Federal Royalty Contacts (Issue #2232)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cf65e3f7b0f904efb506408dab29b7b12%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638018678111747850%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oCKcjdjbOVCtBwTJHfJhoXwyCZnXv089A%2FLnEcWPQp4%3D&reserved=0>

I think I have these locations updated:

  *   http://2017onrr/reportpay/royalty-reporting.htm (in the right-side blue contacts box)
  *   http://2017onrr/about/contact.htm

Please let me know if there are any other locations that you would like updated.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj 

Great, these changes are now live: 
https://www.onrr.gov/reportpay/royalty-reporting.htm
https://www.onrr.gov/about/contact.htm

Please use "Ctrl+F5" to refresh the page.

Note: Contact updates will be made in the new onrr.gov site once we receive the spreadsheet we discussed last week.

Thanks,
Christine
