### ISSUE TITLE
Create image folders and save images for new RV examples

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#2235]
We need to:

- [ ]  Create individual image folders for each RV example. 
- [ ]  Save the examples images to the appropriate folder.
- [ ]  Maintain a clear naming scheme for all images.

One example is already complete.
Use this image folder as a guide for appropriate image naming scheme.
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/8cccbfd1-74ae-4da9-bbc0-e2717f86e57d)

We can do a separate issue for image tagging and developing good alt text.

**Comment by cthomasONRR** [comment]
@eelzi-ONRR I created file folders for each example. Let me know if you want to set up a meeting to go over saving/adding images to the folders.

![image](https://user-images.githubusercontent.com/72526208/197580685-b3fbe140-1319-4f96-8a69-a0d16cd7f4ff.png)

**Comment by cthomasONRR** [comment]
@eelzi-ONRR I checked the "2_RPMP-Act" image folder and it looks great! Please feel free to do the other examples. Let me know if you want me to do a few as well. Thanks!

**Comment by eelzi-ONRR** [comment]
@cthomasONRR I've finished up all the images and it's ready for you to review

**Comment by cthomasONRR** [comment]
@eelzi-ONRR 

Examples 3-5 look great! 

In example "6_MinNGL" in the "Scenarios" section, there are 3 images at the end of the example that need to be added:

![image](https://user-images.githubusercontent.com/72526208/199088789-4d829331-68f2-4c68-ac23-87aac0dd3033.png)
![image](https://user-images.githubusercontent.com/72526208/199088825-626a8806-6f4d-43fd-9065-b0695626b8b8.png)
![image](https://user-images.githubusercontent.com/72526208/199088858-3485cfcf-56d9-4d77-ac11-d0b8c1971d71.png)

Once these 3 images are added, you can close this issue. Thanks!!!

**Comment by cthomasONRR** [comment]
We also need to look into the plant statements, but since some examples don't even have them attached, we can do that under a different issue.

I think we need to change the image color contrast on the plant statements. I remember there something being wrong with the blue they are using for the letter indicators. (See the MinNGL plant statement for an example of this)
