### ISSUE TITLE
Update Payment page with new contact information

### ISSUE THREAD

**Issue by vcs5274** [ONRR/onrr.gov-site#2239]
**Please read the directions below before submitting your issue:**

Please reference the following wiki to make sure you format your issue correctly: https://github.com/ONRR/onrr.gov-site/wiki/Using-github

**If your request is to update existing document(s), PLEASE**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name

**If your request is to add new content, PLEASE**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Give the exact language that needs to be added
* Give us the hyperlink with the exact language that should go to that hyperlink url (if applicable) 

THANK YOU

______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**

Please update the payment page. Under Payments please update the contact information to General Ledger Team onrr-rfrmasgl@onrr.gov.

https://www.onrr.gov/reportpay/payments.htm

**Comment by cthomasONRR** [comment]
@vcs5274
On the payments webpage, there are multiple contacts (pictured below)
Which contacts do you want updated?

![image](https://user-images.githubusercontent.com/72526208/197865906-d27e6ee8-8dc3-431c-896b-1c060ee80b68.png)

**Comment by vcs5274** [comment]
Hello,

Under Payments Gary Brunette and Soukanay Phommachally.

I want to remove the contact names and phone numbers and replace them with General Ledger Team and the group email address ***@***.***


Respectfully,

Victoria Soto, Supervisory Accountant (she/her/hers)
Accounting Services, General Ledger
Office of Natural Resources Revenue
Denver Federal Center (6th Ave West & Kipling St)
Bldg. 85, Entrance N-1
Denver, CO  80225
Phone: 303-231-3085
Mobile: 720-220-6044
Fax: 303-445-9526
Email: ***@***.******@***.***>

"Remember. Everyday some ordinary person does something extraordinary. Today, it's your turn." - Lou Holtz

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________
From: Christine Thomas ***@***.***>
Sent: Tuesday, October 25, 2022 1:36 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Soto, Victoria C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update Payment page with new contact information (Issue #2239)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@vcs5274<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvcs5274&data=05%7C01%7Cvictoria.soto%40onrr.gov%7C7502b7774b7e405c1fed08dab6c04af2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638023235125568911%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=tkD%2FsY8vUsQjdeQqDTtgI2N174XSXDWjvjgqexOf22w%3D&reserved=0>
On the payments webpage, there are multiple contacts (pictured below)
Which contacts do you want updated?

[image]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F72526208%2F197865906-d27e6ee8-8dc3-431c-896b-1c060ee80b68.png&data=05%7C01%7Cvictoria.soto%40onrr.gov%7C7502b7774b7e405c1fed08dab6c04af2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638023235125568911%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=fOKKCKsy91Zvcxxn8coFUd3N5BUSI8uX9bQ%2Bvn5G6Zs%3D&reserved=0>

**Comment by cthomasONRR** [comment]
@vcs5274 

Great, these changes are now in the dev site: http://2017onrr/reportpay/payments.htm
Please review and give us approval to go live.

In the future, when requesting changes in contact information, we kindly ask that you format your request in the following way: "Please update contact information on [webpage URL]. Under [contact header], please remove [old contact info] and replace it with [new contact info]"

Thanks,
Christine

**Comment by vcs5274** [comment]
Everything looks great.

Thank you for the explanation. I will save this email as a reminder for future updates to the webpage.


Respectfully,

Victoria Soto, Supervisory Accountant (she/her/hers)
Accounting Services, General Ledger
Office of Natural Resources Revenue
Denver Federal Center (6th Ave West & Kipling St)
Bldg. 85, Entrance N-1
Denver, CO  80225
Phone: 303-231-3085
Mobile: 720-220-6044
Fax: 303-445-9526
Email: ***@***.******@***.***>

"Remember. Everyday some ordinary person does something extraordinary. Today, it's your turn." - Lou Holtz

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________
From: Christine Thomas ***@***.***>
Sent: Tuesday, October 25, 2022 2:03 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Soto, Victoria C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update Payment page with new contact information (Issue #2239)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@vcs5274<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvcs5274&data=05%7C01%7Cvictoria.soto%40onrr.gov%7C91b45173ebbe4b47951608dab6c3facf%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638023250823567769%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=4lYzCqlLodfAxQgZpDfgeH2oxuCNW5tSWISeZ%2BHPRaM%3D&reserved=0>

Great, these changes are now in the dev site: http://2017onrr/reportpay/payments.htm
Please review and give us approval to go live.

In the future, when requesting changes in contact information, we kindly ask that you format your request in the following way: "Please update contact information on [webpage URL]. Under [contact header], please remove [old contact info] and replace it with [new contact info]"

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@vcs5274 

Great, these changes are live: https://www.onrr.gov/reportpay/payments.htm
Please remember to use "Ctrl+F5" to refresh the page.

And thank you so much for your patience and cooperation! I really appreciate it!

Christine
