### ISSUE TITLE
Map additions to Indian Gas Index and Indian Gas Major Portion

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#224]
We have new maps created for the Indian Gas Index Zone and Indian Gas Major Portion prices areas and would like to make them available on the Valuation web pages similar to the Indian Oil Major Portion that is available.

For the Indian Index Zone map, if you could place it below the "Index Zones" that are located on the right side of the page, that would be good.  The oil map is a hyperlink title, so a similar layout should be fine..."Indian Gas Index Zone Map" with a hyperlink to the map.

For the Indian Gas Major Portion, the page is laid out similar to the Oil Major Portion, so if you could add a "Reference" section at the bottom and a title with hyperlink, that would good as well.  "Indian Gas Major Portion Map"

Thanks, 
Cory Forgrave
[Indian_Gas_Index_Zone_Map.pdf](https://github.com/ONRR/onrr.gov-site/files/4885872/Indian_Gas_Index_Zone_Map.pdf)
[Indian_Gas_Major_Portion_Map.pdf](https://github.com/ONRR/onrr.gov-site/files/4885875/Indian_Gas_Major_Portion_Map.pdf)

@sudarr

**Comment by forgravec** [comment]
Jennifer,
I missed a map that Robert would like to be updated as well; the Indian Oil Major Portion map. There is currently a map on that webpage at the bottom under "Refereces", but we have a new version of it.
Thanks,
Cory 
[Indian_Oil_Major_Portion_Map.pdf](https://github.com/ONRR/onrr.gov-site/files/4886022/Indian_Oil_Major_Portion_Map.pdf)

@sudarr

**Comment by jennmalcolm** [comment]
@forgravec, these are ready for your review:
http://2017onrr/Valuation/MonMajPP.htm
http://2017onrr/Valuation/allzones.htm
http://2017onrr/Valuation/IndianOilIBMP.htm

**Comment by forgravec** [comment]
Jennifer,

They all look good, with one minor picky change.  For the "Indian Gas Major Portion map" will you capitalize 'Gas Major Portion' so that it matches the Indian Gas Index Zone one?

I haven't heard from Robert yet, but I think it looks great.

Thanks,
Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589

________________________________

**Comment by jennmalcolm** [comment]
Yes @forgravec I can change the capitalization. Do you want me to wait to make it live until Robert reviews it, or should I push these changes to production now?

**Comment by forgravec** [comment]
I heard back from Robert and he thought they looked good and was in agreement on the capitalization.  So you are good for pushing them through.

Kind regards,
Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589

________________________________

**Comment by jennmalcolm** [comment]
These maps are live on onrr.gov now.

**Comment by forgravec** [comment]
Thanks for completing this so fast.

Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589

________________________________
