### ISSUE TITLE
Minimum NGL Value example

### ISSUE THREAD

**Issue by jpetersononrr** [ONRR/onrr.gov-site#2240]
Hello!

Could you please post the below example on the examples table on this page https://onrr.gov/valuation/index.htm (as well as wherever it goes in the corresponding beta site)?  The title will be Indian Example:  Minimum NGL Value.  Thank you!!

[Minimum NGL Value.pdf](https://github.com/ONRR/onrr.gov-site/files/9864467/Minimum.NGL.Value.pdf)

**Comment by lpgoldstein** [comment]
@jpetersononrr Here is how it will look on the new site as well: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=valuation-examples

**Comment by jpetersononrr** [comment]
Thank you!!  Those both look great!

Jodie Peterson
Minerals Revenue Specialist
Royalty Valuation Guidance
Research, Enforcement, Guidance, & Appeals
Office of Natural Resources Revenue
***@***.******@***.***>
(303)231-3719

Royalty Valuation - Consistent Answers to Complex Questions

This email does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. Rather, this communication serves as guidance for determining value for royalties and is not an appealable decision or order under 30 CFR Part 1290, Subpart B. This guidance is based solely on the information provided and should only be used for the particular issue or question presented at the time of this communication. While this message is not appealable, ONRR may use this guidance in conducting audits and as a basis for demanding additional royalties.

From: lpgoldstein ***@***.***>
Sent: Tuesday, October 25, 2022 7:31 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Peterson, Jodie F ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Minimum NGL Value example (Issue #2240)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jpetersononrr<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjpetersononrr&data=05%7C01%7Cjodie.peterson%40onrr.gov%7C2af907884f4c4d1c61d708dab6f1cf1d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638023446922792469%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KDtjvdLixFN6KBE0P%2FChY7DGtJXObdg%2FeQ0m0WftuQg%3D&reserved=0> Here is how it will look on the new site as well: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=valuation-examples<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Freferences%2Fvaluation%3Ftabs%3Dvaluation-examples&data=05%7C01%7Cjodie.peterson%40onrr.gov%7C2af907884f4c4d1c61d708dab6f1cf1d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638023446922792469%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ELIYOMddGtCdXYVR6RdaGWtdgp9M9IK4SuWQrtgDV%2F0%3D&reserved=0>

**Comment by lpgoldstein** [comment]
@jpetersononrr It's live so I'm closing out the issue.

**Comment by jpetersononrr** [comment]
Thank you!!

Jodie Peterson
Minerals Revenue Specialist
Royalty Valuation Guidance
Research, Enforcement, Guidance, & Appeals
Office of Natural Resources Revenue
***@***.******@***.***>
(303)231-3719

Royalty Valuation - Consistent Answers to Complex Questions

This email does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. Rather, this communication serves as guidance for determining value for royalties and is not an appealable decision or order under 30 CFR Part 1290, Subpart B. This guidance is based solely on the information provided and should only be used for the particular issue or question presented at the time of this communication. While this message is not appealable, ONRR may use this guidance in conducting audits and as a basis for demanding additional royalties.

From: lpgoldstein ***@***.***>
Sent: Wednesday, October 26, 2022 8:16 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Peterson, Jodie F ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Minimum NGL Value example (Issue #2240)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Closed #2240<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F2240&data=05%7C01%7Cjodie.peterson%40onrr.gov%7C9b744201179346de1f0d08dab75c9037%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638023905434203614%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5WE2XpAJwoWN6Y9Ep3QoVrSz1%2FH5CEvsUOHDbm1qq94%3D&reserved=0> as completed.
