### ISSUE TITLE
Royalty Reporting Reporting Forms Title Changes

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2243]
Please change the title of the below reporting forms on this page - https://onrr.gov/reportpay/royalty-reporting.htm.

Change the title Allowances to read Indian Allowance Forms
Change the title Valuation to read Indian Valuation Forms

Screenshot from webpage attached for reference.  Please let me know if you need additional information.

[Royalty Reporting Forms screenshot.docx](https://github.com/ONRR/onrr.gov-site/files/9882592/Royalty.Reporting.Forms.screenshot.docx)

Thank You
Jessica Bowlen

**Comment by lpgoldstein** [comment]
@bowlenj ready for your review: http://2017onrr/reportpay/royalty-reporting.htm

**Comment by bowlenj** [comment]
Looks great!  Approved to move to prod!


Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning, and Coordination
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: lpgoldstein ***@***.***>
Sent: Thursday, October 27, 2022 1:38 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Royalty Reporting Reporting Forms Title Changes (Issue #2243)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cb0b87b63dbfb4508b77108dab852ccae%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638024963011710621%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Sbmy1G7UvuxZ03sHCUpGqjHhWs2D%2B6%2BU%2BdxDSF1n%2FoA%3D&reserved=0> ready for your review: http://2017onrr/reportpay/royalty-reporting.htm

**Comment by lpgoldstein** [comment]
@bowlenj This is live so closing. https://onrr.gov/reportpay/royalty-reporting.htm
