### ISSUE TITLE
Load CY 2023 IDD Disb Memo

### ISSUE THREAD

**Issue by bakercook** [ONRR/onrr.gov-site#2247]
Hello,

File is corrected 32 checks. Please add to Indian Services/Allottee Assistance/Royalty Distribution Dates. Place above CY 2022 memo.
Thank you.
[CY 2023 Disb Memo.pdf](https://github.com/ONRR/onrr.gov-site/files/9902323/CY.2023.Disb.Memo.pdf)

**Comment by bakercook** [comment]
Christine- no issues this time?

**Comment by cthomasONRR** [comment]
@bakercook No issues! I'm working on getting it up on dev right now! Thanks :)

**Comment by bakercook** [comment]
Finally! Thank you. So sorry for the bad files before.


Cheri

________________________________
From: Christine Thomas ***@***.***>
Sent: Monday, October 31, 2022 9:13 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Baker, Cheri L ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Load CY 2023 IDD Disb Memo (Issue #2247)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bakercook<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbakercook&data=05%7C01%7Ccheri.baker%40onrr.gov%7C4b2408bc2fbc4086442b08dabb5289d9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638028260432450700%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bJYSXDJRtdlCj5%2BczBxEY9R%2Bxt6e97dZhbxQLLB2%2BMI%3D&reserved=0> No issues! I'm working on getting it up on dev right now! Thanks :)

**Comment by cthomasONRR** [comment]
@bakercook 

No worries! This update is now on the dev site: http://2017onrr/IndianServices/index.htm
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by bakercook** [comment]
Looks good. Thank you Christine.


Cheri

________________________________
From: Christine Thomas ***@***.***>
Sent: Monday, October 31, 2022 9:20 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Baker, Cheri L ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Load CY 2023 IDD Disb Memo (Issue #2247)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bakercook<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbakercook&data=05%7C01%7Ccheri.baker%40onrr.gov%7C15d9c5d20bb140cd42c808dabb5374c7%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638028264358851514%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=R6AE2y70AzVBN%2F47%2BhW3KrKBJZ%2F2EJ4ZHMKkXq1TraM%3D&reserved=0>

No worries! This update is now on the dev site: http://2017onrr/IndianServices/index.htm
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bakercook 

This update is now live: https://www.onrr.gov/IndianServices/index.htm
Please use "Ctrl+F5" to refresh the page.

Thanks,
Christine
