### ISSUE TITLE
October Analytics - onrr.gov

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#2249]

**Comment by cthomasONRR** [comment]
@lpgoldstein

The onrr.gov analytics are ready for your review:
https://github.com/ONRR/onrr.gov-site/wiki/Analytics

Check sheet: https://doimspp-my.sharepoint.com/:w:/r/personal/thomasc_mms_gov/Documents/CLT%20Analytics/Check%20Sheets/Analytics%20October%2022.docx?d=w6ff1bbc7f74345be9d940602172dd133&csf=1&web=1&e=GDmasL

**Comment by lpgoldstein** [comment]
@cthomasONRR Also looks good!
