### ISSUE TITLE
EASTETRN OK REGIONAL VIRTUAL MEETING                                         Add New Document under Event Calendar

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#2250]
https://www.onrr.gov/events.htm

EASTERN OK REGIONAL VIRTUAL MEETING
Thursday, November 17, 2022
1:00 pm to 2:00 pm CST

Location:  By Telephone

DESCRIPTION: The Office of Natural Resources Revenue (ONRR) will be hosting a virtual (call-in) Outreach Meeting for Indian trust property owners.  Representatives from the Bureau of Land Management (BLM), Bureau of Trust Funds Administration (BTFA), and the Bureau of Indian Affairs (BIA) will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts, and Indian Trust property issues.  The meeting will begin with the brief introduction by the ONRR representative.  Owners will have an opportunity to ask questions with the representatives of the four agencies during the Q&A session 

WHO SHOULD ATTEND:  Indian mineral owners, IIM account holders and other Indian Trust property owners in the Eastern Oklahoma regional area.
  
OTHER INFORMATION: To reserve a space and get a passcode for this meeting please contact the ONRR OKC Outreach Office toll-free at (800) 354-7015. The OKC office hours are Mon.- Fri. from 7:30 am-5:00 pm.

CONTACT: ONRR OKC Outreach Office, Phone: Toll Free (800) 354-7015
EMAIL: onrroutreachokc@onrr.gov

**Comment by cthomasONRR** [comment]
@Toddsand21 

I'm working on this right now. Would you like me to remove the October events?

**Comment by cthomasONRR** [comment]
@Toddsand21 

This update is in dev: http://2017onrr/events.htm
Please review and give us your approval to go live.

(I can add the October events back if needed.)

Thanks,
Christine

**Comment by Toddsand21** [comment]
Yes, you can delete the October events.  The proof looks fine and ready to post.

**Comment by cthomasONRR** [comment]
@Toddsand21 

Great, these changes are now live: https://www.onrr.gov/events.htm
Please remember to use "Ctrl+F5" to refresh the page.

Thanks,
Christine
