### ISSUE TITLE
Build new Indian Interactive Example "RPMP-Act"

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#2251]
**Revised Reporting Using Actual Dual Accounting for Processed Gas in Non-Index Zone (Major Portion) Areas**

https://beta.onrr.gov/document/Revised.Reporting.Using.Actual.Dual.Accounting.for.Processed.Gas.in.Non-Index.Zone.Major.Portion.Areas.pdf

**Comment by cthomasONRR** [comment]
@eelzi-ONRR 

- [ ] Move this intro paragraph up above the first-level tabs:
![image](https://user-images.githubusercontent.com/72526208/200400672-bbd21b85-42bf-4895-81bb-5f05df4f1898.png)

- [ ] Add the RV email to Contact, remove the Updates card (as there are no updates), and either title the Downloadable example hyperlink "Download PDF" or "Download [entire example title]" I'd recommend just "Download PDF"
![image](https://user-images.githubusercontent.com/72526208/200400329-7b5519a3-ffe9-45ad-89cf-6b5c36abdf40.png)

- [ ] I can't find this section anywhere, it should be added to the overview, after the bulleted list:
![image](https://user-images.githubusercontent.com/72526208/200400808-a9ea8dbe-e215-4330-9a5c-05a5be69ad1d.png)
 
- [ ] Add the bold text format in the bulleted list in the Overview tab
![image](https://user-images.githubusercontent.com/72526208/200400938-b18f037b-40f3-43ea-b8a2-f4014dc92406.png)

- [ ] Add a Sample Statement tab to the first-level tabs with this info in it, plus an image of the plant statement and a downloadable PDF link to the plant statement as well. (see the 2016 example for reference)
![image](https://user-images.githubusercontent.com/72526208/200401141-a89d1318-0334-4b83-b98b-440f513446cc.png)

- [ ] Add a product codes tab to the first-level tabs. (see the 2016 example for reference)

- [ ] In the Detailed Example Tab - Make the Assumptions accordion automatically be open:
![image](https://user-images.githubusercontent.com/72526208/200401489-c3cacdeb-16d7-4b82-8a32-f3c19bfb6417.png)

- [ ] The content within your Assumptions accordion does not match the assumptions in your example. Did you add this as an existing expansion panel? You need to add a new, unique panel for your example. See my example page for ref: https://dev-onrr-cms.app.cloud.gov/admin/content/pages/171
![image](https://user-images.githubusercontent.com/72526208/200401652-ad789cd2-93af-4e99-9642-9ec793bf92ae.png)

- [ ] Major Portion Value Requirement- Make sure you add in the hyperlinks: 
![image](https://user-images.githubusercontent.com/72526208/200401935-f658c812-0e62-438f-8610-3982786fe900.png)

- [ ] Determining Dual Accounting - content needs to be italicized
![image](https://user-images.githubusercontent.com/72526208/200402254-027c0d8e-395b-49f7-bdd7-fd13174cd05d.png)

- [ ] Minimum Value Requirement- Step 1 needs a hyperlink
![image](https://user-images.githubusercontent.com/72526208/200402412-6b19262d-0b6f-4423-acf1-ce7bab64064e.png)

- [ ] There's a table after Step 10 that needs to be added
![image](https://user-images.githubusercontent.com/72526208/200402622-36357a0b-a675-44f6-a5d2-d1c57af7bb6c.png)

**Comment by eelzi-ONRR** [comment]
Yep - I know it's not done yet. I was looking to get some feedback on a few things from you when we meet this afternoon before I keep working on it

**Comment by eelzi-ONRR** [comment]
@cthomasONRR This page is ready for review - I pushed to dev so you can access it easier:
[https://dev-onrr-frontend.app.cloud.gov/references/valuation/rpmp-act?tabs=overview](https://dev-onrr-frontend.app.cloud.gov/references/valuation/rpmp-act?tabs=overview)

I addressed all the things you listed previously - they either reflect your suggested changes or we discussed them in Slack or a meeting.

I experimented with setting the Minimum Value Requirement width to 12, but that made the images real fuzzy. So I reverted it back to 8.

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Great! I might not get to review this until Monday- lots of meetings today!

For images being blurry, you can modify their width in the CMS. It's definitely annoying and takes trial-and-error to get the correct width though.
![image](https://user-images.githubusercontent.com/72526208/201142601-3cf5df09-14a2-451d-b087-f4a8ef80ac52.png)

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Looks pretty good- a few things to look at- 

Overview:

- [ ] Bold these words:
![image](https://user-images.githubusercontent.com/72526208/201197107-68a169bf-615c-4d92-89ee-ec1886c570fe.png)

Assumptions:

- [ ] Make the Assumptions expansion panel be open by default (let me know if you figure it out, I can show you, it's kind of tricky)
![image](https://user-images.githubusercontent.com/72526208/201197439-c2b76735-1936-40af-b627-d7f45c8749e7.png)
- [ ] Assumptions Step 2, remove extra words that aren't in the PDF
![image](https://user-images.githubusercontent.com/72526208/201197758-0757628e-dced-4c34-8c31-cf8d75cabf67.png)
- [ ] Initial reporting section, words not bolded and the note is missing. I think you should just copy+paste from mine. I know your trying to paraphrase, but mentions of "Assumption 7" in the Assumption 8 are confusing without the same numbering.
![image](https://user-images.githubusercontent.com/72526208/201198608-f775fccf-9909-4288-a674-8d4518780ed0.png)

Other than that, looks good!

**Comment by cthomasONRR** [comment]
@eelzi-ONRR 

Oh! one more thing- you can add "previous" and "next" hyperlinks at the bottom of each 2nd level tab: 
![image](https://user-images.githubusercontent.com/72526208/201201996-03a23afe-91c5-47cf-8249-2301a8688f6c.png)

**Comment by eelzi-ONRR** [comment]
@cthomasONRR Thank you!

I've made the changes - can you check them once more?

I ended up removing the initial reporting text and just linking to your page. That way if the initial reporting assumptions change, we don't have to update both pages.

I got the Assumptions accordion to default to open, but I tried a couple things at once and I'm not sure which one (or all?) of those did the trick. So if you can show me the proper way to do it at some point, that would be great!

For the Minimum Value Requirement width set at 12 - I had to make the images more narrow than the text in order for them to not be blurry. I think it looks okay, but let me know your thoughts.
