### ISSUE TITLE
Replace Federal Royalty Reporting Contacts

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2255]
Please replace the existing Federal Royalty Reporting contact sheet with the attached updated sheet on the following web pages:

https://www.onrr.gov/about/contact.htm
https://www.onrr.gov/reportpay/royalty-reporting.htm

Thank you!
Jessica
[Federal Royalty Reporting Assignments.pdf](https://github.com/ONRR/onrr.gov-site/files/9922997/Federal.Royalty.Reporting.Assignments.pdf)

**Comment by lpgoldstein** [comment]
@bowlenj Ready for your review: http://2017onrr/about/contact.htm
https://www.onrr.gov/reportpay/royalty-reporting.htm#contacts

**Comment by bowlenj** [comment]
This page looks great - http://2017onrr/about/contact.htm.

I'm not seeing the updated contact sheet on this page - https://www.onrr.gov/reportpay/royalty-reporting.htm#contacts<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2Freportpay%2Froyalty-reporting.htm%23contacts&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C5ae96e3df53c4fd1890508dabd02e567%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638030117383410818%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JEJcrxIhER4xcWvbst5BjwljHZdU32VhDLK6KuDQu1E%3D&reserved=0>.  I tried the Ctrl F5 refresh but I didn't see the update.  Can you verify the new one was attached to this page?


Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning, and Coordination
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: lpgoldstein ***@***.***>
Sent: Wednesday, November 2, 2022 12:34 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Replace Federal Royalty Reporting Contacts (Issue #2255)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C5ae96e3df53c4fd1890508dabd02e567%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638030117383410818%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rZKlxvG3YFzC0vCe7tlotd7yU1sE2dova99f2bLpx%2FE%3D&reserved=0> Ready for your review: http://2017onrr/about/contact.htm
https://www.onrr.gov/reportpay/royalty-reporting.htm#contacts<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2Freportpay%2Froyalty-reporting.htm%23contacts&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C5ae96e3df53c4fd1890508dabd02e567%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638030117383410818%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JEJcrxIhER4xcWvbst5BjwljHZdU32VhDLK6KuDQu1E%3D&reserved=0>

**Comment by lpgoldstein** [comment]
@bowlenj This is live!
