### ISSUE TITLE
Add accessibility reporting info

### ISSUE THREAD

**Issue by eelzi-ONRR** [ONRR/onrr.gov-site#2256]
We have the DOI Accessibility link in the footer, but no where for users to report website accessibility issues to us. There's the Website Feedback on the Contact Us page, but searching for accessibility wouldn't take the user to that.

It's beyond 508 requirements, but good practice to include explicit info on how to report accessibility issues and what to expect in response. If someone needs to report an accessibility issue, they probably are already struggling with the site, and we don't want to make it any more difficult for them than it already is.

**Comment by Maroyafaied** [comment]
@eelzi-ONRR Let's contact the Departments 508 coordinator to ask if we can add our own accessibility page instead of linking to the Departments page.

**Comment by eelzi-ONRR** [comment]
Email sent. Sid is OOO until tomorrow, so it might be a few days before we hear back

**Comment by eelzi-ONRR** [comment]
@Maroyafaied  Sid got back to me, and yes - we can create our own page and to link to it in our footer. He also directed me to this resource: [https://www.section508.gov/manage/laws-and-policies/website-accessibility-statement/](https://www.section508.gov/manage/laws-and-policies/website-accessibility-statement/)

I'll start working on a page based off DOI's but with our contact info, and use the link Sid sent to see if there's any other changes we should consider

**Comment by eelzi-ONRR** [comment]
@Maroyafaied this page is ready for review

[https://preview-onrr-frontend.app.cloud.gov/accessibility](https://preview-onrr-frontend.app.cloud.gov/accessibility)

I used the vulnerability disclosure policy page as a template.

If you want to see exactly what was changed from the DOI accessibility statement, the changes are tracked in [this doc](https://doimspp-my.sharepoint.com/:w:/g/personal/elzie_mms_gov/EXUq_erJh41NgeW_5vcmC1cBhdwHjgMH0dZ2sYbxWLahtA?e=OFqM6l)

I added a last updated date, as per the resource that Sid sent me (linked above)

**Comment by Maroyafaied** [comment]
@eelzi-ONRR This looks good, the only other thing I think we should change is the footer title, we should probably remove "DOI" and have it as just "Accessibility". We should also make an issue for the NRRD to add a similar accessibility page. Nice work! 

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/f3f0a6bc-88ab-48d0-be65-5eada3d8698b)

**Comment by eelzi-ONRR** [comment]
@Maroyafaied Footer title has been changed and the page is live. Once you review we can close this ticket
