### ISSUE TITLE
Update index zone pricing on onrr.gov

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#2257]
Please update the Indian Index Zone prices based on the data provided in the "Data for ONRR.gov" spreadsheet.

Thanks!
@sudarr

**Comment by lpgoldstein** [comment]
@boices Ready for your review: http://2017onrr/valuation/allzones.htm

**Comment by boices** [comment]
That's perfect--thanks again!

**Comment by lpgoldstein** [comment]
@boices This is live so I'm closing out the issue - https://onrr.gov/valuation/allzones.htm
