### ISSUE TITLE
Monthly NYMEX pricing

### ISSUE THREAD

**Issue by WW-Git-Hub** [ONRR/onrr.gov-site#2258]
The October NYMEX pricing is ready to be added to ONRR.gov.  Spreadsheet below.
[NYMEX102022.xlsx](https://github.com/ONRR/onrr.gov-site/files/9931931/NYMEX102022.xlsx)

Also, the ONRR.gov page with the NYMEX prices opens to 2021.  Can this be updated to open to 2022?
https://onrr.gov/valuation/NYMEX.htm

@Sudarr

**Comment by lpgoldstein** [comment]
@WW-Git-Hub Ready for your review: http://2017onrr/valuation/NYMEX.htm

Also, I'm sorry, we are unable to fix that because we don't have any developer capacity at the moment. It will show up properly on the new site.

**Comment by WW-Git-Hub** [comment]
Everything looks correct.

Thanks

**Comment by lpgoldstein** [comment]
@WW-Git-Hub This is live so I'm closing out the issue https://onrr.gov/valuation/NYMEX.htm 
Also this is what it will look like on the new site - https://beta.onrr.gov/references/valuation?tabs=pricing,nymex-oil-prices
