### ISSUE TITLE
Replace Lease & Agreement Maintenance Contacts

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2259]
Please replace the existing lease & agreement maintenance contacts with the updated attached version on the following web pages:

https://www.onrr.gov/about/contact.htm
https://www.onrr.gov/reportpay/royalty-reporting.htm

[Lease Agreement Maintenance Contacts.pdf](https://github.com/ONRR/onrr.gov-site/files/9932238/Lease.Agreement.Maintenance.Contacts.pdf)

**Comment by cthomasONRR** [comment]
@bowlenj 

This update is on the dev site:
http://2017onrr/about/contact.htm
http://2017onrr/reportpay/royalty-reporting.htm

Please review and give us your approval to go live.

Thanks,
Christine

**Comment by bowlenj** [comment]
Looks GREAT!  Approved for live.


Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning, and Coordination
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, November 3, 2022 1:14 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Replace Lease & Agreement Maintenance Contacts (Issue #2259)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cc3da0f4cabee48abe27108dabdcf9cd5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638030996635080278%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7cSYFFT20HWOk3uqU5K28o4LV%2BmIM6bOMaKist8OaMo%3D&reserved=0>

This update is on the dev site:
http://2017onrr/about/contact.htm
http://2017onrr/reportpay/royalty-reporting.htm

Please review and give us your approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj 

Great, these changes are now live:
https://www.onrr.gov/about/contact.htm
https://www.onrr.gov/reportpay/royalty-reporting.htm

Note: the beta site will be updated when we receive an updated excel sheet.

Thanks,
Christine
