### ISSUE TITLE
change name on checklist

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#226]
https://www.onrr.gov/ReportPay/prod-checklist.htm; under Onshore Production Reporters change Eugenia (Jeannie) Lynn to Justin Hatfield, 303-231-3886, Justin.hatfield@onrr.gov

This is from Service Now. If you make the changes in dev, I will review them, and then we can publish.

**Comment by lpgoldstein** [comment]
@jennmalcolm this is ready for your review: http://2017onrr/reportpay/prod-checklist.htm

**Comment by jennmalcolm** [comment]
Looks good. I moved i to the center because the alignment bothered me, but its good to go! Thanks.
