### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov - November 2022

### ISSUE THREAD

**Issue by aalveari1** [ONRR/onrr.gov-site#2260]
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “November 2022 Lease Agreement XREF.txt" and "November 2022 Lease Agreement XREF.xlsx”.  The data was queried from the system on 11/07/2022.
[November 2022 Lease Agreement XREF.txt](https://github.com/ONRR/onrr.gov-site/files/9953735/November.2022.Lease.Agreement.XREF.txt)
[November 2022 Lease Agreement XREF.xlsx](https://github.com/ONRR/onrr.gov-site/files/9953776/November.2022.Lease.Agreement.XREF.xlsx)

**Comment by lpgoldstein** [comment]
@aalveari1 ready for your review; http://2017onrr/reportpay/CrossRef.htm

**Comment by lpgoldstein** [comment]
@aalveari1 it's live! https://onrr.gov/reportpay/CrossRef.htm
