### ISSUE TITLE
Write alt text for new RV example

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#2269]
This issue is for the following example: "Indian Example: Initial Reporting for Unprocessed Gas in Non-Index Zone (Major Portion) Areas"

Here is the CMS file library location where the images are saved. Add the alt text to the description field:
https://dev-onrr-cms.app.cloud.gov/admin/files/folders/2c4eba5a-694d-4b1c-b198-9c82787ef460

Here is a link to the PDF version of the example:
https://beta.onrr.gov/document/Initial_Reporting_for_Unprocessed_Gas_in_Non-Index_Zone_MajorPortion_Areas.pdf
Use the text in the PDF to write the alt text.

For reference see these 2 image file folders where alt text was recently added:
https://dev-onrr-cms.app.cloud.gov/admin/files/folders/8035bee1-c034-4fdb-9c0a-a9fce5f2a70a
https://dev-onrr-cms.app.cloud.gov/admin/files/folders/c00a2c1a-58dc-423b-8f4f-bc4799804959

**Comment by cthomasONRR** [comment]
@Isabelh99 

Try using this link on Chrome: 
https://dev-onrr-cms.app.cloud.gov/admin/content/pages

Let me know if this works, thanks!

**Comment by Isabelh99** [comment]
Ah maybe. I tried this new link and the same thing happens :/....
<img width="371" alt="image" src="https://user-images.githubusercontent.com/93946660/203135536-1fe0c3f2-ae5f-4e39-86c4-5a489a48fa07.png">
I read somewhere online that it might due to requiring the 2FA without having actually actually enabled... something like that

**Comment by Isabelh99** [comment]
It works now!

**Comment by Isabelh99** [comment]
Hello! @eelzi-ONRR & @cthomasONRR!
I did all images on 4 and wanted to get your feedback on it! And or green light to do more 👍

**Comment by cthomasONRR** [comment]
@Isabelh99 @eelzi-ONRR I think these look good. Erin, want to approve?

**Comment by eelzi-ONRR** [comment]
@cthomasONRR @Isabelh99  I agree! Great job on these ones!

**Comment by cthomasONRR** [comment]
@Isabelh99 @eelzi-ONRR Great! Isabel, want to go ahead and do examples 3, 5, and 6? Thanks!

**Comment by Isabelh99** [comment]
I wanted to write a few notes before I forget on here:
- For this folder:
3_RPMP-Alt: Revised Reporting Using Alternative Dual Accounting for Processed Gas in Non-Index Zone (Major Portion) Areas
*I couldn't find the last pic of the "Rpmp Alt Sample Statement" image on the **pdf link**: https://www.onrr.gov/document/Revised.Reporting.Using.Alternative.Dual.Accounting.for.Processed.Gas.in.Non-Index.Zone.Major.Portion.Areas.pdf
**location**: https://www.onrr.gov/references/valuation?tabs=valuation-examples

Other than this, I think I'll work on the 6th folder and should be done this later in the week or so.

**Comment by cthomasONRR** [comment]
@Isabelh99 Good observation - for "3_RPMP-Alt" , the sample statement is not in the PDF. We had to ask for it separately. For creating the alt text, focus on the letters used in that example. (This sample statement is reused in other examples)

**Comment by cthomasONRR** [comment]
@Isabelh99 I noticed that you added all alt text. I reviewed and did some light editing. I'll close this issue and we can discuss future tasks at our next meeting.

**Comment by Isabelh99** [comment]
Yes, I think I had 1 left but I did finish them. 👍 Sounds good.
