### ISSUE TITLE
Webpage Update (100% Fed Agrmt)

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#227]
Please update the following webpage http://www.onrr.gov/ReportPay/royalty-reporting.htm with the attached PDF file.

100% Federal Agreements with the Same Royalty Rate & Royalty Distributions.  Also change update to read 07/01/2020.

Thanks
[fedagmts.pdf](https://github.com/ONRR/onrr.gov-site/files/4893309/fedagmts.pdf)

**Comment by Maroyafaied** [comment]
@merrellc please review the updates in the development site, if everything looks correct then I will publish it to the live site. http://2017onrr/ReportPay/royalty-reporting.htm

**Comment by merrellc** [comment]
Thank you. You can publish to live site.

**Comment by Maroyafaied** [comment]
This is live now.
