### ISSUE TITLE
Contact List Template for Beta Site-Complete

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2270]
Attached is the completed template for DISCs contacts on the new beta site.  We've split each functional area into different tabs, Lease & Agreement, Royalty, Onshore Production and Offshore Production.  Please let us know if this format works and if you have any issues with the update/load.

If there are any issues Candace and I are happy to continue working with your team to get this correct so contact updates are easier moving forward for your team.  Thank you again for all the help, time and suggestions with getting this spreadsheet setup!  We really appreciate all of you!

Thank You
Jessica
[DISC new contact template.xlsx](https://github.com/ONRR/onrr.gov-site/files/9965675/DISC.new.contact.template.xlsx)

**Comment by cthomasONRR** [comment]
@lpgoldstein I reviewed, and I don't see any glaring errors. I think this is good to send back to Jessica for final approval.

**Comment by lpgoldstein** [comment]
@bowlenj Ready for your review! https://beta.onrr.gov/about/contact
Also we need to set up a meeting to talk through the spreadsheet. I'll get something on the calendar for next week.

**Comment by bowlenj** [comment]
Hi Lindsay, thank you for chatting and walking me through the updates.  This is approved for closure.

Candace and I can make additional updates needed to the new spreadsheet you send us and re-submit next week.  Thank you again!!!!!


Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning, and Coordination
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: lpgoldstein ***@***.***>
Sent: Monday, November 14, 2022 7:07 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Contact List Template for Beta Site-Complete (Issue #2270)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C1d1974aaf89642cbe37d08dac6498e11%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638040316472835251%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CR1SYJ4AhLCGBPMBFbAHXRVZSDjuhRKwsXBr%2BGOFml0%3D&reserved=0> Ready for your review! https://beta.onrr.gov/about/contact<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbeta.onrr.gov%2Fabout%2Fcontact&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C1d1974aaf89642cbe37d08dac6498e11%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638040316472835251%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=f6LddLkK0cDuEsZF%2BBBbriPM7EQLsTjlR0h9fhFNiAA%3D&reserved=0>
Also we need to set up a meeting to talk through the spreadsheet. I'll get something on the calendar for next week.
