### ISSUE TITLE
Plan/process for checking accessibiliy on new PDFs

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#228]
Making all documents on onrr.gov accessible will be huge (#128), but let's think about putting a process in place to check new documents provided to us and how to work with the document owners to make sure anything new we post is accessible.

**Comment by jennmalcolm** [comment]
come up with action plan to present to Kimbra and Howard

**Comment by mcharg** [comment]
@jennmalcolm We might want to indicate that the checklists at the bottom open docs instead of webpages.  Otherwise, looks good.
