### ISSUE TITLE
RV to review example "Revised Reporting Using Actual Dual Accounting for Processed Gas in Non-Index Zone (Major Portion) Areas"

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#2281]
@jpetersononrr

Hi Jodie,

Here is a link to the interactive example: 
https://beta.onrr.gov/references/valuation/rpmp-act

Once we make any requested corrections and you approve it, this example will be linked on the appropriate card here: https://beta.onrr.gov/references/valuation?tabs=valuation-examples

Thanks,
Erin & Christine

**Comment by eelzi-ONRR** [comment]
Feedback from Jodie:

**Revised Actual DA MP** 

- In “Major Portion Requirement” the last paragraph has an extra hard return before it. 

- In “Determining Dual Accounting” the third and fourth paragraphs have an extra hard return between them. 

- Same hard return in “Dual accounting requirement” before the third paragraph 

- The text in the first three tabs can be extended out to the full width of the tab. 

- Before the tables in the “Minimum Value Requirement”, “Form ONRR-2014” can be removed. 

- Could a final tab be created that is “calculations” where steps 1-10 live?  They are not tied to the minimum value requirement, but we want that requirement to have equal weight.  Open to another word, but that was the one that sprang to mind!

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Response from Jodie:
![image](https://user-images.githubusercontent.com/72526208/204586267-13be661c-1e46-4b1d-8b75-59f008f52431.png)

**Comment by eelzi-ONRR** [comment]
@cthomasONRR can you share this with her? The first three math boxes show variations on the size. 1st is the current, smallest size, 2nd is expanded a little, and 3rd is expanded to the full width. They get blurrier as they increase in size - but if she still wants them full width I'll do that.

[https://dev-onrr-frontend.app.cloud.gov/references/valuation/rpmp-act?tabs=detailed-example,calculations&panel=assumptions-revised-reporting-using-actual-dual-accounting-for-processed-gas-in-non-index-zone-major-portion-areas](https://dev-onrr-frontend.app.cloud.gov/references/valuation/rpmp-act?tabs=detailed-example,calculations&panel=assumptions-revised-reporting-using-actual-dual-accounting-for-processed-gas-in-non-index-zone-major-portion-areas)

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Just shared it! FYI feel free to chat her on Teams- her name is Jodie Peterson. 

Another option (while tedious) is to resave the images as larger image sizes (I usually make them as big as I can on the PDF before taking screen grabs) and replacing them in the image files. After looking, it does seem that your images are much smaller in size than the ones I saved in my example.

**Comment by eelzi-ONRR** [comment]
@cthomasONRR I don't mind remaking them. Now that I have photoshop it will be much faster and easier

**Comment by eelzi-ONRR** [comment]
New images created and uploaded. Approved via Teams
