### ISSUE TITLE
Review Code for America proposals

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#2282]
@Maroyafaied 

We wrote 3 proposals in the document linked below. Please review and let us know if you have any comments/suggestions. Thanks!

https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Outreach/Proposals%20%26%20Presentations/FY23/CfA_23_Brainstorm.docx?d=we1a03312132b499381c9a3f6d249e826&csf=1&web=1&e=6r24oF

**Comment by cthomasONRR** [comment]
@Maroyafaied I added your proposal to the word doc. I added in some comments and made some edits, mainly to make sure we are still at that 150 word limit. Looks good, excited to get these submitted!

**Comment by eelzi-ONRR** [comment]
@Maroyafaied I love that topic idea, and thank you for your input on the ones we came up with!
