### ISSUE TITLE
Take GitHub Training 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2288]

**Comment by lpgoldstein** [comment]
https://doitalent.ibc.doi.gov/course/view.php?id=20144

**Comment by Maroyafaied** [comment]
@R-mohansai please see the response from Oscar, it looks like you already completed the course on Nov 18th. That's probably why the links don't work anymore. ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/c7352bde-45dc-4180-85ad-9fda847a5372)

**Comment by R-mohansai** [comment]
Raised Github License ticket and closing the ticket as complete.
