### ISSUE TITLE
Montana Virtual Outreach                                    

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#2291]
Thursday, December 8, 2022
10:00 am-11:00 am MST
Location:  By Telephone

Description: Representatives from the Office of Natural Resources Revenue will host a Question-and-Answer session by telephone for Indian Mineral Owners and Trust Property Owners regarding their Indian Oil & Gas leases, IIM Accounts, and Indian Trust Properties. Representatives from the Bureau of Land Management, Bureau of Indian Affairs, and Bureau of Trust Funds Administration have been invited to be in attendance to answer questions.

Who Should Attend: IIM account holders, Indian mineral owners, and Indian trust property owners in the Billings, Lame Deer, Crow, Butte, Helena, Missoula, Harlem, Browning, or Great Falls, Montana areas. 

Other Information: To attend the outreach session, please contact the ONRR Denver Outreach Office at (800) 982-3226, for the call-in number and passcode.  The ONRR Denver Outreach Office hours are Monday-Friday 7:30am-4:00pm.

Contact:  ONRR Denver Outreach Office, Toll-fee (800) 092-3226.
Email: onrroutreachdenver@onrr.gov

______________________________________________________________________________________________________________________________________
ADD YOUR ISSUE INSTRUCTIONS HERE:
To be added to Event Calendar following NOV Events.  Please leave November events up through the end of November or until we add more events.

**Comment by cthomasONRR** [comment]
@Toddsand21 

These changes are now in Dev: http://2017onrr/events.htm
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by Toddsand21** [comment]
It looks fine and ready!

**Comment by cthomasONRR** [comment]
@Toddsand21 

Great! These changes are now live: https://www.onrr.gov/events.htm
Please remember to use "Ctrl+F5" to refresh the page.

Thanks,
Christine

**Comment by Toddsand21** [comment]
Thank you!
