### ISSUE TITLE
Add ability to add "Federal" or "Indian" in Primary Role contacts field 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2292]
Adjust code to be able to add "Federal" and "Indian" to "Primary Contact", "Supervisor", "Back-Up Contact" to accommodate RRM.

**Comment by cthomasONRR** [comment]
@Maroyafaied Where in dev should I check? Do we need to revise the spreadsheet and reload in dev? 
![image](https://user-images.githubusercontent.com/72526208/202301576-3bb0028d-6e89-4254-a586-1669b9954401.png)

**Comment by Maroyafaied** [comment]
@cthomasONRR I just tested with a random existing card in the cms and changed it back.  I was playing with the Appeal & Sureties card but I will change it back to "Primary Contact"
![image](https://user-images.githubusercontent.com/40175688/202301924-d488e599-fa1c-4304-a971-c688c3fa54aa.png)

**Comment by cthomasONRR** [comment]
@Maroyafaied OK awesome, so I think we will need to revise the spreadsheet and reload it. We can make an issue to do that next sprint.

**Comment by Maroyafaied** [comment]
@cthomasONRR Ok, I'll close this issue and create another one to test next sprint.
