### ISSUE TITLE
Update revenue statistics to FY 22 number

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2294]
@eelzi-ONRR I'm assigning this issue to you and to @lpgoldstein to help out /review.   The FY 22 revenue and disbursements values are now published on the NRRD, we need to update them on the homepage on onrr.gov 

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/3a4947b1-1932-432b-86df-7cabf8449310)

**Comment by eelzi-ONRR** [comment]
Was discussed and reviewed in slack.
