### ISSUE TITLE
Add FY 22 press release & test new workflow 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2295]
Add the FY22 press release that went out in September.

**Comment by Maroyafaied** [comment]
@greensomes here's the info you need
Status: Published
Title: Interior Department Announces $21.53 Billion in Fiscal Year 2022 Energy Revenue, Highest-Ever Disbursements from Clean Energy from Federal Lands and Waters
Date:11/4/2022
File: click choose from library and select "FY 2022 Disbursements Press Release"
Excerpt: **WASHINGTON—**Today, the Department of the Interior's Office of Natural Resources Revenue (ONRR) disbursed $21.53 billion in revenues generated in fiscal year 2022 from energy production on federal and Tribal onshore lands, and federal offshore areas, including the record $4.37 billion generated from the New York Bight offshore wind lease sale.

**Comment by greensomes** [comment]
Done!
