### ISSUE TITLE
Rulemaking update

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2300]
Good morning, 

Thank you, Maroya, for allowing me to do this through onrrweb while I fix the GitHub issue.

Please publish the following in onrr.gov:

Under https://www.onrr.gov/references/rulemakings, please update as follows: 

Above Inflation Adjustment to Civil Monetary Penalty Rates for Calendar Year 2021, enter the below information:

2022-09-30    1012-AA32     Electronic Provisions of Records During an Audit (hyperlink)    Audits

The hyperlink should lead the the following content:

Regulation Identifier Number 1012-AA32

Electronic Provision of Records During an Audit

30 CFR Parts 1206, 1208, 1217, and 1220

Abstract: ONRR proposes to amend its regulations to allow ONRR and other authorized Department of the Interior (‘‘Department’’) representatives the option to require that an auditee use electronic means to provide records requested during an audit of an auditee’s royalty reporting and payment.

Proposed Rulemaking: 87 FR 59350 (hyperlink to the following Federal Register page: https://www.federalregister.gov/documents/2022/09/30/2022-20495/electronic-provision-of-records-during-an-audit) 9/30/2022

Please let me know if you have any questions.

Thanks

**Comment by Maroyafaied** [comment]
I will send these links via email for review

https://preview-onrr-frontend.app.cloud.gov/references/rulemakings

https://preview-onrr-frontend.app.cloud.gov//references/rulemakings/aa-32

**Comment by Maroyafaied** [comment]
@cthomasONRR I'm adding you to this issue to review if I added the correct topics to the rule, feel free to change as you see fit. I created a new page for the rule as well (links above). I haven't heard back from Luis yet, he sent the request through email. ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/e106966b-62dc-4070-b7c6-b20b73975fe7)

**Comment by cthomasONRR** [comment]
@Maroyafaied I think audit and reporting are appropriate. I looked through the other topics, and I don't think I would add any more. Let's wait for Luis's review, but I think he will approve this.

**Comment by cthomasONRR** [comment]
From Dane: 

![image](https://user-images.githubusercontent.com/72526208/204656099-b0ca7150-93e7-4afc-8521-6ddd1b740b10.png)

**Comment by cthomasONRR** [comment]
Dane approved and changes are live.
