### ISSUE TITLE
Update & Test Sitemap before submitting to google & bing 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2302]
The xml file was deleted from GitHub, we have to re-add it and also update it with any new pages since July as retest it to validate it. https://dev-onrr-frontend.app.cloud.gov/ONRR-sitemap.xml

link to test https://www.xml-sitemaps.com/validate-xml-sitemap.html

**Comment by Maroyafaied** [comment]
@eelzi-ONRR I re-added it to Github ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/403433c2-fb4e-4167-934e-1a3b6f1c148d)

**Comment by eelzi-ONRR** [comment]
@Maroyafaied I figured out the proper URL structure for the file you added to the CMS and now it validates. Yay teamwork!

Sitemap: [https://dev-onrr-frontend.app.cloud.gov/documents/sitemap.xml](https://dev-onrr-frontend.app.cloud.gov/documents/sitemap.xml)
Verification Tool: [https://www.xml-sitemaps.com/validate-xml-sitemap.html](https://www.xml-sitemaps.com/validate-xml-sitemap.html)

**Comment by Maroyafaied** [comment]
@eelzi-ONRR You're awesome. Thanks for looking into this before we submitted it. I removed the file from GitHub since it's not necessary to have it there.

**Comment by eelzi-ONRR** [comment]
It's been pushed to main, so we can now use this link for the sitemap: [https://onrr.gov/documents/sitemap.xml](https://onrr.gov/documents/sitemap.xml)
