### ISSUE TITLE
USWDS document review and contribute

### ISSUE THREAD

**Issue by eelzi-ONRR** [ONRR/onrr.gov-site#2304]
Help answer questions on how well we are following the principles of USWDS.

The sections highlighted in yellow need particular attention, but feel free to comment on other parts of the document if there's more info to add.

[https://docs.google.com/document/d/1LXkWAUr-34pHuucNWxYnuBUVzJ78h13HNtoC2D1IHqE/edit?usp=sharing](https://docs.google.com/document/d/1LXkWAUr-34pHuucNWxYnuBUVzJ78h13HNtoC2D1IHqE/edit?usp=sharing)

**Comment by cthomasONRR** [comment]
@eelzi-ONRR @Maroyafaied I added a bunch of comments throughout the doc. My text is in green.

**Comment by Maroyafaied** [comment]
@eelzi-ONRR I've added my comments in blue. This is a lot of good information, I think next steps is to clean up the doc and decide if we want this published on our wiki or only stored in our Team's folders.

**Comment by eelzi-ONRR** [comment]
@Maroyafaied Great! I'll close this issue then, and make a new one for making a cleaned-up document with all the info we added to this one
