### ISSUE TITLE
Update CMS section on the wiki

### ISSUE THREAD

**Issue by eelzi-ONRR** [ONRR/onrr.gov-site#2315]
[https://github.com/ONRR/onrr.gov-site/wiki/CMS-user-guide](https://github.com/ONRR/onrr.gov-site/wiki/CMS-user-guide)

Some processes have changed since this was written, and there are some processes and functions that need to be added. Such as:

- Adding files

- Creating buttons

**Comment by cthomasONRR** [comment]
@eelzi-ONRR I added a new section for creating button links: https://github.com/ONRR/onrr.gov-site/wiki/CMS-User-Guide#Adding-button-links

I'll let you update the adding files section :)

**Comment by eelzi-ONRR** [comment]
The button instructions look good!

I updated the adding documents and accordions sections.
[https://github.com/ONRR/onrr.gov-site/wiki/CMS-User-Guide#Adding-documents-and-proper-tagging](https://github.com/ONRR/onrr.gov-site/wiki/CMS-User-Guide#Adding-documents-and-proper-tagging)
[https://github.com/ONRR/onrr.gov-site/wiki/CMS-User-Guide#Setting-up-accordions](https://github.com/ONRR/onrr.gov-site/wiki/CMS-User-Guide#Setting-up-accordions)

 Do you think we should add a section on making changes to the header/footer?

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Those updates look good. Sure, if you want to add a section on the header/footer go for it :) If you can get to it this sprint, we can keep this issue open. Otherwise you can create a new issue for next sprint.
