### ISSUE TITLE
KAULEY VIRTUAL OUTREACH MEETING

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#2317]
KAULEY VIRTUAL OUTREACH MEETING
Thursday, December 15, 2022
1:00 pm to 2:00 pm CST

Location:  By Telephone

DESCRIPTION: The Office of Natural Resources Revenue (ONRR) will be hosting a Virtual (call-in) Outreach Meeting for Indian trust property owners.  Representatives from the Bureau of Land Management (BLM), Bureau of Trust Funds Administration (BTFA), and the Bureau of Indian Affairs (BIA) will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts, and Indian Trust property issues.  The meeting will begin with the brief introduction by the ONRR representative.  Owners will have an opportunity to ask questions with the representatives of the four agencies during the Q&A session 

WHO SHOULD ATTEND:  Indian mineral owners, IIM account holders and other Indian Trust property owners in the Eastern Oklahoma region.
  
OTHER INFORMATION: To reserve a space and get a passcode for this meeting please contact the ONRR OKC Outreach Office toll-free at (800) 354-7015 prior to the meeting. The OKC office hours are Mon.- Fri. from 8:00 am-5:00 pm.

CONTACT: ONRR OKC Outreach Office, Phone: Toll Free (800) 354-7015 or our main number at (405) 879-6050.  EMAIL: [onrroutreachokc@onrr.gov] (https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=onrroutreachokc@onrr.gov)
 
______________________________________________________________________________________________________________________________________
**Please add this to Event Calendar to the existing December events that are already listed there and delete any November events to this area. 
 
https://onrr.gov/events?tabs=indian-outreach-events

**Comment by cthomasONRR** [comment]
@Toddsand21 

Hello, this change is now in preview: https://preview-onrr-frontend.app.cloud.gov/events
Please review and give us approval to go live.

Thanks,
Christine

**Comment by Toddsand21** [comment]
It looks perfect and ready to go!  Thanks for the quick response.

**Comment by cthomasONRR** [comment]
@Toddsand21 Thanks, this update is now live: https://onrr.gov/events
