### ISSUE TITLE
Update Title for Forms

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2322]
Please update the Allowance and Valuation titles on the following page as shown below - https://www.onrr.gov/reporting/revenue?tabs=forms

Update Allowances to read Indian Allowance Forms
Update Valuation to read Indian Valuation Forms

Please let me know if you have any questions!

Thank you!!!!!!!!

**Comment by lpgoldstein** [comment]
@bowlenj Ready for your review: https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=forms

**Comment by bowlenj** [comment]
Perfect, approved to push live!  Thank you!!!!


Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning, and Coordination
Office of Natural Resources Revenue
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.



________________________________
From: lpgoldstein ***@***.***>
Sent: Tuesday, December 6, 2022 2:30 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update Title for Forms (Issue #2322)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C34f5edf7f0704ab1474d08dad76c92fc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638059158577323631%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2Be4DEy6Hd1dwlgwYpSs75YzEfd6gBpZCjb3C0DRQZKs%3D&reserved=0> Ready for your review: https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=forms<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Freporting%2Frevenue%3Ftabs%3Dforms&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C34f5edf7f0704ab1474d08dad76c92fc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638059158577323631%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cZNOtomzdk7N47B1rzGN52Dp2%2BjqNftedsptti6NJZE%3D&reserved=0>

**Comment by lpgoldstein** [comment]
@bowlenj This is live as well: https://www.onrr.gov/reporting/revenue?tabs=forms so closing
