### ISSUE TITLE
Update Civil Penalty amounts

### ISSUE THREAD

**Issue by KristianL3101** [ONRR/onrr.gov-site#2326]
If your request is to update existing document(s), PLEASE [read through this example in our Wiki.](https://github.com/ONRR/onrr.gov-site/wiki/Using-github#example---clear-request-to-update-an-existing-document) 

**Follow these directions:**

* Write a detailed issue title
* Direct us to the exact URL web location for where the update should go
* Direct us to the exact file URL that needs updating
* Specify that this is an update and not a new document that needs to be added
* Make the new document file name match the old file name
* Attach the updated file

THANK YOU
______________________________________________________________________________________________________________________________________
Please update the following: https://onrr.gov/compliance-enforcement/enforcement?tabs=civil-penalties

Please update the amounts in the following two paragraphs under the "Civil Penalties" Banner:

Update:

$1288.00 to $1368.00
$12891.00 to $13693.00
$25780.00 to $27384.00
$64452.00 to $68462.00

"ONRR regulations at [30 CFR part 1241](https://www.ecfr.gov/current/title-30/chapter-XII/subchapter-A/part-1241#sp30.3.1241.b) provide a grace period of at least 20 days for regulatory violations, such as failure to submit reports. Violations not fixed within the grace period are subject to civil penalties until fixed. These penalties can be up to $1,288.00 per day ($12,891.00 per day after 40 days).
Certain violations, such as failure to permit an audit, failure to timely pay royalties, or submission/maintenance of false, inaccurate, or misleading information are subject to higher civil penalties. They can be as much as $25,780.00 or $64,452.00 per violation for each day the violation continues."

Thank you.

**Comment by lpgoldstein** [comment]
@KristianL3101 Ready for your review: https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/enforcement?tabs=civil-penalties

**Comment by lpgoldstein** [comment]
@KristianL3101 live so closing issue.
