### ISSUE TITLE
prod-onrr-frontend failing unless re-ran with SSH

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2327]
This is the error message:

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/d7fa538a-57c5-462d-ad7a-19fecf3b5b7d)

**Comment by greensomes** [comment]
Looking at the logs, I see that the build is killed after the caniuse warning appear. I'm not certain that it's related, but I updated caniuse and caniuse-lite. It's strange that the warnings were not thrown when building for dev.

**Comment by Maroyafaied** [comment]
@greensomes I'm closing this since it seems to be resolved with the fix you did.
