### ISSUE TITLE
Verify google search console 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2328]

**Comment by eelzi-ONRR** [comment]
@Maroyafaied  These two files should be added to the onrr.gov root. Once that's done I can try again to verify in G-Search Console


- **Sitemap XML file:** [sitemap.xml](https://onrr.gov/documents/sitemap.xml)

- **Google Search Console HTML File** - Zenhub and the Teams drive won't accept the file format, so I'll send it to you via chat  


  

**Additional Details for the Google HTML file** 

![image.png](https://images.zenhubusercontent.com/63482c003bae1bf4351c6f26/53352d7c-a2ab-4434-9965-cd355f71c479)

**Comment by Maroyafaied** [comment]
@eelzi-ONRR I also added you, @lpgoldstein and @cthomasONRR as owners. ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/5fe2d5f9-5b0d-4615-9ba9-57262f004c9a)

**Comment by cthomasONRR** [comment]
@Maroyafaied I got confirmation emails and see myself as one of the owners.

**Comment by Maroyafaied** [comment]
@eelzi-ONRR the site has been verified and I submitted the sitemap and it's not showing any errors anymore. If you are seeing the same, please go ahead and close this issue. [Uploading... image.png]

**Comment by eelzi-ONRR** [comment]
Looks good to me!
