### ISSUE TITLE
Fix Press Release Bug 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2330]
Not able to add new press releases to the collection

**Comment by Maroyafaied** [comment]
@R-mohansai any updates on this issue? This is the one I showed when sharing my screen that gives an error when trying ta add a new press release to the collection.

**Comment by R-mohansai** [comment]
I have looked into it -->postgreSQL issue it seems -->will complete this ticket this sprint.

**Comment by R-mohansai** [comment]
I have made a change but not taking any effect in CMS(I am not sure whether triggering main branch updates CMS dev after merging PR.

**Comment by Maroyafaied** [comment]
@R-mohansai I'm not sure what you're asking. Merging dev to master updates the database and gets any code changes in dev to be updated in main, as it always has been the case. To update the cms, you have to trigger the pipeline and add parameters.  It looks like on circle ci, there was a push to update the cms so if your code changes is not taking affect then it's probably not the correct code fix.

**Comment by greensomes** [comment]
Old function: 
```
CREATE OR REPLACE FUNCTION public.function_press_releases_insert()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$ 
DECLARE

existing_url varchar(255);
BEGIN
insert into links ( type, target, url, label, category, title, directus_files_id)  select   'application/press-releases' as type,   filename_download as target,  concat('/press-releases/', filename_download) as url,  press_releases.title as label, 'Reporter Letters' as category, press_releases.title as title, file as directus_files_id  from directus_files where directus_files.id=NEW.file;

RETURN NEW;
END;
$function$
```

**Comment by greensomes** [comment]
Old function:

```
$$function$$
```

**Comment by greensomes** [comment]
New function:

```
CREATE OR REPLACE FUNCTION public.function_press_releases_insert()
 RETURNS trigger
 LANGUAGE plpgsql
AS $$ 
DECLARE

existing_url varchar(255);
BEGIN
insert into links ( type, target, url, label, category, title, directus_files_id)  select   'application/press-releases' as type,   filename_download as target,  concat('/press-releases/', filename_download) as url,  NEW.title as label, 'Press Releases' as category, NEW.title as title, NEW.file as directus_files_id  from directus_files where directus_files.id=NEW.file;

RETURN NEW;
END;
$$;
```

**Comment by greensomes** [comment]
There were bugs in the above function. Closing now.
