### ISSUE TITLE
Send updated org chart and REGA update to Howard for review

### ISSUE THREAD

**Issue by eelzi-ONRR** [ONRR/onrr.gov-site#2331]
**Updated org chart**: [https://onrr.gov/about/organization?tabs=organization-chart](https://onrr.gov/about/organization?tabs=organization-chart)

- Changed CEVA to REGA

- Changed Shayna to program manager instead of SE

- Updates to April and Yvette's title

- Added Linda as Western Audit Management

**REGA tab**: [https://onrr.gov/about/organization?tabs=leadership,research-enforcement-guidance-appeals](https://onrr.gov/about/organization?tabs=leadership,research-enforcement-guidance-appeals)

- Updated the REGA tab name and the first sentence of Bonnie's bio

**Comment by Maroyafaied** [comment]
@eelzi-ONRR I have an email drafted to Howard but will send it tomorrow. I noticed in Bonnie's tab, we need to take out "Indian Trust Outreach & Coordination" , and add " & Guidance " to "Royalty Valuation", and change "Analytics & Risk Management" to "Research & Analytics".  Please make those changes. Thanks

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/152a2a0a-f61d-433d-8bbf-9393a5e8dc4d)

**Comment by eelzi-ONRR** [comment]
@Maroyafaied I made those changes and you can view them in dev: [https://dev-onrr-frontend.app.cloud.gov/about/organization?tabs=leadership,research-enforcement-guidance-appeals](https://dev-onrr-frontend.app.cloud.gov/about/organization?tabs=leadership,research-enforcement-guidance-appeals)

**Comment by Maroyafaied** [comment]
@eelzi-ONRR looks good, please let me know when the changes are on the live site and I'll send the email to Howard. Thanks

**Comment by eelzi-ONRR** [comment]
@Maroyafaied The changes are on the live site now

**Comment by Maroyafaied** [comment]
Email sent, I will keep this open until we receive a response and approval .

**Comment by Maroyafaied** [comment]
Approved by Howard.
