### ISSUE TITLE
User Research on Pricing Table Filters

### ISSUE THREAD

**Issue by eelzi-ONRR** [ONRR/onrr.gov-site#2333]
Internal users think they need to refresh the page to apply changes to the table filters. Confusion has been reported on all the tables except NYMEX (NYMEX only has 1 filter option - the others have 2).

[https://www.onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone](https://www.onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone)

**Comment by Maroyafaied** [comment]
@eelzi-ONRR is this issue a duplicate? If so, please go ahead and close it. Thanks

**Comment by eelzi-ONRR** [comment]
Duplicate issue
