### ISSUE TITLE
URGENT (TIME SENSITIVE): Update to IESC page on onrr.gov

### ISSUE THREAD

**Issue by ONRRamandagarrison** [ONRR/onrr.gov-site#234]
On the page:  https://www.onrr.gov/IndianServices/indian-energy-service-center.htm

The following information and attachment need to be added by **8AM MT on Thursday, 7/30/20** if possible. This notice will allow trust beneficiaries to contact the Fort Berthold Agency to attend the webex training.

[Dear Landowers Letter ROW Market Analysis.pdf](https://github.com/ONRR/onrr.gov-site/files/4997417/Dear.Landowers.Letter.ROW.Market.Analysis.pdf)

Also, on the page, the following information should be added:

Fort Berthold Agency WebEx Training: Market Analysis for ROWs on FBIR
Thursday, July 30th at 2:00PM CST
Thursday, August 6th at 2:00PM CST

To obtain a WebEx invite, please contact Thomas Burr at Thomas.Burr@bia.gov or Lonnie Wright at Lonnie.Wright@bia.gov

**Comment by lpgoldstein** [comment]
@ONRRamandagarrison For your review: http://2017onrr/IndianServices/indian-energy-service-center.htm

**Comment by ONRRamandagarrison** [comment]
Looks great! Thank you!

Amanda Garrison

Supervisory Minerals Revenue Specialist
Indian Energy Service Center
P: (720) 595-2025

**Comment by lpgoldstein** [comment]
@ONRRamandagarrison It should be live soon.
