### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov – December 2022

### ISSUE THREAD

**Issue by StaceyKaiser** [ONRR/onrr.gov-site#2342]
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “December 2022 Lease Agreement XREF.txt" and "December 2022 Lease Agreement XREF.xlsx”.  The data was queried from the system on 12/06/2022.

[December 2022 Lease Agreement XREF.txt](https://github.com/ONRR/onrr.gov-site/files/10169047/December.2022.Lease.Agreement.XREF.txt)

[December 2022 Lease Agreement XREF.xlsx](https://github.com/ONRR/onrr.gov-site/files/10169609/December.2022.Lease.Agreement.XREF.xlsx)

**Comment by cthomasONRR** [comment]
@StaceyKaiser 

These changes are on the dev site: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

Please review and give us your approval to go live.

Thanks,
Christine

**Comment by StaceyKaiser** [comment]
@cthomasONRR 

The changes look good. Please move to the live site.  Thanks!

Stacey

**Comment by cthomasONRR** [comment]
@StaceyKaiser Great! These changes are now live: https://onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

Thanks,
Christine
