### ISSUE TITLE
Indian pricing

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2344]
A user submitted an IT ticket saying they are seeing different prices for Indian, here's the screen shots they provided. 

@lpgoldstein can you please see if you can replicate this issue and confirm if the correct prices are shown on the site. Thanks

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/1a87b6bc-c831-4a93-8327-8fd5b048dcf4)

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/39ca15f8-9608-41ed-9a81-4ccfe0b659bb)

**Comment by lpgoldstein** [comment]
![image](https://user-images.githubusercontent.com/39419003/206230296-61c36f57-a66f-4a1a-be0c-18a8dbbefb44.png)
Confirmed that these prices are correct with the original data spreadsheet

**Comment by lpgoldstein** [comment]
These prices are correct as well 
![image](https://user-images.githubusercontent.com/39419003/206233180-86ae823b-1870-4c9a-a02c-19272e407d35.png)

**Comment by Maroyafaied** [comment]
@lpgoldstein how about this screenshot? it shows different a different price for March for Fort Berthold as $2.24 instead of $2.94.  Can you check on Edge as well. 
![image](https://user-images.githubusercontent.com/40175688/206235356-f5a6034e-d903-490d-b569-a5b089781d83.png)

**Comment by lpgoldstein** [comment]
edge showing correct prices as well - trying to filter different ways to get the error to happen again 
![image](https://user-images.githubusercontent.com/39419003/206238399-93e1faa0-6368-43ce-a329-a6ebab29afaf.png)

**Comment by lpgoldstein** [comment]
also correct here in edge 
![image](https://user-images.githubusercontent.com/39419003/206238969-b175cca7-6b30-4a78-b778-30a440584cf7.png)
