### ISSUE TITLE
Update Dec Indian index zone prices on onrr.gov

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#2348]
Good afternoon,

Please update onrr.gov with the December Indian index zone prices available on the 'Data for ONRR.gov' spreadsheet.

Thanks!

@sudarr

**Comment by lpgoldstein** [comment]
Ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone @boices

**Comment by boices** [comment]
That's perfect--thanks again!

**Comment by lpgoldstein** [comment]
@boices It's live! https://onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone
