### ISSUE TITLE
November NYMEX prices for ONRR.gov

### ISSUE THREAD

**Issue by penvosej** [ONRR/onrr.gov-site#2351]
Hello,
The most recent NYMEX prices are ready to be posted to ONRR.gov. I've attached the file with the data. Thank you!
@sudarr
[NYMEX112022.xlsx](https://github.com/ONRR/onrr.gov-site/files/10197798/NYMEX112022.xlsx)

**Comment by lpgoldstein** [comment]
@penvosej Ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices

**Comment by penvosej** [comment]
Man, Lindsay, you guys are always so ON TOP of this! Thanks for updating the site. The changes look good.

From: lpgoldstein ***@***.***>
Sent: Friday, December 9, 2022 1:08 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] November NYMEX prices for ONRR.gov (Issue #2351)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpenvosej&data=05%7C01%7CJessica.Penvose%40onrr.gov%7Cc596f0d9c42744ba6ecd08dada2105f7%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638062132624772591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FY9xM8sDYIteI4TjY4gphOquCeA4Cqbp7mVNGzBTXbA%3D&reserved=0> Ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Freferences%2Fvaluation%3Ftabs%3Dpricing%2Cnymex-oil-prices&data=05%7C01%7CJessica.Penvose%40onrr.gov%7Cc596f0d9c42744ba6ecd08dada2105f7%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638062132624928805%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zCj5AR9Oe1FdSeUWV8i2RzFVDXQqT0Ac8vlCzSZhLds%3D&reserved=0>

-

**Comment by lpgoldstein** [comment]
@penvosej Prices are live! https://onrr.gov/references/valuation?tabs=pricing,nymex-oil-prices

**Comment by penvosej** [comment]
Thanks, Lindsay!

From: lpgoldstein ***@***.***>
Sent: Friday, December 9, 2022 3:23 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] November NYMEX prices for ONRR.gov (Issue #2351)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpenvosej&data=05%7C01%7CJessica.Penvose%40onrr.gov%7Cf754b3acc67849dc29f808dada33f779%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638062213993814528%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cyRsFUUfQDF9mDD200QGazu8bQUgCNUu15j4DExOVyA%3D&reserved=0> Prices are live! https://onrr.gov/references/valuation?tabs=pricing,nymex-oil-prices<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fonrr.gov%2Freferences%2Fvaluation%3Ftabs%3Dpricing%2Cnymex-oil-prices&data=05%7C01%7CJessica.Penvose%40onrr.gov%7Cf754b3acc67849dc29f808dada33f779%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638062213993814528%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9%2F9hmwYiljZXY%2FHuIQMru3lLSu6jGYAzI2EIVyNaIX8%3D&reserved=0>

-
