### ISSUE TITLE
November 2022 IBMP Price

### ISSUE THREAD

**Issue by damionschulte** [ONRR/onrr.gov-site#2355]
All I have updated the November 22 IBMP Prices on the data for ONRR sheet in the OneDrive. Also attached are the prices in a spreadsheet that is formatted per your request.  Can you please have the prices published to website?  Thanks 
[November 22 IBMP For GitHub.xlsx](https://github.com/ONRR/onrr.gov-site/files/10211430/November.22.IBMP.For.GitHub.xlsx)

@sudarr

**Comment by lpgoldstein** [comment]
@damionschulte ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-oil-major-portion

**Comment by damionschulte** [comment]
Prices look great!  Thank you!

From: lpgoldstein ***@***.***>
Sent: Monday, December 12, 2022 12:46 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] November 2022 IBMP Price (Issue #2355)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@damionschulte<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdamionschulte&data=05%7C01%7Cdamion.schulte%40onrr.gov%7Cc9e8ea0b4fb9411e3b2508dadc79763f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638064711482927917%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tU5XAlEyXbrQG7XEZY7BbxQ051YbaXPPKvJZvptB8TY%3D&reserved=0> ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-oil-major-portion<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Freferences%2Fvaluation%3Ftabs%3Dpricing%2Cindian-oil-major-portion&data=05%7C01%7Cdamion.schulte%40onrr.gov%7Cc9e8ea0b4fb9411e3b2508dadc79763f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638064711482927917%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AaCnbfSJEBnVqEZh2Gx%2BAL00QV5G5hfAFwLcH7w9Y5k%3D&reserved=0>

-

**Comment by lpgoldstein** [comment]
@damionschulte Live! https://onrr.gov/references/valuation?tabs=pricing,indian-oil-major-portion

**Comment by damionschulte** [comment]
Thank you again!

From: lpgoldstein ***@***.***>
Sent: Monday, December 12, 2022 1:33 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] November 2022 IBMP Price (Issue #2355)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@damionschulte<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdamionschulte&data=05%7C01%7Cdamion.schulte%40onrr.gov%7C22422977bae04e920d8108dadc8004e0%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638064739642077820%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Gi5ZNEGZ1tZHns0O7ZowgUVzphvFNlZi2IC8uQfCKJc%3D&reserved=0> Live! https://onrr.gov/references/valuation?tabs=pricing,indian-oil-major-portion<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fonrr.gov%2Freferences%2Fvaluation%3Ftabs%3Dpricing%2Cindian-oil-major-portion&data=05%7C01%7Cdamion.schulte%40onrr.gov%7C22422977bae04e920d8108dadc8004e0%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638064739642077820%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QWvZ2KOMnUn7ZKiClAUU1kPCyzsuu%2FKnXTVJwYZkpmc%3D&reserved=0>

-
