### ISSUE TITLE
URGENT (TIME SENSITIVE): Add WebEx Link to onrr.gov

### ISSUE THREAD

**Issue by ONRRamandagarrison** [ONRR/onrr.gov-site#236]
So sorry, but can the link below get added to the updates that I requested yesterday:

https://teams.microsoft.com/l/meetup-join/19%3a4c7a8ea8f1a942c18a5dd421bdc04045%40thread.skype/1595951693238?context=%7b%22Tid%22%3a%220693b5ba-4b18-4d7b-9341-f32f400a5494%22%2c%22Oid%22%3a%2210f8fcce-bd52-4144-a53f-4eb329e6c1d2%22%7d

- Make the hyperlink say "FBA Market Analysis Meeting"

![image](https://user-images.githubusercontent.com/62029054/88947592-f7354680-d24d-11ea-9f5e-24f94ea9e50a.png)

Fort Berthold Agency WebEx Training: Market Analysis for ROWs on FBIR
Thursday, July 30th at 2:00PM CST    (Add link here) "FBA Market Analysis Meeting"
Thursday, August 6th at 2:00PM CST

If you have any questions or need assistance, please contact:

Thomas Burr
 Thomas.Burr@bia.gov
Lonnie Wright
 Lonnie.Wright@bia.gov

**Comment by jennmalcolm** [comment]
Please review in dev @ONRRamandagarrison 

http://2017onrr/IndianServices/indian-energy-service-center.htm

**Comment by jennmalcolm** [comment]
I will just make it live since I know it is urgent. If there are issues with it, let me know.
