### ISSUE TITLE
Updated PDF  document ready for publishing

### ISSUE THREAD

**Issue by NSweeneyonrr** [ONRR/onrr.gov-site#2360]
Greetings,

The attached document is an updated version that needs to go live on onrr.gov.  The current document is located under: Reporting >Oil and Gas Revenue >References >Troubleshooting.  It is the third bullet down titled "Form ONRR-2014 Complete List of Edits."

This attachment needs to replace what is currently displayed.

Thank you!
[Form ONRR-2014 Edit Listing.pdf](https://github.com/ONRR/onrr.gov-site/files/10221162/Form.ONRR-2014.Edit.Listing.pdf)

**Comment by cthomasONRR** [comment]
@NSweeneyonrr 

Hello, 

This document is updated on the dev site: https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=troubleshooting&panel=i-need-to-troubleshoot-errors-in-my-2014

Please review and give us your approval to go live.

Thanks,
Christine

**Comment by NSweeneyonrr** [comment]
I've reviewed the dev site and everything looks good. 

I approve for this to go live.

Thank you!
Nicole

**Comment by cthomasONRR** [comment]
@NSweeneyonrr 

Great! This is live: https://onrr.gov/reporting/revenue?tabs=troubleshooting&panel=i-need-to-troubleshoot-errors-in-my-2014

Thanks,
Christine
