### ISSUE TITLE
Annual remote work

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2361]
Reminder to renew remote work agreements

**Comment by cthomasONRR** [comment]
I looked into the documents that were signed and submitted. I think the employee and direct supervisor just need to sign the "ONRR Remote Work Agreement FINAL" PDF. The last page has a renewal signature table:
![image](https://user-images.githubusercontent.com/72526208/210432018-9afee215-a403-4fa2-927a-26e5c4ce6d3a.png)

**Comment by Maroyafaied** [comment]
@cthomasONRR I signed yours and sent to Heidi.

**Comment by Maroyafaied** [comment]
@eelzi-ONRR I reviewed your application and replied with minor changes. Thanks
