### ISSUE TITLE
Update Indian A/R & Billing contact list

### ISSUE THREAD

**Issue by ChrisDavisONRR** [ONRR/onrr.gov-site#2364]
Happy holidays,

I'm not sure if the process to update a contact list is the same with the new site (we don't seem to have a Word/PDF anymore...). 

But, I am requesting an update to the Indian Accounts Receivable & Billing contacts found here:
https://onrr.gov/about/contact/paying-contacts?tabs=contacts,indian-accounts-receivable

I've attached the list.  Nothing else on the page would change, except the contact person for some companies (example; adding a backup for Cond-End companies, and swapping Sabrina and Ishwar's work assignments). 

Thank you!
Chris Davis
Christopher.Davis@onrr.gov
[FSIndianCoAssign_122022.pdf](https://github.com/ONRR/onrr.gov-site/files/10230772/FSIndianCoAssign_122022.pdf)

**Comment by cthomasONRR** [comment]
@ChrisDavisONRR Hi Chris, we no longer upload the PDF contact lists anymore. Could you outline what contacts are changing, and we can make those updates within our new Content Management System.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@ChrisDavisONRR I did a quick peruse... can you verify that the highlighted contacts are the only ones changing? Thanks!
![image](https://user-images.githubusercontent.com/72526208/207694269-bf5a5a29-e321-49b7-bb06-587898e00f4a.png)

**Comment by eelzi-ONRR** [comment]
@ChrisDavisONRR We've made the changes that Christine highlighted above and they're ready for you to review: [https://dev-onrr-frontend.app.cloud.gov/paying/contacts-paying?tabs=contacts,indian-accounts-receivable](https://dev-onrr-frontend.app.cloud.gov/paying/contacts-paying?tabs=contacts,indian-accounts-receivable)

Please let us know if these look good, and if there are any other changes we need to make. 

Thanks!
Erin

**Comment by ChrisDavisONRR** [comment]
Yes that looks great, thanks!

**Comment by cthomasONRR** [comment]
@ChrisDavisONRR Thanks for the confirmation! 
These updates are live: https://onrr.gov/about/contact/paying-contacts?tabs=contacts,indian-accounts-receivable
