### ISSUE TITLE
Create a sharable document of how we use USWDS principles

### ISSUE THREAD

**Issue by eelzi-ONRR** [ONRR/onrr.gov-site#2366]
Take the information we gathered and create a version that can be shared on the wiki.

Info gathering doc: [https://docs.google.com/document/d/1LXkWAUr-34pHuucNWxYnuBUVzJ78h13HNtoC2D1IHqE/edit](https://docs.google.com/document/d/1LXkWAUr-34pHuucNWxYnuBUVzJ78h13HNtoC2D1IHqE/edit)

**Comment by eelzi-ONRR** [comment]
@Maroyafaied Draft of the write up is ready for review: https://doimspp-my.sharepoint.com/:w:/g/personal/elzie_mms_gov/EYUYvjY5MqRCrlemQ-q2nf0BbGrlTNLUv0E8Ip-sDlqafQ?e=0CG0pV 

@lpgoldstein also offered to review when she's back

**Comment by Maroyafaied** [comment]
@eelzi-ONRR This is GREAT! I reviewed and had minor comments. I think this can easily be turned into a blog post, we can discuss if you're comfortable with that.
