### ISSUE TITLE
Change RV Sample Statements images to blue letters

### ISSUE THREAD

**Issue by eelzi-ONRR** [ONRR/onrr.gov-site#2367]
We can keep the accessible linked pdfs as is, and just change the embedded images of the statements to minimize the amount of work needed to use blue text on these pages. 

@cthomasONRR I got the blues to match. Let me know what you think before I do the others.

[https://preview-onrr-frontend.app.cloud.gov/references/valuation/rpmp-act?tabs=sample-statement](https://preview-onrr-frontend.app.cloud.gov/references/valuation/rpmp-act?tabs=sample-statement)

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Just recapping what we discussed at standup: The blue looks awesome! The black numbers on the sample statement are small and blurry for me. If possible to modify, the image dimensions on the sample statement here are much easier to read: https://preview-onrr-frontend.app.cloud.gov/references/valuation/ipmp?tabs=sample-statement

**Comment by eelzi-ONRR** [comment]
@cthomasONRR The 4 existing sample pages are done. Can you have a look and check my work? Preview has been weird today so they're in dev

[https://dev-onrr-frontend.app.cloud.gov/references/valuation/rpmp-act?tabs=sample-statement](https://dev-onrr-frontend.app.cloud.gov/references/valuation/rpmp-act?tabs=sample-statement)

[https://dev-onrr-frontend.app.cloud.gov/references/valuation/ipmp?tabs=sample-statement](https://dev-onrr-frontend.app.cloud.gov/references/valuation/ipmp?tabs=sample-statement)

[https://dev-onrr-frontend.app.cloud.gov/references/valuation/pop-example?tabs=sample-statement](https://dev-onrr-frontend.app.cloud.gov/references/valuation/pop-example?tabs=sample-statement)

[https://dev-onrr-frontend.app.cloud.gov/references/valuation/processed-gas-example?tabs=sample-statement](https://dev-onrr-frontend.app.cloud.gov/references/valuation/processed-gas-example?tabs=sample-statement)

**Comment by cthomasONRR** [comment]
@eelzi-ONRR They look great! I'll start working on getting the blue color incorporated within the Detailed Example tab.

**Comment by cthomasONRR** [comment]
@eelzi-ONRR The Detailed Example tabs are updated and ready for your review :)

**Comment by eelzi-ONRR** [comment]
@cthomasONRR Looks good! I'm closing this issue
