### ISSUE TITLE
URGENT: Update to onrr.gov for IESC 

### ISSUE THREAD

**Issue by ONRRamandagarrison** [ONRR/onrr.gov-site#237]
![image](https://user-images.githubusercontent.com/62029054/89193384-222bdd00-d563-11ea-969e-a97bfacc75a5.png)

Add WebEx Link:  https://onrr.webex.com/onrr/j.php?MTID=m16ccc645dd190850d3918b2c07735466

Fort Berthold Agency WebEx Training: Market Analysis for ROWs on FBIR
Thursday, August 6th at 2:00PM CST
(Add link here) Label it: "FBA Market Analysis Meeting"

If you have any questions or need assistance, please contact:

Thomas Burr
Thomas.Burr@bia.gov
Lonnie Wright
Lonnie.Wright@bia.gov

**Comment by lpgoldstein** [comment]
Please review @ONRRamandagarrison http://2017onrr/IndianServices/indian-energy-service-center.htm

**Comment by ONRRamandagarrison** [comment]
Is there a way to center all the text?

Other than that, it looks great! Thank you for your help and your speed!

Amanda Garrison

Supervisory Minerals Revenue Specialist
Indian Energy Service Center
P: (720) 595-2025

**Comment by lpgoldstein** [comment]
@ONRRamandagarrison check this out http://2017onrr/IndianServices/indian-energy-service-center.htm

**Comment by ONRRamandagarrison** [comment]
Perfect!

Thank you,
Amanda

Amanda Garrison

Supervisory Minerals Revenue Specialist
Indian Energy Service Center
P: (720) 595-2025

**Comment by lpgoldstein** [comment]
@ONRRamandagarrison It should be live at 10:30. I'm in a meeting from 10:30-11 but will check back after that.
