### ISSUE TITLE
DISC Contacts Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2370]
Please update the contacts for Royalty, Offshore Production, Onshore Production, and Lease & Agreements using the Shared Contacts spreadsheet.  All changes have been highlighted on the spreadsheet, however Hilcorp was removed from the Onshore Production list and 2 new companies were added to the Offshore Production list, those are highlighted.  

Please make the changes to the webpages listed below:
Lease & Agreement - https://www.onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts
Onshore & Offshore Production - https://www.onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production
Royalty - https://www.onrr.gov/about/contact/royalty-contacts?tabs=contacts

Thank You
Jessica Bowlen

**Comment by cthomasONRR** [comment]
@bowlenj 

These updates are on the dev site:
https://onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production
https://onrr.gov/about/contact/production-contacts?tabs=contacts,offshore-production
https://onrr.gov/about/contact/royalty-contacts?tabs=contacts
https://onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts

Please review and give us your approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj 

SORRY- dev site links
https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production
https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,offshore-production
https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?tabs=contacts
https://dev-onrr-frontend.app.cloud.gov/about/contact/royalty-contacts?tabs=contacts

**Comment by bowlenj** [comment]
This looks great, approved to push live!  Thank you so much for getting that done so quickly!


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Christine Thomas ***@***.***>
Sent: Monday, December 19, 2022 9:09 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] DISC Contacts Update (Issue #2370)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cc77427d225584fbe748008dae1db5be2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638070629510159270%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VIj3qekLCwNezuaUsBmshFdaKPX6XpwJTP3s26581fs%3D&reserved=0>

SORRY- dev site links
https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Fabout%2Fcontact%2Fproduction-contacts%3Ftabs%3Dcontacts%2Conshore-production&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cc77427d225584fbe748008dae1db5be2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638070629510159270%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IAkShTKEF5GOBPMfyX58Xs22hOFFAi0pGFslaGjfejY%3D&reserved=0>
https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,offshore-production<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Fabout%2Fcontact%2Fproduction-contacts%3Ftabs%3Dcontacts%2Coffshore-production&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cc77427d225584fbe748008dae1db5be2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638070629510159270%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=d1o3SELClt6uFHmRSzEoNHW1YHPKTvPYOzn2TStSFNg%3D&reserved=0>
https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts?tabs=contacts<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Fabout%2Fcontact%2Flease-agreement-contacts%3Ftabs%3Dcontacts&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cc77427d225584fbe748008dae1db5be2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638070629510315494%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OuNR3IUoK9s89G6s22pyLs%2FeBt2yLqhU%2BPzrseaW6ZU%3D&reserved=0>
https://dev-onrr-frontend.app.cloud.gov/about/contact/royalty-contacts?tabs=contacts<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Fabout%2Fcontact%2Froyalty-contacts%3Ftabs%3Dcontacts&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cc77427d225584fbe748008dae1db5be2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638070629510315494%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pA7WdD9sn8EtnhSQrEywNXnkpptQkVvfW86RjeRRhdw%3D&reserved=0>

**Comment by cthomasONRR** [comment]
@bowlenj 

Great! These changes are live:
https://onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production
https://onrr.gov/about/contact/production-contacts?tabs=contacts,offshore-production
https://onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts
https://onrr.gov/about/contact/royalty-contacts?tabs=contacts
