### ISSUE TITLE
Investigate search results showing up old urls 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2372]

**Comment by eelzi-ONRR** [comment]
I've dug into the Bing Webmaster Tools, and it shows that all of our new URLs are discovered by Bing, but "The inspected URL is known to Bing but has some issues which are preventing indexation."

The Webmaster dashboards don't provide any details of what the issues are. There is a Webmaster tool that allows you to submit a URL one by one to request that Bing indexes it - I've summited a handful to see if that works and if they are able to provide us with details we can use to fix the rest. I've also opened a support ticket with Bing.

**Comment by Maroyafaied** [comment]
@eelzi-ONRR I took the same approach and submitted one url to be indexed/scanned and it was the main url for the website and this is the report with errors that I got. Just FYI incase it's helpful. 
![image](https://user-images.githubusercontent.com/40175688/208539162-4e40e6d9-97ec-4f97-956f-ac26e1f900b7.png)

**Comment by Maroyafaied** [comment]
@eelzi-ONRR I also submitted this url and it seems to be pulling up in search results now. So maybe we have to compile a list of all the urls and submit them. We probably have most of the new  urls listed within the redirect excel sheets. 
![image](https://user-images.githubusercontent.com/40175688/208541717-d779a5f2-bf7b-4d5f-9234-fde859cac96e.png)
![image](https://user-images.githubusercontent.com/40175688/208541766-7ff9bb69-d2f0-4cfa-9f38-4884a48062b9.png)

**Comment by eelzi-ONRR** [comment]
@Maroyafaied Ah great! That was my thought - to see if the ones I submitted today get indexed and if so then submit the rest. The site map lists the URLS, so I can take them from there.

I'm come across a lot of discussion boards that indicate this is pretty common - Bing essentially blocking sites from indexing without explanation. Once people are able to get Bing support to respond, then they lift the block, but people have said that can take months. So looks like submitting the URLs one by one is a quicker method! We only have 150ish or so URLs, so it won't be too bad to do them all

**Comment by Maroyafaied** [comment]
@eelzi-ONRR  I just tested it out and you can submit more than one url at a time, they just have to be in their own line but copying and pasting from a spreadsheet will put them in their own line. The 159 urls in the sitemap don't include links to documents and such, so we'll probably have to submit those as well which will be quite a lot. OR we can submit the 159 main page urls and the rest can be done when Bing lifts the block.  I'd suggest looking at the redirect spreadsheet and deciding if it's easier to copy urls from there since I believe it has the main page urls as well.  I'll leave it up to you what you decide but at the very least, we should submit the 159 main pages urls in the sitemap.

![image](https://user-images.githubusercontent.com/40175688/208544941-710d10cc-b641-4640-b28d-38f2eb5630ef.png)

**Comment by Maroyafaied** [comment]
We updated the sitemap and will re-submit to google and bing. @eelzi-ONRR also researched and suggested creating a robot.txt file to optimize the site crawling and indexing, I created an issue for that next sprint.
