### ISSUE TITLE
Configure CMS for local development 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2375]

**Comment by greensomes** [comment]
I'm getting the Directus/Vue example up and running locally. I'm running into the same issues as with the CMS.

Directus has a dependency on sharp that does not run on Mac M1 chips. I'm looking into potential workarounds.

**Comment by greensomes** [comment]
I discovered that a locally installed version of libvips was interfering with the prebuilt version of libvips. I removed the local version via `brew uninstall libvips` and the example installation of libvips works.

**Comment by greensomes** [comment]
The `.env` file used for local development must have keys and values for `POSTGRES_USER`, `POSTGRES_PASSWORD`, and `POSTGRES_DB`.

**Comment by greensomes** [comment]
After update `.env` (see previous comment), I encounter the following error when running `rpm run start` from the repo root:

`Database doesn't have Directus tables installed.`

Looking into this now.

**Comment by greensomes** [comment]
From the `database` directory, I ran `docker-compose up`. In a separate console window, I connected to the docker container via `docker exec -it bash`. Once connected, run `pg_restore -U directus -v -d directus database_backup.new.pg` from the `backup` directory.

**Comment by greensomes** [comment]
The previous issue was resolved by steps in previous comment. The latest error is `[cache] Error: getaddrinfo ENOTFOUND cache`. I've observed there is no redis docker container running. Looking into this now...

**Comment by greensomes** [comment]
The redis cache container failed to start because of downstream failure in the cms docker-compose. This failure was because the directus container was unable to connect to the database. After changing the`DB_HOST` entry in `.env` from `localhost` to `host.docker.internal`, the cms container was able to connect and start cleanly.

**Comment by greensomes** [comment]
So, I'm seeing two issues now. After getting the directus, redis, and database docker containers up, the directus admin is resulting in a white screen at `http://localhost:8055`. The error console is showing ssl errors. 🤔

The other issue is that there is no docker-compose for the front end. I think we want that. I'll look into that as well.

**Comment by greensomes** [comment]
We don't need the frontend to run in docker. Per the README document, `npm run serve` from the `frontend` directory works.

**Comment by greensomes** [comment]
I've got the CMS running and the frontend running. There are internal server errors thrown in the frontend, but the menu query is returning data and rendering in the frontend. I'm going to look at the internal server errors before closing this issue out. Once closed, I will update instructions in the README to include all information necessary to get local development up and running.

**Comment by greensomes** [comment]
I resolved the internal server error by adding `MAX_RELATIONAL_DEPTH=2000` to my local `.env` file. All is hunky dory with running the site locally now. Will make sure everything is properly documented.
