### ISSUE TITLE
PAWNEE AREA VIRTUAL MEETING

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#2377]
[EVENT CAL OKC JAN 2023.docx](https://github.com/ONRR/onrr.gov-site/files/10273169/EVENT.CAL.OKC.JAN.2023.docx)

Please see the attached file to be used for our new issue to be added to the Indian Outreach and Events Tab below.  
https://www.onrr.gov/events?tabs=indian-outreach-events

THANK YOU
______________________________________________________________________________________________________________________________________
**ADD YOUR ISSUE INSTRUCTIONS HERE:**

**Comment by eelzi-ONRR** [comment]
@Toddsand21 We've removed the past events and added the January one. It's ready for you to review:

[https://dev-onrr-frontend.app.cloud.gov/events?tabs=indian-outreach-events](https://dev-onrr-frontend.app.cloud.gov/events?tabs=indian-outreach-events)

**Comment by Toddsand21** [comment]
What happened to the other 2 events for January?  There were 3 altogether?

**Comment by eelzi-ONRR** [comment]
@Toddsand21 Sorry! All 3 events are on the page now: 

[https://dev-onrr-frontend.app.cloud.gov/events?tabs=indian-outreach-events](https://dev-onrr-frontend.app.cloud.gov/events?tabs=indian-outreach-events)

**Comment by Toddsand21** [comment]
I can see all 3 of them now.  Thanks, it looks fine and ready to go!

**Comment by eelzi-ONRR** [comment]
@Toddsand21 Great! The changes are now on the live site. [https://onrr.gov/events?tabs=indian-outreach-events](https://onrr.gov/events?tabs=indian-outreach-events)

Thanks!
