### ISSUE TITLE
Update sitemap to include all urls

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2381]
@eelzi-ONRR I opened up this issue based on your update in issue  issue #2372. 

The current sitemap only includes 159 urls for the main pages, we were advised to update the sitemap to include all links on the website.

**Comment by eelzi-ONRR** [comment]
Sitemap created with 263 URLS pulled from page export and redirect export in CMS, plus the content tracking spreadsheet. All links also submitted to bing separately for indexing. Many of the tabbed URLS in the sitemap caused it to fail so they were removed. 

Followed by issue #2385 to submit additional tabbed URLs to Bing
