### ISSUE TITLE
Update phone number

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2382]
@eelzi-ONRR This request came in through an IT help desk ticket. I've emailed the requestor from onrrweb mailbox and cc'd you.  Once you make the update please send her the link to dev to review by email. 

If your request is to add or update contact information, PLEASE [read through this example in our Wiki.]
"I am requesting the main number on ONRR.GOV for the Tulsa location to be updated to our main line number.

 Right now it has the phone number as 918-615-5230, this is incorrect

The correct number should be 918-615-5050.

 Please reach out to me or Cassady Blakesley  with any questions."

**Comment by Maroyafaied** [comment]
@eelzi-ONRR I believe she's referencing the phone number on this page for the Tulsa card. https://onrr.gov/about/office-locations

**Comment by eelzi-ONRR** [comment]
Reviewed and approved via email.
