### ISSUE TITLE
Create Robots.txt file for Sitemap 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2383]
This will help search engines find the Sitemap. It optimizes site crawling and indexing.

**Comment by Maroyafaied** [comment]
@eelzi-ONRR please review in dev https://dev-onrr-frontend.app.cloud.gov/robots.txt

I did some research, and you can specify for a search engine not to index a specific url but I don't think we need to do that and we can simply list the urls of the sitemap. I also looked at robots.txt file for search.gov and the only have the sitemap url listed https://search.gov/robots.txt

If this looks good to you , I'll add the file to the main branch. Thanks

**Comment by eelzi-ONRR** [comment]
@Maroyafaied Do you think we should block the beta site from being indexed? It's showing up in results and getting clicks. I've checked and beta still updates to match to prod, so it's not a huge problem that people are finding it, but it might be good to remove it from indexing and search results.

**Comment by Maroyafaied** [comment]
@eelzi-ONRR Please review again, from the articles I read we should use an "*" for the user-agent command line to direct all search engines without having to specify each one and I put the beta link in the disallow command line.   
![image](https://user-images.githubusercontent.com/40175688/211906156-bd28a82f-22f5-4dd8-9dae-f12555994165.png)

**Comment by eelzi-ONRR** [comment]
@Maroyafaied Looks good! The articles I've looked at also say this format for user agent, disallow and sitemaps is correct

**Comment by Maroyafaied** [comment]
@eelzi-ONRR this is live. https://onrr.gov/robots.txt
