### ISSUE TITLE
 Update files - Production Reporting References, Offshore

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2386]
@eelzi-ONRR This request came through onrrweb@onrr.gov. Please let me know if you need help with it. You can email Maria back to approve the changes.  The files that need to be updated live on this page [https://onrr.gov/references/reference-lists?tabs=production-reporting-references](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fonrr.gov%2Freferences%2Freference-lists%3Ftabs%3Dproduction-reporting-references&data=05%7C01%7CONRRWeb%40onrr.gov%7C0610d452b77844cadccb08dae906366a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638078510276746409%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DMEKR00pT28Ffvlmm9VGzg9FT6XoWKTsPQLm8dGUYZE%3D&reserved=0)

**Comment by eelzi-ONRR** [comment]
Reviewed and approved via email
