### ISSUE TITLE
Next steps for accessibility

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#239]
- [x] Prepare draft email for Howard to send (Lindsay)

- [x] Prepare presentation for OLT (Shannon and Maroya)

- [x] Contact Christina and Iris about getting admins training (Jennifer)

**Comment by lpgoldstein** [comment]
email for your review - please edit as needed @jennmalcolm @mcharg @Maroyafaied https://doimspp-my.sharepoint.com/personal/mchargs_mms_gov/_layouts/15/doc.aspx?sourcedoc={0d144f2b-aa96-4203-9582-9f1d8e477d7f}&action=edit

**Comment by Maroyafaied** [comment]
@lpgoldstein looks good, I added a comment to mention the instructions on the wiki to assist with checks.

**Comment by mcharg** [comment]
@lpgoldstein Looks good. I made a couple edits.

**Comment by jennmalcolm** [comment]
Looks good. I added 1 sentence.

**Comment by Maroyafaied** [comment]
@lpgoldstein @jennmalcolm please review the power point slides for the OLT presentation. 

https://doimspp-my.sharepoint.com/:p:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7BEDA34FD5-95E9-4EA1-AF51-43F3CCBB5167%7D&file=ONRR.gov%20508%20Plan.pptx&action=edit&mobileredirect=true&PreviousSessionID=eb1fe585-94e5-f948-7d49-7015f379fd07&cid=69ec814f-c11d-43e9-a091-df21c151e402

**Comment by jennmalcolm** [comment]
Looks good. I made a few changes in the presentation.
