### ISSUE TITLE
Active Agreements Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2392]
Please replace the Active Agreements spreadsheet on this webpage - https://www.onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,active-agreements, with the updated attached spreadsheet.

Please also change the Updated date from 10/06/2022 to 01/03/2023.

Thank You,
Jessica Bowlen
[saaname.xlsx](https://github.com/ONRR/onrr.gov-site/files/10338728/saaname.xlsx)

**Comment by lpgoldstein** [comment]
@bowlenj This is ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,active-leases

**Comment by lpgoldstein** [comment]
@bowlenj live so closing issue.
