### ISSUE TITLE
Update Federal Onshore Terminable Leases

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2395]
Please replace the existing spreadsheet for Federal Onshore Terminable Leases - sorted by Due Date on the following webpage - https://www.onrr.gov/reporting/revenue?tabs=references, with the updated attached spreadsheet.

Please also change the updated date from 12/01/2022 to 01/03/2023.

Thank you,
Jessica Bowlen
[20230103.xlsx](https://github.com/ONRR/onrr.gov-site/files/10339108/20230103.xlsx)

**Comment by cthomasONRR** [comment]
@bowlenj 

These updates are on the dev site: https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=references

Please review and give us your approval to go live.

Thanks,
Christine

**Comment by bowlenj** [comment]
This looks great!  Approved for live and closure.


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Christine Thomas ***@***.***>
Sent: Tuesday, January 3, 2023 12:25 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update Federal Onshore Terminable Leases (Issue #2395)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C3b82ea44f02f4400ef1d08daedc04815%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638083707342299859%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tq7HPUiEmcKSaTz3tTxwmUdJ%2F3X6FyuTZEJxwUaiwcM%3D&reserved=0>

These updates are on the dev site: https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=references<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Freporting%2Frevenue%3Ftabs%3Dreferences&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C3b82ea44f02f4400ef1d08daedc04815%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638083707342299859%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UCSW4Nk8%2FosO266qHApEZvRMsfPDf8AuphVdyhn5i54%3D&reserved=0>

Please review and give us your approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj 

Great, these changes are now live: https://onrr.gov/reporting/revenue?tabs=references
