### ISSUE TITLE
Indian Gas Major Portion

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#240]
The 2018 Indian Gas Major Portion prices were just published in the FR today, Aug. 4, and can now be posted onto the ONRR.gov site (https://www.onrr.gov/Valuation/MonMajPP.htm).  

The prices were added to the Data for ONRR.gov spreadsheet in the OneDrive.  The prices will be updated for 5 reservations/allottees...Ft. Belknap, Ft. Berthold, Ft. Peck, Navajo Nation Allottees and Turtle Mountain.

If the spreadsheet in the OneDrive is not compatible with your process please let me know and I will provide them an alternate way.

Kind regards,
Cory Forgrave
@Sudarr

**Comment by lpgoldstein** [comment]
@forgravec This is ready for your review: http://2017onrr/Valuation/MonMajPP.htm

**Comment by forgravec** [comment]
The prices look good.
Thanks for completing this so quick.

Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
cory.forgrave@onrr.gov

________________________________

**Comment by lpgoldstein** [comment]
@forgravec Great! It should be live in a few minutes.
