### ISSUE TITLE
ONRR.gov December NYMEX prices

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#2403]
The December NYMEX and Roll prices are ready to be posted to ONRR.gov. The spreadsheet is attached as well for upload.
NYMEX CMA: $76.52
NYMEX Roll: $1.19

Thanks
Cory Forgrave
@Sudarr 
[NYMEX122022.xlsx](https://github.com/ONRR/onrr.gov-site/files/10355687/NYMEX122022.xlsx)

**Comment by forgravec** [comment]
Prices look good...thanks.

Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
***@***.***
________________________________
From: lpgoldstein ***@***.***>
Sent: Friday, January 6, 2023 7:14 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Forgrave, Cory J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] ONRR.gov December NYMEX prices (Issue #2403)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@forgravec<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fforgravec&data=05%7C01%7Ccory.forgrave%40onrr.gov%7C0fa173c8e88642fcd4cf08daeff059c9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638086112829357658%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aE9Ifz%2BnA8%2F8g1pr%2FXU73pe5fVysn2pKCkW99Xrco%2BI%3D&reserved=0> ready of your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Freferences%2Fvaluation%3Ftabs%3Dpricing%2Cnymex-oil-prices&data=05%7C01%7Ccory.forgrave%40onrr.gov%7C0fa173c8e88642fcd4cf08daeff059c9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638086112829357658%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iC2xXhYlZYeDFUKpLGFoieUWw%2BqZOyyUN6eNKVNl%2Fsg%3D&reserved=0>

**Comment by lpgoldstein** [comment]
@forgravec It's live! https://onrr.gov/references/valuation?tabs=pricing,nymex-oil-prices
