### ISSUE TITLE
Contact update - Tribal Assistance 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2404]
@lpgoldstein this request came to my email. I cc'd you in my response. Thanks

We have some changes for onrr.gov [https://www.onrr.gov/indian/assistance?tabs=tribal-assistance](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2Findian%2Fassistance%3Ftabs%3Dtribal-assistance&data=05%7C01%7CMaroya.Faied%40onrr.gov%7C567ec021711445f7dfb808daf24f3e54%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638088719409601602%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=c0%2BA07OKp5qGB1b8qkr%2Be9W9ZuDsVUR5%2FZIq%2FnUoiDo%3D&reserved=0)

Change Program Manager, to:
Yvette Smith 

Program Manager

Outreach, Audit Services, and Indian State Support (OASISS)

Office: (303) 231-3485

Feel free to abbreviate OASISS rather than typing it out as shown below:

Change Michel's title to read:  Tribal Liaison, Outreach, Audit Services & Tribal State Support (OASISS)

Change Bethany's title to read: Tribal Liaison Office, Outreach, Audit Services & Tribal State Support (OASISS), ONRR Branch Chief (IESC)

Bethany Hagen-Templin (she/her/hers)
Tribal Liaison Officer
Outreach, Audit Services, Indian State Support (OASISS)
Office of Natural Resources Revenue
Work: 303.231.3667 Cell: 303.549.8408

**Comment by lpgoldstein** [comment]
Approved via email so closing issue.
