### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov – January 2023

### ISSUE THREAD

**Issue by StaceyKaiser** [ONRR/onrr.gov-site#2405]
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “January 2023 Lease Agreement XREF.txt" and "January 2023 Lease Agreement XREF.xlsx”.  The data was queried from the system on 1/9/2023.

[January 2023 Lease Agreement XREF.txt](https://github.com/ONRR/onrr.gov-site/files/10374969/January.2023.Lease.Agreement.XREF.txt)

[January 2023 Lease Agreement XREF.xlsx](https://github.com/ONRR/onrr.gov-site/files/10375037/January.2023.Lease.Agreement.XREF.xlsx)

**Comment by lpgoldstein** [comment]
@StaceyKaiser ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

**Comment by StaceyKaiser** [comment]
@lpgoldstein everything looks good. Please move the files to the live site.  Thanks!

**Comment by lpgoldstein** [comment]
@StaceyKaiser This is live so I'm closing out the issue https://onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers
