### ISSUE TITLE
January Indian Index Zones on onrr.gov

### ISSUE THREAD

**Issue by penvosej** [ONRR/onrr.gov-site#2407]
Hi there! The prices for Indian Index Zones have been calculated for January 2023. The values can be found in the "Data for ONRR.gov" file. Could you please update the public website with this information?  @sudarr

Thank you!!!

**Comment by lpgoldstein** [comment]
@penvosej  ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone

**Comment by penvosej** [comment]
Hi Lindsay,

The prices on the page look good! Thanks!

- Jessica

From: lpgoldstein ***@***.***>
Sent: Monday, January 9, 2023 4:15 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] January Indian Index Zones on onrr.gov (Issue #2407)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpenvosej&data=05%7C01%7CJessica.Penvose%40onrr.gov%7C5275289e8ffd4ee7bd0608daf29766a3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638089029324043174%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=v7aVvytpnl2kQKqvj8ptpHFExEBbdDZjOB7fyygiHko%3D&reserved=0> ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Freferences%2Fvaluation%3Ftabs%3Dpricing%2Cindian-gas-index-zone&data=05%7C01%7CJessica.Penvose%40onrr.gov%7C5275289e8ffd4ee7bd0608daf29766a3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638089029324043174%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5%2FDQRJyknTeK5jQPoT9V%2F1%2Fcy4hHKiDuKBcOvyDq6nQ%3D&reserved=0>

-

**Comment by lpgoldstein** [comment]
@penvosej These are live - https://onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone
