### ISSUE TITLE
Meet with RV for design enhancements 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2413]

**Comment by eelzi-ONRR** [comment]
Met with Jodi on 1/18. 

Notes: https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Valuation/RV%20Pages%20Enhancement%20Notes.docx?d=w72482177cb6a47ca90731d44d7d5ea72&csf=1&web=1&e=2GLO6Z

Will work on mock-ups next sprint
