### ISSUE TITLE
Update NYMEX prices on ONRR.gov

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#242]
Please update the prices and upload the attached spreadsheet. Thanks! @sudarr
[NYMEX0720.xlsx](https://github.com/ONRR/onrr.gov-site/files/5031149/NYMEX0720.xlsx)

**Comment by lpgoldstein** [comment]
@boices This is ready for your review: http://2017onrr/Valuation/NYMEX.htm

**Comment by boices** [comment]
That looks great--thanks again!

**Comment by lpgoldstein** [comment]
@boices It's live!
