### ISSUE TITLE
Contact List Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2422]
The shared "Contacts Spreadsheet - To Update" spreadsheet has been updated for Onshore Production tab and Leases & Agreements tab.  The changes have been highlighted on the spreadsheet and the page links are listed below. Please let Candace and I know if you have any questions.

https://www.onrr.gov/about/contact/production-contacts?tabs=contacts,onshore-production
https://www.onrr.gov/about/contact/lease-agreement-contacts?tabs=contacts

Thank You
Jessica

**Comment by lpgoldstein** [comment]
@bowlenj ready for your review: https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts
https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production

**Comment by bowlenj** [comment]
Thank you, this looks great!  Approved to publish and close.


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: lpgoldstein ***@***.***>
Sent: Wednesday, January 18, 2023 10:14 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Contact List Update (Issue #2422)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C0c5b59c520634e91982808daf9776f5e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638096588619367668%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DjANvMzIXnguH%2Bc85xwHOhc52ogLJKCS4bvmne9nIA4%3D&reserved=0> ready for your review: https://dev-onrr-frontend.app.cloud.gov/about/contact/lease-agreement-contacts<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Fabout%2Fcontact%2Flease-agreement-contacts&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C0c5b59c520634e91982808daf9776f5e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638096588619367668%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Q2Nb2DmNgOZivOquYFQf5khVfLIMxGVMAfWEFl02kpg%3D&reserved=0>
https://dev-onrr-frontend.app.cloud.gov/about/contact/production-contacts?tabs=contacts,onshore-production<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Fabout%2Fcontact%2Fproduction-contacts%3Ftabs%3Dcontacts%2Conshore-production&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C0c5b59c520634e91982808daf9776f5e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638096588619367668%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7e0g%2FfuTtgDd%2F3gm8ictYOQUOxRkINSigOX08ufb7ko%3D&reserved=0>

**Comment by lpgoldstein** [comment]
@bowlenj This is live!
