### ISSUE TITLE
Reporter Training Schedule and Agendas

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2423]
Please add the below dates for the upcoming Oil & Gas and Solid Mineral Reporter Trainings along with the attached agendas to the following page - https://www.onrr.gov/references/training?tabs=training-schedule

February 27th - March 2nd, 2023 - Oil & Gas Reporter Training
[Oil and Gas Reporter Training Agenda_Registration Links.pdf](https://github.com/ONRR/onrr.gov-site/files/10448805/Oil.and.Gas.Reporter.Training.Agenda_Registration.Links.pdf)

February 28th - March 2nd, 2023 - Solid Mineral Reporter Training
[Solid Mineral Reporter Training Agenda_Registration Links.pdf](https://github.com/ONRR/onrr.gov-site/files/10448809/Solid.Mineral.Reporter.Training.Agenda_Registration.Links.pdf)

Please let Candace and I know if you have any questions.

Thank You
Jessica Bowlen

**Comment by Maroyafaied** [comment]
@eelzi-ONRR let me know if you need help with this

**Comment by eelzi-ONRR** [comment]
@bowlenj These have been added and are ready for review:

https://dev-onrr-frontend.app.cloud.gov/references/training?tabs=training-schedule

They have also been added to the events page:

https://dev-onrr-frontend.app.cloud.gov/events?tabs=other-onrr-events 

Thanks!

**Comment by bowlenj** [comment]
This looks great!  Thank you for also adding to the events page, we weren't aware that page was there.  Both pages look great, approved to publish and close!


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Erin Elzi ***@***.***>
Sent: Wednesday, January 18, 2023 2:45 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Reporter Training Schedule and Agendas (Issue #2423)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C4851e67bc34847ff8d2108daf99d4573%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638096751135653104%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0qPs%2Blrzv3gb50Mfml3sogL27QYKYA23edssGWNmSLs%3D&reserved=0> These have been added and are ready for review:

https://dev-onrr-frontend.app.cloud.gov/references/training?tabs=training-schedule<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Freferences%2Ftraining%3Ftabs%3Dtraining-schedule&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C4851e67bc34847ff8d2108daf99d4573%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638096751135653104%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CBG%2F7s1iOUM%2BXAgEjzdR%2Fh6EJm%2F3x58bwpDk79Ao7uM%3D&reserved=0>

They have also been added to the events page:

https://dev-onrr-frontend.app.cloud.gov/events?tabs=other-onrr-events<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Fevents%3Ftabs%3Dother-onrr-events&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C4851e67bc34847ff8d2108daf99d4573%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638096751135653104%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=m3bacEACgmHo9ocz56X30BH%2FY3nnm1HBP%2BcNSobFFRM%3D&reserved=0>

Thanks!

**Comment by eelzi-ONRR** [comment]
Thanks, @bowlenj ! Both pages are live now so I'll close this issue

https://onrr.gov/references/training?tabs=training-schedule
https://onrr.gov/events?tabs=other-onrr-events
