### ISSUE TITLE
Update Civil Penalties page

### ISSUE THREAD

**Issue by KristianL3101** [ONRR/onrr.gov-site#2426]
Please create an "FY 2022 Penalties" PDF with the included attachment and delete "2017 Penalties" PDF. Update the "Historical Penalties" PDF with the Included attachment Thank you. LInk and attachments below.

Link: https://onrr.gov/compliance-enforcement/enforcement?tabs=civil-penalties        

(PDF's are on the right-hand side down the page..)

Attachments:

[Historical Penalty Collections.pdf](https://github.com/ONRR/onrr.gov-site/files/10468670/Historical.Penalty.Collections.pdf)

[Fiscal Year 2022 Penalty Collections.pdf](https://github.com/ONRR/onrr.gov-site/files/10468671/Fiscal.Year.2022.Penalty.Collections.pdf)

**Comment by cthomasONRR** [comment]
@KristianL3101 

Hi Kristian, I checked both the Historical Penalty and FY 2022 PDFs, and they are not 508-compliant. Could you please send us a compliant version of these documents?
![image](https://user-images.githubusercontent.com/72526208/213768625-6a3dd4de-e7f3-4ac5-ba1b-b6c1fdff40b4.png)
![image](https://user-images.githubusercontent.com/72526208/213769436-63a1e964-a58e-4bf1-8f7e-6f0c8d5c1c74.png)

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@KristianL3101 

Thanks for your work in making these PDFs compliant!
I updated the dev site. Please review and give us your approval to go live:
https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/enforcement?tabs=civil-penalties

Thanks,
Christine

**Comment by KristianL3101** [comment]
Looks good. Thanks.

Kristian Lee
Enforcement Specialist
ONRR/OE Litigation Support
Denver Federal Center, Bldg 85/B76
PO Box 25165 MS 64200B
Denver, CO  80225-0165
(303) 231-3101

________________________________
From: Christine Thomas ***@***.***>
Sent: Tuesday, January 31, 2023 7:13 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Lee, Kristian H ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update Civil Penalties page (Issue #2426)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@KristianL3101<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKristianL3101&data=05%7C01%7Ckristian.lee%40onrr.gov%7C9fa3726ef5314f24c76008db039555a2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638107712152364805%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gmJinW3ixSUPNSwu7kZwsR5Tw6gjA99m%2FjI3GNEbEhw%3D&reserved=0>

Thanks for your work in making these PDFs compliant!
I updated the dev site. Please review and give us your approval to go live:
https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/enforcement?tabs=civil-penalties<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Fcompliance-enforcement%2Fenforcement%3Ftabs%3Dcivil-penalties&data=05%7C01%7Ckristian.lee%40onrr.gov%7C9fa3726ef5314f24c76008db039555a2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638107712152364805%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3dRg3IbeajWgm%2Fsq8jkaYBhRUMrdjCrrFStSLsAagfc%3D&reserved=0>

Thanks,
Christine
