### ISSUE TITLE
Update Civil Penalty Amounts

### ISSUE THREAD

**Issue by KristianL3101** [ONRR/onrr.gov-site#2427]
Please update Current Civil penalties amounts to the following:

"Violations not fixed within the grace period are subject to civil penalties until fixed. These penalties can be up to $1,474.00 per day ($14,754 .00 per day after 40 days).

Certain violations, such as failure to permit an audit, failure to timely pay royalties, or submission/maintenance of false, inaccurate, or misleading information are subject to higher civil penalties. They can be as much as $29,505.00 or $73,764.00 per violation for each day the violation continues."

This text can be found at this link: https://onrr.gov/compliance-enforcement/enforcement?tabs=civil-penalties

Under the "Civil Penalties" section. Thank you.

**Comment by eelzi-ONRR** [comment]
@KristianL3101 The penalty amounts have been updated and are ready for review: 

https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/enforcement?tabs=civil-penalties

Thanks!
Erin

**Comment by eelzi-ONRR** [comment]
Approved via Teams.

@KristianL3101 This update is now live.

https://onrr.gov/compliance-enforcement/enforcement?tabs=civil-penalties

Thanks!
