### ISSUE TITLE
Webpage Updat 100% fed Agmt

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#2428]
Please update the following webpage http://www.onrr.gov/ReportPay/royalty-reporting.htm with the attached excel file.
100 % Federal Agreements with the Same Royalty Rate & royalty Distributions

Also change update to read 01/01/2023
Thank you!

[100pct fed agreements.xlsx](https://github.com/ONRR/onrr.gov-site/files/10470383/100pct.fed.agreements.xlsx)

**Comment by lpgoldstein** [comment]
@merrellc Ready for your review: https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=references

**Comment by merrellc** [comment]
Ready to go. Thank you!



Kind Regards,
​Candace Merrell
Minerals Revenue Specialist - Staff
Data Solutioning and Technical Support
Data Intake, Solutioning and Coordination
Office of Natural Resources Revenue
303-231-3517
***@***.***


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.


________________________________
From: lpgoldstein ***@***.***>
Sent: Friday, January 20, 2023 3:18 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Webpage Updat 100% fed Agmt (Issue #2428)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@merrellc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmerrellc&data=05%7C01%7Ccandace.merrell%40onrr.gov%7Cf2d3370a748b48d78f1008dafb343a2a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638098498980243197%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0VL2Lm4P50XBH0Ff6tDE6h%2FUCUSOL5CK3GAIFedJy1c%3D&reserved=0> Ready for your review: https://dev-onrr-frontend.app.cloud.gov/reporting/revenue?tabs=references<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Freporting%2Frevenue%3Ftabs%3Dreferences&data=05%7C01%7Ccandace.merrell%40onrr.gov%7Cf2d3370a748b48d78f1008dafb343a2a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638098498980243197%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=16H4rBHPaNuQdcF3life5QJ5Rz0IgykHza9GzUXYBKo%3D&reserved=0>

**Comment by lpgoldstein** [comment]
@merrellc site is live so closing out issue. https://onrr.gov/references/reference-lists?tabs=revenue-reporting-references
