### ISSUE TITLE
Add section in CMS user guide about archiving documents

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#2431]
I made a new section within the CMS user guide with updating and archiving instructions:
https://github.com/ONRR/onrr.gov-site/wiki/CMS-User-Guide#Updating-and-archiving-documents

**Comment by cthomasONRR** [comment]
@eelzi-ONRR I made a new entry in the CMS user guide about updating and archiving docs. If you have time could you please review? Thanks!

**Comment by eelzi-ONRR** [comment]
@cthomasONRR Looks good! Clear and easy to follow :)
