### ISSUE TITLE
Update to Forms Reference page

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2433]
Please update the follow webpage - https://onrr.gov/references/forms, with the updated descriptions as shown below:

Please replace description under heading "Taxpayer ID" with the below:
ONRR is required to collect a Taxpayer Identification Number for all persons with whom we do business.  You can email a completed W-9 to forms.industry@onrr.gov for faster processing.  Please see Instructions for mailing address and form requirements.

Please add description under heading "Designation Form for Royalty Payment Responsibility":
If you are a lessee under 30 U.S.C. § 1702(7), and you want to designate a person to make all or part of the payments due under a lease on your behalf under 30 U.S.C. § 1712(a), you should provide to ONRR information in writing of such designation by submitting a Form ONRR-4425 and Written Designation Acceptance Letter.  You can email a completed Form ONRR-4425 and additional information to forms.industry@onrr.gov for faster processing.

Thank You
Jessica Bowlen & Jason Roach

**Comment by cthomasONRR** [comment]
@bowlenj 

These changes are in the dev site: https://dev-onrr-frontend.app.cloud.gov/references/forms
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by bowlenj** [comment]
This looks great, approved to publish and close!


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: Christine Thomas ***@***.***>
Sent: Tuesday, January 24, 2023 2:53 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update to Forms Reference page (Issue #2433)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C952da1d67353449f67f208dafe556b90%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638101940076548766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MEHAac3QygYjSI4gO%2BnR6INMhFfXsPq%2BhGFe81B5lh4%3D&reserved=0>

These changes are in the dev site: https://dev-onrr-frontend.app.cloud.gov/references/forms<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Freferences%2Fforms&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7C952da1d67353449f67f208dafe556b90%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638101940076548766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Co4Q9bbARcafChvUI0VBIqrq6uv39i9n9V2oTiLBij8%3D&reserved=0>
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
@bowlenj 

Good morning,
These updates are now live: https://onrr.gov/references/forms
Closing this issue now.

Thanks,
Christine
