### ISSUE TITLE
EASTERN OK REGIONAL VIRTUAL MEETING

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#2437]
**EASTERN OK REGIONAL VIRTUAL MEETING**
Thursday, February 16, 2023
1:00 pm to 2:00 pm CST

Location:  By Telephone

DESCRIPTION: The Office of Natural Resources Revenue (ONRR) will be hosting a virtual (call-in) Outreach Meeting for Indian trust property owners.  Representatives from the Bureau of Land Management (BLM), Bureau of Trust Funds Administration (BTFA), and the Bureau of Indian Affairs (BIA) will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts, and Indian Trust property issues.  The meeting will begin with the brief introduction by the ONRR representative.  Owners will have an opportunity to ask questions with the representatives of the four agencies during the Q&A session 

WHO SHOULD ATTEND:  Indian mineral owners, IIM account holders and other Indian Trust property owners in the Eastern Oklahoma region.
  
OTHER INFORMATION: To reserve a space and get a passcode for this meeting please contact the ONRR OKC Outreach Office toll-free at (800) 354-7015. The OKC office hours are Mon.- Fri. from 7:30 am-5:00 pm.

CONTACT: ONRR OKC Outreach Office, Toll Free (800) 354-7015 or Main No.
(405)879-6050.  EMAIL: [onrroutreachokc@onrr.gov](https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=onrroutreachokc@onrr.gov)

**ND, SD, MT, OR, WA Virtual Outreach Meeting**
Thursday, February 16, 2023
10:00 am-11:00 am MST

LOCATION:  By Telephone

DESCRIPTION: Representatives from the Office of Natural Resources Revenue will host a virtual Question-and-Answer session by telephone for Indian Mineral Owners and Trust Property Owners regarding their Indian Oil & Gas leases, IIM Accounts, and Indian Trust Properties. Representatives from the Bureau of Land Management, Bureau of Indian Affairs, and Bureau of Trust Funds Administration have been invited to be in attendance to answer questions.

WHO SHOULD ATTEND:  IIM account holders, Indian mineral owners, and Indian trust property owners in the Trenton, ND, Parshall, ND, Ft. Berthold, ND, Minot, ND, Ft. Totten, ND, Turtle Mountain, ND, Mandaree, ND, Twin Buttes, ND, White Shield, ND, Bismarck, ND, Fargo, ND, Poplar, MT, Rapid City, SD, Agency Village, SD, Aberdeen, SD, Standing Rock, SD, Portland, OR, Spokane, WA, and Seattle, WA areas.

OTHER INFORMATION: To attend the outreach session, please contact the ONRR Denver Outreach Office at (800) 982-3226, for the call-in number and passcode.  The ONRR Denver Outreach Office hours are Monday-Friday 7:30am-4:00pm.

CONTACT:  ONRR Denver Outreach Office, Toll Free (800) 982-3226, Email: [onrroutreachdenver@onrr.gov](mailto:onrroutreachdenver@onrr.gov)

**Comment by Toddsand21** [comment]
Can we change the OKC Office hours on the Eastern OK Regional Meeting to read:   from 7:30 am - 4:30 pm.     (On the Other Information)?
And on the other ND, SD... Outreach Meeting, could you add the word "at" to follow Office in the first sentence.  Please contact the ONRR Denver Outreach Office at ,,,,,         (On the Other Information)?

**Comment by lpgoldstein** [comment]
@Toddsand21 ready for your review again. https://dev-onrr-frontend.app.cloud.gov/events

**Comment by Toddsand21** [comment]
On the Eastern OK Meeting could you change the word "the" to "a" ....to read:   .will begin with "a" brief introduction by the ONRR...  (found in the 2nd to last sentence in the Description).

**Comment by Toddsand21** [comment]
And last, could you put a comma after OR, in the 2nd meeting heading, and add "and" to the heading,   " ND, SD, MT, OR, and WA Virtual Outreach Meeting.

**Comment by lpgoldstein** [comment]
@Toddsand21 No problem: https://dev-onrr-frontend.app.cloud.gov/events

**Comment by Toddsand21** [comment]
Looks fine. Let's go with it.

**Comment by lpgoldstein** [comment]
@Toddsand21 live! https://onrr.gov/events
