### ISSUE TITLE
ONRR.gov January 2023 NYMEX prices

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#2447]
The January 2023 NYMEX and Roll prices are ready to be added to the ONRR.gov site. The spreadsheet is attached for upload as well.
Kind regards,
Cory Forgrave
@Sudarr 
[NYMEX012023.xlsx](https://github.com/ONRR/onrr.gov-site/files/10572304/NYMEX012023.xlsx)

**Comment by lpgoldstein** [comment]
@forgravec ready for review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices

**Comment by forgravec** [comment]
All looks good...thanks.

Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
***@***.***
________________________________
From: lpgoldstein ***@***.***>
Sent: Thursday, February 2, 2023 12:08 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Forgrave, Cory J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] ONRR.gov January 2023 NYMEX prices (Issue #2447)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@forgravec<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fforgravec&data=05%7C01%7Ccory.forgrave%40onrr.gov%7C5c7ed08817954253639408db0550e715%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638109617257138928%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FRXQ0jMTh%2BmorATBZ0oInW%2FzDUl7RkAnSNZUYVJML%2Bg%3D&reserved=0> ready for review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,nymex-oil-prices<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Freferences%2Fvaluation%3Ftabs%3Dpricing%2Cnymex-oil-prices&data=05%7C01%7Ccory.forgrave%40onrr.gov%7C5c7ed08817954253639408db0550e715%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638109617257138928%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ujU%2BGwPCTkpYcMT6JX0A1W1Kg3YRkN9loCTt6lP5J1s%3D&reserved=0>

**Comment by lpgoldstein** [comment]
@forgravec it's live! https://onrr.gov/references/valuation?tabs=pricing,nymex-oil-prices
