### ISSUE TITLE
Update onrr.gov with Feb Index Zone prices

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#2448]
Hello,

Please update the onrr.gov website with the Feb prices contained in the Data for ONRR.gov shared spreadsheet.

Thanks!

@sudarr

**Comment by lpgoldstein** [comment]
@boices ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone Also in the future can you please just create a spreadsheet with the monthly data and post here? We upload this directly into our content management system and it updates from the spreadsheet. If you create it vs us copying and pasting, it will decrease chance of error. Here's a template. Thanks! 
[2023_02.xlsx](https://github.com/ONRR/onrr.gov-site/files/10572569/2023_02.xlsx)

**Comment by boices** [comment]
That's perfect--thanks again!

**Comment by lpgoldstein** [comment]
@boices It's live! https://onrr.gov/references/valuation?tabs=pricing,indian-gas-index-zone
