### ISSUE TITLE
Webpage Update - New Lease Agreement XREF files for onrr.gov – Feb 2023

### ISSUE THREAD

**Issue by StaceyKaiser** [ONRR/onrr.gov-site#2450]
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm titled, “Cross-Reference Lease to Agreement Number” with the new provided files titled, “February 2023 Lease Agreement XREF.txt" and "February 2023 Lease Agreement XREF.xlsx”.  The data was queried from the system on 2/6/2023.
[February 2023 Lease Agreement XREF.txt](https://github.com/ONRR/onrr.gov-site/files/10668389/February.2023.Lease.Agreement.XREF.txt)
[February 2023 Lease Agreement XREF.xlsx](https://github.com/ONRR/onrr.gov-site/files/10668398/February.2023.Lease.Agreement.XREF.xlsx)

**Comment by cthomasONRR** [comment]
@StaceyKaiser

These changes are now in our dev site: https://dev-onrr-frontend.app.cloud.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

Please review and give us your approval to go live.

Thanks,
Christine

**Comment by StaceyKaiser** [comment]
@cthomasONRR The changes look god. Please move to the live site.  Thanks!

**Comment by cthomasONRR** [comment]
@StaceyKaiser 

Thanks, these changes are now live: https://onrr.gov/references/reference-lists?tabs=leases-agreement-numbers,cross-reference-lease-to-agreement-numbers

Closing this issue now.
Christine
