### ISSUE TITLE
Add Link to Training Video

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#2452]
Please add link the below link to New Reporter Videos located here - https://www.onrr.gov/references/training?tabs=training-videos,new-reporters&panel=basic-ecommerce-navigation.

This link is for Basic eCommerce Navigation Video Series: Part 1.  Part 2 and 3 are still there but somehow Part 1 didn't carry over from the old onrr.gov.

Basic eCommerce Navigation Video Series: Part 1 - https://www.youtube.com/watch?v=iQh2DIqfOkE&list=PLHqjbxv3m6Rw5QdQ5nOa4MTJWy3nAwweS&index=2

Please let me know if you have any questions.

Thank You
Jessica Bowlen x3102

**Comment by lpgoldstein** [comment]
@bowlenj 

ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/training?tabs=training-videos,new-reporters&panel=basic-ecommerce-navigation

**Comment by bowlenj** [comment]
Perfect, thank you Lindsay!  Approved to post and close.


Thank You,

Jessica Bowlen

Minerals Revenue Specialist - Staff

Data Solutioning and Technical Support

Data Intake, Solutioning, and Coordination

Office of Natural Resources Revenue

303-231-3202

***@***.******@***.***>


This communication is based solely on the information provided and should be considered only for the particular issue or question presented. It is guidance and not binding on ONRR. It does not provide legal advice and should not be construed as stating ONRR’s legal interpretation or position. It is not an appealable decision or order under 30 CFR Part 1290, Subpart B. Any reliance on this communication does not limit ONRR in its compliance activities or in the appealable decisions and orders it may issue.

________________________________
From: lpgoldstein ***@***.***>
Sent: Monday, February 6, 2023 2:05 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Add Link to Training Video (Issue #2452)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cce6f50d9444e4f7319cc08db0885dd10%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638113143256756129%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yZ5AxmreyDJxkJrFi4IAEWsAV5bu0GZOkHaxE7e6czw%3D&reserved=0>

ready for your review: https://dev-onrr-frontend.app.cloud.gov/references/training?tabs=training-videos,new-reporters&panel=basic-ecommerce-navigation<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev-onrr-frontend.app.cloud.gov%2Freferences%2Ftraining%3Ftabs%3Dtraining-videos%2Cnew-reporters%26panel%3Dbasic-ecommerce-navigation&data=05%7C01%7Cjessica.bowlen%40onrr.gov%7Cce6f50d9444e4f7319cc08db0885dd10%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638113143256756129%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nFNYV4NmU7%2BK0Gs02nMjKxuiZBCwnUdToWPrRLVPNYA%3D&reserved=0>

**Comment by lpgoldstein** [comment]
@bowlenj it's live so closing issue!
