### ISSUE TITLE
New file for onrr.gov

### ISSUE THREAD

**Issue by grjson** [ONRR/onrr.gov-site#246]
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm called “Downloadable Text Cross-Reference Lease to Agreement Number” with the file entitled “Aug 2020 Lease Agreement XREF.txt”.  It was queried from the system on 8/6/2020.
[Aug 2020 Lease Agreement XREF.txt](https://github.com/ONRR/onrr.gov-site/files/5037699/Aug.2020.Lease.Agreement.XREF.txt)

**Comment by lpgoldstein** [comment]
@grjson This is ready for your review http://2017onrr/ReportPay/CrossRef.htm

**Comment by grjson** [comment]
Lindsay the Cross Reference file looks good please make it live
Thank you,
Gary

**Comment by lpgoldstein** [comment]
@grjson The file is now live.
