### ISSUE TITLE
New update to ONRR.gov (Indian Index Zones)

### ISSUE THREAD

**Issue by jpenvose773** [ONRR/onrr.gov-site#247]
Please update the Indian Index Zone prices for August on ONRR.gov. The data has been updated with the newest prices in the Data For ONRR.gov Excel spreadsheet.   @sudarr

**Comment by lpgoldstein** [comment]
@jpenvose773 This is ready for your review: http://2017onrr/Valuation/allzones.htm

**Comment by jpenvose773** [comment]
The data placed on the website looks good! Thanks for taking care of this!

**Comment by lpgoldstein** [comment]
@jpenvose773 It should be live soon!
