### ISSUE TITLE
Webpage Update - Indian Fund Code

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#249]
Please update the following webpage http;//onrr.gov./Reportpay/payments.htm with the attached file's:

Indian Leases Cross-walked to Distributee Codes
Downloadable Excel Version Indian Leases Cross-walked to Distributee Codes

Also change updated to 08/07/2020 for both files.

In addition to the above please update the updated to read 08/07/2020 on URL http://www.onrr.gov/ReportPay/royalty-reporting.htm for the same files linked to this URL.

Thank You

[FCIL.pdf](https://github.com/ONRR/onrr.gov-site/files/5044066/FCIL.pdf)
[FCIL.xlsx](https://github.com/ONRR/onrr.gov-site/files/5044067/FCIL.xlsx)

**Comment by Maroyafaied** [comment]
@merrellc please review the changes, if everything looks correct then I will publish it to the live site. Thanks

http://2017onrr/ReportPay/payments.htm
http://2017onrr/ReportPay/royalty-reporting.htm

**Comment by merrellc** [comment]
Hello, ready to publish.  Thank you


Kindly,
​Candace Merrell
Office of Natural Resources Revenue

Reference and Reporting Management

Candace.Merrell@onrr.gov

303-231-3517

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________

**Comment by Maroyafaied** [comment]
This is now updated on the site. Thanks
