### ISSUE TITLE
July IBMP Prices

### ISSUE THREAD

**Issue by damionschulte** [ONRR/onrr.gov-site#250]
Hello,  I've updated the Office 365 sheet ( Data for ONRR.gov.xlsx) to include the July 2020 IBMP prices for the https://www.onrr.gov/Valuation/IndianOilIBMP.htm page.

Can you please post them to our development site and I'll review before we make them public?

@sudarr

**Comment by lpgoldstein** [comment]
@damionschulte These are ready for your review: http://2017onrr/Valuation/IndianOilIBMP.htm

**Comment by damionschulte** [comment]
These look great!  Thank you

**Comment by lpgoldstein** [comment]
@damionschulte The updates are live. Please check on IE if chrome doesn't update properly - you may need to clear your cache as well.
