### ISSUE TITLE
Update footer's  link’s text to read “U.S. Department of the Interior”

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#253]
We received this request in our mailbox. 

"Hi.

In the footer of ONRR.gov we link to www.doi.gov.

Please update the link’s text to read “U.S. Department of the Interior” to indicate the title of the page we are linking to.

Thanks,"

jim

James (Jim) Witkop

Supervisor, Program Support and Project Management Office

Strategic Resource Management Program

Office of Natural Resources Revenue (ONRR)

US Department of the Interior

703-787-1051 or @PMO

**Comment by jennmalcolm** [comment]
@Maroyafaied please review this in dev.

**Comment by Maroyafaied** [comment]
@jennmalcolm looks good

**Comment by jennmalcolm** [comment]
done
