### ISSUE TITLE
Add Mailing Address on Office Location Page

### ISSUE THREAD

**Issue by vcs5274** [ONRR/onrr.gov-site#254]
Good afternoon,

Please add the following address for check payments to the office locations mailing addresses.

Payments

PO Box 25627
Denver, CO  80225-25627

**Comment by jennmalcolm** [comment]
@vcs5274 please review your requested changes on our development site, and let us know if it's ready to publish.

http://2017onrr/About/office-locations.htm

**Comment by vcs5274** [comment]
Good morning,

The changes look good. Please publish.

Thank you,

Victoria Soto
Office of Natural Resources Revenue
Bldg 85, Denver Federal Center
Denver, CO  80225
Accounting Services, Supervisor General Ledger
Phone: 1-800-433-9801 x13210
     -or-      303-231-3210
Fax: 303-445-9526
Email: victoria.soto@onrr.gov<mailto:victoria.soto@onrr.gov>

"Ability is what you are capable of doing. Motivation determines what you do. Attitude determines how well you do." - Lou Holtz

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________

**Comment by jennmalcolm** [comment]
The changes are live.
