### ISSUE TITLE
Create XML SEO site map

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#259]
This is for the XML sitemap, not the sitemap page.

**Comment by jennmalcolm** [comment]
Figure out automated way to do it.

**Comment by mcharg** [comment]
@mojobnichols I think you're going to have to put in tagging before we can generate the XML sitemap. This is what I got from an automatic sitemap generator.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/8dbda7a9-ef5a-4c67-a9a7-dd8045dbcb0f)

**Comment by cthomasONRR** [comment]
@mojobnichols Yeah, when I go to https://dev-onrr-frontend.app.cloud.gov/site-map > right click > view page source, this is what I see:

![image](https://user-images.githubusercontent.com/72526208/175325312-421efc72-8cab-4637-9eb4-4cd888878528.png)

**Comment by cthomasONRR** [comment]
XML Site Map Generator: https://www.xml-sitemaps.com/

**Comment by mcharg** [comment]
Christine and I figured out how to generate an XML sitemap of all the pages using the import/export function in the CMS. Checking with @mojobnichols about whether there's a place to upload via GitHub to put it in the location it needs to go to be read by search engines.

Will need to run export function separately for each folder with documents and copy/paste along with some finding and replacing to get those added.

Unless @mojobnichols knows of a way to do this more automated.

**Comment by mcharg** [comment]
Sitemap: https://dev-onrr-frontend.app.cloud.gov/ONRR-sitemap.xml

Location in GitHub: https://github.com/ONRR/onrr.gov-site/tree/dev/frontend/dist

@cthomasONRR Do you want to review? This is the tool I used to validate. https://www.xml-sitemaps.com/validate-xml-sitemap.html

**Comment by cthomasONRR** [comment]
@mcharg Thank you for your help on this. I used the validation tool you listed and also get the the site map is valid: 
![image](https://user-images.githubusercontent.com/72526208/177624123-2765ff0a-325b-41f3-910d-9da16db1514c.png)

I think this is good until Mojo figures out how to automate a sitemap. 

Should we send it to our search.gov contacts for an additional review?

**Comment by mcharg** [comment]
@cthomasONRR I think that's a good idea.

**Comment by cthomasONRR** [comment]
@mcharg Great, just emailed her with the following:

"Hi Arantxa,

Thank you for the advice! We have our site map here: https://dev-onrr-frontend.app.cloud.gov/ONRR-sitemap.xml
We’ve validated with this checker: https://www.xml-sitemaps.com/validate-xml-sitemap.html, and it’s coming back error free.
Would you mind also checking out our site map to see if you ID any errors/concerns?

Thanks,
Christine"

**Comment by cthomasONRR** [comment]
@mcharg I just got the following response:

"Christine,

We checked and your sitemap looks good. However, we recommend that you wait until your site goes live to submit it to Bing. 

Hope this is helpful.

Arantxa"
