### ISSUE TITLE
Build content model for onrr.gov

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/onrr.gov-site#26]
This scope of work involves referencing our content audit of onrr.gov to build a content model for that site. The scope also involves testing [USWDS](https://designsystem.digital.gov/) federalist templates to assess suitability for onrr.gov.

**Comment by mcharg** [comment]
I think we've got this covered with the taxonomy that came out of the card sorting and tree testing (#365) and the issue to evaluate technology (#376).
