### ISSUE TITLE
Link in revenue reporter handbook is going to dev instead of production

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#261]
Goes to: http://2017onrr/ReportPay/payments.htm#PI
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/ff13324a-0da6-4b24-b356-b83291c70dde)

**Comment by jennmalcolm** [comment]
This is fixed now. Please confirm @mcharg

https://www.onrr.gov/ReportPay/Handbooks/revenue-handbook/index.htm

**Comment by mcharg** [comment]
Looks good.
