### ISSUE TITLE
Update org chart to reflect Howard as Director 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#2611]
https://onrr.gov/about/organization?tabs=organization-chart

**Comment by eelzi-ONRR** [comment]
@cthomasONRR Do you have time to review? 

https://dev-onrr-frontend.app.cloud.gov/about/organization?tabs=organization-chart

I updated the powerpoint and image to remove (acting) from the director box, and changed the deputy director box from Howard to Vancant. And I updated the updated date to April 2023

**Comment by cthomasONRR** [comment]
@eelzi-ONRR This was probably on the old one too. 

But in the text, I think we need to reword the description for Solicitor's Office and IBC. 

SOL doesn't "report to" ONRR's Director, it's more like they work in tandem (hence the dotted line with arrows going in both directions.). SOL is not a subordinate of the Director.

The same goes for IBC. IBC works in tandem with the Deputy Director. They aren't a subordinate of the DD.

![image](https://user-images.githubusercontent.com/72526208/234051850-83a11e25-a8b7-4749-bdb6-3abc25699c1d.png)

**Comment by eelzi-ONRR** [comment]
@cthomasONRR Good catch! What if I change it to "collaborates with Director"?

**Comment by cthomasONRR** [comment]
@eelzi-ONRR I think "collaborates" is a good descriptor. Thanks!
