### ISSUE TITLE
Broken link: eCFR

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#262]
URL: http://ecfr.gpoaccess.gov/
Location: Indian Payor Handbook section 1.9
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/79d993ad-684a-40fe-ab8c-fdac768ed995)

**Comment by lpgoldstein** [comment]
@mcharg please review http://2017onrr/ReportPay/Handbooks/indian-payor-handbook-chapter-1.htm

**Comment by mcharg** [comment]
@lpgoldstein Looks good.
