### ISSUE TITLE
Some forms use http in the links and some use https

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#263]
So they're being counted separately in the analytics.  We should decide on one and get the links all consistent.

Example of the Form 4444 links (shows up twice in the download rankings as 13 and 95)
https://www.onrr.gov/reportpay/PDFDocs/ONRR4444.pdf
http://www.onrr.gov/ReportPay/PDFDocs/ONRR4444.pdf

**Comment by mcharg** [comment]
List of documents that have http instead of https:
http://www.onrr.gov/ReportPay/PDFDocs/ONRR4444_Instructions.pdf
http://www.doi.gov/ost/press_room/upload/rev6-27-13GuidetoYourIIMStatementofPerformance-v3.pdf
http://www.onrr.gov/pdfdocs/GOMESA-National-2019.pdf
http://www.onrr.gov/pdfdocs/GOMESA-Texas-2019.pdf
http://www.onrr.gov/pdfdocs/GOMESA-Mississippi-2019.pdf
http://www.onrr.gov/pdfdocs/GOMESA-Louisiana-2019.pdf
http://www.onrr.gov/pdfdocs/GOMESA-Alabama-2019.pdf
http://www.onrr.gov/pdfdocs/20181101.pdf
http://www.onrr.gov/pdfdocs/GOMESA-Press-Release-Binder-04-26-18.pdf
http://www.onrr.gov/pdfdocs/20171130.pdf
http://www.onrr.gov/pdfdocs/20171130-NM.pdf
http://www.onrr.gov/pdfdocs/20171130-MT.pdf
http://www.onrr.gov/pdfdocs/20171130-ND.pdf
http://www.onrr.gov/pdfdocs/20171130-LA.pdf
http://www.onrr.gov/pdfdocs/20171130-UT.pdf
http://www.onrr.gov/pdfdocs/20171130-CO.pdf
http://www.onrr.gov/pdfdocs/20171130-WYO.pdf
http://www.onrr.gov/pdfdocs/20161125b.pdf
http://www.onrr.gov/about/pdfdocs/20161118.pdf
http://www.onrr.gov/pdfdocs/20161007.pdf
http://www.onrr.gov/about/pdfdocs/20160729.pdf
http://www.onrr.gov/about/pdfdocs/20160706.pdf
http://www.onrr.gov/about/pdfdocs/20160630.pdf
http://www.onrr.gov/about/pdfdocs/20160629.pdf
http://www.onrr.gov/about/pdfdocs/20160505A.pdf
http://www.onrr.gov/about/pdfdocs/20160505B.pdf
http://www.onrr.gov/about/pdfdocs/20160225.pdf
http://www.onrr.gov/about/pdfdocs/20151229.pdf
http://www.onrr.gov/about/pdfdocs/20151125a.pdf
http://www.onrr.gov/about/pdfdocs/20151125.pdf
http://www.onrr.gov/about/pdfdocs/Summary2015Disbursements.pdf
http://www.onrr.gov/about/pdfdocs/20151123.pdf
http://www.onrr.gov/about/pdfdocs/20151019.pdf
http://www.onrr.gov/about/pdfdocs/20150925.pdf
http://www.onrr.gov/about/pdfdocs/20150921.pdf
http://www.onrr.gov/about/pdfdocs/20150915.pdf
http://www.onrr.gov/about/pdfdocs/20150812.pdf
http://www.onrr.gov/about/pdfdocs/20150706.pdf
http://www.onrr.gov/about/pdfdocs/20150618.pdf
http://www.onrr.gov/about/pdfdocs/20150513.pdf
http://www.onrr.gov/about/pdfdocs/20150506.pdf
http://www.onrr.gov/about/pdfdocs/20150504.pdf
http://www.onrr.gov/about/pdfdocs/20150430.pdf
http://www.onrr.gov/about/pdfdocs/20150410.pdf
http://www.onrr.gov/about/pdfdocs/20150401.pdf
http://www.onrr.gov/about/pdfdocs/20150325.pdf
http://www.onrr.gov/about/pdfdocs/20150218.pdf
http://www.onrr.gov/about/pdfdocs/20150211.pdf
http://www.onrr.gov/about/pdfdocs/20150205.pdf
http://www.onrr.gov/about/pdfdocs/20141219.pdf
http://www.onrr.gov/about/pdfdocs/20141209.pdf
http://www.onrr.gov/about/pdfdocs/20141202b.pdf
http://www.onrr.gov/about/pdfdocs/20141202.pdf
http://www.onrr.gov/about/pdfdocs/12-14-FY-2014-SummaryDisbursements.pdf
http://www.onrr.gov/about/pdfdocs/20140918.pdf
http://www.onrr.gov/about/pdfdocs/20140908.pdf
http://www.onrr.gov/about/pdfdocs/20140904.pdf
http://www.onrr.gov/about/pdfdocs/20140618.pdf
http://www.onrr.gov/about/pdfdocs/20140612.pdf
http://www.onrr.gov/about/pdfdocs/20140523.pdf
http://www.onrr.gov/about/pdfdocs/20140408.pdf
http://www.onrr.gov/about/pdfdocs/20140331.pdf
http://www.onrr.gov/about/pdfdocs/20140328.pdf
http://www.onrr.gov/about/pdfdocs/20140327.pdf
http://www.onrr.gov/about/pdfdocs/20140318EITI.pdf
http://www.onrr.gov/about/pdfdocs/20140226.pdf
http://www.onrr.gov/about/pdfdocs/20140122.pdf
http://www.onrr.gov/about/pdfdocs/20140108.pdf
http://www.onrr.gov/about/pdfdocs/11-13-DOI-SummaryDisbursementsData.pdf
http://www.onrr.gov/about/pdfdocs/20131119a.pdf
http://www.onrr.gov/about/pdfdocs/20131113.pdf
http://www.onrr.gov/about/pdfdocs/20131022a.pdf
http://www.onrr.gov/about/pdfdocs/20131022.pdf
http://www.onrr.gov/about/pdfdocs/20131021.pdf
http://www.onrr.gov/about/pdfdocs/20131013.pdf
http://www.onrr.gov/about/pdfdocs/20130916.pdf
http://www.onrr.gov/about/pdfdocs/20130819.pdf
http://www.onrr.gov/about/pdfdocs/20130812a.pdf
http://www.onrr.gov/about/pdfdocs/20130812.pdf
http://www.onrr.gov/about/pdfdocs/20130708.pdf
http://www.onrr.gov/about/pdfdocs/20130620.pdf
http://www.onrr.gov/about/pdfdocs/OXY_USA_Civil_Penalty.pdf
http://www.onrr.gov/about/pdfdocs/ONRR_Dynamic_Offshore_Civil_Penalty.pdf
http://www.onrr.gov/about/pdfdocs/20130402.pdf
http://www.onrr.gov/about/pdfdocs/20130301.pdf
http://www.onrr.gov/about/pdfdocs/20130104.pdf
http://www.onrr.gov/about/pdfdocs/20121206-disbursments.pdf
http://www.onrr.gov/about/pdfdocs/20121206.pdf
http://www.onrr.gov/about/pdfdocs/20120822EITI.pdf
http://www.onrr.gov/about/pdfdocs/20120726.pdf
http://www.onrr.gov/about/pdfdocs/20120718.pdf
http://www.onrr.gov/about/pdfdocs/20120711.pdf
http://www.onrr.gov/about/pdfdocs/20120703.pdf
http://www.onrr.gov/about/pdfdocs/20120509.pdf
http://www.onrr.gov/about/pdfdocs/20120430.pdf
http://www.onrr.gov/about/pdfdocs/20120420.pdf
http://www.onrr.gov/about/pdfdocs/20120416.pdf
http://www.onrr.gov/about/pdfdocs/20120405.pdf
http://www.onrr.gov/about/pdfdocs/20120329.pdf
http://www.onrr.gov/about/pdfdocs/20120316.pdf
http://www.onrr.gov/about/pdfdocs/20120312.pdf
http://www.onrr.gov/about/pdfdocs/20120307.pdf
http://www.onrr.gov/about/pdfdocs/20120307a.pdf
http://www.onrr.gov/about/pdfdocs/20120224.pdf
http://www.onrr.gov/about/pdfdocs/20120222.pdf
http://www.onrr.gov/about/pdfdocs/12-11ShellSettlementPressRelease.pdf
http://www.onrr.gov/about/pdfdocs/01-12-12BakkenIndianRevenuesrelease.pdf
http://www.onrr.gov/about/pdfdocs/ONRR_Peer_Review_Successful_11-02-11.pdf
http://www.onrr.gov/about/pdfdocs/11BillionMineralsrevenuesRevised_v2.pdf
http://www.onrr.gov/about/pdfdocs/FY2011StateDisbursements.pdf
http://www.onrr.gov/pdfdocs/GOMESAFY2011Final.pdf
http://www.onrr.gov/about/pdfdocs/20110916.pdf
http://www.onrr.gov/about/pdfdocs/20110913.pdf
http://www.onrr.gov/about/pdfdocs/20110913a.pdf
http://onrr.gov/Laws_R_D/FRNotices/PDFDocs/55838.pdf
http://onrr.gov/Laws_R_D/FRNotices/PDFDocs/55837.pdf
http://onrr.gov/About/PDFDocs/8-11EnergyResourcesCivilPenalty.pdf
http://www.onrr.gov/about/pdfdocs/20110720.pdf
http://www.onrr.gov/about/pdfdocs/20110620.pdf
http://www.onrr.gov/about/pdfdocs/20110526.pdf
http://www.onrr.gov/about/pdfdocs/20110524.pdf
http://www.onrr.gov/about/pdfdocs/20110510.pdf
http://www.onrr.gov/about/pdfdocs/363_CIV.pdf
http://www.onrr.gov/Unbundling/pdf/Enterprise%20Carlsbad%20Transportation%20System%20and%20Dew%20Point%20Plant.pdf
http://www.onrr.gov/About/PDFDocs/2-1_eCommerce_press_release.pdf
http://www.onrr.gov/About/PDFDocs/20110128.pdf
http://www.onrr.gov/About/PDFDocs/20101104a.pdf
http://www.onrr.gov/About/PDFDocs/20101104b.pdf
http://www.onrr.gov/About/PDFDocs/20101015.pdf
http://www.onrr.gov/FM/PDFDocs/20091106.pdf
http://www.onrr.gov/AssetManagement/PDFDocs/FY09RIKAnnualReport.pdf
http://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/32343.pdf
http://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/30430.pdf
http://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/22159.pdf

**Comment by mcharg** [comment]
@Maroyafaied The bulk of these are press releases and federal register notices.  I did a find and replace on the press releases XML file in dev.  Let me know if that looks good to push to the live site.
http://2017onrr/About/NewsReleases.htm

The FRN ones will be fixed when we swap out for links to the federal register.

The only other docs were the 4444 and instructions, which I already fixed, and AUP, which has been replaced with a newer link.

**Comment by Maroyafaied** [comment]
@mcharg these 3 press releases links don't work, in year 2010. They don't work in the live site either so it's not something you did. 
![image](https://user-images.githubusercontent.com/40175688/113764070-b5f80f00-96d7-11eb-9ad2-a22793975909.png)

**Comment by mcharg** [comment]
@Maroyafaied I created #643 to fix the broken links, since we need to figure out where they're supposed to link.

**Comment by mcharg** [comment]
Pushed to the live site.
