### ISSUE TITLE
Acceptable Use Policy for External Users - 2 docs

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#264]
We have two documents for the same thing.  We should consolidate to one.
https://www.onrr.gov/PDFDocs/ONRR_External_User_Acceptable_Use_Policy.pdf
https://www.onrr.gov/ReportPay/PDFDocs/ONRR_AUP.pdf

**Comment by jennmalcolm** [comment]
Get rid of old one and update any links to new one.

**Comment by jennmalcolm** [comment]
Find where this link is used in content audit.

**Comment by jennmalcolm** [comment]
I replaced the old version linked on this page with the updated version and archived the old version. Please review @mcharg 

http://2017onrr/reportpay/reporter-maintenance.htm

**Comment by mcharg** [comment]
The old one is also on the 3 checklist pages.

**Comment by jennmalcolm** [comment]
Ok, thanks @mcharg. I've updated those too in dev. 

http://2017onrr/reportpay/solids-checklist.htm
http://2017onrr/reportpay/roy-checklist.htm
http://2017onrr/reportpay/prod-checklist.htm

**Comment by mcharg** [comment]
The use policy button on the solids page is still opening the old one (with a 4040 error).
![image](https://user-images.githubusercontent.com/38465926/97496461-5a16a680-193f-11eb-8d70-049fd315d1c5.png)

**Comment by mcharg** [comment]
The other ones are also opening the old file.  Did you not post your changes?

**Comment by jennmalcolm** [comment]
Yes, but you might need to clear your cache. They're updated for me.

**Comment by mcharg** [comment]
@jennmalcolm Looks good.

**Comment by jennmalcolm** [comment]
Thanks, changes live
