### ISSUE TITLE
Analyze findings from handbook user interviews

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#266]

**Comment by mcharg** [comment]
Consolidated the first 6 participants.  We have one additional participant scheduled for tomorrow.
https://teams.microsoft.com/l/file/59CE9D34-39CA-46F6-A7B4-8C2A41D6B68F?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FUser%20Research%2FStudies%2F04_Handbooks%2FConsolidatedFindings.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by mcharg** [comment]
@Maroyafaied @lpgoldstein Can you take a look and let me know if you disagree with anything?

**Comment by Maroyafaied** [comment]
@mcharg it looks great, no changes for me.

**Comment by lpgoldstein** [comment]
@mcharg looks good to me too.
