### ISSUE TITLE
Plan closed card sort

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#267]

**Comment by mcharg** [comment]
@jennmalcolm The plan is ready for you to review.
https://teams.microsoft.com/l/file/A6FE6D9C-E9F2-40DB-B04B-19BF89824760?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FUser%20Research%2FStudies%2F05_closed_card_sort%2FStudy%20Plan%20%26%20Guide%20edited%20for%20closed%20card%20sort.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by mcharg** [comment]
And the GitHub project.
https://github.com/ONRR-Research/onnr.gov-card-sort-closed/projects

**Comment by mcharg** [comment]
@Maroyafaied @lpgoldstein Can one of you take a look at the plan, since Jennifer is out?

**Comment by Maroyafaied** [comment]
@mcharg I have reviewed and put my comments.

**Comment by lpgoldstein** [comment]
@mcharg This looks good to me. I didn't have much to do with the last one but I think I could run a session just based on these directions.

**Comment by mcharg** [comment]
@lpgoldstein You have to accept the invite to the ONRR-Research org to see the GitHub link.

**Comment by lpgoldstein** [comment]
@mcharg I need a new invite please. Mine expired.
