### ISSUE TITLE
Remove IESC announcement

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#268]
@ONRRamandagarrison can we remove this meeting announcement from the IESC page now?

![image](https://user-images.githubusercontent.com/30806839/91477060-d6233e00-e86b-11ea-878e-ec0165e9b1eb.png)

**Comment by ONRRamandagarrison** [comment]
Yes, please!

Thank you,
Amanda

Amanda Garrison

Supervisory Minerals Revenue Specialist
Indian Energy Service Center
P: (720) 595-2025

**Comment by jennmalcolm** [comment]
thanks, done
