### ISSUE TITLE
Synch up the About rollover nav menu and left nav

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#269]
There are completely different things in the two menus and they're in a different order.  They should match.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/8d3e5fdd-46c8-46a6-9008-9307e59528d4)

**Comment by jennmalcolm** [comment]
Please review changes in dev @mcharg.

http://2017onrr/About/index.htm

**Comment by mcharg** [comment]
@jennmalcolm Looks good.

**Comment by jennmalcolm** [comment]
done
