### ISSUE TITLE
Link to Stats site on FOIA page

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#270]
It redirects to NRRD, but we might want to update the reference, so it doesn't refer to statistical information.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/6747514c-9b3c-4bcd-8caa-16bf16550868)

**Comment by Maroyafaied** [comment]
@jennmalcolm please review http://2017onrr/FOIA/index.htm
