### ISSUE TITLE
Update Interest Calculator and Interest on site

### ISSUE THREAD

**Issue by Sheetsj** [ONRR/onrr.gov-site#2701]
Hello,
On the late Payment & Underpayment Interest Table page, at https://onrr.gov/paying/interest?tabs=interest-rates,oil-gas, please make the following updates:

Add a new line at the top of the Late Payment & Underpayment table for Period 7/1/2023-9/30/2023. Oil and gas remains the same at 7%.

On the Late Payment & Underpayment Interest Table page, at https://onrr.gov/paying/interest?tabs=interest-rates,solid-minerals-geothermal, please make the following updates:

Please change line "4/1/2023-6/30/2023" interest to 3%
Add a new line at the top of the Late Payment & Underpayment table for Period 7/1/2023-9/30/2023. Solid's remains the same at 3%.

Replace the Interest Calculator excel file at https://onrr.gov/paying/interest?tabs=interest-calculator with the attached below:

[Interest_Calculator_Master_v2.xlsx](https://github.com/DOI-ONRR/onrr.gov-site/files/11668419/Interest_Calculator_Master_v2.xlsx)

Thank you,

Jessica

**Comment by lpgoldstein** [comment]
@Sheetsj Ready for your review: https://dev-onrr-frontend.app.cloud.gov/paying/interest?tabs=interest-calculator

**Comment by Sheetsj** [comment]
Everything looks great. Thank you!

**Comment by lpgoldstein** [comment]
@Sheetsj Live! https://onrr.gov/paying/interest?tabs=interest-rates,solid-minerals-geothermal Have a good evening.
