### ISSUE TITLE
Email FOIA link is missing envelope icon

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#272]
On the Contact Us page:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/ee02b8b5-3343-44f5-83e2-acd49137c616)

**Comment by lpgoldstein** [comment]
@mcharg Please check http://2017onrr/About/contact.htm

**Comment by mcharg** [comment]
@lpgoldstein Looks good.
