### ISSUE TITLE
The 4444 has three different links

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#274]
https://www.onrr.gov/reportpay/PDFDocs/ONRR4444.pdf
http://www.onrr.gov/ReportPay/PDFDocs/ONRR4444.pdf
https://www.onrr.gov/ReportPay/PDFDocs/4444.pdf

And the instructions has two:
https://www.onrr.gov/ReportPay/PDFDocs/ONRR4444_Instructions.pdf
http://www.onrr.gov/ReportPay/PDFDocs/ONRR4444_Instructions.pdf

We should settle on the definitive location for each and use the same for in all locations.

**Comment by mcharg** [comment]
@lpgoldstein I think I have this updated in dev.  Can you please review?

All the links should have https and have ONRR before 4444.

Homepage: http://2017onrr/
Setup & Maintenance: http://2017onrr/reportpay/reporter-maintenance.htm
Production Checklist: http://2017onrr/reportpay/prod-checklist.htm
Royalty Checklist: http://2017onrr/reportpay/roy-checklist.htm
Solids Checklist: http://2017onrr/reportpay/solids-checklist.htm
Forms: http://2017onrr/reportpay/Forms/index.htm

**Comment by lpgoldstein** [comment]
@mcharg Looks good

**Comment by mcharg** [comment]
Updated in production
