### ISSUE TITLE
Remove Link from Public Comments header - https://www.onrr.gov/Laws_R_D/FRNotices/AD04.htm

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/onrr.gov-site#277]
This link is a circular reference to the main page of and makes no sense 
![image](https://user-images.githubusercontent.com/39419003/91745393-23f3bb00-eb78-11ea-88d5-bc59bb1444a1.png)
https://www.onrr.gov/Laws_R_D/FRNotices/AD04.htm#

**Comment by Maroyafaied** [comment]
@jennmalcolm please review, the link was in a few places under each year.  http://2017onrr/Laws_R_D/FRNotices/AD04.htm#

**Comment by jennmalcolm** [comment]
Looks good to me
