### ISSUE TITLE
Federal Register Notices have an extra pdf icon

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#278]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/a6287189-573e-4c95-84e7-2172e668f0c0)

**Comment by jennmalcolm** [comment]
I ran out of time to dig into the files and figure this out, so we'll have to move it to next sprint, and I might need a developer to help with it.

**Comment by jlouis-onrr** [comment]
@Maroyafaied, this update is now in the dev enviroment: http://2017onrr/

**Comment by Maroyafaied** [comment]
@jlouis-onrr I appreciate you taking care of this. @jennmalcolm can you review and publish it? Thank you both.

**Comment by jennmalcolm** [comment]
Thanks @jlouis-onrr it looks good in dev. What files did you update so I know what to push to production? Thanks.

**Comment by jlouis-onrr** [comment]
@Maroyafaied and @jennmalcolm, you should now be seeing this update out in production:

https://www.onrr.gov/Laws_R_D/FRNotices/index.htm

**Comment by jennmalcolm** [comment]
Yes, it's in production.
