### ISSUE TITLE
Webpage Updates (cross Reference Lease to Agreement)

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#281]
Hello, please update the following webpage - http://www.onrr.gov/ReportPay/CrossRef.htm

Cross-Reference Lease to Agreement Numbers sorted by Agreement Name
Cross-Reference Lease to Agreement Numbers sorted by Agreement Number
Cross-Reference Lease to Agreement Numbers sorted by Lease Number

with the attached PDF files. Please also change updated for all three to 09/01/2020.

[CRAName.pdf](https://github.com/ONRR/onrr.gov-site/files/5163004/CRAName.pdf)
[CRANumber.pdf](https://github.com/ONRR/onrr.gov-site/files/5163009/CRANumber.pdf)
[CRLNumber.pdf](https://github.com/ONRR/onrr.gov-site/files/5163010/CRLNumber.pdf)

Thank you

**Comment by lpgoldstein** [comment]
@merrellc The pdfs that you sent don't meet accessibility standards. I'm attaching the accessibility reports and the pdfs with the reports as an attachment. Please review our [wiki](https://github.com/ONRR/onrr.gov-site/wiki/Accessibility) for assistance with fixing the errors 
[CRL Number Accessibility Report.pdf](https://github.com/ONRR/onrr.gov-site/files/5164464/CRL.Number.Accessibility.Report.pdf)
[CRAName Accessibility Report.pdf](https://github.com/ONRR/onrr.gov-site/files/5164465/CRAName.Accessibility.Report.pdf)
[CRANumber Accessibility Report.pdf](https://github.com/ONRR/onrr.gov-site/files/5164468/CRANumber.Accessibility.Report.pdf)



[CRLNumber_check.pdf](https://github.com/ONRR/onrr.gov-site/files/5164452/CRLNumber_check.pdf)
[CRAName_check.pdf](https://github.com/ONRR/onrr.gov-site/files/5164454/CRAName_check.pdf)
[CRANumber_check.pdf](https://github.com/ONRR/onrr.gov-site/files/5164455/CRANumber_check.pdf)

**Comment by merrellc** [comment]
Attached are the updated dcuments.  Please let me know if more changes are required.

Thank you

[CRAName.pdf](https://github.com/ONRR/onrr.gov-site/files/5176898/CRAName.pdf)
[CRANumber.pdf](https://github.com/ONRR/onrr.gov-site/files/5176900/CRANumber.pdf)
[CRLNumber.pdf](https://github.com/ONRR/onrr.gov-site/files/5176902/CRLNumber.pdf)

**Comment by lpgoldstein** [comment]
@merrellc Each file still has 3 issues that are the same for each file. I'm attaching the new accessibility reports and then will follow up by email/phone. 
[CRANumber Accessibility Report 9_8_2020.pdf](https://github.com/ONRR/onrr.gov-site/files/5189619/CRANumber.Accessibility.Report.9_8_2020.pdf)
[CRLNumber Accessibility Report 9_08_2020.pdf](https://github.com/ONRR/onrr.gov-site/files/5189621/CRLNumber.Accessibility.Report.9_08_2020.pdf)
[CRAName Accessibility Report 9_08_2020.pdf](https://github.com/ONRR/onrr.gov-site/files/5189622/CRAName.Accessibility.Report.9_08_2020.pdf)

**Comment by merrellc** [comment]
Thank you.  I will try and have to you later today after my meetings.


Kindly,
​Candace Merrell
Office of Natural Resources Revenue

Reference and Reporting Management

Candace.Merrell@onrr.gov

303-231-3517

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________

**Comment by lpgoldstein** [comment]
Sure!
________________________________

**Comment by lpgoldstein** [comment]
@merrellc Here is this file with the accessibility check attached. I've also included a few screen shots of the report. Adobe thinks that the first few columns of every row are part of a header. And then for the nesting, it's highlighting part of the header. 
![image](https://user-images.githubusercontent.com/39419003/92788106-e73d7600-f366-11ea-93e9-94f1a51a8d02.png)

[CRAName_Accessibility_091020.pdf](https://github.com/ONRR/onrr.gov-site/files/5204131/CRAName_Accessibility_091020.pdf)

![image](https://user-images.githubusercontent.com/39419003/92787811-aa717f00-f366-11ea-98dd-66e0a2b1ef37.png)

**Comment by lpgoldstein** [comment]
Closing this issue because @merrellc will wait to update until next month.
