### ISSUE TITLE
Update Indian Index Zone prices on ONRR.gov

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#286]
Please update the August index zone values on the ONRR.gov website. The data can be found in our OneDrive in a spreadsheet called "Data for ONRR.gov" in the first tab "Index-Zones".

@sudarr

Thanks!

**Comment by lpgoldstein** [comment]
@boices This is ready for your review: http://2017onrr/Valuation/allzones.htm

**Comment by boices** [comment]
Looks good--thank you!

**Comment by lpgoldstein** [comment]
@boices It's live! https://www.onrr.gov/Valuation/allzones.htm
