### ISSUE TITLE
create redirects for old MRRH to new handbook

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#287]

**Comment by jennmalcolm** [comment]
Redirects created for these old links:
https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Chapter-1.pdf
https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Chapter-2.pdf
https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Chapter-3.pdf
https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Chapter-4.pdf
https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Chapter-5.pdf
https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Chapter-6.pdf
https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Chapter-7.pdf
https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Chapter-8.pdf
https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Appendix-A.pdf
https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Appendix-B.pdf
https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Appendix-C.pdf
https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Appendix-D.pdf
https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Appendix-E.pdf
https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Appendix-F.pdf
https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Appendix-G.pdf
https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Table-of-Contents.pdf
https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Glossary.pdf

**Comment by jennmalcolm** [comment]
@lpgoldstein could you review my work on the redirects? Thanks.

**Comment by lpgoldstein** [comment]
@jennmalcolm they all look good!

**Comment by lpgoldstein** [comment]
@jennmalcolm they all look good.

**Comment by jennmalcolm** [comment]
Thanks @lpgoldstein
