### ISSUE TITLE
Posting of August NYMEX prices

### ISSUE THREAD

**Issue by jpenvose773** [ONRR/onrr.gov-site#288]
Hi ONRR.gov team! I am writing to see if you could please add the August NYMEX and NYMEX roll prices to ONRR.gov. I've attached the file with the data you need. Let me know if you aren't able to access it or if you need the data sent to you via another method.

Thanks!
Jessica

@sudarr
[NYMEX0820.xlsx](https://github.com/ONRR/onrr.gov-site/files/5189861/NYMEX0820.xlsx)

**Comment by Maroyafaied** [comment]
@jpenvose773
 As previously communicated by ONRR’s Deputy Director, as of September 1, 2020, electronic documents submitted for posting on onrr.gov must be accessible to employees and members of the public with disabilities. 

The document you have requested to be uploaded on onrr.gov is not accessible and does not meet the 508 compliance standards.  Attached is a snapshot of the  identified accessibility errors (merged cells) that must be corrected by the document owner before the Data Display team is able to upload the document on onrr.gov.  To check accessibility on excel, click on the "Review" tab then click on "check accessibility", the results will show on the right side. 

Section 508 of the Rehabilitation Act of 1973, as amended, requires that all Information and Communication Technology developed, procured, maintained, or used by federal agencies must be fully accessible to employees and members of the public with disabilities. 

Data Display has created a list of resources and available training to assist with this process. If you have questions, please feel free to contact Data Display at onrrweb@onrr.gov. 

![image](https://user-images.githubusercontent.com/40175688/92518189-30f65700-f1d5-11ea-9a97-2e41ca9f1540.png)

**Comment by jpenvose773** [comment]
Thank you for advising us of this issue. I have checked the file and fixed all instances of merged cells. I also ran the Accessibility Checker and it said there are no more issues. But if there is something that the software doesn't catch that needs to be addressed, please let me know. I have attached a new version of the file that has been corrected.
[NYMEX082020_508Compliant.xlsx](https://github.com/ONRR/onrr.gov-site/files/5191186/NYMEX082020_508Compliant.xlsx)

**Comment by Maroyafaied** [comment]
@jpenvose773 the file looks great, thanks for making it accessible. Please review the updated changes on the dev site. 

http://2017onrr/Valuation/NYMEX.htm

**Comment by jpenvose773** [comment]
The information on the development site looks good. When I clicked to view the Excel file it said "File Not Found" but I suspected that was because it's the dev site and once it's on the live site it will work as expected. Thanks for doing this and for helping us with the accessibility issues!

**Comment by Maroyafaied** [comment]
@jpenvose773 the file should work on the dev site now and it will be posted live soon. Thanks

**Comment by Maroyafaied** [comment]
This is live now.
