### ISSUE TITLE
Web Page - Federal Onshore Terminable Leases

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#290]
Please update the following webpage http://www.onrr.gov/ReportPay/royalty-reporting.htm with the attached PDF file:

Federal Onshore Terminable Leases - sorted by Due Date, update to read (update 9/8/2020).
[FLTerm.pdf](https://github.com/ONRR/onrr.gov-site/files/5197263/FLTerm.pdf)

**Comment by lpgoldstein** [comment]
@bowlenj As previously communicated by ONRR’s Deputy Director, as of September 1, 2020, electronic documents submitted for posting on onrr.gov must be accessible to employees and members of the public with disabilities.

The document you have requested to be uploaded on onrr.gov is not accessible and does not meet the 508 compliance standards. Attached is the accessibility report with the identified accessibility errors that must be corrected by the document owner before the Data Display team is able to upload the document on onrr.gov.

Section 508 of the Rehabilitation Act of 1973, as amended, requires that all Information and Communication Technology developed, procured, maintained, or used by federal agencies must be fully accessible to employees and members of the public with disabilities.

Data Display has created a [list of resources](https://github.com/ONRR/onrr.gov-site/wiki/Accessibility) and available training to assist with this process. If you have questions, please feel free to contact Data Display at onrrweb@onrr.gov.

Here is the file with the accessibility report attached and the separate report. There are just a few issues! 
[FLTerm (9).pdf](https://github.com/ONRR/onrr.gov-site/files/5197511/FLTerm.9.pdf)
[FLTerm Accessibility Report 9_9_2020.pdf](https://github.com/ONRR/onrr.gov-site/files/5197515/FLTerm.Accessibility.Report.9_9_2020.pdf)

**Comment by Maroyafaied** [comment]
@bowlenj Thank you for making the document accessible, it has passed all the checks. Please review the updates on the dev site and let me know if everything looks correct.  Thanks

 http://2017onrr/ReportPay/royalty-reporting.htm

**Comment by lpgoldstein** [comment]
@bowlenj It's live. @Maroyafaied closing the issue
