### ISSUE TITLE
Webpage update (Indian Fund Code)

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#293]
Please update the following webpage - http://onrr.gov/ReportPay/payments.htm with the attached files:
Indian Leases Cross-walked to Distributee codes
Downloadable Excel Version Indian Leases Cross-walked to Distributee Codes

Also change updated to read 09/18/2020 for both files.

In addition to the above, please update the updated date to 09/18/2020 on URL http://www.onrr.gov/ReportPay/royalty-reporting.htm for the same file linked to this URL.

Thank You

[FCIL.pdf](https://github.com/ONRR/onrr.gov-site/files/5246855/FCIL.pdf)
[FCIL.xlsx](https://github.com/ONRR/onrr.gov-site/files/5246860/FCIL.xlsx)

**Comment by Maroyafaied** [comment]
@merrellc 
As previously communicated by ONRR’s Deputy Director, as of September 1, 2020, electronic documents submitted for posting on onrr.gov must be accessible to employees and members of the public with disabilities.

The pdf document you have requested to be uploaded on onrr.gov is not accessible and does not meet the 508 compliance standards, the excel file passed the accessibility checks. Attached is the accessibility report of the identified accessibility errors
[FCIL report.pdf](https://github.com/ONRR/onrr.gov-site/files/5257530/FCIL.report.pdf)
  that must be corrected by the document owner before the Data Display team is able to upload the document on onrr.gov. 

Section 508 of the Rehabilitation Act of 1973, as amended, requires that all Information and Communication Technology developed, procured, maintained, or used by federal agencies must be fully accessible to employees and members of the public with disabilities.

Data Display has created [a list of resources](https://github.com/ONRR/onrr.gov-site/wiki/Accessibility) and available training to assist with this process. If you have questions, please feel free to contact Data Display at onrrweb@onrr.gov.

[FCIL report.pdf](https://github.com/ONRR/onrr.gov-site/files/5257532/FCIL.report.pdf)

**Comment by merrellc** [comment]
Please let me know if this is okay.

Thank you
[FCIL.pdf](https://github.com/ONRR/onrr.gov-site/files/5262349/FCIL.pdf)

**Comment by merrellc** [comment]
Let's see if this worked.
[FCIL.pdf](https://github.com/ONRR/onrr.gov-site/files/5263337/FCIL.pdf)

**Comment by Maroyafaied** [comment]
@merrellc looks great! Please review the dev site and let me know if everything looks correct.

http://2017onrr/ReportPay/payments.htm

http://2017onrr/ReportPay/royalty-reporting.htm

**Comment by merrellc** [comment]
Great!


Thank you
​Candace Merrell
Office of Natural Resources Revenue

Reference and Reporting Management

Candace.Merrell@onrr.gov

303-231-3517

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________

**Comment by merrellc** [comment]
Ready to Go.

Thank you

**Comment by Maroyafaied** [comment]
It's live now. Thanks
