### ISSUE TITLE
Update Contact list on ONRR.GOV

### ISSUE THREAD

**Issue by Sheetsj** [ONRR/onrr.gov-site#295]
Hello, I need to have updated the contact AR list. Location on ONRR.gov  - Home>About>Contact us>Accounts receivable, Billing, and Financial Issues Information - Federal.  This is located under Online Resources>  ONRR Contacts by Company Assignment. 

On the N'Drive the PDF file name is finserAssign. Located -Den_Common>FMD>FinancialServices>Admin>Fed Assignment Contact List

Please let me know if you have any questions or concerns about this. 

Thank you so much!

**Comment by jennmalcolm** [comment]
@Sheetsj the change is ready for your review on our development site. Please let us know if you approve to make live:

http://2017onrr/About/contact.htm

**Comment by Sheetsj** [comment]
@jennmalcolm thank you! I approve to go live.

**Comment by jennmalcolm** [comment]
changes live
