### ISSUE TITLE
Royalty reporting contact update

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#299]
Please update the attached listing on the onrr.gov webpage at the following address:  https://www.onrr.gov/ReportPay/PDFDocs/royassign.pdf 

I submitted a heat ticket (RITM0361079) and it hasn't been updated yet.  I forgot about sending to this address. 
[royassign.pdf](https://github.com/ONRR/onrr.gov-site/files/5294351/royassign.pdf)

**Comment by jennmalcolm** [comment]
sent accessibility report by email for corrections

**Comment by jennmalcolm** [comment]
Requester resubmitted document, and I sent a new error report by email.

**Comment by lpgoldstein** [comment]
In review via email. Errors corrected

**Comment by lpgoldstein** [comment]
approved via email
