### ISSUE TITLE
Remove "recommended by ONRR" search results

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#302]
Search results still can give bad "Recommended by ONRR." This result recommends a dev site that doesn't exist. 
![image](https://user-images.githubusercontent.com/30806839/94813027-c0e28780-03b4-11eb-881f-8677f6b6fcdb.png)

**Comment by mcharg** [comment]
I figured out how to remove the "best bets" in search.gov.
https://search.usa.gov/search?query=ogor&affiliate=ONRR

**Comment by Maroyafaied** [comment]
Looks good!
