### ISSUE TITLE
Updates to language

### ISSUE THREAD

**Issue by jpetersononrr** [ONRR/onrr.gov-site#307]
Hello!

The Exec Sec office asked that we add new language to our guidance pages.  The language is more of a disclaimer, so if it could be in font that indicates that at the bottom of the following pages, that would be great (either slightly smaller or something like that):

Language:
Note on ONRR guidance:
•	Guidance documents lack the force and effect of law unless expressly authorized by statute or incorporated into a contract.
•	ONRR may not cite, use, or rely on any guidance that is not posted on the website existing under EO 13891, except to establish historical facts.

Pages:
https://www.onrr.gov/ReportPay/policy.htm
https://www.onrr.gov/DearRep.htm
https://www.onrr.gov/ReportPay/Handbooks/
https://www.onrr.gov/ReportPay/training/index.htm
https://www.onrr.gov/unbundling/index.htm
https://www.onrr.gov/valuation/index.htm

Thanks for your help!

Jodie

**Comment by jennmalcolm** [comment]
@jpetersononrr, please review the changes in dev. 

http://2017onrr/ReportPay/policy.htm
http://2017onrr/dearrep.htm
http://2017onrr/ReportPay/Handbooks/index.htm
http://2017onrr/ReportPay/training/index.htm
http://2017onrr/unbundling/index.htm
http://2017onrr/Valuation/index.htm

**Comment by jpetersononrr** [comment]
That looks great!!  Thank you!

**Comment by jennmalcolm** [comment]
These are live now.
