### ISSUE TITLE
October Indian Index Zone prices on ONRR.gov

### ISSUE THREAD

**Issue by jpenvose773** [ONRR/onrr.gov-site#310]
Please update the Indian Index Zone prices for October on ONRR.gov. The data has been updated with the newest prices in the Data for ONRR.gov Excel spreadsheet.

@sudarr

**Comment by Maroyafaied** [comment]
@jpenvose773 please review the updates. Thanks 

http://2017onrr/Valuation/allzones.htm

**Comment by jpenvose773** [comment]
Hi Maroya,

The prices look good. I was wondering about something, though. Is it possible to fix the formatting on the prices so that it shows both digits after the decimal point? For example, the $1.70 price this month shows up as “1.7”. and I thought I saw a $2.00 price one of the months that showed up as “$2”. The latter isn’t the worst thing ever, but to see .7 instead of .70 is a little odd. I was just curious if this could be corrected so that it looks better visually. If not, the prices for this month as good to go!

Thanks!
Jessica

**Comment by Maroyafaied** [comment]
@jpenvose773 I changed the formatting, please review. Thanks 

http://2017onrr/Valuation/allzones.htm

**Comment by jpenvose773** [comment]
That looks great; thank you so much for doing that! Everything looks good to go.

**Comment by Maroyafaied** [comment]
It's live now. Thank you!
