### ISSUE TITLE
Put 508 audit procedures in Wiki

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#313]

**Comment by jennmalcolm** [comment]
@lpgoldstein and @Maroyafaied please review the procedures for checking accessibility in adobe that I've added to the onrr.gov Wiki. If they look good to you, I think I'll add a link to this page from the accessibility resources page. I don't think I will add it to our main Wiki menu--unless you want me to.

https://github.com/ONRR/onrr.gov-site/wiki/Checking-the-accessibility-of-a-PDF

**Comment by Maroyafaied** [comment]
@jennmalcolm these steps don't work for me, do they work for you @lpgoldstein? I usually go to accessibility report then click on the paper clip icon and click then link from there. Most likely I'm doing something wrong but I tried it a few times. 
![image](https://user-images.githubusercontent.com/40175688/98309242-38dd3800-1f87-11eb-847b-bd2f8ca27771.png)

**Comment by lpgoldstein** [comment]
@jennmalcolm I usually do what @Maroyafaied does. I then copy and paste into word. When I tried to save it your way, it was saved as an an html file but I was unable to save it as anything else.

**Comment by jennmalcolm** [comment]
So do neither of you have the option to "create a pdf from file" in your menus @Maroyafaied or @lpgoldstein, or is it just not working?

**Comment by Maroyafaied** [comment]
@jennmalcolm I have it in my menu but it doesn't create a pdf.  I go to the paper clip then open the html link and copy and paste the report into a word doc.  Maybe you can show me your way during our 1:1 this morning, it seems much easier so I'd like to know what I'm doing wrong. 
![image](https://user-images.githubusercontent.com/40175688/98683920-d38c9c80-2322-11eb-9761-9600e50e69cf.png)

**Comment by jennmalcolm** [comment]
Ok, let's try it in the meeting, but either way I will need to edit the directions since they're not sufficient to follow. I'll work on that after the meeting.

**Comment by jennmalcolm** [comment]
@lpgoldstein I made a couple changes to the directions to try to make it more clear. Can you please check if you can follow the process now?

**Comment by lpgoldstein** [comment]
@jennmalcolm I was able to follow the directions successfully! Thanks!

**Comment by jennmalcolm** [comment]
Ok, thanks @lpgoldstein. I'll be closing this issue then.
