### ISSUE TITLE
Please update the Rules and Regulations web page as follows

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#317]
Hello,

Please update the Rules and Regulations web page as follows:

Under the following link:
https://www.onrr.gov/Laws_R_D/FRNotices/ICR0122.htm

Under the "Federal Register Publications and Comments" heading and above the last posting,
Please add the following:

30-Day [Agency Information Collection](https://www.federalregister.gov/documents/2020/07/14/2020-15124/agency-information-collection-activities-submission-to-the-office-of-management-and-budget-for) (85 FR 42426--July 14, 2020)

Please make the "Agency Information Collection" portion of the statement above a hyperlink to the following website:
https://www.federalregister.gov/documents/2020/07/14/2020-15124/agency-information-collection-activities-submission-to-the-office-of-management-and-budget-for

Please let me know if you have any questions.

Thanks for your time,
Christine Thomas

**Comment by lpgoldstein** [comment]
@cthomasONRR Here is the accessibility report for your document: 
[1012-0006_30.Day.Notice_07-14-2020.pdf  Accessibility Report.docx](https://github.com/ONRR/onrr.gov-site/files/5357277/1012-0006_30.Day.Notice_07-14-2020.pdf.Accessibility.Report.docx)
[1012-0006_30.Day.Notice_07-14-2020.pdf](https://github.com/ONRR/onrr.gov-site/files/5357278/1012-0006_30.Day.Notice_07-14-2020.pdf)



As previously communicated by ONRR’s Deputy Director, as of September 1, 2020, electronic documents submitted for posting on onrr.gov must be accessible to employees and members of the public with disabilities.

The pdf documents you have requested to be uploaded on onrr.gov aren't accessible and don't meet the 508 compliance standards. Attached are the accessibility report of the identified accessibility errors that must be corrected by the document owner before the Data Display team is able to upload the document on onrr.gov.

Section 508 of the Rehabilitation Act of 1973, as amended, requires that all Information and Communication Technology developed, procured, maintained, or used by federal agencies must be fully accessible to employees and members of the public with disabilities.

Data Display has created a list of resources and available training to assist with this process. If you have questions, please let us know.

**Comment by cthomasONRR** [comment]
@lpgoldstein ,

The PDFs are directly from the Federal Register. ONRR is not able to modify these documents. We have previously published the same PDFs on https://www.onrr.gov/Laws_R_D/FRNotices/ICR0122.htm and other ICR webpages. I am not sure how to proceed since we are not able to modify these documents.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
Hello, as per our 508-compliance discussion with Lindsay Goldstein-

Instead of using the PDF hyperlink, could you instead link to the following Federal Register website:
https://www.federalregister.gov/documents/2020/07/14/2020-15124/agency-information-collection-activities-submission-to-the-office-of-management-and-budget-for

Please let me know if you have any questions.

Thanks,
Christine

**Comment by lpgoldstein** [comment]
@cthomasONRR Please review your requested changes: http://2017onrr/Laws_R_D/FRNotices/iCR0122.htm

**Comment by cthomasONRR** [comment]
@lpgoldstein , Looks great! I approve. Thanks for all your help!

**Comment by lpgoldstein** [comment]
@cthomasONRR your changes are live!
