### ISSUE TITLE
Request to Update ONRR Rules and Regulations Webpage

### ISSUE THREAD

**Issue by aklong09** [ONRR/onrr.gov-site#318]
Hi,

Please update the ONRR webpage located at https://www.onrr.gov/Laws_R_D/FRNotices/ICR0073.htm

Under the Federal Register Publications heading, please create a new bulleted entry above the last posting as follows:
"30-Day Agency Information Collection - (85 FR  55490--September 8, 2020)"

Please add a hyperlink to the "(85 FR 55490--September 8, 2020)" to the following attachment:
[30-Day Notice (85 FR 55490).pdf](https://github.com/ONRR/onrr.gov-site/files/5355919/30-Day.Notice.85.FR.55490.pdf)

Please let me know if you have any questions.

Thank you,
Alexis

**Comment by lpgoldstein** [comment]
@aklong09 
[30-Day.Notice.85.FR.55490.pdf](https://github.com/ONRR/onrr.gov-site/files/5357318/30-Day.Notice.85.FR.55490.pdf)
[30-Day.Notice.85.FR.55490.pdf Accessibility Report.docx](https://github.com/ONRR/onrr.gov-site/files/5357319/30-Day.Notice.85.FR.55490.pdf.Accessibility.Report.docx)

As previously communicated by ONRR’s Deputy Director, as of September 1, 2020, electronic documents submitted for posting on onrr.gov must be accessible to employees and members of the public with disabilities.

The pdf documents you have requested to be uploaded on onrr.gov aren't accessible and don't meet the 508 compliance standards. Attached are the accessibility report of the identified accessibility errors that must be corrected by the document owner before the Data Display team is able to upload the document on onrr.gov.

Section 508 of the Rehabilitation Act of 1973, as amended, requires that all Information and Communication Technology developed, procured, maintained, or used by federal agencies must be fully accessible to employees and members of the public with disabilities.

Data Display has created a list of resources and available training to assist with this process. If you have questions, please let us know.

**Comment by aklong09** [comment]
Hi, 
Please see the **updated request** below:

Please update the ONRR webpage located at https://www.onrr.gov/Laws_R_D/FRNotices/ICR0073.htm

Under the Federal Register Publications heading, please create a new bulleted entry above the last posting as follows:
"30-Day Agency Information Collection - (85 FR 55490--September 8, 2020)"

Please make the "Agency Information Collection" portion of the statement above a hyperlink to the following website: https://www.federalregister.gov/documents/2020/09/08/2020-19763/agency-information-collection-activities-submission-to-the-office-of-management-and-budget-for 

Please let me know if you have any questions. Thanks so much for your assistance and your patience!

**Comment by lpgoldstein** [comment]
@aklong09 This is ready for your review: http://2017onrr/Laws_R_D/FRNotices/ICR0073.htm

**Comment by aklong09** [comment]
Good morning. Looks good to me. Thanks again!

**Comment by lpgoldstein** [comment]
@aklong09 Your changes are live!
