### ISSUE TITLE
Please update the Federal Register Notices web page as follows

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#319]
Hello,

Please update the Federal Register Notices web page located at:
https://www.onrr.gov/Laws_R_D/FRNotices/index.htm

Please add two new entries under the "FR Notices 2020" heading.

FIRST ENTRY:

Below the February 25, 2020 entry (FR 7221), please add:

"FR 5033
Tuesday, January 28, 2020
**Denver, CO** In accordance with the Paperwork Reduction Act of 1995, the Office of Natural Resources Revenue is proposing to renew an information collection request. OMB Control Number 1012-0005."

Please add a hyperlink titled "View FR document" to the following website:
https://www.federalregister.gov/documents/2020/01/28/2020-01360/agency-information-collection-activities-submission-to-the-office-of-management-and-budget-for

SECOND ENTRY:

Above the March 27, 2020 entry (FR 17362), please add:

"FR 42426
Tuesday, July 14, 2020
**Denver, CO** In accordance with the Paperwork Reduction Act of 1995, the Office of Natural Resources Revenue is proposing to renew an information collection request. OMB Control Number 1012-0006."

Please add a hyperlink titled "View FR document" to the following website:
https://www.federalregister.gov/documents/2020/07/14/2020-15124/agency-information-collection-activities-submission-to-the-office-of-management-and-budget-for

Please let me know if you have any questions.

Thanks for your time,
Christine Thomas

**Comment by cthomasONRR** [comment]
As per our 508-compliance discussion with Lindsay Goldstein, please see the following updates to the original request. We will be replacing the PDF links with links to the Federal Register webiste.


Please update the Federal Register Notices web page located at:
https://www.onrr.gov/Laws_R_D/FRNotices/index.htm

Please add two new entries under the "FR Notices 2020" heading.

FIRST ENTRY:

Below the February 25, 2020 entry (FR 7221), please add:

"FR 5033
Tuesday, January 28, 2020
Denver, CO In accordance with the Paperwork Reduction Act of 1995, the Office of Natural Resources Revenue is proposing to renew an information collection request. OMB Control Number 1012-0005."

Please add a hyperlink titled "View FR document" to the following website:
https://www.federalregister.gov/documents/2020/01/28/2020-01360/agency-information-collection-activities-submission-to-the-office-of-management-and-budget-for

SECOND ENTRY:

Above the March 27, 2020 entry (FR 17362), please add:

"FR 42426
Tuesday, July 14, 2020
Denver, CO In accordance with the Paperwork Reduction Act of 1995, the Office of Natural Resources Revenue is proposing to renew an information collection request. OMB Control Number 1012-0006."

Please add a hyperlink titled "View FR document" to the following PDF attachment:
https://www.federalregister.gov/documents/2020/07/14/2020-15124/agency-information-collection-activities-submission-to-the-office-of-management-and-budget-for

Please let me know if you have any questions.

Thanks for your time,
Christine Thomas

**Comment by lpgoldstein** [comment]
@cthomasONRR Please review the changes here: http://2017onrr/Laws_R_D/FRNotices/index.htm

Note that we aren't able to title the hyperlink "View FR document" because the current formatting requires "View FR xxxxx document". We can change that wording when we reconfigure the site.

**Comment by cthomasONRR** [comment]
@lpgoldstein Thanks so much- I approve the required "View FR XXXXX document" wording.

**Comment by lpgoldstein** [comment]
@cthomasONRR changes are live! https://www.onrr.gov/Laws_R_D/FRNotices/index.htm
