### ISSUE TITLE
Analyze findings from onrr.gov user interviews

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#32]
After we finish the interviews.

**Comment by Maroyafaied** [comment]
@mcharg can you review the consolidated findings. I added the rest of the participants

https://doimspp-my.sharepoint.com/:x:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B1F2B30D3-9531-4133-ABBD-EC508A4B0FCD%7D&file=Consolidated%20Findings.xlsx&action=default&mobileredirect=true

**Comment by Maroyafaied** [comment]
@mcharg , Lindsay went through the majority of the comments and I made minor changes. I think it's good to close now?
