### ISSUE TITLE
Sept. 2020 IBMP Prices

### ISSUE THREAD

**Issue by damionschulte** [ONRR/onrr.gov-site#320]
All I have updated the OneDrive sheet with the September 2020 IBMP prices and they are ready to be published.  Thank you

@sudarr

**Comment by lpgoldstein** [comment]
@damionschulte please review: http://2017onrr/Valuation/IndianOilIBMP.htm

**Comment by damionschulte** [comment]
These look great!  Thank you.

**Comment by lpgoldstein** [comment]
@damionschulte It should be live at 7:15
