### ISSUE TITLE
100% Federal Agreements with the Same Royalty Rate & Royalty Distribution

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#321]
Please update the following webpage http://www.onrr.gov/ReportPay/royalty-reporting.htm with the attached PDF file.

100% Federal Agreements with the Same Royalty Rate & Royalty Distributions 

Also change (updated 7/1/2020) to read 10/1/2020.
[fedagmts.xlsx](https://github.com/ONRR/onrr.gov-site/files/5378430/fedagmts.xlsx)

**Comment by bowlenj** [comment]
I’m getting this error when I try to open the file on onrr.gov:

[cid:image002.jpg@01D6A21E.E93C9AB0]

Thank You,
Jessica Bowlen
Office of Natural Resource Revenue
Reference and Reporting Management
303-231-3202
Jessica.Bowlen@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

**Comment by Maroyafaied** [comment]
@bowlenj it should be fixed now, please try again. Thanks

**Comment by bowlenj** [comment]
Looks great, thank you!

Thank You,
Jessica Bowlen
Office of Natural Resource Revenue
Reference and Reporting Management
303-231-3202
Jessica.Bowlen@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

**Comment by Maroyafaied** [comment]
It's live now . Thanks
