### ISSUE TITLE
IBMP Price page

### ISSUE THREAD

**Issue by jpetersononrr** [ONRR/onrr.gov-site#323]
Hi!

I know this is MSA's page, but they're saying they can see the data just fine, but we in RV can't.  I tried the page in regular and dev just to see if you were maybe working on it?  It's this page:

https://www.onrr.gov/Valuation/IndianOilIBMP.htm

Here's what we see (Jahed brought it up and I tried it as well):

![image](https://user-images.githubusercontent.com/64428541/96029350-c5c52380-0e17-11eb-9f09-00f98b41f8dc.png)

Maybe the pic is there?  If not, there's a big red box saying "Data Currently Not Available!"

I told Jahed I'd submit it since I have an account already and if there's something he and I are missing then you can tell me I'm crazy!  Thanks!

**Comment by Maroyafaied** [comment]
@jpetersononrr we are working on fixing it. Thanks!

**Comment by Maroyafaied** [comment]
@jpetersononrr it's working now and the September prices will be up later today. Thanks https://www.onrr.gov/Valuation/IndianOilIBMP.htm
