### ISSUE TITLE
Request to Update ONRR Rules & Regulations, RIN 1012-AA27 Page

### ISSUE THREAD

**Issue by aklong09** [ONRR/onrr.gov-site#326]
Good evening, 

I am requesting changes to the ONRR website, located at https://www.onrr.gov/Laws_R_D/FRNotices/AA27.htm 

On the “Regulation Identifier Number 1012-AA27” page, please **remove** the following bulleted information, including the PDF that is currently linked:
•	Proposed Rulemaking (08/06/2020)

Following the current abstract narrative, please **add** the following text (with a space between the end of the abstract and the beginning of the text provided below):

“On October 1, 2020, ONRR’s proposed rule published in the Federal Register, at 85 Fed. Reg. 62054.  Through this proposed rule, ONRR is seeking public comment for a 60-day period.  Per the instructions in the proposed rule, all comments must be submitted on or before November 30, 2020. 

For more information, please visit https://www.regulations.gov/ (or https://beta.regulations.gov/) and search “ONRR-2020-0001” or click the following links:”

Under the above-mentioned text, please list the following text (and accompanying hyperlink) in bulleted format:

**Add Bullet 1:**  “To view the proposed rule:  https://www.regulations.gov/document?D=ONRR-2020-0001-0001”
**Add Bullet 2:**  “To access the docket folder:  https://www.regulations.gov/docket?D=ONRR-2020-0001”
**Add Bullet 3:**  “To submit comments:*  https://www.regulations.gov/comment?D=ONRR-2020-0001-0001”

Following the bullets, please **add** the following text (non-bullet format):  “*Hyperlink will be removed once the public comment period closes.”

Please let me know if you have any questions.

Thank you,
Alexis Long

**Comment by jennmalcolm** [comment]
@aklong09 please review the changes on our dev site, and let me you know you approve to publish on onrr.gov. Thanks.

http://2017onrr/Laws_R_D/FRNotices/AA27.htm

**Comment by aklong09** [comment]
Hi @jennmalcolm,

I tried the link you sent and I keep receiving an error message that says the site can't be reached.  Can you please resend the hyperlink?

Thank you!

**Comment by jennmalcolm** [comment]
@aklong09 are you on VPN? You have to be to see the dev site.

**Comment by aklong09** [comment]
@jennmalcolm  yep, that was the issue. Sorry about that! I reviewed the changes. Everything looks good to me, so I approve to publish. Thanks again!

**Comment by jennmalcolm** [comment]
Thanks, the changes are live now.
