### ISSUE TITLE
Please alter and move the guidance disclaimer on the following ONRR webpages

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#331]
Hello,

We need to add language to and move the guidance disclaimer that is located at the bottom of the following webpages:
https://www.onrr.gov/ReportPay/policy.htm
https://www.onrr.gov/DearRep.htm
https://www.onrr.gov/ReportPay/Handbooks/
https://www.onrr.gov/ReportPay/training/index.htm
https://www.onrr.gov/unbundling/index.htm
https://www.onrr.gov/valuation/index.htm

Currently the guidance disclaimer says:
"Note on ONRR guidance:
- Guidance documents lack the force and effect of law unless expressly authorized by statute or incorporated into a contract.
- ONRR may not cite, use, or rely on any guidance that is not posted on the website existing under EO 13891, except to establish historical facts."

Could you please modify the disclaimer to say the following:
"_[Executive Order 13891](https://www.federalregister.gov/documents/2019/10/15/2019-22623/promoting-the-rule-of-law-through-improved-agency-guidance-documents), "Promoting the Rule of Law Through Improved Agency Guidance Documents" directs all Federal agencies to ensure their guidance documents clarify only existing obligations that significantly affect the public, and do not create binding requirements outside of those developed through activities regulated by the [Administrative Procedure Act](https://www.archives.gov/federal-register/laws/administrative-procedure).

Please see [RIN 1093-AA27](https://www.federalregister.gov/documents/2020/10/26/2020-22238/procedures-for-issuing-guidance-documents) for Department of Interior’s Interim Final Rule implementing Executive Order 13891.

Note on ONRR guidance:
•	Guidance documents lack the force and effect of law unless expressly authorized by statute or incorporated into a contract.
•	ONRR may not cite, use, or rely on any guidance that is not posted on the website existing under EO 13891, except to establish historical facts._"

Please be sure to have "Executive Order 13891" be a hyperlink to the following website: https://www.federalregister.gov/documents/2019/10/15/2019-22623/promoting-the-rule-of-law-through-improved-agency-guidance-documents
Please be sure to have "Administrative Procedure Act" be a hyperlink to the following website:
https://www.archives.gov/federal-register/laws/administrative-procedure
Please be sure to have "RIN 1093-AA27" be a hyperlink to the following website:
https://www.federalregister.gov/documents/2020/10/26/2020-22238/procedures-for-issuing-guidance-documents

For all webpages listed here:
https://www.onrr.gov/ReportPay/policy.htm
https://www.onrr.gov/DearRep.htm
https://www.onrr.gov/ReportPay/Handbooks/
https://www.onrr.gov/ReportPay/training/index.htm
https://www.onrr.gov/unbundling/index.htm
https://www.onrr.gov/valuation/index.htm
Please move this revised guidance language from the bottom of the page to the top of the page. For example, at https://www.onrr.gov/ReportPay/policy.htm, please move the guidance language to be before the paragraph that begins with "ONRR publishes guidance in the form of Dear Reporter Letters, Handbooks, ... "

Please also put this guidance language in a text box, so it is set apart from the existing language on the webpage. I have included an example of how I would like this to look as a Word attachment in this request. 

Please let me know if you have any questions.

Thanks for your time and help,
Christine

[EO13891_WebpageLanguage.docx](https://github.com/ONRR/onrr.gov-site/files/5438993/EO13891_WebpageLanguage.docx)

**Comment by cthomasONRR** [comment]
Hi, Please PAUSE on this! I need to add an additional hyperlink! I will let you know when my request is updated!

**Comment by cthomasONRR** [comment]
Ok, I have added an additional hyperlink to the updated text, and updated the example word document. Sorry about that!

**Comment by jennmalcolm** [comment]
@cthomasONRR, please review the changes on our development site and let me know if you approve to publish to onrr.gov.

http://2017onrr/ReportPay/policy.htm
http://2017onrr/dearrep.htm
http://2017onrr/ReportPay/Handbooks/index.htm
http://2017onrr/ReportPay/training/index.htm
http://2017onrr/unbundling/index.htm
http://2017onrr/Valuation/index.htm

**Comment by cthomasONRR** [comment]
Hi Jennifer, 

This looks great!

Could you change "Please see RIN 1093-AA27 for Department of Interior’s Interim Final Rule implementing Executive Order 13891."

To "Please see RIN 1093-AA27, "Procedures for Issuing Guidance Documents" for the Department of Interior’s interim final rule implementing Executive Order 13891."

Please keep the same hyperlink on the "RIN 1093-AA27" part of the language.

After this wording change, it will be ready to publish!

Thanks so much for your time and help,
Christine

**Comment by cthomasONRR** [comment]
I see the updates on the development site links- it looks great. I approve to publish to onrr.gov.

Thanks!
Christine

**Comment by jennmalcolm** [comment]
The changes are live now.

**Comment by cthomasONRR** [comment]
Thanks so much for your help! It looks great!
