### ISSUE TITLE
Italics!

### ISSUE THREAD

**Issue by jpetersononrr** [ONRR/onrr.gov-site#333]
When the bullets got moved to the top of these pages, everything on the page got put in italics.  Could you fix the text outside the box?  Thanks!

https://www.onrr.gov/ReportPay/policy.htm
https://www.onrr.gov/DearRep.htm
https://www.onrr.gov/ReportPay/Handbooks/
https://www.onrr.gov/ReportPay/training/index.htm
https://www.onrr.gov/unbundling/index.htm
https://www.onrr.gov/valuation/index.htm

**Comment by jennmalcolm** [comment]
Thank you @jpetersononrr, please review the corrections in dev. 
http://2017onrr/ReportPay/policy.htm
http://2017onrr/DearRep.htm
http://2017onrr/ReportPay/Handbooks/index.htm
http://2017onrr/ReportPay/training/index.htm
http://2017onrr/unbundling/index.htm
http://2017onrr/Valuation/index.htm

**Comment by jpetersononrr** [comment]
Thank you!  That's so much easier to look at!
