### ISSUE TITLE
Production reporting references page

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#336]
I had a hard time finding where to update files because I don't think this page is on the navigation menus or linked anywhere
https://www.onrr.gov/ReportPay/references.htm

We should put on menu or at least link from the production page

**Comment by mcharg** [comment]
It's in the reporter tools in the right nav on all the reporting pages.
![image](https://user-images.githubusercontent.com/38465926/106156445-895fce00-614f-11eb-94b8-c5d8889dc0ad.png)

**Comment by jennmalcolm** [comment]
Ok, maybe we should just rename that link in the right nave to say Production Reporter References. I also am not a fan of that right nav/reporter tools section because it isn't specific reporting page you're on. For example when you're on solids reporting, you still just get links to all kinds of oil and gas stuff. Anyway, that's probably something to deal with in the re-design.

**Comment by mcharg** [comment]
Yeah, each reporting page has its own references tab in the redesign, so we can put only the stuff that's relevant there.  I like renaming it, for now.

**Comment by jennmalcolm** [comment]
done
