### ISSUE TITLE
Content update to IESC pages

### ISSUE THREAD

**Issue by ONRRamandagarrison** [ONRR/onrr.gov-site#339]
on this link:  https://www.onrr.gov/IndianServices/iescstaff.htm

Staff Role | Name/Email Contact | Agency

Change current contact to --> IESC Director (Delegated Authority) | Carla Clark | BIA (carla.clark@bia.gov)

NEW, need to add --> IESC Beneficiary Services Branch Chief (Fiduciary Trust Officer) | Michelle Deason | BTFA (michelle_deason@btfa.gov)

Change current contact to -->  IESC Minerals Services Branch Chief | Bethany Hagen-Templin | ONRR (Bethany.HagenTemplin@onrr.gov)

REMOVE -->  IESC Production Accountability Specialist | Scott Doebbler | BLM

NEW, need to add --> IESC Land Law Examiner | Mayom Achuk | BLM (machuk@blm.gov)

REMOVE  --> IESC Land Law Examiner | Christopher Lee | BLM

NEW, need to add -->  IESC Realty Specialist | LaWanda Gibson | BIA (Lawanda.Gibson@bia.gov)

**Comment by lpgoldstein** [comment]
@ONRRamandagarrison this is ready for your review: http://2017onrr/IndianServices/iescstaff.htm

**Comment by ONRRamandagarrison** [comment]
[cid:image001.jpg@01D6B2A6.65152C50]

Can you put Albert Bond above Michelle Deason?

Also, can you add back in under IESC Director:

IESC Deputy Director    Carla Clark

So technically Carla is listed twice.


The rest of the page looks great! Thank you!

Amanda Garrison

Supervisory Minerals Revenue Specialist
Indian Energy Service Center
P: (720) 595-2025

**Comment by lpgoldstein** [comment]
@ONRRamandagarrison got it! http://2017onrr/IndianServices/iescstaff.htm

**Comment by ONRRamandagarrison** [comment]
Perfect! Thanks!

Amanda Garrison

Supervisory Minerals Revenue Specialist
Indian Energy Service Center
P: (720) 595-2025

**Comment by lpgoldstein** [comment]
@ONRRamandagarrison the onrr.gov production server has been down since yesterday and we are unable to make any updates to the live site. I'll make the changes as soon as we are live again.

**Comment by lpgoldstein** [comment]
@ONRRamandagarrison It's live https://www.onrr.gov/IndianServices/iescstaff.htm
