### ISSUE TITLE
Update content on IESC "main" page

### ISSUE THREAD

**Issue by ONRRamandagarrison** [ONRR/onrr.gov-site#340]
At think link:  https://www.onrr.gov/IndianServices/indian-energy-service-center.htm

Replace current text on page with the text below: All current formatting and photos will remain the same 

The Indian Energy Service Center (IESC) is a multi-agency collaboration between the Bureau of Indian Affairs (BIA), Bureau of Land Management (BLM), Office of Natural Resources Revenue (ONRR), and Bureau of Trust Fund Administration (BTFA) whose mission is to expedite Indian oil and gas activities, standardize processes, and provide for multi-disciplinary engagement in support of gaining efficiencies in the management of all types of Indian Energy, Renewable Energy, and Mineral development and activities to better serve Indian beneficiaries and Tribes. 

The IESC was created through a recommendation from an Indian Energy and Minerals Steering Committee (IEMSC) subcommittee to address the growing backlog at Agencies due to the increased activity in various parts of Indian country. Approved by the Assistant Secretary of Indian Affairs, the IESC received federal funding in FY2016 and has in-house staff from BIA, BLM, ONRR and BTFA .  

Purpose 

Support and streamline Interior's Indian energy development business process employed in the dozens of Interior field offices across the country that manages all types of Indian energy, renewable energy, and mineral leasing and development activities. These field offices operate under varying interpretations of applicable requirements, input and output complicated program information to numerous other processing offices, and are regularly overwhelmed by surging workloads. The Federal offices included in the IESC structure, BIA, BLM, ONRR, and BTFA , are those that directly manage and process all types of the Federal government’s Indian energy, renewable energy, and mineral leasing activities and within which the aforementioned Interior field offices exist. 

Mission 

Streamline business processes to efficiently develop the Indian mineral estate while protecting trust assets by removing barriers to all types of energy, renewable energy, and mineral development on Indian lands. 

Principles 

"Quality of Life, Stewardship, Accountability, and Beneficiary Focus" 

Each of the four principles was a collaboration of principles from each of the four agencies represented at the IESC. 

Quality of Life 

BIA’s mission is to enhance, promote economic opportunity, and to carry out the responsibility to protect and improve the trust assets.  

Stewardship 

BLM is tasked with being the steward of all public and trust lands.  

Accountability 

ONRR collects, accounts for, and verifies natural resource and energy revenues due.  

Beneficiary Focus  

BTFA focuses on protecting, preserving, providing, and engaging for beneficiaries and all Indian trust assets.  

  

Main Functions 

IESC offers a cost effective solution to providing a centralized and multifunctional processing capacity necessary to ensure Interior’s successful fulfillment of its Indian energy and mineral development trust responsibilities in the face of fluctuating workloads.  

It also promulgates across Interior’s Indian energy organizations a common business process that works to standardize and streamline all types of Indian energy, renewable energy, and mineral development functions in the best interest for Tribes and Indian beneficiaries.  

Efficiencies are gained by applying significant streamlining improvements offered in the recently updated Onshore Federal and Indian Energy and Mineral Lease Management Standard Operating Procedures (SOP), a business process that greatly simplifies processing activities while assuring that Interior responsibilities in Titles 25, 30, and 43 of the Code of Federal Regulations are fulfilled. 

The IESC provides the critical role of facilitating the SOP training(s) to support a streamlined and standardized process for all DOI employees in order to meet our Indian trust responsibility.  Each of these offices (BIA, BLM, ONRR and BTFA ) serves an active and extensive roles in the Indian energy, renewable energy and mineral development processes.  The IESC conducts SOP classroom is currently working on Computer Based Training (CBT) modules and, SOP Training for Tribes, Trust Beneficiaries and Operators.  

Pursuant to Interior Secretarial Order number 3377, the IESC created new guidance for Tribal Energy Resource Agreement (TERA) and Tribal Energy Development Organization (TEDO) processing to be included in the Onshore Energy and Mineral Lease Management Interagency Standard Operating Procedures (SOP).  This attachment will discuss the policies and procedures of TERA/TEDO applications as well as roles and responsibilities of DOI offices. The IESC will administer Title I Self-Determination contracts for oil and gas activities on trust lands with the BIA, BLM and ONRR.  

  

Organizational Alignment 

The Service Center Director reports directly to the BIA Deputy Bureau Director – Trust Services. Each agency has an onsite branch chief that oversees the duties of the employees from their agency. The four branches of the IESC are: Real Estate Services (BIA), Engineering Services (BLM), Mineral Services (ONRR) and Beneficiary Services (BTFA ).

**Comment by Maroyafaied** [comment]
@ONRRamandagarrison please review the changes on our dev site. Thanks

http://2017onrr/IndianServices/indian-energy-service-center.htm

**Comment by ONRRamandagarrison** [comment]
It’s perfect! Thank you!

Amanda Garrison

Supervisory Minerals Revenue Specialist
Indian Energy Service Center
P: (720) 595-2025

**Comment by Maroyafaied** [comment]
@ONRRamandagarrison it's live now. Thanks https://www.onrr.gov/IndianServices/indian-energy-service-center.htm
