### ISSUE TITLE
Indian Index Zone Pricing update

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#346]
Will you please update the Indian Gas Index Zone prices for November.  The prices have been added to the "Data for ONRR" spreadsheet in the OneDrive.

Thanks,
Cory Forgrave
@sudarr

**Comment by forgravec** [comment]
Also, not sure if I still need to state this, but please provide a link before it goes live so that I can verify once more the prices are correct...thanks, Cory

**Comment by Maroyafaied** [comment]
@forgravec yes we always provide a link before it goes live, here is the link to review this month's update, if everything looks correct then we'll publish it live. Thanks 

http://2017onrr/Valuation/allzones.htm

**Comment by forgravec** [comment]
Thanks Maroya, the prices look good.

Kind regards,
Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
cory.forgrave@onrr.gov

________________________________

**Comment by Maroyafaied** [comment]
@forgravec this is live now. Thanks https://www.onrr.gov/Valuation/allzones.htm
