### ISSUE TITLE
Document and implement an internal content review process 

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/onrr.gov-site#351]
Document and implement a content review process so we can be consistent with our content owners.

**Comment by Maroyafaied** [comment]
We will wait on this till we figure out the CMS.

**Comment by mcharg** [comment]
We probably should get this worked out next sprint, so we have a plan for how we're going to do reviews as we add content to the CMS.

**Comment by daniel-coleman-1** [comment]
https://iencsj.axshare.com

**Comment by Maroyafaied** [comment]
For this issue, I'd like a simple checklist to include the following. Let me know your thoughts @mcharg @lpgoldstein @daniel-coleman-1 

For person adding content:
- Add content based on the wireframes
- Ensure correct files are added and correct links
- Ask another person on the team to check added content with link to the dev site
-Update CMS tracking sheet with status or any blockers
- Add your name to CMS tracking sheet to "Content Added by" column


For person reviewing new added content:
- Make sure content matches wireframe
- Check links are working, correct files attached, check spelling, title case, etc
- Comment on issue with any correction needed or if no corrections found
- Update content tracking spreadsheet with your name in "Reviewed by" column

**Comment by lpgoldstein** [comment]
@Maroyafaied For the first iteration of content adding do we want to make sure that someone on our team reviews everything as well?

**Comment by Maroyafaied** [comment]
@lpgoldstein Yes, the section that says " for person reviewing new added content" is meant for someone on our team to do the review.

**Comment by mcharg** [comment]
@Maroyafaied I think we may also need something about adding collections, since a lot of the content and documents will be added using collections.

Otherwise, looks good.

**Comment by mcharg** [comment]
We should also attach issues for any blockers to the GitHub issue as depedencies.

**Comment by Maroyafaied** [comment]
@mcharg Thanks for the feedback, I've edited my draft checklist. Please revise as you see fit. 

For person adding content:
- Add content based on the wireframes
- Add appropriate collection for the page
- Ensure correct files are added and correct links
- Ask another person on the team to check added content with link to the dev site
- Update CMS tracking sheet with status or any blockers
- If blockers are identified then attach appropriate GitHub issues as dependencies.
- Add your name to CMS tracking sheet to "Content Added by" column

For person reviewing new added content:
- Make sure content matches wireframe
- Check links are working, correct files attached, check spelling, title case, etc
- Comment on issue with any correction needed or if no corrections found
- Update content tracking spreadsheet with your name in "Reviewed by" column

**Comment by mcharg** [comment]
@Maroyafaied Should we add something about adding comments to wireframe and/or sitemap if we find things that need to be changed on that end?

**Comment by Maroyafaied** [comment]
@mcharg sure, I added it to the list above.

**Comment by mcharg** [comment]
@Maroyafaied Looks good.

**Comment by Maroyafaied** [comment]
@cthomasONRR @lpgoldstein @mcharg please review the updated instructions based on the content tracking sheet. Once you are done with your review , I can use it for issue #1246 since I just added that page and @cthomasONRR can test it out again when she adds pages. https://doimspp.sharepoint.com/sites/NRRD/_layouts/15/doc.aspx?sourcedoc={e1a9e465-d8df-40bc-a745-1c5c891ca07a}&action=edit

**Comment by mcharg** [comment]
@Maroyafaied I reviewed and added some comments and tracked edits.

**Comment by cthomasONRR** [comment]
@Maroyafaied I made some edits mainly just for readability.

**Comment by Maroyafaied** [comment]
@mcharg @cthomasONRR I've implemented your comments

**Comment by mcharg** [comment]
@Maroyafaied I want to move the GitHub issue and blockers columns to the left after working with the spreadsheet yesterday, so I'll update the column letters accordingly.

**Comment by Maroyafaied** [comment]
@mcharg sounds good, can you let @lpgoldstein know when it's updated so she can add this list to the wiki. Thanks

**Comment by mcharg** [comment]
@lpgoldstein The column letters are updated.

**Comment by Maroyafaied** [comment]
@mcharg I went ahead and added this to the wiki since @lpgoldstein is out. Can you review? https://github.com/ONRR/onrr.gov-site/wiki/Adding-content-internal-checklist

**Comment by mcharg** [comment]
@Maroyafaied Looks good.
