### ISSUE TITLE
Ocotber 2020 IBMP Prices

### ISSUE THREAD

**Issue by damionschulte** [ONRR/onrr.gov-site#358]
All I have updated the onrr.gov sheet on OneDrive with the October 2020 IBMP prices and they are ready to be published.  Thank you

@sudarr

**Comment by lpgoldstein** [comment]
@damionschulte this is ready for your review: http://2017onrr/Valuation/IndianOilIBMP.htm

**Comment by damionschulte** [comment]
Looks great!  Thank you. Please push to live

**Comment by lpgoldstein** [comment]
@damionschulte This is live https://www.onrr.gov/Valuation/IndianOilIBMP.htm
