### ISSUE TITLE
Update file on ONRR.gov

### ISSUE THREAD

**Issue by KerriGallant** [ONRR/onrr.gov-site#363]

**Comment by KerriGallant** [comment]
Please update https://www.onrr.gov/about/contact.htm, ONRR Contacts by Company Assignment, Onshore Production Reporting.pdf file with the new contact list that was uploaded to:

https://www.onrr.gov/ReportPay/production-reporting.htm, Reporter Tools Section, Onshore.Production.Contacts.101620.xlsx

Better said: take the old pdf contact list out of the contacts page, and replace with the new spreadsheet found in tools on the Production page. 

Thanks!

**Comment by lpgoldstein** [comment]
@KerriGallant Thank you! This is ready for your review. http://2017onrr/About/contact.htm

**Comment by KerriGallant** [comment]
That page looks great!  The correct file is loaded and I appreciate your work.

HOWEVER, LOL

As I went to review, I found a retired person listed:

[cid:cb6420a2-4012-4738-8d73-7f6e637209a2]

I'm going to find out who should be listed here and get back with you.  Should I do a new github ticket?



Kerri Gallant | Minerals Revenue Specialist | (303) 231-3154

Reference & Reporting Management | Office of Natural Resources Revenue | US Dept. of the Interior


NOTE REGARDING ONRR FORM 2014 OVERRIDES:

ALL reporting to ONRR is subject to further review and audit.


________________________________

**Comment by lpgoldstein** [comment]
@KerriGallant of course! Yes. I'll go ahead and publish this one and then we can update later.

**Comment by KerriGallant** [comment]
Thank you!


Kerri Gallant | Minerals Revenue Specialist | (303) 231-3154

Reference & Reporting Management | Office of Natural Resources Revenue | US Dept. of the Interior


NOTE REGARDING ONRR FORM 2014 OVERRIDES:

ALL reporting to ONRR is subject to further review and audit.


________________________________
