### ISSUE TITLE
Create process diagram for onrr.gov

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#366]
That explains how everything works.

**Comment by mcharg** [comment]
Useful files for this are in this folder: https://teams.microsoft.com/_#/files/General?threadId=19%3A34f9f9ee6b0441dbacab56bfd552f819%40thread.skype&ctx=channel&context=Process%2520Diagrams&rootfolder=%252Fsites%252FNRRD%252FShared%2520Documents%252FGeneral%252FONRR.gov%252FDiscovery%252FProcess%2520Diagrams

It might also be helpful to look at the lease level journey map: https://teams.microsoft.com/l/file/454F91DE-D58A-4EF4-BA69-FB8A9057099E?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=vsd&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FDesign%2FLease%20Level%20Data%2FBackground%20Info%2FLeaseLevelJourneyMap.vsd&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by mcharg** [comment]
I forgot I reworked the end to end journey map as part of the SPOT project.  Here's the process that came out of that.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/da09e88e-4b9f-470f-8bfb-2ef79d92a44b)

**Comment by mcharg** [comment]
@jnwang01 This is the page the diagram will go on.
https://qmcq5k.axshare.com/#id=1t0m2d&p=how_leasing_works

**Comment by mcharg** [comment]
@jnwang01 Where are you at with this?

**Comment by jnwang01** [comment]
I sent a draft to Maroya, but I forgot to put it here. https://cz2rch.axshare.com

**Comment by Maroyafaied** [comment]
@jnwang01 I also made some comments, you can use a lot of content from this section in the NRRD that Chris and I wrote a while ago.  It explains what ONRR does pretty well. Also, lets consolidate the steps into 3 (Collection, Validation, Transparency).

**Comment by jnwang01** [comment]
@Maroyafaied Thanks ! I'll get on that. The doc you're referring to, is that the one that you send me during our meeting?

**Comment by Maroyafaied** [comment]
@jnwang01 sorry forget the link , it's the data collection and validation section in the download page. https://revenuedata.doi.gov/downloads/#Data-Collection-and-Validation

**Comment by jnwang01** [comment]
@Maroyafaied thank you!

**Comment by jnwang01** [comment]
https://cz2rch.axshare.com here is the updated diagram

**Comment by mcharg** [comment]
@jnwang01 @Maroyafaied I resolved all the comments that have been addressed and left the ones that are still open and added some new ones.

**Comment by jnwang01** [comment]
https://cz2rch.axshare.com here is the new axure link with the edits

**Comment by Maroyafaied** [comment]
@jnwang01 It's looking good, I put a couple of comments and resolved most of the comments.

**Comment by mcharg** [comment]
Created #679 for next step.
