### ISSUE TITLE
Remove 2017 from footer and the last updated text

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#369]
This shows up when you click overview for any of the pages

https://www.onrr.gov/compliance/index.htm

![image](https://user-images.githubusercontent.com/40175688/99819757-19a8e380-2b0d-11eb-9fc4-de415c712eac.png)

**Comment by jennmalcolm** [comment]
This is ready for your review in dev @Maroyafaied.

**Comment by Maroyafaied** [comment]
@jennmalcolm It looks good but seems like these icons went away? 
![image](https://user-images.githubusercontent.com/40175688/100246640-9fa2a100-2ef6-11eb-9606-b2e5f860a3b4.png)

**Comment by jennmalcolm** [comment]
I didn't do anything in that area, so I'm not sure why you're not seeing the icons. I see them in dev. Maybe clear your cache and refresh @Maroyafaied or tell me what page you're looking at if you still don't see them.

![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/aee686fa-1fc0-44eb-91b5-2fb8a9cf524f)

**Comment by jennmalcolm** [comment]
@Maroyafaied I pushed this page to production, can you check it to see if you're missing the icons. 

https://www.onrr.gov/compliance/index.htm

**Comment by Maroyafaied** [comment]
@jennmalcolm I see the icons in that page. I assume this page hasn't been pushed to production yet? https://www.onrr.gov/reportpay/index.htm

**Comment by jennmalcolm** [comment]
Correct @Maroyafaied I wanted to test with one page before pushing the hundreds of other pages. I'll proceed with the rest now.

**Comment by jennmalcolm** [comment]
All pages should be updated in production now if you want to take another look @Maroyafaied.

**Comment by Maroyafaied** [comment]
@jennmalcolm looks good! Thank you
