### ISSUE TITLE
Request to Update ONRR's Rules and Regulations Page

### ISSUE THREAD

**Issue by aklong09** [ONRR/onrr.gov-site#371]
Good morning,

On the page located at https://www.onrr.gov/Laws_R_D/FRNotices/AA27.htm please **remove** the following public comment period information:

"To submit comments: *https://www.regulations.gov/comment?D=ONRR-2020-0001-0001

*Hyperlink will be removed once the public comment period closes."

Because this public comment period closes tonight at 11:59PM (11/30), we are requesting that this information be **removed first thing tomorrow morning (Tuesday, December 1)**, if possible. 

Please let me know if you have any questions.

Thank you,
Alexis

**Comment by jennmalcolm** [comment]
@aklong09 this is ready for your review on our development site. If you approve, I will publish first thing tomorrow morning. http://2017onrr/Laws_R_D/FRNotices/AA27.htm

**Comment by aklong09** [comment]
Hi @jennmalcolm -- yes, this looks good. Thanks so much!

**Comment by jennmalcolm** [comment]
The changes are live.
