### ISSUE TITLE
Offshore Production Reporting References

### ISSUE THREAD

**Issue by ONRR-31577** [ONRR/onrr.gov-site#372]
On the ONRR.gov page under Production, Reporting References, please replace the five Gulf files with the attached. and update the "as of date" to today.

Thank you,
[Gulf Buy Back.xlsx](https://github.com/ONRR/onrr.gov-site/files/5616516/Gulf.Buy.Back.xlsx)
[Gulf Flash Gas.xlsx](https://github.com/ONRR/onrr.gov-site/files/5616517/Gulf.Flash.Gas.xlsx)
[Gulf Gas Plants.xlsx](https://github.com/ONRR/onrr.gov-site/files/5616518/Gulf.Gas.Plants.xlsx)
[Gulf Metering Systems.xlsx](https://github.com/ONRR/onrr.gov-site/files/5616519/Gulf.Metering.Systems.xlsx)
[Gulf Sales Tanks.xlsx](https://github.com/ONRR/onrr.gov-site/files/5616520/Gulf.Sales.Tanks.xlsx)

**Comment by jennmalcolm** [comment]
@onrr-31577, please review on dev, and let us know if you approve to publish live on onrr.gov.

http://2017onrr/reportpay/references.htm

Thanks

**Comment by ONRR-31577** [comment]
Everything looks good.
Thank you,



Johnny Erle

Office of Natural Resources Revenue (ONRR)
RRM Team 1A
Minerals Revenue Specialist-GVS
john.erle@onrr.gov<mailto:john.erle@onrr.gov>
303-231-3577
800-525-7922  ext.13577
fax: 303-231-3566
________________________________

**Comment by jennmalcolm** [comment]
changes are live
