### ISSUE TITLE
Valuation - Federal Gas Index Option - Verbiage change

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#373]
We have been asked to change the verbiage on Federal Gas Index Option page.  Near the bottom in the table, there are references to "processing allowance" and the request is to have "allowance" changed to "adjustment."  There are three places where the change needs to be made...two in the table, and one in the sentence just above the table.
[Val - Fed Ind Option - verbiage.docx](https://github.com/ONRR/onrr.gov-site/files/5616948/Val.-.Fed.Ind.Option.-.verbiage.docx)

https://www.onrr.gov/Valuation/federal-gas-index-option.htm

Thanks,
Cory Forgrave

@sudarr

**Comment by jennmalcolm** [comment]
This is ready for your review in dev @forgravec.

http://2017onrr/Valuation/federal-gas-index-option.htm

**Comment by forgravec** [comment]
Looks good.

Thanks,
Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
cory.forgrave@onrr.gov

________________________________

**Comment by forgravec** [comment]
Jennifer,

If it is not too late, will you hold off on making it "live"...they are discussing on whether to make another change as well.

If not, that is fine, the changes you made are good, they are just debating on whether to change "T&F Fee".

Thanks,
Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
cory.forgrave@onrr.gov

________________________________

**Comment by jennmalcolm** [comment]
Sorry @forgravec, I just pushed it to production, and it will be live in a couple of minutes. I can certainly make whatever other changes you need. Just let me know. Thanks.
