### ISSUE TITLE
Valuation - Federal Index Option - Verbiage change 2

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#374]
An additional change to the Federal Index Option page has been requested.  At the bottom where the table is, they would like the "T&F FEE" changed to "T&F Adjustment." There will be two places to make this change, in the table itself, and the sentence above the table. 
In addition, since we are getting rid of "fee," the column heading that now states "Adjustment and Fee" should be changed to "Adjustments."

I have reattached an image to show what I am referring to.

Thanks,
Cory Forgrave
@sudarr
[Val - Fed Ind Option - verbiage.docx](https://github.com/ONRR/onrr.gov-site/files/5617452/Val.-.Fed.Ind.Option.-.verbiage.docx)

**Comment by jennmalcolm** [comment]
Ok, ready for your review @forgravec 

http://2017onrr/Valuation/federal-gas-index-option.htm

**Comment by forgravec** [comment]
In the table it states "Processing Adjustment" and "T&F Adjustments"...the difference being the second is plural.  I am not sure the correct grammatical spelling...should "T&F Adjustments" being singular to match "Processing Adjustment" or should "Processing Adjustment" be plural.

I think the plural spelling in the line above the table makes sense, but I am not sure what would be correct for the table.

Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
cory.forgrave@onrr.gov

________________________________

**Comment by forgravec** [comment]
Jennifer,
I asked Robert and he thinks we should make the "Processing Adjustment," in the table, plural to match "T&F Adjustments".

Thanks,
Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
cory.forgrave@onrr.gov

________________________________

**Comment by jennmalcolm** [comment]
Ok, I've made that and the total line plural. Let me know if it looks good to publish.

http://2017onrr/Valuation/federal-gas-index-option.htm

**Comment by forgravec** [comment]
Looks good...thanks for making the changes so quickly.

Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
cory.forgrave@onrr.gov

________________________________

**Comment by jennmalcolm** [comment]
The changes are live now.
