### ISSUE TITLE
NYMEX November 2020 price upload 

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#377]
Attached is the NYMEX spreadsheet for the November upload.  It has been a while since I requested this price upload, so I am providing the prices in the message not knowing if you normally grab them from the spreadsheet or not.
November 2020 NYMEX: $41.35
NYMEX Roll: ($0.39)
[NYMEX112020_508Compliant.xlsx](https://github.com/ONRR/onrr.gov-site/files/5639418/NYMEX112020_508Compliant.xlsx)

@sudarr
Thanks, Cory Forgrave

**Comment by lpgoldstein** [comment]
@forgravec This is ready for your review http://2017onrr/Valuation/NYMEX.htm

**Comment by forgravec** [comment]
Looks good.

Thanks!
Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
cory.forgrave@onrr.gov

________________________________

**Comment by lpgoldstein** [comment]
@forgravec This is live https://www.onrr.gov/Valuation/NYMEX.htm
