### ISSUE TITLE
Add 2020 disbursements press releases to onrr.gov

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/onrr.gov-site#378]

**Comment by Maroyafaied** [comment]
[FY2020 Disbursements Louisiana Press Release.pdf](https://github.com/ONRR/onrr.gov-site/files/5653465/FY2020.Disbursements.Louisiana.Press.Release.pdf)
[FY2020 Disbursements National Press Release.pdf](https://github.com/ONRR/onrr.gov-site/files/5653466/FY2020.Disbursements.National.Press.Release.pdf)
[FY2020 Disbursements New Mexico Press Release.pdf](https://github.com/ONRR/onrr.gov-site/files/5653467/FY2020.Disbursements.New.Mexico.Press.Release.pdf)

**Comment by mentastc** [comment]
It looks like the banner on the homepage never updated and is still displaying the GOMESA disbursement from the spring. Please make this banner display the FY2020 Disbursements.

Also, it looks like only the National press release was posted, could you please make sure the 5 state press releases are also posted. If we could make them appear with the Dec 7th date (like the national release) that would also be great.

**Comment by lpgoldstein** [comment]
@mentastc what banner documents do you want to show? Just national press release and link to nrrd? We don't have one document with all of the states press releases together. Please combine and post here if you want that to show.

**Comment by lpgoldstein** [comment]
@mentastc Do you want to review: http://2017onrr/index.htm
