### ISSUE TITLE
December Indian Index Zone prices for ONRR.gov

### ISSUE THREAD

**Issue by jpenvose773** [ONRR/onrr.gov-site#379]
Please update the Indian Index Zone prices for December 2020 on ONRR.gov. The data has been updated with the newest prices in the Data for ONRR.gov Excel spreadsheet.

@sudarr

**Comment by lpgoldstein** [comment]
@jpenvose773 Is this the right link? I only see prices through November. https://doimspp-my.sharepoint.com/:x:/r/personal/sudarr_mms_gov/_layouts/15/guestaccess.aspx?share=EfYTCWFEzCJChSH62epf6w4BFJf_yZ0WACeOqmuAGRh_IQ

**Comment by jpenvose773** [comment]
Hi Lindsay,

I’m so sorry, I forgot to update this file. I thought that we weren’t updating it for at least one of the two prices MSA is responsible for (though I never did understand why that changed) but it looks like that policy applies to NYMEX, not Indian Index Zone. Let me enter the prices right now and I’ll email again when I’m done. My apologies for that!

Jessica

**Comment by jpenvose773** [comment]
Okay, I’ve entered the index zone prices in the spreadsheet you linked. Again, I’m so sorry about that!

From: Penvose, Jessica M
Sent: Monday, December 7, 2020 11:06 AM
To: ONRR/onrr.gov-site <reply@reply.github.com>; ONRR/onrr.gov-site <onrr.gov-site@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [EXTERNAL] Re: [ONRR/onrr.gov-site] December Indian Index Zone prices for ONRR.gov (#379)

Hi Lindsay,

I’m so sorry, I forgot to update this file. I thought that we weren’t updating it for at least one of the two prices MSA is responsible for (though I never did understand why that changed) but it looks like that policy applies to NYMEX, not Indian Index Zone. Let me enter the prices right now and I’ll email again when I’m done. My apologies for that!

Jessica

**Comment by lpgoldstein** [comment]
@jpenvose773 This is ready for your review http://2017onrr/Valuation/allzones.htm

**Comment by jpenvose773** [comment]
The webpage looks good. Thanks for adding this information!

**Comment by lpgoldstein** [comment]
@jpenvose773 It's live!
