### ISSUE TITLE
Press releases not showing up in IE and Safari

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#382]
Safari ![image](https://user-images.githubusercontent.com/30806839/101658561-22594f00-3a13-11eb-8e80-6cb6e9596433.png)

IE 
![image](https://user-images.githubusercontent.com/30806839/101658681-3dc45a00-3a13-11eb-9d3c-3b1341e80fd5.png)

Seems to be working fine in Chrome and Firefox. I can't check Edge

**Comment by jlouis-onrr** [comment]
fixed a malformed html character, seems to be now showing up in IE and Safari.  @jennmalcolm and @lpgoldstein can you check it out?

**Comment by jennmalcolm** [comment]
Yes, it's looking good in dev now. Thank you @jlouis-onrr.

**Comment by lpgoldstein** [comment]
@jlouis-onrr Looks good to me too! Thank you! Would you please push to production?

**Comment by jennmalcolm** [comment]
Fixed on live site now.
