### ISSUE TITLE
Web page Update (Indian Fund Code)

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#384]
Please update the following webpage http://onrr.gov/ReportPay/payments.htm with the attached files:

Indian Leases Cross-walked to Distributee Codes
Downloadable Excel Version Indian Leases Cross-walked to Distributee Codes
Also change updated to 12/09/2020 for both files.

In addition to the above please update to 12/09/2020 on URL http://www.onrr.gov/ReportPay/royalty-reporting.htm for the same files linked to this URL.
[FCIL.pdf](https://github.com/ONRR/onrr.gov-site/files/5668347/FCIL.pdf)
[FCIL.xlsx](https://github.com/ONRR/onrr.gov-site/files/5668356/FCIL.xlsx)

Thank you

**Comment by jennmalcolm** [comment]
Hi @merrellc there are a few accessibility  errors in the pdf. Here is the report. Thanks.
[FCIL.pdf.accreport.pdf](https://github.com/ONRR/onrr.gov-site/files/5668725/FCIL.pdf.accreport.pdf)

**Comment by jennmalcolm** [comment]
@merrellc I went ahead and updated the Excel file on our dev site, and it is ready for your review here:

http://2017onrr/ReportPay/royalty-reporting.htm

Please let me know if it's ready to publish. Once we receive a pdf without the accessibility errors, I'll get that updated too. Thanks.

**Comment by merrellc** [comment]
Ready to publish.


Kindly,
​Candace Merrell
Office of Natural Resources Revenue
Reference and Reporting Management
Candace.Merrell@onrr.gov
303-231-3517

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________

**Comment by jennmalcolm** [comment]
The Excel file is live on the site. I will keep this issue open for the pdf.

**Comment by merrellc** [comment]
Attached is the updated PDF.
[FCIL.pdf](https://github.com/ONRR/onrr.gov-site/files/5675139/FCIL.pdf)

**Comment by jennmalcolm** [comment]
Thank you @merrellc the pdf looks good, and it's ready for your review on the dev site now. 

http://2017onrr/ReportPay/royalty-reporting.htm

**Comment by merrellc** [comment]
Ready to publish.


Kindly,
​Candace Merrell
Office of Natural Resources Revenue
Reference and Reporting Management
Candace.Merrell@onrr.gov
303-231-3517

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________

**Comment by jennmalcolm** [comment]
The pdf is live now too.
