### ISSUE TITLE
Plan user interviews for people who post things to onrr.gov

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#388]
To learn what their tasks are and how they would use a CMS.

**Comment by mcharg** [comment]
@Maroyafaied @jennmalcolm Do you want to review?
https://teams.microsoft.com/l/file/4BFE654A-0CCF-40DF-AFA3-4F0889985C33?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FUser%20Research%2FStudies%2F07_ContentProcess%2FContentProcess_InterviewGuide.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by Maroyafaied** [comment]
@mcharg it looks good, the only thing I might add or ask about is if we had a CMS that gave them access to update their own document or content on the page if they would utilize that or willing to be trained.

**Comment by jennmalcolm** [comment]
I think it looks good. My only suggestion is to incorporate a question about timeframes for updating the content on onrr.gov (e.g. When you request updates, are any of them urgent, and what kind of turnaround times do you expect?) That might help us in putting together our content change review/approval process.
