### ISSUE TITLE
Public laws page has incorrect left nav

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#389]
It has the Indian Services left nav, but it lives in the About section.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/888fbc86-fa72-4220-b24e-e2aaf1a6258b)

**Comment by mcharg** [comment]
@jennmalcolm I got the correct left nav on the page, but it made the table get out of whack.  Do you know how to fix it?
http://2017onrr/Laws_R_D/PubLaws/index.htm

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/92844b7e-9f92-4f9b-8228-faa8510e7881)

**Comment by jennmalcolm** [comment]
Yes @mcharg, it had code in the div tag that set up the column with to move it over 2, but since the new nav is longer, that isn't necessary.

**Comment by mcharg** [comment]
@jennmalcolm Thank you!

**Comment by mcharg** [comment]
@jennmalcolm I'm getting a 404 error when I click on any of the items in the new left nav.  Any idea why?

**Comment by jennmalcolm** [comment]
@mcharg probably the links are relative and this menu is only used in pages that are one level up in the file structure. Let me look.

**Comment by jennmalcolm** [comment]
Yes, that's the issue @mcharg. These are relative links in the about section, but this page is actually in the Laws_R_D folder. If that's the right nav for this page--aside from looking at our information architecture in the re-design--we could fix this by changing the links in the library nav to be the full URLs, but you'll need to use the live onrr.gov site, not the dev site. Let me know if you want help.

**Comment by mcharg** [comment]
I might be able to copy what the FRN page does, since that page is also a sub of Rules & Regs.  I'll look at it tomorrow.

**Comment by jennmalcolm** [comment]
It looks like someone manually added an extra ../ to the links in that navigation menu on the FRN page. This will work on the public laws page too. I'm just not sure if it will update the library item on the pages that have been manually changed, but we could test it.

**Comment by mcharg** [comment]
Change is live.
https://www.onrr.gov/Laws_R_D/PubLaws/index.htm
