### ISSUE TITLE
Pay.gov training video link doesn't go to a video

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#390]
It just goes to the Payments page, so we should remove it.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/6d8cffef-3ecb-4916-bd11-22020e6a17f0)

**Comment by lpgoldstein** [comment]
@mcharg This is ready for your review: http://2017onrr/ReportPay/training/index.htm

**Comment by mcharg** [comment]
@lpgoldstein Looks good.
