### ISSUE TITLE
Remove case of the missing data video

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#391]
It's at the bottom of the training index page.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/34a352b9-db83-4c12-8795-8eeee1c9fc02)

**Comment by lpgoldstein** [comment]
@mcharg ready for your review file://iondeniisp01/ONRR2017/reportpay/training/index.htm

**Comment by mcharg** [comment]
@lpgoldstein Looks good.
