### ISSUE TITLE
"2018" pdf is now 508 compliant

### ISSUE THREAD

**Issue by schartoa** [ONRR/onrr.gov-site#394]
[2018_508 Accessible.pdf](https://github.com/ONRR/onrr.gov-site/files/5712786/2018_508.Accessible.pdf)

Hi,
This "Top 100" downloaded document on ONRR.gov should now be 508 compliant.  It is located at https://www.onrr.gov/compliance/civil-penalties.htm and is the "2018" hyperlinked document on the right side of the page.  Please let me know if you have any questions.

Thank you,
Andrea Scharton

**Comment by lpgoldstein** [comment]
@schartoa Please review to make sure this looks okay. Thanks for updating your document! http://2017onrr/compliance/civil-penalties.htm

**Comment by schartoa** [comment]
The document looks great - thank you!

**Comment by lpgoldstein** [comment]
@schartoa It's live!
