### ISSUE TITLE
Please update the PDF links at https://www.onrr.gov/Laws_R_D/FRNotices/AA13.htm 

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#395]
Hello,

In an effort to make the following website more 508-Compliant, we need to switch out the PDF links with links that instead point to the Federal Register website.

On webpage: https://www.onrr.gov/Laws_R_D/FRNotices/AA13.htm,

Please replace the "Postponement of Effectiveness of the Final Rulemaking (82 FR 11823--February 27, 2017)" PDF link ([https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/11823.pdf](url)) with the following link: 
[https://www.federalregister.gov/documents/2017/02/27/2017-03861/postponement-of-effectiveness-of-the-consolidated-federal-oil-and-gas-and-federal-and-indian-coal](url)

Please replace the "Final Rulemaking: (81 FR 43338 --July 1, 2016)" PDF link ([https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/43338.pdf](url)) with the following link: [https://www.federalregister.gov/documents/2016/07/01/2016-15420/consolidated-federal-oil-and-gas-and-federal-and-indian-coal-valuation-reform](url)

Please replace the "Proposed Rule; Notice of Extension of Public Comment Period (80 FR 7994--February 13, 2015) " PDF link ([https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/7994.pdf](url)) with the following link: [https://www.federalregister.gov/documents/2015/02/13/2015-02997/consolidated-federal-oil-and-gas-and-federal-and-indian-coal-valuation-reform](url)

Please replace the "Proposed Rulemaking: (80 FR 608-- January 6, 2015)" PDF link ([https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/608.pdf](url)) with the following link: [https://www.federalregister.gov/documents/2015/01/06/2014-30033/consolidated-federal-oil-and-gas-and-federal-and-indian-coal-valuation-reform](url)

Please let me know if you have any questions.

Thanks,
Christine

**Comment by lpgoldstein** [comment]
@cthomasONRR This is ready for your review: http://2017onrr/Laws_R_D/FRNotices/AA13.htm

**Comment by cthomasONRR** [comment]
@lpgoldstein, this looks great. I approve for this to go live. Thanks for your help!

**Comment by lpgoldstein** [comment]
@cthomasONRR It's live https://www.onrr.gov/Laws_R_D/FRNotices/AA13.htm
