### ISSUE TITLE
Please update the Federal Register Notices web page as follows

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#398]
Hello,

Please update the Federal Register Notices web page located at:
[https://www.onrr.gov/Laws_R_D/FRNotices/index.htm](url)

Please add one new entry under the "FR Notices 2020" heading.

Above the July 14, 2020 entry (FR 42426), please add:

"FR 80147
Friday, December 11, 2020
**Denver, CO** ONRR provides two types of accounting and auditing relief for Federal onshore or Outer Continental Shelf lease production from marginal properties. For calendar year 2020, we provide in this notice about the affected States’ decisions to allow one or both types of relief."

Please add a hyperlink titled "View FR document" to the following website:
https://www.federalregister.gov/documents/2020/12/11/2020-27267/states-decisions-on-participating-in-accounting-and-auditing-relief-for-federal-oil-and-gas-marginal

Please let me know if you have any questions.

Thanks for your time,
Christine Thomas

**Comment by jennmalcolm** [comment]
@cthomasONRR, the changes are ready for your review on our development site. Please let me know if you approve to make live.

http://2017onrr/Laws_R_D/FRNotices/index.htm

Thanks

**Comment by cthomasONRR** [comment]
@jennmalcolm, looks good. I approve for these changes to go live. 

Thanks so much for your help!

Christine

**Comment by jennmalcolm** [comment]
The changes are live.

**Comment by cthomasONRR** [comment]
@jennmalcolm , does it take some time for the changes to be viewed? I don't see the update on the website yet.

Thanks,
Christine

**Comment by jennmalcolm** [comment]
@cthomasONRR, you probably need to clear your cache. Try looking in a different browser of clearing your cache. Contorl F5 usually works to clear you cache. Let me know if you still don't see it. Thanks.

**Comment by cthomasONRR** [comment]
@jennmalcolm  I see it now. Thanks!
