### ISSUE TITLE
Findings & Recommendations PowerPoint for the ONRR.gov discovery research study. 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#40]
We have consolidated the findings, we need to come up with recommendations and present findings during demo.

**Comment by Maroyafaied** [comment]
@lpgoldstein @mcharg here is what I have worked on for the power point https://doimspp-my.sharepoint.com/:p:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7BE611C91E-6083-46E7-9A39-7F897D670D25%7D&file=ONRR%20Discovery%20Findings.pptx&wdOrigin=OFFICECOM-WEB.START.MRU&action=edit&mobileredirect=true

**Comment by mcharg** [comment]
@Maroyafaied This is a great start. I put some comments in the presentation.

**Comment by Maroyafaied** [comment]
@mcharg @lpgoldstein  I worked through all the comments, please take another look and let me know if there are more changes. Thanks

**Comment by mcharg** [comment]
@Maroyafaied Looks good.  I added a couple of additional comments.

**Comment by Maroyafaied** [comment]
@mcharg thank you, I worked through them and I was confused on one comment. I replied to it on the power point. Thanks
