### ISSUE TITLE
Co-work with valuation & pricing group for wireframe feedback

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#402]

**Comment by Maroyafaied** [comment]
first draft an email then send and set up a meeting.

**Comment by mcharg** [comment]
Draft email template: https://teams.microsoft.com/l/file/C393EAFF-7B74-47D0-8EB6-BA90402AC0D1?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FDesign%2FDesignReviewInvitationEmail.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by Maroyafaied** [comment]
@mcharg the draft looks good, I added a comment about mentioning how much time the design review would take.
