### ISSUE TITLE
Create a list of onrr.gov contributors 

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/onrr.gov-site#404]
Add onrr.gov content creators to onrr.gov market map - new tab so we can reach out for next usability study

**Comment by lpgoldstein** [comment]
@mcharg @jennmalcolm Here is the list I've come up with based on github and emails - please add anyone that you think is missing https://doimspp.sharepoint.com/:x:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7BC989D844-57F7-4090-8C35-DE6F819F178E%7D&file=ONRR.gov%20market%20map.xlsx&action=default&mobileredirect=true.

**Comment by jennmalcolm** [comment]
I added two people who've contacted me for updates. Also, why do we have the program managers on there? I think only one of them has ever actually contacted us to make updates.

**Comment by mcharg** [comment]
I agree that we should focus on people who actually make updates unless there's some insight program managers could give us into how they assign updates across their team that might be useful for workflows in the CMS.

**Comment by lpgoldstein** [comment]
@jennmalcolm @mcharg I added the program managers because they are document owners - just to have as a reference.
