### ISSUE TITLE
Change default month on IBMP page

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#406]
It's weird to always default to the current month--which never has prices. We should default to the previous month. 
![image](https://user-images.githubusercontent.com/30806839/103039127-122a8f00-453e-11eb-889b-0c5b1cfd8910.png)

**Comment by jennmalcolm** [comment]
I have updated the JS to select the previous month in dev. Please review @Maroyafaied.

**Comment by Maroyafaied** [comment]
@jennmalcolm looks good
