### ISSUE TITLE
Archive links from phase 1

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#408]
We identified the following 4 links to be archived, please update the tracking sheet after they're been removed and archived. 

Row 12: https://www.onrr.gov/about/pdfdocs/ONRR_External_Org_Chart.pdf
Row 36: https://www.onrr.gov/ReportPay/training/files/Scheduled_Courses.xlsx
Row 65: https://www.onrr.gov/ReportPay/PDFDocs/ogphb3.pdf
Row 78: https://www.onrr.gov/ReportPay/training/files/2019_Oklahoma_Daily_Agenda.xlsx

**Comment by jennmalcolm** [comment]
Complete
