### ISSUE TITLE
Update Gulf spreadsheets

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#410]
All,
   On the ONRR.gov home page, under Reporting/Paying, Production Reporting, References, Offshore, please replace the five Gulf files with the attached and update the as of date to 12/31/20.

Thank you,
[Gulf-Metering-Systems (1).xlsx](https://github.com/ONRR/onrr.gov-site/files/5764636/Gulf-Metering-Systems.1.xlsx)
[Gulf-Gas-Plants (1).xlsx](https://github.com/ONRR/onrr.gov-site/files/5764637/Gulf-Gas-Plants.1.xlsx)
[Gulf-Buy-Back (1).xlsx](https://github.com/ONRR/onrr.gov-site/files/5764638/Gulf-Buy-Back.1.xlsx)
[Gulf-Sales-Tanks (1).xlsx](https://github.com/ONRR/onrr.gov-site/files/5764639/Gulf-Sales-Tanks.1.xlsx)
[Gulf-Flash-Gas (1).xlsx](https://github.com/ONRR/onrr.gov-site/files/5764640/Gulf-Flash-Gas.1.xlsx)

**Comment by jennmalcolm** [comment]
@ONRR-31577 these updates are ready for your review in dev:

http://2017onrr/ReportPay/references.htm

Thanks.

**Comment by ONRR-31577** [comment]
The updates are good to go.

Thank you,



Johnny Erle

Office of Natural Resources Revenue (ONRR)
RRM Team 1A
Minerals Revenue Specialist-GVS
john.erle@onrr.gov<mailto:john.erle@onrr.gov>
303-231-3577
800-525-7922  ext.13577
fax: 303-231-3566
________________________________

**Comment by jennmalcolm** [comment]
The changes are live.
