### ISSUE TITLE
Webpage Update Active Leases

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#416]
Please update the following webpage:
http://www.onrr.gov/ReportPay/CrossRef.htm with the attached file.

Active Leases - Sorted by State and Agency Lease Number (Updated 10/09/2020) please update to show updated 01/04/2021.

Thank You!
Jessica
[ALwState.xlsx](https://github.com/ONRR/onrr.gov-site/files/5766328/ALwState.xlsx)

**Comment by jennmalcolm** [comment]
@bowlenj this is ready for your review on our development site:

http://2017onrr/ReportPay/CrossRef.htm

Please let me know if you approve to publish. Thanks.

**Comment by bowlenj** [comment]
I found some errors in the file, can you please upload this new file instead of the previous file?
[ALwState.xlsx](https://github.com/ONRR/onrr.gov-site/files/5770820/ALwState.xlsx)

**Comment by bowlenj** [comment]
This looks great, thank you so much for helping me get that corrected!

Have a great day 😊

Thank You,
Jessica Bowlen
Office of Natural Resource Revenue
Reference and Reporting Management
303-231-3202
Jessica.Bowlen@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

**Comment by jennmalcolm** [comment]
Thanks, the changes are live now.
