### ISSUE TITLE
Take Documents off Website-Phase 1Heidi Badaracco 

### ISSUE THREAD

**Issue by madiganc1962** [ONRR/onrr.gov-site#418]
Please remove documents from website:
1.  https://www.onrr.gov/IndianServices/pdfdocs/Brochure.pdf
2.  https://www.onrr.gov/IndianServices/pdfdocs/FAQ.pdf

**Comment by lpgoldstein** [comment]
@madiganc1962 Thanks for creating an account and submitting your issue. This is ready for your review: http://2017onrr/IndianServices/index.htm
http://2017onrr/IndianServices/fimo.htm
http://2017onrr/IndianServices/tribal-assistance.htm
http://2017onrr/IndianServices/consultation.htm

**Comment by lpgoldstein** [comment]
Confirmed changes via email.
