### ISSUE TITLE
Incorrect URL

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#42]
We received this message in our email box. I logged into the ONRR website to change my password, but was unable to as I received the following message:

 

 

Therefore, I selected the “Contact Us” button at the bottom of the bottom of the screen and received the following message:

 
![image](https://user-images.githubusercontent.com/30806839/75688662-e2885e80-5c6d-11ea-9f0f-d5fc3b809e83.png)

 

Since I reached the above page from a direct link on your website, I wanted to let you know so that you can update the referring page, as requested.

 
![image](https://user-images.githubusercontent.com/30806839/75688719-fcc23c80-5c6d-11ea-8727-452e9771c8c1.png)

**Comment by Maroyafaied** [comment]
@jennmalcolm I just checked the contact us page and it's working for me , I don't get this server error. 
![image](https://user-images.githubusercontent.com/40175688/75793552-c3043b00-5d2c-11ea-9155-36370ff78d19.png)

**Comment by Maroyafaied** [comment]
This issue is regarding ONRR systems log in so I forward it to the help desk.

**Comment by Maroyafaied** [comment]
@jennmalcolm is this issue ok to close? I haven't heard back from the help desk but they might of contacted the person with the issue?

**Comment by jennmalcolm** [comment]
Yes, just email the requester back from the shared email box to let them know that we forwarded the email to the help desk since we don't manage that system, and provide them contact info for the help desk in case they  haven't heard back on it and want to follow up. Then you can close it.

**Comment by Maroyafaied** [comment]
Sending the requestor an email letting her know that the issue was forwarded to the help desk and provided her their email address.
