### ISSUE TITLE
Update 404 page

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#424]
We should probably update the email address to the onrrweb one and review the instructions to make sure they're still revelent.  Also, why the plant?
https://www.onrr.gov/404.htm

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/0ff6e919-eb77-403f-b497-f959c6771a86)

**Comment by mcharg** [comment]
Also, for the ones that say to change the url, can we setup redirects?

**Comment by mcharg** [comment]
We're getting about 300 sessions a month that land on this page.

**Comment by mcharg** [comment]
Correct email address: onrrweb@onrr.gov

**Comment by arcasarana** [comment]
Here's the redesign!

![redesign.png](https://images.zenhubusercontent.com/5f3e89546d2e5c87e3b06f99/02e05e50-445a-4125-ba64-6b658ee3dfdc)
