### ISSUE TITLE
ONRR.gov - Indian Gas Index Zone prices - January

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#429]
The Indian Gas Index Zone prices for January are ready for ONRR.gov.
I have placed the prices into the "Data for ONRR.gov" spreadsheet on the shared OneDrive site.

Thanks,
Cory Forgrave
@Sudarr

**Comment by jennmalcolm** [comment]
This is ready for your review in dev @forgravec. Thanks. 

http://2017onrr/Valuation/allzones.htm

**Comment by forgravec** [comment]
Jennifer,

The link to review took me to the 2020 page and I did not see 2021 in the dropdown.

Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
cory.forgrave@onrr.gov

________________________________

**Comment by jennmalcolm** [comment]
Please clear your cache (control F5) @forgravec

**Comment by forgravec** [comment]
Prices look good...thanks!

Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
cory.forgrave@onrr.gov

________________________________

**Comment by jennmalcolm** [comment]
The prices are live.
