### ISSUE TITLE
Wiki documentation for onrr.gov

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#43]
This issue will be to outline the documentation that we will have in our Wiki and begin  by documenting the pieces we have.

**Comment by Maroyafaied** [comment]
I added a documentation folder under the onrr.gov folder on the shared drive. I started the outline using what we have that is relevant on the NRRD outline. 
https://doimspp-my.sharepoint.com/personal/mchargs_mms_gov/_layouts/15/doc.aspx?sourcedoc={89149f21-bf50-4698-9157-d58dbd60ec9d}&action=edit
