### ISSUE TITLE
ONRR.gov - Valuation - NYMEX Oil Prices

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#433]
We would like to add the statement, "The NYMEX prices provided have been calculated excluding weekends and holidays."
If you would add it after the "...NYMEX Roll oil prices referenced in 30 CFR 1206.113." it would be greatly appreciated.

Thanks,
Cory Forgrave
@sudarr

**Comment by jennmalcolm** [comment]
@forgravec, I've made the change in dev, and its ready for your review. I also noted that For reporters' convenience is bolded. It seems to me that we should remove that bold, but please let me know if you all want that bolded for some reason. Thanks.

http://2017onrr/Valuation/NYMEX.htm

**Comment by forgravec** [comment]
Looks good. Thanks for adding it in.

Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
cory.forgrave@onrr.gov

________________________________

**Comment by jennmalcolm** [comment]
complete
