### ISSUE TITLE
Update Dec NYMEX values on onrr.gov

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#434]
Good morning,

Please update onrr.gov with the latest NYMEX prices--see attached. @sudarr

Thanks,
Sean
[NYMEX122020_508Compliant.xlsx](https://github.com/ONRR/onrr.gov-site/files/5783227/NYMEX122020_508Compliant.xlsx)

**Comment by jennmalcolm** [comment]
This is ready for your review in dev @boices.

http://2017onrr/Valuation/NYMEX.htm

**Comment by boices** [comment]
Looks perfect--thank you!

**Comment by jennmalcolm** [comment]
The prices are live.
