### ISSUE TITLE
Update Offshore Production Reporting Contacts 

### ISSUE THREAD

**Issue by KerriGallant** [ONRR/onrr.gov-site#437]
Please replace the file called, "Offshore Production Reporting," at this link: https://www.onrr.gov/about/contact.htm, **AND** this link: https://www.onrr.gov/ReportPay/production-reporting.htm, with the attached file.

[Offshore Operators revised 113020.xlsx](https://github.com/ONRR/onrr.gov-site/files/5784681/Offshore.Operators.revised.113020.xlsx)

**Comment by lpgoldstein** [comment]
@KerriGallant This is ready for your review: http://2017onrr/About/contact.htm http://2017onrr/ReportPay/production-reporting.htm

**Comment by KerriGallant** [comment]
Looks good, thank you!
