### ISSUE TITLE
Analyze onrr.gov study findings

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#438]

**Comment by mcharg** [comment]
@Maroyafaied @jennmalcolm @jlouis-onrr These are ready to review.
https://teams.microsoft.com/l/file/4220A805-86D2-4230-B519-032E1DC4259D?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FUser%20Research%2FStudies%2F07_ContentProcess%2FConsolidatedFindings.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by Maroyafaied** [comment]
@mcharg it looks good, I added a couple of comments.
