### ISSUE TITLE
Webpage Royalty Checklist Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#439]
Please update the following path on the onrr.gov website - https://www.onrr.gov/reportpay/roy-checklist.htm
 
Please change the contact from Jessica Bowlen to read as:
 
To obtain your ONRR Payor Number, to set up electronic reporting, and to receive an explanation of reporting requirements, email both contacts listed below:
 
Stacey Lopez – Stacey.Lopez@onrr.gov
Dustin Adair – Dustin.Adair@onrr.gov

**Comment by lpgoldstein** [comment]
@bowlenj This is ready for your review: http://2017onrr/reportpay/roy-checklist.htm

**Comment by bowlenj** [comment]
Hi Lindsay,

Can we change the highlighted word to Payor for this one?  The production checklist can say operator.

[cid:image002.jpg@01D6E5C3.9F332180]

Thank You,
Jessica Bowlen
Office of Natural Resource Revenue
Reference and Reporting Management
303-231-3202
Jessica.Bowlen@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

**Comment by lpgoldstein** [comment]
Yes, done. It's live!
