### ISSUE TITLE
Get update about EMARF development

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#444]
It's #1 doc in phase 1. We need an update to know what to do with it on onrr.gov

**Comment by jennmalcolm** [comment]
I sent a request for an update.

**Comment by jennmalcolm** [comment]
Here's the update:

the New EMARF Form is almost ready,  There are a few more tweaks before it can be put on the ONRR.Gov pages. I know I have a lot of requests in Github for link updates on some of the onrr.gov pages, but I believe the new link will be ready to go by end of next week.
