### ISSUE TITLE
Post Training Course Information on IESC Page

### ISSUE THREAD

**Issue by ONRRamandagarrison** [ONRR/onrr.gov-site#445]
At the top of this page (https://www.onrr.gov/IndianServices/indian-energy-service-center.htm) in a box, the following information needs to be added:

Fort Berthold Agency, Great Plains Region and IESC will host a 
WebEx ROW Training for Industry, Trust Beneficiaries, and MHA Nation 
January 21, 2021  1:00 -3:00PM CST 

For a link to the meeting or questions about the training, please email: IndianEnergyServiceCenter@bia.gov

The announcement can be removed on January 22nd.

**Comment by jennmalcolm** [comment]
@ONRRamandagarrison please review the changes on the development site, and let me know if you approve to publish. http://2017onrr/IndianServices/indian-energy-service-center.htm

**Comment by ONRRamandagarrison** [comment]
Looks good to publish! Only thing to "fix" is can the text be centered in the box. That's it.

Thank you,
Amanda

Amanda Garrison

Supervisory Minerals Revenue Specialist
Indian Energy Service Center
P: (720) 595-2025

**Comment by jennmalcolm** [comment]
The announcement is live now.
