### ISSUE TITLE
Change OST to the Bureau of Trust Funds Administration

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#447]
https://www.doi.gov/ost

In a reorganization effective October 1, 2020, the Bureau of Trust Funds Administration assumed the fiduciary functions previously managed by the Office of the Special Trustee for American Indians.

![image](https://user-images.githubusercontent.com/40175688/104634475-ea6ea880-565d-11eb-86c7-00c6b7a945b3.png)

**Comment by jennmalcolm** [comment]
This is ready. Please review dev @Maroyafaied.

http://2017onrr/About/index.htm

**Comment by Maroyafaied** [comment]
@jennmalcolm There's a mention of OST in this paragraph that needs to be changed. Thanks 
![image](https://user-images.githubusercontent.com/40175688/105388330-c1a56080-5bd3-11eb-81cd-0ac256b39d38.png)

**Comment by jennmalcolm** [comment]
Thanks, I made the other change, and pushed to prod.
