### ISSUE TITLE
Design diagram for how valuation works

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#448]

**Comment by mcharg** [comment]
A start:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/b35c69ef-de81-4b4e-a5ce-b3ff559ecee2)

**Comment by jennmalcolm** [comment]
Unit value is not always the sales price--specifically in non-arm's length situations and due to index price and major portion prices for Indian properties. Allowances are either transportation or processing. Unbundling determines what percentage of certain costs are allowable deductions.

**Comment by jennmalcolm** [comment]
I see you have a separate issue for Indian pricing diagram, so you can ignore my comment about the Indian prices.

**Comment by jennmalcolm** [comment]
If you haven't seen this pdf, or something similar, it talks about the royalty equation. It does only focus on oil and gas valuation, but solids have a similar situation where non-arm's length sales value is determined by benchmarks.  https://www.onrr.gov/ReportPay/training/pdfdocs/2018_Denver/FEDERALOIL_GASVALUATION%20OVERVIEW.pdf

**Comment by mcharg** [comment]
@jennmalcolm Thank you!

**Comment by mcharg** [comment]
@jennmalcolm Is this better?
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/3362a79f-27ab-40d9-9abd-0b2e6cb98619)

**Comment by jennmalcolm** [comment]
Yes, it's better, but I don't think the Indian prices are considered benchmark prices so maybe we could replace "a benchmark price" with "another price required by regulations."

**Comment by mcharg** [comment]
@jennmalcolm How's this?
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/a96604b3-f821-4794-9156-e9d33326c693)

**Comment by jennmalcolm** [comment]
I believe that the term "benchmark" was used with the old valuation rules. I don't think it's exactly accurate for the new valuation rules. I don't know what term to replace it with. Maybe we could just refer them to the valuation regulations index page for regulations and guidance that apply to non-arm's length sales? For Indian, change to "index or major portion prices for oil and gas on Indian lands."

**Comment by mcharg** [comment]
@jennmalcolm Better?
![image](https://user-images.githubusercontent.com/38465926/106053724-1efc4e80-60b9-11eb-9b50-14fe3bbd0ad3.png)

**Comment by mcharg** [comment]
Created #479 to address stakeholder feedback.
