### ISSUE TITLE
Design diagram for how Indian pricing works

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#449]

**Comment by mcharg** [comment]
A start:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/6453cc19-dfe4-4b7b-9f31-31bd6ec2cf67)

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/0e4aaf95-89ba-4e85-9af2-199829be0bef)

**Comment by mcharg** [comment]
I cut down on the number of words from the previous version:
https://qmcq5k.axshare.com/#id=y89dq7&p=indian_pricing

@Maroyafaied @jennmalcolm @lpgoldstein Do you want to review?

**Comment by Maroyafaied** [comment]
@mcharg it's definitely less words and simpler , I would suggest sending it to Robert Sudar and his team to review it for accuracy.

**Comment by Maroyafaied** [comment]
Waiting for feedback from SME

**Comment by mcharg** [comment]
Created #478 to incorporate stakeholder feedback.
