### ISSUE TITLE
Request to Update ONRR's Rules & Regulations Webpage

### ISSUE THREAD

**Issue by aklong09** [ONRR/onrr.gov-site#450]
Hello,

The ONRR Regulations Team is requesting updates to the ONRR Rules & Regulations webpage located at https://www.onrr.gov/Laws_R_D/FRNotices/AA27.htm – Please revise everything below the “30 CFR Parts 1206 and 1241” heading to read as follows:

“**Abstract:** The Office of Natural Resources Revenue (“ONRR”) published a proposed and final rule to amend certain regulations on how it values oil and gas produced from Federal leases for royalty purposes, values coal produced from Federal and Indian leases for royalty purposes, and assesses civil penalties for violations of certain statutes, regulations, leases, and orders associated with mineral leases. ONRR additionally made some minor, non-substantive corrections to its regulations through this rulemaking. 

On October 1, 2020, ONRR's proposed rule published in the Federal Register, at 85 Fed. Reg. 62054. Through the proposed rule, ONRR invited public comment for a 60-day period, which closed on November 30, 2020.

ONRR’s final rule was published in the Federal Register on January 15, 2021, at 86 Fed. Reg. 4612. The final rule shall become effective on February 16, 2021. ONRR’s final rule provided a separate compliance date under the DATES caption to establish that—for the amendments to 30 CFR part 1206 only—lessees must conform to the amended requirements under this final rule beginning with production that occurs on and after May 1, 2021.

For more information, please visit https://www.regulations.gov/ (or https://www.beta.regulations.gov/) and search “ONRR-2020-0001” or click the following links:

•	To access the docket folder: https://www.regulations.gov/docket?D=ONRR-2020-0001 
•	To view the proposed rule: https://www.federalregister.gov/documents/2020/10/01/2020-17513/onrr-2020-valuation-reform-and-civil-penalty-rule 
•	To view the final rule: https://www.federalregister.gov/documents/2021/01/15/2021-00217/onrr-2020-valuation-reform-and-civil-penalty-rule”

Would it also be possible to revise part of the navigation panel/headings for this page (my apologies for the wonky description)? Right now, it currently reads “Home / Rules & Regulations / Federal Register Notices / Proposed Rule RIN 1012-AA27” but the last part should instead just read as “RIN 1012-AA27” (removed the “Proposed Rule” part). 

Please feel free to reach out with any questions.

Thanks so much,
Alexis

**Comment by lpgoldstein** [comment]
@aklong09 This is ready for your review: http://2017onrr/Laws_R_D/FRNotices/AA27.htm

**Comment by aklong09** [comment]
Looks great, approved to publish! Thanks so much!

**Comment by lpgoldstein** [comment]
This one is live! https://www.onrr.gov/Laws_R_D/FRNotices/AA27.htm
