### ISSUE TITLE
Request to Update ONRR’s Federal Register Notices Webpage

### ISSUE THREAD

**Issue by aklong09** [ONRR/onrr.gov-site#451]
Hello,

The ONRR Regulations Team is requesting updates to the ONRR Federal Register Notices webpage, located at https://www.onrr.gov/Laws_R_D/FRNotices/index.htm 

First, please create a new page and dropdown option for the year 2021. 

Second, please create a new entry for our first 2021 publication (under a “FR Notices 2021” heading) to read as follows:

“86 FR 4612

Friday, January 15, 2021
**Denver, CO** ONRR published its final rule, entitled as the “ONRR 2020 Valuation Reform and Civil Penalty Rule” (RIN 1012-AA27), to amend certain regulations located in 30 CFR Parts 1206 and 1241. More specifically, ONRR’s final rule amends the portions of its regulations that relate to how it values oil and gas produced from Federal leases for royalty purposes, values coal produced from Federal and Indian leases for royalty purposes, and assesses civil penalties for violations of certain statutes, regulations, leases, and orders associated with mineral leases. ONRR additionally made some minor, non-substantive corrections to its regulations through this rulemaking.”

After the above description, please also add a hyperlink labeled as “View FR document” to the following website: https://www.federalregister.gov/documents/2021/01/15/2021-00217/onrr-2020-valuation-reform-and-civil-penalty-rule 

If possible, we’d also like to add an additional hyperlink (since this is a final rule) labeled as “View ONRR’s RIN 1012-AA27 Rulemaking Summary” to link back to the following ONRR webpage: https://www.onrr.gov/Laws_R_D/FRNotices/AA27.htm 

Please let me know if you have any additional questions.

Thanks in advance,
Alexis

**Comment by lpgoldstein** [comment]
@jlouis-onrr Can you help me with this please? http://2017onrr/Laws_R_D/FRNotices/index.htm How do I make this default to 2021 as the current year when the page loads? I added the new entry in the XML file but the default index view is still showing 2020 instead of 2021. 
![image](https://user-images.githubusercontent.com/39419003/105035280-f66cb880-5a17-11eb-887a-e432a9288c5c.png)

**Comment by lpgoldstein** [comment]
@aklong09 Please take a look when you get a chance. I'm getting some help from a developer to make 2021 show up as the new default year but the information is there. http://2017onrr/Laws_R_D/FRNotices/index.htm . Please choose 2021 in the drop down menu on the right hand side to see the information.

**Comment by aklong09** [comment]
Good morning, this one looks great too! Also approved to publish. My apologies for the delayed response by the way. I was on leave yesterday. 

Thanks again!

**Comment by lpgoldstein** [comment]
@aklong09 This is live and 2021 is now the default year for current frs. No worries! That's what I figured. You are always very quick to respond when in the office.
