### ISSUE TITLE
Prices that end in 0 are missing the 0 digit.

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#454]
Robert pointed this out in the wireframes, but they're screenshots from the live site.

NYMEX:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/9d2b478e-cccb-4c7f-a910-c4f301715450)

Indian Gas Index Zone:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/67e25590-94a5-4bc9-b88b-7da5723e41a1)

Indian Oil Major Portion:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/4a112039-7cb6-4e88-9965-57560a766219)

Indian Gas Major Portion is displaying correctly.

**Comment by lpgoldstein** [comment]
http://2017onrr/Valuation/NYMEX.htm
http://2017onrr/Valuation/allzones.htm
http://2017onrr/Valuation/IndianOilIBMP.htm
@mcharg please check

**Comment by mcharg** [comment]
@lpgoldstein Looks good!
