### ISSUE TITLE
Update ONRR Payments PAge

### ISSUE THREAD

**Issue by vcs5274** [ONRR/onrr.gov-site#458]
Please update the ONRR Payments page.

Remove Michelle Van Vleet and replace with Soukanya Phommachaly

ONRR-RFMASGL@onrr.gov
(800) 433-9801 x 3110
(303) 231-3110

**Comment by jennmalcolm** [comment]
@vcs5274 the changes are ready for you to review on our development site: http://2017onrr/ReportPay/payments.htm

Please let me know if they look good to publish. Thanks.

**Comment by vcs5274** [comment]
Good morning,

The changes look good to publish.

Thank you,

Victoria Soto
Office of Natural Resources Revenue
DFC 6th Ave & Kipling
Bldg 85 Entrance N-1
Denver, CO  80225
Supervisory Accountant, Accounting Services, General Ledger
Phone: 1-800-433-9801 x13085
     -or-      303-231-3085
Fax: 303-445-9526
Email: victoria.soto@onrr.gov<mailto:victoria.soto@onrr.gov>

"Virtually nothing is impossible in this world if you just put your mind to it and maintain a positive attitude." - Lou Holtz

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________

**Comment by jennmalcolm** [comment]
The changes are live.
