### ISSUE TITLE
New Production Operator Checklist Update Request

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#459]
Please update the following path on the onrr.gov website- https://www.onrr.gov/ReportPay/prod-checklist.htm

2. After you receive your OCS Qualification Number, call one of the following contacts to obtain your ONRR Operator Number, set up electronic reporting, and receive an explanation of reporting requirements:

Stacey Lopez
New User Contact
Stacey.Lopez@onrr.gov 

Dustin Adair
New User Contact
Dustin.Adair@onrr.gov

**Comment by jennmalcolm** [comment]
@bowlenj, the changes are ready for you to review on our development site:

http://2017onrr/ReportPay/prod-checklist.htm

**Comment by bowlenj** [comment]
Perfect!  Thank you for correcting this so quickly!

Thank You,
Jessica Bowlen
Office of Natural Resource Revenue
Reference and Reporting Management
303-231-3202
Jessica.Bowlen@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

**Comment by jennmalcolm** [comment]
The changes are live.
