### ISSUE TITLE
Please remove eCFR box

### ISSUE THREAD

**Issue by jpetersononrr** [ONRR/onrr.gov-site#463]
Hello!

Can you please remove the "eCFR Update" box on the right side of this page?  Thanks!

https://www.onrr.gov/Valuation/index.htm

Jodie

**Comment by jennmalcolm** [comment]
This is ready for your review in dev @jpetersononrr.

http://2017onrr/Valuation/index.htm

**Comment by jpetersononrr** [comment]
Looks splendid!  Thank you!

​Jodie Peterson
Minerals Revenue Specialist
Office of Natural Resources Revenue
​jodie.peterson@onrr.gov
(303)231-3719

Royalty Valuation - Consistent Answers to Complex Questions

**Comment by jennmalcolm** [comment]
The changes are live.
