### ISSUE TITLE
Design new reporter checklist

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#464]

**Comment by mcharg** [comment]
Wireframe:
https://qmcq5k.axshare.com/#id=muwj32&p=new_reporter_setup

Logic:
https://qmcq5k.axshare.com/#id=atfm3f&p=checklist_logic&g=1

@Maroyafaied @lpgoldstein @jennmalcolm Do you want to review?

**Comment by Maroyafaied** [comment]
@mcharg Do we need to add more details here in the logic or will it be in the checklist? For example, which forms to establish access to the data warehouse (acceptable use policy and EMARF) or which form to establish contact (ONRR-4444)?

**Comment by mcharg** [comment]
@Maroyafaied It's in the checklist, if you look at the wireframe.

**Comment by Maroyafaied** [comment]
@mcharg Oh I should've scrolled down on the wireframe before I commented!

**Comment by Maroyafaied** [comment]
@mcharg I reviewed the wireframe, it looks great. The only think I think is missing is the EMARF contact for solid minerals. Great job capturing everything.

![image](https://user-images.githubusercontent.com/40175688/106037327-c2d30380-6093-11eb-8a08-3bd98ff3c977.png)

**Comment by mcharg** [comment]
@Maroyafaied I added the solids contact along with an IT service desk number that was on the royalty checklist for the other commodities.
