### ISSUE TITLE
change to contacts

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#47]
- [x] https://www.onrr.gov/reportpay/prod-checklist.htm - Onshore production reporters- Remove Michael Haring and modify “Eugene Lynn to “Eugenia (Jeannie) Lynn” (it has a typo currently), and add her email address in addition to the phone number (Eugenia.lynn@onrr.gov)

 

- [x] https://www.onrr.gov/reportpay/roy-checklist.htm    - Part 2  currently has Candace Merrell listed as the contact for EMARFS- it should now be Stacey Brown

- [x] Requester review (in email box)

**Comment by Maroyafaied** [comment]
Send it for review and waiting for a response.

**Comment by jennmalcolm** [comment]
Requester reviewed and responded by email, but we may have a change to one of the contacts. So, I have reached out for more info from others.

**Comment by jennmalcolm** [comment]
@Maroyafaied go ahead and push these changes to production. The requested did review them. I reached out to some other people for some additional info, which I haven't received. If we receive more feedback, we can make another change. Thanks.

**Comment by Maroyafaied** [comment]
This issue is now fixed on onrr.gov 
https://www.onrr.gov/reportpay/prod-checklist.htm 
https://www.onrr.gov/reportpay/roy-checklist.htm

**Comment by jennmalcolm** [comment]
@Maroyafaied we just got a change of the requested contact for the EMARF. Could you change this now?

Please use the following information for EMARF Contact on ONRR.Gov:

Enterprise IT Service Desk: 1 877-256-6260

**Comment by Maroyafaied** [comment]
@jennmalcolm which page is this contact?

**Comment by jennmalcolm** [comment]
It is on this page: https://www.onrr.gov/reportpay/roy-checklist.htm

In this issue, we had changed it to Stacey Browne, but we just got more feedback on it, and it should be the service desk.

**Comment by Maroyafaied** [comment]
@jennmalcolm  Please review https://www.onrr.gov/ReportPay/roy-checklist.htm

**Comment by jennmalcolm** [comment]
Looks good. Thanks @Maroyafaied
