### ISSUE TITLE
Clean up wireframes in Reporting section

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#475]
I want to get rid of screenshots and do readability edits before we review with the teams.

**Comment by mcharg** [comment]
@Maroyafaied @jennmalcolm @lpgoldstein These are ready for you to review.
https://qmcq5k.axshare.com/#id=oy6t9q&p=reporting

**Comment by Maroyafaied** [comment]
@mcharg it looks great, I really like how you included the handbooks in the reference tabs.  I wonder if reference list and reporting codes should move up with the cards but we can get feedback on that from the stakeholders. Also, I think some of the items are not relevant for geothermal but again we'll have to talk to SME. 
![image](https://user-images.githubusercontent.com/40175688/107546431-95a14d80-6b89-11eb-8272-5cfbf5313b4a.png)

**Comment by lpgoldstein** [comment]
I really like the task oriented headers and how all of the pages have less information. Much easier to digest.

**Comment by jennmalcolm** [comment]
They look good to me.
