### ISSUE TITLE
Remove book icon from checklist links

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#476]
This is the glossary icon, but these aren't glossary links.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/6c0879ee-0bb4-47f8-9895-cf7a0293fa60)

**Comment by jennmalcolm** [comment]
I started to do this but realized that those are actually links to the glossary. If you click on the books, you get the definitions for new production reporter, new royalty reporter, and new solids reporter. Do you still want to get rid of them? 
![image](https://user-images.githubusercontent.com/30806839/106816808-ebcf3780-6643-11eb-9fbd-23c9e2517fcb.png)

**Comment by mcharg** [comment]
I didn't realize those were glossaries and neither did Ryan (I added this issue when reviewing his doc) and I don't think the glossary content is helpful.  I think we should remove them.

**Comment by jennmalcolm** [comment]
Ok I've removed them in dev. Please review @mcharg.

http://2017onrr/ReportPay/production-reporting.htm

**Comment by mcharg** [comment]
Looks good.

**Comment by mcharg** [comment]
This is now live.
