### ISSUE TITLE
ONRR.gov Production Reporting References

### ISSUE THREAD

**Issue by ONRR-31577** [ONRR/onrr.gov-site#48]
On the Production Reporting References page at https://onrr.gov/ReportPay/references.htm, in the Offshore section,
please
- replace the five Gulf link pdf files with the attached pdf files--the
file names are the same; and
- replace the (as of ...) dates for all files with  02/27/2020
[Gulf-Metering-Systems.pdf](https://github.com/ONRR/onrr.gov-site/files/4283661/Gulf-Metering-Systems.pdf)
[Gulf-Sales-Tanks.pdf](https://github.com/ONRR/onrr.gov-site/files/4283662/Gulf-Sales-Tanks.pdf)
[Gulf-Gas-Plants.pdf](https://github.com/ONRR/onrr.gov-site/files/4283663/Gulf-Gas-Plants.pdf)
[Gulf-Flash-Gas.pdf](https://github.com/ONRR/onrr.gov-site/files/4283664/Gulf-Flash-Gas.pdf)
[Gulf-Buy-Back.pdf](https://github.com/ONRR/onrr.gov-site/files/4283665/Gulf-Buy-Back.pdf)

**Comment by mentastc** [comment]
email sent to dev site with update

**Comment by mentastc** [comment]
@ONRR-31577, I've update the site in staging, please review the link below, when I have your ok I will push it to the live site.

Link: http://2017onrr/ReportPay/references.htm
Thanks,

Chris

**Comment by jennmalcolm** [comment]
@lpgoldstein please review and we'll just push since we haven't heard back from @ONRR-31577

**Comment by jennmalcolm** [comment]
@lpgoldstein have you reviewed these changes?

**Comment by ONRR-31577** [comment]
Jennifer,
    Yes. I replied to the original email asking me to review. And I replied it the app telling you I approved. Hopefully you receive this message.
Yes I approve.
Thank you,

-------- Original Message --------

**Comment by jennmalcolm** [comment]
Thank you @ONRR-31577, we did receive this reply. I think this repo may not be set up to post replies to email notifications, but I'll look into changing that. @mentastc please push this to production.

**Comment by mentastc** [comment]
@ONRR-31577 the changes have been pushed to the live site and should appear in the next 15 minutes.
