### ISSUE TITLE
Contact program managers about Phase 2 projects

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#480]
1. create a spreadsheet for each program manager
2. send email with deadline for phase 2

**Comment by lpgoldstein** [comment]
@Maroyafaied link to spreadsheets https://doimspp-my.sharepoint.com/:x:/r/personal/mchargs_mms_gov/Documents/onrr.gov/508/Phase%202/Phase%202%20-%20Michael%20Marchetti.xlsx?d=wbe19ac1c835442e9a41daf810dab0e2a&csf=1&web=1&e=AScJDQ

**Comment by jennmalcolm** [comment]
I think we should ask Patty about the acceptable use policy.

**Comment by Maroyafaied** [comment]
Contacted everyone but Lee Ann's group , will reach out after they complete phase 1.
