### ISSUE TITLE
production references update

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#482]
On the ONRR.gov home page, please update the Production Reporting References with the attached files. The new as of date is 29 Jan 2021.
There are five Gulf files and three Pacific files.
[Gulf-Metering-Systems.xlsx](https://github.com/ONRR/onrr.gov-site/files/5911031/Gulf-Metering-Systems.xlsx)
[Gulf-Sales-Tanks.xlsx](https://github.com/ONRR/onrr.gov-site/files/5911032/Gulf-Sales-Tanks.xlsx)
[Pacific Gas Plants.xlsx](https://github.com/ONRR/onrr.gov-site/files/5911033/Pacific.Gas.Plants.xlsx)
[Pacific Metering Systems.xlsx](https://github.com/ONRR/onrr.gov-site/files/5911034/Pacific.Metering.Systems.xlsx)
[Pacific Sales Tanks.xlsx](https://github.com/ONRR/onrr.gov-site/files/5911035/Pacific.Sales.Tanks.xlsx)
[Gulf-Buy-Back.xlsx](https://github.com/ONRR/onrr.gov-site/files/5911036/Gulf-Buy-Back.xlsx)
[Gulf-Flash-Gas.xlsx](https://github.com/ONRR/onrr.gov-site/files/5911037/Gulf-Flash-Gas.xlsx)
[Gulf-Gas-Plants.xlsx](https://github.com/ONRR/onrr.gov-site/files/5911038/Gulf-Gas-Plants.xlsx)

**Comment by jennmalcolm** [comment]
@ONRR-31577 the changes are ready for your review in our development site:

http://2017onrr/ReportPay/references.htm

**Comment by ONRR-31577** [comment]
That looks good Jennifer.

Thank you,



Johnny Erle

Reference, Royalty, and Production Team 1A - Production Specialist (GVS)
Reference and Reporting Management
Office of Natural Resources Revenue
Office: (303) 231-3577



________________________________

**Comment by jennmalcolm** [comment]
The updates are live.
