### ISSUE TITLE
Update to ONRR.gov Civil Penalties Page

### ISSUE THREAD

**Issue by schartoa** [ONRR/onrr.gov-site#484]
Good morning,

Please update the ONRR.gov>Compliance>Civil Penalties page with a new PDF document (attached) under the heading "Penalty Collections by Fiscal Year."  Please use "2020" for this document's hyperlink.  

Thank you for your help!
Andrea Scharton
[FY 2020 Civil Penalty Collections-508 Accessible.pdf](https://github.com/ONRR/onrr.gov-site/files/5912923/FY.2020.Civil.Penalty.Collections-508.Accessible.pdf)

**Comment by jennmalcolm** [comment]
Hi @schartoa there is still one 508 error. It looks like you need to set a language. Please see the attached error report and re-attach the document once you address that issue. 
[FY.2020.Civil.Penalty.Collections-508.Accessible.pdf.accreport.pdf](https://github.com/ONRR/onrr.gov-site/files/5913078/FY.2020.Civil.Penalty.Collections-508.Accessible.pdf.accreport.pdf)

**Comment by schartoa** [comment]
[FY 2020 Civil Penalty Collections-508 Accessible.pdf](https://github.com/ONRR/onrr.gov-site/files/5913227/FY.2020.Civil.Penalty.Collections-508.Accessible.pdf)

Hi Jennifer,
I have set the language in the attached PDF.  Please let me know if you come across any other errors.  Thank you!

**Comment by jennmalcolm** [comment]
@schartoa please review the updates on our development site, and let us know if you approve to publish live on onrr.gov. Thanks.

http://2017onrr/compliance/

**Comment by schartoa** [comment]
Looks great! Please publish to onrr.gov.  Thank you, Jennifer!

**Comment by jennmalcolm** [comment]
This is live.
