### ISSUE TITLE
ONRR.gov Indian Gas Index Zone monthly price update

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#486]
The February Indian Gas Index Zone prices are ready to be updated.  The prices have been added to the DataforONRR.gov spreadsheet in OneDrive.

Thanks,
Cory Forgrave
@sudarr

**Comment by mcharg** [comment]
@forgravec This is updated on dev.  Please review. http://2017onrr/Valuation/allzones.htm

**Comment by forgravec** [comment]
@mcharg The prices look good.
Thanks!

@sudarr

**Comment by mcharg** [comment]
@forgravec Change is live.
https://www.onrr.gov/Valuation/allzones.htm
