### ISSUE TITLE
Webpage Update - Cross Reference Lease to Agreement

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#487]
Please update the following webpage http://www.onrr.gov/ReportPay/CrossRef.htm

Cross-Reference Lease to Agreement Numbers sorted by Agreement Name
Cross-Reference Lease to Agreement Numbers sorted by Agreement Number
Cross-Reference Lease to Agreement Numbers sorted y Lease Number
with the attached  files.  Also change update to 02/01/2021

Thank you

[sorted by agreement name.xlsx](https://github.com/ONRR/onrr.gov-site/files/5920297/sorted.by.agreement.name.xlsx)
[sorted by agreement number.xlsx](https://github.com/ONRR/onrr.gov-site/files/5920301/sorted.by.agreement.number.xlsx)
[sorted by Lease Number.xlsx](https://github.com/ONRR/onrr.gov-site/files/5920304/sorted.by.Lease.Number.xlsx)

/2021.

**Comment by lpgoldstein** [comment]
@merrellc This is ready for your review http://2017onrr/ReportPay/CrossRef.htm

**Comment by merrellc** [comment]
Hi, do I need to lock the spreadsheet before submitting?  I was able to change the data.

Kindly

​Candace Merrell
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
Candace.Merrell@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________

**Comment by lpgoldstein** [comment]
@merrellc I don't think so. The person that downloads it can't make any changes to the spreadsheet on the website.

**Comment by merrellc** [comment]
So, it's not changing the original document?

Kindly

​Candace Merrell
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
Candace.Merrell@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________

**Comment by lpgoldstein** [comment]
@merrellc Nope! Only someone with access to our system can change the original document.

**Comment by merrellc** [comment]
Thank you! The file is ready.

Kindly

​Candace Merrell
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
Candace.Merrell@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________

**Comment by lpgoldstein** [comment]
@merrellc changes are live!
