### ISSUE TITLE
Electronic EMARF link - updates on all pages

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#489]
Please remove the pdf EMARF form and have the word EMARF in blue be a link to the electronic EMARF located at:

https://www.onrr.gov/reportpay/forms/index.htm

Link to electronic EMARF - https://emarf.onrr.gov/emarf

**Comment by bowlenj** [comment]
Please also add the EMARF link to the following webpages as well:
https://www.onrr.gov/reportpay/prod-checklist.htm
https://www.onrr.gov/reportpay/roy-checklist.htm
        #2 under Establish Access to the ONRR Data Warehouse
https://www.onrr.gov/reportpay/solids-checklist.htm
        #1 under Next

**Comment by jennmalcolm** [comment]
Hi @bowlenj all of these changes are available for you to review in dev:

http://2017onrr/

I've also made some changes to the wording in some descriptions as requested by our designer. 

Please review the link updates you requested and let me know if you approve. Thanks.

**Comment by bowlenj** [comment]
Hi Jennifer,

The link looks great!

I did a search on ONRR.gov and found some other areas where the old form is still out there.

Can we get these updated to the new link as well, we don't want the pdf version online, IT is no longer accepting that form.
https://www.onrr.gov/reportpay/forms/
https://www.onrr.gov/reportpay/PDFDocs/EMARF_Instructions.pdf
https://www.onrr.gov/reportpay/forms/index.htm
https://www.onrr.gov/ - Under quick forms, please remove pdf form and add new link
https://www.onrr.gov/ReportPay/access.htm - #2<https://www.onrr.gov/ReportPay/access.htm%20-%20#2> at the top, remove PDF and add new link
https://www.onrr.gov/reportpay/reporter-maintenance.htm - #2 at the top, remove PDF and add new link
https://www.onrr.gov/ReportPay/roy-checklist.htm  - #2, remove PDF and add new link



Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
Jessica.Bowlen@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

**Comment by mcharg** [comment]
Hi @bowlenj I think all the pages you referenced have been updated in dev.  If you take a look and give the okay, I can push them live today.

Forms page: http://2017onrr/ReportPay/Forms/index.htm
Quick forms on homepage: http://2017onrr/
Access page: We don't think this one is linked anywhere and has similar content to the reporter maintenance.  Could we redirect that page to the reporter maintenance one?
Reporter maintenance: http://2017onrr/ReportPay/reporter-maintenance.htm
Royalty reporter checklist: http://2017onrr/ReportPay/roy-checklist.htm

The link to the PDF itself - we can probably redirect that link to the online form, but I don't know how to do it, so it'll have to wait until Jennifer is back in the office on Monday.

**Comment by bowlenj** [comment]
Thank you!  They all look great 😊

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
Jessica.Bowlen@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

**Comment by mcharg** [comment]
@bowlenj The changes are now live, if you want to take a look and see if they look ok.
https://www.onrr.gov/

**Comment by mcharg** [comment]
@bowlenj I created new issues for redirecting the pdf url (#493) and access page (#494), so we can close this issue if you are good with the changes in production.

**Comment by bowlenj** [comment]
Thank you, it looks great!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
Jessica.Bowlen@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.
