### ISSUE TITLE
NYMEX price upload

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#49]
This is a test to make sure we are correctly completing our requests for ONRR.gov website changes.
Our group, MSA, upload NYMEX, and Indian Gas Index prices at the beginning of every month to the "Valuation" section of ONRR.gov.  This upcoming week, we will have new prices that will need to be uploaded to the 'NYMEX Oil Prices' webpage as well as the 'Indian Gas Index Zone' webpage.

We also have a spreadsheet that gets uploaded with the NYMEX prices.

**Comment by forgravec** [comment]
Just testing the process of how we will be submitting a request to upload prices.

**Comment by jennmalcolm** [comment]
This looks good. Thanks!
