### ISSUE TITLE
Solids WebPage Updates

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#490]
Please update the Solids Checklist, Solids Minerals Page, and Solids information on the Handbook page of the web site per the attached file.
[Solids Webpage Update_2-1-21.docx](https://github.com/ONRR/onrr.gov-site/files/5926765/Solids.Webpage.Update_2-1-21.docx)

**Comment by lpgoldstein** [comment]
@bowlenj please review: http://2017onrr/ReportPay/solids-checklist.htm
http://2017onrr/ReportPay/solids.htm

**Comment by bowlenj** [comment]
Hello,

Can we update the contact for Solid Minerals Reporter Handbook, just like for the other contacts:

Below are changes to the Handbooks Page located at - https://www.onrr.gov/ReportPay/Handbooks/index.htm



  *   Remove Mike Anspach as contact and add:
               onrrsolidmineralreferencedata@onrr.gov or calling your Solid Mineral Contact listed here: insert link to Lease Maintenance contact sheet -                  https://www.onrr.gov/ReportPay/PDFDocs/RS_LeAgAssignments.pdf

[Graphical user interface, text, application, email  Description automatically generated]


Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
Jessica.Bowlen@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

**Comment by lpgoldstein** [comment]
@bowlenj http://2017onrr/ReportPay/Handbooks/index.htm The changes should be here - maybe you need to clear your cache to see?

**Comment by bowlenj** [comment]
Yep, I see it now!  Thank you it looks great 😊

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
Jessica.Bowlen@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

**Comment by lpgoldstein** [comment]
@bowlenj Changes are live!
