### ISSUE TITLE
Make copy tweaks related to the new online EMARF

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#491]
Edits are in this prototype: https://t3tt84.axshare.com

Edits are on these pages:
- [x] Home
- [x] Setup & Maintenance
- [x] Forms
- [x] Production Reporter Checklist
- [x] Royalty Reporter Checklist
- [x] Solid Minerals Reporter Checklist
- [x] EMARF glossary term
- [ ] Access page
- [x] Add 4425 to forms page

**Comment by jennmalcolm** [comment]
I think I have all but the access page in dev and ready for your review @mcharg. I'll wait to see if we need to keep the access page before I work on it.

**Comment by mcharg** [comment]
@jennmalcolm It's not looking like the glossary got updated.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/ad09934f-4207-44bb-afc9-6d947fcb5535)

**Comment by mcharg** [comment]
Everything else looks good.

**Comment by mcharg** [comment]
Glossary is now updated and I created and I created #494 for redirecting the access page.
