### ISSUE TITLE
Make the ONRR logo open the homepage

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#492]
The site title currently does, but the logo doesn't.

**Comment by mcharg** [comment]
@Maroyafaied This along with fixing capitalization in links are on dev.  Let me know if it looks good to push live (copying every page to the live folder).  For the links, I did a find and replace on capitalization, so not sure what to check, but let me know if you find any broken links.
http://2017onrr/

**Comment by Maroyafaied** [comment]
@mcharg the logo and links are good but I noticed some of the symbols are missing, I'm not sure if it's anything related to changes made in this issue. 
![image](https://user-images.githubusercontent.com/40175688/113919333-b7413e80-97a0-11eb-99b4-3fafe90636f2.png)

**Comment by mcharg** [comment]
@Maroyafaied Those are always missing in dev for me, but show up on the live site.

**Comment by Maroyafaied** [comment]
@mcharg ok , you're good to push live.

**Comment by mcharg** [comment]
Pushed live
