### ISSUE TITLE
Redirect EMARF pdf link to EMARF online form

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#493]
Old link: https://www.onrr.gov/reportpay/PDFDocs/EMARF_Instructions.pdf

Redirect to: https://emarf.onrr.gov/emarf

**Comment by jennmalcolm** [comment]
I don't know how to redirect from a url for a pdf. @jlouis-onrr is there a way we can do this?

**Comment by mcharg** [comment]
@jennmalcolm If we can't do that, maybe we can make a one page PDF with the same name with just a link to the tool and a note to update bookmarks in it.

**Comment by jennmalcolm** [comment]
Never mind @jlouis-onrr, I figured out a way to do it.

@mcharg  please review in dev.

**Comment by mcharg** [comment]
@jennmalcolm Looks good.

**Comment by jennmalcolm** [comment]
live
