### ISSUE TITLE
Redirect Access page to Reporter Maintenance page

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#494]
Old link: https://www.onrr.gov/ReportPay/access.htm

Redirect to: https://www.onrr.gov/reportpay/reporter-maintenance.htm

**Comment by jennmalcolm** [comment]
Please review in dev @mcharg

**Comment by mcharg** [comment]
When I got to http://2017onrr/ReportPay/access.htm it's redirecting to the access page on the live site, not to the reporter maintenance page.

**Comment by jennmalcolm** [comment]
My mistake @mcharg. Please check again, and thanks for catching that.

**Comment by mcharg** [comment]
@jennmalcolm Looks good.

**Comment by jennmalcolm** [comment]
changes live
