### ISSUE TITLE
Redirect second production reporter checklist to the one that's linked

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#495]
Old link: https://www.onrr.gov/ReportPay/production-reporter-checklist.htm

Redirect to: https://www.onrr.gov/reportpay/prod-checklist.htm

**Comment by jennmalcolm** [comment]
Please review in dev @mcharg

**Comment by mcharg** [comment]
@jennmalcolm Looks good.

**Comment by jennmalcolm** [comment]
Changes live
