### ISSUE TITLE
January NYMEX to be posted to ONRR.gov

### ISSUE THREAD

**Issue by jpenvose773** [ONRR/onrr.gov-site#496]
[NYMEX012021.xlsx](https://github.com/ONRR/onrr.gov-site/files/5934986/NYMEX012021.xlsx)
The January NYMEX prices are ready to be posted to ONRR.gov. I've attached the file with the data. Thank you!
@sudarr

**Comment by jennmalcolm** [comment]
@jpenvose773, this is ready for your review in dev. Thanks

http://2017onrr/Valuation/NYMEX.htm

**Comment by jpenvose773** [comment]
Hi Jennifer,

The webpage with January 2021 NYMEX data looks great; thank you!

Jessica

**Comment by jennmalcolm** [comment]
The changes are live--but you'll probably have to clear your cache to see them.
