### ISSUE TITLE
Write open opportunities description for someone to do visual design

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#497]
https://openopps.usajobs.gov/

https://usajobs.github.io/openopps-help/opportunity-creators/

**Comment by mcharg** [comment]
@Maroyafaied Here's a draft post.  Thoughts? https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/Documents/NRRD%20Portal/Outreach/Proposals/FY21/OpenOppurtunities_VizDesign.docx?d=we2545ea0f20b4789b37ed96adf86ff9e&csf=1&web=1&e=MaHECo

**Comment by Maroyafaied** [comment]
@mcharg looks good , I like it.  What do we have to do to post it? Do we need to mention time frame?

**Comment by mcharg** [comment]
Submitted. They'll let me know within two days whether they accept it.

**Comment by mcharg** [comment]
Opportunity is live: https://openopps.usajobs.gov/tasks/2108
