### ISSUE TITLE
Update events calendar

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#50]
to include
Wednesday, March 18, 2020 at 1:00:00 PM | Wednesday, March 18, 2020 at 2:30:00 PM | KAULEY MEETING | Anadarko | OK | Wichita & Affiliated Tribes, Administration Bldg. | Presentation/Meeting with Owners | Office of Natural Resources Revenue | Indian Trust Land Owners | Bring any statements, EOPs, or other documents you wish to discuss. | Oklahoma City Office | Toll Free (800) 354-7015 | sandra.todd@onrr.gov
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Saturday, April 4, 2020 at 1:00:00 PM | Wednesday, April 4, 2020 at 6:30:00 PM | Oklahoma City University Powwow Outreach | Oklahoma City | OK | Henry J Freede Wellness Center, OCU Campus | OKC Outreach Booth | Office of Natural Resources Revenue | Indian Trust Land Owners | Bring EOPS and other documents | Oklahoma City Office | Toll Free (800) 354-7015 | sandra.todd@onrr.gov

**

**Comment by mentastc** [comment]
email sent from web mailbox to review dev

**Comment by jennmalcolm** [comment]
@Lindsay, could you review the calendar additions in dev so that we can get this pushed to prod since this is time-sensitive, and we haven't heard back from the requester.

**Comment by jennmalcolm** [comment]
@mentastc I reviewed this and it looks good, so please push this file to production, and then let the requester know that we went ahead and made it live due to the time-sensitive nature.

**Comment by mentastc** [comment]
site has been updated
