### ISSUE TITLE
January 2021 IBMP Pirces

### ISSUE THREAD

**Issue by damionschulte** [ONRR/onrr.gov-site#500]
All, I have updated the ONRR.Gov sheet with the January 2021 IBMP Prices.  Can you please publish them?  Thank you 

@sudarr

**Comment by jennmalcolm** [comment]
@damionschulte this is ready for your review in dev:

http://2017onrr/Valuation/IndianOilIBMP.htm

You will probably need to clear your cache to get the new year to come up. Thanks.

**Comment by damionschulte** [comment]
These look great!  Thank you

**Comment by jennmalcolm** [comment]
The prices are live.
