### ISSUE TITLE
Paper form is listed twice on the solid minerals checklist

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#501]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/17162fa5-2e12-4cc4-a278-68e86308b5be)

**Comment by lpgoldstein** [comment]
@mcharg ready for your review: http://2017onrr/ReportPay/solids.htm

**Comment by mcharg** [comment]
@lpgoldstein Looks good.
