### ISSUE TITLE
Safety net report is missing a header on the solids page

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#502]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/0125a576-283f-4b1e-8f42-8aa2bb9d76f3)

**Comment by mcharg** [comment]
@Maroyafaied This is updated in dev.  I also cleaned up the heading levels on this page. Can you please review?
http://2017onrr/reportpay/solids.htm

**Comment by Maroyafaied** [comment]
@mcharg looks good

**Comment by mcharg** [comment]
Pushed to the live site.
