### ISSUE TITLE
Update FS FED Contact list on ONRR.GOV

### ISSUE THREAD

**Issue by Sheetsj** [ONRR/onrr.gov-site#507]
Hello,

I need to update the contact list on ONRR.gov. Location, "Contact US>under Online Resources> under ONRR Contacts by Company Assignment>File "Accounts Receivable, Billing, and Financial Issues information--Federal. 

File can be located on N'Drive: \\ISEDENNAS\DEN_Common\FMD\FinancialServices\Admin\Fed Assignment Contact List 
Name of PDF file finserAssign
[finserAssign.pdf](https://github.com/ONRR/onrr.gov-site/files/5961653/finserAssign.pdf)

**Comment by lpgoldstein** [comment]
@Sheetsj This is ready for your review: http://2017onrr/About/contact.htm

Also, the file still has the update date of 9/28/2020. I'm not sure if that is intentional but wanted to let you know.

**Comment by Sheetsj** [comment]
Thank you so much for getting that up, and letting me know about the date. We are going to have some new people joining the team and also leaving the team soon. So it will be updated again in a few months. Since the names are good right now, I will leave the file update date the way it is and when I submit a new request I will make sure to change it to the correct one. 

Thanks again!

**Comment by Sheetsj** [comment]
I saw that it was not live yet. So I updated the date on the file. I have attached the updated one 
[finserAssign.pdf](https://github.com/ONRR/onrr.gov-site/files/5965315/finserAssign.pdf)

**Comment by lpgoldstein** [comment]
@Sheetsj Thanks! I was unable to tell if I had the right file so just wanted to make sure http://2017onrr/About/contact.htm - please check the preview and then I will push to the live site.

**Comment by Sheetsj** [comment]
That is perfect! Thank you! you are good to make it live.

**Comment by lpgoldstein** [comment]
@Sheetsj It's live

**Comment by Sheetsj** [comment]
Thank you!

**Comment by Sheetsj** [comment]
Does it take a little bit? I just went on there and it is still showing the old version?

**Comment by jennmalcolm** [comment]
@Sheetsj it looks like the production server might be having issues updating. We're looking into it. Thanks.

**Comment by jennmalcolm** [comment]
This is working now @Sheetsj.

**Comment by Sheetsj** [comment]
I just looked and it is still the old one?

**Comment by Sheetsj** [comment]
I just looked again and it is still not live :(

**Comment by lpgoldstein** [comment]
@Sheetsj You probably just need to clear your cache or try on another browser. Jennifer and I can both see it and we checked on personal cell phones as well.

**Comment by Sheetsj** [comment]
I just tried it on another browser and it is up to date. Thank you again for your help in this.

**Comment by lpgoldstein** [comment]
Of course! Have a great weekend!
