### ISSUE TITLE
Broken Link on ONRR.gov  and Missing Handbook

### ISSUE THREAD

**Issue by mentastc** [ONRR/onrr.gov-site#51]
I was looking for the Oil and Gas Payor Handbook, Volume III—Product Valuation, it is not on the Handbook page, it states that it is being revised but the old version is not out there, only an Indian Payor Handbook is available and I do not need the one specific to Indian, please tell me if I am looking in the wrong place for the Oil and Gas Payor Handbook, Volume III—Product Valuation? 

Below are urls and screen shots of how I got to the broken link

https://www.onrr.gov/ReportPay/Handbooks/index.htm
 
![image](https://user-images.githubusercontent.com/15347998/75891826-578a9e00-5dfe-11ea-9600-b46e15af9ad7.png)

 So I searched for the Oil and Gas Payor Handbook, Volume III—Product Valuation and came to the page below

https://www.onrr.gov/Valuation/index.htm
Clicked on the link below
 
![image](https://user-images.githubusercontent.com/15347998/75891879-6a04d780-5dfe-11ea-9ecd-8d7735d6e775.png)

 And it took me here
https://www.onrr.gov/404.htm
 
![image](https://user-images.githubusercontent.com/15347998/75891917-76893000-5dfe-11ea-999f-d014f23aa8cc.png)

Donna Galloway, Program Analyst

**Comment by mentastc** [comment]
This may be blocked by the RPC litigation. @jennmalcolm do you know if this was taken down intentionally?

**Comment by jennmalcolm** [comment]
I talked to RV, and they took the handbook off intentionally.

**Comment by jennmalcolm** [comment]
@mentastc I can tell you who to talk to in RV to follow up on this.

**Comment by lpgoldstein** [comment]
@jennmalcolm RV says they are still working on this so we can pull it out of this sprint.

**Comment by lpgoldstein** [comment]
@jennmalcolm This is ready for your review. The link has been removed. http://2017onrr/Valuation/index.htm

**Comment by jennmalcolm** [comment]
Looks good @lpgoldstein

**Comment by lpgoldstein** [comment]
removed the broken link from the website.
