### ISSUE TITLE
Correct Solids Email link on webpage

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#511]
The link for the solids email address is not working.  Can you please take and look and correct the link?  It takes you to a google page but doesn't open an email.

email address for Solids - onrrsolidmineralreferencedata@onrr.gov

Please correct on the below webpages:
https://www.onrr.gov/ReportPay/solids.htm
https://www.onrr.gov/ReportPay/Handbooks/index.htm
https://www.onrr.gov/ReportPay/solids-checklist.htm
[Solids email correction.pdf](https://github.com/ONRR/onrr.gov-site/files/5972597/Solids.email.correction.pdf)

**Comment by jennmalcolm** [comment]
@bowlenj we can't get these updates made right away because there are server issues. Once those are fixed, we'll get this done. Sorry for the delay!

**Comment by bowlenj** [comment]
Hi Jennifer,

Thank you for letting me know, I'll let the group know that there will be a delay due to systems issues.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
Jessica.Bowlen@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

**Comment by jennmalcolm** [comment]
@bowlenj these changes are ready for your review in dev. I changed the links so they should open up your default email program. I also spelled out the full emails as requested.
http://2017onrr/ReportPay/solids.htm
http://2017onrr/ReportPay/Handbooks/index.htm
http://2017onrr/ReportPay/solids-checklist.htm

**Comment by bowlenj** [comment]
These look great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
Jessica.Bowlen@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

**Comment by jennmalcolm** [comment]
The updates are live.
