### ISSUE TITLE
Please update the RIN 1012-AA27 webpage (https://www.onrr.gov/Laws_R_D/FRNotices/AA27.htm)

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#512]
Hello,

Please update the RIN 1012-AA27 webpage (https://www.onrr.gov/Laws_R_D/FRNotices/AA27.htm) as follows:

At the bottom of the webpage, after "To view the final rule: https://www.federalregister.gov/documents/2021/01/15/2021-00217/onrr-2020-valuation-reform-and-civil-penalty-rule", please add another bullet point to say the following:

"To view the delay of effective date rule and submit public comments: [https://www.federalregister.gov/documents/2021/02/12/2021-03052/onrr-2020-valuation-reform-and-civil-penalty-rule-delay-of-effective-date-request-for-public-comment](url)  The new effective date is April 16, 2021. The public comment period ends March 15, 2021."

Please let me know if you have any questions.

Thanks for your help!
Christine

**Comment by cthomasONRR** [comment]
I will be out of the office all of next week (2/15 - 2/19).

Please contact Alexis Long (alexis.long@onrr.gov) to complete this request.

Thanks!
Christine

**Comment by lpgoldstein** [comment]
@cthomasONRR and @aklong09 this is ready for your review: http://2017onrr/Laws_R_D/FRNotices/AA27.htm

Thanks for always being so clear with your directions!

**Comment by cthomasONRR** [comment]
Hi @lpgoldstein,

After the new link, could you please add the following: "The new effective date is April 16, 2021. The public comment period ends March 15, 2021."

It should look like this image:
![image](https://user-images.githubusercontent.com/72526208/108001447-b9113180-6fa9-11eb-9d91-69775deba6ff.png)

Thanks,
Christine

**Comment by lpgoldstein** [comment]
@cthomasONRR @aklong09 Fixed! http://2017onrr/Laws_R_D/FRNotices/AA27.htm

**Comment by aklong09** [comment]
Thank you @lpgoldstein! This one is also approved to publish.

**Comment by lpgoldstein** [comment]
@aklong09 This is live too https://www.onrr.gov/Laws_R_D/FRNotices/AA27.htm
