### ISSUE TITLE
Please add a new hyperlink under the "ONRR Rulemakings" dropdown located here: https://www.onrr.gov/Laws_R_D/index.htm

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#514]
Hello,

Within the Rules and Regulations webpage (https://www.onrr.gov/Laws_R_D/index.htm), there is a drop-down tab entitled "ONRR Rulemakings"

Within this ONRR Rulemakings dropdown, please add a new hyperlink above the "AA27: ONRR 2020 Valuation Reform and Civil Penalty Rule" hyperlink.

Please title the hyperlink as "Inflation Adjustment to Civil Monetary Penalty Rates for Calendar Year 2021"

Within the "Inflation Adjustment to Civil Monetary Penalty Rates for Calendar Year 2021" hyperlink, please include the following information. Please format this information in the same style as the https://www.onrr.gov/Laws_R_D/FRNotices/AA25.htm webpage.

"Regulation Identifier Number 1012-AA29

Inflation Adjustment to Civil Monetary Penalty Rates for Calendar Year 2021

30 CFR Part 1241

**Abstract:** The Office of Natural Resources Revenue is publishing this final rule to adjust our maximum civil monetary penalty rates for calendar year 2021 under the Federal Civil Penalties Inflation Adjustment Act of 1990, as amended by the Federal Civil Penalties Inflation Adjustment Act Improvements Act of 2015, and Office of Management and Budget guidance.

Final Rulemaking: 86 FR 7808 [https://www.federalregister.gov/documents/2021/02/02/2021-01502/inflation-adjustments-to-civil-monetary-penalty-rates-for-calendar-year-2021](url) (02/02/2021)"

Please let me know if you have any questions.

Thank you for your help!
Christine

**Comment by cthomasONRR** [comment]
I will be out of the office all of next week (2/15 - 2/19).

Please contact Alexis Long (alexis.long@onrr.gov) to complete this request.

Thanks!
Christine

**Comment by lpgoldstein** [comment]
@aklong09 This is ready for your review http://2017onrr/Laws_R_D/index.htm
http://2017onrr/Laws_R_D/FRNotices/AA29.htm

**Comment by aklong09** [comment]
@lpgoldstein both look great--approved to publish. Thank you!

**Comment by lpgoldstein** [comment]
@aklong09 This is live https://www.onrr.gov/Laws_R_D/index.htm
https://www.onrr.gov/Laws_R_D/FRNotices/AA29.htm

Make sure you clear your browsing history or open in another browser if you can't see the changes.
