### ISSUE TITLE
Please replace Enforcement presentations on ONRR.gov

### ISSUE THREAD

**Issue by schartoa** [ONRR/onrr.gov-site#517]
Hi - Enforcement would like to replace the Power Point files at https://www.onrr.gov/compliance/civil-penalties.htm under the "References" section.

Please use the file "Revised Feb 2021 - OE STRAC Presentation" to replace the hyperlinked file titled "ONRR Enforcement Updates".  Please move this hyperlink to the top and replace the date with (02/2021).

Please use the file "Revised Feb 2021 - RMMLF Oct 2018 Civil Penalty Presentation" to replace the hyperlinked file titled "Enforcement and Civil Penalties" and move to the bottom as the second file.  Please replace date with (02/2021).

Thank you!

Andrea Scharton
[Revised Feb 2021 - RMMLF Oct 2018 Civil Penalty Presentation.pptx](https://github.com/ONRR/onrr.gov-site/files/5991527/Revised.Feb.2021.-.RMMLF.Oct.2018.Civil.Penalty.Presentation.pptx)
[Revised Feb 2021 - OE STRAC Presentation.pptx](https://github.com/ONRR/onrr.gov-site/files/5991530/Revised.Feb.2021.-.OE.STRAC.Presentation.pptx)

**Comment by lpgoldstein** [comment]
@schartoa This is ready for your review: http://2017onrr/compliance/civil-penalties.htm

**Comment by schartoa** [comment]
Hi Lindsey,

The powerpoint file links do not work; when I click on the hyperlinks I receive a server error file error (404 - File not found).  Could this be because I made the PP files read only?  Thanks.

![image](https://user-images.githubusercontent.com/76186525/108519110-92dbe200-7286-11eb-8796-8f0790b28768.png)

**Comment by lpgoldstein** [comment]
@schartoa Let me look into it. I'm sure I did something wrong.

**Comment by lpgoldstein** [comment]
@schartoa I had them as pdfs instead of pptx - they should work now.

**Comment by schartoa** [comment]
Thanks, Lindsey!  Another question for you - when you click on the link, you must save the pptx file rather than just view it.  Is there any way around this or must the file first be saved?

Andrea Scharton
Program Analyst, Enforcement and Litigation Support
Office of Natural Resources Revenue
6th Avenue and Kipling Street, Bldg 85
Denver, CO 80225
303.231.3046

**Comment by lpgoldstein** [comment]
@schartoa This is a setting you can change in your browser I think. There is a way to get the file to open as a preview but I don't know how to do it. I just download the file.

**Comment by schartoa** [comment]
Thank you for all of your help.  Let's go ahead and publish these to ensure that we meet Phase 2 of the 508 Compliance deadline.  I will work to make these compliant in Adobe in the near future.  Thank you again!

**Comment by lpgoldstein** [comment]
@schartoa this is live! The powerpoint version is fine to use on the site - you don't have to change to a pdf.

**Comment by schartoa** [comment]
Thank you very much for your help!

Andrea Scharton
Program Analyst, Enforcement and Litigation Support
Office of Natural Resources Revenue
6th Avenue and Kipling Street, Bldg 85
Denver, CO 80225
303.231.3046
