### ISSUE TITLE
Update onrr.gov NYMEX prices

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#52]
Please update the NYMEX prices on the onrr.gov website (home page>valuation>NYMEX Oil Prices).

[NYMEX0220.xlsx](https://github.com/ONRR/onrr.gov-site/files/4294168/NYMEX0220.xlsx)

**Comment by jennmalcolm** [comment]
Thanks @boices, the dev site is ready for your review: http://2017onrr/Valuation/NYMEX.htm.

Please confirm here if it looks good to publish.

**Comment by boices** [comment]
That looks great--thanks!

**Comment by jennmalcolm** [comment]
The prices are live on the site now.
