### ISSUE TITLE
Please replace 

### ISSUE THREAD

**Issue by schartoa** [ONRR/onrr.gov-site#521]
Hello,

Please update https://www.onrr.gov/compliance/civil-penalties.htm by replacing the current documents, found under "Penalty Collections by Fiscal Year", with the attached PDFs.  (We have decided to only go back five fiscal years and include a historical "totals" document - Penalty Collections.  Please delete the files 2007-2015 from the page).

Please also update the last sentence of the first paragraph to read: "ONRR has collected more than $60 million in civil penalties since its inception in 1982."

(I have also added the company names to the keyword metadata in the FY16-FY20 files to try to improve search functionality.)

Thank you for your help!
Andrea

[FY16 Penalty Collections.pdf](https://github.com/ONRR/onrr.gov-site/files/6013264/FY16.Penalty.Collections.pdf)
[FY17 Penalty Collections.pdf](https://github.com/ONRR/onrr.gov-site/files/6013265/FY17.Penalty.Collections.pdf)
[FY18 Penalty Collections.pdf](https://github.com/ONRR/onrr.gov-site/files/6013266/FY18.Penalty.Collections.pdf)
[FY19 Penalty Collections.pdf](https://github.com/ONRR/onrr.gov-site/files/6013267/FY19.Penalty.Collections.pdf)
[FY20 Penalty Collections.pdf](https://github.com/ONRR/onrr.gov-site/files/6013268/FY20.Penalty.Collections.pdf)
[Penalty Collections.pdf](https://github.com/ONRR/onrr.gov-site/files/6013270/Penalty.Collections.pdf)

**Comment by lpgoldstein** [comment]
@schartoa This is ready for your review http://2017onrr/compliance/civil-penalties.htm

**Comment by lpgoldstein** [comment]
@schartoa This is live
