### ISSUE TITLE
RRM Offshore Production Contact List

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#526]
Please replace the existing Offshore Production Reporting with the attached pdf at the below location:
https://www.onrr.gov/about/contact.htm
[RRM Offshore Production Contacts.pdf](https://github.com/ONRR/onrr.gov-site/files/6045824/RRM.Offshore.Production.Contacts.pdf)

**Comment by lpgoldstein** [comment]
@bowlenj Will you please send a current link to the file that you would like to have replaced?

**Comment by lpgoldstein** [comment]
@bowlenj Sorry I was a little confused because this file has been converted to excel. Can I ask why you want to convert it back to pdf? Is more than one person/team responsible for this document? Also in case you weren't aware - our user research has shown that our users prefer the excel format because they can search more easily for what they need.

**Comment by bowlenj** [comment]
Most of our documents we've put out as excel but for contact lists we were asked to make them a pdf.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
Jessica.Bowlen@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

**Comment by lpgoldstein** [comment]
@bowlenj This is ready for your review: http://2017onrr/reportpay/index.htm
http://2017onrr/reportpay/contacts.htm

**Comment by mcharg** [comment]
@lpgoldstein Is the offshore doc supposed to be there for the PASR?  There's different contact info on the live site.

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/8de912ba-7a65-4346-a886-6d48fd273c6f)

**Comment by mcharg** [comment]
@bowlenj I'm assuming the xls files need to change back to pdf on the main Contact Us page, as well, correct?
http://2017onrr/About/contact.htm

**Comment by bowlenj** [comment]
Yes, we would like to remove the excel and replace with the updated PDF.  We're only doing this for contact lists, the other reports will be excels.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
Jessica.Bowlen@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

**Comment by bowlenj** [comment]
This one is still the old list also, we need this updated to the Onshore Production Contact List https://www.onrr.gov/ReportPay/PDFDocs/Onshore-Production-Reporting-Contacts.pdf

We want Stacey's name removed and the link to the new Offshore Production Contact list.


Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
Jessica.Bowlen@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

**Comment by lpgoldstein** [comment]
@bowlenj All changes are live. Please clear your cache or check on a different browser if you  don't see them.
