### ISSUE TITLE
Replace onshore production reporting contacts pdf with xls file in additional locations

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#527]
It was updated on the main Contact Us page, but not on these pages.

https://www.onrr.gov/reportpay/index.htm (in the reporter tools in the right column)
https://www.onrr.gov/ReportPay/contacts.htm

**Comment by lpgoldstein** [comment]
@mcharg ready for your review http://2017onrr/reportpay/contacts.htm
http://2017onrr/reportpay/index.htm

**Comment by mcharg** [comment]
@lpgoldstein I'm getting a 404 saying the file isn't found.  Looks like the file name has periods instead of the dashes in the url it's trying to find.
![image](https://user-images.githubusercontent.com/38465926/109509304-bebd4b80-7a6e-11eb-803a-248b23ae6e8d.png)

**Comment by bowlenj** [comment]
Please replace existing excel contact list for Onshore Production at https://www.onrr.gov/about/contact.htm with the attached pdf.
[RRM Onshore Production Contacts.pdf](https://github.com/ONRR/onrr.gov-site/files/6062534/RRM.Onshore.Production.Contacts.pdf)

**Comment by lpgoldstein** [comment]
@bowlenj This is ready for your review: http://2017onrr/reportpay/index.htm
http://2017onrr/reportpay/contacts.htm

**Comment by bowlenj** [comment]
These look good, can we update the Contact Us page at https://www.onrr.gov/about/contact.htm also?
Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
Jessica.Bowlen@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

**Comment by lpgoldstein** [comment]
@bowlenj Ready for your review: http://2017onrr/About/contact.htm

**Comment by bowlenj** [comment]
The Onshore and Offshore are still xcel files, we want them to be the new PDFs.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
Jessica.Bowlen@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

**Comment by bowlenj** [comment]
[cid:image001.png@01D70F4C.C54F7910]

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
Jessica.Bowlen@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.
