### ISSUE TITLE
Webpage Update Indian Fund Code

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#528]
Please update the following webpage http://onrr.gov/ReportPay/payments.htm with the attached files.
Indian Leases Cross-walked to Distributee Codes
Downloadable Excel Version Indian Leases Cross-walked to Distributee codes

Also change updated date to read 02/25/2021 for both files.
Thank you
[FCIL.pdf](https://github.com/ONRR/onrr.gov-site/files/6045883/FCIL.pdf)
[FCIL.xlsx](https://github.com/ONRR/onrr.gov-site/files/6045886/FCIL.xlsx)

**Comment by lpgoldstein** [comment]
@merrellc This is ready for your review: http://2017onrr/ReportPay/payments.htm

**Comment by merrellc** [comment]
Looks Great! 🙂


Thank you
​Candace Merrell
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
Candace.Merrell@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________

**Comment by lpgoldstein** [comment]
@merrellc This is live! I had to check in another browser to see it in case you can't see it either https://www.onrr.gov/ReportPay/payments.htm

**Comment by merrellc** [comment]
I clicked on link and I am not seeing the update date changed like in the previous email link.


Thank you
​Candace Merrell
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
Candace.Merrell@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________
