### ISSUE TITLE
Redirect 4444 form and instructions to ONRR4444 form and instructions

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#529]
After we do this, we can remove the duplicate form and instructions.

Redirect: https://www.onrr.gov/reportpay/PDFDocs/4444.pdf
To: https://www.onrr.gov/reportpay/PDFDocs/ONRR4444.pdf

Recirect: https://www.onrr.gov/reportpay/PDFDocs/4444_Instructions.pdf
To: https://www.onrr.gov/reportpay/PDFDocs/ONRR4444_Instructions.pdf

**Comment by mcharg** [comment]
This is updated in dev. @Maroyafaied Can you review?
http://2017onrr/reportpay/PDFDocs/4444.pdf
http://2017onrr/reportpay/PDFDocs/4444_Instructions.pdf

**Comment by Maroyafaied** [comment]
@mcharg looks good.
