### ISSUE TITLE
Update Indian Gas Index Zone prices

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#53]
Please update the ONRR.gov Valuation - Indian Gas Index Zone prices webpage with the new March prices.  
The prices are located in the "Data for ONRR.gov" spreadsheet that is located on the OneDrive. The prices will be in the 'Index-Zones' tab.  Here is a link...I hope it works. If not we may have to have Robert add you to the list.
https://doimspp-my.sharepoint.com/:x:/r/personal/sudarr_mms_gov/Documents/Data%20for%20ONRR.gov.xlsx?d=w610913f6cc4442228521fad9ea5feb0e&csf=1&e=NOUx7w

Please let me know when the prices are ready for review before they go live.
Thanks,
Cory Forgrave

**Comment by jennmalcolm** [comment]
@lpgoldstein I requested access to the prices because I don't have it. You should do the same. Let me know if you want to work know if you want to work on this issue together.

**Comment by jboroos** [comment]
> 
> 
> @lpgoldstein I requested access to the prices because I don't have it. You should do the same. Let me know if you want to work know if you want to work on this issue together.

Hi guys, I shared the sheet with you in oneDrive but I think Robert is the official owner.  Hopefully the link I sent works for you but let me know if you still don't have access to it.  - Jason

**Comment by lpgoldstein** [comment]
@jboroos I have access to the sheet. Thanks!

**Comment by lpgoldstein** [comment]
@jboroos and @forgravec please check and let me know if this looks correct http://2017onrr//Valuation/allzones.htm

**Comment by forgravec** [comment]
@lpgoldstein Prices look good...Thanks.
