### ISSUE TITLE
Deduplicate reporter letter links

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#530]
We have two urls that link to the same reporter letter.  We need to decide which is current and link them all to the same place and redirect whichever we get rid of to the one we're keeping.

https://www.onrr.gov/PDFDocs/20141218.pdf (Phase 1, not yet accessible, rank 72)
https://www.onrr.gov/ReportPay/PDFDocs/20141218.pdf (Phase 3, made accessible by program, rank 418)

Where it's linked:

Page: https://www.onrr.gov/ReportPay/handbooks/indian-payor-handbook-chapter-2.htm (Section 2.4.5)
url: https://www.onrr.gov/ReportPay/PDFDocs/20141218.pdf

Page: https://www.onrr.gov/DearRep.htm
url: https://www.onrr.gov/PDFDocs/20141218.pdf

Page: https://www.onrr.gov/unbundling/methodology.htm
url: https://www.onrr.gov/PDFDocs/20141218.pdf

**Comment by lpgoldstein** [comment]
@mcharg The one in the main pdf folder is the accessible one. I'm going to get rid of the other one and relink to the accessible one. It must just have been mismarked in the spreadsheet.

**Comment by lpgoldstein** [comment]
@mcharg This is ready for your review: http://2017onrr/ReportPay/Handbooks/indian-payor-handbook-chapter-2.htm#24

**Comment by mcharg** [comment]
@lpgoldstein Looks good.
