### ISSUE TITLE
Update offshore reporting contacts links

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#531]
Links on these pages link to pdf and should link to excel.
Correct link: https://www.onrr.gov/ReportPay/PDFDocs/Offshore-Production-Reporting-Contacts.xlsx

Production Reporting Contacts: https://www.onrr.gov/ReportPay/contacts.htm
Reporter tools (in right column): https://www.onrr.gov/reportpay/index.htm

**Comment by lpgoldstein** [comment]
@mcharg This is ready for your review http://2017onrr/reportpay/index.htm
http://2017onrr/reportpay/contacts.htm

**Comment by mcharg** [comment]
@lpgoldstein Looks good on reporter tools.

On Production Contacts, not sure why it's showing up a second time under PASR.

Dev:
![image](https://user-images.githubusercontent.com/38465926/109510216-bca7bc80-7a6f-11eb-8d73-b138b9ca23cd.png)

Live site:
![image](https://user-images.githubusercontent.com/38465926/109510248-c7fae800-7a6f-11eb-9fce-f906cc615f4a.png)

**Comment by lpgoldstein** [comment]
@mcharg I was just asked to change it to the contact list instead of the single name. It's correct.
