### ISSUE TITLE
Update link to FR43338 to link to Federal Register

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#532]
We updated it in one location, but not the other.

Page: https://www.onrr.gov/Laws_R_D/FRNotices/index.htm (July 1, 2016)
Correct link: https://www.federalregister.gov/documents/2016/07/01/2016-15420/consolidated-federal-oil-and-gas-and-federal-and-indian-coal-valuation-reform

**Comment by lpgoldstein** [comment]
http://2017onrr/Laws_R_D/FRNotices/index.htm @mcharg ready for review

**Comment by mcharg** [comment]
@lpgoldstein Looks good.
