### ISSUE TITLE
Update link to FR24794 to federal register

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#533]
We updated it in one location, but not the other.

Page: https://www.onrr.gov/Laws_R_D/FRNotices/index.htm (May 1, 2015)
Correct link: https://www.federalregister.gov/documents/2015/05/01/2015-09955/indian-oil-valuation-amendments

**Comment by lpgoldstein** [comment]
@mcharg ready for review: http://2017onrr/Laws_R_D/FRNotices/index.htm

**Comment by mcharg** [comment]
@lpgoldstein Looks good.
