### ISSUE TITLE
508 Compliance Project

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#537]
Please load Chapter 4 Transaction codes to the ONRR Website at the below location.

https://www.onrr.gov/ReportPay/Handbooks/revenue-handbook/pdfs/RRM-Chapter.4.pdf

Thank you
Candace
[RRM-Chapter.4.pdf](https://github.com/ONRR/onrr.gov-site/files/6052278/RRM-Chapter.4.pdf)

--

**Comment by merrellc** [comment]
Please add the attached file to the below location:
https://www.onrr.gov/ReportPay/Handbooks/revenue-handbook/pdfs/RRM-Appendix.C.pdf
Thank you
[RRM-Appendix.C (1).pdf](https://github.com/ONRR/onrr.gov-site/files/6052490/RRM-Appendix.C.1.pdf)

--

**Comment by lpgoldstein** [comment]
[RRM-Chapter.4.pdf.accreport.pdf](https://github.com/ONRR/onrr.gov-site/files/6055157/RRM-Chapter.4.pdf.accreport.pdf)
@merrellc  The second document looks good but the first one has some issues. See attached report.

**Comment by merrellc** [comment]
The attached accessibility report is showing zero failed issues.


Thank you
​Candace Merrell
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
Candace.Merrell@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________

**Comment by lpgoldstein** [comment]
@merrellc ready for your review: http://2017onrr/ReportPay/Handbooks/revenue-handbook/index.htm

**Comment by merrellc** [comment]
Looks great.


Thank you
​Candace Merrell
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
Candace.Merrell@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________

**Comment by lpgoldstein** [comment]
@merrellc It should be live.
