### ISSUE TITLE
Testing email notifications

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#54]
@jennmalcolm test email replies

**Comment by jennmalcolm** [comment]
@mentastc test

**Comment by mentastc** [comment]
yes

Chris Mentasti

Data Display
Office of Natural Resources Revenue
Chris.Mentasti@onrr.gov<mailto:Chris.Mentasti@onrr.gov> | (202) 809-5513

**Comment by jennmalcolm** [comment]
Thanks.
