### ISSUE TITLE
Update to ONRR.gov Civil Penalties page

### ISSUE THREAD

**Issue by schartoa** [ONRR/onrr.gov-site#540]
Good afternoon!

Some of our collection data changed in the last week, so I would like to request that the following PDFs be replaced on https://www.onrr.gov/compliance/civil-penalties.htm  Thank you for your help!

[Penalty Collections.pdf](https://github.com/ONRR/onrr.gov-site/files/6052332/Penalty.Collections.pdf)
[FY16 Penalty Collections.pdf](https://github.com/ONRR/onrr.gov-site/files/6052336/FY16.Penalty.Collections.pdf)
[FY17 Penalty Collections.pdf](https://github.com/ONRR/onrr.gov-site/files/6052339/FY17.Penalty.Collections.pdf)
[FY19 Penalty Collections.pdf](https://github.com/ONRR/onrr.gov-site/files/6052371/FY19.Penalty.Collections.pdf)
[FY20 Penalty Collections.pdf](https://github.com/ONRR/onrr.gov-site/files/6052372/FY20.Penalty.Collections.pdf)

**Comment by lpgoldstein** [comment]
@schartoa This is ready for your review: http://2017onrr/compliance/civil-penalties.htm

**Comment by schartoa** [comment]
This looks great and is ready to go live.  Thank you, Lindsay!

Andrea Scharton
Program Analyst, Enforcement and Litigation Support
Office of Natural Resources Revenue
6th Avenue and Kipling Street, Bldg 85
Denver, CO 80225
303.231.3046

**Comment by lpgoldstein** [comment]
@schartoa This should be live. Please clear your cache if you are checking in Chrome and let me know if it doesn't show up in the next hour or so.

**Comment by schartoa** [comment]
Looks great!! Thank you very much, Lindsay!

Andrea Scharton
Program Analyst, Enforcement and Litigation Support
Office of Natural Resources Revenue
6th Avenue and Kipling Street, Bldg 85
Denver, CO 80225
303.231.3046
