### ISSUE TITLE
Request from Kimbra

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#544]
change the statement at the bottom of this page:  https://www.onrr.gov/About/index.htm  where is says we are headquartered in Washington DC to say we are headquartered in Denver?

Thank you.

**Comment by mcharg** [comment]
@Maroyafaied Updated in dev.  Let me know if it's good to push to production.
http://2017onrr/About/index.htm

**Comment by Maroyafaied** [comment]
looks good

**Comment by mcharg** [comment]
Change is now live.
https://www.onrr.gov/About/index.htm

**Comment by Maroyafaied** [comment]
@mcharg she would like us to mention that we have an office in DC

**Comment by mcharg** [comment]
@Maroyafaied Updated in dev.  Let me know if it's good to push live.
http://2017onrr/About/index.htm

**Comment by Maroyafaied** [comment]
@mcharg you can push live.

**Comment by mcharg** [comment]
@Maroyafaied Changes are live.
https://www.onrr.gov/About/index.htm
