### ISSUE TITLE
Update Production Reporting References 

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/onrr.gov-site#546]
Request received through email box. will update here. 
[Gulf-Metering-Systems.xlsx](https://github.com/ONRR/onrr.gov-site/files/6070956/Gulf-Metering-Systems.xlsx)
[Alaska-Metering-Systems.xlsx](https://github.com/ONRR/onrr.gov-site/files/6070957/Alaska-Metering-Systems.xlsx)
[Gulf-Sales-Tanks.xlsx](https://github.com/ONRR/onrr.gov-site/files/6070958/Gulf-Sales-Tanks.xlsx)
[Gulf-Buy-Back.xlsx](https://github.com/ONRR/onrr.gov-site/files/6070959/Gulf-Buy-Back.xlsx)
[Gulf-Flash-Gas.xlsx](https://github.com/ONRR/onrr.gov-site/files/6070960/Gulf-Flash-Gas.xlsx)
[Gulf-Gas-Plants.xlsx](https://github.com/ONRR/onrr.gov-site/files/6070961/Gulf-Gas-Plants.xlsx)

**Comment by lpgoldstein** [comment]
http://2017onrr/reportpay/references.htm

**Comment by ONRR-31577** [comment]
Everything looks good Lindsay, thank you!

**Comment by lpgoldstein** [comment]
This is live https://www.onrr.gov/reportpay/references.htm
