### ISSUE TITLE
Request to Update ONRR Rules & Regulations and FRN Webpages

### ISSUE THREAD

**Issue by aklong09** [ONRR/onrr.gov-site#549]
Hello,

ONRR’s Regulations Team respectfully requests updates to the Federal Register Notices and Rules & Regulations pages. To ensure consistency with the 508 compliance requirements, please remove the PDFs for the following Federal Register documents and replace them with the hyperlinks provided, as described further below:

•	The first update is located at https://www.onrr.gov/Laws_R_D/FRNotices/index.htm under the year 2011 and the entry is dated June 28, 2011. Please replace the PDF linked to this entry (currently https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/37828.pdf) and replace it with the following hyperlink labeled as “View FR Document” -- https://www.federalregister.gov/documents/2011/06/28/2011-16125/update-to-indian-index-zone-price-points 

•	The second update is located at https://www.onrr.gov/Laws_R_D/FRNotices/AD05.htm. Please remove the PDF linked to “Final Rule — (70 FR 11869--March 10, 2005)” (currently https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/11869.pdf) and replace it with following hyperlink -- https://www.federalregister.gov/documents/2005/03/10/05-4515/federal-gas-valuation 

Please let me know if you have any questions.

Thanks in advance, 
Alexis

**Comment by lpgoldstein** [comment]
@aklong09 This is ready for your review: http://2017onrr/Laws_R_D/FRNotices/index.htm
http://2017onrr/Laws_R_D/FRNotices/AD05.htm

**Comment by aklong09** [comment]
@lpgoldstein Thank you, these look great! Approved to publish.

**Comment by lpgoldstein** [comment]
@aklong09 This is live https://www.onrr.gov/Laws_R_D/FRNotices/AD05.htm
https://www.onrr.gov/Laws_R_D/FRNotices/index.htm
