### ISSUE TITLE
Request to Update ONRR's Public Laws Page

### ISSUE THREAD

**Issue by aklong09** [ONRR/onrr.gov-site#551]
Hello,

Please update the ONRR Public Laws webpage, located at https://www.onrr.gov/Laws_R_D/PubLaws/index.htm. 

Please remove the PDF linked to the Federal Oil & Gas Royalty Management Act of 1982 and replace it with the following hyperlink:  https://uscode.house.gov/view.xhtml?path=/prelim@title30/chapter29&edition=prelim 

Thanks in advance,
Alexis

**Comment by lpgoldstein** [comment]
@aklong09 This is ready for your review: http://2017onrr/Laws_R_D/PubLaws/index.htm

**Comment by aklong09** [comment]
@lpgoldstein Looks great! Thanks so much for this. Approved to publish.

**Comment by lpgoldstein** [comment]
@aklong09 This is live https://www.onrr.gov/Laws_R_D/PubLaws/index.htm
