### ISSUE TITLE
Data Warehouse Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#552]
Please update ONRR Data Warehouse Portal to ONRR WebCenter Portal in the locations identified on the attached document.

ONRR WebCenter Portal link is portal.onrr.gov
[WebCenter Portal Update.docx](https://github.com/ONRR/onrr.gov-site/files/6078554/WebCenter.Portal.Update.docx)

**Comment by lpgoldstein** [comment]
Please remove old link for ONRR Data Warehouse Portal to – ONRR WebCenter Portal and add new link portal.onrr.gov in the below locations:
https://www.onrr.gov/
Please update to show ONRR WebCenter Portal and update link to go to portal.onrr.gov:
 
Please update the below link for ONRR Data Warehouse Portal to – ONRR WebCenter Portal
https://www.onrr.gov/reportpay/prod-checklist.htm
 
 
https://www.onrr.gov/ReportPay/:
Please update to say ONRR WebCenter (eCommerce) Portal and provide correct link to portal.onrr.gov
 
https://www.onrr.gov/reportpay/forms/index.htm
Please update to say ONRR WebCenter Portal and provide link.
 
https://www.onrr.gov/ReportPay/payments.htm
Please rename to ONRR WebCenter Portal and provide correct link
 
https://www.onrr.gov/ReportPay/solids.htm
Update to read ONRR WebCenter Portal and provide correct link:
 
https://www.onrr.gov/ReportPay/royalty-reporting.htm
Update to say ONRR WebCenter Portal and provide link
 
https://www.onrr.gov/ReportPay/roy-checklist.htm
Correct to read ONRR WebCenter Portal  
https://www.onrr.gov/ReportPay/reporter-maintenance.htm
Change to read ONRR WebCenter Portal and provide link where it was previously

**Comment by lpgoldstein** [comment]
@bowlenj This is ready for your review: http://2017onrr/ 
You should be able to access all of the preview links through the homepage to see the changes.

**Comment by bowlenj** [comment]
This looks good, I just have a few spots where it still shows Data Warehouse instead of WebCenter Portal.  I've added screenshots below:

http://2017onrr/reportpay/production-reporting.htm
[cid:image001.png@01D710EF.842DA110]
http://2017onrr/reportpay/prod-checklist.htm

[cid:image002.png@01D710EF.842DA110] ONRR WebCenter Portal
http://2017onrr/reportpay/roy-checklist.htm

[cid:image003.png@01D710EF.842DA110] ONRR WebCenter Portal

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
Jessica.Bowlen@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

**Comment by lpgoldstein** [comment]
@bowlenj I updated everything I found in those files. Hopefully it shows up now.

**Comment by bowlenj** [comment]
Can you check the headers at the below and change the working from Data Warehouse to WebCenter Portal.  I think all the links have been updated.

http://2017onrr/reportpay/prod-checklist.htm

[cid:image001.png@01D710FA.A2259780]ONRR WebCenter Portal
http://2017onrr/reportpay/roy-checklist.htm

[cid:image002.png@01D710FA.A2259780]ONRR WebCenter Portal

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
Jessica.Bowlen@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

**Comment by lpgoldstein** [comment]
@bowlenj I can't see your screenshots. Want to drop them into chat or email?
