### ISSUE TITLE
Webpage -Cross Reference Lease to Agreement

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#555]
Please update the following webpage http://www.onrr.gov/reportPay/CrossRef.htm

Cross Reference Lease to Agreement Numbers sorted by AgreementNumber
Cross Reference Lease to Agreement Numbers sorted by LeaseNumber
Update to read 03/01/2021

Thank you

[sorted by agreement number.xlsx](https://github.com/ONRR/onrr.gov-site/files/6079759/sorted.by.agreement.number.xlsx)
[sorted by Lease number.xlsx](https://github.com/ONRR/onrr.gov-site/files/6079762/sorted.by.Lease.number.xlsx)

**Comment by lpgoldstein** [comment]
@merrellc This is ready for your review: http://2017onrr/ReportPay/CrossRef.htm

I went ahead and updated the dates for all three files and will load the third file as soon as I get it.

**Comment by merrellc** [comment]
The sorted by Lease number "updated" is in there twice. Other than that, it is ready to go.


Thank you
​Candace Merrell
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
Candace.Merrell@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________

**Comment by lpgoldstein** [comment]
@merrellc These are live now https://www.onrr.gov/ReportPay/CrossRef.htm

**Comment by merrellc** [comment]
Thanks for all your help!


Thank you
​Candace Merrell
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
Candace.Merrell@onrr.gov

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________
