### ISSUE TITLE
ONRR.gov Indian Index Zone Price update - March

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#556]
The Indian Index Zone prices for March are ready to be updated.  The prices are in the "Data for ONRR.gov" spreadsheet on the OneDrive.

Thanks,
Cory Forgrave
@sudarr

**Comment by lpgoldstein** [comment]
@forgravec This is ready for your review: http://2017onrr/Valuation/allzones.htm

**Comment by forgravec** [comment]
Prices look good...thanks!

Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
cory.forgrave@onrr.gov

________________________________

**Comment by lpgoldstein** [comment]
@forgravec This is live https://www.onrr.gov/Valuation/allzones.htm
