### ISSUE TITLE
Add February NYMEX prices to ONRR.gov

### ISSUE THREAD

**Issue by penvosej** [ONRR/onrr.gov-site#557]
The February 
[NYMEX022021.xlsx](https://github.com/ONRR/onrr.gov-site/files/6085853/NYMEX022021.xlsx)
NYMEX prices are ready to be posted to ONRR.gov. I've attached the file with the data. Thank you!
@sudarr

**Comment by lpgoldstein** [comment]
@penvosej Ready for review: http://2017onrr/Valuation/NYMEX.htm

**Comment by penvosej** [comment]
The webpage looks good!

**Comment by lpgoldstein** [comment]
@penvosej it's live!

**Comment by penvosej** [comment]
Thanks, Lindsay!
