### ISSUE TITLE
Corrected document from Lee Ann Martin group

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#560]
Please upload this corrected document after checking it for accessibility errors. Thanks
[CMP2014Form_Industry_FAQ.pdf](https://github.com/ONRR/onrr.gov-site/files/6091813/CMP2014Form_Industry_FAQ.pdf)

**Comment by Maroyafaied** [comment]
looks like it has accessibility errors, I'll ask the person that send it to correct them

**Comment by mcharg** [comment]
@Maroyafaied Is this the doc in #634?

**Comment by Maroyafaied** [comment]
@mcharg I don't believe it's the same document.

**Comment by mcharg** [comment]
@Maroyafaied I got this doc from Lori.  It's updated in dev on two pages.  Who needs to review?
http://2017onrr/reportpay/royalty-reporting.htm
http://2017onrr/reportpay/Handbooks/revenue-handbook/index.htm (on the supplemental information tab and in the TOC)

**Comment by Maroyafaied** [comment]
@mcharg I send an email to review the changes. Thanks

**Comment by Maroyafaied** [comment]
@mcharg review was verified by email, this is good to push live.  Please also note on the tracking sheet that this doc is accessible. Thanks

**Comment by mcharg** [comment]
Pushed live.
