### ISSUE TITLE
Request to Update ONRR's Rules and Regulations Page

### ISSUE THREAD

**Issue by aklong09** [ONRR/onrr.gov-site#563]
Hello,
Please update ONRR’s Rules and Regulations page, located at: https://www.onrr.gov/Laws_R_D/FRNotices/ICR0107.htm 

Under the “Federal Register Publications and Comments” heading, please add the following two bullet points at the top of the current list. The new bullet points should read as follows:

- “30-Day Agency Information Collection - (86 FR 13398 –March 8, 2021)” Please add the following hyperlink to the “(86 FR 13398 –March 8, 2021)” text: https://www.federalregister.gov/documents/2021/03/08/2021-04684/agency-information-collection-activities-collection-of-monies-due-to-the-federal-government-and 

- “60-Day Agency Information Collection - (85 FR 65395—October 15, 2020)” Please add the following hyperlink to the “(85 FR 65395—October 15, 2020)” text: https://www.federalregister.gov/documents/2020/10/15/2020-22773/agency-information-collection-activities-collection-of-monies-due-the-federal-government-and 

Please let me know if you have any questions.
Thanks in advance,
Alexis

**Comment by Maroyafaied** [comment]
@aklong09 please review the changes on the dev site. http://2017onrr/Laws_R_D/FRNotices/ICR0107.htm

**Comment by Maroyafaied** [comment]
This is live now. Thanks
