### ISSUE TITLE
Update links to 2016 rule with link to Federal Register

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#569]
We removed the pdf in one place, but not all places.

Correct link: https://www.federalregister.gov/documents/2016/07/01/2016-15420/consolidated-federal-oil-and-gas-and-federal-and-indian-coal-valuation-reform

Pages needing updating:
https://www.onrr.gov/ReportPay/policy.htm (right column eCFR update)

**Comment by mcharg** [comment]
This is updated in dev.  @Maroyafaied Can you review?
http://2017onrr/ReportPay/policy.htm

**Comment by Maroyafaied** [comment]
@mcharg looks good
