### ISSUE TITLE
Publish Outreach Video How does the Market affect my Royalties

### ISSUE THREAD

**Issue by Rebekah474** [ONRR/onrr.gov-site#570]
Please publish the latest ONRR Outreach video on ONRR.gov on the allottee assistance page on the right side under the event calendar.
Here is the announcement text for the front ONRR.gov page:
Our ONRR Outreach team has published the next video in their series answering frequently asked questions from Indian Mineral Owners. How does the Market affect my Royalties? The link is available in the Library on the Allottee Assistance page.
It can also be found on [Youtube](https://youtu.be/rgvGPGP1wE4),  [Facebook](https://youtu.be/rgvGPGP1wE4)

And is the video and text for the “Allottee Assistance” page:
[Youtube](https://youtu.be/rgvGPGP1wE4)
How does the Market affect my Royalties? – This video is about the impact various global and local factors have on oil and natural gas prices. Also, how those factors affect your royalties.

**Comment by Maroyafaied** [comment]
@Rebekah474 Where exactly would you like the video to be published in the Allottee Assistance page? I can put it under quick references? I know you made another issue to create a video library but we are very short staffed and this will take time, we are also working on redesigning the website so @mcharg  can incorporate a video library in the wireframes of the redesign.  Let me know where you'd the video to be placed in the page for now. Also, if I'm understanding correctly, you also want the video to be in the announcement section in the homepage ? Would you like me to replace this announcement currently on the homepage with the video? 
![image](https://user-images.githubusercontent.com/40175688/111335000-a554fb80-8639-11eb-91e4-1947f5287fa6.png)

**Comment by Rebekah474** [comment]
Hi,
I think I wanted the video a little higher than that. I've pasted a picture here.
Also I understand about the library. I knew the site was going through a redesign so yes incorporating it in the wireframe of the redesign is great.
No do not replace the announcement, just putting the video on our Allottee assistance page is fine.
Thank  you

***@***.***D71A50.E5546C20]

Rebekah Ingraham
Mineral Revenue Specialist
ONRR SIO
Oklahoma City
405-879-6037
800-354-7015
6:30-5:00 CT M-TH
Always help someone. You might be the only one who does. - Unknown
For Allottee Assistance go to:
https://www.onrr.gov/IndianServices/index.htm
To see ONRR's training videos, go to:
http://onrr.gov/ReportPay/training/default.htm<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fonrr.gov%2FReportPay%2Ftraining%2Fdefault.htm&data=04%7C01%7CRebekah.Ingraham%40onrr.gov%7Ca29245c053404365512b08d8c2539fbc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637473011765313008%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E142FCBxPg5gABpSs1evwGMqNwb74eYi%2FydxnFHgZkE%3D&reserved=0>
https://www.youtube.com/user/ONRRChannel<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fuser%2FONRRChannel&data=04%7C01%7CRebekah.Ingraham%40onrr.gov%7Ca29245c053404365512b08d8c2539fbc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637473011765322970%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Tn5sNbkUPpw1HNAEfqFHNm%2BCELA47cvwFxcq%2BJYIWns%3D&reserved=0>



From: Maroyafaied ***@***.***>
Sent: Tuesday, March 16, 2021 10:27 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Ingraham, Rebekah J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Publish Outreach Video How does the Market affect my Royalties (#570)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Rebekah474<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRebekah474&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7Cc73c95f1880f43d53b7608d8e88ff2ea%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637515052244791079%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=luzZEnpLL5mDgERB4IMGH%2F0kkUXK4u3rd33p%2BJtfnx4%3D&reserved=0> Where exactly would you like the video to be published in the Allottee Assistance page? I can put it under quick references? I know you made another issue to create a video library but we are very short staffed and this will take time, we are also working on redesigning the website so @mcharg<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmcharg&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7Cc73c95f1880f43d53b7608d8e88ff2ea%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637515052244791079%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tTyQUm228YPMe17ZYxudphBHHO%2Frp4NA%2BVItzHhuUUw%3D&reserved=0> can incorporate a video library in the wireframes of the redesign. Let me know where you'd the video to be placed in the page for now. Also, if I'm understanding correctly, you also want the video to be in the announcement section in the homepage ? Would you like me to replace this announcement currently on the homepage with the video?
[image]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F40175688%2F111335000-a554fb80-8639-11eb-91e4-1947f5287fa6.png&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7Cc73c95f1880f43d53b7608d8e88ff2ea%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637515052244801047%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ByxLCV3c143H4z8VjeQp1BvLMUxhoas3VCMn%2BE%2Fsub0%3D&reserved=0>

-

**Comment by Maroyafaied** [comment]
@Rebekah474 it looks like your photo didn't attach. You can send it to my email maroya.faied@onrr.gov Thanks

**Comment by Rebekah474** [comment]
***@***.***D71AF9.48DB27E0]

Here is the picture.
Thank you


Rebekah Ingraham
Mineral Revenue Specialist
ONRR SIO
Oklahoma City
405-879-6037
800-354-7015
6:30-5:00 CT M-TH
Always help someone. You might be the only one who does. - Unknown
For Allottee Assistance go to:
https://www.onrr.gov/IndianServices/index.htm
To see ONRR's training videos, go to:
http://onrr.gov/ReportPay/training/default.htm<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fonrr.gov%2FReportPay%2Ftraining%2Fdefault.htm&data=04%7C01%7CRebekah.Ingraham%40onrr.gov%7Ca29245c053404365512b08d8c2539fbc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637473011765313008%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E142FCBxPg5gABpSs1evwGMqNwb74eYi%2FydxnFHgZkE%3D&reserved=0>
https://www.youtube.com/user/ONRRChannel<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fuser%2FONRRChannel&data=04%7C01%7CRebekah.Ingraham%40onrr.gov%7Ca29245c053404365512b08d8c2539fbc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637473011765322970%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Tn5sNbkUPpw1HNAEfqFHNm%2BCELA47cvwFxcq%2BJYIWns%3D&reserved=0>



From: Maroyafaied ***@***.***>
Sent: Tuesday, March 16, 2021 11:33 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Ingraham, Rebekah J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Publish Outreach Video How does the Market affect my Royalties (#570)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Rebekah474<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRebekah474&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7C1893729706aa40a4b92d08d8e8992c81%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637515093625423862%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=NP9hi3k9KoGPDW%2FLmPM8eux1ZnLhP0wlNPZMImeqG2E%3D&reserved=0> it looks like your photo didn't attach. You can send it to my email ***@***.******@***.***> Thanks

-

**Comment by Maroyafaied** [comment]
@Rebekah474 I still can't see the picture, you can email it to me or to onrrweb@onrr.gov. Thanks

**Comment by Rebekah474** [comment]
Hi,
Instead of pasting it into the email I have tried sending it as an attachment
Hopefully this works

Rebekah Ingraham
Mineral Revenue Specialist
ONRR SIO
Oklahoma City
405-879-6037
800-354-7015
6:30-5:00 CT M-TH
Always help someone. You might be the only one who does. - Unknown
For Allottee Assistance go to:
https://www.onrr.gov/IndianServices/index.htm
To see ONRR's training videos, go to:
http://onrr.gov/ReportPay/training/default.htm<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fonrr.gov%2FReportPay%2Ftraining%2Fdefault.htm&data=04%7C01%7CRebekah.Ingraham%40onrr.gov%7Ca29245c053404365512b08d8c2539fbc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637473011765313008%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E142FCBxPg5gABpSs1evwGMqNwb74eYi%2FydxnFHgZkE%3D&reserved=0>
https://www.youtube.com/user/ONRRChannel<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fuser%2FONRRChannel&data=04%7C01%7CRebekah.Ingraham%40onrr.gov%7Ca29245c053404365512b08d8c2539fbc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637473011765322970%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Tn5sNbkUPpw1HNAEfqFHNm%2BCELA47cvwFxcq%2BJYIWns%3D&reserved=0>



From: Maroyafaied ***@***.***>
Sent: Wednesday, March 17, 2021 8:56 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Ingraham, Rebekah J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Publish Outreach Video How does the Market affect my Royalties (#570)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Rebekah474<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRebekah474&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7C13a7ca059a4447b3a44508d8e94c8f15%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637515862321604719%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OZqu3bYjgT%2BSLj106YvEUS5jaBMhlSdhhHNTn6hOz3c%3D&reserved=0> I still can't see the picture, you can email it to me or to ***@***.******@***.***>. Thanks

-

**Comment by Maroyafaied** [comment]
@Rebekah474 Please review the updated changes in the dev site, if everything looks correct then I will publish it. Thanks http://2017onrr/IndianServices/index.htm

**Comment by Rebekah474** [comment]
I think that is okay. I thought the video would actually be there, not a link.



Rebekah Ingraham

Mineral Revenue Specialist

ONRR SIO

Oklahoma City

405-879-6037



Nature, to be commanded, must be obeyed. - Francis Bacon

________________________________
From: Maroyafaied ***@***.***>
Sent: Wednesday, March 17, 2021 10:23 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Ingraham, Rebekah J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Publish Outreach Video How does the Market affect my Royalties (#570)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Rebekah474<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRebekah474&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7Cb0e0a7bf397f42bf5b8d08d8e959fa9c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637515919958269895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cQH8p074oI67RzAeHSTKLA7Bk7DL8r6Yngp57ekOu9o%3D&reserved=0> Please review the updated changes in the dev site, if everything looks correct then I will publish it. Thanks http://2017onrr/IndianServices/index.htm

**Comment by Maroyafaied** [comment]
@Rebekah474 I embedded the video instead of the link, is it ok to publish now? http://2017onrr/IndianServices/index.htm

**Comment by Rebekah474** [comment]
Yes, that looks perfect
thank you


Rebekah Ingraham

Mineral Revenue Specialist

ONRR SIO

Oklahoma City

405-879-6037



Nature, to be commanded, must be obeyed. - Francis Bacon

________________________________
From: Maroyafaied ***@***.***>
Sent: Wednesday, March 17, 2021 11:16 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Ingraham, Rebekah J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Publish Outreach Video How does the Market affect my Royalties (#570)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Rebekah474<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRebekah474&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7Ca649d8920d3c43892ecc08d8e960162b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637515946195997581%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=n%2But0qtvs0Tgji8TCsoZnNFgVn4hhJfxzTKN18jh%2F2c%3D&reserved=0> I embedded the video instead of the link, is it ok to publish now? http://2017onrr/IndianServices/index.htm

**Comment by Rebekah474** [comment]
Thank you

Rebekah Ingraham
Mineral Revenue Specialist
ONRR SIO
Oklahoma City
405-879-6037
800-354-7015
6:30-5:00 CT M-TH
Always help someone. You might be the only one who does. - Unknown
For Allottee Assistance go to:
https://www.onrr.gov/IndianServices/index.htm
To see ONRR's training videos, go to:
http://onrr.gov/ReportPay/training/default.htm<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fonrr.gov%2FReportPay%2Ftraining%2Fdefault.htm&data=04%7C01%7CRebekah.Ingraham%40onrr.gov%7Ca29245c053404365512b08d8c2539fbc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637473011765313008%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E142FCBxPg5gABpSs1evwGMqNwb74eYi%2FydxnFHgZkE%3D&reserved=0>
https://www.youtube.com/user/ONRRChannel<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fuser%2FONRRChannel&data=04%7C01%7CRebekah.Ingraham%40onrr.gov%7Ca29245c053404365512b08d8c2539fbc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637473011765322970%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Tn5sNbkUPpw1HNAEfqFHNm%2BCELA47cvwFxcq%2BJYIWns%3D&reserved=0>



From: Maroyafaied ***@***.***>
Sent: Wednesday, March 17, 2021 11:38 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Ingraham, Rebekah J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Publish Outreach Video How does the Market affect my Royalties (#570)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



This is live. I will close this issue. Thanks

-
