### ISSUE TITLE
Create Video Library for Outreach Videos

### ISSUE THREAD

**Issue by Rebekah474** [ONRR/onrr.gov-site#571]
Please build a library similar to our other ONRR video libraries, like the 2014 training videos library.
Please put the link to the library below the event calendar on the right and above the current video (if published) on the Allottee Assitance Page in the Indian Services Tab.
Right now we have two videos;
ONRR Indian Outreach Royalty [Help](https://www.youtube.com/watch?v=kyOZwxd9CSQ&list=PLHqjbxv3m6RyeSJz42qgr2bo0Mw9eTYWP&index=1)
How does the Market Affect [Royalties?](https://www.youtube.com/watch?v=rgvGPGP1wE4&list=PLHqjbxv3m6RyeSJz42qgr2bo0Mw9eTYWP&index=2)

**Comment by Maroyafaied** [comment]
@Rebekah474 this is the wireframe that @mcharg worked on with and reviewed with Amanda Garrison and other supervisors. We have included the videos in the Indian Resources tab, will that work to put the videos in this tab when we redesign the site? https://qmcq5k.axshare.com/#id=vqfjwr&p=indian_resources

**Comment by Rebekah474** [comment]
Yes, I think that will work as a place to store the videos


Rebekah Ingraham

Mineral Revenue Specialist

ONRR SIO

Oklahoma City

405-879-6037



Nature, to be commanded, must be obeyed. - Francis Bacon

________________________________
From: Maroyafaied ***@***.***>
Sent: Wednesday, March 17, 2021 10:32 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Ingraham, Rebekah J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Create Video Library for Outreach Videos (#571)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Rebekah474<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRebekah474&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7Cee9ec5a4494147f793d908d8e959e54c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637515919596705997%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZmMXZljT2UxdjYnuhPzscl%2BOOaPSrZUKGQiJec3G1AE%3D&reserved=0> this is the wireframe that @mcharg<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmcharg&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7Cee9ec5a4494147f793d908d8e959e54c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637515919596715953%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rNUCGLqBuU51yga0WP0RRSeGhWHHmq%2FodHZFM4yZpyY%3D&reserved=0> worked on with and reviewed with Amanda Garrison and other supervisors. We have included the videos in the Indian Resources tab, will that work to put the videos in this tab when we redesign the site? https://qmcq5k.axshare.com/#id=vqfjwr&p=indian_resources<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fqmcq5k.axshare.com%2F%23id%3Dvqfjwr%26p%3Dindian_resources&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7Cee9ec5a4494147f793d908d8e959e54c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637515919596715953%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ooLaRKsL0SX322PxAjvDcnxJ%2Fg2RH15RliTwJ2S5o6U%3D&reserved=0>

-

**Comment by Rebekah474** [comment]
Hi,
These are samples of what I thought the library would look like.
I only have 2 videos now, but I have a total of 14 to publish.
I was picturing a link to a video library and then another page to the video library.

Rebekah Ingraham
Mineral Revenue Specialist
ONRR SIO
Oklahoma City
405-879-6037
800-354-7015
6:30-5:00 CT M-TH
Always help someone. You might be the only one who does. - Unknown
For Allottee Assistance go to:
https://www.onrr.gov/IndianServices/index.htm
To see ONRR's training videos, go to:
http://onrr.gov/ReportPay/training/default.htm<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fonrr.gov%2FReportPay%2Ftraining%2Fdefault.htm&data=04%7C01%7CRebekah.Ingraham%40onrr.gov%7Ca29245c053404365512b08d8c2539fbc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637473011765313008%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E142FCBxPg5gABpSs1evwGMqNwb74eYi%2FydxnFHgZkE%3D&reserved=0>
https://www.youtube.com/user/ONRRChannel<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fuser%2FONRRChannel&data=04%7C01%7CRebekah.Ingraham%40onrr.gov%7Ca29245c053404365512b08d8c2539fbc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637473011765322970%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Tn5sNbkUPpw1HNAEfqFHNm%2BCELA47cvwFxcq%2BJYIWns%3D&reserved=0>

**Comment by Maroyafaied** [comment]
@mcharg I'm attaching the pic since it doesn't show on GitHub, can you incorporate this in the wireframe? 
![image](https://user-images.githubusercontent.com/40175688/111500968-28de1d80-870a-11eb-85d5-981fa231a2e2.png)

**Comment by Maroyafaied** [comment]
@Rebekah474 when do you plan to publish the 14 videos? The redesign of the website is going to take a while so if you need these videos to be published in the near future then please let us know the time frame so we can plan our work accordingly. Thanks

**Comment by Rebekah474** [comment]
It takes about 4-6 weeks to get each video approved. I have 2 done and published; the 3rd just started the approval process so it should be out in about mid-April. So, for the remaining 11 videos it will take about a year for all of them to be published.
I was hoping to get about 1 video published each month.
I hope that helps.


Rebekah Ingraham

Mineral Revenue Specialist

ONRR SIO

Oklahoma City

405-879-6037



Nature, to be commanded, must be obeyed. - Francis Bacon

________________________________
From: Maroyafaied ***@***.***>
Sent: Wednesday, March 17, 2021 11:30 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Ingraham, Rebekah J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Create Video Library for Outreach Videos (#571)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Rebekah474<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRebekah474&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7C0926b0a7aec74e8bf3af08d8e9620e8c%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637515954750401166%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=31yP1gOCjX9nTy5OAp6vUSVPIum4DEtqRXFuivU5ZN4%3D&reserved=0> when do you plan to publish the 14 videos? The redesign of the website is going to take a while so if you need these videos to be published in the near future then please let us know the time frame so we can plan our work accordingly. Thanks

**Comment by Rebekah474** [comment]
Hi,
I don't think that's the best place because the videos are directed to Indian Mineral Owners.
I looked at the site and I wonder if it would fit somewhere in the FAQ page since the videos are video answers to FAQs. I tried to attach a picture pointing out where I thought it might fit if that helps.


Rebekah Ingraham

Mineral Revenue Specialist

ONRR SIO

Oklahoma City

405-879-6037



Nature, to be commanded, must be obeyed. - Francis Bacon

________________________________
From: mcharg ***@***.***>
Sent: Wednesday, March 17, 2021 11:39 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Ingraham, Rebekah J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Create Video Library for Outreach Videos (#571)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



I already have a video library on the Training tab on the Indian References page. Will this work to add the rest of the videos to?

https://qmcq5k.axshare.com/#id=xj5291&p=indian_references<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fqmcq5k.axshare.com%2F%23id%3Dxj5291%26p%3Dindian_references&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7C6bbef3d9fb5247bdd3c508d8e963405a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637515959776950734%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Y1hPyt62TIgJ1i%2FqN77%2FPWFRlfhKJmacbyM9pWrVuEQ%3D&reserved=0>

**Comment by mcharg** [comment]
@Rebekah474 I'm not seeing a picture and we don't have an FAQ page on the new site.  Would it make sense to add tabs to this page and have one dedicated to the videos?

![image](https://user-images.githubusercontent.com/38465926/111505414-f985db80-871e-11eb-9a16-e4290e7c746b.png)

**Comment by mcharg** [comment]
@Rebekah474 How's this?

Prototype link: https://qmcq5k.axshare.com/#id=tzo87j&p=assistance
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/b65701d8-45e8-4a25-907c-a8fe244592fa)

**Comment by Rebekah474** [comment]
I like it except instead of Training Videos can you change the title of the tab to Owner Videos?
Other than that, it's perfect.
thank you


Rebekah Ingraham

Mineral Revenue Specialist

ONRR SIO

Oklahoma City

405-879-6037



Nature, to be commanded, must be obeyed. - Francis Bacon

________________________________
From: mcharg ***@***.***>
Sent: Monday, March 22, 2021 12:51 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Ingraham, Rebekah J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Create Video Library for Outreach Videos (#571)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Rebekah474<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRebekah474&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7C7f93b031d66e4e21345308d8ed5b3162%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637520323220982833%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jswEkUpdRxN7%2F6ypIrwewClk5rjz7AyvLU4tVAR69hI%3D&reserved=0> How's this?

Prototype link: https://qmcq5k.axshare.com/#id=tzo87j&p=assistance<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fqmcq5k.axshare.com%2F%23id%3Dtzo87j%26p%3Dassistance&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7C7f93b031d66e4e21345308d8ed5b3162%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637520323220982833%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6U0%2F1dsF9qgPFOrnZ%2FE6ibptZ8Xtmam8B2ct8G3B4rc%3D&reserved=0>
[image.png]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcamo.githubusercontent.com%2F16fe1b0ce54e2b96eec1575ea139e94f8959a1165594b52713750254ce4bb387%2F68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563353839666535653138303632303831326561323261612f62363537303164382d343565382d346132352d393037632d613866653234343539326661&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7C7f93b031d66e4e21345308d8ed5b3162%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637520323220992786%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=09bZ1jJbdrVpJBo7JsiIWj0shFX4UGGUa0GptYrAR9U%3D&reserved=0>

**Comment by mcharg** [comment]
@rebekah474 I made the text change.
https://qmcq5k.axshare.com/#id=tzo87j&p=assistance

**Comment by Rebekah474** [comment]
I love it,
thank you


Rebekah Ingraham

Mineral Revenue Specialist

ONRR SIO

Oklahoma City

405-879-6037



Nature, to be commanded, must be obeyed. - Francis Bacon

________________________________
From: mcharg ***@***.***>
Sent: Monday, March 22, 2021 1:20 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Ingraham, Rebekah J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Create Video Library for Outreach Videos (#571)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Rebekah474<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRebekah474&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7C5d5b8c39c60a4319015408d8ed5f476d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637520340772066033%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZNDdCQP6dk8hBnq%2FgaLexpnc%2BQJf6IhRIdPFq%2FyWX2o%3D&reserved=0> I made the text change.
https://qmcq5k.axshare.com/#id=tzo87j&p=assistance<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fqmcq5k.axshare.com%2F%23id%3Dtzo87j%26p%3Dassistance&data=04%7C01%7Crebekah.ingraham%40onrr.gov%7C5d5b8c39c60a4319015408d8ed5f476d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637520340772066033%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=L%2Bh1z4KyTOSf2HOMPYyztxTLjYfZpkrpJwN%2FjGl%2BrG8%3D&reserved=0>
