### ISSUE TITLE
Apply changes to 404 page

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#575]

**Comment by mcharg** [comment]
Design:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/72d70660-8685-4eb3-b46b-0a96a28c14b9)

**Comment by mcharg** [comment]
@Maroyafaied This is updated in dev.  Can you please review?  It's currently not redirecting to the 404 page on the live site, so we might need to do something to fix that.

http://2017onrr/404.htm

**Comment by Maroyafaied** [comment]
@mcharg it looks good, Jennifer redirected some links before so I'll look into how she did it.
