### ISSUE TITLE
update Indian Oil IBMP prices on onrr.gov

### ISSUE THREAD

**Issue by jboroos** [ONRR/onrr.gov-site#58]
Good afternoon, can you please update the Indian Oil IBMP price page (https://www.onrr.gov/Valuation/IndianOilIBMP.htm).  These prices are in the IBMP tab of the "Data for ONRR.gov" spreadsheet on OneDrive located at - https://doimspp-my.sharepoint.com/:x:/r/personal/sudarr_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B610913F6-CC44-4222-8521-FAD9EA5FEB0E%7D&file=Data%20for%20ONRR.gov.xlsx&action=default&mobileredirect=true

Let me know if the link to the excel sheet doesn't work for you.  Can you please post these updates first to our development site (http://2017onrr/Valuation/IndianOilIBMP.htm) and @sudarr and I'll review before we make them public?  

Thanks!

**Comment by lpgoldstein** [comment]
@jboroos and @sudarr please review and let us know if this looks okay: http://2017onrr/Valuation/IndianOilIBMP.htm

**Comment by jboroos** [comment]
Hi @lpgoldstein, two of our prices are missing their trailing 0s in the table.  PC 02 for Oklahoma should be $49.70 and PC 63 for Uintah and Ouray - Duchesne is $38.10.  I'm not sure why but this has happened in the past and Chad had a way to fix the issue but I'm not sure what it was.  All the other prices looked good so once this issue is fixed we're good to post to the public.  @sudarr

**Comment by jennmalcolm** [comment]
I fixed the decimals issue. You may need to clear your cache to review.

**Comment by jboroos** [comment]
Thank you @jennmalcolm and @lpgoldstein!  The prices look good and we're good to post @sudarr

**Comment by jennmalcolm** [comment]
Feb prices are live now.
