### ISSUE TITLE
WebEx Reporter Training

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#584]
Please add the attached powerpoints to the following location using the below title:

https://www.onrr.gov/ReportPay/Training/index.htm

WebEx Reporter Training
[Accounts Receivable FED Basic.pptx](https://github.com/ONRR/onrr.gov-site/files/6150614/Accounts.Receivable.FED.Basic.pptx)
[Audit Module.pptx](https://github.com/ONRR/onrr.gov-site/files/6150615/Audit.Module.pptx)
[Basic Lease and Agreements.pptx](https://github.com/ONRR/onrr.gov-site/files/6150616/Basic.Lease.and.Agreements.pptx)
[Basic OGOR.pptx](https://github.com/ONRR/onrr.gov-site/files/6150623/Basic.OGOR.pptx)
[Billing.pptx](https://github.com/ONRR/onrr.gov-site/files/6150628/Billing.pptx)
[BLM CA.pdf](https://github.com/ONRR/onrr.gov-site/files/6150632/BLM.CA.pdf)
[ERRORS 2014 Reporting.pptx](https://github.com/ONRR/onrr.gov-site/files/6150634/ERRORS.2014.Reporting.pptx)
[ERRORS OGOR Reporting.pptx](https://github.com/ONRR/onrr.gov-site/files/6150637/ERRORS.OGOR.Reporting.pptx)
[Liquid Verification System and Gas Verification Team.pptx](https://github.com/ONRR/onrr.gov-site/files/6150644/Liquid.Verification.System.and.Gas.Verification.Team.pptx)
[Offshore FMP-PASR.pptx](https://github.com/ONRR/onrr.gov-site/files/6150652/Offshore.FMP-PASR.pptx)
[OGOR CSV REPORTING.pptx](https://github.com/ONRR/onrr.gov-site/files/6150654/OGOR.CSV.REPORTING.pptx)
[Royalty Transaction Codes.pptx](https://github.com/ONRR/onrr.gov-site/files/6150663/Royalty.Transaction.Codes.pptx)
[WebCenter Portal.pptx](https://github.com/ONRR/onrr.gov-site/files/6150664/WebCenter.Portal.pptx)

[2014 Indian Adjustments.pptx](https://github.com/ONRR/onrr.gov-site/files/6150610/2014.Indian.Adjustments.pptx)
[2014 Federal Adjustments.pptx](https://github.com/ONRR/onrr.gov-site/files/6150611/2014.Federal.Adjustments.pptx)

**Comment by Maroyafaied** [comment]
@bowlenj I just wanted to let you know that due to our team being very short staffed, it will take us a few days to make your update. Also, we have to run an accessibility check for each file , if we identify any of them as non-accessible then we will ask that you correct it before we are able to post them on the site. Thanks for your understanding.

**Comment by bowlenj** [comment]
I completely understand!  I did do an accessibility check on each one but please let me know if you find anything.  I believe there are some duplicate slide warnings but hopefully I cleaned up the errors.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: Maroyafaied ***@***.***>
Sent: Tuesday, March 16, 2021 11:35 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] WebEx Reporter Training (#584)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C786688fc8fcd4bd19c9d08d8e8a1dee1%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637515129214323130%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tq%2B9bfeD4lPMF44zvHSsF4VqV0%2BguP8a%2FUc1PpN%2Bk4c%3D&reserved=0> I just wanted to let you know that due to our team being very short staffed, it will take us a few days to make your update. Also, we have to run an accessibility check for each file , if we identify any of them as non-accessible then we will ask that you correct it before we are able to post them on the site. Thanks for your understanding.

-

**Comment by mcharg** [comment]
@bowlenj The 2014 Indian Adjustments file has an error for having multiple slides with the same title.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/a700ab82-fa5d-4f42-a9ee-60f905a4ab2d)

**Comment by mcharg** [comment]
@bowlenj The Basic Lease and Agreements doc has a warning about reading order.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/94b118ef-8d58-41d8-bfe3-b91b6d61f81b)

**Comment by mcharg** [comment]
@bowlenj Basic OGOR has two errors about duplicate slide titles and reading order.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/565d0e34-38e9-4ef0-832f-65c64333318a)

**Comment by mcharg** [comment]
@bowlenj Errors OGOR Reporting has a duplicate slide title.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/c32ccac6-19df-44eb-834e-e7eb1c6494ad)

**Comment by mcharg** [comment]
@bowlenj Liquid Verification System has a contrast issue and reading order issues.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/f55113ba-407c-46ae-a3db-d4b1d6b2d013)

**Comment by mcharg** [comment]
@bowlenj Offshore FMP PASR has errors for contrast and reading order.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/70b53b93-27c5-4d11-9f38-5e40d7e14694)

**Comment by mcharg** [comment]
@bowlenj OGOR CSV Reporting has duplicate slide titles.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/53acefc9-d45e-4e8e-96ab-3280155f57d0)

**Comment by mcharg** [comment]
@bowlenj Royalty Transaction Codes has duplicate slide titles.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/c0058781-ecd0-4939-a872-189e636dd351)

**Comment by mcharg** [comment]
@bowlenj WebCenter Portal has duplicate slide titles.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/ac15c8fe-7038-4f4d-8b8f-7dc84307c2ab)

**Comment by mcharg** [comment]
@bowlenj The rest are good.

**Comment by bowlenj** [comment]
We thought that was a tip that didn't need to be corrected.  Do all Errors, Warnings and Tips have to be corrected?

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: mcharg ***@***.***>
Sent: Wednesday, March 17, 2021 2:06 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] WebEx Reporter Training (#584)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C77be26d4a0f942b7b35008d8e9801fe3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637516083797281899%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Qms4dOj3DGAPBAg8O%2FxpCH8LaF2nQenvWmWFD32%2BCkg%3D&reserved=0> The 2014 Indian Adjustments file has an error for having multiple slides with the same title.
[https://camo.githubusercontent.com/9aa438bf5a61b9e273d05350ba62542c1281be14c52a0b6dad907765efac99de/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563353839666535653138303632303831326561323261612f61373030616238322d666135642d346]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcamo.githubusercontent.com%2F9aa438bf5a61b9e273d05350ba62542c1281be14c52a0b6dad907765efac99de%2F68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563353839666535653138303632303831326561323261612f61373030616238322d666135642d346634322d613965652d363066393035613461623264&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C77be26d4a0f942b7b35008d8e9801fe3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637516083797291846%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iyqJOCZKoU8cBdWt1XBHqkkzN7RdB%2FZTV2wzVOz%2BM%2Fg%3D&reserved=0>

-

**Comment by bowlenj** [comment]
All errors have been corrected 😊

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: mcharg ***@***.***>
Sent: Wednesday, March 17, 2021 2:06 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] WebEx Reporter Training (#584)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C77be26d4a0f942b7b35008d8e9801fe3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637516083797281899%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Qms4dOj3DGAPBAg8O%2FxpCH8LaF2nQenvWmWFD32%2BCkg%3D&reserved=0> The 2014 Indian Adjustments file has an error for having multiple slides with the same title.
[https://camo.githubusercontent.com/9aa438bf5a61b9e273d05350ba62542c1281be14c52a0b6dad907765efac99de/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563353839666535653138303632303831326561323261612f61373030616238322d666135642d346]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcamo.githubusercontent.com%2F9aa438bf5a61b9e273d05350ba62542c1281be14c52a0b6dad907765efac99de%2F68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563353839666535653138303632303831326561323261612f61373030616238322d666135642d346634322d613965652d363066393035613461623264&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C77be26d4a0f942b7b35008d8e9801fe3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637516083797291846%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iyqJOCZKoU8cBdWt1XBHqkkzN7RdB%2FZTV2wzVOz%2BM%2Fg%3D&reserved=0>

**Comment by bowlenj** [comment]
All errors have been corrected.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: mcharg ***@***.***>
Sent: Wednesday, March 17, 2021 2:09 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] WebEx Reporter Training (#584)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cb6dc4dd27b70465105c308d8e98091b1%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637516085699375129%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iguMLz%2Fpr7cRtHQLmoVfDl0lW7jSnrqxqLWsvWeX6Ro%3D&reserved=0> Basic OGOR has two errors about duplicate slide titles and reading order.
[https://camo.githubusercontent.com/61a9ef0db663369e0f78846df2be16e72d73ca73e2588bea07be94aacc756eaf/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563353839666535653138303632303831326561323261612f35363564306533342d333865392d346]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcamo.githubusercontent.com%2F61a9ef0db663369e0f78846df2be16e72d73ca73e2588bea07be94aacc756eaf%2F68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563353839666535653138303632303831326561323261612f35363564306533342d333865392d346566302d383332662d363563363433333333313861&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cb6dc4dd27b70465105c308d8e98091b1%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637516085699385086%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZLdZ%2F9zxcDfnTSZgdY2XoL7d3Ld2Gc11kH3vPbs1qEY%3D&reserved=0>

-

**Comment by bowlenj** [comment]
All errors are corrected.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: mcharg ***@***.***>
Sent: Wednesday, March 17, 2021 2:14 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] WebEx Reporter Training (#584)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C13c79afe68a246a709bb08d8e9813fb5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637516088638203562%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=V7CDtTAisrBCtU2hUHuSmOILnK%2FeBUhZ9eH93FCpyV0%3D&reserved=0> Offshore FMP PASR has errors for contrast and reading order.
[https://camo.githubusercontent.com/56a90b469520ccaa133691d3efdad4ae6287d0b50e1013ce8f6eefc518bf6848/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563353839666535653138303632303831326561323261612f37306235336239332d323763352d346]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcamo.githubusercontent.com%2F56a90b469520ccaa133691d3efdad4ae6287d0b50e1013ce8f6eefc518bf6848%2F68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563353839666535653138303632303831326561323261612f37306235336239332d323763352d346431312d396633382d356534306437653134363934&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C13c79afe68a246a709bb08d8e9813fb5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637516088638203562%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6vHNNFnt3h95RCjFjgm64aG0jDfFTfMFlcQJZEbIQQ4%3D&reserved=0>

-

**Comment by bowlenj** [comment]
All errors have been corrected.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: mcharg ***@***.***>
Sent: Wednesday, March 17, 2021 2:15 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] WebEx Reporter Training (#584)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cb614c30f9ec44d96eedc08d8e9815173%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637516088971055090%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LKP%2BJsfLXAjujvAbSS0MJb%2F98PrkkB9pm99q7brKJgg%3D&reserved=0> OGOR CSV Reporting has duplicate slide titles.
[https://camo.githubusercontent.com/ac8162cf436620641e9a4adee254ead42ed9287fd5e50487995011f62459776f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563353839666535653138303632303831326561323261612f35336163656663392d643435652d346]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcamo.githubusercontent.com%2Fac8162cf436620641e9a4adee254ead42ed9287fd5e50487995011f62459776f%2F68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563353839666535653138303632303831326561323261612f35336163656663392d643435652d346538652d393661622d333238303135356635376430&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cb614c30f9ec44d96eedc08d8e9815173%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637516088971065046%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nlZFMNdrcWZ8QLKlMGpeTHOrPP6HZU3%2Bz9pCFKNef2w%3D&reserved=0>

-

**Comment by bowlenj** [comment]
All errors have been corrected.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: mcharg ***@***.***>
Sent: Wednesday, March 17, 2021 2:16 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] WebEx Reporter Training (#584)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cef532e4c71914f0d66e308d8e981797e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637516089598226423%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AeXOuaopC05GzwKsBq4AaWnZw2fiXhGcsfzSanAOauc%3D&reserved=0> Royalty Transaction Codes has duplicate slide titles.
[https://camo.githubusercontent.com/9fde3758d8800f82dda81a3ab6dfacac2683a9e2949425710fbce976c5f2a64f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563353839666535653138303632303831326561323261612f63303035383738312d656364302d343]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcamo.githubusercontent.com%2F9fde3758d8800f82dda81a3ab6dfacac2683a9e2949425710fbce976c5f2a64f%2F68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563353839666535653138303632303831326561323261612f63303035383738312d656364302d343933392d613837322d313839653633366464333531&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cef532e4c71914f0d66e308d8e981797e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637516089598226423%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8gyMM6S1Y3aJNMIQgQ61tcVWjDu18DmPF%2BkRe8ht3LE%3D&reserved=0>

-

**Comment by bowlenj** [comment]
Corrected presentations are attached.  1 additional has been added 2014 Reporting also.
[2014 Reporting.pptx](https://github.com/ONRR/onrr.gov-site/files/6192322/2014.Reporting.pptx)
[WebCenter Portal.pptx](https://github.com/ONRR/onrr.gov-site/files/6192325/WebCenter.Portal.pptx)
[2014 Indian Adjustments.pptx](https://github.com/ONRR/onrr.gov-site/files/6192329/2014.Indian.Adjustments.pptx)
[Basic Lease and Agreements.pptx](https://github.com/ONRR/onrr.gov-site/files/6192331/Basic.Lease.and.Agreements.pptx)
[Basic OGOR.pptx](https://github.com/ONRR/onrr.gov-site/files/6192333/Basic.OGOR.pptx)
[ERRORS OGOR Reporting.pptx](https://github.com/ONRR/onrr.gov-site/files/6192335/ERRORS.OGOR.Reporting.pptx)
[Liquid Verification System and Gas Verification Team.pptx](https://github.com/ONRR/onrr.gov-site/files/6192336/Liquid.Verification.System.and.Gas.Verification.Team.pptx)
[Offshore FMP-PASR.pptx](https://github.com/ONRR/onrr.gov-site/files/6192337/Offshore.FMP-PASR.pptx)
[OGOR CSV REPORTING.pptx](https://github.com/ONRR/onrr.gov-site/files/6192339/OGOR.CSV.REPORTING.pptx)
[Royalty Transaction Codes.pptx](https://github.com/ONRR/onrr.gov-site/files/6192345/Royalty.Transaction.Codes.pptx)

**Comment by mcharg** [comment]
@bowlenj These are all updated in dev.  Let me know if it looks good to push to the live site.
http://2017onrr/ReportPay/training/index.htm

**Comment by bowlenj** [comment]
This looks great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: mcharg ***@***.***>
Sent: Tuesday, March 23, 2021 2:08 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] WebEx Reporter Training (#584)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C39bc087737734842271608d8ee375461%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637521269892699631%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GLfNle%2FQ5YrCsovwD3OlWThryxdrxJhc4g5DHam8JkY%3D&reserved=0> These are all updated in dev. Let me know if it looks good to push to the live site.
http://2017onrr/ReportPay/training/index.htm

-

**Comment by mcharg** [comment]
@bowlenj I pushed these changes to the live site.  Might be a bit before they show up.
