### ISSUE TITLE
Update ONRR Payment page

### ISSUE THREAD

**Issue by vcs5274** [ONRR/onrr.gov-site#586]
Please update the ONRR Payments page. Please remove Tanvir Mojumder under Payments and replace with Gary Brunette. 
Do not change the email address. Update the phone number extension to X3420 and phone number to 303-231-3420.

**Comment by Maroyafaied** [comment]
@vcs5274 please review the changes in the dev site. http://2017onrr/ReportPay/payments.htm

**Comment by vcs5274** [comment]
The changes look good.

Thank you,

Victoria Soto
Office of Natural Resources Revenue
DFC 6th Ave & Kipling
Bldg 85 Entrance N-1
Denver, CO  80225
Supervisory Accountant, Accounting Services, General Ledger
Phone: 1-800-433-9801 x13085
     -or-      303-231-3085
Fax: 303-445-9526
Email: ***@***.******@***.***>

"Virtually nothing is impossible in this world if you just put your mind to it and maintain a positive attitude." - Lou Holtz

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________
From: Maroyafaied ***@***.***>
Sent: Friday, March 19, 2021 12:16 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Soto, Victoria C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update ONRR Payment page (#586)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@vcs5274<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvcs5274&data=04%7C01%7Cvictoria.soto%40onrr.gov%7C770baec6a5e9467d9a0708d8eb03339d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637517746283912014%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gC1%2FfsrGtSg%2FT6qNUMIT3yHJowzt%2FxQ%2Bq68N5tF%2F5Zw%3D&reserved=0> please review the changes in the dev site. http://2017onrr/ReportPay/payments.htm

**Comment by Maroyafaied** [comment]
@vcs5274 Thanks, it should be live in 30 min.

**Comment by Maroyafaied** [comment]
This is live.
