### ISSUE TITLE
Event Calendar   Title: Shawnee Area Meeting

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#588]
March 24, 2021
Title: Shawnee Area Meeting
Event Information
Location:  By Telephone
Time: 1:00 PM to 2:00 PM
Description:  Meeting will be a Call-in Meeting to hear a presentation and updates from ONRR OKC Outreach Office and OK representatives from BLM, BTFM, and BIA also that will discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust properties. There will also be a Q&A session for owners to ask questions.  For those interested in attending must contact the ONRR Outreach office at (800) 354-7015 to reserve their space for attending meeting and to get the call-in number and passcode.  A limited number of lines will be available for callers to this meeting.  
Who Should Attend:  IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Shawnee Agency Area, Southern Plains Region in Oklahoma.
Other Information: To attend meeting you must contact the ONRR OKC Outreach office at (800)354-7015 to reserve your space and to get the call-in number and passcode for the meeting on March 24, 2021.   ONNR Outreach office hours are Monday- Friday from 7:30 am-5:00 pm.
Event Contact
Name: ONRR OKC Office
Phone: Toll-free (800) 354-7015
Email: onrroutreachokc@onrr.gov

**Comment by Maroyafaied** [comment]
@Toddsand21 please review the dev site. http://2017onrr/IndianServices/index.htm#

**Comment by Toddsand21** [comment]
In the Description:  In the first sentence  (put a period after the ONRR OKC Office.  Begin next sentence with Representatives from BLM, BTFM and BIA will also be available to discuss topics regarding.... (mark out "and OK").

**Comment by Toddsand21** [comment]
The rest of it looks fine with just those 2 changes I think its ready to go.

**Comment by Maroyafaied** [comment]
@Toddsand21 please review the changes http://2017onrr/IndianServices/index.htm#

**Comment by Toddsand21** [comment]
Please change the 2nd sentence in the Discussion to:      Representatives from BLM, BTFA, and BIA will also be available to discuss topics regarding Indian oil and gas, IIM accounts and other Indian trust properties.  (Please delete the previous 2nd sentence and replace with the one above).

**Comment by Toddsand21** [comment]
Yes, those are the lines that were needed to be corrected.  It is fine and ready to post. Thanks.

**Comment by Maroyafaied** [comment]
It should be live in 30 min. Thanks

**Comment by Toddsand21** [comment]
Great!

Sandra Todd
Minerals Revenue Specialist
Office of Natural Resources Revenue
Indian Outreach, OKC
(405) 879-6052
(800) 354-7015
________________________________
From: Maroyafaied ***@***.***>
Sent: Tuesday, March 23, 2021 10:56 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Todd, Sandra L. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Event Calendar Title: Shawnee Area Meeting (#588)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



It should be live in 30 min. Thanks

**Comment by Maroyafaied** [comment]
It's live.
