### ISSUE TITLE
Navajo Nation Lockbox Mailing address

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#589]
Please correct the state for the Navajo Nation lockbox mailing address to read CA instead of CO at the below location:

https://www.onrr.gov/ReportPay/payments.htm

Navajo Nation
PO Box 842479
Los Angeles, CA 90084-2479

**Comment by mcharg** [comment]
@bowlenj This is updated in dev.  Let me know if it's good to push to the live site.
http://2017onrr/ReportPay/payments.htm

**Comment by bowlenj** [comment]
Yes, this looks good.  Thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: mcharg ***@***.***>
Sent: Monday, March 22, 2021 9:09 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Navajo Nation Lockbox Mailing address (#589)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C00c29df26dac4d25e51f08d8ed446aff%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637520225637426546%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nLdjnpf%2F3q4O1dh0vwUZ%2BMBPge0NW82CuFHk42jf%2BuQ%3D&reserved=0> This is updated in dev. Let me know if it's good to push to the live site.
http://2017onrr/ReportPay/payments.htm

-

**Comment by mcharg** [comment]
@bowlenj I pushed to the live site.  Might be a bit before it shows up.
