### ISSUE TITLE
Write up for new deputy director

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#59]
We need to write a profile for the new deputy director to be added to onrr.gov next week when he starts.

**Comment by mentastc** [comment]
Howard Cantor assumed duties as the Deputy Director of the Office of Natural Resources Revenue
(ONRR) on March 15, 2020.

As ONRR’s Deputy Director, Mr. Cantor oversees the day-to-day operations of the Denver
Office, as well as the ONRR field offices in Houston and Dallas, Texas; Oklahoma City and
Tulsa, Oklahoma; and Farmington, New Mexico.

Prior to his appointment as Deputy Director, he was the Director of the Bureau of Land Management’s National Operations Center, overseeing 500 employees and contractors providing a wide range of operational and technical support services to BLM stakeholders across the nation.  Prior to his work with BLM Mr. Cantor served as the Deputy Regional Administrator of the EPA Region 8 office in Denver, with responsibility for environmental programs in six states and 27 tribal nations. 

Over the course of his career with EPA, which began in 1994 as a Presidential Management Intern, Howard served as Acting Director of the Office of Criminal Enforcement, Forensics, and Training, where he managed over 350 criminal investigators, attorneys, scientists, engineers, and other support personnel who investigate and assist in the prosecution of criminal conduct that threatens people’s health and the environment.  In addition, he was the Director of the EPA’s National Enforcement Investigations Center, where he oversaw approximately 100 scientists, engineers, and support personnel who provide forensic and investigative services to the EPA’s criminal and civil enforcement programs.  He also served in various positions in EPA's Office of Research and Development, and was an Assistant Inspector General in the Agency's Office of Inspector General.  

Howard holds a Bachelor of Arts degree in psychology from the University of Pennsylvania and a Masters of Public Administration degree from Indiana University’s School of Public and Environmental Affairs.

**Comment by jennmalcolm** [comment]
profile is live
