### ISSUE TITLE
Duplicate files: Accounts Receivable, Billing, and Financial Issues Information -- Federal

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#590]
We have two different files for the same contacts.  Need to decide which to keep.

On Contact Us:
https://www.onrr.gov/ReportPay/PDFDocs/FSFederalCOAssignm.pdf

On Payments:
https://www.onrr.gov/ReportPay/PDFDocs/finserAssign.pdf

**Comment by mcharg** [comment]
@bowlenj Is this doc for your team?  If so, which should we be using?

**Comment by bowlenj** [comment]
This was part of our training but I don't believe it's a reference presentation.  Please add the most recent to the list of training presentations.  We don't want it duplicated.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: mcharg ***@***.***>
Sent: Monday, March 29, 2021 8:45 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Duplicate files: Accounts Receivable, Billing, and Financial Issues Information -- Federal (#590)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Ca73a95cf0c624aa36d5f08d8f2c144d1%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637526259207695508%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nyCVfJLh2WCA1vpgRZAlGzCEt48Y0%2FLlfaKn%2Bl2lt7g%3D&reserved=0> Is this doc for your team? If so, which should we be using?

-

**Comment by mcharg** [comment]
We've identifed Rob Winter as the owner of this form.  Waiting on his response about removing one of them.

**Comment by bowlenj** [comment]
Perfect, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: mcharg ***@***.***>
Sent: Wednesday, March 31, 2021 7:07 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Duplicate files: Accounts Receivable, Billing, and Financial Issues Information -- Federal (#590)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



We've identified Rob Winter as the owner of this form. Waiting on his response about removing one of them.

-

**Comment by mcharg** [comment]
Looks like somebody already replaced the link on the Payments page.

**Comment by bowlenj** [comment]
Great, thank you for looking into this!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: mcharg ***@***.***>
Sent: Friday, April 2, 2021 7:20 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Duplicate files: Accounts Receivable, Billing, and Financial Issues Information -- Federal (#590)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Looks like somebody already replaced the link on the Payments page.

-
