### ISSUE TITLE
Update to Training Presentations

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#593]
Please update the Reference Reporting/Training page at the below location as shown in the attachment.
[Reference Training Update.docx](https://github.com/ONRR/onrr.gov-site/files/6197827/Reference.Training.Update.docx)

**Comment by mcharg** [comment]
@bowlenj @merrellc The training page is updated in dev.  Let me know if it's okay to push to the live site.
http://2017onrr/reportpay/training/index.htm

I also removed the Reporting on Federal Units and Communitization Agreements from the Presentations and Testimony page under About.
http://2017onrr/About/Presentations.htm

**Comment by mcharg** [comment]
@bowlenj These changes are now live.
