### ISSUE TITLE
Get About pages out of screenshots and reduce reading level

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#595]

**Comment by mcharg** [comment]
@Maroyafaied Do you want to review?  The only one I wasn't able to get down to grade 10 is the Interagency Coordination page under Engagement with the MOUs and SOPs on it.  There are too many acronyms.

https://qmcq5k.axshare.com/#id=vsgcdx&p=about_onrr

**Comment by Maroyafaied** [comment]
@mcharg The interagency coordination tab has testimony content in it and there is a testimony tab as well? We should ask Kimbra if the testimony content is still relevant or needed. 
![image](https://user-images.githubusercontent.com/40175688/113730126-d5317500-96b4-11eb-8b61-6b71092033b6.png)

**Comment by mcharg** [comment]
@Maroyafaied I fixed the tabs, so you can now get to the interagency coordination page.
https://qmcq5k.axshare.com/#id=ocslh8&p=engagement

**Comment by Maroyafaied** [comment]
@mcharg looks good
