### ISSUE TITLE
New - Updates to onrr.gov for Indian Services

### ISSUE THREAD

**Issue by ONRRamandagarrison** [ONRR/onrr.gov-site#60]
Hello. I need to make several changes to a page on onrr.gov under the Indian Services/Indian Energy Service Center.

On our "home page" [https://www.onrr.gov/IndianServices/indian-energy-service-center.htm] we would like to post this video: https://app.vyond.com/videos/48871ba4-15c2-4960-8e7d-b786dd470053

I have the video downloaded as well. I don't know what the best method is for posting a video. I can send the file to you and have it hosted on our ONRR YouTube channel. I will let you guys decide on the best method for that.

On our contacts page [https://www.onrr.gov/IndianServices/iescstaff.htm] there are several updates needed.

- REMOVE IESC Director | Johnna Spriggs | BIA

- ADD IESC Director (Acting) | Carla Clark | BIA

- REMOVE IESC Engineering Services Branch Chief | Jim Wood | BLM
  leave position up but label as 'Vacant'

- REMOVE IESC Petroleum Engineer | Kuo-Shian Kao | BLM

- ADD IESC Minerals Revenue Specialist | Matthew Moore | ONRR
   His email address for linking is: matthew.moore@onrr.gov

- REMOVE IESC Mineral Services Branch Chief | Yvette Smith | ONRR

- ADD IESC Mineral Services Branch Chief (Acting) | Heidi Badaracco | ONRR
   Her email address for linking is: heidi.badaracco@onrr.gov

- ADD IESC Production Accountability Specialist | Scott Doebbler  | BLM
  His email address for linking is:  sdoebbler@blm.gov

The last change is optional. If possible, we would like to highlight a position we have that is currently open for people to apply to.

It is for an OST Accounting Technician position that is open until April 1, 2020.  We wanted something on our "home page" that said something like "Job Opportunity Announcement" 
"This position is part of the Office of the Special Trustee for American Indians. The Lakewood, CO vacancy is located at the Indian Energy Service Center.  As a Accounting Technician you will be responsible for financial service functions at the field level, including collection of Individual Indian Money (IIM) accounts, verification and maintenance of accounts and accounting data. The incumbent will also respond to questions of a routine to complex nature regarding various aspect of accounting.
If you are interesting in apply, please visit here: https://www.usajobs.gov/GetJob/ViewDetails/561867300

If you have any questions, please contact me at amanda.garrison@onrr.gov

**Comment by jennmalcolm** [comment]
@mentastc could you put the job announcement on social media too?

**Comment by jennmalcolm** [comment]
@ONRRamandagarrison could you provide the mp4 of the video as well? Thanks.

**Comment by jennmalcolm** [comment]
Hi, @ONRRamandagarrison we need the video file to get that on there right, but the other changes are ready for review. I added the job announcement to the bottom of this page: http://2017onrr/IndianServices/indian-energy-service-center.htm, and you can check the contact revisions on this page: http://2017onrr/IndianServices/iescstaff.htm.

Let us know once you've reviewed these changes on the development site, and we'll get them pushed live.

**Comment by ONRRamandagarrison** [comment]
Jennifer,

I got your voicemail. All the Github emails were going into my junk folder and I didn’t see them or I would have responded sooner. I added the email address to the safe sender list so hopefully I won’t miss anymore communications.

Everything looks great! You can publish it whenever you want. I did send Bill the video already.


Thank you,
Amanda

Amanda Garrison

Supervisory Minerals Revenue Specialist
Indian Energy Service Center
P: (720) 595-2025

**Comment by jennmalcolm** [comment]
All updates are live except the video, which I've opened #66 to do once it's on YouTube.
