### ISSUE TITLE
Replace onshore and offshore production reporting contacts with the correct pdf

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#602]
Some of the ones in the right rail in reporting link to the wrong files.

Incorrect files:
https://www.onrr.gov/reportpay/PDFDocs/Offshore-Production-Reporting-Contacts.pdf
https://www.onrr.gov/reportpay/PDFDocs/Onshore-Production-Reporting-Contacts.pdf

Correct files:
https://www.onrr.gov/ReportPay/PDFDocs/OffshoreProductionContacts.pdf
https://www.onrr.gov/ReportPay/PDFDocs/OnshoreProductionContacts.pdf

**Comment by mcharg** [comment]
@Maroyafaied I updated the links on these pages in dev.  Can you take a look and make sure it's good to post to the live site?
https://www.onrr.gov/ReportPay/production-reporting.htm
https://www.onrr.gov/ReportPay/royalty-reporting.htm
https://www.onrr.gov/ReportPay/solids.htm
https://www.onrr.gov/ReportPay/forms/index.htm

**Comment by mcharg** [comment]
Just realized the checklist pages also have the link and need to be updated.

**Comment by mcharg** [comment]
@Maroyafaied Also updated these pages and added a link to the WebCenter Portal user guide to right nav on all the pages, as well.

http://2017onrr/reportpay/prod-checklist.htm
http://2017onrr/reportpay/roy-checklist.htm

**Comment by Maroyafaied** [comment]
@mcharg Looks great.

**Comment by mcharg** [comment]
I pushed these changes to the live site.
