### ISSUE TITLE
onrr.gov style tile first pass

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#608]

**Comment by abudz19** [comment]
Style tile, lightly applied to some of the most common components. Talk to you soon!
[style tile.pdf](https://github.com/ONRR/onrr.gov-site/files/6259080/style.tile.pdf)

**Comment by mcharg** [comment]
Created #637 for the next step

**Comment by abudz19** [comment]
@jlouis-onrr
