### ISSUE TITLE
Single sign on for datawarehouse and ecommerce

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/onrr.gov-site#61]
These links both go to the same screen: 
![image](https://user-images.githubusercontent.com/39419003/76354401-b9f50a00-62e8-11ea-9e86-99f47c9a3ca9.png)

![image](https://user-images.githubusercontent.com/39419003/76354470-e0b34080-62e8-11ea-9b19-1094485d8e82.png)

**Comment by jennmalcolm** [comment]
Make sure to confirm that it goes the same place after signin.

**Comment by mcharg** [comment]
Will be addressed when Web Center Portal goes live.
