### ISSUE TITLE
Press Release Update

### ISSUE THREAD

**Issue by mentastc** [ONRR/onrr.gov-site#611]
@Maroyafaied @mcharg Please add the following 5 press release with the national press release being at the top. This update should be pushed live once the national press release is added to DOI.gov (around 1pm eastern).

[GOMESA National Release.pdf](https://github.com/ONRR/onrr.gov-site/files/6230158/GOMESA.National.Release.pdf)
[Louisiana GOMESA Release 3.30.pdf](https://github.com/ONRR/onrr.gov-site/files/6230159/Louisiana.GOMESA.Release.3.30.pdf)
[Texas GOMESA Release 3.30.pdf](https://github.com/ONRR/onrr.gov-site/files/6230160/Texas.GOMESA.Release.3.30.pdf)
[Mississippi GOMESA Release 3.30.pdf](https://github.com/ONRR/onrr.gov-site/files/6230161/Mississippi.GOMESA.Release.3.30.pdf)
[Alabama GOMESA Release 3.30.pdf](https://github.com/ONRR/onrr.gov-site/files/6230162/Alabama.GOMESA.Release.3.30.pdf)

**Comment by mentastc** [comment]
@Maroyafaied @mcharg The NRRD link was bad in the previous press releases, I've updated the attached documents that should have good links, please use these. Sorry about that. 
[Alabama GOMESA Release 3.30.pdf](https://github.com/ONRR/onrr.gov-site/files/6230662/Alabama.GOMESA.Release.3.30.pdf)
[Mississippi GOMESA Release 3.30.pdf](https://github.com/ONRR/onrr.gov-site/files/6230663/Mississippi.GOMESA.Release.3.30.pdf)
[Texas GOMESA Release 3.30.pdf](https://github.com/ONRR/onrr.gov-site/files/6230664/Texas.GOMESA.Release.3.30.pdf)
[Louisiana GOMESA Release 3.30.pdf](https://github.com/ONRR/onrr.gov-site/files/6230665/Louisiana.GOMESA.Release.3.30.pdf)
[GOMESA National Release.pdf](https://github.com/ONRR/onrr.gov-site/files/6230666/GOMESA.National.Release.pdf)
[All States GOMESA Release 3.30.pdf](https://github.com/ONRR/onrr.gov-site/files/6230667/All.States.GOMESA.Release.3.30.pdf)

**Comment by Maroyafaied** [comment]
http://2017onrr/

**Comment by Maroyafaied** [comment]
@mentastc It's live now
