### ISSUE TITLE
Review completion of Phase 1 and update status

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#613]
I will review LeeAnn, Barder and Winter group's and update the status of docs in the excel sheet. @mcharg will review the rest.

**Comment by mcharg** [comment]
@Maroyafaied I reviewed the spreadsheets for the other document owners and updated the consolidated list.

**Comment by Maroyafaied** [comment]
@mcharg I reviewed my portion and updated the list and send 2 docs to be corrected in Rob Winter's group and 7 docs to Lee Ann Martin group.
