### ISSUE TITLE
Royalty Contact List Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#614]
Please update the Royalty Contact list with this updated version at the following location - https://www.onrr.gov/ReportPay/PDFDocs/royassign.pdf

[royassign.pdf](https://github.com/ONRR/onrr.gov-site/files/6238009/royassign.pdf)

**Comment by Maroyafaied** [comment]
@bowlenj please review http://2017onrr/reportpay/PDFDocs/royassign.pdf

**Comment by bowlenj** [comment]
Looks good!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: Maroyafaied ***@***.***>
Sent: Thursday, April 1, 2021 12:32 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Royalty Contact List Update (#614)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C49a9ac19eec741049aa908d8f53c7e08%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637528987454411214%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JWtmhesNdnJrH0iNHfd8Q9MyiH4g%2FpC5e07xL4hO2g0%3D&reserved=0> please review http://2017onrr/reportpay/PDFDocs/royassign.pdf

-

**Comment by Maroyafaied** [comment]
This is live.
