### ISSUE TITLE
"Event Calendar"   (Please note: Find it under the Allottee Assistance tab under Indian Services)

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#618]
APRIL 21, 2021
Title: Pawnee Area Meeting, Pawnee Agency 
Event Information
Location:  By Telephone
Time: 1:00 PM to 2:00 PM
Description:  Meeting will be a Call-in Meeting to hear a presentation and updates from ONRR OKC Outreach Office.  Representatives from BLM, BTFM, and BIA will also be available to discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust properties.  For those interested in attending must contact the ONRR Outreach office at 
(800) 354-7015 to reserve their space for attending meeting and to get the call-in number and passcode.  A limited number of lines will be available for callers to this meeting.  
Who Should Attend:  IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Pawnee Agency Area, or any mineral owners located in the Southern Plains Region in Oklahoma. 
Other Information: To attend meeting you must contact the ONRR OKC Outreach office at (800)354-7015 to reserve your space and to get the call-in number and passcode for the meeting on April 21, 2021.   ONNR Outreach office hours are Monday- Friday from 7:30 am-5:00 pm.
Event Contact
Name: ONRR OKC Outreach Office
Phone: Toll-free (800) 354-7015
Email: onrroutreachokc@onrr.gov

APRIL 21, 2021
Title: Helena, Butte, Harlem, Great Falls, and Browning, MT Area Meeting
Event Information
Location:  By Telephone
Time: 1:00 PM to 2:00 PM
Description:  Meeting will be a Call-in Meeting to meet with the ONRR Denver Outreach Office to discuss topics regarding Indian Oil & Gas leases, and Indian trust properties. Owners will have the opportunity to ask questions about their Indian trust properties. 
Who Should Attend:  Indian mineral owners, and Indian Trust property owners in the Helena, Butte, Harlem, Great Falls, and Browning, MT area. 
Other Information: To attend meeting contact the ONRR Denver Outreach office at 
(800) 982-3226 to reserve your space and to get the call-in number and passcode for the meeting on April 21, 2021.   
Event Contact:
Name: ONRR Denver Outreach Office
Phone: Toll-free (800) 982-3226
Email:  onrroutreachdenver@onrr.gov

APRIL 22, 2021
Title: Uintah & Ouray, Utah Area Meeting
Event Information
Location:  By Telephone
Time: 10:00 am - 11:00 am
Description:  Meeting will be a Call-in Meeting to meet with the ONRR Denver Outreach Office to discuss topics regarding Indian Oil & Gas leases, and Indian trust properties.  Owners will have the opportunity to ask questions about their Indian trust properties. 
Who Should Attend:  Indian mineral owners, and Indian Trust property owners in the Uintah & Ouray Agency, Utah area. 
Other Information: To attend meeting contact the ONRR Denver Outreach office at 
(800) 982-3226 to reserve your space and to get the call-in number and passcode for the meeting on April 22, 2021.   
Event Contact:
Name: ONRR Denver Outreach Office
Phone: Toll-free (800) 982-3226
Email:  onrroutreachdenver@onrr.gov

**Comment by Maroyafaied** [comment]
@Toddsand21 Please review. http://2017onrr/IndianServices/index.htm#

**Comment by Toddsand21** [comment]
1. Under the "Description" in all 3 meetings  Please change the last word in first sentence from "properties" to property issues.  2. Under the "Description" for both the Helena, Butte, MT & Uintah & Ouray Meeting delete the whole last sentence beginning with "Owner will have the...
3. Under "Other Information"  for both the Helena, Butte, MT meeting and the Uintah & Ouray Meeting:  Please delete everything in the first sentence after "passcode" it should end with:...  the call-in number and passcode. (end with a period)

**Comment by Toddsand21** [comment]
It should be 1,2 and 3

**Comment by Toddsand21** [comment]
That is all I would change and it's ready.

**Comment by Maroyafaied** [comment]
@Toddsand21 I made the changes and it should be live in 30 min. http://2017onrr/IndianServices/index.htm#

**Comment by Maroyafaied** [comment]
This is live

**Comment by Maroyafaied** [comment]
This is live
