### ISSUE TITLE
Active Leases - Sorted by State and Agency Lease Number

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#619]
Please update the following webpage:
https://www.onrr.gov/reportpay/CrossRef.htm with the attached file.

Active Leases - Sorted by State and Agency Lease Number (updated 1/4/2021) please change date to (Updated 4/1/2021).

Thank You
Jessica
[ALwState.xlsx](https://github.com/ONRR/onrr.gov-site/files/6244930/ALwState.xlsx)

**Comment by Maroyafaied** [comment]
@bowlenj please review http://2017onrr/ReportPay/CrossRef.htm

**Comment by bowlenj** [comment]
Looks good!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: Maroyafaied ***@***.***>
Sent: Thursday, April 1, 2021 12:46 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Active Leases - Sorted by State and Agency Lease Number (#619)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C228dbd776a2643e0d01408d8f53e5fc3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637528995531284010%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=U4FqAe17Iu%2FGsLVn847vaDWnaWIBnpcCLiC1R0WEd9M%3D&reserved=0> please review http://2017onrr/ReportPay/CrossRef.htm

-

**Comment by Maroyafaied** [comment]
This is live.
