### ISSUE TITLE
Replace FRN pdfs with links 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#620]

**Comment by Maroyafaied** [comment]
Generate excel sheet with all places that need to be replaced. @Baymatt help with finding the right links to replace the pdf's.

**Comment by mcharg** [comment]
@Baymatt Here's the list of Federal Register Notices.  I was wrong when I said there were 28.  There were only 28 in our accessibility tracking sheet, but 131 in the content audit.  That means most of them had 0 clicks in the last year.  

I left the ones that already link to the Federal Register, so you can see if there's a pattern in the links.  They are marked as External in the type column.

Spreadsheet: https://teams.microsoft.com/l/file/52528D46-310B-438B-B94D-DFF9B54A5143?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FContent%20Audit%2FFRNs.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

Page where they all live on onrr.gov: https://www.onrr.gov/Laws_R_D/FRNotices/index.htm

Federal Register: https://www.archives.gov/federal-register

**Comment by mcharg** [comment]
@Baymatt This beta Federal Register search, but be easier to find the links.
https://ecfr.federalregister.gov/

**Comment by mcharg** [comment]
And here's a page on the Federal Register for ONRR.
https://www.federalregister.gov/agencies/natural-resources-revenue-office

**Comment by mcharg** [comment]
@Maroyafaied I updated the links to the FRNs from 2018-2021 on the following pages in dev, if you want to start checking. Will continue going through the list tomorrow.

http://2017onrr/Laws_R_D/FRNotices/index.htm
http://2017onrr/Laws_R_D/FRNotices/ICR0103.htm
http://2017onrr/Laws_R_D/FRNotices/ICR0087.htm
http://2017onrr/Laws_R_D/FRNotices/ICR0162.htm
http://2017onrr/Laws_R_D/FRNotices/ICR0107.htm (there's one 2020 link that we need to find the FRN link for, see #650)
http://2017onrr/Laws_R_D/FRNotices/AA22.htm
http://2017onrr/Laws_R_D/FRNotices/AA23.htm
http://2017onrr/Laws_R_D/FRNotices/ICR0120.htm
http://2017onrr/Laws_R_D/FRNotices/AB57.htm
http://2017onrr/Laws_R_D/FRNotices/ICR0139.htm
http://2017onrr/Laws_R_D/FRNotices/AC30.htm
http://2017onrr/Laws_R_D/FRNotices/AA24.htm
http://2017onrr/Laws_R_D/FRNotices/AA25.htm

**Comment by Maroyafaied** [comment]
@mcharg all the above look good. Thanks

**Comment by mcharg** [comment]
@Maroyafaied The 2011-2017 ones that are linked on the FRN page are now updated on the following pages in dev.

http://2017onrr/Laws_R_D/FRNotices/index.htm
http://2017onrr/valuation/IndVal.htm
http://2017onrr/reportpay/Handbooks/indian-payor-handbook-chapter-2.htm (2.5.5.1 tab)
http://2017onrr/valuation/allzones.htm
http://2017onrr/about/NewsReleases.htm (2 links to workshops Sep 9, 2011 - these don't appear updated on my end - not sure why)
http://2017onrr/compliance/treasury-referrals.htm
http://2017onrr/Laws_R_D/FRNotices/AA03.htm
http://2017onrr/Laws_R_D/FRNotices/ICR0087.htm
http://2017onrr/Laws_R_D/FRNotices/AD70.htm
http://2017onrr/Laws_R_D/FRNotices/AA02.htm
http://2017onrr/Laws_R_D/FRNotices/AA04.htm
http://2017onrr/Laws_R_D/FRNotices/AA14.htm
http://2017onrr/Laws_R_D/FRNotices/AD20.htm
http://2017onrr/Laws_R_D/FRNotices/AA08.htm
http://2017onrr/Laws_R_D/FRNotices/AA13.htm
http://2017onrr/Laws_R_D/FRNotices/ICR0103.htm
http://2017onrr/Laws_R_D/FRNotices/ICR1012-0012.htm
http://2017onrr/Laws_R_D/FRNotices/ICR0162.htm
http://2017onrr/Laws_R_D/FRNotices/AA15.htm
http://2017onrr/Laws_R_D/FRNotices/ICR0139.htm
http://2017onrr/Laws_R_D/FRNotices/AA11.htm
http://2017onrr/Laws_R_D/FRNotices/AA05.htm
http://2017onrr/Laws_R_D/FRNotices/AC30.htm
http://2017onrr/Laws_R_D/FRNotices/ICR0120.htm
http://2017onrr/Laws_R_D/FRNotices/ICR0107.htm
http://2017onrr/Laws_R_D/FRNotices/ICR0122.htm
http://2017onrr/Laws_R_D/FRNotices/AB57.htm
http://2017onrr/Laws_R_D/FRNotices/ICR0073.htm
http://2017onrr/Laws_R_D/FRNotices/AA17.htm
http://2017onrr/Laws_R_D/FRNotices/AA21.htm
http://2017onrr/Laws_R_D/FRNotices/AA20.htm
http://2017onrr/Laws_R_D/FRNotices/ICR0136.htm

**Comment by mcharg** [comment]
@Baymatt Turns out not all of the FRNs are linked from the FRN page.  I added a bunch more to the spreadsheet that we need Federal Register links for and more will be coming.

**Comment by Maroyafaied** [comment]
@mcharg all look good, I wonder if the press release ones will show once you push live because when I made updates last time they also didn't show in dev and only when I pushed live.

**Comment by Baymatt** [comment]
@mcharg @Maroyafaied The second batch of links are done. There was an odd one where the pdf on the Federal Register website does not match the pdf linked on the spreadsheet. I've added the relevant links below.


60-Day Agency Information Collection - (65 FR 47802--August 3, 2000) https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/47802.pdf


https://www.federalregister.gov/documents/2000/08/03/00-19654/agency-information-collection-activities-proposed-collection-comment-request

**Comment by mcharg** [comment]
@Baymatt @Maroyafaied Thank you both!

**Comment by mcharg** [comment]
@Baymatt I added another batch to the spreadsheet.  I have a few more pages to go through and will have one more (hopefully smaller) batch tomorrow.

That one pdf is strange.  I'll flag it to review with the regulations team.

**Comment by mcharg** [comment]
@Baymatt The last batch is now in the spreadsheet.

**Comment by Baymatt** [comment]
@mcharg The last batch is finished

**Comment by mcharg** [comment]
@Baymatt There are still 36 that we don't have either the url or comments for.  I added a status column and marked them as URL needed.

**Comment by mcharg** [comment]
@Maroyafaied I started updating links on this page, if you want to start checking.

http://2017onrr/Laws_R_D/FRNotices/AD04.htm

Ones not updated because there are open questions for the regs team:
* Federal Oil Valuation Proposed Rule — (68 FR 50087--August 20, 2003)
* 65 FR 38299--June 20, 2000
* 65 FR 37043--June 13, 2000
* 64 FR 73820--December 30, 1999

I made it part way through the Prior to 1998 accordion, so you might want to leave that group for later.

**Comment by mcharg** [comment]
@Baymatt There are two more marked as URL Needed that were linked to the wrong doc on the site.

**Comment by mcharg** [comment]
These pages are ready to review.

- [ ] http://2017onrr/Laws_R_D/FRNotices/AB57.htm
Not updated:
* (76 FR 13431--March 11, 2011)
* (59 FR 39712--August 4, 1994)
<nr>
- [ ] http://2017onrr/Laws_R_D/FRNotices/AC00.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/AD70.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/AD28.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/AC40.htm

- [ ] http://2017onrr/about/NewsReleases.htm (won't show up until pushed live)
June 1, 2010 - Major Portion Prices and Due Date for Additional Royalty Payments on Indian Gas production in Designated Areas Not Associated with and index Zone

- [ ] http://2017onrr/valuation/index.htm
Coal, Federal & Indian, Historical Rulemaking

**Comment by mcharg** [comment]
@Baymatt I found a couple more stragglers marked as URL Needed in the spreadsheet.

**Comment by mcharg** [comment]
175 updated in dev.  136 plus the ones without links and questions to go.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/66a9beba-3133-404a-a542-74df085dd866)

**Comment by mcharg** [comment]
@Maroyafaied I updated the links on the pages below.

- [ ] http://2017onrr/Laws_R_D/FRNotices/AD22.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/AC25.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0088.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/AC51.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0162.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0103.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0087.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0139.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0136.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0073.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0120.htm
Not updated:
* 60-Day Agency Information Collection - (65 FR 47802--August 3, 2000)

**Comment by Maroyafaied** [comment]
@mcharg looks good

**Comment by mcharg** [comment]
@Maroyafaied Did you review them all or just the last set with the checkmarks?

**Comment by Maroyafaied** [comment]
@mcharg I didn't realize there were more since it didn't look like a checklist above. I'll check them as well now.

**Comment by mcharg** [comment]
@Maroyafaied I updated the links on the following pages:

- [ ] http://2017onrr/Laws_R_D/FRNotices/FRICRDisCont.htm
The last row in the table.
<br>
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0119.htm
Not updated:
* Solicitation of comments - (68 FR 47605--August 11, 2003)
<br>
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0090.htm
Not updated:
* 30-Day Agency Information Collection - (66 FR 42235--August 10, 2001)
<br>
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0123.htm
Not updated:
* 64 FR 1930--January 12, 1999)
<br>
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0121.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0140.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0110.htm
<br>
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0074.htm
Not updated:
* 30-Day Agency Information Collection, submitted to OMB - (66 FR 46023--August 31, 2001)
<br>
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0104.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0095.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0075.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0061.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0135.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0129.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0126.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0042.htm
Note updated:
* 30-Day Agency Information Collection — (59 FR 51607 - October 12, 1994)
<br>
- [ ] http://2017onrr/Laws_R_D/FRNotices/AA13.htm
Only updated: Advance Notice of Proposed Rulemaking (76 FR 30878 May 27, 2011) - under Federal Oil and Gas Valuation accordion.
<br>
- [ ] http://2017onrr/Laws_R_D/FRNotices/AB57.htm
Only updated: (76 FR 13431--March 11, 2011) for calendar year 2009

**Comment by Maroyafaied** [comment]
@mcharg looks good
