### ISSUE TITLE
Solid Minerals Reporter Training Agenda 2021

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#623]
Please add the attached agenda at the following location: https://www.onrr.gov/reportpay/training/index.htm

Please list under Training Dates & Information
Solid Minerals Reporter Training April 20th - April 22nd Agenda

[Solid Minerals Reporter Training Agenda 2021.pdf](https://github.com/ONRR/onrr.gov-site/files/6245719/Solid.Minerals.Reporter.Training.Agenda.2021.pdf)

**Comment by Maroyafaied** [comment]
@mcharg I checked the doc and it's accessible.

**Comment by mcharg** [comment]
@bowlenj I added the doc in dev.  Let me know if it's good to push to the live site.  I got rid of the icons on the headers because I didn't have one to add for agendas and it was hard to differentiate the two for videos and presentations.

http://2017onrr/ReportPay/training/index.htm

**Comment by bowlenj** [comment]
This looks great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: mcharg ***@***.***>
Sent: Thursday, April 1, 2021 2:31 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Solid Minerals Reporter Training Agenda 2021 (#623)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C71e2c23ebdae4ed7eafb08d8f54d1cd2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637529058836386628%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=29Ruz8t1kUTdk%2BqKd3WueVzob%2BcqC%2FHv%2BG6q%2FgVq0T4%3D&reserved=0> I added the doc in dev. Let me know if it's good to push to the live site. I got rid of the icons on the headers because I didn't have one to add for agendas and it was hard to differentiate the two for videos and presentations.

http://2017onrr/ReportPay/training/index.htm

-

**Comment by mcharg** [comment]
@bowlenj I pushed this live.  It might take a bit for it to show up on the site.

**Comment by bowlenj** [comment]
Thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: mcharg ***@***.***>
Sent: Friday, April 2, 2021 7:55 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Solid Minerals Reporter Training Agenda 2021 (#623)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C73aedaedab1e498cc90208d8f5def06d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637529685155936255%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3xe%2FzWWuQKl%2B%2F9XiMnXl8mwFENlVmLo8adp%2BtzW%2FJfw%3D&reserved=0> I pushed this live. It might take a bit for it to show up on the site.

-
