### ISSUE TITLE
Cross Reference Lease to Agreement

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#625]
Please update the following webpage - https://www.onrr.gov/reportpay/CrossRef.htm

Cross-Reference Lease to Agreement Numbers sorted by Agreement Name
Cross-Reference Lease to Agreement Numbers sorted by Agreement Number
Cross-Reference Lease to Agreement Numbers sorted by Lease Number

with the attached excel files.  Please also change (updated 1/04/2021) to (updated 04/01/2021)
[CRAName.xlsx](https://github.com/ONRR/onrr.gov-site/files/6246200/CRAName.xlsx)
[CRANumber.xlsx](https://github.com/ONRR/onrr.gov-site/files/6246209/CRANumber.xlsx)
[CRLNumber.xlsx](https://github.com/ONRR/onrr.gov-site/files/6246211/CRLNumber.xlsx)

**Comment by Maroyafaied** [comment]
@bowlenj Please review http://2017onrr/ReportPay/CrossRef.htm

**Comment by bowlenj** [comment]
Looks good!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: Maroyafaied ***@***.***>
Sent: Friday, April 2, 2021 7:59 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Cross Reference Lease to Agreement (#625)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C6dca1e3d433847aa91e308d8f5df87b8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637529687704572147%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ueMxxUBomd1l4r%2BKstRxiCCkmDZRBCHAAD4vH5a1XMU%3D&reserved=0> Please review http://2017onrr/ReportPay/CrossRef.htm

-

**Comment by Maroyafaied** [comment]
it's live.
