### ISSUE TITLE
Non Accessible document

### ISSUE THREAD

**Issue by Sheetsj** [ONRR/onrr.gov-site#626]
There is a document on ONRR.Gov  that is coming up on the list of Non-Accessible documents. We are not able to find this document where they are saying it is located. Which is:  https://www.onrr.gov/ReportPay/PDFDocs/finserAssign.pd. This will need to be deleted. 

Now this is the same name of the document that we use to update the Contacts under Contact US or Payments. So we do not want that file to be deleted.  This file is updated and is 508 compliant. 

We believe that the document from the link is an old document that might be somewhere on the backend where we can not locate it. 

Thank you 

Jessica

**Comment by mcharg** [comment]
@Sheetsj Can I replace the doc referenced above with this one, which has been made accessible?
https://www.onrr.gov/ReportPay/PDFDocs/FSFederalCOAssignm.pdf

**Comment by Sheetsj** [comment]
Yes that is the updated one. So when I update the contacts should I also have this one changed as well? We don't really know where it is located at. We just want all the docs to be correct on the site. 

Thank you!

**Comment by mcharg** [comment]
@Sheetsj I'll change the link where this one is (on the Payments page) to point to the same one that's on the contacts page.  That way, when we change the doc for contacts, it'll update it in all the places.

**Comment by mcharg** [comment]
@Sheetsj It looks like somebody already swapped out the link on the Payments page, so this doc is no longer linked on the site.  I'll put it in an archive folder.

**Comment by Sheetsj** [comment]
When we looked on the payment page earlier it showed that it was changed when we change the contacts. But this report that keeps coming out is saying that other doc that is not working still shows up. Do you think that this report is old or do you think that this doc is showing up somewhere else?

**Comment by mcharg** [comment]
I had it as only on the Payments page in our content inventory.  I think it got swapped out with the newer doc after we did the inventory.

**Comment by Sheetsj** [comment]
Okay so do we think that bad doc is gone from the site now? I want to make sure before I tell my boss it is gone.

**Comment by mcharg** [comment]
Yep, it's gone.

**Comment by Sheetsj** [comment]
Thank you so much for your help in this.
