### ISSUE TITLE
Documents to delete

### ISSUE THREAD

**Issue by jpetersononrr** [ONRR/onrr.gov-site#627]
The following links/documents are on our Phase 2 list to be converted for 508 compliance.  We have decided these can be deleted.  Thanks!

https://www.onrr.gov/PDFDocs/DearReporterTraining_3-11.pdf

https://www.onrr.gov/PDFDocs/dear-reporter-letter-30-june-2020.pdf

https://www.onrr.gov/valuation/PDFDocs/Processed-gas-example-for-2016-rule-20191112.pdf

https://www.onrr.gov/ReportPay/training/TrainingFiles/OK_Report_Training/AdvancedUnbundling.pdf

https://www.onrr.gov/Valuation/PDFDocs/NewIndianOil_ReporterTraining_June182015.pdf

https://www.onrr.gov/ReportPay/training/pdfdocs/2019_Denver/Unbundling_Basic_Topics.pdf

https://www.onrr.gov/About/PDFDocs/ChrisCareyPASO2015FieldFuel.pdf

https://www.onrr.gov/valuation/PDFDocs/Example-processed-gas-plant-statement.pdf

https://www.onrr.gov/ReportPay/PDFDocs/stepscale.pdf

Thank you!

**Comment by mcharg** [comment]
@jpetersononrr These are all removed in dev.  Let me know if it's good to post the changes to the live site.
http://2017onrr/

**Comment by jpetersononrr** [comment]
That works for me.  We discussed them beforehand, and I have a list if someone goes "where'd those go?!".  Thanks!

**Comment by mcharg** [comment]
These changes are posted to the live site.  Might be a bit before they show up.
