### ISSUE TITLE
RV Phase 2 documents for upload

### ISSUE THREAD

**Issue by jpetersononrr** [ONRR/onrr.gov-site#628]
We had an original list of 34 documents.  I just had 9 deleted.  Attached are 22 to finish that list.  I believe your crew has access to the Phase 2 - John Barder spreadsheet?  If you do, these are the green ones.  Thanks!

- [x] [Indian-Payor-Handbook-Chapter-2-Valuation-Basics-4.2019.pdf](https://github.com/ONRR/onrr.gov-site/files/6250285/Indian-Payor-Handbook-Chapter-2-Valuation-Basics-4.2019.pdf)

- [x] [20150515.pdf](https://github.com/ONRR/onrr.gov-site/files/6250287/20150515.pdf)

- [x] [Blacks Fork UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6250289/Blacks.Fork.UCA.pdf)

- [x] [Carlsbad Gathering and Dew Point UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6250290/Carlsbad.Gathering.and.Dew.Point.UCA.pdf)

- [x] [Chipeata Gas Plant UCA (002).pdf](https://github.com/ONRR/onrr.gov-site/files/6250291/Chipeata.Gas.Plant.UCA.002.pdf)

- [x] [dear-reporter-letter-30-june-2020.pdf](https://github.com/ONRR/onrr.gov-site/files/6250292/dear-reporter-letter-30-june-2020.pdf)

- [x] [DRL_Transportation_Systems_and_Processing_Plants_October_6_2010.pdf](https://github.com/ONRR/onrr.gov-site/files/6250293/DRL_Transportation_Systems_and_Processing_Plants_October_6_2010.pdf)

- [x] [Echo Springs Gas Plant UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6250294/Echo.Springs.Gas.Plant.UCA.pdf)

- [x] [Green River Basin Standard UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6250295/Green.River.Basin.Standard.UCA.pdf)

- [x] [How-to-calculate-a-Processing-UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6250296/How-to-calculate-a-Processing-UCA.pdf)

- [x] [Opal UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6250298/Opal.UCA.pdf)

- [x] [Kutz Gas Plant and Torre Alta transport UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6250299/Kutz.Gas.Plant.and.Torre.Alta.transport.UCA.pdf)

- [x] [Meeker Gas Plant.pdf](https://github.com/ONRR/onrr.gov-site/files/6250301/Meeker.Gas.Plant.pdf)

- [x] [Neptune Gas Plant UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6250303/Neptune.Gas.Plant.UCA.pdf)

- [x] [Offshore Standard UCA with Cryogenic Example.pdf](https://github.com/ONRR/onrr.gov-site/files/6250306/Offshore.Standard.UCA.with.Cryogenic.Example.pdf)

- [x] [Willow Creek UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6250308/Willow.Creek.UCA.pdf)

- [x] [ReporterLetter_KeepwholeGasProcessingContracts.pdf](https://github.com/ONRR/onrr.gov-site/files/6250309/ReporterLetter_KeepwholeGasProcessingContracts.pdf)

- [x] [San Juan Basin Blanco UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6250310/San.Juan.Basin.Blanco.UCA.pdf)

- [x] [San Juan Basin Standardized UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6250311/San.Juan.Basin.Standardized.UCA.pdf)

- [x] [San Juan Conventional Transportation Sysytem - Ignacio Gas Plant.pdf](https://github.com/ONRR/onrr.gov-site/files/6250312/San.Juan.Conventional.Transportation.Sysytem.-.Ignacio.Gas.Plant.pdf)

- [x] [UCA-calculations-accounting-and-contract-data-needs.pdf](https://github.com/ONRR/onrr.gov-site/files/6250313/UCA-calculations-accounting-and-contract-data-needs.pdf)

- [x] [Venice Gas Plant.pdf](https://github.com/ONRR/onrr.gov-site/files/6250314/Venice.Gas.Plant.pdf)

- [x] [12_04_19_IndianGasMajorPortion_508.pdf](https://github.com/ONRR/onrr.gov-site/files/6250319/12_04_19_IndianGasMajorPortion_508.pdf)

- [x] [12_04_19 _IndianOilMajorPortion_508.pdf](https://github.com/ONRR/onrr.gov-site/files/6250320/12_04_19._IndianOilMajorPortion_508.pdf)

- [x] [12_04_19_IndianGasIndexZone_508.pdf](https://github.com/ONRR/onrr.gov-site/files/6250321/12_04_19_IndianGasIndexZone_508.pdf)

**Comment by Maroyafaied** [comment]
@mcharg please note in the tracking sheet that RV still has 3 remaining docs that they plan to correct after a month when they complete a training class on remediating PDFs next month .  The 3 docs are the Processed Gas example, it’s related statement, nor the Indian Gas Payor Handbook Chapter 3

**Comment by Maroyafaied** [comment]
@Maroyafaied I will check the accessibility and @mcharg will upload them and update status on tracking sheet.

**Comment by mcharg** [comment]
@jpetersononrr dear-reporter-letter-30-june-2020.pdf is also listed on the issue to be removed.  Should it be removed or replaced?

**Comment by Maroyafaied** [comment]
@jpetersononrr only 4 documents passed the accessibility checks, I send you and Noelle an email. Please let us know once the other documents are corrected.

**Comment by Maroyafaied** [comment]
@mcharg I'm adding Jodi's email as a part of this issue. 
"We in error requested that this file be removed:  https://www.onrr.gov/PDFDocs/dear-reporter-letter-30-june-2020.pdf. It is not fully compliant, but as it has been signed and time stamped it cannot be edited to be compliant.  Based on my discussions with Sid, an acceptable alternative is to also post a compliant version of a document labeled “accessible.”  I have created such a Word document version of the letter to be posted with the signed Dear Reporter letter.  It is locked for editing."
[Dear Reporter Letter 2016 Rule Extension 2020 06 26 Accessible (1).docx](https://github.com/ONRR/onrr.gov-site/files/6306795/Dear.Reporter.Letter.2016.Rule.Extension.2020.06.26.Accessible.1.docx)

**Comment by mcharg** [comment]
@Maroyafaied @jpetersononrr I updated the reporter letter in dev.  Let me know if you like what I did for the accessible version and if it's good to post to the live site.
http://2017onrr/DearRep.htm

**Comment by jpetersononrr** [comment]
That looks good to me!  Can you make sure the link on the reporter letters section on the home page works as well?  Thanks!!

​Jodie Peterson
Minerals Revenue Specialist
Office of Natural Resources Revenue
***@***.***
(303)231-3719

Royalty Valuation - Consistent Answers to Complex Questions

From: mcharg ***@***.***>
Sent: Wednesday, April 14, 2021 6:46 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Peterson, Jodie F ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] RV Phase 2 documents for upload (#628)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Maroyafaied<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMaroyafaied&data=04%7C01%7Cjodie.peterson%40onrr.gov%7C5dbdec2f2a2a4fe27f2d08d8ff444da2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637540016118463686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Pt2PrkKLAnf17npop0uCtZ%2BOaNgIxIPmu4zOnyRk0yE%3D&reserved=0> @jpetersononrr<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjpetersononrr&data=04%7C01%7Cjodie.peterson%40onrr.gov%7C5dbdec2f2a2a4fe27f2d08d8ff444da2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637540016118473645%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5ed4RUAEFZidDxZhILAUXv2FsriI9gobSoknH1sCvV0%3D&reserved=0> I updated the reporter letter in dev. Let me know if you like what I did for the accessible version and if it's good to post to the live site.
http://2017onrr/DearRep.htm

**Comment by mcharg** [comment]
@jpetersononrr I will fix the link on the homepage.  I'll see if we can get a second link on that for the accessible version.  If not, we may take that tab out of the homepage.  Very few people click on it, anyway.

**Comment by mcharg** [comment]
@jpetersononrr The reporter letter is live.  The link is fixed on the homepage, but I didn't see a way to add the accessible version to that list.  Will discuss removing that tab with Maroya.

**Comment by mcharg** [comment]
@jpetersononrr The 4 docs marked as accessible above have been replaced.  It might be a bit before they show up on the live site.

**Comment by jpetersononrr** [comment]
I've added table summaries to all of these.  Should be all the ones on the list.  Thanks!
[12_04_19_IndianGasMajorPortion_508.pdf](https://github.com/ONRR/onrr.gov-site/files/6361198/12_04_19_IndianGasMajorPortion_508.pdf)
[20150515.pdf](https://github.com/ONRR/onrr.gov-site/files/6361199/20150515.pdf)
[Blacks Fork UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6361201/Blacks.Fork.UCA.pdf)
[Carlsbad Gathering and Dew Point UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6361202/Carlsbad.Gathering.and.Dew.Point.UCA.pdf)
[Chipeata Gas Plant UCA (002).pdf](https://github.com/ONRR/onrr.gov-site/files/6361203/Chipeata.Gas.Plant.UCA.002.pdf)
[Echo Springs Gas Plant UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6361204/Echo.Springs.Gas.Plant.UCA.pdf)
[Green River Basin Standard UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6361205/Green.River.Basin.Standard.UCA.pdf)
[How-to-calculate-a-Processing-UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6361206/How-to-calculate-a-Processing-UCA.pdf)
[Kutz Gas Plant and Torre Alta transport UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6361207/Kutz.Gas.Plant.and.Torre.Alta.transport.UCA.pdf)
[Meeker Gas Plant.pdf](https://github.com/ONRR/onrr.gov-site/files/6361208/Meeker.Gas.Plant.pdf)
[Neptune Gas Plant UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6361209/Neptune.Gas.Plant.UCA.pdf)
[Offshore Standard UCA with Cryogenic Example.pdf](https://github.com/ONRR/onrr.gov-site/files/6361210/Offshore.Standard.UCA.with.Cryogenic.Example.pdf)
[Opal UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6361211/Opal.UCA.pdf)
[ReporterLetter_KeepwholeGasProcessingContracts.pdf](https://github.com/ONRR/onrr.gov-site/files/6361212/ReporterLetter_KeepwholeGasProcessingContracts.pdf)
[San Juan Basin Blanco UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6361214/San.Juan.Basin.Blanco.UCA.pdf)
[San Juan Basin Standardized UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6361215/San.Juan.Basin.Standardized.UCA.pdf)
[San Juan Conventional Transportation Sysytem - Ignacio Gas Plant.pdf](https://github.com/ONRR/onrr.gov-site/files/6361217/San.Juan.Conventional.Transportation.Sysytem.-.Ignacio.Gas.Plant.pdf)
[UCA-calculations-accounting-and-contract-data-needs.pdf](https://github.com/ONRR/onrr.gov-site/files/6361218/UCA-calculations-accounting-and-contract-data-needs.pdf)
[Venice Gas Plant.pdf](https://github.com/ONRR/onrr.gov-site/files/6361219/Venice.Gas.Plant.pdf)
[Willow Creek UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6361220/Willow.Creek.UCA.pdf)

**Comment by mcharg** [comment]
@jpetersononrr The Green River Basin doc has some issues with the tables.
![image](https://user-images.githubusercontent.com/38465926/116111150-5c568500-a684-11eb-946d-98b9f0d4575b.png)

**Comment by mcharg** [comment]
@jpetersononrr All of these except for the Green River one are updated.  It might be a bit before they show up on the live site.

**Comment by jpetersononrr** [comment]
Hi,

When I try to correct the phantom table (because nothing is highlighted when I click on it), it then says that various words have character issues.  So I don’t have a good answer for this one…

​Jodie Peterson
Minerals Revenue Specialist
Office of Natural Resources Revenue
***@***.***
(303)231-3719

Royalty Valuation - Consistent Answers to Complex Questions

From: mcharg ***@***.***>
Sent: Friday, May 7, 2021 7:36 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Peterson, Jodie F ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] RV Phase 2 documents for upload (#628)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jpetersononrr<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjpetersononrr&data=04%7C01%7Cjodie.peterson%40onrr.gov%7C262db4db51884728d7bb08d9115d0fc1%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637559913685526724%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=94ty1pltDxNEHp8KACUVBVJxHBQzXxltnUS8BLxlseM%3D&reserved=0> Are you going to send the updated Green River doc?

**Comment by mcharg** [comment]
@jpetersononrr Are you starting from a Word doc you can send me and I can see if I can figure it out?

**Comment by mcharg** [comment]
@jpetersononrr Can you send me your source doc, so I can try to help?

**Comment by mcharg** [comment]
@jpetersononrr I was able to clear the errors by removing what appeared to be empty table tags.  Does this look good to you?
[https://app.zenhub.com/files/210892300/d122d854-4c6c-4a9d-964c-b3c85e784e6f/download](https://app.zenhub.com/files/210892300/d122d854-4c6c-4a9d-964c-b3c85e784e6f/download)

**Comment by jpetersononrr** [comment]
Thank you!

Apologies as I was out for a week.  I couldn’t get rid of the table tag without breaking a million other things.  That works for me!

​Jodie Peterson
Minerals Revenue Specialist
Office of Natural Resources Revenue
***@***.***
(303)231-3719

Royalty Valuation - Consistent Answers to Complex Questions

From: mcharg ***@***.***>
Sent: Wednesday, June 9, 2021 1:15 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Peterson, Jodie F ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] RV Phase 2 documents for upload (#628)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jpetersononrr<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjpetersononrr&data=04%7C01%7Cjodie.peterson%40onrr.gov%7C5a443cb8274040bbe13608d92b7b0442%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637588629627528001%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Pge88xh8Ry9muEqkQLfbznY7msP9sgDfX1FyIMTrv4w%3D&reserved=0> I was able to clear the errors by removing what appeared to be empty table tags. Does this look good to you?
https://app.zenhub.com/files/210892300/d122d854-4c6c-4a9d-964c-b3c85e784e6f/download<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapp.zenhub.com%2Ffiles%2F210892300%2Fd122d854-4c6c-4a9d-964c-b3c85e784e6f%2Fdownload&data=04%7C01%7Cjodie.peterson%40onrr.gov%7C5a443cb8274040bbe13608d92b7b0442%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637588629627528001%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nUdMCNROwIHAp%2FsAlq231n08nb3%2BrmJjnyTXU6g8Hto%3D&reserved=0>

**Comment by mcharg** [comment]
@jpetersononrr The Green River file is not updated on the site.  Might be a bit before it shows up on the live site.
