### ISSUE TITLE
Remove 2 docs from Robert Winter's list in phase 1

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#630]
They confirmed to remove these two documents.

https://www.onrr.gov/IndianServices/pdfdocs/Calendar-Year-2020-DistDates.pdf

https://www.onrr.gov/ReportPay/PDFDocs/finserAssign.pdf

**Comment by mcharg** [comment]
Done.  There's nothing to review, since neither of these docs are linked on the site.
