### ISSUE TITLE
Overlap Presentation

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#631]
Please add this presentation to the list of Training Presentations - https://www.onrr.gov/ReportPay/training/index.htm
[2020 Overalp Training_WebEx.pptx](https://github.com/ONRR/onrr.gov-site/files/6250889/2020.Overalp.Training_WebEx.pptx)

**Comment by mcharg** [comment]
@bowlenj The accessibility looks good on this. I'll get it uploaded tomorrow.

**Comment by bowlenj** [comment]
Thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: mcharg ***@***.***>
Sent: Monday, April 5, 2021 2:51 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Overlap Presentation (#631)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cc6a648b7d91a40ef61b908d8f874970f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637532526924158852%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BRPXD%2BzbEKaY3w2myhqCBx7t2lkJbMuaD%2FqaUI%2FD3wU%3D&reserved=0> The accessibility looks good on this. I'll get it uploaded tomorrow.

-

**Comment by mcharg** [comment]
@bowlenj This is updated in dev.  Let me know if it's good to post to the live site.
http://2017onrr/ReportPay/training/index.htm

**Comment by bowlenj** [comment]
Looks great!  Thank you 😊

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: mcharg ***@***.***>
Sent: Tuesday, April 6, 2021 8:34 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Overlap Presentation (#631)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C70ba9f20364d4a25f5e308d8f909036b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637533164399507574%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XSUwaq0ezNt0lGygoeRPtXb%2BaXKJS6GqyiAaXGkiPV4%3D&reserved=0> This is updated in dev. Let me know if it's good to post to the live site.
http://2017onrr/ReportPay/training/index.htm

**Comment by mcharg** [comment]
Pushed to the live site.
