### ISSUE TITLE
ONRR.gov/Reporting Paying/Production Reporting/Production Reporting References/ Offshore

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#633]
This request came from the onrrweb mailbox , the 5 files are in the email. 

All,
   On the ONRR.gov home page, please update the Production Reporting References with the attached files. The new as of date is 02 Apr 2021.
There are five Gulf files.

Thank you,

Johnny Erle

Reference, Royalty, and Production Team 1A - Production Specialist (GVS)
Reference and Reporting Management
Office of Natural Resources Revenue
Office: (303) 231-3577

**Comment by mcharg** [comment]
@Maroyafaied The accessibility looks good on these docs.  I'll get them uploaded tomorrow.

**Comment by mcharg** [comment]
Approved and pushed to the live site.
