### ISSUE TITLE
check for final 508 compliance 

### ISSUE THREAD

**Issue by evabauer-onrr** [ONRR/onrr.gov-site#634]
Hello,

Please check for final 508 compliance for the attached file:
ONRR_Esternal_User_Acceptable_Use_Policy1.pdf
[ONRR_External_User_Acceptable_Use_Policy1.pdf](https://github.com/ONRR/onrr.gov-site/files/6259292/ONRR_External_User_Acceptable_Use_Policy1.pdf)

**Comment by lyokomizo** [comment]
Here is the file corrected
[ONRR_External_User_Acceptable_Use_Policy1.pdf](https://github.com/ONRR/onrr.gov-site/files/6259414/ONRR_External_User_Acceptable_Use_Policy1.pdf)

**Comment by mcharg** [comment]
Is this the same document referenced in #560?

**Comment by mcharg** [comment]
@evabauer-onrr @lyokomizo The accessibility looks good on this.  I'll get it uploaded tomorrow.

**Comment by evabauer-onrr** [comment]
Yes, I wanted to also learn how to use the GitHub system and did not know if Lori would be able to submit the document this week, which was due last week.

Thank you.

From: mcharg ***@***.***>
Sent: Monday, April 5, 2021 2:44 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bauer, Eva M ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] check for final 508 compliance (#634)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Is this the same document referenced in #560<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F560&data=04%7C01%7Ceva.bauer%40onrr.gov%7C0328a9ae866e40bd5c9708d8f8738a93%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637532522425541593%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OznPYAoE6PblVCq5hmcMCpzKanckAPSlb7zwgulim6E%3D&reserved=0>?

-

**Comment by mcharg** [comment]
@evabauer-onrr @lyokomizo I posted the updated doc.  It might be a bit before it shows up on the live site.
