### ISSUE TITLE
Style tile revisions and mock up one sample page

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#637]

**Comment by abudz19** [comment]
**3 versions of about page**
Please note there are three different primary navigation spacing treatments, one per version
[About page v1 - midsize nav.pdf](https://github.com/ONRR/onrr.gov-site/files/6320460/About.page.v1.-.midsize.nav.pdf)
[About page v2 - smallest nav.pdf](https://github.com/ONRR/onrr.gov-site/files/6320463/About.page.v2.-.smallest.nav.pdf)
[About page v3 - large size nav.pdf](https://github.com/ONRR/onrr.gov-site/files/6320465/About.page.v3.-.large.size.nav.pdf)

About Page v2 & v3 w/out sample image
[About page v2 - smallest nav - image placeholder.pdf](https://github.com/ONRR/onrr.gov-site/files/6320461/About.page.v2.-.smallest.nav.-.image.placeholder.pdf)
[About page v3 - large size nav - placeholder image.pdf](https://github.com/ONRR/onrr.gov-site/files/6320464/About.page.v3.-.large.size.nav.-.placeholder.image.pdf)

**Comparison between squared vs rounded edges**
<img width="707" alt="material-design-stickersheet_sketch" src="https://user-images.githubusercontent.com/11526811/114923672-1afbe500-9dfb-11eb-9a9c-03cf2b173b5f.png">
