### ISSUE TITLE
onrr.gov/ReportPay/contacts.htm

### ISSUE THREAD

**Issue by LisaReimer** [ONRR/onrr.gov-site#639]
https://www.onrr.gov/ReportPay/contacts.htm

The 1-800 number and extension under my name goes to Alexis Long in OE.  Dallas does not have a 1-800 number.  Please remove.  See attached.  Thank you. 

Lisa Reimer
Minerals Revenue Specialist - Production Analyst
Reference, Royalty and Production, Team 4B
Reference and Reporting Management
Office of Natural Resources Revenue
Office Phone:  214-640-9049

[onrr.gov - ReportPay - contacts.htm.docx](https://github.com/ONRR/onrr.gov-site/files/6265061/onrr.gov.-.ReportPay.-.contacts.htm.docx)

**Comment by Maroyafaied** [comment]
@lisareimer please review http://2017onrr/ReportPay/contacts.htm

**Comment by LisaReimer** [comment]
Perfect!  Thank  you!
One more thing...is it possible to move Michael Nestlehut's name up to the same line as the letter icon  (see below)?  If not, no worries.

[cid:559d7e7e-e03c-45de-bb3a-7a4b0288bf4f]

...

Respectfully,

Lisa Reimer
Minerals Revenue Specialist - Production Analyst
Reference, Royalty and Production, Team 4B
Reference and Reporting Management
Office of Natural Resources Revenue
Office Phone:  214-640-9049
Fax:  303-445-9547


Please note **ONRR is bound by lease terms and therefore, pursuant to 30 CFR:  For production reporting of oil, gas and geothermal resources on Federal lands, Indian lands, and in the Outer Continental Shelf, per 30 CFR §1210.103, production forms (Form ONRR-4054, Oil and Gas Operations Report, and Form ONRR-4058, Production Allocation Schedule Report) must be received by ONRR by the 15th day of the second month following the month for which you are reporting.**


SELF-HELP LINKS:

  *   **New** Online EMARF here<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Femarf.onrr.gov%2Femarf&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542895181%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9tpVSPHQiPeBdAJ6jNIRckNy7ywCP0tkmfBXR6wBlyw%3D&reserved=0>!
  *   Help with REPORTING here<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2FReportPay%2Froyalty-reporting.htm&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542905139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=919ifU%2Bh08yj1CY7aNWptnvTMWCW%2F8TZ3bCnWd544XM%3D&reserved=0>!
  *   Data Warehouse (E-Commerce, Invoices, eSoa, etc.)<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsso.onrr.gov%2Foaam_server%2Flogin.do&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542905139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ImLZGDDsSDt6s3YSEHCxRY7wpCENnwxvRrCZD7zjuHo%3D&reserved=0>
  *   Reporter handbooks<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2Freportpay%2FHandbooks%2Findex.htm&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542915097%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EgrQCW7lTBj0gvganvJR1gkXTI2oGAKYyhw9jSZEucg%3D&reserved=0>
  *   Guidance on adjustments, recoupments & refunds<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2FReportPay%2FHandbooks%2Fpdfdocs%2FMRRH-Chapter-6.pdf&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542915097%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MXRu7Gsu3Jax0UnpY3yJFJ26I6P6YbXtWYMCJf400Ig%3D&reserved=0>
  *   Lease (STATUS & MAINTENANCE) click here<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2FReportPay%2FPDFDocs%2FRS_LeAgAssignments.pdf&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542915097%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=z%2F7owWW6iIW6HdtHc3v0mGTT2y6ztxTNC8LFmqxT4Wg%3D&reserved=0>!
  *   Access to the system/update your info here<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2Freportpay%2Fforms%2Findex.htm&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542925049%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AsWvPCT1rLMO2XuYBTR8ndGnDLXzChvJlsU2xxUgyV0%3D&reserved=0>! (EMARF/4444/SURETY/W-9)
  *   Help with PAYMENTS here<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2Freportpay%2Fpayments.htm&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542925049%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jdm21YHcrJxVN5XrdHr8Bl3D4N%2FfZMDxd8ofcMpVpRk%3D&reserved=0>!
  *   Help with a ‘Demand to Pay’ or ‘Potential Treasury Referral’ here<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2FReportPay%2FPDFDocs%2FDebtCollectionAssign.pdf&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542935009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UHEGmLOua6%2FiwnAFxa7VX1Gwz95d6Pf5aPSpVtJNzOU%3D&reserved=0>!
  *   Federal Accounts Receivable Contacts<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2FReportPay%2FPDFDocs%2FfinserAssign.pdf&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542935009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=u3LKeart1Xqd32xNeYmLsCQx8ytIKhH26GhMtoheRHY%3D&reserved=0>
  *   Indian Accounts Receivable Contacts<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2FReportPay%2FPDFDocs%2FFSIndianCoAssign.pdf&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542935009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DCu%2BIQEGAvhWfJB0EwXRKcuCtdoSxHqzll8ijviDPr4%3D&reserved=0>
  *   Password resets/System issues-contact the help desk at 303-231-3333 or ***@***.******@***.***>
  *   For help with 2014's: Royalty Reporting Contacts<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.onrr.gov%2FReportPay%2FPDFDocs%2Froyassign.pdf&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542944962%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MDy6sJSXpnLRkdiBgwQGcgeIdvumgnkK2bu8hHeua08%3D&reserved=0>
  *   For help with OGOR's: Production Reporting Contacts<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.onrr.gov%2FReportPay%2FPDFDocs%2Foperasgn.pdf&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542944962%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=me0zy8SnauPbEhMhTy7p0tcC%2BrsdsigW7tDQvOJZdok%3D&reserved=0>
  *   For help with Lease/Agreement Reporting: Lease Agreement Reporting Contacts<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.onrr.gov%2FReportPay%2FPDFDocs%2FRS_LeAgAssignments.pdf&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542954916%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jCV3%2FNLyTuZRTa8UikcwiGPTUQLgv5N4CzAByokxAus%3D&reserved=0>









________________________________
From: Maroyafaied ***@***.***>
Sent: Wednesday, April 7, 2021 15:05
To: ONRR/onrr.gov-site ***@***.***>
Cc: Reimer, Lisa F ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] onrr.gov/ReportPay/contacts.htm (#639)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@LisaReimer<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLisaReimer&data=04%7C01%7Clisa.reimer%40onrr.gov%7C4331cd798cd449ff903808d8fa00afad%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637534228158896441%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AKf32xvQ2umUF0k1c5PpM3qcV9i30ps%2F%2BEdNbRntd9M%3D&reserved=0> please review http://2017onrr/ReportPay/contacts.htm

**Comment by Maroyafaied** [comment]
@LisaReimer I tried but unfortunately the email address is too long and doesn't fit. I'll put the changes live , you should see it in 30 min. Thanks

**Comment by LisaReimer** [comment]
Thank you!!  🙂

Respectfully,

Lisa Reimer
Minerals Revenue Specialist - Production Analyst
Reference, Royalty and Production, Team 4B
Reference and Reporting Management
Office of Natural Resources Revenue
Office Phone:  214-640-9049
Fax:  303-445-9547


Please note **ONRR is bound by lease terms and therefore, pursuant to 30 CFR:  For production reporting of oil, gas and geothermal resources on Federal lands, Indian lands, and in the Outer Continental Shelf, per 30 CFR §1210.103, production forms (Form ONRR-4054, Oil and Gas Operations Report, and Form ONRR-4058, Production Allocation Schedule Report) must be received by ONRR by the 15th day of the second month following the month for which you are reporting.**


SELF-HELP LINKS:

  *   **New** Online EMARF here<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Femarf.onrr.gov%2Femarf&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542895181%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9tpVSPHQiPeBdAJ6jNIRckNy7ywCP0tkmfBXR6wBlyw%3D&reserved=0>!
  *   Help with REPORTING here<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2FReportPay%2Froyalty-reporting.htm&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542905139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=919ifU%2Bh08yj1CY7aNWptnvTMWCW%2F8TZ3bCnWd544XM%3D&reserved=0>!
  *   Data Warehouse (E-Commerce, Invoices, eSoa, etc.)<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsso.onrr.gov%2Foaam_server%2Flogin.do&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542905139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ImLZGDDsSDt6s3YSEHCxRY7wpCENnwxvRrCZD7zjuHo%3D&reserved=0>
  *   Reporter handbooks<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2Freportpay%2FHandbooks%2Findex.htm&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542915097%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EgrQCW7lTBj0gvganvJR1gkXTI2oGAKYyhw9jSZEucg%3D&reserved=0>
  *   Guidance on adjustments, recoupments & refunds<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2FReportPay%2FHandbooks%2Fpdfdocs%2FMRRH-Chapter-6.pdf&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542915097%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MXRu7Gsu3Jax0UnpY3yJFJ26I6P6YbXtWYMCJf400Ig%3D&reserved=0>
  *   Lease (STATUS & MAINTENANCE) click here<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2FReportPay%2FPDFDocs%2FRS_LeAgAssignments.pdf&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542915097%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=z%2F7owWW6iIW6HdtHc3v0mGTT2y6ztxTNC8LFmqxT4Wg%3D&reserved=0>!
  *   Access to the system/update your info here<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2Freportpay%2Fforms%2Findex.htm&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542925049%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AsWvPCT1rLMO2XuYBTR8ndGnDLXzChvJlsU2xxUgyV0%3D&reserved=0>! (EMARF/4444/SURETY/W-9)
  *   Help with PAYMENTS here<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2Freportpay%2Fpayments.htm&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542925049%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jdm21YHcrJxVN5XrdHr8Bl3D4N%2FfZMDxd8ofcMpVpRk%3D&reserved=0>!
  *   Help with a ‘Demand to Pay’ or ‘Potential Treasury Referral’ here<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2FReportPay%2FPDFDocs%2FDebtCollectionAssign.pdf&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542935009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UHEGmLOua6%2FiwnAFxa7VX1Gwz95d6Pf5aPSpVtJNzOU%3D&reserved=0>!
  *   Federal Accounts Receivable Contacts<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2FReportPay%2FPDFDocs%2FfinserAssign.pdf&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542935009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=u3LKeart1Xqd32xNeYmLsCQx8ytIKhH26GhMtoheRHY%3D&reserved=0>
  *   Indian Accounts Receivable Contacts<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.onrr.gov%2FReportPay%2FPDFDocs%2FFSIndianCoAssign.pdf&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542935009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DCu%2BIQEGAvhWfJB0EwXRKcuCtdoSxHqzll8ijviDPr4%3D&reserved=0>
  *   Password resets/System issues-contact the help desk at 303-231-3333 or ***@***.******@***.***>
  *   For help with 2014's: Royalty Reporting Contacts<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.onrr.gov%2FReportPay%2FPDFDocs%2Froyassign.pdf&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542944962%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MDy6sJSXpnLRkdiBgwQGcgeIdvumgnkK2bu8hHeua08%3D&reserved=0>
  *   For help with OGOR's: Production Reporting Contacts<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.onrr.gov%2FReportPay%2FPDFDocs%2Foperasgn.pdf&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542944962%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=me0zy8SnauPbEhMhTy7p0tcC%2BrsdsigW7tDQvOJZdok%3D&reserved=0>
  *   For help with Lease/Agreement Reporting: Lease Agreement Reporting Contacts<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.onrr.gov%2FReportPay%2FPDFDocs%2FRS_LeAgAssignments.pdf&data=04%7C01%7CLisa.Reimer%40onrr.gov%7Cd8d4a90b7429433c134308d8c3b66af8%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637474535542954916%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jCV3%2FNLyTuZRTa8UikcwiGPTUQLgv5N4CzAByokxAus%3D&reserved=0>









________________________________
From: Maroyafaied ***@***.***>
Sent: Thursday, April 8, 2021 15:29
To: ONRR/onrr.gov-site ***@***.***>
Cc: Reimer, Lisa F ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] onrr.gov/ReportPay/contacts.htm (#639)




@LisaReimer<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLisaReimer&data=04%7C01%7Clisa.reimer%40onrr.gov%7C71da8df227f14f04130d08d8facd0ed2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637535105913552030%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xuUIo%2FtmP334ucnH625WZDiaE4IDXvY4nHYaaHF83VE%3D&reserved=0> I tried but unfortunately the email address is too long and doesn't fit. I'll put the changes live , you should see it in 30 min. Thanks
