### ISSUE TITLE
Remove broken press release links

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#643]
These three links in 2010 are broken.

http://www.boemre.gov/offshore/PDFs/GOMESAFY2010Final.pdf
http://www.onrr.gov/FM/PDFDocs/20091106.pdf
http://www.onrr.gov/AssetManagement/PDFDocs/FY09RIKAnnualReport.pdf

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/8bfd8f62-afea-402f-918c-a790ffe51903)

**Comment by Maroyafaied** [comment]
@mentastc can you please help us find the correct links? or let us know if they should be removed. Thanks

**Comment by mcharg** [comment]
@mentastc These are removed both in dev and the live site, since the press release changes don't show up in dev.  Let me know if you notice any issues.
