### ISSUE TITLE
Update Indian Major Portion Prices on onrr.gov

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#645]
Good morning,

We need to update the Major Portion Pricing on onrr.gov. The relevant data is the section with the "05/31/2021" due date on the "Data for ONRR.gov" shared spreadsheet on our OneDrive. Please let me know if you have any questions!

Thanks, 
Sean

@sudarr

**Comment by sudarr** [comment]
I just wanted to note that this is for the Gas Major Portion prices page.


Robert J Sudar
Manager, Market & Spatial Analytics
Office of Natural Resources Revenue
***@***.***
Office: 303-231-3511, Cell: 720-492-6420
________________________________
From: boices ***@***.***>
Sent: Thursday, April 8, 2021 8:31 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Sudar, Robert J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] [ONRR/onrr.gov-site] Update Indian Major Portion Prices on onrr.gov (#645)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Good morning,

We need to update the Major Portion Pricing on onrr.gov. The relevant data is the section with the "05/31/2021" due date on the "Data for ONRR.gov" shared spreadsheet on our OneDrive. Please let me know if you have any questions!

Thanks,
Sean

@sudarr<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsudarr&data=04%7C01%7Crobert.sudar%40onrr.gov%7Cd7376c8efc42415ec21a08d8fa9afd28%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637534890867002474%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nQBQKSDigVYNX7RB0Jpo8sCUO6pqxEx%2BOwMlfmS9%2BKM%3D&reserved=0>

**Comment by Maroyafaied** [comment]
@boices please review the dev site. http://2017onrr/valuation/MonMajPP.htm

**Comment by boices** [comment]
Prices look great-thank you!

Sean Boice
Economist
Office of Natural Resources Revenue

From: Maroyafaied ***@***.***>
Sent: Friday, April 9, 2021 9:44 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Boice, Sean P ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update Indian Major Portion Prices on onrr.gov (#645)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@boices<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fboices&data=04%7C01%7Csean.boice%40onrr.gov%7C95bd02d046b34921ba2708d8fb6e6ceb%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637535798984424429%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TfTxHlUQERsHXkQtYdfBzTz5%2BJhIqukMWkD1FcvuWKk%3D&reserved=0> please review the dev site. http://2017onrr/valuation/MonMajPP.htm

-

**Comment by Maroyafaied** [comment]
This is live.
