### ISSUE TITLE
Duplicate FRN numbers on onrr.gov

### ISSUE THREAD

**Issue by Baymatt** [ONRR/onrr.gov-site#648]
There are two FRNs called FR 20574. I believe the one occurring on July 18, 2012 should be changed to FR 42230 but the link is correct. https://www.federalregister.gov/documents/2012/07/18/2012-17511/indian-oil-valuation-negotiated-rulemaking-committee

<img width="771" alt="Screen Shot 2021-04-09 at 1 05 49 PM" src="https://user-images.githubusercontent.com/43329595/114235026-6c583000-9934-11eb-8ee2-ae267d704e89.png">
<img width="737" alt="Screen Shot 2021-04-09 at 1 05 56 PM" src="https://user-images.githubusercontent.com/43329595/114235028-6d895d00-9934-11eb-9a88-e6330236d6f5.png">

**Comment by mcharg** [comment]
@Maroyafaied This is fixed in dev for you to review.
http://2017onrr/Laws_R_D/FRNotices/index.htm

**Comment by Maroyafaied** [comment]
@mcharg looks good. Thanks @Baymatt for catching that.

**Comment by mcharg** [comment]
Pushed live.
