### ISSUE TITLE
Remove 26 presentation

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#649]
Christina will send us an email confirming we can remove these presentations after confirming with owners. https://onrr.gov/about/presentations.htm

**Comment by mcharg** [comment]
@mentastc These are removed in dev.  Let us know when you have a new presentation to post and we'll update the live site.
http://2017onrr/about/presentations.htm

**Comment by Maroyafaied** [comment]
@mentastc please let us know when your presentation is ready.

**Comment by mcharg** [comment]
@mentastc is waiting for the valuation team to give him presentations.

**Comment by mcharg** [comment]
@mentastc This accidentally got pushed live when I was making changes to the global header.  Do you want me to put back one of the presentations?
