### ISSUE TITLE
Requesting update to ONRR.gov for Indian Index Zones

### ISSUE THREAD

**Issue by penvosej** [ONRR/onrr.gov-site#651]
Please update the Indian Index Zone prices for April on ONRR.gov. The data has been updated with the newest prices in the Data for ONRR.gov Excel spreadsheet.

@sudarr

**Comment by Maroyafaied** [comment]
@penvosej please review http://2017onrr/valuation/allzones.htm

**Comment by penvosej** [comment]
Thanks, Maroya! Can you do me just one small favor? Can you have the January price for the Northern Rocky Mountains read "$2.20" instead of "$2.2"? Otherwise, everything looks great!

From: Maroyafaied ***@***.***>
Sent: Monday, April 12, 2021 2:49 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Requesting update to ONRR.gov for Indian Index Zones (#651)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpenvosej&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C8e6c755ae031471d2a6d08d8fdf462c5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637538573364411048%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qN4rbfd3EX06pjMaE%2BUFHGvYDGRe%2Bbd11eZmD5dWQcw%3D&reserved=0> please review http://2017onrr/valuation/allzones.htm

-

**Comment by Maroyafaied** [comment]
I made that change, I'll make it live.

**Comment by penvosej** [comment]
Perfect; thanks!

From: Maroyafaied ***@***.***>
Sent: Monday, April 12, 2021 3:57 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Requesting update to ONRR.gov for Indian Index Zones (#651)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



I made that change, I'll make it live.

-

**Comment by Maroyafaied** [comment]
This is live
