### ISSUE TITLE
Updates to onrr.gov - IESC referral form 

### ISSUE THREAD

**Issue by ONRRamandagarrison** [ONRR/onrr.gov-site#655]
Need to remove current referral form link here:  https://www.onrr.gov/IndianServices/iesc-referrals.htm

**Need to replace with link to digital form:  Below is the code for embedding**

<iframe width="640px" height= "480px" src= "https://forms.office.com/Pages/ResponsePage.aspx?id=urWTBhhLe02TQfMvQApUlAG9FkklRGNHoggEpBcwhwpUNlQ2VFZOOFUxRDdEUk80TDBCNVI2RDBFMyQlQCN0PWcu&embed=true" frameborder= "0" marginwidth= "0" marginheight= "0" style= "border: none; max-width:100%; max-height:100vh" allowfullscreen webkitallowfullscreen mozallowfullscreen msallowfullscreen> </iframe>

Here is the URL link as well:  https://forms.office.com/Pages/ResponsePage.aspx?id=urWTBhhLe02TQfMvQApUlAG9FkklRGNHoggEpBcwhwpUNlQ2VFZOOFUxRDdEUk80TDBCNVI2RDBFMyQlQCN0PWcu

**Under 'Contacts' change the second Carla to:**
Albert Bond
IESC Deputy Director (Acting)
dale.bond@bia.gov
 (720) 484-3333

**Content update to main body:**

Referral Information
Federal agencies may submit new projects through their respective leadership for consideration and initiation to the IESC.

When nominating projects for energy, renewable energy, and minerals program support, please fill out the 'Request for Indian Energy Service Center (IESC) Assistance' digital form. Nominations should consider and include:

Contact information for the project,
Brief description of the technical support needed and reasons for the need,
Estimate of the timeframes associated with the workload,
Critical completion/project dates,
Risk posed to DOI if the work is not completed.

After submitting the IESC Request for Assistance form, please submit any supporting documents to IESCRequests@bia.gov 

All cases nominated will be prioritized by the IESC. Prioritization will be based on the items noted above. Due to staffing limitations, not all projects nominated may be selected for assistance. The IESC will keep the Bureau Offices apprised of the status of their nominations.

Background: The IESC provides a suite of support services to BIA Agencies and Regional Offices; BLM Field Offices and State Offices; BTFA Fiduciary Trust Officers and Regional Trust Administrators; and ONRR for purposes of expediting the leasing, permitting, developing, and reporting for oil and gas development on Indian Trust lands. The IESC is relied upon to:

Serve as a processing center for expediting certain nationwide Trust functions to augment or support an office.
Help formulate and develop consistent policy, rules, regulations, and business processes.
Procure contract services to provide direct services in support of oil and gas development.
Address backlogs restricting the timely development of oil and gas resources.
Participate in efforts to encourage coordination and promote resource sharing between Interior Bureaus and Offices, as well as other Federal agencies.
Conduct SOP training of Interior employees having a role in oil and gas programs.
Reconcile data between the various Bureau systems during performance of work tasks.
The IESC Director reports directly to the Deputy Bureau Director – Trust Services, Bureau of Indian Affairs, with guidance provided by an Executive Management Group (EMG) comprised of representation from BIA, ONRR, BLM, and BTFA.

The IESC is available to provide technical support and guidance in processing all types of Indian energy, renewable energy and, mineral leasing and development activities, actions or drafting policy.

**Comment by mcharg** [comment]
@ONRRamandagarrison This is updated in dev.  Let me know if it's good to post to the live site.
http://2017onrr/IndianServices/iesc-referrals.htm

**Comment by ONRRamandagarrison** [comment]
Looks good! Please make it live.


Thank you,
Amanda

Amanda Garrison

Supervisory Minerals Revenue Specialist
Indian Energy Service Center
P: (720) 595-2025

From: mcharg ***@***.***>
Sent: Wednesday, April 14, 2021 11:54 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Garrison, Amanda T ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Updates to onrr.gov - IESC referral form (#655)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@ONRRamandagarrison<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRRamandagarrison&data=04%7C01%7Camanda.garrison%40onrr.gov%7C759e15190f274019700e08d8ff6e5409%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637540196612701075%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MLCazDoWDY0rTYX1DwA1bYch5ORefedmJlXWVkFRIcs%3D&reserved=0> This is updated in dev. Let me know if it's good to post to the live site.
http://2017onrr/IndianServices/iesc-referrals.htm

-

**Comment by mcharg** [comment]
@ONRRamandagarrison I pushed it live.  It might be a bit before it shows up on the live site.
