### ISSUE TITLE
Remove Reporter Letters tab from homepage

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#657]
We haven't been updating the XML file when we update the reporter letters page, so it's out of date, and very few people click on this tab on the homepage.

**Comment by mcharg** [comment]
It'll also be more maintenance to keep if we end up doing second accessible versions for all the reporter letters.

**Comment by mcharg** [comment]
@Maroyafaied This is updated in dev.  Let me know if it's good to push to the live site.
http://2017onrr/index.htm

**Comment by Maroyafaied** [comment]
@mcharg looks good.

**Comment by mcharg** [comment]
Pushed live.
