### ISSUE TITLE
Get IESC video on their page on onrr.gov

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#66]
Once it's added to ONRR's YouTube, we need to add IESC's new video to their page on onrr.gov

**Comment by jennmalcolm** [comment]
currently waiting for version with closed captioning

**Comment by jennmalcolm** [comment]
@ONRRamandagarrison I added the video to the container on the right side of the IESC page. Please review it in our dev site and let me know if you're ready to make it live. Thanks.

http://2017onrr/IndianServices/indian-energy-service-center.htm

**Comment by ONRRamandagarrison** [comment]
It looks great! You can publish it.

Thank you so much,
Amanda

Amanda Garrison

Supervisory Minerals Revenue Specialist
Indian Energy Service Center
P: (720) 595-2025

**Comment by jennmalcolm** [comment]
The video is live now.
