### ISSUE TITLE
Webpage update - Indian Fund Code

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#663]
Please update the following webpage http://onrr.gov/ReortPay/payments.htm with the attached file.
Downloadable Excel Version Indian Leases Cross-walked to Distributee

Also change update to read 04/16/2021.

In additon to the above please update the date to read 04/16/2021 on URL
http//www.onrr.gov/ReportPay/royalty-reporting.htm
Thank you
[FCIL.xlsx](https://github.com/ONRR/onrr.gov-site/files/6327690/FCIL.xlsx)

**Comment by merrellc** [comment]
Please use attached file in place of the original one sent (date was not updated). 
Thank you
[FCIL.xlsx](https://github.com/ONRR/onrr.gov-site/files/6327818/FCIL.xlsx)

**Comment by merrellc** [comment]
I did not mean to close.  Please add the latest file.

Thank you

**Comment by Maroyafaied** [comment]
@merrellc please review 
http://2017onrr/ReportPay/payments.htm
http://2017onrr/ReportPay/royalty-reporting.htm

**Comment by merrellc** [comment]
Looks great!


Thank you
​Candace Merrell
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________
From: Maroyafaied ***@***.***>
Sent: Tuesday, April 27, 2021 2:42 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Webpage update - Indian Fund Code (#663)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@merrellc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmerrellc&data=04%7C01%7Ccandace.merrell%40onrr.gov%7Cb6aa8bc9c1eb4e5e940d08d909bcfde4%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637551529582151434%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QFgvIOQbMHm879CmWGZF%2F%2FWKBkqUwlOKyrVK11kKbhk%3D&reserved=0> please review
http://2017onrr/ReportPay/payments.htm
http://2017onrr/ReportPay/royalty-reporting.htm

**Comment by Maroyafaied** [comment]
This is live.
