### ISSUE TITLE
Title: Concho Area Meeting                     (under EVENT CALENDAR tab)

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#664]
May 19, 2021
Event Information
Location: By Telephone
Time: 1:00 PM - 2:00 PM
Description:  Meeting will be a Call-in Meeting to hear a presentation and updates from ONRR OKC Outreach Office. Representatives from BLM, BTFA, and BIA will also be available to discuss topics regarding Indian oil and gas, IIM accounts and other Indian trust property issues. There will also be a Q&A session for owners to ask questions. For those interested in attending must contact the ONRR Outreach office at (800) 354-7015 to reserve their space for attending meeting and to get the call-in number and passcode. A limited number of lines will be available for callers to this meeting.
Who Should Attend: IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Concho Agency Area, or any Indian mineral owners located in the Southern Plains Region in Oklahoma.
Other Information:  To attend meeting you must contact the ONRR OKC Outreach office at (800)354-6015 to reserve your space and to get the call-in number and passcode for the meeting on May 19, 2021. ONNR Outreach office hours are Monday- Friday from 7:30 am-5:00 pm.
Event Contact:  Name: ONRR OKC Office
Phone: Toll Free (800) 354-7015
Email: onrroutreachokc@onrr.gov

May 19, 2021
Title: Minot, Ft Berthold, and Fargo, ND area Meeting
Event Information
Location: By Telephone
Time: 1:00 pm-2:00 pm
Description: Meeting will be a Call-in Meeting to meet with the ONRR Denver Outreach Office to discuss topics regarding Indian Oil & Gas leases and other trust property issues.
Who Should Attend: Indian mineral owners and Indian trust property owners in the Minot, Ft Berthold, and Fargo, ND area.
Other Information: To attend meeting contact the ONRR Denver Outreach office at (800) 982-3226 to reserve your space and to get the call-in number and passcode.
Event Contact
Name: ONRR Denver Outreach Office
Phone: Toll Free (800) 982-3226
Email: onrroutreachdenver@onrr.gov

**Comment by Maroyafaied** [comment]
@Toddsand21 what would like as a "Title" for the first event? I have to put something in that field, I can put "Call-in meeting" or whatever you like?

**Comment by Toddsand21** [comment]
Concho Area Meeting

**Comment by Maroyafaied** [comment]
@Toddsand21 can I delete some of the older events? There's not room to include all the events?

**Comment by Toddsand21** [comment]
Delete all of March Events and in May we'll start deleting April.

**Comment by Maroyafaied** [comment]
@Toddsand21 please review http://2017onrr/IndianServices/index.htm#. Thanks

**Comment by Toddsand21** [comment]
All of the corrections are in the first event "Concho"  please see:  1) Concho is spelled wrong.  It's with an "o" not a in the Title.  and,  2) in the last sentence in "Other Information" can you add OKC to read  ONRR OKC Outreach office hours...     and, 3) and below that under Name add **Outreach** to read ONRR OKC Outreach Office

**Comment by Maroyafaied** [comment]
I made those updates, please review http://2017onrr/IndianServices/index.htm#

**Comment by Toddsand21** [comment]
Everything looks fine. I'll be touch.

**Comment by Maroyafaied** [comment]
This is live.
