### ISSUE TITLE
Request to Update ONRR's Federal Register Notices Page 

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#668]
Hello,

Please update ONRR’s Federal Register Notices page, located at https://www.onrr.gov/Laws_R_D/FRNotices/index.htm, to add the following two new entries:

1. The first new entry should be displayed as the most recent notice published and should read as follows:

“86 FR 20710
Wednesday, April 21, 2021
**Denver, CO** In accordance with the Paperwork Reduction Act of 1995, ONRR is proposing to renew an information collection request. OMB Control Number 1012-0001.”

At the bottom of the entry, please add “View FR document” with the following hyperlink: https://www.federalregister.gov/documents/2021/04/21/2021-08170/agency-information-collection-activities-accounts-receivable-confirmations-reporting

2. The second entry should appear after the first entry and should read as follows:

“86 FR 20708
Wednesday, April 21, 2021
**Denver, CO** In accordance with the Paperwork Reduction Act of 1995, ONRR is proposing to renew an information collection request. OMB Control Number 1012-0002”

At the bottom of the entry, please add “View FR document” with the following hyperlink: https://www.federalregister.gov/documents/2021/04/21/2021-08153/agency-information-collection-activities-indian-oil-and-gas-valuation-30-cfr-parts-1202-1206-and

Please let me know if you have any questions.

Thanks,
Christine

**Comment by Maroyafaied** [comment]
@cthomasONRR please review http://2017onrr/Laws_R_D/FRNotices/index.htm

**Comment by cthomasONRR** [comment]
@Maroyafaied this looks great! I approve. Thanks so much for your help!

**Comment by Maroyafaied** [comment]
This should be live in 30 min.
