### ISSUE TITLE
Request to Update ONRR's Webpage "OMB Control Number 1012-0001"

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#669]
Hello,

Could I please get a link added to the following webpage: https://www.onrr.gov/Laws_R_D/FRNotices/ICR0162.htm

Under the "Federal Register Publications" header, please add the following entry to the top of the list:

"60-Day Agency Information Collection - [86 FR 20710 -- April 21, 2021](https://www.federalregister.gov/documents/2021/04/21/2021-08170/agency-information-collection-activities-accounts-receivable-confirmations-reporting)"

Please format this entry exactly like the existing entries below it, meaning please add the black circular bullet point and have the hyperlink in parenthesis.

Please let me know if you have any questions.

Thanks for your help!
Christine

**Comment by Maroyafaied** [comment]
@cthomasONRR please review http://2017onrr/Laws_R_D/FRNotices/ICR0162.htm

**Comment by cthomasONRR** [comment]
@Maroyafaied looks great. I approve. Thanks!!!!

**Comment by Maroyafaied** [comment]
This should be live in 30 min. Thanks
