### ISSUE TITLE
Two new UCA's to be published

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#671]
This request came from the onrrweb mailbox, the documents are corrected and accessible. 
Could you publish the attached "Versado Saunders Gas Plant UCA"  and "Orla Gas Plant" on the ONRR Unbundling website, with the following attributes on the table(s): 

Name: Versado Saunders Gas Plant
Type: Plant
[Orla UCA example.pdf](https://github.com/ONRR/onrr.gov-site/files/6352324/Orla.UCA.example.pdf)
[Versado Saunders Gas Plant UCA.pdf](https://github.com/ONRR/onrr.gov-site/files/6352325/Versado.Saunders.Gas.Plant.UCA.pdf)

Operator:  Targa 
Location: NM
Doc Date: April 19, 2021

and 

Name: Orla Gas Plant
Type: Plant
Operator: Enterprise 
Location: TX
Doc Date: October 10, 2020

Thank you!

Noelle White
Chemical Engineer
Royalty Valuation, Team C 
Office of Natural Resources Revenue
Telephone Number:  303-231-3789

**Comment by mcharg** [comment]
Updated in dev and sent an email to requestor to review.
http://2017onrr/unbundling/index.htm

**Comment by mcharg** [comment]
They expect to send us changes next week.

**Comment by mcharg** [comment]
Updated dev with new docs from Noelle and waiting for approval.
http://2017onrr/unbundling/index.htm

**Comment by mcharg** [comment]
Approved and pushed live.
