### ISSUE TITLE
Continue onrr.gov visual design

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#672]
Iterate design from meeting.

**Comment by abudz19** [comment]
**Changes**
Footer
- revert to gray footer
- removed contact info in favor of link to contact page
- show two-line wrap version of logo/watermark

Header
- show two-line wrap version of logo/watermark

Content
- show flyout search



[About page v4 - slide out search.pdf](https://github.com/ONRR/onrr.gov-site/files/6400363/About.page.v4.-.slide.out.search.pdf)
[About page v4 - two line wrap logo - gray footer.pdf](https://github.com/ONRR/onrr.gov-site/files/6400364/About.page.v4.-.two.line.wrap.logo.-.gray.footer.pdf)
[Cooperative Agreements - two line wrap logo.pdf](https://github.com/ONRR/onrr.gov-site/files/6400366/Cooperative.Agreements.-.two.line.wrap.logo.pdf)
