### ISSUE TITLE
Collect images for onrr.gov

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#673]

**Comment by Maroyafaied** [comment]
I'll add Christa to this issue.

**Comment by mcharg** [comment]
@jnwang01 We're meeting with leadership on Wednesday to get their feedback on the type of images they would like to see.  After that, I think you can start picking images for each section and styling them to go with the visual design.

**Comment by meshanw** [comment]
@mcharg Are we thinking more nature type images similar to what's on onrresource or images of wells, solid minerals, etc?

**Comment by mcharg** [comment]
@meshanw We're meeting with Kimbra and Howard on Wednesday and will find out which of those two directions they want to go with the images.

**Comment by mcharg** [comment]
We're going with the nature image theme.
