### ISSUE TITLE
Request for revisions to the Contacts Page at  https://www.onrr.gov/ReportPay/contacts.htm 

### ISSUE THREAD

**Issue by LisaReimer** [ONRR/onrr.gov-site#674]
Request for revisions to the Contacts Page at  https://www.onrr.gov/ReportPay/contacts.htm 
Please see attached Excel Spreadsheet that reflects requested updates and PDF reflecting management approval.

Let me know if you have any questions.  Thank you for your help.

[CONTACT PAGE REVISIONS.xlsx](https://github.com/ONRR/onrr.gov-site/files/6367139/CONTACT.PAGE.REVISIONS.xlsx)
[Mail - Reimer, Lisa F - Outlook.pdf](https://github.com/ONRR/onrr.gov-site/files/6367149/Mail.-.Reimer.Lisa.F.-.Outlook.pdf)

**Comment by mcharg** [comment]
@LisaReimer This is updated in dev.  Let me know if it's good to push to the live site.
http://2017onrr/reportpay/contacts.htm

**Comment by LisaReimer** [comment]
Hello,

Thank you for the great work and for the dev link so I could review.  I just had one question.  Is it possible to enter ONSHORE above my name and OFFSHORE above Michael Nestlehut's name under the ASCII TXT and CSV Assistance?

[cid:ce84423c-b938-4370-9b13-b5ed2f1eb625]

...

Respectfully,

Lisa Reimer
Minerals Revenue Specialist - Production Analyst
Reference, Royalty and Production, Team 4B
Reference and Reporting Management
Office of Natural Resources Revenue
Office Phone:  214-640-9049
Fax:  303-445-9547



________________________________
From: mcharg ***@***.***>
Sent: Tuesday, May 4, 2021 08:38
To: ONRR/onrr.gov-site ***@***.***>
Cc: Reimer, Lisa F ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Request for revisions to the Contacts Page at https://www.onrr.gov/ReportPay/contacts.htm (#674)




@LisaReimer<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLisaReimer&data=04%7C01%7Clisa.reimer%40onrr.gov%7C7079701cfec64712359408d90f01eaee%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637557323181993172%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gO2Zu%2B4ymtkzx38ZdT%2BONp5dHf4A9fxVWP0Y2KBZNF8%3D&reserved=0> This is updated in dev. Let me know if it's good to push to the live site.
http://2017onrr/reportpay/contacts.htm

**Comment by mcharg** [comment]
@LisaReimer How's this?
http://2017onrr/reportpay/contacts.htm

**Comment by LisaReimer** [comment]
Perfect!  Thank you so much!  It is ready to go live.

Respectfully,

Lisa Reimer
Minerals Revenue Specialist - Production Analyst
Reference, Royalty and Production, Team 4B
Reference and Reporting Management
Office of Natural Resources Revenue
Office Phone:  214-640-9049
Fax:  303-445-9547



________________________________
From: mcharg ***@***.***>
Sent: Tuesday, May 4, 2021 13:26
To: ONRR/onrr.gov-site ***@***.***>
Cc: Reimer, Lisa F ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Request for revisions to the Contacts Page at https://www.onrr.gov/ReportPay/contacts.htm (#674)





@LisaReimer<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLisaReimer&data=04%7C01%7Clisa.reimer%40onrr.gov%7Cc213d90b63c74ab8d43e08d90f2a3726%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637557496262225025%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rk%2FBPx2n%2BjXRG4TBGWg%2FTGWN1uQNz2Y9r77ThyQ1QEg%3D&reserved=0> How's this?
http://2017onrr/reportpay/contacts.htm

**Comment by mcharg** [comment]
@LisaReimer Pushed live.  It might be a bit before it shows up on the live site.

**Comment by LisaReimer** [comment]
Thank you!

Lisa Reimer
Minerals Revenue Specialist - Production Analyst
Reference, Royalty and Production, Team 4B
Reference and Reporting Management
Office of Natural Resources Revenue
Office Phone:  214-640-9049
Fax:  303-445-9547


________________________________
From: mcharg ***@***.***>
Sent: Tuesday, May 4, 2021 14:27
To: ONRR/onrr.gov-site ***@***.***>
Cc: Reimer, Lisa F ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Request for revisions to the Contacts Page at https://www.onrr.gov/ReportPay/contacts.htm (#674)




@LisaReimer<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLisaReimer&data=04%7C01%7Clisa.reimer%40onrr.gov%7C383254bf3eac4ca2df7e08d90f32c32b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637557532967366001%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cWsHt5inDFiWeogCIhZq3LcVjH%2FAfSfjf%2FA28BNW16M%3D&reserved=0> Pushed live. It might be a bit before it shows up on the live site.
