### ISSUE TITLE
Update wireframes with RRM feedback

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#676]

**Comment by Maroyafaied** [comment]
Add Christa to this.

**Comment by CM805** [comment]
Mary and Sonny, with RRM, are working on this today.

**Comment by CM805** [comment]
@mcharg and @Maroyafaied I have feedback from Mary and Sonny.  I need to get it in front of April Lockler for her thoughts and then we can discuss implementation.  I'll pick up on this after I return from leave.

**Comment by mcharg** [comment]
@sghahn @jillbong79 I think this doc actually belongs to the compliance team.  It's only on the compliance overview and we're removing it.  You can remove it from your list.  Not sure we assigned it to your team.
https://www.onrr.gov/pdfdocs/American-IndianTrustFundManagementReformActof1994.pdf

**Comment by sghahn** [comment]
@mcharg thank you, I will remove it from our list.

**Comment by CM805** [comment]
@mcharg I emailed you this comment as well.

I was planning to run these by April Lockler first, but then I got to thinking that it would be much easier for her to see what it looks like on the actual wireframe.  So, can we get it added there and then send it to her for review and final approval?

**Comment by CM805** [comment]
Sent latest prototypes to RRM for review via email.

**Comment by CM805** [comment]
April Lockler gave us the thumbs up on the latest prototype!
