### ISSUE TITLE
Bring process diagram into alignment with visual design and NRRD homepage cards

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#679]
Also, remove graph.

**Comment by Maroyafaied** [comment]
Would like to show this next sprint with the about page wireframe.

**Comment by mcharg** [comment]
@jnwang01 Leadership wanted to change this to match what they're calling the steps elsewhere to be Collect & Disburse, Achieve Compliance, Report & Share.  They'll be sending us a diagram they have that they'd like us to consider.

**Comment by mcharg** [comment]
@jnwang01 This is the diagram. They want ours to be inline with the 3 blue boxes.
![image](https://user-images.githubusercontent.com/38465926/119031532-3073aa00-b979-11eb-87e7-fd67ea5debe1.png)

**Comment by Maroyafaied** [comment]
@jnwang01 send this revised version 

https://nrezre.axshare.com/#id=13pxu2&p=version_2_icons_cards

**Comment by Maroyafaied** [comment]
@jnwang01 It's not letting me comment in axure but I think it's better for this sentence to move down after the lease creation box. ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/82df1da9-a8d5-4c9b-976f-327e3ca87562)

**Comment by jnwang01** [comment]
https://nrezre.axshare.com here is the updated lease diagram, switched to use tab and card visuals

**Comment by mcharg** [comment]
@jnwang01 Is this page the latest? https://nrezre.axshare.com/#id=7xvuey&p=page_1&g=14

**Comment by mcharg** [comment]
@jnwang01 I made comments in AxShare.  If you send me the Axure file, I can make edits if you don't have time.

**Comment by jnwang01** [comment]
https://nrezre.axshare.com here is the updated link. I'm not sure about the geothermal, is there somewhere I can get the info?

**Comment by mcharg** [comment]
@jnwang01 You can pull something about geothermal from here: https://qmcq5k.axshare.com/#id=up0lnh&p=geothermal

**Comment by mcharg** [comment]
@jnwang01 When you click on the tabs, it reverts to the old wording.
![image](https://user-images.githubusercontent.com/38465926/125456300-29af87c2-54d4-42a6-8427-14948cb7759d.png)

**Comment by mcharg** [comment]
@jnwang01 Can you please send me the Axure file for the latest, so I can import it into the overall prototype?

**Comment by mcharg** [comment]
I pulled this into my Axure file and made the remaining edits.
https://qmcq5k.axshare.com/#id=1t0m2d&p=how_leasing_works

**Comment by mcharg** [comment]
Created #892 to finalize visual design.

@Maroyafaied You can close this after you review next week.

**Comment by Maroyafaied** [comment]
This looks good.
