### ISSUE TITLE
TITLE: FIMO CALL-IN OUTREACH                                          (to add to the Event Calendar under ONRR EVENTS)

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#681]
May 12th, 2021
TITLE: FIMO CALL-IN OUTREACH
EVENT INFORMATION
LOCATION: By Telephone 
TIME: 9:00 AM - 11:30 AM 
DESCRIPTION: Meeting will be a Call-In Meeting to hear current updates from the Federal Indian Minerals Office (FIMO).  Representatives from BLM, BTFA, and BIA will be available to discuss topics regarding Indian oil and gas, IIM accounts, Indian trust property issues, and probate.  There will be a Q&A session for landowners to ask questions. A limited number of lines will be available for callers to this phone-in meeting. 
WHO SHOULD ATTEND:  IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Navajo Agency Area or any mineral owners located in the Four Corners Region. 
OTHER INFORMATION:  The Federal Indian Minerals Office is open from Monday through Friday, 8:00 AM to 4:30 PM, closed during the lunch hour, 12:00 PM to 1:00 PM. 
EVENT CONTACT 
NAME: Federal Indian Minerals Office 
PHONE: Toll Free (800) 283-2839 
EMAIL:  Leona.begay@onrr.gov or Jennifer.benally@onrr.gov

**Comment by Maroyafaied** [comment]
@toddsand21 please review http://2017onrr/IndianServices/index.htm#

**Comment by Toddsand21** [comment]
I cannot open the file to review it.  It is probably because my Access card is not working right now.  I am scheduled to get it reset in the office next Tuesday.  So it may have to wait until then or we can go ahead and post it?

**Comment by Toddsand21** [comment]
Actually I wasn't closing this issue.  I was waiting for a reply.

**Comment by Maroyafaied** [comment]
@Toddsand21 I can post it if you want, just let me know. Here's the link again. Thanks

http://2017onrr/IndianServices/index.htm#

**Comment by Maroyafaied** [comment]
@toddsand21 would you like me to post this?

**Comment by Maroyafaied** [comment]
Sandra asked to go ahead and publish. This will be live in 30 min or so.
