### ISSUE TITLE
Find urls for public laws

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#682]
I added a tab to the FRN doc for public laws.
https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Content%20Audit/FRNs.xlsx?d=w52528d46310b438bb94ddff9b54a5143&csf=1&web=1&e=0qA8Q0

Here's an example public law url:
https://www.congress.gov/111/plaws/publ88/PLAW-111publ88.pdf

**Comment by Baymatt** [comment]
@mcharg Added links to the laws on the doc, many of them are the entire portion of the law cause I couldn't find the shortened version that we have on ONRR.gov

**Comment by mcharg** [comment]
@Baymatt Thank you!
