### ISSUE TITLE
Webpage Update Cross Reference Lease to Agreement

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#684]
Please update the following webpage https://www.onrr.gov/reportpay/CrossRef.htm 

Cross-Reference Lease to Agreement Numbers sorted by AgreementName
Cross-Reference Lease to Agreement Numbers sorted by AgreementNumber
Cross-Reference Lease to Agreement Numbers sorted by LeaseNumber

with the attached excel files.  Please also change (updated 4/1/2021 to 5/3/2021)
[CRANumber.xlsx](https://github.com/ONRR/onrr.gov-site/files/6417011/CRANumber.xlsx)
[CRLease.xlsx](https://github.com/ONRR/onrr.gov-site/files/6417013/CRLease.xlsx)
[CRAName.xlsx](https://github.com/ONRR/onrr.gov-site/files/6417015/CRAName.xlsx)

**Comment by Maroyafaied** [comment]
@bowlenj please review http://2017onrr/reportpay/CrossRef.htm

**Comment by bowlenj** [comment]
Looks great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: Maroyafaied ***@***.***>
Sent: Tuesday, May 4, 2021 9:43 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Webpage Update Cross Reference Lease to Agreement (#684)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C9b01110bbca7451b152108d90f1388c3%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637557398841262466%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SyWEY44j0lYwdtCRTWePy1kSEGBFBgH95f%2F9i4VYp9I%3D&reserved=0> please review http://2017onrr/reportpay/CrossRef.htm

-

**Comment by Maroyafaied** [comment]
This is live.
