### ISSUE TITLE
Add May Indian Index Zone prices to ONRR.gov

### ISSUE THREAD

**Issue by penvosej** [ONRR/onrr.gov-site#688]
Please include the Indian Index Zone prices for May on ONRR.gov. The Data for ONRR.gov Excel spreadsheet has been updated with the newest prices.

@sudarr

**Comment by Maroyafaied** [comment]
@penvosej please review http://2017onrr/valuation/allzones.htm

**Comment by penvosej** [comment]
Hi Maroya,

When I clicked on the link you provided, the last month of prices shown was April. Can you let me know if the Data for ONRR.gov document doesn't have the May prices? I'm pretty sure I updated it but it's possible it didn't save!

Thanks,
Jessica

***@***.***D741C0.2EC86410]

From: Maroyafaied ***@***.***>
Sent: Wednesday, May 5, 2021 2:52 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Add May Indian Index Zone prices to ONRR.gov (#688)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpenvosej&data=04%7C01%7Cjessica.penvose%40onrr.gov%7Cf2124c7bd9064010431108d91007c494%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637558447815430899%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HOIFK7fAU7cFHL3sb3IXHzXOMv8o0TS1i%2ByD64mZK%2BE%3D&reserved=0> please review http://2017onrr/valuation/allzones.htm

-

**Comment by Maroyafaied** [comment]
@penvosej please try clearing your cache by hitting ctrl and F5, I see May prices on my browser. 
![image](https://user-images.githubusercontent.com/40175688/117210671-3e400180-adb5-11eb-82e3-1c72806daf29.png)

**Comment by penvosej** [comment]
Thanks for the tip; that did the trick! The prices look good.

From: Maroyafaied ***@***.***>
Sent: Wednesday, May 5, 2021 3:20 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Add May Indian Index Zone prices to ONRR.gov (#688)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpenvosej&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C3c3d5c9f87944344672708d9100b93ee%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637558464185292086%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vKCAxgz%2FwF3wxPPRO9zLTw8WsuWch2q6VuoZqETw%2BDY%3D&reserved=0> please try clearing your cache by hitting ctrl and F5, I see May prices on my browser.
[image]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F40175688%2F117210671-3e400180-adb5-11eb-82e3-1c72806daf29.png&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C3c3d5c9f87944344672708d9100b93ee%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637558464185292086%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2F8sOz%2BnT%2F6rDaWLNvC7JNj8tpgROfX0Ci6CBFdKB250%3D&reserved=0>

-

**Comment by Maroyafaied** [comment]
This is live.
