### ISSUE TITLE
Subscribe here link doesn't work in homepage 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#691]
This link doesn't work in the press release tab or FR notices tab. 

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/c0f13d6e-3a99-4363-b15b-55f6e0423c5f)

**Comment by mcharg** [comment]
@Maroyafaied I commented out the links in dev.  Does that work?
http://2017onrr/

**Comment by Maroyafaied** [comment]
@mcharg was there an email address or something for a user to subscribe? I have an email from a user asking how they can subscribe.

**Comment by mcharg** [comment]
@Maroyafaied It was probably an RSS feed, but I have no idea how that works.

**Comment by Maroyafaied** [comment]
@mcharg Ok commenting it out is fine then.

**Comment by mcharg** [comment]
Pushed to live site.
