### ISSUE TITLE
Update April NYMEX on onrr.gov

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#692]
Good afternoon,

Please update onrr.gov with the April NYMEX prices as attached. @sudarr

Thank you!
[NYMEX042021.xlsx](https://github.com/ONRR/onrr.gov-site/files/6430188/NYMEX042021.xlsx)

**Comment by Maroyafaied** [comment]
@boices please review http://2017onrr/valuation/NYMEX.htm

**Comment by boices** [comment]
That's perfect--thanks again!

**Comment by Maroyafaied** [comment]
This is live.
