### ISSUE TITLE
Request to Update ONRR's ICR Page

### ISSUE THREAD

**Issue by aklong09** [ONRR/onrr.gov-site#693]
Hello, 

Please update ONRR’s ICR page entitled “OMB Control Number 1012-0003” located at https://www.onrr.gov/Laws_R_D/FRNotices/ICR0087.htm. 

Under the “Federal Register Publications” heading, please add a new bullet at the top of the list to read as follows, with the linked hyperlink:
•	60-Day Agency Information Collection - [(86 FR 20194—April 16, 2021)](https://www.federalregister.gov/documents/2021/04/16/2021-07885/agency-information-collection-activities-30-cfr-parts-1227-1228-and-1229-delegated-and-cooperative)

Please let me know if you have any questions.

Thanks in advance,
Alexis

**Comment by mcharg** [comment]
@aklong09 I pushed to the live site.  Updates to the live site have been really slow today, so it might not show up before the end of the day.
