### ISSUE TITLE
TITLE: FIMO PHONE-IN OUTREACH

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#702]
( Please add the following to the Event Calendar on the Allottee Assistance Page for May Events.)
MAY 20, 2021
TITLE: FIMO PHONE-IN OUTREACH 
Event Information
LOCATION: By Telephone 
TIME: 1:00 pm - 3:30 pm (mst)
DESCRIPTION: Meeting will be a Call-In Meeting to hear current updates from the Federal Indian Minerals Office.  Representatives from BLM, BTFA, and BIA will be available to discuss topics regarding Indian oil and gas, IIM accounts, Indian trust property issues, and probate.  A limited number of lines will be available for callers to this phone-in meeting. 
WHO SHOULD ATTEND:  IIM account holders, and other Indian Trust property owners in the Navajo Agency Area located in the Four Corners Region. 
OTHER INFORMATION:  The FIMO office hours are Monday .through Friday from 8:00 am to 12:00 pm, and closed during the lunch hour, and from1:00 pm to 4:30 pm.
EVENT CONTACT 
NAME: Federal Indian Minerals Office (FIMO)
PHONE: Toll Free (800) 283-2839 
EMAIL: leona.begay@onrr.gov, jennifer.benally@onrr.gov

**Comment by Maroyafaied** [comment]
@Toddsand21 please review http://2017onrr/IndianServices/index.htm#

**Comment by Maroyafaied** [comment]
![image](https://user-images.githubusercontent.com/40175688/118019381-2b2db400-b316-11eb-8638-63b69c1b51fc.png)

**Comment by Maroyafaied** [comment]
Approved by chat, should be live soon.

**Comment by Maroyafaied** [comment]
This is live.

**Comment by Toddsand21** [comment]
Thanks I see it.  You can now delete April's Events.

**Comment by Maroyafaied** [comment]
@Toddsand21 I deleted April's events, it should be live soon. Thanks

**Comment by Toddsand21** [comment]
Yes I see it's done. Thanks.
