### ISSUE TITLE
Get eCommerce Guide for onrr.gov

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#706]
@meshanw Stacey told me there was one, but hasn't responded to my email asking for it.

**Comment by mcharg** [comment]
This is where it will live.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/a2cb946c-ad66-486b-9474-fa8e87f3d890)

**Comment by mcharg** [comment]
@Maroyafaied Turns out there isn't a guide specific to eCommerce, but this handbook has a section on it.  Thoughts on pulling the eCommerce section from this to make an eCommerce guide?
https://www.onrr.gov/reportpay/PDFDocs/2012ReporterTrainingBook.pdf

**Comment by Maroyafaied** [comment]
@mcharg Ya we can do that if the information is different than what's on the other documents related to ecommerce. We can also link to the training video related to ecommerce.

**Comment by meshanw** [comment]
@mcharg One of my team members provided the attached guide. They are going to check to see if there is an updated version since this one is from 2017. 
[eCommerce_Reporting_Website_User_Guide.pdf](https://github.com/ONRR/onrr.gov-site/files/6503647/eCommerce_Reporting_Website_User_Guide.pdf)

Once I get an updated copy, I will post here.

**Comment by mcharg** [comment]
@meshanw Awesome. Thanks!

**Comment by mcharg** [comment]
@cthomasONRR Can you please add the eCommerce guide above to the accessibility tracking sheet assigned to Stacey Browne?  It's not on the site yet, but we want it added and it has accessibility errors.

**Comment by cthomasONRR** [comment]
@mcharg I added it to the accessibility tracking tab, but could not get the formulas to work in the content audit tab.

**Comment by mcharg** [comment]
@meshanw Can you point me to whomever gave you the eCommerce guide? We're trying to get an accessible version and Stacey hasn't responded to me.

**Comment by meshanw** [comment]
@mcharg Sure, try Candace Merrell in RRM.

**Comment by mcharg** [comment]
@meshanw Thank you!
