### ISSUE TITLE
Follow up with Stacey about reference files

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#707]
@meshanw I met with Stacey a while ago to show her the onrr.gov wireframes and she asked me to compile a list of reference docs that we might be able to look up directly from other systems.  She hasn't gotten back to me since I sent her the list.  Can you follow up with her?

Here's the list of docs:
https://doimspp-my.sharepoint.com/:x:/g/personal/mchargs_mms_gov/EaWcktrIyj1CohLzBlPyADQBfCefH4MP9WKNGiXy4x2NHA?e=EXeKVk

**Comment by meshanw** [comment]
@mcharg Can you forward me the email and I will certainly try to get her to respond. (Sometimes it's easier to have multiple people on emails to her or you have to stay at the top of her email box if you need a response)

**Comment by mcharg** [comment]
@meshanw and I met and pulled in Rick and Anna and decided to try to identify where each document is pulled from and scheduled a meeting with Jay next week to discuss whether there's anything we can do to get the data out of Accenture now vs. what needs to be considered in BPR requirements for the future state.

**Comment by mcharg** [comment]
Met with Stacey and she's going to have her team look at the files, set up a MART demo with our team, and use a file as a pilot as part of an exchange project.
