### ISSUE TITLE
Iterate visual design with feedback from review

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#710]
- [ ] Explore lighter tints for tabs, accordions, and table headers.
- [ ] Explore using title case instead of all caps for tabs and primary nav.
- [ ] Explore using a smaller font for second level of tabs.

**Comment by mcharg** [comment]
Leadership wants to see less blue, so:
- [ ] Explore using one of the expanded color as the secondary color.

**Comment by CM805** [comment]
Yellow was specifically mentioned

**Comment by abudz19** [comment]
### Tab variations

**Comment by mcharg** [comment]
@abudz19 The valuation & pricing page purple appears to not have finished uploading and I can't get the file.
