### ISSUE TITLE
Write alt text for diagrams on onrr.gov

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#713]
- [ ] Determining Geothermal Lease Class https://qmcq5k.axshare.com/#id=up0lnh&p=geothermal&g=14
- [ ] How Valuation Works https://qmcq5k.axshare.com/#id=l9inb4&p=valuation___pricing&g=14
- [ ] Compliance https://qmcq5k.axshare.com/#id=wxa2eb&p=compliance&g=14
- [ ] About ONRR > Our History https://qmcq5k.axshare.com/#id=vsgcdx&p=about_onrr&g=14

**Comment by daniel-coleman-1** [comment]
[AltText.07.09.docx](https://github.com/ONRR/onrr.gov-site/files/6792792/AltText.07.09.docx)

Here is a start @mcharg @arcasarana 

I couldn't get the Determining Geothermal Lease page to load in Axshare, will revisit Monday.

**Comment by mcharg** [comment]
@daniel-coleman-1 Can you please put the doc in Teams, so we can edit collaboratively?

**Comment by daniel-coleman-1** [comment]
Alt text document:

https://teams.microsoft.com/l/file/707C8F9D-1192-4E43-9BED-4E7BC13354F2?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FDesign%2FDesign%20Reviews%20-%20ONRR%20teams%2FDesign%20Review%20-%20Alt%20Text%20for%20Graphics.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by daniel-coleman-1** [comment]
![Screenshot 2021-07-13 115211](https://user-images.githubusercontent.com/83892362/125518976-69724a49-1be4-434b-af9d-83de00e43e33.jpg)

Minor typo in one graphic, "least" needs to be changed to "lease"

**Comment by daniel-coleman-1** [comment]
![Screenshot 2021-07-13 141413](https://user-images.githubusercontent.com/83892362/125519096-561821c6-23b9-4dad-a877-307e2b7c7bee.jpg)

Minor typo in one graphic, "least" needs to be changed to "lease"

**Comment by mcharg** [comment]
@daniel-coleman-1 This is a good start.  I added one comment to the doc.  Also fixed the typo in the geothermal diagram.

**Comment by arcasarana** [comment]
@daniel-coleman-1 @mcharg

I added some of my versions for alt-text informed by what Daniel wrote and Shannon's comment.  I didn't make edits over Daniel's and just copied and pasted my versions so it's easier to read.

**Comment by daniel-coleman-1** [comment]
@arcasarana @mcharg Sarah's versions look great to me
