### ISSUE TITLE
Document Removal Request

### ISSUE THREAD

**Issue by sghahn** [ONRR/onrr.gov-site#716]
Good morning @mcharg would you please remove the https://www.onrr.gov/ReportPay/PDFDocs/2012ReporterTrainingBook.pdf document from the website. Thank you!

**Comment by mcharg** [comment]
@sghahn This is updated in dev. Let me know if it's good to push to the live site.
http://2017onrr/reportpay/royalty-reporting.htm

**Comment by sghahn** [comment]
@mcharg, yes please proceed with the removal.

**Comment by mcharg** [comment]
@sghahn This is now live.
https://www.onrr.gov/reportpay/royalty-reporting.htm
