### ISSUE TITLE
Wireframe updates from About page reivew

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#718]

**Comment by mcharg** [comment]
I addressed Howard's edits, but I need to get the values to incorporate those.

**Comment by mcharg** [comment]
@Maroyafaied Let me know if you have any feedback.

https://qmcq5k.axshare.com/#id=vsgcdx&p=about_onrr

**Comment by Maroyafaied** [comment]
@mcharg this looks good, let's put Kimbra's small changes she send.

**Comment by mcharg** [comment]
Made Kimbra's changes.
