### ISSUE TITLE
Replace FRN pdfs with links to federal register

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#719]
- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/1230.pdf	
https://www.federalregister.gov/citation/53-FR-1230

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/1978thru1994/1184.pdf	
https://www.federalregister.gov/citation/53-FR-1184

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/46527.pdf	
https://www.federalregister.gov/citation/56-FR-46527

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/14868.pdf	
https://www.reginfo.gov/public/do/eAgendaViewRule?pubId=200304&RIN=1010-AD01

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/1978thru1994/30826.pdf	
https://www.federalregister.gov/citation/52-FR-30826

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/1978thru1994/4732.pdf	
https://www.federalregister.gov/citation/52-FR-4732

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/1978thru1994/30776.pdf	
https://www.federalregister.gov/citation/52-FR-30776

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/1978thru1994/39792.pdf	
https://www.federalregister.gov/citation/52-FR-39792

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/1978thru1994/1858.pdf	
Please delete from ONRR.gov - SM: Comment out the link and title rather than deleting it.

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/1978thru1994/39846.pdf	
https://www.federalregister.gov/citation/52-FR-39846

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/1978thru1994/35451.pdf	
https://www.federalregister.gov/citation/52-FR-35451

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/57256.pdf	
https://www.federalregister.gov/citation/56-FR-57256

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/50087.pdf	https://www.federalregister.gov/documents/2003/08/20/03-21217/federal-oil-valuation 

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/37504.pdf	
https://www.federalregister.gov/documents/2000/06/15/00-15201/amendments-to-gas-valuation-regulations-for-indian-leases 

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/1929.pdf	
https://www.federalregister.gov/documents/1999/01/12/99-37/appeals-of-mms-orders 

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/73819.pdf	
https://www.federalregister.gov/documents/1999/12/30/99-33613/establishing-oil-value-for-royalty-due-on-federal-leases 

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/37043.pdf	
https://www.federalregister.gov/documents/2000/06/13/00-14778/approved-publications-and-tables-for-use-in-applying-revised-royalty-valuation-regulations-for 

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/38299.pdf	
https://www.federalregister.gov/documents/2000/06/20/00-15498/market-centers-for-use-in-applying-revised-royalty-valuation-regulations-for-federal-oil 

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/36030.PDF	
https://www.federalregister.gov/documents/1997/07/03/97-17312/establishing-oil-value-for-royalty-due-on-federal-leases-and-on-sale-of-federal-royalty-oil 

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/3741.pdf	
https://www.federalregister.gov/documents/1997/01/24/97-1573/establishing-oil-value-for-royalty-due-on-federal-leases-and-on-sale-of-federal-royalty-oil 

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/1978thru1994/39712.pdf	https://www.federalregister.gov/documents/1994/08/04/94-19053/valuation-of-oil-and-gas-from-indian-leases 

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/47802.pdf 	
https://www.federalregister.gov/documents/2000/08/03/00-19654/agency-information-collection-activities-proposed-collection-comment-request 

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/47605.pdf 	
https://www.federalregister.gov/documents/2003/08/11/03-20354/royalty-in-kind-rik-eligible-refiner-determination-of-need 

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/42235.pdf 	
https://www.federalregister.gov/documents/2001/08/10/01-20100/agency-information-collection-activities-submitted-for-office-of-management-and-budget-omb-review 

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/46023.pdf 	
https://www.federalregister.gov/documents/2001/08/31/01-22076/agency-information-collection-activities-submitted-for-office-of-management-and-budget-omb-review

**Comment by mcharg** [comment]
Steps to update these:
1. Look up the file in the content audit tab of the [accessibility tracking spreadsheet](https://doimspp-my.sharepoint.com/:x:/r/personal/mchargs_mms_gov/Documents/onrr.gov/508/AccessibilityTracking.xlsx?d=w928732e3ba624e428d4da815c2802c66&csf=1&web=1&e=nbGMpN) to see what page(s) the document is linked on.
2. Find the page(s) in the dev folder and open it in Atom or Notepad to edit.
3. Find the link to the document on the page.
4. Copy the link to the federal register listed below the doc above and paste it in place of the link to the pdf.
5. Save the changes on the page.
6. Navigate to the page on dev and make sure the link goes to the new link on the federal register and the pdf icon is not showing up on the link.
7. Repeat for any additional pages that the document is on based on the content audit tab.
8. Find the document in the dev folder and place it in the archive folder within the folder it's in.
9. Update the url for the document to the url for the federal register in the content audit sheet and change the type from pdf to external.
10. Find the document in the Accessibility Tracking tab of the [accessibility tracking spreadsheet](https://doimspp-my.sharepoint.com/:x:/r/personal/mchargs_mms_gov/Documents/onrr.gov/508/AccessibilityTracking.xlsx?d=w928732e3ba624e428d4da815c2802c66&csf=1&web=1&e=nbGMpN) and update the status to Removed in Dev and color that cell and the first cell in the row in orange.  Add your name to Column P.
11. Copy and paste the link to the pages you updated in dev to this issue, so @Maroyafaied or @mcharg can review the changes.
12. Wait for approval to push to the live site.
13. Copy the pages changed from the dev site to the live site.
14. Archive the removed pdfs on the live site (repeat step 8 in the live site folder).
15. Update the Accessibility Tracking tab status to Removed.

**Comment by mcharg** [comment]
I updated ones on pages I touched when removing public comments.

- [ ] http://2017onrr/Laws_R_D/FRNotices/AD04.htm

**Comment by meshanw** [comment]
updated link in dev http://2017onrr/Laws_R_D/FRNotices/ab57.htm

**Comment by mcharg** [comment]
The ones on the public comments pages have been approved by the regs team and updated on the live site.

**Comment by mcharg** [comment]
Updated remaining pages in dev:
- [ ] http://2017onrr/Laws_R_D/FRNotices/AB17.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/Ad04.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0120.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0119.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0090.htm
- [ ] http://2017onrr/Laws_R_D/FRNotices/ICR0074.htm

**Comment by mcharg** [comment]
Sent to regs team to review remaining FRN updates.  Also found two more FRN links that I missed in the list to get a replacement link.

**Comment by mcharg** [comment]
Approved via email and pushed to the live site.
