### ISSUE TITLE
Replace FRNs with accessible PDFs

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#720]
These ones don't have links to the federal register.

- [x] https://www.onrr.gov/Laws_R_D/pubcomm/PDFDocs/990520.pdf
- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/74157.pdf
- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/74156.pdf

Accessible versions attached.
[https://app.zenhub.com/files/210892300/b04a741d-40dd-4a13-bf23-42907bbf2e22/download](https://app.zenhub.com/files/210892300/b04a741d-40dd-4a13-bf23-42907bbf2e22/download)<br>[https://app.zenhub.com/files/210892300/838ca898-0649-4c24-8ffb-5aca573dd268/download](https://app.zenhub.com/files/210892300/838ca898-0649-4c24-8ffb-5aca573dd268/download)<br>[https://app.zenhub.com/files/210892300/d0c9cbf8-536d-4e3f-9888-a58b8492c9e4/download](https://app.zenhub.com/files/210892300/d0c9cbf8-536d-4e3f-9888-a58b8492c9e4/download)

**Comment by mcharg** [comment]
Steps to update these:
1. Find the document in the Accessibility Tracking sheet.
2. Save the new pdf to your computer and rename it to match the old file name.
3. Run an accessibility check on the document.  Let @mcharg know if there are errors and I'll return it to the regulations team.
4. If there are no errors, save the new document to the location where the old document was in both the dev site and the live site.

**Comment by daniel-coleman-1** [comment]
@mcharg no accessibility errors, updated files in both dev and live site.
