### ISSUE TITLE
Update FRN page wireframe

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#721]
This is what the regulations team would like.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/08a585ef-e659-403c-9978-ef3bcd657561)

**Comment by mcharg** [comment]
Sent to regs team to review.  Got it down to grade 12.  @Maroyafaied @daniel-coleman-1 Any ideas to get it down to grade 10?
https://qmcq5k.axshare.com/#id=kkqoxq&p=federal_register_notices

**Comment by Maroyafaied** [comment]
@mcharg I actually get grade 10 with your changes on hemmingway. 
![image](https://user-images.githubusercontent.com/40175688/121026111-0dac0880-c763-11eb-8f9a-8314dfc4be82.png)
