### ISSUE TITLE
Remove Public Laws docs

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#722]
- [x] https://www.onrr.gov/Laws_R_D/PubLaws/PDFDocs/GOMESAct2006.pdf
- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/RSFA_Public_Law_104-200_Sep_22_1996.pdf
- [x] https://www.onrr.gov/Laws_R_D/PubLaws/PDFDocs/AppropriationsAct1992.pdf

**Comment by Maroyafaied** [comment]
Christine Thomas is the reviewer

**Comment by mcharg** [comment]
@daniel-coleman-1 Do you want to take this one, while you're in the Public Laws page?

**Comment by daniel-coleman-1** [comment]
@mcharg @Maroyafaied
Removed from the dev site, live site is unchanged.

**Comment by mcharg** [comment]
@daniel-coleman-1 This looks good.  Once you update the link for the Energy Policy Act, I'll send the Public Laws page to Christine for approval.

**Comment by mcharg** [comment]
Sent email to Christine for review.

**Comment by mcharg** [comment]
@daniel-coleman-1 We have one more to remove.

https://www.onrr.gov/Laws_R_D/PubLaws/PDFDocs/rsfa.pdf

**Comment by daniel-coleman-1** [comment]
> @daniel-coleman-1 We have one more to remove.
> 
> https://www.onrr.gov/Laws_R_D/PubLaws/PDFDocs/rsfa.pdf

Done

**Comment by mcharg** [comment]
@daniel-coleman-1 This one is also on the Compliance Overview, so can you please remove it there?

**Comment by mcharg** [comment]
@daniel-coleman-1 Can you also remove from the compliance overview?

**Comment by daniel-coleman-1** [comment]
> @daniel-coleman-1 This one is also on the Compliance Overview, so can you please remove it there?

Removed in Dev

**Comment by mcharg** [comment]
@daniel-coleman-1 One more they want removed.

Royalty Simplification and Fairness Act of 1996

**Comment by daniel-coleman-1** [comment]
> @daniel-coleman-1 One more they want removed.
> 
> Royalty Simplification and Fairness Act of 1996

Current status: Removed in Dev

I made no changes

**Comment by daniel-coleman-1** [comment]
We got that one this morning, it just hasn't published yet

**Comment by mcharg** [comment]
@daniel-coleman-1 Looks like it was replaced with a link, but they want the line removed.

**Comment by daniel-coleman-1** [comment]
@mcharg my mistake, fixed.  Line is removed.

**Comment by mcharg** [comment]
@daniel-coleman-1 Did you save your changes?  I'm still seeing the line.
![image](https://user-images.githubusercontent.com/38465926/120536525-3b373180-c3b2-11eb-905d-cad4803e45e5.png)

**Comment by daniel-coleman-1** [comment]
> @daniel-coleman-1 Did you save your changes? I'm still seeing the line.
> ![image](https://user-images.githubusercontent.com/38465926/120536525-3b373180-c3b2-11eb-905d-cad4803e45e5.png)

What URL is this, and how can I find it from the front page of the site?  I've been removing from the Compliance page.

**Comment by mcharg** [comment]
@daniel-coleman-1 It's the Public Laws page. http://2017onrr/Laws_R_D/PubLaws/index.htm

You get there from About >Rules & Regulations > Legal Citations (right nav)

**Comment by mcharg** [comment]
On the Compliance page, on the ones that are replaced with a link, can you change "Open File" to "Open Website"?
![image](https://user-images.githubusercontent.com/38465926/120646707-ca425900-c447-11eb-90c4-1a7f246fb40e.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 The Public Laws page is approved to push live.  Let's wait on pushing the changes to Compliance until after the June 17 meeting.

**Comment by mcharg** [comment]
Approved and pushed to the live site.  Moved the comment about the compliance page to #754 to address when we update that page.

**Comment by daniel-coleman-1** [comment]
> On the Compliance page, on the ones that are replaced with a link, can you change "Open File" to "Open Website"?
> ![image](https://user-images.githubusercontent.com/38465926/120646707-ca425900-c447-11eb-90c4-1a7f246fb40e.png)

Updated in Dev
