### ISSUE TITLE
Replace Public Laws documents with links

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#723]
- [x] https://www.onrr.gov/Laws_R_D/PubLaws/PDFDocs/97-451.pdf
https://uscode.house.gov/view.xhtml?path=/prelim@title30/chapter29&edition=prelim

- [x] https://www.onrr.gov/Laws_R_D/PubLaws/PDFDocs/MineralLeasingAct1920.pdf
https://uscode.house.gov/view.xhtml?path=/prelim@title30&edition=prelim

- [x] https://www.onrr.gov/Laws_R_D/PubLaws/PDFDocs/LandsAct1953.pdf
https://uscode.house.gov/view.xhtml?path=/prelim@title43/chapter29&edition=prelim

- [x] https://www.onrr.gov/Laws_R_D/PubLaws/PDFDocs/25USC2103.pdf
https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title25-section2103&num=0&edition=prelim

- [x] https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/25_USC_396.pdf
https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title25-section396&num=0&edition=prelim

**Comment by mcharg** [comment]
Steps to update these:
1. Look up the file in the content audit tab of the accessibility tracking spreadsheet to see what page(s) the document is linked on.
2. Find the page(s) in the dev folder and open it in Atom or Notepad to edit.
3. Find the link to the document on the page.
4. Copy the link listed below the doc above and paste it in place of the link to the pdf.
5. Save the changes on the page.
6. Navigate to the page on dev and make sure the link is the new link and opens a page and the pdf icon is not showing up on the link.
7. Repeat for any additional pages that the document is on based on the content audit tab.
8. Find the document in the dev folder and place it in the archive folder within the folder it's in.
9. Update the url for the document to the url for the federal register in the content audit sheet and change the type from pdf to external.
10. Find the document in the Accessibility Tracking tab of the accessibility tracking spreadsheet and update the status to Removed in Dev and color that cell and the first cell in the row in orange. Add your name to Column P. Copy and paste the new link into the notes column.
11. Copy and paste the link to the pages you updated in dev to this issue, so @Maroyafaied or @mcharg can review the changes.
12. Wait for approval to push to the live site.
13. Copy the pages changed from the dev site to the live site.
14. Archive the removed pdfs on the live site (repeat step 8 in the live site folder).
15. Update the Accessibility Tracking tab status to Removed.

**Comment by daniel-coleman-1** [comment]
Updated in dev site, pending review

**Comment by mcharg** [comment]
97-451.pdf was also on the Homepage and Civil Penalties page.  I updated the links on those pages.
http://2017onrr/index.htm
http://2017onrr/compliance/civil-penalties.htm

**Comment by mcharg** [comment]
I also moved the files to the archive folder and updated the content audit and accessibility tracking spreadsheet.  I'll send to Christine for approval.

**Comment by mcharg** [comment]
@daniel-coleman-1 I missed one.

Replace: https://www.onrr.gov/Laws_R_D/PubLaws/PDFDocs/EnergyPolicyAct2005.pdf
With: https://www.congress.gov/109/plaws/publ58/PLAW-109publ58.pdf

**Comment by daniel-coleman-1** [comment]
I didn't go through the accessibility tracker to find them, I just looked around on the site until I found a place where they were housed.  I'm not totally sure how to use the accessibility tracking sheet here.

For #1. Look up the file in the content audit tab of the accessibility tracking spreadsheet to see what page(s) the document is linked on, what row should I be looking at in the spreadsheet?

**Comment by mcharg** [comment]
@daniel-coleman-1 I just did the Energy Policy Act, so I can send the page to Christine for review.

**Comment by mcharg** [comment]
Sent email to Christine for review.

**Comment by mcharg** [comment]
@daniel-coleman-1 We got one more link to replace.

Replace: https://www.onrr.gov/Laws_R_D/PubLaws/PDFDocs/GeothermalAct1970.pdf
With: https://uscode.house.gov/view.xhtml?path=/prelim@title30/chapter23&edition=prelim

**Comment by mcharg** [comment]
@daniel-coleman-1 The Public Laws page is approved to push live.  Let's wait on pushing the changes to Compliance until after the June 17 meeting.

**Comment by mcharg** [comment]
Approved and pushed to the live site.
