### ISSUE TITLE
Decide on photos for each section

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#724]

**Comment by mcharg** [comment]
We know leadership wants to use these 3.![Navajo Bridge.jpg](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/8d9f95ad-208a-459e-92ab-ff4c37151d67)![hero image idea 4.jpg](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/f7f5d9dc-89a3-4bef-b824-1430d98e3a16)![Hero Photo Idea 3.jpg](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/e1c7d966-46fc-4ead-a5bf-3ad506841562)

**Comment by mcharg** [comment]
Additional photos: https://teams.microsoft.com/_#/files/General?threadId=19%3A34f9f9ee6b0441dbacab56bfd552f819%40thread.skype&ctx=channel&context=Indian%2520Resources%2520Amanda%2520Garrison%2520Photos&rootfolder=%252Fsites%252FNRRD%252FShared%2520Documents%252FGeneral%252FONRR.gov%252FDesign%252FOpenOpp%2520-%2520Visual%2520Design%252FPhotos%252FIndian%2520Resources%2520Amanda%2520Garrison%2520Photos

**Comment by mcharg** [comment]
@CM805 Will put all the photos into Slack to vote on and @abudz19 will note which ones she's tried that don't work with the size allotted.

**Comment by abudz19** [comment]
[Uploading Hero images.pdf…]()
