### ISSUE TITLE
Remove PDF file: Indian Leases Cross-walked to Distributee Codes

### ISSUE THREAD

**Issue by CM805** [ONRR/onrr.gov-site#725]
Remove the PDF version of this file from the Royalty Reporting page.

https://www.onrr.gov/reportpay/royalty-reporting.htm

![image](https://user-images.githubusercontent.com/83783622/119050957-cb6f8280-b97f-11eb-994b-ffc3fdc18546.png)

**Comment by CM805** [comment]
@mcharg please review in dev: http://2017onrr/reportpay/payments.htm

**Comment by mcharg** [comment]
@CM805 Looks good. You can push this to the live site.

**Comment by CM805** [comment]
This is being worked under #728.
