### ISSUE TITLE
Remove file from ONRR.gov Payments page: Indian Leases Cross-walked to Distributee Code

### ISSUE THREAD

**Issue by CM805** [ONRR/onrr.gov-site#726]
Remove the PDF version from ONRR.gov payments page

https://www.onrr.gov/reportpay/payments.htm

![image](https://user-images.githubusercontent.com/83783622/119053027-b7795000-b982-11eb-8b32-ead6cb43facd.png)

**Comment by CM805** [comment]
Working under issue #728

**Comment by CM805** [comment]
@mcharg this is the pne on the payments page that you just reviewed.  I will push changed to live site once my access gets fixed.

**Comment by CM805** [comment]
@mcharg you can go ahead and make these changes to the live site while my access gets fixed. Thanks!

**Comment by mcharg** [comment]
@CM805 I pushed the change to the live site.  It might take a bit (like 30 minutes) to show up.  Once you see the change on the live site, you can close the issue.
https://www.onrr.gov/reportpay/payments.htm
