### ISSUE TITLE
Consolidate files on ONRR.gov: Cross-Reference Lease to Agreement Numbers

### ISSUE THREAD

**Issue by CM805** [ONRR/onrr.gov-site#727]
Replace three existing excel files with one file, based on usage analytics

https://www.onrr.gov/reportpay/CrossRef.htm

![image](https://user-images.githubusercontent.com/83783622/119056610-3de46080-b988-11eb-84f4-ac5f308215dc.png)

**Comment by mcharg** [comment]
Analytics:
Sorted by Agreement Name (updated 05/03/2021) - 48 downloads in the last 30 days
Sorted by Agreement Number (updated 05/03/2021) - 82 downloads in the last 30 days
Sorted by Lease Number (updated 05/03/2021) - 113 downloads in the last 30 days

**Comment by CM805** [comment]
@mcharg Ready to review in dev
http://2017onrr/reportpay/CrossRef.htm

**Comment by mcharg** [comment]
@CM805 Can we drop the heading and have just a link that says "Cross-Reference Lease to Agreement Numbers"?  Now that there's only one file, the heading and saying how it's sorted seem unnecessary.
![image](https://user-images.githubusercontent.com/38465926/119545843-414d6280-bd61-11eb-9237-abfdde2f1758.png)

**Comment by CM805** [comment]
@mcharg I removed the heading.  Can't figure out how to move the bullet to the left.  Also, I think we can rename this Agreements tied to a lease number.  
![image](https://user-images.githubusercontent.com/83783622/119553737-2545c300-bd59-11eb-85b3-baccce607a81.png)

Also, the two documents just above this do not include the lease number.  So, as they are now, we cannot eliminate them in favor of the one in this issue.  But I do think we can consolidate those two down to just one.  Want me to create a new issue for that?

**Comment by mcharg** [comment]
@CM805 I'll go in and change it.  Yes, let's create a new issue for consolidating the other two docs.  I'll look them up in the analytics to see which is used more often.

**Comment by mcharg** [comment]
@CM805 It's updated in dev.
http://2017onrr/reportpay/CrossRef.htm

**Comment by mcharg** [comment]
For future reference, it's `<li>` tags nested under a second `<ul>` set that make it into sub bullets.

I commented out the `<ul>` set highlighted in yellow.
![image](https://user-images.githubusercontent.com/38465926/119555475-e79e6580-bd6b-11eb-90b2-d4d56cbfce59.png)

**Comment by CM805** [comment]
@mcharg looks good in dev

**Comment by mcharg** [comment]
@CM805 Should we run it by anyone in RRM before pushing live?

**Comment by CM805** [comment]
@mcharg I think we're good to push live

**Comment by mcharg** [comment]
Updated on the live site.
https://www.onrr.gov/reportpay/CrossRef.htm
