### ISSUE TITLE
Update Contact list

### ISSUE THREAD

**Issue by Sheetsj** [ONRR/onrr.gov-site#731]
Hello, 
I need the contact list on ONRR.GOV updated.  Located: ONRR.GOV-Contact US-Online Resources- ONRR Contacts by Company Assignment-Accounts Receivable, Billing, and Financial Issues Information -- Federal

File located on the N'Drive: \\ISEDENNAS\DEN_Common\FMD\FinancialServices\Admin\Fed Assignment Contact List
File Name: finserAssign

**Comment by Sheetsj** [comment]
I tried to attached the file, but I don't think it is letting me do it. I have tried dragging & dropping ,but it just opens the file up. I also selecting it. I am not sure if it attached.

**Comment by Maroyafaied** [comment]
@Sheetsj you can email the document to onrrweb@onrr.gov

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 here is the document

[finserAssign.pdf](https://github.com/ONRR/onrr.gov-site/files/6532849/finserAssign.pdf)

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I believe this is the document that needs to be updated.  And it's saved in the report pay folder, then pdf folder, titled as FSFederalCOAssignm.pdf. So you will need to change the name of the document when you save it.  
![image](https://user-images.githubusercontent.com/40175688/119533319-f3c1fd00-bd42-11eb-8bfa-08d762c543ac.png)
FSFederalCOAssignm.pdf

**Comment by daniel-coleman-1** [comment]
@Sheetsj
Please review:
http://2017onrr/about/contact.htm

**Comment by Sheetsj** [comment]
When I click the link it is still showing the old version. I have attached the file again just in case it was an old one that I sent in. 
[finserAssign.pdf](https://github.com/ONRR/onrr.gov-site/files/6553968/finserAssign.pdf)
.

**Comment by Maroyafaied** [comment]
@Sheetsj please refresh and clear your cache by pressing ctrl and F5. Let us know if it works

**Comment by Sheetsj** [comment]
Okay I just cleared my cache and it is updated and looks good. Thank You!

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 you can make this live by saving the document below to the publication folder (Z) \\Isehrnpubstg01\onrr2017\reportpay\PDFDocs
[FSFederalCOAssignm.pdf](https://github.com/ONRR/onrr.gov-site/files/6556516/FSFederalCOAssignm.pdf)

**Comment by daniel-coleman-1** [comment]
Confirmed, the document is live.  Issue closed.
