### ISSUE TITLE
Update document 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#733]
This request came from the mailbox:

Please update this document https://onrr.gov/reportpay/royalty-reporting.htm

[royassign.pdf](https://github.com/ONRR/onrr.gov-site/files/6532807/royassign.pdf)

**Comment by daniel-coleman-1** [comment]
Accessibility report came back with 1 error.  Maroya emailed document owner to correct error.

**Comment by Maroyafaied** [comment]
This was resolved in issue #762
