### ISSUE TITLE
Write guide for how to update onrr.gov

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#734]
To go on the wiki.

**Comment by Maroyafaied** [comment]
Put instructions on wiki in issues #719 and #720.

**Comment by daniel-coleman-1** [comment]
[How to Update ONRR.gov.docx](https://github.com/ONRR/onrr.gov-site/files/6634667/How.to.Update.ONRR.gov.docx)
@meshanw @mcharg 
for your review!

**Comment by mcharg** [comment]
@daniel-coleman-1 It's a good start.  I added comments to the doc.

**Comment by meshanw** [comment]
Nice! @daniel-coleman-1 I added a few comments as well.

**Comment by mcharg** [comment]
@daniel-coleman-1 I took another look at the guide doc.  There are still some open comments.  Also, did you start the wiki page?

**Comment by daniel-coleman-1** [comment]
Here's the Wiki:
https://github.com/ONRR/onrr.gov-site/wiki/How-to-Update-ONRR.gov
@meshanw @mcharg for your review!
@CM805 if you could take a look and  provide a high level overview, I'd appreciate it! No worries if you don't have time now though.

**Comment by CM805** [comment]
High level- It's clean and the layout is easy to follow.  I really like that the narrative is engaging and that it not only provides instructions but background info as well.

I'm using this right now to help me with #782. 

- I think it'd be helpful to tell readers how to open the .htm file (you have to right click on it and open it in notepad).  I remember being stumped on this after Maroya taught us and then I tried to do it on my own for the first time.
- We may need a note about updating the Audit Content tracker
- Consider a box-style checklist that can be added to issues to update ONRR.gov (the numbered one is a starting point, and can maybe be renamed work flow or work process or something like that)

I'll use this more after I get the updated document I need for the issue I'm working on.  If I have any additional thoughts I'll let you know.

**Comment by mcharg** [comment]
@daniel-coleman-1 Looks good.  My feedback below.

Updating links:
* If a link is being updated, it should be updated in the Content Audit tab in the Accessibility Tracking worksheet, so that reflects the current state of the site.
* You should also check the Content Audit when making link changes to see if the link needs to be updated in more than once place.

Commenting out:
* If you're commenting out links or links do docs, the Content Audit needs to be updated.

Checking for accessibility:
* Need to add instructions for PPT, XLS, and DOC files.
* When saving the accessible file, make sure to use the same file name as the old file, so links don't have to be updated.
* If the file is only updated in dev the status in the spreadsheet should be Accessible in Dev and changes to Accessible after it's pushed to the live site.

General:
* You may have to use the content audit to find the file to be updated if the updater changed the file name.
* You may have to use the content audit to find the location of the file or link to be updated, especially if it's on more than one page.

**Comment by mcharg** [comment]
@Maroyafaied should also review.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 
1. Under the structure section, you mentioned the dev site, it would good to include the link to it and mention that you have to be connected to VPN to view it. http://2017onrr/
2.  For the running accessibility check section, we should just use Jennifer's instructions. We can either link or copy and paste it your section. https://github.com/ONRR/onrr.gov-site/wiki/Checking-the-accessibility-of-a-PDF

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 This looks good, you can close this issue!
