### ISSUE TITLE
Request for onrr.gov issues/GitHub account instructions on onrresource

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#74]
I was wondering if you will be posting instructions on how to create an GitHub account and how to make a request on onrreosuce?

 
Email request:
As a web content member I have folks who will contact me about onrr.gov site changes and before I would just refer them to Chad. If there was an easy way for me to redirect them to the GitHub process that would be great. I figured a page on onrresource would be an easy way to get them started on using the preferred method of interaction.

We could maintain the instructions in the Wiki and provide references to those instructions on onrresource.

**Comment by jennmalcolm** [comment]
We have it in GitHub, so the next step is to find a place on onrresource and reach out to the requester to let him know where to find the instructions.

**Comment by Maroyafaied** [comment]
I added a link in our data display page and reached out to the requester to let him know where the instructions are. 

https://onrresource/Data-Display/

![image](https://user-images.githubusercontent.com/40175688/79483561-af0c5400-7fcf-11ea-8aad-14ebc3cf91fc.png)

**Comment by Maroyafaied** [comment]
@jennmalcolm The requester liked where the link is. Let me know if you're ok with the changes and I'll close this issue. Thanks

**Comment by jennmalcolm** [comment]
That works for me @Maroyafaied. Thanks
