### ISSUE TITLE
Implement visual design theming into vuetify

### ISSUE THREAD

**Issue by jlouis-onrr** [ONRR/onrr.gov-site#742]

**Comment by jlouis-onrr** [comment]
https://react-theming.github.io/create-mui-theme/

**Comment by mcharg** [comment]
@jlouis-onrr Here's the MUI theme with the primary and secondary colors from @abudz19. https://material.io/resources/color/#!/?view.left=0&view.right=1&primary.color=1A227E&secondary.color=0076A3&primary.text.color=ffffff

**Comment by Maroyafaied** [comment]
Includes light and dark theme.

**Comment by Maroyafaied** [comment]
Jerome implemented color palette. Will create a new issue for establishing dark theme colors.
