### ISSUE TITLE
Replace Indian Distributee Codes pdfs with Excel file

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#744]
I have received approval to replace the following PDFs with one Excel file.  I am trying to locate the Excel file. 

![image](https://user-images.githubusercontent.com/83783622/119053410-425a4a80-b983-11eb-9a7e-df4b76d7d097.png)

**Comment by CM805** [comment]
I took a look at the Accessibility Tracking sheet to find out which program manager this falls under.  I drafted an email to ask Rob Winter about it and sent it to @Maroyafaied.   Do you want me to send it to him, or do you prefer to send it to him?

**Comment by Maroyafaied** [comment]
@CM805 send email to Rob Winter

**Comment by CM805** [comment]
@Maroyafaied I have not heard back.  Can you please follow up with Rob?

**Comment by Maroyafaied** [comment]
@CM805 I just send an email following up. Thanks

**Comment by Maroyafaied** [comment]
@CM805 Please remove the two pdfs and add the attached excel sheet. Send the dev link to review for Rob Winter and Antoinette. [https://app.zenhub.com/files/210892300/00edf197-2b18-4c30-9311-159df3f025a8/download](https://app.zenhub.com/files/210892300/00edf197-2b18-4c30-9311-159df3f025a8/download)

**Comment by CM805** [comment]
There were two accessibility issues.  @mcharg or @Maroyafaied do you know if Antoinette has a GitHub username?  I didn't find one by just looking for her name.

![image](https://user-images.githubusercontent.com/83783622/127034350-def45298-4e2f-44f9-9581-fed6d08b5ee2.png)

**Comment by CM805** [comment]
@mcharg when I add the new file to the Accessibility Tracking sheet do you want me to add it to the bottom and just give it the next number in line?

**Comment by mcharg** [comment]
@CM805 That works.

**Comment by CM805** [comment]
I've updated with the non-accessible file in Dev, so once I have the new file I just need to replace it.  I've also added the file to the Accessibility tracking sheet and content audit sheet as "Not Accessible".  Will update this after receipt and replacement with new file.  Indicated two old files as "Removed" on Accessibility tracking sheet, and grayed out on Content Audit sheet.

**Comment by CM805** [comment]
Updated on Dev and Live.  Emailed link to verify live change to Antoinette and Rob.
