### ISSUE TITLE
Consolidate files on ONRR.gov Cross Ref Page: Active Agreements xls

### ISSUE THREAD

**Issue by CM805** [ONRR/onrr.gov-site#745]
Cancel out one of the files below, based on analytics.  These two files contain the same information sorted different ways.

https://www.onrr.gov/reportpay/CrossRef.htm

![image](https://user-images.githubusercontent.com/83783622/119681799-9d66c400-bdff-11eb-8c44-359b9794503b.png)

**Comment by mcharg** [comment]
@CM805 Here are the analytics.

saaname.xls was downloaded 78 times in the last 30 days
saanum.xls was downloaded 63 times in the last 30 days

**Comment by CM805** [comment]
@mch please review in dev

http://2017onrr/reportpay/CrossRef.htm

**Comment by mcharg** [comment]
@CM805 I think you can drop the "sorted by..." part of the link label and just call it Active Agreements.

**Comment by CM805** [comment]
@mcharg done.  Want to review?  Then I'll push to live.

**Comment by mcharg** [comment]
@CM805 Looks good to push live.

**Comment by CM805** [comment]
@mcharg live is up:

https://onrr.gov/reportpay/CrossRef.htm
