### ISSUE TITLE
Figure out if we can remove the text Cross-Reference Lease to Agreement Number file

### ISSUE THREAD

**Issue by CM805** [ONRR/onrr.gov-site#746]
https://github.com/ONRR/onrr.gov-site/issues/466

https://onrr.gov/reportpay/CrossRef.htm

![image](https://user-images.githubusercontent.com/83783622/119689620-3c8eba00-be06-11eb-85c3-05759dc802a7.png)

Contact Stacy Kiser about this.

@mcharg can you look at analytics for this one?  Can I look at analytics myself?

**Comment by mcharg** [comment]
80 downloads in the last 30 days

@CM805 If you fill out this form to get DAP access, you can get into analytics. https://docs.google.com/forms/d/e/1FAIpQLSc002Xp2hMjH0KxzilzfKG-ei8TzHLK-uady-qQbbAZms7jNQ/viewform

**Comment by CM805** [comment]
@mcharg I compared the two files:

![image](https://user-images.githubusercontent.com/83783622/119853534-855d7600-becd-11eb-8512-a01a9f893224.png)

All of the data that is in the Excel file is in the text file.  There is more in the text file, to include: active versus inactive status, land classification, lease allocation percentage, and more.  So I do not thing we should get rid of the text file.  It might be an option for us to replace the current Excel file with an Excel version of what is in the text file.  If we do that then I do think we could eliminate the text file.  But, I also wonder if having a Excel file with more info, versus less info, would be confusing to some of our audience.

**Comment by mcharg** [comment]
@Maroyafaied Should we have a meeting with whomever pulls the Excel file and DORC to see if we can just be pulling this data once and get to one file?

**Comment by Maroyafaied** [comment]
@mcharg Do we know who provides the excel file?

**Comment by mcharg** [comment]
@CM805 Is it Candace that provides the Excel file?

**Comment by CM805** [comment]
@mcharg I think so.  

On the accessibility tracking sheet maybe we should add a column to track the person who maintains the file (not just the program manager, but the actual person to contact)

**Comment by mcharg** [comment]
@CM805 Good idea.

**Comment by Maroyafaied** [comment]
@Maroyafaied set up a meeting with DORC and Candace. Request one excel file with all columns and one person to provide it.

**Comment by Maroyafaied** [comment]
@CM805 I send an email out about this.

**Comment by Maroyafaied** [comment]
@StaceyKaiser will convert the text file to excel and @bowlenj approved removing the other excel file.

**Comment by mcharg** [comment]
Created #782 for after we get the new .xls file created with the same data as the .txt file.
