### ISSUE TITLE
EVENT CALENDAR                    (Please add these to our Event Calendar on the Alottee Assistance page)

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#748]
JUNE 9, 2021
Title: FIMO PHONE-IN OUTREACH 
Event Information
Location: By Telephone 
Time: 10:00 AM - 12:00 PM 
Description: Meeting will be a Call-In Meeting to hear current updates from the Federal Indian Minerals Office (FIMO).  BLM, BTFA, and BIA representatives will also be on the call to discuss topics regarding Indian oil and gas, IIM accounts, Indian trust property issues, and probate.   Owners will be able to ask questions during the Q&A session. 
Who Should Attend:  IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Navajo Agency Area or any mineral owners located in the Four Corners Region. 
Other Information:  A limited number of lines will be available for callers to this phone-in meeting. 
FIMO is open from Monday through Friday, 8:00 AM to 12:00 PM, closed during the lunch hour, and 1:00 PM to 4:30 PM. 
Event Contact:
NAME: Federal Indian Minerals Office 
PHONE: Toll Free at (800)283-2839 
EMAIL: Leona.begay@onrr.gov, Jennifer.benally@onrr.gov

JUNE 16, 2021
TITLE: KAULEY MEETING 
Event Information
Location: By Telephone 
Time: 1:00 PM – 2:00 PM CST
Description:  Meeting will be a Call-in Meeting to hear a presentation and updates from ONRR OKC Outreach Office.  BLM, BTFM, and BIA representatives will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust properties.  A limited number of lines will be available for callers to call in to this meeting, please contact the ONRR OKC Office to reserve a space and for the call-in number
Who Should Attend:  IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Southern Plains Region in Oklahoma.
Other Information:  To reserve a space and get a passcode for this meeting please contact the ONRR OKC Outreach office at (800)354-7015.  The ONNR Outreach Office hours are Monday- Friday from 7:30 am-5:00 pm.
Event Contact
NAME: ONRR Outreach OKC Office 
PHONE: Toll Free (800) 354-7015 
EMAIL:  onrroutreachokc@onrr.gov

JUNE 16, 2021
TITLE: FIMO PHONE-IN OUTREACH 
Event Information
Location: By Telephone 
Time: 10:00 AM - 12:00 PM 
Description: Meeting will be a Call-In Meeting to hear current updates from the Federal Indian Minerals Office (FIMO). BLM, BTFA, and BIA representatives will also be on the call to discuss topics regarding Indian oil and gas, IIM accounts, Indian trust property issues, and probate.  Owners will be able to ask questions during the Q&A session. 
Who Should Attend:  IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Navajo Agency Area or any mineral owners located in the Four Corners Region. 
Other Information:  Limited number of lines will be available for callers to this phone-in meeting. 
FIMO is open from Monday through Friday, 8:00 AM to 12:00 PM, closed during the lunch hour, 1:00 PM to 4:30 PM.
Event Contact
Name: Federal Indian Minerals Office 
Phone: Toll Free (800) 283-2839 
Email: Leona.begay@onrr.gov,  or Jennifer.benally@onrr.gov

JUNE 23, 2021
TITLE: SHAWNEE AREA MEETING 
Event Information
Location:  By Telephone 
Time:  1:00 PM – 2:00 PM CST
Description:  Meeting will be a Call-in Meeting to hear a presentation and updates from ONRR OKC Outreach Office.  BLM, BTFM, and BIA representatives will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust properties.  A limited number of lines will be available for callers to call in to this meeting, please contact the ONRR OKC Office to reserve a space and for the call-in number and passcode. 
Who Should Attend:  IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Shawnee Agency Area, Southern Plains Region in Oklahoma.
Other Information: To reserve a space and get the call-in number and passcode for this meeting you may contact the ONRR OKC Outreach office at (800)354-7015.  The ONNR Outreach Office hours are Monday- Friday, 7:30 am-5:00 pm.
Event Contact
NAME: ONRR Outreach OKC Office 
PHONE: Toll Free (800) 354-7015 
EMAIL:  onrroutreachokc@onrr.gov

JUNE 24, 2021
TITLE: WIND RIVER AND FT WASHAKIE, WY AREA MEETING
Event Information 
Location: By Telephone 
Time: 10:00 AM – 11:00 AM MST
Description:  Meeting will be a Call-in Meeting to meet with the ONRR Denver Outreach Office to discuss topics regarding Indian Oil & Gas leases and other trust property issues.
Who Should Attend:  Indian mineral owners and Indian Trust property owners in the Wind River and Ft. Washakie, WY area.
Other Information: To attend meeting contact the ONRR Denver Outreach office at (800) 982-3226 to reserve your space and to get the call-in number and passcode. 
Event Contact
NAME: ONRR Denver Outreach Office 
PHONE: Toll Free (800)982-3226     
EMAIL: onrroutreachdenver@onrr.gov

**Comment by Maroyafaied** [comment]
@toddsand21 for some reason it's only allowing me to add only 2 events at a time, can you review the first two events and I'll push live if it looks good and try to add the others later. http://2017onrr/IndianServices/index.htm#

**Comment by Toddsand21** [comment]
Yes they look fine please post the first 2 June events.  And you will be deleting the rest of May events, correct?

**Comment by Maroyafaied** [comment]
@Toddsand21 Ya I'll add the rest of the events and delete May.

**Comment by Maroyafaied** [comment]
@Toddsand21 All the events are added and I removed May's events. Please review http://2017onrr/IndianServices/index.htm#

**Comment by Toddsand21** [comment]
It's only showing me blank lines.

**Comment by Maroyafaied** [comment]
@Toddsand21 That's so weird, it was showing yesterday. I'll look into it today. @jlouis-onrr Do you have any idea why the events are not showing up? \\iondeniisp01\ONRR2017\assets\events

**Comment by Toddsand21** [comment]
Yes yesterday I could see the first 2 along with May's events but today it just shows blank lines.

**Comment by Maroyafaied** [comment]
@Toddsand21 Can you try reviewing again? It should show up now http://2017onrr/IndianServices/index.htm#

**Comment by Toddsand21** [comment]
Everything looks fine except the Email Address for the Wind River Meeting it reads:  "Undefined" and it should be: 
onrroutreachdenver@onrr.gov

**Comment by Maroyafaied** [comment]
@Toddsand21 I made that change and pushed it live, it'll be live in 30 min or so.

**Comment by Toddsand21** [comment]
I see the first 4 have posted.  Is there more?  Will the June 24 Wind River Meeting post too?

**Comment by Toddsand21** [comment]
I'm sorry it still shows the old post with the May events included.  You said it'll take 30 min.  I'll give it time to load. Thanks.

**Comment by Maroyafaied** [comment]
@Toddsand21 please clear your cache by pressing ctrl and F5

**Comment by Toddsand21** [comment]
It looks good.  Thanks!
