### ISSUE TITLE
Presentation for Homepage study

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/onrr.gov-site#75]
Create presentation for homepage study

https://doimspp-my.sharepoint.com/:p:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7BA8D183B8-FA53-4052-A99A-94F5F96205FE%7D&file=ONRR%20Homepage%20Findings.pptx&action=edit&mobileredirect=true&PreviousSessionID=8a12ec9a-66b4-0597-5ae3-f2f8aaeb7a56&cid=cf81ff0a-f930-4d16-a696-8a4aecbefad5

@Maroyafaied and @mcharg please take a look.

**Comment by mcharg** [comment]
@lpgoldstein Looks good.  I fixed a couple typos.
