### ISSUE TITLE
Training link to "WebCenter Portal user Guide.Pdf" not working

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#751]
This request came in by email:

In the ONRR website https://www.onrr.gov/ReportPay/training/index.htm, when you click on the Training Presentation for the “WebCenter Portal User Guide.PDF”, it gives an error showing the file may have been removed or changed.  I am able to open the file right above it called “WebCenter Portal.PDF” with no problems. 
 
Can you please look into this and let me know when this report will be available to view on ONRR website?

![image](https://user-images.githubusercontent.com/40175688/120366814-58de9b00-c2cd-11eb-91e4-c3bb932f581f.png)

**Comment by mcharg** [comment]
@Maroyafaied I fixed this.  The file got put into the Not Linked folder.
