### ISSUE TITLE
508 Compliance (12 Documents, 12 Accessibility Reports)

### ISSUE THREAD

**Issue by LisaReimer** [ONRR/onrr.gov-site#752]
Good afternoon,

Please see attached 508 Compliance documents.  There are 12 documents and 12 corresponding Accessibility Reports.

Please let me know if you would prefer to receive these documents in a zip format in the future. 

- [x] [MPRH-Chapter-4.pdf](https://github.com/ONRR/onrr.gov-site/files/6580351/MPRH-Chapter-4.pdf)
[MPRH-Chapter-4_Accessibility Report.pdf](https://github.com/ONRR/onrr.gov-site/files/6580352/MPRH-Chapter-4_Accessibility.Report.pdf)

[4430Instr - Accessibility Report.pdf](https://github.com/ONRR/onrr.gov-site/files/6580273/4430Instr.-.Accessibility.Report.pdf)
- [x] [4430Instr.pdf](https://github.com/ONRR/onrr.gov-site/files/6580274/4430Instr.pdf)

[Error_Msg_Production_HOW_TO - Accessibility Report.pdf](https://github.com/ONRR/onrr.gov-site/files/6580275/Error_Msg_Production_HOW_TO.-.Accessibility.Report.pdf)
- [x] [Error_Msg_Production_HOW_TO.pdf](https://github.com/ONRR/onrr.gov-site/files/6580278/Error_Msg_Production_HOW_TO.pdf)

[MPRH-Abbreviations  - Accessibility Report.pdf](https://github.com/ONRR/onrr.gov-site/files/6580279/MPRH-Abbreviations.-.Accessibility.Report.pdf)
- [x] [MPRH-Abbreviations.pdf](https://github.com/ONRR/onrr.gov-site/files/6580280/MPRH-Abbreviations.pdf)

[MPRH-Appendix-C - Accessibility Report.pdf](https://github.com/ONRR/onrr.gov-site/files/6580282/MPRH-Appendix-C.-.Accessibility.Report.pdf)
- [x] [MPRH-Appendix-C.pdf](https://github.com/ONRR/onrr.gov-site/files/6580284/MPRH-Appendix-C.pdf)

[MPRH-Appendix-D - Accessibility Report.pdf](https://github.com/ONRR/onrr.gov-site/files/6580285/MPRH-Appendix-D.-.Accessibility.Report.pdf)
- [x] [MPRH-Appendix-D.pdf](https://github.com/ONRR/onrr.gov-site/files/6580286/MPRH-Appendix-D.pdf)

[MPRH-Appendix-G - Accessibility Report.pdf](https://github.com/ONRR/onrr.gov-site/files/6580288/MPRH-Appendix-G.-.Accessibility.Report.pdf)
- [x] [MPRH-Appendix-G.pdf](https://github.com/ONRR/onrr.gov-site/files/6580289/MPRH-Appendix-G.pdf)

[MPRH-Appendix-J - Accessibility Report.pdf](https://github.com/ONRR/onrr.gov-site/files/6580290/MPRH-Appendix-J.-.Accessibility.Report.pdf)
- [x] [MPRH-Appendix-J.pdf](https://github.com/ONRR/onrr.gov-site/files/6580291/MPRH-Appendix-J.pdf)

[MPRH-Appendix-O - Accessibility Report.pdf](https://github.com/ONRR/onrr.gov-site/files/6580292/MPRH-Appendix-O.-.Accessibility.Report.pdf)
- [x] [MPRH-Appendix-O.pdf](https://github.com/ONRR/onrr.gov-site/files/6580294/MPRH-Appendix-O.pdf)

[MPRH-Chapter-1 - Accessibility Report.pdf](https://github.com/ONRR/onrr.gov-site/files/6580295/MPRH-Chapter-1.-.Accessibility.Report.pdf)
- [x] [MPRH-Chapter-1.pdf](https://github.com/ONRR/onrr.gov-site/files/6580296/MPRH-Chapter-1.pdf)

[RRM-Appendix.A - Accessibility Report.pdf](https://github.com/ONRR/onrr.gov-site/files/6580297/RRM-Appendix.A.-.Accessibility.Report.pdf)
- [x] [RRM-Appendix.A.pdf](https://github.com/ONRR/onrr.gov-site/files/6580298/RRM-Appendix.A.pdf)

[SMRH_Table_of_Contents - Accessibility Report.pdf](https://github.com/ONRR/onrr.gov-site/files/6580299/SMRH_Table_of_Contents.-.Accessibility.Report.pdf)
- [x] [SMRH_Table_of_Contents.pdf](https://github.com/ONRR/onrr.gov-site/files/6580300/SMRH_Table_of_Contents.pdf)

**Comment by jillbong79** [comment]
More 508 files RRM:
[MPRH-Chapter-2.pdf](https://github.com/ONRR/onrr.gov-site/files/6585596/MPRH-Chapter-2.pdf)
[MPRH-Table-of-Contents.pdf](https://github.com/ONRR/onrr.gov-site/files/6585597/MPRH-Table-of-Contents.pdf)
[SalesTyp Codes--non-Solids.pdf](https://github.com/ONRR/onrr.gov-site/files/6585598/SalesTyp.Codes--non-Solids.pdf)
[SMRH_Chapter_2.pdf](https://github.com/ONRR/onrr.gov-site/files/6585599/SMRH_Chapter_2.pdf)
[dispAdj.pdf](https://github.com/ONRR/onrr.gov-site/files/6585600/dispAdj.pdf)

**Comment by Maroyafaied** [comment]
@jillbong79 Attaching the files to the issue works fine, we will plan to work on updating this next week. Thanks

**Comment by jillbong79** [comment]
Thank you so much!


Respectfully,

Jill Heinen (she, her, hers)

Minerals Revenue Specialist - Production
Reference, Royalty and Production Team 4A
Reference and Reporting Management
Office of Natural Resources Revenue
Office Phone: (303) 231-3523

“In the end, we will remember not the words of our enemies, but the silence of our friends”. – Martin Luther King, Jr.


Please note **ONRR is bound by lease terms and therefore, pursuant to 30 CFR:  For production reporting of oil, gas and geothermal resources on Federal lands, Indian lands, and in the Outer Continental Shelf, per 30 CFR §1210.103, production forms (Form ONRR-4054, Oil and Gas Operations Report, and Form ONRR-4058, Production Allocation Schedule Report) must be received by ONRR by the 15th day of the second month following the month for which you are reporting.**


SELF-HELP LINKS:

  *   **New** Online EMARF here<https://emarf.onrr.gov/emarf>!
  *   Help with REPORTING here<https://www.onrr.gov/ReportPay/royalty-reporting.htm>!
  *   Data Warehouse (E-Commerce, Invoices, eSoa, etc.)<https://sso.onrr.gov/oaam_server/login.do>
  *   Reporter handbooks<https://www.onrr.gov/reportpay/Handbooks/index.htm>
  *   Guidance on adjustments, recoupments & refunds<https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Chapter-6.pdf>
  *   Lease (STATUS & MAINTENANCE) click here<https://www.onrr.gov/ReportPay/PDFDocs/RS_LeAgAssignments.pdf>!
  *   Access to the system/update your info here<https://www.onrr.gov/reportpay/forms/index.htm>! (EMARF/4444/SURETY/W-9)
  *   Help with PAYMENTS here<https://www.onrr.gov/reportpay/payments.htm>!
  *   Help with a ‘Demand to Pay’ or ‘Potential Treasury Referral’ here<https://www.onrr.gov/ReportPay/PDFDocs/DebtCollectionAssign.pdf>!
  *   Federal Accounts Receivable Contacts<https://www.onrr.gov/ReportPay/PDFDocs/finserAssign.pdf>
  *   Indian Accounts Receivable Contacts<https://www.onrr.gov/ReportPay/PDFDocs/FSIndianCoAssign.pdf>
  *   Password resets/System issues-contact the help desk at 303-231-3333 or ***@***.******@***.***>
  *   For help with 2014's: Royalty Reporting Contacts<http://www.onrr.gov/ReportPay/PDFDocs/royassign.pdf>
  *   For help with OGOR's: Production Reporting Contacts<http://www.onrr.gov/ReportPay/PDFDocs/operasgn.pdf>
  *   For help with Lease/Agreement Reporting: Lease Agreement Reporting Contacts<http://www.onrr.gov/ReportPay/PDFDocs/RS_LeAgAssignments.pdf>

________________________________
From: Maroyafaied ***@***.***>
Sent: Wednesday, June 2, 2021 9:34 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bongiovanni, Jill W ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] 508 Compliance (12 Documents, 12 Accessibility Reports) (#752)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jillbong79<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjillbong79&data=04%7C01%7Cjill.bongiovanni%40onrr.gov%7C9009167f1844462f28d208d925dbf7ac%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637582448956783072%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9cBDs7g%2B4f79Yx3jobgs9iitAbVF0TN%2BkLizZ70CTX4%3D&reserved=0> Attaching the files to the issue works fine, we will plan to work on updating this next week. Thanks

**Comment by daniel-coleman-1** [comment]
- [ ] MPRH-Chapter-4.pdf

- [ ] 4430Instr.pdf

- [ ] Error_Msg_Production_HOW_TO.pdf

- [ ] MPRH-Abbreviations.pdf

- [ ] MPRH-Appendix-C.pdf

- [ ] MPRH-Appendix-D.pdf

- [ ] MPRH-Appendix-G.pdf

- [ ] MPRH-Appendix-J.pdf

- [ ] MPRH-Appendix-O.pdf

- [ ] MPRH-Chapter-1.pdf

- [ ] RRM-Appendix.A.pdf

- [ ] SMRH_Table_of_Contents.pdf

**Comment by mcharg** [comment]
@daniel-coleman-1 Are the docs you listed updated in dev or the live site?

**Comment by jillbong79** [comment]
This should be the last of the documents for phase 2:
[W-9_Instructions.pdf](https://github.com/ONRR/onrr.gov-site/files/6632955/W-9_Instructions.pdf)
[MPRH-Appendix-F.pdf](https://github.com/ONRR/onrr.gov-site/files/6632956/MPRH-Appendix-F.pdf)

For https://www.onrr.gov/ReportPay/PDFDocs/W-9.pdf please hyperlink the document to the IRS site.  Document is locked and cannot be updated to 508

**Comment by daniel-coleman-1** [comment]
@mcharg just in the dev site

**Comment by daniel-coleman-1** [comment]
Hi @jillbong79, I ran accessibility reports and came back with errors for the following:
MPRH-Chapter-2.pdf
[MPRH-Chapter-2.pdf.accreport.pdf](https://github.com/ONRR/onrr.gov-site/files/6633264/MPRH-Chapter-2.pdf.accreport.pdf)

SalesTyp Codes--non-Solids.pdf
[SalesTyp.Codes--non-Solids.pdf.accreport.pdf](https://github.com/ONRR/onrr.gov-site/files/6633265/SalesTyp.Codes--non-Solids.pdf.accreport.pdf)

 SMRH_Chapter_2.pdf
[SMRH_Chapter_2.pdf.accreport.pdf](https://github.com/ONRR/onrr.gov-site/files/6633266/SMRH_Chapter_2.pdf.accreport.pdf)

Could you correct and resubmit?

The following are updated in dev:
MPRH-Table-of-Contents.pdf
dispAdj.pdf

**Comment by daniel-coleman-1** [comment]
@jillbong79 for the W-9, are you ok with linking to this form:
https://www.irs.gov/pub/irs-pdf/fw9.pdf

or should we link to the page where the form is hosted?

**Comment by sghahn** [comment]
@daniel-coleman-1 yes, please use the linked form you referenced, [https://www.irs.gov/pub/irs-pdf/fw9.pdf]

**Comment by jillbong79** [comment]
The corrected files are attached.  All ran with no errors and saved again before adding them here.


**Please note new email address: ***@***.*** is now ***@***.***​​​​

Respectfully,

Jill Heinen (she, her, hers)

Minerals Revenue Specialist - Production
Reference, Royalty and Production Team 4A
Reference and Reporting Management
Office of Natural Resources Revenue
Office Phone: (303) 231-3523

“In the end, we will remember not the words of our enemies, but the silence of our friends”. – Martin Luther King, Jr.


Please note **ONRR is bound by lease terms and therefore, pursuant to 30 CFR:  For production reporting of oil, gas and geothermal resources on Federal lands, Indian lands, and in the Outer Continental Shelf, per 30 CFR §1210.103, production forms (Form ONRR-4054, Oil and Gas Operations Report, and Form ONRR-4058, Production Allocation Schedule Report) must be received by ONRR by the 15th day of the second month following the month for which you are reporting.**


SELF-HELP LINKS:

  *   **New** Online EMARF here<https://emarf.onrr.gov/emarf>!
  *   Help with REPORTING here<https://www.onrr.gov/ReportPay/royalty-reporting.htm>!
  *   Data Warehouse (E-Commerce, Invoices, eSoa, etc.)<https://sso.onrr.gov/oaam_server/login.do>
  *   Reporter handbooks<https://www.onrr.gov/reportpay/Handbooks/index.htm>
  *   Guidance on adjustments, recoupments & refunds<https://www.onrr.gov/ReportPay/Handbooks/pdfdocs/MRRH-Chapter-6.pdf>
  *   Lease (STATUS & MAINTENANCE) click here<https://www.onrr.gov/ReportPay/PDFDocs/RS_LeAgAssignments.pdf>!
  *   Access to the system/update your info here<https://www.onrr.gov/reportpay/forms/index.htm>! (EMARF/4444/SURETY/W-9)
  *   Help with PAYMENTS here<https://www.onrr.gov/reportpay/payments.htm>!
  *   Help with a ‘Demand to Pay’ or ‘Potential Treasury Referral’ here<https://www.onrr.gov/ReportPay/PDFDocs/DebtCollectionAssign.pdf>!
  *   Federal Accounts Receivable Contacts<https://www.onrr.gov/ReportPay/PDFDocs/finserAssign.pdf>
  *   Indian Accounts Receivable Contacts<https://www.onrr.gov/ReportPay/PDFDocs/FSIndianCoAssign.pdf>
  *   Password resets/System issues-contact the help desk at 303-231-3333 or ***@***.******@***.***>
  *   For help with 2014's: Royalty Reporting Contacts<http://www.onrr.gov/ReportPay/PDFDocs/royassign.pdf>
  *   For help with OGOR's: Production Reporting Contacts<http://www.onrr.gov/ReportPay/PDFDocs/operasgn.pdf>
  *   For help with Lease/Agreement Reporting: Lease Agreement Reporting Contacts<http://www.onrr.gov/ReportPay/PDFDocs/RS_LeAgAssignments.pdf>

________________________________
From: daniel-coleman-1 ***@***.***>
Sent: Thursday, June 10, 2021 11:26 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Heinen, Jill B ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] 508 Compliance (12 Documents, 12 Accessibility Reports) (#752)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi @jillbong79<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjillbong79&data=04%7C01%7Cjill.heinen%40onrr.gov%7C60e5a7b249d145af6c9708d92c354776%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637589429615655887%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nOJEeSQK2CpoFhqYxT32PEUekQQd%2Fgo%2FfiFzRKRK2hU%3D&reserved=0>, I ran accessibility reports and came back with errors for the following:
MPRH-Chapter-2.pdf
MPRH-Chapter-2.pdf.accreport.pdf<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Ffiles%2F6633264%2FMPRH-Chapter-2.pdf.accreport.pdf&data=04%7C01%7Cjill.heinen%40onrr.gov%7C60e5a7b249d145af6c9708d92c354776%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637589429615665843%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XcfM1f%2BEQSw%2BHrrLVUBsljpFcqTFDwdzsqVRoXxBZoA%3D&reserved=0>

SalesTyp Codes--non-Solids.pdf
SalesTyp.Codes--non-Solids.pdf.accreport.pdf<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Ffiles%2F6633265%2FSalesTyp.Codes--non-Solids.pdf.accreport.pdf&data=04%7C01%7Cjill.heinen%40onrr.gov%7C60e5a7b249d145af6c9708d92c354776%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637589429615675804%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YAGxjTw44a1jAL3otBHuSlZSDsnG9dmoFLDd3XVddhw%3D&reserved=0>

SMRH_Chapter_2.pdf
SMRH_Chapter_2.pdf.accreport.pdf<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Ffiles%2F6633266%2FSMRH_Chapter_2.pdf.accreport.pdf&data=04%7C01%7Cjill.heinen%40onrr.gov%7C60e5a7b249d145af6c9708d92c354776%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637589429615675804%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3M7FwkIOvVd2RuzotIlp8URqpWdWbEN%2B%2Blkmco%2BhrmA%3D&reserved=0>

Could you correct and resubmit?

The following are updated in dev:
MPRH-Table-of-Contents.pdf
dispAdj.pdf

**Comment by jillbong79** [comment]
Here is the correct file for SMRH_Chapter_2: [SMRH_Chapter_2.pdf](https://github.com/ONRR/onrr.gov-site/files/6640762/SMRH_Chapter_2.pdf)

[MPRH-Chapter-2.pdf.accreport.pdf](https://github.com/ONRR/onrr.gov-site/files/6640769/MPRH-Chapter-2.pdf.accreport.pdf)
![image](https://user-images.githubusercontent.com/51677345/121743408-8c37db80-cabe-11eb-94bf-e9ad0e09a920.png)

**Comment by daniel-coleman-1** [comment]
@jillbong79 great, we are good to go on that one! SMRH_Chapter_2.prf also saved in dev.

**Comment by daniel-coleman-1** [comment]
@sghahn @jillbong79 
W-9 link updated in dev to: https://www.irs.gov/pub/irs-pdf/fw9.pdf

**Comment by jillbong79** [comment]
Corrected file for Appendix F:
[MPRH-Appendix-F.pdf](https://github.com/ONRR/onrr.gov-site/files/6641078/MPRH-Appendix-F.pdf)
[MPRH-Appendix-F.pdf.accreport.pdf](https://github.com/ONRR/onrr.gov-site/files/6641080/MPRH-Appendix-F.pdf.accreport.pdf)

**Comment by jillbong79** [comment]
Corrected file for Sales Type Code:
[SalesTyp Codes--non-Solids.pdf](https://github.com/ONRR/onrr.gov-site/files/6641185/SalesTyp.Codes--non-Solids.pdf)
[SalesTyp Codes--non-Solids.pdf.accreport.pdf](https://github.com/ONRR/onrr.gov-site/files/6641189/SalesTyp.Codes--non-Solids.pdf.accreport.pdf)

**Comment by jillbong79** [comment]
File 4058:
[4058.pdf](https://github.com/ONRR/onrr.gov-site/files/6641220/4058.pdf)
[4058.pdf.accreport.pdf](https://github.com/ONRR/onrr.gov-site/files/6641221/4058.pdf.accreport.pdf)

**Comment by mcharg** [comment]
@daniel-coleman-1 Please mark documents updated in dev in the spreadsheet with a status of Accessible in Dev and save Accessible for ones updated on the live site.

**Comment by sghahn** [comment]
@mcharg @daniel-coleman-1 have the following documents been accepted as correct by your team:

MPRH-Appendix-F.pdf
SalesTyp Codes--non-Solids.pdf
4058.pdf

**Comment by Maroyafaied** [comment]
@sghahn I just checked on these documents for you and 2 out of the 3 are accessible with no errors. The 4058.pdf came back with one error for figures alternate text , I've attached the report for your reference. Thanks
[4058.pdf.accreport.pdf](https://github.com/ONRR/onrr.gov-site/files/6665946/4058.pdf.accreport.pdf)

**Comment by mcharg** [comment]
@LisaReimer @jillbong79 @sghahn I went through this issue to see what's still outstanding.  Daniel had some of the handbook files in the wrong folder, so I moved those to the correct location.  All links on the dev site should now be pointing to the accessible versions. Let me know if we're good to push the updates for the accessible files to the live site.

I created #785 to update the link to the W-9, since it needs to be updated on several pages.

We still need an error-free version of these files:
- [ ] MPRH-Chapter-2.pdf
- [ ] 4058.pdf

**Comment by sghahn** [comment]
@Maroyafaied @mcharg @jillbong79 @LisaReimer 

Attached are the accessible versions of:
- MPRH-Chapter-2.pdf
[MPRH-Chapter-2.pdf](https://github.com/ONRR/onrr.gov-site/files/6688269/MPRH-Chapter-2.pdf)
- 4058.pdf
[4058.pdf](https://github.com/ONRR/onrr.gov-site/files/6688273/4058.pdf)

Yes, please push all updates to the live site.

Issue #752 should resolve the following 21 documents that were in issue #752:

- [ ] MPRH-Chapter-4
- [ ] 4430Instr
- [ ] Error_Msg_Production_HOW_TO
- [ ] MPRH-Abbreviations
- [ ] MPRH-Appendix-C
- [ ] MPRH-Appendix-D
- [ ] MPRH-Appendix-G
- [ ] MPRH-Appendix-J
- [ ] MPRH-Appendix-O
- [ ] MPRH-Chapter 1
- [ ] RRM-Appendix-A
- [ ] SMRH_Table_of_Contents
- [ ] MPRH-Table-of-Contents
- [ ] SalesTypCodes-non Solids
- [ ] SMRH_Chapter_2
- [ ] dispAdj
- [ ] W9 Instructions
- [ ] MPRH-Appendix F
- [ ] W9 (direct link)
- [ ] MPRH-Chapter-2 (this attachment)
- [ ] 4058 (this attachment)

Once these documents are pushed to the live sight we should be okay to close this issue.

Please let me know if you have any questions, thank you.

**Comment by sghahn** [comment]
didn't mean to close

**Comment by mcharg** [comment]
@sghahn I'll get these updates made as soon as I can get back on the vpn.

**Comment by mcharg** [comment]
@sghahn The MPRH-Chapter-2 looks good and is updated in dev.

The 4058 is missing alt text on an image.

**Comment by sghahn** [comment]
@mcharg I re-uploaded the 4058 in my previous message, and there were no errors on it.

Just in case here they are again, let me know if I'm overlooking something, thanks.

[4058_AccReport.pdf](https://github.com/ONRR/onrr.gov-site/files/6688397/4058_AccReport.pdf)
[4058.pdf](https://github.com/ONRR/onrr.gov-site/files/6688398/4058.pdf)

**Comment by mcharg** [comment]
@sghahn This is the error I'm seeing. It seems to think the contact name label is an image.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/abc5c12a-4180-4096-b87b-c936ce0f5e26)![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/2d480ef1-045a-4a15-b993-716b75bbb668)

**Comment by mcharg** [comment]
I pushed the rest of the docs live.  It may be a bit before they show up on the live site.

**Comment by sghahn** [comment]
@mcharg, **_please use the form I submitted twice this morning,_** you are opening a previous version submitted by another user that has the error, the form that you are looking at is a fillable form and should not be.

Please see what I have attached, it is not a fillable form. 

[4058_AccReport.pdf](https://github.com/ONRR/onrr.gov-site/files/6688420/4058_AccReport.pdf)
[4058.pdf](https://github.com/ONRR/onrr.gov-site/files/6688421/4058.pdf)

**Comment by mcharg** [comment]
@sghahn Got the updated version this time.  Not sure why it kept downloading the old version.  I updated it in both dev and the live site.

I created a separate issue for the W-9, since it needs to be updated in several places.

Let me know if we're good to close this issue.

**Comment by sghahn** [comment]
@mcharg, there is some weird internet stuff going on this morning, glad it finally worked for you :)

I believe we should be good to go now to close the ticket, yay, thanks so much!
