### ISSUE TITLE
Update Production Reporting References

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#753]
This request came in by email from Johnny Erle

All,
   On the ONRR.gov home page, please update the Production Reporting References with the attached files. The new as of date is 30 Apr 2021.
There are five Gulf files.

Thank you,
[Gulf-Sales-Tanks.xlsx](https://github.com/ONRR/onrr.gov-site/files/6585791/Gulf-Sales-Tanks.xlsx)
[Gulf-Metering-Systems.xlsx](https://github.com/ONRR/onrr.gov-site/files/6585792/Gulf-Metering-Systems.xlsx)
[Gulf-Flash-Gas.xlsx](https://github.com/ONRR/onrr.gov-site/files/6585793/Gulf-Flash-Gas.xlsx)
[Gulf-Buy-Back.xlsx](https://github.com/ONRR/onrr.gov-site/files/6585795/Gulf-Buy-Back.xlsx)
[Gulf-Gas-Plants.xlsx](https://github.com/ONRR/onrr.gov-site/files/6585797/Gulf-Gas-Plants.xlsx)

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 once you made the updates in dev , please send it for review to john.erle@onrr.gov. Thanks

**Comment by daniel-coleman-1** [comment]
@Maroyafaied  for the files that are being updated, do I move them to the archive and then replace with these files, or do I just replace them in dev?
If we are archiving, where is the archive folder?

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 you just replace them by saving it by the same name.

**Comment by daniel-coleman-1** [comment]
Updated and awaiting review from John

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 please update the date to 6/10/2021 on these documents in dev  http://2017onrr/reportpay/references.htm

**Comment by daniel-coleman-1** [comment]
Saved dev file to Z drive

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 you can go ahead and push all the updates live since the requestor already approved with making the date changes. Thanks

**Comment by daniel-coleman-1** [comment]
Pushed to live site, updates are showing on the live site.  Ready to close, I think.
