### ISSUE TITLE
Update ONRR.gov Compliance page

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/onrr.gov-site#754]
Convert links from PDF downloads to document links & descriptions from Federal Laws page

[Preview link](http://2017onrr/compliance/index.htm)

**Comment by daniel-coleman-1** [comment]
- [ ] 2009 Federal Oil And Gas Royalty Management Act (FOGRMA, Amendment)
- [ ] 2005 Energy Policy Act
- [ ] 2000 Principles For The Discharge Of The Secretary's Trust Responsibility
- [ ] 1996 Federal Oil And Gas Royalty Simplification And Fairness Act (FOGRSFA)
- [ ] 1994 American Indian Trust Fund Management Reform Act
- [ ] 1991 Mineral Leasing Act (MLA, Amendment)
- [ ] 1982 Federal Oil And Gas Royalty Management Act (FOGRMA) 
- [ ] 1970 Geothermal Steam Act
- [ ] 1953 Outer Continental Shelf Lands Act (OCSLA)
- [ ] 1920 Mineral Leasing Act (MLA)

**Comment by mcharg** [comment]
@daniel-coleman-1 See the email thread about this.  This compliance team wants to move to something like the federal laws page on NRRD with a user-friendly description for each law.  We may be able to copy the descriptions we have on the NRRD page.

**Comment by mcharg** [comment]
@Maroyafaied We should find out who Jeff and/or Dane want us to work with on descriptions.

**Comment by daniel-coleman-1** [comment]
> @daniel-coleman-1 See the email thread about this. This compliance team wants to move to something like the federal laws page on NRRD with a user-friendly description for each law. We may be able to copy the descriptions we have on the NRRD page.

What I'm seeing is that they would prefer that we link to hosted documents, but we'd like to link to hosted documents that are not hosted on our site - same access to information but less to maintain on our end.  Is that correct?  Also happy to chat verbally about this.

**Comment by mcharg** [comment]
@daniel-coleman-1 They just gave us the go ahead to use the links and descriptions we have on the NRRD federal laws page for the laws that are on the compliance page.  Then they can react to what we show them.

**Comment by daniel-coleman-1** [comment]
> @daniel-coleman-1 They just gave us the go ahead to use the links and descriptions we have on the NRRD federal laws page for the laws that are on the compliance page. Then they can react to what we show them.

Ahhhhhhhhhhh I understand.

**Comment by daniel-coleman-1** [comment]
@mcharg  updated task description

**Comment by mcharg** [comment]
@daniel-coleman-1 This can wait until next sprint, since we're not meeting until the 17th.

**Comment by mcharg** [comment]
@daniel-coleman-1 Moving this to this issue, so I can push the Public Laws page live and close that issue. 

On the Compliance page, on the ones that are replaced with a link, can you change "Open File" to "Open Website"?
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/4d7c520c-b355-4048-a36e-3cc5b8403775)

**Comment by mcharg** [comment]
Updated in dev and sent email for approval:

Compliance overview: http://2017onrr/compliance/index.htm
Public laws: http://2017onrr/Laws_R_D/PubLaws/index.htm

**Comment by mcharg** [comment]
Approved via email and pushed live. https://www.onrr.gov/compliance/index.htm
https://www.onrr.gov/Laws_R_D/PubLaws/index.htm
