### ISSUE TITLE
Create SEO component to handle all page meta data

### ISSUE THREAD

**Issue by jlouis-onrr** [ONRR/onrr.gov-site#755]

**Comment by jlouis-onrr** [comment]
adding SEO scrape doc so that we can associate cms ids with old and new urls[https://app.zenhub.com/files/210892300/f301ea37-ea45-4101-8121-6849dce81a5c/download](https://app.zenhub.com/files/210892300/f301ea37-ea45-4101-8121-6849dce81a5c/download)

**Comment by mcharg** [comment]
I uploaded the spreadsheet into Teams.  Might be a while before I finish it.
https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/CMS/SEO_export.xlsx?d=w239b0ae10a62442b83734e9d1a132b2a&csf=1&web=1&e=aiNlIn

**Comment by mcharg** [comment]
@jlouis-onrr The spreadsheet is complete.
