### ISSUE TITLE
Update ONRR.gov Handbook Page

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#757]
Please update the following page with the below information - https://www.onrr.gov/reportpay/Handbooks/index.htm

Please remove Lee-Ann Martins name and phone number and replace with:

April Lockler
(303) 231-3105

Also please remove the note "regarding contents."
[ONRR.gov update April.docx](https://github.com/ONRR/onrr.gov-site/files/6592772/ONRR.gov.update.April.docx)

**Comment by meshanw** [comment]
@bowlenj Please review http://2017onrr/reportpay/Handbooks/index.htm

**Comment by Maroyafaied** [comment]
@mcharg this issue is a contact update.

**Comment by bowlenj** [comment]
Perfect, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: meshanw ***@***.***>
Sent: Tuesday, June 8, 2021 10:39 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update ONRR.gov Handbook Page (#757)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Ccb98a9ed427b442b7c9208d92a9bf078%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637587672107910153%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=LaeJuuy4J6tBt4gZ4JJhQKMtkWeTxyYV%2FByzsGmFfnM%3D&reserved=0> Please review http://2017onrr/reportpay/Handbooks/index.htm

-

**Comment by meshanw** [comment]
Approved via email and pushed to live site 
https://onrr.gov/reportpay/Handbooks/index.htm
