### ISSUE TITLE
NYMEX May prices ready for upload

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#758]
The NYMEX May prices are ready to be added to the Valuation NYMEX page. Attached is the spreadsheet for uploading as well.

NYMEX: $65.16
Roll: $0.00 (yes, this is correct, the roll happened to be 0 for May)
[NYMEX052021.xlsx](https://github.com/ONRR/onrr.gov-site/files/6593486/NYMEX052021.xlsx)

Thanks,
Cory Forgrave
@sudarr

**Comment by Maroyafaied** [comment]
@forgravec please review http://2017onrr/valuation/NYMEX.htm

**Comment by forgravec** [comment]
Look good.

Thanks,
Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
***@***.***

________________________________
From: Maroyafaied ***@***.***>
Sent: Monday, June 7, 2021 1:51 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Forgrave, Cory J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] NYMEX May prices ready for upload (#758)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@forgravec<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fforgravec&data=04%7C01%7Ccory.forgrave%40onrr.gov%7Cb641e69872164adde26508d929edbbda%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637586923300227263%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mujL6tbMCW5Gu%2B%2Fr45vtd8Ly35HFQt6MjrLKH8pvdU0%3D&reserved=0> please review http://2017onrr/valuation/NYMEX.htm

**Comment by Maroyafaied** [comment]
This is live.
