### ISSUE TITLE
Add New Outreach video to Allottee Assistance Page on ONRR.gov

### ISSUE THREAD

**Issue by Rebekah474** [ONRR/onrr.gov-site#759]
Add the video with the link [https://youtu.be/mmmbqZjySUI] to the Allottee Assistance page on ONRR.gov. Do not take the other video down, we are building a library.

**Comment by Maroyafaied** [comment]
@rebekah474 Do you want the title of the video to "Why did my royalties go down"? Do you want to add a description like the other video or just a title?

**Comment by Maroyafaied** [comment]
@rebekah474 it's ready for your review if you don't want to add a description. http://2017onrr/IndianServices/index.htm

**Comment by Maroyafaied** [comment]
@Rebekah474 This should be live in 30 min or so.

**Comment by Maroyafaied** [comment]
This is live.

**Comment by Rebekah474** [comment]
I don't see the new video anymore. I only see the How does the market affect my royalties? Was it (the Why did my royalties go down? video) posted on the Allottee assistance page?
