### ISSUE TITLE
Visual design for homepage

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#760]
Figure what to do instead of the icons I just dropped in.
https://qmcq5k.axshare.com/

**Comment by mcharg** [comment]
@jnwang01's first pass.
https://qh1m7w.axshare.com/

Related feedback:

- I think the image works well.  I wonder if we can get an accessible overlay of the text on the image where it's a single image it'll be overlaying.  I also think we can remove the commodity icons under the intro text now that we have the image.
- The icons in the new to reporting section feel out of place.  Not sure if we want to remove them altogether or find something to replace them with.
- Can you also play around the with visual design of all the boxes?
- There are some link boxes in the style tile Alex did.
- We could also use the header styles in the style tile.

**Comment by mcharg** [comment]
@jnwang01 Have you had a chance to iterate this?  I pulled the comments I made previous out of chat to better keep track of them.

**Comment by mcharg** [comment]
Since I haven't heard from @jnwang01 in a while and we want to make sure we have a homepage before we start demoing the dev site with anyone, I took a stab at this.

https://qh1m7w.axshare.com/#id=5g8mg4&p=home_visual_2&g=1

**Comment by mcharg** [comment]
@Maroyafaied @arcasarana @CM805 @meshanw @jlouis-onrr @daniel-coleman-1 Any feedback?

**Comment by mcharg** [comment]
I spot checked a bunch of the shades in the gradient behind the text over the image and they're all accessible levels of contrast.

**Comment by meshanw** [comment]
I like the colors and contrast. Layout is straightforward and not too busy. My only comment is can the "Paying" header be changed to "Payment" or a better term? I know on the current homepage, it's Reporting/Paying which makes it look a bit better when it's combined but when it's separated, "Paying" just jumps out at me. Even when you hover over and the drop down appears, 'Paying Home' displays. So maybe that can be changed to 'Payment Home' or another term? Just my two cents. Everything else is welcoming, fresh, and easy/calm on the eye (especially with the scenic image) :)
