### ISSUE TITLE
Update June Indian Index Zone Prices on onrr.gov

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#761]
Please update the Indian Index Zone prices for June on ONRR.gov. The "Data for ONRR.gov" spreadsheet has been updated with the newest prices.

@sudarr

**Comment by Maroyafaied** [comment]
@boices please review http://2017onrr/valuation/allzones.htm

**Comment by boices** [comment]
All prices look good-thanks again!

Sean Boice
Economist
Office of Natural Resources Revenue

From: Maroyafaied ***@***.***>
Sent: Monday, June 7, 2021 1:46 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Boice, Sean P ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update June Indian Index Zone Prices on onrr.gov (#761)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@boices<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fboices&data=04%7C01%7Csean.boice%40onrr.gov%7Ccdf23ae3812f4aba72db08d929ecf6e9%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637586919999566626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ysSELCI4P2LEc8unF42BgXl6JgOpDV%2Fs3bUjyGMTU9U%3D&reserved=0> please review http://2017onrr/valuation/allzones.htm

-

**Comment by Maroyafaied** [comment]
This is live.
