### ISSUE TITLE
Updated Royalty Contact List

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#762]
Please replace the current Royalty contact list with the attached list on the following page - https://www.onrr.gov/reportpay/PDFDocs/royassign.pdf

[royassign.pdf](https://github.com/ONRR/onrr.gov-site/files/6598436/royassign.pdf)

**Comment by mcharg** [comment]
@bowlenj This is updated in dev.  Let me know if it's good to push to the live site.

**Comment by bowlenj** [comment]
Can you send me the link to check, it didn't seem to attach to the email.

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: mcharg ***@***.***>
Sent: Monday, June 7, 2021 1:29 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Updated Royalty Contact List (#762)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C58f67ddd1ed44674126408d929ea81a7%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637586909442034365%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dIbXwC%2Bq5giqwFArcL28c2oVv%2F8lnUQpG3aXWAgw95w%3D&reserved=0> This is updated in dev. Let me know if it's good to push to the live site.

-

**Comment by mcharg** [comment]
@bowlenj The file is linked on this page.
http://2017onrr/about/contact.htm

**Comment by bowlenj** [comment]
Looks great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: mcharg ***@***.***>
Sent: Monday, June 7, 2021 2:18 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Updated Royalty Contact List (#762)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf1128d3978e04ce976c808d929f16048%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637586938943684244%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pWrm8YcTbBBajzpIpObX9%2FTc2HiCwHeDvFBTBfniTK0%3D&reserved=0> The file is linked on this page.
http://2017onrr/about/contact.htm

-

**Comment by mcharg** [comment]
@bowlenj I pushed the change to the live site.  Should show up in about 30 minutes.
