### ISSUE TITLE
Red Earth Festival Outreach                                                                 (To add to our Event Calendar)

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#763]
June 12-13, 2021
Red Earth Festival Outreach
Event Information
Location:  Grand Casino Hotel Resort & Event Center, 777 Grand Casino Blvd., Shawnee, OK.  Booth will be located in the Event Center Lobby area.
Time:  Saturday, June 12th, 9:00 am – 7:00 pm, and Sunday, June 13th,  10:00 am – 5:00 pm

Description:  The Office of Natural Resources Revenue (ONRR) OKC Outreach Office will have a booth to speak with Indian mineral owners, Indian Trust property owners that attend the festival who may have questions on their Indian trust properties and Indian Oil & Gas leases.  Information booklets will be available.
Who Should Attend:  Indian mineral owners, Indian Trust property owners, and IIM account holders in the Southern Plains Region or the Eastern Oklahoma Region, or any Indian trust property owners in the Oklahoma, Kansas, Texas and surrounding areas.  
Other Information: Indian Trust property owners outside the Oklahoma and surrounding area could also benefit by visiting the ONRR Outreach booth to meet with them and ask questions that are common for all Indian trust property owners.  Information booklets will be available with contact information listed for an ONRR office in their area.  ONRR has Outreach offices in Denver, CO and Farmington, NM and Oklahoma City, OK who work with inquiries from Indian Trust property owners in their area coverage.
 
Event Contact:
 Name: ONRR Outreach OKC Office
 Phone: Toll Free (800) 354-7015
 Email: onrroutreachokc@onrr.gov

**Comment by Toddsand21** [comment]
We would like to get this posted asap since the event is coming up soon.

**Comment by Maroyafaied** [comment]
@Toddsand21 please review, I was able to add it without deleting anything. http://2017onrr/IndianServices/index.htm#

**Comment by Toddsand21** [comment]
1) Can you change on the Time: Sat: 11:00 am -7:00 pm, Sun: 10:00am - 5:00pm:  If you cannot, we will add it as the last sentence to.. "Other Information"  2) on Who Should Attend: Delete everything in the first sentence beginning with   "in the Southern Plains region  .....  and replace with: .. "including those within the OK area, and also those outside of OK, who may have questions on their Indian trust properties".  3)On Other Information:  Delete the first sentence.

**Comment by Maroyafaied** [comment]
@Toddsand21 please review the changes, I specified the timing in the "other information" http://2017onrr/IndianServices/index.htm#

**Comment by Toddsand21** [comment]
It looks fine, but could you change the last sentence on Other Information to read:  Oklahoma City, who work on inquiries from Indian Trust property owners within their area.         

Then it's ready to post.  Thanks Maroya!

**Comment by Maroyafaied** [comment]
@Toddsand21 I made that change, it should be live in 30 min or so.

**Comment by Maroyafaied** [comment]
This is live.
