### ISSUE TITLE
Strategy for Phase 3

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#764]
Include Carrie to run accessibility reports### ###

**Comment by mcharg** [comment]
@Maroyafaied We can probably start with reporter letters.  Amy was asking about the status of her team's docs today and that's the biggest chunk left.

**Comment by Maroyafaied** [comment]
We will contact program managers with their lists of documents in phase 3 and ask them to strategize which docs they want to remove and which they want to keep & correct. Once they identify which ones they want to correct, we will offer to run accessibility reports for those docs.
