### ISSUE TITLE
ONRR.gov homepage

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#767]
Please delete everything in the upper left corner box titled "Trust Beneficiary Outreach Session"  under Announcements on the ONRR.gov homepage.

**Comment by Maroyafaied** [comment]
@Toddsand21 Do you want the box deleted all together or did you want to update the content on there with something? We could delete the box entirely and put the Mineral Owner box on top to replace as you guys requested yesterday.

**Comment by Toddsand21** [comment]
Yes I would replace it with the Mineral Owner box for now.  Can we always create another box if we need to if we delete it entirely?

**Comment by Maroyafaied** [comment]
@Toddsand21 Yes you can.

**Comment by Maroyafaied** [comment]
@Toddsand21 Please review http://2017onrr/

**Comment by Toddsand21** [comment]
That looks fine. Lets go with it. I'm sure Heidi will approve.

**Comment by Maroyafaied** [comment]
@Toddsand21 it'll be live in 30 min or so.

**Comment by Toddsand21** [comment]
Can you hold off on that? She wants to add the phone numbers to it instead of the link.

**Comment by Maroyafaied** [comment]
@Toddsand21 I already pushed it live but you can put in another request for phone numbers and changes.

**Comment by Maroyafaied** [comment]
@Toddsand21 Do you have the phone number and which link you want to replace?

**Comment by Maroyafaied** [comment]
@Toddsand21 where do you want this? In the Mineral Owner box?

**Comment by Maroyafaied** [comment]
@Toddsand21 please review http://2017onrr/index.htm

**Comment by Toddsand21** [comment]
It looks fine and ready to go.  Thanks Maroya for your quick response!

**Comment by Maroyafaied** [comment]
@Toddsand21 I made that change, is it good to go live? http://2017onrr/

**Comment by Toddsand21** [comment]
It looks good and ready to go.  Thx.

**Comment by Maroyafaied** [comment]
This is live.
