### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#77]
There are links on the Treasury Referrals page that do not work:

![image](https://user-images.githubusercontent.com/30806839/77349287-2ae8e880-6d11-11ea-8298-504f99a5af6e.png)

"Debt Collection Improvement Act of 1996" link does not work
"Debt collection Reporter Letter" link results does not work

**Comment by jennmalcolm** [comment]
@Maroyafaied could you find what this links should be and correct? If you need help, let me know.

**Comment by Maroyafaied** [comment]
@jennmalcolm I think these should be the correct link, let me know if you agree and I'll make the changes. 

Debt Collection Improvement Act of 1996
https://fiscal.treasury.gov/dms/about/about-dcia.html

Debt collection Reporter Letter
https://www.onrr.gov/ReportPay/PDFDocs/961125.pdf

**Comment by jennmalcolm** [comment]
@Maroyafaied the first link looks good. I think the reporter letter link is fine, but for some reason that pdf was missing in production. It was in the dev folder, so I just copied it to prod too.

Could you fix the first link and confirm that the other is working on onrr.gov after about 15 mins?

**Comment by jennmalcolm** [comment]
The email from the requester is in the shared box so you can contact them for review.

**Comment by Maroyafaied** [comment]
@jennmalcolm The reporter letter link works now and I fixed the first link and send it to the requester for review. Thanks

http://2017onrr/compliance/Treasury-Referrals.htm

**Comment by Maroyafaied** [comment]
The requester reviewed and links are now working on the site.
