### ISSUE TITLE
Capitalization of federal and tribal

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#770]
Research with both terms should be capitalized and consult with Matt Williams

**Comment by daniel-coleman-1** [comment]
Reached out to Matt Williams via email

**Comment by Maroyafaied** [comment]
Please work with Chris Mentasti on this.

**Comment by daniel-coleman-1** [comment]
Chris and I are scheduled for coffee Monday morning.

**Comment by daniel-coleman-1** [comment]
Michelle Rogers as well

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 put this in the wiki under the content guide.
