### ISSUE TITLE
Update Tribal Assistance page

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#776]
1)    Upper Right Hand Corner in box titled “Contacts”.  Change what’s in the box to say:
Email the Tribal Liaison Officer with questions. (Link to the email address as shown at the bottom of the Tribal Consultation page).  Which needs to be updated to link to: "Bethany Temple-Hagen@onrr.gov" since she is the Tribal Liaison Officer.  Which will also be part of the next New Issue too I will submit next.

2)    At the very bottom of the TA page under “Contacts”, delete Denver and OK Outreach contact info, and replace with:

Heidi Badaracco, Program Manager, ITOC, (303) 231-3434
Bethany Hagen-Templin, Tribal Liaison Officer, ITOC/ONRR Branch Chief (IESC), (303) 231-3667
Michel Mouton,  Minerals Revenue Specialist\Tribal Liaison, ITOC, (281) 987-6809  

(Note: Their names should include hyperlinks to their email addresses).

**Comment by mcharg** [comment]
@Maroyafaied I'll do the box on the right change while I have Dreamweaver open, since that's in a Library and it takes like an hour for Dreamweaver to open.

**Comment by Maroyafaied** [comment]
@mcharg sounds good, thank you!

**Comment by mcharg** [comment]
@Maroyafaied I'm just going to do the whole thing, since I'm in the page.

**Comment by Maroyafaied** [comment]
@mcharg Awesome, thanks.

**Comment by mcharg** [comment]
@toddsand21 This is updated in dev.  Let me know if it looks good to push live.
http://2017onrr/IndianServices/tribal-assistance.htm

**Comment by mcharg** [comment]
@toddsand21 have you had a chance to look at this?

**Comment by Toddsand21** [comment]
I cannot get to view the changes when I click on the Tribal Liaison Officer it takes me to a Google sign in page.  Should I be signing into something to view?  Sorry I was off yesterday and I had a few meetings today.

**Comment by Maroyafaied** [comment]
@Toddsand21 the tribal liaison officer email link opens up a google email message with Bethany's email address. Shannon also added the contacts to the bottom as requested,
![image](https://user-images.githubusercontent.com/40175688/122130512-f8834980-cdf4-11eb-9461-db85bc936dac.png)
![image](https://user-images.githubusercontent.com/40175688/122130598-1cdf2600-cdf5-11eb-936d-2a2a8b66fae1.png)

**Comment by Toddsand21** [comment]
I could see the changes at the top "Tribal Liaison Officer" and link, and also at the bottom but is everybody going to get the Gmail page when they click on their link?  And can we shorten Michel's title to just Tribal Liaison, ITOC and his number?  Because we just need to know who the Tribal Liaison contact is?

**Comment by mcharg** [comment]
@toddsand21 It'll open whatever the user has set as their default email program.  It opens in Outlook for me because that is set as my default.  I shortened Michel's title.

**Comment by Toddsand21** [comment]
Ok that should be fine.  It should be ready to post then.  I'll send the next New Issue after you reply to this one.  Thank you all for working on this.  I'm sue Heidi and others should be pleased it's being done!

**Comment by mcharg** [comment]
@toddsand21 Pushed live.  Might be about 30 minutes before the changes show up on the live site.
