### ISSUE TITLE
Request to update ONRR's Regulations Page (RIN 1012-AA27)

### ISSUE THREAD

**Issue by aklong09** [ONRR/onrr.gov-site#778]
Hello,

Please update ONRR’s Regulations page for RIN 1012-AA27, located at https://www.onrr.gov/Laws_R_D/FRNotices/AA27.htm.

Please update the abstract to include the following statement directly above the “For more information, please visit . . .” paragraph:

“ONRR published a Notice of Proposed Withdrawal of this rulemaking in the Federal Register on June 11, 2021. The proposed withdrawal provides a 60-day public comment period. Please see the Federal Register publication for more information on how to submit a comment on the proposed withdrawal. To be assured consideration, comments must be received by 11:59 p.m. EST on August 10, 2021.”

At the end of the bulleted list, please also add another bullet to read as follows:

“To view the proposed withdrawal rule:” and include a hyperlink to https://www.federalregister.gov/documents/2021/06/11/2021-12318/onrr-2020-valuation-reform-and-civil-penalty-rule-notification-of-proposed-withdrawal

Please let me know if you have any questions.
Thanks in advance,
Alexis

**Comment by Maroyafaied** [comment]
@meshanw  do you have time for this one as well?

**Comment by meshanw** [comment]
> @meshanw do you have time for this one as well?

Yes

**Comment by meshanw** [comment]
@aklong09 @Maroyafaied Please review http://2017onrr/Laws_R_D/FRNotices/AA27.htm

**Comment by aklong09** [comment]
Hi @meshanw --this looks good to me. We approve the changes. Thank you!

**Comment by Maroyafaied** [comment]
@meshanw looks good, please push live. Thanks

**Comment by meshanw** [comment]
Pushed to live site. 
https://onrr.gov/Laws_R_D/FRNotices/AA27.htm

**Comment by meshanw** [comment]
Changes are now live.
