### ISSUE TITLE
508 Compliance, 5 Documents 

### ISSUE THREAD

**Issue by LisaReimer** [ONRR/onrr.gov-site#780]
Good afternoon,

Please see attached 508 Compliance documents. There are 5 documents.

Thank you for your help.

- [x] [MPRH-Appendix-B.pdf](https://github.com/ONRR/onrr.gov-site/files/6651351/MPRH-Appendix-B.pdf)

- [x] [MPRH-Appendix-A ONRR Opr Number.pdf](https://github.com/ONRR/onrr.gov-site/files/6651352/MPRH-Appendix-A.ONRR.Opr.Number.pdf)

- [x] [RRM-Appendix.B.pdf](https://github.com/ONRR/onrr.gov-site/files/6651368/RRM-Appendix.B.pdf)

- [ ] [RRM-Printable.Minerals.Revenue.Handbook.pdf](https://github.com/ONRR/onrr.gov-site/files/6651371/RRM-Printable.Minerals.Revenue.Handbook.pdf)

- [x] [SMRH_Chapter_4.pdf](https://github.com/ONRR/onrr.gov-site/files/6651374/SMRH_Chapter_4.pdf)

Lisa Reimer

Minerals Revenue Specialist - Production Analyst
Reference, Royalty and Production, Team 4B
Reference and Reporting Management
Office of Natural Resources Revenue
Office Phone:  214-640-9049
Fax:  303-445-9547

**Comment by mcharg** [comment]
@lisareimer The printable handbook has regularity errors.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/b54c25b3-5708-4b63-910f-8252587866b5)

**Comment by mcharg** [comment]
@lisareimer The other 4 docs are updated in dev.  Let me know if they're good to push live.

**Comment by sghahn** [comment]
@mcharg they are good to go live. I'm looking at the "printable handbook" now, let you know ASAP on this one. Thanks

**Comment by mcharg** [comment]
@sghahn The four are pushed to the live site.

**Comment by sghahn** [comment]
@mcharg attached last document for this issue.

[RRM-Printable.Minerals.Revenue.Handbook_AccReport.pdf](https://github.com/ONRR/onrr.gov-site/files/6689237/RRM-Printable.Minerals.Revenue.Handbook_AccReport.pdf)

[RRM-Printable.Minerals.Revenue.Handbook.pdf](https://github.com/ONRR/onrr.gov-site/files/6689214/RRM-Printable.Minerals.Revenue.Handbook.pdf)

**Comment by mcharg** [comment]
@sghahn The printable handbook is updated in dev, let me know if it's good to post live.

**Comment by mcharg** [comment]
@sghahn Is the printable handbook good to push live?

**Comment by sghahn** [comment]
@mcharg Yes, please push the printable handbook to live site, thank you for following up on this one!!

**Comment by mcharg** [comment]
@sghahn Done
