### ISSUE TITLE
Update Contact on ONRR.GOV

### ISSUE THREAD

**Issue by Sheetsj** [ONRR/onrr.gov-site#781]
Hello,
We need to update the contacts on ONRR.GOV

Location: Contact Us-Online Resources-ONRR contacts by Company assignment-Accounts Receivable, Billing, and Financial Issues Information --Indian

**Comment by Sheetsj** [comment]
The file is not letting me upload it here.

**Comment by Sheetsj** [comment]
[finserAssign-IND 2.pdf](https://github.com/ONRR/onrr.gov-site/files/6656860/finserAssign-IND.2.pdf)

**Comment by mcharg** [comment]
@sheetsj This is updated in dev.  Let me know if it looks good to post to the live site.
http://2017onrr/about/contact.htm

**Comment by Sheetsj** [comment]
Hello,

I was able to view it and it looks good. I am not able to get onto the site right now. The internet is going in and out. But I agree that it could go live.

Thank you,

Jessica Sheets
Financial Services Staff Accountant
Office of Natural Resources Revenue
Phone: 303-231-3401
________________________________
From: mcharg ***@***.***>
Sent: Monday, June 21, 2021 9:54 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Sheets, Jessica E ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update Contact on ONRR.GOV (#781)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Sheetsj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSheetsj&data=04%7C01%7Cjessica.sheets%40onrr.gov%7Ce5123c1153934669829608d934cf4314%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637598887498310382%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UDTE%2FFh5j%2Fo8BEhilso%2BxDC8XKPUO5BTSDlgJ3iuIP8%3D&reserved=0> This is updated in dev. Let me know if it looks good to post to the live site.
http://2017onrr/about/contact.htm

**Comment by mcharg** [comment]
@Sheetsj Great.  Once I can get back on the VPN, I'll push it live.

**Comment by mcharg** [comment]
@sheetsj Pushed live.  Might be a bit before it shows up on the live site.
