### ISSUE TITLE
Replace the XREF.txt and the CRLNumber.xlsx files with a single xls file

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#782]
Need to get the file from @StaceyKaiser will convert the text file to excel and @bowlenj approved removing the other excel file once we get that.

**Comment by StaceyKaiser** [comment]
Please replace the existing file located at: http://www.onrr.gov/ReportPay/CrossRef.htm called “Downloadable Text Cross-Reference Lease to Agreement Number” with the file entitled “June 2021 Lease Agreement XREF.xlsx”.  It was queried from the system on 6/21/2021.
[June 2021 Lease Agreement XREF.xlsx](https://github.com/ONRR/onrr.gov-site/files/6689311/June.2021.Lease.Agreement.XREF.xlsx)

**Comment by mcharg** [comment]
Thank you @StaceyKaiser!

**Comment by CM805** [comment]
@StaceyKaiser can you please correct the two accessibility issues and get it back to me?

![image](https://user-images.githubusercontent.com/83783622/123149210-419f5300-d41e-11eb-915d-df4ecd0fbb12.png)

![image](https://user-images.githubusercontent.com/83783622/123149253-4e23ab80-d41e-11eb-8be7-96070913b8e9.png)

**Comment by StaceyKaiser** [comment]
Here is a new Excel file
[June 2021 Lease Agreement XREF.xlsx](https://github.com/ONRR/onrr.gov-site/files/6705207/June.2021.Lease.Agreement.XREF.xlsx)

**Comment by CM805** [comment]
@StaceyKaiser there is one more accessibility issue.  My apologies for sending the same screenshot twice last time.  I meant to have this as one of the screenshots.
![image](https://user-images.githubusercontent.com/83783622/123821744-e86d6e80-d8b8-11eb-9919-7f502f7c6499.png)

**Comment by StaceyKaiser** [comment]
Please see attached Excel file with an update to the colors.
[June 2021 Lease Agreement XREF.xlsx](https://github.com/ONRR/onrr.gov-site/files/6743264/June.2021.Lease.Agreement.XREF.xlsx)

**Comment by CM805** [comment]
@StaceyKaiser this is ready to review in dev: http://2017onrr/reportpay/CrossRef.htm

Also, I had to make a change to the table colors again to get it to fully pass the accessibility check.  Basically, if you use one of the black table schemes or the dark blue you should be fine.  Orange, green, and light blue all cause issues.  Here is the file the way I modified it.

[June.2021.Lease.Agreement.XREF.xlsx](https://github.com/ONRR/onrr.gov-site/files/6743639/June.2021.Lease.Agreement.XREF.xlsx)

@mcharg I updated the old XREF.TXT file on the Accessibility Tracking Sheet and the Content Audit by indicating both are removed.  Do I add the new document to both worksheets?  And if I do, should I change the program manager and should I add a new column so we can begin to track the document contact person (in this case Stacey)?

**Comment by StaceyKaiser** [comment]
I get an error when I click on the link to the file: 404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

**Comment by CM805** [comment]
@StaceyKaiser can you try again?  I just added .xlsx to the file name on the link

**Comment by StaceyKaiser** [comment]
Looks good now.  You can post to the live site now.  Thanks!

**Comment by CM805** [comment]
Should be live later today at:  https://onrr.gov/reportpay/CrossRef.htm

**Comment by mcharg** [comment]
@CM805 You can note in the Notes column in the Accessibility Tracking sheet that we're replacing the old documents with the new one.  We haven't been adding new documents to that sheet.

For the Content Audit sheet, we should add the new document, so that one reflects the current state of the site.  We should probably add columns to that one with the program manager (pulled from the accessibility tracking sheet for documents in that one) and document updaters.

**Comment by CM805** [comment]
Verified changes on live site.

Created issue #805 to update Accessibility Tracking document with additional information
