### ISSUE TITLE
508 Compliance 2 Doc), Phase 2

### ISSUE THREAD

**Issue by LisaReimer** [ONRR/onrr.gov-site#783]
Good afternoon,

Please see attached 508 Compliance document (1).

[MPRH-Chapter-6-SH redo.pdf](https://github.com/ONRR/onrr.gov-site/files/6659693/MPRH-Chapter-6-SH.redo.pdf)

Thank you for your help.

**Comment by mcharg** [comment]
@lisareimer This is updated in dev.  Let me know if it's good to push to the live site.

**Comment by sghahn** [comment]
@mcharg Yes, please push to live site

**Comment by sghahn** [comment]
@mcharg please upload this to live site as well...

- [ ] [4430.pdf](https://github.com/ONRR/onrr.gov-site/files/6689266/4430.pdf)

**Comment by mcharg** [comment]
@sghahn Chapter 6 is pushed live.  4430 is updated in dev, let me know if it's good to post live.

**Comment by sghahn** [comment]
@mcharg Ch. 6 is good to go live. 4430 good to go live when you are ready.

**Comment by mcharg** [comment]
@sghahn Both docs have been pushed live.
