### ISSUE TITLE
Tribal Consultation Page Changes

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#784]
1) On the Tribal Consultation page in the upper right hand corner and under the box titled “Contacts”. where it says Click here for  FIMO staff and related contacts. Please delete all including its link to FIMO staff: and replace with a link (to Tribal Liaison Officer), and it should say  "Email the Tribal Liaison Officer with questions". same as the Tribal Assistance page's upper right hand corner..
2) Next, please delete everything including the heading 2019 Scheduled Consultations and its 3 paragraphs that follow including the Box with the 3 scheduled meetings with the Dates and Locations of those consultations for 2019.
3) Also delete the sentence and it's link under the the box and following the ? that begins with "Should you have questions please contact..... (delete all).
4) At this time it will not be replaced with anything.

**Comment by meshanw** [comment]
@Toddsand21 @mcharg Please review http://2017onrr/IndianServices/consultation.htm

**Comment by mcharg** [comment]
@meshanw Looks good to me.

**Comment by Toddsand21** [comment]
Yes it looks fine to me and ready to post.  And I think we're done w these pages.  Thanks for all your help.

**Comment by meshanw** [comment]
Pushed to live site. https://onrr.gov/IndianServices/consultation.htm
