### ISSUE TITLE
Plan onrr.gov usability study

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#788]

**Comment by mcharg** [comment]
@Maroyafaied Should we start planning a study on the wireframes next sprint?  I think it's going to be a while before we get the live site to a place where it's ready to do a study.

**Comment by Maroyafaied** [comment]
@mcharg Ya we can the study on the wireframes and maybe include questions about our color choices when we go live.

**Comment by mcharg** [comment]
Draft plan is ready.
https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/User%20Research/Studies/08_Wireframes/Research%20plan%20ONRR.gov.docx?d=wb237a438c97c4ae98b926bfa5df47a31&csf=1&web=1&e=twHrAG

@Maroyafaied @cthomasONRR Can you please review?

**Comment by Maroyafaied** [comment]
@mcharg this looks good, I added one comment. I'm wondering if we could also use this study to ask about the how leasing works diagram design and homepage visual design like the icons, what do you think?

**Comment by mcharg** [comment]
@Maroyafaied If we have time we can cover those.

**Comment by mcharg** [comment]
@Maroyafaied I added those to the plan.
