### ISSUE TITLE
ONRR Broken Links

### ISSUE THREAD

**Issue by alenahuang** [ONRR/onrr.gov-site#79]
The bullet is the page that the broken link is on. The sub bullet is the actual link that is broken.

 - [x] **1** https://www.onrr.gov/About/contact.htm 
 "USEITI Multi-Stakeholder Group"
- [x] **2**  https://www.onrr.gov/about/production-data.htm
  - U.S. Extractive Industries Transparency Initiative (USEITI)
  - Federal Production page of the USEITI Data Portal
  - available for download
- [x] **3** https://www.onrr.gov/about/employment.htm
  - Find Recent Graduate Jobs
- [x] **4**https://www.onrr.gov/about/Presentations.htm
  - Five-Year Asset Management Strategic Business Plan FY 2008-2012
  - Five-Year Compliance Business Plan FY 2008-2012
  - Five-Year Financial Management Business Plan FY 2008-2012
  - Five-Year Indian Trust Business Plan FY 2008-2012
  - Five-Year Production Business Plan FY 2008-2012
  - Five-Year Resources and Information Management Strategic Business Plan FY 2008-2012
- [x] **5** https://www.onrr.gov/About/NewsReleases.htm
  - (in the 2016 section) Mountain Hawk Energy, LLC Assessed Civil Penalty
  - (in the 2014 section) Extractive Industries Transparency Initiative Board Approves U.S. Candidacy Application
- [ ] **6** https://www.onrr.gov/Valuation/index.htm
  - Oil and Gas Payor Handbook, Volume III Product Valuation (published 2001)
- [x] **7** https://www.onrr.gov/reportpay/prod-checklist.htm
  - (not the correct file) EMARF
- [x] **8** https://www.onrr.gov/ReportPay/Handbooks/indian-payor-handbook-chapter-2.htm
  - (2.5.6.1 Production After July 1, 2015 Tab) February 15, 2015
  - (2.5.6.1 Production After July 1, 2015 Tab) August 21,2015
- [x] **9** https://www.onrr.gov/IndianServices/fimo.htm
  - Bureau of Land Management (BLM)
- [x] **10** https://www.onrr.gov/IndianServices/tribal-assistance.htm
  - Indian Distribution Dates for Current Calendar Year

**Comment by lpgoldstein** [comment]
- [ ] **1** https://www.onrr.gov/About/contact.htm 
 "USEITI Multi-Stakeholder Group"

is ready for your review @jennmalcolm  @Maroyafaied http://2017onrr/about/contact.htm

**Comment by lpgoldstein** [comment]
@jennmalcolm @Maroyafaied I think we should just delete this page all together. It's outdated. 
 - [ ] **2**  https://www.onrr.gov/about/production-data.htm
  - U.S. Extractive Industries Transparency Initiative (USEITI)
  - Federal Production page of the USEITI Data Portal
  - available for download

**Comment by jennmalcolm** [comment]
I agree we shouldn't have that page @lpgoldstein.

**Comment by lpgoldstein** [comment]
3 https://www.onrr.gov/about/employment.htm
Find Recent Graduate Jobs
@jennmalcolm @Maroyafaied Ready for review -I deleted the above link and updated the "students and recent grads link"

**Comment by lpgoldstein** [comment]
9 https://www.onrr.gov/IndianServices/fimo.htm
Bureau of Land Management (BLM) ready for review http://2017onrr/IndianServices/fimo.htm

**Comment by jennmalcolm** [comment]
I've reviewed 1, 3, and 9. You can make those live.

**Comment by lpgoldstein** [comment]
- [ ]  4 https://www.onrr.gov/about/Presentations.htm

Five-Year Asset Management Strategic Business Plan FY 2008-2012
Five-Year Compliance Business Plan FY 2008-2012
Five-Year Financial Management Business Plan FY 2008-2012
Five-Year Indian Trust Business Plan FY 2008-2012
Five-Year Production Business Plan FY 2008-2012
Five-Year Resources and Information Management Strategic Business Plan FY 2008-2012

@jennmalcolm ready for your review http://2017onrr/About/Presentations.htm

**Comment by lpgoldstein** [comment]
- [ ] 10 https://www.onrr.gov/IndianServices/tribal-assistance.htm

Indian Distribution Dates for Current Calendar Year

@jennmalcolm ready for your review file://iondeniisp01/ONRR2017/IndianServices/tribal-assistance.htm

**Comment by lpgoldstein** [comment]
- [ ] 8 https://www.onrr.gov/ReportPay/Handbooks/indian-payor-handbook-chapter-2.htm

(2.5.6.1 Production After July 1, 2015 Tab) February 15, 2015
(2.5.6.1 Production After July 1, 2015 Tab) August 21,2015

@jennmalcolm I think I figured out this one. The February date should actually be May and the pdfs were in a different folder so I copied them into this folder so that the link would work.

**Comment by jennmalcolm** [comment]
@lpgoldstein I checked this morning and Dreamweaver didn't work to push all of the pages that have the about left side nav, so we'll have to push each individually. I did that for the about/overview (index) page. Could you work on finding and pushing the other pages that have the left side nav with production data still on it.

**Comment by jennmalcolm** [comment]
I reviewed 4, 8, and 10. They look good.

**Comment by lpgoldstein** [comment]
@jennmalcolm I think I found all of the production data references on the left side nav! http://2017onrr/about/index.htm

- [ ]  2 https://www.onrr.gov/about/production-data.htm

**Comment by jennmalcolm** [comment]
Thanks @lpgoldstein I think just the rules and regulations page still has production data, so I'll push that.

**Comment by lpgoldstein** [comment]
closing this issue and will address 6 in issue #51
