### ISSUE TITLE
Work with regulations team to make FOGRMA Amendments page accessible

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#792]
It currently uses color coding and the colors used aren't enough contrast from the background.  I asked and they want to keep the page instead of linking externally.
https://www.onrr.gov/Laws_R_D/PubLaws/PL97451.htm

Alexis Long is the contact for this on the regulations team.

**Comment by daniel-coleman-1** [comment]
If I understand Section 508 correctly, we need to get the contrast ratio to 4.5:1.

I switched the red to blue, and the magenta to a dark green.  
Blue (#00008B) comes in at 15.3:1
Dark Green (#006400) comes in at 7.44:1

I used:
https://adasitecompliance.com/ada-color-contrast-checker/

Updated page on dev:
http://2017onrr/Laws_R_D/PubLaws/PL97451.htm

**Comment by mcharg** [comment]
@daniel-coleman-1 I think we may also need to make sure the green and blue are contrasted enough from each other, but the bold/italics may help with that.

Can you please work with @aklong09 to make sure the regulations team is okay with the changes?

**Comment by mcharg** [comment]
@daniel-coleman-1 We should also remove the underlining as a code, since underlines mean clickable on the rest of the site.

**Comment by mcharg** [comment]
@daniel-coleman-1 You can use color brewer with the colorblind safe box checked to find colors that are differentiated enough from each other.
https://colorbrewer2.org/

**Comment by daniel-coleman-1** [comment]
@mcharg  Colorbrewer looks like its made for mapping - but maybe I'm missing something there?  We talked in the stand up and Mojo told me to use Lighthouse from within Chrome, I ran an accessibility check and it passed - but it looks like it didn't compare the text colors against each other, just the foreground to the background.

**Comment by daniel-coleman-1** [comment]
submitted changes to @aklong via email, awaiting approval.

**Comment by mcharg** [comment]
@daniel-coleman-1 You can only rely so much on automated checks and those won't tell you about whether two colors are differentiated enough from each other if they're not on top of each other.  Color Brewer was designed for maps, but it will give you colors that are differentiated enough for colorblind users to distinguish.

**Comment by mcharg** [comment]
@daniel-coleman-1 The section numbers also look like links, but they're not, which needs to be fixed.

**Comment by mcharg** [comment]
@daniel-coleman-1 Found an Adobe pallette accessibility check and it looks like your colors are good.  
https://color.adobe.com/create/color-accessibility
![image](https://user-images.githubusercontent.com/38465926/123154840-5dfaba00-d435-11eb-9830-d970d656732a.png)

I still think we need to reserve underlining for links.

**Comment by daniel-coleman-1** [comment]
Changes have been approved and are live:
https://www.onrr.gov/Laws_R_D/PubLaws/PL97451.htm

Also a sidenote:
I went with blue and green because the two primary types of colorblindness are red/green and blue/yellow.
