### ISSUE TITLE
RRM 508 Compliance Ph 3

### ISSUE THREAD

**Issue by sghahn** [ONRR/onrr.gov-site#796]
@mcharg Please remove the following documents from the website:

- [x] https://www.onrr.gov/ReportPay/PDFDocs/Book-1-Tuesday-September-8.pdf
- [x] https://www.onrr.gov/ReportPay/PDFDocs/Book-2-Wednesday-September-9.pdf
- [x] https://www.onrr.gov/ReportPay/PDFDocs/Solid-Minerals-Reporter -Training-Agenda.pdf
- [x] https://www.onrr.gov/ReportPay/PDFDocs/20150730.pdf
- [x] https://www.onrr.gov/About/excel/Production-Summary-Data-for-ONRR-Website.xlsx

**Comment by sghahn** [comment]
I'm not sure why the document link isn't working for https://www.onrr.gov/ReportPay/PDFDocs/Solid-Minerals-Reporter -Training-Agenda.pdf it's line #68 on Maroya's spreadsheet

**Comment by mcharg** [comment]
@sghahn I'll find the doc and remove it.

**Comment by mcharg** [comment]
@sghahn The reporter letter https://www.onrr.gov/ReportPay/PDFDocs/20150730.pdf is also on the reporter letters page (and we have a copy of it in a different folder), should it be removed there, as well? https://www.onrr.gov/PDFDocs/20150730.pdf

**Comment by sghahn** [comment]
@mcharg yes, please remove in all locations.

**Comment by mcharg** [comment]
@sghahn Done.  I went ahead and made all these changes in both dev and the live site, since the only one that was still linked on the site was the reporter letter on the reporter letters page.

**Comment by sghahn** [comment]
@mcharg I'd like to keep the issue open for the Phase 3 compliance docs, it would be open a couple of months, if that's ok with you?? It would be easier for out team to track all of the documents rather than having several different issues open. What are your thoughst?

**Comment by mcharg** [comment]
@sghahn Ok.

**Comment by jillbong79** [comment]
6 Documents and Reports Phase 3:
[JOA_ACC_RPT.PDF](https://github.com/ONRR/onrr.gov-site/files/6712328/JOA_ACC_RPT.PDF)
[JOA.pdf](https://github.com/ONRR/onrr.gov-site/files/6712329/JOA.pdf)
[eCommerce_2012_Acrobat_Accessibility_Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6712330/eCommerce_2012_Acrobat_Accessibility_Report.PDF)
[eCommerce_2012.pdf](https://github.com/ONRR/onrr.gov-site/files/6712332/eCommerce_2012.pdf)
[OGORedits Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6712336/OGORedits.Acrobat.Accessibility.Report.PDF)
[OGORedits.PDF](https://github.com/ONRR/onrr.gov-site/files/6712337/OGORedits.PDF)
[20100507 Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6712338/20100507.Acrobat.Accessibility.Report.PDF)
[20100507.pdf](https://github.com/ONRR/onrr.gov-site/files/6712339/20100507.pdf)
[MPRH-Appendix-K Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6712340/MPRH-Appendix-K.Acrobat.Accessibility.Report.PDF)
[MPRH-Appendix-K.pdf](https://github.com/ONRR/onrr.gov-site/files/6712341/MPRH-Appendix-K.pdf)
[SMRH_Title_Page Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6712342/SMRH_Title_Page.Acrobat.Accessibility.Report.PDF)
[SMRH_Title_Page.pdf](https://github.com/ONRR/onrr.gov-site/files/6712343/SMRH_Title_Page.pdf)

**Comment by mcharg** [comment]
@jillbong79 All 6 docs are updated on both the dev and live sites.  Might be a bit before they show up on the live site.

**Comment by jillbong79** [comment]
@mcharg thanks!  will update our side appreciate it

**Comment by jillbong79** [comment]
Documents and Reports Phase 3:
[SMRH_Appendix_C.pdf](https://github.com/ONRR/onrr.gov-site/files/6719077/SMRH_Appendix_C.pdf)
[20101215 Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6719078/20101215.Acrobat.Accessibility.Report.PDF)
[20101215.pdf](https://github.com/ONRR/onrr.gov-site/files/6719079/20101215.pdf)
[MPRH-Appendix-M Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6719080/MPRH-Appendix-M.Acrobat.Accessibility.Report.PDF)
[MPRH-Appendix-M.pdf](https://github.com/ONRR/onrr.gov-site/files/6719081/MPRH-Appendix-M.pdf)
[4293ss1a Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6719082/4293ss1a.Acrobat.Accessibility.Report.PDF)
[4293ss1a.pdf](https://github.com/ONRR/onrr.gov-site/files/6719083/4293ss1a.pdf)
[4293s1a Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6719084/4293s1a.Acrobat.Accessibility.Report.PDF)
[4293s1a.pdf](https://github.com/ONRR/onrr.gov-site/files/6719085/4293s1a.pdf)
[4293s1b Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6719086/4293s1b.Acrobat.Accessibility.Report.PDF)
[4293s1b.pdf](https://github.com/ONRR/onrr.gov-site/files/6719087/4293s1b.pdf)
[MPRH-Appendix-N Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6719088/MPRH-Appendix-N.Acrobat.Accessibility.Report.PDF)
[MPRH-Appendix-N.pdf](https://github.com/ONRR/onrr.gov-site/files/6719089/MPRH-Appendix-N.pdf)
[SMRH_Chapter_4 Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6719090/SMRH_Chapter_4.Acrobat.Accessibility.Report.PDF)
[SMRH_Chapter_4.pdf](https://github.com/ONRR/onrr.gov-site/files/6719091/SMRH_Chapter_4.pdf)
[SMRH_Appendix_C Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6719092/SMRH_Appendix_C.Acrobat.Accessibility.Report.PDF)

**Comment by jillbong79** [comment]
I believe this is a duplicate from phase 2.  Would someone mind checking this??
![image](https://user-images.githubusercontent.com/51677345/123491917-3f332980-d5d5-11eb-8008-d8e5adb6abd0.png)
[SalesTyp Codes--non-Solids.pdf](https://github.com/ONRR/onrr.gov-site/files/6719134/SalesTyp.Codes--non-Solids.pdf)
[SalesTyp Codes--non-Solids.pdf.accreport.pdf](https://github.com/ONRR/onrr.gov-site/files/6719135/SalesTyp.Codes--non-Solids.pdf.accreport.pdf)

**Comment by mcharg** [comment]
@jillbong79 I have the SalesTyp Codes--Non-Solids.pdf listed as phase 2 and it's already accessible.

**Comment by mcharg** [comment]
@jillbong79 SMRH_Chapter_4 was also updated in phase 2.

**Comment by mcharg** [comment]
@jillbong79 The documents above are all updated on both dev and the live site.  Might be a bit before they show up on the live site.

**Comment by jillbong79** [comment]
Phase 3 Docs:
[Current-Pipeline-Condensate-Systems.pdf](https://github.com/ONRR/onrr.gov-site/files/6728649/Current-Pipeline-Condensate-Systems.pdf)
[PASR_CSV_Record_Layout Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6728651/PASR_CSV_Record_Layout.Acrobat.Accessibility.Report.PDF)
[PASR_CSV_Record_Layout.pdf](https://github.com/ONRR/onrr.gov-site/files/6728652/PASR_CSV_Record_Layout.pdf)
[4440Instr Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6728653/4440Instr.Acrobat.Accessibility.Report.PDF)
[4440Instr.pdf](https://github.com/ONRR/onrr.gov-site/files/6728654/4440Instr.pdf)
[RRM-Appendix.B Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6728655/RRM-Appendix.B.Acrobat.Accessibility.Report.PDF)
[RRM-Appendix.B.pdf](https://github.com/ONRR/onrr.gov-site/files/6728656/RRM-Appendix.B.pdf)
[4292ss1a Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6728657/4292ss1a.Acrobat.Accessibility.Report.PDF)
[4292ss1a.pdf](https://github.com/ONRR/onrr.gov-site/files/6728658/4292ss1a.pdf)
[Current-Pipeline-Condensate-Systems Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6728659/Current-Pipeline-Condensate-Systems.Acrobat.Accessibility.Report.PDF)

**Comment by mcharg** [comment]
@jillbong79 The list above is updated in both dev and the live site.  Might be a bit before they show up on the live site.

**Comment by jillbong79** [comment]
Phase 3 Upload:
[USGS-sodium-potassium-011877 Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6736301/USGS-sodium-potassium-011877.Acrobat.Accessibility.Report.PDF)
[USGS-sodium-potassium-011877.pdf](https://github.com/ONRR/onrr.gov-site/files/6736302/USGS-sodium-potassium-011877.pdf)
[RRM-Chapter.3 Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6736303/RRM-Chapter.3.Acrobat.Accessibility.Report.PDF)
[RRM-Chapter.3.pdf](https://github.com/ONRR/onrr.gov-site/files/6736304/RRM-Chapter.3.pdf)
[SMRH_Chapter_9 Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6736305/SMRH_Chapter_9.Acrobat.Accessibility.Report.PDF)
[SMRH_Chapter_9.pdf](https://github.com/ONRR/onrr.gov-site/files/6736306/SMRH_Chapter_9.pdf)
[RRM-Appendix.G Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6736307/RRM-Appendix.G.Acrobat.Accessibility.Report.PDF)
[RRM-Appendix.G.pdf](https://github.com/ONRR/onrr.gov-site/files/6736308/RRM-Appendix.G.pdf)
[4292s1b Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6736309/4292s1b.Acrobat.Accessibility.Report.PDF)
[4292s1b.pdf](https://github.com/ONRR/onrr.gov-site/files/6736310/4292s1b.pdf)
[RRM-Multi-Unit.Well Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6736669/RRM-Multi-Unit.Well.Acrobat.Accessibility.Report.PDF)
[RRM-Multi-Unit.Well.Agreements.pdf](https://github.com/ONRR/onrr.gov-site/files/6736670/RRM-Multi-Unit.Well.Agreements.pdf)

Thanks!!

**Comment by sghahn** [comment]
@mcharg 7 508 uploads:

- [ ] [4292.pdf](https://github.com/ONRR/onrr.gov-site/files/6742504/4292.pdf)

- [ ] [4293.pdf](https://github.com/ONRR/onrr.gov-site/files/6742509/4293.pdf)

- [ ] [4393.pdf](https://github.com/ONRR/onrr.gov-site/files/6742511/4393.pdf)

- [ ] [4411.pdf](https://github.com/ONRR/onrr.gov-site/files/6742512/4411.pdf)

- [ ] [SMRH_Abbreviations.pdf](https://github.com/ONRR/onrr.gov-site/files/6742513/SMRH_Abbreviations.pdf)

- [ ] [SMRH_Appendix_B.pdf](https://github.com/ONRR/onrr.gov-site/files/6742514/SMRH_Appendix_B.pdf)

- [ ] [SMRH_Glossary.pdf](https://github.com/ONRR/onrr.gov-site/files/6742515/SMRH_Glossary.pdf)

**Comment by mcharg** [comment]
@sghahn The 4411.pdf has some errors about tagged annotations.
![image](https://user-images.githubusercontent.com/38465926/124003478-fc8e9a00-d9a4-11eb-8741-bcabe5fa9548.png)

**Comment by sghahn** [comment]
@mcharg I'll take a look at this now, thank you.

**Comment by mcharg** [comment]
@sghahn The rest of the docs in your list look good and have been updated.

**Comment by sghahn** [comment]
@mcharg corrected 4411 with report

- [ ] [4411.pdf](https://github.com/ONRR/onrr.gov-site/files/6742888/4411.pdf)
- [ ] [4411_AccReport.pdf](https://github.com/ONRR/onrr.gov-site/files/6742889/4411_AccReport.pdf)

**Comment by mcharg** [comment]
@sghahn 4411 is updated.

**Comment by jillbong79** [comment]
Phase 3 Upload:
[4292s1a.pdf](https://github.com/ONRR/onrr.gov-site/files/6743432/4292s1a.pdf)
[4292s1a Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6743433/4292s1a.Acrobat.Accessibility.Report.PDF)
[RRM-Overlapping.Agreement.Training.2020.Handbook.pdf](https://github.com/ONRR/onrr.gov-site/files/6743563/RRM-Overlapping.Agreement.Training.2020.Handbook.pdf)
[RRM-Overlapping.Agreement Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6743564/RRM-Overlapping.Agreement.Acrobat.Accessibility.Report.PDF)
[4440.pdf](https://github.com/ONRR/onrr.gov-site/files/6743680/4440.pdf)
[4440 Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6743681/4440.Acrobat.Accessibility.Report.PDF)
[ASCpasr.PDF](https://github.com/ONRR/onrr.gov-site/files/6743682/ASCpasr.PDF)
[ASCpasr Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6743683/ASCpasr.Acrobat.Accessibility.Report.PDF)
[Gulf_TIMS_Contacts.pdf](https://github.com/ONRR/onrr.gov-site/files/6743687/Gulf_TIMS_Contacts.pdf)
[Gulf_TIMS_Contacts Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6743688/Gulf_TIMS_Contacts.Acrobat.Accessibility.Report.PDF)
[SMRH.Complete.Handbook Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6743689/SMRH.Complete.Handbook.Acrobat.Accessibility.Report.PDF)
[SMRH.Complete.Handbook.pdf](https://github.com/ONRR/onrr.gov-site/files/6743690/SMRH.Complete.Handbook.pdf)
[SMRH_Appendix_F.pdf](https://github.com/ONRR/onrr.gov-site/files/6743694/SMRH_Appendix_F.pdf)
[SMRH_Appendix_F Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6743695/SMRH_Appendix_F.Acrobat.Accessibility.Report.PDF)


Thanks!

**Comment by jillbong79** [comment]
Phase 3 Upload:
[SMRH_Appendix_E Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6744224/SMRH_Appendix_E.Acrobat.Accessibility.Report.PDF)
[SMRH_Chapter_7 Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6744225/SMRH_Chapter_7.Acrobat.Accessibility.Report.PDF)
[SMRH_Chapter_1 Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6744226/SMRH_Chapter_1.Acrobat.Accessibility.Report.PDF)
[SMRH_Chapter_3 Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6744227/SMRH_Chapter_3.Acrobat.Accessibility.Report.PDF)
[MPRH-Appendix-E Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6744228/MPRH-Appendix-E.Acrobat.Accessibility.Report.PDF)
[SMRH_Chapter_6 Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6744229/SMRH_Chapter_6.Acrobat.Accessibility.Report.PDF)
[WellStatusCodes Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6744230/WellStatusCodes.Acrobat.Accessibility.Report.PDF)
[RRM-Appendix.A Acrobat Accessibility Report.PDF](https://github.com/ONRR/onrr.gov-site/files/6744231/RRM-Appendix.A.Acrobat.Accessibility.Report.PDF)
[RRM-Appendix.A.pdf](https://github.com/ONRR/onrr.gov-site/files/6744232/RRM-Appendix.A.pdf)
[WellStatusCodes.pdf](https://github.com/ONRR/onrr.gov-site/files/6744233/WellStatusCodes.pdf)
[SMRH_Chapter_6.pdf](https://github.com/ONRR/onrr.gov-site/files/6744234/SMRH_Chapter_6.pdf)
[MPRH-Appendix-E.pdf](https://github.com/ONRR/onrr.gov-site/files/6744235/MPRH-Appendix-E.pdf)
[SMRH_Chapter_3.pdf](https://github.com/ONRR/onrr.gov-site/files/6744236/SMRH_Chapter_3.pdf)
[SMRH_Chapter_1.pdf](https://github.com/ONRR/onrr.gov-site/files/6744237/SMRH_Chapter_1.pdf)
[SMRH_Chapter_7.pdf](https://github.com/ONRR/onrr.gov-site/files/6744238/SMRH_Chapter_7.pdf)
[SMRH_Appendix_E.pdf](https://github.com/ONRR/onrr.gov-site/files/6744239/SMRH_Appendix_E.pdf)

**Comment by mcharg** [comment]
@jillbong79 RRM-Appendix.A was updated in Phase 2.  Do you want me to use this doc or leave the one that's there now?

**Comment by mcharg** [comment]
@jillbong79 The rest of the documents are all updated.  I think that's all the Phase 3 docs for your team.

**Comment by sghahn** [comment]
@mcharg Leave the RRM-Appendix A from phase 2 please don't use the one uploaded yesterday. Thank  you.

Yes, this should should make RRM 100% complete on Phase 3 (and Phase 1 & 2)!!! yay @jillbong79 !!

Many thanks everyone. Have a great holiday weekend. I will update RRM on our completed status.

**Comment by mcharg** [comment]
@sghahn @jillbong79 You were super fast with this round!  And you're the first team to finish all 3 phases!!

So much for keeping the issue open for a couple months.  Is it good to close?

**Comment by sghahn** [comment]
@mcharg @jillbong79  Jill blew it out of the park!! We are thrilled to be done, yes we can close the ticket, woot woot!!

**Comment by jillbong79** [comment]
@mcharg @sghahn whoop whoop!
