### ISSUE TITLE
Event Calendar  (please enter these on the Allottee Assistance page under this tab)

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#799]
EVENT CALENDAR
TITLE: FIMO JULY 2021 PHONE-IN OUTREACH
Date: Wednesday, July 14, 2021
Time: 10:00 AM - 12:00 PM
Location: By Telephone
Description:  Meeting will be a Call-In Meeting to hear current updates from the Federal Indian Minerals Office.  Representatives from BLM, BTFA, and BIA will be available to discuss topics regarding Indian oil and gas, IIM accounts, Indian trust property issues, and probate.  There will be a Q&A session for landowners to ask questions. A limited number of lines will be available for callers to this phone-in meeting. 

Who Should Attend:  IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Navajo Agency Area or any mineral owners located in the Four Corners Region.
Other Information:  The Federal Indian Minerals Office is open from Monday through Friday, 8:00 AM to 12:00 PM, closed during the lunch hour, 1:00 PM to 4:00 PM. 
Event Contact 
Name: Federal Indian Minerals Office 
Phone: Toll Free (800) 283-2839 
Email: Leona.begay@onrr.gov, Jennifer.benally@onrr.gov

TITLE: PAWNEE AREA MEETING
Date: Tuesday, July 20, 2021
Time: 1:00 pm - 2:00 pm

Location: By Telephone 
Description: Meeting will be a Call-in Meeting to hear a presentation and updates from ONRR OKC Office.  Representatives from BLM, BTFM, and BIA will also be available to discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust properties.  
Who Should Attend:  IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Pawnee Agency Area, or any mineral owners located in the Southern Plains Region in Oklahoma. 
Other Information: To attend meeting you must contact the ONRR OKC Outreach office at (800) 354-7015 to reserve your space and   get the call-in number and passcode for the meeting.   ONNR OKC Outreach office hours are Monday- Friday from 7:30 am-5:00 pm.
Event Contact:
Name: ONRR OKC Outreach Office 
Phone: Toll Free (800) 354-7015 
Email:  onrroutreachokc@onrr.gov

Title: FIMO JULY 2021 PHONE-IN OUTREACH
Date: Wednesday, July 21, 2021
Time: 10:00 AM - 11:30 PM
Location: By Telephone 
Description: Meeting will be a Call-In Meeting to hear current updates from the Federal Indian Minerals Office.  Representatives from BLM, BTFA, and BIA will be available to discuss topics regarding Indian oil and gas, IIM accounts, Indian trust property issues, and probate.  There will be a Q&A session for landowners to ask questions. A limited number of lines will be available for callers to this phone-in meeting. 

Who Should Attend:  IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Navajo Agency Area or any mineral owners located in the Four Corners Region. 
Other Information:  The Federal Indian Minerals Office is open from Monday through Friday, 8:00 AM to 12:00 PM, closed during the lunch hour, 1:00 PM to 4:00 PM. 
Event Contact:
Name: Federal Indian Minerals Office 
Phone: Toll Free (800) 283-2839 
Email: Leona.begay@onrr.gov, Jennifer.benally@onrr.gov

Title:  Fort Duchesne and Salt Lake City, UT Area Virtual Outreach  
Date:  Wednesday, July 28, 2021  
Time: 1:00 pm-2:00 pm MST  
Location: By Telephone 
Description: Representatives from the Office of Natural Resources Revenue will host a Question and Answer session by phone for Indian Mineral Owners and Trust Property Owners regarding their Indian Oil & Gas leases, IIM Accounts, and Indian Trust Properties. Representatives from the Bureau of Land Management, Bureau of Indian Affairs, and Bureau of Trust Funds Administration are invited to be in attendance to answer questions.   
Who Should Attend:  IIM account holders, Indian mineral owners, and Indian trust property owners in the Fort Duchesne and Salt Lake City area in Utah.   
Other Information: To attend the outreach session, please contact the ONRR Denver Outreach Office at (800) 982-3226, for the call-in number and passcode.  The ONRR Denver Outreach Office hours are Monday-Friday 7:30am-4:00pm.  

Event Contact:  
Name: ONRR Denver Outreach Office, 
Phone: Toll Free (800) 982-3226, 
Email:  onrroutreachdenver@onrr.gov

**Comment by meshanw** [comment]
@Toddsand21 Would you like the June events removed?

**Comment by Toddsand21** [comment]
Yes go ahead and delete then if you need to make room.  We will have one more to add once we decide if we are having it but it's not until the end of July and I guess we'll know for sure in the next week or so.

**Comment by meshanw** [comment]
@Toddsand21 Please review http://2017onrr/events.htm

**Comment by meshanw** [comment]
@Toddsand21 please review http://2017onrr/events.htm

**Comment by Toddsand21** [comment]
It looks fine and ready to post.  Thanks!

**Comment by meshanw** [comment]
Pushed to live site
