### ISSUE TITLE
Create redirect for FOGRMA doc

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#803]
Someone reached out to Lori saying they have broken links.  We replaced the doc with an external ink.

**Comment by mcharg** [comment]
Updated in dev.

http://2017onrr/Laws_R_D/PubLaws/PDFDocs/97-451.pdf 
redirects to 
https://uscode.house.gov/view.xhtml?path=/prelim@title30/chapter29&edition=prelim

@meshanw Can you please test it out and make sure it looks good to post to the live site?

**Comment by mcharg** [comment]
I forgot @meshanw said she was out the rest of the week.  @CM805 Can you please review?

**Comment by CM805** [comment]
@mcharg I confirmed the link is working.  I also tried it from here and it is good: http://2017onrr/Laws_R_D/PubLaws/

Also, I don't see an issue with the link on the live site: https://www.onrr.gov/Laws_R_D/PubLaws/index.htm

**Comment by mcharg** [comment]
Pushed live.
