### ISSUE TITLE
Update Content Audit Sheet

### ISSUE THREAD

**Issue by CM805** [ONRR/onrr.gov-site#805]
New issue, based on working #782 

Update the Content Audit worksheet on the [Accessibility Tracking](https://doimspp-my.sharepoint.com/:x:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B928732e3-ba62-4e42-8d4d-a815c2802c66%7D&action=edit&wdSkeletonState=%7B%22IsEnabled%22%3Atrue%2C%22Options%22%3A1088%7D&wdenableroaming=1&wdodb=1&wdorigin=Other&wdredirectionreason=Force_SingleStepBoot&wdinitialsession=b59f1b9a-abed-4dc2-bc46-3529af7a1d71&wdrldsc=2&wdrldc=1&wdrldr=ContinueInExcel) document to include Program Manager and Document Updater.

- [x]  Use formulas to bring in known information from from the Accessibility Tracking worksheet and from [Reference Docs](https://doimspp-my.sharepoint.com/:x:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B928732e3-ba62-4e42-8d4d-a815c2802c66%7D&action=edit&wdSkeletonState=%7B%22IsEnabled%22%3Atrue%2C%22Options%22%3A1088%7D&wdenableroaming=1&wdodb=1&wdorigin=Other&wdredirectionreason=Force_SingleStepBoot&wdinitialsession=b59f1b9a-abed-4dc2-bc46-3529af7a1d71&wdrldsc=2&wdrldc=1&wdrldr=ContinueInExcel)

- [x] Instead of having Accessibility Tracking as the source for the Program Manager, make the Content Audit the source.  Add formula to Accessibility Tracking for this.

**Comment by CM805** [comment]
@mcharg I got all the formulas in to bring in the data.  When I put the formula into the Accessibility Tracking sheet, there are several blanks...which means we have documents on Accessibility Tracking that we do not have on the Content Audit sheet.

I also added conditional formatting to the Accessibility Tacking current status.

@Baymatt is going to try to figure out how to do conditional formatting based on the value in another cell.

**Comment by mcharg** [comment]
@CM805 The ones we have on the accessibility tracking sheet that aren't in the content audit are likely ones we've replaced with links to external sites or pdfs that are now xls, so the links no longer match.

**Comment by Baymatt** [comment]
Sent the updated spreadsheet to @CM805, but here are the rules that I created for reference. Message/tag me if the functionality is not what is expected. 

<img width="710" alt="Screen Shot 2021-07-01 at 2 12 39 PM" src="https://user-images.githubusercontent.com/43329595/124191107-25339400-da78-11eb-80c6-e3a052682df0.png">

**Comment by CM805** [comment]
Done.  Thanks for the help @Baymatt 
Created #806 to get Content Audit sheet up to date.
