### ISSUE TITLE
Add missing files to Content Audit sheet

### ISSUE THREAD

**Issue by CM805** [ONRR/onrr.gov-site#806]
Some files are on the Accessibility Tracking worksheet and not the Content Audit worksheet.  These can be identified in column N as N/A.  They need to be added to the Content Audit worksheet and have all metadata populated.

**Comment by mcharg** [comment]
@CM805 We don't need to add any that have been removed from the site or are replaced with a different file format (like pdf turned into xls).

**Comment by mcharg** [comment]
@CM805 I probably messed up your formula here.  A bunch of RV files were reassigned to RRM and then to other teams and I didn't want to updated them in multiple places, so I updated them in the accessibility tracking sheet, but not the content audit.
