### ISSUE TITLE
June Analytics

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#808]

**Comment by mcharg** [comment]
Instructions for onrr.gov analytics:
https://github.com/ONRR/onrr.gov-site/wiki/Analytics-Templates-&-Instructions

**Comment by daniel-coleman-1** [comment]
Completed, my only comment is that outbound links dropped significantly this month.
![Screenshot 2021-07-22 085403](https://user-images.githubusercontent.com/83892362/126660441-e04b84de-6958-473a-957d-9963c62083ba.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 You date range may have gotten set back to the default.  This is what I'm getting for the month.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/d0cfc6bd-a9f5-4807-9995-67502dccb4b9)

**Comment by daniel-coleman-1** [comment]
@mcharg you were right, I had the date range wrong.  Nice catch! Corrected.

**Comment by mcharg** [comment]
Looks good.
