### ISSUE TITLE
FRNotices page updates

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#81]
Attached is the published FRN for -  30 CFR Part 1243, Suspensions Pending Appeal and Bonding

Please make updates to the following web pages, as follows:

https://www.onrr.gov/Laws_R_D/FRNotices/ICR0122.htm [https://www.onrr.gov/Laws_R_D/FRNotices/ICR0122.htm]

  Under sub-heading Federal Register Publications and above the last posting, add"60-Day Agency Information Collection [https://www.onrr.gov/Laws_R_D/FRNotices/PDFDocs/60034.pdf] - (85 FR 16954--March 25, 2020) - hyperlink "Agency Information Collection" with PDF attachment.

__________________________

https://www.onrr.gov/Laws_R_D/FRNotices/index.htm [http://www.onrr.gov/Laws_R_D/FRNotices/index.htm]

    Under heading "FR Notices 2020," place the attached FRN above the most recent FRN, as follows:
On the Left side, type "Mar 25" following the same font size and format as the last posted notice of "7 Feb."

Then, add the below statement following the same format as the other posted FRNs.

FR 16954
Wednesday, March 25, 2020
Denver, CO In accordance with the Paperwork Reduction Act of 1995, the Office of Natural Resources Revenue is proposing to renew an information collection request. OMB Control Number 1012-0006. [https://www.onrr.gov/Laws_R_D/FRNotices/ICR0136.htm] -- [Hyperlink "OMB Control Number 1012-0006" to the following web page:  https://www.onrr.gov/Laws_R_D/FRNotices/ICR0122.htm [https://www.onrr.gov/Laws_R_D/FRNotices/ICR0122.htm]

At the end of the above statement, add "View FR 16954 document." - Attach and hyperlink PDF document.
[16954.pdf](https://github.com/ONRR/onrr.gov-site/files/4404392/16954.pdf)

**Comment by Maroyafaied** [comment]
http://2017onrr/Laws_R_D/FRNotices/ICR0122.htm

**Comment by jennmalcolm** [comment]
@Maroyafaied did you see that the requester approved to push to production by email?

**Comment by Maroyafaied** [comment]
@jennmalcolm i just saw it, pushing it now.  I'll close the issue when it shows on the live site soon.

**Comment by jennmalcolm** [comment]
I confirmed the changes are live. Thanks @Maroyafaied
