### ISSUE TITLE
July Indian Index Zone prices

### ISSUE THREAD

**Issue by penvosej** [ONRR/onrr.gov-site#810]
The prices for the 6 Indian Index Zones have been calculated for July and are ready to be posted to ONRR.gov.  You can find the prices that need to be posted in the shared OneDrive Excel document titled "Data for ONRR.gov".

@sudarr
@schulted

**Comment by Maroyafaied** [comment]
@penvosej please review http://2017onrr/valuation/allzones.htm

**Comment by penvosej** [comment]
Hi Maroya!

The data on the webpage looks good. Thanks for taking care of that for us!!

Jessica

From: Maroyafaied ***@***.***>
Sent: Wednesday, July 7, 2021 8:45 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] July Indian Index Zone prices (#810)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpenvosej&data=04%7C01%7Cjessica.penvose%40onrr.gov%7Ce2012d2e8b4a4449092d08d94155de45%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637612659327212786%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3Og3HaXyQrKAeyljXGvptHZFuiiB0FIjd0J4DtMBAhs%3D&reserved=0> please review http://2017onrr/valuation/allzones.htm

-

**Comment by Maroyafaied** [comment]
This is live.
