### ISSUE TITLE
Webpage update - Active Agreements

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#814]
Please update the following webpage -
http://www.onrr.gov/ReportPay/CrossRef.htm

Active Agreement - sorted by State and Agreement name with the attached PDF file. Also change updated to read updated 07/01/2021.

Thank you
[Active Agreements sorted by Agreement Name.xlsx](https://github.com/ONRR/onrr.gov-site/files/6779118/Active.Agreements.sorted.by.Agreement.Name.xlsx)

**Comment by Maroyafaied** [comment]
@meshanw this doc is accessible.

**Comment by meshanw** [comment]
@merrellc Please review http://2017onrr/reportpay/CrossRef.htm

**Comment by merrellc** [comment]
Review completed.


Thank you
​Candace Merrell
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________
From: meshanw ***@***.***>
Sent: Wednesday, July 7, 2021 3:46 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Webpage update - Active Agreements (#814)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@merrellc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmerrellc&data=04%7C01%7Ccandace.merrell%40onrr.gov%7Cc470f1f69165474aa25408d94190c573%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637612912307920520%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2LgVK2heaVWiSICfk7Cqe3MeWEDKqANC2OEt61XtjMA%3D&reserved=0> Please review http://2017onrr/reportpay/CrossRef.htm

**Comment by meshanw** [comment]
Changes pushed to live site.
