### ISSUE TITLE
Webpage Update - 100% Fed Agrmt

### ISSUE THREAD

**Issue by merrellc** [ONRR/onrr.gov-site#818]
Please update the following webpage http://www.onrr.gov/ReportPay/royalty-reporting.htm with the attached PDF file.

100% Federal Agreements with the Same Royalty Rate & Royalty Distributions  Also change updated to read 07/01/2021.

Thank you
[100pct fed agreements.xlsx](https://github.com/ONRR/onrr.gov-site/files/6802977/100pct.fed.agreements.xlsx)

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 this doc is accessible , please update in dev and post live after review is approved. Thanks

**Comment by merrellc** [comment]
Approved. Thanks


Thank you
​Candace Merrell
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________
From: Maroyafaied ***@***.***>
Sent: Monday, July 12, 2021 10:48 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Webpage Update - 100% Fed Agrmt (#818)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@daniel-coleman-1<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdaniel-coleman-1&data=04%7C01%7Ccandace.merrell%40onrr.gov%7Cea266edfe8574f1d03bd08d94554dc4e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637617053053001817%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=loH3rjMi8HddcqS5nD9S3ZFkj9q5HYLP6wl%2BHT5L59Q%3D&reserved=0> this doc is accessible , please update in dev and post live after review is approved. Thanks

**Comment by Maroyafaied** [comment]
@merrellc I don't think @daniel-coleman-1 has made the changes in the dev site. @daniel-coleman-1 can you please update the doc in dev and send @merrellc the link to review? Thanks

**Comment by daniel-coleman-1** [comment]
@merrellc changes are implemented in dev here:
http://2017onrr/reportpay/royalty-reporting.htm

with your approval I will push changes live.

**Comment by merrellc** [comment]
Approve.


Thank you
​Candace Merrell
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resources Revenue
303-231-3517
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

________________________________
From: daniel-coleman-1 ***@***.***>
Sent: Tuesday, July 13, 2021 11:05 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Merrell, Candace J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Webpage Update - 100% Fed Agrmt (#818)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@merrellc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmerrellc&data=04%7C01%7Ccandace.merrell%40onrr.gov%7C85459a1bc770489c134308d946207fdc%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637617927679865335%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GuKpWm6B0tj%2FNjWOZBv4AqOcjnDwy1aRTsjI6F%2BZIj0%3D&reserved=0> changes are implemented in dev here:
http://2017onrr/reportpay/royalty-reporting.htm

with your approval I will push changes live.

**Comment by daniel-coleman-1** [comment]
@merrellc @Maroyafaied 
We are live!
