### ISSUE TITLE
Remove Docs (3) & Run accessibility report (1)  for Heidi in Phase 3

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#819]
Please remove the 3 docs identified in the excel sheet to be removed and run accessibility report for the doc they identified as to be corrected and send to evelyn.shropshire@onrr.gov

https://doimspp-my.sharepoint.com/:x:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7BA2233ADB-0155-46B9-8C98-6B719CC3C7FD%7D&file=Phase%203%20-%20Heidi%20Badaracco.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1&ct=1626190833194&wdOrigin=OFFICECOM-WEB.START.OTHER&cid=0cb48b52-a109-4680-b102-18ecc3bf7796

**Comment by mcharg** [comment]
Docs to be removed:
https://www.onrr.gov/IndianServices/pdfdocs/so3215.pdf
https://www.onrr.gov/IndianServices/pdfdocs/SO-3317-Tribal-Consultation-Policy.pdf
https://www.onrr.gov/IndianServices/pdfdocs/EXOrder_13175.pdf

Doc to run accessibility report:
https://www.onrr.gov/IndianServices/pdfdocs/ONRR-Tribal-Consultation-Policy.pdf

**Comment by mcharg** [comment]
Accessibility report and link to dev sent to Evelyn.

**Comment by mcharg** [comment]
Approved via email and pushed live.
