### ISSUE TITLE
Collection: Pricing

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#821]
When adding pricing as a collection in the CMS , we should base it off of this excel sheet the pricing team updates monthly for updates on the webpage. 

https://doimspp-my.sharepoint.com/:x:/r/personal/sudarr_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B610913F6-CC44-4222-8521-FAD9EA5FEB0E%7D&file=Data%20for%20ONRR.gov.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1&ct=1626180224678&wdOrigin=OFFICECOM-WEB.START.OTHER&cid=f008b02c-3d96-4619-b739-fb1bfa345f1a

**Comment by Maroyafaied** [comment]
@mojobnichols @jlouis-onrr I created folders with the test files that MSA send for each pricing collection. Here they are

[Indian Gas Index Zone](https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Collections/Indian%20Gas%20Index%20Zone?csf=1&web=1&e=DLWRBR)
[Indian Gas Major Portion](https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Collections/Indian%20Gas%20Major%20Portion%20Prices?csf=1&web=1&e=iwrfHc)
[Indian Oil Major Portion ](https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Collections/Indian%20Oil%20Major%20Portion%20Prices?csf=1&web=1&e=9zkmaB)

**Comment by jlouis-onrr** [comment]
@Maroyafaied, what is the frequency in which the Indian Gas Index Zone gets updated or will be uploaded?

**Comment by Maroyafaied** [comment]
@jlouis-onrr  The Indian Gas Index Zone gets updated on a monthly basis.

**Comment by jlouis-onrr** [comment]
@Maroyafaied, Indian Gas Index Zone collection is now in dev.

**Comment by jlouis-onrr** [comment]
@mcharg, is there meaning behind the $-- vs -- in the prototype, https://qmcq5k.axshare.com/#id=l9inb4&p=valuation___pricing ? or should the blank fields be like the current site, $-- or just --

**Comment by Maroyafaied** [comment]
@jlouis-onrr Awesome! It looks great, I will review more in depth tomorrow and send it to the MSA team for their review as well.

**Comment by mcharg** [comment]
@jlouis-onrr It doesn't matter much to me how we show the blank values as long as we're consistent across all the pricing collections.

**Comment by mcharg** [comment]
@Maroyafaied Do you know what the asterisk is for in the Central Rocky Mountains name? I think it's in the spreadsheet, but isn't reflected anywhere on the current site. We should either drop it or add a footnote to go with it.
![image](https://user-images.githubusercontent.com/38465926/158812332-1e54b7ff-7ab1-4de0-b4c1-481a2b0f253d.png)

**Comment by Maroyafaied** [comment]
@mcharg @jlouis-onrr I will find time to call Robert today and ask him about the asterisk and how they want the blank values to show.Thanks

**Comment by jlouis-onrr** [comment]
@Maroyafaied, @mcharg IBMP pricing collection is out in dev now

**Comment by mcharg** [comment]
@jlouis-onrr IBMP looks good.

**Comment by Maroyafaied** [comment]
@jlouis-onrr @mcharg Robert would like to remove the asterisk in the Indian Gas Index Zone, is it best to remove it in the shared spreadsheet.  I send the IBMP for review and asked about displaying blank prices as "--".

**Comment by jlouis-onrr** [comment]
@Maroyafaied, the asterisk in the Indian Gas Index Zone has been removed and reinserted into db.  Also, the pricing collection filters updates are now out in dev.

**Comment by Maroyafaied** [comment]
@jlouis-onrr everything looks great, I removed the asterisk from the shared spreadsheet but looks like you already handled that. I'll keep this issue open until MSA reviews and gives feedback. Thanks
