### ISSUE TITLE
About ONRR Page CMS - add content , children links and upload files. 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#822]

**Comment by mcharg** [comment]
About ONRR page is in:
https://dev-onrr-frontend.app.cloud.gov/about-onrr

**Comment by mcharg** [comment]
@Maroyafaied @daniel-coleman-1 The FOIA and Anti-harassment program pages would be good ones for you to start with.  They don't have tabs, so should be doable with the components we have now.

All documents that are uploaded to link to should go in the About folder I created and if they aren't already accessible, I'm tagging them with an Accessibility Errors tag, so we know to fix them before we go live.

FOIA:
Page in CMS: https://dev-onrr-cms.app.cloud.gov/admin/collections/pages/31
Page preview: https://dev-onrr-frontend.app.cloud.gov/about-onrr/foia (you may have to go to the homepage and navigate through the menu to not get the 404 page)
Wireframe: https://qmcq5k.axshare.com/#id=7ctmer&p=freedom_of_information_act__foia_
Live page (needed for links that aren't specified in the wireframe): https://www.onrr.gov/foia/index.htm

Anti-harassment program:
Page in CMS: https://dev-onrr-cms.app.cloud.gov/admin/collections/pages/32
Page preview: https://dev-onrr-frontend.app.cloud.gov/about-onrr/anti-harassment (you may have to go to the homepage and navigate through the menu to not get the 404 page)
Wireframe: https://qmcq5k.axshare.com/#id=l88jo0&p=anti-harassment_program
Live page (needed for links that aren't specified in the wireframe): https://www.onrr.gov/about/anti-harassment.htm

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 will do FOIA and @Maroyafaied will do Anti-harassments.

**Comment by mcharg** [comment]
Link format for files.

You should be able to grab the file id from the url when viewing it under assets.

If you want to download it you can add the download param, like:
<a href="https://your-directus.com/assets/<file-id>?download" target="_blank" download="Your File.pdf">Download</a>

So for this file: https://dev-onrr-cms.app.cloud.gov/admin/files/28df066e-f610-48f4-a3e8-605b202148b2

It would be:
https://dev-onrr-cms.app.cloud.gov/assets/28df066e-f610-48f4-a3e8-605b202148b2

**Comment by mcharg** [comment]
Add the file number to the Content Audit sheet in the Accessibility Tracking spreadsheet.

**Comment by Maroyafaied** [comment]
@mcharg @daniel-coleman-1 I added the anti-harassments page, for file links I did what Mojo suggested and uploaded all the files for that page in a folder I created (About > Anti-harassment) . I also updated the audit content with the CMS path for all the files. 

Please review https://dev-onrr-frontend.app.cloud.gov/

**Comment by mcharg** [comment]
@Maroyafaied Looks good.

**Comment by mcharg** [comment]
@Maroyafaied Should I put the ones from the About ONRR Home page in a Home folder under About?

**Comment by Maroyafaied** [comment]
@mcharg Yes please do, I think doing it that way will help us be better organized long term.

**Comment by mcharg** [comment]
@Maroyafaied Done

**Comment by mcharg** [comment]
@Maroyafaied I just test out the links on the Anti-Harassment page and the Culture Transformation page doesn't appear to exist anymore. Can we just remove the link or do we need to try to find a replacement?
https://www.doi.gov/employees/culturetransformation

**Comment by Maroyafaied** [comment]
@mcharg I'm not finding a link that replaces it, I'll remove it from CMS and live site. Thanks
