### ISSUE TITLE
When adding a link to existing text, it doesn't pull that text into the link dialogue 

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#826]
Can we populate the text you have highlighted into the Display Text field?

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/ca07bf95-b270-4697-9597-37b9c7434213)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/b8e25318-a07f-4e90-ac9e-cbff53fc3482)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/442e19d5-e086-46c6-b45c-0b198fef92db)

**Comment by Maroyafaied** [comment]
closing this, falls under customized links.
