### ISSUE TITLE
Add way to link to documents

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#828]
I want to be able to find the document I uploaded to link to.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/d0c48f2b-645b-497a-919d-865d94136b99)

**Comment by mcharg** [comment]
@mojobnichols @jlouis-onrr Do you want some design help from one of the interns with this?

**Comment by Maroyafaied** [comment]
All files should be collections

**Comment by mcharg** [comment]
How would it work for stand-alone document links like the pricing maps to be in a collection?
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/b598f730-0992-4994-90ca-bffe0c50ecb7)

**Comment by mcharg** [comment]
And what about pages where we have a mix of things?  Would each list be a separate collection?
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/2b28d4ab-2cb7-452e-87e8-578ebca09cbf)

**Comment by mcharg** [comment]
Another example where cards have different numbers of links and some are docs and some are external links. ![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/90f2dadf-41b0-4e4e-a85a-61a509351f19)

**Comment by mcharg** [comment]
We've also got docs that live in multiple places and I don't want them to have to live in two collections.

**Comment by mcharg** [comment]
For example, the valuation example pdfs are on the page listing the examples and again on the example page.  Same with all the handbooks.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/8ad497fe-040c-4c03-9919-92b6f7003acb)

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/33a26e31-5a87-49d3-bb26-f02bcaceb407)

**Comment by mcharg** [comment]
There are also forms linked from many pages.

**Comment by mcharg** [comment]
And reporter letters.

**Comment by mcharg** [comment]
And we link to the GOMESA press releases on the homepage separate from the list of press releases.

**Comment by mcharg** [comment]
@mojobnichols See above comments for places where there might be problems using collections for all documents.
