### ISSUE TITLE
INDIAN HILLS POWWOW, OKLAHOMA CITY                                    (To be added to Event Calendar)

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#829]
July 23-24, 2021

71st ANNUAL INDIAN HILLS POWWOW, OKLAHOMA CITY

Event Information
Location: 8980 N Sooner Rd, Oklahoma City, OK 73151
Time: Friday 5:00 pm-8:00 pm; Saturday 1:00 pm-8:00 pm

Description: The ONRR Indian Outreach Office will have an Information booth at the powwow to discuss oil and gas issues with Indian mineral owners on their Indian trust properties. If owners should have specific questions or items to discuss they might bring their O&G statements or other documents with them to meet with an ONRR representative.
Other Information: For more information or directions, please contact the ONRR OKC Outreach office toll-free at (800) 354-7015. The ONNR Outreach Office hours are Mon- Fri from 7:30 am-5:00 pm.  

Event Contact
NAME: ONRR Outreach OKC Office
PHONE: Toll Free (800) 354-7015
EMAIL: onrroutreachokc@onrr.gov

**Comment by Maroyafaied** [comment]
@meshanw can you take this one?

**Comment by meshanw** [comment]
@Maroyafaied Sure.

**Comment by meshanw** [comment]
@Toddsand21 Please review http://2017onrr/events.htm

**Comment by Toddsand21** [comment]
Looks good but could you add **Email:** after our phone number and before our email.  

(Note: Some of our readers are like me and wouldn't notice it as an email address.  Thanks!)

**Comment by meshanw** [comment]
@Toddsand21 Added Email: to this and all other events. Please review http://2017onrr/events.htm

**Comment by Toddsand21** [comment]
Looks great and ready to post!  Thank you.

**Comment by meshanw** [comment]
Changes pushed to live site.
