### ISSUE TITLE
Review ONRR.gov Content Guide

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/onrr.gov-site#830]
[Content Guide](https://github.com/ONRR/onrr.gov-site/wiki/Content-guide)

@CM805 @mcharg @meshanw @Maroyafaied

**Comment by daniel-coleman-1** [comment]
![Screenshot 2021-07-14 185142](https://user-images.githubusercontent.com/83892362/125711008-91bfa1aa-3058-456d-9fb6-9c668bc109fc.jpg)

Text of Native American and legislation access

**Comment by daniel-coleman-1** [comment]
Gender use:

![Screenshot 2021-07-14 185341](https://user-images.githubusercontent.com/83892362/125711160-b61e2e6a-e0b2-443d-88d3-c68105559a5f.jpg)

![Screenshot 2021-07-14 185412](https://user-images.githubusercontent.com/83892362/125711163-28e14fe9-d0bc-4d8d-92e3-dded5e9cd70f.jpg)

**Comment by daniel-coleman-1** [comment]
Capitalization guidance for federal & tribal
![Screenshot 2021-07-14 185610](https://user-images.githubusercontent.com/83892362/125711296-a2d2c689-80dc-4e2f-9bdf-daec215ab4e0.jpg)

**Comment by mcharg** [comment]
@daniel-coleman-1 onrr.gov doesn't have a how it works section.
![image](https://user-images.githubusercontent.com/38465926/125800523-40d0c87b-6779-4a2d-8b5d-25639a6888a3.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 @Maroyafaied We've been using Indian instead of Native American on onrr.gov because it has less of a public audience and all of the regulations and such use Indian.  Do we want to continue to do that? When I talked with Amanda Garrison from the Indian team, she thought it made sense to use Native American on NRRD and Indian on onrr.gov.

**Comment by mcharg** [comment]
@daniel-coleman-1 onrr.gov doesn't currently use markdown.
![image](https://user-images.githubusercontent.com/38465926/125801315-e5683703-0ed9-4ac8-8397-bafb86dde70b.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 Do we want to continue only title casing H1s?  Jennifer told me not to do it for onrr.gov because the current site doesn't.  We should check this against the DOI style guides.
![image](https://user-images.githubusercontent.com/38465926/125801450-29d657a4-545a-44b2-9b16-ad95d6b6798d.png)

**Comment by Maroyafaied** [comment]
@mcharg yes, we want to keep using Indian on onrr.gov. @daniel-coleman-1 as we spoke about during our check in, can you take out the Native American section from onrr.gov content guide and only include in the NRRD's content guide? Thanks

**Comment by mcharg** [comment]
@daniel-coleman-1 @Maroyafaied We're now referencing the Outer Continental Shelf instead of waters in some places to improve readability and understandability, so we should revisit this one.
![image](https://user-images.githubusercontent.com/38465926/125801894-832235b7-bda8-4bc0-a9ac-caf9c2422e84.png)

**Comment by mcharg** [comment]
Some of the specific words and phrases in here are NRRD specific and there are probably others to add for onrr.gov.

**Comment by mcharg** [comment]
@daniel-coleman-1 This won't apply to onrr.gov.  We'll have to add the ability to add glossaries to the CMS.  The Jekyll part can also be removed from the NRRD one.
![image](https://user-images.githubusercontent.com/38465926/125802128-a4fc90aa-9623-464f-a0e9-5c93793a508b.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 Should we link to ONRR or DOI style guides here?

**Comment by meshanw** [comment]
@Maroyafaied  @mcharg  @daniel-coleman-1 Will this content guide cover both onrr.gov and NRRD? Or will their be separate guides for each site?

**Comment by daniel-coleman-1** [comment]
@mcharg do you know if the DOI has a style guide?  I am not finding one.

**Comment by mcharg** [comment]
@daniel-coleman-1 I sent an email to DeRon, who runs the DOI Web Council, and copied you.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I'm not able to open onrr.gov's content style guide , this is what I see when I click on it in the wiki. 
![image](https://user-images.githubusercontent.com/40175688/126324334-988cd1bf-e7ee-47de-b738-df60dfde757d.png)

**Comment by mcharg** [comment]
@Maroyafaied The link in the right nav got broken (Daniel must have changed the page name). It should work now.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 @mcharg we say that we build our style guide based off 18F's, we should review their style guide as well to take ideas.  For example, I noticed they have guidance about plain language and using active voice and we don't have guidance about that and I know these principals are important to ONRR. I made an issue for plain language and active voice but it should be reviewed and compared to ours.  I also like how they have a section called "Inclusive Language" in which they mention Native American and other inclusive language we should consider. https://content-guide.18f.gov/our-style/

**Comment by daniel-coleman-1** [comment]
> @daniel-coleman-1 Do we want to continue only title casing H1s? Jennifer told me not to do it for onrr.gov because the current site doesn't. We should check this against the DOI style guides.
> ![image](https://user-images.githubusercontent.com/38465926/125801450-29d657a4-545a-44b2-9b16-ad95d6b6798d.png)

This is a really good point, I'm still thinking "Hmmmmmmmm..." about it.  Will compare to DOI style guide when we have it, thanks for sending that email.

**Comment by daniel-coleman-1** [comment]
@meshanw I'm going to create a separate issue for the NRRD content guide

**Comment by CM805** [comment]
Here is some food for thought.  I'm not making a suggestion or expressing a preference.  Just giving what I have found for the team's consideration.

A link to the ONRR Content Guide can be found here:  https://onrresource/Program-Areas/Communication---don-t-use/
         - Toward the end of this it stays that ONRR used the GPO style guide.  "Use the GPO style guide for all other grammar rules."
        - The ONRR style guide also addresses headers.

I wonder if the GPO Style Guide has any different guidance than the Chicago Manual of Style or the Conscious Style Guide.....found one:  CMS says to abbreviate United States as "US" and GPO says "U.S."

GPO Style Manual can be found here:  https://www.govinfo.gov/app/details/GPO-STYLEMANUAL-2016

The DOI Secretarial Correspondence Handbook can be found here:  https://www.doi.gov/elips/browse
       - Handbooks Section     -382 DM 5
        -  It does specifically say that in some instances guidance may be different than the GPO manual due to the Secretary's preference.
