### ISSUE TITLE
Adding an image asks for a size, can we make them responsive?

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#834]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/9f20b2d4-a93c-4e53-8785-af64e3d0fced)

**Comment by Maroyafaied** [comment]
@mcharg Review in editor JS once its in development website.

**Comment by mcharg** [comment]
@jlouis-onrr Is this fixed?
