### ISSUE TITLE
Reassign Phase 3 reporter letters from RRM

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#839]

**Comment by Maroyafaied** [comment]
- [ ] Amy Lunt
- [ ] Bob Kronebusch
- [ ] Christina Mathers
- [ ] Heidi Badaracco
- [ ] James Smith
- [ ] Jeff Carlson
- [ ] Karen Garza
- [ ] Ken Stamper
- [ ] Matt Collins
- [ ] Michael Marchetti
- [ ] Patty Damon
- [ ] Rhonda Baker
- [ ] Robert Winter
- [ ] Stacey Browne

**Comment by Maroyafaied** [comment]
@mcharg I made the excel sheets and send all the emails, can you please change the status from blank to sent on all of the above in the excel tracking sheet? Thanks

**Comment by mcharg** [comment]
@Maroyafaied Done
