### ISSUE TITLE
RRM 508 Phase 3 Extended

### ISSUE THREAD

**Issue by sghahn** [ONRR/onrr.gov-site#841]
@mcharg 
- [x] [Dear Reporter Letter - OGOR B, Form MMS-4054-B, Change to Product Disposition for Certain Gas Sales.pdf](https://github.com/ONRR/onrr.gov-site/files/6824655/Dear.Reporter.Letter.-.OGOR.B.Form.MMS-4054-B.Change.to.Product.Disposition.for.Certain.Gas.Sales.pdf)
- [x] [Reporter Letter for Oil & Gas re CRs.pdf](https://github.com/ONRR/onrr.gov-site/files/6824658/Reporter.Letter.for.Oil.Gas.re.CRs.pdf)
- [x] [20090421.pdf](https://github.com/ONRR/onrr.gov-site/files/6824659/20090421.pdf)
- [x] [20100804.pdf](https://github.com/ONRR/onrr.gov-site/files/6824660/20100804.pdf)
- [x] [880314.pdf](https://github.com/ONRR/onrr.gov-site/files/6824662/880314.pdf)
- [x] [910723.pdf](https://github.com/ONRR/onrr.gov-site/files/6824663/910723.pdf)
- [x] [910903.pdf](https://github.com/ONRR/onrr.gov-site/files/6824664/910903.pdf)
- [x] [12_24_15_Reporter_Letter.pdf](https://github.com/ONRR/onrr.gov-site/files/6824661/12_24_15_Reporter_Letter.pdf)
** I checked the weblink on this (12_24_15) document and it is no longer valid, but I manually passed it, because I'm not going to insert a correct link on a document that was date stamped and signed in 2015.

**Comment by mcharg** [comment]
@sghahn  Reporter Letter for Oil & Gas re CRs.pdf was on the list of FM.  I replaced the doc.  Should we leave it assigned to FM or is it RRM's?

**Comment by mcharg** [comment]
@Maroyafaied Thoughts on the links in 12_24_15_Reporter_Letter.pdf?  I could setup redirects, since they're all links to onrr.gov. The document was only downloaded 17 times in the year we looked at.

**Comment by mcharg** [comment]
@sghahn I'm assuming you want to keep this issue open until all the remaining docs are updated?

**Comment by sghahn** [comment]
@mcharg Yes, please keep this issue open, thank you.

**Comment by mcharg** [comment]
@sghahn Maroya said we can leave the links broken, since that's a separate issue from accessibility.  The last doc is updated.

**Comment by sghahn** [comment]
@mcharg I'm not sure what you are referencing with earlier comment on broken links, it's Monday, so I may be forgetting something?

**Comment by mcharg** [comment]
@sghahn The ones in this doc that you didn't want to fix, since it was signed. 12_24_15_Reporter_Letter.pdf

**Comment by sghahn** [comment]
@mcharg ooh, see it's Monday, the doc is accessible except for one link, cool :) and thank you.

**Comment by sghahn** [comment]
@mcharg 6 documents:

- [ ] [20100430.pdf](https://github.com/ONRR/onrr.gov-site/files/6857768/20100430.pdf)
- [ ] [20031201.pdf](https://github.com/ONRR/onrr.gov-site/files/6857769/20031201.pdf)
- [ ] [Geothermal-Report-06-19-2013.pdf](https://github.com/ONRR/onrr.gov-site/files/6857770/Geothermal-Report-06-19-2013.pdf)
- [ ] [20091106.pdf](https://github.com/ONRR/onrr.gov-site/files/6857771/20091106.pdf)
- [ ] [20100415.pdf](https://github.com/ONRR/onrr.gov-site/files/6857772/20100415.pdf)
- [ ] [Dear Reporter Letter - OGOR B, Form MMS-4054-B, Change to Product Disposition for Certain Gas Sales.pdf](https://github.com/ONRR/onrr.gov-site/files/6857773/Dear.Reporter.Letter.-.OGOR.B.Form.MMS-4054-B.Change.to.Product.Disposition.for.Certain.Gas.Sales.pdf)

**Comment by mcharg** [comment]
@sghahn Those 5 docs are all removed.

**Comment by sghahn** [comment]
@mcharg Here are 10 documents for upload.

- [ ] [881114a.pdf](https://github.com/ONRR/onrr.gov-site/files/6963804/881114a.pdf)
- [ ] [930712.pdf](https://github.com/ONRR/onrr.gov-site/files/6963806/930712.pdf)
- [ ] [990812.pdf](https://github.com/ONRR/onrr.gov-site/files/6963807/990812.pdf)
- [ ] [20010925.pdf](https://github.com/ONRR/onrr.gov-site/files/6963808/20010925.pdf)
- [ ] [20080820.pdf](https://github.com/ONRR/onrr.gov-site/files/6963809/20080820.pdf)
- [ ] [20080829a.pdf](https://github.com/ONRR/onrr.gov-site/files/6963810/20080829a.pdf)
- [ ] [20100428.pdf](https://github.com/ONRR/onrr.gov-site/files/6963811/20100428.pdf)
- [ ] [ASCII_File_Rent_Instructions.pdf](https://github.com/ONRR/onrr.gov-site/files/6963812/ASCII_File_Rent_Instructions.pdf)
- [ ] [Pacific_TIMS_Contacts.pdf](https://github.com/ONRR/onrr.gov-site/files/6963813/Pacific_TIMS_Contacts.pdf)
- [ ] [Reporter Letter for Solids re CRs.pdf](https://github.com/ONRR/onrr.gov-site/files/6963822/Reporter.Letter.for.Solids.re.CRs.pdf)

(Hahn)

**Comment by sghahn** [comment]
@mcharg 9 documents for upload:

- [ ] [880630.pdf](https://github.com/ONRR/onrr.gov-site/files/6963836/880630.pdf)
- [ ] [881114b.pdf](https://github.com/ONRR/onrr.gov-site/files/6963837/881114b.pdf)
- [ ] [890119.pdf](https://github.com/ONRR/onrr.gov-site/files/6963838/890119.pdf)
- [ ] [900615.pdf](https://github.com/ONRR/onrr.gov-site/files/6963839/900615.pdf)
- [ ] [910612.pdf](https://github.com/ONRR/onrr.gov-site/files/6963840/910612.pdf)
- [ ] [920917.pdf](https://github.com/ONRR/onrr.gov-site/files/6963841/920917.pdf)
- [ ] [930414.pdf](https://github.com/ONRR/onrr.gov-site/files/6963842/930414.pdf)
- [ ] [950209b.pdf](https://github.com/ONRR/onrr.gov-site/files/6963843/950209b.pdf)
- [ ] [20060523.pdf](https://github.com/ONRR/onrr.gov-site/files/6963844/20060523.pdf)

(Amariles)

**Comment by cthomasONRR** [comment]
18/19 files passed the accessibility check:
- [ ] 20060523.pdf failed accessibility check - has issues with tagged annotations.

**Comment by cthomasONRR** [comment]
@mcharg and @sghahn 

I got all the files updated in Dev (http://2017onrr/) except for:

- [ ] 20060523.pdf  - failed accessibility check - has issues with tagged annotations.
- [ ] Reporter Letter for Solids re CRs.pdf  - is a duplicate, not sure what to do with it.

Note Shannon M:
Pacific_TIMS_Contacts.pdf - I could not find it in the content audit tab of the accessibility tracking excel, but moved the updated file in Dev. All other documents are updated in the excel.

**Comment by mcharg** [comment]
@cthomasONRR The Reporter Letter for Solids re CRs.pdf one is in our list twice, so you can just mark both rows as accessible.  We have it assigned to Rob Winter, so you can change that to April Lockler.  I'll go into Rob's list and mark it as reassigned.

**Comment by sghahn** [comment]
@cthomasONRR @mcharg 

Corrected the following:
- [ ] [20060523.pdf](https://github.com/ONRR/onrr.gov-site/files/6968838/20060523.pdf)

Pacific_TIMS_Contacts.pdf was originally assigned to Heidi

**Comment by KerriGallant** [comment]
@mcharg @cthomasONRR 
2 documents to upload:

- [ ] 
[930818.pdf](https://github.com/ONRR/onrr.gov-site/files/7035001/930818.pdf)

- [ ] 
[920106.pdf](https://github.com/ONRR/onrr.gov-site/files/7035003/920106.pdf)

(Amariles)

**Comment by cthomasONRR** [comment]
@KerriGallant @mcharg 

Thanks for sending these 2 documents over. They are updated in dev and live sites. (Shannon- our accessibility tracking spreadsheet is also updated.)

**Comment by KerriGallant** [comment]
@mcharg @cthomasONRR 
2 documents to upload:

- [ ] [970916.pdf](https://github.com/ONRR/onrr.gov-site/files/7069820/970916.pdf)

- [ ] [20001006.pdf](https://github.com/ONRR/onrr.gov-site/files/7069821/20001006.pdf)

- [ ] [970916.pdf](https://github.com/ONRR/onrr.gov-site/files/7069825/970916.pdf)
[20001006.pdf](https://github.com/ONRR/onrr.gov-site/files/7069826/20001006.pdf)
[910314.pdf](https://github.com/ONRR/onrr.gov-site/files/7069827/910314.pdf)
[910314.pdf](https://github.com/ONRR/onrr.gov-site/files/7069822/910314.pdf)

**Comment by cthomasONRR** [comment]
@KerriGallant @mcharg 

Thanks for sending these 3 documents over. They are updated in dev and live sites. (Shannon- our accessibility tracking spreadsheet is also updated.)

**Comment by sghahn** [comment]
@mcharg @cthomasONRR 

14 files for upload:

- [ ] [920423.pdf](https://github.com/ONRR/onrr.gov-site/files/7078708/920423.pdf)
- [ ] [920618.pdf](https://github.com/ONRR/onrr.gov-site/files/7078709/920618.pdf)
- [ ] [921015a.pdf](https://github.com/ONRR/onrr.gov-site/files/7078710/921015a.pdf)
- [ ] [930513.pdf](https://github.com/ONRR/onrr.gov-site/files/7078711/930513.pdf)
- [ ] [940112.pdf](https://github.com/ONRR/onrr.gov-site/files/7078712/940112.pdf)
- [ ] [941017.pdf](https://github.com/ONRR/onrr.gov-site/files/7078713/941017.pdf)
- [ ] [951012.pdf](https://github.com/ONRR/onrr.gov-site/files/7078714/951012.pdf)
- [ ] [961223.pdf](https://github.com/ONRR/onrr.gov-site/files/7078715/961223.pdf)
- [ ] [970109.pdf](https://github.com/ONRR/onrr.gov-site/files/7078716/970109.pdf)
- [ ] [970117.pdf](https://github.com/ONRR/onrr.gov-site/files/7078717/970117.pdf)
- [ ] [970512.pdf](https://github.com/ONRR/onrr.gov-site/files/7078718/970512.pdf)
- [ ] [980323b.pdf](https://github.com/ONRR/onrr.gov-site/files/7078719/980323b.pdf)
- [ ] [20030219.pdf](https://github.com/ONRR/onrr.gov-site/files/7078720/20030219.pdf)
- [ ] [20111014.pdf](https://github.com/ONRR/onrr.gov-site/files/7078721/20111014.pdf)

(Hahn)

**Comment by sghahn** [comment]
@cthomasONRR @mcharg 

3 files for upload:

- [ ] [880316a.pdf](https://github.com/ONRR/onrr.gov-site/files/7078904/880316a.pdf)
- [ ] [980602.pdf](https://github.com/ONRR/onrr.gov-site/files/7078910/980602.pdf)
- [ ] [20080421.pdf](https://github.com/ONRR/onrr.gov-site/files/7078912/20080421.pdf)

(Hahn)

**Comment by cthomasONRR** [comment]
@sghahn the "980323b" PDF failed the accessibility check. Could you fix and resend this document? I will work on getting the others updated. Thanks!
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/6133e59a-4d72-457f-836a-c77301fa51c1)

**Comment by cthomasONRR** [comment]
@mcharg and @sghahn 
I have all these files EXCEPT for "980323b.pdf" updated in dev and live sites. (Shannon- our accessibility tracking spreadsheet is also updated.)

**Comment by sghahn** [comment]
@cthomasONRR @mcharg 

1 Corrected: file:
- [ ] [980323b.pdf](https://github.com/ONRR/onrr.gov-site/files/7079326/980323b.pdf)

3 new files for upload:
- [ ] [20000602.pdf](https://github.com/ONRR/onrr.gov-site/files/7079327/20000602.pdf)
- [ ] [4292s1.pdf](https://github.com/ONRR/onrr.gov-site/files/7079328/4292s1.pdf)
- [ ] [4293s1.pdf](https://github.com/ONRR/onrr.gov-site/files/7079329/4293s1.pdf)

**Comment by cthomasONRR** [comment]
@sghahn @mcharg 

Thanks for sending these 4 documents over. They are updated in dev and live sites. (Shannon M- our accessibility tracking spreadsheet is also updated.)

**Comment by sghahn** [comment]
Good morning @mcharg @cthomasONRR 

11 files:
- [ ] [880316b.pdf](https://github.com/ONRR/onrr.gov-site/files/7155547/880316b.pdf)
- [ ] [891127.pdf](https://github.com/ONRR/onrr.gov-site/files/7155548/891127.pdf)
- [ ] [911030.pdf](https://github.com/ONRR/onrr.gov-site/files/7155549/911030.pdf)
- [ ] [930115.pdf](https://github.com/ONRR/onrr.gov-site/files/7155550/930115.pdf)
- [ ] [940120.pdf](https://github.com/ONRR/onrr.gov-site/files/7155551/940120.pdf)
- [ ] [950209a.pdf](https://github.com/ONRR/onrr.gov-site/files/7155552/950209a.pdf)
- [ ] [961022.pdf](https://github.com/ONRR/onrr.gov-site/files/7155553/961022.pdf)
- [ ] [970812.pdf](https://github.com/ONRR/onrr.gov-site/files/7155554/970812.pdf)
- [ ] [971126b.pdf](https://github.com/ONRR/onrr.gov-site/files/7155555/971126b.pdf)
- [ ] [20110706.pdf](https://github.com/ONRR/onrr.gov-site/files/7155556/20110706.pdf)
(Doebbler)


- [ ] [881108.pdf](https://github.com/ONRR/onrr.gov-site/files/7155582/881108.pdf)
(Amariles)

**Comment by cthomasONRR** [comment]
@sghahn @mcharg 
Good morning! These 11 documents are updated in dev and live sites. (Shannon M- our accessibility tracking spreadsheet is also updated.)

**Comment by sghahn** [comment]
@mcharg @cthomasONRR 
Good morning, here are 3 documents:

- [ ] [920330.pdf](https://github.com/ONRR/onrr.gov-site/files/7186052/920330.pdf)
- [ ] [961104.pdf](https://github.com/ONRR/onrr.gov-site/files/7186059/961104.pdf)
- [ ] [20030117.pdf](https://github.com/ONRR/onrr.gov-site/files/7186068/20030117.pdf)

(Amariles)

We show that we have 18 remaining documents and these will be uploaded in a few hour (later today).

**Comment by cthomasONRR** [comment]
@mcharg @sghahn 
Good morning! These 3 documents are updated in dev and live sites. (Shannon M- our accessibility tracking spreadsheet is also updated.)

**Comment by sghahn** [comment]
@cthomasONRR @mcharg 
Here are 3 more:

- [ ] [921015b.pdf](https://github.com/ONRR/onrr.gov-site/files/7187545/921015b.pdf)
- [ ] [930512.pdf](https://github.com/ONRR/onrr.gov-site/files/7187546/930512.pdf)
- [ ] [20070420.pdf](https://github.com/ONRR/onrr.gov-site/files/7187547/20070420.pdf)

(Doebbler)

**Comment by cthomasONRR** [comment]
@mcharg @sghahn
These 3 documents are updated in dev and live sites. (Shannon M- our accessibility tracking spreadsheet is also updated.)

**Comment by sghahn** [comment]
@cthomasONRR @mcharg 
These last 15 should make RRM completed on Phase 3. Please confirm the RRM count/completion status.
(I have 20010313 compliant in case it comes back that we need to add it back to the site)

- [ ] [911216.pdf](https://github.com/ONRR/onrr.gov-site/files/7187744/911216.pdf)
- [ ] [911218.pdf](https://github.com/ONRR/onrr.gov-site/files/7187745/911218.pdf)
- [ ] [950717.pdf](https://github.com/ONRR/onrr.gov-site/files/7187746/950717.pdf)
- [ ] [970528.pdf](https://github.com/ONRR/onrr.gov-site/files/7187747/970528.pdf)
- [ ] [970701.pdf](https://github.com/ONRR/onrr.gov-site/files/7187748/970701.pdf)
- [ ] [980323a.pdf](https://github.com/ONRR/onrr.gov-site/files/7187749/980323a.pdf)
- [ ] [981124.pdf](https://github.com/ONRR/onrr.gov-site/files/7187750/981124.pdf)
- [ ] [20000803.pdf](https://github.com/ONRR/onrr.gov-site/files/7187751/20000803.pdf)
- [ ] [20000919.pdf](https://github.com/ONRR/onrr.gov-site/files/7187752/20000919.pdf)
- [ ] [20010921.pdf](https://github.com/ONRR/onrr.gov-site/files/7187753/20010921.pdf)
- [ ] [20050817.pdf](https://github.com/ONRR/onrr.gov-site/files/7187754/20050817.pdf)
- [ ] [20080902.pdf](https://github.com/ONRR/onrr.gov-site/files/7187755/20080902.pdf)
- [ ] [20090121.pdf](https://github.com/ONRR/onrr.gov-site/files/7187756/20090121.pdf)
- [ ] [20111122.pdf](https://github.com/ONRR/onrr.gov-site/files/7187757/20111122.pdf)
- [ ] [Geothermal-Report-06-18-2013.pdf](https://github.com/ONRR/onrr.gov-site/files/7187758/Geothermal-Report-06-18-2013.pdf)

(Heinen/Hahn)

**Comment by cthomasONRR** [comment]
@mcharg @sghahn
These 15 documents are updated in dev and live sites. (Shannon M- our accessibility tracking spreadsheet is also updated.)

There is one more document assigned to RRM: https://www.onrr.gov/ReportPay/PDFDocs/20060523.pdf
Shannon H- are you able to remediate this one as well? Thanks so much for all your help!!!!

**Comment by sghahn** [comment]
@mcharg @mcharg 

Here is
[20060523.pdf](https://github.com/ONRR/onrr.gov-site/files/7188034/20060523.pdf)

This should make is us current except possibly 20010313 , let you know more as soon as I learn more.

**Comment by cthomasONRR** [comment]
@mcharg @sghahn

AWESOME!!! THANK YOU SO MUCH!!!
As far as I can tell, all RRM documents are now 508-Compliant!!!

**Comment by sghahn** [comment]
@cthomasONRR 

Awesome, thank you everyone for your assistance, it's been great working with you all. 

If we can keep this ticket open until next week when I hope to know more about 20010313 that would be great.

**Comment by cthomasONRR** [comment]
@sghahn Sounds good!

**Comment by cthomasONRR** [comment]
@sghahn Dane has replied saying they would like 20010313.pdf remediated and back on the website. Could you help us get this document compliant?

**Comment by cthomasONRR** [comment]
@sghahn Here is the document in case you don't have it:

[20010313](https://app.zenhub.com/files/210892300/35a015d9-0918-4887-9b1b-359ad57230d0/download)

**Comment by sghahn** [comment]
@cthomasONRR @mcharg 

Good morning here is the document for the Western Audit team, please make sure that RRM is not shown as the "owner", we made this compliant as a courtesy for Dane Templin's team.

- [ ] [20010313.pdf](https://github.com/ONRR/onrr.gov-site/files/7236302/20010313.pdf)

We can now close this issue. Thank you again for all of your help.

**Comment by cthomasONRR** [comment]
@sghahn 

Good morning! I have the updated document on the dev and live sites.

Thank you SO MUCH for your help!!!! We really appreciate you!!!

I will close this issue now.
