### ISSUE TITLE
Add document card component

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#843]
Examples:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/deddff60-561c-41f0-8a0f-e2999e5008c1)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/c7ac5c31-da58-46ea-8e11-1e8eaf1d14e5)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/3f7cc519-f45b-4b7e-ae53-9598810695c5)
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/dbcc6a52-a3ed-4b65-b080-66356070c133)

**Comment by Maroyafaied** [comment]
@jlouis-onrr will start by installing storybook
