### ISSUE TITLE
Collection: Office Locations

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#844]
For formatting things like addresses.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/d44d7a99-3621-4281-ab36-3d94b0dd9dba)

**Comment by mcharg** [comment]
There's also weirdness where if I paste things in they're italic and I can't make the unitalic.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/ca65631d-2d45-484b-ad74-1add3249d66a)

**Comment by mcharg** [comment]
And sometimes if I paste, there's not the extra row, but I can't get it to do that other than pasting in.

**Comment by mcharg** [comment]
Heading levels aren't always working right.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/cdeedba4-3238-4527-a74e-bc939e2c9b07)

**Comment by Maroyafaied** [comment]
Create issue for Office collection, the rest of the issues should be fixed with page layout.

**Comment by mcharg** [comment]
I was able to hard code this.

**Comment by mcharg** [comment]
Spreadsheet for collection: https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Collections/Office%20Locations/OfficeLocationsCollection.xlsx?d=w99321b73b023412ea9c620d3c91ea7ae&csf=1&web=1&e=lDxznD

**Comment by mcharg** [comment]
We don't need a collection for this.
