### ISSUE TITLE
Component: Table (apply variations and styling)

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#852]

**Comment by mcharg** [comment]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/cbc1abdd-bae1-486b-b41d-2fcb8cabc1bd)

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/35aa3803-351f-4cc3-b8e2-1e427df46f8f)

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/fdeae82d-b46b-4f85-9e72-20573c103e6f)

**Comment by mcharg** [comment]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/f73c6b94-1e52-4c10-97ef-0e703aed1427)

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/31f3e01d-284f-4ca6-8053-122e27833f0c)

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/4809350c-ab07-47d3-83cf-b6cc44c005b2)

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/3c7b76e5-faca-4998-9517-725d3faacfa1)

**Comment by mcharg** [comment]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/139b3b33-10a7-489f-b9f6-b03008f30e81)

**Comment by mcharg** [comment]
Table Type 1: Standard table
Example: https://dev-onrr-frontend.app.cloud.gov/compliance-enforcement/compliance?tabs=compliance-authorities
![image](https://user-images.githubusercontent.com/38465926/167474595-ace39785-bfa4-43c7-a48f-1c37e70e8a57.png)
Styling:
![image](https://user-images.githubusercontent.com/38465926/167474689-f7e73dad-bdcf-443d-870c-1d5dd3907234.png)

**Comment by mcharg** [comment]
Table Type 2: Searchable Collection Table
Example: https://dev-onrr-frontend.app.cloud.gov/references/rulemakings
![image](https://user-images.githubusercontent.com/38465926/167475087-41d919d6-47a1-474d-a192-20c504aebc77.png)

Styling:
![image](https://user-images.githubusercontent.com/38465926/167475698-58bd34fe-f147-4a3a-93c0-53d5ce9b9b31.png)

**Comment by mcharg** [comment]
Table Type 3: Handbook TOC
Example: https://dev-onrr-frontend.app.cloud.gov/references/handbooks/minerals-revenue-reporter-handbook
![image](https://user-images.githubusercontent.com/38465926/167475901-9ef37083-b326-4402-b2ef-10b065cb979c.png)

Styling:
![image](https://user-images.githubusercontent.com/38465926/167475984-159cae71-1551-440a-bb86-c86f4138ec22.png)

**Comment by mcharg** [comment]
Table Type 4: Inline Pricing Table
Example: https://dev-onrr-frontend.app.cloud.gov/references/handbooks/indian-payor-handbook?tabs=chapter-3-indian-oil-valuation,31&panel=311-comparing-gross-proceeds-ibmp-prices
![image](https://user-images.githubusercontent.com/38465926/167476508-251269c7-cc4a-4daf-b266-4ec4c24edfa4.png)

Styling: Like standard table, but allows right aligning select columns.

**Comment by mcharg** [comment]
Table Type 5: Pricing Collection Table
Example: https://dev-onrr-frontend.app.cloud.gov/references/valuation?tabs=pricing,indian-gas-index-zone
![image](https://user-images.githubusercontent.com/38465926/167476814-b77789a2-9774-4090-81b3-f79bc65c7511.png)

Styling: Like Searchable Collection Table, but allows right aligning select columns.

**Comment by mcharg** [comment]
@jlouis-onrr I think we have 5 types of tables. See above for the types.

**Comment by mcharg** [comment]
@jlouis-onrr Can you make numerical values that aren't dollar amounts align right?
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/673cfce7-9d43-403a-b197-d27a887df880)
https://dev-onrr-frontend.app.cloud.gov/references/valuation/processed-gas-example

**Comment by mcharg** [comment]
@jlouis-onrr Not sure why this column is right aligning.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/5a3de2ee-57a4-407e-842d-8996a9e2b819)
https://dev-onrr-frontend.app.cloud.gov/references/handbooks/indian-payor-handbook?tabs=chapter-3-indian-oil-valuation,32&panel=333-example

**Comment by mcharg** [comment]
@jlouis-onrr The styling looks good.

**Comment by mcharg** [comment]
Would also be nice if percentages were right aligned.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/e4b2f92e-12c3-47be-aa40-55bb11fe160d)

**Comment by mcharg** [comment]
@Maroyafaied Should we close this issue and open a new one with the right alignment tweaks, so we can prioritize it separately for Jerome's remaining time?

**Comment by mcharg** [comment]
@jlouis-onrr Can you add a rule on the bottom row, so it doesn't look like it's floating when the last row is white?
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/1506dda0-51f4-4cbe-859f-2d21da3a1a56)

**Comment by Maroyafaied** [comment]
@mcharg Yes, that's fine. Just out of curiosity , are we now able to control the width of table columns?

**Comment by mcharg** [comment]
@Maroyafaied No we can't/

**Comment by mcharg** [comment]
Created #1940 for column alignment and #1941 for adding a rule to the bottom of the table.
