### ISSUE TITLE
Create spreadsheet for redirects from old site to new site

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#853]

**Comment by mcharg** [comment]
Also documents.

**Comment by mcharg** [comment]
Data intern can help by creating a spreadsheet mapping old urls to new urls.

**Comment by cvojslavek** [comment]
Added internal and external redirects to Redirects spreadsheet for 2,525 old urls. 

Opened "Add new site 301 redirects to Redirects spreadsheet#1145" to add the new site 301 redirects for internal redirects found.
