### ISSUE TITLE
Design event calendar

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#857]
I just have it as a tab on the reporter training page (https://qmcq5k.axshare.com/#id=cwcm9b&p=reporter_training) right now, but most of the events are actually for Tribal Consultation (https://www.onrr.gov/events.htm), so we need to rethink.

**Comment by Maroyafaied** [comment]
Event collection

**Comment by mcharg** [comment]
@jlouis-onrr @mojobnichols Would this be a good issue to put Chris on and have him work with the UX interns to iterate based on what comes out of the box?

**Comment by mcharg** [comment]
Lightbox design: https://dcpea5.axshare.com/#id=judyuy&p=events
Expanding design: https://ulfcy9.axshare.com/

**Comment by jkwonatx** [comment]
I made an update to the Expanding design above. I fixed the issue with expanding the third event box and unified the Sign Up call to action buttons to a single design: https://ulfcy9.axshare.com

**Comment by Maroyafaied** [comment]
Will close this one and make another issue for build.

**Comment by mcharg** [comment]
Created #1210 for building.
