### ISSUE TITLE
Strategy on how to get users to submit issues on Github

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#86]
We are still receiving requests through service now or directly to Jennifer's email, we need to come up with a strategy or content to use for users to start using github.

**Comment by lpgoldstein** [comment]
@Maroyafaied and @jennmalcolm we should just send them a nice email response that says "In order to have your request handled promptly, please submit through github and include the link to the wiki that shows how to set up an account and submit an issue.

**Comment by Maroyafaied** [comment]
@jennmalcolm @lpgoldstein  This is similar language to what I have been using. We could start by sending this to any requester sending emails or going through ServiceNow.  Feel free to make changes or suggest a different approach. 


"We have received your request to make changes/updates on onrr.gov.  We would like to let you know that the Data Display team is now in charge of onrr.gov and our team uses Github for requests which enables us to better track and handle requests promptly. 

We ask that you create an account with Github and submit issues through Github for any future requests on the site. For instruction on creating and submitting issues on Github, please visit our [wiki page](https://github.com/ONRR/onrr.gov-site/wiki/Using-github). 

If you have any questions regarding using Github, please feel free to contact the data display team at nrrd@onrr.gov."

**Comment by jennmalcolm** [comment]
I think this wording works. We should also decide if we need to try some other avenues to communicate the change to the organization? Maybe one of the weekly messages on onrresource or perhaps an email to all ONRR? We could also put a link in the footer of onrr.gov, which @Maroyafaied suggested.

**Comment by jennmalcolm** [comment]
Just with the wording, we should probably be consistent about our capitalization of Data Display.

**Comment by Maroyafaied** [comment]
@jennmalcolm I fixed the capitalization. I think a mass email to all ONRR is a good idea, I'm not sure if many people read the weekly messages.

**Comment by lpgoldstein** [comment]
@jennmalcolm @Maroyafaied I agree about the mass email, link and email response message.

**Comment by Maroyafaied** [comment]
I have send an email for Nathan to approve to send to all on ONRR.

**Comment by jennmalcolm** [comment]
I think this issue is done. We can create an issue to get the email out once Nathan approves.
