### ISSUE TITLE
Continue putting content for static pages in CMS

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#860]

**Comment by mcharg** [comment]
@meshanw Here's a list of pages to start.

- [ ] Federal Register Notices
Wireframe: https://qmcq5k.axshare.com/#id=kkqoxq&p=federal_register_notices
Current Page: https://www.onrr.gov/Laws_R_D/FRNotices/index.htm (very different from wireframe, but in case you need any links)
Page in CMS: https://dev-onrr-cms.app.cloud.gov/admin/collections/pages/45

- [ ] Unpaid Debt
Wireframe: https://qmcq5k.axshare.com/#id=xmti8p&p=unpaid_debt
Current Page: https://www.onrr.gov/compliance/treasury-referrals.htm
Page in CMS: https://dev-onrr-cms.app.cloud.gov/admin/collections/pages/39

Those are the only remaining pages without tabs or tables.

**Comment by meshanw** [comment]
@mcharg Please review

**Comment by mcharg** [comment]
@meshanw 

Upaid Debt

- Debt Collection Rule can link here: https://www.federalregister.gov/documents/2012/05/02/2012-10361/debt-collection-and-administrative-offset-for-monies-due-the-federal-government
- Debt Collection Act can link here: https://www.govinfo.gov/content/pkg/FR-1994-07-11/html/94-16632.htm
- Debt Collection Improvement Act can link here: https://fiscal.treasury.gov/dms/about/about-dcia.html
- References should be an H2 heading
- Create a new subfolder under Paying for Debt Collection and upload these two documents to link to after we get the better linking tool.
  - https://www.onrr.gov/reportpay/PDFDocs/Reporter-Letter-3-21-13.pdf
  - https://www.federalregister.gov/documents/2012/05/02/2012-10361/debt-collection-and-administrative-offset-for-monies-due-the-federal-government

**Comment by mcharg** [comment]
@meshanw 

Federal Register Notices

- Remove link to wireframe
- National Archives and Records Administration (NARA) Federal Register can link here: http://www.archives.gov/
- ONRR_RegulationsMailbox@onrr.gov can link to: mailto:ONRR_RegulationsMailbox@onrr.gov
- Rules & Regulations can link here: References/regulations/
- Information Collection Requests can link here: Regerences/icrs/
- Major Portion Prices and Due Date should be an H2 heading
- State Accounting and Audit Relief should be an H2 heading
- Once Christine starts, let's ask her for the links for the most recent publications and docket for past publications.

**Comment by meshanw** [comment]
@mcharg All listed changes have been made to FRN and Unpaid debt pages in CMS

**Comment by mcharg** [comment]
@meshanw 

Unpaid Debt
- Can you add the contact info to the bottom of the page, for now, since we don't have the ability to add a second column?
![image](https://user-images.githubusercontent.com/38465926/126656544-229b4882-63e4-42a6-9ed0-c8b8371e15b8.png)
- It looks like there's an extra line under the first paragraph that can be removed.
![image](https://user-images.githubusercontent.com/38465926/126656635-b9b0d728-9b76-4434-a41e-7263727ccfbf.png)
- There's a missing space before one of the links.
![image](https://user-images.githubusercontent.com/38465926/126656728-e4e13121-9e94-4965-926a-63ddbc03f310.png)

**Comment by mcharg** [comment]
@meshanw

FRNs
- There's text that's showing up twice.
![image](https://user-images.githubusercontent.com/38465926/126657011-f174a1ca-140d-479c-bd9e-22f19ce9da87.png)

- Remove extra lines.
![image](https://user-images.githubusercontent.com/38465926/126657078-6b3e7dbf-ed29-42c6-a22c-917569f4d16c.png)

**Comment by mcharg** [comment]
@cthomasONRR Can you help us find the links for "Most recent annual publication" and "Docket for past publications" for the FRNs page?

**Comment by cthomasONRR** [comment]
Major Portion most recent annual publication: https://www.federalregister.gov/documents/2021/04/07/2021-07092/major-portion-prices-and-due-date-for-additional-royalty-payments-on-gas-produced-from-indian-lands

Major Portion docket: https://www.regulations.gov/docket/ONRR-2011-0012

Marginal Properties most recent annual publication: https://www.federalregister.gov/documents/2020/12/11/2020-27267/states-decisions-on-participating-in-accounting-and-auditing-relief-for-federal-oil-and-gas-marginal

Marginal Properties docket: https://www.regulations.gov/docket/ONRR-2011-0002

**Comment by meshanw** [comment]
@mcharg On FRN page - extra lines removed and major portion links updated.
Unpaid debt page - contact added, space added, extra line referred to is included in wireframe (Should we remove in CMS?)

**Comment by mcharg** [comment]
@meshanw Looks good.

I added in the second set of links for Marginal Properties on the FRN page, so I think we're good to close this issue.
