### ISSUE TITLE
ONRR.gov Site Map Update Section 1.0 and 2.0

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/onrr.gov-site#861]

**Comment by daniel-coleman-1** [comment]
https://92ix0j.axshare.com/

**Comment by daniel-coleman-1** [comment]
Here is the menu option file I used:
https://qmcq5k.axshare.com/#id=e1wh3o&p=home_v3

And here is the site map file:
https://92ix0j.axshare.com/#id=6cfibl&p=7_0_about_onrr&g=1

I'd like access to that file to edit it, and to the menu options to update them as well.  Will bring up in the meeting.

Document:
[Site_Map_New.docx](https://github.com/ONRR/onrr.gov-site/files/6940288/Site_Map_New.docx)

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I believe @mcharg invited you to access the AxShare folder, can you check?

**Comment by mcharg** [comment]
@daniel-coleman-1 I sent you the Axure file via chat and gave you access to the AxShare folder to be able to publish changes to the same link.

**Comment by mcharg** [comment]
@daniel-coleman-1 The file is now also on Teams. https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/ONRR.gov/Design/Sitemap/sitemap_2021.rp

**Comment by daniel-coleman-1** [comment]
Here is my updated site map:

https://doimspp-my.sharepoint.com/:u:/g/personal/mchargs_mms_gov/ETT05UVj2-1KtJd1L6FA8kEBq-rtSMiVu0kmG88arkeVjg?e=fRxz4I

I kept everything from both versions, so I am assuming we will consolidate some menu options.

Do we want to change the order around at all?
@mcharg @Maroyafaied

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I'm not able to open the link, I get this message. 
![image](https://user-images.githubusercontent.com/40175688/128781686-7696098a-e034-48cc-9469-4a514304157d.png)

**Comment by daniel-coleman-1** [comment]
Ahh, ok, I understand how linking the pages works now.
https://92ix0j.axshare.com/

@Maroyafaied

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I'm not sure if I'm checking the correct folder but I'm checking the "After Redesign" folder, I looked a bit at the primary nav section and "7.0 About ONRR" section and I'm finding quite a few things not matching the wireframe. I added a few comments in axure. Can you schedule a meeting with @mcharg and I tomorrow to make sure we're all on the same page and I'm reviewing the correct folder. Thanks

**Comment by daniel-coleman-1** [comment]
@Maroyafaied sounds good, there may be extra to pare down.  I set us a meeting with @mcharg for 11:30 tomorrow morning.

**Comment by mcharg** [comment]
@daniel-coleman-1 You have to publish your Axure file to AxShare, like I showed you, to get a link where people can comment.

@Maroyafaied You're commenting on the last version I did in December.

**Comment by mcharg** [comment]
@daniel-coleman-1 The menus in the wireframes are pretty well vetted with stakeholders, so we don't want to change them unless we have a good reason to.

**Comment by daniel-coleman-1** [comment]
@Maroyafaied updated the document based on your notes

**Comment by daniel-coleman-1** [comment]
Wrapping up for the day, completed through the Reporting tab:

https://92ix0j.axshare.com/

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 Just to make sure what to review, did you work on getting started and all the subsections under it?

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 please specify which section you worked on and ready for review? I reviewed the Oil and Gas Production section that we discussed completing yesterday and it still needs updating? I also looked at the Getting Started section and there's some updates needed there too.

**Comment by mcharg** [comment]
@daniel-coleman-1 I don't think you published your latest changes.  The last file was uploaded to AxShare at 10:45 AM yesterday.

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/8702aee6-2be6-4b4f-8ca7-d3c24f0d602e)

**Comment by mcharg** [comment]
@daniel-coleman-1 I went through and commented on the Getting Started and Reporting sections and resolved comments that have been addressed.

**Comment by daniel-coleman-1** [comment]
@mcharg thanks for the comments, going through and making edits now.

**Comment by daniel-coleman-1** [comment]
@Maroyafaied I put in most of @mcharg 's edits, but I stripped the 2.1, 2.2, 2.3, and 2.4 pages of most of their content to keep the items on the pages for each tab.  I think it conveys the info more clearly, but I'm welcome welcome to feedback.  I still need to add in the lists of documents, but other than that the Reporting section is good to go.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I reviewed everything in reporting and put my comments, I also looked at the Getting Started but it seems like that section and sub sections hasn't been updated.

**Comment by mcharg** [comment]
@daniel-coleman-1 I reviewed the Reporting section again.  It's looking pretty good.  Most of my comments are numbering and box color coding.

**Comment by daniel-coleman-1** [comment]
@Maroyafaied @mcharg for your review:
https://92ix0j.axshare.com

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 sorry can you remind me which sections are ready for review?

**Comment by daniel-coleman-1** [comment]
@Maroyafaied Just 1.0 Getting Started for now

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 That section looks fine for me, let me know when other sections are ready for review. Thanks

**Comment by mcharg** [comment]
@daniel-coleman-1 I also reviewed 1.0 Getting Started.

**Comment by mcharg** [comment]
@daniel-coleman-1 Can we review the Reporting section to make sure all of the previous comments have been addressed?

**Comment by daniel-coleman-1** [comment]
@mcharg they haven't all been addressed yet, I'll let you know when it's ready

**Comment by mcharg** [comment]
@daniel-coleman-1 I took another pass through and there's just one outstanding comment on the solids handbook.

**Comment by daniel-coleman-1** [comment]
@mcharg resolved, thanks!

@Maroyafaied ready for your review.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 @mcharg Axure is not letting me comment for some reason, but it's looking great. I only had one question/comment in the pic below. I was curious if this needed it's own box since it's a link in the overview tab, it's probably done correctly but just wanted to make sure. 
![image](https://user-images.githubusercontent.com/40175688/131355013-8d036ba1-3656-4fd0-930d-b84248724cc9.png)

**Comment by mcharg** [comment]
@Maroyafaied It's at the bottom of both tabs.

**Comment by daniel-coleman-1** [comment]
@mcharg do you think it's good as is or should I bring it to below  both 1.4.1 and 1.4.2 to reflect it's in both tabs?

**Comment by mcharg** [comment]
@daniel-coleman-1 It's good as is.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 you can close this issue now.

**Comment by daniel-coleman-1** [comment]
Woooo!
