### ISSUE TITLE
Please update the Rules and Regulations web pages as indicated in the email.

### ISSUE THREAD

**Issue by luisaguilar-onrrgov** [ONRR/onrr.gov-site#87]
Please submit this to the appropriate IT Web Team for processing.

Attached is the published FRN for -  30 CFR part 1220, OCS Net Profit Share Payment

Please make updates to the following web pages, as follows:

https://www.onrr.gov/Laws_R_D/FRNotices/ICR0073.htm

Under sub-heading Federal Register Publications and above the last posting, add"60-Day Agency Information Collection - (85 FR 17362--March 27, 2020) - hyperlink "85 FR 17362--March 27, 2020" with PDF attachment.]

__________________________

https://www.onrr.gov/Laws_R_D/FRNotices/index.htm

Under heading "FR Notices 2020," place the attached FRN above the most recent FRN, as follows:
On the Left side, type "27 Mar" following the same font size and format as the last posted notice of "25 Mar."

Then, add the below statement following the same format as the other posted FRNs.

FR 17362
Friday, March 27, 2020
Denver, CO In accordance with the Paperwork Reduction Act of 1995, the Office of Natural Resources Revenue is proposing to renew an information collection request. OMB Control Number 1012-0009. -- [Hyperlink "OMB Control Number 1012-0009" to the following web page:  https://www.onrr.gov/Laws_R_D/FRNotices/ICR0073.htm 

At the end of the above statement, add "View FR 17362 document." - Attach and hyperlink PDF document.

[17362.pdf](https://github.com/ONRR/onrr.gov-site/files/4417390/17362.pdf)

Please contact me if you have any questions

**Comment by Maroyafaied** [comment]
@luisaguilar-onrrgov  thank you for submitting your issue on Github!

**Comment by Maroyafaied** [comment]
@luisaguilar-onrrgov please review the links on the staging website, if everything looks correct then please comment here and I'll make it live. Thanks!

http://2017onrr/Laws_R_D/FRNotices/ICR0073.htm
http://2017onrr/Laws_R_D/FRNotices/index.htm

**Comment by Maroyafaied** [comment]
@luisaguilar-onrrgov approved the changes and they are now on the live site.
