### ISSUE TITLE
Remove regulations docs (231)

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#870]

**Comment by mcharg** [comment]
Page: http://2017onrr/reportpay/roy-checklist.htm
- [ ] https://www.onrr.gov/ReportPay/PDFDocs/30_CFR_re_TIN.pdf

**Comment by mcharg** [comment]
Sent email to Matt seeing if he wants someone on his team to review the changes in dev or if he wants @cthomasONRR to review.

**Comment by cthomasONRR** [comment]
@mcharg 

First round review completed. I found the following issues:

http://2017onrr/Laws_R_D/FRNotices/ICR0107.htm - Has some spacing issues in the oldest bullet points.
http://2017onrr/Laws_R_D/FRNotices/ICR0104.htm - I think the "(Expires February 29, 2008)" can be removed.
http://2017onrr/Laws_R_D/FRNotices/ICR0061.htm – All 7 PDFs that should have been removed are still present
http://2017onrr/Laws_R_D/FRNotices/AC30.htm – The 1 PDF that should have been removed is still present

**Comment by cthomasONRR** [comment]
@mcharg 

I corrected the 4 issues above! I can move on to getting the archived files downloaded for Regs Team.

**Comment by cthomasONRR** [comment]
Got all 231 documents archived and saved onto the Regs Team's N-drive. I have folders for both Phase 2 and Phase 3 documents.

N:\CEVA\Regulations\MISC\508 Compliance - PDF backups from website

**Comment by mcharg** [comment]
Changes are now live.
