### ISSUE TITLE
Create site search (add code snippets from search.gov)

### ISSUE THREAD

**Issue by jlouis-onrr** [ONRR/onrr.gov-site#873]
@mojobnichols I set up a site for search.gov. I think we just need to add in this code somewhere.

Form Snippet
```
<!DOCTYPE html>
<html>
<head><title>page title</title></head>
<body>
  <form id="search_form" action="https://search.usa.gov/search" accept-charset="UTF-8" method="get">

    <input type="hidden" name="affiliate" id="affiliate" value="onrr.gov" autocomplete="off" />
    <label for="query">Enter Search Term(s):</label>
    <input type="text" name="query" id="query" autocomplete="off" class="usagov-search-autocomplete" />
    <input type="submit" name="commit" value="Search" data-disable-with="Search" />
  </form>
```

Type-ahead search and Search.gov Tag Snippet
```
<script>
//<![CDATA[
      var usasearch_config = { siteHandle:"onrr.gov" };

      var script = document.createElement("script");
      script.type = "text/javascript";
      script.src = "//search.usa.gov/javascripts/remote.loader.js";
      document.getElementsByTagName("head")[0].appendChild(script);

//]]>
</script>
</body>
</html>
```

**Comment by mcharg** [comment]
please see below links to the information we discussed during our call:
[Manage Your Site Configuration and Use of Features from the Admin Center](https://search.gov/admin-center/index.html)
[APIs for Search.gov Customers](https://search.gov/developer/)
[How to Index with Search.gov - Our indexer](https://search.gov/indexing/indexing-with-searchgov.html)

**Comment by cthomasONRR** [comment]
@mcharg emailed them with this: 

"Hello again,

One more question for you- We have the [search.gov](http://search.gov/) code in and search field seems to be working. We won’t get search results until we submit the site map to Bing, which we won’t do until we go live. Is there anything else we should be doing before we go live?

Thanks for all your patience!

Christine Thomas"

**Comment by mcharg** [comment]
@mojobnichols The styling updates look good and I still get to the search results page.  Will wait for response from search.gov before closing.
