### ISSUE TITLE
Phase 3 - Training videos

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#879]
The video production team will identify the content owner for each video. Our team will contact the content owner and ask if they want the video to be removed or corrected, if they chose for it to be correct then they have to submit a service ticket.

**Comment by Maroyafaied** [comment]
We've discussed with Bill that videos will be their own separate project as most of the videos will need to be re-done based on the website redesign. We send him the wireframes to get a head start of creating content for videos along with the new accessible ONRR logo.  @cthomasONRR @mcharg can one of you update the tracking spreadsheet to take videos out and create another with just videos. Thanks

**Comment by cthomasONRR** [comment]
@Maroyafaied Can we move the videos into a different tab within the same spreadsheet, or do you want a new spreadsheet?

**Comment by Maroyafaied** [comment]
@cthomasONRR That's fine.

**Comment by cthomasONRR** [comment]
OK I made I new 'Videos' tab on the existing accessibility tracking spreadsheet, moved all Bill's videos to that tab, and removed them from the 'Accessibility Tracking' tab. 

@mcharg could you review to make sure I didn't ruin anything?

**Comment by mcharg** [comment]
@cthomasONRR Looks good.  I took out a few columns we don't need.

**Comment by cthomasONRR** [comment]
@mcharg Awesome! Is there anything else we need to do for this issue?

**Comment by Maroyafaied** [comment]
We're good, thank you both.
