### ISSUE TITLE
Lease/Agreement Maintenance Contacts

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#880]
Please update the contact list at the below link with the attached list:

https://www.onrr.gov/reportpay/PDFDocs/RS_LeAgAssignments.pdf
[Lease Agreement Maintenance Contacts_7-22-21.pdf](https://github.com/ONRR/onrr.gov-site/files/6863971/Lease.Agreement.Maintenance.Contacts_7-22-21.pdf)

**Comment by meshanw** [comment]
@bowlenj please review http://2017onrr/reportpay/PDFDocs/LeaseAgreementMaintenanceContacts_7-22-21.pdf

**Comment by bowlenj** [comment]
Looks great, thank you!

Thank You,
Jessica Bowlen
Minerals Revenue Specialist - Staff
Reference, Royalty and Production
Reference and Reporting Management
Office of Natural Resource Revenue
303-231-3202
***@***.***

Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.

From: meshanw ***@***.***>
Sent: Friday, July 23, 2021 11:06 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Lease/Agreement Maintenance Contacts (#880)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf28794ce861f4e1f4b1008d94dfc2eb5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637626567775598051%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=aOh2EpA4iXK73mHoz82gg6GzCz0ILf7nzawGYzB4Q2c%3D&reserved=0> please review http://2017onrr/reportpay/PDFDocs/LeaseAgreementMaintenanceContacts_7-22-21.pdf

-

**Comment by meshanw** [comment]
Changes pushed to live site.

**Comment by mcharg** [comment]
@cthomasONRR Will rename this to the old file name:

https://www.onrr.gov/reportpay/PDFDocs/RS_LeAgAssignments.pdf

To fix broken links.

**Comment by cthomasONRR** [comment]
@mcharg Updated the document with the old file name and updated the file name in Atom for http://2017onrr/reportpay/royalty-reporting.htm

**Comment by mcharg** [comment]
@cthomasONRR Looks good to me in dev, so you can go ahead and push live.

**Comment by bowlenj** [comment]
That's the royalty page, we need it to take us to the contact sheet for lease agreement maintaince - http://2017onrr/about/contact.htm

Thank You,
Jessica Bowlen
Office of Natural Resource Revenue
Distribution and Disbursement Support Services
Team 1B
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Monday, August 9, 2021 9:52 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Lease/Agreement Maintenance Contacts (#880)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@mcharg<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmcharg&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf93c9e6028a54b79d7c508d95b4dbc2e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641211705441454%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uVp75mOdGQ21N1HZofbIcZmza1x%2FhGK1gTH2mV%2B0Fgo%3D&reserved=0> Updated the document with the old file name and updated the file name in Atom for http://2017onrr/reportpay/royalty-reporting.htm

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F880%23issuecomment-895337486&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf93c9e6028a54b79d7c508d95b4dbc2e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641211705451479%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GnHShZCBQ3dAWmntdc%2FTTzFYGEVV1KAoLWKC3V38CfI%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VHYWV67R6FUKCRGAKF3T372T5ANCNFSM5A2MX6QA&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf93c9e6028a54b79d7c508d95b4dbc2e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641211705451479%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AXJEE%2BOV6oC1v2qfNr7QtINVwp2G1QlNZzLfnFWvyCI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf93c9e6028a54b79d7c508d95b4dbc2e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641211705461358%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=W0riiNYt4QTVuV6FJkFOb6AcldqDAuL4CqrvMMq3AbM%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Cf93c9e6028a54b79d7c508d95b4dbc2e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641211705461358%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RAs9Je8W1osTqK%2FGp%2B5m4i3vTl0i1nhOT85fsX1xidY%3D&reserved=0>.

**Comment by bowlenj** [comment]
Thank you, that looks like it worked!

Thank You,
Jessica Bowlen
Office of Natural Resource Revenue
Distribution and Disbursement Support Services
Team 1B
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Monday, August 9, 2021 10:04 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Lease/Agreement Maintenance Contacts (#880)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowenJ<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FbowenJ&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C64dbd4300bf04172ba1108d95b4f89ad%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641219957621589%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=miYjjXqwjVDEsZGTqjIPKLtt4x02vShC9wAFHUl%2BaAw%3D&reserved=0>

It has been updated for all webpages (http://2017onrr/about/contact.htm)... sometimes you need to press ctrl+F5 to see the updates pushed through. We see it fixed on our end.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F880%23issuecomment-895346411&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C64dbd4300bf04172ba1108d95b4f89ad%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641219957621589%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VdIojDrLseDWUHrghYbGEf3XqCOXMzauXW6RKLlHGEA%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH5ECJF4M65JX45E5RLT374APANCNFSM5A2MX6QA&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C64dbd4300bf04172ba1108d95b4f89ad%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641219957631543%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EWBTjhx12b%2FJNjrGNdBsa%2F%2FI6FHzNZejMUbN%2Fri82LQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C64dbd4300bf04172ba1108d95b4f89ad%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641219957631543%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Oci%2B3efImm6nYZcXZyl0jDz%2FSm3R1nobq5WAMx842s0%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C64dbd4300bf04172ba1108d95b4f89ad%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641219957641501%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3c1M%2B%2B9LmNqf6EWmGhd6PE3lDnoNeTH%2Bt%2BaNTG%2BpWPc%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
Awesome! Glad I could help. I will close this project again.

**Comment by bowlenj** [comment]
Thank you, it looks great!

Thank You,
Jessica Bowlen
Office of Natural Resource Revenue
Distribution and Disbursement Support Services
Team 1B
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: mcharg ***@***.***>
Sent: Monday, August 9, 2021 9:54 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Lease/Agreement Maintenance Contacts (#880)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@cthomasONRR<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FcthomasONRR&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1ae38316802d4f83827808d95b4e049e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641212933635688%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=L0%2B2D83nIj5GQCFIwQJNRx2fqzf5DFGgr6Ihh1JSiYQ%3D&reserved=0> Looks good to me in dev, so you can go ahead and push live.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F880%23issuecomment-895339047&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1ae38316802d4f83827808d95b4e049e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641212933645644%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5XX7sbxCZGdTnH9rIBg1EOiitG6AD%2B%2BVv%2FMCWZL80ds%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH5AKE4DK2THXAN4VBLT3723ZANCNFSM5A2MX6QA&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1ae38316802d4f83827808d95b4e049e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641212933645644%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wIoUmjDZwV9ppnqxqnYAZPlvoDWUs3roWYqm0zl7RZI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1ae38316802d4f83827808d95b4e049e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641212933655599%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jzJkFt%2FjNIXXeHFKMWLbsveUhe76YETgT4DcRIDzojE%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7C1ae38316802d4f83827808d95b4e049e%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641212933655599%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ahDf2EN4iZjopleD8dBBh2MYsrRCd75ZxqlF8FbUhkM%3D&reserved=0>.
