### ISSUE TITLE
Update links to 4292 and 4293 Schedule 1 forms on solids page

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#882]
They currently link to the main forms.

**Comment by cthomasONRR** [comment]
I talked with Alexis on the Regs Team, and they are OK with removing form 4292 and 4293 from https://www.onrr.gov/Laws_R_D/FRNotices/ICR0074.htm. This ICR 1010-0074 is a discontinued ICR. The forms 4292 and 4293 are updated and part of current ICR 1012-0010 (https://www.onrr.gov/Laws_R_D/FRNotices/ICR0120.htm).

**Comment by mcharg** [comment]
@sghahn The Solids page now links to the Schedule 1 docs in dev. Let me know if they look good to push to the live site.
http://2017onrr/reportpay/solids.htm

**Comment by sghahn** [comment]
@mcharg the links are correct to push live. I have added the documents to the list to be made 508 compliant.

**Comment by mcharg** [comment]
@sghahn Pushed live.  Might be a bit before it shows up on the live site.
