### ISSUE TITLE
Add hyphen guidance to content guide

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/onrr.gov-site#884]

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 did you mean to close this issue? Was this already worked on? If so, can you add a comment and someone to review? Thanks

**Comment by daniel-coleman-1** [comment]
@Maroyafaied  I closed it since we are collaborating with the ONRR Web team for the style guide. I didn't want to dig into the most granular aspects like specific punctuation rules beforehand, especially because I'm not sure if setting a rule for hyphen use is necessary.
