### ISSUE TITLE
Design single page for ICRs

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#887]
Now that all the documents are gone, it can be a table.

**Comment by cthomasONRR** [comment]
I'm first developing a table in Word to capture all the information currently captured on the Discontinued ICRs webpage (https://www.onrr.gov/Laws_R_D/FRNotices/FRICRDisCont.htm)

The Word document is saved on Teams: 
NRRD Team - General - ONRR.gov - Design - Regulations
(https://teams.microsoft.com/l/file/D0C4DEEF-0D13-4A9D-A582-B411D5B4D48D?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FDesign%2FRegulations%2FDiscontinued%20ICRs%20Table.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

**Comment by cthomasONRR** [comment]
I completed the Word document. Waiting until @mcharg gets back to take next steps.

**Comment by mcharg** [comment]
@cthomasONRR This is a great start!  I'll mock up what it looks like in accordions similar to the ones we have for contacts.

**Comment by cthomasONRR** [comment]
@mcharg Great! Please let me know if I can help!

**Comment by mcharg** [comment]
Here's the mock up with the accordions: https://qmcq5k.axshare.com/#id=tqf3j1&p=information_collection_requests

**Comment by cthomasONRR** [comment]
@mcharg It looks good to me! I cross checked it with the Word doc.

**Comment by mcharg** [comment]
@Maroyafaied This is ready for you to review.
https://qmcq5k.axshare.com/#id=tqf3j1&p=information_collection_requests

**Comment by Maroyafaied** [comment]
@mcharg Looks good, the only difference I noticed is for this entry below (Aug,31,2004) , it says "Expired" on the site currently, so I'm not sure if want to include that word in the table. 
![image](https://user-images.githubusercontent.com/40175688/128938331-c89ad142-5534-46c2-b731-a8b7266f42a5.png)

**Comment by mcharg** [comment]
I'll defer to @cthomasONRR on that.  Does expired mean something different from discontinued?

**Comment by cthomasONRR** [comment]
@mcharg When ICRs get 'discontinued', it just means that we let them expire without any intention of renewing them. I think it's OK to be consistent and use the word 'discontinued' everywhere. Hope this is helpful!

**Comment by mcharg** [comment]
Great.  I'll go ahead and close this issue.
