### ISSUE TITLE
How Valuation Works visual design

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#889]
https://qmcq5k.axshare.com/#id=l9inb4&p=valuation___pricing&g=14

**Comment by cthomasONRR** [comment]
I reviewed over chat. Here are my comments:

I like the grey boxes around the items that were previously 'floating'. In my view, the arrows you had in the 'calculating oil royalties' and 'calculating gas royalties' are now missing... should those be added back in, or are they no longer needed now that the equations have been flipped? Also, should the top equation be flipped (MATH = Royalty Value) to be consistent with the two equations below it?

**Comment by mcharg** [comment]
@CM805 is researching whether we have the right boxes paired from the first diagram to the other diagrams.

**Comment by CM805** [comment]
I've been taking a look at this today, but I'd really like to wait and look at some hard copy documents that I have at home.

**Comment by CM805** [comment]
@mcharg can you make me a PDF of the page that I can mark up?  I tried to print to PDF from the preview link, but I can't get the formatting right.  Maybe you know of another method?

**Comment by mcharg** [comment]
@CM805 I was able to export it to an image.  Does that work?
![ValEquation](https://user-images.githubusercontent.com/38465926/130811502-6faa1f11-18d9-4601-9f72-d30bcb99e571.png)

**Comment by mcharg** [comment]
Pulling this into this sprint, since it's on a page that will show during the demo.

**Comment by mcharg** [comment]
@lpgoldstein I took your suggestion and built these in PPT.  Then exported to PNG.

RVPA
![RVPA.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/edfbafed-7cc7-4532-adad-15e9f3bd0e18)
RVLA
![RVLA.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/4dfd4c69-644e-4681-8fbe-5c0f5c6712ca)

This is what they look like in dev. Much cleaner than the Axure ones. (Note: I stuck them on the wrong page because the url issue prevents the valuation page from displaying. Also, there's a bug where images are cutting off on the sides.)
https://dev-onrr-frontend.app.cloud.gov/about/organization

@lpgoldstein @cthomasONRR Any feedback?

**Comment by mcharg** [comment]
I just realized I need to add brackets to the RVLA one.

**Comment by mcharg** [comment]
![RVLA.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/97653b7e-e2d4-4aaa-b39e-b4ce90947cca)

**Comment by cthomasONRR** [comment]
@mcharg Sorry it's been a while. I remember RRM and RV had very differing opinions on how to display these equations. Did they come to an agreement? I'm a bit confused why the royalty rate is being applied twice.

**Comment by mcharg** [comment]
@cthomasONRR What I have is the version they agreed on.

**Comment by cthomasONRR** [comment]
@mcharg OK thanks! If that's what they agreed on, let's not do any changes! haha

**Comment by mcharg** [comment]
@cthomasONRR Any feedback on the look and feel? The blue and yellow worked well for Gina and Megan.

**Comment by cthomasONRR** [comment]
@mcharg  If possible, I would maybe change the color of the RVLA box, so that it's different from volume, unit value, and allowances. Maybe a purple?

**Comment by mcharg** [comment]
I can do that.  I think we made it thicker because Gina and Megan couldn't differentiate any other colors, but wouldn't hurt to make it thicker and another color.

**Comment by mcharg** [comment]
@cthomasONRR Better?
![RVLA](https://user-images.githubusercontent.com/38465926/145106074-5ba85229-9c42-48e0-be67-4897ebb1cf78.png)

**Comment by cthomasONRR** [comment]
@mcharg Yes! I like that this makes the final RVLA value stand out.

**Comment by mcharg** [comment]
Now in the wireframes.  @Maroyafaied This is ready for you to review.
https://qmcq5k.axshare.com/#id=l9inb4&p=valuation___pricing

**Comment by Maroyafaied** [comment]
@mcharg Since volume, unit value and allowance are all given the same square shape, should we differentiate them by different colors ? Just a thought, otherwise looks good.

**Comment by mcharg** [comment]
@Maroyafaied When I reviewed with Megan and Gina, they wanted fewer colors because they were having difficulty trying to differentiate when I had more.

**Comment by Maroyafaied** [comment]
@mcharg sounds good, glad you got that feedback from them.
