### ISSUE TITLE
Create a style tile for onrr.gov

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#89]
Build off of ONRR logo, the NRRD color pallet, and the USWDS standards as a starting point for visual design for onrr.gov

**Comment by mcharg** [comment]
Designs:
https://w8tuba.axshare.com/

**Comment by jennmalcolm** [comment]
working on template with MUI now

**Comment by mcharg** [comment]
MUI designs are now in the prototype.
