### ISSUE TITLE
Transfer all documents on onrr.gov to the N Drive

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#891]
There has been a request to put everything on the N drive after we're done with 508 compliance when we go to the new site.
N:\MRM Shared\Data Transfers

**Comment by cthomasONRR** [comment]
Y-drive is backed-up and stored here on the N-drive:

N:\IDM\DD\onrr.gov Y-drive Archive
![image](https://user-images.githubusercontent.com/72526208/213016932-72d8e95a-b0af-4471-9b40-ac6b1db6fb63.png)

**Comment by cthomasONRR** [comment]
@Maroyafaied I have both the old dev site and old live site files stored here: 
N:\IDM\DD

![image](https://user-images.githubusercontent.com/72526208/213257021-25320059-c55f-4895-87b9-2329ddfcbb52.png)

Shannon mentions the following location, N:\MRM Shared\Data Transfers, but I don't have editing privileges at this location. There is a TON of stuff in this folder, so not sure if we want our backups there too? Let me know if you do want to also put the archives in that location, and I can work with IT to figure out how to add them.

**Comment by Maroyafaied** [comment]
@cthomasONRR I have access to N:\MRM Shared\Data Transfers. I'll copy the folders to that location as well. I'll let you know when it's complete

**Comment by Maroyafaied** [comment]
@cthomasONRR The folders are now also in the Data Transfers shared folder. 
![image](https://user-images.githubusercontent.com/40175688/213485128-319c030c-dfb6-42cc-a046-09e52a96cc66.png)

**Comment by cthomasONRR** [comment]
@Maroyafaied Awesome, thanks! Closing this issue now :)
