### ISSUE TITLE
Visual design for geothermal diagram

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#893]
https://qmcq5k.axshare.com/#id=up0lnh&p=geothermal&g=14

**Comment by mcharg** [comment]
@lpgoldstein Thoughts on this for geothermal?
![Geothermal.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/73688b03-55d3-4718-9e1e-ddc8b4ff2626)

**Comment by lpgoldstein** [comment]
@mcharg What about vertical?    
![image](https://user-images.githubusercontent.com/39419003/145142144-b12ae9eb-6834-402a-9a91-4003ec0c5c25.png)

**Comment by mcharg** [comment]
@lpgoldstein I think that could work if we rotate the text on the arrows, so it's right side up.

**Comment by lpgoldstein** [comment]
@mcharg That makes more sense

**Comment by mcharg** [comment]
@lpgoldstein What do you think?
![image](https://user-images.githubusercontent.com/38465926/145228259-d2498548-98f0-4f63-b7ca-e089ffb3f0ad.png)

**Comment by mcharg** [comment]
@lpgoldstein This version might fit nicer below the content. And then we can put links to the handbooks right below each box.
![image](https://user-images.githubusercontent.com/38465926/145228822-1be461a3-75b7-4f24-99ec-36269736eb7b.png)

**Comment by mcharg** [comment]
@lpgoldstein This version puts class 1 before classes 2 & 3.
![image](https://user-images.githubusercontent.com/38465926/145229133-39e112f6-ba1b-49df-8c2a-01d0a4fd8381.png)

**Comment by mcharg** [comment]
@lpgoldstein Cleaned it up a bit.
![image](https://user-images.githubusercontent.com/38465926/145230008-f9985e76-8069-4646-aa60-411401c175a8.png)

**Comment by mcharg** [comment]
Another option.
![image](https://user-images.githubusercontent.com/38465926/145230427-ba219b2e-1066-4cc3-b5c6-a68a21319d96.png)

**Comment by lpgoldstein** [comment]
@mcharg I  like the last option the best - it's clean and easy to read - follows the natural progression of reading down the page

**Comment by mcharg** [comment]
@Maroyafaied I updated the page in the wireframes, if you want to send it to Herb.
https://qmcq5k.axshare.com/#id=e1wh3o&p=home_v3

**Comment by mcharg** [comment]
Now in the wireframes. https://qmcq5k.axshare.com/#id=vsgcdx&p=about_onrr

**Comment by Maroyafaied** [comment]
@mcharg where is this in the wireframe? both links above don't go to the diagram.

**Comment by mcharg** [comment]
@Maroyafaied Fixed the link above.

**Comment by mcharg** [comment]
Cleaned up shape usage.![Geothermal.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/717d8d43-beb1-4b3e-a61e-6a01dc8fadbc)

**Comment by Maroyafaied** [comment]
@mcharg Thanks, I send it to Herb.

**Comment by mcharg** [comment]
Gina wanted it more centered and both her and Jodie approved this version.![Geothermal.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/26da1cea-de47-4655-a854-a270896df64f)
