### ISSUE TITLE
Visual design for ONRR history diagram

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#895]
https://qmcq5k.axshare.com/#id=vsgcdx&p=about_onrr&g=14

**Comment by mcharg** [comment]
@lpgoldstein Thoughts?
![History.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/7903a0af-132c-46a0-a05d-09a969fa85a1)

In dev:
https://dev-onrr-frontend.app.cloud.gov/about

**Comment by lpgoldstein** [comment]
I like it - this is what it looks like in Dev 
![image](https://user-images.githubusercontent.com/39419003/145110208-bd5317bb-6d88-4377-950d-37a82a3b0fb8.png)

**Comment by mcharg** [comment]
Yeah, dev is cutting off all images.

**Comment by mcharg** [comment]
Changed font to Lato.
![History](https://user-images.githubusercontent.com/38465926/145110896-52022996-ef58-44ae-b725-c1abbd135f15.png)

**Comment by mcharg** [comment]
@Maroyafaied Do you have any feedback?

**Comment by Maroyafaied** [comment]
@mcharg It looks good to me, and I believe we showed it to Kimbra when reviewing wireframes so it should be good to go.
