### ISSUE TITLE
Update Contact list on ONRR.gov

### ISSUE THREAD

**Issue by Sheetsj** [ONRR/onrr.gov-site#896]
Hello,

I need to update the contact list on ONRR.gov. Location, "Contact US>under Online Resources> under ONRR Contacts by Company Assignment>File "Accounts Receivable, Billing, and Financial Issues information--Federal.

File can be located on N'Drive: \ISEDENNAS\DEN_Common\FMD\FinancialServices\Admin\Fed Assignment Contact List
Name of PDF file finserAssign
[finserAssign.pdf](https://github.com/ONRR/onrr.gov-site/files/6903200/finserAssign.pdf)

**Comment by cthomasONRR** [comment]
@sheetsj 

I downloaded the new PDF, and it failed the accessibility check.

Here are the errors we are seeing:
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/611a3094-ec33-4d17-a97e-89b674bf6aff)

This table summary errors are OK and you do not need to fix them since the rest of the table passed the accessibility test: 
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/f3e69ad2-f1bc-49c2-98b9-9577c3f8e911)

Please fix these accessibility errors, and then we'll be good to post.

Thanks,
Christine

**Comment by Sheetsj** [comment]
Hello Christine,

That is weird that it failed. I did the check before I sent it over to you. I will look at it again to see why it is doing that.



Jessica Sheets
Financial Services Staff Accountant
Office of Natural Resources Revenue
Phone: 303-231-3401
________________________________
From: Christine Thomas ***@***.***>
Sent: Thursday, July 29, 2021 2:39 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Sheets, Jessica E ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update Contact list on ONRR.gov (#896)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@Sheetsj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSheetsj&data=04%7C01%7Cjessica.sheets%40onrr.gov%7C9d55bbdbafa84244a2b408d952d100b6%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637631880633618498%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=%2FcJReVlryOEtLFkw79WIRLEXnPH%2F%2BXPKGUzGBzRJpss%3D&reserved=0>

I downloaded the new PDF, and it failed the accessibility check.

Here are the errors we are seeing:
[image.png]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcamo.githubusercontent.com%2Fcc80088460477e5c12b1dc8414938bd4ab7de77d7e61813872c31808ff063839%2F68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630663938303765626332626637373963633339323166322f36313161333039342d656333332d346431372d613937652d383962363734626636616666&data=04%7C01%7Cjessica.sheets%40onrr.gov%7C9d55bbdbafa84244a2b408d952d100b6%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637631880633618498%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=bw6RNntVGG9hEPUR1%2FS%2BsoBnP40xn2elDrhR4fU%2BxIs%3D&reserved=0>

This table summary errors are OK and you do not need to fix them since the rest of the table passed the accessibility test:
[image.png]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcamo.githubusercontent.com%2F3f9596d4a1e108ba86f045e4a9189ced62bf49c59e72a0bde27637b1bcf82f84%2F68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630663938303765626332626637373963633339323166322f66336536396164322d663162632d343963322d393862392d393537376333663865393131&data=04%7C01%7Cjessica.sheets%40onrr.gov%7C9d55bbdbafa84244a2b408d952d100b6%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637631880633628456%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=eHaTHY4upW08uTazwK2tryv661th8TwADLkmofAYZ%2F8%3D&reserved=0>

Please fix these accessibility errors, and then we'll be good to post.

Thanks,
Christine

**Comment by Sheetsj** [comment]
[finserAssign.pdf](https://github.com/ONRR/onrr.gov-site/files/6909003/finserAssign.pdf)
Okay, I think I fixed all the issues.

**Comment by cthomasONRR** [comment]
@sheetsj

Thanks! It's now on the Dev Site: http://2017onrr/about/contact.htm

Please review and let us know if it's good to go live.

Thanks,
Christine

**Comment by Sheetsj** [comment]
Looks good! Thank you, you can go live with it!

**Comment by cthomasONRR** [comment]
@sheetsj

Great! We just pushed it over to the live site (https://www.onrr.gov/about/contact.htm). There is usually some lag time before it appears.

Please let us know if you have any questions.

Thanks!
Christine
