### ISSUE TITLE
Identify all the components used in the wireframes

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#898]

**Comment by mcharg** [comment]
I went through the wireframes and added issues with "Component:" in the title for all the components I found.

**Comment by Maroyafaied** [comment]
@mcharg @jlouis-onrr would adding  icons such as a pdf icon next  to docs  or a glossary icon be considered a "component"? Also do we need something for the new reporter set up page for building checklists?

**Comment by mcharg** [comment]
I figured the checklist would be a page template and created #900 for that.
