### ISSUE TITLE
Wireframe for valuation example page

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#899]
The current page uses nonstandard components, so we need to make one using standard components.

**Comment by mcharg** [comment]
@cthomasONRR Here's a first pass.  Thoughts?  I'm going to put the second example that lives on the live site into this framework tomorrow because that one's got a tab that's a drop-down that I need to figure out what to do with.

https://qmcq5k.axshare.com/#id=0royo3&p=valuation_example

**Comment by cthomasONRR** [comment]
@mcharg  

I really like this! I especially like how you can be in one of the subtabs of the detailed example, quickly check the example statement, and when you go back to the detailed example tab, it remembers what specific subtab you were on. It will definitely be easier for someone actively working through the example to navigate through the webpage!

For the 'Royalty Value Less Allowances' subtab, the content is different, so just want to make sure the correct content is in the final version. (Looks like it is the PC03 steps repeated instead of what's currently in the RVLA tab.)

With the detailed example subtabs, when you scroll to the bottom of a subtab, there are currently links that bring you back to the main subtab menu at the top of the page, bot those aren't in the wireframe... will those links still be in the final version?

Other than those questions, it looks good to me!

**Comment by mcharg** [comment]
@Maroyafaied This is ready for you to review and I scheduled a meeting with Jodie and Amy to get their feedback.
Example 1 wireframe: https://qmcq5k.axshare.com/#id=0royo3&p=valuation_example&g=1
Example 2 wireframe: https://qmcq5k.axshare.com/#id=nm9ju1&p=valuation_example_2&g=1

**Comment by Maroyafaied** [comment]
@mcharg sorry for the late response on this. I added some comments but we'll see what Amy thinks. Also, I liked what you did with example 2 for disallowed costs but put a comment in there asking if we checked with Jerome it's something we can do within the tabs.

**Comment by mcharg** [comment]
@Maroyafaied I did check with Jerome on that.

**Comment by mcharg** [comment]
@Maroyafaied @cthomasONRR I applied the changes to the first example.
https://qmcq5k.axshare.com/#id=0royo3&p=valuation_example&g=1

A few things to note:
* I only applied changes to the first tab of the detailed example.
* I applied visual design, so we can see how the tips and letters work with that overall.
* I used green instead of blue for the letters, since blue means clickable everywhere else on the site.  Purple is also an option if it feels like there is too much green.

**Comment by cthomasONRR** [comment]
@mcharg - I think this looks good. 

My one question: for the first tab of the detailed example, is there a way to make the call-out boxes directly associated with a bullet point within a step? Right now, the first green info box is kind of in between subsets, and I'm wondering if we can make it a little more defined so the call-out boxes aren't 'floating' in the right margin. Maybe something like this?
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/55d842b8-6d46-48b0-8efd-3ea03c48b7c0)

**Comment by mcharg** [comment]
@cthomasONRR I have a feeling that would be difficult to code.  We may not even have the ability for them to be in a separate column, at first, and may have to move them inline with the text.

**Comment by cthomasONRR** [comment]
@mcharg - OK just curious about what we can do. Being inline with the text might be better, as it will help the reader directly associated it with a specific substep.

**Comment by Maroyafaied** [comment]
@mcharg I think this looks great, there's just some formatting things with step 2.  We just need to be consistent with the ( ) and there's some spacing issue but that's just small stuff, the overall look of the wireframe is great! 
![image](https://user-images.githubusercontent.com/40175688/130489392-e0592d26-f291-4bed-89d2-af3407735565.png)

**Comment by mcharg** [comment]
@Maroyafaied It's because Axure can't do a second level of bullets and I had to put in a line break and spaces to get the second line of the fake bullets to line up, which looks different depending on the browser.

**Comment by mcharg** [comment]
Changes applied to second example.
https://qmcq5k.axshare.com/#id=nm9ju1&p=valuation_example_2&g=1

**Comment by mcharg** [comment]
I scheduled a meeting to review, since we haven't gotten a response via email.
