### ISSUE TITLE
Upload NYMEX March prices

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#90]
We have the monthly NYMEX prices and spreadsheet ready to be uploaded to the ONRR.gov website.  The spreadsheet is attached.  Please reference the shared document "Data for ONRR.gov" on OneDrive.
@sudarr
[NYMEX0320.xlsx](https://github.com/ONRR/onrr.gov-site/files/4429517/NYMEX0320.xlsx)

Thanks,
Cory Forgrave

**Comment by lpgoldstein** [comment]
@jennmalcolm and @forgravec These are ready for your review http://2017onrr//Valuation/NYMEX.htm

**Comment by forgravec** [comment]
@lpgoldstein The prices look good, but when I click on the spreadsheet to download it, I get an error. The February one downloads fine, but not March.

@Sudar, Robert J<mailto:Robert.Sudar@onrr.gov>

Thanks,
Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
________________________________

**Comment by jennmalcolm** [comment]
@forgravec and @sudarr the file download should be working now. Please confirm, and I will push to production. Thanks.

**Comment by forgravec** [comment]
Looks good.
@Sudar, Robert J<mailto:Robert.Sudar@onrr.gov>

Thanks,
Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
________________________________

**Comment by jennmalcolm** [comment]
Nymex March price now live on onrr.gov.
