### ISSUE TITLE
EVENT CALNDAR                                                   Note: Please add to Event Calendar on Allottee Assistance page.

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#909]
AUGUST 18, 2021

CONCHO AREA MEETING

Event Information
Location:  By Telephone 
Time: 1:00 pm to 2:00 pm CST
 
Description:  Meeting will be a Call-in Meeting to hear a presentation and updates from ONRR Outreach Office and representatives from BLM, BTFM, and BIA will discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust properties.    A limited number of lines will be available for callers to this meeting. 
 
Who Should Attend:  IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Concho Agency area, Southern Plains Region in Oklahoma.
Other Information: To attend the meeting you must contact the ONRR OKC Outreach Office at (800) 354-7015 to reserve your space and to get the call-in number and passcode for the meeting on August 18th, 2021.   A limited number of lines will be available for callers to this meeting.  ONNR Outreach office hours are Monday- Friday from 7:30 am-5:00 pm.

Event Contact
Name: ONRR OKC Outreach Office
Phone: Toll-free (800) 354-7015
Email: onrroutreachokc@onrr.gov

AUGUST 24, 2021

FT. TOTTEN, TURTLE MTN - BELCOURT, NEW TOWN, ND. VIRTUAL OUTREACH MEETING

Event Information
Location:  Telephone 
Time: 10:00 am - 11:00 am MST 

Description: Representatives from the Office of Natural Resources Revenue will host a Question and Answer session by phone for Indian Mineral Owners and Trust Property Owners regarding their Indian Oil & Gas leases, IIM Accounts, and Indian Trust Properties. Representatives from the Bureau of Land Management, Bureau of Indian Affairs, and Bureau of Trust Funds Administration are invited to be in attendance to answer questions

Who Should Attend:  IIM account holders, Indian mineral owners, and Indian trust property owners in the Ft. Totten, Turtle Mtn - Belcourt, New Town area in North Dakota. 
Other Information: To attend the outreach session, please contact the ONRR Denver Outreach Office at (800) 982-3226, for the call-in number and passcode.  The ONRR Denver Outreach Office hours are Monday-Friday 7:30am-4:00pm. 

Event Contact
Name: ONRR Denver Outreach Office, 
Phone: Toll Free (800) 982-3226,
Email: onrroutreachdenver@onrr.gov 

AUGUST 26, 2021 

BILLINGS, N. CHEYENNE SR. CENTER - LAME DEER, BIA CROW AGENCY, CROW AGENCY, MT VIRTUAL OUTREACH

Event Information
Time: 10:00 am - 11:00 am MST 
Location:  Telephone 

Description: Representatives from the Office of Natural Resources Revenue will host a Question and Answer session by phone for Indian Mineral Owners and Trust Property Owners regarding their Indian Oil & Gas leases, IIM Accounts, and Indian Trust Properties. Representatives from the Bureau of Land Management, Bureau of Indian Affairs, and Bureau of Trust Funds Administration are invited to be in attendance to answer questions.  

Who Should Attend:  IIM account holders, Indian mineral owners, and Indian trust property owners in the Billings, N. Cheyenne - Lame Deer, Crow Agency area in Montana.
Other Information: To attend the outreach session, please contact the ONRR Denver Outreach Office at (800) 982-3226, for the call-in number and passcode.  The ONRR Denver Outreach Office hours are Monday-Friday 7:30am-4:00pm. 

Event Contact:  
Name: ONRR Denver Outreach Office, 
Phone: Toll Free (800) 982-3226,
Email:  onrroutreachdenver@onrr.gov

**Comment by Maroyafaied** [comment]
@Toddsand21 would you like us to remove the July events?

**Comment by Maroyafaied** [comment]
@Toddsand21 Please review the dev site and let us know if you'd like the July events removed. Thanks 

http://2017onrr/events.htm

**Comment by Toddsand21** [comment]
On the Concho Meeting :  1)  could we add an "S" in between the CT on the time for central standard time (CST).  2)  And also in the paragraph Other Information: could we add the words "toll-free"  in the sentence to read  "to get the toll-free call-in number and passcode"
And last delete the July Ft Duchesne Meeting but keep the 71st Indian Hills Powwow info on there (just to show we are doing both virtual and in person outreach).  Everything else looks fine.  Thanks.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 Can you please make the changes above. Thanks

**Comment by daniel-coleman-1** [comment]
@Maroyafaied changes updated and verified in dev, moving to the live site now.

**Comment by Toddsand21** [comment]
Great! Thanks Guys!

**Comment by daniel-coleman-1** [comment]
@Maroyafaied @Toddsand21 

[We are live!](https://onrr.gov/events.htm)

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 looks great, thanks!
