### ISSUE TITLE
April 2020 Indian Index Zone Prices 

### ISSUE THREAD

**Issue by damionschulte** [ONRR/onrr.gov-site#91]
Hello,
 I've updated the Office 365 sheet ( Data for ONRR.gov.xlsx) to include the April Indian Index Zone prices for the http://2017onrr/Valuation/allzones.htm page.  
 
Can you please post them to our development site and I'll review before we make them public?  

@sudarr

**Comment by lpgoldstein** [comment]
@jennmalcolm and @damionschulte These are ready for your review

**Comment by jennmalcolm** [comment]
@lpgoldstein it looks good to me, but we will wait until we get the ok from @damionschulte or @sudarr to publish. Thanks.

**Comment by damionschulte** [comment]
@jennmalcom , where to I view these?  Sorry new to this process :)

@sudarr

**Comment by jennmalcolm** [comment]
@damionschulte here is the link: http://2017onrr/Valuation/allzones.htm 

You'll need to use VPN.

**Comment by damionschulte** [comment]
@jennmalcom, and @lpgoldstein, these prices look great!  Thank you both so much.  

@sudarr

**Comment by damionschulte** [comment]
@jennmalcom, and @lpgoldstein, Sorry do I need to hit the close issue button to finish this?

@sudarr

**Comment by jennmalcolm** [comment]
No, @damionschulte, just the comment is good. We'll push the prices to the live site, and close once they're live. Thank you!

**Comment by damionschulte** [comment]
@jennmalcom, and @lpgoldstein, Cool thank you again.  You guys are the best!

@sudarr

**Comment by jennmalcolm** [comment]
The prices are live on onrr.gov.
