### ISSUE TITLE
Identify content types for CMS 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#913]
What type of sections of pages will non developers interact with?

**Comment by mcharg** [comment]
@daniel-coleman-1 Have you started anything on this?

**Comment by daniel-coleman-1** [comment]
@mcharg here's the teams doc:

https://teams.microsoft.com/l/file/3141268f-ed5a-4386-832e-af660d02f595?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp-my.sharepoint.com%2Fpersonal%2Fcolemanw_mms_gov%2FDocuments%2FMicrosoft%2520Teams%2520Chat%2520Files%2FContent%2520Types.docx&baseUrl=https%3A%2F%2Fdoimspp-my.sharepoint.com%2Fpersonal%2Fcolemanw_mms_gov&serviceName=recent

**Comment by mcharg** [comment]
@daniel-coleman-1 Please give me access to the file.

**Comment by mcharg** [comment]
@daniel-coleman-1 I still don't have access to the doc.  Please move it into one of the shared folders, like I showed you how to do yesterday.

**Comment by daniel-coleman-1** [comment]
@mcharg 

https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/Documents/onrr.gov/Content%20Audit/Content%20Types.docx?d=w50e896e9a659497d9e22c1ce28dcef1a&csf=1&web=1&e=LgZEAC

**Comment by Maroyafaied** [comment]
This was for identifying UI components which has already been done.
