### ISSUE TITLE
Replace Documents on the About ONRR Page 

### ISSUE THREAD

**Issue by cmathers1** [ONRR/onrr.gov-site#914]
Good afternoon, 

Please replace these three documents on the ONRR About Us MOU/SOP page: 
http://2017onrr/about/MOUs-and-SOPs.htm

[FINAL Interagency SOP - 09-23-13.pdf](https://github.com/ONRR/onrr.gov-site/files/6920166/FINAL.Interagency.SOP.-.09-23-13.pdf)

[Concurrence Memo June 2013 (1).pdf](https://github.com/ONRR/onrr.gov-site/files/6920171/Concurrence.Memo.June.2013.1.pdf)

[Signed SOP Memo September 18 2013.pdf](https://github.com/ONRR/onrr.gov-site/files/6920172/Signed.SOP.Memo.September.18.2013.pdf)

**Comment by cthomasONRR** [comment]
Good morning, @cmathers1 -
All 3 files passed the accessibility check! Congrats! Thank you for all your hard work!

I have updated the documents on the Dev Site: http://2017onrr/about/MOUs-and-SOPs.htm

Please let us know if it looks good, and give us your approval for it to go on the live site.



@Maroyafaied - I am still in the process of getting full access to the Z-drive and will need help moving the documents from Y to Z for them to go live. Thanks!

**Comment by cthomasONRR** [comment]
I got Christina's approval via Teams chat.

@Maroyafaied - I was able to move these 3 PDFs from to Y-drive to the Z-drive without issues.

@cmathers1 - the changes should be live shortly!

I will go ahead and close this request.
Thanks!
