### ISSUE TITLE
NYMEX July prices ready for ONRR.gov

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#918]
The July NYMEX and Roll prices are ready to be updated as well as the spreadsheet ready to be added to ONRR.gov
[NYMEX072021.xlsx](https://github.com/ONRR/onrr.gov-site/files/6947334/NYMEX072021.xlsx)

Thanks,
Cory Forgrave
@sudarr

**Comment by Maroyafaied** [comment]
1. Save file here as "NYMEX0721" \\iondeniisp01\ONRR2017\valuation\ExcelFiles
2.  Add date, calendar month avg, NYMEX roll and name of excel file (step 1) to this excel sheet \\iondeniisp01\ONRR2017\assets\NYMX
3. Check dev site if most recent month is updated  and send link to review http://2017onrr/valuation/NYMEX.htm

**Comment by cthomasONRR** [comment]
@forgravec I updated the Dev site (http://2017onrr/valuation/NYMEX.htm). Please review and let us know if you approve for these changes to go live. Thanks!

**Comment by forgravec** [comment]
Prices look good...Thanks!

Cory Forgrave
Economist
Office of Natural Resources Revenue
303-231-3589
***@***.***

________________________________
From: Christine Thomas ***@***.***>
Sent: Monday, August 9, 2021 11:42 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Forgrave, Cory J ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] NYMEX July prices ready for ONRR.gov (#918)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@forgravec<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fforgravec&data=04%7C01%7Ccory.forgrave%40onrr.gov%7Cd10c549e3bfa4f51907708d95b5d2f47%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641278524079960%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=68sx8HXsTeKMc1Q%2FRgspoWuU6i54IvSdcUmw6BoLYGY%3D&reserved=0> I updated the Dev site (http://2017onrr/valuation/NYMEX.htm). Please review and let us know if you approve for these changes to go live. Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F918%23issuecomment-895413480&data=04%7C01%7Ccory.forgrave%40onrr.gov%7Cd10c549e3bfa4f51907708d95b5d2f47%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641278524089917%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yNi9ArAZ6PrMo5c%2FxYFWPyww6C%2FS2EcuvonYihbSTvs%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOXGYMFITZ73S44JF42V3T3T4AHSHANCNFSM5BWMPLCQ&data=04%7C01%7Ccory.forgrave%40onrr.gov%7Cd10c549e3bfa4f51907708d95b5d2f47%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641278524089917%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9UV8VBzK3QS8COcN5Ur%2Fj5MKBcEy%2BXHHymg%2Buv8A04A%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ccory.forgrave%40onrr.gov%7Cd10c549e3bfa4f51907708d95b5d2f47%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641278524099873%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=epUb3n6wm7qZ5TVJPyAxfvJL3vgcDnDssGCKp9wUxfA%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Ccory.forgrave%40onrr.gov%7Cd10c549e3bfa4f51907708d95b5d2f47%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641278524099873%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=m42dEpMyi2aVkdMHDdOE%2Fs5mIE3TRVpxoKX1mioFXs0%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@forgravec I just made the changes live (https://www.onrr.gov/valuation/NYMEX.htm). Please allow around 30min for these changes to appear on the live site. Press Ctrl+F5 to refresh the page. Thanks!

**Comment by cthomasONRR** [comment]
@forgravec 

The changes are now live for me. Closing this issue.
