### ISSUE TITLE
August Indian Index Zone prices

### ISSUE THREAD

**Issue by penvosej** [ONRR/onrr.gov-site#920]
Please include the Indian Index Zone prices for August on ONRR.gov. The "Data for ONRR.gov" Excel spreadsheet has been updated with the newest prices.

@sudarr

**Comment by Maroyafaied** [comment]
@cthomasONRR I'll schedule us for today to work on the pricing update issues together.

**Comment by cthomasONRR** [comment]
@Maroyafaied Sounds good- thanks for the help!

**Comment by Maroyafaied** [comment]
1. Copy prices for most recent month from this shared spreadsheet https://doimspp-my.sharepoint.com/:x:/r/personal/sudarr_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B610913F6-CC44-4222-8521-FAD9EA5FEB0E%7D&file=Data%20for%20ONRR.gov.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1&ct=1628529521799&wdOrigin=OFFICECOM-WEB.START.OTHER&cid=ecd8e4fe-d9f0-4804-8353-8afe18a9c432
2. Paste prices here \\iondeniisp01\ONRR2017\assets\Index-Zones
3. Check dev site and send link for review http://2017onrr/valuation/allzones.htm
4. Post live

**Comment by cthomasONRR** [comment]
@penvosej I made the updates on the Dev site (http://2017onrr/valuation/allzones.htm). Could you please review and give us your approval for it to go live? Thanks!

**Comment by penvosej** [comment]
Hi Christine,

The Indian Index Zone prices for August look good. Can you please do me one small favor, though? Could you please correct the January & June NRM prices to have a "0" in the hundredths place, and do the same for the July San Juan Basin price? I try to catch these but I guess the times I've been assigned the primary role for Indian Index Zone this year I must have missed them.

Thanks!
Jessica

From: Christine Thomas ***@***.***>
Sent: Monday, August 9, 2021 11:50 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] August Indian Index Zone prices (#920)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpenvosej&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C547becf9770e4ba8117e08d95b5e315a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641282378480803%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SMCvzznnt1LYN34yEQYK49zEPWPCuqxRJxU2BxU1S00%3D&reserved=0> I made the updates on the Dev site (http://2017onrr/valuation/allzones.htm). Could you please review and give us your approval for it to go live? Thanks!

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F920%23issuecomment-895417854&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C547becf9770e4ba8117e08d95b5e315a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641282378490762%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OsWbaxPJ799iDrP3Fjc4h8qxG5tFZSC7h19VCPPPPe4%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQQSAVFYSJHREV4YBAWOQNLT4AIMDANCNFSM5BWOUFYA&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C547becf9770e4ba8117e08d95b5e315a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641282378490762%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KvELP%2F%2BTR%2BOyxKTc2lqJRpcFxT1sihihN4vX7Zepk8o%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C547becf9770e4ba8117e08d95b5e315a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641282378500715%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GK9tQpcqFMvluB5qALi1fFDWiJuT%2F3USSKoT5ETEhoo%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C547becf9770e4ba8117e08d95b5e315a%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641282378500715%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=y9TBsSqhqfs2Q%2FLz5rUSlSotZO0nuN889m%2F2GEPr7Hw%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@penvosej - Just fixed! Please let me know what you think!

**Comment by penvosej** [comment]
Everything looks great; thank you so much for fixing those! The data looks good to go live.

From: Christine Thomas ***@***.***>
Sent: Monday, August 9, 2021 12:04 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Penvose, Jessica M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] August Indian Index Zone prices (#920)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@penvosej<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpenvosej&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C6cc337130b1545d6c96808d95b600d57%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641290744187854%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kfhM%2BTDPwGjJzF%2FgIBZKlvHvldrBSQaCIZLOQT7NdkE%3D&reserved=0> - Just fixed! Please let me know what you think!

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F920%23issuecomment-895426466&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C6cc337130b1545d6c96808d95b600d57%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641290744187854%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TR3DfENIBXnIaOJJRNA2bztjyRtQEXp0tvsClyOOqZQ%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQQSAVHRHLXTBNPULBQFGG3T4AJ7VANCNFSM5BWOUFYA&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C6cc337130b1545d6c96808d95b600d57%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641290744197813%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=x5feE4umAho%2F4oCl1DRsUdDQEbShr9Uh90sLnGpxOXU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C6cc337130b1545d6c96808d95b600d57%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641290744197813%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NgX0vrqS91i8Fs1o3hQ5OU4ItMCyLCBfU4HJ7IXx9E4%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cjessica.penvose%40onrr.gov%7C6cc337130b1545d6c96808d95b600d57%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641290744207769%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tlJugSoMux2yX2fhb%2FDpMgZlbIhCYDZil%2BGDq9NRuyo%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@penvosej I just made the changes live (https://www.onrr.gov/valuation/allzones.htm). Please allow around 30min for these changes to appear on the live site. Press Ctrl+F5 to refresh the page. Thanks!

**Comment by cthomasONRR** [comment]
@penvosej 

The changes are now live for me. Closing this issue.
