### ISSUE TITLE
Updated AM documents

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#922]
Lori sent me an email with these two docs on AM's list.  They have errors, so I asked her to fix them.

- [x] [8-27-12--2.pdf](https://app.zenhub.com/files/210892300/14c97b6c-5684-4330-8feb-0f9887eae8b7/download)
- [x] [20141106.pdf](https://app.zenhub.com/files/210892300/bd10c25b-15ad-4b98-a05c-f7ab1d84681b/download)

**Comment by cthomasONRR** [comment]
@mcharg 

- [ ]  8-27-12--2.pdf
This PDF is not 508-Compliant. It has issues with Alt Text and Headings.

- [ ]  20141106.pdf
This PDF is not 508-Compliant. It has issues with Alt Text and Headings.

**Comment by mcharg** [comment]
@cthomasONRR I asked Lori to correct the issues.  I'll post the updated versions when she sends them.

**Comment by mcharg** [comment]
Testing chat integration

**Comment by cthomasONRR** [comment]
Lori emailed Shannon a 508-Compliant version of [8-27-12--2](https://app.zenhub.com/files/210892300/19c9ad7a-3bf7-4358-ae6b-565a10a9767b/download). I uploaded to the dev and live sites, and updated the accessibility tracking spreadhseet.

**Comment by cthomasONRR** [comment]
Lori emailed Shannon a 508-Compliant version of [20141106](https://app.zenhub.com/files/210892300/48f4b33a-d18f-4ece-b882-a80391310d67/download).

I uploaded to the dev and live sites, and updated the accessibility tracking spreadsheet.

**Comment by mcharg** [comment]
@cthomasONRR I think this issue is good to close.

**Comment by cthomasONRR** [comment]
Closing this issue.
