### ISSUE TITLE
Remediated Documents for onrr.gov

### ISSUE THREAD

**Issue by cmathers1** [ONRR/onrr.gov-site#923]
Good morning, 

Please post these remediated document on onrr.gov.  Thank you!

[ONRR WES Supplemental Statistical Report 2017-09-29 (2) (1).pdf](https://github.com/ONRR/onrr.gov-site/files/6956063/ONRR.WES.Supplemental.Statistical.Report.2017-09-29.2.1.pdf)

[ONRR Proposed Workplace Environment Response Plan 04042018.pdf](https://github.com/ONRR/onrr.gov-site/files/6956065/ONRR.Proposed.Workplace.Environment.Response.Plan.04042018.pdf)

[ONRR Harassing Conduct PB Plan - 5.8.18 (1).pdf](https://github.com/ONRR/onrr.gov-site/files/6956066/ONRR.Harassing.Conduct.PB.Plan.-.5.8.18.1.pdf)

Thank you, 
Christina

**Comment by cthomasONRR** [comment]
All 3 files passed the accessibility test! I'm working on getting them updated on the Dev site.

**Comment by cmathers1** [comment]
Thank you!  Have a great day!

Sincerely,

Christina

Christina Mathers
Staff Assistant
Director/Deputy Director's Office
Office of Natural Resources Revenue
6th Avenue and Kipling Street Bldg. 85
Denver, Colorado 80225
Phone:  303-231-3429
Cell: 303-503-1315
________________________________
From: Christine Thomas ***@***.***>
Sent: Monday, August 9, 2021 12:44 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Mathers, Christina ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Remediated Documents for onrr.gov (#923)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



All 3 files passed the accessibility test! I'm working on getting them updated on the Dev site.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F923%23issuecomment-895453726&data=04%7C01%7Cchristina.mathers%40onrr.gov%7Cda5f4c4c0e46440f1cd708d95b65c9d4%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641315025169718%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AKyoAcQxx5euLCgYsawA3k3sdIv%2BXL2PoW92t%2BZ4%2FTQ%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAU5GF7TE67XSYUPP4DWOJXDT4AOZ5ANCNFSM5B2MZP7A&data=04%7C01%7Cchristina.mathers%40onrr.gov%7Cda5f4c4c0e46440f1cd708d95b65c9d4%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641315025179675%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hL6NUhoPkbbJu8UDUqnQjU8lzQM%2FLyq6jCf4V7DZC7k%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cchristina.mathers%40onrr.gov%7Cda5f4c4c0e46440f1cd708d95b65c9d4%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641315025189630%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DOAvzJcrIM0jCvczhFDwZei%2Fdss%2F9V6vHE9j693aTws%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cchristina.mathers%40onrr.gov%7Cda5f4c4c0e46440f1cd708d95b65c9d4%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641315025199589%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=I83HgYoXjMaHYThuWH1c%2FDbSthCFfvEwWKcV27zzOaA%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@cmathers1

These 3 PDFs are updated on the Dev site (http://2017onrr/about/anti-harassment.htm). Please review and give us your approval for the changes to go live. 

Thank you so much for your efforts in making all the documents 508-Compliant!!!

**Comment by cthomasONRR** [comment]
@cmathers1 - can we get your approval to go live? Thanks!

**Comment by cmathers1** [comment]
Good morning,

Yes, we can go live. Thank you!

Sincerely,

Christina

Christina Mathers
Staff Assistant
Director/Deputy Director's Office
Office of Natural Resources Revenue
6th Avenue and Kipling Street Bldg. 85
Denver, Colorado 80225
Phone:  303-231-3429
Cell: 303-503-1315
________________________________
From: Christine Thomas ***@***.***>
Sent: Tuesday, August 10, 2021 7:25 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Mathers, Christina ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Remediated Documents for onrr.gov (#923)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@cmathers1<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcmathers1&data=04%7C01%7Cchristina.mathers%40onrr.gov%7C50d397fee35e4ef6a12008d95c025120%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641987299799007%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OyiU%2FeYJ0fqUAxkfZyxTWAQabtywppPAC7I57voWfjM%3D&reserved=0> - can we get your approval to go live? Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F923%23issuecomment-896026589&data=04%7C01%7Cchristina.mathers%40onrr.gov%7C50d397fee35e4ef6a12008d95c025120%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641987299808960%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TbqXirieM4jo9T4wcWs1j0YZN03MvKkgY1XlHKV1Ehs%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAU5GF7QPWP2ELYF7ALTXRSTT4ESDLANCNFSM5B2MZP7A&data=04%7C01%7Cchristina.mathers%40onrr.gov%7C50d397fee35e4ef6a12008d95c025120%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641987299808960%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zOKs3GltbfWM2pCZVfzxpiEoP0ytwdFCluJRKl5NXGc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cchristina.mathers%40onrr.gov%7C50d397fee35e4ef6a12008d95c025120%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641987299818927%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=W2CEFrZ0MeYzqpK5GYHls1UAdwjkB46NKPthLJeUieI%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cchristina.mathers%40onrr.gov%7C50d397fee35e4ef6a12008d95c025120%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641987299818927%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oI5fUYESCbX9w8wGRpqfiCRg0OpxbZz2n%2Bh61RWNQJk%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@cmathers1

Great! Thanks!
I made these changes live (https://www.onrr.gov/about/anti-harassment.htm). Please allow around 30min for the changes to appear on the live site. Press "Ctrl+F5" to refresh the page.

**Comment by cthomasONRR** [comment]
I verified that these 508-compliant PDFs made it to the live site before closing this issue.
