### ISSUE TITLE
Remediated Documents for onrr.gov

### ISSUE THREAD

**Issue by cmathers1** [ONRR/onrr.gov-site#925]
Good afternoon,

Please replace the existing documents with the attached remediated documents on the Testimony page. Thank you!
[OMB cleared FAIR Act statement.pdf](https://github.com/ONRR/onrr.gov-site/files/6956546/OMB.cleared.FAIR.Act.statement.pdf)
[BOEMRE_Reorg_testimony_7-15-11.pdf](https://github.com/ONRR/onrr.gov-site/files/6956547/BOEMRE_Reorg_testimony_7-15-11.pdf)
[ONRR-Testimony-3-17-11.pdf](https://github.com/ONRR/onrr.gov-site/files/6956548/ONRR-Testimony-3-17-11.pdf)

**Comment by daniel-coleman-1** [comment]
@cmathers1  changes have been implemented in dev, with your approval I will push the changes live.

file:///Y:/about/presentations.htm

**Comment by cmathers1** [comment]
Thank you. Please post them to the live site Have a great day!

Sincerely,

Christina

Christina Mathers
Staff Assistant
Director/Deputy Director's Office
Office of Natural Resources Revenue
6th Avenue and Kipling Street Bldg. 85
Denver, Colorado 80225
Phone:  303-231-3429
Cell: 303-503-1315
________________________________
From: daniel-coleman-1 ***@***.***>
Sent: Monday, August 9, 2021 12:37 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Mathers, Christina ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Remediated Documents for onrr.gov (#925)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@cmathers1<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcmathers1&data=04%7C01%7Cchristina.mathers%40onrr.gov%7C5a5b7e033f884a19307f08d95b64c8c1%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641310696768566%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Su%2ByFDdF9xQknZQ1nH1TsJQ472uTUVsgw31XVv4tJRU%3D&reserved=0> changes have been implemented in dev, with your approval I will push the changes live.

file:///Y:/about/presentations.htm

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F925%23issuecomment-895448269&data=04%7C01%7Cchristina.mathers%40onrr.gov%7C5a5b7e033f884a19307f08d95b64c8c1%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641310696768566%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KyknOKv%2BiBbI1STzG5ffqiDReVJaQcxcAkCSNB3Lj5Y%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAU5GF7THYQYK3C7OPRFTM6DT4AN5HANCNFSM5B2RONAA&data=04%7C01%7Cchristina.mathers%40onrr.gov%7C5a5b7e033f884a19307f08d95b64c8c1%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641310696778526%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yaXgGqxw0yoFaUFcAYuyPpQEkvea8AqvX3KdhTFflTs%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cchristina.mathers%40onrr.gov%7C5a5b7e033f884a19307f08d95b64c8c1%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641310696778526%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rlcyFs%2BmU%2FJanpGFSvM0QdYedQBBW6w42T%2F6sNNO9Zc%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cchristina.mathers%40onrr.gov%7C5a5b7e033f884a19307f08d95b64c8c1%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637641310696788475%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ULQ3HGrvX8C75R7QyPK%2FqotB5%2BYCNz1xR5d8fBFBpP0%3D&reserved=0>.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 Thanks for taking this issue, please update the accessibility tracking sheet once these are updated live. Thanks

**Comment by daniel-coleman-1** [comment]
@Maroyafaied  updated in accessibility tracking spreadsheet

**Comment by daniel-coleman-1** [comment]
@cmathers1 Fantastic, we are live!

[Presentations & Testimony](https://www.onrr.gov/About/Presentations.htm)
