### ISSUE TITLE
Create a "how-to" guide for uploading MSA prices to ONRR.gov

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#926]
I created a how-to guide for uploading MSA pricing data to ONRR.gov.

It is located on Teams: NRRD > General > ONRR.gov 
The word document is called ["How to upload MSA monthly prices"](https://teams.microsoft.com/l/file/7DAF2AF4-F328-4B2C-B58F-B477552029A1?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FHow%20to%20upload%20MSA%20monthly%20prices.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

@maroyafaied this is ready for your review!

**Comment by Maroyafaied** [comment]
@cthomasONRR GREAT JOB! Thanks for getting on top of that so quickly, it looks great! We also upload the gas major portion (IndianMajorPortionGasPrices excel file) and oil major portion pricing (IBMP excel file), it's a very similar process to the Index zone update where we copy and paste from the file MSA sends us.  Can you create a section for both of these prices with the same instructions as the Indian Index zone but with the appropriate excel file and links? Let me know if that makes sense.

**Comment by cthomasONRR** [comment]
@Maroyafaied - I added in those sections. They are ready for your review.

**Comment by Maroyafaied** [comment]
@cthomasONRR looks good.

**Comment by cthomasONRR** [comment]
@Maroyafaied Awesome! 

I'm thinking of creating a new folder within ONRR.gov to house documentation like this... or should it go on the onrr.gov wiki instead?

**Comment by Maroyafaied** [comment]
@cthomasONRR Yes, let's create a folder in teams. We can add it to the wiki under releasing changes but take the link out to the spreadsheet that MSA provides, I don't want to make it public even though I know you have to request access but better to take precaution incase they put prices in there they don't want us to publish yet.

**Comment by cthomasONRR** [comment]
@Maroyafaied - Great! I made a folder in Teams. Let me know when you're out of the doc and I can move it over.

I can work on creating a wiki section for it too, will hopefully finish that this week.

**Comment by cthomasONRR** [comment]
@Maroyafaied The GitHub Wiki is ready for your review: https://github.com/ONRR/onrr.gov-site/wiki/Releasing-changes-to-production

**Comment by Maroyafaied** [comment]
@cthomasONRR looks great. Thanks

**Comment by cthomasONRR** [comment]
Great! I will close this issue.
