### ISSUE TITLE
July IBMP Prices

### ISSUE THREAD

**Issue by damionschulte** [ONRR/onrr.gov-site#927]
All, I have updated the ONRR.gov sheet with the July 2021 IBMP prices.  Can you please publish them to the website?  Thank you
@sudarr

**Comment by Maroyafaied** [comment]
@cthomasONRR we can work on this one together tomorrow during our check in.

**Comment by cthomasONRR** [comment]
@damionschulte

The July prices are on the Dev site: http://2017onrr/valuation/IndianOilIBMP.htm
Please review and let us know if you approve for the changes to go live. Thanks!

**Comment by damionschulte** [comment]
These look great! Thank you.

From: Christine Thomas ***@***.***>
Sent: Wednesday, August 11, 2021 9:21 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] July IBMP Prices (#927)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@damionschulte<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdamionschulte&data=04%7C01%7Cdamion.schulte%40onrr.gov%7Cbf2b5fd970914e6965f108d95cdbb85b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637642921939987972%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zAOQEWDQgL8jaJvxaxkkTMN61%2BMrnKnVUApfbwpsXtg%3D&reserved=0>

The July prices are on the Dev site: http://2017onrr/valuation/IndianOilIBMP.htm
Please review and let us know if you approve for the changes to go live. Thanks!

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F927%23issuecomment-896918979&data=04%7C01%7Cdamion.schulte%40onrr.gov%7Cbf2b5fd970914e6965f108d95cdbb85b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637642921939997929%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sF%2BKy5CW4jcICZ37PebNPrL7ocLK6kWrZUTVDL1q8ik%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAO4AEPNBJCPFHXZIE74NCETT4KIPNANCNFSM5B42U6OA&data=04%7C01%7Cdamion.schulte%40onrr.gov%7Cbf2b5fd970914e6965f108d95cdbb85b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637642921939997929%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wYEjRK2iWa9IGz5J%2F%2BTrB%2Fo8XfML0yPeBp%2Fb67PQXIU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdamion.schulte%40onrr.gov%7Cbf2b5fd970914e6965f108d95cdbb85b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637642921940007880%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Ip6qvA3Y%2FXOXkJLv5fJfDejfiZUJd61Igv1u52QW258%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cdamion.schulte%40onrr.gov%7Cbf2b5fd970914e6965f108d95cdbb85b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637642921940007880%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wswxtPt2Vfc76UyGh%2BtnKPfbeSF09zVG4y%2B%2FbGQGaZo%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@damionschulte

Great- I just pushed the changes to the live site (https://www.onrr.gov/valuation/IndianOilIBMP.htm)
It sometimes takes up to 30min for the changes to appear live, use Ctrl+F5 to refresh the webpage.

I will close this issue once I see the changes live.

Thanks!

**Comment by cthomasONRR** [comment]
July data made it to the live site. Closing this issue now.

**Comment by damionschulte** [comment]
Awesome thank you!

From: Christine Thomas ***@***.***>
Sent: Wednesday, August 11, 2021 10:08 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] July IBMP Prices (#927)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



July data made it to the live site. Closing this issue now.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F927%23issuecomment-896956032&data=04%7C01%7Cdamion.schulte%40onrr.gov%7Cc5998edc5389407b9a0a08d95ce23b5b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637642950812417137%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qjaV3AoeS%2FbqwQ0odh1NDXcO%2B2kHIV2YEW5eyCBtAFw%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAO4AEPIAQN7XEHIQFZPRLNDT4KN57ANCNFSM5B42U6OA&data=04%7C01%7Cdamion.schulte%40onrr.gov%7Cc5998edc5389407b9a0a08d95ce23b5b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637642950812427092%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4U%2BmgFktoMvPF9Sp8rpV5FTbQXmeqnfHW0VACRMTp6I%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdamion.schulte%40onrr.gov%7Cc5998edc5389407b9a0a08d95ce23b5b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637642950812427092%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tYftVczj2dYdTtwAYpE0s15T9nWt4hBhns2HbsyySDQ%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cdamion.schulte%40onrr.gov%7Cc5998edc5389407b9a0a08d95ce23b5b%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637642950812437045%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7skJ8ZAW4Bss5Zjxs%2Bh3CB5J%2BHWdwMdaeLty6I41t%2BY%3D&reserved=0>.
