### ISSUE TITLE
Recruit participants for onrr.gov study

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#929]

**Comment by cthomasONRR** [comment]
@mcharg Do you have a list of people who have previously participated in the wireframe studies? Should we start by contacting those who indicated they would like to participate in future studies? I also want to avoid people that might not want to participate again. Thanks!

**Comment by cthomasONRR** [comment]
I will work on sending emails out the the following people this week. I'm hoping that since I know them/have worked with them in the past, they might be more responsive.  @mcharg Please let me know if there is an email template that's been used previously, and I will start with that and customize it.

- [ ] Alexis Long
- [ ] Luis Aguilar
- [ ] Jessica Penvose
- [ ] Corey Forgrave
- [ ] Jessica Sheets
- [ ] Amanda Garrison
- [ ] Jennifer Dougherty
- [ ] Janice Lopez
- [ ] Jahed Nabiyar
- [ ] Jodie Peterson

**Comment by Maroyafaied** [comment]
@mcharg @lpgoldstein I think it would be helpful for Christine and the cross trainers to schedule a meeting showing the wireframes , the study plan, and how we've done recruiting & scheduling in the past.

**Comment by mcharg** [comment]
@Maroyafaied I scheduled a meeting.

@cthomasONRR We've done templates for NRRD, but should probably tweak that to create one for onrr.gov.  Here are the NRRD ones. https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/NRRD/User%20Research/Templates?csf=1&web=1&e=aDzfuV

I also pinged Jodie and she said she can give us email addresses for people who have contacted RV, but she's out the rest of the week.  @cthomasONRR Can you follow up with her on that next week?

**Comment by cvojslavek** [comment]
- I checked with Bruce Rumburg to see if it was okay to ask STRAC members for volunteers after my presentation at the STRAC meeting on September 15. He said that would be fine and let him how he can help. 

- Then I asked if he wanted to volunteer and he said yes, but after the STRAC meeting (September 14-16). 

- Bruce mentioned Peter Hanley may be interested too, so I will add him to my list to reach out to as well. 

- My friend Ethan with SSA said he would be willing to volunteer as well. He is blind and would bring a good perspective. @mcharg Would he be a good volunteer and would he be able to view changes to onrr.gov prior to the interview?

**Comment by mcharg** [comment]
@Maroyafaied Do you think we should exclude anyone who participated in stakeholder reviews of the wireframes?  A lot of the people on @cthomasONRR's list participated in the reviews.

**Comment by Maroyafaied** [comment]
@mcharg Yes, I think we should try to avoid interviewing those who were involved in the stakeholders reviews since the wireframes are build based on their feedback, I think it would be best to recruit people that we haven't spoken to already. @cvojslavek Thanks for getting a list of names, if you're friend uses a screen reader than that won't work with the wireframes but it would be good to have their name for a later study.

**Comment by mcharg** [comment]
@cthomasONRR I added a column to the participant spreadsheet indicating which were involved in stakeholder reviews of the wireframes.

**Comment by cthomasONRR** [comment]
OK - I put a strickthrough on the names of those that were involved in the stakeholder reviews. I updated the [following spreadheet](https://teams.microsoft.com/l/file/CF95F231-CAB5-4B62-B409-321AD4633073?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR.gov%2FUser%20Research%2FStudies%2F08_Wireframes%2FParticipant%20list%20.xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a) with a few more names of people who contacted me in RV when I worked there.

**Comment by cthomasONRR** [comment]
@mcharg Here is my draft email. Please let me know if anything should be modified:

SUBJECT: New onrr.gov website - request for feedback

Hi [Name], 

I hope you are all doing well! The Data Display team is working on a new version of onrr.gov and we would love your feedback.

We are planning a study to understand what users think about the format of the updated website, and if it is meeting your needs. We’re conducting short interviews to understand the needs of people who use onrr.gov.

- How long is a session?
     - Only 30 minutes!
- When and where?
     - We conduct our sessions using Microsoft Teams or Webex, so no need to go anywhere, and we can work with your schedule.
- Interested in participating?
     - Please respond to this message with a couple of time slots that work for you during the **weeks** of:
         - **September 13 and September 20**

Your participation will help us make the onrr.gov website better and more easily accessible to everyone. 

If you have any questions, please feel free to ask!

Thanks for your time and participation,

Christine Thomas

**Comment by mcharg** [comment]
@cthomasONRR Looks good!

**Comment by cthomasONRR** [comment]
I sent emails to the following people, with a request for them to participate in an interview:

- [ ] Jessica Sheets
- [ ] Janice Gonzales
- [ ] Kelsey Zabrusky
- [ ] Latisha Williams
- [ ] Forence Vigil
- [ ] Alicia Pterson
- [ ] Matthew Decker
- [ ] Michelle Nichols

**Comment by codyeckstein** [comment]
I work with Alicia, Latisha, and Janice--I'd be happy to sit in on their interviews.

**Comment by codyeckstein** [comment]
Sent emails to Crowheart (hoping for a newer reporter) and Judy at EOG (seasoned reporter),

**Comment by cvojslavek** [comment]
Hi @lpgoldstein @mcharg Should I change anything on this email and meeting invite to Bruce? I'm planning to use the FindTime add-in to find the best time that works with Bruce's schedule and then I can add additional interns and team members as attendees. Would you prefer that I add everyone to vote on the time?
![image.png](https://images.zenhubusercontent.com/612e37e94df0eb7eee8b9988/91ac1890-eb44-4f4a-aa8e-e1cae1420d76)

**Comment by cvojslavek** [comment]
After talking with my husband, here is an example of a possible informal cold recruiting email to send.
Subject: Requesting your expertise

Hey NAME, if your idea of a fun time at work is providing your opinion, never being wrong, and improving the world I have just the initiative that requires your expertise.

ONRR is making a new website to empower, JOB TITLES, like you to, do X, Y, and Z better.

Would it be better to connect for 30 minutes DAY or DAY 2?

Talk soon,
