### ISSUE TITLE
Update Website Information

### ISSUE THREAD

**Issue by mlvanvleet** [ONRR/onrr.gov-site#937]
On our payments page under the Lockbox payment instructions for Ute Indian Tribe the Information needs to change to:

Lockbox Mailing address:                                                                    
Ute Indian Tribe #3
LB 003271
PO Box 35146
Seattle, WA 98124-5146               

There should be no reference to courier information only this payment information. Website Link: https://www.onrr.gov/reportpay/payments.htm                       
Scroo down to Lockbox tribes and Addresses and then select Ute Indian Tribe

![image](https://user-images.githubusercontent.com/89099386/129785468-5ba681a1-1ccd-4762-bfe3-f50cc19185c1.png)

**Comment by cthomasONRR** [comment]
@mlvanvleet 

Could you please verify that I understand:

I need to:
1. Update the mailing address, and
2. Remove everything in the "Courier (delivery) address" section

Thanks,
Christine

**Comment by mlvanvleet** [comment]
Good Morning,

Yes, thank you, address updated and removing the courier address information.


Michelle Van Vleet
Accountant, General Ledger
Bldg 85, Denver Federal Center
Denver, CO 80225
Office of Natural Resources Revenue
(303) 231-3178

"Be the Change you want to see in the world"  Mahatma Gandhi


________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, August 18, 2021 7:52 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Van Vleet, Michelle L ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update Website Information (#937)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@mlvanvleet<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmlvanvleet&data=04%7C01%7Cmichelle.vanvleet%40onrr.gov%7C5dada96439084bd41eec08d9624f9a03%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637648916297251093%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=c4OzABOtAPlXuzQdvGIx089o1W91owQ8i%2F5swGFMopk%3D&reserved=0>

Could you please verify that I understand:

I need to:

  1.  Update the mailing address, and
  2.  Remove everything in the "Courier (delivery) address" section

Thanks,
Christine

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F937%23issuecomment-901133464&data=04%7C01%7Cmichelle.vanvleet%40onrr.gov%7C5dada96439084bd41eec08d9624f9a03%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637648916297261050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9LN33p2TDJMOa3qiycmGhv4GZXPay%2FPKA4HrcPyBPuA%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVHYY6SNWOY6ZN2W5M4CPK3T5O3JBANCNFSM5CKP2YCQ&data=04%7C01%7Cmichelle.vanvleet%40onrr.gov%7C5dada96439084bd41eec08d9624f9a03%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637648916297261050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=le3V%2FTLXFrWG%2FBloCMX6Non8AIE1CTTV3wM5uhKFTY8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmichelle.vanvleet%40onrr.gov%7C5dada96439084bd41eec08d9624f9a03%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637648916297261050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=j2geg%2BsPLcIAgYqjxWfOxjk7Pmeshf5xvCXWOX39pYY%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cmichelle.vanvleet%40onrr.gov%7C5dada96439084bd41eec08d9624f9a03%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637648916297271006%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gULod5fx4wbOiS8ye6N6EZjW1W%2BBDJbJwYaKjsjUBEE%3D&reserved=0>.

**Comment by mlvanvleet** [comment]
Thank you so much! I saw the information has been updated.  Have a great day!

Michelle Van Vleet
Accountant, General Ledger
Bldg 85, Denver Federal Center
Denver, CO 80225
Office of Natural Resources Revenue
(303) 231-3178

"Be the Change you want to see in the world"  Mahatma Gandhi


________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, August 18, 2021 9:31 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Van Vleet, Michelle L ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Update Website Information (#937)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@mlvanvleet<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmlvanvleet&data=04%7C01%7Cmichelle.vanvleet%40onrr.gov%7C33c19084275e4d4145e608d9625d47d2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637648975814108747%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xKWcyumufAhUFeruCtaOxYBPjs6gvuJPzzVKUwuxIM0%3D&reserved=0>

Great, thanks! I moved these changes to the live site. It usually takes around 30min for the live site to update, please sue "Ctrl+F5" to update the page.

I will close this issue once the live site updates.

Thanks,
Christine

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F937%23issuecomment-901212561&data=04%7C01%7Cmichelle.vanvleet%40onrr.gov%7C33c19084275e4d4145e608d9625d47d2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637648975814118607%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nWw91S1LbDKzGU44a1Yu9eDO8IWLlXMnxrzu3H0qoEY%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVHYY6X55XB43S2GNLFV523T5PG33ANCNFSM5CKP2YCQ&data=04%7C01%7Cmichelle.vanvleet%40onrr.gov%7C33c19084275e4d4145e608d9625d47d2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637648975814118607%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nKkzAb6T7vAoAcUuB2A2U7zlMO16KpILTehtviZAeiM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmichelle.vanvleet%40onrr.gov%7C33c19084275e4d4145e608d9625d47d2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637648975814128571%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WFeenmkwfAqF40cevqfKzGkdUhfzBFHiPf9GVaswvCM%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cmichelle.vanvleet%40onrr.gov%7C33c19084275e4d4145e608d9625d47d2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637648975814128571%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JOZ47QOAwbEfkMPwR1kZlEToLYqHiTtlJm2K91liHbk%3D&reserved=0>.
