### ISSUE TITLE
Event Calendar 

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#938]
Please delete the July event: "71st ANNUAL INDIAN HILLS POWWOW, OKLAHOMA CITY from the Event Calendar on the Allottee Assistance page.

**Comment by cthomasONRR** [comment]
@Toddsand21 

Good morning, this entry is deleted from the dev site (http://2017onrr/events.htm).
Please review and give us your approval for this change to go live.

Thanks!
Christine

**Comment by Toddsand21** [comment]
Yes it looks fine. Thanks!  Do you think we would have room to start adding September events before we delete August's events?

**Comment by cthomasONRR** [comment]
@Toddsand21

Great- I just made this change live. It can take up to 30min for it to appear on the live site, please use "Ctrl+F5" to refresh.

I believe we have room to add in September events. Please send them over and I will add them.

Thanks,
Christine

**Comment by Toddsand21** [comment]
Is it a new Issue?

**Comment by cthomasONRR** [comment]
Yes, let's make it a new issue. This helps our metrics be more accurate :) I will close out this issue and look for your new one. Thanks!

**Comment by Toddsand21** [comment]
That will be great. Thanks!
