### ISSUE TITLE
Please upload ONRR form 4425 as follows:

### ISSUE THREAD

**Issue by luisaguilar-onrrgov** [ONRR/onrr.gov-site#939]
Please note that the attached PDF form is 508 compliant.
Under the following link: https://www.onrr.gov/Laws_R_D/FRNotices/ICR0107.htm, please replace and update as follows:

Change the (Expires April 30, 2021) to (Expires July 31, 2024)
Under the “Forms” section, replace the “ONRR-4425 and Instructions” PDF with the attached PDF.
Under the following link: https://www.onrr.gov/reportpay/Forms/index.htm, please replace as follows:
Below the “Designation Form for Royalty Payment Responsibility”, please replace the “Form 4425” PDF with the attached PDF.
Please let me know if you have any questions.
ONRR Form 4425 and instr_508 Compliant_08.10.2021.pdf

**Comment by cthomasONRR** [comment]
Luis emailed me the PDF [ONRR Form 4425](https://app.zenhub.com/files/210892300/520c671a-318b-434e-a3dc-8f95e9ea69f2/download)

@luisaguilar-onrr The updated Form 4425 is now on the dev site (http://2017onrr/Laws_R_D/FRNotices/ICR0107.htm). Please review and give us your approval for the changes to go live.

Thanks!
Christine

**Comment by luisaguilar-onrrgov** [comment]
Approved... Thanks.

**Comment by cthomasONRR** [comment]
@luisaguilar-onrrgov Great! I made the updates to the live site, so those should appear in about 30min. I will close this issue once I see the live site has updated. Thanks!

**Comment by cthomasONRR** [comment]
Live site updated- closing issue.
