### ISSUE TITLE
Update file

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#94]
Good morning, please see attached to be used to update the FS Federal Team contact sheet on ONRR.gov. The URL is https://www.onrr.gov/ReportPay/payments.htm [https://www.onrr.gov/ReportPay/payments.htm]

Below is a screenshot of the site and the document being referred to.

Please let me know if you need any additional information.
![image001](https://user-images.githubusercontent.com/30806839/78585197-6dc5b880-7807-11ea-93a4-a9f9fa84e1eb.png)
[finserAssign.pdf](https://github.com/ONRR/onrr.gov-site/files/4439793/finserAssign.pdf)

**Comment by jennmalcolm** [comment]
@Maroyafaied I've forwarded the email I got to the shared box for follow up.

**Comment by Maroyafaied** [comment]
@jennmalcolm I made the update and send it for review and also let the requester know about Github. 
http://2017onrr/ReportPay/payments.htm

**Comment by jennmalcolm** [comment]
Thanks @Maroyafaied the requester has reviewed and approved, so this can go live.

**Comment by Maroyafaied** [comment]
It's live. Thanks
