### ISSUE TITLE
EVENT CALENDAR   (Please add the following to the ONRR Outreach Event Calendar under Allottee Assistance Pg)

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#941]
**KAULEY VIRTUAL OUTREACH MEETING**
SEPTEMBER 15, 2021

EVENT INFORMATION
LOCATION: By Telephone
TIME: 1:00 PM – 2:00 PM CST

DESCRIPTION: Meeting will be a Call-in Meeting to hear a presentation and updates from the ONRR Outreach Office  Representatives from the BLM, BTFA, and BIA will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust properties.  Owners will have an opportunity to ask questions for the representatives of the four agencies during the Q&A session.

WHO SHOULD ATTEND: IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Southern Plains Region in Oklahoma.
OTHER INFORMATION: To reserve a space and get a passcode for this meeting please contact the ONRR OKC Outreach office at (800)354-7015. The OKC Outreach office hours are Monday- Friday from 7:30 am-5:00 pm.

_EVENT CONTACT
NAME: ONRR OKC Outreach Office,  PHONE: Toll Free (800) 354-7015
EMAIL_: onrroutreachokc@onrr.gov

**UTE MOUNTAIN UTE, AND SOUTHERN UTE VIRTUAL OUTREACH** 
SEPTEMBER 22, 2021 

EVENT INFORMATION
LOCATION:  By Telephone 
TIME: 10:00 AM- 11:00 AM MST 

DESCRIPTION Representatives from the Office of Natural Resources Revenue will host a Question and Answer session by phone for Indian Mineral Owners and Trust Property Owners regarding their Indian Oil & Gas leases, IIM Accounts, and Indian Trust Properties. Representatives from the Bureau of Land Management, Bureau of Indian Affairs, and Bureau of Trust Funds Administration are invited to be in attendance to answer questions. 

WHO SHOULD ATTEND:  IIM account holders, Indian mineral owners, and Indian trust property owners in the Towaoc and Ignacio areas in Colorado. 
OTHER INFORMATION: To attend the virtual outreach session, please contact the ONRR Denver Outreach office at (800) 982-3226, for the call-in number and passcode.  The Denver Outreach office hours are Monday-Friday 7:30am-4:00pm. 

_EVENT CONTACT:  
NAME: ONRR Denver Outreach Office, PHONE: Toll Free (800) 982-3226, EMAIL:_onrroutreachdenver@onrr.gov

**SHAWNEE VIRTUAL OUTREACH**
SEPTEMBER 22,2021
EVENT INFORMATION
LOCATION: By Telephone
TIME: 1:00 PM– 2:00 PM CST

DESCRIPTION: Meeting will be a Call-in Meeting to hear a presentation and updates from the ONRR Outreach Office  Representatives from the BLM, BTFM, and BIA will also be on the call to discuss topics regarding Indian Oil & Gas leases, IIM Accounts and Indian Trust properties.  Owners will have an opportunity to ask questions for the representatives of the four agencies during the Q&A session.

WHO SHOULD ATTEND: IIM account holders, Indian mineral owners, and other Indian Trust property owners in the Shawnee Agency Area, Southern Plains Region in Oklahoma.
OTHER INFORMATION: To reserve a space and get the call-in number and passcode for this meeting you may contact the ONRR OKC Outreach office at (800) 354-7015. The OKC Outreach office hours are Monday- Friday, 7:30 am-5:00 pm.

_EVENT CONTACT
NAME: ONRR OKC Outreach Office, PHONE: Toll Free (800) 354-7015
EMAIL_: onrroutreachokc@onrr.gov

**Comment by cthomasONRR** [comment]
@toddsand21

I have these 3 new entries on the dev site (http://2017onrr/events.htm).
Please review and give us approval to make these changes live.

Thanks!
Christine

**Comment by Toddsand21** [comment]
1) In the first sentence of the Kauley Meeting after the Description:  Please put a period after it reads "ONRR Outreach Office.    2)In the Shawnee Meeting: after Description: Change the "M" to and an "A" where it reads: Representatives from the BLM, BTFM (change to"BTFA" )
Everything else looks fine.

**Comment by cthomasONRR** [comment]
Great! I made these changes to the dev site (http://2017onrr/events.htm). Please do one more look-though, and with your approval, I will go live. Thanks!

**Comment by Toddsand21** [comment]
It looks fine!  Thanks.

**Comment by cthomasONRR** [comment]
Great! I just moved the changes over to the live site. I will close this issue once I see the changes go live.

**Comment by cthomasONRR** [comment]
Updates are now live. Closing issue.

**Comment by Toddsand21** [comment]
What is it I hit to refresh it or update the website?  F11 or what?

**Comment by cthomasONRR** [comment]
It's "Ctrl+F5" I see it live (https://www.onrr.gov/events.htm).
