### ISSUE TITLE
Remove Letter from onrr.gov

### ISSUE THREAD

**Issue by cmathers1** [ONRR/onrr.gov-site#942]
Good morning, 

Please remove the attached Dear Reporter Letter from onrr.gov. Thank you!
[970926.pdf](https://github.com/ONRR/onrr.gov-site/files/7008939/970926.pdf)

**Comment by cthomasONRR** [comment]
Hi Christina,

I removed this Dear Reporter Letter (9/26/1997) from the dev and live sites. I'll close this issue once I see it removed from the live site.

Thanks!
Christine

**Comment by cmathers1** [comment]
Thank you, Christine!  Have a great day!

Sincerely,

Christina

Christina Mathers
Staff Assistant
Director/Deputy Director's Office
Office of Natural Resources Revenue
6th Avenue and Kipling Street Bldg. 85
Denver, Colorado 80225
Phone:  303-231-3429
Cell: 303-503-1315
________________________________
From: Christine Thomas ***@***.***>
Sent: Wednesday, August 18, 2021 1:31 PM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Mathers, Christina ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Remove Letter from onrr.gov (#942)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi Christina,

I removed this Dear Reporter Letter (9/26/1997) from the dev and live sites. I'll close this issue once I see it removed from the live site.

Thanks!
Christine

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F942%23issuecomment-901374445&data=04%7C01%7Cchristina.mathers%40onrr.gov%7Ca77e0b714ac84e85bd7508d9627ed061%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637649119082768112%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4EaEbKIik75mAVwXN4elioki6hkjGgcA3Z2Qc9XmEBM%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAU5GF7XSE53HUS5QNNT3DHLT5QDBJANCNFSM5CMOXDBA&data=04%7C01%7Cchristina.mathers%40onrr.gov%7Ca77e0b714ac84e85bd7508d9627ed061%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637649119082778068%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Gnm4pB6OE8aUTEY%2BqRBQYsrVdQ3dcaNUTA09%2FHs3rjg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cchristina.mathers%40onrr.gov%7Ca77e0b714ac84e85bd7508d9627ed061%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637649119082788025%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MBibIP64Kpq%2Bpy2vDJODqTexqeD3Z5uDsC7QBDkz4yQ%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cchristina.mathers%40onrr.gov%7Ca77e0b714ac84e85bd7508d9627ed061%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637649119082788025%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LiuH4xKTHRpnx8fdZkNfAOdS%2FkaOWKjcgpIq5EY73sU%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
PDF removed from the live site. Closing this issue.
