### ISSUE TITLE
508 compliance upload for COS

### ISSUE THREAD

**Issue by mentastc** [ONRR/onrr.gov-site#946]
Hi guys!

Attached are the first 62 documents from the 508 compliance file I'll complete the remaining files when I return from paternity leave. I've also updated  the share xls for tracking. 

- [x] [20110620.pdf](https://github.com/ONRR/onrr.gov-site/files/7031727/20110620.pdf)
- [x] [20110720.pdf](https://github.com/ONRR/onrr.gov-site/files/7031728/20110720.pdf)
- [x] [20110913.pdf](https://github.com/ONRR/onrr.gov-site/files/7031729/20110913.pdf)
- [x] [20110913a.pdf](https://github.com/ONRR/onrr.gov-site/files/7031730/20110913a.pdf)
- [x] [20110916.pdf](https://github.com/ONRR/onrr.gov-site/files/7031731/20110916.pdf)
- [x] [20120222.pdf](https://github.com/ONRR/onrr.gov-site/files/7031732/20120222.pdf)
- [x] [20120224.pdf](https://github.com/ONRR/onrr.gov-site/files/7031733/20120224.pdf)
- [x] [20120307.pdf](https://github.com/ONRR/onrr.gov-site/files/7031734/20120307.pdf)
- [x] [20120307a.pdf](https://github.com/ONRR/onrr.gov-site/files/7031735/20120307a.pdf)
- [x] [20120312.pdf](https://github.com/ONRR/onrr.gov-site/files/7031736/20120312.pdf)
- [x] [20120313.pdf](https://github.com/ONRR/onrr.gov-site/files/7031737/20120313.pdf)
- [x] [20120316.pdf](https://github.com/ONRR/onrr.gov-site/files/7031738/20120316.pdf)
- [x] [20120326.pdf](https://github.com/ONRR/onrr.gov-site/files/7031739/20120326.pdf)
- [x] [20120329.pdf](https://github.com/ONRR/onrr.gov-site/files/7031740/20120329.pdf)
- [x] [20120405.pdf](https://github.com/ONRR/onrr.gov-site/files/7031741/20120405.pdf)
- [x] [20120416.pdf](https://github.com/ONRR/onrr.gov-site/files/7031742/20120416.pdf)
- [x] [20120420.pdf](https://github.com/ONRR/onrr.gov-site/files/7031743/20120420.pdf)
- [x] [20120430.pdf](https://github.com/ONRR/onrr.gov-site/files/7031744/20120430.pdf)
- [x] [20120509.pdf](https://github.com/ONRR/onrr.gov-site/files/7031745/20120509.pdf)
- [x] [20120703.pdf](https://github.com/ONRR/onrr.gov-site/files/7031746/20120703.pdf)
- [x] [20120711.pdf](https://github.com/ONRR/onrr.gov-site/files/7031747/20120711.pdf)
- [x] [20120718.pdf](https://github.com/ONRR/onrr.gov-site/files/7031748/20120718.pdf)
- [x] [20120726.pdf](https://github.com/ONRR/onrr.gov-site/files/7031749/20120726.pdf)
- [x] [20120822EITI.pdf](https://github.com/ONRR/onrr.gov-site/files/7031750/20120822EITI.pdf)
- [x] [20120823.pdf](https://github.com/ONRR/onrr.gov-site/files/7031751/20120823.pdf)
- [x] [20121206.pdf](https://github.com/ONRR/onrr.gov-site/files/7031752/20121206.pdf)
- [x] [20121206-disbursments.pdf](https://github.com/ONRR/onrr.gov-site/files/7031753/20121206-disbursments.pdf)
- [x] [20130104.pdf](https://github.com/ONRR/onrr.gov-site/files/7031755/20130104.pdf)
- [x] [20130301.pdf](https://github.com/ONRR/onrr.gov-site/files/7031756/20130301.pdf)
- [x] [20130402.pdf](https://github.com/ONRR/onrr.gov-site/files/7031758/20130402.pdf)
- [x] [20130620.pdf](https://github.com/ONRR/onrr.gov-site/files/7031759/20130620.pdf)
- [x] [20130708.pdf](https://github.com/ONRR/onrr.gov-site/files/7031760/20130708.pdf)
- [x] [20130812.pdf](https://github.com/ONRR/onrr.gov-site/files/7031761/20130812.pdf)
- [x] [20130812a.pdf](https://github.com/ONRR/onrr.gov-site/files/7031762/20130812a.pdf)
- [x] [20130819.pdf](https://github.com/ONRR/onrr.gov-site/files/7031763/20130819.pdf)
- [x] [20130829.pdf](https://github.com/ONRR/onrr.gov-site/files/7031764/20130829.pdf)
- [x] [20130916.pdf](https://github.com/ONRR/onrr.gov-site/files/7031765/20130916.pdf)
- [x] [20131013.pdf](https://github.com/ONRR/onrr.gov-site/files/7031766/20131013.pdf)
- [x] [20131021.pdf](https://github.com/ONRR/onrr.gov-site/files/7031767/20131021.pdf)
- [x] [20131022.pdf](https://github.com/ONRR/onrr.gov-site/files/7031768/20131022.pdf)
- [x] [20131022a.pdf](https://github.com/ONRR/onrr.gov-site/files/7031769/20131022a.pdf)
- [x] [20131113.pdf](https://github.com/ONRR/onrr.gov-site/files/7031770/20131113.pdf)
- [x] [20131119.pdf](https://github.com/ONRR/onrr.gov-site/files/7031771/20131119.pdf)
- [x] [20131119a.pdf](https://github.com/ONRR/onrr.gov-site/files/7031772/20131119a.pdf)
- [x] [FY2011StateDisbursements.pdf](https://github.com/ONRR/onrr.gov-site/files/7031773/FY2011StateDisbursements.pdf)
- [x] [GOMESAFY2011Final.pdf](https://github.com/ONRR/onrr.gov-site/files/7031774/GOMESAFY2011Final.pdf)
- [x] [ONRR_Dynamic_Offshore_Civil_Penalty.pdf](https://github.com/ONRR/onrr.gov-site/files/7031775/ONRR_Dynamic_Offshore_Civil_Penalty.pdf)
- [x] [ONRR_Peer_Review_Successful_11-02-11.pdf](https://github.com/ONRR/onrr.gov-site/files/7031776/ONRR_Peer_Review_Successful_11-02-11.pdf)
- [x] [OXY_USA_Civil_Penalty.pdf](https://github.com/ONRR/onrr.gov-site/files/7031777/OXY_USA_Civil_Penalty.pdf)
- [x] [01-12-12BakkenIndianRevenuesrelease.pdf](https://github.com/ONRR/onrr.gov-site/files/7031778/01-12-12BakkenIndianRevenuesrelease.pdf)
- [x] [2-1_eCommerce_press_release.pdf](https://github.com/ONRR/onrr.gov-site/files/7031780/2-1_eCommerce_press_release.pdf)
- [x] [8-11EnergyResourcesCivilPenalty.pdf](https://github.com/ONRR/onrr.gov-site/files/7031781/8-11EnergyResourcesCivilPenalty.pdf)
- [x] [11BillionMineralsrevenuesRevised_v2.pdf](https://github.com/ONRR/onrr.gov-site/files/7031782/11BillionMineralsrevenuesRevised_v2.pdf)
- [x] [12-11ShellSettlementPressRelease.pdf](https://github.com/ONRR/onrr.gov-site/files/7031783/12-11ShellSettlementPressRelease.pdf)
- [x] [363_CIV.pdf](https://github.com/ONRR/onrr.gov-site/files/7031784/363_CIV.pdf)
- [x] [20101015.pdf](https://github.com/ONRR/onrr.gov-site/files/7031785/20101015.pdf)
- [x] [20101104a.pdf](https://github.com/ONRR/onrr.gov-site/files/7031786/20101104a.pdf)
- [x] [20101104b.pdf](https://github.com/ONRR/onrr.gov-site/files/7031787/20101104b.pdf)
- [x] [20110128.pdf](https://github.com/ONRR/onrr.gov-site/files/7031788/20110128.pdf)
- [x] [20110510.pdf](https://github.com/ONRR/onrr.gov-site/files/7031789/20110510.pdf)
- [x] [20110524.pdf](https://github.com/ONRR/onrr.gov-site/files/7031790/20110524.pdf)
- [x] [20110526.pdf](https://github.com/ONRR/onrr.gov-site/files/7031791/20110526.pdf)

Thanks,

Chris

**Comment by Maroyafaied** [comment]
@mcharg @cthomasONRR I've assigned this to next sprint, I'm thinking we can have the cross trainers assist with this one.

**Comment by cthomasONRR** [comment]
@Maroyafaied Sounds good- I start start working on this first thing next week. (Taking this Wednesday-Friday off.)

**Comment by cthomasONRR** [comment]
I'm updating these in groups of 10... the first group of 10 is updated in dev and live sites, and accessibility tracking spreadsheet is updated.
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/a6957ff4-22b6-4e60-ab6c-73dac658accc)

**Comment by cthomasONRR** [comment]
Documents 11-12 are updated in dev and live sites, and accessibility tracking spreadsheet is updated.
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/b300ad9d-d1d9-4d0d-a10f-de2b651a7af7)

**Comment by cthomasONRR** [comment]
Documents 21-30 are updated in dev and live sites, and accessibility tracking spreadsheet is updated.
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/c1d1d3e6-44a1-49b2-9013-abe30d0bc7e1)

Two documents needed the title updated. I did that, saved a new version, and uploaded this new version:
- [ ] [20130104](https://app.zenhub.com/files/210892300/f49be870-d9b4-4a7b-99ed-2e1ab6366c2c/download)
- [ ] [20120718](https://app.zenhub.com/files/210892300/1120c1a3-97b3-4266-8491-28d157d5a715/download)

**Comment by cthomasONRR** [comment]
Documents 31-40 are updated in dev and live sites, and accessibility tracking spreadsheet is updated.
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/5869ca3d-ed83-4408-b555-53b1d96c156e)

**Comment by cthomasONRR** [comment]
Documents 41-50 are updated in dev and live sites, and accessibility tracking spreadsheet is updated.
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/c8a4d176-6d14-4ae0-a5eb-8c5c8051f82c)

3 docs needed table summaries added. I added table summaries, saved an updated version, and uploaded this new version:
- [ ] [GOMESAFY2011Final](https://app.zenhub.com/files/210892300/85f892e4-6a9c-43b6-b67e-26b5e2e0da9e/download)
- [ ] [FY2011StateDistributions](https://app.zenhub.com/files/210892300/eef4ea4f-47cc-44d5-92e1-afd2b16582fc/download)
- [ ] [20131119](https://app.zenhub.com/files/210892300/f1b6873b-c638-4ab3-8022-3261fcf0a520/download)

**Comment by mcharg** [comment]
@cthomasONRR Do you need me to double check any of the links?

**Comment by Maroyafaied** [comment]
@mcharg please do review the links since Chris won't be doing a review. Thanks

**Comment by cthomasONRR** [comment]
Documents 51-64 are updated in dev and live sites, and accessibility tracking spreadsheet is updated.
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/cc02e78a-5c51-4f9a-8696-7f485367c4a6)

1 docs needed a table summary added. I added table summary, saved an updated version, and uploaded this new version:
- [ ] [20101104a](https://app.zenhub.com/files/210892300/ba8222b2-d08c-4010-8d65-3d3a8f3c500d/download)

@mcharg these are ready for your review now!

**Comment by mcharg** [comment]
Looks good.
