### ISSUE TITLE
ONRR.gov Site Map Update Sections 3.0 & 4.0 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#948]
**3.0 References** 

- [x] 3.0 References (Home)
- [x]  3.1 Statutes 
- [x]  3.2 Rules & Regulations 
- [x]  3.3 Federal Register Notices 
- [x]  3.4 Information Collection Requests
- [x]  3.5 Forms 
- [x]  3.5.1 System Access
- [x]  3.5.2 Oil & Gas Production Reporting
- [x]  3.5.3 Oil & Gas Revenue Reporting
- [x]  3.5.4 Solid Mineral Reporting
- [x]  3.5.5 Geothermal Reporting
- [x]  3.5.6 Appeal Surety
- [x]  3.6 Reference Lists and Codes 
- [x]  3.7 Handbooks 
- [x]    3.4.1 Minerals Revenue Reporter Handbook 
- [x]    3.4.2 Minerals Production Handbook
- [x]    3.4.3 Solid Minerals Reporter Handbook 
- [x]    3.4.4 Geothermal Payor Handbook - Class 1 Leases
- [x]    3.4.5 Geothermal Payor Handbook - Class 2 & 3 Leases 
- [x]    3.4.6 Indian Payor Handbooks 
- [x]      3.4.6.1.1.1 Chapter 1 
- [x]      3.4.6.1.1.2 Chapter 2
- [ ]      3.4.6.1.1.3 Chapter 3 
- [x] 3.8 Valuation & Pricing 
- [x]    3.1.1 How Valuation Works 
- [x]    3.1.2 Pricing 
- [x]    3.1.3 Unbundling 
- [x]    3.1.4 Valuation Regulations 
- [x]    3.1.5 Valuation Examples 
- [x]      3.1.4.1 2016 Valuation Rule Federal Processed Gas Reporting Example 
- [x]      3.1.4.2 Federal Percent-of-Proceeds Contract Reporting Example
- [x]      3.1.4.2.6 Indian Valuation Information 
- [x]      3.1.6 Contacts 
- [x] 3.9 Reporter Training 
- [x]    3.3.4.1 OGOR Training Videos
- [x]    3.3.4.3 Form 2014 Training Videos 
- [x]    3.2.1 Cross-Referenced Lease & Agreement Number Lists 
- [x]    3.2.2 Production Reporting References 
- [ ] 

**4.0 Paying** 

- [x] 4.0 Paying (Home) 
- [x] 4.1 Payment Options 
- [x] 4.2 Jointly Owned Lease Payments 
- [x] 4.3 Late Payment Interest 
- [x] 4.4 Unpaid Debt
- [x] 4.5 Contacts

**Comment by daniel-coleman-1** [comment]
https://qmcq5k.axshare.com/#id=e1wh3o&p=home_v3

**Comment by daniel-coleman-1** [comment]
@mcharg Section 3.0 is ready for your review

**Comment by mcharg** [comment]
@daniel-coleman-1 I reviewed section 3.0.

**Comment by daniel-coleman-1** [comment]
@mcharg Section 4.0 is ready for your review

**Comment by mcharg** [comment]
@daniel-coleman-1 I took a pass back through 3.0 and through 4.0.  Several pages of 4.0 have nothing on them (4.2, 4.3, and 4.4) and a few sections of 4.1 need significant updates to match the wireframe - it looks like you left what was already there, which has changed significantly.

**Comment by daniel-coleman-1** [comment]
@mcharg Just updated, could you take another look?

**Comment by mcharg** [comment]
@mcharg The missing pages are now there - I took a look at those.  You can go through and see if any of my other comments have been addressed.  I've already spent an hour reviewing this morning and have my own work to do.

**Comment by daniel-coleman-1** [comment]
@mcharg thanks!

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 Please make sure the latest version is updated before posting for review so we're not wasting time and also make sure each section is matching the wireframes. At this point, reviewing should go pretty quickly. Thanks!

**Comment by daniel-coleman-1** [comment]
@Maroyafaied roger that, will do!

**Comment by daniel-coleman-1** [comment]
@mcharg and @Maroyafaied 

I've reviewed and edited through 3.0 and 4.0, just took another look at 4.0 and made some updates.  4.0 should be good to go.

**Comment by mcharg** [comment]
@daniel-coleman-1 I'll take a look in the morning.

**Comment by mcharg** [comment]
@daniel-coleman-1 I went back through and there's another round of comments.  There were also a number that you had marked resolved that hadn't been resolved.  I noted those with a comment when unresolving.

**Comment by Maroyafaied** [comment]
@mcharg can you create a checklist for things you look for when reviewing so @daniel-coleman-1 can use when he does his own review.  Thanks

**Comment by mcharg** [comment]
Checklist:

- [ ] Sitemap reflects what's in the wireframe.
- [ ] Ensure the correct document or page type is reflected in the coloring or line styles.
- [ ] All coloring and line styles match the key.
- [ ] Numbering is accurate.
- [ ] Numbering that refers to other pages is accurate (check to make sure section numbers for those haven't changed).

**Comment by daniel-coleman-1** [comment]
@mcharg is it possible to make those images of the handbooks interactive?  I can't interact with the pages so don't know where links go, what they contain etc.

**Comment by mcharg** [comment]
@daniel-coleman-1 Use what's on the live site.
https://www.onrr.gov/reportpay/Handbooks/index.htm

**Comment by daniel-coleman-1** [comment]
Updated and all issues resolved, @Maroyafaied I think this one is good to close once you've reviewed it.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I'll review this tomorrow if I log on, otherwise I'll review Monday morning. Thanks

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I reviewed, I added comments mainly in the Mineral Revenue Handbook and the Indian Payor handbook sections.  Please address the comments before closing this issue. Thanks

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I did a quick review on the Indian handbook and left comments, some things were duplicated and a few numbers were wrong. Thanks 

![image](https://user-images.githubusercontent.com/40175688/133148829-901333b9-3321-43aa-98f2-9c3b74216c42.png)
![image](https://user-images.githubusercontent.com/40175688/133148969-6100d5c5-a973-4727-b363-3dd9014c02b8.png)

**Comment by daniel-coleman-1** [comment]
@Maroyafaied thanks for catching that, I've resolved those.
