### ISSUE TITLE
Refine valuation equation

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#949]

**Comment by mcharg** [comment]
@jpetersononrr and Jahed Nabiyar are the ones from RV to include in this discussion.

**Comment by mcharg** [comment]
Added @jkwonatx since he's reviewing the user research plan to incorporate the equation.

RV and RRM should be meeting to come up with a final equation before we test.

**Comment by jkwonatx** [comment]
@mcharg I added comments to the research plan for review.

**Comment by mcharg** [comment]
@jkwonatx Great! I made some revisions based on your comments.

**Comment by mcharg** [comment]
RV and RRM met yesterday and they hope to have an update to us this afternoon.

**Comment by mcharg** [comment]
Jodie said they sent the updates to the RRM folks and gave them until end of day today to provide feedback.  Then she'll get it to me, so I can update the prototype tomorrow, so it's ready to test on Monday.

**Comment by mcharg** [comment]
Sent to Jodie, Jahed, Megan, and Gina for review.
https://qmcq5k.axshare.com/#id=l9inb4&p=valuation___pricing
