### ISSUE TITLE
March Indian Oil IBMP prices on onrr.gov

### ISSUE THREAD

**Issue by jboroos** [ONRR/onrr.gov-site#96]
Can you please update the Indian Oil IBMP price page (https://www.onrr.gov/Valuation/IndianOilIBMP.htm) with the March prices?  These prices are in the IBMP tab of the "Data for ONRR.gov" spreadsheet on OneDrive.  Let me know if you have issues accessing the file.

Please update our development site (http://2017onrr/Valuation/IndianOilIBMP.htm) and let me know so I can review them before they go public.

Thanks!  - @jboroos, @sudarr

**Comment by lpgoldstein** [comment]
@jennmalcolm @jboroos This is ready for your review http://2017onrr/Valuation/IndianOilIBMP.htm

**Comment by jboroos** [comment]
Thank you @lpgoldstein.  This looks good to me.  @jennmalcolm @sudarr

**Comment by jennmalcolm** [comment]
Thanks, @jboroos. The prices are live now.
