### ISSUE TITLE
Re-write intro paragraph on onrresource for our team

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#960]
@daniel-coleman-1 can you rewrite this paragraph to be simpler and take out what's not relevant and add something about onrr.gov. Carrie is making changes to IDM's page and asked each team to provide 1-3 sentences along with 1-2 bullet points with important info in the intro page. 

![image](https://user-images.githubusercontent.com/40175688/131412280-c2fcdfb7-530c-4779-b0a3-8eddaf35174d.png)

**Comment by mcharg** [comment]
We should also add a link to the blog.

**Comment by daniel-coleman-1** [comment]
@Maroyafaied what do you think about this?  I know we are supposed to only have one paragraph but I like it in two paragraphs, the first paragraph describing the What and the second paragraph describing the How.

Grade level is 15, I'm going to revisit the verbiage tomorrow to try and simplify.

https://teams.microsoft.com/l/file/?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp-my.sharepoint.com%2Fpersonal%2Fcolemanw_mms_gov%2FDocuments%2FMicrosoft%2520Teams%2520Chat%2520Files%2FD3paragraph.docx&serviceName=recent

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 the link is not opening for me.

**Comment by daniel-coleman-1** [comment]
@Maroyafaied how about this one?

https://teams.microsoft.com/l/file/?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp-my.sharepoint.com%2Fpersonal%2Fcolemanw_mms_gov%2FDocuments%2FMicrosoft%2520Teams%2520Chat%2520Files%2FD3paragraph.docx&serviceName=recent

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 No it didn't work, are you saving it in the shared drive? I've been having computer issues so I'll try again in tomorrow morning.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 it's not opening for me still, I tried looking for it in the shared folder and I couldn't find it. Can you put it in the content folder here https://doimspp-my.sharepoint.com/personal/mchargs_mms_gov/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fmchargs%5Fmms%5Fgov%2FDocuments%2FNRRD%20Portal%2FContent

**Comment by daniel-coleman-1** [comment]
How's this:
https://doimspp-my.sharepoint.com/:w:/g/personal/mchargs_mms_gov/ER9ZZXYu3yJCnQSkNE3Xww0BcVzagl6HoIyxuVMRoFkEKg?e=EfvRzy

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 Yes that opened for me, I'll review today. Thanks

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I added my comments.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I made changes in the document, if it looks good to you  then I'll send it to Carrie. Thanks

The Open Data, Design, and Development team manages ONRR’s public websites using agile project management methodology and user-centered design process.  The Natural Resources Revenue Data website publicly displays timely and useful data about how the government manages federal energy and mineral resources, revenue, and disbursements. This informs policy debates and raises public awareness. 

 The onrr.gov website delivers trusted and easy to use information and customer service. This enables companies who lease federal and Indian lands to accurately report production and pay revenue due. 

Open Data, Design, and Development are responsible for maintaining: 

The Natural Resources Revenue Data website (referred to as NRRD) 

The Office of Natural Resources Revenue website  

Team’s blog 

These sites are managed in accordance with the 21st Century Integrated Digital Experience Act (IDEA) and the Open, Public, Electronic, and Necessary (OPEN) Government Data Act.

**Comment by Maroyafaied** [comment]
Send to Carrie
