### ISSUE TITLE
Upload Content in CMS - About Page

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#963]
Please put your name on the section you will update

- [x] About ONRR home @cthomasONRR 
- [ ] Public Affairs - @Maroyafaied 
- [ ] Organization & Leadership @cthomasONRR 
- [ ] Office Locations @daniel-coleman-1 
- [x] Employment @mcharg 
- [ ] Engagement @daniel-coleman-1
- [ ] Interagency Coordination - @mcharg 
- [x] Freedom of Information Act (FOIA) @cthomasONRR 
- [ ] Anti-Harassment Program - @daniel-coleman-1 
- [x] Contact Us @mcharg

**Comment by daniel-coleman-1** [comment]
@mcharg I only have two, may I steal one from you?

**Comment by mcharg** [comment]
@daniel-coleman-1 I figured Jerome already did Employment, so that one just needs a sanity check with the wireframes and Contact Us needs to wait for the accordion component for most of the page, so I'll just be moving over intro copy.

**Comment by cthomasONRR** [comment]
I would like to do at least one... I'm in a BPR meeting and trying to focus on that this morning...

**Comment by mcharg** [comment]
@cthomasONRR There are two left for you.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 you can have my anti-harassments section, feel free to remove my name.

**Comment by daniel-coleman-1** [comment]
@Maroyafaied done, thanks!

**Comment by mcharg** [comment]
I gave @cthomasONRR Organization & Leadership, since she didn't have any with tabs.

**Comment by cthomasONRR** [comment]
I completed the 'About ONRR home' page - there was no way for me to imbed links, and the image under 'History' is not appearing on the dev site (https://dev-onrr-frontend.app.cloud.gov/about-onrr).

**Comment by cthomasONRR** [comment]
I completed the 'FOIA' page. There was no way for me to imbed links, so I will need to go back and do that once we're able to. I also need to figure out how to make 2 columns so the 'Contact' information isn't at the bottom.

**Comment by cthomasONRR** [comment]
I'm not able to complete the 'Organization & Leadership' page because the tab nesting functionality is not yet ready for us to use.

**Comment by daniel-coleman-1** [comment]
Anti-Harassment Program is good to go (https://qmcq5k.axshare.com/#id=l88jo0&p=anti-harassment_program)

Engagement needs the tab nesting function, content card components and a table component.
Office locations needs content card components.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 The anti-harassment page is not showing on the dev site, the content that I added in that page a while ago needs to be moved to the page builder box for it to show in dev.  https://dev-onrr-frontend.app.cloud.gov/about-onrr/anti-harassment

**Comment by Maroyafaied** [comment]
I did what I could on the Public Affairs page while page builder was working. https://dev-onrr-frontend.app.cloud.gov/about-onrr/public-affairs

**Comment by mcharg** [comment]
Got as far as I could with Employment and Contact Us.  Created #1010 for issues with tabs that stopped me on Interagency Coordination.

**Comment by Maroyafaied** [comment]
will need to evaluate grape js vs editor js.
