### ISSUE TITLE
Review content audit and create issues 

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#97]

**Comment by Maroyafaied** [comment]
https://doimspp-my.sharepoint.com/personal/mchargs_mms_gov/_layouts/15/onedrive.aspx?sortField=LinkFilename&isAscending=true&id=%2Fpersonal%2Fmchargs%5Fmms%5Fgov%2FDocuments%2Fonrr%2Egov%2FContent%20Audit

**Comment by Maroyafaied** [comment]
I have created several issues based on the content audit.
