### ISSUE TITLE
Upload corrected docs from Carrie

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/onrr.gov-site#970]
@cthomasONRR I'm opening this issue for next sprint, I'd like to use it to train the cross trainers. Thanks

Carrie has corrected the documents left from Chris Mentasti's list and has shared them in this folder. https://doimspp-my.sharepoint.com/personal/andersca_mms_gov/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fandersca%5Fmms%5Fgov%2FDocuments%2F508%20Compliance%20Accessible&ct=1630584089668&or=OWA%2DNT&cid=0e720da0%2D858e%2Dc9c9%2D1614%2D239f45a7956d&originalPath=aHR0cHM6Ly9kb2ltc3BwLW15LnNoYXJlcG9pbnQuY29tLzpmOi9nL3BlcnNvbmFsL2FuZGVyc2NhX21tc19nb3YvRWlNYnlVbC1iZTVGakVuTlpZbnltOThCOTBqWjRER0NDdXVMQXNLRUQxT2xLZz9ydGltZT0yYnR4WmdsdTJVZw

- [ ] Recheck docs for accessibility
- [ ] Upload docs in dev site
- [ ] Review docs in dev site
- [ ] Publish to the live site
- [ ] Update Accessibility tracking sheet 
- [ ] Move file within One Drive from '508 Compliance Accessible' to 'Completed'

**Comment by cthomasONRR** [comment]
- [ ] [11-13-DOI-SummaryDisbursementsData.pdf](https://github.com/ONRR/onrr.gov-site/files/7099437/11-13-DOI-SummaryDisbursementsData.pdf)
- [ ] [12-14-FY-2014-SummaryDisbursements.pdf](https://github.com/ONRR/onrr.gov-site/files/7099469/12-14-FY-2014-SummaryDisbursements.pdf)
- [ ] [20130812.pdf](https://github.com/ONRR/onrr.gov-site/files/7099470/20130812.pdf)
- [ ] [20131119a.pdf](https://github.com/ONRR/onrr.gov-site/files/7099473/20131119a.pdf)
- [ ] [20140108.pdf](https://github.com/ONRR/onrr.gov-site/files/7099478/20140108.pdf)
- [ ] [20140122.pdf](https://github.com/ONRR/onrr.gov-site/files/7099479/20140122.pdf)
- [ ] [20140226.pdf](https://github.com/ONRR/onrr.gov-site/files/7099480/20140226.pdf)
- [ ] [20140318EITI.pdf](https://github.com/ONRR/onrr.gov-site/files/7099481/20140318EITI.pdf)
- [ ] [20140327.pdf](https://github.com/ONRR/onrr.gov-site/files/7099483/20140327.pdf)
- [ ] [20140328.pdf](https://github.com/ONRR/onrr.gov-site/files/7099485/20140328.pdf)
- [ ] [20140331.pdf](https://github.com/ONRR/onrr.gov-site/files/7099489/20140331.pdf)
- [ ] [20140403.pdf](https://github.com/ONRR/onrr.gov-site/files/7099491/20140403.pdf)
- [ ] [20140408.pdf](https://github.com/ONRR/onrr.gov-site/files/7099492/20140408.pdf)
- [ ] [20140523.pdf](https://github.com/ONRR/onrr.gov-site/files/7099493/20140523.pdf)
- [ ] [20140612.pdf](https://github.com/ONRR/onrr.gov-site/files/7099495/20140612.pdf)
- [ ] [20140618.pdf](https://github.com/ONRR/onrr.gov-site/files/7099496/20140618.pdf)
- [ ] [20140904.pdf](https://github.com/ONRR/onrr.gov-site/files/7099499/20140904.pdf)
- [ ] [20140908.pdf](https://github.com/ONRR/onrr.gov-site/files/7099500/20140908.pdf)
- [ ] [20140918.pdf](https://github.com/ONRR/onrr.gov-site/files/7099502/20140918.pdf)
- [ ] [20141106.pdf](https://github.com/ONRR/onrr.gov-site/files/7099505/20141106.pdf)
- [ ] [20141202.pdf](https://github.com/ONRR/onrr.gov-site/files/7099506/20141202.pdf)
- [ ] [20141202b.pdf](https://github.com/ONRR/onrr.gov-site/files/7099507/20141202b.pdf)
- [ ] [20141209.pdf](https://github.com/ONRR/onrr.gov-site/files/7099508/20141209.pdf)
- [ ] [20141211.pdf](https://github.com/ONRR/onrr.gov-site/files/7099510/20141211.pdf)
- [ ] [20141219.pdf](https://github.com/ONRR/onrr.gov-site/files/7099511/20141219.pdf)
- [ ] [20150205.pdf](https://github.com/ONRR/onrr.gov-site/files/7099512/20150205.pdf)
- [ ] [20150211.pdf](https://github.com/ONRR/onrr.gov-site/files/7099514/20150211.pdf)
- [ ] [20150218.pdf](https://github.com/ONRR/onrr.gov-site/files/7099515/20150218.pdf)
- [ ] [20150325.pdf](https://github.com/ONRR/onrr.gov-site/files/7099517/20150325.pdf)
- [ ] [20150401.pdf](https://github.com/ONRR/onrr.gov-site/files/7099518/20150401.pdf)
- [ ] [20150410.pdf](https://github.com/ONRR/onrr.gov-site/files/7099519/20150410.pdf)
- [ ] [20150430.pdf](https://github.com/ONRR/onrr.gov-site/files/7099520/20150430.pdf)
- [ ] [20150504.pdf](https://github.com/ONRR/onrr.gov-site/files/7099521/20150504.pdf)
- [ ] [20150513.pdf](https://github.com/ONRR/onrr.gov-site/files/7099523/20150513.pdf)
- [ ] [20150618.pdf](https://github.com/ONRR/onrr.gov-site/files/7099524/20150618.pdf)
- [ ] [20150706.pdf](https://github.com/ONRR/onrr.gov-site/files/7099525/20150706.pdf)
- [ ] [20150812.pdf](https://github.com/ONRR/onrr.gov-site/files/7099526/20150812.pdf)
- [ ] [20150915.pdf](https://github.com/ONRR/onrr.gov-site/files/7099528/20150915.pdf)
- [ ] [20150921.pdf](https://github.com/ONRR/onrr.gov-site/files/7099531/20150921.pdf)
- [ ] [20150925.pdf](https://github.com/ONRR/onrr.gov-site/files/7099532/20150925.pdf)
- [ ] [20151019.pdf](https://github.com/ONRR/onrr.gov-site/files/7099533/20151019.pdf)
- [ ] [20151123.pdf](https://github.com/ONRR/onrr.gov-site/files/7099536/20151123.pdf)
- [ ] [20151125.pdf](https://github.com/ONRR/onrr.gov-site/files/7099537/20151125.pdf)
- [ ] [20151125a.pdf](https://github.com/ONRR/onrr.gov-site/files/7099538/20151125a.pdf)
- [ ] [20151229.pdf](https://github.com/ONRR/onrr.gov-site/files/7099539/20151229.pdf)
- [ ] [20160225.pdf](https://github.com/ONRR/onrr.gov-site/files/7099541/20160225.pdf)
- [ ] [20160505A.pdf](https://github.com/ONRR/onrr.gov-site/files/7099543/20160505A.pdf)
- [ ] [20160505B.pdf](https://github.com/ONRR/onrr.gov-site/files/7099544/20160505B.pdf)
- [ ] [20160629.pdf](https://github.com/ONRR/onrr.gov-site/files/7099545/20160629.pdf)
- [ ] [20171130-CO.pdf](https://github.com/ONRR/onrr.gov-site/files/7099546/20171130-CO.pdf)
- [ ] [20171130-LA.pdf](https://github.com/ONRR/onrr.gov-site/files/7099547/20171130-LA.pdf)
- [ ] [20171130-MT.pdf](https://github.com/ONRR/onrr.gov-site/files/7099548/20171130-MT.pdf)
- [ ] [20171130-ND.pdf](https://github.com/ONRR/onrr.gov-site/files/7099549/20171130-ND.pdf)
- [ ] [20171130-NM.pdf](https://github.com/ONRR/onrr.gov-site/files/7099550/20171130-NM.pdf)
- [ ] [20171130-UT.pdf](https://github.com/ONRR/onrr.gov-site/files/7099551/20171130-UT.pdf)
- [ ] [20171130-WYO.pdf](https://github.com/ONRR/onrr.gov-site/files/7099552/20171130-WYO.pdf)
- [ ] [20160630.pdf](https://github.com/ONRR/onrr.gov-site/files/7099553/20160630.pdf)
- [ ] [20160706.pdf](https://github.com/ONRR/onrr.gov-site/files/7099554/20160706.pdf)
- [ ] [20160729.pdf](https://github.com/ONRR/onrr.gov-site/files/7099555/20160729.pdf)
- [ ] [20161007.pdf](https://github.com/ONRR/onrr.gov-site/files/7099556/20161007.pdf)
- [ ] [20161118.pdf](https://github.com/ONRR/onrr.gov-site/files/7099557/20161118.pdf)
- [ ] [20161125a.pdf](https://github.com/ONRR/onrr.gov-site/files/7099558/20161125a.pdf)
- [ ] [20161125b.pdf](https://github.com/ONRR/onrr.gov-site/files/7099559/20161125b.pdf)
- [ ] [20171130.pdf](https://github.com/ONRR/onrr.gov-site/files/7099560/20171130.pdf)
- [ ] [GOMESA-Texas-2019.pdf](https://github.com/ONRR/onrr.gov-site/files/7099561/GOMESA-Texas-2019.pdf)
- [ ] [Press_Release2020_Proposed_Valuation_Reform_and_Civil_Penalty_Rule.pdf](https://github.com/ONRR/onrr.gov-site/files/7099562/Press_Release2020_Proposed_Valuation_Reform_and_Civil_Penalty_Rule.pdf)
- [ ] [Summary2015Disbursements.pdf](https://github.com/ONRR/onrr.gov-site/files/7099563/Summary2015Disbursements.pdf)
- [ ] [USEITI Advisory_04-26-16.pdf](https://github.com/ONRR/onrr.gov-site/files/7099564/USEITI.Advisory_04-26-16.pdf)
- [ ] [DOI-Energy-Production-NR-02-11-2020-final.pdf](https://github.com/ONRR/onrr.gov-site/files/7099565/DOI-Energy-Production-NR-02-11-2020-final.pdf)
- [ ] [GOMESA-Alabama-2019.pdf](https://github.com/ONRR/onrr.gov-site/files/7099566/GOMESA-Alabama-2019.pdf)
- [ ] [GOMESA-Louisiana-2019.pdf](https://github.com/ONRR/onrr.gov-site/files/7099567/GOMESA-Louisiana-2019.pdf)
- [ ] [GOMESA-Mississippi-2019.pdf](https://github.com/ONRR/onrr.gov-site/files/7099568/GOMESA-Mississippi-2019.pdf)
- [ ] [GOMESA-National-2019.pdf](https://github.com/ONRR/onrr.gov-site/files/7099569/GOMESA-National-2019.pdf)

**Comment by cvojslavek** [comment]
Spot checked the following documents on the live site:

- 20151125a.pdf
- 20151229.pdf
- 20171130-CO.pdf
- 20160630.pdf

**Comment by codyeckstein** [comment]
![image.png](https://images.zenhubusercontent.com/612e68b98872341fdb32e3ff/28c3e057-0bff-43eb-9560-34a6dcec46ca)

This two files 20150506 and GOMESA-Press  are not on the issue checklist but I will update.

**Comment by cthomasONRR** [comment]
@codyeckstein Thanks! Yes, I think Carrie added those in after I had created the checklist. I will add them to the checklist now...

**Comment by codyeckstein** [comment]
![image.png](https://images.zenhubusercontent.com/612e68b98872341fdb32e3ff/369efba1-f204-4856-a06e-f18d84adabe1)

These are not in the 508 folder

**Comment by cthomasONRR** [comment]
@codyeckstein Thanks. I'm checking with Shannon to see if those were sent to Carrie and she hasn't gotten to them, or if we need to send these links over to her.

**Comment by codyeckstein** [comment]
spot checked these on the live site:

![image.png](https://images.zenhubusercontent.com/612e68b98872341fdb32e3ff/5f1f4439-81d0-4b9f-bf2f-f9a6e78f687a)

**Comment by cthomasONRR** [comment]
@codyeckstein @cvojslavek Thank you both for all your help!!! I am going to email Carrie about those 6 remaining documents, I don't think they were sent to her to remediate.

**Comment by cthomasONRR** [comment]
@mcharg @Maroyafaied As far as I can tell, all the Chief of Staff documents are now 508-Compliant!!! Thanks to @codyeckstein and @cvojslavek for all their work!!!! Here's an update on the status pivot:
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/8ee87f96-e7c7-43d0-bd80-5a5faa4d75e8)

**Comment by Maroyafaied** [comment]
That's great, thank you all for your hard work!

**Comment by cvojslavek** [comment]
@cthomasONRR Thank you for teaching us how to help upload 508 documents!

**Comment by cthomasONRR** [comment]
I believe we are done with this issue. Closing now :)
