### ISSUE TITLE
Update August NYMEX prices on onrr.gov

### ISSUE THREAD

**Issue by boices** [ONRR/onrr.gov-site#971]
Hello,

Please update onrr.gov with the August NYMEX prices as attached. @sudarr

Thanks!
[NYMEX082021.xlsx](https://github.com/ONRR/onrr.gov-site/files/7100832/NYMEX082021.xlsx)

**Comment by cthomasONRR** [comment]
@boices The August NYMEX prices are on the dev site (http://2017onrr/valuation/NYMEX.htm). Please review and give us your approval to go live. 

Thanks!
Christine

**Comment by boices** [comment]
That's perfect--thanks again!

**Comment by cthomasONRR** [comment]
@boices Awesome! I just made these changes live. 

It can take up to 30min for the live site to update, please use “Ctrl+F5” to refresh. (https://www.onrr.gov/valuation/NYMEX.htm)

I will close this issue once I see the changes live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
August prices are live! Closing this issue.
