### ISSUE TITLE
ONRR.gov Indian Index Zone prices - September 2021

### ISSUE THREAD

**Issue by forgravec** [ONRR/onrr.gov-site#972]
The September Indian Index Zone prices are ready to be updated.
The prices were placed into the "Data for ONRR.gov" spreadsheet in the OneDrive

Please copy Robert Sudar on the email chain for when the webpage with the new prices are ready for review and when it goes live. I will be gone the next couple business days, and he will need to verify the prices.

Thanks,
Cory Forgrave

@sudarr

**Comment by lpgoldstein** [comment]
@sudarr This is ready for your review http://2017onrr/valuation/allzones.htm

**Comment by sudarr** [comment]
@lpgoldstein  This looks great to me, please post it. Thanks

**Comment by lpgoldstein** [comment]
@sudarr These are live https://onrr.gov/valuation/allzones.htm
