### ISSUE TITLE
Review Ryan's evaluation and create issues

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/onrr.gov-site#98]

**Comment by lpgoldstein** [comment]
I created some notes on Ryan's notes. It seems like there are a few things we should be able to tackle quickly that will streamline the site and improve load time too. @jennmalcolm let's discuss on Monday https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B8475B48F-24A5-4527-9C16-0A0E879CAE9C%7D&file=Notes%20on%20Ryan%27s%20notes.docx&action=default&mobileredirect=true
