### ISSUE TITLE
Royalty Reporting and Error Correction Contact List Update

### ISSUE THREAD

**Issue by bowlenj** [ONRR/onrr.gov-site#991]
Please replace the Royalty Reporting and Error Correction contact list at the following location - https://www.onrr.gov/reportpay/PDFDocs/royassign.pdf, with the attached updated version.
[royassign.pdf](https://github.com/ONRR/onrr.gov-site/files/7108065/royassign.pdf)

**Comment by cthomasONRR** [comment]
@bowlenj

This updated document is on the dev site (http://2017onrr/reportpay/royalty-reporting.htm).
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by Maroyafaied** [comment]
@mcharg can you show @cthomasONRR the contact excel sheet we're using for the CMS to see if contacts need to be updated with this issue. Thanks

**Comment by cthomasONRR** [comment]
@bowlenj

Hi Jessica,

Just checking in to see if you've been able to review:

This updated document is on the dev site (http://2017onrr/reportpay/royalty-reporting.htm).
Please review and give us your approval to go live.

Thanks,
Christine

**Comment by mcharg** [comment]
@Maroyafaied Will do.

**Comment by bowlenj** [comment]
Hello,

Thank you, this looks great!

Thank You,
Jessica Bowlen
Office of Natural Resource Revenue
Distribution and Disbursement Support Services
Team 1B
303-231-3202
***@***.***


Warning:  This message is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged or confidential and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient or the employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by return e-mail.




________________________________
From: Christine Thomas ***@***.***>
Sent: Tuesday, September 7, 2021 6:56 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Bowlen, Jessica G ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] Royalty Reporting and Error Correction Contact List Update (#991)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@bowlenj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbowlenj&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Ce495305c67604262968a08d971feede5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637666161995194497%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BgiYs80miBysvcqV2fegRG0SLZcskyhaLUvMDUhZKdo%3D&reserved=0>

Hi Jessica,

Just checking in to see if you've been able to review:

This updated document is on the dev site (http://2017onrr/reportpay/royalty-reporting.htm).
Please review and give us your approval to go live.

Thanks,
Christine

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F991%23issuecomment-914283320&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Ce495305c67604262968a08d971feede5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637666161995194497%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wsWxz0kpNM1wJkYJ3iz6PlggFJYeCMkD40CNPIfLoII%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ56VH2X76I6EOFO72DBRLDUAYDXRANCNFSM5DMKNGLA&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Ce495305c67604262968a08d971feede5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637666161995204449%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2PBjkptrGKyY8taU6ECfLOnMD3ynneBv4sQl13BiHUc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Ce495305c67604262968a08d971feede5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637666161995214403%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RnXZ58VB0g0Kn5dRuud4HC9bJQKZSobBrg8ixw1Ldbg%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjessica.bowlen%40onrr.gov%7Ce495305c67604262968a08d971feede5%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637666161995214403%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rjQRRoT9R5C8gdwT5X9bAb4fg%2BRZO687bFg1TnYr3TA%3D&reserved=0>.

**Comment by cthomasONRR** [comment]
@bowlenj Thanks! I just moved the document to the live site (https://www.onrr.gov/reportpay/PDFDocs/royassign.pdf). Please allow about 30 minutes for the changes to appear on the live site. Please use "Ctrl+F5" to refresh the page.

@Maroyafaied and @mcharg - I updated the spreadsheet as well.

I will close this issue once I see the changes live.

Thanks,
Christine

**Comment by cthomasONRR** [comment]
New PDF is live! Closing this issue.
