### ISSUE TITLE
August 2021 IBMP Pirces

### ISSUE THREAD

**Issue by damionschulte** [ONRR/onrr.gov-site#998]
All I have updated the onrr.gov spreadsheet on the OneDrive with the August 2021 IBMP prices.  Can you please have them published to the web?  Thanks 

@sudarr

Damion Schulte

**Comment by lpgoldstein** [comment]
@codyeckstein Let's work on this together this morning. I'm available anytime.

**Comment by lpgoldstein** [comment]
@damionschulte Please check dev site http://2017onrr/valuation/IndianOilIBMP.htm

**Comment by damionschulte** [comment]
These look amazing. Once again you guys have delivered.  Thank you.

From: lpgoldstein ***@***.***>
Sent: Wednesday, September 8, 2021 10:20 AM
To: ONRR/onrr.gov-site ***@***.***>
Cc: Schulte, Damion C ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ONRR/onrr.gov-site] August 2021 IBMP Pirces (#998)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@damionschulte<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdamionschulte&data=04%7C01%7Cdamion.schulte%40onrr.gov%7C1d4c8f3cc109416a165e08d972e48126%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637667148016585883%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xQJwiNbwwm2ElLUJgX%2F5O%2F%2Bl64rYMrgktA9N0guJjuY%3D&reserved=0> Please check dev site http://2017onrr/valuation/IndianOilIBMP.htm

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FONRR%2Fonrr.gov-site%2Fissues%2F998%23issuecomment-915381168&data=04%7C01%7Cdamion.schulte%40onrr.gov%7C1d4c8f3cc109416a165e08d972e48126%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637667148016585883%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IhDZs53%2FsvhVedv4U2Y10FyupMCGfCPHXqlkZHC%2FUPQ%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAO4AEPMXSLZH62WJ3PJ4R63UA6EKDANCNFSM5DTE5OZQ&data=04%7C01%7Cdamion.schulte%40onrr.gov%7C1d4c8f3cc109416a165e08d972e48126%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637667148016595851%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MXBDeaP7cHqR6kdGrHrWlDgkVL3xxVRbsnP5Sd55nNc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdamion.schulte%40onrr.gov%7C1d4c8f3cc109416a165e08d972e48126%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637667148016595851%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3TXXIDUN0mLrgjnvenuV5mkG1%2B9%2F6ewK4BAfntHyTsI%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdamion.schulte%40onrr.gov%7C1d4c8f3cc109416a165e08d972e48126%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637667148016605795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=i5RSVXjLp0%2FINCH%2FWJ%2FYHOi4JoBaGs2km2%2FBq4vZCuk%3D&reserved=0>.

**Comment by lpgoldstein** [comment]
@damionschulte This is live! https://onrr.gov/valuation/IndianOilIBMP.htm
