### ISSUE TITLE
Figure out what to put on how to price Indian page

### ISSUE THREAD

**Issue by mcharg** [ONRR/onrr.gov-site#999]
I reached out to the Indian team because they had wanted to put something like "go see the handbook" in place of what I have in the wireframe. Now they're saying to use the language on the existing site, which doesn't exist.  It would be good for someone to work with them on a middle ground.

https://qmcq5k.axshare.com/#id=y89dq7&p=indian_pricing

**Comment by mcharg** [comment]
I sent Noelle notes from when we had meetings and she's rethinking.

**Comment by cthomasONRR** [comment]
- Let's make sure that the images are hyperlinks that will bring up the detailed PDF of the maps

- At the end of the oil and gas tabs, let's add links to the handbook for further reading

- If we don't hear back from Noelle, let's contact Cindy Gothberg  and Megan Hessee for their help

- If Noelle wants this 'how to price' tab removed, we will push back with the recent positive feedback from the onrr.gov interviews

**Comment by mcharg** [comment]
Noelle sent me new copy, so I'll get it updated in the prototype tomorrow, so we can get user feedback next week.

**Comment by mcharg** [comment]
Page updated and sent out for review.
https://qmcq5k.axshare.com/#id=y89dq7&p=indian_pricing

@daniel-coleman-1 There are some new links that should be updated in the sitemap.
